### PR TITLE
Python swiftclient recipe

### PR DESCRIPTION
**Pull request by jtratner**
Step 1 towards getting a stor conda package built :)

cc @kyleabeauchamp

### CODE REVIEW

**Comment by jtratner** [comment]
(I think this can't be noarch because of futures requirement)

**Comment by kyleabeauchamp** [comment]
LGTM.

**Comment by jtratner** [comment]
Hi @conda-forge/staged-recipes - would someone have time to take a look at this recipe? (and is there anything else I need to do for it?) 

Thanks! :)

**Comment by kyleabeauchamp** [comment]
@jakirkham it seems like @jtratner  cannot ping @conda-forge/staged-recipes to request review, can you ping the correct group for us?  Thanks!

**Comment by kyleabeauchamp** [comment]
Same story for a couple other PRs, actually:

https://github.com/conda-forge/staged-recipes/pull/5349

https://github.com/conda-forge/staged-recipes/pull/5350

**Comment by jakirkham** [comment]
cc @CJ-Wright

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes

**Comment by jakirkham** [comment]
@conda-forge-admin, please lint.

**Comment by jakirkham** [comment]
It appears now [this feedstock has `python-swiftclient`]( https://github.com/conda-forge/python-swiftclient-feedstock ). So closing this out. Please consider becoming maintainers of it if you are interested. Thanks again for your work 🙂

**Pull request closed without merging**
