### PR TITLE
Add r-survivalroc.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by bgruening** [comment]
@jakirkham @isuruf way are we building against `defaults` here and not just the pined R versions from conda-forge?

**Comment by jdblischak** [comment]
I restarted the Travis and Appveyor builds now that conda-smithy 2.4.3 has been released.

@ocefpaf Could you please restart the CircleCI build?

**Comment by bgruening** [comment]
@cbrueffer please add a few more maintainers if you like: https://github.com/bgruening/conda_r_skeleton_helper/blob/master/extra.yaml

**Comment by jdblischak** [comment]
Restarted AppVeyor. @bgruening could you please restart CircleCI?

**Comment by bgruening** [comment]
Done!

**Pull request merged**
