### PR TITLE
Add scikit-hep

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @chrisburr, thanks for getting ahead on this. But please wait for release 1.0.0 to add `scikit-hep` to conda. Keep me in the loop for this package ... Thanks.

**Comment by chrisburr** [comment]
@eduardo-rodrigues, don't worry I will and regardless Conda-forge doesn't allow unreleased versions to be deployed. I just did this to see if anything needed to be done in preparation.

**Comment by chrisburr** [comment]
@eduardo-rodrigues Shall I add you to the maintainers section (which gives you merge rights on the "feedstock" repository that is used for updates).

**Comment by eduardo-rodrigues** [comment]
> @eduardo-rodrigues, don't worry I will and regardless Conda-forge doesn't allow unreleased versions to be deployed. I just did this to see if anything needed to be done in preparation.

OK, fair enough. Good idea.

**Comment by eduardo-rodrigues** [comment]
> @eduardo-rodrigues Shall I add you to the maintainers section? (which gives you merge rights on the "feedstock" repository that is used for updates)

Thanks. That's probably a good idea - I believe you've been doing the same thing for Henry/... where they are the main Scikit-HEP package maintainer.

**Pull request closed without merging**
