### PR TITLE
add auto3d

### PR DESCRIPTION
**Pull request by hadim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hadim** [comment]
Blocked by https://github.com/isayevlab/Auto3D_pkg/issues/26

**Comment by hadim** [comment]
@LiuCMU if you want to be added as a maintainer, please confirm it here in that ticket. I can remove you if you are not interested.

**Comment by LiuCMU** [comment]
@hadim yeah, I'd love to,  I'm pretty new to conda-forge though. Not sure what I can do here

**Comment by hadim** [comment]
> @hadim yeah, I'd love to, I'm pretty new to conda-forge though. Not sure what I can do here

No problem. It's mostly about making sure new versions are correctly packaged with the correct deps. It's nothing more than reviewing a PR for each release.

**Comment by hadim** [comment]
@conda-forge/help-python ready for review (windows failing is expected)

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Ignoring noarch Windows build failure due to missing dependency.

**Comment by hadim** [comment]
Thanks @dopplershift !

**Comment by LiuCMU** [comment]
Thank you! @hadim It's wonderful to make auto3d also available in conda

Just a question, if I update auto3d for PyPI in the future, how could the conda-forge distribution also be updated?

**Comment by dopplershift** [comment]
@LiuCMU conda-forge has a bot that will see the updated version on PyPI and issue a PR against the [feedstock](https://github.com/conda-forge/auto3d-feedstock) for this recipe to update to the latest version. As a maintainer for this recipe, you'll have access to merge that PR (and update it to adjust e.g. dependencies). You can also make a manual PR against the feedstock yourself to update the version if you want, but the bot usually catches it within an hour or two.

**Comment by LiuCMU** [comment]
Got it, that's awesome!  Thank you very much!

**Pull request merged**
