### PR TITLE
Pandas data package reader

### PR DESCRIPTION
**Pull request by znicholls**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by znicholls** [comment]
@rgieseke are you happy to help maintain this?

**Comment by rgieseke** [comment]
> @rgieseke are you happy to help maintain this?

What does that entail? :-)

I've pushed a new release including "sdist"

**Comment by znicholls** [comment]
Keeping an eye on the conda package and doing updates as needed (I’ll help).

Awesome thanks will update

**Comment by rgieseke** [comment]
Cool, happy to help with that!

**Comment by rgieseke** [comment]
Pushed 0.13.1: https://pypi.org/project/pandas-datapackage-reader/0.13.1/

**Comment by rgieseke** [comment]
SHA256 according to PyPI:

bdb9e853a080e1c2df718b9ae603e84908bcff6abf92ce8e3643db0f482c744c

https://pypi.org/project/pandas-datapackage-reader/0.13.1/#copy-hash-modal-a42b0d6c-002f-4739-a423-06a968c31c93

**Comment by znicholls** [comment]
> SHA256 according to PyPI:

This is why you don't try to do things on your phone...

**Comment by znicholls** [comment]
@conda-forge/help-python can we please request a review?

**Pull request merged**
