### PR TITLE
Add pogo recipe

### PR DESCRIPTION
**Pull request by beenje**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by beenje** [comment]
@dlacoste-esrf could you please confirm you want to be a maintainer?

**Comment by beenje** [comment]
I copied the preferences from <https://gitlab.com/tango-controls/TangoSourceDistribution/-/blob/main/assets/pogo/preferences>

- I don't see any `org.tango.pogo.copyright` in [Pogo.site_properties.in](https://gitlab.com/tango-controls/TangoSourceDistribution/-/blob/main/assets/pogo/preferences/Pogo.site_properties.in)
- By generating the `pogo` script in `build.sh` we can use the `$PREFIX` variable (that will be expanded) and let conda replace that variable at install time. If we don't generate the script, we have to rely on `$CONDA_PREFIX` variable which is exported when you activate an environment. I usually prefer the first solution as you don't have to rely on variables set at activation time. I'd do that as well on windows but my windows skills are very limited.
- For `org.tango.pogo.makefile_home`, I should be able to use sed to replace the line at build time.

**Comment by dlacoste-esrf** [comment]
ok.
Thanks for the explanation! It's fine by me, and my love for symmetry won't make me improve my windows skills to help you on this, so perfect as it is!
the copyright field exists, but if it's not on TangoSourceDistribution, don't bother.

**Comment by beenje** [comment]
@conda-forge/staged-recipes, ready for review!

**Review by xhochy — APPROVED** [review]

**Comment by beenje** [comment]
Thanks @xhochy !

**Pull request merged**
