### PR TITLE
Add TRMM RSL recipe

### PR DESCRIPTION
**Pull request by jjhelmus**
Add a recipe for [NASA's TRMM RSL library](http://trmm-fc.gsfc.nasa.gov/trmm_gv/software/rsl/) which does not build on Windows.  Using the `trmm_rsl` name for this package as `rsl` is a [valid package on pypi](https://pypi.python.org/pypi/rsl).

### CODE REVIEW

**Comment by jjhelmus** [comment]
Travis seems to be failing because it tries to create the feedstock, not sure why it does this on a non-merge.

**Comment by pelson** [comment]
> Travis seems to be failing because it tries to create the feedstock

The lines and responsibilities are a bit blurry at the moment, but essentially the error is as follows:


```
/Users/travis/build/conda-forge/staged-recipes/ready_recipes/trmm_rsl has some lint:

  The recipe must have some tests.
```

In order to know that what we are building continues to work as expected, it would be handy to have some tests in the recipe.

**Comment by jjhelmus** [comment]
Yes, my bad on not reading that error message fully.  I do not think the libraries comes with any tests but I can create something that at least checks that the scripts are available.

**Comment by pelson** [comment]
> I can create something that at least checks that the scripts are available.

That is all we want here. The project is responsible for testing the *functionality* is as expected, but the recipe is responsible for testing that it is *functioning* as expected.

**Comment by jjhelmus** [comment]
Had to get a bit creative on the tests because the installed commands return 255 when the help messages are printed out.

**Pull request merged**
