### PR TITLE
Add iminuit to conda-forge

### PR DESCRIPTION
**Pull request by mwcraig**
@cdeil -- are you willing to be a maintainer on this one too?

I'm also wondering if I got the runtime dependencies right (numpy, matplotlib)...I know matplotlib is technically optional but installation with conda is easy enough it seems like it makes sense to include it.

### CODE REVIEW

**Comment by cdeil** [comment]
@mwcraig - OK to add me as maintainer on this one.

> I'm also wondering if I got the runtime dependencies right (numpy, matplotlib)...I know matplotlib is technically optional but installation with conda is easy enough it seems like it makes sense to include it.

As mentioned at http://iminuit.readthedocs.io/en/latest/installation.html#dependencies , everything except `setuptools` is an optional dependency. Many people use `iminuit` with `ipython`, `numpy`, `matplotlib`or `cython`, but there's also people that just use `iminuit` with Python functions.

My suggestion would be to remove **all** of the optional dependencies from the package spec, instead of adding them all or some of them. Users can just separately install `numpy`, `matplotlib`, `ipython` or `cython` if they want to use it.

I think that the sdist from PyPI has the Cython-generated C code, so that Cython is not a build or runtime dependency, it's only used if someone wants to write their functions that `iminuit` will optimize in Cython.

**Comment by mwcraig** [comment]
Thanks @cdeil, I've updated the dependencies.

**Comment by cdeil** [comment]
Green light from all the CI services. Merge?

_For reference: This is a C++ / Cython heavy package, so if anyone encounters any issues with the conda-forge package, please report them over at https://github.com/iminuit/iminuit/issues and we'll try to fix the package or build._

**Comment by mwcraig** [comment]
@cdeil -- I'll give this one more day for comments then merge late Monday if there are not any.

**Pull request merged**
