### PR TITLE
Add recipe for cfgv

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge/staged-recipes @ocefpaf this is a `noarch: python` package and CircleCI has already passed so I believe this can be merged. 👍

**Comment by scopatz** [comment]
Please include the license in the feedstock manually https://conda-forge.org/docs/meta.html#packaging-the-license-manually

**Comment by ocefpaf** [comment]
@scopatz it will be in the next version of the package. See https://github.com/asottile/cfgv/pull/3

**Comment by scopatz** [comment]
Yeah, I saw that, but it still means the license is missing for this version :(

**Comment by ocefpaf** [comment]
A long time ago we agreed that, when a package does not ship a license, we would not enforce it. Are we changing that policy? If so we have tons of packages to fix! I do understand the legal argument but the majority  of package on PyPI are broken when it comes to shipping license, it would be an herculean job to fix that.

**Comment by scopatz** [comment]
Oh I didn't know about that policy : smile: would be nice if that made it into the docs, if it is not already!

**Comment by ocefpaf** [comment]
> Oh I didn't know about that policy : smile: would be nice if that made it into the docs, if it is not already!

We never wrote that b/c it is not a nice policy. (And we agreed on that before we had docs!)

Anyway, I still think that opening issues upstream is the best way to go. Copying licenses can be error prone as not all licenses are the same boilerplate text. (And sometimes they are missing even from the repo.)

**Comment by scopatz** [comment]
I agree!

**Comment by CJ-Wright** [comment]
We could create a list of licence-less packages, at least then we would have something to go off of.
I'd be interested to see how many of the license-less packages have source on GitHub. If there are a bunch we could try to scrape the license off GitHub and PR it into the various feedstocks.

**Comment by CJ-Wright** [comment]
The first part wouldn't be that bad, we already crawl though all the `meta.yaml`s, although we don't currently track the license info. We should just capture the entire `meta.yaml` in the graph nodes.
The second part is a bit more difficult, but most of the machinery is there.

**Pull request merged**
