### PR TITLE
Haskell stack

### PR DESCRIPTION
**Pull request by eggzilla**
This adds a recipe for the stack tool. Stack is a cross-platform program for developing Haskell projects.

### CODE REVIEW

**Comment by bgruening** [comment]
Nice! Thanks @eggzilla!

**Comment by ocefpaf** [comment]
@eggzilla re-packaging is fair game and we have a few like those in `conda-forge`. However, it is always preferred to try to build things from scratch. Can you just write a few quick lines on why you chose to re-package and how difficult would it be to build from source before we merge this?

**Comment by eggzilla** [comment]
@ocefpaf Sure :-) I actually also prefer building from source. In this case a haskell compiler, e.g. ghc, would be required that compiles stack. I can try to add a recipe for this in the future, but in my experience with ghc this is not so easy. Moreover there is the pandoc recipe in conda-forge that could be built with stack and maybe also others. So this would be a first step closer to building from scratch :-)

**Comment by ocefpaf** [comment]
> Moreover there is the pandoc recipe in conda-forge that could be built with stack and maybe also others.

I like the sound of that :smile:

**Comment by bgruening** [comment]
:tada:

**Pull request merged**
