### PR TITLE
python-stratify

### PR DESCRIPTION
**Pull request by bjlittle**

### CODE REVIEW

**Comment by ocefpaf** [comment]
The Windows error:

```shell
stratify\_vinterp.c(2756) : warning C4013: 'isnan' undefined; assuming extern returning int
stratify\_vinterp.c(2862) : error C2065: 'NAN' : undeclared identifier
stratify\_vinterp.c(2929) : error C2065: 'INFINITY' : undeclared identifier
stratify\_vinterp.c(2949) : error C2065: 'INFINITY' : undeclared identifier
stratify\_vinterp.c(4824) : error C2065: 'NAN' : undeclared identifier
stratify\_vinterp.c(29872) : warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
stratify\_vinterp.c(29878) : warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

sounds familiar. @gillins is this something easy to fix?

**Comment by ocefpaf** [comment]
> Any help/guidance would be just awesome!

I have a faint memory that I saw this before but I cannot remember where. I will research the other feedstocks later to see if I can find it. (Skipping Window is OK for now.)

**Comment by ocefpaf** [comment]
@bjlittle I am merging this so I can work on the Windows issue in the feedstock.

**Comment by ocefpaf** [comment]
@bjlittle see https://github.com/SciTools-incubator/python-stratify/pull/8 for a possible fix.

**Comment by gillins** [comment]
Sorry for delay - use `_isnan` and `_isfinite` on VC 2008 (Python 2.7).

**Comment by ocefpaf** [comment]
> Sorry for delay - use `_isnan` and `_isfinite` on VC 2008 (Python 2.7). 

No problem. Thanks for the feedback! What do you think of the approach I took in  SciTools-incubator/python-stratify#8 ?

```cython
cdef extern from "numpy/npy_math.h" nogil:
    bint isnan "npy_isnan"(long double)
    float NAN "NPY_NAN"
    float INFINITY "NPY_INFINITY"
```

**Comment by gillins** [comment]
:+1: Looks great! Those npy_xxx macros could very handy for portability...

**Pull request merged**
