### PR TITLE
Add rpm-tools

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/staged-recipes ready for review!

**Comment by scopatz** [comment]
Thanks @chrisburr!

**Comment by jakirkham** [comment]
Very cool! Thanks Chris. 😄

Is the idea to use to this to repackage Conda packages in RPMs? Or is there another motivation? 😉

**Comment by chrisburr** [comment]
Thanks @scopatz for merging both this and the other PR!

@jakirkham No, nothing that interesting I'm afraid. 😆 Just need to be able to use `createrepo` to manage an internal software repo for $DAY_JOB. Everything else in this part of the infrastructure is deployed from an `environment.yaml` file so it's cleaner to add the missing bits to conda-forge :)

**Pull request merged**
