### PR TITLE
Added recipe for r-officedown

### PR DESCRIPTION
**Pull request by bsennblad**
Hi @conda-forge/help-r, 
This is a PR adding a recipe for the R-package [officedown](https://davidgohel.github.io/officedown/) using tar-bll from cran.

- Recipe is created using the most recent version of [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper). 
- LICENSE is removed from `license_file`
- comments are removed

Reviews and comments are gratefully accepted.

/B

Checklist
- [ x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ x] Source is from official source
- [ x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ x] If static libraries are linked in, the license of the static library is packaged.
- [ x] Build number is 0
- [ x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there -- Comment! This is assuming that the addition of `conda-forge/r` by default by conda_r_skeleton_helper implies that these are excempt from this requirement -- I myself hereby confirm that I am willing to be listed.

### CODE REVIEW

**Comment by bsennblad** [comment]
@conda-forge/help-r If you have the time, I could need some feedback on this, please:)
So the CI fails for the recipe. If I read it right, all fails are related to the bld.bat being missing, which is a bit strange. There is a bld.bat in the recipe and it is taken directly as generated by the conda_r_skeleton_helper, but the CI does not find it. 
Do you have a suggestion on how to address this? Or should I just remove the bld.bat and skip the windows build (as I believe was recommended for my previous recipe PRs)?
Thanks in advance /B

**Comment by bsennblad** [comment]
BTW @cbrueffer  Thanks for fixing the linting problem!

**Comment by cbrueffer** [comment]
Oh! I didn't pay attention and thought this was an update in an existing feedstock (need more coffee).

The issue is that the files are directly in `recipes`, when they should be in `recipes/r-officedown`; if you move them things should work.

**Comment by bsennblad** [comment]
@cbrueffer OK. Thanks!
So it was all carelessness from my side. A trailing "/" mistake when copying from the conda_r_skeleton_helper folder and then not double-checking the folder before committing:(
Apologies for taking up your time unnecessarily! Update coming soon.
Again huge thanks,
/B

**Comment by cbrueffer** [comment]
This error is pretty common at the moment since we're stopping building for R 3.5; just add `skip: true  # [r_base == "3.5.1"]` (two spaces between true and #).

**Comment by bsennblad** [comment]
@cbrueffer Sorry I missed your comment. After some trials with running the CI locally, I came to the same conclusion, but I solved it by adding a version requirement `> 3.6`. This solved it locally.

Is your solution `skip: true # [r_base == "3.5.1"]` the preferred one by conda-forge? If so, I will revert my change and apply the one you suggest instead. (I just want to see if my solution works with the CIs first:)

Hmm, the requirement should in any case probably rather be >=3.6(?)

Thanks for the help.

**Comment by cbrueffer** [comment]
Using `>=3.6` breaks the windows package build as far as I remember. The `>` gets embedded in the package name, but is an illegal Windows pathname character.

**Comment by bsennblad** [comment]
@cbrueffer As you predicted, the win CI failed. I'll now commit your solution:)
Thanks for explaining

**Comment by bsennblad** [comment]
@cbrueffer 
Thanks a million for the help with this!

The osx CI failure while setting up conda that I saw after my last commit:
```
++ tar -xf MacOSX10.9.sdk.tar.xz -C /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```
Was this just some arbitrary docker setup failure? The osx CI worked locally and now it seems to have passed also the conda-forge CIs. Did you fix something?

**Comment by cbrueffer** [comment]
No problem! Yeah, that was some spurious error, rerunning the CI fixed it.

**Pull request merged**
