### PR TITLE
Add recipe for Helios++

### PR DESCRIPTION
**Pull request by dokempf**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by lwiniwar** [comment]
Hi, I'm happy to be listed as a co-maintainer of this recipe (helios).

**Comment by han16nah** [comment]
Hi, I'm also happy to be listed as a co-maintainer of this recipe (helios).

**Comment by bhoefle-3dgeo** [comment]
I am willing to be listed here as co-maintainer.

**Comment by dokempf** [comment]
@conda-forge/help-python-c This is in general ready for review. 

Two remarks:
* I have investigated the build failure on Windows for quite some time now and I am out of ideas: It reports that I am overlinking `liblapack`, but I do not link against it (anymore). The dependency that requires it is `armadillo`. My current guess would be that something about the CMake build system of `armadillo` is causing this issue. What also puzzles me is how that error would only occur on Windows.
* We are aiming for an alpha pre-release here, hence the `channel_targets:` in the config. The reason for this is the following: For the next major release, we want to switch our user workflow to a Conda-based installation. However, there is a chicken-egg situation with such a shift: We need to be able to properly test it "live" before communicating it to users. Packaging the previous major version for `conda-forge` was not possible, because it involved a rewrite of the entire CMake build system.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
