### PR TITLE
Add pc_rasterize

### PR DESCRIPTION
**Pull request by fbunt**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by fbunt** [comment]
@conda-forge/help-python Any advice?

I don't understand why the `pip check` test failed. Looking at the logs, it says "pc-rasterize 0.2.0 requires python-pdal, which is not installed." but, as far as I can tell, `python-pdal` is installed right before the test.

**Comment by fbunt** [comment]
I reproduced this locally. For whatever reason `pip check` cannot see python-pdal. The pc_rasterize imports and works just fine though so I'm going to remove that test. I'll just have the import test for now.

**Comment by synapticarbors** [comment]
I'm not exactly sure what `pip check` is looking at but perhaps it's somehow confused by the fact that `pypi` has a `pdal` and `python-pdal` and what conda-forge calls `python-pdal` is actually `pdal` on `pypi`. On `pypi`, `python-pdal` looks like some sort of place holder.

**Comment by fbunt** [comment]
Wow. That's a bit of a mess. Thanks for looking at it.

**Pull request merged**
