### PR TITLE
R metapackages.

### PR DESCRIPTION
**Pull request by johanneskoester**
This PR adds the two metapackages for installing R together with r-recommended which are known from the R channel.

### CODE REVIEW

**Comment by johanneskoester** [comment]
@conda-forge/core, can you please merge this? No tests needed here, because these are metapackages.

**Comment by johanneskoester** [comment]
@jakirkham maybe I have broken master with this merge, sorry! See here: https://travis-ci.org/conda-forge/staged-recipes#L323

**Comment by isuruf** [comment]
No, this is a known issue with the new release of conda-smithy. Restarting the build will fix the errors.
https://github.com/conda-forge/conda-smithy/issues/506

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
