### PR TITLE
Add toposort

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/staged-recipes/issues/2840

A Python package for doing topological sorts.

### CODE REVIEW

**Comment by jakirkham** [comment]
CC-ing @johanneskoester @bgruening as maintainers of this package in bioconda.

**Comment by jakirkham** [comment]
Would you like me to add you as maintainers?

**Comment by bgruening** [comment]
If you need help, anytime!

**Comment by johanneskoester** [comment]
Sure, if you like!

**Comment by jakirkham** [comment]
Thanks. Have added both of you.

**Comment by jakirkham** [comment]
Thanks @pkgw.

Feedstock is live. Packages are now available.

**Pull request merged**
