### PR TITLE
Fix the comment that this is a py script, not a sh script.

### PR DESCRIPTION
**Pull request by pelson**
Again, follows up from #185.

### CODE REVIEW

**Comment by jakirkham** [comment]
LGTM

**Comment by jakirkham** [comment]
Do you have a recipe that you want to try?

**Comment by pelson** [comment]
> Do you have a recipe that you want to try?

It always triggered when something is merged to this repo, so I've actually already been able to see that the trigger is behaving as expected.

**Comment by jakirkham** [comment]
Yeah, I noticed Travis was running for the webpage after I wrote that.

**Comment by jakirkham** [comment]
Should it be changed to match a more specific condition though or are you already writing this?

**Comment by jakirkham** [comment]
Namely, I am thinking we hold off on trigger until recipes have been feedstocked and removed.

**Comment by pelson** [comment]
> Namely, I am thinking we hold off on trigger until recipes have been feedstocked and removed.

That is what is happening: The trigger occurs after the feedstocks have been created *and* the commit has been pushed which removes them from ``recipes``.  https://github.com/conda-forge/staged-recipes/pull/185/files#diff-41f1cd77c53034a9c5b20fc35b79ccf6R10

**Comment by jakirkham** [comment]
Ah, sorry, it is clear. ( now whose not reading :wink: )

**Comment by jakirkham** [comment]
Should we add this functionality to the feedstocks, as well? We might need to throttle it somehow if it gets too busy, but I like the idea of keeping things up-to-date as they change.

**Comment by jakirkham** [comment]
lol Sorry to bring it up again.

Just think it is nice to have this automated when adding new maintainers.

Another thought (as you have been playing with Heroku), is to have a bot that manages running this queue. We send it request to run and then based on some criteria YTBD it runs something or not. Guessing bundling temporally close requests makes sense. Not sure if having logic to weed out requests as completed is worth the effort now (maybe in the future).

**Pull request merged**
