### PR TITLE
WIP: Add zeromq

### PR DESCRIPTION
**Pull request by jakirkham**
Requires: https://github.com/conda-forge/staged-recipes/pull/143

Adds a recipe to build zeromq. Based of the recipe from conda recipes. Tweaked so as to fit better in conda-forge.

### CODE REVIEW

**Comment by pelson** [comment]
Looks like a nice recipe. There are certainly some contributors we can add here, and I think it probably just needs a few finishing touches to get the CI passing. :+1:

**Comment by jakirkham** [comment]
Ideally, I want to get this in and yes I think there are people interested. It was just I had some issues with libsodium that need to be resolved first.

**Comment by jakirkham** [comment]
Test failures on Mac and LInux are known failures. See Linux issue ( https://github.com/zeromq/libzmq/issues/1462 ) and Mac issue ( https://github.com/zeromq/libzmq/issues/1509 ). Probably should patch these out from the test suite while we run them.

**Comment by jakirkham** [comment]
CI is passing. Skipping Windows for now. We can try to re-add Windows support in the future. As there are no complaints and this was very backlogged, going to go ahead and merge as is so we can get it out there. Feedback welcome in the feedstock.

**Comment by jakirkham** [comment]
@minrk, would you be interested in being added as a maintainer on the [zeromq feedstock]( https://github.com/conda-forge/zeromq-feedstock )? Also, do you have any thoughts on the recipe as is? Largely the same as it was in conda-recipes (newer version though). However, I had to temporarily disable Windows. If you have any thoughts on getting Windows to work, I would be really curious to hear.

**Comment by minrk** [comment]
(same as libsodium) I'm happy to work on this, but lack expertise for doing it properly on Windows, where I typically bundle zeromq as a Python extension, rather than a proper DLL dependency.

**Comment by jakirkham** [comment]
(also basically the same as libsodium) Thanks @minrk. This PR ( https://github.com/conda-forge/zeromq-feedstock/pull/3 ) will add you as a maintainer to the `zeromq` feedstock. In particular, this will add you to the `zeromq` team. Once accepted, you will be given commit privileges on the zeromq [feedstock/repo]( https://github.com/conda-forge/zeromq-feedstock ).

**Comment by jakirkham** [comment]
As far as the Windows stuff goes, `zeromq` should be a bit easier as it does support `cmake`. My plan is to just build it with `nmake`, which seems to basically work like `make` for Windows from my minimal experience with it. The only trick is providing `libsodium` or some equivalent replacement.

**Pull request merged**
