### PR TITLE
Add scarplet

### PR DESCRIPTION
**Pull request by rmsare**

### CODE REVIEW

**Comment by rmsare** [comment]
AppVeyor build fails due to an unavailable dependency on win64 (also win32), PyFFTW.

**Comment by rmsare** [comment]
This is a Linux/OSX package for scientific software used in processing elevation data. 

Would someone (maybe @pelson?) be willing to review? 

There is a [concurrent journal review](https://github.com/openjournals/joss-reviews/issues/1066), and installation via conda would be convenient for potential users and contributors.

Thank you!

**Comment by mcflugen** [comment]
@conda-forge/staged-recipes, this is ready for review when someone has a moment.

It's being built as *noarch* but the tests on AppVeyor fail because a dependency is not yet available for Windows.

**Comment by scopatz** [comment]
Looks like you changed the example repo rather than copying the example to a new directory.  Can you please fix? Thanks!

**Comment by rmsare** [comment]
@scopatz Thanks! I fixed the conflict. Sorry about that.

**Pull request merged**
