### PR TITLE
First attempt at cppcheck conda package

### PR DESCRIPTION
**Pull request by tovrstra**
I'm new at this, so fingers crossed...

### CODE REVIEW

**Comment by tovrstra** [comment]
The `dir` line in bld.bat will be removed. I just want to see where it installs the cppcheck binary and I'll remove that eventually (I don't have a windows machine to test this locally.)

I'm not sure why it isn't running circleci?

**Comment by tovrstra** [comment]
@ocefpaf I'm looking for someone to help me with this recipe. Somehow circle CI does not even start Any idea why? The rest seems to be working. (I'm new to this.)

**Comment by jakirkham** [comment]
It may be an account settings thing. Have you logged into CircleCI with your GitHub account yet?

**Comment by tovrstra** [comment]
Never done that. I'll try.

**Comment by tovrstra** [comment]
Thanks, it is picking it up now. I first logged on to circle ci and then did `git commit --amend` without any changes, then force pushed. Fingers crossed ...

**Comment by jakirkham** [comment]
Why not build from source on Windows? It appears this is supported by the author.

**Comment by tovrstra** [comment]
Good point. I just copied this trick from another recipe.

It will me take some time to figure out how to build it from source. (I
don't have access to a Windows install at the moment.)

**Comment by jakirkham** [comment]
Fair enough. Would recommend skipping Windows then. Someone can always explore adding Windows support in the feedstock.

**Comment by tovrstra** [comment]
It should be good now.

**Comment by jakirkham** [comment]
Thanks @tovrstra!

**Pull request merged**
