### PR TITLE
intake-axds recipe

### PR DESCRIPTION
**Pull request by kthyng**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by kthyng** [comment]
Thank you @synapticarbors!!

**Comment by kthyng** [comment]
Oh my goodness, I see what you mean. How embarrassing. I will fix this now.

**Comment by beckermr** [comment]
Already fixed on main!

**Comment by beckermr** [comment]
This should have been caught by our reviewers and is not really something folks should have to know. Thanks for the recipe!

**Comment by kthyng** [comment]
@beckermr I knew what to type but I think my fingers didn't cooperate. Thanks for your help!

**Comment by BastianZim** [comment]
Possible fix in #21451

**Comment by kthyng** [comment]
Does something need to happen to recreate the whole recipe perhaps? I am not seeing anything come in at https://github.com/conda-forge/intake-axds-feedstock. @beckermr

**Comment by kthyng** [comment]
@jakirkham Ah ok, thank you! Sorry to bother you.

**Comment by jakirkham** [comment]
No bother at all. Sorry we don't have a better answer atm

**Comment by jakirkham** [comment]
This should now be resolved

https://github.com/conda-forge/intake-axds-feedstock

**Comment by kthyng** [comment]
Thank you!

**Pull request merged**
