### PR TITLE
Added gymnasium as a package

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge/staged-recipes ready for review!

**Comment by h-vetinari** [comment]
I consider it pretty discourteous to add this without contacting @conda-forge/gym 

Upstream has a big notice that "Gymnasium is a maintained fork of OpenAI’s Gym library."

This is recipe is fundamentally deficient (none of the many optional packages, missing the core pygame dependency, no tests). The feedstock should be replaced wholesale by the history of gym-feedstock, and then we continue maintenance based on updating that recipe. This is what we were [discussing](https://github.com/conda-forge/gym-feedstock/pull/29#issuecomment-1349668570), now that pygame and ale-py have finally been unblocked.

**Comment by thewchan** [comment]
@h-vetinari I am unaware, so I apologize. I will be adding Gymnasium developers to feedstock maintainers as I have been in contact with them. In the past I have seen guidance that it is acceptable to support core dependency only, so that's what I chose to do here for now. But I can add those (also as requested by Gymnasium developers.) As for testing, most recipe in Conda Forge also just use the import and pip check test, I do often include upstream test suite if all files are included in source. Finally, I did ping staged-recipe for review as usual so again I apologize if I deviated from any process that I am unaware of.

**Comment by thewchan** [comment]
@h-vetinari I'm also unaware of any requirement to contact project forked from unmaintained projects? It is not my intention to be discourteous, please let me know so I can avoid being so in the future. CC: @conda-forge/staged-recipes @conda-forge/core

**Comment by h-vetinari** [comment]
> I'm also unaware of any requirement to contact project forked from unmaintained projects?

It happens rarely enough that there are no formal rules (that I'm aware of). But in this case it's really a handover, gym goes until 0.26.1, which is equivalent to gymnasium 0.26.1, and then gymnasium continues. Gymnasium advertises itself as a drop-in replacement, and the fact that the packaging needs to support that claim should be unsurprising.

But yes (and without speaking for core or anyone else), packaging forked projects absolutely should at least notify the feedstock maintainers of the original project, because there can be any number of concerns that should be taken care of (i.e. a handover, avoid being co-installable, keeping the feedstock history, avoiding duplicate packages in c-f, other specifics depending on the situation, etc. etc.).

**Comment by ocefpaf** [comment]
> I consider it pretty discourteous to add this without contacting @conda-forge/gym

With the distributed nature of conda-forge it is virtually impossible to know that gym existed and make the proper contact. While I agree that it is important to loop in the gym team we just cannot ensure that it could happen!

We do have a package name analysis lint that should help when the name is close enough but I cannot see the lint working properly for gym vs gymnasium.

With that said. I'm pretty sure we can work it out and do what the gym teams thinks is best in this situation. Let's just try to not be accusative and expect things to happen when in a perfect way when they cannot.

**Review by h-vetinari — COMMENTED** [review]
> With the distributed nature of conda-forge it is virtually impossible to know that gym existed and make the proper contact.

Agreed about the c-f side, though if packaging a project that has large notices about being a fork (it's even in the `summary:` of this PR...), it should be basic due diligence to check whether the original project has been packaged already.

> Let's just try to not be accusative and expect things to happen in a perfect way when they cannot.

Sorry for the tone. For context, we spent an extraordinary amount of time to unblock gym from [pygame](https://github.com/conda-forge/staged-recipes/pull/19665) and [ale-py](https://github.com/conda-forge/staged-recipes/pull/19664), and it's frustrating to have the plans for fixing the feedstock dashed after all that.

Mistakes happen, water under the bridge. Happy to find a common path forward.

**Comment by thewchan** [comment]
@h-vetinari i will reference the work on the Gym feedstock and work on the Gymnasium feedstock to adhere the work you and others have done. Just give me some time.

**Comment by h-vetinari** [comment]
Thanks. Referencing is nice but functionally irrelevant. We need to restore all the outputs, and we _should_ restore the git history too (yes, this requires force-pushing `main`, but this was similarly done for shifting the `qt` feedstock to `qt-main`; the existing state could be preserved as a branch that gets no further updates).

**Comment by thewchan** [comment]
@conda-forge/core I'll rely on your guidance here. Certain dependencies on some Gymnasium outputs are not available on Conda yet, so I'll work on those first. After that, I will modify the feedstock on https://github.com/conda-forge/gymnasium-feedstock to include each of the outputs as defined here: https://github.com/Farama-Foundation/Gymnasium/blob/main/pyproject.toml

**Comment by thewchan** [comment]
@conda-forge/core Reading through the comments again I'm trying to interpret what I'm being directed to do here. Is it that I'm being told to hand over maintenance of https://github.com/conda-forge/gymnasium-feedstock to the original maintainers of the Gym feedstock? Because they were planning to contribute themselves anyway? Again, I'm sorry I'm completely unaware of of any of thes plans. If there are packages on PyPI that were claimed and should be off limits for contributors like me who work independently, please let me know, or let me know how not to get into trouble like this next time.

**Comment by ocefpaf** [comment]
Anyone can send packages to conda-forge. The right thing to do here is to invite them to the feedstock and let them update it too.

**Comment by thewchan** [comment]
@ocefpaf I'm trying to read into what's being said here, but it seems that there were already plans to transition Gym feedstock into Gymnasium? But what I did here blocked that?

**Comment by ocefpaf** [comment]
> @ocefpaf I'm trying to read into what's being said here, but it seems that there were already plans to transition Gym feedstock into Gymnasium? But what I did here blocked that?

@h-vetinari ideally you should archive `gym` and move the changes to `gymnasium`. We do note recommend in place changes like that even when they are drop-in replacement b/c the source upstream is different. If I understand this correctly `gymnasium` is a fork of `gym`, so we need a new feedstock.

**Comment by thewchan** [comment]
@ocefpaf @h-vetinari I'm totally okay to add whoever as maintainer on Gymnasium feedstock and stay out of the way. If that's what's preferred.

**Comment by h-vetinari** [comment]
> If I understand this correctly `gymnasium` is a fork of `gym`, so we need a new feedstock.

Yes, we wanted to create a new feedstock, but keep continuity with the previous packages (and feedstock), because that's what upstream did as well. So this change would show up as a single commit that changes the source, renames some outputs (and normally in such cases, adds compatibility-outputs with the old names).

I'm happy to join the gymnasium feedstock and do the necessary preparations.

After that, the help of @thewchan in the continued maintenance of the feedstock would of course be greatly appreciated. :)

**Pull request merged**
