### PR TITLE
Add pypdfium2 recipe

### PR DESCRIPTION
**Pull request by kellend-git**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mara004** [comment]
Note: this seems to be a copy of @boldorider4's https://github.com/AnacondaRecipes/pypdfium2-feedstock/blob/cd045f19c634da481a290e8b1226706b2d5d92d4/recipe/meta.yaml, an outdated snapshot of https://github.com/AnacondaRecipes/pypdfium2-feedstock/tree/pkg-2559_build_4.18.0.

**Comment by mara004** [comment]
@melonhead901 Hello, pypdfium2 maintainer here. As I'm planning to provide official pypdfium2 conda packages in the nearer future in a custom channel on anaconda, I do feel very uneasy about unofficial pypdfium2 packages in conda-forge or anaconda main, as that's bound to run people into confusion and/or unknowing installation of unofficial packages.
I feel like the upcoming official packages should be "first line treatment".

------

That said, the new approach taken here with build against conda-provided libraries is interesting, but there are some things to note:
* Google's build toolchain is quite big, so checkout for build takes rather long.
*  When embedding the pdfium binary into pypdfium2, you'd have to build for each python version due to conda limitations. Packaging pdfium separately would allow to declare pypdfium2 as `noarch: python`, bypassing this limitation.
* pdfium tends to focus on cross-compliation. I don't know if google's toolchain supports building natively on all common non-x86_64 CPUs. At least for armv7l you'd probably have to cross-compile.

**Comment by melonhead901** [comment]
Feedstock now available here: https://github.com/conda-forge/pypdfium2-feedstock

**Comment by mara004** [comment]
> Feedstock now available here: https://github.com/conda-forge/pypdfium2-feedstock

Yes, and it's pretty bad too. Supports only linux-64 and osx-64, which is but a fraction of the platforms we support upstream. Moreover, the packages are python version specific, which has no technical justification for pypdfium2.

**Pull request closed without merging**
