### PR TITLE
Add recipe for r-gwidgetstcltk2 (used conda r skeleton helper)

### PR DESCRIPTION
**Pull request by npavlovikj**

### CODE REVIEW

**Comment by npavlovikj** [comment]
There is an issue with AppVeyor and noarch packages - if I remove the noarch line the recipe builds fine on Windows.

**Comment by npavlovikj** [comment]
Initially, for Linux builds I was getting:
_Warning: no DISPLAY variable so Tk is not available_
_Error in structure(.External(.C_dotTclObjv, objv), class = "tclObj") :_
_[tcl] invalid command name "font"._
After some searching, I used the solution from the `qtconsole` feedstock, https://github.com/regro-cf-autotick-bot/qtconsole-feedstock/tree/607bf8a3772eb662c67bc46b5992bd68a015d69e/recipe, to fix this.

**Comment by npavlovikj** [comment]
@conda-forge/staged-recipes , I would appreciate your feedback on this recipe please.

**Comment by dbast** [comment]
@npavlovikj Thanks for getting this in and running.

**Pull request merged**
