### PR TITLE
fix r-boot

### PR DESCRIPTION
**Pull request by ocefpaf**
@johanneskoester this is passing on my fork. So let's hope it fixes the failure in `master`.

### CODE REVIEW

**Comment by jakirkham** [comment]
So it was [passing]( https://travis-ci.org/conda-forge/staged-recipes/builds/198724053 ) in the previous PR ( https://github.com/conda-forge/staged-recipes/pull/2354 ). 😕

Not entirely sure how this fixes the [`r-base` unsatisfiable on `osx-64` problem]( https://travis-ci.org/conda-forge/staged-recipes/builds/198760898#L300-L301 ), but if it does, great.

**Comment by jakirkham** [comment]
Maybe we need some sort of fix to `conda-smithy`? My best guess would be we need the same version constraints that `conda-build-all` has. I can try to look at it tonight.

xref: https://github.com/conda-forge/conda-smithy/issues/447

**Comment by johanneskoester** [comment]
Is this ready for merging?

**Comment by ocefpaf** [comment]
> Is this ready for merging?

I am waiting on @pelson's comments in https://github.com/conda-forge/conda-smithy/pull/453

If he is still MIA I will merge that and issue a new release so we can iterate what may be the next steps.

**Pull request merged**
