### PR TITLE
libunistring Recipe

### PR DESCRIPTION
**Pull request by stefan-balke**

### CODE REVIEW

**Comment by stefan-balke** [comment]
FAIL: uniname/test-uninames.sh

That test failed in travis-ci.

**Comment by ocefpaf** [comment]
> FAIL: uniname/test-uninames.sh

@stefan-balke do you know how to fix that?

**Comment by stefan-balke** [comment]
> @stefan-balke do you know how to fix that?

0.9.6 resolves this issue

**Comment by ocefpaf** [comment]
:tada:

**Pull request merged**
