### PR TITLE
Adding recipe for hieroglyph

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
Documented to work with 2.7 and 3.6 -- hopefully 3.5 as well.

Sorry for the extra commits from my wxpython experiments -- they should get squashed on merge...

### CODE REVIEW

**Comment by jjhelmus** [comment]
The build failure on Windows is a result of using conda-build 2.  Updating to conda build 3 will fix the issue.

**Comment by ChrisBarker-NOAA** [comment]
how does one update that?

**Comment by jjhelmus** [comment]
#5274 will change staged-recipes to use conda-build 3

**Comment by ChrisBarker-NOAA** [comment]
OK, so I wait for that to be merged?

**Comment by scopatz** [comment]
I don't think we need to wait for #5274

**Comment by scopatz** [comment]
Since this is no-arch python

**Comment by ChrisBarker-NOAA** [comment]
but it's failing on Windows....

**Comment by scopatz** [comment]
Failing to build or test?  It shouldn't matter if it fails to build on a platform or two if it is noarch

**Comment by ChrisBarker-NOAA** [comment]
Failing to build or test? It shouldn't matter if it fails to build on a
platform or two if it is noarch

It fails the build, due to entry_point executables on Windows.

Does that mean you can’t do noarch for a package with scripts, as the
scripts have to be done differently for each platform?

Now that I think about it — it probably does. I guess I’ll make this with
platform dependent packages instead.

-CHB


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/staged-recipes/pull/5498#issuecomment-378012094>,
or mute the thread

**Pull request closed without merging**
