### PR TITLE
Add pennylane

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

The packages have a circular dependency. Since pennylane is noarch, my plan is to remove the dependency there and then build both since pennylane-lightning depends on pennylane. Once built, I will mark the packages as broken and rebuild pennylane with the correct dependencies.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge/help-python-c this would be ready for review.

The packages have a circular dependency. Since _pennylane_ is noarch, my plan is to remove the dependency there and then build both since _pennylane-lightning_ depends on _pennylane_. Once built, I will mark the packages as broken and rebuild _pennylane_ with the correct dependencies.

Should I add `- pybind11-abi` to this? I don't see an interface but am not sure.

I get the following warning: 
```shell
[WARNING] This wheel needs a higher macOS version than is set in MACOSX_DEPLOYMENT_TARGET variable.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 10_14 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
```
Is this something I should change or ignore?

**Comment by BastianZim** [comment]
Gentle ping here @conda-forge/staged-recipes thanks! :)

**Comment by BastianZim** [comment]
Thanks for merging!

**Comment by ocefpaf** [comment]
> The packages have a circular dependency. Since pennylane is noarch, my plan is to remove the dependency there and then build both since pennylane-lightning depends on pennylane. Once built, I will mark the packages as broken and rebuild pennylane with the correct dependencies.

I wonder if we could do better than that with our tooling.

**Comment by BastianZim** [comment]
I guess they could be built in the same recipe? But even then I'm not sure if that works. Do you have a specific idea in mind?

**Comment by ocefpaf** [comment]
> Do you have a specific idea in mind?

Nothing really. I'm just upset with the current state.

**Pull request merged**
