### PR TITLE
add fvcore

### PR DESCRIPTION
**Pull request by rluria14**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rluria14** [comment]
> Looks good, @conda-forge/staged-recipes This package has no release builds and probably won't have soon, what is our policy on that? Given that the pre-releases are somewhat real releases, merge anyway?

Referencing this [PR](https://github.com/conda-forge/staged-recipes/pull/10793#pullrequestreview-356096431) that also uses a prerelease, I've added a prerelease channel target in the conda_build_config.

**Comment by rluria14** [comment]
@conda-forge/staged-recipes @xhochy this recipe is ready for review

**Comment by chrisburr** [comment]
As there are downstream packages with non-pre-release versions I'd be inclined to suggest including it on the main channel. I'll merge if you either revert that commit or comment to say you'd rather keep it this way.

**Comment by rluria14** [comment]
> As there are downstream packages with non-pre-release versions I'd be inclined to suggest including it on the main channel. I'll merge if you either revert that commit or comment to say you'd rather keep it this way.

@chrisburr fixed by removing the conda_build_config

**Pull request merged**
