### PR TITLE
Adding fast-pt.

### PR DESCRIPTION
**Pull request by dderienzo**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dderienzo** [comment]
@conda-forge/help-python 
Hello, I was about to stage this PR, but the linter failed because a feedstock exists with the same name. That, along with the copy of fast-pt on conda-forge is deprecated, and I am not sure who the old maintainer is.

What can I do?

**Comment by jablazek** [comment]
Hi. I would also like to be a maintainer. I believe @beckermr is the original maintainer.

**Comment by beckermr** [comment]
Is this the same package or a different one? If it is the same, we should update the feedstock.

**Comment by dderienzo** [comment]
@beckermr It should be the same (but more recent version) package of fast-pt that already exists in conda-forge at this link:
https://anaconda.org/conda-forge/fast-pt

How can we transfer ownership to me and @jablazek and work to update the feedstock?

**Comment by beckermr** [comment]
Make a pr to the feedstock and add yourself as a maintainer. We do not remove maintainers unless they ask to be removed.

**Comment by dderienzo** [comment]
@beckermr I made a PR to the feedstock, pending review. I wasn't sure if you wanted to remain the maintainer or not so I left you in the meta.yaml.

**Pull request closed without merging**
