### PR TITLE
Add APR

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/staged-recipes/issues/1662

Adds packages for APR, APR-util, and APR-iconv. Uses a split package idea that Ray and I discussed sometime ago in PR ( https://github.com/conda-forge/staged-recipes/pull/2815 ), which it appears he and Nehal [implemented]( https://github.com/AnacondaRecipes/aggregate/tree/53047f8afc2b7091d0f3aa3297a798b3c40ce93c/apr-feedstock ). Going to give this a try at `staged-recipes` and see if this just works or needs some changes.

### CODE REVIEW

**Comment by jakirkham** [comment]
Alright had to do a bit more work to actually split the package, but that is done in the commit above. This works for me locally on macOS. Haven't test Linux, but expect that would be the same story. Also haven't tested Windows; so, will need to get that result from CI.

Appears that the build script at `staged-recipes` [detects a cycle]( https://travis-ci.org/conda-forge/staged-recipes/builds/471990737#L316 ) in the build. AFAIK there is no cycle and `conda-build` seems to have no issues with the recipe. So maybe there is a bug in the script? Help isolating that would be appreciated.

Could use some reviews (😉 @mingwandroid and @nehaljwani) when they have a chance.

Though all of this can wait until after the holiday as I'm sure others are not as excited to build APR during their break. 😄

**Comment by jakirkham** [comment]
@conda-forge/staged-recipes, any ideas why the build script at `staged-recipes` [detects a cycle]( https://travis-ci.org/conda-forge/staged-recipes/builds/471990737#L316 ) in the build? `conda-build` seems to build the recipe without issues locally. Has this run into some sort of edge case in the build script?

**Comment by scopatz** [comment]
@jakirkham - maybe this is because conda-build is being pinned to an older version still?

**Comment by mingwandroid** [comment]
LGTM.

**Comment by jakirkham** [comment]
Thanks for taking a look, @mingwandroid.

@scopatz, I tried merging it into `master` (as `conda-build` is unpinned again), but the issue persists. FWIW `conda-build` seemed to build this without issues, but running `.ci_support/build_all.py recipes` produces the problem.

**Comment by scopatz** [comment]
It seems like #7426 might be releated

**Comment by jakirkham** [comment]
Thanks for pointing that out. It seems to change what happens before the error, but the error itself is the same.

```python
$ python .ci_support/build_all.py recipes/
Building apr with conda-forge/label/main
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
rendering /Users/kirkhamj/Developer/Conda/conda-forge/staged-recipes/recipes/apr for osx-64
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Dependency libapr, version any is not installable from your channels: ['local', 'conda-forge', 'defaults', 'conda-forge', 'defaults'] with subdir osx-64.  Seeing if we can build it...
Dependency libapriconv, version any is not installable from your channels: ['local', 'conda-forge', 'defaults', 'conda-forge', 'defaults'] with subdir osx-64.  Seeing if we can build it...
Dependency libaprutil, version any is not installable from your channels: ['local', 'conda-forge', 'defaults', 'conda-forge', 'defaults'] with subdir osx-64.  Seeing if we can build it...
Traceback (most recent call last):
  File ".ci_support/build_all.py", line 134, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, old_comp_folders, arch, channel_urls)
  File ".ci_support/build_all.py", line 109, in build_folders
    order = list(nx.topological_sort(G))
  File "/zopt/conda3/lib/python3.6/site-packages/networkx/algorithms/dag.py", line 208, in topological_sort
    raise nx.NetworkXUnfeasible("Graph contains a cycle or graph changed "
networkx.exception.NetworkXUnfeasible: Graph contains a cycle or graph changed during iteration
```

**Comment by chrisburr** [comment]
This isn't the same issue as #7426. It seems conda-forge can't handle building a top level recipe at the same time as the outputs. I think you can use the workaround from `clangdev 5.0.0` and apply this patch:
```diff
diff --git a/recipes/apr/meta.yaml b/recipes/apr/meta.yaml
index f0bec3839..cd2aec98a 100644
--- a/recipes/apr/meta.yaml
+++ b/recipes/apr/meta.yaml
@@ -4,7 +4,7 @@
 {% set mirror = "http://www-us.apache.org/dist/" %}

 package:
-  name: apr
+  name: apr_combined
   version: {{ apr_ver }}

 source:
@@ -30,13 +30,20 @@ source:
 build:
   number: 0

+# Specifying `compiler('c')` as a top-level build requirements to force
+# conda-smithy to generate the correct build matrix.
 requirements:
-  run:
-    - libapr
-    - libaprutil
-    - libapriconv
+  build:
+    - {{ compiler('c') }}

 outputs:
+  - name: apr
+    version: {{ apr_ver }}
+    requirements:
+      run:
+        - libapr
+        - libaprutil
+        - libapriconv
   - name: libapr
     version: {{ apr_ver }}
     build:
```

(It's important that the top level recipe isn't called `apr` to avoid https://github.com/conda/conda-build/issues/3337.)

**Comment by jakirkham** [comment]
Was afraid someone might say this. 😄 Thanks for the info.

**Comment by jakirkham** [comment]
Have tried merging with `master` and it appears the macOS and Linux builds now pass. 🎉 

Windows is failing rather early on due to some sort of issue determining what to build.

```python
Traceback (most recent call last):
  File ".ci_support\build_all.py", line 130, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support\build_all.py", line 104, in build_folders
    config=config, finalize=False)
  File "C:\projects\staged-recipes\.ci_support\compute_build_graph.py", line 403, in construct_graph
    recipes_dir, config=config, finalize=finalize)
  File "C:\projects\staged-recipes\.ci_support\compute_build_graph.py", line 219, in add_recipe_to_graph
    rendered = _get_or_render_metadata(recipe_dir, worker, config=config, finalize=finalize)
  File "C:\Miniconda36-x64\lib\site-packages\conda\exports.py", line 182, in __call__
    return self.func(*args, **kw)
  File "C:\projects\staged-recipes\.ci_support\compute_build_graph.py", line 212, in _get_or_render_metadata
    bypass_env_check=True, config=config, finalize=finalize)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 51, in render
    bypass_env_check=bypass_env_check):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 1994, in get_output_metadata_set
    for k in out_metadata.get_used_vars()}))] = out, out_metadata
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 2122, in get_used_vars
    force_global=force_global)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 2175, in _get_used_vars_meta_yaml
    force_top_level=force_top_level, force_global=force_global, apply_selectors=False)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 2162, in _get_used_vars_meta_yaml_helper
    apply_selectors=apply_selectors))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 1693, in extract_single_output_text
    output = output_matches[output_index] if output_matches else ''
IndexError: list index out of range
```

ref: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22603852#L185

**Comment by scopatz** [comment]
Glad that this is a conda-build issue.

**Comment by jakirkham** [comment]
Nope, turns out the error is mine. Though minimizing the issue was productive as that bug is now fixed.

**Comment by jakirkham** [comment]
Hmm...it appears I'm getting a build failure on Windows. It seems to not be able to find `expat`. 😕 @mingwandroid @nehaljwani, any ideas?

```batch
"%SRC_DIR%\apr-util\libaprutil.vcxproj" (default target) (2) ->
(ClCompile target) -> 
  xml\apr_xml.c(35): fatal error C1083: Cannot open include file: 'expat.h': No such file or directory [%SRC_DIR%\apr-util\libaprutil.vcxproj]
```

ref: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22633909

**Comment by jakirkham** [comment]
Alright this built through the VS 2015 build and ran the tests. Also macOS and Linux haven't been changed since they last passed. However it appears to be hung up on some other bug that is specific to staged-recipes. Have checked locally that a normal feedstock will be created through re-rendering. Am going to go ahead and merge and deal with any other issues that arise in the feedstock. Thanks all for putting up with my noise and helping me slog through this one.

**Comment by jakirkham** [comment]
FWIW in the feedstock [Windows VS 2008 and VS 2015 passed]( https://ci.appveyor.com/project/conda-forge/apr-feedstock/builds/22648351 ). The rest of the packages should follow soon.

**Pull request merged**
