### PR TITLE
Add pytest-azurepipelines

### PR DESCRIPTION
**Pull request by leouieda**
Plugin for pytest that makes it simple to work with Azure Pipelines. Pure python and no special treatment for different Python versions (so using noarch).

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by leouieda** [comment]
@tonybaloney I setup this conda-forge recipe for pytest-azurepipelines to make it easier to install for people using conda. May I add you as a maintainer? The main work would be merging in the PRs when new versions are published. I'm willing to help out and maintain as well and the conda-forge team is super nice and responsive.

**Comment by leouieda** [comment]
:wave: @conda-forge/help-python this is ready for review whenever you have the time

**Comment by chrisburr** [comment]
Looks good to me, LGTM 👍 
(you can edit the maintainers in the feedstock if needed)

**Comment by tonybaloney** [comment]
@leouieda I’m already on the forge org so happy to be added as maintainer

**Comment by leouieda** [comment]
Thanks @chrisburr! @tonybaloney I'll add you on the feedstock.

**Pull request merged**
