### PR TITLE
add recipe for r-autometric from conda_r_skeleton_helper

### PR DESCRIPTION
**Pull request by brendanf**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by brendanf** [comment]
```
  ERROR (r-autometric,lib/R/library/autometric/libs/x64/autometric.dll): Needed DSO Library/mingw-w64/bin/libwinpthread-1.dll found in ['conda-forge/win-64::m2w64-libwinpthread-git==5.0.0.4634.697f757=2']
  ERROR (r-autometric,lib/R/library/autometric/libs/x64/autometric.dll): .. but ['conda-forge/win-64::m2w64-libwinpthread-git==5.0.0.4634.697f757=2'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
WARNING (r-autometric): dso library package conda-forge/win-64::m2w64-gcc-libs==5.3.0=7 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-autometric): dso library package conda-forge/win-64::vc14_runtime==14.40.33810=hcc2c482_22 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-autometric): interpreter (R) package conda-forge/win-64::r-base==4.1.3=h22dd5fe_16 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-autometric): dso library package conda-forge/win-64::m2w64-gcc-libs-core==5.3.0=7 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-autometric): dso library package conda-forge/win-64::ucrt==10.0.22621.0=h57928b3_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

**Comment by brendanf** [comment]
`ERROR (r-autometric,lib/R/library/autometric/libs/x64/autometric.dll): $RPATH/R.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.`

**Comment by brendanf** [comment]
@conda-forge/help-r Ready for review.

**Review by mfansler — APPROVED** [review]
Looks good.

Note that newer `conda_r_skeleton_helper` includes the `missing_dso_whitelist` as default boilerplate.

**Pull request merged**
