### PR TITLE
Recipe for monty package.

### PR DESCRIPTION
**Pull request by shyuep**
Recipe for monty package. Previous comments have been handled.

### CODE REVIEW

**Comment by shyuep** [comment]
Hi there,

This recipe is merged, but I can't find the package in the feedstock. Can you check on this pls? Thanks.

**Comment by scopatz** [comment]
@jakirkham and @conda-forge/core know more about this problem than I do... Did a feedstock get created? If so, try rebuilding that

**Comment by synapticarbors** [comment]
It looks like the travis check failed, so maybe that killed the feedstock creation (I think the travis build actually creates the feedstock, but I'm not 100% on this)?

**Comment by ocefpaf** [comment]
You are correct. And Travis-CI is still recovering from an outage. I will
check its status and restart it to get the feedstock created.

**Comment by shyuep** [comment]
Hi there, can I check if this issue has been resolved yet? Thanks.

**Comment by shyuep** [comment]
Hi there, I still do not see monty on conda-forge. As far as I know, there shouldn't be any issues with the tests on this module.

**Comment by jakirkham** [comment]
Not sure what happened. Could you please try adding a new PR to staged-recipes? We can merge that ASAP and that will hopefully fix the issue.

**Comment by shyuep** [comment]
Just resubmitted a PR. https://github.com/conda-forge/staged-recipes/pull/2141

**Pull request merged**
