### PR TITLE
Adding PyPI package seamm-dashboard-client to conda forge.

### PR DESCRIPTION
**Pull request by paulsaxe**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [] (N/A) If static libraries are linked in, the license of the static library is packaged.
- [] (N/A) Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by paulsaxe** [comment]
@conda-forge/staged-recipes Checking if this PR has fallen through the cracks. Hopefully very simple and straightforward. This package is required by the [seamm](https://github.com/conda-forge/seamm-feedstock) package in CondaForge, so that package is waiting.

**Comment by BastianZim** [comment]
> Checking if this PR has fallen through the cracks.

We only review once the relevant team is pinged and the labels are added. Otherwise, we wouldn't know if it's ready for review. :)

**Comment by paulsaxe** [comment]
Thanks for merging. Your comment suggests that I need to ping some team or do something else; however, I followed the instructions at https://conda-forge.org/docs/maintainer/adding_pkgs.html <https://conda-forge.org/docs/maintainer/adding_pkgs.html> which did not mention any further steps:
"Once you finished your PR, all you have to do is wait for feedback from our review team.”  For future reference, is there another step?

Paul

3793 Fairway View Drive
Riner VA 24149-2247
USA
***@***.***
+1.505.603.8182

**Comment by BastianZim** [comment]
Ahh that is indeed incorrect. Please open an issue for the docs here: https://github.com/conda-forge/conda-forge.github.io

Once ready for review, you need to ping the team that is responsible for the language that you are submitting, as outlined in the PR body.

If you click on "edit" you will be able to find the following text:


Thank you very much for putting in this recipe PR!

This repository is very active, so if you need help with a PR, please let the
right people know. There are language-specific teams for reviewing recipes.

| Language        | Name of review team           |
| --------------- | ----------------------------- |
| python          | `conda-forge/help-python`    |
| python/c hybrid | `conda-forge/help-python-c`  |
| r               | `conda-forge/help-r`         |
| java            | `conda-forge/help-java`      |
| nodejs          | `conda-forge/help-nodejs`    |
| c/c++           | `conda-forge/help-c-cpp`     |
| perl            | `conda-forge/help-perl`      |
| Julia           | `conda-forge/help-julia`     |
| ruby            | `conda-forge/help-ruby`      |
| other           | `conda-forge/staged-recipes` |

(I have removed the @ so teams don't get pinged)

Once the PR is ready for review, please mention one of the teams above in a
new comment. i.e. `conda-forge/help-some-language, ready for review!`
Then, a bot will label the PR as 'review-requested'.

Due to GitHub limitations, first time contributors to conda-forge are unable
to ping conda-forge teams directly, but you can [ask a bot to ping the team][1]
using a special command in a comment on the PR to get the attention of the
`staged-recipes` team. You can also consider asking on our [Gitter channel][2]
if your recipe isn't reviewed promptly.

[1]: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-ping-team
[2]: https://gitter.im/conda-forge/conda-forge.github.io

**Pull request merged**
