### PR TITLE
add awscrt

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ocefpaf** [comment]
```
    --- Building dependency: aws-lc (RelWithDebInfo) ---
    /home/conda/staged-recipes/build_artifacts/awscrt_1619035367907/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/cmake -DCMAKE_PREFIX_PATH=/tmp/pip-req-build-5jfjgulx/build/deps/install -DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-5jfjgulx/build/deps/install -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_LIBSSL=OFF /tmp/pip-req-build-5jfjgulx/crt/aws-lc
    CMake Error at CMakeLists.txt:39 (message):
      GCC 9.3.0 is not supported.
```

:unamused:

**Comment by chrisburr** [comment]
Apparently this is intentional to ban this version: https://github.com/awslabs/aws-lc/blob/129fc373c971f6ac275a1ed5de2b96410d9cc9d9/CMakeLists.txt#L31-L42

It should still be possible to use GCC 7 using a `conda_build_config.yaml`.

**Comment by ocefpaf** [comment]
> Apparently this is intentional to ban this version: https://github.com/awslabs/aws-lc/blob/129fc373c971f6ac275a1ed5de2b96410d9cc9d9/CMakeLists.txt#L31-L42
> 
> It should still be possible to use GCC 7 using a `conda_build_config.yaml`.

Do you know the right syntax for it? I tried:

```yaml
ctng_gcc:
  - 7.5.0
```

but it didn't work.

**Comment by xhochy** [comment]
@ocefpaf Welcome to the world of aws-c-* packages 😍 I will dig a bit into this as it is probably better to use the C(++) packages from conda-forge instead of the bundled sources. For the referenced error, I would suggest a different fix: Find out how to build it without `aws-lc`. That is AWS' own OpenSSL fork, you should be able to build instead without `aws-lc` normally and use our `openssl` package.

**Comment by ocefpaf** [comment]
Thanks @xhochy!

**Comment by xhochy** [comment]
Depends on https://github.com/conda-forge/aws-c-mqtt-feedstock/pull/8

**Comment by xhochy** [comment]
@conda-forge/staged-recipes With the latest build of `aws-c-mqtt` this is now ready for review/merge.

**Pull request merged**
