### PR TITLE
Add free proxy

### PR DESCRIPTION
**Pull request by rpanai**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xhochy** [comment]
You need to rebase this on the current master.

**Comment by rpanai** [comment]
> You need to rebase this on the current master.

done!

**Comment by xhochy** [comment]
Please rebase, seems like you merged and this now contains many commits that shouldn't be part of this PR.

**Comment by rpanai** [comment]
> Please rebase, seems like you merged and this now contains many commits that shouldn't be part of this PR.

Do you mind to tell me how to do it? Or share a link. I think I'm lost here.

**Comment by arunkannawadi** [comment]
@rpanai - do you need help with rebasing? I'd like this package in conda-forge and will be willing to help you with it, especially if you volunteer to be the maintainer (which you have)

**Comment by arunkannawadi** [comment]
This package is being added in https://github.com/conda-forge/staged-recipes/pull/17289

**Comment by dopplershift** [comment]
Superseded by #17289.

**Pull request closed without merging**
