### PR TITLE
WIP: add pip

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
This is failing pretty hilariously because in efforts to remove itself as a dependency, it is installing Python 1.0.  This PR is WIP.

**Comment by jakirkham** [comment]
This and `setuptools` what a mess. What did you do internally for these before?

**Comment by jjhelmus** [comment]
You need to set the `add_pip_as_python_depedency` to false in the .condarc file.  This needs to be done before conda build is called. `conda config --set add_pip_as_python_dependency false` will do this.

**Comment by msarahan** [comment]
@jjhelmus - so correct me if I'm wrong, but that means those are changes that have to happen in the CI scripts?

**Comment by jakirkham** [comment]
That sounds accurate. However, I can understand some changes in CI when it comes to packaging `pip`. This is just an odd ball 🎱.

Thoughts @pelson?

**Comment by jjhelmus** [comment]
> @jjhelmus - so correct me if I'm wrong, but that means those are changes that have to happen in the CI scripts?

Yes the change would need to be done before the build command is called, so in the CI scripts.

**Comment by jakirkham** [comment]
Turns out `add_pip_as_python_depedency` is not documented. So, have added a PR ( https://github.com/conda/conda-docs/pull/276 ) to the docs.

Though IMHO setting this `add_pip_as_python_depedency` to `False` seems like a totally reasonable thing to do in general. Otherwise `setuptools` and `pip are automatically installed. In some case, these are not needed. Also, in cases where they are needed, people may forget to document this as there is no consequence (i.e. build failure) from not doing so. Not including them by default fixes that problem and makes packaging things like this easier. Will propose PRs for staged-recipes and conda-smithy to change this.

**Comment by jakirkham** [comment]
Doc change got accepted in record time. 🐎 See the change [here]( http://conda.pydata.org/docs/config.html#add-pip-as-python-dependency-add-pip-as-python-depedency ).

**Comment by jakirkham** [comment]
Here is the `staged-recipes` PR ( https://github.com/conda-forge/staged-recipes/pull/629 ) and the `conda-smithy` PR ( https://github.com/conda-forge/conda-smithy/pull/172 ). Both of these set `add_pip_as_python_depedency` to `false`.

**Comment by pelson** [comment]
Would you mind rebasing this @msarahan. I suspect it will build fine on staged-recipes, but still anticipate feedstock issues (pending conda-smithy changes).

**Comment by jakirkham** [comment]
@jjhelmus put this in PR ( https://github.com/conda-forge/staged-recipes/pull/864 ).

**Pull request closed without merging**
