### PR TITLE
Cufflinks added.

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by xmnlab** [comment]
@renomoto added as maintainer.

**Comment by Cashalow** [comment]
I think this package is already available at cufflinks-py 
https://github.com/conda-forge/cufflinks-py-feedstock

**Comment by cbrueffer** [comment]
Indeed; there's a popular bioinformatics package called cufflinks that is downstream in bioconda, hence the altered name to avoid clashes.

**Comment by xmnlab** [comment]
Oh I see .. thank you for the explanation.

**Pull request closed without merging**
