### PR TITLE
Add recipe for r-magicaxis, used the conda_r_skeleton_helper script for it

### PR DESCRIPTION
**Pull request by npavlovikj**
Add recipe for r-magicaxis, used the conda_r_skeleton_helper script for it

### CODE REVIEW

**Comment by cbrueffer** [comment]
@npavlovikj did you disable the win64 build because of `r-mapproj`? I added win64 packages today, so that should work now. If there's a different reason, please add a short explanatory comment above the skip line.

**Comment by npavlovikj** [comment]
@cbrueffer , thanks for adding the win-64 package. That was indeed the reason why I skipped the win-64 build - I added it again, and the built was successful.

**Comment by cbrueffer** [comment]
Great, thanks!

**Comment by npavlovikj** [comment]
@cbrueffer , all feedstock builds failed, https://github.com/conda-forge/r-magicaxis-feedstock. It looks like the download url, https://cran.r-project.org/src/contrib/Archive/magicaxis/magicaxis_2.0.3.tar.gz, is suddenly non-existent which is really odd. Should I modify the recipe, or contact someone from cran first?

**Comment by cbrueffer** [comment]
@npavlovikj looks like it was an intermittent problem; I've restarted the builds and it seems to work now.

**Pull request merged**
