### PR TITLE
Adding NARDINI sequence analysis package

### PR DESCRIPTION
**Pull request by jaredl7**
Added recipe for the NARDINI sequence analysis package.

PyPi project page: https://pypi.org/project/nardini/
Github repository: https://github.com/mshinn23/nardini

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jaredl7** [comment]
Our project uses GPL 3.0 for licensing. According to SPDX, "GPL-3.0" is an [OSI approved short identifier](https://spdx.dev/spdx-specification-21-web-version/), although it is [deprecated](https://spdx.org/licenses/GPL-3.0). 

> Hi! This is the friendly automated conda-forge-linting service.
> 
> I just wanted to let you know that I linted all conda-recipes in your PR (`recipes/nardini`) and found it was in an excellent condition.
> 
> I do have some suggestions for making it better though...
> 
> For **recipes/nardini**:
> 
> * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.
> 
> Documentation on acceptable licenses can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions).

**Comment by jaredl7** [comment]
Hello @conda-forge/python, this PR is ready for review. Thanks for looking into this on our behalf! Should any edits be required, let us know and we'll work to address them post-haste.

**Comment by jaredl7** [comment]
@conda-forge/help-python, ready for review!

**Comment by jaredl7** [comment]
Thanks, @dopplershift! I've committed the SPDX identifier in the `about` section within `meta.yaml`.

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Ignoring noarch Windows build failure due to missing dependency.

**Pull request merged**
