### PR TITLE
Add thefuck recipe

### PR DESCRIPTION
**Pull request by proinsias**

### CODE REVIEW

**Comment by proinsias** [comment]
The CircleCI log states:

    conda.resolve.NoPackagesFound: Package missing in current linux-64 channels: 
  - pathlib

`pathlib` is included in python 3.4+, so it's only a dependency for earlier versions – see the `setup.py` for this package:

    extras_require = {':python_version<"3.4"': ['pathlib']}

Is there a way of specifying this in a `meta.yaml` file? Otherwise, I'll look into putting pathlib into conda.

**Comment by proinsias** [comment]
@conda-forge-admin, please rerender

**Comment by proinsias** [comment]
@conda-forge-admin, please restart ci

**Comment by proinsias** [comment]
Appveyor is failing with error:

```
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
Command exited with code 1
```

From some searching of this repo, this seems to be an intermittent issue with AppVeyor, soI'm not investigatiing further for now.

**Comment by proinsias** [comment]
@conda-forge/staged-recipes – I believe this is ready for review now.

**Comment by beckermr** [comment]
This package name probably violates our community standards. cc @conda-forge/core

**Comment by jjhelmus** [comment]
@proinsias Thanks for putting this together.  

As mentioned in our [governance documentation](https://conda-forge.org/docs/orga/governance.html) conda-forge adheres to the [NumFocus Code of Conduct](https://numfocus.org/code-of-conduct).  

I think that the name of this package conflicts with this code of conduct and therefore cannot be distributed by conda-forge.  Specifically, the code of conducts calls out "The use of sexualized language or imagery" and "Excessive profanity (please avoid curse words; people differ greatly in their sensitivity to swearing)" as unacceptable behavior.

I'm certain your intentions were not to violate this code but rather to provide this utility to conda-forge users who may find it helpful.  Unfortunately, as an organization we cannot provide some packages because of naming choices that the authors have made. Working with the upstream developers to rename the project to something that does not conflict with our code of conduct is an option, if there is interest to get the functionality of this package available in conda-forge.

**Comment by synapticarbors** [comment]
If you search the issues upstream, it seems pretty clear that the author will not change the name, although gives the option to fork the project or use aliases (not that that will help here):

https://github.com/nvbn/thefuck/issues/801
https://github.com/nvbn/thefuck/issues/1070
etc...

**Comment by beckermr** [comment]
OK. Let's close this for now. We can reopen it later if things change.

**Pull request closed without merging**
