### PR TITLE
Add htcondor

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This adds a recipe for `htcondor` the high-throughput computing jobscheduler. The build takes a monolithic library build and separates out into a few component packages

- `libcondor_utils`
- `htcondor-classads`
- `htcondor-procd`
- `htcondor-utils` (including `condor_q`, `condor_submit`, etc.)

and then builds out (separately) a `python-htcondor` package for the python bindings. There is finally a `htcondor` metapackage that just depends upon everything else.

This covers all of the 'user' utilities to communicate with an existing scheduler - currently the daemons that are required to run htcondor as a service are not included in any of the packages, but are planned to be included in a future build/release once the HTCondor team have been able to play around with the conda packages a bit more.

@jasoncpatton, please post a message here indicating that you are willing to be named as a maintainer.

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@jasoncpatton, the [build is failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=83642&view=logs&jobId=10bda42a-d420-5c28-a43f-bc4e66405e5c&taskId=bef775d0-a1a2-55a3-9721-17147029baf0&lineStart=4480&lineEnd=4480&colStart=175&colEnd=201) with:

```
/home/conda/staged-recipes/build_artifacts/htcondor_1571846347415/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -l-Wl,-Bstatic
collect2: error: ld returned 1 exit status
```

any ideas?

**Comment by jasoncpatton** [comment]
> @jasoncpatton, the [build is failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=83642&view=logs&jobId=10bda42a-d420-5c28-a43f-bc4e66405e5c&taskId=bef775d0-a1a2-55a3-9721-17147029baf0&lineStart=4480&lineEnd=4480&colStart=175&colEnd=201) with:
> 
> ```
> /home/conda/staged-recipes/build_artifacts/htcondor_1571846347415/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -l-Wl,-Bstatic
> collect2: error: ld returned 1 exit status
> ```
> 
> any ideas?

The variable containing the name of the boost.python library is left undefined when building on a machine (or inside a container) that has an unexpected `${SYSTEM_NAME}`. (Sigh.) The result is the compiler is passed a bare `-l` flag, resulting the error above. See https://github.com/duncanmmacleod/staged-recipes/pull/3 for a fix.

**Comment by jasoncpatton** [comment]
I can be the maintainer on this recipe once we get the build figured out.

**Comment by duncanmmacleod** [comment]
It's ALIVE! @conda-forge/staged-recipes, I think this is ready for review now. Reminder: this is a `linux`-only package for now.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
