### PR TITLE
Adding opensim package

### PR DESCRIPTION
**Pull request by chrisdembia**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by chrisdembia** [comment]
@kidzik @moorepants are you willing to be maintainers of this package? See the message above:

> GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

**Comment by chrisdembia** [comment]
@romainmartinez are you still interested in helping with this package?

**Comment by moorepants** [comment]
Yes, I'm fine helping with this.

**Comment by kidzik** [comment]
Sure, happy to help, thanks for listing me

**Comment by JonathanAMichaels** [comment]
Hi @chrisdembia, I'd be very interested in getting this working (at least for the linux build with opensim 4.0+). Let me know how I can help.

**Comment by moorepants** [comment]
@JonathanAMichaels You can start with this branch and build on it. If you pull it, make your edits, and open a new PR you can iterate there.

**Pull request closed without merging**
