### PR TITLE
Add SMAC

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by BastianZim** [comment]
CC #5656

**Comment by mfeurer** [comment]
> I cannot run the unit tests because the PyPI package includes all test folders but not __init__.py. Not a huge problem, just for your information.

I don't see a reason that's not included - do you know why that's the case?

> Could you just quickly indicate if you'd like to be added as a maintainer here as well?

Yes, I think that would be helpful in the long run.

> The docs mention a C++ compiler and SWIG for the random forest but since we're packaging pyrfr separately, this should not be needed, correct?

Correct, this should not be needed.

> The requirements mention that only LINUX systems are supported, is that correct (Windows will always fail since pynisher is not available there but would macOS work)?

We don't test OSX so we don't know. AFAIK it can be installed and used, it's just unclear whether the behavior is the same.

> I'm currently testing the command line with smac --helpwhich requires scikit-optimize. This is listed upstream as optional in extras_require.json but seems to be mandatory here, is that correct?

Sorry, I don't know about that. I think we currently don't have anyone who maintains the CLI interface. Maybe @mlindauer knows.

> The docs mention python >=3.5.2 whereas setup.py states python_requires=">=3.6". Do you know which one is correct?

Most likely the latter one. We run unit tests for 3.6-3.9.

**Comment by mlindauer** [comment]
> > I'm currently testing the command line with smac --helpwhich requires scikit-optimize. This is listed upstream as optional in extras_require.json but seems to be mandatory here, is that correct?
> 
> Sorry, I don't know about that. I think we currently don't have anyone who maintains the CLI interface. Maybe @mlindauer knows.

SMAC's cli imports all our facades. One of these is the BO facade, which indeed requires scikit-optimize.

**Comment by BastianZim** [comment]
> I don't see a reason that's not included - do you know why that's the case?

No not immediately, maybe that's a reserved name somewhere? Anyways, not a problem I'll just use the GitHub releases as a source. The latest version on PyPI is 0.13.1 whereas the latest GitHub release is 0.13.0. Is there a difference, or is it just a re-release?

> We don't test OSX so we don't know. AFAIK it can be installed and used, it's just unclear whether the behavior is the same. 

Ok, I'll test it on OSX and then we can still decide if it makes sense or not.

> Sorry, I don't know about that. I think we currently don't have anyone who maintains the CLI interface. Maybe @mlindauer knows.

Since it's working in the tests I think it's fine if we just include and remove it again if any errors arise.

> Most likely the latter one. We run unit tests for 3.6-3.9.

Ok, since conda-forge only tests on those as well, I'll add that as a minimum bound.

**Comment by mfeurer** [comment]
> If that's something fixable that I'm missing let me know, otherwise I'd skip OSX.

Sorry, I'm not an OSX user and I think none of the developers is either so you'd have to skip these unless anyone wants to help out here.

**Comment by BastianZim** [comment]
Ok no worries, thanks for the feedback then I'll leave it out.

Just one last question: Can you just quickly confirm whether 0.13.0 on GitHub is the same as 0.13.1 on PyPI?

**Comment by mfeurer** [comment]
> Just one last question: Can you just quickly confirm whether 0.13.0 on GitHub is the same as 0.13.1 on PyPI?

No, it's not the same. I just created the appropriate [0.13.1](https://github.com/automl/SMAC3/releases/tag/v0.13.1) on GitHub.

**Comment by BastianZim** [comment]
Thank you!

**Comment by BastianZim** [comment]
@conda-forge/help-python Would be ready for review, thanks!

One note: The package is only available on Linux. As there currently is no `__linux` virtual package, I used `__glibc`instead as that seems to be the closest and preserves `noarch`. Let me know if I should change that to `skip`.

I have created https://github.com/conda/conda/pull/10552 at conda to introduce that but until then these seem to be the only two alternatives I can find.

**Review by beckermr — CHANGES_REQUESTED** [review]
Declaring this package noarch but then restricting to only linux makes no difference in terms of CI usage IIUIC. Why did you do that?

**Comment by BastianZim** [comment]
@beckermr Wouldn't it be rendered on all python versions and Linux platforms once it's a feedstock whereas a noarch package would only be rendered in one test?

**Comment by beckermr** [comment]
Ack you are right! Sorry!

**Comment by BastianZim** [comment]
No worries, thanks for merging! :)

**Pull request merged**
