### PR TITLE
Add et_xmlfile

### PR DESCRIPTION
**Pull request by curtisalexander**

### CODE REVIEW

**Comment by curtisalexander** [comment]
@jakirkham @mariusvniekerk As both of you helped me in the past...do you have suggestions on how to handle a missing `LICENSE` file?

Within the `tar.gz` file on [pypi](https://pypi.python.org/pypi/et_xmlfile) there is not any `LICENSE` (or `LICENCE`) file.  The package metadata on pypi notes that it is licensed under an MIT license.  This is consistent with the repo on [bitbucket](https://bitbucket.org/openpyxl/et_xmlfile/src).

**Comment by mariusvniekerk** [comment]
So typically the approach is make a pr to the source repo and get the license file added to the MANIFEST. 
Comment out the license file portion of the recipe and leave a comment referencing the pr you made to the source.

**Comment by synapticarbors** [comment]
You could also manually package the license file:

http://conda-forge.github.io/docs/meta.html#packaging-the-license-manually

**Comment by curtisalexander** [comment]
@mariusvniekerk Per your suggestion, I created a [PR](https://bitbucket.org/openpyxl/et_xmlfile/pull-requests/2) at the source repo to include the license file - `LICENCE.rst` - within `MANIFEST.in`.

@synapticarbors I'll follow your recommendation and include the `LICENCE.rst` for the time being so that I can get the package built and merged.

**Pull request merged**
