### PR TITLE
Add lftp

### PR DESCRIPTION
**Pull request by epruesse**
I tried to get this working on windows, but I'm missing some header files (curses.h or ncurses.h or terminfo.h) in the msys2 packages.

### CODE REVIEW

**Comment by epruesse** [comment]
@conda-forge/core This is ready I believe.

**Comment by epruesse** [comment]
@mingwandroid Can you tell me how to get `curses.h` using your `m2*-*` packages?

**Comment by mingwandroid** [comment]
You cannot mix GCC and MSVC easily like this I am afraid. You probably need to compile ncurses with MSVC if that possible. Also the m2- packages aren't native Windows, they are Cygwin-like, so if you did want to try you need to use m2w64- packages.

For some hints on interoperability between these toolchains you should look at my rstudio package in conda-recipes. Rpy2 is also off some interest as is theano. For theano, the recipe is in the tarball.

**Comment by epruesse** [comment]
@conda-forge/core Any chance for a review? This is a straight-forward pure-c tool.

(Windows deferred until there is a package providing ncurses header files)

**Comment by scopatz** [comment]
FWIW, Circle didn't seem to run on this PR.

**Comment by epruesse** [comment]
@scopatz Probably just the last round. It ran fine while I was trying to get windows to work, failing ultimately at the missing `[n]curses.h`. Thx!

**Pull request merged**
