### PR TITLE
Add the natasha, navec, slovnet, razdel, yargy, ipymarkup libraries

### PR DESCRIPTION
**Pull request by harri-pltr**
NB. These libraries don't currently support Windows. Future versions may, at which point this recipe will need to be updated.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by HarriBellThomas** [comment]
@conda-forge/staged-recipes Can we have a review?

**Comment by wolfv** [comment]
I wonder if you could use the new __unix metapackage, and create noarch packages. cc @conda-forge/core?

**Comment by harri-pltr** [comment]
@wolfv Do you have any documentation on `__unix`? I can only find references to it in the Conda changelog.

**Comment by mbargull** [comment]
> @wolfv Do you have any documentation on `__unix`? I can only find references to it in the Conda changelog.

A bit of information is in here: http://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=__osx#requiring-newer-macos-sdks

> I wonder if you could use the new __unix metapackage, and create noarch packages. cc @conda-forge/core?

No, we shouldn't rely on newly introduced virtual packages because the prerequisite for that is to have the user base running recent `conda` versions. We should add a `__conda`/`__package_spec`/something virtual package first, then wait X amount of time until the user base is updated and *then* we can rely on newer virtual packages.

What could be done today, is creating non-virtual packages like `_platform_unix`, `_platform_linux`, `_subdir_linux_64`, etc. and build those only for the appropriate platforms, e.g., have the aforementioned example packages explicitly *not* built on `win-64`.
(Solver messaging could/should be improved then, of course.)

**Comment by wolfv** [comment]
@mbargull so should we merge this PR then? :)

**Comment by harri-pltr** [comment]
@mbargull @wolfv +1 on this -- keen to get this in and used internally ASAP.

**Comment by harri-pltr** [comment]
@mbargull @wolfv Bump on this

**Comment by harri-pltr** [comment]
@conda-forge-admin, please ping team

**Pull request merged**
