### PR TITLE
ENH exit early if out of API requests

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by beckermr** [comment]
cc @jakirkham  for viz

**Comment by beckermr** [comment]
Let’s try it.

**Comment by jakirkham** [comment]
Looks like [it's working]( https://travis-ci.com/conda-forge/staged-recipes/builds/146089355#L830 ).

**Comment by beckermr** [comment]
Ohhh hmmmm. I am still seeing failures when we try to rekick Travis.

**Comment by beckermr** [comment]
Maybe we are running out of Travis requests. They allow only so many per hour for that endpoint.

**Comment by jakirkham** [comment]
Yeah I think they have a really low limit (like 5) IIIRC.

**Comment by beckermr** [comment]
Right. See the issue I made on moving to circle for more discussion.

**Comment by jakirkham** [comment]
Yeah already there 😉

FWIW these things are cyclical ( https://github.com/conda-forge/staged-recipes/issues/916 ) 😄

**Comment by beckermr** [comment]
Of course! I have zero pretense that I am original in basically anything I do. :) I’m mostly just of the opinion that staged-recipes is broken most of the time now, so it probably makes sense to invest more into it. It may not of in the past of course.

**Comment by jakirkham** [comment]
Yep no objections to fixing things. Just thought you might find that an interesting piece of history 😉

**Pull request merged**
