### PR TITLE
Added dliswriter package

### PR DESCRIPTION
**Pull request by the-mysh**
`dliswriter` 1.0.1, first contribution

### CODE REVIEW

**Comment by the-mysh** [comment]
Confirming I'm one of the maintainers

**Comment by nup002** [comment]
Confirming I'm one of the maintainers

**Comment by nup002** [comment]
Confirming I'm one of the maintainers

**Comment by the-mysh** [comment]
@conda-forge-admin, please ping team

**Comment by the-mysh** [comment]
@conda-forge/help-python, recipe ready for your review!

**Pull request merged**
