### PR TITLE
add warcio

### PR DESCRIPTION
**Pull request by hadim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hadim** [comment]
@wolfv @beckermr I got this error:

```yaml
Error: 
  × Parsing: an unspecified error occurred.
    ╭─[23:7]
 22 │   host:
 23 │     - python ${{ python_min }}
    ·       ────────────┬───────────
    ·                   ╰── This match spec is ambiguous. Do you mean `python ==3.9` or `python 3.9.*`?
 24 │     - pip
    ╰────
```

Are there new guidelines for `python_min` or is it a bug from the latest rattler-build?

**Comment by synapticarbors** [comment]
> @wolfv @beckermr I got this error:
> 
> ```yaml
> Error: 
>   × Parsing: an unspecified error occurred.
>     ╭─[23:7]
>  22 │   host:
>  23 │     - python ${{ python_min }}
>     ·       ────────────┬───────────
>     ·                   ╰── This match spec is ambiguous. Do you mean `python ==3.9` or `python 3.9.*`?
>  24 │     - pip
>     ╰────
> ```
> 
> Are there new guidelines for `python_min` or is it a bug from the latest rattler-build?

This is the first time I've seen this with the v1 recipes. I thought `python 3.9` is the same as `python 3.9.*`

**Comment by wolfv** [comment]
We're inter interpreting 3.9 as 3.9.0 with rattler and thus the warning to resolve the ambiguity.

Variants automatically get a .* added, so they are fine :)

**Comment by wolfv** [comment]
Here is some discussion about this change in 0.32: https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/rattler-build.20.22strict.22.20matchspec.20parsing/near/488975665

**Comment by hadim** [comment]
@conda-forge/help-python ready for review

**Pull request merged**
