### PR TITLE
Add conda recipe for hydrotrend.

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds a conda recipe for the *HydroTrend* model,

> Kettner, Albert J., Syvitski, James P.M., 2008. HydroTrend v.3.0: A climate-driven hydrological transport model that simulates discharge and sediment load leaving a river system. Computers & Geosciences, 34, 1170-1183. 10.1016/j.cageo.2008.02.008

*HydroTrend* v.3.0 is a climate-driven hydrological water balance and transport model that simulates water discharge and sediment load at a river outlet.

### CODE REVIEW

**Comment by mcflugen** [comment]
OK. This should be good to go now. The Windows build isn't complete yet but we're skipping it anyway.

**Comment by marcelotrevisani** [comment]
It is not using the right compiler, you can check this in the CI, I will do some modifications if you don't mind which may fix it
```
-- Check for working C compiler: /opt/rh/devtoolset-2/root/usr/bin/gcc
-- Check for working C compiler: /opt/rh/devtoolset-2/root/usr/bin/gcc -- works
```

**Comment by mariusvniekerk** [comment]
So I don't think we have a way to use anaconda compilers in staged recipes yet

**Comment by mcflugen** [comment]
If it is a problem with *staged-recipes*, is there anything to be done right now or can it just be merged? I'm surprised this hasn't come up as an issue before. There must be lots of packages that use the anaconda compilers.

**Comment by mcflugen** [comment]
@marcelotrevisani, @mariusvniekerk It seems as though the anaconda compilers were not being used because they were never installed. The `compiler()` function was either being ignored (even though *conda-build* 3 is being used) or returning something other than the name of the appropriate anaconda compiler. If I specify the compilers by their real name (i.e. `gcc_linux-64`, `clang_osx-64
`, etc.), they're installed and things appear to be built with the anaconda compilers.

This doesn't seem like a great solution but it does seem to work. What do you all think? Any ideas about why the jinja `compiler` function might not be working as expected?

**Comment by marcelotrevisani** [comment]
So, I want to say sorry that I mixed up the migration to ``gcc 7`` in ``conda-forge`` with this recipe. @mariusvniekerk is right as usual :)

I will merge that as soon as the build in linux platform pass.

**Comment by mcflugen** [comment]
@marcelotrevisani The linux build errored out with an HTTP error. Could you please give it a kick to restart the build?

**Comment by marcelotrevisani** [comment]
Again, sorry for the confusion and thanks to add this in ``conda-forge``! :tada:

**Pull request merged**
