### PR TITLE
pyproj 1.9.5

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @pelson

### CODE REVIEW

**Comment by ocefpaf** [comment]
... and Windows is failing with the new proj.4 source :unamused: 
I will take a look at this tomorrow.

**Comment by ocefpaf** [comment]
Good to go.  I removed the patch and updated to the latest release.

**Comment by pelson** [comment]
Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
Thanks @pelson for merging.

(And https://github.com/ioos/conda-recipes/pull/691 to ensure I will keep conda-forge as the canonical source for our `pyproj` recipe.)

**Pull request merged**
