### PR TITLE
add openfoam

### PR DESCRIPTION
**Pull request by ngam**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dopplershift** [comment]
Please don't modify any files outside your recipe directory.

**Comment by ngam** [comment]
@dopplershift hi, I needed to do that because I want to use centos7 for this recipe. I couldn't get it to work and so I copied  the procedure from another feedstock and it works. How can I use centos7 in a staged-recipe like this without editing outside the recipe directory? The conda-forge knowledge base says to edit a file in root and I wanted to rerender... Or is it not possible?

Also, since you're here (if interested), this is significantly more difficult than I anticipated and so I need help:
- this takes more than 6 hours to finish and I am still struggling to figure out a way to leave it in a state of a regular package --- the key point is to whether or not to source a startup file and how to do that
- I am trying to get rid of the ThirdParty optional pieces and use conda-forge packages instead of them, but that's not going as smoothly as I want; in particular, I am not sure how to better automate the build.sh file
- I also need to reduce the overhead (both build time and eventual size) of this package and I am not sure how best to pursue that

I can build it successfully and the tests in build.sh pass, but then usually something happens when it is finalizing everything. For example, I get a lot of warnings about binaries having no headers and asking whether or not this is repackaging binaries.

**Comment by dopplershift** [comment]
To add centOS 7 to a staged-recipe build, follow those instructions in the knowledge base, but you should only put:
```yaml
os_version:
  linux_64: cos7
```
into `conda-forge.yml` *inside* your recipe directory. `staged-recipes` is the repository for every package added to conda-forge, and any changes you make to files outside your recipe will affect every build that comes after. No re-rendering is needed for staged-recipes, as the infrastructure will take care of "rendering" your recipe as part of the build process.

At any rate, please remove the commits modifying files outside your recipe.

As far as dealing with build times and other issues with the built packages, maybe someone from @conda-forge/staged-recipes can help?

**Comment by ngam** [comment]
@dopplershift thanks a lot!! 

> At any rate, please remove the commits modifying files outside your recipe.

I will start a new pr from scratch once I figure out how to bring down the build time to under 6 hours.

Is there a mechanism by which one can have the effect of sourcing a file once the build is done? So that when someone adds this package to their env, it can have the effect of sourcing those files from within the installed package? I suspect it won't be enough to just `source <file>` at the end of the build.sh script, right?

**Comment by dopplershift** [comment]
If necessary, you can add an [activate script](https://docs.conda.io/projects/conda-build/en/latest/resources/activate-scripts.html).

**Comment by ngam** [comment]
Thank you 🥇

**Comment by ngam** [comment]
Fyi, legit pr is here #17068

**Comment by ngam** [comment]
In case someone from @conda-forge/staged-recipes sees this, please follow here #17068 

I think everything is almost good, but some cleanup and speedup is needed. My goals are:
1. complete correct build for only linux64 (including activation)
2. Then need to figure out ways to build for win and macos (will likely require extensive patching)

**Comment by ngam** [comment]
Closing!

**Pull request closed without merging**
