### PR TITLE
Added pelican-bibliography.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by moorepants** [comment]
I need to delete the pyproject.toml file for this windows build also.

**Comment by moorepants** [comment]
@conda-forge/help-python this is ready for review. I couldn't figure out how to handle the pyproject.toml file (as usual!). I'll convert this to a noarch build once the feedstock is created.

**Review by carterbox — CHANGES_REQUESTED** [review]
This project uses [both `poetry` and `setuptools`](https://github.com/micahjsmith/pelican-bibliography/blob/master/pyproject.toml#L80) in its build system. Did you try adding `poetry` to the host section of the recipe?

**Comment by moorepants** [comment]
No, I am not really familiar with poetry. I thought it was an end user's optional tool for installing and managing virtual environments. I've always thought that `python setup.py install` is all that is needed for installing Python packages and thus `pip install` works too because it uses setup.py. Things like venv, conda, etc. are supposed to be required for installed a package, right?

**Comment by moorepants** [comment]
These are relevant issues:

https://github.com/conda-forge/conda-forge.github.io/issues/1174

https://github.com/conda-forge/conda-forge.github.io/pull/1540

that explain the complications of the pyproject.toml file (which maybe that is tied to poetry?)

**Comment by moorepants** [comment]
Another related issue, is that the dependency pins in that toml files are very restrictive and if used as is, would make this package difficult to install alongside a large number of packages in a conda environment. I've elected to not include upper bounds on the pins for the conda package to ease the work of the conda sat solver.

**Comment by carterbox** [comment]
OK, but if you [look at the build logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=494062&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b&l=1619), it tells you that it needs poetry.

> I've always thought that python setup.py install is all that is needed for installing Python packages and thus pip install works too because it uses setup.py.

Yes, but as you noted in the linked issues, the python ecosystem is moving away from `setup.py` because of various reasons such as not being able to define build dependencies from inside `setup.py`.

In the PR you linked, the preferred method for dealing with this problem is adding `--use-deprecated=out-of-tree-build` to pip.

```
script: {{ PYTHON }} -m pip install . -vv --use-deprecated=out-of-tree-build
```

Which you did try, but you didn't add poetry to the host requirements. So please try the out of tree build whilst also installing poetry.

**Comment by moorepants** [comment]
Sure, I can try more things. I've tried lots of things over the past year+ and haven't landed on a consistently functioning solution other than deleting the toml files.

**Comment by moorepants** [comment]
The windows build failed with:
```
Verifying transaction: ...working... failed
Traceback (most recent call last):
  File "D:\a\1\s\.ci_support\build_all.py", line 205, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "C:\Miniconda\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 321, in execute_actions
    execute_instructions(plan, index, verbose)
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 533, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 73, in UNLINKLINKTRANSACTION_CMD
    unlink_link_transaction.execute()
  File "C:\Miniconda\lib\site-packages\conda\core\link.py", line 277, in execute
    self.verify()
  File "C:\Miniconda\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda\lib\site-packages\conda\core\link.py", line 241, in verify
    maybe_raise(CondaMultiError(exceptions), context)
  File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 1022, in maybe_raise
    raise error
conda.CondaMultiError: The package for pelican located at C:\Miniconda\pkgs\pelican-4.7.2-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2010/d�cembre/02/this-is-a-super-article/index.html'
specified in the package manifest cannot be found.

The package for pelican located at C:\Miniconda\pkgs\pelican-4.7.2-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2011/f�vrier/17/article-1/index.html'
specified in the package manifest cannot be found.

The package for pelican located at C:\Miniconda\pkgs\pelican-4.7.2-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2011/f�vrier/17/article-2/index.html'
specified in the package manifest cannot be found.

The package for pelican located at C:\Miniconda\pkgs\pelican-4.7.2-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2011/f�vrier/17/article-3/index.html'
specified in the package manifest cannot be found.

The package for pelican located at C:\Miniconda\pkgs\pelican-4.7.2-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2012/f�vrier/29/second-article/index.html'
specified in the package manifest cannot be found.```

Maybe there's a unicode character in a path?

**Comment by carterbox** [comment]
On the bright side the unix builds succeeded, so we're kinda just back where we were just with a different error. 😄

**Comment by carterbox** [comment]
The other bright side is that this error from the Windows build is coming from trying to install @conda-forge/pelican and not coming from the package in this recipe.

**Comment by carterbox** [comment]
Related: https://github.com/conda/conda-build/issues/4043

**Comment by carterbox** [comment]
@moorepants, I believe this situation is summarized as "the package does not install on windows because a dependency is broken", so I will merge this PR and you will have to decide if you want to chase down the solution for pelican's broken install on Windows.

**Pull request merged**
