### PR TITLE
add sbcl for linux [ROS]

### PR DESCRIPTION
**Pull request by wolfv**
ROS has some light dependency on SBCL, the steel bank common lisp compiler. 

I couldn't find a package on conda/conda-forge. I believe this package works (for linux), however, it *does not* bootstrap the lisp compiler. It downloads a precompiled binary from the official website and installs it into the conda environment. 

Not sure if conda-forge is willing to accept this? 

Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vend other packages
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xhochy** [comment]
@wolfv Have you checked that this binary repackaging works with the conda-forge toolchain in general?

**Comment by xhochy** [comment]
(we can merge on red win+osx builds here, the feedstock will be fine).

**Comment by wolfv** [comment]
@xhochy i checked that this way of installing works locally on a linux machine. 

The build output says:

```
WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libc.so.6
WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libdl.so.2
WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libpthread.so.0
WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libm.so.6
```

Do I need to add any libraries to host/run for this to fix up library links better? Or is it fine to link against the system libs for this?

SBCL is not super-urgent. I am happy to wait with this to make sure that everyone is comfortable with this way of shipping.

**Comment by xhochy** [comment]
> @xhochy i checked that this way of installing works locally on a linux machine.
> 
> The build output says:
> 
> ```
> WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libc.so.6
> WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libdl.so.2
> WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libpthread.so.0
> WARNING (sbcl,bin/sbcl): did not find - or even know where to look for: /lib64/libm.so.6
> ```
> 
> Do I need to add any libraries to host/run for this to fix up library links better? Or is it fine to link against the system libs for this?
> 
> SBCL is not super-urgent. I am happy to wait with this to make sure that everyone is comfortable with this way of shipping.

No, I think these should be fine.

**Pull request merged**
