### PR TITLE
Pass MAKEFLAGS for circleci builds

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
Let's wait on this for some discussion. Also, we need a new release of `conda-build` to do this.

**Comment by msarahan** [comment]
It will not hurt anything to merge this now.  It just won't work until we're actually employing the new conda build.  +1 to merge from me.  This will "magically" speed up builds when we roll out the new conda build.  The bummer is that Linux is already our fastest platform. =(

**Comment by msarahan** [comment]
@jschueller is there any chance that anyone sets MAKEFLAGS elsewhere and either clobbers this value, or is clobbered by this value?  Is it of value to have

    MAKEFLAGS="${MAKEFLAGS} -j2"

instead?

**Comment by jschueller** [comment]
@msarahan, I just checked it doesn't clobber anything.

**Comment by jschueller** [comment]
@msarahan, @jakirkham Now that conda-build 1.20.2 includes the MAKEFLAGS change, maybe this could be merged ?

**Comment by msarahan** [comment]
When you say "I just checked" - can you say how/what you checked?  This is one of those subtle things that could really confuse someone someday, and I'd feel much better if you changed it to my suggested value above, maintaining any potential prior setting.  IMHO, people should do this by default, only (potentially) clobbering other values as a conscious, commented choice.

**Comment by jschueller** [comment]
@msarahan The circleci env is not using it.

**Comment by msarahan** [comment]
OK, but what you are saying is essentially "it doesn't use it now, and I don't care if it uses it in the future."  What I am saying is "please future-proof here."

Am I missing something?  Is there a downside to my suggestion?

**Comment by jschueller** [comment]
@msarahan I guess I'd rather set ```MAKEFLAGS="-j2 ${MAKEFLAGS}"``` instead of appending.

**Comment by msarahan** [comment]
Cool - that's totally fine with me too.  Just so long as we aren't discarding any potential MAKEFLAGS.  Priority is a different set of bugs - and one that isn't likely to matter nearly as much here.

Thanks!

**Comment by jschueller** [comment]
@msarahan, done

**Comment by msarahan** [comment]
Thanks @jschueller!  And thanks for bearing with me.

**Comment by jakirkham** [comment]
Thanks for cleaning this up and getting this in guys. It seems like a nice addition.

**Comment by jakirkham** [comment]
If you haven't already, could you please submit a similar change to [`conda-smithy`]( https://github.com/conda-forge/conda-smithy ), @jschueller? If you have, an xref here would be nice.

**Comment by jschueller** [comment]
@jakirkham I have no clue what you're talking about

**Comment by jakirkham** [comment]
`conda-smithy` is the tool we use to generate all the feedstocks here. So, while it is nice to have this in `staged-recipes`, that only helps recipes while we test them. That feature is then gone when they become feedstocks currently. To fix that, I would recommend adding a PR that changes this [file]( https://github.com/conda-forge/conda-smithy/blob/9cd7e42428c4621039366b023a19c1eba5214954/conda_smithy/templates/run_docker_build.tmpl ) to include the same logic.

**Comment by jschueller** [comment]
@jakirkham, ok I understand, see https://github.com/conda-forge/conda-smithy/pull/174

**Pull request merged**
