### PR TITLE
add genanki 0.10.1

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
  - [x] upstream PR created to request license file in future releases
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/staged-recipes @conda-forge/help-python ready for review!

**Comment by bollwyvl** [comment]
Thanks! A little terrified of actually trying to build anki (bazel AND
python AND rust AND protobuf AND qt) but this is a nice starting point...

**Comment by xhochy** [comment]
I have a lot of fun with bazel recently, feel free to ask for help on a PR. https://github.com/conda-forge/grpc_java_plugin-feedstock/tree/master/recipe is a simple but mighty example of what you need as basics to build bazel things with the conda-forge compilers. I plan to do more work with bazel in the next days on other feedstock, so this will evolve a bit,

**Comment by bollwyvl** [comment]
😋 looks ripe for cargo culting. Anki is in that "app" category where I'd
like to have it to test with, but looks complex enough that I don't want to
be on the support hook... Unsurprisingly, I'm looking to integrate parts of
it into the Jupyter.

**Pull request merged**
