### PR TITLE
initial commit for ipyvolume

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by jjhelmus** [comment]
LGTM, thanks @maartenbreddels, merging.

**Comment by maartenbreddels** [comment]
👍  thx

**Comment by maartenbreddels** [comment]
something stuck in the pipes? I didn't get an email that about it landing in the feedstock

**Comment by jjhelmus** [comment]
The [feedstock](https://github.com/conda-forge/ipyvolume-feedstock) seems to have been created fine, just took a bit longer given the backlog on Travis CI.

**Comment by maartenbreddels** [comment]
Yes, I saw it, thx for the notice!

**Pull request merged**
