### PR TITLE
Add intake-astro

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by martindurant** [comment]
@mariusvniekerk , this PR merger did not seem to generate the feedstock. Is there any way to retrigger?

**Comment by martindurant** [comment]
@beckermr are you able to re-execute this merge, because the bot did not create a feedstock, for some reason.

**Comment by beckermr** [comment]
Hmmmmmm. I don't know how to do that. Maybe copy paste to a new PR? We could find the merge commit and retrigger the CI too, but a new PR seems easier.

**Comment by martindurant** [comment]
https://github.com/conda-forge/staged-recipes/pull/7761

**Comment by beckermr** [comment]
@conda-forge/core Can you look into this feedstock? We cannot seem to find the repo on github and the package doesn't seem to exist, but when we made another PR to add the package, the linter is complaining that it does exist.

**Comment by scopatz** [comment]
Just ignore the linter

**Comment by beckermr** [comment]
Thanks @scopatz !

**Comment by scopatz** [comment]
Obviously not always but in this case, I think it is safe :wink:

**Pull request merged**
