### PR TITLE
Add marshmallow-enum

### PR DESCRIPTION
**Pull request by xylar**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xylar** [comment]
@justanr, please let me know if you would like to be a maintainer of the conda-forge recipe for marshmallow-enum.

**Comment by xylar** [comment]
@conda-forge/help-python, this is ready for review.

**Comment by justanr** [comment]
@xylar I don't use forge so I probably wouldn't be the best to maintain this, thanks for the heads up though.

**Comment by xylar** [comment]
@justanr, no worries.  Just wanted to make sure.

**Pull request merged**
