### PR TITLE
Revert `conda-build` 1.20.0 downgrade to Python 3.4 64-bit AppVeyor

### PR DESCRIPTION
**Pull request by jakirkham**
Reverts this PR ( https://github.com/conda-forge/staged-recipes/pull/455 ) and this PR ( https://github.com/conda-forge/staged-recipes/pull/452 ) that came before it.

This was a workaround for `conda-build` 1.20.1 on AppVeyor Python 3.4 64-bit builds due to this issue ( https://github.com/conda/conda-build/issues/895 ), which was discussed in this issue ( https://github.com/conda-forge/staged-recipes/issues/448 ) at some length by various affected parties. This is believed to be fixed in `conda-build` 1.20.2; so, we are unpinning it here. A similar change has been proposed to `conda-smithy` ( https://github.com/conda-forge/conda-smithy/pull/170 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
This change is required for `curl` ( https://github.com/conda-forge/staged-recipes/pull/378 ).

**Comment by jakirkham** [comment]
We might want to hold off on this as it is going to cause problems when pinning the Windows' `python` test requirement. See this issue ( https://github.com/conda/conda-build/issues/955 ).

Alternatively, we can go ahead with this and temporarily use a different strategy like the one with selectors that @msarahan and myself were trying out as shown below. I had added this to the wiki back when the linter had trouble with this syntax ( `python {{ environ['PY_VER'] + '*' }}  # [win]` ).

```
test:
    requires:
        - python 2.7.*  # [win and py27]
        - python 3.4.*  # [win and py34]
        - python 3.5.*  # [win and py35]
```

The trick here is we absolutely need `conda-build` 1.20.2 for some cases like `curl`, which we have been desperate to get in here, or `icu`, which is blocking `qt5` and is desirable for `boost`. However, it is going to cause problems with the currently used selection strategy. IMHO upgrading to 1.20.2 and using the slightly more verbose syntax is the least of the two evils.

**Comment by ocefpaf** [comment]
What about @msarahan suggestion to use

    {{ PY_VER ~ "*" }}

**Comment by jakirkham** [comment]
If it works, people could use that too. I have not tried that; whereas, the selector syntax above I know works from experience.

**Comment by jakirkham** [comment]
The other reason I had picked the syntax above is I know that people (include myself) have had to sit on old `conda-build` versions for awhile due to bugs just like this one. As a result, I tried to pick syntax that while it may appear more verbose is supported by much older versions of `conda-build`.

I forget exactly when `conda-build` started injecting variables from `environ` directly into the context. It might have been done by a mixture of work by @stuarteberg and myself that culminated in this PR ( https://github.com/conda/conda-build/pull/694 ). Though I can't recall if we were merely fixing that behavior so that it would work again or if we actually added it there. If that change did add this variable injection functionality, then it requires a fairly recent version of `conda-build` namely 1.19.0 or later. The selector syntax has been around much longer by comparison at least since 1.9.0 if not longer. Though the complete list of selectors that we know exists by 1.16.0 IIRC.

**Comment by jakirkham** [comment]
Sounds like there will be a new `conda-build` release soon so let's hold on this.

**Pull request closed without merging**
