### PR TITLE
Recipes for pyro-api and pyro-ppl

### PR DESCRIPTION
**Pull request by jamestwebber**
Submitting recipes to add [Pyro](pyro.ai) to conda-forge, which will make life easier for some downstream projects. There are two recipes: `pyro-ppl` is the main package while `pyro-api` is a base package used to share common code with other projects.

Both are pure Python* so I included `noarch: python` in the recipes.

\* `pyro-ppl` technically contains C++ but it is imported at runtime by PyTorch rather than compiled on installation.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] ~If static libraries are linked in, the license of the static library is packaged.~ N/A
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jamestwebber** [comment]
@conda-forge-admin, please ping team

**Comment by jamestwebber** [comment]
One note that I don't know how to fix: the proper/supported source for `pytorch` is from their channel (e.g. `conda install pytorch -c pytorch`). That might be why the windows build is failing?

**Comment by jamestwebber** [comment]
`pytorch` just released a new version (1.8.0) and `pyro` tries to match releases, so they released as well (1.6.0).

I was able to build the new release locally, but the conda-forge channel doesn't have pytorch 1.8.0 yet so I didn't push the changes here.

Also, I looked at the windows errors and I have no idea what it's complaining about. It seems to have some issue in the dependency solver but I don't know what it is.

**Comment by chrisburr** [comment]
Yeah, apparently we're missing pytorch builds for Windows: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32

As this is `noarch: python` it doesn't matter as we'll only build on Linux in the feedstock.

**Pull request merged**
