### PR TITLE
Add r-uwot

### PR DESCRIPTION
**Pull request by apcamargo**
This recipe was created with `conda_r_skeleton_helper`.

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dbast** [comment]
Requires r-dqrng which seems to require r-sitmo to be added.

**Comment by apcamargo** [comment]
@conda-forge-admin , please rerender

**Comment by apcamargo** [comment]
@conda-forge-admin, please rerender

**Comment by apcamargo** [comment]
Pinging @conda-forge/core 

This recipe is finally ready for merge.

**Comment by dbast** [comment]
there seems to be a copy & paste error in the summary text. will update it.

**Comment by dbast** [comment]
The Linter is now also happy :)

**Pull request merged**
