### PR TITLE
Adds CoreUI Dash Components

### PR DESCRIPTION
**Pull request by dgasmith**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

This is a bit of an odd package as [Dash](https://plot.ly/dash/) stores the JavaScript required inside the package itself. In some ways this could be viewed as vendoring another package as the full [`CoreUI`](https://github.com/coreui/coreui) JS is distributed. That file of course has its full license MIT license retained in the file. I don't think this is an issue, but wanted to bring it up out of an abundance of caution.

This is analogous to the `dash-bootstrap-components` package.

@lnaden Can you be a co-maintainer on this package as well with your MolSSI hat on so that we have two.

@conda-forge/help-python

### CODE REVIEW

**Comment by Lnaden** [comment]
Yes, I can agree to be a maintainer

**Comment by dgasmith** [comment]
Hmm, URL looks good? All failures suggest it isn't random.

```
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING conda_build.source:download_to_cache(84): Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/d/dash-coreui-components/dash-coreui-components-0.1.0.tar.gz>
```

**Comment by dgasmith** [comment]
@conda-forge/help-python The link `https://pypi.io/packages/source/d/dash-coreui-components/dash-coreui-components-0.0.1.tar.gz` appears not to work for some reason where the PyPI release is here `https://pypi.org/project/dash-coreui-components/0.1.0/`.

@loriab Any ideas here too?

**Comment by isuruf** [comment]
https://pypi.io/packages/source/d/dash-coreui-components/dash_coreui_components-0.0.1.tar.gz

**Comment by dgasmith** [comment]
@isuruf Thanks, how does this work for projects like [dash-boostrap-components](https://github.com/conda-forge/dash-bootstrap-components-feedstock/blob/master/recipe/meta.yaml) in this case?

**Comment by dgasmith** [comment]
@conda-forge/staged-recipes Seems good, ready to merge.

**Pull request merged**
