### PR TITLE
Add pyenchant

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@jakirkham : Do I need to build enchant on conda-forge to make it work?

**Comment by jakirkham** [comment]
Is there a PR for it already? If not, yes, it will need to be added.

**Comment by cshaley** [comment]
Enchant is a C/C++ library with one external dependency (glib) and should be buildable on any C/C++ compiler.  It looks like it can be installed via brew on mac os (brew install enchant) or apt-get on linux.  [But it will not build for windows64](https://github.com/rfk/pyenchant/issues/42).  There is a compiled installer for win32 on [pypi](https://pypi.python.org/pypi/pyenchant/) that should theoretically be wholly self-contained.

@jakirkham Are there any good examples of feedstocks for a C/C++ library we can use to work off of?  Latest release of the C/C++ package linked to from [here](https://github.com/AbiWord/enchant/releases).  
It looks like building the package requires glib-2.0 and gmodule-2.0, and then configure, make, and make install commands.  I'm guessing then that we would need to package glib and gmodule as well?

**Comment by jakirkham** [comment]
So we have `glib` (though not 2.0 if that version is of particular importance). Can PR to the feedstock to get an older version on a legacy branch. Though we don't have `gmodule`. Maybe @pkgw has some thoughts on a recipe for `gmodule`. In any event, `gmodule` would have to be added.

There are lots of C/C++ recipes in conda-forge to look at. Maybe [`ncurses`]( https://github.com/conda-forge/ncurses-feedstock ) would be a good one to look at. For Windows, we like to use CMake if we can as it makes it easier to build and install. Sometimes the MinGW compilers can be used, but these have some rough edges that one needs to be aware of when combined with Visual Studio compiled libraries (like when used with Python).

**Comment by cshaley** [comment]
It looks like glib-2.0 is of particular importance.  I tried configuring the build on a linux box with glib installed from conda forge, but enchant is looking for "glib-2.0" and "gmodule-2.0".
`No package 'glib-2.0' found
No package 'gmodule-2.0' found
`
So it looks like we'll have to build a separate package for glib-2.0.

**Pull request closed without merging**
