### PR TITLE
Add intel-compute-runtime

### PR DESCRIPTION
**Pull request by isuruf**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vend other packages
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/staged-recipes, ready for review.

@inducer, would you like to be a maintainer?

**Comment by chrisburr** [comment]
Looks good to me. I'll merge and let the maintainer field be updated in the feedstock if needed.

Thank you once again @isuruf! 🍰

**Comment by inducer** [comment]
I wouldn't mind, but I can't promise I'll have much time to do maintenance. :)

**Comment by isuruf** [comment]
Thanks. I'll add you in the feedstock.

Btw, I checked on a Coffee Lake machine and Intel works now.

```
Choose platform:
[0] <pyopencl.Platform 'Oclgrind' at 0x5568b220ce80>
[1] <pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x5568b2001580>
[2] <pyopencl.Platform 'Portable Computing Language' at 0x7f92f67bb020>
```

**Comment by inducer** [comment]
Thanks for working on this! I've always been curious about this runtime. Installed it on my new Ice Lake thing, and it seems to work just fine. Even passes the PyOpenCL test suite, modulo some complaints about enabling fp64.

**Pull request merged**
