### PR TITLE
add caproto

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This is a noarch package (curio doesn't have a windows build though).

**Comment by ocefpaf** [comment]
LGTM waiting on the CircleCI to merge this.

**Comment by CJ-Wright** [comment]
Thank you! (I guess I forgot to edit some of the deps from conda skeleton :sheep: )

**Comment by CJ-Wright** [comment]
Thank you very much!

**Comment by ocefpaf** [comment]
My pleasure!

**Pull request merged**
