### PR TITLE
Add fimex

### PR DESCRIPTION
**Pull request by alexander-buerger-met-no**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
  Static libraries are built. They use only packages from conda-forge that are run requirements (for the dynamic libraries).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
       They both also posted a comment here, in addition to the email they had previously sent.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by alexander-buerger-met-no** [comment]
@conda-forge/staged-recipes This should be ready for review/merge.

**Comment by heikoklein** [comment]
Hi, I am happy to be listed as maintainer for those recipes.

**Comment by audunc** [comment]
Hi, I am happy to be listed as maintainer for those recipes

**Comment by alexander-buerger-met-no** [comment]
@conda-forge/staged-recipes The PR comment is updated, the PR should be ready for review/merge.

**Comment by alexander-buerger-met-no** [comment]
Thanks for merging.

The PR includes three packages:
- mi-cpptest was built successfully after the merge
- mi-programoptions did not build in CI as it was missing mi-cpptest when the build was started
- fimex did not build in CI as it was missing both mi-cpptest and mi-programoptions when the build was started
The PR build sorted these dependencies out by itself, but after the merge it does not work.

How can I trigger a rebuild attempt, first for mi-programoptions, and, once that is finished, for fimex? I do not understand the [docs](https://conda-forge.org/docs/maintainer/infrastructure.html#ci-build-services), I do not see anything with "GitHub Checks" in the [mi-programoptions feedstock](https://github.com/conda-forge/mi-programoptions-feedstock).

**Comment by ocefpaf** [comment]
> How can I trigger a rebuild attempt, first for mi-programoptions, and, once that is finished, for fimex? I do not understand the [docs](https://conda-forge.org/docs/maintainer/infrastructure.html#ci-build-services), I do not see anything with "GitHub Checks" in the [mi-programoptions feedstock](https://github.com/conda-forge/mi-programoptions-feedstock).

You'll have to send an empty commit to trigger the packages that required the dependency in the race condition.

**Comment by alexander-buerger-met-no** [comment]
@ocefpaf 
I have problems to install basemap and fimex into the same conda environment. The same applies for gdal, but gdal has many more dependencies, so I was experimenting with basemap.

The dependency resolver says something that I do not understand when I try `conda create -n compat fimex basemap`, similarly incomprehensible with `gdal`.

`conda search basemap --info` says that basemap for python 3.8 and numpy 1.16 depends on proj `7.1.1,<7.1.2.0a0` while fimex depends on proj `7.2.1,<7.2.2.0a0`. I am not sure where this strict constraint on proj comes from. It is not in the fimex recipe.

How can I add fimex builds that are installable together with basemap, gdal, …? And with numpy 1.20 and python 3.9?

**Pull request merged**
