### PR TITLE
Adding KFP Pipeline Spec

### PR DESCRIPTION
**Pull request by tanguycdls**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by akchinSTC** [comment]
@tanguycdls - Hello, just wondering if there is any movement on getting this PR in? We currently have a feedstock dependent on the kfp package with `pip check` enabled. When installing the latest kfp (1.1.2), kfp-pipeline-spec is not required in the conda requirements but IS required in the pypi version resulting in the failed `pip check`. Would be happy to help or assist in anyway.

**Comment by tanguycdls** [comment]
> @tanguycdls - Hello, just wondering if there is any movement on getting this PR in? We currently have a feedstock dependent on the kfp package with `pip check` enabled. When installing the latest kfp (1.1.2), kfp-pipeline-spec is not required in the conda requirements but IS required in the pypi version resulting in the failed `pip check`. Would be happy to help or assist in anyway.

Hello Yes indeed we have same issue with kfp pipelines ! I started doing the recipe but it's not that easy the setup.py is very custom and they dont provide a tar for those files only
:https://github.com/kubeflow/pipelines/blob/master/api/v2alpha1/python/setup.py. 

so i think we would need to download the full repo and execute the pip install in the good folder but I dont have the bandwidth to do it and test soon... :(

**Comment by ckadner** [comment]
@maximerihouey @tanguycdls -- could we revive this PR to add a new feedstock recipe for `kfp-pipeline-spec`?

We depend on the [`kfp-feedstock` `v1.3.0`](https://github.com/conda-forge/kfp-feedstock/pull/40) to be merged in order to get the latest [`kfp-tekton` recipe](https://github.com/conda-forge/kfp-tekton-feedstock/pull/1/) merged

**Comment by tanguycdls** [comment]
> @maximerihouey @tanguycdls -- could we revive this PR to add a new feedstock recipe for `kfp-pipeline-spec`?
> 
> We depend on the [`kfp-feedstock` `v1.3.0`](https://github.com/conda-forge/kfp-feedstock/pull/40) to be merged in order to get the latest [`kfp-tekton` recipe](https://github.com/conda-forge/kfp-tekton-feedstock/pull/1/) merged

Hello, @maximerihouey added you as a maintener for kfp pipeline.
For kfp pipeline spec as explained above I'm not really sure on how to proceed to add it to conda forge. 
The setup.py of the package is here: 
https://github.com/kubeflow/pipelines/blob/fcb2a68452b011847eed6d57bd8daec2096ac559/api/v2alpha1/python/setup.py
but it uses Protobuf to compile the file. 

I dont know if your option would work for that pr to move on I dont know if someone from Conda forge could give us a hint on how to do so ?
ping @conda-forge/help-python . 

Thank you by advance

**Comment by chensun** [comment]
I'm giving this another shot via https://github.com/conda-forge/staged-recipes/pull/16307

**Comment by chensun** [comment]
I'm giving this another shot via https://github.com/conda-forge/staged-recipes/pull/13409

**Pull request closed without merging**
