### PR TITLE
add python-uv

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

References:
- fixes https://github.com/conda-forge/uv-feedstock/issues/42
 - raised in https://github.com/conda-forge/staged-recipes/pull/28330

This is the <10 files of the python side of the house of `uv`, which (at least presently) have no direct bindings to the `rust`-built binary provided by `uv`. It uses some patches to: 
- replace the `maturin` backend in `pyproject.toml` with `setuptools`
- short-circuit `find_uv_bin` with the known paths populated by `uv` in `$PREFIX/bin/uv` or `%PREFIX%\Library\bin\uv.exe` 

with a dependency on `uv {{ version }}.*` to provide the actual CLI.

This allows us to:
- continue to offer a `uv` that _doesn't_ require `python`
- appease `pip check`
- enable the PEP517 build backend (currently gated behind `UV_PREVIEW`) 
- NOT do a full `py x os x arch` build on `uv-feedstock`

Notes:

I couldn't find a way to do one a singleton, proper `noarch: python` build over on `uv-feedstock` (it always ended up doing a matrix).

This would at least allow us to start shipping, even if meant there was a delay between the availability of `uv` (the `rust` CLI), which takes a while to build,  and `python-uv`. But the tight pin should keep everything working smoothly.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/help-python @conda-forge/uv ready for review

**Comment by bollwyvl** [comment]
@conda-forge-admin ready for review

**Comment by bollwyvl** [comment]
@conda-forge-help-python ready for review

**Comment by beckermr** [comment]
Can you add more of the notes from the PR description as comments to the recipe? The patches change enough that it is worth it here.

**Comment by bollwyvl** [comment]
> notes from the PR description as comments to the recipe

I added them as comments to `meta.yaml`: did you mean adding them to the patches as well/instead?

**Comment by beckermr** [comment]
nope the metayaml is fine. thanks!

**Comment by bollwyvl** [comment]
Thanks!

**Pull request merged**
