### PR TITLE
Add log4j recipe

### PR DESCRIPTION
**Pull request by beenje**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

I'm trying to package some java applications and one of them has log4j 1 as dependency.
I know it has reached end of life a while ago and that users are recommended to upgrade to log4j 2 but I'd need this version to be available.

Note that I don't recompile the jar but download it from the official source, as done in the [maven](https://github.com/conda-forge/maven-feedstock/blob/main/recipe/meta.yaml) and [bfg](https://github.com/conda-forge/bfg-feedstock/blob/main/recipe/meta.yaml) feedstocks.

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge/help-java, ready for review!

**Comment by mfansler** [comment]
Chiming in as a community member, I feel that there should be some effort to warn users that **this is classified as critically vulnerable software**. For example, [a pre-link script](https://docs.conda.io/projects/conda-build/en/stable/resources/link-scripts.html#adding-pre-link-post-link-and-pre-unlink-scripts) that shows a warning to the user and provides [a link to the known (and never-to-be-fixed) CVEs](https://logging.apache.org/log4j/1.2/). Would be even better if the users had to accept a prompt. What do others think?

Also, [this post shows it doesn't work with Java 9](https://blogs.apache.org/logging/entry/moving_on_to_log4j_2) (and possibly later?). Hence, the metadata should probably include upper bounds on Java version and testing should verify it runs rather than just test existence.

**Comment by beenje** [comment]
Thanks for the comment @mfansler. I agree it might not be a good idea to make log4j 1 available on conda-forge. I'll push to get the project I'm interested in migrate to log4j 2. I already opened an issue: https://gitlab.com/tango-controls/LogViewer/-/issues/9

Will update this MR for log4j 2.

**Comment by beenje** [comment]
Closing for now. Will see what happens with LogViewer. Will open a new PR if this is needed.

**Pull request closed without merging**
