### PR TITLE
Kerberos

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### Comment:
Replaces existing pykerberos-feedstock with kerberos - Points to apple github of original kerberos github source

https://github.com/conda-forge/pykerberos-feedstock/issues/20

https://github.com/02strich/pykerberos

recommends using 
https://pypi.org/project/kerberos/ 
which points to 
https://github.com/apple/ccs-pykerberos

Reference - https://github.com/02strich/pykerberos/blob/master/README.txt

`NOTE: this fork of ccs-kerberos is currently on life support mode as Apple has resumed work on upstream. Please try to use https://pypi.python.org/pypi/kerberos instead of this fork if possible.`

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin ready for review! - This replaces the feedstock pykerberos https://github.com/conda-forge/pykerberos-feedstock/issues/20 that is now recommending a different git source (see comments in title)- Please confirm if the package name kerberos is fine (matches pypi) or if it should be python-kerberos as suggested in https://github.com/conda-forge/pykerberos-feedstock/issues/20#issuecomment-1747299111

**Comment by duncanmmacleod** [comment]
@rxm7706, as discussed over on https://github.com/conda-forge/pykerberos-feedstock/issues/20#issuecomment-1747553211, I think this feedstock should be called `python-kerberos`. IMO `kerberos` is too general a name given that the package only provides a Python interface for GSSAPI. But, I won't be maintaining this feedstock, and am not a conda-forge/core team member, so please weight my opinion appropriately (~0).

**Comment by rxm7706** [comment]
> @rxm7706, as discussed over on [conda-forge/pykerberos-feedstock#20 (comment)](https://github.com/conda-forge/pykerberos-feedstock/issues/20#issuecomment-1747553211), I think this feedstock should be called `python-kerberos`. IMO `kerberos` is too general a name given that the package only provides a Python interface for GSSAPI. But, I won't be maintaining this feedstock, and am not a conda-forge/core team member, so please weight my opinion appropriately (~0).

@duncanmmacleod - Thank you -  
I think that's good enough for me ! I've asked conda-forge admins to weigh in too - I'll keep a PR handy with the package name python-kerberos handy - I agree with your reasoning. Thank you for the direction. Appreciate it. Regards.

**Comment by rxm7706** [comment]
@conda-forge/staged-recipes  ready for review

This replaces the feedstock pykerberos https://github.com/conda-forge/pykerberos-feedstock/issues/20 that is now recommending a different git source (see comments in title)- Please confirm if the package name kerberos is fine (matches pypi) or if it should be python-kerberos as suggested in https://github.com/conda-forge/pykerberos-feedstock/issues/20#issuecomment-1747299111

**Comment by ocefpaf** [comment]
> @conda-forge/staged-recipes ready for review
> 
> This replaces the feedstock pykerberos [conda-forge/pykerberos-feedstock#20](https://github.com/conda-forge/pykerberos-feedstock/issues/20) that is now recommending a different git source (see comments in title)- Please confirm if the package name kerberos is fine (matches pypi) or if it should be python-kerberos as suggested in [conda-forge/pykerberos-feedstock#20 (comment)](https://github.com/conda-forge/pykerberos-feedstock/issues/20#issuecomment-1747299111)

It should be prefixed with python, as python-kerberos, b/c conda is an agnostic package manager and `kerberos` is another package that may be in conda soon. BTW, isn't the c-lib `kerberos` required for python-kerberos?

**Pull request merged**
