### PR TITLE
Added recipe for slicedimage

### PR DESCRIPTION
**Pull request by micknudsen**
Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vend other packages
- [ X Build number is 0
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by micknudsen** [comment]
@conda-forge/bioconda-recipes This recipe should be moved here from bioconda (see https://github.com/bioconda/bioconda-recipes/pull/16168)

**Comment by scopatz** [comment]
This is noarch python. Thanks!

**Comment by micknudsen** [comment]
@scopatz Why was this merged even though a test failed?

**Comment by scopatz** [comment]
It is a noarch python recipe, so it only needs to pass on linux

**Comment by micknudsen** [comment]
Thanks, that was new to me. I don't know anything about Windows.

**Pull request merged**
