### PR TITLE
Adding PyHeatDemand Recipe

### PR DESCRIPTION
**Pull request by AlexanderJuestel**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by AlexanderJuestel** [comment]
@conda-forge/help-python, I need some help with respect to the failing tests. 

I recently renamed the package from `pyhd` to `pyheatdemand` as the name `pyhd` was not available on PyPi anymore. The failing test suggests that `pyhd` is still imported from the `__init__.py` file. However, that was changed accordingly before uploading the package to PyPi the first time

https://github.com/AlexanderJuestel/pyheatdemand/blob/c186aa83ec161d81a03f42514a9636e223f6eb1a/pyheatdemand/__init__.py#L1-L6

image

**Comment by ocefpaf** [comment]
> @conda-forge/help-python, I need some help with respect to the failing tests.
> 
> I recently renamed the package from `pyhd` to `pyheatdemand` as the name `pyhd` was not available on PyPi anymore. The failing test suggests that `pyhd` is still imported from the `__init__.py` file. However, that was changed accordingly before uploading the package to PyPi the first time
> 
> https://github.com/AlexanderJuestel/pyheatdemand/blob/c186aa83ec161d81a03f42514a9636e223f6eb1a/pyheatdemand/__init__.py#L1-L6

Not on your 0.0.7 release. See https://github.com/AlexanderJuestel/pyheatdemand/blob/v0.0.7/pyheatdemand/__init__.py#L6

**Comment by AlexanderJuestel** [comment]
@ocefpaf All checks are passing now and the recipe in in "excellent condition"

**Comment by AlexanderJuestel** [comment]
@ocefpaf All checks are passing now :)

**Pull request merged**
