### PR TITLE
Remove auditwheel and pyelftools

### PR DESCRIPTION
**Pull request by jakirkham**
Related: https://github.com/conda-forge/staged-recipes/issues/179

Appears that things went a bit strange. Some recipes were converted to feedstocks, but not all. Here we try to clear out the few that did get converted. The hope is the other two will be properly converted to feedstocks this time.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @pelson @ocefpaf

**Comment by jakirkham** [comment]
As this merely cleans out that recipe and CI is supposed to be canceled, merging...

**Comment by pelson** [comment]
Thanks @jakirkham. I've now reverted this change and will look to address any issues that weren't caused by these recipes. :+1:

**Comment by jakirkham** [comment]
Sure. These were not problem causers. I just thought they actually generated feedstocks correctly and was a little worried what would happen if we fixed the bug and they tried to regenerate feedstocks.

**Comment by pelson** [comment]
> I just thought they actually generated feedstocks correctly and was a little worried what would happen if we fixed the bug and they tried to regenerate feedstocks.

**Pull request merged**
