### PR TITLE
r-dive stuff

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @alexetnunes

### CODE REVIEW

**Comment by cbrueffer** [comment]
I added `r-dosefinder` yesterday, so you may want to rebase and give this another try. Please consider adding more maintainers:

```
- johanneskoester
- bgruening
- daler
- jdblischak
- cbrueffer
```

**Comment by ocefpaf** [comment]
> I added `r-dosefinder` yesterday, so you may want to rebase and give this another try. Please consider adding more maintainers:

Thanks @cbrueffer! I'll get back to this and finish them soon.

**Comment by ocefpaf** [comment]
@cbrueffer can you take a quick look at the recipes and let me know if they are OK?
(I only package r when needed/requested and I don't really use the packages after that.)

**Comment by cbrueffer** [comment]
@ocefpaf please add `license_file` information, see e.g. in https://github.com/conda-forge/staged-recipes/blob/c094cb1a0b0f929ef5ecbb8366f82ab03a3f170c/recipes/r-rcppziggurat/meta.yaml
Otherwise they looks fine.

For the future I recommend using https://github.com/bgruening/conda_r_skeleton_helper , it runs `conda skeleton cran` and post-processes the recipe to add license info, maintainers etc.

**Comment by ocefpaf** [comment]
Failing on Windows with:

```
C:/bld/r-sel_1533733230229/_h_env/R/../Library/mingw-w64/bin/gcc  -I"C:/bld/r-sel_1533733230229/_h_env/R/include" -DNDEBUG     -I"C:/bld/r-sel_1533733230229/_h_env/R/../Library/mingw-w64/include"     -O2 -Wall  -std=gnu99 -march=x86-64 -mtune=generic -c knotave.c -o knotave.o
/bin/sh: C:/bld/r-sel_1533733230229/_h_env/R/../Library/mingw-w64/bin/gcc: No such file or directory
C:/bld/r-sel_1533733230229/_h_env/R/etc/x64/Makeconf:208: recipe for target 'knotave.o' failed
make: *** [knotave.o] Error 127
Warning: running command 'make -f "C:/bld/r-sel_1533733230229/_h_env/R/etc/x64/Makeconf" -f "C:/bld/r-sel_1533733230229/_h_env/R/share/make/winshlib.mk" SHLIB="SEL.dll" WIN=64 TCLBIN=64 OBJECTS="knotave.o"' had status 2
ERROR: compilation failed for package 'SEL'
* removing 'C:/bld/r-sel_1533733230229/_h_env/R/library/SEL'
(C:\bld\r-sel_1533733230229\_h_env) C:\bld\r-sel_1533733230229\work>IF 1 NEQ 0 exit 1 
```

@cbrueffer is that something easy to fix or do you recommend to skip Windows for now?

**Comment by cbrueffer** [comment]
Should be, a compiler would be good on Windows :-) Try this in `r-sel`:

```
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
```

**Pull request merged**
