### PR TITLE
Add a recipe for spyder-terminal

### PR DESCRIPTION
**Pull request by ccordoba12**
This is a Spyder plugin to run bash or cmd terminal sessions inside Spyder.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@andfoy, @goanpeca, please accept being maintainers :-)

**Comment by andfoy** [comment]
I accept

**Comment by ccordoba12** [comment]
This is ready. It's only pending a fix for conda-forge/coloredlogs-feedstock#5

**Comment by ccordoba12** [comment]
Please see conda-forge/coloredlogs-feedstock#6

**Comment by goanpeca** [comment]
@ccordoba12 cool being a maintainer :-)

**Comment by ccordoba12** [comment]
This is finally ready!! Yay!

@conda-forge/staged-recipes, could you give a hand here, please?

**Comment by goanpeca** [comment]
Nice! @andfoy do not forget to copy the packages to anaconda.org/spyder-ide channel

**Pull request merged**
