### PR TITLE
add Pylons

### PR DESCRIPTION
**Pull request by rluria14**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rluria14** [comment]
@oblute @mwilson8 agree to be maintainers?

**Comment by marcelotrevisani** [comment]
It seems this project should be just for python 2
If you see this part
https://github.com/Pylons/pylons/blob/8625d5af790560219c5114358611bc7e0edcf12f/pylons/controllers/core.py#L108
That way to catch an exception is Python 2 only

**Comment by marcelotrevisani** [comment]
> It seems this project should be just for python 2
> If you see this part
> https://github.com/Pylons/pylons/blob/8625d5af790560219c5114358611bc7e0edcf12f/pylons/controllers/core.py#L108
> That way to catch an exception is Python 2 only

For Python 3+ that should be
```
        except (HTTPException, httpe):
```

**Comment by mwilson8** [comment]
> > It seems this project should be just for python 2
> > If you see this part
> > https://github.com/Pylons/pylons/blob/8625d5af790560219c5114358611bc7e0edcf12f/pylons/controllers/core.py#L108
> > That way to catch an exception is Python 2 only
> 
> For Python 3+ that should be
> 
> ```
>         except HTTPException as httpe:
> ```

@marcelotrevisani Would it be better to just try to patch this file, or to restrict the py version for the build?

**Comment by rluria14** [comment]
@conda-forge/staged-recipes @marcelotrevisani ready for final review and merge

**Comment by marcelotrevisani** [comment]
> > > It seems this project should be just for python 2
> > > If you see this part
> > > https://github.com/Pylons/pylons/blob/8625d5af790560219c5114358611bc7e0edcf12f/pylons/controllers/core.py#L108
> > > That way to catch an exception is Python 2 only
> > 
> > 
> > For Python 3+ that should be
> > ```
> >         except HTTPException as httpe:
> > ```
> 
> @marcelotrevisani Would it be better to just try to patch this file, or to restrict the py version for the build?

I think it would be better to open an issue/PR on the project and see if the maintainers will accept it. If it is a project which is not maintained anymore you can patch it to also support Python 3+

**Comment by marcelotrevisani** [comment]
> @conda-forge/staged-recipes @marcelotrevisani ready for final review and merge

I did some modifications. Came back with the ``noarch: python`` and limited ``python`` on the requirements

**Pull request merged**
