### PR TITLE
Hg-Git

### PR DESCRIPTION
**Pull request by krinsman**
Extension to Mercurial that allows pushing to and pulling from git repositories.

### CODE REVIEW

**Comment by krinsman** [comment]
Just realized that this won't work on Windows because I didn't supply a `build.bat`. I don't know how to write Windows batch files however. I am not sure what to do.

**Comment by jakirkham** [comment]
Can just add a `skip` for Windows and add an issue for it on the feedstock.

**Comment by krinsman** [comment]
@jakirkham That sounds good to me! I didn't realize that was an option

**Comment by krinsman** [comment]
Another thing I need to change is the dependencies -- this doesn't seem to work with Mercurial 4.9.1 for some reason, even though it works with Mercurial 4.7.2. 

So I probably need to update this somehow to be compatible with Mercurial 4.9.1. but do not have the bandwidth to do so at the moment.

**Pull request closed without merging**
