### PR TITLE
add pytest-describe 0.12.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Test dependency of https://github.com/conda-forge/graphql-core-feedstock/pull/13

### CODE REVIEW

**Comment by bollwyvl** [comment]
appears to be some temporary issue on the pypi side... using the full url:
```
https://files.pythonhosted.org/packages/89/f7/f3b2418c71aa932abbb7b5e989661d767c9c88ed74db2c949c9574db9773/pytest-describe-0.12.0.tar.gz
```
seems to at least download correctly with the matching SHA... will observe...

**Comment by bollwyvl** [comment]
Apparently only _some_ newer features are broken, and `graphql-core` is using it effectively with a 5.x pytest... kind of an odd situation...

**Comment by bollwyvl** [comment]
@conda-forge/help-python ready for review!

**Comment by scopatz** [comment]
Thanks!

**Comment by bollwyvl** [comment]
Woo!

**Pull request merged**
