### PR TITLE
Aimrocks

### PR DESCRIPTION
**Pull request by hadim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hadim** [comment]
Blocked by the missing rocksdb 6.29.5 on conda-forge.

**Comment by hadim** [comment]
@gorarakelyan now that rocksdb 6.29.5 is available, I can continue on this one. For now, I have hard-coded the git hash matching `aimrocks==0.2.1` but before merging here we need to get a git tag from `aimrocks`. Is that something you could do? 

Also do you want to be added as a maintainer of the package?

**Comment by hadim** [comment]
@conda-forge/help-python-c ready for review

**Comment by hadim** [comment]
correlated package: https://github.com/conda-forge/staged-recipes/pull/21651

**Comment by gorarakelyan** [comment]
@hadim I just pushed `v0.2.1` tag for `aimrocks`. Yes, if it is possible please add me as a maintainer for both aimrocks and aim-ui.

**Comment by hadim** [comment]
@gorarakelyan: I noticed the rocksdb `.so` file is embedded into the package which is not a good practice when packaging on conda forge since the rocksdb lib is now a direct dep of the `aimrocks` package.

I have a made small patch to the `setup.py` file of `aimrocks` to be able to control whether one wants to embed rocksdb or not. The default behaviour remains the same as before, so you could eventually backport this patch upstream if you want for your next release.

You can check the patch at https://github.com/conda-forge/staged-recipes/pull/21653/commits/08fb6d9f55ef31dc2f22b88ca1f879f0c926cac2

**Comment by hadim** [comment]
LGTM

**Comment by hadim** [comment]
Thanks @beckermr!

**Pull request merged**
