### PR TITLE
Add r-aggregation

### PR DESCRIPTION
**Pull request by apcamargo**
The recipe was created using `conda_r_skeleton_helper`. It was successfully built locally with conda-build.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Just one thing. You have two meta.yaml
Which one is the right one?
Both are for the same recipe
Look the babe, one is meta.yaml and the another one is meta.yaml~

**Comment by apcamargo** [comment]
I forgot to delete "meta.yaml~". My bad.
Do you want me to create a commit?

**Comment by marcelotrevisani** [comment]
Yes, please remove one and let just the right one. :)

**Comment by apcamargo** [comment]
There it is!

**Comment by marcelotrevisani** [comment]
Thanks @apcamargo to your effort to put this in ``conda-forge`` !

I'm going to merge this

**Pull request merged**
