### PR TITLE
DOC add command to ping the team in PR template

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds the command to ping teams to the PR template.

@conda-forge/staged-recipes for viz

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please ping team

**Comment by beckermr** [comment]
It works!

**Comment by chrisburr** [comment]
Thanks @beckermr! This is a really nice solution to the problem 🍰

**Comment by jakirkham** [comment]
Thanks for doing this @beckermr! Also nice to see it in action. 😀

**Pull request merged**
