### PR TITLE
Pyntcloud

### PR DESCRIPTION
**Pull request by daavoo**
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vend other packages
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Hi @daavoo , I modified a bit your recipe, I hop you don't mind.

Any questions about my modifications please fell free to ask

**Comment by daavoo** [comment]
Hola @marcelotrevisani ! Thank you so much. 

I do have some questions about your modifications but first I'm going to re-read https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml to check what I missed

**Comment by marcelotrevisani** [comment]
> Hola @marcelotrevisani ! Thank you so much.
> 
> I do have some questions about your modifications but first I'm going to re-read https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml to check what I missed

Sure, when you think that is fine please ping me and I will merge it

**Comment by daavoo** [comment]
@marcelotrevisani please correct me if I'm wrong:

It seems that most of the modifications were necessary because I did not have my fork updated (https://conda-forge.org/docs/maintainer/adding_pkgs.html#synchronizing-fork-for-future-use) 

What I do not understand is the `noarch` addition (and/or the removal of the Python version constraints) because `pyntcloud` does not complain one of the points in the checklist (https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python); `pyntcloud` uses some Python>= 3.6 features and it won't run on lower versions.

Should I add `python >=3.6` to the host and run sections ?

Thanks again

**Comment by daavoo** [comment]
@marcelotrevisani nevermind about the >=3.6 requirements. I removed them and didn't remember :')

Feel free to merge if it's of for you

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani nevermind about the >=3.6 requirements. I removed them and didn't remember :')
> 
> Feel free to merge if it's of for you

I forgot about this requirement, I can add it, it wil drop the package for python 2.7
If you r project does not work with python 2.7 we should drop it then

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani please correct me if I'm wrong:
> 
> It seems that most of the modifications were necessary because I did not have my fork updated (https://conda-forge.org/docs/maintainer/adding_pkgs.html#synchronizing-fork-for-future-use)
> 
> What I do not understand is the `noarch` addition (and/or the removal of the Python version constraints) because `pyntcloud` does not complain one of the points in the checklist (https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python); `pyntcloud` uses some Python>= 3.6 features and it won't run on lower versions.
> 
> Should I add `python >=3.6` to the host and run sections ?
> 
> Thanks again

It was mixed the ``host`` and ``build`` section. You can think the ``build`` section as the tools and compilers you need to build a project if it is a pure python project you will not need compilers and stuff. Because of that, this section is not necessary for this package.

The removal of the constrain for Python <=3.6 was my mistake, sorry about that

The addition of ``noarch`` is because as this project is a pure python project it does not rely on anything specific of any platform. ``noarch`` stands for no architecture, you can see more explanation about that here: [noarch builds](https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=noarch#noarch-builds)

And to constrain Python in ``noarch`` builds we do not use the ``skip: true  #[py2]`` for example, we should add the constrains in ``host`` and also in ``run`` requirements. I will add it to this recipe

**Comment by daavoo** [comment]
> > @marcelotrevisani please correct me if I'm wrong:
> > It seems that most of the modifications were necessary because I did not have my fork updated (https://conda-forge.org/docs/maintainer/adding_pkgs.html#synchronizing-fork-for-future-use)
> > What I do not understand is the `noarch` addition (and/or the removal of the Python version constraints) because `pyntcloud` does not complain one of the points in the checklist (https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python); `pyntcloud` uses some Python>= 3.6 features and it won't run on lower versions.
> > Should I add `python >=3.6` to the host and run sections ?
> > Thanks again
> 
> It was mixed the `host` and `build` section. You can think the `build` section as the tools and compilers you need to build a project if it is a pure python project you will not need compilers and stuff. Because of that, this section is not necessary for this package.
> 
> The removal of the constrain for Python <=3.6 was my mistake, sorry about that
> 
> The addition of `noarch` is because as this project is a pure python project it does not rely on anything specific of any platform. `noarch` stands for no architecture, you can see more explanation about that here: [noarch builds](https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=noarch#noarch-builds)
> 
> And to constrain Python in `noarch` builds we do not use the `skip: true #[py2]` for example, we should add the constrains in `host` and also in `run` requirements. I will add it to this recipe

Thank you for the clarifications :)

**Comment by marcelotrevisani** [comment]
You are welcome! :)

Thanks for added this project to ``conda-forge``!

**Pull request merged**
