### PR TITLE
ParMETIS: Add recipe

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk Once we get this in, we need to decide how to handle the scotch/ptscotch metis.h/parmetis.h compatibility headers.

**Comment by isuruf** [comment]
See https://github.com/conda-forge/staged-recipes/pull/3107#issuecomment-307640481

**Comment by dalcinl** [comment]
@knepley, @minrk, and @dalcinl emailed the author asking for permission to distribute binary packages within the conda-forge effort, and the author agreed. What should I do to get this PR accepted?

**Comment by isuruf** [comment]
Can you add the email contents as a text file in `recipes/parmetis` folder? That should clarify the redistribution issue.
One other question would be whether we add this in the main channel or under a `nonfree` label like debian does. cc @conda-forge/core

**Comment by dalcinl** [comment]
@isuruf The plain-text email response from ParMETIS author is base64-encoded, to it is not human readable. I can add it to the recipe dict. Below I'm pasting the contents after decoding and removing headers.

```
From: Matthew Knepley <knepley@buffalo.edu>
Date: Friday, October 13, 2017 at 9:19 AM
To: George Karypis <karypis@cs.umn.edu>
Cc: Lisandro Dalcin <dalcinl@gmail.com>, MinRK <benjaminrk@gmail.com>
Subject: ParMetis Request

Hi George,

We are starting to have a pretty robust software stack for treating PDEs in Python using the Anaconda distribution from Continuum. A key piece of this would be hosting a ParMetis recipe on conda-forge with something like share-alike permissions on redistribution (standard "redistribution must include this copyright notice" stuff). Would this be alright with you?

I am Cc'ing the developers actually responsible for all the work.

  Thanks,

     Matt
```

```
From: George Karypis <george@karypis.net>
Date: Sat, 14 Oct 2017 13:02:36 +0000
To: Matthew Knepley <knepley@buffalo.edu>, George Karypis <karypis@cs.umn.edu>
CC: Lisandro Dalcin <dalcinl@gmail.com>, MinRK <benjaminrk@gmail.com>
Subject: Re: ParMetis Request

Matt,

It is fine with me.

Regards,

George
_________________________________________________
George Karypis, Associate Head
Distinguished McKnight University Professor
ADC Chair of Digital Technology
Department of Computer Science & Engineering
University of Minnesota, Minneapolis, USA
http://www.cs.umn.edu/~karypis
karypis@umn.edu, tel: (612) 625-8144
```

**Comment by isuruf** [comment]
> The plain-text email response from ParMETIS author is base64-encoded, to it is not human readable. I can add it to the recipe dir, of course.

Human readable form is fine.

@jakirkham, @ocefpaf what do you think about having this in the main channel or in a separate label? I suggested a separate label so that the user installing this package or a downstream package know that the package is not free.

**Comment by dalcinl** [comment]
@isuruf Would the special label somehow prevent the listing of parmetis as a dependency of other packages?

**Comment by isuruf** [comment]
No, you'll have to change the `conda-forge.yml` in the dependencies though

**Comment by mwcraig** [comment]
@isuruf -- I don't see a need for a `non-free` label unless we have done that in other cases with similar licenses (we may have, I just don't know). I do think given the license terms that it is very good to have added the permission to redistribute to the recipe.

**Comment by isuruf** [comment]
Okay then. @dalcinl, if you could add the plain text version of the email to the recipe folder, we can merge this

**Comment by dalcinl** [comment]
@isuruf Done. BTW, I took the liberty of adding you as a recipe maintainer. If you are not OK with that, let me know and I'll strip the last commit.

**Pull request merged**
