### PR TITLE
Add bob.db.casme2 recipe

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by pelson** [comment]
```
+ nosetests -sv bob.db.casme2
Failure: SkipTest (The database file './bob/db/casme2/db.sql3' is not available; did you forget to run 'bob_dbmanage.py casme2 create' ?) ... SKIP: The database file './bob/db/casme2/db.sql3' is not available; did you forget to run 'bob_dbmanage.py casme2 create' ?
```

**Comment by 183amir** [comment]
Thank you this is probably a bug. I will report it upstream.

**Comment by pelson** [comment]
Want to merge anyway @183amir and fix in the feedstock?

**Comment by 183amir** [comment]
That would be great, thanks.

**Pull request merged**
