### PR TITLE
perl-app-cpanminus

### PR DESCRIPTION
**Pull request by jerowe**
I am trying to add perl-app-cpanminus to conda-forge.

### CODE REVIEW

**Comment by jerowe** [comment]
How on earth am I supposed to get make on windows?

**Comment by jerowe** [comment]
@jakirkham  - Some OSX builds of perl modules that need to be compiled are failing because the are trying to link to gcc.

```
 perl -V
Summary of my perl5 (revision 5 version 20 subversion 3) configuration:
   
  Platform:
    osname=darwin, osvers=13.4.0, archname=darwin-thread-multi-2level
    uname='darwin traviss-mac-377.local 13.4.0 darwin kernel version 13.4.0: sun aug 17 19:50:11 pdt 2014; root:xnu-2422.115.4~1release_x86_64 x86_64 '
    config_args='-Dusethreads -Duserelocatableinc -Dprefix=/Users/travis/miniconda/conda-bld/perl-net-ssleay_1501859962260/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac -de'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector',
    optimize='-O3',
    cppflags='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector'
    ccversion='', gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib /usr/local/lib
    libs=-lpthread -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=, so=dylib, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector'
```

**Comment by jerowe** [comment]
@conda-forge/core - I think travis is stuck.

**Comment by scopatz** [comment]
This looks good to me, if it looks good to you.

**Comment by jerowe** [comment]
yes, please!

**Comment by jakirkham** [comment]
Could you please send a PR to drop the two level structure of the recipe directory here? Name rename `perl-app-cpanminus/1.7043` to `perl-app-cpanminus`. Suspect this directory structure is blocking this recipe from being converted. Thanks.

**Comment by jerowe** [comment]
@jakirham - i opened a new PR. not sure if that was the ideal scenario or not. ;-)

**Pull request merged**
