### PR TITLE
Add viztracer recipe

### PR DESCRIPTION
**Pull request by gforsyth**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by gforsyth** [comment]
@gaogaotiantian -- I'm adding `viztracer` to `conda-forge`, happy to keep it updated here, but let me know if you'd like to be added to the list of recipe maintainers.  Thanks!

**Comment by gforsyth** [comment]
@conda-forge/core I believe I need to require the newer OSX SDK as documented here: https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

getting a failure to build on OSX right now:
```
  x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/viztracer_1611326703138/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/viztracer_1611326703138/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/viztracer_1611326703138/work=/usr/local/src/conda/viztracer-0.11.3 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/viztracer_1611326703138/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniforge3/conda-bld/viztracer_1611326703138/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -mmacosx-version-min=10.9 -I/Users/runner/miniforge3/conda-bld/viztracer_1611326703138/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/python3.8 -c src/viztracer/modules/snaptrace.c -o build/temp.macosx-10.9-x86_64-3.8/src/viztracer/modules/snaptrace.o
  clang-11: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  src/viztracer/modules/snaptrace.c:91:5: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
      clock_gettime(CLOCK_MONOTONIC, &t);
      ^
  src/viztracer/modules/snaptrace.c:91:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
      clock_gettime(CLOCK_MONOTONIC, &t);
                    ^
```

Just checking in that that's ok to do

**Comment by xhochy** [comment]
There is an open PR to support this: https://github.com/conda-forge/staged-recipes/pull/13722

Skip `osx` here and add it on the feedstock.

**Comment by gforsyth** [comment]
Hey @conda-forge/help-python this is ready for review!

(note skipping `osx` until feedstock is created)

**Review by xhochy — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Gil! 😀

**Comment by gaogaotiantian** [comment]
Hi @gforsyth, thank you for this effort! I'm not a conda expert so I don't know how I could help. Will the recipe pull the version changes automatically from pypi/github when I update? If not, is there anything I could do to help with this process?

**Comment by gforsyth** [comment]
Hey @gaogaotiantian -- happy to help!  `viztracer` is very cool!

There are some helpful bots that will automatically open a release PR against https://github.com/conda-forge/viztracer-feedstock whenever you push up a new release to pypi.  Unless something goes sideways, the only thing to do is to merge that PR.

I am definitely willing to keep an eye on it and merge them on releases, but if you'd like to be able to merge them if I'm not around, I can add you to the recipe maintainers list .

**Comment by gaogaotiantian** [comment]
@gforsyth okay I got it. Thank you for your help. You are obviously much more familiar with the system and will do a better job than me. I'll leave this to you. Appreciate it!

**Pull request merged**
