### PR TITLE
Adding vaex-viz (Generated by releash)

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I have a question regarding entry_points, console entry points can be listed under 'build', but I am not sure what happens to other entry points? I found in an [older thread](https://github.com/conda/conda/issues/404#issuecomment-30198190) to use the `preserve_egg_dir: True`, is that still required/adviced?

**Comment by maartenbreddels** [comment]
An alternative way (as discussed in https://github.com/jupyter/notebook/issues/2894) is to use:
```yaml 
  script: pip install --no-deps .
```

**Comment by maartenbreddels** [comment]
ping @jakirkham || @dougalsutherland
After 8 days it didn't get assigned to anyone, maybe it was overlooked because I started my own conversation?

**Comment by dougalsutherland** [comment]
Sorry, I think a lot of the review team has been relatively busy lately and things have been somewhat slow. The best thing to do in general though is to ping @ conda-forge/staged-recipes.

I don't know what the situation is with non-script entrypoints. @conda-forge/core?

**Comment by mwcraig** [comment]
@msarahan or @jjhelmus may be in the best position to answer the question about non-script entry points...

**Comment by maartenbreddels** [comment]
ping @conda-forge/staged-recipes it's ~1 month now, can I help getting this merged?

**Comment by dougalsutherland** [comment]
@maartenbreddels Sorry for the extreme delay. I think `preserve_egg_dir: True` is probably the right thing do; merging now.

**Comment by maartenbreddels** [comment]
No worries, thanks!

(from mobile phone)

**Pull request merged**
