### PR TITLE
Add recipe: openpathsampling-cli

### PR DESCRIPTION
**Pull request by dwhswenson**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dwhswenson** [comment]
@conda-forge/staged-recipes: This is ready for review, but one question:

This is a situation where the code in *this* recipe is noarch (but py3+), however, one of its dependencies doesn't support Windows. At https://conda-forge.readthedocs.io/en/latest/meta.html, I came across the following:

> `noarch: python` can also work with recipes that would work on a given platform except that we don’t have one of its dependencies available. If this is the case, when the install runs `conda` will fail with an error message describing which dependency couldn’t be found. If the dependency is later made available, your package will start working without having to change anything.

I had interpreted that to mean that I could make this package noarch (cf7ffd6) and the missing dep on `win` would have been allowed. Was I misunderstanding that paragraph? Basically, should I be using `python: noarch; python >=3` here, or `skip: True  # [win or py2k]`? Currently have the latter.

**Comment by chrisburr** [comment]
`python: noarch; python >=3` is the right thing to do and it's okay for Windows to fail here on staged-recipes as it won't be used for the feedstock build.

**Comment by dwhswenson** [comment]
Thanks @chrisburr! This is now `noarch`. The `win_64` fail is the expected failure because a dependency doesn't exist for Windows (yet). The AppVeyor fail is because AppVeyor has been flaky with SSL certificates all day. Everything else passes.

**Comment by rpanai** [comment]
I've the same problem with `AppVeyor` failing with SSL certificates.

**Pull request merged**
