### PR TITLE
ModernGL recipe

### PR DESCRIPTION
**Pull request by patricksnape**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by patricksnape** [comment]
@conda-forge/staged-recipes Having issues with missing `libGL.so.1`:

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/moderngl_1562621825939/test_tmp/run_test.py", line 5, in <module>
    import moderngl.mgl
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

I added CDTs for mesa-libgl but this didn't seem to help?

**Comment by isuruf** [comment]
@patricksnape, CDTs are used for building only. If a dependency like OpenGL is needed for testing, it should be added to `recipe/yum_requirements.txt`

**Comment by patricksnape** [comment]
@cprogrammer1994 this would be an 'official' conda-forge repository for your project. Would you be ok being listed as a maintainer and thus a point of contact if future builds fail? It also gives you admin rights on the created repository so you can perform releases yourself :)

**Comment by cprogrammer1994** [comment]
@patricksnape yes, sure.

**Comment by patricksnape** [comment]
@conda-forge/staged-recipes Ready for review

**Comment by patricksnape** [comment]
@chrisburr Thank you!

**Pull request merged**
