### PR TITLE
Add recipe for wilds

### PR DESCRIPTION
**Pull request by mlondschien**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] ~~If static libraries are linked in, the license of the static library is packaged.~~
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mlondschien** [comment]
@kohpangwei @ssagawa @teetone I'd like to add `wilds` to conda-forge. Please leave a quick 👍 or 👎 depending on whether you'd like to be added as a maintainer of the feedstock.

**Comment by mlondschien** [comment]
@conda-forge/staged-recipes : I would like to add a noarch package that has a dependency (`pytorch`) that does not exist for windows. What is the right approach here?

**Comment by ocefpaf** [comment]
> @conda-forge/staged-recipes : I would like to add a noarch package that has a dependency (`pytorch`) that does not exist for windows. What is the right approach here?

Just make it noarch and, when pytorch is available on Windows, the package will work.

**Comment by mlondschien** [comment]
Thanks @ocefpaf. This yields
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {MatchSpec("pytorch[version='>=1.2.0']"), MatchSpec("ogb==1.2.6=pyhd8ed1ab_0"), MatchSpec("torchvision[version='>=0.8.2']")}
```

I tried skipping windows in https://github.com/conda-forge/staged-recipes/pull/22094/commits/cd1bc3cebdedb3e6480bd9a3f17e16e0263c1b0f, but then the linter complains that this is not allowed for noarch packages.

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf. This yields

That is expected. It won't build nor install on Windows now. However, if pytorch is ever made available on Windows, you don't need to do anything and this package will be installable there.

**Comment by ocefpaf** [comment]
> @kohpangwei @ssagawa @teetone I'd like to add `wilds` to conda-forge. Please leave a quick +1 or -1 depending on whether you'd like to be added as a maintainer of the feedstock.

Just waiting on their OK to merge this.

**Comment by kohpangwei** [comment]
Thank you @mlondschien ! We didn't include torch_scatter and torch_geometric in the pip setup because required specifying some additional fields, but it looks like their conda install might be more straightforward (https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#installation-via-binaries). Do you think it makes sense to include `pyg` in the conda install?

**Comment by mlondschien** [comment]
@kohpangwei Yes. I added `pytorch_geometric` and `pytorch_scatter` as requirements. Are you ok with being added to this repo as a maintainer?

**Comment by kohpangwei** [comment]
Yes, please add me and @ssagawa as maintainers! Thank you for setting this up. I'm not familiar with adding recipes to conda, so would you mind helping us to test that the install works as expected please?

**Comment by mlondschien** [comment]
Thank you.

@ssagawa can you give a quick thumbs up?

There should be nothing more to do after merging this :).

**Comment by ssagawa** [comment]
Thanks for working on this, Malte! And yes, please add me as a maintainer!

**Comment by mlondschien** [comment]
Thanks. This is ready to merge @conda-forge/staged-recipes.

**Comment by kohpangwei** [comment]
Thanks Malte!

**Pull request merged**
