### PR TITLE
Add pyfolio (again)

### PR DESCRIPTION
**Pull request by alen12345**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Please rebase onto master.

**Comment by CJ-Wright** [comment]
It seems you deleted your package in your own commit history, which got merged.
Please make certain to always make a separate branch for each package and never delete anything from staged-recipes.

**Comment by alen12345** [comment]
So sorry, I started stupidly working on master and then realised I needed more packages. I am working on the rebase now.

**Comment by alen12345** [comment]
Again...

**Comment by CJ-Wright** [comment]
You might try:
1. copy your recipe somewhere else (to keep it safe)
1. checking out master
1. making certain your master is up to date with upstream master (`git pull upstream master --ff-only`) or a hard reset on upstream master (assuming that upstream is conda-forge)
1. making a brand new branch (`git checkout -b pyfolio_again`)
1. add the recipe to the new branch (you could also potentially do some `git checkout` stuff to get the file from the other branch, maybe)
1. push it to your fork
1. PR it into cf

I think this should make certain your history is clean.

**Comment by alen12345** [comment]
Let me rebase with your origin and not mine

**Comment by CJ-Wright** [comment]
Ok, please close this PR when you issue the new one.

**Comment by alen12345** [comment]
I cannot fast forward, I will just restart from scratch working seriously.

**Pull request closed without merging**
