### PR TITLE
Add recipe for py-cpuinfo

### PR DESCRIPTION
**Pull request by mstimberg**
https://pypi.python.org/pypi/py-cpuinfo

### CODE REVIEW

**Comment by mstimberg** [comment]
Oops, I did not expect that the test server runs outdated versions of conda and conda-build so that the new `noarch: python` mechanism does not work... I guess this will change soon?

**Comment by mstimberg** [comment]
Ok, I read conda-forge/conda-feedstock#16 and only now realized that conda-forge has its own version of conda-build/conda (I though these packages were always taken from the default channel). I updated the recipe to use the old syntax for architecture-independent packages, it should build now.

**Comment by jakirkham** [comment]
Thanks @mstimberg.

**Comment by jakirkham** [comment]
Kind of orthogonal, but is there any plan to add Brian to conda-forge? Seems like a really nice addition. 😉

**Comment by mstimberg** [comment]
> Kind of orthogonal, but is there any plan to add Brian to conda-forge?

Yes, this is indeed planned -- I wanted to get some experience with the conda-forge process before tackling the more complicated task of adding Brian (although we do already have a conda package, so it should be rather straightforward to add it).

**Comment by jakirkham** [comment]
Make sense. Well feel free to ping me if I can help.

**Pull request merged**
