### PR TITLE
adding (grayskull generated and completed recipe) for the pypi-hosted casq package

### PR DESCRIPTION
**Pull request by soli**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by soli** [comment]
@conda-forge-admin, please ping team

**Comment by soli** [comment]
@conda-forge/help-python I guess the PR is ready for review.

**Comment by soli** [comment]
Thanks @ocefpaf !

**Comment by soli** [comment]
Hey @ocefpaf sorry to bother you but apparently the package failed to build on Azure (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=945506&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=675) and I'm not sure who to ask for help (no idea why "import casq" would fail to be honest). Can you point me in the right direction to try and debug this?

**Comment by soli** [comment]
You're probably quite busy, but if I may be of any help, please keep me posted!

**Comment by soli** [comment]
@conda-forge/help-python Can anyone help me understand what I can do to fix this?

**Comment by ocefpaf** [comment]
I tried to build it locally and the package is empty. I don't know how it passed in staged-recipes but not in the CIs. While there are a few build deps version that got upgraded, none that would explain that behavior. I'm at a loss here :-/

Maybe as in our element room chat to give a chance for more people to see this problem. Maybe someone knows what to do here.

**Comment by soli** [comment]
Ok thanks I'll try that, but what do you mean "the package is empty"? Does this mean the conda recipe fails building the package from the source dist?

**Comment by bollwyvl** [comment]
it's the hatch vs the new `conda-smithy` default  `.gitignore` junk again:

```toml
# pyproejct.toml
[tool.hatch.build.targets.wheel]
ignore-vcs = true
```

You could either propose that change upstream, or hot append it to the end of `pyproject.toml`. I don't think there's an environment variable workaround or anything

**Pull request merged**
