### PR TITLE
add EO-learn-mask

### PR DESCRIPTION
**Pull request by dcunn**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dcunn** [comment]
@conda-forge/staged-recipes @conda-forge/help-python I have never seen this error before. Any ideas?

**Comment by scopatz** [comment]
noarch packages only need to run on linux

**Comment by dcunn** [comment]
@scopatz Thank you. How should I fix the recipe? Skip the windows build?

**Comment by scopatz** [comment]
No need to change it, it is allowed to fail on windows

**Comment by dcunn** [comment]
@mwilson8 @oblute @rluria14 @benhuff want to be maintainers with me?

**Comment by dcunn** [comment]
@scopatz recipe is ready for review

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
