### PR TITLE
Wkhtmltopdf

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by synapticarbors** [comment]
Any reason not to include support for windows and osx? It looks like the binaries are available.

**Comment by scopatz** [comment]
Hi @synapticarbors - I don't happen to need the mac and windows packages, but I'd gladly accept a PR either to my branch or the feedstock once it is created.

**Comment by synapticarbors** [comment]
I'll put in a PR on the feedstock if I can remember to do it at some point.

**Comment by scopatz** [comment]
Cool! Any objections to merging this then?

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
