### PR TITLE
Submitting polcart

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
All tests pass! ping @ocefpaf @jakirkham @msarahan.

**Comment by ocefpaf** [comment]
Everything looks good but let's wait for Travis-CI to catch up. Not all the recipes you removed there are feedstocks yet.

**Comment by ocefpaf** [comment]
Alright, everything you removed here is feedstock'ed  now! We can merge this as soon as you finish the tests.

**Comment by ericmjl** [comment]
@ocefpaf thanks a lot! Btw, to learn a bit more, what's this concept of 'feedstocked'? What stuff is being removed to be "feed stocked"?

**Comment by ocefpaf** [comment]
In this PR you removed a few recipes. (I guess that maybe you did not remove them but rather picked up from an incomplete cycle for the feedstock creation.)

For example, one of the recipes removed is `preprocess`, and now you can see that it became a feedstock only 2 hours ago: https://github.com/conda-forge/preprocess-feedstock

So removing the recipe prematurely could prevent that from happening. I am not sure if the latest changes to Travis-CI will account for that but I did not want to risk it.

**Comment by ericmjl** [comment]
Okay, got it! Yes, that's right, I did pull from conda-forge:staged-recipes/master before forking. Maybe in the future I shouldn't do that?

**Comment by scopatz** [comment]
Please merge from master to clear this up.

**Comment by ocefpaf** [comment]
> Please merge from master to clear this up.

It is OK now because all of those became feedstocks.

**Comment by ericmjl** [comment]
@ocefpaf Just wondering how long it takes to become a feedstock? I haven't yet gotten a note, and there's a separate package I'm releasing to conda-forge that depends on polcart being on conda-forge.

**Comment by ocefpaf** [comment]
Travis-CI is completely overwhelmed right now, as you can see it has not get to that yet: https://travis-ci.org/conda-forge/staged-recipes/builds

**Comment by ericmjl** [comment]
Got it. Big thanks for the help and info!

**Pull request merged**
