### PR TITLE
Add recipe for pymemcache [skip appveyor]

### PR DESCRIPTION
**Pull request by nicoddemus**
This package is a requirement for `clcache>=4.2`.

@tadeu please ping here if you are OK being a maintainer here as well.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
We are seeing this kinda of problem in our CI, probably something related to the new conda build.

https://github.com/conda-forge/staged-recipes/issues/6621

I will open an issue in ``conda-build``

**Comment by marcelotrevisani** [comment]
Besides of that the recipe looks good to me.  :)

**Comment by nicoddemus** [comment]
The builds are failing with:

```
conda.exceptions.CondaHTTPError: HTTP 404 CONNECTION FAILED for url <file:///opt/conda/conda-bld/noarch/repodata.json>
Elapsed: 00:00.000085
```

Seems to be an infrastructural problem. Any hints what the problem might be?

**Comment by nicoddemus** [comment]
Oops missed your https://github.com/conda-forge/staged-recipes/pull/6624#issuecomment-419087671 hehehe. Thanks for the heads up.

**Comment by tadeu** [comment]
> @tadeu please ping here if you are OK being a maintainer here as well.

@nicoddemus ok!

**Comment by marcelotrevisani** [comment]
I just opened an issue in ``conda-build`` for that:

https://github.com/conda/conda-build/issues/3114

**Comment by tadeu** [comment]
Indeed it seems related to Conda, it's trying to open an HTTP connection to a `file:///`

**Comment by marcelotrevisani** [comment]
I opened a PR in ``staged-recipes`` just to pin ``conda-build`` to the latest stable version. So , it may fix for now this problem until they fix it in ``conda-build``

https://github.com/conda-forge/staged-recipes/pull/6627

**Comment by nicoddemus** [comment]
Still no dice 😕

**Comment by marcelotrevisani** [comment]
I'm on a train so I just triggered the CI in the easiest way possible, haha. It should work now

**Comment by marcelotrevisani** [comment]
Thanks to put this in conda-forge! :)

**Comment by nicoddemus** [comment]
Thanks!

**Pull request merged**
