### PR TITLE
Adding trame-xterm package

### PR DESCRIPTION
**Pull request by milljm**
Adding a trame subpackage for Kitware Inc's trame project.

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by milljm** [comment]
I will maintain this package as necessary.

**Comment by jourdain** [comment]
I will maintain this package as necessary as well. Thanks for doing that initial push

**Comment by jourdain** [comment]
Closing in favor of https://github.com/conda-forge/staged-recipes/pull/24875

**Comment by milljm** [comment]
@jourdain Thank you! I completely forgot about this...

**Comment by milljm** [comment]
This will be handled in another PR: https://github.com/conda-forge/staged-recipes/pull/24875

**Pull request closed without merging**
