### PR TITLE
Copied lief recipe from Anaconda/aggregate.

### PR DESCRIPTION
**Pull request by mariusvniekerk**
This is used for conda-build so we should build it for both
compiler stacks.

Fixes https://github.com/conda-forge/staged-recipes/issues/5788

### CODE REVIEW

**Comment by hmaarrfk** [comment]
maybe this just needs new compilers?

**Comment by jakirkham** [comment]
Have merged with current `master` to see if it passes. Would be nice to get the linter to pass as well.

**Comment by hmaarrfk** [comment]
travis
> The job exceeded the maximum log length, and has been terminated.

**Comment by mariusvniekerk** [comment]
Needs windows to pass

**Pull request closed without merging**
