### PR TITLE
Adding netgraph

### PR DESCRIPTION
**Pull request by paulbrodersen**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by paulbrodersen** [comment]
@conda-forge-admin, please ping help-python

**Comment by paulbrodersen** [comment]
This PR is ready for review. 

One potential issue is the dependency [`rectangle-packer`](https://github.com/Penlect/rectangle-packer).
When I created the `meta.yaml` with grayskull, it reported that the package is available on conda-forge. 
However, in preparation for submitting netgraph to conda-forge, I could not find a matching package on conda-forge (via google), nor had the author and maintainer uploaded `rectangle-packer` to conda-forge as indicated by [this issue](https://github.com/Penlect/rectangle-packer/issues/18). 

**I would be grateful if someone could confirm whether `rectangle-packer` is indeed available on conda-forge.**

**Comment by BastianZim** [comment]
The package is in conda-forge: https://github.com/conda-forge/rectangle-packer-feedstock
Is that the one you mean?

If you're looking for conda-forge packages, this should give you a good starting point: https://conda-forge.org/feedstock-outputs/

**Comment by paulbrodersen** [comment]
@BastianZim That seems to be the correct package. Thank you. 

On a different note, I went to school with a Sebastian Zimmermann. You didn't grow up in Berlin, by any chance?

**Comment by BastianZim** [comment]
Unfortunately, I grew up in Frankfurt but that would've been a nice coincidence 😄

**Comment by paulbrodersen** [comment]
@BastianZim Either way: ein herzliches "Servus", and thanks for all the help.

**Comment by BastianZim** [comment]
Merci! And my pleasure :)

**Pull request merged**
