### PR TITLE
Adding rerun-sdk 0.7.0

### PR DESCRIPTION
**Pull request by ruben-arts**
This MR is draft because I want to discuss it with the Rerun team as they would be better candidates to judge over the package. Also, only Linux support is tested and they support Windows and Mac as well so that might be a nice addition before merging. 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ruben-arts** [comment]
I tested this locally with the `python build_locally.py` and that worked, after that I could simply install using with `micromamba create -f environment.yml` and this environment:
```yaml
name: rerun-ros
channels:
  - conda-forge
  - robostack-staging
  - file://MY_SYSTEM/development/staged-recipes/build_artifacts
dependencies:
  - ros-humble-desktop
  - gazebo
  - ros-humble-navigation2 
  - ros-humble-turtlebot3 
  - ros-humble-turtlebot3-gazebo
  - numpy
  - opencv
  - yourdfpy
  - rerun-sdk
 ```
 And rerun's ros tutorial https://www.rerun.io/docs/howto/ros2-nav-turtlebot

**Comment by ruben-arts** [comment]
@conda-forge-admin, please rerender

**Comment by ruben-arts** [comment]
There is progress `osx-64` now succeeds :smiley:

**Comment by ruben-arts** [comment]
@conda-forge-admin, please add user @jleibs

**Comment by emilk** [comment]
I think the following needs to be added to the CI:

```
rustup target add wasm32-unknown-unknown
sudo apt-get -y install binaryen
```

This is needed to build the web viewer, which is a .wasm file. It is used when putting Rerun in a Jupyter notebook.

**Comment by ruben-arts** [comment]
> I think the following needs to be added to the CI:
> 
> ```
> rustup target add wasm32-unknown-unknown
> sudo apt-get -y install binaryen
> ```
> 
> This is needed to build the web viewer, which is a .wasm file. It is used when putting Rerun in a Jupyter notebook.

As we also run a build for windows on windows, what is required to run on on there?

**Comment by emilk** [comment]
For windows we have this in our CI:

```yaml
      # Since 'winget' is not available within the GitHub runner, we download the package directly:
      # See: https://github.com/marketplace/actions/engineerd-configurator
      - name: Install binaryen for building the web-viewer Wasm on windows
        if: inputs.platform == 'windows'
        uses: engineerd/configurator@v0.0.9
        with:
          name: "wasm-opt.exe"
          url: "https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-windows.tar.gz"
          pathInArchive: "binaryen-version_111/bin/wasm-opt.exe"
```

**Review by jleibs — APPROVED** [review]
This looks great to me!

**Comment by ruben-arts** [comment]
@conda-forge-admin, please add user @jleibs

**Pull request merged**
