### PR TITLE
Switch to the conda-forge-manager user's GH_TOKEN on Travis (Pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
This reproposes PR ( https://github.com/conda-forge/staged-recipes/pull/757 ) and reverts the reversion in PR ( https://github.com/conda-forge/staged-recipes/pull/926 ). This will switch back over to conda-forge-manager. However, it requires conda-forge-manager have the correct permissions set. Hence why it says WIP. Once that is resolved WIP can be removed and this merged.

cc @pelson

### CODE REVIEW

**Comment by pelson** [comment]
Let's hold off on doing this until we are back online with travis-ci. Don't want too many moving parts, especially considered that this token is used to authenticate with TravisCI in the first place.

**Comment by jakirkham** [comment]
Are we closer to implementing this? I think I invited the right bot.

**Comment by pelson** [comment]
I have no problem with merging this. I'm around so if there is a problem, I would be more able to help in fixing it (rather than needing to revert), so it is a pretty good time to merge IMO.

**Comment by jakirkham** [comment]
Removed the WIP. Though I think `conda-forge-manager` has an invitation they need to accept. 😉

**Comment by conda-forge-manager** [comment]
The power mwa ha ha ha ha 😈

**Comment by pelson** [comment]
Thanks for the gentle reminder @jakirkham 😉

**Comment by jakirkham** [comment]
Of course.

Kind of want to test it. This PR ( https://github.com/conda-forge/staged-recipes/pull/985 ) looks like it is in good enough shape to be merged. What do you think?

**Comment by jakirkham** [comment]
Actually this PR ( https://github.com/conda-forge/staged-recipes/pull/754 ) is ready to go too.

**Comment by jakirkham** [comment]
Looks like @ocefpaf is going to test it with PR ( https://github.com/conda-forge/staged-recipes/pull/1044 ).

**Comment by jakirkham** [comment]
So, it failed. Though not due to the usual Travis CI API issue. Has @conda-forge-manager logged into Travis CI yet and synced, @pelson? If not, I think that would correct the issue we are seeing. Traceback included below.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/pysal-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
Traceback (most recent call last):
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 158, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 194, in add_project_to_travis
    raise RuntimeError(msg.format(user))
RuntimeError: Unable to register the repo on Travis
(Is it down? Is the "conda-forge" name spelt correctly? [note: case sensitive])
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.1', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 171, in __call__
    print(e.message)
AttributeError: 'RuntimeError' object has no attribute 'message'
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp3b4chkl7__feedstocks/pysal-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by conda-forge-manager** [comment]
Yep, needed to sign in to TravisCI. Let's see if that helps.

**Comment by jakirkham** [comment]
Awesome. Restarted Travis CI.

**Comment by pelson** [comment]
Thanks @jakirkham.

**Comment by jakirkham** [comment]
If it hasn't finished syncing, it should by the time the job starts.

**Comment by jakirkham** [comment]
Thanks @pelson and @conda-forge-manager. 😄

**Comment by jakirkham** [comment]
Yep, everything is working now.

**Comment by pelson** [comment]
Awesome. All I did was sign in with the conda-forge-manager. No need to synch or anything.

Thanks @jakirkham 👍

**Comment by jakirkham** [comment]
Perfect. Yeah, `conda-smithy` probably did the syncing. Well we are up and running now.

**Comment by jakirkham** [comment]
It looks like @conda-forge-manager is about to be watching a lot of repos soon. 😜

**Pull request merged**
