### PR TITLE
Appveyor: cache packages

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by xoviat** [comment]
Ping @conda-forge/staged-recipes

**Comment by msarahan** [comment]
seems like it should work to me.  Have you tested it on any repos?

**Comment by xoviat** [comment]
I've tested this in the sense that it shouldn't make the pull requests start failing.

**Comment by CJ-Wright** [comment]
Would you mind elaborating on that testing procedure?

**Comment by xoviat** [comment]
Well, here's the latest test:

https://ci.appveyor.com/project/isuruf/flang/build/1.0.534

My previous testing procedure was to run the PR on my own appveyor.

**Comment by isuruf** [comment]
From the docs

> Cache size (beta)
With the introduction of the new cache we are also changing the way it’s metered.
The total size of build cache is limited per account and depends on the plan.
Total cache size per account consist of all caches from all projects. If projects contain more than one job in build matrix or in parallel testing, each job has its own separate cache, which cannot be shared with other jobs or projects.
Free - 1GB
It’s a hard quota which means the build will fail while trying to upload cache item exceeding the quota.

Not a viable option for conda-forge

**Comment by xoviat** [comment]
conda-forge is not on the free tier. And I'm only talking about enabling this on staged-recipes, which sees the most use.

**Pull request closed without merging**
