### PR TITLE
Add nglview

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
Seems like the linter is broken, there is exactly only one empty newline at EOF.

**Comment by marscher** [comment]
cc @gph82, @hainm are you fine with being maintainer here?

**Comment by hainm** [comment]
We already have it in bioconda channel. Not sure why need one more here. :(

**Comment by marscher** [comment]
On 08.03.2017 14:16, Hai Nguyen wrote:
> We already have it in bioconda channel. Not sure why need one more here. :(
Do you have Numpy-1.12 and Python 3.6 in bioconda?

We basically want to have it here, because we need pyemma for 
projections explorer/molpx and we're not (yet) willing supporting all of 
pyemma's dependencies in bioconda.

I can remove you as a maintainer here then. Thanks for your statement.

**Comment by marscher** [comment]
On 08.03.2017 14:24, Hai Nguyen wrote:
> but why not jus using |pip|? it's pure python and javascript.
>
> |nglview| does not require specific version of numpy.
>
>     we're not (yet) willing supporting all of pyemma's dependencies in
>     bioconda.
>
> |conda install -c bioconda nglview|
>
> PS: Not supporting pyhton 3.6 yet but |pip| is a friend here.
>

Thanks for this suggestion, but we really want to declare all of your 
dependencies within the conda recipe, which we cant for a pypi package. 
Cross-channel dependencies are also hard to maintain, maybe there will 
be a feature for conda some day (like selectors, but for channels).

**Comment by hainm** [comment]
I see. One more important reason that I prefer bioconda because people get used to install nglview from that channel and not everyone read the README file for changes.

**Comment by hainm** [comment]
> Cross-channel dependencies are also hard to maintain, maybe there will
be a feature for conda some day (like selectors, but for channels).

FYI: I just double-check the installation and turns out that there is no cross-channel dependency here.

`conda install -c bioconda nglview` should be enough. A new recipe is being updated to work with any python version (https://github.com/bioconda/bioconda-recipes/pull/4065).

**Comment by gph82** [comment]
@marscher: I agree to be mantainer

**Pull request merged**
