### PR TITLE
Add r-riskregression.

### PR DESCRIPTION
**Pull request by cbrueffer**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble be please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dbast** [comment]
Requires r-publish to be added to conda-forge.

**Comment by cbrueffer** [comment]
Good spotting, thanks! Added in https://github.com/conda-forge/staged-recipes/pull/13259

**Comment by dbast** [comment]
Updated r-timereg... lets see if that helps.

**Comment by dbast** [comment]
osx error:
```
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package ‘riskRegression’
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘magrittr.dylib’ not found
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace -> library.dynam
Execution halted
```

**Comment by cbrueffer** [comment]
Common error at the moment, maybe we need to rebuild `r-magrittr` for some reason.

**Pull request merged**
