### PR TITLE
Added recipe for jira

### PR DESCRIPTION
**Pull request by pmlandwehr**
Pinging @ssbarnea in case they'd like to be added as a maintainer to the `jira` builder on [conda-forge](http://conda-forge.github.io), a library of community-built [`conda`](http://conda.pydata.org) packages. The maintenance burden here is light: all testing and releases are built and deployed automatically with CI. Changes to how the package is being built can be controlled by changing the recipe which will be located at https://github.com/conda-forge/jira-feedstock shortly after this PR is finished and merged. If you aren't interested in helping maintain the build, that's entirely fine too.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
`jira` wants `filemagic`. `filemagic`. `filemagic` requires an install of [`libmagic`](https://filemagic.readthedocs.io/en/latest/guide.html), and I'm not certain how to contend with that issue for the moment.

**Comment by pmlandwehr** [comment]
Got a WIP pull for filemagic: [pull 1392](https://github.com/conda-forge/staged-recipes/pull/1392). That said, since I'm still not sure how to fix this, It'll probably stagnate for some more time.

**Comment by parente** [comment]
FWIW, the filemagic dependency is optional in the jira client.py (https://github.com/pycontribs/jira/blob/ebe1c3f7c59501f667aad3fc4720b618e050cee3/jira/client.py#L2111). It's only used to determine file types when available. Otherwise, the code falls back on using the std lib python mimetypes module (https://github.com/pycontribs/jira/blob/ebe1c3f7c59501f667aad3fc4720b618e050cee3/jira/client.py#L2131-L2135). It's not clear why filemagic is needed at all. (Better mimetype guessing?)

So maybe we can get this recipe going without the filemagic depedency?

/cc @jakirkham @ericdill

**Pull request closed without merging**
