### PR TITLE
add r-gridextra r-hexbin r-htmltools r-httpuv r-httr r-hunspell

### PR DESCRIPTION
**Pull request by bgruening**
r-gridextra
r-hexbin
r-htmltools
r-httpuv
r-httr
r-hunspell

xref: https://github.com/conda-forge/staged-recipes/issues/2009

### CODE REVIEW

**Comment by isuruf** [comment]
appveyor build of `r-gdata-feedstock` failed due to a network error. I've restarted it.

**Comment by bgruening** [comment]
@isuruf This was my mistake I think we skip win builds for the packages entirely.

**Comment by isuruf** [comment]
That comment was not meant for this PR

**Comment by bgruening** [comment]
@isuruf can you please restart the CCI build. Thanks.

**Comment by bgruening** [comment]
@isuruf thanks. It's green now!

**Comment by bgruening** [comment]
@johanneskoester @jakirkham ready for merging.

**Pull request merged**
