### PR TITLE
Add useq-schema recipe

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by goanpeca** [comment]
@tlambert03 do you agree to be added as a maintainer of this package?

**Comment by tlambert03** [comment]
i do!  thanks!

**Review by tlambert03 — APPROVED** [review]

**Comment by ngam** [comment]
@goanpeca you opened 81 pull requests in the past day or so. _81_. They all seem to be related, so why not add them all at once in one PR? It would make the lives of @conda-forge/staged-recipes and @conda-forge/core easier.

**Comment by goanpeca** [comment]
@ngam thanks for the suggestion, we are in the process of doing a "mass migration" of napari plugins to conda packages. 
They are related but not necessarily something that makes sense to bundle.

@jaimergp will be reviewing and merging these PRs

**Comment by ngam** [comment]
I didn't mean one recipe; I meant one (or fewer than 81 PRs). Like this: https://conda-forge.org/docs/maintainer/adding_pkgs.html#adding-multiple-packages-at-once

**Comment by ngam** [comment]
But things should be good, good luck :)

**Comment by jaimergp** [comment]
Don't worry @ngam - we are aware. There are different reasons why this is not being done multi-recipe:

* Github API has some rate limiting, so merging a 80+ recipe PR would have issues with feedstock creation
* The suggestion is to add a maximum of 10 recipes per PR to avoid this ^ issue
* However, as upstream maintainers are being asked to opt-in as recipe maintainers and it would be hard to track the notifications if several unrelated people had to be notified in the same PR.

It's a lot of noise so apologies for that! I'll be handling this so no worries :)

**Comment by ngam** [comment]
> Don't worry

Yes, once I realized this was part of a plan and it's coordinated, it's all good :)

I was just initially worried about overwhelming the reviewers, etc., but it is clear this is the correct strategy for your specific case. Best of luck!

**Comment by goanpeca** [comment]
>I didn't mean one recipe; I meant one PR (or fewer than 81 PRs). Like this: conda-forge.org/docs/maintainer/adding_pkgs.html#adding-multiple-packages-at-once

Yes sorry I meant one PR :)

**Pull request merged**
