### PR TITLE
Create recipe for R rxode

### PR DESCRIPTION
**Pull request by PertuyF**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Created using bgruening/conda_r_skeleton_helper, builds locally.

### CODE REVIEW

**Comment by PertuyF** [comment]
A couple dependencies exist in `r` channel for R 3.6 only.

What would be the recommended way to restrict build to R 3.6 @conda-forge/help-r ? I had troubles with windows builds using `r-base >=3.6` in requirements.

**Comment by cbrueffer** [comment]
All dependencies must be present in the `conda-forge` channel, since the `r` channel is not a prerequisite. If one of the dependencies is only available for R >= 3.6, the `r-base` minimum version dependency should be adapted accordingly.

**Comment by PertuyF** [comment]
@cbrueffer unfortunately, windows builds were failing when forcing `r-base >=3.6` due to an invalid file name where `>=` symbols were included:

```
Renaming work directory,  C:\Miniconda\conda-bld\r-rxode_1578322233430\work  to  C:\Miniconda\conda-bld\r-rxode_1578322233430\work_moved_r-rxode-0.9.1_8-r>=36h5b3a9a7_0_win-64_main_build_loop
Traceback (most recent call last):
  File "C:\Miniconda\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Miniconda\\conda-bld\\r-rxode_1578322233430\\work' -> 'C:\\Miniconda\\conda-bld\\r-rxode_1578322233430\\work_moved_r-rxode-0.9.1_8-r>=36h5b3a9a7_0_win-64_main_build_loop'
```
Is it a known issue?

**Comment by cbrueffer** [comment]
@PertuyF yes, we're seeing this in other R feedstocks as well, I don't think anyone has figured out yet what's going wrong.

**Comment by PertuyF** [comment]
@conda-forge-admin, please rerender

**Comment by PertuyF** [comment]
@cbrueffer looks like `conda-forge.yml` can't be used in staged recipes, and now I get a failure on Linux64 when using `r-base 3.6`. Any solution in mind?

**Comment by cbrueffer** [comment]
@PertuyF yes, please follow Natasha's example here: https://github.com/conda-forge/r-depmixs4-feedstock/pull/6

**Comment by cbrueffer** [comment]
@PertuyF sorry, my suggestion in the linked PR didn't actually work. If you explicitly skip 3.5.1 instead of 3.5* it should work.

**Comment by npavlovikj** [comment]
@PertuyF , just for fun, can you please try Christian's suggestion but with `skip: True  # [r_base == "3.5.*"]` instead? (please note the dot before *)

**Comment by cbrueffer** [comment]
@npavlovikj tried that one in another feedstock, but it didn't work.

**Comment by npavlovikj** [comment]
> @npavlovikj tried that one in another feedstock, but it didn't work.

I tried building this recipe locally using `bioconda-utils`, and it built correctly, that is why I suggested it. But I just realized that `bioconda` is not using 3.5 anymore, so that is why it probably worked...

**Comment by PertuyF** [comment]
Thanks @cbrueffer and @npavlovikj , unfortunately I now get a (new) library error on Linux:

```
INFO conda_build.build:bundle_conda(891): Packaging r-rxode-0.9.1_8-r36h6786f55_0
Packaging r-rxode-0.9.1_8-r36h6786f55_0
number of files: 51
Warning: rpath /home/conda/staged-recipes/build_artifacts/r-rxode_1579630946068/_build_env/lib is outside prefix /home/conda/staged-recipes/build_artifacts/r-rxode_1579630946068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla (removing it)
  ERROR :: lib/R/lib/libR.so not in prefix_owners
   INFO (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO lib/R/lib/libR.so found in conda-forge::r-base-3.6.2-h3a67422_0
   INFO (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_4
   INFO (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO lib/libstdc++.so.6 found in conda-forge::libstdcxx-ng-9.2.0-hdf63c60_2
   INFO (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_4
   INFO (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO lib/libopenblas.so.0 found in conda-forge::libopenblas-0.3.7-h5ec1e0e_6
   INFO (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_4
   INFO (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO lib/libgcc_s.so.1 found in conda-forge::libgcc-ng-9.2.0-h24d8f2e_2
  ERROR (r-rxode,lib/R/library/RxODE/libs/RxODE.so): Needed DSO lib/libgomp.so.1 found in ['_openmp_mutex']
  ERROR (r-rxode,lib/R/library/RxODE/libs/RxODE.so): .. but ['_openmp_mutex'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
WARNING (r-rxode): dso library package conda-forge::libgfortran-ng-7.3.0-hdf63c60_4 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-digest-0.6.23-r36h0357c0b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-sys-3.3-r36hcdcec82_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-rcpp-1.0.3-r36h0357c0b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-mvnfast-0.2.5-r36h0357c0b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-ggforce-0.3.1-r36h0357c0b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-precisesums-0.3-r36hcdcec82_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-dparser-0.1.8-r36hcdcec82_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-matrix-1.2_18-r36hcdcec82_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-units-0.6_5-r36h0357c0b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
   INFO (r-rxode): plugin library package conda-forge::r-rcpparmadillo-0.9.800.3.0-r36h0357c0b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

**Comment by cbrueffer** [comment]
Adding `- _openmp_mutex              # [linux]` works for me in a different feedstock.

**Comment by cbrueffer** [comment]
Looks good now, thanks! It may take longer than usual until packages are available for this, since feedstock conversion doesn't seem to be working at the moment.

**Comment by PertuyF** [comment]
Thanks for the assistance @cbrueffer @npavlovikj

**Pull request merged**
