### PR TITLE
pypi.io -> PyPI.org in example recipe

### PR DESCRIPTION
**Pull request by Carreau**
The io domain has not been used from quite some time; so this will avoid (at least) one redirect.

Note that https://pypi.org/packages/*... redirects to https://files.pythonhosted.org/$1, so maybe we should avoid a second redirect an do that replacement as well ?

I know it's a single redirect and it's not much, but should this be auto-applied to all existing recipes as well ?

### CODE REVIEW

**Comment by Carreau** [comment]
> If these changes are intentional (and you aren't submitting a recipe), please add a `maintenance` label to the PR.

Note that this message should likely be updated as external contributor can't add labels like this.

**Comment by jaimergp** [comment]
> should this be auto-applied to all existing recipes as well ?

This can be added as a hint in the linter. Also, not sure if `grayskull` is still defaulting to `.io` sources.

**Review by jaimergp — APPROVED** [review]

**Comment by Carreau** [comment]
Should we then do a full redirect and replace by `files.pythonhosted.org/<stuff>` ? 

Also any pointer as to where the linter rule would be ?

**Comment by jaimergp** [comment]
I think we are fine with just .org. Given that the equivalent PR in conda-smithy was merged, I'll get this one in too, as is.

**Pull request merged**
