### PR TITLE
Add recipe for r-partitions, conda_r_skeleton used

### PR DESCRIPTION
**Pull request by npavlovikj**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
:tada:

**Comment by npavlovikj** [comment]
Many thanks for the merge @SylvainCorlay !
@conda-forge-admin , is there a reason why the feedstock is not created and the package is not uploaded to the channel although it was merged 2 days ago?

**Comment by xhochy** [comment]
Feedstock was meanwhile created: https://github.com/conda-forge/r-partitions-feedstock

**Comment by npavlovikj** [comment]
Yes, the feedstock was created with only the "win" build though... As per your suggestion @xhochy , I am re-trigerring build for OSX and Linux now.

**Pull request merged**
