### PR TITLE
Add awkward-cpp

### PR DESCRIPTION
**Pull request by henryiii**
Adding awkward-cpp, which is the C++ component of AwkwardArray, preparing for the 2.0 release.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mbargull** [comment]
Copied message from @mbargull at https://gitter.im/conda-forge/conda-forge.github.io?at=6384afcfabfb5860bb37e2ae :
> scikit-build really isn't the place to hack around it.
> I'm also not happy the way `CMAKE_GENERATOR` and similar are set and/or hardcoded in different places. There are at least 3 places that set them:
> - `conda-forge-pinning` sets the NMake default for Windows
> - `conda-build` sets the Unix Makesfiles default for non-Win
> - `vs*_win-64` (from the vc-feedstock) set it to VS if unset
> 
> The `CMAKE_GEN` is essentially a (temporary?) variable in the `vs*` activation scripts that I'm not aware of if used/should be used anywhere else.
> The behavior you encountered (N.B.: it would've been good to link to https://github.com/conda-forge/staged-recipes/pull/21267 in your messages ;) ) is just due to some unfortunate interaction within staged-recipes that is different from what you'd encounter in actual feedstock builds: `conda-build` adds all entries (for the selected platform) from `conda_build_config.yaml` as environment variables during the build. At staged-recipes the `conda-forge-pinning` package is installed for the build and as such you get all those variables set in the environment -- including `CMAKE_GENERATOR=NMake Makefiles` on Windows. Since it gets set by `conda-build` that way, the `vs*` activation script does not `set CMAKE_GENERATOR=%CMAKE_GEN%`. For a build in an actual feedstock repository, only a subset of `conda-forge-pinning`'s `conda_build_config.yaml` is generated by `conda-smithy rerender` which won't set `CMAKE_GENERATOR` by default (i.e., unless read from the recipe YAML/script files).
> If you add `CMAKE_GENERATOR: ''` in the recipe's `conda_build_config.yaml` it probably behaves like you'd want.

**Comment by mbargull** [comment]
> I'm also not happy the way `CMAKE_GENERATOR` and similar are set and/or hardcoded in different places. There are at least 3 places that set them:
> 
> * `conda-forge-pinning` sets the NMake default for Windows
> * `conda-build` sets the Unix Makesfiles default for non-Win
> * `vs*_win-64` (from the vc-feedstock) set it to VS if unset

I wouldn't mind if you'd open issues in the repositories mentioned above so we can come up with a cleaner and more consistent solution to this problem. (and ping me and -- if he's available -- `@isuruf` because he probably has a better overview on how/where `CMAKE_GENERATOR` is used in other feedstocks etc.).

**Comment by henryiii** [comment]
Is `CMAKE_GENERATOR` really needed? Conda-build shouldn't be touching it, since "Unix Makefiles" is already the CMake default, and it breaks the ability of scikit-build or scikit-build-core to depend on `ninja` and use that if no default is set (since a default is set, just incorrectly). And it's ridiculous to set it to "Unix Makefiles" if `make` isn't even in your environment (and `ninja` is, for example)!

For `conda-forge-pinning`, the "NMake Makefiles" is broken (since `CMAKE_GENERATOR_*` are set by `vs*_win-64`, and setting it breaks `vs*_win-64`'s activation. And it sounds like staged-recipes could be broken but the created recipe would work.

`vs*_win-64` setting it seems quite reasonable. Also, on Windows, the default is tricky in CMake - it checks the registry for VS, and if it can't find it, the default is NMake Makefiles (and the bittiness in `CMAKE_GENERATOR_PLATFORM` is useful too).

I am setting temporary workaround in scikit-build-core, since it's very important for me that it work out of the box correctly. I think, from the above, we should try to get it removed in `conda-forge-pinning` and `conda-build`?

**Comment by henryiii** [comment]
Will reopen once scikit-build-core rebuilds)

**Comment by henryiii** [comment]
I believe I can't actually patch out the `CMAKE_GENERATOR` setting from conda-build, forcing the use of `make` over `ninja` if it's not fixed upstream. :(

**Comment by henryiii** [comment]
@conda-forge/help-python this ready for review! @agoose77 If you add yourself to the regular awkward feedstock you'll get access to this one too.

**Comment by henryiii** [comment]
(just restarting to make sure this is fine with scikit-build-core 0.1.2)

**Comment by henryiii** [comment]
Anything needed here? Awkward 2 is planning to ship early Dec.

**Comment by henryiii** [comment]
@conda-forge/help-python https://github.com/conda-forge/awkward-feedstock/pull/89 is blocked on this.

**Comment by beckermr** [comment]
Happy new year!

**Comment by beckermr** [comment]
It reruns itself. We'll have to wait.

**Pull request merged**
