### PR TITLE
coloredlogs

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @rsignell-usgs

### CODE REVIEW

**Comment by ocefpaf** [comment]
On Windows only `TARGET_ARCH=x64, CONDA_PY=34` is passing. That is where we are pinning to an older version of `conda-build` (`1.20.0`).

@patricksnape and @msarahan any ideas? I will skip Windows for now.

```shell
Package: humanfriendly-1.44.7-py27_0
source tree in: C:\Miniconda\conda-bld\work\humanfriendly-1.44.7
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-all-script.py", line 9, in <module>
    load_entry_point('conda-build-all==0.13.0', 'console_scripts', 'conda-build-all')()
  File "C:\Miniconda\lib\site-packages\conda_build_all\cli.py", line 85, in main
    b.main()
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 224, in main
    built_dist_location = self.build(meta)
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 181, in build
    return bldpkg_path(build.build(meta.meta))
  File "C:\Miniconda\lib\site-packages\conda_build_all\build.py", line 32, in build
    build_module.build(meta, post=None, need_source_download=True, **kwd)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 573, in build
    windows.build(m, build_file, dirty=dirty, activate=activate)
  File "C:\Miniconda\lib\site-packages\conda_build\windows.py", line 207, in build
    fo.write(msvc_env_cmd(bits=cc.bits, override=m.get_value('build/msvc_compiler', None)))
  File "C:\Miniconda\lib\site-packages\conda_build\windows.py", line 114, in msvc_env_cmd
    vcvarsall_vs_path = build_vcvarsall_vs_path(version)
  File "C:\Miniconda\lib\site-packages\conda_build\windows.py", line 75, in build_vcvarsall_vs_path
    PROGRAM_FILES_PATH = os.environ['ProgramFiles']
KeyError: 'ProgramFiles'
```

**Comment by patricksnape** [comment]
Is it something to do with the resolution order? Failure I'm seeing for the latest build, Python 2.7 x86 appears to be because it can't find `humanfriendly` which is in the list of packages to be built? As a note, the builds using the latest `conda-build` installed  `conda-build-all=0.13.0` where as the `conda-build=1.20.0` installed `conda-build-all=0.13.1` which is then downgraded to `conda-build-all=0.11.0`.

**Comment by ocefpaf** [comment]
Nope. I am skipping it now and we are hitting another bug. Where even though we skip a build it still tries to build it. (Solved in the latest `conda-build-all`, but the latest `conda-build-all` is not available for all Archs because of another bug...)

The error when I do not skip is in https://github.com/conda-forge/staged-recipes/pull/1111#issuecomment-234246070

PS: As soon as Travis-CI passes I will merge this and try again the Windows build on the feedstock so we can isolate the issue.

**Comment by patricksnape** [comment]
Looks like some env variables aren't getting propagated correctly because 'ProgramFiles' or `ProgramFiles(x86)` should *definitely* be there.

**Comment by ocefpaf** [comment]
> Looks like some env variables aren't getting propagated correctly because `ProgramFiles` or `ProgramFiles(x86)` should *definitely* be there.

Thanks. I don't need Windows there so skipping is fine for now. If this is a bug in `conda-build` I can open the issue later xref-ing the build in the feedstock.

**Comment by jakirkham** [comment]
@xolox, just letting you know we have added `coloredlogs` to [conda-forge]( http://conda-forge.github.io/ ). This will allow users to easily install this with [`conda`]( http://conda.pydata.org/docs/ ) (`conda install -c conda-forge coloredlogs`). The maintenance burden here is light as all testing releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this repo]( https://github.com/conda-forge/coloredlogs-feedstock ). If you have any interest in being added as a maintainer (to make new releases for instance), we would love to have you on board. Thanks for your work on `coloredlogs`. 😄

**Pull request merged**
