### PR TITLE
Added a recipe for dynamicisttoolkit.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
I'm not sure what to do about this linter. The name of the license for this package contains the word license.

**Comment by isuruf** [comment]
Looks good to me. If you can remove all the unnecessary comments, we can merge

**Comment by moorepants** [comment]
Done.

**Comment by isuruf** [comment]
I'll merge once the tests pass

**Comment by moorepants** [comment]
Thanks.

**Comment by moorepants** [comment]
What's up with the http errors on appveyor? I'm getting that on a number of conda-forge repos.

**Pull request merged**
