### PR TITLE
Add vulkan-volk

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@libvulkan-loader @libvulkan-headers  I would appreciate your review here, it seems like this is now a dependency of https://github.com/conda-forge/vulkan-tools-feedstock/pull/8

**Comment by hmaarrfk** [comment]
@conda-forge/vulkan-loader @conda-forge/vulkan-headers

**Review by xhochy — APPROVED** [review]

**Review by traversaro — APPROVED** [review]
The recipe seems fine! Just to understand, what is the reason why this needs to be a static library?

**Comment by hmaarrfk** [comment]
> The recipe seems fine! Just to understand, what is the reason why this needs to be a static library?

https://github.com/zeux/volk?tab=readme-ov-file#building

This is all i know. I had opened PRs but they seem to include a `volk.c` inside the `volk.h` file, so I figured this was likely some super trickery that was being made..... didn't seem safe to deviate too much from upstream.

I had opened PRs https://github.com/zeux/volk/pull/202 https://github.com/zeux/volk/pull/201 but i figured i would use them as intended first, then make recommendations.

**Comment by hmaarrfk** [comment]
Thanks you two, let me know if you want to help maintain downstream by pinging me on the feedstock

**Pull request merged**
