### PR TITLE
add mkdocstrings-python-legacy, mkdocstrings-python, and griffe

### PR DESCRIPTION
**Pull request by bandersen23**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bandersen23** [comment]
@conda-forge/help-python - This is ready for review 😄 Thanks!

**Comment by hadim** [comment]
LGTM for me (not a conda forge reviewer but FYI).

Do you think [mkdocstrings-python ](https://github.com/mkdocstrings/python )and [griffe](https://github.com/mkdocstrings/griffe) should be packaged as well? Those are optional deps mkdocstrings, but I feel like users might want to have them by default too.

**Comment by bandersen23** [comment]
I'm working on that for a different PR now. Probably submitted later today.

**Comment by hadim** [comment]
Thanks for the work @bandersen23 !

**Comment by bandersen23** [comment]
@conda-forge/staged-recipes - This should be ready whenever you have a chance! Thank you so much! 

This is for https://github.com/conda-forge/mkdocstrings-feedstock/issues/19#issuecomment-1059809790.

**Comment by bandersen23** [comment]
@conda-forge/staged-recipes This is ready to review! Thank you so much!

This is for: https://github.com/conda-forge/mkdocstrings-feedstock/issues/19#issuecomment-1059809790

**Comment by hadim** [comment]
@conda-forge/staged-recipes the three feedstocks have an empty repo:

- https://github.com/conda-forge/griffe-feedstock
- https://github.com/conda-forge/mkdocstrings-python-feedstock
- https://github.com/conda-forge/mkdocstrings-python-legacy-feedstock

**Comment by bandersen23** [comment]
Good catch. @chrisburr thanks for approving! Any idea why this might be? I know there's a lot going on so I wonder if the CI is busy?

**Comment by BastianZim** [comment]
You can follow the logs of the CI here: https://github.com/conda-forge/staged-recipes/actions
Seems like some rate-limiting, should resolve itself in a couple of hours.

**Comment by bandersen23** [comment]
Awesome! I didn't know that, thanks for sharing!

**Comment by bandersen23** [comment]
I looked at the logs for these three packages and they keep getting errors on the feedstock creation (I copied the error from one of the three feedstocks, but these three seem to be getting it:

```bash
CI Summary for conda-forge/mkdocstrings-python-legacy-feedstock (can take ~30s):
[1264](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1264)
Traceback (most recent call last):
[1265](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1265)
  File "/home/runner/Mambaforge/bin/conda-smithy", line 10, in <module>
[1266](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1266)
    sys.exit(main())
[1267](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1267)
  File "/home/runner/Mambaforge/lib/python3.9/site-packages/conda_smithy/cli.py", line 681, in main
[1268](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1268)
    args.subcommand_func(args)
[1269](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1269)
  File "/home/runner/Mambaforge/lib/python3.9/site-packages/conda_smithy/cli.py", line 296, in __call__
[1270](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1270)
    ci_register.travis_configure(owner, repo)
[1271](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1271)
  File "/home/runner/Mambaforge/lib/python3.9/site-packages/conda_smithy/ci_register.py", line 504, in travis_configure
[1272](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1272)
    response.raise_for_status()
[1273](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1273)
  File "/home/runner/Mambaforge/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
[1274](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1274)
    raise HTTPError(http_error_msg, response=self)
[1275](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1275)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.com/repo/22901922/setting/builds_only_with_travis_yml
[1276](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1276)
Traceback (most recent call last):
[1277](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1277)
  File "/home/runner/work/staged-recipes/staged-recipes/.travis_scripts/create_feedstocks.py", line 283, in <module>
[1278](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1278)
    subprocess.check_call(
[1279](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1279)
  File "/home/runner/Mambaforge/lib/python3.9/subprocess.py", line 373, in check_call
[1280](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1280)
    raise CalledProcessError(retcode, cmd)
[1281](https://github.com/conda-forge/staged-recipes/runs/5465015290?check_suite_focus=true#step:6:1281)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--without-appveyor', '--without-webservice', '--feedstock_directory', '/tmp/tmp9cn24gzc__feedstocks/mkdocstrings-python-legacy-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1.
```

**Comment by BastianZim** [comment]
Yeah, that happens from time to time, unfortunately. Generally, this resolves itself after some hours, otherwise you can post in the gitter chat and someone from the respective team will have a look.

**Comment by bandersen23** [comment]
Great, I'll check it later tonight and see how it's doing! 👍

**Comment by bandersen23** [comment]
@conda-forge/core - any thoughts on why these three recipe are not getting built? I just checked and noticed they still haven't been built, but they have an empty git repo. Is it a problem that the git repo was already created? They've been merged in for ~24 hours now and I keep seeing the same error on the `create feedstocks` action. Thank you 🙂

**Pull request merged**
