### PR TITLE
Add prison

### PR DESCRIPTION
**Pull request by xylar**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xylar** [comment]
The repo doesn't yet have a license file.  I will try to work with the developer to add one.

**Comment by xylar** [comment]
@betodealmeida, again, your help with the license would be greatly appreciated.  Also, if you would like to be a maintainer of the conda-forge package, let me know and I'll add you.

**Comment by chrisburr** [comment]
[The `setup.py` file states MIT.](https://github.com/betodealmeida/python-rison/blob/master/setup.py#L94)

**Comment by xylar** [comment]
@chrisburr, thanks very much for noticing that.  I've added the MIT license file (and included it in a PR to the developer's repo as well).

**Comment by xylar** [comment]
@chrisburr (or @conda-forge/help-python), this is ready to review.

**Comment by xylar** [comment]
Thanks again @chrisburr.

**Pull request merged**
