### PR TITLE
Add recipe for morfessor

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by souravsingh** [comment]
Pinging @psmit for review of the conda recipe

**Comment by synapticarbors** [comment]
Looks good to me to merge as long as @psmit gives the ok that they are ok being a co-maintainer.

**Comment by psmit** [comment]
Sure, that is ok by me. I assume the main responsibility is to keep the version number up to date?

**Comment by synapticarbors** [comment]
@psmit -- basically that is the main role. Also you might occasionally get an automated PR to "re-render" the recipe, which involves changes to the CI machinary and not to the package. See:

https://conda-forge.org/docs/recipe.html#maintainer-role

**Comment by psmit** [comment]
Ok, that is fine by me!

**Pull request merged**
