### PR TITLE
Add conda-forge recipt for sos-bash

### PR DESCRIPTION
**Pull request by BoPeng**
Checklist

- [x ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x ] Source is from official source
- [x ] Package does not vend other packages
- [ x] Build number is 0
- [ x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Pending PR #9348 for `bash_kernel`.

### CODE REVIEW

**Comment by BoPeng** [comment]
@conda-forge/help-python This is ready to be reviewed. It is a `noarch:python` with failed tests under windows due to lack of bash.

**Comment by BoPeng** [comment]
Ping @conda-forge/help-python again just in case this recipe is being ignored because of failed tests. Also mentioning #9369, which is also ready to be reviewed.

**Comment by scopatz** [comment]
There is git-bash on windows you could depend on as well as a bash package for other OSes

**Comment by BoPeng** [comment]
Indeed, but what is the use of https://anaconda.org/conda-forge/bash since bash is available on mac and linux anyway?

**Comment by BoPeng** [comment]
Also I have to remove `noarch: python` because of the `[win]` selector. Let us see if `sos-bash` works with `git-bash`.

**Comment by BoPeng** [comment]
`bash_kernel` does not work with `git-bash`, so `sos-bash` would not work with `git-bash` either. This is a no-go so I have reverted the patch.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
