### PR TITLE
add python-twitter recipe

### PR DESCRIPTION
**Pull request by gboeing**

### CODE REVIEW

**Comment by gboeing** [comment]
@conda-forge/staged-recipes I added all the requirements from setup.py into the meta.yaml file, but the tests fail with the error:

```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/pytest-runner/
```

Any suggestions?

**Comment by gboeing** [comment]
@isuruf that didn't seem to fix it

**Comment by isuruf** [comment]
It did fix the error you mentioned.

New error is,
```
    import python-twitter
                 ^
SyntaxError: invalid syntax
```

**Comment by gboeing** [comment]
@isuruf ah, of course. Thank you. This is ready to merge now.

**Pull request merged**
