### PR TITLE
ENH add pytest-session2file

### PR DESCRIPTION
**Pull request by beckermr**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by beckermr** [comment]
Alright @conda-forge/staged-recipes @conda-forge/core, this one a little tricky.

1. This project appears largely abandoned but I would very much like it in conda.
2. The `setup.py` lists the license as LGPLv3, but the project itself doesn't have a copy of the license in it. I have made an issue on this upstream: https://github.com/BuhtigithuB/pytest_session2file/issues/9 and included the license text in the recipe.
3. The project needs a patch to run on python 3. This patch is on master, but a release has not been made since 2016 (!!!!). Thus I have included the python 3 patch in the recipe. I have also made an issue on this: https://github.com/BuhtigithuB/pytest_session2file/issues/8
4. The project is a pytest plugin and I am not sure how to ship it as noarch and properly list the entry point. Thus I am not using noarch right now.

Thus my question for @conda-forge/core is, can we ship this package? It is clear that it is meant to be LGPLv3 from the code and the repo is basically abandoned. It is currently distributed on pypi without the license text as well.

My question for @conda-forge/staged-recipes, how do we do noarch with pytest plugins? I could not find an example where the entry point was listed.

**Comment by beckermr** [comment]
@brianv0 for viz

**Comment by chrisburr** [comment]
4. Only console_scripts entry points need special handling so this can be noarch

The rest seems reasonable to me. I’m happy to merge it after giving upstream a few days to comment provided no one objects.

**Comment by beckermr** [comment]
Great @chrisburr! I went ahead and changed the recipe to noarch!

**Comment by mbargull** [comment]
> Only console_scripts entry points need special handling so this can be noarch

+1

> I'm happy to merge it after giving upstream a few days to comment provided no one objects.

IMO, there is no need to wait here (<- coming from someone who usually doesn't take licensing issues lightly).
*Both* readme files, `setup.py`, as well as the source code itself say "LGPLv3 (http://www.gnu.org/licenses/lgpl.html)" without any other license mentioned.
So this is a pretty clear/unambiguous case here. Feel free to merge!

**Comment by beckermr** [comment]
Thanks everyone!

**Comment by BuhtigithuB** [comment]
Hi guys,

Will try to give it a little attention, if you need it, sorry, I am not having much time in my life for open source as much as I would like :(

**Pull request merged**
