### PR TITLE
Add cinnabar

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@IAlibay @richardjgowers @dwhswenson @RiesBen
Please post a comment confirming you are willing to be listed as a maintainer

**Comment by IAlibay** [comment]
I confirm that I am willing to be a maintainer.

**Comment by mikemhenry** [comment]
> Build number is 0.

We are making a new feedstock so it matches our new package name. We are forking the old package name and will use that old feedstock to publish packages. Because of this, `cinnabar` version `0.2.3` build number `1` exits, so I am bumping the build number to `2`. That way it doesn't overwrite the old package.

**Comment by RiesBen** [comment]
I confirm :)

**Comment by richardjgowers** [comment]
yep all good, thanks Mike

**Comment by dwhswenson** [comment]
Maintainerize me!

(I'm willing to be a maintainer for this)

**Comment by mikemhenry** [comment]
Cool, I'll do that then ping the conda-forge team for review

**Comment by mikemhenry** [comment]
@@conda-forge/help-python ready for review!

**Comment by xhochy** [comment]
CI is failing

**Comment by mikemhenry** [comment]
@xhochy sorry about that! Ready for re-review!

**Pull request merged**
