### PR TITLE
Add python-fire

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes why is this requiring https://files.pythonhosted.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz#md5=baa81e951a29958563689d868ef1064dr

It is not listed in the reqs for fire.

**Comment by jjhelmus** [comment]
`python-fire` seems to use `setuptools` for its install.  I needs to be added as a build requirement.  That should fix the downloading of `certifi`.  Additionally the install line should likely be changed to `python setup.py install --single-version-externally-managed --record record.txt`.

**Comment by CJ-Wright** [comment]
Ah, thank you @jjhelmus. Also it doesn't have a licence in the release I have requested one so maybe for the next build? https://github.com/google/python-fire/issues/81

**Comment by jjhelmus** [comment]
LGTM, just waiting on AppVeyor.  The missing license file is fine for now but thanks for requesting one.

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
