### PR TITLE
Adding m3gnet

### PR DESCRIPTION
**Pull request by shyuep**
Checklist
- [X ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sgbaird** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=522973&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd
```python
2022-06-17T02:09:51.9276145Z export PREFIX=/home/conda/staged-recipes/build_artifacts/m3gnet_1655431566504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
2022-06-17T02:09:51.9278156Z export SRC_DIR=/home/conda/staged-recipes/build_artifacts/m3gnet_1655431566504/test_tmp
2022-06-17T02:09:52.8934958Z import: 'm3gnet'
2022-06-17T02:09:52.8937511Z import: 'm3gnet.graph'
2022-06-17T02:09:55.1529868Z import: 'm3gnet.layers'
2022-06-17T02:09:55.1567601Z import: 'm3gnet.models'
2022-06-17T02:09:55.1723656Z import: 'm3gnet.trainers'
2022-06-17T02:09:55.1800374Z 2022-06-17 02:09:55.179316: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2022-06-17T02:09:55.1803708Z To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-17T02:09:55.1828175Z import: 'm3gnet.utils'
2022-06-17T02:09:55.1829346Z import: 'm3gnet'
2022-06-17T02:09:55.1830053Z import: 'm3gnet.graph'
2022-06-17T02:09:55.1830755Z import: 'm3gnet.layers'
2022-06-17T02:09:55.1831450Z import: 'm3gnet.models'
2022-06-17T02:09:55.1832119Z import: 'm3gnet.trainers'
2022-06-17T02:09:55.1832792Z import: 'm3gnet.utils'
2022-06-17T02:09:55.6307935Z + pip check
2022-06-17T02:09:56.3729735Z tensorflow 2.4.3 has requirement absl-py~=0.10, but you have absl-py 1.1.0.
2022-06-17T02:09:56.3732802Z tensorflow 2.4.3 has requirement wrapt~=1.12.1, but you have wrapt 1.14.1.
2022-06-17T02:09:58.1366044Z Tests failed for m3gnet-0.0.5-py39hac2352c_0.tar.bz2 - moving package to /home/conda/staged-recipes/build_artifacts/broken
2022-06-17T02:09:58.1367874Z WARNING:conda_build.build:Tests failed for m3gnet-0.0.5-py39hac2352c_0.tar.bz2 - moving package to /home/conda/staged-recipes/build_artifacts/broken
2022-06-17T02:09:58.1713687Z TESTS FAILED: m3gnet-0.0.5-py39hac2352c_0.tar.bz2
2022-06-17T02:10:05.2683589Z ##[error]Bash exited with code '1'.
2022-06-17T02:10:05.2753268Z ##[section]Finishing: Run docker build
2022-06-17T02:10:05.2842482Z ##[section]Starting: Checkout conda-forge/staged-recipes@refs/pull/19315/merge to s
2022-06-17T02:10:05.2849307Z ==============================================================================
2022-06-17T02:10:05.2849759Z Task         : Get sources
2022-06-17T02:10:05.2850103Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2022-06-17T02:10:05.2850462Z Version      : 1.0.0
2022-06-17T02:10:05.2850729Z Author       : Microsoft
2022-06-17T02:10:05.2851085Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2022-06-17T02:10:05.2851508Z ==============================================================================
2022-06-17T02:10:05.5890584Z Cleaning any cached credential from repository: conda-forge/staged-recipes (GitHub)
2022-06-17T02:10:05.6008294Z ##[section]Finishing: Checkout conda-forge/staged-recipes@refs/pull/19315/merge to s
2022-06-17T02:10:05.6061091Z ##[section]Starting: Finalize Job
2022-06-17T02:10:05.6090671Z TestResultLogParser: JasmineTestResultParser : Starting jasmine test result parser.
2022-06-17T02:10:05.6091045Z TestResultLogParser: JestTestResultParser : Starting jest test result parser.
2022-06-17T02:10:05.6091409Z TestResultLogParser: MochaTestResultParser : Starting mocha test result parser.
2022-06-17T02:10:05.6091791Z TestResultLogParser: PythonTestResultParser : Starting python test result parser.
2022-06-17T02:10:05.8590738Z TestResultLogParser: Waiting for log plugin to finish, pending process 10 log lines.
2022-06-17T02:10:05.9954238Z Cleaning up task key
2022-06-17T02:10:05.9955814Z Start cleaning up orphan processes.
2022-06-17T02:10:06.0444734Z ##[section]Finishing: Finalize Job
2022-06-17T02:10:06.0483443Z ##[section]Finishing: linux_64
```

**Comment by sgbaird** [comment]
Any idea what happened with Windows? The logs are kind of strange/unhelpful:

image

But then it shows "no logs" and that it was cancelled instead of failed?

image

**Comment by sgbaird** [comment]
Since it's possible it's an [issue with azure](https://github.com/conda-forge/staged-recipes#11-some-checks-failed-but-it-wasnt-my-recipe-how-do-i-trigger-a-rebuild), though I'm not sure it will let me.

@conda-forge-admin, please restart ci

**Comment by sgbaird** [comment]
@conda-forge/python

**Comment by jakirkham** [comment]
@conda-forge-admin, please ping team

**Pull request merged**
