### PR TITLE
ulmo and dependencies

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @dharhas. Want to be the maintainer of this recipe at conda-forge? (I can explain the details of conda-forge in a e-mail later. It is the next step for a better conda community channel and will supersede the IOOS channel.)

### CODE REVIEW

**Comment by ocefpaf** [comment]
@msarahan I had to add (and bump) a recipe for `suds-jurko` to circumvent [this](https://circleci.com/gh/conda-forge/staged-recipes/680). I guess something is not right with `suds-jurko` in the default channel.

**Comment by ocefpaf** [comment]
@pelson I will hold of merging this one until we figure out a better strategy for version conflicts.

However, if the problem turns out to be `suds-jurko` from the default channel, this will be the first success story for conda-forge/default channel communications :wink:

**Comment by msarahan** [comment]
Weird.  I built that package as a noarch package not long ago.  Bummer that
there are issues with it.  Please let me know if you discover the cause for
any issues with it - either in a recipe, or in the noarch system.

**Comment by pelson** [comment]
> Weird.  I built that package as a noarch package not long ago.  Bummer that
there are issues with it.  Please let me know if you discover the cause for
any issues with it - either in a recipe, or in the noarch system.

Just from that traceback, it could be that the version isn't py3 compatible (i.e. looks like it could be a relative vs absolute import issue).

**Comment by dharhas** [comment]
@ocefpaf Sure, I can be the maintainer, let me know how y'all are planning things to work with conda-forge

**Comment by ocefpaf** [comment]
@dharhas the gist of conda-forge is to create feedstocks (separate repos for each recipe) that uploads the binaries to the conda-forge channel. Each feedstock has a team of maintainers with commit rights.  The maintainers "job" is to update the recipe. Mostly fixing compilation stuff and pushing new software versions. The maintainers can be the software devs or any user interested into having the binaries available in conda-forge.

The feedstocks are created after the recipe, submitted to [staged-recipes](https://github.com/conda-forge/staged-recipes),  gets merged. [Here](https://github.com/conda-forge/ulmo-feedstock) is ulmo's feedstock. (Please check if you have commit rights there. I added your GitHub handle to the recipe, so you are automatically added to the maintainers team.)

Please feel free to ask me anything about conda-forge either here on GitHub or via e-mail.

**Pull request merged**
