### PR TITLE
Added recipe for Lightwood

### PR DESCRIPTION
**Pull request by paxcema**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by paxcema** [comment]
I confirm I am okay with being listed as recipe maintainer.

**Comment by paxcema** [comment]
@conda-forge-admin, please ping team @conda-forge/help-python

**Comment by paxcema** [comment]
Weirdly, Windows CI fails due to `pytorch` unavailablility. It should be [possible](https://pytorch.org/get-started/locally/), but also depends on CUDA availability. I'm looking at [this](https://github.com/conda-forge/torchvision-feedstock/blob/main/recipe/meta.yaml) recipe, but I'm not sure how to modify the dependency, so any pointers would be appreciated.

**Comment by ocefpaf** [comment]
> Weirdly, Windows CI fails due to `pytorch` unavailablility. It should be [possible](https://pytorch.org/get-started/locally/), but also depends on CUDA availability. I'm looking at [this](https://github.com/conda-forge/torchvision-feedstock/blob/main/recipe/meta.yaml) recipe, but I'm not sure how to modify the dependency, so any pointers would be appreciated.

We don't have pytorch on Windows yet but keeing this one noarch is the way to go. If we have package pytorch on Win this pkg would be "ready" for installation there.

**Comment by paxcema** [comment]
@ocefpaf Thanks! That makes sense.

I tried out the recipe on an M1 Mac, but sadly I'm getting this:

```
(base) patricio@B-Air ~ % conda install -c conda-forge lightwood        
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==12.4=0
  - feature:|@/osx-arm64::__osx==12.4=0
  - lightwood -> pytorch[version='>=1.9.0'] -> __osx[version='>=11.0']

Your installed version is: 12.4

Note that strict channel priority may have removed packages required for satisfiability.
```

Which is a bit odd to me given that `pytorch==1.12.1` [seems to be in `conda-forge`](https://anaconda.org/conda-forge/pytorch) for osx-arm64. Any ideas on what might be the issue?

**Comment by ocefpaf** [comment]
osx-arm64 are not built automatically. You need to send a PR to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt and add your pkg to the list. The bot will send a PR to your feedstock to add it.

**Comment by paxcema** [comment]
Thanks again, @ocefpaf! Made the PR, [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3241).

**Comment by paxcema** [comment]
@ocefpaf do I need to invoke the bot somehow? It's been a few days since the PR was merged but I've received no PRs from it. Maybe a new package release would trigger the check?

(I read the conda-forge maintainer docs but was unable to find an answer to this)

**Comment by ocefpaf** [comment]
There are tons of dependencies there and the bot will send PRs in topological order until it is possible to send one for lightwood. Some of those dependencies look quite hard to build though. You can try to help out fix the osx-arm64 by checking their feedstock.

**Comment by paxcema** [comment]
> There are tons of dependencies there and the bot will send PRs in topological order until it is possible to send one for lightwood.

I think this makes sense, but I want to confirm I've wrapped my head around it. Essentially, you're saying that before opening a PR for Lightwood, the bot has to (recursively) go through all its dependencies and check whether 1) osx-arm64 support is requested, 2) if so, open a PR if there is no osx-arm64 support yet, 3) wait for the maintainer to merge it. Is this correct?

> You can try to help out fix the osx-arm64 by checking their feedstock.

Do you mean that in step 1) I could help by going to conda-forge-pinning-feedstock and adding all the missing packages?

**Pull request merged**
