### PR TITLE
some minor xonsh updates

### PR DESCRIPTION
**Pull request by scopatz**
for new dependencies.

### CODE REVIEW

**Comment by scopatz** [comment]
Woohoo! it passes.

**Comment by ocefpaf** [comment]
In light of the line https://github.com/conda-forge/staged-recipes/pull/24/files#diff-61b978e435f4b6b49ee412fb051179a6R10

Do we need the `bld.bat`?

**Comment by scopatz** [comment]
That was put in by @pelson and unrelated to this PR.

**Comment by scopatz** [comment]
The bld.bat that is.

**Comment by pelson** [comment]
> Do we need the bld.bat?

Yes. This is a bug with conda-build. The Windows build does not make use of the ```script``` section of the meta.yaml. I don't think this is intentional, so I will propose a fix (when I get around to it, unless somebody beats me to it).

**Comment by ocefpaf** [comment]
> Yes. This is a bug with conda-build. 

Thanks for the explanation @pelson!  IMO having all the build instructions/information in a single file is desirable.  (Specially in a simple `python setup.py install` case.)

**Pull request merged**
