### PR TITLE
Add recipe for itk

### PR DESCRIPTION
**Pull request by thewtex**
This re-uses the PyPI packages that wrap the Insight Toolkit (ITK). The
infrastructure is based off the tensorflow conda recipe.

Currently a monolithic package for "itk" in created. In the future, it is
possible to splite it into an itk metapackage and multiple dependent packages,
itk-core, itk-io, itk-segmentation, etc.

Co-authored-by: Eric Dill <thedizzle@gmail.com>

This is a re-submission of #3263 since the feedstock did not get created the first time around due to the existing repository.

CC: @blowekamp @ericdill @jjhelmus @msarahan

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jjhelmus I see that you renamed the feedstock and I believe this PR was already merged at some point. So can you take a quick look and merge this? (I am not familiar with the need for re-packaging here to merge this myself.)

PS: the renamed feedstock may be out of the `feedstocks` repo. Not sure what would take to fix that.

**Comment by thewtex** [comment]
This issue should address the missing `github.com/conda-forge/itk-feedstock` and the missing macOS conda-forge `itk` package that users have been reporting because of a missing Travis build.

**Comment by scopatz** [comment]
Merging this should work.

**Comment by thewtex** [comment]
Thanks, @scopatz !

It looks like the [GitHub repository](https://github.com/conda-forge/itk-feedstock) and [TravisCI](https://travis-ci.org/conda-forge/itk-feedstock) build still did not get created. Maybe they have to be created manually in this situation.

**Comment by scopatz** [comment]
Hmmm @thewtex... I don't know how to fix that. Any ideas @conda-forge/core?

**Comment by isuruf** [comment]
You need to manually create an empty repo, so that the redirection is stopped

**Comment by scopatz** [comment]
And then it will build?

**Comment by isuruf** [comment]
And then this recipe has to readded.

**Comment by scopatz** [comment]
I don't have permissions to create an empty repo

**Comment by isuruf** [comment]
Me neither. @jakirkham, @ocefpaf

**Comment by jakirkham** [comment]
Why is an empty repo needed? Why not just readd?

**Comment by isuruf** [comment]
Because `itk-feedstock` was renamed to `libitk-feedstock` and github adds a redirection. This confuses conda-smithy.

**Comment by jakirkham** [comment]
I see. We need to be more principled about renaming things then.

**Comment by jakirkham** [comment]
Also done. Please go ahead with the readd.

**Comment by thewtex** [comment]
Thanks all. PR for the readd here: https://github.com/conda-forge/staged-recipes/pull/3907

**Pull request merged**
