### PR TITLE
Add py bip39 bindings

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by MementoRC** [comment]
@conda-forge/help-python-c @conda-forge/staged-recipes, Hello ready to review

**Comment by carterbox** [comment]
@MementoRC, when possible, you should use the build tools as specified by the upstream project instead of patching the project to switch or upgrade tools to newer versions. There are exceptions, but I don't think they apply in this case.

In this case, I was able to succesfully build this package by telling conda to use maturin 0.14.0 which fits in the range specified by this package's metadata instead of adding a bunch of patches. If you feel that this project needs your patches, then please open a pull request upstream and have them make a new release.

Please use the feedback in this PR to update your other similar recipes.

**Comment by carterbox** [comment]
LGTM if the builds pass. I'll check later.

**Comment by MementoRC** [comment]
@carterbox , Thank you for your review and overall help in becoming a better contributor. I confess that I came to conda-forge from an incorrect mindset on many levels, as well as poor PR etiquette. Let's hope I can grow from this journey. Thank you

**Comment by carterbox** [comment]
I appreciate your patience and willingness to adapt to our channel's conventions / practices.

**Pull request merged**
