### PR TITLE
added `typepigeon`

### PR DESCRIPTION
**Pull request by zacharyburnett**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by zacharyburnett** [comment]
ok, I'm not sure what I'm doing wrong but it looks like the tests aren't being copied to the `sdist`

I think that's fine though, I've removed the testing step from `meta.yml`

tests for this package are at https://github.com/zacharyburnett/TypePigeon/actions/workflows/tests.yml?query=branch%3Amain+

**Comment by zacharyburnett** [comment]
@conda-forge/staged-recipes this is ready for review, when you get a chance, thanks!

**Review by BastianZim — CHANGES_REQUESTED** [review]

**Comment by BastianZim** [comment]
> ok, I'm not sure what I'm doing wrong but it looks like the tests aren't being copied to the `sdist`, so the `conda-forge` process isn't able to find them and run tests

Yes it's empty: https://files.pythonhosted.org/packages/ec/7a/2210605dedbb6979dcb8a0832aa68bcac4a5c192883d5238ea79888452e5/typepigeon-1.0.9.tar.gz

But this is not a problem. Generally, import and `pip check` is fine. We normally run extensive testing more for compiled packages etc.

**Comment by BastianZim** [comment]
> Please let me know if I'm pinging too much

No worries, all good! Thanks for contributing to conda-forge.

**Comment by zacharyburnett** [comment]
@conda-forge-admin resolved `setuptools >=41.2` and bumped the version

ready to merge now, thanks!

**Pull request merged**
