### PR TITLE
Add R package scatterpie

### PR DESCRIPTION
**Pull request by ryanraaum**
Recipe created with conda-build and conda_r_skeleton_helper

### CODE REVIEW

**Comment by dbast** [comment]
@ryanraaum Your first commit was just fine and ready to merge... no manual change on top is required.... the failing windows build for noarch is a bit misleading and can afaik be ignored for now

**Comment by dbast** [comment]
CIs seem to not work again...

**Comment by dbast** [comment]
@ryanraaum Thanks and welcome at conda-forge!

**Comment by ryanraaum** [comment]
Great! Thanks @dbast !

**Pull request merged**
