### PR TITLE
WIP: package libxar

### PR DESCRIPTION
**Pull request by h-vetinari**
Requested by Isuru [here](https://github.com/conda-forge/lld-feedstock/pull/33#issuecomment-1033486879). Not 100% convinced myself, but want to unblock LLVM work.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@isuruf, I'm not sure why the CommonCrypto headers aren't found.
```
+ make
x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libxar-1.8 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -fPIC -DPIC -dynamic -Iinclude -Iinclude -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -I/Users/runner/mambaforge/include/libxml2 -I/Users/runner/mambaforge/include -c lib/archive.c -o lib/archive.o
In file included from lib/archive.c:64:
lib/archive.h:45:10: fatal error: 'CommonCrypto/CommonDigestSPI.h' file not found
#include <CommonCrypto/CommonDigestSPI.h>
```

Can't find another usable [example](https://github.com/search?q=org%3Aconda-forge+CommonCrypto&type=code) in conda-forge either. Sidenote: even the offical xar from apple doesn't build against our macos sdk anymore...

Linux fails with some openssl issue. Presumably xar was built against an openssl that was quite a bit older (1.0.2?). I also think we should skip linux and just do the minimum to unblock lld on osx.

PS. I added you as a maintainer on this, because you suggested to build it in the first place, and I don't think I can reasonably maintain it by myself.

**Comment by xhochy** [comment]
`CommonDigestSPI.h` has been part of the SDK quite a while ago. It should be in `$SDKROOT/usr/include/CommonCrypto` but I don't see it in any of the SDK we support in conda-forge.

**Comment by isuruf** [comment]
It's not required AFAIK

**Comment by h-vetinari** [comment]
> It's not required AFAIK

I tried both `-DLLVM_HAVE_LIBXAR=0` and `-DLLVM_ENABLE_LIBXAR=OFF` in https://github.com/conda-forge/lld-feedstock/pull/33 without success. Not sure how else to switch it off...

**Comment by isuruf** [comment]
lld probably uses the setting from llvm. We'll have to turn it off in llvmdev-feedstock

**Comment by h-vetinari** [comment]
> lld probably uses the setting from llvm. We'll have to turn it off in llvmdev-feedstock

OK: https://github.com/conda-forge/llvmdev-feedstock/pull/145

**Pull request closed without merging**
