### PR TITLE
Tf-slim

### PR DESCRIPTION
**Pull request by adbeda**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by adbeda** [comment]
@conda-forge/help-python how do I provide `write access` to this repository? I thought it was ready for MR

**Comment by scopatz** [comment]
I think once you start the PR, you can't change the writes updates.

**Comment by scopatz** [comment]
Can you please resolve the conflicts though?  Not sure how you got them even.

**Comment by scopatz** [comment]
Did you render this repo? You can only do that on feedstocks

**Comment by adbeda** [comment]
@scopatz honestly, i don't even know what caused it. I'm happy to look into it further

**Comment by scopatz** [comment]
Try merging from master, or just close this PR and reopen a new one built off a fresh master

**Pull request closed without merging**
