### PR TITLE
Add the `Imath` library, which seems to replace `IlmBase`

### PR DESCRIPTION
**Pull request by pkgw**
So, the motivation for this new package is basically https://github.com/conda-forge/openexr-python-feedstock/pull/6 . I think that that update is failing because conda-forge's version of OpenEXR is quite old: we have 2.5.5, while upstream is at 3.1.4. This is important because there are several CVEs that I believe apply to the 2.x series.

In order to build newer versions of OpenEXR that can be used by OpenEXR-python, I believe we need to add this package, which has been split from `ilmbase`.  The main OpenEXR build can download and use an internal version of Imath, but in that case it doesn't provide libImath, which OpenEXR-python needs to build.

- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

I've propagated the maintainers from `ilmbase` — please comment regarding whether you'd like to be added as a maintainer of this package or not:

- @npavlovikj
- @SylvainCorlay
- @wolfv
- @JohanMabille

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks for tackling this! I am happy to stay as maintainer of the new recipe. I don't know about the other ones (I work with Sylvain and Johan, so probably OK for them, too).

**Comment by JohanMabille** [comment]
Thanks for working on this. Like Wolf, I am happy to be a maintainer of the new recipes.

**Comment by pkgw** [comment]
No problem. I was planning to give @SylvainCorlay and @npavlovikj a few more days to follow up, but with the two of you onboard I think that's a good complement of maintainers if we don't hear back.

**Comment by pkgw** [comment]
@conda-forge/staged-recipes ready for review.

**Pull request merged**
