### PR TITLE
Added recipe for wurlitzer

### PR DESCRIPTION
**Pull request by bjodah**
cc @minrk : do you mind being added to maintainers of this recipe? (you being the author and all :) )

### CODE REVIEW

**Comment by asmeurer** [comment]
@minrk do you want to be a maintainer?

**Comment by asmeurer** [comment]
I suspected it didn't work on Windows.

In the future, don't delete the other recipes. The bot does that automatically, and it just makes it harder to review. Also I'm not sure, but if this gets merged before the deleted recipes get converted to feedstocks, it might prevent that from happening.

**Comment by bjodah** [comment]
Yeah sorry about that. I commited those deletions by mistake. Rebased now.

**Comment by minrk** [comment]
I'm happy to be a maintainer

**Comment by jakirkham** [comment]
Thanks for adding this all.

Wish I had known about this package ages ago. Very useful. 😄

**Pull request merged**
