### PR TITLE
Drop CUDA 11.2

### PR DESCRIPTION
**Pull request by jakirkham**
Follows up on the discussion in issue ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5339 ) and [this announcement]( https://conda-forge.org/news/2024/03/06/dropping-cuda-112/ )

This drops CUDA 11.2 from `staged-recipes` making CUDA 11.8 the new minimum.

Closes https://github.com/conda-forge/staged-recipes/pull/25027
Closes https://github.com/conda-forge/staged-recipes/pull/25676

### CODE REVIEW

**Comment by jakirkham** [comment]
Testing this out in these PRs:

* https://github.com/conda-forge/staged-recipes/pull/25027
* https://github.com/conda-forge/staged-recipes/pull/25676

**Comment by jakirkham** [comment]
@conda-forge/core , this is ready for review!

**Review by h-vetinari — APPROVED** [review]
👍

**Comment by jakirkham** [comment]
Thanks Axel! 🙏

**Pull request merged**
