### PR TITLE
Add types-aioboto3 recipes

### PR DESCRIPTION
**Pull request by vemel**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### Recipes

- [x] types-aioboto3
- [x] types-aioboto3-lite
- [x] types-aiobotocore
- [x] types-aiobotocore-lite

This is a follow-up to https://github.com/conda-forge/staged-recipes/pull/19740

### CODE REVIEW

**Comment by vemel** [comment]
Hello! I need some help with this recipe. I am getting this error:

```
 File "/home/conda/staged-recipes/build_artifacts/types-aiobotocore-lite_1658862932247/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/home/conda/staged-recipes/build_artifacts/types-aiobotocore-lite_1658862932247/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/collections/__init__.py)
```

However, this error is related to `botocore` does not fully support `py310` yet. @maresb Do you know how to fix this error properly?

**Comment by maresb** [comment]
Do you need to add a runtime requirement that `python <3.10`? Or do you need a build requirement to that effect? If it's the latter, you might be able to put `- python >=3.7,<3.10` in the `host:` requirements sections.

**Comment by vemel** [comment]
Thank you! So, in this case, the package will not be available for py310, right?

**Comment by maresb** [comment]
It would be if the tests are passing. Seems to be broken also at runtime for 3.10? In that case you shouldn't allow 3.10.

**Comment by vemel** [comment]
I found the issue. The problem is that a very old version of `aiobotocore` is installed: 

```
aiobotocore:                      0.10.0-py_0               conda-forge
```

Checking, why

**Comment by vemel** [comment]
Okay, `aiobotocore` recipe is up to date: https://github.com/conda-forge/aiobotocore-feedstock/blob/main/recipe/meta.yaml

However, it depends on `botocore >=1.24.21,<1.24.22`. So this requirement should be unlocked or somehow updated via autoupdate. I am going to create a PR.

**Pull request closed without merging**
