### PR TITLE
Add custom_inherit

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dpryan79** [comment]
Needed for https://github.com/conda-forge/staged-recipes/pull/11328

**Comment by dpryan79** [comment]
@conda-forge/help-python This is ready for review

**Comment by npavlovikj** [comment]
Thank you @dpryan79 🎉

**Comment by synapticarbors** [comment]
It looks like the same package already exists:

https://github.com/conda-forge/custom-inherit-feedstock

**Comment by synapticarbors** [comment]
note the difference between `custom_inherit` vs `custom-inherit`

**Comment by dpryan79** [comment]
Weird, I wonder why I didn't find that one before. If someone from core wants to delete this feedstock then that'd be :+1: from me.

**Comment by synapticarbors** [comment]
At first glance it seems like an unfortunate naming decision in the original feedstock since the package is called `custom_inherit` and that's how it's installed via pip, so I can see where the confusion originates. I've put in a question on gitter about how best to clean this up.

**Comment by npavlovikj** [comment]
Thanks for noticing this @synapticarbors, I should have been more careful when merging the PR. I am glad to see that things are sorted out now though.

**Pull request merged**
