### PR TITLE
Add c-kzg-4844/ckzg

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by MementoRC** [comment]
@step21 This should be good to go when `libblst` (currently under review by @xhochy: https://github.com/conda-forge/staged-recipes/pull/27476) is approved. I tested that it passes by supplying the lib in the draft recipe (I made too many commits and shied away from PR)

**Comment by step21** [comment]
Awesome. Thanks for all your work!

**Comment by MementoRC** [comment]
@step21 Have you had a chance to look at this alternative recipe?

**Comment by step21** [comment]
> @step21 Have you had a chance to look at this alternative recipe? I prefer to build conda package from github source

I haven't, but would look more closely when it builds. However, if you want speedy merging, I suggest using pypi and not github, as that is a conda-forge rule. I think one reason is that github is seen as less reliable and files can change. (or some other reason)

**Comment by MementoRC** [comment]
Redundant

**Pull request closed without merging**
