### PR TITLE
Add recipe for pygedm

### PR DESCRIPTION
**Pull request by mattpitkin**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mattpitkin** [comment]
@conda-forge/help-c-cpp My build is having an issue with FORTRAN on the OSX build (sorry, I know this help is C/C++, but it's the closest I could think of that might have come across this issue!). The Linux build works, but the OSX failed towards the end with:

```

   INFO (pygedm,lib/python3.6/site-packages/ymw16.cpython-36m-darwin.so): Needed DSO /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT
   INFO (pygedm,lib/python3.6/site-packages/ymw16.cpython-36m-darwin.so): Needed DSO lib/libc++.1.dylib found in conda-forge::libcxx-11.1.0-habf9029_0
  ERROR (pygedm,lib/python3.6/site-packages/pygedm/density.cpython-39-darwin.so): /usr/local/opt/gcc/lib/gcc/10/libgfortran.5.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
   INFO (pygedm,lib/python3.6/site-packages/pygedm/density.cpython-39-darwin.so): Needed DSO /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT
  ERROR (pygedm,lib/python3.6/site-packages/pygedm/density.cpython-39-darwin.so): /usr/local/lib/gcc/10/libgcc_s.1.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
  ERROR (pygedm,lib/python3.6/site-packages/pygedm/density.cpython-39-darwin.so): /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
WARNING (pygedm): interpreter (Python) package conda-forge::python-3.6.13-h7728216_0_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (pygedm): plugin library (Python) package conda-forge::astropy-4.1-py36h642477c_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (pygedm): interpreted library (Python) package conda-forge::pybind11-2.6.2-py36h615c93b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (pygedm): plugin library (Python) package conda-forge::numpy-1.17.5-py36h08dc641_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (pygedm): plugin library (Python) package conda-forge::scipy-1.5.3-py36h04de62b_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
Traceback (most recent call last):
  File "/Users/runner/work/1/s/.ci_support/build_all.py", line 175, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/Users/runner/work/1/s/.ci_support/build_all.py", line 100, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/Users/runner/work/1/s/.ci_support/build_all.py", line 156, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 2351, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 1644, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 1490, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/post.py", line 1317, in post_build
    check_overlinking(m, files, host_prefix)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/post.py", line 1223, in check_overlinking
    return check_overlinking_impl(m.get_value('package/name'),
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/post.py", line 1206, in check_overlinking_impl
    raise OverLinkingError(overlinking_errors)
conda_build.exceptions.OverLinkingError: overlinking check failed 
['  ERROR (pygedm,lib/python3.6/site-packages/pygedm/dmdsm.cpython-39-darwin.so): /usr/local/opt/gcc/lib/gcc/10/libgfortran.5.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (pygedm,lib/python3.6/site-packages/pygedm/dmdsm.cpython-39-darwin.so): /usr/local/lib/gcc/10/libgcc_s.1.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (pygedm,lib/python3.6/site-packages/pygedm/dmdsm.cpython-39-darwin.so): /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (pygedm,lib/python3.6/site-packages/pygedm/density.cpython-39-darwin.so): /usr/local/opt/gcc/lib/gcc/10/libgfortran.5.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (pygedm,lib/python3.6/site-packages/pygedm/density.cpython-39-darwin.so): /usr/local/lib/gcc/10/libgcc_s.1.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (pygedm,lib/python3.6/site-packages/pygedm/density.cpython-39-darwin.so): /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']
##[error]Bash exited with code '1'.
```

Has anyone seem similar errors, or have any suggestions for fixes?

**Comment by mattpitkin** [comment]
Hi @telegraphic, I've created a conda recipe for pygedm for conda-forge. Are you happy to be added as a maintainer along with me?

**Comment by xhochy** [comment]
We can merge this with you as the sole maintainer and you can add others on the feedstock. Then this would finally get a merge.

**Comment by mattpitkin** [comment]
@xhochy I'm happy to get it merged in now.

**Comment by telegraphic** [comment]
Hi @mattpitkin, this is great stuff! I'm happy to be listed as a maintainer, but don't have much experience with conda feedstocks.

**Comment by mattpitkin** [comment]
@telegraphic I've added you as a maintainer. I'll actually set up the conda-forge feedstock to automatically update if/whwn new releases appear on PyPI, so you shouldn't have to do anything.

I suppose one thing to do would be to update the documentation to say that you can now install the package using conda.

**Pull request merged**
