### PR TITLE
Added recipe for tangelo

### PR DESCRIPTION
**Pull request by pmlandwehr**
Pinging @ronichoudhury in case he'd like to be added as a maintainer to the [`tangelo`](https://tangelo.readthedocs.io/en/v0.10/) builder on conda-forge, a library of community-build `conda` packages. The maintenance burden here is light: all testing and releases are built and deployed automatically with CI. Changes to how the package is being built can be controlled by changing the recipe which will be located at https://github.com/conda-forge/tangelo-feedstock shortly after this PR is finished and merged. If you aren't interested in helping maintain the build, that is entirely fine too.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Hmm... @ocefpaf what do we do about pinned reqs that aren't in a feedstock? Branch and build the older version?

**Comment by ocefpaf** [comment]
> Hmm... @ocefpaf what do we do about pinned reqs that aren't in a feedstock? Branch and build the older version?

I believe you mean `ws4py 0.3.2`, right? And only `ws4py 0.3.5` is available. We can do:

1. The ugly thing: "update" the feedstock to `ws4py 0.3.2`, get that merged and the binaries in the the channel, and then restore `ws4py 0.3.5`.
2. No so ugly: branch for a `ws4py 0.3.2` build. But branching is mostly to keep both version updated as they evolve. I believe `ws4py 0.3.2` is no longer being developed.

@pelson what do prefer 1 or 2?

**Comment by jakirkham** [comment]
@pelson and I had this same discussion with NumPy ( https://github.com/conda-forge/numpy-feedstock/issues/10 ). IMHO we can always do the ugly thing now to break ground here and if we decide we cleaning up in this way is an ok thing to do we can do that later.

**Comment by pelson** [comment]
Ironically, if we already know the older version doesn't need long term maintenance, I actually prefer the ugly thing. The reason is simply that if we branch, we will end up deleting the commit unless we merge it back to master at some point. The (ugly) alternative you propose would put the 0.3.2 into a commit, then immediately revert (i.e. not delete the commit, just undo the changes) back to 0.3.5. Our master branch would therefore have 0.3.2 in its git log for future readers.

**Comment by ocefpaf** [comment]
@pmlandwehr two makes a crowd and now you have a plan to move this forward. Let's close this and work on option 2.

**Pull request closed without merging**
