### PR TITLE
nCephes

### PR DESCRIPTION
**Pull request by Horta**

### CODE REVIEW

**Comment by Horta** [comment]
Requires build_capi package: https://github.com/conda-forge/staged-recipes/pull/1928

**Comment by Horta** [comment]
Bit lost here. Any hints?
Otherwise I think I need to get my hands on some windows machine...

**Comment by Horta** [comment]
I think this one is now ready to merge. Feel free =)

**Comment by Horta** [comment]
Thank you =) It says here https://github.com/conda-forge/ncephes-feedstock that the repository is empty. Shall I just wait?

**Comment by ocefpaf** [comment]
Yep. Sometimes it take a while to process the feedstocks. Let me know if that does not show up in 24-48 hours though.

**Pull request merged**
