### PR TITLE
Add a recipe for whatthepatch

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Description

This is a new dependency for the next version of Python-lsp-server, which is already part of conda-forge (see [here](https://github.com/conda-forge/python-lsp-server-feedstock)).

### CODE REVIEW

**Comment by ccordoba12** [comment]
@andfory, @steff456, @dalthviz, do you agree to be maintainers of this package?

**Comment by steff456** [comment]
Yes!

**Comment by andfoy** [comment]
Yes, I agree

**Comment by ccordoba12** [comment]
@conda-forge/staged-recipes, this is ready for review.

**Comment by ccordoba12** [comment]
Ping @conda-forge/staged-recipes again. Sorry to bother you, but we need this to have Python-lsp-server 1.5.0 in conda-forge and then release Spyder 5.3.2.

**Comment by ccordoba12** [comment]
Thanks @BastianZim!

**Pull request merged**
