### PR TITLE
Add scriptengine-tasks-ecearth

### PR DESCRIPTION
**Pull request by uwefladrich**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by uwefladrich** [comment]
Hi @zklaus ,

Could you please have a look at this PR? There is an issue with one of the dependencies. The package needs `python-redmine`, which is not available on conda-forge, only on PyPI. Now I wonder if this is correctly reflected in `meta.yaml`. I would expect `redmine-python` listed explicitly as pip dependency, but it is not. There was also a `grayskull` warning about this when creating the recipe.

**Comment by uwefladrich** [comment]
> [...] The package needs `python-redmine`, which is not available on conda-forge, only on PyPI. Now I wonder if this is correctly reflected in `meta.yaml`. I would expect `redmine-python` listed explicitly as pip dependency, but it is not. There was also a `grayskull` warning about this when creating the recipe.

Now there are also error in the ci pipeline about this. So I guess `python-redmine` must be listed as pip dependency. Is it as easy as:
```yaml
requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - scriptengine >=0.8.1
    - pyyaml >=5.1
    - matplotlib-base >=3.1
    - numpy >=1.18
    - imageio >=2.18
    - scitools-iris !=3.2.0,!=3.2.0.post0,>=3.1
    - cartopy >=0.20
    - pip:
      - python-redmine
```
?

**Comment by zklaus** [comment]
Actually, conda-forge should be self-sufficient, i.e. the correct thing to do is to add python-redmine as a package. Since it is already on pypi, that is probably pretty simple. Just follow the same steps you used for this package and the other scriptengine-hpc-tasks package.

**Comment by uwefladrich** [comment]
Opened maxtepkeev/python-redmine#308 to get python-redmine into conda-forge.

**Comment by uwefladrich** [comment]
Hi @valentinaschueller, I would like you to be a co-maintainer of the `scriptengine-tasks-ecearth` conda package recipe. Is that okay with you?

**Comment by valentinaschueller** [comment]
Hi @uwefladrich, yes please!

**Comment by zklaus** [comment]
Looks good. The build number should be `0` though.

**Comment by uwefladrich** [comment]
> Looks good. The build number should be `0` though.

It was 0 in 03d0a28bdc73251f2d06ccd220f88e52ee4bc27f but then I needed to trigger the build again with a5e78a4fa4d44915ce2507c5ef8bbeab43cc08a4, without changing the meta-data. My understanding was that I change back to 0 once I jump to the next se-t-ece version.

Unless the change in `test.commands` counts as change in meta-data, in which case increasing `build.number` in a5e78a4fa4d44915ce2507c5ef8bbeab43cc08a4 was not necessary (I was a bit unsure about it).

Does a build number >0 prevent further steps?

**Comment by zklaus** [comment]
Any commit here will trigger the check builds, you don't need to increase the build number for that. The build number should be increased when a new build is uploaded to the conda-forge channel, but since recipes in staged-recipes have by definition no prior builds, their build number must always be 0.

**Comment by zklaus** [comment]
Sorry for dropping the ball here a little. When done, you should ping the team. This will set the review-requested label and alert someone with merge powers. In this case, I'll do like this:

@conda-forge/help-python, ready for review :)

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
