### PR TITLE
Add pytest-fixture-config recipe

### PR DESCRIPTION
**Pull request by jcfr**
See https://github.com/manahl/pytest-plugins/tree/master/pytest-fixture-config#readme

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the review :+1: 

We should be all set now

**Comment by marcelotrevisani** [comment]
Thanks @jcfr for your effort. I'm going to merge that

**Comment by jcfr** [comment]
Great. After `pytest-shutil` and `pytest-fixture-config` make it to conda-gorge, I will be able to create a recipe for `pytest-virtualenv`.

Do you have to wait for there two packages to have a feedstock ? Or can I go already move forward with a receipt for `pytest-virtualenv` before its dependencies are in conda-forge ?

**Comment by marcelotrevisani** [comment]
@jcfr you can create the recipe, but I recommend to you to wait for the packages in conda-forge, otherwise your build may fail

**Comment by marcelotrevisani** [comment]
Sorry, I will revert this, I found one error here

**Comment by marcelotrevisani** [comment]
I will create a PR for that, just one moment

You created the recipe folder in the root folder, next time please create inside of the ``recipe`` folder
It's a common mistake and I also forgot to check that. sorry

Your another PR you have to move your folder to the ``recipes`` folder please

**Pull request merged**
