### PR TITLE
itermplot: add reipe for v0.331

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge/python Now sure what to do about license here :)

**Comment by ocefpaf** [comment]
> @conda-forge/python Now sure what to do about license here :)

We should open an issue upstream and ask them for a license file :-/

**Comment by nehaljwani** [comment]
The issue is already available: https://github.com/daleroberts/itermplot/issues/39

This backend is very useful for working remotely and displaying matplotlib visualizations on iterm2 terminal without needing any X server.

**Comment by ocefpaf** [comment]
> The issue is already available: [daleroberts/itermplot#39](https://github.com/daleroberts/itermplot/issues/39)

Great! Just added that as a comment on the recipe.
While we would be missing the copyright statement you can add a "generic" MIT license text there just as a placeholder until the author issues one.

**Comment by nehaljwani** [comment]
This is ready, @ocefpaf

**Pull request merged**
