### PR TITLE
Add recipe for gz-utils

### PR DESCRIPTION
**Pull request by traversaro**
The ignition robotics libraries, that are currently packaged in conda-forge under the `libignition-*`, have been renamed to Gazebo libraries (see https://community.gazebosim.org/t/a-new-era-for-gazebo/1356).

To avoid confusion related to the feedstock name in the future, we are re-submitting all the `libignition-` recipes to conda-forge to have descriptive and coherent names that start with `gz-`, as described in https://github.com/conda-forge/libignition-cmake0-feedstock/issues/26#issuecomment-1255871405 . 

This PR creates a new `gz-utils-feedstock` to package [`gz-utils`](https://github.com/gazebosim/gz-utils), using the recipe already available in https://github.com/conda-forge/libignition-utils-feedstock .

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
@Tobias-Fischer do you agree to be a mantainer of this as you were already a mantainer of https://github.com/conda-forge/libignition-utils-feedstock ? 

For @wolfv we can rely on the permission in https://github.com/conda-forge/staged-recipes/pull/20547#issuecomment-1261908808 .

@conda-forge/help-c-cpp The recipe is ready for review.

**Comment by wolfv** [comment]
let's get a blanket yes or no from Tobias, too, so that I can merge these quicker :)

**Comment by traversaro** [comment]
> let's get a blanket yes or no from Tobias, too, so that I can merge these quicker :)

Ack, I updated the question and added also one for @j-rivero (even if he was not already mantainer of this feedstock, so for this specific case we can merge even without his reply).

**Comment by j-rivero** [comment]
> @j-rivero do you agree to be a mantainer of the gazebo recipes for the packages of which you are already a mantainer of the ignition version ?

Sure. I won't be always very fast in my answers but count with me for any questions specially related to upstream code.

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
