### PR TITLE
Do we need the Token in appveyor.yml [ci skip]    [skip appveyor]

### PR DESCRIPTION
**Pull request by ocefpaf**
We don't do any uploads in staged-recipes, so I am guessing this is safe. @pelson if so we could also change the AppVeyor account as suggested in #244, right?

### CODE REVIEW

**Comment by pelson** [comment]
> We don't do any uploads in staged-recipes, so I am guessing this is safe.

Not quite as safe as you might think. conda-build-all is going to use that to login to anaconda.org. That said, I think the query we are doing should be fine in anonymous, so :+1:

**Comment by pelson** [comment]
I'd rather not skip appveyor though for this change...

**Comment by pelson** [comment]
Merging to see what happens. If we revert the change, so be it! :+1:

**Comment by ocefpaf** [comment]
My original plan was to use this as first step to split staged-recipes AppVeyor from the feedstocks AppVeyor. However, I don't think we should do this now. The new AppVeyor config seems to be OK with the current load.

**Pull request merged**
