### PR TITLE
[R4R] ASAP3

### PR DESCRIPTION
**Pull request by jochym**
ASAP is a calculator for doing large-scale classical molecular dynamics within the Campos Atomic Simulation Environment (ASE).

The reason this is a new recipe and not update of the asap-feedstock is that the upstream is distributed on pypi as asap3 and asap is a different package. Keeping pypi and conda in sync will minimize user confusion.

### CODE REVIEW

**Comment by jochym** [comment]
@jakirkham I hate to bother you again but something may be wrong with the linter - suddenly it started to hate me ;) And I cannot find any asap3 recipe in bioconda!

BTW - re-enabling build for staged-recipes in CCI worked. While checking this I may have stumbled on the reason. Some time ago I have removed my fork of staged-recipes and re-forked today. Maybe CCI remembered the old repo and treated the new fork as new repo?

**Comment by jakirkham** [comment]
Hmm... 🤔 @conda-forge/core, any thoughts on the linter issues here?

**Comment by CJ-Wright** [comment]
Did we release the new version of conda-smithy?

**Comment by jochym** [comment]
I think this is ready to be merged.

**Comment by CJ-Wright** [comment]
Thank you @jochym!

**Pull request merged**
