### PR TITLE
Add yasm

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a recipe to build yasm. Borrowed from conda recipes. Cleaned up a bit to fit nicely at conda-forge.

Broken out from the FFMPEG PR ( https://github.com/conda-forge/staged-recipes/pull/111 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
Would you be interested in being a maintainer on this too, @ocefpaf? It is a build tool. Though I don't know if it interests you.

**Comment by ocefpaf** [comment]
> Would you be interested in being a maintainer on this too, @ocefpaf? It is a build tool. Though I don't know if it interests you.

Sure. I will probably just merge the `MNT` PRs though.

**Comment by jakirkham** [comment]
Fair enough. I think after people see how useful it is for other stuff in the stack; there will be other people volunteering to maintain this, as well.

**Comment by jakirkham** [comment]
Passing. :smile: Any feedback on this?

**Comment by msarahan** [comment]
This might also be used for OpenSSL - can't quite remember.  Good addition.

**Comment by jakirkham** [comment]
Yeah, it was needed for x264, which is in turn needed for FFMPEG, as well. There's a bunch of stuff where it comes in real handy.

**Comment by jakirkham** [comment]
More feedback is welcome in the feedstock (once generated).

**Pull request merged**
