### PR TITLE
Django simplehistory

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@conda-forge-admin: Could you please review and merge.

**Comment by jakirkham** [comment]
So this got added to the `example` directory. 😕 Also means that the recipe was not actually tested on CI. @sannykr, could you please submit a PR to move this out of the `example` directory?

**Comment by sannykr** [comment]
@jakirkham : Thanks for pointing out. I create meta.yaml file directly on github UI, and that's why made such mistakes. I will make sure not to repeat that.

**Comment by CJ-Wright** [comment]
@jakirkham @scopatz I did this last week, could I interest you in https://github.com/conda-forge/conda-smithy/pull/686

**Pull request merged**
