### PR TITLE
Enable mambabuild

### LINKED ISSUE #13931: How to incorporate new build files?
Hi,

I was wondering what the suggested approach is to using new build files from conda-smithy for staged-recipes.

Specifically, I would like to test the changes incorporated in https://github.com/conda-forge/conda-smithy/pull/1441 in my local fork of `staged-recipes` using `./.scripts/run_docker_build.sh` but those changes are only available once a recipe is successfully converted into a feedstock, where they can be invoked with `build_locally.py`.
Is there a way to rerender `staged-recipes` to incorporate these changes, or do I have to manually copy those into my fork and then remove the changes again before submitting, once I have successfully tested the package?

Thanks!

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Closes #13931

### CODE REVIEW

**Comment by BastianZim** [comment]
This line needs to be changed but I'm not sure if mambabuild has an equivalent?

https://github.com/conda-forge/staged-recipes/blob/28def1d9c585670ed4daab8dcb544662df320523/.ci_support/build_all.py#L156

**Comment by BastianZim** [comment]
Thanks for the link. I tested it locally and it works!

**Comment by beckermr** [comment]
just mambabuild

**Comment by BastianZim** [comment]
And would it make sense to switch from miniforge to mambaforge instead of installing it separately?

**Comment by BastianZim** [comment]
Should mambabuild be the default and it changed with a conda-forge.yaml or the other way round?

**Comment by beckermr** [comment]
> Should mambabuild be the default and it changed with a conda-forge.yaml or the other way round?

We should match smithy which now defaults to mambabuild. So let's make mambabuild the default and allow people to turn it off it needed. This setting being off will propagate to the feedstock as well, making everything consistent.

**Comment by beckermr** [comment]
@BastianZim Can you put a test recipe in this dir and make sure it builds? We can remove it before merging.

**Comment by BastianZim** [comment]
Ready from my side.

**Comment by 183amir** [comment]
Great initiative, we switched to mamba and mambabuild in the bob channel as well. Besides [not having a proper Python API](https://github.com/mamba-org/boa/issues/192) and having to run `conda clean --all` (see: https://github.com/mamba-org/boa/issues/192#issuecomment-934544639) everything else went smoothly and our CI time was reduced a lot! e.g. [33 minutes](https://gitlab.idiap.ch/bob/bob.devtools/-/jobs/245675) compared to [12 minutes](https://gitlab.idiap.ch/bob/bob.devtools/-/jobs/247078)

**Comment by beckermr** [comment]
I think a lot of the miniconda stuff on windows is because we are using their preinstalled miniconda. So I don't think we can change those paths. We maybe able to use mamba though. Can someone on @conda-forge/core confirm?

**Comment by beckermr** [comment]
This PR is likely blocked on the bug we flushed out here: https://github.com/conda-forge/ctng-compilers-feedstock/pull/77

**Comment by BastianZim** [comment]
I have _very_ tentatively created a PR at https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/169 to add boa as a run dependency. This should satisfy what @isuruf requested above in terms of one source of truth and also not force the installation in case boa should be removed in some instances.

Please let me know any opinions.

**Comment by beckermr** [comment]
This looks great to me!

**Comment by beckermr** [comment]
Thank you for all of the hard work here!

**Comment by BastianZim** [comment]
Thanks!

**Pull request merged**
