### PR TITLE
Add airflow 1.8.0 recipe to conda-forge.

### PR DESCRIPTION
**Pull request by sodre**
The recipe currently does not build pass the test because
- [x] flask-swagger 
- [x] python-nvd3
  - [x] update python-slugify-feedstock
- [x] dependency on flask-login =0.2.11 (conda-forge/flask-login-feedstock#5, conda-forge/flask-login-feedstock#6)
- [x] dependency on gunicorn >=19.3.0,<19.4.0 (conda-forge/gunicorn-feedstock#6)
- [x] dependency on flask-admin =1.4.1 (conda-forge/flask-admin-feedstock#3)
- [x] Decision from @conda-forge/core on how to handle the extra features/requirements. 

I will be working to create additional packages for those.

### CODE REVIEW

**Comment by sodre** [comment]
@conda-forge/core, 
I need some input on how to handle the [extra_requires](https://gist.github.com/sodre/a5fb32df81d1aabc7383565aecc29c84) for airflow. It is not a small-list so I don't think adding all of them to the recipe is the best choice.  I know CIO is working on the establishing the "optional" requirements but while that does not arrive what have we done lately.

One possibility is to create several airflow-<extra> metapackages that brings in the additional dependencies. Is there a conda-forge example for that?

**Comment by mariusvniekerk** [comment]
So for now i would try and get a minimal airflow recipe building fully on conda-forge.

Treating the additional dependencies as metapackages for now is probably the simplest approach.  For a few of those sets of dependencies you are going to have to submit additional conda-forge packages in any case so it may be simpler for you to iterate that way?

**Comment by jakirkham** [comment]
Have heard `conda` 4.4 has support for optional dependencies, but do not know how one would take advantage of this. Maybe ask at `conda` or `conda-build` how to use this.

**Comment by sodre** [comment]
In the short term I will go with @mariusvniekerk suggestion of a minimal airflow install. I will create an issue for the missing extra-packages for airflow and slowly create the associated metapackages.

The new feature in for handling optional dependencies in conda through meta.yaml is solved through conda/conda-build#2001. Once it becomes part of conda-forge we can augment the main recipe.

**Comment by sodre** [comment]
@conda-forge/core this is ready for review.

**Comment by pmlandwehr** [comment]
Congrats!

**Comment by sodre** [comment]
I need to start getting the add-ons done, or just wait for conda 4.4.

**Pull request merged**
