### PR TITLE
Adding mvlearn

### PR DESCRIPTION
**Pull request by gmischl1**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

I am ok with being listed as a maintainer

### CODE REVIEW

**Comment by rflperry** [comment]
I am okay with being listed as a maintainer.

**Comment by gmischl1** [comment]
This PR is ready for review, thanks! @conda-forge/help-python 
[ping the team](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-ping-team)

**Comment by jakirkham** [comment]
Is there a reason this is closed, @gmischl1?

**Comment by gmischl1** [comment]
@jakirkham I opened a new PR to get it closer to the top, since I wasn’t sure if it was too far down the list to get any attention.

**Comment by jakirkham** [comment]
Instead of doing that would bring it up on Gitter (after having pinged the staged-recipes team).

**Comment by jakirkham** [comment]
Superseded by PR ( https://github.com/conda-forge/staged-recipes/pull/11453 ).

**Pull request closed without merging**
