### PR TITLE
Adding r-assertive.* packages for developers

### PR DESCRIPTION
**Pull request by jenzopr**
Hi all,
this PR adds the `r-assertive` package and all of its assertive* dependencies:
- r-assertive.base
- r-assertive.code
- r-assertive.data
- r-assertive.data.uk
- r-assertive.data.us
- r-assertive.datetimes
- r-assertive.files
- r-assertive.matrices
- r-assertive.models
- r-assertive.numbers
- r-assertive.properties
- r-assertive.reflection
- r-assertive.sets
- r-assertive.strings
- r-assertive.types

They contain lots of predicates (is_* functions) to check the state of variables, and assertions (assert_* functions) to throw errors if they aren't in the right form.

Best,
Jens

### CODE REVIEW

**Comment by jenzopr** [comment]
All recipes have been generated with the conda_r_skeleton_helper script.

**Comment by jenzopr** [comment]
@bgruening thanks for your quick review! 
Unfortunately, some of the packages reside as their initial version in CRAN, meaning there is no file in the /Archive tree. On Appveyor, a package download from the primary URL failed, so it tried the secondary (non-existent) URL. Should we remove the secondary URL in those cases (r-assertive.data, r-assertive.data.uk, r-assertive.data.us, r-assertive.code)?

**Comment by bgruening** [comment]
The secondary is for later rebuilds. It should not fail on the first URL right? I will try to restart the build.

**Comment by jenzopr** [comment]
Thanks for helping me out! The first URL is definitely available, I checked that. I assume it was just a temporary timeout.

**Comment by bgruening** [comment]
Funnny enough that is only fails in one of 6 Windows builds.
I think we can deal with this in the feedstocks. @jenzopr can you keep an eye on the feedstocks and check if all of them are build correctly?

**Comment by jenzopr** [comment]
Hey @bgruening 
The feedstocks for 
* [r-assertive](https://github.com/conda-forge/r-assertive-feedstock)
* [r-assertive.data](https://github.com/conda-forge/r-assertive.data-feedstock)
* [r-assertive.data.us](https://github.com/conda-forge/r-assertive.data.us-feedstock)
* [r-assertive.data.uk](https://github.com/conda-forge/r-assertive.data.uk-feedstock)

did not build correctly. This was mainly because [r-assertive.strings](https://github.com/conda-forge/r-assertive.strings-feedstock) was not available during build time (which in turn had a successful build). 

* [r-assertive.code](https://github.com/conda-forge/r-assertive.code-feedstock)
* [r-assertive.datetime](https://github.com/conda-forge/r-assertive.datetimes-feedstock)

also failed because of assertive.properties/assertive.types

* [r-assertive.files](https://github.com/conda-forge/r-assertive.files-feedstock)

failed only on OSX because of assertive.numbers.
Best,
Jens

**Comment by bgruening** [comment]
@jenzopr in theory you should be able to restart the builds. I tried to restart a few. Lets see :)

**Comment by jenzopr** [comment]
By increasing the build number in the recipe you mean? :)

**Comment by bgruening** [comment]
Oh no, you can just click the CI symbol and click restart on the CI system.

**Pull request merged**
