### PR TITLE
Add yaqd-attune

### PR DESCRIPTION
**Pull request by ksunden**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ksunden** [comment]
@untzag ping

**Comment by untzag** [comment]
willing :smile:

**Comment by ksunden** [comment]
@conda-forge/help-python I believe this is ready for review

To preempt concerns brought up in past reviews:

We use flit in a way that needs to import the package to determine the version when installing. This has the drawback of needing the runtime dependencies at build time. We may seek to smooth that over in the future, but this is needed for this version at least.

**Review by carterbox — CHANGES_REQUESTED** [review]
I couldn't find a dependency specification in the source metadata. The Flit docs say the dependencies should be listed in pyproject.toml??? But I didn't see them. If Flit isn't including any dependency metadata, then `pip check` won't work as intended.

Anyways, from browsing the imports, it looks like the following packages are missing?:

- [ ] pint
- [ ] WrightTools
- [ ] qtpy? pyqt? qtypes?
- [ ] yaq_traits

If you want the GUI related stuff to be optional, I suggest adding a second output of this recipe which depends on yaqd_attune but adds the GUI dependencies. An example of this is the `matplotlib-base` and `matplotlib` packages.

**Comment by ksunden** [comment]
Closing in favor of #18760

**Pull request closed without merging**
