### PR TITLE
R packages from bioconda, subdag 0

### PR DESCRIPTION
**Pull request by daler**
xref https://github.com/bioconda/bioconda-recipes/issues/5582

### CODE REVIEW

**Comment by bgruening** [comment]
@daler this PR has too many recipes in it. We exceed build time. Let me know if I should recreate it.

**Comment by bgruening** [comment]
Blocked by https://github.com/conda-forge/r-digest-feedstock/pull/1

**Comment by bgruening** [comment]
Oh nice, finally I managed to make it pass :)
ping @ocefpaf

**Comment by daler** [comment]
Thank you Bjoern!

**Pull request merged**
