### PR TITLE
Updated to the latest ObviousCI, conda, and conda-build.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by scopatz** [comment]
Looks like appveyor is hanging...

**Comment by pelson** [comment]
> Looks like appveyor is hanging...

Just slow today. Looks like its doing its thing now.

**Comment by scopatz** [comment]
Thanks @pelson!

**Comment by pelson** [comment]
Woohoo. All passing!

@scopatz - surprised you haven't submitted an xonsh recipe yet :wink:

**Comment by scopatz** [comment]
Incoming :)

**Pull request merged**
