### PR TITLE
Package box2d-py (dependency for gym)

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Working towards #11162 (since the solver doesn't get the dependency build order correctly there). Curiously, there has been a surprising amount of progress on the dependencies in the few days that I haven't touched this, see #11195 for `atari-py`. Also see #11152, although the [repo](https://github.com/openai/box2d-py) of the dependency that's needed for gym says:
> This is a repackaged version of [pybox2d](https://github.com/pybox2d/pybox2d). For all information, see that repo. 

Maybe @christopherhesse can provide some more information on how compatible these packages are. Also, you're welcome to help/contribute in the recipe maintainership, if you're interested.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes. This is green and would unblock me on #11162. :)

**Comment by h-vetinari** [comment]
Thanks @beckermr!

@christopherhesse, if/once you see this, feel free to comment here or participate on [the feedstock](https://github.com/conda-forge/box2d-py-feedstock)

**Comment by christopherhesse** [comment]
I think the only reason box2d-py exists is that pybox2d would fail to install all the time and wasn't getting fixed so we had to create a fork of it.  If you want to maintain a conda version of this, go for it.

**Comment by h-vetinari** [comment]
@christopherhesse 
Thanks for the response. Do I understand you correctly that the changes that you made from `pybox2d` to `box2d-py` are sufficiently small that `gym-box2d` could depend on `pybox2d` directly?

**Comment by christopherhesse** [comment]
It's possible but I'm not certain.  The `gym` library depends on `box2d-py` I think

**Comment by h-vetinari** [comment]
> @christopherhesse: The `gym` library depends on `box2d-py` I think

Well, that's my point. If the only difference is the packaging (I couldn't tell from a quick glance a the repo how much was done), then `gym` could just depend on `pybox2d` directly, and this feedstock would not be necessary anymore.

**Comment by christopherhesse** [comment]
If `gym` depended on `pybox2d` directly, but `pybox2d` still fails to install for most of `gym`'s users, I don't see how that makes things better.

**Comment by h-vetinari** [comment]
> If `gym` depended on `pybox2d` directly, but `pybox2d` still fails to install for most of `gym`'s users, I don't see how that makes things better.

Well that's the beauty of conda. All those pybox2d installs would work (that specific install combination is tested for all platforms each time gym is built)!

**Comment by christopherhesse** [comment]
I suspect the vast majority of gym users are using pip.  If `pybox2d` had binary wheels for the version used by `gym` on pypi, I think we would then want to switch `gym` to depend on those instead of `box2d-py`.

I contacted the author of `pybox2d` about a year ago about this but they said they were looking for a new maintainer for the project and did not have time to merge those changes.

**Comment by h-vetinari** [comment]
> I suspect the vast majority of gym users are using pip. If pybox2d had binary wheels for the version used by gym on pypi, I think we would then want to switch gym to depend on those instead of box2d-py.

I'm not suggesting that gym (as maintained by you and others; "upstream" from conda) should change their dependency from `box2d-py` to `pybox2d`. I was just trying to understand if there's any difference between the two packages that goes beyond simple packaging, because then conda-forge could avoid this duplication and let the "recipe" for `gym` depend directly on `pybox2d`.

OTOH, if however `pybox2d` ends up being abandoned, but with development continuing in `box2d-py`, then we should leave things as is.

**Comment by christopherhesse** [comment]
Oh I misunderstood, sorry.

Yes those should be all packaging changes, though it's not forked from `pybox2d` directly for unknown reasons: https://github.com/jonasschneider/box2d-py/compare/master...openai:master

**Comment by h-vetinari** [comment]
> Oh I misunderstood, sorry.

No worries!

> Yes those should be all packaging changes, though it's not forked from pybox2d directly for unknown reasons: https://github.com/jonasschneider/box2d-py/compare/master...openai:master

Ok, pybox2d must have moved repo and some point, and broken the "forked-by" chain (AFAIK, github support is able to recify that if you're interested).

In any case, to quickly use the comparison UI from github, I forked pybox2d, but force-pushed the state of box2d-py to my fork. The resulting comparison is then: https://github.com/pybox2d/pybox2d/compare/master...h-vetinari:master. It does look like most changes are related to packaging, but [`library/Box2d/Box2d.py`](https://github.com/pybox2d/pybox2d/compare/master...h-vetinari:master#diff-f5f0a38a8795dd7b01cda03b1932b911) is completely removed, for example.

**Comment by christopherhesse** [comment]
I think that's because it's auto-generated by the build process.

**Pull request merged**
