### PR TITLE
add nwchem

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ltalirz** [comment]
@edoapra 

Your patch did change something  - this was the error before:
```
export PREFIX=/home/conda/staged-recipes/build_artifacts/nwchem_1620151640657/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
export SRC_DIR=/home/conda/staged-recipes/build_artifacts/nwchem_1620151640657/test_tmp

 =======================================================
 QM: Running a very small subset of the available tests 
 =======================================================


 Running tests/h2o_opt/h2o_opt 
 
     cleaning scratch
     copying input and verified output files
     running nwchem ($PREFIX/bin/nwchem)  with 2 processors 
 
     NWChem execution failed
            Nuclear Dipole moment (a.u.) 
            ----------------------------
        X                 Y               Z
 ---------------- ---------------- ----------------
    -0.0000000000     0.0000000000    -0.0000000000

 Attempting to read a basis set from a  non-existing file:
 /home/conda/staged-recipes/build_artifacts/nwchem_1620151640657/work/src/basis/libraries/6-31gs                                                                                                                                                                
 ------------------------------------------------------------------------
 bas_tag_lib: failed opening basis file                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    66: task scf optimize
 ------------------------------------------------------------------------
 Attempting to read a basis set from a  non-existing file:
 ------------------------------------------------------------------------
 There is an error in the specified basis set
 ------------------------------------------------------------------------
 For more information see the NWChem manual at https://github.com/nwchemgit/nwchem/wiki


 For further details see manual section:                                                                                                                                                                                                                                                                
0:bas_tag_lib: failed opening basis file:Received an Error in Communication
 /home/conda/staged-recipes/build_artifacts/nwchem_1620151640657/work/src/basis/libraries/6-31gs                                                                                                                                                                
 bas_tag_lib: failed opening basis file                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
  current input line : 
     0: 
 ------------------------------------------------------------------------
```

error after:
```
 =======================================================
 QM: Running a very small subset of the available tests 
 =======================================================


 
 Running tests/h2o_opt/h2o_opt 
 
     cleaning scratch
     copying input and verified output files
     running nwchem ($PREFIX/bin/nwchem)  with 2 processors 
 
     NWChem execution failed
 Effective nuclear repulsion energy (a.u.)       7.3282379250

            Nuclear Dipole moment (a.u.) 
            ----------------------------
        X                 Y               Z
 ---------------- ---------------- ----------------
    -0.0000000000     0.0000000000    -0.0000000000

  bas_tag_lib: looking for O               6-31G*                                                                                                                                                                                                                                                         $PREFIX/s
 ------------------------------------------------------------------------
 bas_tag_lib: failed to open basis library                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    66: task scf optimize
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 There is an error in the specified basis set
 ------------------------------------------------------------------------
 For more information see the NWChem manual at https://github.com/nwchemgit/nwchem/wiki


 For further details see manual section:                                                                                                                                                                                                                                                                
```


What puzzles me is the original error message
```
 Attempting to read a basis set from a  non-existing file:
 /home/conda/staged-recipes/build_artifacts/nwchem_1620151640657/work/src/basis/libraries/6-31gs      
```

This reads like nwchem is trying to look for the basis sets in the `work` directory, while it should be looking in `$PREFIX/share/nwchem`.
Is it possible that the line
```
export NWCHEM_BASIS_LIBRARY=$PREFIX/share/nwchem/libraries/
```
is not picked up by the tests?

**Comment by ltalirz** [comment]
thanks @edoapra , I've added your second patch but the error message seems to stay (almost) the same (not sure whether the repetition of `bas_tag_lib: looking for O               6-31G*     ` means anything here): 

```
=======================================================
 QM: Running a very small subset of the available tests 
 =======================================================


 
 Running tests/h2o_opt/h2o_opt 
 
     cleaning scratch
     copying input and verified output files
     running nwchem ($PREFIX/bin/nwchem)  with 2 processors 
 
     NWChem execution failed
 Effective nuclear repulsion energy (a.u.)       7.3282379250

            Nuclear Dipole moment (a.u.) 
            ----------------------------
        X                 Y               Z
 ---------------- ---------------- ----------------
    -0.0000000000     0.0000000000    -0.0000000000

  bas_tag_lib: looking for O               6-31G*                                                                                                                                                                                                                                                         $PREFIX/s
 bas_tag_lib: failed to open basis library                   0
  bas_tag_lib: looking for O               6-31G*                                                                                                                                                                                                                                                         $PREFIX/s
 ------------------------------------------------------------------------
 bas_tag_lib: failed to open basis library                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    66: task scf optimize
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 There is an error in the specified basis set
 ------------------------------------------------------------------------
 For more information see the NWChem manual at https://github.com/nwchemgit/nwchem/wiki

```

**Comment by edoapra** [comment]
@ltalirz Could you `cat` the full  output file?
```
cat $NWCHEM_TOP/QA/testoutputs/h2o_opt.out
```

**Comment by edoapra** [comment]
@ltalirz Could you please remove the two patches I sent you, then send me the output of `h2o_opt.out` after this change?
The changes caused by those two patches I sent have  nefarious effects in various parts of the code, therefore they should be discarded for the time being.

**Comment by ltalirz** [comment]
sure! 

by the way, I've also invited you as a collaborator to my fork in case you'd like to try any changes directly

**Comment by ltalirz** [comment]
I think the relevant bits are 

```
  warning:::::::::::::: from_environment
  NWCHEM_BASIS_LIBRARY set to: <$PREFIX/sh>
  but file does not exist !
  using .nwchemrc or compiled library
  warning:::::::::::::: from_nwchemrc
  NWCHEM_BASIS_LIBRARY set to: </home/conda/staged-recipes/build_artifacts/nwchem_1620258323068/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_>
  but file does not exist !
  using compiled in library
  warning:::::::::::::: from_compile
  NWCHEM_BASIS_LIBRARY is: </home/conda/staged-recipes/build_artifacts/nwchem_1620258323068/work/src/basis/libraries/>
  but file does not exist or you do not have access to it !
 Attempting to read a basis set from a  non-existing file:
 /home/conda/staged-recipes/build_artifacts/nwchem_1620258323068/work/src/basis/libraries/aug-cc-pvdz   
```

I guess in the first case the output is somehow cut short - this looks like the correct path (but it fails because the path is too long).
In the second case I'm not quite sure  where the path comes from but it also points to a non-existing one
In the third case it looks inside the test's working directory, where the library also does not exist.

I will now add it to the $SRC directory and point nwchem there. 
This might solve the issue

**Comment by ltalirz** [comment]
Looks to me like we're getting close...

now I get 
```
 =======================================================
 QM: Running a very small subset of the available tests 
 =======================================================


 
 Running tests/h2o_opt/h2o_opt 
 
     cleaning scratch
     copying input and verified output files
     running nwchem ($PREFIX/bin/nwchem)  with 2 processors 
 
     verifying output ... nwparse.pl failed on test output h2o_opt.out
 
Failed
```

Is there a way to see a more verbose output of the parsing script?
In general, does the script make assumptions about any files being present other than the contents of the `QA` folder?

**Comment by edoapra** [comment]
Do you have `perl` installed? If `perl` is installed, it might well be some required perl components are missing.
You can see  what the `nwparse.pl` script does by executing
```
cd $NWCHEM_TOP/QA
perl nwparse.pl testoutputs/h2o_opt.out
```

**Comment by edoapra** [comment]
Added a comment in
https://github.com/ltalirz/staged-recipes/commit/943ddf337c3bf9aa1900c142ed029505c92086bb

**Comment by ltalirz** [comment]
> Not sure if changing the stacksize is going to help

You would suggest `ulimit -s unlimited`?

**Comment by ltalirz** [comment]
I guess I'll wait until the tests pass on https://github.com/edoapra/nwchem/commit/c8e634a5378cb30802938b362941f97aae144b21 before including the patch

**Comment by ltalirz** [comment]
> better change
> `make 64_to_32`
> to
> `make 64_to_32 DEPEND_CC=${CC}`
> since this stage is already trying to use `DEPEND_CC`

but no `_CC=${_CC}` for `make 64_to_32` or also that?

**Comment by edoapra** [comment]
> I guess I'll wait until the tests pass on [edoapra/nwchem@c8e634a](https://github.com/edoapra/nwchem/commit/c8e634a5378cb30802938b362941f97aae144b21) before including the patch

Right. The first logs are promising since they show no errors when using `depend.x`
https://github.com/edoapra/nwchem/runs/2520622096?check_suite_focus=true
I would add the patch and see if it fixes the seg fault.
https://github.com/edoapra/nwchem/commit/c8e634a5378cb30802938b362941f97aae144b21.patch

**Comment by edoapra** [comment]
> > better change
> > `make 64_to_32`
> > to
> > `make 64_to_32 DEPEND_CC=${CC}`
> > since this stage is already trying to use `DEPEND_CC`
> 
> but no `_CC=${_CC}` for `make 64_to_32` or also that?

It should not be needed, but it would not hurt to add it. In other words
```
make 64_to_32 DEPEND_CC=${CC} CC=${CC}  _CC=${CC}
```
You might want to add `DEPEND_CC=${CC}` to the `make nwchem_config` line, too, just to be extra cautious
```
make CC=${CC} _CC=${_CC} FC=${FC} _FC=${_FC}  DEPEND_CC=${CC} nwchem_config
```

**Comment by ltalirz** [comment]
On the previous commit it looks to me like the tests are passing, i.e. I think there is hope that we've arrived.

As mentioned previously, if you'd like to be added as a co-maintainer of this conda-forge feedstock, just let me know.

**Comment by ltalirz** [comment]
@conda-forge/staged-recipes Sorry for asking but I've done a couple of feedstocks by now and this has never happened to me:
We just managed to make the `test` stage pass here, and it looks to me like we are caught in an infinite "build-test-loop"(?)

If you look at the [raw logs](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/314125/logs/34) (output is already a bit long for the interactive one) and search for `BUILD START` I have already 4 hits (after the second one, history just repeats itself).

Any ideas what might be causing this?

**Comment by edoapra** [comment]
The runs are marked at successful now (after more than 5 hours).
While trying to follow the log when the job(s) were running, I was under the impression that the log of the penultimate job (https://github.com/conda-forge/staged-recipes/runs/2522601261) seemed to be containing part of the last log (https://github.com/conda-forge/staged-recipes/runs/2522963263)  and the other way around, too ... In other words, two running jobs seems to stepping into each other.
Could you try to run the checks again from scratch to see if my theory has any validity?

**Comment by ltalirz** [comment]
Hmm I can no longer access the logs from https://github.com/conda-forge/staged-recipes/runs/2522601261 ([build not found](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=314093&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd) ).

Let's maybe wait for someone from @conda-forge/staged-recipes to have a look before I start doing something that ends up removing the latest logs as well.
I think it is likely that we are not the first ones to observe this.

**Comment by edoapra** [comment]
According to  
https://github.com/conda-forge/staged-recipes#11-some-checks-failed-but-it-wasnt-my-recipe-how-do-i-trigger-a-rebuild
you can trigger a rebuild by typing
```
git commit --amend
git push -f
```

**Comment by ltalirz** [comment]
Ok, for the record I'm attaching the raw log output of https://github.com/conda-forge/staged-recipes/runs/2522963263
[log.zip](https://github.com/conda-forge/staged-recipes/files/6445384/log.zip).

Will now restart the build to see what happens.

**Comment by isuruf** [comment]
> search for BUILD START I have already 4 hits 

That's for each python version. (3.6, 3.7, 3.8, 3.9)

**Comment by ltalirz** [comment]
Thanks a lot for the hint @isuruf !

@edoapra the python dependency under `run` came from the [recipe I started with](https://github.com/insilichem/conda-recipes/blob/master/nwchem/meta.yaml) - is it actually needed for running nwchem (e.g. do you include some python scripts)?

if not, I can remove it from `run`.

**Comment by edoapra** [comment]
> @edoapra the python dependency under `run` came from the [recipe I started with](https://github.com/insilichem/conda-recipes/blob/master/nwchem/meta.yaml) - is it actually needed for _running_ nwchem (e.g. do you ship some python scripts)?
> 
Yes, NWChem does have  [python interface](https://github.com/nwchemgit/nwchem-wiki/blob/master/Python.md).
It is not strictly necessary to run NWChem. However, the Python interface adds more flexibility for running NWChem.

**Comment by ltalirz** [comment]
Thanks! That leads me to some follow-up questions:
 * which python versions are supported?  
   (in practice, it only matters whether python 3.6-3.9 are supported)
 * is python used during the nwchem build stage?   
   if yes, does the python version used during the build stage need to be the same version as the one where nwchem is installed (e.g. are you building any C-extensions, ...)

**Comment by ltalirz** [comment]
Thanks, in that case the individual builds for the different python versions may be necessary.
It may make sense to eventually split off the python interface into a separate package (say, nwchempy) that depends on nwchem in order to save build time.

Perhaps the conda-forge maintainers have another suggestion for this.

**Comment by ltalirz** [comment]
@conda-forge/staged-recipes, ready for review

**Pull request merged**
