### PR TITLE
Add scisweeper

### PR DESCRIPTION
**Pull request by jan-janssen**
@conda-forge/help-python

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by isuruf** [comment]
Can this recipe be noarch?

**Comment by jan-janssen** [comment]
> Can this recipe be noarch?

In terms of the code it could be, but the `pyfileindex` is using os.stat quite frequently which is not working for windows. Basically on windows the file system information are not updated in time. Therefore I would prefer not to provide a windows version for now.

**Comment by isuruf** [comment]
I think that's fine. PyPI package has the same issue. Having the recipe `noarch: python` reduces CI resources and maintenance.

**Comment by mariusvniekerk** [comment]
We probably dont need to have all the deps in the host section

**Comment by jan-janssen** [comment]
@conda-forge/staged-recipes, ready for review

**Pull request merged**
