### PR TITLE
add redo

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jaimergp** [comment]
Hey @mozbhearsum, would you be ok with being a package maintainer?

**Comment by mozbhearsum** [comment]
> Hey @mozbhearsum, would you be ok with being a package maintainer?

What does that involve? I'm entirely unfamiliar with conda.

**Comment by jaimergp** [comment]
> What does that involve? I'm entirely unfamiliar with conda.

Most of the `conda-forge` infrastructure is automated, so it will mainly involve reviewing bot-submitted PRs for the new versions. This is pure Python with no dependencies, so that's it. I would also be a maintainer, so the chances that you have to do something are close to zero, but I like having one of member of the project team as a maintainer.

**Review by chrisburr — APPROVED** [review]

**Comment by mozbhearsum** [comment]
> > What does that involve? I'm entirely unfamiliar with conda.
> 
> Most of the `conda-forge` infrastructure is automated, so it will mainly involve reviewing bot-submitted PRs for the new versions. This is pure Python with no dependencies, so that's it. I would also be a maintainer, so the chances that you have to do something are close to zero, but I like having (at least) one of members of the project team as a maintainer.

Let's give it a shot. I reserve the right to back out later :)

**Pull request merged**
