### PR TITLE
Adding `chalk-diagrams` from PyPI

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sugatoray** [comment]
Opened an issue to add the license file to the upstream-repository and also to the PyPI source.

- https://github.com/danoneata/chalk/issues/26

**Comment by sugatoray** [comment]
PR is ready. Request for review/merging.

cc: @conda-forge/help-python

**Comment by BastianZim** [comment]
If you have the time, it would be nice if you could patch the Windows error as well upstream. Or are you already doing that somewhere?

**Comment by sugatoray** [comment]
@BastianZim The upstream maintainers only tested this on Mac OS and Linux so far. So, am not aware of any fix being worked on. 

If I were to use a patch, how would I?

**Comment by BastianZim** [comment]
Ahh ok then it's not a problem. 

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 544: character maps to <undefined>` this line generally occurs when there is a funny character in the readme or so but I haven't actually checked if that's the case – was just suspecting it.

Ref: https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character

**Pull request merged**
