### PR TITLE
add libvpx from Anaconda

### LINKED ISSUE #6579: Package x265
Would be great to have a package for `x265`. Particularly for `ffmpeg` ( https://github.com/conda-forge/ffmpeg-feedstock/pull/35 ).

### PR DESCRIPTION
**Pull request by hmaarrfk**
xref: #6579
Taken from Anaconda recipes.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Why is it trying to use AVX for mac?

**Comment by hmaarrfk** [comment]
It seems I have to pick mp-clang-3.9 exactly.

https://trac.macports.org/ticket/55800

I guess the compiler upgrade can't come soon enough.

**Comment by hmaarrfk** [comment]
Maybe we just need to disable avx512 on mac osx

https://github.com/Homebrew/homebrew-core/blob/master/Formula/libvpx.rb#L30

**Comment by hmaarrfk** [comment]
@conda-forge/staged-recipes does anybody have a clue how to deal with the changing sha256 everytime I download the archive? Why is google doing that?

**Comment by ocefpaf** [comment]
> @conda-forge/staged-recipes does anybody have a clue how to deal with the changing sha256 everytime I download the archive? Why is google doing that?

I would bring this up with the source upstream. Archives should not change the checksum :-/

**Comment by kmuehlbauer** [comment]
@hmaarrfk @ocefpaf That hash changes constantly because AFAIK the thing is gzipped on the fly. That leads to changing hashes. But there is one tarball without that issue: https://chromium.googlesource.com/webm/libvpx/+archive/f80be22a1099b2a431c2796f529bb261064ec6b4.tar.gz
But that one is not so *nice*.

**Comment by ocefpaf** [comment]
> @hmaarrfk @ocefpaf That hash changes constantly because AFAIK the thing is gzipped on the fly. That leads to changing hashes


Ouch! I guess we can download it once and serve it somewhere to avoid that but it is also not a good approach :-/

**Comment by hmaarrfk** [comment]
Thanks for chiming in @kmuehlbauer, but I still get different SHAs:

```bash
$ wget -q https://chromium.googlesource.com/webm/libvpx/+archive/f80be22a1099b
  2a431c2796f529bb261064ec6b4.tar.gz       
$ sha256sum f80be22a1099b2a431c2796f529bb261064ec6b4.tar.gz                   
38bb26010ed9db3f10e5b7074daa587c9e1aa33c6c47abda383df7884467f7d6  f80be22a1099b2a431c2796f529bb261064ec6b4.tar.gz
mark2@xps ~/Downloads                                                   
$ rm f80be22a1099b2a431c2796f529bb261064ec6b4.tar.gz                          
mark2@xps ~/Downloads                                                   
$ wget -q https://chromium.googlesource.com/webm/libvpx/+archive/f80be22a1099b
  2a431c2796f529bb261064ec6b4.tar.gz                                          
mark2@xps ~/Downloads                                                   
$ sha256sum f80be22a1099b2a431c2796f529bb261064ec6b4.tar.gz                   
6e2235f082f469c1a6d2f990283a5da82619618fc8c00cd56815f23b0e841bda  f80be22a1099b2a431c2796f529bb261064ec6b4.tar.gz
```

**Comment by kmuehlbauer** [comment]
@hmaarrfk Hmm, I checked this few minutes ago. I'll have a second look. Maybe I sent you the wrong link.

**Comment by hmaarrfk** [comment]
Is this because the timestamps are changing? I feel silly making a mirror for VPX.....

**Comment by kmuehlbauer** [comment]
Yes, gzip adds the current timestamp in this process, AFAIK.

**Comment by kmuehlbauer** [comment]
@hmaarrfk How about using the code name: https://chromium.googlesource.com/webm/libvpx/+archive/mandarinduck.tar.gz
This seems to be a pre-built tarball.

**Comment by hmaarrfk** [comment]
xref: https://bugs.chromium.org/p/webm/issues/detail?id=1582

**Comment by kmuehlbauer** [comment]
Seems there is no real solution to this..
:cry:

**Comment by hmaarrfk** [comment]
This is the real issue: 

https://github.com/google/gitiles/issues/84

**Comment by kmuehlbauer** [comment]
This looks to me like a failure in design. It might make sense for changing endpoints (eg. master branch) to create the tarball at time of request. But for those endpoints which should not change (like tags or releases) this doesn't make any sense to me.

**Comment by hmaarrfk** [comment]
ok, well I left a lengthy comment and just went with git. 

Hopefully this is OK. Builds should pass.

**Pull request closed without merging**
