### PR TITLE
Add effect

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by kalefranz** [comment]
Needs python `testtools` package to pass...

**Comment by msarahan** [comment]
Please go ahead and add a testtools recipe here, if it is required for effect to work.

**Comment by kalefranz** [comment]
> Please go ahead and add a testtools recipe here, if it is required for effect to work.

Yep, planning on it!

**Comment by kalefranz** [comment]
Ok so testtools has about five other dependencies all part of this one github org https://github.com/testing-cabal/.  I started down the path of building all of them, except they all have this gnarly circular dependency chain: you can't build and test any of them without testtools, but you can't build and test testtools without these dependencies.

So since testtools is needed only for the test phase, what do you conda-forge guys (@pelson, @jakirkham, @ocefpaf, @msarahan et al) think of pip installing that into the test env, as I did in the latest commit?

**Comment by kalefranz** [comment]
green!

**Comment by msarahan** [comment]
Thanks!

**Comment by jakirkham** [comment]
@radix, just letting you know that we have added `effect` to [conda-forge]( http://conda-forge.github.io/ ). This will allow users to easily install this with [`conda`]( http://conda.pydata.org/docs/ ) ( [`conda install -c conda-forge effect`]( http://anaconda.org/conda-forge/effect ) ). The maintenance burden here is light as all releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this feedstock (repo)]( https://github.com/conda-forge/effect-feedstock ). If you have any interest in being added as a maintainer (useful for making new releases for instance), we would be more than happy to add you to the maintainers list.

**Comment by radix** [comment]
Thank you @kalefranz and @jakirkham! I probably don't have time to learn about how Conda maintainership works at the moment, but please feel free to ping me in the future about any issues relating to Effect. If/when I make another Effect release I will try to look into updating the Conda package.

**Pull request merged**
