### PR TITLE
Add ordered-set

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @benjwadams. This is the recipe you sent to IOOS, so I added you as a maintainer here.

xref: https://github.com/ioos/conda-recipes/pull/821

### CODE REVIEW

**Comment by jakirkham** [comment]
Tried restarting Travis CI a few times, but it is not working. Believe it is this issue ( https://github.com/conda-forge/staged-recipes/issues/458 ) still.

**Comment by ocefpaf** [comment]
Don't worry. We'll figure it out tomorrow.

**Comment by jakirkham** [comment]
I hope so. :four_leaf_clover:

**Comment by jakirkham** [comment]
What can I say after several retries it cleared. :smile: 

Still the CircleCI issue is definitely here, but it is sporadic.

**Comment by ocefpaf** [comment]
Thanks for re-trying it!

**Pull request merged**
