### PR TITLE
Add asgiref

### LINKED ISSUE #6872: Package asgiref
https://github.com/django/asgiref/

### PR DESCRIPTION
**Pull request by dhirschfeld**
Closes #6872

### CODE REVIEW

**Comment by dhirschfeld** [comment]
***c.c.*** @carlodri

**Comment by carlodri** [comment]
LGTM! thanks @dhirschfeld!

Maybe add this reference https://github.com/django/asgiref/pull/70 in a comment just above the `license_file` entry, to keep track of things. You can skip ci obviously.

**Comment by dhirschfeld** [comment]
@conda-forge/staged-recipes could someone please review and merge this?

**Comment by dhirschfeld** [comment]
Sorry @carlodri - I didn't read your comment properly. I'm now watching that PR so will remove the license when it's no longer necessary...

**Pull request merged**
