### PR TITLE
add nteract-scrapbook 0.3.1

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/papermill @conda-forge/nteract_on_jupyter anybody interested in co-maintaining?

**Comment by bollwyvl** [comment]
@conda-forge/help-python ready for review!

**Comment by bollwyvl** [comment]
Thanks!

**Comment by MSeal** [comment]
As the primary scrapbook author, I should probably be on the list for helping the feedstock -- just hard to dedicate the time to monitor and repair the large number of parallel feedstocks to the PyPI release paths.

**Comment by bollwyvl** [comment]
@mseal all your efforts indeed greatly appreciated: we try to do the best we can to make it easy on upstreams. i'll open a PR over there, and will just need a quick comment from you there to confirm...

**Pull request merged**
