### PR TITLE
Skip noarch recipes on Travis and AppVeyor

### PR DESCRIPTION
**Pull request by jdblischak**
Noarch recipes are currently built unnecessarily in PRs to staged-recipes. This uses up CI time and also causes failures (since the recipes are only intended to run on CircleCI).

The bash code for Travis should work fine. However, I wasn't able to thoroughly test the code for AppVeyor. I based it off of the line to remove recipes in master, but I couldn't execute that code on my local Windows 10 machine (using either Command Shell or PowerShell). I confirmed that `grep -l "noarch:" */meta.yaml` will return the list of `meta.yaml` files that contain "noarch:", but I couldn't figure out how to pipe it to `dirname`.

cc: @CJ-Wright @bgruening 
xref: https://github.com/conda-forge/conda-forge.github.io/issues/683

### CODE REVIEW

**Comment by CJ-Wright** [comment]
ping @conda-forge/staged-recipes and @conda-forge/core

**Comment by jdblischak** [comment]
@CJ-Wright Thanks! But please don't merge until someone can test out the AppVeyor script. I don't think it currently works. If no one offers to test it locally, I can push a test commit with some fake recipes to test (and then remove the commit once we're satisfied the CI scripts are working).

**Comment by jdblischak** [comment]
We chose to fix the linter instead in https://github.com/conda-forge/conda-smithy/pull/966

**Comment by CJ-Wright** [comment]
Are those PRs fixing the same thing? It seems that this PR will reduce our CI load on staged recipes.

**Comment by jdblischak** [comment]
@CJ-Wright Yes. I created both of these PRs as alternative solutions to Issue https://github.com/conda-forge/conda-forge.github.io/issues/683. @isuruf wants to continue building noarch recipes for all 3 platforms (see https://github.com/conda-forge/conda-forge.github.io/issues/683#issuecomment-446368514), thus we went with the linter change. If conda-forge core decides that noarch recipes shouldn't be built for all 3 platforms for staged-recipes PRs, this PR could be reopened.

**Pull request closed without merging**
