### PR TITLE
Add aiida-workgraph

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge/staged-recipes, ready for review

**Comment by jan-janssen** [comment]
@conda-forge/help-python

**Comment by jan-janssen** [comment]
@synapticarbors Thanks for the suggestion - I updated the recipe.

**Comment by synapticarbors** [comment]
It's unclear to me why `python_min` is missing on osx and win, but not linux. @conda-forge/staged-recipes -- does anyone have any idea on why these are failing? The recipe looks fine to me.

**Comment by jan-janssen** [comment]
The windows and Mac OS tests fail with: 
```
Traceback (most recent call last):
  File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/metadata.py", line 2005, in _get_contents
    rendered = template.render(environment=env)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniforge3/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/runner/miniforge3/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/runner/work/1/s/recipes/node-graph/meta.yaml", line 19, in top-level template code
    - python {{ python_min }}
jinja2.exceptions.UndefinedError: 'python_min' is undefined
```

**Comment by jan-janssen** [comment]
@synapticarbors Is it possible to merge the pull request as is or should I revert back to the old format without `python_min` which worked fine on Windows and MacOS ?

**Comment by synapticarbors** [comment]
I'm still confused to why this is failing like this. One solution might be to use a jinja variable in the recipe to mirror what should be the global pin (`{% set python_min = "3.9" %}`), although I would like to know why this is happening.

**Pull request merged**
