### PR TITLE
add aws stuff

### PR DESCRIPTION
**Pull request by ocefpaf**
- [x] aws-cdk.assets
- [x] aws-cdk.aws-acmpca
- [x] aws-cdk.aws-apigateway
- [x] aws-cdk.aws-applicationautoscaling
- [x] aws-cdk.aws-autoscaling
- [x] aws-cdk.aws-autoscaling-common
- [x] aws-cdk.aws-autoscaling-hooktargets
- [x] aws-cdk.aws-batch
- [x] aws-cdk.aws-certificatemanager
- [x] aws-cdk.aws-cloudformation
- [x] aws-cdk.aws-cloudfront
- [x] aws-cdk.aws-cloudwatch
- [x] aws-cdk.aws-codebuild
- [x] aws-cdk.aws-codecommit
- [x] aws-cdk.aws-codeguruprofiler
- [x] aws-cdk.aws-codestarnotifications
- [x] aws-cdk.aws-cognito
- [x] aws-cdk.aws-dynamodb
- [x] aws-cdk.aws-ec2
- [x] aws-cdk.aws-ecr
- [x] aws-cdk.aws-ecr-assets
- [x] aws-cdk.aws-ecs
- [x] aws-cdk.aws-efs
- [x] aws-cdk.aws-elasticloadbalancing
- [x] aws-cdk.aws-elasticloadbalancingv2
- [x] aws-cdk.aws-events
- [x] aws-cdk.aws-fsx
- [x] aws-cdk.aws-globalaccelerator
- [x] aws-cdk.aws-iam
- [x] aws-cdk.aws-imagebuilder
- [x] aws-cdk.aws-kinesis
- [x] aws-cdk.aws-kms
- [x] aws-cdk.aws-lambda
- [x] aws-cdk.aws-logs
- [x] aws-cdk.aws-route53
- [x] aws-cdk.aws-route53-targets
- [x] aws-cdk.aws-s3
- [x] aws-cdk.aws-s3-assets
- [x] aws-cdk.aws-sam
- [x] aws-cdk.aws-secretsmanager
- [x] aws-cdk.aws-servicediscovery
- [x] aws-cdk.aws-signer
- [x] aws-cdk.aws-sns
- [x] aws-cdk.aws-sns-subscriptions
- [x] aws-cdk.aws-sqs
- [x] aws-cdk.aws-ssm
- [x] aws-cdk.aws-stepfunctions
- [x] aws-cdk.cloud-assembly-schema
- [x] aws-cdk.core
- [x] aws-cdk.custom-resources
- [x] aws-cdk.cx-api
- [x] aws-cdk.region-info
- [x] constructs

### CODE REVIEW

**Comment by ocefpaf** [comment]
> * A conda package with same name (python-jsii) already exists.

We can remove it here when https://github.com/conda-forge/python-jsii-feedstock/pull/35 is merged.

**Comment by ocefpaf** [comment]
Looks like 3 > 10 for construct :-/

Fixing that in the next commit.

Screenshot_2023-07-29-11-56-49-093-edit_com android chrome

**Comment by rsignell-usgs** [comment]
Phew, exhausting!  Thanks for the good fight, @ocefpaf!

**Comment by ocefpaf** [comment]
It has been a while that I've seen such an intricate set of packages!

Screenshot from 2023-07-30 15-16-21

**Comment by ocefpaf** [comment]
@conda-forge/staged-recipes this one is ready for review.

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
