### PR TITLE
Try to build pyshtools

### PR DESCRIPTION
**Pull request by megies**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by megies** [comment]
Not sure why it's not finding the Python header, as far as I can see it's always present in conda..

```
    creating build/temp.linux-x86_64-3.6/src
    compile options: '-I/home/conda/feedstock_root/build_artifacts/pyshtools_1565604404052/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages/numpy/core/include -c'
    x86_64-conda_cos6-linux-gnu-cc: src/_SHTOOLSmodule.c
    src/_SHTOOLSmodule.c:14:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    src/_SHTOOLSmodule.c:14:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
```

**Comment by leouieda** [comment]
@megies I'm interested in keeping this open and trying to get it done. I don't know what went wrong but could you try rebasing onto the master branch to see what happens?

**Comment by megies** [comment]
@leouieda sure thing, rebased on current master

**Comment by leouieda** [comment]
That's curious. I'm having the same problem trying to build shtools locally using conda libraries. Would you mind upgrading to version 4.5?

**Comment by megies** [comment]
Can do

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by megies** [comment]
Closing in favor of #11298 which seems good to go.

CC @leouieda

**Pull request closed without merging**
