### PR TITLE
Add bfio recipe

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- ~[ ] If static libraries are linked in, the license of the static library is packaged.~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Depends on:
- https://github.com/conda-forge/ome-types-feedstock/pull/5

### CODE REVIEW

**Comment by goanpeca** [comment]
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be automatically open, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the @conda-forge/napari team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

--- 

@Nicholas-Schaub, do you agree with being added as a maintainer?

**Comment by Nicholas-Schaub** [comment]
Yes, please do add me as a maintainer. However, I am in the process of changing how the `bfio` Napari plugin works. Right now it's wrapped directly into the `bfio` package. What I'm doing in the next week is creating a separate repository for the Napari plugin. I think it would be a good idea to wait to merge this until I make that repo and transfer the plugin over.

**Comment by goanpeca** [comment]
>I think it would be a good idea to wait to merge this until I make that repo and transfer the plugin over.

Sounds good @Nicholas-Schaub ! Let us know how that goes or if you have questions :)

**Comment by goanpeca** [comment]
Will continue working on this. Not (yet) stale :)

**Comment by goanpeca** [comment]
Pinging @Nicholas-Schaub

I have seen some new versions released. Is the plan still to split the napari plugin or can we continue with this package?

Cheers!

**Comment by goanpeca** [comment]
Pinging @Nicholas-Schaub

**Comment by goanpeca** [comment]
Pinging @Nicholas-Schaub

**Review by dopplershift — APPROVED** [review]
Just need confirmation from @jaimergp that they're willing to be listed as maintainer for this recipe.

**Comment by jaimergp** [comment]
@dopplershift - yes, thanks!

**Pull request merged**
