### PR TITLE
Added recipe for snakebite

### PR DESCRIPTION
**Pull request by pmlandwehr**
Two notes on this build:

1. I've left out the requirements for `snakebite[kerberos]` because it requires both `sasl` and `python-krbV`, and both of those have been giving us build trouble. I don't know if the default anaconda `snakebite` supports kerberos, but it certainly *doesn’t* support windows. So this seemed like a decent idea.
2. For reasons that are unclear, if I test the `snakebite` console commands, `conda build` reports a test failure. The commands themselves appear to run fine (based on printed output) so I'm not certain what's up. As is, I've omitted those tests, but that's hardly a satisfying explanation.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Pinging @wouterdebie in case he'd like to be added as a maintainer to the `snakebite` builder on [conda-forge](http://conda-forge.github.io), a library of community-built [`conda`](http://conda.pydata.org) packages. The maintenance burden here is light: all testing and releases are built and deployed automatically with CI. Changes to how the package is being built can be controlled by changing the recipe which will be located at https://github.com/conda-forge/snakebite-feedstock shortly after this PR is finished and merged. If you aren't interested in helping maintain the build, that's entirely fine too.

**Comment by pmlandwehr** [comment]
Getting crashes on `py26` build because of conflicts with `protobuf > 2.4.1`. In the [`protobuf` feedstock](https://github.com/conda-forge/protobuf-feedstock) there's nothing banning `py26` builds but it doesn't seem like any have been posted to anaconda.org. Not sure what's up.

**Comment by ocefpaf** [comment]
@pmlandwehr in conda-forge we don't build `PY26`. Only PY27, PY34, and PY35. See https://github.com/conda-forge/staged-recipes/blob/master/.CI/build_all#L27

**Comment by pmlandwehr** [comment]
Well, that would explain it.

**Comment by wouterdebie** [comment]
Happy to help out! Anything you need help with?

**Comment by jakirkham** [comment]
Thanks @wouterdebie.

If you could help make sure we are building `snakebite` correctly here, that would be great.

Also, if you have the bandwidth to help maintain the recipe, that would be awesome. Mainly it should just come down to making new releases. This tends to be a pretty painless process.

If not, letting us know when new releases are coming out is already very helpful. In addition, working with us if we come across any issues with packaging is very useful.

Please let us know what you are comfortable doing.

**Comment by jakirkham** [comment]
LGTM. Is there anything else you are wanting to do here, @pmlandwehr, or is this good to go? I'd also like to wait and see if @wouterdebie has anything to add before merging.

**Pull request merged**
