### PR TITLE
Add astrocats

### PR DESCRIPTION
**Pull request by guillochon**

### CODE REVIEW

**Comment by guillochon** [comment]
Waiting on some dependencies to merge...

**Comment by pmlandwehr** [comment]
Looks like we're missing some packages:
- [ ] `ads`
- [ ] `astroquery`

**Comment by guillochon** [comment]
@pmlandwehr yes these were just merged earlier today, have to wait for them to appear on the forge.

**Comment by pmlandwehr** [comment]
Also, were you seeing crash-outs because of missing packages during build or during the test imports? It's likely (though not certain) that you can switch most build dependencies over to just be runtime dependencies.

**Comment by pkgw** [comment]
Closing and reopening to trigger rebuilds now that `ads` and `astroquery` should be available.

**Comment by pkgw** [comment]
The messages will be lost to history when the feedstock is created, but it would be helpful if your commit message would give a quick explanation of the changes you're making.

**Comment by pkgw** [comment]
Hmm, I'm not sure what's going on with httpretty; it looks like pip should be realizing that it's installed. It's only available for Python 2.7 ... the best course of action might be to replace it something else, since it's looking like it's not a well-supported library.

**Comment by guillochon** [comment]
Yeah except astrocats itself does not depend on `httpretty`, it's one of the packages its including. Which must have been installed via conda.

**Comment by pkgw** [comment]
Well, I can install it in a Python 2 environment and pip seems to see it. What depends on httpretty? What version does it need? If it requires a specific version that's not the one that conda-forge provides (0.8.14), I bet it will give the sort of error that you're seeing.

**Comment by pkgw** [comment]
Yeah, so the `requirements.txt` in the `ads` package specifies that it requires exactly `httpretty = 0.8.10`, which isn't available in conda/conda-forge. Hence the setuptools attempt to download it.

The version pin was added in [this commit](https://github.com/andycasey/ads/commit/c1986957b3a00be5a3aaf8e206be37af33ae8194), which makes me think that it's not really behaving as intended. [This random guy](https://www.peterbe.com/plog/bye-bye-httpretty) ended up ditching httpretty in his Python 3 stuff.

In the long term, it would probably be good to work with @andycasey and figure out a more sustainable solution for the `ads` package. In the short term, it might make sense to issue a new package of `ads` that patches the `requirements.txt` to drop the httpretty requirement. It's only used for testing as far as I can tell, so I'm comfortable hacking it out.

**Comment by guillochon** [comment]
Thanks for the sleuthing @pkgw! Alternatively we could create a conda install for the older version of httpretty?

**Comment by pkgw** [comment]
It is possible to create downgrades if you really really have to, but it is deeply baked in that versions shall only move forwards, not backwards.

CC [ads-feedstock#2](https://github.com/conda-forge/ads-feedstock/pull/2).

**Pull request merged**
