### PR TITLE
Add gammpy to conda-forge

### PR DESCRIPTION
**Pull request by mwcraig**
@cdeil -- could you please confirm that you are willing to be listed as a maintainer on this? Being a maintainer just means you will have the ability to update gammapy's version when you make a new release. Builds here will automatically be copied over to the astropy channel also.

### CODE REVIEW

**Comment by mwcraig** [comment]
Note that @bsipocz agreed to be added to multiple recipes at https://github.com/conda-forge/staged-recipes/pull/3407#issuecomment-319965382

**Comment by dougalsutherland** [comment]
Just a note that the failures here are because there's not yet a conda-forge package for [regions](https://pypi.python.org/pypi/regions/).

**Comment by mwcraig** [comment]
Thanks, I'll try to fix that later today.

**Comment by cdeil** [comment]
@mwcraig - Yes, of course I'd be happy to be listed as maintainer for `gammapy` (and also `regions` if you're making a recipe for that also).

@adonath or @joleroi -- would you also be willing to be listed as maintainer for the conda-forge recipe for `gammapy`. Like @mwcraig said above, this isn't really a big commitment, just:

> Being a maintainer just means you will have the ability to update gammapy's version when you make a new release. Builds here will automatically be copied over to the astropy channel also.

**Comment by mwcraig** [comment]
PR to add regions is #3456

**Comment by bsipocz** [comment]
@mwcraig - can you close-reopen to trigger appveyor and circle to rebuild?

**Comment by mwcraig** [comment]
I think something funny is happening with circleCI because regions hasn't built on circle yet...

**Comment by bsipocz** [comment]
and appveyor has that issue I had this afternoon locally while trying to build pytest...

**Comment by mwcraig** [comment]
@cdeil -- I'll add the others as maintainers once the feedstock is created.

**Pull request merged**
