### PR TITLE
Add altair recipe

### PR DESCRIPTION
**Pull request by jakevdp**
This adds an [altair](http://github.com/ellisonbg/altair) recipe to conda-forge.

The recipe currently points at the v1.0.0rc2 release candidate; before merging the PR, we should wait for altair version 1.0 to be released and then update the version/md5 in the recipe.

CC/ @ellisonbg

### CODE REVIEW

**Comment by ellisonbg** [comment]
Altair 1.0.0 is released. Here is the tag:

https://github.com/ellisonbg/altair/tree/1.0.0

@jakevdp do you want to point this PR at that and then can it be merged?

**Comment by ellisonbg** [comment]
Awesome! After everything passes, this should be ready to go!

**Comment by jakevdp** [comment]
Already getting some strange failures on appveyor: it's complaining it can't find a bunch of packages named ``bob.*``.

**Comment by jakevdp** [comment]
Looks like some sort of spill-over from #498. Not sure why that would happen

**Comment by jakevdp** [comment]
Even the travis scripts seem to be testing the ``bob`` package rather than the ``altair`` package. Something screwy is happening here. Have you ever seen this kind of cross-talk between PRs?

**Comment by jjhelmus** [comment]
> Have you ever seen this kind of cross-talk between PRs?

This sometimes happens when the feedstock creation fails and a package in staged-recipes does not get correctly removed.  @jakirkham or @ocefpaf have some methods for fixing this and would know more about the issue.

**Comment by jakevdp** [comment]
Cool... hopefully the experts can figure it out :smile:

**Comment by jakevdp** [comment]
I'm realizing now I should have had the rc2 recipe merged previously, so that I could control the 1.0 release. We'd like to get this finished ASAP, because we've already announced the package with install instructions depending on this PR being merged (oops).

**Comment by ocefpaf** [comment]
> This sometimes happens when the feedstock creation fails and a package in staged-recipes does not get correctly removed.

Not sure that is the case here. My guess it is an old issue re-surfacing. Latest conda has a render recipe step that `conda-build-all` was not ready for it. In theory this was fixed. I need to take a closer look to see if we are pinning versions somewhere to diagnose this.

@pelson could this still be related to https://github.com/SciTools/conda-build-all/issues/41 ?

**Comment by jakirkham** [comment]
So the reason those recipes haven't occurred is the Travis CI API has been giving us some issues. This affects our ability to register a new feedstock for CI and configure it to upload to the conda-forge channel. See this long list of related problems caused by it ( https://github.com/conda-forge/staged-recipes/issues/923 ).

@pelson and I have looked into it some, but it seems that this problem is not unique to conda-forge. It also comes and goes sporadically making it hard to identify and try to fix. Instead it may be a larger Travis CI API issue and have raised it upstream ( https://github.com/travis-ci/travis-ci/issues/6284 ). Hopefully someone can give us some insight.

In the meantime, feel free to merge this branch with `master` and remove any recipes that are not in your PR. That will at least give you a clean place to work.

**Comment by jakevdp** [comment]
Thanks @jakirkham. I merged with master and then removed the ``bob`` recipe there. Fingers crossed!

**Comment by jakevdp** [comment]
Shoot. Forgot to remove cliff recipe. Sorry for the extra CI load.

**Comment by ocefpaf** [comment]
@jakevdp I did not see any lingering recipes in https://github.com/conda-forge/staged-recipes/pull/1014/commits/69d2ae68c7394f0a97396ca84001be6306d22026

Hopefully the rebase will just do...

**Comment by jakevdp** [comment]
But there are two recipes currently in master: https://github.com/conda-forge/staged-recipes/tree/master/recipes

These are the ones I had to remove manually after merging.

**Comment by ocefpaf** [comment]
Argh.. I missed that. I see AppVeyor is already on its path to green!

**Comment by jakevdp** [comment]
Tests passed! If things look clear, I'd love to see this merged – thanks!

**Comment by jakirkham** [comment]
Glad to see this working. Sorry for the annoying workaround @jakevdp.

**Comment by jakevdp** [comment]
No problem – thanks for the help debugging it!

**Comment by jakirkham** [comment]
LGTM

**Comment by pelson** [comment]
@jakirkham - do you have a plan for ensuring cliff and bob... get feedstocked after this is merged? 
That is my only hesitation for this PR, otherwise 👍

**Comment by ocefpaf** [comment]
@pelson I am monitoring [`cliff`](https://github.com/conda-forge/cliff-feedstock) and the answer is no :unamused: 

No idea what happened to `bob` nor why it was failing.

@jakevdp in theory you could leave passing recipes there without them influencing yours besides the CI time.

**Comment by jakevdp** [comment]
> in theory you could leave passing recipes there without them influencing yours besides the CI time.

Except it looks like ``bob`` doesn't build on windows... would that prevent ``altair`` from building on windows as well?

**Comment by pelson** [comment]
> would that prevent altair from building on windows as well?

No, it shouldn't. So, this recipe is good to go. Since I know you guys could do with the feedstock in fairly short order, I'm going to feedstock it by hand.

**Comment by ocefpaf** [comment]
> Except it looks like ``bob`` doesn't build on windows... would that prevent ``altair`` from building on windows as well?

That should not be a problem if the feedstocks are created properly. (Also I belve **a**ltair would get build before **b**bob :wink:)

@183amir any idea why the failure was there? You usually add `skip: True  # [win]`, right? Something is weird in that failure.  Anyways, finding what it was is beyond your PR @jakevdp. We need to make the recipe creation "imune" to lingering recipes.

**Comment by jakevdp** [comment]
>  I'm going to feedstock it by hand.

Appreciate it – thanks so much!

**Comment by jakirkham** [comment]
> Except it looks like ``bob`` doesn't build on windows... would that prevent ``altair`` from building on windows as well?

Ah, wasn't looking so closely that puts @ocefpaf's comment in the right context. So, maybe there is a `conda-build-all` issue resurfacing too or things got a little stale here.

**Comment by jakirkham** [comment]
> @jakirkham - do you have a plan for ensuring cliff and bob... get feedstocked after this is merged?
That is my only hesitation for this PR, otherwise 👍

I also have that concern, @pelson. Though I don't really have any magic fixes ATM.

I think we should let them sit unless there is an urgent need for them. It would be great if we could do a chat on Saturday (assuming we have some more info/ideas to work with) and figure out something to do for these Travis CI API issues.

**Comment by pelson** [comment]
So I added https://github.com/conda-forge/altair-feedstock by hand off the back of this PR. I haven't run the team management script, so currently you won't have merge rights @jakevdp and @ellisonbg, but at least that should get you going for installable an package. I'm going to work on a few mitigation strategies to avoid the awkward TravisCI issues we are seeing. 

The error that prompted you to remove those recipes is a genuine bug and I'll take a look at addressing that shortly.

**Comment by jakirkham** [comment]
AFAICT merging this shouldn't harm anything, but it isn't strictly necessary either.

**Comment by jakirkham** [comment]
I say that as the removed recipes are already cleared now.

**Pull request merged**
