### PR TITLE
Ifcopenshell

### PR DESCRIPTION
**Pull request by looooo**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge/coris one should be ready

**Comment by looooo** [comment]
@conda-forge/core please review and merge.

**Comment by jjhelmus** [comment]
LGTM

**Comment by looooo** [comment]
Thx

**Pull request merged**
