### PR TITLE
Add r-modes

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge/help-r Is there a way to properly do a `noarch: generic` on staged-recipes when building on windows has a requirement? I assume actually rerendering would then muck up other staged recipes.

**Comment by bgruening** [comment]
Leave `noarch: generic` and remove the zip for the moment. Windows build will fail but we will merge and since it will be a noarch this does not matter. @jdblischak is fixing this at the moment.

**Comment by dpryan79** [comment]
Ah, good to know, thanks!

**Comment by jdblischak** [comment]
@dpryan79 As @bgruening noted, the short-term solution is to remove `{{posix}}zip`. If you pull the latest changes of the [helper script](https://github.com/bgruening/conda_r_skeleton_helper), it will do this for you automatically.

Long-term I've submitted 2 potential solutions to this issue (https://github.com/conda-forge/conda-forge.github.io/issues/683):

1. Skip Travis/AppVeyor for noarch recipes submitted to staged-recipes #7239
1. Change the linter to only check for selectors in runtime dependencies https://github.com/conda-forge/conda-smithy/pull/966

Neither has generated much enthusiasm, so I'm not sure when this issue will be resolved.

**Pull request merged**
