### PR TITLE
Adding explainerdashboard

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [NA] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by raybellwaves** [comment]
Not sure if CI failure is related to the package?

`ValueError: variant config in /home/conda/staged-recipes-copy/.ci_support/linux64.yaml is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented.`
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=237349&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=508

**Comment by raybellwaves** [comment]
Windows CI is useful:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=237349&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77&l=123

```
conda.exceptions.ResolvePackageNotFound: 
  - dtreeviz[version='>=1.0']
  - dash-auth
  - jupyter-dash
```

**Comment by raybellwaves** [comment]
Working on dtreeviz here:

https://github.com/conda-forge/staged-recipes/pull/13191

**Comment by oegedijk** [comment]
Thanks for picking this up! I think dtreeviz could be tricky due to the graphviz dependency though!

**Comment by oegedijk** [comment]
jupyter-dash is on https://anaconda.org/plotly/repo instead of conda-forge but dash-auth doesn't seem to be there. Maybe could ping them.

**Comment by raybellwaves** [comment]
Thanks.

@oegedijk are you happy to be added to the maintainers?

**Comment by oegedijk** [comment]
> Thanks.
> 
> @oegedijk are you happy to be added to the maintainers?

Sure! Please add me!

**Comment by raybellwaves** [comment]
@conda-forge-admin, please restart ci

**Comment by raybellwaves** [comment]
need to take a look at dash-auth next

**Comment by raybellwaves** [comment]
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'jupyter-dash'}

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=245489&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=596

I'll look at adding soon.

**Comment by raybellwaves** [comment]
jupyter-dash PR here: https://github.com/conda-forge/staged-recipes/pull/13357

**Comment by raybellwaves** [comment]
@conda-forge-admin, please restart ci

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
