### PR TITLE
Add a few CRAN packages

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge/help-r This is ready to be merged.

**Comment by dbast** [comment]
Please revert the fix compilers change and ignore the linter for now.

Also don't strip the description which is appended at the end of the meta.yaml. That was stripped in the past, but turned out to be very useful for reviewing etc.

**Comment by dbast** [comment]
Done

**Comment by dpryan79** [comment]
Good to know, thanks!

**Comment by dbast** [comment]
Thanks!

**Pull request merged**
