### PR TITLE
Added recipe for pyaml

### PR DESCRIPTION
**Pull request by pmlandwehr**
Added a recipe for [pyaml](https://pypi.python.org/pypi/pyaml), which improves [PyYAML](https://pypi.python.org/pypi/PyYAML). Also pinging @mk-fg in case he's interested in being a maintainer to help make sure that future versions of the package are rapidly built for conda-forge.

### CODE REVIEW

**Comment by jakirkham** [comment]
So, we already have this. 😕

Would you like to change something about it? Here's the [feedstock]( https://github.com/conda-forge/pyyaml-feedstock ) if you would like to propose a change or are just curious.

**Comment by jakirkham** [comment]
Sorry, missed one less `y`. What is the difference between the two?

**Comment by pmlandwehr** [comment]
I had needed it before (pre-conda forge) as a dependency for a few other modules. (Would need to dig to find which one. Since there isn't an Anaconda version, it seemed worth adding. Fundamentally, it wraps various `pyyaml` features for additional prettiness and ease-of-use.

**Comment by mk-fg** [comment]
First time I heard of Conda, to be honest, and since I'm obviously not using Conda myself, I'd be a terrible candidate for maintaining anything here, unfortunately.

Don't know which modules use pyaml either, never checked, but there's probably some pypi tool that can do that, by looking at dependencies in setup.py for all registered modules.

Thing is indeed a rather simple wrapper around PyYAML, currently passing a few options to it, overriding few dumpers, and such.
Most things it used to do either PyYAML does well enough now, or I just found a way to do properly with PyYAML by finding right dumper options, so not sure how relevant the module is by now, and I rarely need it myself.

**Comment by ocefpaf** [comment]
@pmlandwehr looks like this will be a legacy module then. Perfect job for conda-forge (and low maintenance I guess :wink:)

**Pull request merged**
