### PR TITLE
test patching with conda-forge-build-setup=4

### PR DESCRIPTION
**Pull request by dolfim**
this is supposed to fail in the windows CI with conda-forge-build-setup=4

### CODE REVIEW

**Comment by ocefpaf** [comment]
If I had to guess this is related to `conda-build 2` can you try pinning to `conda-build=1` right after the setup just to confirm that?

I believe that upgrading `miniconda` in the CIs will fix that. At least I remember doing that in another project and it fixed the issues.

**Comment by dolfim** [comment]
@ocefpaf this seems to work, but it is not a fix for the staged-recipes since it is touching the CI scripts, or?

**Comment by ocefpaf** [comment]
Indeed. Sorry... But we need a permanent solution for that.

Some time ago @msarahan helped me fix that bug in another project and after some PRs to `conda-build 2`, we finally fixed that by downloading latest miniconda in the CIs.

Miniconda was updated recently in AppVeyor... Making this even more confusing. I will try to revise the `appveyor.yml` to see if I can catch anything.

Meanwhile we can merge your PR and then you can hack the CIs script in the feedstock to install `conda-build=1`. That is not ideal but better then changing the scripts in staged-recipes.

**Comment by jakirkham** [comment]
Could you please raise an issue on the `conda-build` issue tracker with a link back this PR, @dolfim ? Also please note in the issue that you are using `conda-build` 2.1.0 when this issue occurs. Thanks.

**Comment by dolfim** [comment]
This is solved in ```conda-build 2.1.1``` which is automatically be pulled in the CI machines.

**Pull request closed without merging**
