### PR TITLE
Add robot-testing-framework recipe

### PR DESCRIPTION
**Pull request by traversaro**
[`robot-testing-framework`](https://robotology.github.io/robot-testing-framework/) is a testing framework specifically taylored for robotic and cypher physicals systems, that is described in detail in the paper ["A Generic Testing Framework for Test Driven Development of Robotic Systems"](https://link.springer.com/chapter/10.1007/978-3-319-22383-4_17) . 
`robot-testing-framework` is already packaged under the same name in the Debian/Ubuntu distros: https://repology.org/project/robot-testing-framework/versions .

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
The PR is ready for review. @conda-forge/help-c-cpp

**Review by xhochy — APPROVED** [review]

**Comment by traversaro** [comment]
> 
> 
> The PR is ready for review. @conda-forge/help-c-cpp

Actually it still had a few typos in the testing section on Windows, sorry for the noise. Hopefully is should be ok now.

**Comment by traversaro** [comment]
> 
> 
> > The PR is ready for review. @conda-forge/help-c-cpp
> 
> Actually it still had a few typos in the testing section on Windows, sorry for the noise. Hopefully is should be ok now.

The CI is finally actually green.

**Comment by traversaro** [comment]
Thanks @xhochy !

**Pull request merged**
