### PR TITLE
Add torchapp

### PR DESCRIPTION
**Pull request by vinisalazar**
Depends on #23426.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by rbturnbull** [comment]
I confirm that I am a maintainer.

**Comment by vinisalazar** [comment]
@rbturnbull could you please have a look at the "test" section of this recipe? Apparently it's what's causing the checks to fail.

**Comment by vinisalazar** [comment]
@rbturnbull I had a go at improving the test section of the recipe, now it's a matter to get the `pytest` command to pass all tests.

**Comment by rbturnbull** [comment]
Hi @vinisalazar - thanks for your work on this. I'm sorry I missed your messages. I'll work on it now.

**Comment by rbturnbull** [comment]
Hi @vinisalazar - the tests are passing now on torchapp and i've released a new version. Do you know what needs to happen now?

**Comment by vinisalazar** [comment]
@rbturnbull I updated the version number and checksum in the recipe file. Let's see if it works.

**Comment by vinisalazar** [comment]
@rbturnbull I just realised that the PyPI distribution does not package the `tests` directory, and thus pytest cannot find the test files.

See the contents of this tarball downloaded from PyPI:
```
.
├── LICENSE
├── PKG-INFO
├── README.rst
├── pyproject.toml
└── torchapp
    ├── __init__.py
    ├── apps.py
    ├── bibtex
    ├── blocks.py
    ├── callbacks
    ├── citations.py
    ├── download.py
    ├── enums.py
    ├── examples
    ├── main.py
    ├── metrics.py
    ├── params.py
    ├── testing.py
    ├── tuning
    ├── util.py
    └── vision.py

5 directories, 16 files
```

In contrast with this one using the tarball from GitHub:

```
.
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.rst
├── LICENSE
├── README.rst
├── docs
├── mkdocs.sh
├── paper.bib
├── paper.md
├── paper.sh
├── poetry.lock
├── pyproject.toml
├── tests
└── torchapp

3 directories, 10 files
```

There are two ways that I see to work around this:

1. Use the GitHub tarball in this recipe's source section (easier, preferred)
2. Configure `pyproject.toml` to include package data, see [here](https://stackoverflow.com/questions/69647590/specifying-package-data-in-pyproject-toml), an alternative if retrieving the source code from PyPI is a must.

Other helpful links:
- [Python packaging guide](https://stackoverflow.com/questions/69647590/specifying-package-data-in-pyproject-toml)
- [Contributing packages - conda-forge docs](https://conda-forge.org/docs/maintainer/adding_pkgs.html#copying-test-files)

**Comment by rbturnbull** [comment]
Hi @vinisalazar - that makes sense. I think it's a good idea to use Github as the source as you've done. Thanks!

**Comment by vinisalazar** [comment]
Hi @rbturnbull, tests are now correctly being detected, but a couple of them are still failing. Do you think you could have a look through the log files? [Here's the link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=755485&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1831)

Here is a summary:

```
+ pytest
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: $SRC_DIR
collected 92 items

tests/test_apps.py ............                                          [ 13%]
tests/test_enums.py .                                                    [ 14%]
tests/test_image_classifier.py .ss......ss.                              [ 27%]
tests/test_iris.py ...........F                                          [ 40%]
tests/test_logging_wandb.py ....                                         [ 44%]
tests/test_logistic.py ...........F                                      [ 57%]
tests/test_main.py ....                                                  [ 61%]
tests/test_params.py .                                                   [ 63%]
tests/test_testing.py .                                                  [ 64%]
tests/test_tuning_optuna.py ...F.                                        [ 69%]
tests/test_tuning_skopt.py ......                                        [ 76%]
tests/test_tuning_wandb.py .........                                     [ 85%]
tests/test_vision.py .ss......ss..                                       [100%]

=================================== FAILURES ===================================
______________________________ TestIris.test_cli _______________________________
______________________ TestLogisticRegressionApp.test_cli ______________________
_____________________________ test_optuna_tune_tpe _____________________________
```

Perhaps we could consider running less restrictive tests for CI purposes? And leave the full testing suite only for development/new releases.

**Comment by rbturnbull** [comment]
Thanks @vinisalazar - I'll make the tests less strict

**Comment by rbturnbull** [comment]
hi @vinisalazar - i've changed the tests now and I've issued a new release. Hopefully they should pass on the conda-forge runner now.

**Comment by vinisalazar** [comment]
@rbturnbull the build worked fine for Linux, but is failing for Win and OS X. From the log file, it is unclear why. I will keep looking into .

**Comment by vinisalazar** [comment]
Apparently the Windows build is due to an incompatible dependency:

```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {MatchSpec("pytorch[version='>=1.7,<1.14']"), MatchSpec("torchvision[version='>=0.13.0']"), MatchSpec("fastai==2.7.10=pyhd8ed1ab_0")}
```

Not sure about OS X though. The tests are interrupted halfway without any of them having failed. Could be lack of memory in the CI worker or something. Are the tests computing-intensive?

**Comment by rbturnbull** [comment]
Thanks @vinisalazar - I'm not sure about the failure on the tests on Mac but I just fixed an issue on the Mac a few days ago where the MPS backend didn't like float64s. I'll have a look at the windows issue now.

**Comment by vinisalazar** [comment]
@conda-forge/help-python could anyone please have a look at this error?

[Here's the line before the error in the logs.](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=761501&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2125)

Thanks in advance!

**Comment by rbturnbull** [comment]
Hi @vinisalazar - I'm not sure about the Windows dependency resolution error. It looks like it is trying fastai 2.7.10 which requires pytorch <1.14. Later versions of fastai (which we are compatible with) can work with later versions of pytorch. Should we make the fastai conda dependency to be 2.7.12? Should I change that in my pyproject.toml or should that just be in the conda receipe? I'd prefer not to restrict the version of fastai in the python package unnecessarily. Do you have any ideas?

**Comment by vinisalazar** [comment]
I'll try removing the dependency pin on fastai for now.

**Comment by rbturnbull** [comment]
Hi @vinisalazar - it looks like it is still trying to get fastai 2.7.10. Should we pin it to fastai >=2.7.12 in the conda recipe?

**Comment by vinisalazar** [comment]
@rbturnbull by pinning that version of fastai, the environment failed to solve, even for Linux.

Are there any particular dependencies that MUST have their version pinned? I'm thinking we should pin those, and remove version numbers for all dependencies.

**Pull request closed without merging**
