### PR TITLE
Added libflac recipe

### PR DESCRIPTION
**Pull request by dschreij**
Continuation of https://github.com/conda-forge/staged-recipes/pull/2026 which needed a reboot.

### CODE REVIEW

**Comment by dschreij** [comment]
@jakirkham `make check` tests all pass locally, but on CircleCI one doesn't with the message 

~~~
++++++ testing level 1 interface
simple iterator on read-only file
generating FLAC file for test
	testing 'metadata.flac'... 0... 1... 2... content... PASSED
is writable = 1
ERROR: iterator claims file is writable when tester thinks it should not be; are you running as root?

ERROR during test_libFLAC
make[1]: *** [check] Error 1
make[1]: Leaving directory `/staged-recipes/build_artefacts/work/flac-1.3.1/test'
make: *** [check-recursive] Error 1
Command failed: /bin/bash -x -e /staged-recipes/build_artefacts/work/flac-1.3.1/conda_build.sh
~~~

and I think there is no way I can fix this as it seems inherent to CircleCI. How do you advise to proceed?

**Comment by jakirkham** [comment]
Yeah the failure makes sense. We are planning to stop running as `root` on Linux. My recommendation would be to patch out the failing test.

**Comment by dschreij** [comment]
Hmm, sadly simply commenting out the test with a patch doesn't do the trick:
~~~
++++++ testing level 1 interface
simple iterator on read-only file
generating FLAC file for test
	testing 'metadata.flac'... 0... 1... 2... content... ./test_libFLAC.sh: line 27:  8089 Segmentation fault      (core dumped) test_libFLAC${EXE} $*
ERROR during test_libFLAC
make[1]: *** [check] Error 1
make[1]: Leaving directory `/staged-recipes/build_artefacts/work/flac-1.3.1/test'
make: *** [check-recursive] Error 1
Command failed: /bin/bash -x -e /staged-recipes/build_artefacts/work/flac-1.3.1/conda_build.sh
~~~

I am disabling `make check` for CircleCI/Linux builds for now, and hopefully they can be run in the future.

**Comment by jakirkham** [comment]
That segmentation fault is a little troubling. Are there any open issues or bug reports that note similar problems and any suggested workarounds/solutions?

**Comment by dschreij** [comment]
@jakirkham no because I think this segmentation fault is a direct result of the patch I created to comment out the failing test that checked for writing/root privileges (per your suggestion). I doubt that this is an error which occurs with the original code. My knowledge of C is limited, but as far as I know I didn't do anything "illegal" by commenting out some code in that it causes a segfault, so I have no idea where to look for a solution. 

Would you be against omitting `make check` on CircleCI until it doesn't run the build scripts as root anymore (as I have done in the latest commit which builds correctly)?

**Comment by jakirkham** [comment]
I don't think you did anything illegal with the patch, @dschreij . However, I do think it is possible that we uncovered some other issue. TBH it is not a blocker just trying to help figure it out.

**Comment by jakirkham** [comment]
Thanks @dschreij .

**Comment by jakirkham** [comment]
Out of my own interest, what are you using all of these audio libraries for?

**Comment by dschreij** [comment]
Thanks @jakirkham. These audio libraries are (optional) dependencies of sdl2_mixer, which uses them to decode (and possibly encode) various audio formats. I want to make sure sdl2_mixer can handle as many types of audioformats as possible, so I'm trying to make all audio libraries it can work with are available and compile sdl2_mixer against them.
My ultimate purpose is to integrate SDL2 in the [OpenSesame](http://osdoc.cogsci.nl) experiment builder, which is used in social sciences (mainly cognitive psychology) to build graphical experiments (it is also available on conda as python-opensesame on the cogsci channel).
Currently OpenSesame uses Pygame (based on SDL1) to draw stimuli to the screen or play sound, but this project is not very well maintained and aging quite badly, so I hope to make the push to SDL2 sometime soon. To do so I need to make sure all SDL2 modules and their dependencies are available on conda, since I think you've got the best Python package manager around. Doing so makes it easy to install and set up the environment required for OpenSesame to run on all platforms. Especially getting SDL2 to work on Windows can be quite a pain, so I hope I have this covered by making sure all C packages are also available on conda.
And I think SDL2 will be a real asset to the conda ecosystem (it's a very popular game creation library that also forms the backbone of Kivy for instance), so I'm trying to build each sdl2 as as well and complete as I can.

**Pull request merged**
