### PR TITLE
Adding dadi

### PR DESCRIPTION
**Pull request by RyanGutenkunst**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by RyanGutenkunst** [comment]
@conda-forge/bioconda-recipes : This package is already in bioconda. But I just had a user who was surprised that bioconda does not include Windows versions of packages. The easiest solution seemed to be moving to conda-forge.

**Comment by RyanGutenkunst** [comment]
@conda-forge-admin, please ping team
My Linux build is failing due to an internal logging error within conda-build.

The error is
File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 400, in mk_relative_osx
log.warn("Found Mach-O file but patching is only supported on macOS, skipping: %s", path)
NameError: name 'log' is not defined

The fact that a warning is (trying) to be emitted may point to underlying issues with my build script, but it seems like bad logging in conda_build is the immediate cause of the error.

What's the best way to address this?

**Comment by nehaljwani** [comment]
The bug has been fixed an released in conda-build-v3.19.3
xref: https://github.com/conda/conda-build/pull/3925

However, one should not be distributing pre-compiled files in a source dist. So you have two choices:
- Cut a new release of dadi and upload an sdist which does not contain the pre compiled C extensions, OR:
- Use the following patch:
```diff
diff --git a/recipes/dadi/meta.yaml b/recipes/dadi/meta.yaml
index cbfd8edf8..b2ea1d0c3 100644
--- a/recipes/dadi/meta.yaml
+++ b/recipes/dadi/meta.yaml
@@ -11,7 +11,10 @@ source:
 
 build:
   number: 0
-  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --install-option="--cython" '
+  script:
+    # Remove pre-compiled C extensions from the sdist
+    - rm -f $SRC_DIR/*/*/*-darwin.so  # [unix]
+    - '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --install-option="--cython" '
 
 requirements:
   build:
```

**Comment by RyanGutenkunst** [comment]
Thanks @nehaljwani . I'm not sure why setuptools was including those files, but I'll add them to the exclude list and update on PyPI.

**Pull request merged**
