### PR TITLE
add spatialdata-plot recipe

### PR DESCRIPTION
**Pull request by LucaMarconato**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by LucaMarconato** [comment]
@timtreis @Sonjia-Stockhaus @kevinyamauchi @giovp @melonora I am adding you as co-maintainers of the conda recipe for spatialdata-plot. If agree please state this as a comment in this thread.

The maintainer roles, [as explained here](https://conda-forge.org/docs/maintainer/adding_pkgs/#maintainer-role) are:
- Keep the feedstock updated by merging eventual maintenance [PR](https://conda-forge.org/docs/glossary/#pr)s from conda-forge's bots.
- Keep the feedstock on par with new releases of the source package by:
- Bumping the version number and checksum.
- Making sure that the feedstock's requirements stay accurate.
- Make sure the test requirements match those of the updated package.
- Answer eventual questions about the package on the feedstock issue tracker.

**Comment by kevinyamauchi** [comment]
I agree to be a maintainer on this recipe

**Comment by melonora** [comment]
I agree to be a maintainer on this recipe

**Comment by giovp** [comment]
I agree to be a maintainer of this recipe.

**Comment by timtreis** [comment]
I agree to be a maintainer on this recipe

**Comment by Sonja-Stockhaus** [comment]
I agree to be a maintainer on this recipe

**Comment by LucaMarconato** [comment]
Ready for review 😊

**Comment by LucaMarconato** [comment]
@conda-forge/help-python, ready for review!

**Review by xhochy — APPROVED** [review]

**Pull request merged**
