### PR TITLE
create geetools recipe

### PR DESCRIPTION
**Pull request by 12rambau**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by 12rambau** [comment]
@fitoprincipe can you confirm you agree to be listed in the package maintainers ?

**Comment by fitoprincipe** [comment]
sorry for the late reply. 
Answering https://github.com/conda-forge/staged-recipes/pull/25220#issuecomment-1925944656, yes I do. Thanks

**Comment by 12rambau** [comment]
@conda-forge/help-python ready for review

**Comment by ocefpaf** [comment]
Failing with:

```
import: 'geetools'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/geetools_1707085594737/test_tmp/run_test.py", line 2, in <module>
    import geetools
  File "/home/conda/staged-recipes/build_artifacts/geetools_1707085594737/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.12/site-packages/geetools/__init__.py", line 31, in <module>
    from .DateRange import DateRangeAccessor
  File "/home/conda/staged-recipes/build_artifacts/geetools_1707085594737/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.12/site-packages/geetools/DateRange/__init__.py", line 10, in <module>
    @register_class_accessor(ee.DateRange, "geetools")
                             ^^^^^^^^^^^^
AttributeError: module 'ee' has no attribute 'DateRange'
WARNING: Tests failed for geetools-1.0.0-pyhd8ed1ab_0.conda - moving package to /home/conda/staged-recipes/build_artifacts/broken
TESTS FAILED: geetools-1.0.0-pyhd8ed1ab_0.conda
```

**Comment by 12rambau** [comment]
arf I solved this one in the latest release. Let me update the version in the recipe

**Comment by 12rambau** [comment]
@ocefpaf sorry for the noise I needed an extra release step. frm pypi side.

**Pull request merged**
