### PR TITLE
Added Jupyter Kernel Gateway recipe

### PR DESCRIPTION
**Pull request by parente**

### CODE REVIEW

**Comment by parente** [comment]
Python 3.4 import test is failing on circle and travis. I'll try building all to see if I can replicate locally.

**Comment by parente** [comment]
I manually verified that conda-build and conda build-all fail on the *second* python version package built. For instance:

```
# in a clean root environment
conda build --python3.4 .   # works
conda build --python3.5 .   # fails

# in another clean root environment
conda build --python2.7 .   # works
conda build --python3.4 .   # fails
```

Is there some trick to building packages that are also configured for wheels? The first package that does get built has no version on it (jupyter_kernel_gateway-1.1.1-0.tar.bz2) which seems out of the ordinary.

**Comment by parente** [comment]
On travis and circle, the following gets logged:

```
Computed that there are 3 distributions from the 1 recipes:
Resolved dependencies, will be built in the following order: 
	jupyter_kernel_gateway-1.1.1-0 (will be built: True)
	jupyter_kernel_gateway-1.1.1-0 (will be built: True)
	jupyter_kernel_gateway-1.1.1-0 (will be built: True)
```

For other packages, I see the Python version # in the filename. Not sure why it's missing here. I'm pretty sure it leads to the build failures. On appveyor, where there is no failure, the python version-specific packages appear to be built in a separate, clean environment.

**Comment by jakirkham** [comment]
Thanks @parente.

**Pull request merged**
