### PR TITLE
Create meta.yaml

### PR DESCRIPTION
**Pull request by ianozsvald**
First attempt at adding recipe based on work by @ps-git (thanks!)

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @ianozsvald! Seems like this already exists: https://github.com/conda-forge/ipython_memory_usage-feedstock Feel free to add yourself as a maintainer there

**Comment by ianozsvald** [comment]
> Thanks @ianozsvald! Seems like this already exists: https://github.com/conda-forge/ipython_memory_usage-feedstock Feel free to add yourself as a maintainer there

Hey there. How do I add myself as a maintainer on that project? Fork it? Add myself under "extra; recipe-maintainers" of the feedstock?

BTW - hello :-)

**Comment by scopatz** [comment]
> Hey there. How do I add myself as a maintainer on that project? Fork it? Add myself under "extra; recipe-maintainers" of the feedstock?
 
Yes, exactly! We also have a ton of docs over at https://conda-forge.org/docs/

And hello!  It is good to "see" you again!

**Comment by msarahan** [comment]
Closing as housekeeping.  @ianozsvald if you need any further help, please join us at https://gitter.im/conda-forge/conda-forge.github.io

**Pull request closed without merging**
