### PR TITLE
PR: Add flaky recipe

### PR DESCRIPTION
**Pull request by goanpeca**
@ccordoba12, @rlaverde

### CODE REVIEW

**Comment by goanpeca** [comment]
@jakirkham all appveyor builds failed with :-(

screen shot 2017-03-21 at 7 57 42 pm

**Comment by ccordoba12** [comment]
:+1:

**Comment by jakirkham** [comment]
Yep, this is a known issue ( https://github.com/appveyor/ci/issues/1426 ). Have already proposed fixes in PRs ( https://github.com/conda-forge/conda-smithy/pull/489 ) and ( https://github.com/conda-forge/staged-recipes/pull/2648 ). Please take a look.

**Comment by goanpeca** [comment]
@jakirkham I saw the PR got merged, has the new version been released :-)

**Comment by mariusvniekerk** [comment]
@goanpeca restarted your windows build

**Comment by goanpeca** [comment]
@mariusvniekerk thanks, but did not we need to update or rerender with the latest version of smithy?

**Comment by jakirkham** [comment]
No need to re-render at staged-recipes. Literally just restarting the CIs should be sufficient (thanks @mariusvniekerk). Though feedstocks will need re-rendering, which can be done with 2.2.1 that was released earlier today.

**Comment by goanpeca** [comment]
@jakirkham awesome work :-) thanks!

**Comment by goanpeca** [comment]
@jakirkham merge :-) ?

**Comment by jakirkham** [comment]
Yep. 👍 Thanks @goanpeca.

**Pull request merged**
