### PR TITLE
Add gtsam - take 3

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Fix #14339 #15578

### CODE REVIEW

**Comment by wolfv** [comment]
Cool!

**Comment by Tobias-Fischer** [comment]
I am not sure what's going on with boost on Windows @wolfv - I'm suggesting to skip Windows for now and open an issue in the feedstock, unless you want to play around with the Win build?

**Comment by Tobias-Fischer** [comment]
It's ready to go :)

**Comment by Tobias-Fischer** [comment]
I'm giving up on osx, no idea why it still finds the wrong python .. skip as well? Maybe it'll magically work in the feedstock?

**Comment by wolfv** [comment]
in the last build cmake reports python 3.8 as found?

```
-- Python toolbox flags                                      
--  Build Python module with pybind                  : Enabled
--  Python version                                   : 3.8
-- ===============================================================
```

**Comment by Tobias-Fischer** [comment]
Ah thank goodness. I thought I still saw the system python somewhere. This is ready for merge :)

**Comment by wolfv** [comment]
awesome!

**Comment by ameysutavani** [comment]
Thanks for following up on this @Tobias-Fischer and @wolfv . I had forgotten about this. :P

**Pull request merged**
