### PR TITLE
Add ffsend

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/staged-recipes, ready for review

**Comment by chrisburr** [comment]
I was just looking at building those, `cargo-license` (#11844) fails to find any of the licence files and `cargo-license-hound` is proving a little tricker to build.

**Comment by jakirkham** [comment]
Are you still working on this Chris? 🙂

**Comment by chrisburr** [comment]
Now that [Firefox Send](https://support.mozilla.org/en-US/kb/what-happened-firefox-send) has been shutdown probably not... 😄 

I'd like to deal with the rust licensing stuff still but it's unlikely to be a priority for me in the near future

**Pull request closed without merging**
