### PR TITLE
Add napari-process-points-and-surfaces recipe

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- ~[ ] If static libraries are linked in, the license of the static library is packaged.~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by goanpeca** [comment]
Still working on this :)

**Comment by haesleinhuepf** [comment]
Hi @goanpeca ,

it's been a while :-) We eventually managed to update napari-process-points-and-surfaces so that since version [0.4.0](https://github.com/haesleinhuepf/napari-process-points-and-surfaces/releases/tag/0.4.0) we don't need open3d anymore. This should pave the path to make it available on conda-forge. 

Let me know if anything else is necessary to pull this through.

Big thanks again!

Best,
Robert

**Comment by Mrdonnie1** [comment]
congrats!

Donnie Lee Jr.

**Comment by goanpeca** [comment]
Hi @haesleinhuepf, will take a look at this during the week :) 

Cheers!

**Comment by goanpeca** [comment]
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

@jaimergp, @haesleinhuepf do you agree with being added as maintainers?

**Comment by haesleinhuepf** [comment]
> @jaimergp, @haesleinhuepf do you agree with being added as maintainers?

Yes, I'll happily maintain this. Thanks for efforts!

**Comment by jaimergp** [comment]
Yes.

**Comment by goanpeca** [comment]
This one is ready for review @conda-forge/staged-recipes :)

**Comment by dopplershift** [comment]
It's unclear why this is failing on Windows.

**Comment by goanpeca** [comment]
Indeed, not sure I understand either :-\


WARNING: Skipping C:\bld\napari-process-points-and-surfaces_1680054430942\_test_env\Lib\site-packages\vtk-9.2.6.egg-info due to invalid metadata entry 'name'
vedo 2023.4.4 requires vtk, which is not installed.

**Comment by haesleinhuepf** [comment]
How about adding `vtk` to requirements [as done in vedo-feedstock](https://github.com/conda-forge/vedo-feedstock/blob/main/recipe/meta.yaml#L23)? If you give me write-access @goanpeca , I'll try myself.

**Comment by goanpeca** [comment]
Hi @haesleinhuepf , I already tried that in this commit, which still failed with the same error

https://github.com/conda-forge/staged-recipes/pull/19248/commits/b7f3492a16fb546a5bba11dc29198bb6ecdc6d27

Not sure what the issue is

**Comment by goanpeca** [comment]
This one is ready for review @conda-forge/staged-recipes :)

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
