### PR TITLE
Adding recipe for mkl_fft package

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
@dgursoy

### CODE REVIEW

**Comment by msarahan** [comment]
Looks like there are some roundoff error issues on windows with x86.  Are those worth addressing?  If not, please skip that test somehow.

**Comment by oleksandr-pavlyk** [comment]
Thank you @msarahan, I will address this in a moment.

**Comment by msarahan** [comment]
Thanks @oleksandr-pavlyk - merging.

**Comment by jakirkham** [comment]
Also you should get an invitation to join conda-forge. Can just navigate to the GitHub org page and the invite should show up at the top. May be in your email as well.

**Pull request merged**
