### PR TITLE
Add r-svars (with dep r-steadyica)

### PR DESCRIPTION
**Pull request by leej3**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by leej3** [comment]
@conda-forge/help-r

**Review by mfansler — APPROVED** [review]

**Comment by dbast** [comment]
Merging requires retriggering the builds in the created feedstocks in the right order as they depend on each other.

**Comment by leej3** [comment]
Shall I just force push an amended commit? Though I don't understand what you mean by the above... r-svars depends on r-steadyica... this situation is resolved automatically by [the build infrastrucure](https://github.com/conda-forge/staged-recipes/blob/main/.ci_support/build_all.py#L160)... is there some other dependency that I am not spotting that is causing an issue?

**Comment by dbast** [comment]
Nothing to do right now. Only after the merge and feedstock creation. Will have a look later

**Pull request merged**
