### PR TITLE
WIP*2: Add bzip2

### PR DESCRIPTION
**Pull request by jakirkham**
Very much WIP at this point. This should build bzip2 when we are done.

### CODE REVIEW

**Comment by jjhelmus** [comment]
I've had luck compiling bzip2 with the following for the `build.sh` script:

```
#!/bin/bash

make -f Makefile-libbz2_so
make
make install PREFIX=$PREFIX

# optionally remove the bin and man directories since they are not needed
rm -rf $PREFIX/bin
rm -rf $PREFIX/man
```

Feel free to add me as a maintainer.

**Comment by pelson** [comment]
Might also be interested in my raspberrypi recipe: https://github.com/pelson/raspberrypi-conda-recipes/tree/master/recipes/bzip2

**Comment by jakirkham** [comment]
Yeah, sorry guys, this has mainly been a lack of time more than anything else. When that changes, I'll give it another go. Alternatively, if one of you feels a real drive to get this done, feel free to take over.

**Comment by jlanga** [comment]
Hi @jakirkham, @pelson and @jjhelmus 

Mind if I PR? The recipe from `defaults` doesn't generate `libbzip2.so*` and I need them for other recipes.

https://github.com/jlanga/staged-recipes/tree/bzip2/recipes/bzip2

**Comment by msarahan** [comment]
@jlanga PRs are always welcome here.  Please ping anyone if you need help or review.

**Comment by jakirkham** [comment]
Go nuts. 😄 Will close this out.

**Comment by jakirkham** [comment]
Replaced by PR ( https://github.com/conda-forge/staged-recipes/pull/1977 ).

**Pull request closed without merging**
