### PR TITLE
Add urdf-parser-py and torchkin

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/help-python - this is ready for review. It adds another required package for https://github.com/conda-forge/theseus-ai-feedstock/pull/7 (@ocefpaf already kindly merged #23199).

/cc @traversaro - this adds urdf-parser-py, which is also packaged by ROS.

**Comment by Tobias-Fischer** [comment]
Many thanks, that was quick @ocefpaf :)

**Comment by traversaro** [comment]
The `urdf_parser_py` Python module was already packaged as part of the `urdfdom-py` Python package in https://github.com/conda-forge/staged-recipes/pull/21870 (the naming was choosen for consistency with ROS).

**Comment by Tobias-Fischer** [comment]
Ah, damn .. apologies for that! I should have dug deeper :(

I requested to archive the urdf-parser-py feedstock here: https://github.com/conda-forge/admin-requests/pull/744
At least then we will have some visibility for the future.

**Comment by traversaro** [comment]
> Ah, damn .. apologies for that! I should have dug deeper :(

No problem, the whole different naming between the package and the module is quite confusing. Furthermore, the package on PyPI is stuck to quite an old version, but that is another story.

**Pull request merged**
