### PR TITLE
add spdlib recipe

### PR DESCRIPTION
**Pull request by gillins**
http://spdlib.org

@danclewley @petebunting this is the recipe I've been working on. Let me know if you see any problems. A couple of things:

- are you going to upload a tarball to bitbucket? This recipe currently uses the hg tag. 
- I've added a patch as `boost/python/numeric.hpp` as been renamed to `boost/python/numpy.hpp` in recent `boost` versions. Not sure if you want this applied to `spdlib` trunk.

@danclewley @petebunting @armstonj I assume you are happy to be maintainers of this recipe?

### CODE REVIEW

**Comment by gillins** [comment]
Turns out mercurial is [not installed](https://travis-ci.org/conda-forge/staged-recipes/builds/352663486#L303) on the CI's so tarball will be the way to go.

Not sure why the Windows build won't start though...

**Comment by danclewley** [comment]
I've uploaded a tarball. Details are:
```
  url: https://bitbucket.org/petebunting/spdlib/downloads/spdlib-{{ version }}.tar.gz
  sha256: ded350c5eedb7b3b92a84a1e2d6dfa4c6f9ecb09bd83f0fcfb7fe17c1595b9c7
```

**Comment by gillins** [comment]
Thanks Dan!

I think this one is good to go.

**Comment by danclewley** [comment]
@gillins - are you waiting on anything from me on this? I’m not quite sure on the procedure for stage recipes.

**Comment by gillins** [comment]
No - I think we are just waiting for an admin to merge it - @ocefpaf ? :smiley:

**Comment by ocefpaf** [comment]
Thanks for the ping :-)

**Comment by gillins** [comment]
Thanks @ocefpaf and @danclewley !

**Pull request merged**
