### PR TITLE
Add gw build spec

### PR DESCRIPTION
**Pull request by kcleal**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dopplershift** [comment]
Looks like the last commit here deleted the recipe?

**Comment by alperozoner** [comment]
Staged-recipes test succeeded as seen here from Build #20221031.50.

**Comment by dopplershift** [comment]
The summary of this PR says "0 files changed". Tests succeed because there's nothing to build. Note the failed linter saying:

> I was trying to look for recipes to lint for you, but couldn't find any.

**Comment by kcleal** [comment]
Hi @conda-forge-bot @dopplershift  How do I add a channel to meta.yaml - I would like to add bioconda as a channel, is this possible?

**Comment by dopplershift** [comment]
We can't add a package to conda-forge that depends on bioconda. You either need to instead add this package to bioconda (if that makes sense), or we need to migrate any needed dependencies from bioconda to conda-forge.

**Pull request closed without merging**
