### PR TITLE
Add recipe for pymca 5.4.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Any thoughts on how to fix this `numpy` version issue?

**Comment by CJ-Wright** [comment]
That PR is pending the compiler rebuild I think.

**Comment by tschoonj** [comment]
In the meantime, would it be ok if I just pin numpy to 1.10 for `host` and 1.10+ for `run`?

**Comment by tschoonj** [comment]
This one is ready to go now...

**Comment by marcelotrevisani** [comment]
Sorry for the delay, sometimes that happens

LGTM, thanks for adding this to ``conda-forge`` ! :tada:

**Comment by tschoonj** [comment]
I think something may have gone wrong while creating the repo: [it's there](https://github.com/conda-forge/pymca-feedstock) but without a single commit...

Looks suspicious to me :suspect:

**Pull request merged**
