### PR TITLE
Add bioconductor-survcomp.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by bgruening** [comment]
@cbrueffer this is the wrong repo :) I think this should go to bioconda.

**Comment by cbrueffer** [comment]
Well, there's nothing inherently biological to it, that's why I submitted it here. The other survival-related packages are also in conda-forge. Happy to commit it to bioconda though :-)

**Comment by bgruening** [comment]
Mh, interesting. I though we agreed that *bio*conductor, means more or less its bio-enough. Your call :)

**Comment by cbrueffer** [comment]
True; I just (seemed to?) remember a comment on another general bioconductor package submission in bioconda (not from me) with a comment pointing towards conda-forge. I may be misremembering :-) In any case, I'm happy to keep bioconductor packages in bioconda.

**Pull request closed without merging**
