### PR TITLE
new r-* packages

### PR DESCRIPTION
**Pull request by bgruening**
related to bioconda/bioconda-recipes#5582

cc @daler and @jdblischak

### CODE REVIEW

**Comment by jdblischak** [comment]
The Appveyor [build](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.16631/job/68eohg8a567q9q29#L6533) failed again because of fftw:

```
RuntimeError: Can't build {'config': <conda_build.config.Config object at 0x0000008ABF94F550>, 'undefined_jinja_vars': [], 'requirements_path': 'C:\\projects\\staged-recipes\\recipes\\r-fftwtools\\requirements.txt', 'path': 'C:\\projects\\staged-recipes\\recipes\\r-fftwtools', 'meta_path': 'C:\\projects\\staged-recipes\\recipes\\r-fftwtools\\meta.yaml', 'meta': {'build': {'rpaths': ['lib/R/lib/', 'lib/'], 'number': '0'}, 'extra': {'final': True, 'recipe-maintainers': ['johanneskoester', 'bgruening', 'daler', 'jdblischak']}, 'about': {'summary': "Provides a wrapper for several 'FFTW' functions. This package provides access to the two-dimensional 'FFT', the multivariate 'FFT', and the one-dimensional real to complex 'FFT' using the 'FFTW3' library. The package includes the functions fftw() and mvfftw() which are designed to mimic the functionality of the R functions fft() and mvfft(). The 'FFT' functions have a parameter that allows them to not return the redundant complex conjugate when the input is real data. ", 'license': 'GPL (>= 2)', 'home': 'https://github.com/krahim/fftwtools', 'license_family': 'GPL3'}, 'test': {'commands': ['"%R%" -e "library(\'fftwtools\')"']}, 'package': {'version': '0.9_8', 'name': 'r-fftwtools'}, 'source': {'url': ['https://cran.r-project.org/src/contrib/fftwtools_0.9-8.tar.gz', 'https://cran.r-project.org/src/contrib/Archive/fftwtools/fftwtools_0.9-8.tar.gz'], 'fn': 'fftwtools_0.9-8.tar.gz', 'sha256': '4641c8cd70938c2a8bde0b6da6cf7f83e96175ef52f1ca42ec3920a1dabf1bdb'}, 'requirements': {'run': ['r-base', 'fftw 3.3.6'], 'build': ['r-base', 'fftw 3.3.6', 'posix', 'm2w64-toolchain']}}} due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - fftw 3.3.6
```

fftw 3.3.6 is available on the conda-forge Anaconda Cloud channel for win-64.

https://anaconda.org/conda-forge/fftw/files?version=3.3.6

**Comment by bgruening** [comment]
mh, restarted it ... thanks for looking into it.

**Comment by jdblischak** [comment]
Still getting the same [error](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.16677/job/dap2o5dbje7m12hq#L6474) as before.

**Comment by bgruening** [comment]
Thanks @ocefpaf!

**Pull request merged**
