### PR TITLE
Adding dartsim

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Fix https://github.com/conda-forge/staged-recipes/issues/12862. 

@wolfv @Tobias-Fischer feel free to reply if you like to be added as maintainers, thanks!

### CODE REVIEW

**Comment by wolfv** [comment]
Sweet! I’d be happy to be added!

**Comment by traversaro** [comment]
> 
> 
> Sweet! I’d be happy to be added!

Done!

**Comment by traversaro** [comment]
The `win_64` build is working correctly on a clean environment locally, so I suspect there are some difference due to the specific version of VS2017 used. Do you have any suggestions on how to debug the CI failure? There is any simple process to download the `C:/Miniconda/conda-bld/dartsim_1602369457250/work/build/CMakeFiles/CMakeOutput.log` and  `C:/Miniconda/conda-bld/dartsim_1602369457250/work/build/CMakeFiles/CMakeError.log` ?

**Comment by traversaro** [comment]
In https://github.com/conda-forge/staged-recipes/pull/12863/commits/a4cb25c3f1638866084e0c72429d4c8198cd697a I tried a shot in the dark by compiling with the (MSVC ABI compatible) clang-cl compiler.

**Comment by traversaro** [comment]
> 
> 
> In [a4cb25c](https://github.com/conda-forge/staged-recipes/commit/a4cb25c3f1638866084e0c72429d4c8198cd697a) I tried a shot in the dark by compiling with the (MSVC ABI compatible) clang-cl compiler.

This was failing even locally with the error: 
~~~
-- Build files have been written to: C:/Users/STraversaro/Miniconda3/conda-bld/dartsim_1602411808657/work/build

Microsoft (R) Program Maintenance Utility Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target dart-external-odelcpsolver
[  1%] Building CXX object dart/external/odelcpsolver/CMakeFiles/dart-external-odelcpsolver.dir/error.cpp.obj
clang-cl.exe: error: no such file or directory: '/permissive-'
NMAKE : fatal error U1077: 'C:\Users\STraversaro\Miniconda3\Library\bin\clang-cl.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
~~~

**Comment by traversaro** [comment]
I was able to display `CMakeOutput.log` and `CMakeError.log`, but I could not find anything different w.r.t. to the equivalent version that I had locally. Anyhow, I noticed that a lot of `check_cxx_source_compiles` tests were actually failing even if they should not, and then I realized that dart is hardcoding the MSVC names for most of its dependencies (see https://github.com/dartsim/dart/blob/e18046107679ff71a0da75dbbf2982b5650ff490/cmake/Findassimp.cmake#L29). So, even if that is not the cause of the failure, is better to fix that. 
 
> > In [a4cb25c](https://github.com/conda-forge/staged-recipes/commit/a4cb25c3f1638866084e0c72429d4c8198cd697a) I tried a shot in the dark by compiling with the (MSVC ABI compatible) clang-cl compiler.
> 
> This was failing even locally with the error:

This was just before you did not added `clang` to the build dependencies, so an old clang 5.0 was used.

**Comment by wolfv** [comment]
I jsut tried locally with MSVC and the issues appears to be in the `urdf_sensor/sensor.h` header file. `far` (and `near`?) appear to be reserved words in MSVC? 

I added `#undef far; #undef near` to the sensor.h header, and then it works.

Next problem is missing freeglut on windows. I am looking into that rn.

**Comment by wolfv** [comment]
@traversaro how should we handle this? Patch urdfdom_headers?

**Comment by wolfv** [comment]
adding `- freeglut  # [win]` to host and run seems to make it work.

**Comment by wolfv** [comment]
https://github.com/cython/cython/issues/1959 this is the issue we're hitting on urdfdom_headers. Going to send a patch to there as well.

**Comment by traversaro** [comment]
> @traversaro how should we handle this? Patch urdfdom_headers?

For the windows.h nasty macro collision, typically the best solution is to avoid as much as possible the inclusion of `windows.h`, and when it is included in a compilation unit make sure that the compilation unit is as  small as possible and `windows.h` is included as the last include. In this case, I am not sure in which compilation unit you had the near/far problem. However,  until it creates problem the patch in https://github.com/conda-forge/urdfdom_headers-feedstock/pull/7 is ok for me.

**Comment by traversaro** [comment]
Note that even if the build works correctly on `win_64`, we noticed some problems that basically prevent to link the resulting static library in any executable, see https://github.com/ignitionrobotics/ign-physics/issues/87#issuecomment-707379052 . I fixed them in https://github.com/dartsim/dart/pull/1510, but applying that patch exposes an assimp issue, as the build fails with:
~~~
[ 53%] Linking CXX executable test_Distance.exe
LINK: command "C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\test_Distance.dir\objects1.rsp /out:test_Distance.exe /implib:test_Distance.lib /pdb:C:\Users\STraversaro\Miniconda3\envs\dart-deps\src\dart\build-ninja\unittests\comprehensive\test_Distance.pdb /version:0.0 /machine:x64 /LTCG /INCREMENTAL:NO /subsystem:console ..\..\lib\dart.lib ..\..\lib\gtest.lib ..\gtest_main.lib ..\..\lib\dart-collision-bullet.lib ..\..\lib\gtest.lib ..\..\lib\dart.lib ..\..\dart\external\odelcpsolver\dart-external-odelcpsolver.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\fcl.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\ccd.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\bin\assimp-vc141-mt.dll C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\boost_system.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\boost_filesystem.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\octomap.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\octomath.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\BulletDynamics.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\BulletCollision.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\LinearMath.lib C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\lib\BulletSoftBody.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:test_Distance.exe.manifest" failed (exit code 1107) with the following output:
C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\bin\assimp-vc141-mt.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x300
NMAKE : fatal error U1077: 'C:\Users\STraversaro\Miniconda3\envs\dart-deps\Library\bin\cmake.exe' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
~~~

At this point, I wonder if it makes more sense to just merge this with `skip: true  # [win]` and then work on Windows support in the feedstock.

**Comment by wolfv** [comment]
yeah I am not sure why it locally works for me. It seems to me that the compiler checks are buggy. Next thing I'd try is to patch the dartsim CMake to remove the compiler checks and see if that fixes everything :)

**Comment by wolfv** [comment]
yeah but why not merge this as is, and then we can do stuff over on the feedstock. That might be easier :)
We can also try to motivate some core-dartsim people by opening an issue over there.

**Comment by wolfv** [comment]
@traversaro do you want to push with skip: true  # [win]?

**Comment by wolfv** [comment]
and maybe squash the commits :)

**Comment by traversaro** [comment]
> 
> 
> @traversaro do you want to push with skip: true # [win]?



> 
> 
> and maybe squash the commits :)

Ok, do you prefer that I squash them myself or that you merge with squash at GitHub level? Both are fine for me.

**Comment by wolfv** [comment]
thanks, awesome! Squashing isn't enabled for this repo but I think it's fine.

**Comment by traversaro** [comment]
> 
> 
> thanks, awesome! Squashing isn't enabled for this repo but I think it's fine.

Thanks, good to know about the squashing.

**Pull request merged**
