### PR TITLE
Embree

### PR DESCRIPTION
**Pull request by scopatz**
This is a simple recipe for the embree package that we had lying around. Maybe @MatthewTurk @atmyers or @Xarthisius are willing to be maintainers?

### CODE REVIEW

**Comment by scopatz** [comment]
Looks like this is passing, for what it is worth.

**Comment by Xarthisius** [comment]
I'm ok with co-maintaining. BTW, is this PR is going to be followed by `pyembree`? :)  It'd be nice to get latest version too. There are an order of magnitude speed-ups in some cases according to upstream's changelog.

**Comment by scopatz** [comment]
@Xarthisius yes and yes.  I was hoping someone else would do the version bump once this is in a feedstock.  I wanted to build the recipe with something that I know works.  And yeah, once this has a feedstock, I was going to propose adding a version tag to pyembree and then moving the recipe here.

Thanks, I'll add you to the maintainers list!

**Comment by scopatz** [comment]
ping on this recipe!

**Pull request merged**
