### PR TITLE
Add healpy

### PR DESCRIPTION
**Pull request by mwcraig**
Questions: Should I ask the package authors if they would like to be added as maintainers?

### CODE REVIEW

**Comment by mwcraig** [comment]
Another question: why is the full matrix of appveyor runs started when Windows builds are skipped in `meta.yaml`? I understand that meta doesn't necessarily get used until conda build runs, but would it be worth skipping those builds if a recipe indicates Windows should be skipped?

**Comment by ocefpaf** [comment]
That will happen in the feedstrock. In staged-recipes we recommend people to add [skip appveyor] to the commit message.

**Comment by mwcraig** [comment]
ok, thanks!

**Comment by ocefpaf** [comment]
Thanks @mwcraig!

**Comment by mwcraig** [comment]
My pleasure, hopefully fixes an issue for a user running an older version of linux!

**Pull request merged**
