### PR TITLE
Add eis_toolkit

### PR DESCRIPTION
**Pull request by nialov**
Hey,

I wish to create a `conda-forge` package for `eis_toolkit` <https://github.com/GispoCoding/eis_toolkit/issues/318>.

Thanks in advance!

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by nialov** [comment]
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I wanted to let you know that I linted all conda-recipes in your PR (`recipes/eis_toolkit`) and found some lint.
> 
> Here's what I've got...
> 
> For **recipes/eis_toolkit**:
> 
>     * The following maintainers have not yet confirmed that they are willing to be listed here: nmaarnio. Please ask them to comment on this PR if they are.

@nmaarnio can you comment here in the issue to confirm addition as maintainer?

**Comment by nmaarnio** [comment]
> @nmaarnio can you comment here in the issue to confirm addition as maintainer?

Hey, yes, I confirm that I would like to be added as maintainer.

**Comment by nialov** [comment]
Hey, @conda-forge/help-python, this PR is ready for review. It adds `eis_toolkit`, a library what provides mineral prospectivity analysis tools using geospatial and machine learning methods. See <https://github.com/GispoCoding/eis_toolkit>. It currently has no *PyPI* release although that might change later. Packaging now, even though the package is still under active development, is useful to distribute it to testers more easily (`conda install eis_toolkit -c conda-forge`).

I do have a question regarding the `tensorflow`dependency install problems on Windows: Even though the tests fail here, I assume that Windows users will still be able to install the package, and most likely successfully, as they have the `anaconda` channel available on their local machines where later versions of `tensorflow` are available on Windows? The package has `noarch: python` in `meta.yaml` so it should be platform-independent.

**Comment by nialov** [comment]
Hey, @conda-forge/help-python, anyone got time to review this?

**Review by xhochy — APPROVED** [review]

**Pull request merged**
