### PR TITLE
ENH updated gfortran for OSX

### PR DESCRIPTION
**Pull request by beckermr**
@mingwandroid @msarahan 

OK. I have put a build of gfortran 8.2.0 for osx here. The exact structure of the packages is up for debate, but this is one way to do it. The build works as follows:

1. build a package containing gcc and gfortran (called gfortran_build in the recipes dir, open to changes OFC)
2. build libgfortran and gfortran from that package

The last step follows the current build of these packages from the old gcc 4.8.5 packages. If we go with this, I would simply merge the build package and push the changes to the gfortran and libgfortran packages to those repos. I copied pasted them here and put in the changes so that I could test it all out. 

All of this works locally on my mac using a toolchain build (on mojave). The CI services will test the new anaconda 5 clang compilers for osx

Some issues:

1. Building gcc/gfortran requires 5 dependencies (isl, gmp, mpfr, mpc, libiconv). I am pulling these out of conda-forge, but I am unsure of the pinning. 
2. My local toolchain builds use the c++ stdlib and zlib from my mac. I am guessing with the anaconda compilers a proper run export for these will be added? It will need to be added to the downstream gfortran package by hand otherwise.
3. I did not use run exports in gfortran_build since the libgfortran package built on it would get the run exports only needed for the gfortran package. 
4. gfortran 8.2.0 ends up shipping libgfortran version 5. I wonder if it makes sense to roll back the gcc version so we get an update libgfortran lib that still has the 3 major version. This might break less stuff in other places (eg numpy). IDK if that is actually true, but it seems safer.

Some things I tried but could not figure out:

1. I tried to build a multioutput package that runs the gcc/gfortran build and then builds libgfortran and gfortran directly. Unfortunately, `make install` from gcc compiles code and installs everything. This leaves the task of basically removing all of the stuff you don't want, which is annoying and hard.
2. I tried to package just gfortran and libgfortran into a multioutput package with the build as a separate package. This got complicated and I was worried about how it would interact with the packages already around.

So here we are.

### CODE REVIEW

**Comment by beckermr** [comment]
Well this build error seems impossible to debug. Any ideas?

**Comment by beckermr** [comment]
The internets seem to think it is an old bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57438

However I am already using their fix. :(

**Comment by beckermr** [comment]
Hmmm. 

Chris Green 2016-09-29 18:41:03 UTC
For those people still running into this (problem still exists with GCC 6.2), the following workaround will do the job on OS X / Mac OS: simply add this definition to your compile commands:

-D__builtin_unreachable=__builtin_trap

Worth a shot.

**Comment by beckermr** [comment]
The fact that it builds locally makes me think this is due to the older Xcode on circle and not the recipe.

**Comment by beckermr** [comment]
Updating xcode broke the conda build sys root. @mingwandroid can you take a look?

**Comment by beckermr** [comment]
OK. This is related to xcode 6.3 - I ran my own build on 7.3 and it worked fine

https://github.com/beckermr/staged-recipes/pull/2

**Comment by beckermr** [comment]
Bump on this...

**Comment by beckermr** [comment]
here @mingwandroid

**Comment by beckermr** [comment]
ACK. this is a toolchain build. IDK why...

**Comment by beckermr** [comment]
I figured out a way around needing this. Closing for now. Thanks for everyone's time!

**Comment by mingwandroid** [comment]
Can you let us know your workaround here for others facing the same issue (us probably in a few months to be precise!)

**Comment by beckermr** [comment]
Ohhhh it was in the code I was trying to build and very FORTRAN specific. I will post an example.

**Comment by beckermr** [comment]
Here is the thing:

```fortran
program tester
    use iso_c_binding
    implicit none

    integer, parameter :: lmax_arr = 10

    Type lSamples
        integer l0
        integer l(lmax_arr)
    end Type lSamples

    integer(c_int), target :: ivar
    type(c_ptr) jvar, kvar
    type(lSamples), target :: ls

    ivar = 42
    jvar = c_loc(ivar)
    kvar = c_loc(ivar)
    ! this line fails on gfortran 4.8 if you remove the '(1)'
    kvar = c_loc(ls%l(1))

    call assert_true(c_associated(jvar, kvar))
    call assert_true(c_associated(c_loc(ivar), c_loc(ivar)))

    contains

    subroutine assert_true(var1)
        logical, intent(in) :: var1

        if (var1 .eqv. .true.) then
            print *, "true"
        else
            print *, "false"
        endif
    end subroutine assert_true

end program tester
```

See the comment in the middle. For whatever reason, when using `c_loc` you need to feed it a indexed value in 4.8, but apparently not in 4.9+. I looked around for the docs on when or why this changed but I could not find anything. Someone with more serious fortran-fu might know.

**Pull request closed without merging**
