### PR TITLE
Add stardist recipe

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by uschmidt83** [comment]
Building this package might be complicated, since it needs to be done with gcc (and not clang), and it also uses openmp.
See [cibuildwheel](https://github.com/stardist/stardist/blob/master/.github/workflows/cibuildwheel.yml) action for details.

**Comment by jaimergp** [comment]
`-std=c+11` causes errors on CLang because the `Extension` object is taking both C++ and C source files, and `-std` is not allowed for C files. This is not a problem with GCC, but conda-forge only uses CLang on macOS so...

We could:

A) Rename every .c file to .cpp and cross fingers it's a valid subset
B) Subclass the `*Compiler` class and add a behaviour like the one specified in these SO questions ([1](https://stackoverflow.com/questions/47872981/python-extension-using-different-compiler-flags-for-a-c-parts-and-c-parts), [2](https://stackoverflow.com/questions/15527611/how-do-i-specify-different-compiler-flags-for-just-one-python-c-extension-source))

Linux does pass :)

**Comment by uschmidt83** [comment]
Thanks for working on this, @jaimergp!

> `-std=c+11` causes errors on CLang because the `Extension` object is taking both C++ and C source files, and `-std` is not allowed for C files. This is not a problem with GCC, but conda-forge only uses CLang on macOS so...

That's why we use gcc on macOS in our [wheel creation workflow](https://github.com/stardist/stardist/blob/master/.github/workflows/cibuildwheel.yml).

**Comment by uschmidt83** [comment]
> B) Subclass the `*Compiler` class and add a behaviour like the one specified in these SO questions ([1](https://stackoverflow.com/questions/47872981/python-extension-using-different-compiler-flags-for-a-c-parts-and-c-parts), [2](https://stackoverflow.com/questions/15527611/how-do-i-specify-different-compiler-flags-for-just-one-python-c-extension-source))

We're already using a [custom `build_ext`](https://github.com/stardist/stardist/blob/858cae17cf17f979122000ad2294a156d0547135/setup.py#L8-L35) for OpenMP support, maybe that's the way to go?

**Comment by jaimergp** [comment]
Yep, that's the idea @uschmidt83! Let's see if this simple patch works - I couldn't debug it locally yet so blind shot 🤞

**Comment by uschmidt83** [comment]
I just tried it locally, the `-std=c++11` is part of `extra_postargs`. It does compile if I remove it from there.

**Comment by jaimergp** [comment]
I think we got OpenMP support for free thanks to [this line](https://github.com/conda-forge/staged-recipes/pull/17766/files#diff-9e96ec64e2b25aa1c56159ea35a337acf285a5dd74fef3482ead2be9d41b99c9R23) (see [docs](https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp)).

**Comment by jaimergp** [comment]
@uschmidt83, which C++ standard should we target on Windows? `-std=c++11` is ignored on this platform, but maybe we can choose [something](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170) else?

**Comment by uschmidt83** [comment]
We only use features from the C++11 standard and the lowest standard in MSVC seems to be `/std:c++14`, hence it probably doesn't matter?

**Comment by jaimergp** [comment]
Ok, then last thing! Licenses! There are three vendored dependencies, and we need the license for all three:

* QHull, included.
* Nanoflann, missing! Is it [this one](https://github.com/jlblancoc/nanoflann/blob/master/COPYING)?
* Clipper, missing! Is it [this one](https://github.com/skyrpex/clipper/blob/master/License.txt)?

@uschmidt83 - can you confirm these are the correct ones? Ideally, the `stardist` repo should include them in a future release too. Notice the PyPI release is missing them too.

**Comment by uschmidt83** [comment]
> * Nanoflann, missing! Is it [this one](https://github.com/jlblancoc/nanoflann/blob/master/COPYING)?

The license is included [at the top of the source file](https://github.com/stardist/stardist/blob/858cae17cf17f979122000ad2294a156d0547135/stardist/lib/external/nanoflann/nanoflann.hpp#L2-L30) that we include. Apart from a year difference, it's the same as you've chosen.


> * Clipper, missing! Is it [this one](https://github.com/skyrpex/clipper/blob/master/License.txt)?

Looks good, since it matches https://www.boost.org/LICENSE_1_0.txt as indicated in a comment at the [top of the source file](https://github.com/stardist/stardist/blob/858cae17cf17f979122000ad2294a156d0547135/stardist/lib/external/clipper/clipper.cpp#L2-L31) that we bundle.

**Comment by jaimergp** [comment]
Excellent, good to go!

**Comment by uschmidt83** [comment]
I'm just noticing that I'm not listed as a "recipe maintainer". What are the consequences of this?

**Comment by jaimergp** [comment]
Oops, I'll fix that once the feedstock gets created.

**Comment by jaimergp** [comment]
Done! Check https://github.com/conda-forge/stardist-feedstock

**Pull request merged**
