### PR TITLE
Add skopeo

### PR DESCRIPTION
**Pull request by epruesse**
Checklist
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by bgruening** [comment]
Wow, if that works that would be great. I have just seen btrfs-tools and co as dependencies and assumed that it would be way harder.

**Comment by epruesse** [comment]
You can apparently disable those features. I assume `gpgme` is needed for signing/verifcation, `brtfs` probably for local container formats, etc.

**Comment by epruesse** [comment]
We'll see whether it builds. Didn't do full isolation on my box.

**Comment by epruesse** [comment]
@bgruening - any suggestions for co maintainers?

**Comment by epruesse** [comment]
@bgruening Trying to fix the circleci build by rebasing. My fork is pretty old.

**Comment by epruesse** [comment]
@bgruening Still awake? Need a merge :)

**Comment by epruesse** [comment]
- vendoring - this is a go package, so it vendors a lot of stuff. It all comes with the release tar ball, though, and the package only contains a single binary.
- skips - in theory, macos and windows builds are probably possible, but the real point of this tool is to be able to manipulate docker images from within a docker container without needing access to the docker socket. So the use case is primarily linux anywat.

We are going to use this in the Bioconda build pipeline.

**Pull request merged**
