### PR TITLE
Add python-pcl

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/help-python-c, this is ready for review.

A few notes:
  - The package is not officially maintained anymore (https://github.com/strawlab/python-pcl/issues/395). Hence there are quite a few packages, with basically all of them stemming from the Debian package (except for the last one that adds conda-forge include directories).
  - The package is a RC, but as it's not officially maintained anymore, the best we can get our hands on. It has been shipped in Debian (https://packages.debian.org/sid/python3-pcl).
  - I have skipped Windows as the Debian patches only take care of the Unix side of things. I don't think it's impossible to fix, but I have little interest in Windows and can open an issue in the feedstock once it exists to keep track of it (@traversaro, do you have a use case/interest? No worries if not.)

**Comment by traversaro** [comment]
> * (@traversaro, do you have a use case/interest? No worries if not.)

Cool, I did not even know about this, and it could indeed be useful. Anyhow, no one on our side is using it, and given that it is not currently mantained I am not interested in it.

**Comment by Tobias-Fischer** [comment]
Kind reminder @conda-forge/help-python-c @wolfv

**Comment by Tobias-Fischer** [comment]
Another ping @conda-forge/help-python-c @wolfv

**Comment by Tobias-Fischer** [comment]
Another friendly ping @conda-forge/staged-recipes :)

**Comment by Tobias-Fischer** [comment]
Thanks @wolfv!

**Pull request merged**
