### PR TITLE
Add r-sysfonts to conda-forge

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dpryan79** [comment]
Breaking due to the current conda 4.7 issues.

**Comment by dbast** [comment]
You can make the linter happy by using the latest conda-build version together with the r skeleton helper :)

**Comment by dpryan79** [comment]
> You can make the linter happy by using the latest conda-build version together with the r skeleton helper :)

I like to think of myself as a frequent tester that the linter is working :P

**Comment by dpryan79** [comment]
@dbast: Any clue what's wrong with `tar` on windows?

**Comment by dbast** [comment]
Hm... have seen something like that before.... still wired... would add something like `tar --version` to the bld.bat to understand what version of tar that is ... maybe that version needs to be called with dash for the flags `tar -xzf $file` instead `tar xzf $file` ... that would require patching the Makevars.win file... maybe adding `{{posix}}tar` + `{{posix}}gzip` to the recipe dependencies helps ... 

Or instead: add `https://statr.me/files/sysfonts-dep-win-biarch.tar.gz  # [win]` with sha256 to sources in meta.yaml and let conda handle the download and extraction into the right folder. Download and extraction can then be patched out of the Makevars.win.

**Comment by dpryan79** [comment]
Seems `{{posix}}tar` and `{{posix}}gzip` did the trick, thanks!

**Comment by dpryan79** [comment]
@conda-forge/help-r This is ready for review

**Comment by cbrueffer** [comment]
Looks good

**Pull request merged**
