### PR TITLE
Add jupyter_core and notebook.

### PR DESCRIPTION
**Pull request by pelson**
Again, added you as a maintainer @minrk - hope that is OK.

### CODE REVIEW

**Comment by jakirkham** [comment]
Just so I know, are you planning to do pyzmq too?

**Comment by pelson** [comment]
> Just so I know, are you planning to do pyzmq too?

Yes, but if you want to take it on, I've got plenty of others to do 😄

**Comment by jakirkham** [comment]
Was planning on it, but not today.

**Comment by pelson** [comment]
Ok. I'll let you know if I start looking at it. Thanks @jakirkham

**Comment by jakirkham** [comment]
If you do, there is a conda-recipes version that basically works. I can't remember whether it expects zeromq for Windows or not. In any event, pyzmq should be able to build that support for itself if those libraries are missing. Maybe that will be the easiest way to go for now until we get those fixed to support Windows

**Comment by pelson** [comment]
I haven't tried to do anything clever with NPM here. I've let the setup.py do its thing. One day... 😄

**Comment by jakirkham** [comment]
Well, that ( https://github.com/conda-forge/staged-recipes/pull/136 ) is still a WIP, right?

**Comment by pelson** [comment]
Build is because npm isn't available. Here goes... 🐇 🌋

**Comment by pelson** [comment]
Ironically, this builds only on Windows because npm is installed by AppVeyor 😄

**Comment by minrk** [comment]
The pyzmq recipe relies on bundling zeromq on Windows, so it has no dependencies on Windows. This is only because I couldn't figure out how to link libzmq properly on Windows, but it should be doable. Starting with the same bundling should be an okay starting point for the package, though.

**Comment by pelson** [comment]
The build on Windows failed this time as the nodejs dependency is stacked up in an AppVeyor queue (GDAL and its 3 hour builds grrr 😄 ). I'm going to go ahead and merge this, as it was working before, and I have no reason to believe it wont work now.

**Pull request merged**
