### PR TITLE
Add voluptuous feedstock.

### PR DESCRIPTION
**Pull request by vamega**

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @vamega.

**Comment by jakirkham** [comment]
@alecthomas @tusharmakkar08, just letting you know we have added `voluptuous` to [conda-forge]( http://conda-forge.github.io/ ). This will allow users to easily install this with [`conda`]( http://conda.pydata.org/docs/ ) (`conda install -c conda-forge voluptuous`). The maintenance burden here is light as all testing releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this repo]( https://github.com/conda-forge/voluptuous-feedstock ). If you have any interest in being added as a maintainer (to make new releases for instance), we would love to have you on board. Thanks for your work on `voluptuous`. 😄

**Comment by tusharmakkar08** [comment]
@vamega @jakirkham Thanks for adding Voluptuous to conda package manager. You can add me as a maintainer and I will try to update the recipe whenever we make new releases.

**Comment by jakirkham** [comment]
Awesome. Thanks @tusharmakkar08. This PR ( https://github.com/conda-forge/voluptuous-feedstock/pull/1 ) will add you as a maintainer of `voluptuous`.

**Pull request merged**
