### PR TITLE
Add r-rdpack and r-gbrd

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by dpryan79** [comment]
Hopefully this actually works. r-gbrd is a dependency of r-rdpack.

**Comment by dpryan79** [comment]
@bgruening I mentioned this on gitter, but one of the recipes (r-forge) that got merged in is throwing an error and blocking other packages from getting pushed through.

**Comment by bgruening** [comment]
Mh, I see it failing at graphql: https://travis-ci.org/conda-forge/staged-recipes/jobs/445018001#L404

**Comment by dpryan79** [comment]
That's a new one.

**Comment by dpryan79** [comment]
BTW, I have a few PRs that are ready for merging :)

**Comment by bgruening** [comment]
Of course you have :)

**Pull request merged**
