### PR TITLE
Add conda forge recipe for torchgeo

### PR DESCRIPTION
**Pull request by adamjstewart**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

@calebrob6 I added you as a maintainer since you use Conda more than I do.
@isaaccorley let me know if you want to help maintain this recipe

Only question I have is about dependencies. Conda doesn't seem to support optional dependencies like pip/spack does, so I included all dependencies required to import any part of the library. There are some optional dataset libraries with lazy imports that didn't get added. I think this is best practice, but let me know if that's not the case.

### CODE REVIEW

**Comment by adamjstewart** [comment]
### Linux/macOS

`pip check` is failing for reasons outside of my control:
```
omegaconf 2.1.1 has requirement antlr4-python3-runtime==4.8, but you have antlr4-python3-runtime 4.9.2.
```
Should I just remove `pip check` or is there a better way to solve this?

### Windows

The concretizer is failing to solve for multiple dependencies, not sure what to do about this other than mark the package as not supporting Windows. We test on Windows and everything works fine, so we would like to distribute it on Windows if possible.

**Comment by TomAugspurger** [comment]
> Conda doesn't seem to support optional dependencies like pip/spack does, so I included all dependencies required to import any part of the library.

That's correct. Sometimes maintainers will choose to have multiple feedstocks where one gives everything and the other gives just the required libraries (e.g. [dask](https://github.com/conda-forge/dask-feedstock/blob/master/recipe/meta.yaml) and [dask-core](https://github.com/conda-forge/dask-core-feedstock/blob/master/recipe/meta.yaml)). There's also the option to do multiple "outputs" from a single recipe / feedstock like matplotlib: https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml. I'm not really sure how that works.

@hmaarrfk do you know if anything is necessary for this recipe to properly depend on pytorch-cpu vs. gpu? I see https://github.com/conda-forge/torchvision-feedstock/blob/master/recipe/meta.yaml, but that might be more complicated since IIUC torchvision depends directly on CUDA. This package doesn't.

And I don't want to bury @adamjstewart questions about pip-check and windows at https://github.com/conda-forge/staged-recipes/pull/16875#issuecomment-965732639.

**Comment by hmaarrfk** [comment]
The pip check should be fixed upstream. I made the PR but likely won't have time to followthrough with it. If you could take it over @adamjstewart if it requires more work I would be grateful.

We didn't build pytorch fo windows sadly... that is likely why it isn't solving: https://github.com/conda-forge/pytorch-cpu-feedstock/blob/master/recipe/meta.yaml#L19


If this package doesn't depend on GPU functionality, I would simply omit any GPU constraints here.

The recipe looks fine here simply depending on `pytorch` no qualifier.

**Comment by hmaarrfk** [comment]
As far as this recipe is concerned, I would commen tout the pip check command, and refer to the PR to the offending recipe. since it is noarch, then it should be fine.

**Comment by adamjstewart** [comment]
@hmaarrfk trying to understand the above message. This package is pure Python so I think `noarch: python` is correct? But the tests were failing due to lack of Windows support for PyTorch, so I think `skip: true  # [win]` is also correct? But they seem incompatible according to the linter? What's the proper way to do this one?

**Comment by hmaarrfk** [comment]
I think the correct thing is not to skip the windows, and explain to the maintainers of `staged-recipes` why the windows tests are failing.

When pytorch gets windows support, this noarch package will be installable by end users.

Until the day that pytorch gets windows support, this noarch package will not be installable by end users.

**Review by dopplershift — APPROVED** [review]
Ignoring Windows failure due to missing deps for noarch. Just need confirmation from @calebrob6 that they are willing to be listed as a maintainer for this recipe.

**Comment by calebrob6** [comment]
fine with me, thanks!

**Pull request merged**
