### PR TITLE
add askbot and required dependencies

### PR DESCRIPTION
**Pull request by AdMax18**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by AdMax18** [comment]
@mxr-conda can you comment to be a maintainer on these packages

**Comment by AdMax18** [comment]
The test steps were modified from pip check primarily because the askbot_requirements.txt restricts some packages to older versions that are not currently available on conda and tests require a database for a dummy application as listed in the instructions: https://pypi.org/project/askbot/

**Comment by mxr-conda** [comment]
> @mxr-conda can you comment to be a maintainer on these packages

agree to maintain

**Comment by AdMax18** [comment]
just pinging @conda-forge/staged-recipes for an initial review

**Comment by ocefpaf** [comment]
Some of those depend on packages in this same PR and you'll face a race condition during the feedstock creation. The best course of action is to wait for the passing ones to be up in the channel and then re-start the failing ones.

**Pull request merged**
