### PR TITLE
Drop Python 3.4 support

### PR DESCRIPTION
**Pull request by jakirkham**
As Python 3.6 is being included throughout feedstocks and Python 3.5 is still in use, it makes sense for us to drop our oldest Python 3 that still remains. The purpose of doing this is to cutdown on the CI burden from building so many things and maintenance burden associate with this and the older Python. So here we drop Python 3.4 from the matrix.

xref: https://github.com/conda-forge/conda-smithy/pull/421

### CODE REVIEW

**Comment by scopatz** [comment]
Appveyor seems to have failed.

**Comment by jakirkham** [comment]
Yeah, it needs a rebase.

**Comment by jakirkham** [comment]
Rebased.

Though the bigger question is are we ready to go ahead with this. In the recent meeting, it sounded like yes, but we had a small sample size. 😄 So what do people think?

cc @conda-forge/core

**Comment by mwcraig** [comment]
LGTM

**Comment by patricksnape** [comment]
LGTM

**Comment by jjhelmus** [comment]
I'm in favor of dropping support for Python 3.4.  👍

**Comment by ocefpaf** [comment]
OK. Almost all of @conda-forge/core gave the :+1:

Merging this to give Travis-CI some time to breath!

PS: We need more votes on #2177

**Comment by jjhelmus** [comment]
Thanks for looking after this @ocefpaf!

**Comment by jakirkham** [comment]
Thanks everyone. 😄

**Pull request merged**
