### PR TITLE
feat: Add qastle

### PR DESCRIPTION
**Pull request by matthewfeickert**
* c.f. https://github.com/iris-hep/qastle
* Recipe generated with grayskull via 'grayskull pypi qastle' and then edited to add additional information.
* Required for https://github.com/ssl-hep/ServiceX_frontend/issues/352

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [N/A] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@masonproffitt Can you comment below if you are willing to be a maintainer on this conda-forge recipe (required before a conda-forge maintainer can review this). (c.f. https://github.com/conda-forge/staged-recipes/pull/26178#issuecomment-2081881679) As the package author I want to include you, but I am willing to do the maintenance of hitting "merge" if there are ever future releases of `qastle`.

**Comment by masonproffitt** [comment]
I am willing to be listed as a maintainer.

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
@conda-forge/help-python, ready for review

**Comment by matthewfeickert** [comment]
cc @chrisburr @mwcraig @dopplershift (people I personally know and feel less bad about bothering as they can also guilt free ignore me :slightly_smiling_face:) as this is on the second page of the requested review page (https://github.com/conda-forge/staged-recipes/issues?page=1&q=is%3Aopen+label%3Areview-requested+label%3Apython) as I opened it so long ago.

**Comment by mwcraig** [comment]
Thanks for the ping and the package, @matthewfeickert, merging...

**Pull request merged**
