### PR TITLE
Re-add python-simplegeneric as simplegeneric

### PR DESCRIPTION
**Pull request by ocefpaf**
Not sure were the discussion on this ended, but it is bringing a lot of grieve to our users and I believe we should move forward with the renaming.

If this is merged we should remove https://github.com/conda-forge/python-simplegeneric-feedstock

Ping @minrk, @msaraha, and @pelson.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @msarahan

**Comment by jakirkham** [comment]
LGTM

**Comment by minrk** [comment]
I haven't followed the package naming prefix back-and-forth closely enough, but 👍 if this is consistent with the current thoughts over there.

**Comment by jakirkham** [comment]
There was a question in a different renaming case as to whether we just rename the feedstock and package name vs re-adding like this. However, that point hasn't come up for discussion w.r.t. `simplegeneric`. IMHO am more than happy to proceed this way. Though fixing the `ipython` dependency to use the `defaults` name (non-prefixed) was the crucial part.

**Comment by pelson** [comment]
We ended up renaming the package within the feedstock (https://github.com/conda-forge/python-simplegeneric-feedstock/pull/3). We will need to tool ourselves up to rename feedstocks quickly and easily, and we have basically reduced the pressure on doing that by separating the package name from the feedstock name.

**Pull request closed without merging**
