### PR TITLE
Move incorrectly merged recipes into correct dir

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by synapticarbors** [comment]
This is to fix the issue mentioned in https://github.com/conda-forge/staged-recipes/pull/12329#discussion_r467228925. As an overview, I incorrectly merged several of @basnijholt's PRs that had recipes outside of the `recipe` directory. I've moved them into the correct location in this PR. I'm not sure if that's enough to back out the issue or if other steps need to be taken. 

Apologies for any issues this might have caused.

**Comment by basnijholt** [comment]
Oops, my apologies! I was using `grayskull` and thought it created a directory too.

**Comment by synapticarbors** [comment]
@basnijholt -- no problem. It was my fault for not noticing before I merged. I pulled in your two other PRs for `dataproperty` and `mbstrdecoder` since I had created a circular dependency between PRs.

**Comment by basnijholt** [comment]
Some of these packages depend on each other, would it work this way (by putting them all together)?

**Comment by synapticarbors** [comment]
You can combine them all and it works out the inter-dependencies. See the following from the log:

```
Resolved dependencies, will be built in the following order:
    releasecmd-0.3.1-on-linux-64
    tcolorpy-0.0.6-on-linux-64
    pathvalidate-2.3.0-on-linux-64
    msgfy-0.1.0-on-linux-64
    mbstrdecoder-1.0.0-on-linux-64
    typepy-1.1.1-on-linux-64
    dataproperty-0.50.0-on-linux-64
    tabledata-1.1.3-on-linux-64
```

**Comment by chrisburr** [comment]
@synapticarbors Yup, this should be fine. Thanks for tidying it up!

@basnijholt I don't remember if this has been fixed but you might find that the first build fails for some of the packages due to them not being built yet. If this happens just push an empty commit to master to re-trigger the build once the dependent packages are available.

**Pull request merged**
