### PR TITLE
Add libharu

### PR DESCRIPTION
**Pull request by hobu**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

@ocefpaf This was requested in #5855.

### CODE REVIEW

**Comment by hobu** [comment]
A problem with this package is many people use master which has a different API than this old release version.

**Comment by xylar** [comment]
VTK needs this package.  It is currently being vendored :-(

If it's alright, I'll make a PR to your fork, @hobu, to try to get this going again.

**Comment by hobu** [comment]
> VTK needs this package. It is currently being vendored :-(

Are they using the old or master API? The biggest problem with this recipe is most people need master and there hasn't been a release in a really long time.

**Comment by xylar** [comment]
> Are they using the old or master API?

"They" is me in this case, but this is for my latest test of 9.0.0.rc1, which is pretty close to `master`: https://github.com/conda-forge/vtk-feedstock/pull/110

**Comment by xylar** [comment]
> The biggest problem with this recipe is most people need master and there hasn't been a release in a really long time.

Yep, we're in that boat, which is why I'm pushing so hard to try to get the RC built correctly and tested on our downstream packages.  We're doing that, and learning just how bad the build currently is :-(

**Comment by xylar** [comment]
@hobu, pull request is there: https://github.com/hobu/staged-recipes/pull/1

Not sure if you were notified.

**Comment by xylar** [comment]
This was merged in #11129 and should be closed.

**Pull request closed without merging**
