### PR TITLE
add gglasso on conda-forge

### PR DESCRIPTION
**Pull request by Vlasovets**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Vlasovets** [comment]
@conda-forge/help-python,
@conda-forge-admin, hi!
I would like to publish gglasso recipe on conda-forge, thank you!

**Comment by Vlasovets** [comment]
@ocefpaf, sorry for disturbing you, you have previously reviewed another of my recipes, may I ask you to take a look at this one also, please?

**Comment by ocefpaf** [comment]
> @ocefpaf, sorry for disturbing you, you have previously reviewed another of my recipes, may I ask you to take a look at this one also, please?

We need all maintainers listed in the extra section to agree to maintain this recipe. We are missing two. (You, as the submitter of the PR, is assumed to be a maintainer.)

**Comment by Vlasovets** [comment]
> We need all maintainers listed in the extra section to agree to maintain this recipe. We are missing two. (You, as the submitter of the PR, is assumed to be a maintainer.)

@ocefpaf, I see, thank you!
I have removed the other two guys from the maintainer's list, now it is only me.

**Comment by ocefpaf** [comment]
> I have removed the other two guys from the maintainer's list, now it is only me.

BTW you can add your team back in the feedstock. We only require acknowledgment in staged-recipes b/c here it is "our responsibility" and, for some reason. some folks get mad with all the automated invites they'll get. In the feedstock it is "your responsibility" and you know who to invite and who not to.

**Pull request merged**
