### PR TITLE
Add mosfit

### PR DESCRIPTION
**Pull request by guillochon**

### CODE REVIEW

**Comment by guillochon** [comment]
Waiting on some dependencies to merge...

**Comment by pkgw** [comment]
Powercycling to rebuild now that astrocats is available.

**Comment by pkgw** [comment]
Oh ... `astrocats` needs to be added in `meta.yaml`.

**Comment by pkgw** [comment]
Still having EAGAIN problems. As long as you're providing your own print function, looks like you should have it catch EAGAIN errors and retry the print calls as per some of the solutions that people have posted online relating to this stuff.

**Comment by pkgw** [comment]
CC [mpi4py-feedstock#8](https://github.com/conda-forge/mpi4py-feedstock/pull/8#issuecomment-296627667) ; mpich nonblocking issues are causing problems for the test scripts. That issue in turn is logged with mpich [here](http://trac.mpich.org/projects/mpich/ticket/1782), inspired by [this StackExchange question](http://stackoverflow.com/questions/14167620/stdin-seems-to-be-broken-after-call-to-system-invoking-mpiexec).

**Comment by pkgw** [comment]
You should add a comment explaining the pipe into cat in the test.sh invocation, but that can happen later.

**Pull request merged**
