### PR TITLE
Add mayavi recipe

### PR DESCRIPTION
**Pull request by hadim**
A revival of https://github.com/conda-forge/staged-recipes/pull/1581

### CODE REVIEW

**Comment by hadim** [comment]
Waiting for an answer there https://github.com/enthought/mayavi/issues/457

**Comment by grlee77** [comment]
Hi @hadim.  If you have time to take this over from #1581 that is fine by me.  One reason aside from lack of time that I have not updated #1581, was that I forgot that VTK was not being built on all platforms due to time limits at the free CI services.  For example, the VTK feedstock does not build any OS X packages (or a python 3.4 package on linux).

https://github.com/conda-forge/vtk-feedstock/blob/bb1903e93ba81a7d55aa84879033463a31e3a0c0/recipe/meta.yaml#L19

The same skip line from the VTK recipe will need to be present in the mayavi recipe.

**Comment by hadim** [comment]
Well I thought the issue was easier to fix than it is.

Maybe we should both keep our PRs open and wait for help or more time to fix it.

**Comment by Cadair** [comment]
can someone restart this build seeing how conda-forge/vtk-feedstock#13 has been merged please.

**Comment by ocefpaf** [comment]
> can someone restart this build seeing how conda-forge/vtk-feedstock#13 has been merged please.

Done.

**Comment by dfroger** [comment]
I forgot to update the build number in VTK when fixing #13, so I'm note sure the VTK package is yet available... See https://github.com/conda-forge/vtk-feedstock/pull/19

**Comment by Cadair** [comment]
@dfroger Should this be restarted now? As conda-forge/vtk-feedstock#19 ?

**Comment by dfroger** [comment]
@Cadair there is another error when importing `vtk` on circleci:

    ImportError: No module named vtkRenderingOpenGLPython

I think we need to add the same [yum_requirements.txt](https://github.com/conda-forge/vtk-feedstock/blob/487d1d33b5f6ce6995454f482928e34520823613/recipe/yum_requirements.txt) as in vtk feedstock.

We should also skip build on OSX and linux+py34, as in vtk [recipe](https://github.com/conda-forge/vtk-feedstock/blob/487d1d33b5f6ce6995454f482928e34520823613/recipe/meta.yaml#L26). (I don't know why OSX and linux+py34 are skipped for VTK).

And there are also errors on appveyor that may need to be fixed...

**Comment by dfroger** [comment]
this can be closed, as #2215 is merged. Other PR coming for windows and osx...

**Pull request closed without merging**
