### PR TITLE
Adding BindsNET package 

### PR DESCRIPTION
**Pull request by Hananel-Hazan**
Adding BindsNET package to conda-forge

### CODE REVIEW

**Comment by Hananel-Hazan** [comment]
Hi 
How can I add conda packages that on conda-forge or other channel to meta.yaml?

**Comment by scopatz** [comment]
Hi @Hananel-Hazan - I am not sure I understand your question fully, but you should not depend on software outside of conda-forge

**Comment by Hananel-Hazan** [comment]
Thank you for replying. 

Building the package locally after adding the needed channel works great. The conda package can be installed on any computer, without need to add more channels.  In the conda package the file `about.json` has the reference to the needed channels:
`
{
  "channels": [
    "defaults",
    "powerai",
    "conda-forge"
  ],
`

I dont find how to add additional channels to the `meta.yaml` in order to compile the package on conda-forge pipeline.

Thank you for all the help

**Comment by scopatz** [comment]
You should not add additional channels to the build. Conda-forge tries to be as self-contained as possible.  If there are dependencies missing on conda-forge, then please put in PRs adding them first :wink:

**Comment by Hananel-Hazan** [comment]
Chasing dependencies is a rabbit hole task, that will be for another day...

At the meantime, is it possible to add the dependencies using conda in the `build.sh` ?

**Comment by scopatz** [comment]
No, you will end up with a package that is uninstallable by users if you do that. Most of the dependencies are probably already on conda-forge

**Comment by Hananel-Hazan** [comment]
Thanks!

**Pull request closed without merging**
