### PR TITLE
Package xeus-cling

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This still depends on versions of xeus that are not on conda-forge but only in QuantStack because of the lack of a recent GCC in conda-forge.

### CODE REVIEW

**Comment by isuruf** [comment]
See my comment in xeus-python about testing

**Comment by SylvainCorlay** [comment]
I have added the conda_build config for new compilers. This is ready!

**Comment by isuruf** [comment]
On OSX

> WARNING (xeus-cling,bin/xeus-cling): Needed DSO lib/libz.1.dylib found in ['zlib']
> WARNING (xeus-cling,bin/xeus-cling): .. but ['zlib'] not in reqs/run, i.e. it is overlinked (likely) or a missing dependency (less likely)

**Comment by SylvainCorlay** [comment]
> On OSX
> 
> > WARNING (xeus-cling,bin/xeus-cling): Needed DSO lib/libz.1.dylib found in ['zlib']
> > WARNING (xeus-cling,bin/xeus-cling): .. but ['zlib'] not in reqs/run, i.e. it is overlinked (likely) or a missing dependency (less likely)
> > 

This appears to already be an issue in `cling-feedstock`. I don't know much about overlinking.

**Comment by msarahan** [comment]
The overlinking warning indicates that zlib has been linked in by xeus-cling, but there is no explicit zlib dependency.  If zlib linking was not intentional, it's "overlinking" and that's what the ``--no-as-needed`` flag tries to get rid of.  On the other hand if it is intentionally linked, and you don't have an explicit dependency listed in meta.yaml, you're relying on it being there implicitly and that's fragile.

**Comment by SylvainCorlay** [comment]
Just adding zlib as a host dependency fixed it!

**Comment by SylvainCorlay** [comment]
This is ready to go!

**Pull request merged**
