### PR TITLE
Add MSMBuilder

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by mpharrigan** [comment]
Would anyone be able to help me with the bizarre travis failure I'm seeing? It can't import numpy even though it's a build dependency. I can't replicate this locally with conda build.

**Comment by mpharrigan** [comment]
@synapticarbors have you ever seen an error like this?

**Comment by synapticarbors** [comment]
@mpharrigan This error seems to be occurring across several staged recipes and is being tracked here:

https://github.com/conda-forge/numpy-feedstock/issues/42

**Comment by jakirkham** [comment]
Please enable CircleCI on your fork and rebase on current `master`.

**Comment by mpharrigan** [comment]
Rebased!

**Comment by mpharrigan** [comment]
This seems beyond my control (??)

```
import: u'pyhmc'
Traceback (most recent call last):
  File "C:\bld\pyhmc_1489692285381\test_tmp\run_test.py", line 2, in <module>
    import pyhmc
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\pyhmc\__init__.py", line 28, in <module>
    from .autocorr1 import integrated_autocorr1
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\pyhmc\autocorr1.py", line 6, in <module>
    from statsmodels.tsa.stattools import acf
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\statsmodels\tsa\stattools.py", line 10, in <module>
    from scipy import stats
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\stats\__init__.py", line 348, in <module>
    from .stats import *
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\stats\stats.py", line 177, in <module>
    from . import distributions
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 16, in <module>
    from scipy.misc import doccer
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\misc\__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\interpolate\__init__.py", line 176, in <module>
    from .interpolate import *
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\interpolate\interpolate.py", line 32, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "scipy/interpolate/interpnd.pyx", line 1, in init scipy.interpolate.interpnd (scipy\interpolate\interpnd.c:25150)
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\site-packages\scipy\spatial\__init__.py", line 94, in <module>
    from .ckdtree import *
  File "scipy/spatial/ckdtree.pyx", line 29, in init scipy.spatial.ckdtree (scipy\spatial\ckdtree.cxx:19224)
  File "C:\bld\pyhmc_1489692285381\_t_env\lib\multiprocessing\__init__.py", line 136, in cpu_count
    raise NotImplementedError('cannot determine number of cpus')
NotImplementedError: cannot determine number of cpus
```

**Comment by mpharrigan** [comment]
Hi all: this is ready to merge now cc @conda-forge/staged-recipes

**Comment by mpharrigan** [comment]
I think something went wrong with the creation of the pyhmc feedstock

https://github.com/conda-forge/pyhmc-feedstock/

**Comment by ericdill** [comment]
The repository got created, but the part where we try and fill it with stuff and automatically register the CI services is flaky. The pyhmc recipe is still in the master branch, so the feedstock will still be created with all the files and CI services registered

**Comment by ericdill** [comment]
We're working through possible solutions to make the CI registration code more robust [here](https://github.com/conda-forge/staged-recipes/issues/2619)

**Comment by mpharrigan** [comment]
ah ok, so patience will do the trick here ?

**Comment by ericdill** [comment]
> ah ok, so patience will do the trick here ?

Yup! It'll get created eventually 😀 We've merged 52 PRs this week and there's only 7 recipes in the master branch. I can't say exactly when it will get created, but none of the recipes in the master branch are more than two days old. (All of the recipes in the master branch are waiting to have their feedstocks created)

**Pull request merged**
