### PR TITLE
add pycroscopy

### PR DESCRIPTION
**Pull request by carlodri**
Addresses https://github.com/pycroscopy/pycroscopy/issues/134.

### CODE REVIEW

**Comment by carlodri** [comment]
@compphyschris and @ssomnath, please confirm here that you agree to be added as recipe maintainers

**Comment by ssomnath** [comment]
I agree to be added as a recipe maintainer

**Comment by CompPhysChris** [comment]
I agree to be added as a recipe maintainer.

**Comment by synapticarbors** [comment]
I'm happy to merge this. I just wanted to make sure it was no longer a WIP before I did.

**Comment by carlodri** [comment]
thanks @synapticarbors, it's indeed still a WIP, I'm waiting for a version bump from the developer's side. I'll ping you as soon as it's ready.

**Comment by carlodri** [comment]
@conda-forge-admin, please lint

**Comment by carlodri** [comment]
@synapticarbors this is ready to be merged AFAIU. Let me know if you see any problems with the recipe.

**Pull request merged**
