### PR TITLE
Add git-annex-remote-rclone

### PR DESCRIPTION
**Pull request by jwodder**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Let's make `git-annex` linux only as we did for datalad -- there is no stock git-annex package yet in conda-forge, but being able to install git-annex-remote-rclone would already be a great step forward, and datalad-installer could be there (filed https://github.com/datalad/datalad-installer/issues/70) to assist as well.

**Comment by yarikoptic** [comment]
no bash on windows... there is m2-bash (msys2 one) but I am not sure if that would work anyhow due to e.g. https://github.com/ContinuumIO/anaconda-issues/issues/12124 . So let's just make this package OSX and Linux only for now

**Comment by jwodder** [comment]
@yarikoptic 

> So let's just make this package OSX and Linux only for now

How do I do that?  I can't find any documentation on that.

**Comment by yarikoptic** [comment]
Look at git annex feedstock. 
https://github.com/conda-forge/git-annex-feedstock/blob/master/recipe/meta.yaml#L72

**Comment by jwodder** [comment]
@yarikoptic New PR: https://github.com/conda-forge/staged-recipes/pull/18364

**Pull request closed without merging**
