### PR TITLE
Add cling recipe

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This makes use of the [cling] variants for llvmdev and clangdev.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Tested locally. *Cling works!* Yeah!

man-in-crowd-screaming

**Comment by SylvainCorlay** [comment]
@conda-forge/core If anyone dropped by and hit the green button, it would be great!

**Comment by scopatz** [comment]
Thanks @SylvainCorlay

**Comment by SylvainCorlay** [comment]
It is merged!

duck-horse1

**Comment by SylvainCorlay** [comment]
@scopatz thanks!

On the conda-forge channel, we tagged certain builds of `llvmdev` and `clangdev` as "broken", which I think can be safely remove completely now. Although I don't have the privileges to do so.

**Pull request merged**
