### PR TITLE
r-randomcolor generated with skeleton

### PR DESCRIPTION
**Pull request by valscherz**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by valscherz** [comment]
Fresh compiling of r-randomcolor made possible thanks to introduction of r-v8 https://github.com/conda-forge/staged-recipes/commit/479d488c9b1e4ac947c22d9c380da8d24e285c52 and v8 in conda-forge.

Similar to https://github.com/conda-forge/staged-recipes/pull/6916, now closed.

**Comment by xhochy** [comment]
@valscherz if this is a `noarch` packages please keep it as such. The failing windows build here because of the missing `r-v8` there is ok. The feedstock will then only be built on Linux and this is fine.

**Comment by valscherz** [comment]
@xhochy You say I should revert to f6df1669d4e380203a8b78288fd127869925a48d and don't pay attention to the failing builds ?
Thanks for your help

**Comment by xhochy** [comment]
Yes

**Comment by valscherz** [comment]
@xhochy Ok thanks, then it is what I have done

**Pull request merged**
