### PR TITLE
add scheme for repodata hotfixing

### PR DESCRIPTION
**Pull request by msarahan**
This scheme is ultimately meant to generate one file per subdir, ``patch_instructions.json``.  That file has entries by 

```
instructions = {
        "patch_instructions_version": 1,
        "packages": defaultdict(dict),
        "revoke": [],
        "remove": [],
    }
```

```revoke``` and ```remove``` are lists of filenames.  ```remove``` makes the file not show up in the index (it may still be downloadable with a direct URL to the file).  ```revoke``` makes packages uninstallable by adding an unsatisfiable dependency.  This can be made installable by including a channel that has that package (to be created by @jjhelmus).

``packages`` is a dictionary, where keys are package filenames.  Values are dictionaries similar to the contents of each package in repodata.json.  Any values in provided in ``packages`` here overwrite the values in repodata.json.  Any value set to None is removed.

A tool on our end will download this package when it sees updates to it, and will apply the patch_instructions.json to the repodata for the static repodata mirror that @kalefranz has proposed.

cc @conda-forge/core - I tried to add everyone to maintainers.  My apologies if I overlooked anyone.

### CODE REVIEW

**Comment by mwcraig** [comment]
Happy to be a maintainer (don't object if I'm not, either 😀)

**Comment by jakirkham** [comment]
Believe `noarch: generic` should work. What jobs are you seeing that shouldn’t be there?

**Comment by msarahan** [comment]
Travis and appveyor? Maybe I'm thinking of the actual feedstock, not just the staged recipes

**Comment by jakirkham** [comment]
Currently we only disable those on the feedstock. We could consider disabling them on staged-recipes as well.

**Comment by mariusvniekerk** [comment]
Yeah looks okay to me.  Guess since we don't really care about the windows build it should not block anything

**Comment by mariusvniekerk** [comment]
Ultimately where are we going to run this since we'd need to generate it at a fairly regular cadence and the current feedstock building process is probably not really it?

**Comment by mariusvniekerk** [comment]
also pushing a conda package to maintain these patches seem odd?

**Comment by msarahan** [comment]
I think of it less as a package to maintain patches, and more as an automated process that happens to leverage the existing infrastructure.  The instructions (the python file) need to be the thing that we really care about, and I don't want people to get hung up on or stuck in dealing with the large JSON files.

I expect that this patch set (and this package build) will be generated only when the python file herein changes.  On Anaconda's side, we will sync repodata with conda-forge on the static mirror.  I think @kalefranz has said every 20 min is a reasonable expectation.  Part of that sync will be to alter the sync'ed repodata with these patches.  Using conda to install specific versions of these patches on our side seems like a decent capability for when mistakes are inevitably made.

**Comment by msarahan** [comment]
The key interface is the large JSON files, though - let me make that clear.  If anyone has other better ideas on how to generate and host those JSON files, please speak up.  I might have a bad case of "when you have a hammer, everything looks like a nail."

**Comment by msarahan** [comment]
I'm going to go ahead and merge this, with the thought being that this will be easier on the CI's as a feedstock.  I don't consider it done necessarily, and I invite further discussion on the feedstock.

**Pull request merged**
