### PR TITLE
Add scvi-tools package

### PR DESCRIPTION
**Pull request by adamgayoso**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by galenxing** [comment]
I am willing to be a maintainer

**Comment by romain-lopez** [comment]
I am willing to be a maintainer

**Comment by adamgayoso** [comment]
@conda-forge/staged-recipes I believe Windows is failing due to Pytorch, but it's hard for me to gather why the linux build is failing. Any help is appreciated!

**Comment by watiss** [comment]
I am willing to be a maintainer

**Comment by jjhong922** [comment]
I am willing to be a maintainer

**Comment by adamgayoso** [comment]
@conda-forge-admin, please ping team

to the conda forge team, we will also no longer be maintaining the bioconda recipe

**Comment by adamgayoso** [comment]
I believe Windows is failing due to Pytorch

**Comment by adamgayoso** [comment]
@conda-forge/staged-recipes please review :-D

**Comment by adamgayoso** [comment]
Hi @conda-forge/core I assume you have many PRs to deal with but to make it clear, the windows build is expected to fail because of pytorch

**Pull request merged**
