### PR TITLE
adding singularity-hpc

### PR DESCRIPTION
**Pull request by ngam**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge/staged-recipes this is ready to go

Please look at my modified tests because 1) some of their test suits rely on singularity/docker being installed (disabled those) and 2) some others return verbose output and fail on as a result (also disabled for linux64). Do you have any other recommendation for tests? Thanks!

**Comment by ngam** [comment]
update: I "fixed" the build for windows. The thing is though, this pkg will likely be useless for anything outside of linux. That is because in order to really make use of this package, one would need Singularity installed (this package is independent of Singularity, however, its functionality is limited without it). Singularity is only available on linux platforms (for now). I am not sure if @conda-forge/staged-recipes folks have an opinion about how to navigate these things: If a pkg is truly noarch (this is one is truly noarch) but the actual practical use of it is only truly available on linux, do we push the noarch build or do we push the linux build only? I would assume the noarch... but I could be mistaken. The authors push their pypi whees as noarch as well fwiw.

**Comment by ngam** [comment]
@conda-forge/staged-recipes gentle reminder to review this when you have chance, thanks :)

**Comment by cbrueffer** [comment]
My preference (and what we do for `noarch` R packages) is to keep packages `noarch` even if dependencies are missing on specific platforms.

**Comment by ngam** [comment]
> My preference (and what we do for `noarch` R packages) is to keep packages `noarch` even if dependencies are missing on specific platforms.

This is still `noarch`:
```yaml
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shpc = shpc.client:run_shpc
```

Or do you mean in the testing?
```yaml
  commands:
    - shpc --help
    - pytest shpc/tests/test_settings.py  # [not win]
    # ignore linux test because test returns verbose value
#     - pytest shpc/tests/test_utils.py  # [not linux64]
    - pytest shpc/tests/test_container_config.py  # [not win] 
    # ignore othere tests because they trigger docker/singularity/podman
```

I didn't know the tests would influence the `noarch` designation. Happy to drop the tests entirely and only have `shpc --help` as the sole test if that's what you think should be done. Otherwise, the tests are meaningless without underlying infrastructure (podman, singularity, docker, etc.) loaded, which we simply cannot do here...

**Comment by cbrueffer** [comment]
It was just a comment on your question from a few days ago ;-) Not a review.

**Comment by ngam** [comment]
> It was just a comment on your question from a few days ago ;-) Not a review.

Oooooops..... Didn't even remember my own question! Thanks!

**Pull request merged**
