### PR TITLE
submit pymc3

### PR DESCRIPTION
**Pull request by ericmjl**
submitting pymc3 recipe!

### CODE REVIEW

**Comment by ericmjl** [comment]
@jakirkham: help request ping please! 

I noticed that CircleCI's tests were failing because:

`bash: line 40: conda-build-all: command not found`

Also noticed that `conda-build` has been downgraded from v2.x to v1.x.

It's been a while since I last submitted a recipe; might there be something that's changed behind-the-scenes that necessitates action on my side?

**Comment by jakirkham** [comment]
Please restore the merged recipes pending conversion that were deleted. The CIs/linter will ignore these automatically in your PR.

xref: https://github.com/conda-forge/staged-recipes#11-why-are-there-recipes-already-in-the-recipes-directory-should-i-do-something-about-it

**Comment by ericmjl** [comment]
Okay, @jakirkham! I'm going to start over. (still a git noob, even after this time...)

**Comment by jakirkham** [comment]
No worries. Part of the reason we made the aforementioned changes was to simplify the amount of effort that went into making a contribution.

**Comment by jakirkham** [comment]
Continued in PR ( https://github.com/conda-forge/staged-recipes/pull/1705 ).

**Pull request closed without merging**
