### PR TITLE
✨ Add Saxon-HE

### PR DESCRIPTION
**Pull request by munechika-koyo**
This commit adds the build scripts and recipe for Saxon-HE, an open-source SAXON XSLT processor developed by Saxonica Limited. The build scripts include a `build.bat` file for Windows and a `build.sh` file for Unix-based systems. The recipe.yaml file specifies the version, source URL, and dependencies for the package. Additionally, the commit includes activation and deactivation scripts for the package.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by munechika-koyo** [comment]
I would like @conda-forge/staged-recipes to review this PR.

**Comment by munechika-koyo** [comment]
@conda-forge/core Please review and push this PR.

**Comment by munechika-koyo** [comment]
@conda-forge/help-java

**Comment by munechika-koyo** [comment]
@ocefpaf Thank you for your response.
This recipe does not contain building a Java program but relocating built distribution into the conda-prefix directory.
Even though it is, we need more volunteers to deal with stacked PR recipes anyway...

**Comment by xhochy** [comment]
Things that seem off here:

1. We don't build from source here. We should do so to get a list of third-party libraries.
2. We don't install into normal directory structures but put everything into a "SaxonHE/" subtree. 
3. The activation scripts add to `LD_LIBRARY_PATH`. They should not be doing that but rather place the libs into the right folder, but I don't see any native libs at all here.

**Comment by munechika-koyo** [comment]
> 1. We don't build from source here. We should do so to get a list of third-party libraries.

Built distribution is easy to package, so I used it as a source. But I also think it is preferable to build from a source.
I will have to learn about how to do it.


> 2. We don't install into normal directory structures but put everything into a "SaxonHE/" subtree.

I use this configuration referencing the [`openjdk`](https://github.com/conda-forge/openjdk-feedstock) conda package, where everything is put into a `/lib/jvm/` directory.
If you have any other solution, I'd be glad to hear them.

> 3. The activation scripts add to `LD_LIBRARY_PATH`. They should not be doing that but rather place the libs into the right folder, but I don't see any native libs at all here.

Actually, at `SaxonHE/lib/`, there is no shared library, only `.jar` files.
I understand in order for Java to find the Java library, `CLASSPATH` has to be set.
However, I don't know if `LD_LIBRARY_PATH` should be configured.
Should we set `JAVA_LD_LIBRARY_PATH` like `openjdk`'s activation scripts?

**Comment by xhochy** [comment]
> Should we set JAVA_LD_LIBRARY_PATH like openjdk's activation scripts?

I don't think anything should be set here.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
