### PR TITLE
Adding Bmad recipe.

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

This recipe depends on https://github.com/conda-forge/staged-recipes/pull/14212 and it will fail while `lapack95` is not available.

### CODE REVIEW

**Comment by ChristopherMayes** [comment]
@hhslepicka I agree to be a maintainer

**Comment by hhslepicka** [comment]
Closing and reopen to trigger CI.

**Comment by hhslepicka** [comment]
Closed/Reopened to kick CI

**Comment by hhslepicka** [comment]
@conda-forge/staged-recipes this one is good for a review.

A thing that may look weird while you review it:
- The URL here points to a GitHub repo (https://github.com/bmad-sim/bmad_distribution). This is an official mirror of the Bmad package releases from the Cornell website to GitHub.
- hdf5 has a minimum version since from that release onwards the Fortran shared libraries are also provided for MacOS.
- gsl is pinned due to Bmad needs.
- The patch used here will eventually be worked with maintainers of the package to be merged upstream.

Thank you!

**Comment by hhslepicka** [comment]
For License information:
```bash
$ cat bmad/Copyright
Bmad is released under the GNU General Pubilc License Version 3 (<http://www.gnu.org/licenses/>).

					-- David Sagan, 2012
```

**Comment by hhslepicka** [comment]
@ocefpaf thank you for the review and merge! 🚀

**Pull request merged**
