### PR TITLE
Add jupyterlab-spreadsheet-editor

### PR DESCRIPTION
**Pull request by maresb**
JupyterLab plugin recipe generated via Grayskull

Note: there are vendored icons:

https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor/tree/main/style/icons

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by maresb** [comment]
@krassowski requests maintainer in https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor/issues/58#issuecomment-1455708727

**Comment by maresb** [comment]
@drhagen, would you be willing to be maintainer for this feedstock? The job is mainly to look over the automated PRs and merge if everything's in order.

**Comment by maresb** [comment]
It looks like this is failing to solve. The pins look rather odd.

**Comment by drhagen** [comment]
Yes, I am willing to be a maintainer of this feedstock.

**Comment by maresb** [comment]
I @drhagen and @krassowski, for convenience I invited you to my staged-recipes fork so that you can make commits here if you want.

**Comment by maresb** [comment]
But also feel free to start your own fork.

**Comment by drhagen** [comment]
It looks like greyskull makes `jupyter_packaging` version 0.7.* a build requirement. But only version 0.12.* is on conda-forge. Is that the reason for the build failure?

**Comment by maresb** [comment]
@drhagen, indeed, nicely spotted.

I think Grayskull is picking up these version numbers from [pyproject.toml](https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor/blob/main/pyproject.toml). @krassowski, perhaps these should be updated?

Since they aren't runtime dependencies, we can try fudging them ourselves. (Relaxing runtime dependencies is more serious, because then users could wind up with incompatible versions, and also `pip check` could fail on this and downstream feedstocks.) I'll remove the upper pin to see if that improves the situation...

**Pull request merged**
