### PR TITLE
Add recipe for handy-archives

### PR DESCRIPTION
**Pull request by domdfcoding**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by domdfcoding** [comment]
@conda-forge/help-python not sure what's up with the osx tests. Seems to be an issue with Python rather than with the recipe. I found https://bugs.python.org/issue46691 which might be related.

**Comment by timsnyder** [comment]
I'm taking a look at why the osx install is failing.

**Comment by timsnyder** [comment]
So, it's definitely a conflict between what `pip` thinks it should be doing (looking at `CFLAGS` for an `-arch` flag but since conda-forge doesn't set `-arch` in `CFLAGS`.  I'm not super familiar with `pyproject.toml` and what pip is doing with it to end up here.

Looking at what you have in handy-archives, it seems like it is pure python that doesn't need to be packaged differently for the different platforms and that you should just make it a `noarch: Python` package as described in https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python

I know that doesn't really answer your question about why the osx_64 build is going astray but it will definitely avoid the issue and just use pip to package it on Linux and use it everywhere.

**Comment by domdfcoding** [comment]
Thanks for taking a look at this. I had already set the recipe as noarch (see line 13 of the recipe; I assume I've done it correctly.) Do the CI jobs in this repo actually take that into account, or is it running the osx job regardless?

Can this PR be merged despite the failing check, if that's allowed?

**Comment by timsnyder** [comment]
@conda-forge-admin, please rerender.

**Comment by timsnyder** [comment]
I guess rerendering doesn't make sense here and it will render the ci correctly once this is merged.  Wolf V confirmed in the gitter that you can ignore the osx failure.  Now you just need to get a memeber of staged-recipes to review and merge.  Sorry I can't help you with that.

**Comment by isuruf** [comment]
https://github.com/python/cpython/blob/main/Lib/_osx_support.py#L532 gets triggered because there's a `-isystem $PREFIX/include` and `$PREFIX` includes `handy-archives` which in turn has `-arch` in it. :facepalm:

**Comment by timsnyder** [comment]
ugh.  Yikes.  Seems like that should be a PR to cpython.  Thanks for looking at that @isuruf .

**Comment by isuruf** [comment]
https://bugs.python.org/issue47154

**Comment by domdfcoding** [comment]
@conda-forge-admin, please ping team

**Comment by domdfcoding** [comment]
Thanks :)

**Pull request merged**
