### PR TITLE
Don't build the example recipe

### LINKED ISSUE #113: We don't need to build example
Each time a PR is submitted, example is built. We really don't need to do that.
We could just remove the recipe before conda-build-all in the CI scripts (e.g. https://github.com/conda-forge/staged-recipes/blob/master/appveyor.yml#L72).

### PR DESCRIPTION
**Pull request by ocefpaf**
Fixes #113

### CODE REVIEW

**Comment by ocefpaf** [comment]
The conda-forge-bot did not clean the master branch yet.  Hold off the merge for a while.

**Comment by jakirkham** [comment]
+1

**Comment by pelson** [comment]
Thanks @ocefpaf. Wow - the AppVeyor queue is pretty large :worried: !

**Comment by ocefpaf** [comment]
> Wow - the AppVeyor queue is pretty large :worried: !

We should start committing non-win recipes with the message `[skip appveyor]`. Also, maybe https://github.com/conda-forge/conda-forge.github.io/issues/45 might help reduce the queue.

**Comment by jakirkham** [comment]
Many of them are dups from old commits that have been pushed forced away. Probably can just be terminated.

**Comment by jakirkham** [comment]
Good point. I should have done that with mine that were non-Windows. Sorry.

**Comment by ocefpaf** [comment]
> Many of them are dups from old commits that have been pushed forced away. Probably can just be terminated.

I will try to kill a few.  If I terminate an important one please ping me back so I can re-start it.

**Comment by jjhelmus** [comment]
Could we buy some additional concurrent jobs for conda-forge on AppVeyor?  Looks like each additional job is $50/month and perhaps 50% off for open-source projects.  We could see if NumFOCUS would sponsor something like this

**Comment by jakirkham** [comment]
Definitely like that idea. Don't want this becoming a bottleneck.

Also we could try to speed up builds with skip Windows so if someone forgets to disable the commit (like myself, sorry), it won't be too much of a wait.

**Comment by pelson** [comment]
> Many of them are dups from old commits that have been pushed forced away. Probably can just be terminated.

I've proposed https://github.com/conda-forge/staged-recipes/pull/123 which will make this an awful lot smoother.

The concurrent AppVeyor option is certainly one we can pursue - shall we hold fire until we see how well we can tune it first?

**Pull request merged**
