### PR TITLE
added arcsi recipe

### PR DESCRIPTION
**Pull request by gillins**
See http://rsgislib.org/arcsi/

### CODE REVIEW

**Comment by gillins** [comment]
@ocefpaf do you have any idea why the OSX packages for `rsgislib` are missing?

**Comment by ocefpaf** [comment]
> @ocefpaf do you have any idea why the OSX packages for `rsgislib` are missing?

Sorry I missed your message earlier. I just checked and the CIs errored. I re-started them... Fingers crossed.

https://travis-ci.org/conda-forge/rsgislib-feedstock

**Comment by gillins** [comment]
That's done it! Thanks @ocefpaf :champagne:

**Comment by gillins** [comment]
@ocefpaf do you have any idea why a different `numpy` (defaults vs conda-forge) and `gsl` (openblas vs not) in the `rsgislib` build (https://travis-ci.org/conda-forge/rsgislib-feedstock) vs the `arcsi` build (https://travis-ci.org/conda-forge/staged-recipes/builds/248738871) on OSX? This seems to be causing the build failure.

I think I've seen something like this on Windows.

No stress if not, I'll have a dig during the week.

**Comment by ocefpaf** [comment]
I don't know why the numpy from `deafults` is selected when we try to install `gsl` alongside `numpy`. We do have a higher build number of `gsl` compiled with `openblas`, maybe that is the source of all the problems here.

Did you try to workaround by specifying `openblas` as a runtime dependency for `arcsi`? Even if that works we need a better solution for this...

**Comment by isuruf** [comment]
It seems the conda solver prefers to use the non openblas build. Maybe we should remove the non openblas from anaconda.org. After that `rsgislib` has to be built with openblas.

**Comment by ocefpaf** [comment]
> It seems the conda solver prefers to use the non openblas build. Maybe we should remove the non openblas from anaconda.org. After that `rsgislib` has to be built with openblas.

Maybe that is the a better solution for now. I will give it a shot by putting the non-openblas `gsl` in a "broken" channel.

**Comment by gillins** [comment]
Thanks @ocefpaf, I'm just doing some testing on Linux and I think you have missed one file when you were marking them as "broken": `https://anaconda.org/conda-forge/gsl/2.2.1/download/linux-64/gsl-2.2.1-0.tar.bz2`. The solver is still grabbing this one rather than the openblas one...

Thanks for looking into this.

**Comment by ocefpaf** [comment]
>  I think you have missed one file 

Sorry about that. I just removed it.

**Comment by gillins** [comment]
Thanks @ocefpaf - all good now. I think this one is ready to go...

**Pull request merged**
