### PR TITLE
ENH check for core too

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Review by carterbox — COMMENTED** [review]
This PR adds core team members to the list of accounts allowed to dismiss review-requested tags. Implementation makes sense. Thanks for your time!

**Comment by carterbox** [comment]
So actually, this doesn't work when the person is not in the core team.

https://github.com/conda-forge/staged-recipes/actions/runs/2484529299

**Comment by carterbox** [comment]
I suspect it is because the async handling of one response is inside the other. Instead the result checking should be flat. Or they should be checked together instead of nested. If the result is not checked but returns an error state, then the error probably bubbles up and that is the cause of the error above.

i.e. Because I am a member of staged recipes, but not core the 404 error from core membership is not handled before the function tries to return.

**Comment by beckermr** [comment]
Weird. I added a handler to both. I'll back out the changes in a bit.  Sorry for the trouble.

**Comment by carterbox** [comment]
I tried some things too, but they didn't work. Maybe we should debug this issue over on the test repo. We just need to figure out how to catch those 404s while having multiple team checks.

**Comment by beckermr** [comment]
Sure. I don't mind debugging live in staged recipes personally.

**Pull request merged**
