### PR TITLE
Add recipe for r-basix

### PR DESCRIPTION
**Pull request by npavlovikj**
Add recipe for r-basix

### CODE REVIEW

**Comment by npavlovikj** [comment]
@johanneskoester , @bgruening , @daler , @jdblischak , @cbrueffer , @dbast , I used "conda_r_skeleton_helper" for this recipe, which is a dependency for another bioconda recipe I am working on. Therefore, I would appreciate if you can review it and/or merge it.

**Comment by jdblischak** [comment]
This package doesn't have any missing R 3.5.1 dependencies, so I think it's good to merge.

**Comment by npavlovikj** [comment]
Thank for the review and merge @jdblischak !

**Comment by jdblischak** [comment]
@npavlovikj No problem. Thanks for the contribution! Though FYI the staged-recipes repo is currently failing, so it may be some time before your feedstock gets created and the binary uploaded to Anaconda Cloud.

**Comment by npavlovikj** [comment]
Hi @jdblischak , is there any update on when the recipe can be available?

**Comment by cbrueffer** [comment]
Hi @npavlovikj , unfortunately the conversion of staged recipes to feedstocks is broken at the moment, you can follow the issue here: https://github.com/conda-forge/staged-recipes/issues/6659

**Comment by npavlovikj** [comment]
Thanks for the info and the issue thread @cbrueffer - I hope things will be back to normal soon.

**Comment by jdblischak** [comment]
@npavlovikj Looks like the issue has been resolved:

https://github.com/conda-forge/r-basix-feedstock
https://anaconda.org/conda-forge/r-basix/files

In the future, if you need a conda package quick, you can always build and upload a given package to your own Anaconda Cloud channel. This is what I tend to do in practice when I need a conda package right away.

**Pull request merged**
