### PR TITLE
Initial packaging of Spotipy2

### PR DESCRIPTION
**Pull request by captivus**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by captivus** [comment]
@conda-forge/help-python, ready for review!

**Comment by captivus** [comment]
@conda-forge/staged-recipes ready for review!

**Comment by captivus** [comment]
@isuruf hello!  These checks were all successful yesterday.  It seems like almost all of the PRs for this repo since #19416 have failed, so is it safe to assume that something is being worked on elsewhere and I should wait?  Please advise -- thanks!

**Comment by isuruf** [comment]
No, the CI was broken yesterday and falsely gave a green signal. This is an issue with this package.

See the error log

```
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/staged-recipes/build_artifacts/spotipy2_1656278253297/work/setup.py", line 6, in <module>
      with open("requirements.txt", encoding="utf-8") as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by captivus** [comment]
@conda-forge/staged-recipes once again ready for review!

**Pull request merged**
