### PR TITLE
Add siphash24

### PR DESCRIPTION
**Pull request by inducer**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by inducer** [comment]
@matthiasdiener Could you confirm you'd like to co-maintain this?

**Comment by matthiasdiener** [comment]
> @matthiasdiener Could you confirm you'd like to co-maintain this?

Sure, that sounds good!

**Comment by matthiasdiener** [comment]
here is a suggestion for the recipe:

```diff
diff --git a/recipes/siphash24/meta.yaml b/recipes/siphash24/meta.yaml
index 053612224a..d69fa93183 100644
--- a/recipes/siphash24/meta.yaml
+++ b/recipes/siphash24/meta.yaml
@@ -10,19 +10,27 @@ source:
   sha256: 242d6901a81260f618938635a25ae7f208e744f7ee6c571f1b255c1c4c62917d

 build:
-  noarch: python
   script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
   number: 0
+  skip: true  # [win]

 requirements:
+  build:
+    - python                                 # [build_platform != target_platform]
+    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
+    - {{ compiler('c') }}
+    - {{ stdlib('c')}}
+    - meson >=1.0.0                          # [build_platform != target_platform]
+    - cython >=3.0.2                         # [build_platform != target_platform]
+    - meson-python >=0.14.0                  # [build_platform != target_platform]
   host:
-    - python >=3.7
+    - python
     - cython >=3.0.2
     - meson >=1.0.0
     - meson-python >=0.14.0
     - pip
   run:
-    - python >=3.7
+    - python
```

**Comment by inducer** [comment]
@conda-forge-admin please restart ci

**Comment by matthiasdiener** [comment]
Until https://github.com/conda-forge/status/issues/181 is resolved, CI wir be able to run I think.

**Comment by inducer** [comment]
@conda-forge/help-python I think this is ready for a look.

**Comment by dnicolodi** [comment]
Hello. `sipahash24` maintainer here. If I can be added as maintainer of the conda-forge recipe I can try to keep it updated for future releases of `siphash24`. I don't have experience in maintaining conda-force recipes, but from what I see in this PR it does not seem to be rocket science :)

**Comment by inducer** [comment]
Thanks again! https://github.com/conda-forge/siphash24-feedstock/pull/4 should add you.

Also sorry again about the multiple different attempts at doing this.

**Comment by dnicolodi** [comment]
Thanks and no worries. conda-forge uses a level of automation I'm not used to 🙂

**Pull request merged**
