### PR TITLE
Fortran Jupyter Kernel

### PR DESCRIPTION
**Pull request by certik**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by certik** [comment]
The macOS failure is a bug that I need to fix upstream first.

**Comment by certik** [comment]
It almost works everywhere now.  The kernel does not install on Windows properly, but otherwise it seems to work.

**Comment by certik** [comment]
This is ready for review. All tests pass on Linux, macOS and Windows.

**Comment by certik** [comment]
Here is the contents of the binary package:
```
miniconda3/pkgs/fortran_kernel-0.1.7-py37_0/
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── has_prefix
│   ├── index.json
│   ├── licenses
│   │   └── LICENSE
│   ├── paths.json
│   ├── recipe
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   ├── meta.yaml.template
│   │   └── win.patch
│   ├── repodata_record.json
│   └── test
│       ├── run_test.py
│       ├── run_test.sh
│       └── test_time_dependencies.json
├── lib
│   └── python3.7
│       └── site-packages
│           ├── fortran_kernel
│           │   ├── __init__.py
│           │   ├── install.py
│           │   ├── kernel.py
│           │   ├── __main__.py
│           │   ├── __pycache__
│           │   │   ├── __init__.cpython-37.pyc
│           │   │   ├── install.cpython-37.pyc
│           │   │   ├── kernel.cpython-37.pyc
│           │   │   ├── __main__.cpython-37.pyc
│           │   │   └── utils.cpython-37.pyc
│           │   ├── tests
│           │   │   ├── __init__.py
│           │   │   ├── __pycache__
│           │   │   │   ├── __init__.cpython-37.pyc
│           │   │   │   └── test_fortran_kernel.cpython-37.pyc
│           │   │   └── test_fortran_kernel.py
│           │   └── utils.py
│           └── fortran_kernel-1.0.dist-info
│               ├── INSTALLER
│               ├── LICENSE
│               ├── METADATA
│               ├── RECORD
│               ├── top_level.txt
│               └── WHEEL
└── share
    └── jupyter
        └── kernels
            └── fortran
                └── kernel.json

16 directories, 37 files
```

**Comment by certik** [comment]
I squashed the commits into just one.

**Comment by wolfv** [comment]
Nice!

**Comment by certik** [comment]
Thanks @isuruf. I tested on Linux and macOS and it works great: @wolfv the kernel automatically registers, the way it works is that the `fortran_kernel` package ships the file `share/jupyter/kernels/fortran/kernel.json`, and that's enough to register the kernel simply by installing the package. I was consulting `xeus-cling`'s package how to do this. ;)

It will take a few months, but once things are in C++, I'll use `xeus` for the kernel.

**Pull request merged**
