### PR TITLE
add r-concaveman

### PR DESCRIPTION
**Pull request by ocefpaf**
Needed for https://github.com/conda-forge/r-lidr-feedstock/pull/4

### CODE REVIEW

**Comment by ocefpaf** [comment]
We need to package `v8` at some point. I do recall trying to package it some time ago but got stuck.

**Comment by xhochy** [comment]
@ocefpaf `r-v8` was merged, so you might want to try to resubmit this.

**Comment by ocefpaf** [comment]
Thanks! I probably won't have time to do it anytime soon though.

**Comment by dbast** [comment]
Opened https://github.com/conda-forge/staged-recipes/pull/8936

**Pull request closed without merging**
