### PR TITLE
Add maite recipe

### PR DESCRIPTION
**Pull request by myeesw**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdarena66** [comment]
I am willing to be listed

**Comment by leihamilton** [comment]
I am willing to be listed as maitainers.

**Comment by zklaus** [comment]
Since this is a `noarch: python` package, it's no problem that it cannot be built on Windows, particularly since it is due to a missing dependency. Once converted to a feedstock, the package will only be built in Linux.

**Comment by kcpevey** [comment]
@conda-forge-admin, please lint

**Comment by kcpevey** [comment]
From @zklaus :

You can ignore the ci failure. Whether the package will work on Windows or not does not depend on the ci build here. Once the PR is merged, the recipe will be converted to a feedstock. At that point, it will be noted that it is a `noarch` and the package will be built only on Linux and then uploaded to the `noarch` subdir. All installations, regardless of the users platform, will download this (Linux-built, but universal) package. If all dependencies are available for the platform, it will work. If not, it cannot be installed.

That is to say you can proceed with merging this as-is. @myeesw can you tick the checkboxes in the PR description here and once those are complete, add a comment to the recipe requesting review by posting this: `@conda-forge/help-python this is ready for review` (I'm hoping that doesn't get picked up by CI :) )

**Pull request merged**
