### PR TITLE
Use conda-build 2 for feedstock creation for now

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/staged-recipes/issues/5660

As `conda-smithy` 3 has not yet been released, we are unable to use `conda-build` 3 in feedstock conversion. For now, revert this portion of the changes in `staged-recipes` until `conda-smithy` 3 is released.

cc @isuruf

xref: https://github.com/conda-forge/staged-recipes/pull/5274/files#r180809475

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by msarahan** [comment]
What is blocking conda-smithy 3?  I don't see anything on the issue tracker there.  I know of 2 things blocking overall migration (CB 3.8.1 release, conda-forge-pinning release with vc behind win selectors), but nothing blocking conda-smithy 3's release, and thus no reason for this change.

**Comment by jakirkham** [comment]
Independently thought we were trying to rebuild [these packages]( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/27 ) first. Or is that not needed?

**Comment by msarahan** [comment]
I know that's true for overall migration, but I don't know if it's true for releasing conda-smithy 3.  At worst, some builds may exhibit duplicate jobs because of the issue pointed out by @isuruf in https://github.com/conda-forge/geos-feedstock/pull/28#issuecomment-381355846

**Comment by ocefpaf** [comment]
Let us talk about this tomorrow during the meeting. Please do not merge this until then.

**Comment by jakirkham** [comment]
So the tradeoff is users get anxious about having their recipes converted in the interim. That said, I have no problem settling this out of band tomorrow.

Personally I'm not sure if I'll make it to that meeting, but am ok with either of these two options as long as people are aware of the pros/cons of each.

**Comment by jakirkham** [comment]
`conda-smithy` 3.0.0 is released. ( https://github.com/conda-forge/conda-smithy-feedstock/pull/91 ) So this is no longer necessary. Triggered [a `master` build for conversion]( https://travis-ci.org/conda-forge/staged-recipes/builds/367840351 ).

**Pull request closed without merging**
