### PR TITLE
next batch of ros recipes

### PR DESCRIPTION
**Pull request by wolfv**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vend other packages
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by wolfv** [comment]
@seanyen just FYI this is probably going to be the first batch of ROS recipes. they're all pretty low level and have few dependencies. 

Naming scheme is `ros-...`, and underscores are turned to dashes, e.g. `ros-genmsg` but `ros-environment` (I removed the double `ros-` there).

These recipes are generated from the superflore script I shared with you. 

One thing I need to figure out is why OS X fails. It might be that the conda-ROS-catkin activation does something bad to the `DYLD_LIBRARY_PATH` path so that the sqlite3 symbols are not found anymore.

I'll probably not have much time to work on this until the middle of next week -- if you let me know what to do for catkin so that it works on Windows then I am more than happy to also activate Windows for these recipes :) Also, let me know if you want to be a maintainer then I add you to the list!

**Comment by seanyen** [comment]
And one quick question, how does the feedstock accommodate potentially different distro (melodic, eloquent...) being released in the future?

**Comment by wolfv** [comment]
Hi @seanyen, unfortunately the recipes will all get split up into their own feedstocks. The main consideration is that it's possible to use "more" CI time if all packages are split up. I agree though, that, especially for the case of ROS packages it would be nice to have multiple or all packages grouped in one feedstock.
Probably we need to figure out some scripts to handle distro upgrades for all the different feedstock repos.

The feedstocks could accomodate different distros by pushing to a different branch in the feedstock (which will also trigger the build of a new package of e.g. a different distro).
Furthermore, we also have the ros mutex package which should make sure that only packages of one distro are installed (https://github.com/conda-forge/ros-conda-mutex-feedstock/blob/master/recipe/meta.yaml)

**Comment by wolfv** [comment]
@seanyen do you also want to be a co-maintainer of these?

**Comment by seanyen** [comment]
> @seanyen do you also want to be a co-maintainer of these?

Sure.

**Pull request merged**
