### PR TITLE
Added friendly as a package.

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Need to add some X11 lib to `yum_requirements.txt`.

**Comment by thewchan** [comment]
> Need to add some X11 lib to `yum_requirements.txt`.

@dopplershift never had to deal with that before... anywhere I can read up on this?

**Comment by thewchan** [comment]
@dopplershift I'm reading this https://conda-forge.org/docs/maintainer/knowledge_base.html#yum-deps

Should I use yum or something on CDT?

**Comment by thewchan** [comment]
> Looks like `pip check` is failing due to bad versions in `stack-data` and `pure-eval`. It looks like that's because the recipes for those packages are missing a build dependency on `setputools_scm`. Would you be willing to open PRs on those recipes to fix that?

At the feedstocks? Yes I can do that.

**Review by Anthchirp — APPROVED** [review]
This looks fine to me, and I've retriggered the build, but the new package versions haven't made it through migration yet. I'll retrigger it again later and see if that clears up the test errors.

**Comment by thewchan** [comment]
@conda-forge-admin, please restart ci

**Comment by alexmojaki** [comment]
Shameless plug for https://futurecoder.io/ which uses friendly_traceback :smile: 

If you ever want to show someone the explanations given by friendly_traceback, https://futurecoder.io/course/#ide is probably the fastest way.

**Pull request merged**
