### PR TITLE
WIP: package torchaudio

### PR DESCRIPTION
**Pull request by h-vetinari**
Necessary for #14474, #17129

* [ ] figure out `RuntimeError: No such operator torchaudio::rnnt_loss`
* [ ] figure out segfaults on linux
* [ ] figure out test failures regarding libarosa
* [ ] package https://github.com/as-ideas/DeepPhonemizer
* [ ] Fix https://github.com/conda-forge/kaldi_io-feedstock/issues/1
* [ ] rebuild sox with patches mentioned [upstream](https://github.com/pytorch/audio/issues/1269#issuecomment-1188423233), see https://github.com/conda-forge/sox-feedstock/pull/27

### CODE REVIEW

**Comment by h-vetinari** [comment]
Not stale

**Comment by thewchan** [comment]
@h-vetinari hey another package I'm maintaining is requiring torchaudio now for dependency... You seem to know a lot more about what's going on with this package, do you feel optimistic about this PR?

**Comment by h-vetinari** [comment]
> @h-vetinari hey another package I'm maintaining is requiring torchaudio now for dependency... You seem to know a lot more about what's going on with this package, do you feel optimistic about this PR?

Hey @thewchan, very sorry for the delay, I had to look for a flat and then move, could not respond to everything in time. I want to revive this PR, especially not that the unix-y parts of kaldi should be solved, we should be able to progress. :)

**Comment by thewchan** [comment]
@h-vetinari thanks very exciting to hear!

**Comment by h-vetinari** [comment]
@conda-forge/pytorch-cpu 

I'm having trouble building against pytorch 1.10 here.
```
  ERROR (torchaudio,lib/python3.7/site-packages/torchaudio/_torchaudio.so): $RPATH/libtorch_cpu.so not found in packages, sysroot(s) nor the missing_dso_whitelist.
  ERROR (torchaudio,lib/python3.7/site-packages/torchaudio/_torchaudio.so): $RPATH/libtorch_cuda.so not found in packages, sysroot(s) nor the missing_dso_whitelist.
  ERROR (torchaudio,lib/python3.7/site-packages/torchaudio/lib/libtorchaudio.so): $RPATH/libtorch_cpu.so not found in packages, sysroot(s) nor the missing_dso_whitelist.
  ERROR (torchaudio,lib/python3.7/site-packages/torchaudio/lib/libtorchaudio.so): $RPATH/libtorch_cuda.so not found in packages, sysroot(s) nor the missing_dso_whitelist.
  ERROR (torchaudio,lib/python3.7/site-packages/torchaudio/lib/libtorchaudio.so): $RPATH/libc10.so not found in packages, sysroot(s) nor the missing_dso_whitelist.

```

The libs as packaged by pytorch [are](https://github.com/regro/libcfgraph/blob/master/artifacts/pytorch/conda-forge/linux-64/pytorch-1.10.2-cuda112py39h4de5995_1.json#L3106-L3116) not under `/lib` but

```
  "lib/python3.9/site-packages/torch/lib/libc10.so",
  "lib/python3.9/site-packages/torch/lib/libc10_cuda.so",
  "lib/python3.9/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so",
  "lib/python3.9/site-packages/torch/lib/libcaffe2_nvrtc.so",
  "lib/python3.9/site-packages/torch/lib/libcaffe2_observers.so",
  "lib/python3.9/site-packages/torch/lib/libshm.so",
  "lib/python3.9/site-packages/torch/lib/libtorch.so",
  "lib/python3.9/site-packages/torch/lib/libtorch_cpu.so",
  "lib/python3.9/site-packages/torch/lib/libtorch_cuda.so",
  "lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so",
  "lib/python3.9/site-packages/torch/lib/libtorch_python.so",
```

I guess this makes sense since it's possibly dependent on the python version, but I don't get why conda is not finding those libs (as the run requirement replicates the host requirement).

PS. This has nothing to do with old builds, the situation is the [same](https://github.com/regro/libcfgraph/blob/master/artifacts/pytorch/conda-forge/linux-64/pytorch-1.12.0-cuda112py39ha0cca9b_200.json#L9448-L9457) for 1.12 though. I'm just avoiding the global pinning because torchaudio 0.10 needs pytorch 1.10, and I don't yet want to upgrade the version here because the upstream build only gains more complicated integrations, it seems.

**Comment by hmaarrfk** [comment]
Basically, i would need to unbundle the library and move it to the lib location. I've been working through pttorch unbundling, but i don't know if I have a good near term solution.

People have been adding them to the missing dso whitelist

**Comment by hmaarrfk** [comment]
> > Basically, i would need to unbundle the library and move it to the lib location. I've been working through pytorch unbundling, but i don't know if I have a good near term solution.
> 
> This might be a naïve question, but shouldn't something like
> 
> ```
> mv $SP_DIR/torch/lib/*.so $PREFIX/lib/
> ```
> 
> at the end of the build script suffice?

To e honest, I'm not interested in doing such hacks.

I'm pretty close with: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/112

to build things out from a C library, then a python library.

Somebody needs to go through the effort of building the python-only part. (and likely refreshing for the latest release).

Presently, I feel like users should voice their opinions to pytorch, so that they know that building on-top of pytorch is an important thing, and that they care about using both the C library, and the pytorch library in a sane manner.

**Comment by h-vetinari** [comment]
> Basically, i would need to unbundle the library and move it to the lib location. I've been working through pttorch unbundling, but i don't know if I have a good near term solution.
> 
> People have been adding them to the missing dso whitelist




> Presently, I feel like users should voice their opinions to pytorch, so that they know that building on-top of pytorch is an important thing, and that they care about using both the C library, and the pytorch library in a sane manner.

Agreed

> To be honest, I'm not interested in doing such hacks.

I have to say - as far as hacks go, this would IMO be really contained & effective (while we work/wait to convince upstream to make the libs first-class citizens, which might take a while). It's one line, no patching, and has a crystal-clear purpose/effect. I'd say it's _less bad_ of a hack than having to play around with `missing_dso_whitelist` in all feedstocks that need the libs.

> I'm pretty close with: [conda-forge/pytorch-cpu-feedstock#112](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/112) to build things out from a C library, then a python library.
> 
> Somebody needs to go through the effort of building the python-only part. (and likely refreshing for the latest release).
> 

That's cool, though it looks way too involved IMO that someone (well, speaking only for myself) could reasonably take this over, rebase it, etc.

Personally I think that on balance, we should move the libs with the next build, and work on more comprehensive strategies mid- to longterm.

**Comment by hmaarrfk** [comment]
> Personally I think that on balance, we should move the libs with the next build, and work on more comprehensive strategies mid- to longterm.

hasn't the missing dso-whitelist been working ok? Maybe we can create a sticky issue with the best-practices for creating conda-packages with pytorch as a dependency?

**Comment by h-vetinari** [comment]
> hasn't the missing dso-whitelist been working ok?

It took me 3-4 tries to get it right (much less knowing who to ask and getting the right pointers from you), but more than that, we're spreading the hack from one feedstock (the origin) to N of them (the consuming ones).

On top of that, searching for `missing_dso_list` in conda-forge yields lots of `- "*"` (granted, sometimes deep in the bowels of our infra packages), which we should really not encourage people to emulate.

**Comment by hmaarrfk** [comment]
I think i would be more OK with the alternative, of patching out the calls that move files into the python package in the first place. 

I'm just very weary of moving so files around. So if they never appear in the problematic directories, I think that is better for me.

It seems that the moving is done in the setup.py but I haven't investigated too much
https://github.com/pytorch/pytorch/blob/master/setup.py#L1000=

**Comment by h-vetinari** [comment]
@thewchan 
I just opened https://github.com/conda-forge/kaldi_io-feedstock/issues/1 because kaldi_io is an optional test dep for torchaudio. Looking at the upstream code though, this is definitely not ready for out-of-the-box use. Would you want to give it a go to fix it (since you maintain that feedstock)?

**Comment by h-vetinari** [comment]
> I think i would be more OK with the alternative, of patching out the calls that move files into the python package in the first place.

Fair enough, I can understand that.

> It seems that the moving is done in the setup.py but I haven't investigated too much
> https://github.com/pytorch/pytorch/blob/master/setup.py#L1000

The problem is that just removing them from `package_data` would mean they don't get installed at all anymore. We'd most likely need to shift the installation of the libs/headers to the CMakeLists.txt.

**Comment by h-vetinari** [comment]
Sidenote @hmaarrfk, would you mind merging https://github.com/conda-forge/parameterized-feedstock/pull/12? For some reason that package cannot be resolved here anymore; the PR is a trivial rerender, which I hope should fix it.

**Comment by hmaarrfk** [comment]
> The problem is that just removing them from package_data would mean they don't get installed at all anymore. We'd most likely need to shift the installation of the libs/headers to the CMakeLists.txt.

To my knowledge, this is already done since I did manage to get it going in my "c-library" package.

**Comment by mthrok** [comment]
FYI: We cleaned up the third party dependencies on torchaudio nightly.

- No longer statically bind libsox. So sox from conda-forge works as-is.
- libsox integration is built by compiling stub library. This means torchaudio with libsox built can be built without libsox installed in the environment.
- FFmpeg integration is built using pre-compiled FFmpeg binaries as scaffolding.
- C++ bindings to flashlight-text and Kaldi were removed. The build process has been simplified a lot.

**Comment by h-vetinari** [comment]
Hey @mthrok, thanks a lot, that's amazing news! 🤩 

I'll try again as soon as there's a new release!

**Comment by mmcauliffe** [comment]
@h-vetinari looks like the dependency changes are released in 2.1: https://github.com/pytorch/audio/releases/tag/v2.1.0

**Comment by hadim** [comment]
FYI: I opened a new PR at https://github.com/conda-forge/staged-recipes/pull/27715

**Comment by h-vetinari** [comment]
Superseded by https://github.com/conda-forge/staged-recipes/pull/27715

**Pull request closed without merging**
