### PR TITLE
Add MRChem package

### PR DESCRIPTION
**Pull request by robertodr**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by bjorgve** [comment]
Awesome!

**Comment by robertodr** [comment]
@conda-forge/help-python-c This is ready for review, but please hold off merging: there will be a new official version of the code tagged very soon (MRChemSoft/mrchem#321) and I will update the recipe to use that.

**Comment by chrisburr** [comment]
I'm going to convert this to a draft until the version is tagged.

**Comment by robertodr** [comment]
> I'm going to convert this to a draft until the version is tagged.

Thanks. Forgot to do it myself :facepalm:

**Comment by robertodr** [comment]
@conda-forge/help-python-c This is ready for review.

**Comment by robertodr** [comment]
Ping @conda-forge/help-c-cpp: this is ready for review.

**Comment by robertodr** [comment]
@conda-forge/staged-recipes this is ready for review

**Comment by ocefpaf** [comment]
LGTM! @chrisburr do you still have any more comments or can we merge this one?

**Comment by robertodr** [comment]
:+1:

**Comment by robertodr** [comment]
@conda-forge/staged-recipes what's the blocker here and how can I help?

**Comment by ocefpaf** [comment]
I was waiting for @chrisburr b/c he was the first reviewer here but it looks likes he is busy. So let's get this in!

**Pull request merged**
