### PR TITLE
added r-dosnow

### PR DESCRIPTION
**Pull request by Tomnl**

### CODE REVIEW

**Comment by Tomnl** [comment]
hi @bgruening 

I have added you and @johanneskoester as maintainers now

**Comment by bgruening** [comment]
Thanks, lets wait for a merge.

**Comment by Tomnl** [comment]
Hi @ocefpaf,

Sorry I am a bit unclear what to do next for this. The [feedstock](https://github.com/conda-forge/r-dosnow-feedstock) was generated but it looks like it fails the CI testing because the package is not available..

**Comment by bgruening** [comment]
@Tomnl I restarted the CI builds, packages will arrive soon. This can happen we normally just need to trigger a restart. Please let us know if this does not solve your problem.

**Comment by ocefpaf** [comment]
The reason why this happened in a race condition in the b/c `r-dsnow` depends on `r-snow`. Usually we warn people to add a single recipe per PR to avoid that but we can "break" the rules for practicality. However, one must keep an eye on the CIs and re-start them accordingly when the dependency is built.

PS: that does not happen with AppVeyor b/c of its single queue, only with CircleCI and Travis-CI.

**Comment by Tomnl** [comment]
Thanks for the quick responses @ocefpaf  and @bgruening.  That make sense then.

In the future, should I always have a single recipe for each package? (unless it was some special case)

**Comment by bgruening** [comment]
@Tomnl yes this is the recommended way. However, if you migrate 100 of packages you might want to make bulk PRs.

**Pull request merged**
