### PR TITLE
add zsh recipe

### PR DESCRIPTION
**Pull request by dougalsutherland**
Try adding zsh, for the cluster I just started using that doesn't have it installed.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
Hmm, it's not loading `pcre`:

```
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
[...]
checking for pcre_compile... no
checking for pcre_study... no
checking for pcre_exec... no
```

Also worrying:
```
checking if we need to ignore ncurses... yes
```

Both of these happening on both Mac and Linux.

**Comment by dougalsutherland** [comment]
`--enable-pcre` fixed the first problem.

I think `need to ignore ncurses` is okay. It comes [from here](https://github.com/zsh-users/zsh/blob/master/configure.ac#L826-L836); it just means we're not using `ncurses` as the terminal library, because we're using `tinfo` instead, which is included in our `ncurses` package. So that should be fine.

**Comment by dougalsutherland** [comment]
Okay, I also tested this locally (on Linux) and it seems to work fine. So: @conda-forge/staged-recipes, ready for review. :)

**Comment by scopatz** [comment]
Thanks @dougalsutherland!

**Pull request merged**
