### PR TITLE
add pypy3.7 recipe based on pypy3.6-feedstock

### PR DESCRIPTION
**Pull request by mattip**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble be please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mattip** [comment]
I left @isuruf but removed @omerbenamram @ohadravid and @ocefpaf from the maintainers. Please comment if that is wrong.

**Comment by ocefpaf** [comment]
> I left @isuruf but removed @omerbenamram @ohadravid and @ocefpaf from the maintainers. Please comment if that is wrong.

I'm fine either way. It is nice to always have a core member in important recipes but you already have Isuru there.

**Comment by isuruf** [comment]
I think we should use `pypy3.6-feedstock` to build both 3.6 and 3.7 simultaneously. The name is a bit unfortunate, but I can live with that.

**Comment by mattip** [comment]
>  think we should use pypy3.6-feedstock to build both 3.6 and 3.7 simultaneously

Is there an example where one feedstock builds from more than one source url?

**Comment by chrisburr** [comment]
Normally situations like this are handled with multiple branches, see python-feedstock for an example.

**Comment by isuruf** [comment]
Done in https://github.com/conda-forge/pypy3.6-feedstock/pull/33

**Pull request closed without merging**
