### PR TITLE
Add scikit-garden

### PR DESCRIPTION
**Pull request by ukaratay**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Looks like the link to the patch is bad?

**Comment by ukaratay** [comment]
@pmlandwehr I think there were changes to the code between the PyPi release and the pull request merges, rendering the patches non working. I will take a diff between the current github repo and the version and add that as a patch for now.

**Comment by CJ-Wright** [comment]
I didn't read through the patch but this otherwise looks good to me.

**Comment by ukaratay** [comment]
@CJ-Wright Patch includes the changes from the package repo. The authors of the package haven't released a new version in a while, and some of the changes are necessary to make it build on windows. See the discussion here: conda-forge/staged-recipes#835

**Pull request merged**
