### PR TITLE
[R4R] Add rb-jekyll to conda-forge

### LINKED ISSUE #5978: package jekyll
Would be great to package https://github.com/jekyll/jekyll, a simple, blog-aware, static site generator perfect for personal, project, or organization sites.

### PR DESCRIPTION
**Pull request by sodre**
Close #5978

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by sodre** [comment]
@conda-forge/staged-recipes, rb-jekyll is ready for review/merge.

**Comment by bgruening** [comment]
Wonderful!

**Comment by quasiben** [comment]
Thank you!  I just came across this and it solved my jekyll install issue!

**Comment by sodre** [comment]
yw!

**Pull request merged**
