### PR TITLE
add verticapy

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by FernandezMathieu** [comment]
@conda-forge-linter restart ci

**Comment by FernandezMathieu** [comment]
@dopplershift Hello, can you tell me what's wrong here ?

**Comment by FernandezMathieu** [comment]
@conda-forge-linter restart ci

**Comment by dopplershift** [comment]
Your problem is that the latest version of `vertica-python` available on conda-forge is 0.10.1 (there are more recent ones available from `defaults`, but we can't use those). The PRs to build updated packages are [open but unmerged](https://github.com/conda-forge/vertica-python-feedstock/pulls)--I'm not sure what's up with the maintainers.

You can try pinging the maintainers in those PRs and also consider adding yourself as a maintainer by making a PR adding yourself to the maintainer list in the recipe in that feedstock repo. If there's no response, you can ping conda-forge/core to merge it.

**Comment by FernandezMathieu** [comment]
@conda-forge-linter restart ci

**Comment by FernandezMathieu** [comment]
@dopplershift we're good here, can you merge ?

**Review by xhochy — APPROVED** [review]

**Pull request merged**
