### PR TITLE
Update conda before adding channel

### PR DESCRIPTION
**Pull request by jschueller**
@dougalsutherland would that solve your issue?
xref https://github.com/conda-forge/idna-feedstock/pull/5

### CODE REVIEW

**Comment by dougalsutherland** [comment]
I don't understand why this is failing, but it's hard to debug without a Windows machine....

I noticed there have been a couple of conda releases since the version that was installed in this build, so I hit restart just in case it was a bug in 3.4.25 for some reason.

**Comment by dougalsutherland** [comment]
Yeah, it still fails with 4.3.27. Is the `anaconda-client` recipe broken on Windows for some reason?

**Comment by jakirkham** [comment]
It looks like that version of `conda` has issues as it is failing to install anything. 😕

**Comment by jakirkham** [comment]
Could you please take a look @kalefranz?

**Pull request closed without merging**
