### PR TITLE
Add python-igraph recipe

### PR DESCRIPTION
**Pull request by sodre**
These are the python bindings to the c igraph library.

Waiting for conda-forge packages:
- [x] igraph: PR #2175 

Once that package is added, the igraph recipe in this PR will be removed.

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @sorde, would you mind splitting these out into two separate PRs, please? Thanks!

**Comment by sodre** [comment]
@scopatz Split what into two separate PRs?
It took so long to get anything back on these that I am a little out of the loop on this. 
python-igraph depends on the C library igraph, which is a different PR already.

**Comment by scopatz** [comment]
If igraph is a different PR then the recipe here shouldn't be included. Can you please remove it and leave just the python recipe in this PR. Thanks!

**Comment by sodre** [comment]
It is all coming back to me now....

I had the igraph recipe in this PR because otherwise the recipe would not build. The idea was to the remove it from this PR once it was merged in master and available in conda-forge. Hence the "dependency" in PR #1385.

I will remove the files are soon as PR#1385 is merged.

**Comment by scopatz** [comment]
Is this good to go?

**Comment by sodre** [comment]
Yes, this is now done.

**Pull request merged**
