### PR TITLE
Adding Gtsam 4.0.3

### PR DESCRIPTION
**Pull request by ameysutavani**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please restart CI

**Comment by Tobias-Fischer** [comment]
Hi @ameysutavani @wolfv - this recipe looks nearly ready, does it? It looks like all it needs is adding `boost-cpp` to the run requirements. Requiring boost 1.76 might be an issue though as we would be out of sync with the rest of Conda-forge :(. Can you remember the reason why it is needed?

**Comment by wolfv** [comment]
I think the problem was a missing or wrong include in one of boost headers on version 1.74 -- similar to this issue: https://github.com/borglab/gtsam/issues/634 -- I was proposing a patch there that might already be part of a later GTSAM release.

**Comment by wolfv** [comment]
It looks like building gtsam itself is fine but building the tests is failing. Anybody with more gtsam experience here? It still looks related to boost. 

Again we could require boost 1.76 but it would be incompatible with other conda-forge things & robostack.

**Comment by Tobias-Fischer** [comment]
I think I'm going crazy, I am sure I added a comment here half an hour ago but it seems gone ..

Happy to add the patches below if you give me write access @ameysutavani, or feel free to add them @wolfv 

Anyhow, here is the patch to get it to build:
```
diff --git a/gtsam/base/serialization.h b/gtsam/base/serialization.h
index 24355c684..e615afe83 100644
--- a/gtsam/base/serialization.h
+++ b/gtsam/base/serialization.h
@@ -25,6 +25,7 @@
 #include <string>
 
 // includes for standard serialization types
+#include <boost/serialization/version.hpp>
 #include <boost/serialization/optional.hpp>
 #include <boost/serialization/shared_ptr.hpp>
 #include <boost/serialization/vector.hpp>
diff --git a/gtsam/linear/NoiseModel.h b/gtsam/linear/NoiseModel.h
index 54b9d955f..a737c5cc8 100644
--- a/gtsam/linear/NoiseModel.h
+++ b/gtsam/linear/NoiseModel.h
@@ -27,6 +27,7 @@
 #include <boost/serialization/extended_type_info.hpp>
 #include <boost/serialization/singleton.hpp>
 #include <boost/serialization/shared_ptr.hpp>
+#include <boost/serialization/version.hpp>
 #include <boost/serialization/optional.hpp>
 
 namespace gtsam {
diff --git a/gtsam/slam/SmartFactorBase.h b/gtsam/slam/SmartFactorBase.h
index ddf56b289..f128bd124 100644
--- a/gtsam/slam/SmartFactorBase.h
+++ b/gtsam/slam/SmartFactorBase.h
@@ -30,6 +30,7 @@
 #include <gtsam/geometry/CameraSet.h>
 
 #include <boost/optional.hpp>
+#include <boost/serialization/version.hpp>
 #include <boost/serialization/optional.hpp>
 #include <boost/make_shared.hpp>
 #include <vector>
```

And here are some other suggestions:
```diff
diff --git a/recipes/gtsam/build.sh b/recipes/gtsam/build.sh
index 3783d83b07..b6e2d1592d 100644
--- a/recipes/gtsam/build.sh
+++ b/recipes/gtsam/build.sh
@@ -5,7 +5,8 @@ cmake .. ${CMAKE_ARGS} \
        -GNinja \
        -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF \
        -DGTSAM_USE_SYSTEM_EIGEN=ON \
-       -DGTSAM_INSTALL_CPPUNITLITE=OFF
+       -DGTSAM_INSTALL_CPPUNITLITE=OFF \
+       -DGTSAM_BUILD_PYTHON=ON
 
 ninja install
 
diff --git a/recipes/gtsam/meta.yaml b/recipes/gtsam/meta.yaml
index 349fbff58a..d5befa8a29 100644
--- a/recipes/gtsam/meta.yaml
+++ b/recipes/gtsam/meta.yaml
@@ -10,6 +10,7 @@ source:
   sha256: c7b5e6cdad52b141c272778f47baf628975457be3e26ed96a7bc2ae685a00af0
   patches:
     - nobuild-examples-timing.patch
+    - fix-boost.patch
 
 build:
   number: 0
@@ -22,12 +23,24 @@ requirements:
     - '{{ compiler("cxx") }}'
     - ninja
     - cmake
+    - pybind11                               # [build_platform != target_platform]
+    - numpy                                  # [build_platform != target_platform]    
   host:
     - boost-cpp
     - eigen
     - geographiclib-cpp
     - metis
     - suitesparse
+    - tbb
+    - tbb-devel
+    - pybind11
+    - pyparsing
+    - numpy
+    - mkl  # [not (osx and arm64)]
+  run:
+    - pyparsing
+    - {{ pin_compatible('numpy') }}
+
 # test:
 #   files:
 #   - test/hello_world.xar
@@ -45,3 +58,4 @@ extra:
   recipe-maintainers:
     - wolfv
     - ameysutavani
+    - Tobias-Fischer
```

**Comment by wolfv** [comment]
Pushed your suggestions, let's see! :)

**Comment by Tobias-Fischer** [comment]
Looks like mkl needs to be removed

**Comment by wolfv** [comment]
Done, also added `python` to run.

**Comment by Tobias-Fischer** [comment]
Thanks Wolf! Weird that it can't find python on Linux and pyparsing on osx .. let's try with DGTSAM_BUILD_PYTHON=OFF and worry about that later I suggest

**Comment by Tobias-Fischer** [comment]
Kind ping @wolfv 

@ameysutavani - any chance you can give me access to your fork?

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - this fixes the issues on both Linux and OSX:

```patch
diff --git a/recipes/gtsam/build.sh b/recipes/gtsam/build.sh
index ae6acd3d66..52069d1690 100644
--- a/recipes/gtsam/build.sh
+++ b/recipes/gtsam/build.sh
@@ -6,7 +6,8 @@ cmake .. ${CMAKE_ARGS} \
        -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF \
        -DGTSAM_USE_SYSTEM_EIGEN=ON \
        -DGTSAM_INSTALL_CPPUNITLITE=OFF \
-    -DGTSAM_BUILD_PYTHON=ON
+       -DGTSAM_BUILD_PYTHON=ON \
+        -DPython3_EXECUTABLE=$PREFIX/bin/python
```

Would be great if you could change it - this obviously still builds python bindings :). Would be exciting to have GTSAM in conda-forge.

**Comment by wolfv** [comment]
Pushed!

**Pull request merged**
