### PR TITLE
Add ogre-next

### PR DESCRIPTION
**Pull request by traversaro**
This PR adds `ogre-next`, a C++ 3D graphics engine . 

First of all, it is important to clarify a bit the relation between `ogre` and `ogre-next`. What is now ogre-next started as ogre 2, with substutiantial changes w.r.t. to ogre 1. However, many users of ogre never migrated to ogre 2, so they continued to use and mantain ogre 1. As a consequence, at some point ogre 2 renamed itself to ogre-next, while ogre 1 continued to exits as ogre, also bumping its major version number, going from 1.13 to 13 (see https://github.com/conda-forge/ogre-feedstock).

As a consequence, it is quite important to permit to ogre and ogre-next to be installed side-by-side in the same environment, as for example in the robotics world RViz2 (a visualizer) uses ogre, while the new generation of Gazebo (formerly known as Ignition) uses ogre-next . The upstream ogre-next still needs to complete its support to be installable side-by-side with ogre (see https://github.com/OGRECave/ogre-next/issues/232), so in this PR we patched the project to be side-by-side installable with ogre as was done in Debian/Ubuntu packacing (see https://salsa.debian.org/ogre-team/ogre-next/-/blob/a27f70cd8c6b82e3fc207fefe557b43bc49634b4/debian/README.Debian).

For an overview of the existing differences between Ogre and Ogre Next, see https://www.ogre3d.org/about/what-version-to-choose .

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
My initial goal here is to create a package that was side-by-side installable with ogre, as done in Debian, see https://salsa.debian.org/ogre-team/ogre-next/-/blob/a27f70cd8c6b82e3fc207fefe557b43bc49634b4/debian/README.Debian , to fix https://github.com/conda-forge/libignition-gazebo-feedstock/issues/27 . 
Unfortunatly, I got stuck as in Windows the rendersystem plugins are installed in `<prefix>/bin` , while on Linux are installed in `<prefix>/lib/OGRE`, so it is not possible on all platforms to install the plugins in a way such that ogre and ogre-next do not interfere.

**Comment by traversaro** [comment]
> From the ignition-rendering point of view, as long as `OGRE2_RESOURCE_PATH` is correctly set (see https://github.com/gazebosim/gz-rendering/blob/e7c8b3a9b061dc38f8085f8f12127f5551c2db90/ogre2/src/Ogre2RenderEngine.cc#L100), everything should work fine.

More in general, as long as `pkg-config --variable=plugindir OGRE-Next` points to the correct directory, downstream libraries can use that value to find the plugins and load them.

**Comment by traversaro** [comment]
Even if the CI is still finishing, `osx_64` and `win_64` were successful before, so I think the PR is ready for review. @conda-forge/help-c-cpp 

@wolfv @Tobias-Fischer this is necessary to actually have a working Gazebo (formerly known as Ignition) packages with ROS2, as ROS2 RViz2 uses Ogre 1.12, and Gazebo does not work with Ogre 1.12 (see https://github.com/RoboStack/ros-galactic/issues/104 for a problem generated by the fact that we do not have ogre-next). As you are mantainers of ogre feedstock, please reply if you like to be mantainers of ogre-next as well, thanks!

**Comment by Tobias-Fischer** [comment]
I'll give this one a miss re becoming maintainer..

**Comment by wolfv** [comment]
Thanks for working in this! I'm happy to be added as a maintainer.

**Comment by traversaro** [comment]
> Thanks for working in this! I'm happy to be added as a maintainer.

Done in https://github.com/conda-forge/staged-recipes/pull/19384/commits/b87742c3437c1dad1f0028985fc0f07a8008cd0f .

**Comment by wolfv** [comment]
Let me know if you think this is ready. Happy to merge!

**Comment by traversaro** [comment]
The PR is ready!

**Comment by traversaro** [comment]
Thanks @wolfv!

**Pull request merged**
