### PR TITLE
Add r-mailr

### PR DESCRIPTION
**Pull request by ning-y**
**This recipe was added with the help of [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper).**

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ning-y** [comment]
@conda-forge/help-r Ready for review!

**Comment by ning-y** [comment]
@conda-forge-admin, please ping team

**Comment by cbrueffer** [comment]
Hi @ning-y, please re-generate the recipe with `https://github.com/bgruening/conda_r_skeleton_helper`; it automatically cleans up the recipe and adds `conda-forge/r` as maintainer.

**Comment by ning-y** [comment]
@cbrueffer I did indeed use conda_r_skeleton_helper's python script to generate the files in this pull request:

```bash
(base) admin:~/github/conda_r_skeleton_helper$ cat packages.txt
r-mailr
(base) admin:~/github/conda_r_skeleton_helper$ cat extra.yaml

extra:
  recipe-maintainers:
    - conda-forge/r
    - ning-y
(base) admin:~/github/conda_r_skeleton_helper$ python run.py
Processing r-mailr
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Parsing input package r-mailr:
.. name: mailr location: None new_location: /home/admin/github/conda_r_skeleton_helper/r-mailr
Making/refreshing recipe for mailr
Tip: install CacheControl and lockfile (conda packages) to cache the CRAN metadata
Fetching main index from https://cran.r-project.org
/home/admin/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cran.r-project.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/admin/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cran.r-project.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Downloading source from https://cran.r-project.org/src/contrib/mailR_0.4.1.tar.gz
No hash (md5, sha1, sha256) provided for source-mailR_0.4.1.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for source-mailR_0.4.1.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
Reading package metadata from /home/admin/miniconda3/conda-bld/src_cache/source-mailR_0.4.1_9c36876a57.tar.gz
Writing recipe for mailr
--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

Traceback (most recent call last):
  File "/home/admin/github/conda_r_skeleton_helper/run.py", line 122, in <module>
    raise ValueError(msg.format(license, SPDX_url))
ValueError: "GPL-3" license not valid. See https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions
(base) admin:~/github/conda_r_skeleton_helper$ diff r-mailr/meta.yaml ../staged-recipes/recipes/r-mailr/meta.yaml
60c60
<   license: GPL-3
---
>   license: GPL-3.0-only
65a66,69
> 
> extra:
>   recipe-maintainers:
>     - ning-y
(base) admin:~/github/conda_r_skeleton_helper$ 
```

I assumed that the failure was something that could be fixed manually (as in the most recent commit 9b921f4), but I suppose not?

I'll try to run the R script at conda_r_skeleton_helper next when I have more time. In the meantime, I will just manually add `conda-forge/r` as maintainer.

**Comment by cbrueffer** [comment]
That must have been caused by a recent change. If you comment out the four lines following `# Checking for valid SPDX license
` in `run.py` and re-run it should work, you only need to fix the SPDX license string afterwards.

**Comment by cbrueffer** [comment]
Thanks @ning-y, looks good!

**Pull request merged**
