### PR TITLE
Add BLIS

### PR DESCRIPTION
**Pull request by isuruf**
cc @jakirkham

### CODE REVIEW

**Comment by isuruf** [comment]
@mingwandroid, here's an example of using msys2 build tools with clang.exe (targetting MSVC) as the compiler

**Comment by jakirkham** [comment]
Seems macOS's version of `clang` doesn't support `-fdebug-prefix-map`. Is it essential to have this argument or can it be dropped somehow?

**Comment by jakirkham** [comment]
We also will want to figure out how to include this in the `blas` selection. Do they provide LAPACK support?

**Comment by jakirkham** [comment]
Thanks for working on this, @isuruf

**Comment by isuruf** [comment]
> We also will want to figure out how to include this in the blas selection.

Let's hold that off for a while

>Do they provide LAPACK support?

`libflame` provides a LAPACK API. We can also use `netlib` reference LAPACK with BLIS as well.

**Comment by isuruf** [comment]
@conda-forge/staged-recipes, ready for review. Note the dev0 tag as the package is relatively new and has a lot of fixes related to build system from the last release. It'll be helpful to merge now to play with it, but will move to a stable release before it is used in other packages if there are any.

**Comment by isuruf** [comment]
Thanks, @scopatz

**Pull request merged**
