### PR TITLE
Appveyor setting of CONDA_PY correctly for Obvious-CI.

### PR DESCRIPTION
**Pull request by pelson**
Doh, this is why the tests were failing. Replaces #4.

### CODE REVIEW

**Comment by pelson** [comment]
> Doh, this is why the tests were failing. Replaces #4.

If only life were that simple... :wink: 

Now that I've got to it, I get a compile error for matplotlib on win64:

```
fatal error C1083: Cannot open include file: 'string'
```

**Comment by pelson** [comment]
@cgohlke - really weird. Do you think it is my compiler setup? https://social.msdn.microsoft.com/Forums/vstudio/en-US/0f580a73-6f11-4aa6-abbe-6bf1438734c2/standard-files-stddefh-stringh-missing-in-visual-studio-2015-rc?forum=vclanguage looks vaguely relevant.

**Comment by ocefpaf** [comment]
There is an old Chinese proverb: "Do not kill the dragon that bothers you.  Another one bigger and meaner will take its place."  :stuck_out_tongue_winking_eye:

**Comment by pelson** [comment]
Indeed @ocefpaf :wink: 
Part of my problem is that I don't have a win64 machine handy to reproduce, so I would end up iterating pretty slowly and I'd be surprised if this were isolated to matplotlib and appveyor's vc2009 installation.

**Comment by ocefpaf** [comment]
> Part of my problem is that I don't have a win64 machine handy to reproduce,

That is my problem too.  It would be nice if the Win64 heroes out there adopted conda+AppVeyor+community channel publishing.

**Pull request merged**
