### PR TITLE
add _openssl-syslib-check package

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Out of the discussion in https://github.com/conda-forge/cryptography-feedstock/pull/37 and https://github.com/conda-forge/openssl-feedstock/pull/56, @mingwandroid [suggested](https://github.com/conda-forge/openssl-feedstock/pull/56#issuecomment-622553603) to introduce a package that both the openssl- & cryptography-feedstock can depend on, so we don't have a mess of activation scripts needing to cover all possible deployment scenarios.

This is a first draft, but comes with a test suite at least. I added some old dlls for that purpose, not sure what the opinion is on that.

I added both @isuruf  and @mingwandroid  as maintainers, since they were by far the most active/knowledgeable in this discussion. If this assumption is wrong, I'm happy to revert.

Still missing:
- [ ] write `activate.sh` and enable testing for it.
- [ ] figure out a way to execute `run_test.py` with enough permissions to change stuff in `C:/Windows/System32` (see this [comment](https://github.com/conda-forge/staged-recipes/pull/11452#issuecomment-622954298))
- [ ] ensure recipe gets tested with correct python version per build (see this [comment](https://github.com/conda-forge/staged-recipes/pull/11452#issuecomment-622990392))

### CODE REVIEW

**Comment by h-vetinari** [comment]
Is there a way to run the tests as root?

Since it was possible to delete dlls from `C:/Windows/System32` (e.g. https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/84), I thought this could be done at testing time as well?

At the moment I wrapped that part in a try-except clause, but the activation script should IMO really be tested in all variants.

**Comment by isuruf** [comment]
I don't think this is a good idea as this adds cycles in the dependency graph.

**Comment by h-vetinari** [comment]
> I don't think this is a good idea as this adds cycles in the dependency graph.

No, this package doesn't depend on anything. And `openssl` / `cryptography` could depend on it just on windows.

**Comment by h-vetinari** [comment]
I wanted to use a trick from the [blas-feedstock](https://github.com/conda-forge/blas-feedstock/blob/master/recipe/build.sh#L24-L28) to install `cryptography` during the test, but I can't seem to get it to work.

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes 
Is there any way to run the tests as an admin? I need to copy some outdated libs to `C:/Windows/System32/` to fully test all scenarios of the activation script (this is harmless, cf. https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/84).

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes 
So conda-smithy says the recipe can't be `noarch` because of the `# [not win]` selector, yet while the build process says it's building:
```
Resolved dependencies, will be built in the following order:
    _openssl-syslib-check-1.0.0-python_3.6.* *_cpython-on-win-64
    _openssl-syslib-check-1.0.0-python_3.7.* *_cpython-on-win-64
```
the test environment actually installs python 3.8 in both cases.

This recipe _must not_ depend on python, but I'd like to be able to test the correct python version nevertheless (because different python versions have different builds regarding `CONDA_DLL_SEARCH_MODIFICATION_ENABLE`, cf. https://github.com/conda-forge/python-feedstock/pull/345) - how can I achieve that?

**Comment by h-vetinari** [comment]
@mingwandroid 
This implements the [idea](https://github.com/conda-forge/openssl-feedstock/pull/56#issuecomment-622553603) you voiced on the openssl-PR. This is IMO ready for a round of review - I'd still need to write `activate.sh`, but thankfully that'd be just a (much easier) translation of the `.bat` version. There are also two open points that I don't have an answer for yet (see OP).

**Comment by h-vetinari** [comment]
PS. As noted [here](https://github.com/conda-forge/openssl-feedstock/pull/56#issuecomment-622984104), there's an argument to be made that the activation scripts could directly live in the openssl-feedstock, and probe for `cryptography` without depending on it. The only downside I see is that I don't know how I could explicitly test with the outdated DLLs as I'm trying to do here (I've tested that it works, modulo the permission errors on azure).

**Comment by h-vetinari** [comment]
@mingwandroid 
What do you think about the approach here - both the general structure of `activate.bat` and the tests for it?

Strictly speaking a test suite for the activation scripts is not necessary, but I thought it's a prudent thing considering the importance of the packages (if we say goodbye to the tests that need elevated privileges, I could implement this in the openssl-feedstock right away).

**Comment by mingwandroid** [comment]
I like it, yes, many thanks. My only concern is a slight overhead added at activate time, but I guess we'll see if that's a big problem. It's certainly better than the alternative! It might be prudent to have a very-early-out env. var check to mitigate this? CONDA_SKIP_OPENSSL_DLL_CHECK or something?

**Comment by h-vetinari** [comment]
@mingwandroid
Good to hear!

I have already added an early out:
```
:: early exit in case no syslibs are found
if "%HAS_SYS_LIBS%"=="F" (
  exit /b 0
)
```
I also thought about an early-out env-var, but then I guess that  2 file-`exist`-checks are probably almost unnoticeably quick? If I'm wrong about that, an even earlier out is easy to add of course.

Do you have some advice if/how `run_test.py` could be run with elevated privileges? And is there a jinja-variable to template over the python-verison in the test-env? Finally, assuming this should just live in openssl directly, would there be a way to pass non-source files from the recipe to the test environment (thinking about the outdated DLLs here)?

**Comment by h-vetinari** [comment]
PS. Besides speed, the `CONDA_SKIP_OPENSSL_DLL_CHECK` would serve a potentially much more important usability-point as well - silencing the warning, for those who don't wanna see it.

**Comment by h-vetinari** [comment]
@isuruf 
Thanks for jumping in and helping out! Is there any way we could execute `run_test.py` with elevated permissions? I mean, the conda-forge-ci-setup definitely runs with those privileges, so I'm guessing it should not be completely impossible to achieve for the testing either?

**Comment by h-vetinari** [comment]
@mingwandroid @isuruf 

This is more or less ready to be added into the openssl-PR, but I still have the open question if there is a way to execute `run_test.py` with elevated privileges somehow?

**Comment by h-vetinari** [comment]
Ping @mingwandroid @isuruf

**Comment by h-vetinari** [comment]
Let's keep this open a bit more. Still planning to come back to this in some form

**Comment by h-vetinari** [comment]
Not (completely) stale

**Comment by xhochy** [comment]
> Not (completely) stale

What's the state here? Do plan to work more on this or should I do a review to get this forward?

**Comment by h-vetinari** [comment]
Hey @xhochy, thanks for taking an interest here!

There were a few open questions for which I never got an answer - mainly revolving around testing. E.g. to test the correct behaviour in all (or even most) variants, we'd have to delete/replace system libraries in CI, which requires running the test with elevated privileges.

Also, I had considered writing some tests for the activation-log output, but never got around to that due to not receiving other feedback - just reread the thread and most things are still current/open.

For context, this PR started [here](https://github.com/conda-forge/openssl-feedstock/pull/56), and then Ray had [suggested](https://github.com/conda-forge/openssl-feedstock/pull/56#issuecomment-622553603):
> Why don't we make a common package for this check that both openssl and anything else can depend on?

**Pull request closed without merging**
