### PR TITLE
Add recipe for editdistance

### PR DESCRIPTION
**Pull request by nelson-liu**
This adds a recipe for https://github.com/aflc/editdistance, which is an implementation of the edit distance in C++ and cython.

Not sure if I packaged the extensions properly, I guess CI will tell me...

### CODE REVIEW

**Comment by nelson-liu** [comment]
ok, looks like tests are passing. @conda-forge/bioconda-recipes , would you be ok with porting editdistance over to `conda-forge`? 

I use edit distance for natural language processing, so it certainly doesn't seem biology-specific. If we decide to go this route, I'd be happy to send a PR to remove `editdistance` from bioconda as well.

**Comment by daler** [comment]
@nelson-liu +1 for removing from bioconda. Looks like it was first added before we were stricter about bio-only stuff. Thanks.

**Comment by bgruening** [comment]
I fixed this for you. Please look at https://conda-forge.org/docs/recipe.html#optional-bld-bat-and-or-build-sh for the new way to install python with pip.

**Comment by nelson-liu** [comment]
@bgruening thanks, much appreciated!

**Comment by nelson-liu** [comment]
This is ready for review, and I'd greatly appreciate if someone could take a look at it.

Thanks!

**Comment by bgruening** [comment]
Thanks!

**Comment by jakirkham** [comment]
FYI we are having conversion problems as noted in issue ( https://github.com/conda-forge/staged-recipes/issues/5846 ).

**Pull request merged**
