### PR TITLE
Add some cos7 ppc64le CDTs

### PR DESCRIPTION
**Pull request by jayfurmanek**
@conda-forge/staged-recipes

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vend other packages
- [x] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jayfurmanek** [comment]
I'm Willing to be maintainer

**Comment by jayfurmanek** [comment]
What's the recommendation here? This is a CDT package for ppc64le. CDT packages are marked noarch. A Test is required, but will only work on ppc64le systems since the `powerpc64le` sysroot only exists there.
Adjust the test perhaps?

**Comment by jayfurmanek** [comment]
I'll emulate: https://github.com/conda-forge/staged-recipes/pull/9028

Will also pull in other CDTs to this PR. Wait to review.

**Comment by jayfurmanek** [comment]
@conda-forge/staged-recipes  This is ready for a review.

**Comment by scopatz** [comment]
Are you sure that we can't just build these?

**Comment by jayfurmanek** [comment]
I guess you tell me. The code itself can certainly be built. The point of the CDT packages, however is to install them into the `sysroot` of the toolchain, not necessarily into the runtime environment. A number of recipes rely on them, including `r-base` which is the package that caused me to add this PR - it needs these three libs to build against.

**Comment by jayfurmanek** [comment]
Anaconda has a (somewhat) clear usage of CDTs (https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#host).
conda-forge on the other hand has some CDTs, but also some fully built xOrg packages and the like. If forge wants to avoid CDTs for these particular packages that's fine, but some recipes might have to change.

**Comment by scopatz** [comment]
> I guess you tell me. 

The default should be to build the real package, rather than have a CDT

**Comment by jayfurmanek** [comment]
re-ping: @conda-forge/staged-recipes

**Comment by jakirkham** [comment]
We are trying to decide whether we should consolidate these into fewer feedstocks in the issue @isuruf has cc’d us on.

**Comment by jayfurmanek** [comment]
I see. Can I help with that somehow?

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
