### PR TITLE
Add recipe for miniwdl-slurm

### PR DESCRIPTION
**Pull request by rhpvorderman**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by DavyCats** [comment]
I'm okay with being a maintainer.

**Comment by rhpvorderman** [comment]
@conda-forge/help-python Windows cannot install the upstream noarch dependency (there is only one dependency). How can I best resolve this issue? If I disable windows, it is not exactly noarch anymore IIRC.

**Comment by BastianZim** [comment]
That's fine. Since it's noarch, the dependency only needs to be available on Linux as that's where it is built. Once the dependency becomes available on windows, your users will then be able to install the package there too.

**Comment by rhpvorderman** [comment]
Thanks for the clarification and merging @BastianZim !

**Pull request merged**
