### PR TITLE
Add napari-stress recipe

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- ~[ ] If static libraries are linked in, the license of the static library is packaged.~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Depends on:
- https://github.com/conda-forge/staged-recipes/pull/19248
- https://github.com/conda-forge/staged-recipes/pull/24360

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
FYI @jo-mueller

**Comment by jo-mueller** [comment]
@goanpeca - is there anything from my side you'd need to move this foward? I'd love to see napari-stress on coda-forge :)

**Comment by haesleinhuepf** [comment]
Hey Johannes @jo-mueller ,

to bring napari-stress to conda-forge, all of its dependencies need to be on conda-forge. Thus, this needs to be resolved:
* https://github.com/haesleinhuepf/napari-process-points-and-surfaces/issues/14

Let me know if you want to help! Your expertise would for example be helpful here:
* https://github.com/haesleinhuepf/napari-process-points-and-surfaces/pull/23#issuecomment-1287826059


Thanks!
Robert

**Comment by jo-mueller** [comment]
@goanpeca 

> Still working on this :)

Is there anything I can do to help?

**Comment by goanpeca** [comment]
Hi @jo-mueller is there a reason for having an exact pinning on the latest version ?

- napari-matplotlib ==0.2.0
?

Could this be relaxed?

**Comment by jo-mueller** [comment]
Hi @goanpeca ,

It used to be necessary, but can be relaxed with the next release which I am planning for the end of this week or so. Thanks for being on top of this!

**Comment by goanpeca** [comment]
>It used to be necessary, but can be relaxed with the next release which I am planning for the end of this week or so. Thanks for being on top of this!

Cool. How can we relax it >= or <= or no pin at all? 

Cheers :)

**Comment by jo-mueller** [comment]
Hi @goanpeca , I relaxed the criteria to napari-matplotlib >= 1.1.0, hope that makes it a bit easier!

**Comment by goanpeca** [comment]
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

@jaimergp, @jo-mueller do you agree with being added as maintainers?

**Comment by jo-mueller** [comment]
@goanpeca Sure thing!

**Comment by goanpeca** [comment]
import: 'napari_stress'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/test_tmp/run_test.py", line 2, in <module>
    import napari_stress
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/__init__.py", line 3, in <module>
    from . import _measurements as measurements
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/_measurements/__init__.py", line 3, in <module>
    from .curvature import (calculate_mean_curvature_on_manifold,
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/_measurements/curvature.py", line 16, in <module>
    from ..types import (_METADATAKEY_MEAN_CURVATURE,
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/types.py", line 2, in <module>
    from magicgui.widgets._bases import CategoricalWidget
ModuleNotFoundError: No module named 'magicgui.widgets._bases'

**Comment by goanpeca** [comment]
import: 'napari_stress'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/test_tmp/run_test.py", line 2, in <module>
    import napari_stress
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/__init__.py", line 3, in <module>
    from . import _measurements as measurements
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/_measurements/__init__.py", line 3, in <module>
    from .curvature import (calculate_mean_curvature_on_manifold,
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/_measurements/curvature.py", line 16, in <module>
    from ..types import (_METADATAKEY_MEAN_CURVATURE,
  File "/home/conda/staged-recipes/build_artifacts/napari-stress_1702056776747/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/napari_stress/types.py", line 2, in <module>
    from magicgui.widgets._bases import CategoricalWidget
ModuleNotFoundError: No module named 'magicgui.widgets._bases'

**Comment by goanpeca** [comment]
This one is ready for review @conda-forge/staged-recipes :)

**Review by xhochy — APPROVED** [review]

**Pull request merged**
