### PR TITLE
Add urdfdom.

### PR DESCRIPTION
**Pull request by lesteve**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by lesteve** [comment]
@jcarpent and @wolfv if you can post a comment saying you are fine being a maintainer for the `urdfdom` recipe.

**Comment by wolfv** [comment]
fine, as always!

**Comment by lesteve** [comment]
By the way I am not sure I fully understand the `run_exports` thing. Is the rule that if the recipe creates a shared library I need to add a `run_exports` section?

**Comment by xhochy** [comment]
> By the way I am not sure I fully understand the `run_exports` thing. Is the rule that if the recipe creates a shared library I need to add a `run_exports` section?

Basically yes except you can guarantee ABI stability in all future version which is quite unlikely.

**Comment by jcarpent** [comment]
It is fine for me too. Thanks to @lesteve!

**Comment by lesteve** [comment]
OK I have added the `run_exports` section and CI is now green (`urdfdom_headers` package has made it to `conda-forge` very recently).

**Pull request merged**
