### PR TITLE
Add r-bezier

### PR DESCRIPTION
**Pull request by brainstorm**

### CODE REVIEW

**Comment by bgruening** [comment]
@brainstorm the last commit should be reverted. The linter is not up to date.

**Comment by brainstorm** [comment]
@bgruening Is the new linter up and running now? [Should I PR/tweak the documentation too](https://conda-forge.org/docs/meta.html#compilers), accordingly? :-S

**Comment by bgruening** [comment]
I don't think so, but we can merge even when the linting is failing :)

**Comment by bgruening** [comment]
Merci and Merry Christmas!

**Pull request merged**
