### PR TITLE
Initial version of SLiM recipe.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jeromekelleher** [comment]
@bhaller, @petrelharp, I had a go at making a conda-forge package for SLiM here. Linux ([here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=111829&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=748)) and OSX ([here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=111829&view=logs&j=c572e5d5-7ba7-55ce-5575-7ce1d9f7161e&t=81967b5f-0283-5c0b-87c1-e8fdeef842a3&l=292)) almost worked and just fell over during compile because of problems with the clock stuff (seems like a dependency on ``lrt`` needs to be declared?). I suspect this is an issue with the CMake file, which should probably be fixed there.

I'm not sure what happened to the windows build, it didn't seem to get started at all.

Anyway, I just wanted to demonstrate that making a conda-forge recipe is pretty straightforward, and having SLiM on conda-forge would be a big bonus for downstream users like stdpopsim.

**Comment by petrelharp** [comment]
Wow, awesome. Perhaps @bnorris03 or @suds12 are interested to know this as well.

**Comment by jeromekelleher** [comment]
Also FYI @molpopgen

**Comment by bhaller** [comment]
> @bhaller, @petrelharp, I had a go at making a conda-forge package for SLiM here.

Awesome!  Thanks!

> Linux ([here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=111829&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=748)) and OSX ([here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=111829&view=logs&j=c572e5d5-7ba7-55ce-5575-7ce1d9f7161e&t=81967b5f-0283-5c0b-87c1-e8fdeef842a3&l=292)) almost worked and just fell over during compile because of problems with the clock stuff (seems like a dependency on `lrt` needs to be declared?). I suspect this is an issue with the CMake file, which should probably be fixed there.

The error is "undefined reference to `clock_gettime'", in eidos_functions.cpp, which comes from the inline code for Eidos_GetMonotonicTimer() in eidos_globals.h.  I'm a bit puzzled by this, because according to the man page on my machine, clock_gettime() is defined in time.h and is part of POSIX.1, and eidos_globals.h duly includes <time.h>, so it should be fine, no?  And in other contexts it does seem to be fine – it builds on both macOS and Linux on travis-CI, and nobody has reported a problem with it as far as I recall.  So why does it cause a problem in this context?  Does this make sense to anybody?

> I'm not sure what happened to the windows build, it didn't seem to get started at all.

Well, SLiM doesn't build on Windows anyway, at present, but I don't know why that would mean that a Windows build would not even start.

> Anyway, I just wanted to demonstrate that making a conda-forge recipe is pretty straightforward, and having SLiM on conda-forge would be a big bonus for downstream users like stdpopsim.

This is great.  I'd be happy to see this happen, but I'm not sure how to fix the build issue seen here.  Is that the only thing remaining to make this work?

**Comment by jeromekelleher** [comment]
> The error is "undefined reference to `clock_gettime'", in eidos_functions.cpp, which comes from the inline code for Eidos_GetMonotonicTimer() in eidos_globals.h. I'm a bit puzzled by this, because according to the man page on my machine, clock_gettime() is defined in time.h and is part of POSIX.1, and eidos_globals.h duly includes <time.h>, so it should be fine, no? And in other contexts it does seem to be fine – it builds on both macOS and Linux on travis-CI, and nobody has reported a problem with it as far as I recall. So why does it cause a problem in this context? Does this make sense to anybody?

I think this issue is possibly that the build environment for conda is a super old CentOS environment (for compatability reasons), so it needs to work with old compilers/libc versions. I don't know though, it is odd that OSX and linux both fail to compile on the clock issues though. Maybe others will have hit this issue? It seems like a small and entirely fixable thing, so it'd be great to get to the bottom of it. @molpopgen, have you hit this when doing bioconda builds?

>> I'm not sure what happened to the windows build, it didn't seem to get started at all.

> Well, SLiM doesn't build on Windows anyway, at present, but I don't know why that would mean that a Windows build would not even start.

OK, well that simplifies things for now: we can just disable the Windows build (are there plans to get SLiM building on Windows via Cmake? It'd be nice...)

If we get this working, are you willing to do the maintenance @bhaller? This would just involve opening a PR which bumps the version number and puts in the new sha256 hash for each new release.

**Comment by npavlovikj** [comment]
@jeromekelleher , few quick notes:

- I think the Windows build is not starting because the script should be named `bld.bat`, and not `build.bat`, https://conda-forge.readthedocs.io/en/latest/recipe.html#optional-bld-bat-and-or-build-sh.
- The developers of the package should know more, but it looks like the "undefined reference to `clock_gettime" can be avoided by adding `-lrt` to the compile flags, https://stackoverflow.com/questions/2418157/c-error-undefined-reference-to-clock-gettime-and-clock-settime. I would suggest you to check the CMake file and try adding `-lrt` to either `CFLAGS` or `LIBS`.

I don't promise this would work, but I hope it helps :)

**Comment by jeromekelleher** [comment]
Thanks so much @npavlovikj, this is super helpful!!

**Comment by jeromekelleher** [comment]
Ah, OK, the windows build started all right now and failed when trying to compile GSL code. I'll disable the Windows build next time I'm looking at this. Thanks again @npavlovikj!

**Comment by bhaller** [comment]
Looking at this idea of adding `-lrt`.  This SO answer has me concerned: https://stackoverflow.com/a/32649327/2752221.  As I understand that answer, adding `-lrt` would have performance implications, as it would cause a load of the pthreads library and switch the C++ runtime over to multithreaded mode.  I don't know whether the effect of that would be noticeable in practice, but in any case I'm not crazy about the idea of switching SLiM over to multithreaded mode when SLiM is in fact still single-threaded.  It sounds like with glibc >= 2.17 the `-lrt` flag is no longer required.  That version of glibc was released back in 2012; it seems reasonable to just require it.  Can we do that somehow, rather than adding `-lrt`?

I'd like to tag @bnorris03 on this question, but tagging her doesn't seem to work here for some reason (@petrelharp 's tag of her also seems not to have worked).

**Comment by jeromekelleher** [comment]
I doubt adding -lrt would make any measurable difference to performance. There's no real option here with requiring things like glibc: you have to use the version available. Building against a super-old glibc is how the portability across different linux distros works. If it turns out that there's a measurable difference in performance in SLiM conda-packaged and SLiM natively built then it might make sense to look into optimising, but until then I'd recommend a "let's just get this working" approach.

**Comment by bhaller** [comment]
> If it turns out that there's a measurable difference in performance in SLiM conda-packaged and SLiM natively built then it might make sense to look into optimising, but until then I'd recommend a "let's just get this working" approach.

OK; but how do we turn on -lrt only when building in conda?

**Comment by jeromekelleher** [comment]
> OK; but how do we turn on -lrt only when building in conda?

Must be some way to do it using CMake I'd imagine. I'm not a CMaker though, so can't really help here.

**Comment by molpopgen** [comment]
> molpop



> I think this issue is possibly that   Tthe build environment for conda is a super old CentOS environment (for compatability reasons), so it needs to work with old compilers/libc versions. I don't know though, it is odd that OSX and linux both fail to compile on the clock issues though. Maybe others will have hit this issue? It seems like a small and entirely fixable thing, so it'd be great to get to the bottom of it. @molpopgen, have you hit this when doing bioconda builds?

On occasion.  Part of the issue is different OS maintainers having difference glibc with different standards for the C++ headers.  @bhaller -- you may want to try to include `ctime.h` instead of `time.h` so that you use `std::time` instead of `time` as the function call.  Ideally, the build system would allow one to check for the existence of functions in different headers, but that is easier with `autools` than with `cmake`.

**Comment by molpopgen** [comment]
Does `conda forge` have an autobump feature?  If not, then `bioconda` may be preferable if we're not doing windows builds.  They allow a recipe to request that a bot monitor for new releases and auto-update he recipe and rebuild

Also, you can just tell Windows users to install via a Linux conda in the Ubuntu subsystem on Windows 10 or later.

**Comment by jeromekelleher** [comment]
> Does conda forge have an autobump feature? If not, then bioconda may be preferable if we're not doing windows builds. They allow a recipe to request that a bot monitor for new releases and auto-update he recipe and rebuild

There are various bots out there for conda-forge. The one that's used for pypi works great anyway, perhaps there's one for Github releases as well. The stdpopsim package is in conda-forge and it would be much easier for us if the SLiM package was also in conda-forge.

> Also, you can just tell Windows users to install via a Linux conda in the Ubuntu subsystem on Windows 10 or later.

I'd really like to have a proper windows build so that we can depend on this upstream in stdpopsim. Having to make exceptions for Windows just makes life so much harder than it needs to be. Windows support really shouldn't be that hard for a standalone executable like this.

**Comment by molpopgen** [comment]
Makes sense.  There is no good reason why the slim binary shouldn't compile
on Windows.  However, IIRC, VS has never been fully standard compliant,
even though several of MS's lead software researchers are on the c++
standards committee.  This situation causes a lot of headaches.

**Comment by petrelharp** [comment]
Whoops - it's @brnorris03, not bnorris03! Hi!!

**Comment by npavlovikj** [comment]
I am not sure if this helps, and I am not a C++ developer by any means, but adding `target_link_libraries(${TARGE} rt)` in `CMakeLists.txt` built the package for Linux, e.g.:
```
set(TARGET_NAME slim)
file(GLOB_RECURSE SLIM_SOURCES ${PROJECT_SOURCE_DIR}/core/*.cpp ${PROJECT_SOURCE_DIR}/eidos/*.cpp)
add_executable(${TARGET_NAME} ${SLIM_SOURCES})
**target_link_libraries(slim rt)**
target_include_directories(${TARGET_NAME} PRIVATE ${GSL_INCLUDES} "${PROJECT_SOURCE_DIR}/core" "${PROJECT_SOURCE_DIR}/eidos")
target_link_libraries(${TARGET_NAME} PUBLIC gsl)
target_link_libraries(${TARGET_NAME} PUBLIC tables)
target_link_libraries(${TARGET_NAME} PUBLIC)

set(TARGET_NAME eidos)
file(GLOB_RECURSE EIDOS_SOURCES  ${PROJECT_SOURCE_DIR}/eidos/*.cpp  ${PROJECT_SOURCE_DIR}/eidostool/*.cpp)
add_executable(${TARGET_NAME} ${EIDOS_SOURCES})
**target_link_libraries(eidos rt)**
target_include_directories(${TARGET_NAME} PRIVATE ${GSL_INCLUDES} "${PROJECT_SOURCE_DIR}/eidos")
target_link_libraries(${TARGET_NAME} PUBLIC gsl)
target_link_libraries(${TARGET_NAME} PUBLIC tables)
```

I hope the developers of the package reply to your inquiry, but if not, you can patch the cmake file and use this is a possible workaround.

Moreover, looks like the executables are named "slim" and "eidos" and are in the "build" directory and not PREFIX, so you will probably need to copy them to ${PREFIX}/bin and modify build.sh and meta.yaml accordingly.

**Comment by jeromekelleher** [comment]
Wow, thank you so much @npavlovikj !

**Comment by jeromekelleher** [comment]
We're working through the clock stuff upstream with the developers so that we hopefully don't need to do the real time clock thing. Thanks for the pointer on the executables, we'll keep an eye out for that.

**Comment by jeromekelleher** [comment]
Looks like this is  working: hooray! Before this gets merged we should:

1. Get the changes in the rtc code upstream released in v3.3.2
2. Either update the recipe to link to the external GSL or include the license file for GSL
3. Add more maintainers (@bhaller --- can I add you as a maintainer here? This will give you write access to the repo used for this conda recipe.)

**Comment by petrelharp** [comment]
> can I add you as a maintainer here

I'd like to not be in charge of this, as I often don't use conda, but feel free to add me to spread things around a bit more

**Comment by bhaller** [comment]
> Looks like this is working: hooray! Before this gets merged we should:
> 
> 1. Get the changes in the rtc code upstream released in v3.3.2

That will happen; I'm not sure when, perhaps soon.

> 2. Either update the recipe to link to the external GSL or include the license file for GSL

The GSL license is already included.  It is in a file named COPYING, inside the gsl subfolder.  That's the same filename used in the GSL source code itself, I think; I didn't rename it IIRC.

> 3. Add more maintainers (@bhaller --- can I add you as a maintainer here? This will give you write access to the repo used for this conda recipe.)

Sure, you can add me as a maintainer, although I have no idea what I'd do :->.  Thanks!

**Comment by jeromekelleher** [comment]
OK, great, thanks all. I'll pick this up again when 3.3.2 is shipped. Can you ping me then please @bhaller?

**Comment by bhaller** [comment]
Sure @jeromekelleher, will do.

**Comment by bhaller** [comment]
@jeromekelleher ping!  SLiM 3.3.2 has just been released, containing the changes that were needed for conda-forge compilation.  Thanks!

**Comment by jeromekelleher** [comment]
I updated the recipe @bhaller, but looks like some transient network issues breaking the build. I'll try it again over the weekend.

**Comment by jeromekelleher** [comment]
@conda-forge-admin, please restart ci

**Comment by jeromekelleher** [comment]
This recipe is ready for review  @npavlovikj  @conda-forge/help-c-cpp

**Comment by npavlovikj** [comment]
This looks great @jeromekelleher , I am glad you were able to make the recipe work! Also, thank you for contributing :)

**Comment by jeromekelleher** [comment]
Thank you @npavlovikj!

**Pull request merged**
