### PR TITLE
Apache maven 3.3.9.

### PR DESCRIPTION
**Pull request by johanneskoester**
This PR adds a recipe for the build tool Apache Maven.

### CODE REVIEW

**Comment by johanneskoester** [comment]
I skip windows because I have no time or experience to work on it.

**Comment by jakirkham** [comment]
Toggling for CircleCI, which is currently missing.

**Comment by jakirkham** [comment]
Still no CircleCI. ☹️ Let's wait and see if it gets added. If not, it is probably due to GitHub changing the API on PR statuses.

**Comment by johanneskoester** [comment]
Please let me know if I can do anything. Thanks!

**Comment by ocefpaf** [comment]
@johanneskoester can you try to send an empty commit to see if we can trigger CircleCI?

**Comment by johanneskoester** [comment]
It seems to get worse...

**Comment by jakirkham** [comment]
Is this PR corrupted somehow? What if we try a brand new one?

**Pull request closed without merging**
