### PR TITLE
Adding jupyterlab-h5web

### PR DESCRIPTION
**Pull request by t20100**
~~[jupyterlab-h5web](https://github.com/silx-kit/jupyterlab-h5web/) depends on [h5grove](https://github.com/silx-kit/h5grove) which packaging is proposed in PR #20357.~~ Merged.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by loichuder** [comment]
Ok being a maintainer

**Comment by t20100** [comment]
@conda-forge/help-python, ready for review!

I tested locally by installing from [the CI noarch artifact](https://artprodeus21.artifacts.visualstudio.com/A910fa339-c7c2-46e8-a579-7ea247548706/84710dde-1620-425b-80d0-4cf5baca359d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NvbmRhLWZvcmdlL3Byb2plY3RJZC84NDcxMGRkZS0xNjIwLTQyNWItODBkMC00Y2Y1YmFjYTM1OWQvYnVpbGRJZC81Njk1NDQvYXJ0aWZhY3ROYW1lL2NvbmRhX3BrZ3Nfbm9hcmNo0/content?format=zip) and it works.

I have some questions:

- The license and the copyright in the license file is only for this package, but since in embeds the webapp bundle which is built from a lot of npm packages. Is this an issue?
- I copied the tests from `jupyterlab-git` feedstock and moved them to `run_test.*` to make it pass on Windows. Are the tests really needed on Windows? If I understand well, no-arch packages are then built on linux only.

**Comment by t20100** [comment]
Looking at other react-based jupyterlab extensions, only the license of the project is advertised in `meta.yml`. I guess using dependencies from npm does not need to be advertised here.

**Comment by t20100** [comment]
Closing since it has been added to conda-forge in the mean time: https://github.com/conda-forge/jupyterlab-h5web-feedstock/

**Pull request closed without merging**
