### PR TITLE
SimpleTAL for python3

### PR DESCRIPTION
**Pull request by stuertz**

### CODE REVIEW

**Comment by stuertz** [comment]
@synapticarbors - Please have a look :-)

**Comment by isuruf** [comment]
You need to send this as a PR to https://github.com/conda-forge/simpletal-feedstock

**Comment by synapticarbors** [comment]
There shouldn't be a separate PR in staged-recipes for this. Once the feedstock is created for v4, then the recipe should be updated there for the newer version. The open question is if the v4 series will no longer be updated and all development is going forward on v5. If it isn't then you might need to have two branches in the feedstock, but I'm not entirely sure. I'd need to check with some of core conda-forge folks.

**Comment by stuertz** [comment]
Damn. You're right. - Sorry.

**Pull request closed without merging**
