### PR TITLE
add recipe for conduit 

### PR DESCRIPTION
**Pull request by cyrush**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jan-janssen** [comment]
You still need to add a file named  `conda_build_config.yaml` with:

```
mpi:
  - mpich
  - openmpi
```
https://conda-forge.org/docs/maintainer/knowledge_base.html#building-mpi-variants

**Comment by cyrush** [comment]
thanks @jan-janssen played a bit with offline docker build that included MPI and I had some tests fail during the build.  Even a smoke test that just launches a few mpi tasks. This makes me think my cmake isn't capturing mpiexec when run the conda forge build env. Do you know if there are any recipes that specify the path to mpiexec for testing?

**Comment by jan-janssen** [comment]
Maybe taking a look at a recipe like https://github.com/conda-forge/lammps-feedstock help.

**Comment by cyrush** [comment]
thanks @jan-janssen lammps was a helpful reference.

I tracked down the issue with running my MPI tests. It appears the build container does not have ssh/rsh installed, so mpiexec will fail to launch any MPI jobs.  I think it's best to avoid running my tests when building (things are tested extensively elsewhere)

**Comment by dopplershift** [comment]
I think you should have numpy, zlib, and hdf5 in host and not build. Build is just about the actual build infrastructure, based on [the docs](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-host-and-run). I use scipy as a [good example](https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/meta.yaml)

**Comment by jan-janssen** [comment]
It seems like Mac OS needs `zlib`

**Comment by cyrush** [comment]
@jan-janssen thanks!

there is another more serious issue with my osx builds -- I need to change my linking strategy for my python extension module. It's likely I need a new release or conduit  to fix + will help on all platforms.  zlib + that will likely solve osx. For windows, it seems I need to pin down the right version of hdf5, or exclude python 2 b/c of visual studio constraints.

**Comment by cyrush** [comment]
worked out the build issues across all platforms. :-)

this will be ready after I finalize and tag the conduit 0.5.1  release and update the tarballs and shas.

**Comment by cyrush** [comment]
@jan-janssen  @dopplershift  -- finally made it over the finish line here for all platforms.
Thank you for your suggestions!

**Comment by scopatz** [comment]
Thanks @cyrush!

**Comment by cyrush** [comment]
Awesome -- thanks @scopatz !

**Pull request merged**
