### PR TITLE
Add recipe for pytest-lazy-fixture

### PR DESCRIPTION
**Pull request by nicoddemus**
@TvoroG since you are the owner of the project, would you like to be added as maintainer of the conda package as well?

### CODE REVIEW

**Comment by TvoroG** [comment]
Yeah, ok! Thanks!

**Comment by nicoddemus** [comment]
Done. 👍

**Comment by nicoddemus** [comment]
@conda-forge/core gentle ping. 😁

**Comment by nicoddemus** [comment]
Thanks @ocefpaf!

**Pull request merged**
