### PR TITLE
Add dit recipe

### PR DESCRIPTION
**Pull request by volpatto**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by volpatto** [comment]
@conda-forge/staged-recipes @conda-forge/help-python I would like to kindly request some help for reviewing and eventually merging this PR. It's a pure Python package. I think everything is fine and ready for merging.

**Comment by volpatto** [comment]
@ocefpaf do you have access to "conda skeleton" (where is it implemented?) scripts? Maybe an update could be done there for "script" generation part.

**Comment by ocefpaf** [comment]
> @ocefpaf do you have access to "conda skeleton" (where is it implemented?) scripts? Maybe an update could be done there for "script" generation part.


conda-skeleton is part of conda-build and a SPDX parse (and script update) would be welcomed. Do you want to send a PR?

https://github.com/conda/conda-build/tree/master/conda_build/skeletons

**Comment by volpatto** [comment]
> > @ocefpaf do you have access to "conda skeleton" (where is it implemented?) scripts? Maybe an update could be done there for "script" generation part.
> 
> conda-skeleton is part of conda-build and a SPDX parse (and script update) would be welcomed. Do you want to send a PR?
> 
> https://github.com/conda/conda-build/tree/master/conda_build/skeletons

I will take a look in the scripts, if I feel comfortable (and confident) to submit a PR, I will try to send one. Otherwise, maybe an issue will be enough. The below is the new `script` command?

```
{{ PYTHON }} -m pip install . --no-deps -vv
```

**Comment by ocefpaf** [comment]
Looks like https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L33 is the latest one :smile:

**Comment by volpatto** [comment]
> Looks like https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L33 is the latest one

Oh, sorry! That is right in front of my eyes lol In the example recipe. That confirms the need of update in the conda skeleton script. I used it to generate the present recipe (and all others I already merged). I will take a look there. Thanks!

**Comment by ocefpaf** [comment]
> Oh, sorry! That is right in front of my eyes lol In the example recipe.

Even I did not see that update :smile: 

> That confirms the need of update in the conda skeleton script. I used it to generate the present recipe (and all others I already merged). I will take a look there. Thanks!

Don't worry too much, this is a minor thing. Those extra options are still used. I guess that they are now default in conda-build and, adding them again in the build script, does not do any harm.

**Pull request merged**
