### PR TITLE
Add comet

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This adds a recipe for `Comet`.

### CODE REVIEW

**Comment by bgruening** [comment]
@duncanmmacleod this seems to be a name clash.
Can we name this package python-comet, or pycomet or anything like that?

Thanks!

**Comment by duncanmmacleod** [comment]
Thanks @bgruening!

**Comment by duncanmmacleod** [comment]
@conda-forge/help-python, [the Appveyor build](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/21402631) is failing because it can't find the script the package should be installing:

```
(%PREFIX%) %SRC_DIR%>comet-sendvo --help 
'comet-sendvo' is not recognized as an internal or external command,
operable program or batch file.
```

Can someone help me figure out how to test this script? It seemingly works on Unix.

**Comment by kiwi0fruit** [comment]
@conda-forge-admin @conda-forge/help-python please review.

**Pull request merged**
