### PR TITLE
Add Psychopy

### PR DESCRIPTION
**Pull request by kastman**
Adding a full conda recipe for psychopy.

Still have to work out the pygame dependency (and python-bidi in PR #5734 ), but wanted to see how this would work the remote CI and get input form other psychopy devs.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Great work! I think pyglet should be packaged as well, since no conda package exists for version 1.3 yet? (and it fixes a memory leak with text stimuli which is present in 1.2)

**Comment by kastman** [comment]
Thanks @hoechenberger  - I submitted a PR to the pyglet feedstock to update pyglet (though there are some CI issues that will need to be worked out). 

One question that we need to address is whether to lock versions to what's in the distributed Standalone App here (so that this conda-forge package will for all practical purposes only be useful within a new, separate conda environment), or let the versions float within conda-forge. That's the standard, recommended method, but the only reason I can think of for psychopy to follow that would be for upstream uses (a la OpenSesame), and even then it's probably best to have versions consistent with the standalone. Thoughts @psychopy/core ?

**Comment by kastman** [comment]
json_tricks looks like it works with `noarch` (packages 14 files), but the import fails. Removing `noarch` works successfully. Anyone know why that might be?

**Comment by hoechenberger** [comment]
> One question that we need to address is whether to lock versions to what's in the distributed Standalone App here (so that this conda-forge package will for all practical purposes only be useful within a new, separate conda environment), or let the versions float within conda-forge. That's the standard, recommended method, but the only reason I can think of for psychopy to follow that would be for upstream uses (a la OpenSesame), and even then it's probably best to have versions consistent with the standalone. Thoughts ?

So this is a thing I had been thinking about for quite a while now. @peircej, how do _you_ keep track of which versions go into standalone? I would very much like if we had a list all all packages and their versions included in each standalone release. We could then provide `requirements.txt` files for each release, allowing users and developers to re-create the "standalone environment" without having to install standlone; this could also be used for CI testing (i.e., Travis).

As for your question, @kastman, I would prefer to have versions free-floating (except maybe for pyglet, which should be forced to 1.3+), as this is what I would expect when installing a package via `conda`. Additionally, we should provide `environment.yml` files with versions locked to those included in each standalone release. Again, this would come in handy for users, developers, and CI testing.

**Comment by peircej** [comment]
In short, I don't keep track of what versions are in Standalone! I take the opposite approach of *trying* to make PsychoPy compatible with all versions of the libs as far as possible. What goes into Standalone on each release is just whatever versions I currently have installed on my dev machines.

**Comment by hoechenberger** [comment]
> I'm OK with the notion, as long as it doesn't lead people to think that this fixes everything and we can stop supporting older versions of libs!

Absolutely agree!


> I imagine pip freeze will
> 
> give more libs that are strictly needed (anything on my python install?)

Yes, but this is okay -- `conda env export` does a very similar thing; since those `requirements` and `environment` files will be used to create a new, independent virtual environment, including implicit dependencies is actually not a bad thing.

> and also not everything that's needed (e.g. some libs not pip-installed)

That's probably just a handful of packages, right?

> be platform specific (which freeze set would we publish and how?)

Platform-dependencies is annoying, I've had to deal with this myself recently, and ended up providing separate environments for macOS, Windows, and Linux.

> but I guess it's OK for a rough pointer

Absolutely!

**Comment by kastman** [comment]
I’ve been wondering that too in connection with useVersion().

`pip freeze` will grab everything, but if we want to have a command line install that’s closest to the standalone all those things are correct to include. A good template is this large microbial analysis toolbox : https://docs.qiime2.org/2018.4/install/native/#install-qiime-2-within-a-conda-environment where they have conda packages but also distribute environment files for different architectures. 

It’s probably more work than it’s worth, but I wonder if we can use CI to build the standalones. That would ideally decrease the number of “incidental” packages and make the release more robust, if day, one of your dev boxes dies?

**Comment by hoechenberger** [comment]
(I would like to second that and wanted to add that ideally the conda packages would also be built / tested via CI, but let's discuss the other things first ;)))

**Comment by hoechenberger** [comment]
> I’ve been wondering that too in connection with useVersion().

x-ref https://github.com/psychopy/psychopy/issues/1397

**Comment by peircej** [comment]
CI builds of Standalone would be great but it would be hell to debug py2app failures from a CI environment (it's nasty enough on a local machine!), and we'd also need a way to post back the resulting file to some server. I've never seen anyone do this and don't fancy it!

Recall my preferred alternative to stop building Standalones altogether and provide an installer script/mini-app that downloads and installs things using pip (or conda I guess) #1768
It would allow users to install to e new env in their existing python or to a new separate Python, and it would be using a regular python that would be easier to find form PyCharm/Spyder...

**Comment by hoechenberger** [comment]
> Recall my preferred alternative to stop building Standalones altogether and provide an installer script/mini-app that downloads and installs things using pip (or conda I guess) #1768

Heh, now _that_ would be an argument to actually invest quite some work into figuring out how to produce those `requirements` and `environment` files for different platforms in an ideally fully-automated manner! :)

**Comment by peircej** [comment]
I still prefer the idea that we let pip install the latest version of each lib and then we fix it to work with that version if needed, rather than saying we require a specific version

**Comment by hoechenberger** [comment]
Oh, now I get what you meant. When there is no standalone anymore, then the need to have fixed version numbers for all dependencies goes away, too. Makes sense!

**Comment by kastman** [comment]
Ok, this is helpful at least from a conda setup perspective - aside from certain known breaking deps (e.g. `pyglet >= 1.3`; and remember, this _can_ be version dependent) I'll leave versions off the conda package completely. Thanks both!

**Comment by peircej** [comment]
> aside from certain known breaking deps 

Yes, the caveat is that I occasionally find a latest version of something breaks (e.g. sometimes a lib releases a broken version that won't even install!) and then I've briefly put in place a fixed-version requirement. (In the case of pyglet we need to fix psychopy to make it work with 1.3 but I'm talking about worse offenders than that)

> do we then recommend that people include a conda env export or pip freeze when sharing their experiments and data?

Yes, this seems smart.

I do also appreciate that it would be better with useVersion to switch to a virtualenv rather than doing a git checkout, but it just seems harder to do, no?

**Comment by kastman** [comment]
I know a lot less about virtualenv (which I experimented with to some meh moderate success before really embracing conda), but I suspect that we could probably the convert from using `git` to `conda` without too much trouble; I've actually been considering taking a shot at that. 

The caveat would be that people have conda or virtualenv installed before they could use that, which I think is reasonable. It's not quite as nice as git, which you can get for OSX just from `xcode-select --install`.

**Comment by kastman** [comment]
Also, the point from the [old thread 1397](https://github.com/psychopy/psychopy/issues/1397) about compiling the psyexp from a command-line and using whichever version is requested in `useVersion()` is a good one; you were working on that for the 1.90 release IIRC?

**Comment by peircej** [comment]
got part way there - I wrote the script to do it 
https://github.com/psychopy/psychopy/blob/master/psychopy/experiment/compileScript.py
but Builder doesn't make use of that script yet!

**Comment by kastman** [comment]
@peircej  @hoechenberger Made a little progress; I'm now getting a gtk X11 error on circleci (osx) when importing `psychopy.app.builder`:

`ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory`

Is this something we've solved on the main CI, or am I forgetting a gtk dependency? Seems like GTK would be a prime candidate for conda, but I can't find one, whcih seems odd. It appears that the build itself was successful, so this may have to do with the sparse testing environment? I'm running this locally to see if it works here.

Also, pyparallel is failing on windows with what looks like a ctypes problem: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.23695#L2027  . Any suggestions here?

**Comment by hoechenberger** [comment]
> @peircej @hoechenberger Made a little progress; I'm now getting a gtk X11 error on circleci (osx) when importing psychopy.app.builder:
> 
> ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
> 
> Is this something we've solved on the main CI, or am I forgetting a gtk dependency?

I don't think we've ever had CI tests running on macOS :) At least not as long as I can remember!

> Also, pyparallel is failing on windows with what looks like a ctypes problem: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.23695#L2027 . Any suggestions here?

This is a [known problem](https://github.com/pyserial/pyparallel/issues/7); however it should not concern us, since PsychoPy requires `pyparallel` for parallel port access on Linux only. So you don't have to build a `pyparallel` Windows package.

**Comment by hoechenberger** [comment]
And we don't need `pyparallel` for macOS either :)

**Comment by kastman** [comment]
Wait, the psychopy CI is linux only?  I only just now realized we're only using Travis and not circle too. Ok, well, I at least need to include wx, which wasn't included yet as it wasn't picked up by the basic `conda skeleton pypi` creation.

I see in the psychopy CI that we test against both wx 3 and 4; do we need to pin that here? 

Re: pyparallel; I'm ditching it for anything but linux then. Thanks for the link.

**Comment by hoechenberger** [comment]
> Wait, the psychopy CI is linux only? I only just now realized we're only using Travis and not circle too. 

Yes, we're not even testing on Windows, which is probably the platform most users have… It's been on the todo list for…ever. :)

> I see in the psychopy CI that we test against both wx 3 and 4; do we need to pin that here?

There was a rather painful transition from 3 to 4, this is why we started testing on both: only wxpython-4 is Python 3 compatible (in fact it supports both Python 2.7 and Python 3); wxpython-3 is Python-2 only. So I would assume that it's safe to pin it to wxpython-4.

> Re: pyparallel; I'm ditching it for anything but linux then. Thanks for the link.

Nice job!

**Comment by hoechenberger** [comment]
> Heh, you should disappear for 2 or 3 years like I did and see how great it is to not remember this history. ;)

Maybe I should ;) Sounds liberating *laughing*

> Looks like the build including wxpython==4 is still failing at the same spot, so I suspect this might still be a headless CI issue for builder?

You mean on CircleCI? Seems to me that it's (still) lacking the GTK libs, no?

**Comment by kastman** [comment]
And the windows build is missing libsndfile (and therefore pysoundfile) which i believe is actually in use. There is a [template](https://github.com/erikd/libsndfile/blob/master/appveyor.yml) and an [open issue](https://github.com/conda-forge/libsndfile-feedstock/issues/4) on the feedstock; maybe worth fixing?

**Comment by hoechenberger** [comment]
> And the windows build is missing libsndfile (and therefore pysoundfile) which i believe is actually in use. There is a template and an open issue on the feedstock; maybe worth fixing?

Could be worth fixing, yes.

Getting the impression the conda packages will be more thoroughly tested than PsychoPy by its own CI ;)

**Comment by kastman** [comment]
> >     Looks like the build including wxpython==4 is still failing at the same spot, so I suspect this might still be a headless CI issue for builder?
> You mean on CircleCI? Seems to me that it's (still) lacking the GTK libs, no?

Yes, I was hoping that wxpython would magically pull in the gtk libs somehow, but I don't believe that's the case. GTK looks like an utter mess to package, and given that no one has done it on conda-forge yet I suspect that's for real. Do you know off the top of your head if psychopy still uses the older pygtk, or has it switched to pygobject? Even the domain name registered with pip redirects from pygtk to pygobject now. Ugh.

> Getting the impression the conda packages will be more thoroughly tested than PsychoPy by its own CI ;)

Ha, no, just the packaging. I'll stop bugging you about it now and go fix some stuff. :)

**Comment by hoechenberger** [comment]
Since I can run the app on my Mac without having GTK installed – could be worth trying to install qt and see if it would automatically be used as a fallback? (I think that's what happening on my computer, but cannot check now.)

**Comment by hoechenberger** [comment]
Well that didn't work. Ugh… Anyway, off to bed now ;)

**Comment by kastman** [comment]
Just an update - currently the psychopy recipe is really only waiting on `libsndfile`. It's tricky because the released version of `libsndfile` has outdated cmake files that don't build on windows, although there are updates in `master` that will fix this. The developers won't patch the release with updated cmake files (sounds like they will only do it with a new version, which won't be released until "other bugs" are fixed). The best solution is to provide patches in conda, but I just haven't gotten around to it yet. 

As soon as libsndfile is in conda, I think we're actually ready to take a stab at a psychopy conda-forge release.

**Comment by kastman** [comment]
Actually, I take it back that linux/mac are ready to go; it looks like Travis is failing on a window test on linux, and gtk is attempted to be imported by wx on mac. I'm not sure how to tell if the Travis issue is is just a headless circle / traivs CI test problem (that should be skipped) or a real problem. 

@peircej any idea why importing wx on OSX would attempt to look for, and not find, gtk?

PS - 1.90.2 is now available for useVersion().

**Comment by kastman** [comment]
Sorry, I was wrong: Travis is the Mac build, which is [first failing for the crs import](https://travis-ci.org/conda-forge/staged-recipes/builds/373307888#L897) when trying to open a pyglet window:

```
import psychopy.hardware.crs
pyglet.window.NoSuchConfigException: No standard config is available.
1.8260 	WARNING 	Monitor specification not found. Creating a temporary one...
```
Is it possible this is a headless problem that's just a test artifact? Pyglet is in both build and run environments. Or possible that this is raising an error even when it should more likely be a warning, or handled later?

--- 

For linux (Circle), the problem is an error trying to import `wx`. However, `wxpython` is in both the build and run environments. It looks like wx is looking for libgtk but not finding it; perhaps the conda package was built against a version that's unavailable? I do see in the wxpython conda-forge feedstock that there's a "yum_requirements" file indicating that libgtk should be installed, but shouldn't that be pulled along upstream?

**Comment by kastman** [comment]
@conda-forge-admin please rerender

**Comment by scopatz** [comment]
rerender is only for feedstocks, not staged-recipes

**Comment by kastman** [comment]
@scopatz d’oh! Thanks. Was just trying to get this started. Pulling in from master instead?

**Comment by kastman** [comment]
@peircej - 

@hoechenberger and I are going to make another run at the psychopy package. 

I'm currently seeing again where we left off on this PR (building 1.90.2 as it's the end of the psychopy2 tree and may be worthwhile?), but is there an easy place to find which dependencies have been added and removed from psychopy 2 to 3 besides just walking through the changelog?

**Comment by hoechenberger** [comment]
> I'm currently seeing again where we left off on this PR (building 1.90.2 as it's the end of the psychopy2 tree and may be worthwhile?), but is there an easy place to find which dependencies have been added and removed from psychopy 2 to 3 besides just walking through the changelog?

I don't think so, but have a look at the conda environments we use for Travis testing:
https://github.com/psychopy/psychopy/tree/master/conda

Don't bother to build PsychoPy 1.x; PsychoPy 3 _still_ supports Python 2.

**Comment by hoechenberger** [comment]
I would also suggest to drop the `pygame` package here, it's not required.

**Comment by hoechenberger** [comment]
Additionally, I would suggest to massively trim down the `tests` section of the recipe.

**Comment by hoechenberger** [comment]
We need to be aware of platform-dependent requirements. For example, on macOS we need `python.app`; on Windows, we need `pywin32`or `pypiwin32` etc.
And PsychoPy's `setup.py` now creates an entry point, we will want to add this to the recipe as well.

**Comment by hoechenberger** [comment]
One important new addition is [psychHID](https://github.com/kleinerm/Psychtoolbox-3/tree/master/PsychPython), which I never got to compile on my Mac. But Jon knows how to do it! :)

**Comment by hoechenberger** [comment]
I'm starting to think we should start with a fresh fork :)

**Comment by peircej** [comment]
Indeed, this is looking like the longest open pull request I've ever seen! :-)
I did manage to compile psychtoolbox and pushed that as a wheel to pypi. Can you install from there? There are some fixes coming that way soon as well (next week I think)

**Comment by hoechenberger** [comment]
> I did manage to compile psychtoolbox and pushed that as a wheel to pypi. Can you install from there? There are some fixes coming that way soon as well (next week I think)

Cool! We need to get it to compile on the `conda-forge` CI services (we need to package it on `conda-forge`, as it will be a dependency of our `psychopy` package), so any guidance on how to compile it would be of help! :)

**Comment by peircej** [comment]
The issue I had was getting the correct version of the MacOS SDK installed (and I'm afraid I've now forgotten which one it needs). Having got that right it "just worked" I think.

**Comment by kastman** [comment]
@hoechenberger I'm happy to do the legwork on switching to a new PR, unless you have a skeleton done already! I agree starting fresh is a good way to go. Should we switch to pushing as the psychopy org so that any one of us has permission to push?

For psychtoolbox, I've seen conda wheel-only packages, so it's possible if we cna't get it, but a recipe would be nice and self-documenting so worth a shot.

**Comment by hoechenberger** [comment]
@kastman I created a new organization (was just the easiest and cleanest thing to do for now) and invited you. I've added a basic recipe there that builds successfully locally for me on the Mac.

https://github.com/psychopy-conda/staged-recipes/tree/psychopy

You can close this PR.

**Pull request closed without merging**
