### PR TITLE
Add cdshealpix recipe

### PR DESCRIPTION
**Pull request by fxpineau**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there (I am the only listen maintainer).
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.
- [X] + I successfully run `CONFIG=linux64 ./.scripts/run_docker_build.sh` on my local machine

### CODE REVIEW

**Comment by wolfv** [comment]
It looks like this is linking in a bunch of static dependencies through Rust... you might need to hunt down the licenses for all of these :/

Maybe @bollwyvl has some tips for that?

**Comment by fxpineau** [comment]
> It looks like this is linking in a bunch of static dependencies through Rust... you might need to hunt down the licenses for all of these :/
> 
> Maybe @bollwyvl has some tips for that?

Here the result of `cargo license` on the project (everything seem to have at least one license in BSD or MIT):
```
Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT (1): wasi
Apache-2.0 OR BSL-1.0 (1): ryu
Apache-2.0 OR MIT (56): autocfg, autocfg, base64, bitflags, bstr, c2-chacha, cast, cdshealpix, cfg-if, criterion, criterion-plot, crossbeam-deque, crossbeam-epoch, crossbeam-queue, crossbeam-utils, crossbeam-utils, either, getrandom, hermit-abi, itertools, itoa, lazy_static, libc, num, num-bigint, num-complex, num-integer, num-iter, num-rational, num-traits, num_cpus, ppv-lite86, proc-macro2, quote, rand, rand_chacha, rand_core, rand_hc, rand_os, rand_xoshiro, rayon, rayon-core, rustc_version, scopeguard, semver, semver-parser, serde, serde_derive, serde_json, syn, tinytemplate, unicode-width, unicode-xid, winapi, winapi-i686-pc-windows-gnu, winapi-x86_64-pc-windows-gnu
MIT (4): atty, clap, memoffset, textwrap
MIT OR Unlicense (9): byteorder, csv, csv-core, katex-doc, memchr, regex-automata, same-file, walkdir, winapi-util
```

**Comment by wolfv** [comment]
can you extract the license texts of these?

This is probably what this should look like: https://github.com/conda-forge/wasmer-feedstock/blob/682a7bf5ac5e723176e3a34fc32880b4adcae022/recipe/meta.yaml#L80

It's a pretty frustrating situation though, I understand that.

**Comment by fxpineau** [comment]
@wolfv  @bollwyvl thank you very much for your feedbacks.

I made a Rust code using the JSON output of `cargo license --json` to download the license texts of all static dependencies.  
Taking the example of [wasmer](https://github.com/conda-forge/wasmer-feedstock/tree/682a7bf5ac5e723176e3a34fc32880b4adcae022/recipe) you pointed out (thanks again), I put all of these in the [library_licenses](https://github.com/cds-astro/staged-recipes/tree/cdshealpix/recipes/cdshealpix/library_licenses) directory and added each file to [meta.yaml](https://github.com/cds-astro/staged-recipes/blob/cdshealpix/recipes/cdshealpix/meta.yaml).

**Comment by wolfv** [comment]
Great! Is the code you used something you could share?

**Comment by fxpineau** [comment]
@wolfv @bollwyvl 

Thank you for the merge.

I just published on [github](https://github.com/cds-astro/get-license-helper) and [crates.io](https://crates.io/crates/get-license-helper) the code that helps me in retrieving the licenses.  
There is room for improvements, but if it may already help someone else...

**Comment by bollwyvl** [comment]
Very nice! I think of course it would be helpful if both it and
cargo-licenses were in conda-forge, as many people (such as myself) just
want to package rust stuff for conda-forge, not develop in it. There's also
the concern of "but what if it changes?!", but trying to infer tag naming
schemes is a mug's game.

Best of all would be getting it into `grayskull cargo`.... But as rust gets
embedded into deeper parts of stacks (e.g. setup tools integration), this
would be less useful.

End of the day, I yearn for package managers, including conda, to adopt
some kind of... Exchange file format. For Data. About Packages. Of
Software. If only there was such a XDPS!

**Pull request merged**
