### PR TITLE
Boost recipe without python bindings for osx and linux

### PR DESCRIPTION
**Pull request by isuruf**
This is an attempt to split boost libraries and the python library. This recipe is the same as the boost recipe except that this does not build the python bindings on linux and osx and therefore doesn't depend on python. See conda-forge/boost-feedstock#1. 

Diff from boost-feedstock https://gist.github.com/isuruf/1797b33871f90f01a74d24e1970ea580

Next step would be to have boost-feedstock recipe depend on this package boost-cpp and build only the python libraries. If you have any suggestions for the name (instead of `boost-cpp`), let me know.

This approach does not break any packages depending on boost. Another approach to solve conda-forge/boost-feedstock#1 would be to change boost-feedstock recipe to build without python and have a new package boost-python that does.

cc @ccordoba12, @jakirkham, @msarahan, @ocefpaf, @jschueller

### CODE REVIEW

**Comment by scopatz** [comment]
From the conversation on the boost feedstock, I can see what this is needed. I am -1 for splitting up packages a la debian style.  I think that packages should come batteries included. I think we should make it more clear that this is the exception rather than the rule.

**Comment by jakirkham** [comment]
So I'd actually like to have a Boost recipe without Python on Windows too. That was one of the big motivators for that discussion. Would it be possible to get Windows to be Python free as well?

**Comment by isuruf** [comment]
@jakirkham, we can, but it's still tied to Python at runtime because of MSVC version.

**Comment by isuruf** [comment]
@jakirkham, ping

**Comment by isuruf** [comment]
ping

**Comment by jschueller** [comment]
seems good
we'll have to modify quite a few feedstock that rely on boost-cpp only

**Comment by isuruf** [comment]
Yes, they'd still work though if `boost` had `boost-cpp` and the python library.
What do you think about the name `boost-cpp`? `boost-nopython` is another alternative.

**Comment by jschueller** [comment]
The name is okay.
We just might want to make sure what we want in the boost package, it's either:
- boost-cpp + boost => "boost" provides python libs
- boost + boost-python => "boost" provides only cpp
But I think boost-cpp + boost is okay ; worst case we have unused python libs and the package builds anyway,
else if we create a boost-python the packager might wonder why python libs aren't included.

**Comment by isuruf** [comment]
ping

**Comment by scopatz** [comment]
I don't think I grok the use-case well enough...

**Comment by scopatz** [comment]
...to review. But others should feel free to review and merge.

**Comment by isuruf** [comment]
Issue is that boost library is compiled with boost-python which is compiled against different python versions. Therefore there are different versions of boost for different python versions.
For C++ libraries that uses boost libraries, but not boost-python, this introduces a dependency on python and therefore that C++ library can be installed only in a specific version of python.

**Comment by jakirkham** [comment]
> we can, but it's still tied to Python at runtime because of MSVC version.

Understood. Still I think it is good thing.

**Comment by isuruf** [comment]
Tests pass now

**Comment by isuruf** [comment]
ping

**Comment by isuruf** [comment]
ping

**Comment by jschueller** [comment]
looks good, some changes could be contributed to the current boost-feedstock first though

**Comment by isuruf** [comment]
> looks good, some changes could be contributed to the current boost-feedstock first though

Submitted to boost-feedstock in conda-forge/boost-feedstock#24

**Comment by jschueller** [comment]
also boost is 1.63 now
could you post the diff between boost-cpp and the updated boost recipe somewhere ?

**Comment by isuruf** [comment]
https://gist.github.com/isuruf/1797b33871f90f01a74d24e1970ea580

**Comment by isuruf** [comment]
Tests pass now. Ready for merge.

**Comment by jschueller** [comment]
could you backport changes from https://github.com/conda-forge/boost-feedstock/pull/26 ?

**Comment by jschueller** [comment]
ah yes sorry

**Comment by jschueller** [comment]
we will even have to disable one of 3.5 and 3.6 then when this gets rerendered

**Comment by isuruf** [comment]
@jschueller, yes. I'll do that in the feedstock.

**Comment by isuruf** [comment]
@conda-forge/core can we get this in?

**Comment by ocefpaf** [comment]
This one waited a lot. If someone is against merging it we can work on that later. Sorry for the long wait @isuruf.

**Comment by isuruf** [comment]
Thanks. np.

**Pull request merged**
