### PR TITLE
Readd failed recipes and revert #2857

### PR DESCRIPTION
**Pull request by isuruf**
This reverts #2857 and readds 2 failed builds. cc @pkgw, @ocefpaf, @jakirkham, @bgruening

### CODE REVIEW

**Comment by bgruening** [comment]
@isuruf my :+1: you have :)

**Comment by isuruf** [comment]
@conda-forge/staged-recipes, don't merge PRs until this is in.

**Comment by isuruf** [comment]
I'm going to merge this and see if it improves the situation.

**Comment by jakirkham** [comment]
Thanks @isuruf. FWIW I agree with you that `--allow-empty` should not have been there. I think that this caused an issue that we saw yesterday with `r-rzmq`. Were there other feedstocks that you know of that were affected?

cc @croth1

**Comment by isuruf** [comment]
`r-coda` was affected as well. See my comment here https://github.com/conda-forge/staged-recipes/pull/2857#issuecomment-298180628

**Comment by jakirkham** [comment]
Looks like you already fixed that. Thanks for taking care of it. If there are other things you need me to do here, please let me know.

**Pull request merged**
