### PR TITLE
Add tesserocr-feedstock

### PR DESCRIPTION
**Pull request by Chilipp**
Closes https://github.com/sirfz/tesserocr/issues/196

This PR adds a new recipe for the tesserocr package (https://github.com/sirfz/tesserocr), a Python wrapper for the tesseract-ocr API.

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

- [x] @sirfz: Please ping any other Github user that should be included as maintainer in the recipe,  here in this thread
- [x] Skipping build for Windows and Python 2.7 - Approved by @sirfz

### CODE REVIEW

**Comment by Chilipp** [comment]
Alright! I think this is ready to be reviewed @conda-forge/help-python-c 

@sirfz: I pinned the recipe to the PATCH version of tesseract (i.e. if the package has been built with tesseract 4.1.0, it will not work with 4.1.1). This is a pretty strong dependency and I would like to know from you, whether it can be relaxed.

**Comment by sirfz** [comment]
Hi @Chilipp, thanks for your effort!

I'm not sure I can answer the version-dependency question as this is more related to tesseract itself rather than tesserocr. However, I think it's safe to assume compatibility between MINOR versions (purely based on experience and not knowledge) if you wish to relax the dependency.

I don't have anyone in mind right now to add as a maintainer but if anyone is interested please let us know.

I'm good with everything else :)

**Comment by Chilipp** [comment]
Thanks for the feedback @sirfz!

> I think it's safe to assume compatibility between MINOR versions

Alright, done by https://github.com/conda-forge/staged-recipes/pull/9734/commits/428adcbf1cb57c3b1cd1495d7727adf259bd19dd

As soon as the CI finishes, the PR is ready to be merged (from my perspective) but probably @conda-forge/help-python-c have some comments

**Comment by sodre** [comment]
thanks @Chilipp and @sirfz

**Comment by Chilipp** [comment]
Thank you very much @sodre for the quick support!

**Pull request merged**
