### PR TITLE
conda skeleton r-ggdark

### PR DESCRIPTION
**Pull request by winni2k**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by winni2k** [comment]
I am happy to be listed as the maintainer of this recipe.

**Comment by winni2k** [comment]
@conda-forge/help-r could I please get a review? Thanks!

**Comment by cbrueffer** [comment]
Hi @winni2k , could you regenerate the recipe with https://github.com/bgruening/conda_r_skeleton_helper ?

**Comment by winni2k** [comment]
There's an issue with the LICENSE file. The file only contains the copyright notice and not the MIT license itself. It appears as if the author might have misunderstood the instructions in the CRAN documentation.

**Comment by winni2k** [comment]
> Hi @winni2k , could you regenerate the recipe with https://github.com/bgruening/conda_r_skeleton_helper ?

Sure thing!

**Comment by winni2k** [comment]
All done. The skeleton helper did not create a LICENSE file. I have left in the one I copied over from the CRAN ggdark source tar.

**Comment by cbrueffer** [comment]
Looks good! You can remove the LICENSE file, the one from the CRAN tarball will be automatically packaged since it's listed in the meta.yaml.

**Comment by winni2k** [comment]
Ok, excellent.

**Pull request merged**
