### PR TITLE
Next round of X.org libraries: libICE libSM libXext libXfixes libXi

### PR DESCRIPTION
**Pull request by pkgw**

### CODE REVIEW

**Comment by pkgw** [comment]
OK, this is currently blocked on the fact that `xorg-libx11` has `python` as a build-time dependency, which brings in `tk` as a dependency, and the `tk` package on OSX includes dummy versions of X11 headers as per [tk issue #15](https://github.com/conda-forge/tk-feedstock/issues/15). So, when the OSX `xorg-libx11` package is built, it's missing `cursorfont.h`, `Xlib.h`, and `Xutil.h`, which then causes problems when building `xorg-libxext` here.

[tk PR #17](https://github.com/conda-forge/tk-feedstock/pull/17) adds `xorg-libx11` as a dependency of `tk`, which (even in its current incomplete form) provides enough headers for `tk` to build successfully and decide not to install its dummy X11 headers. If that goes through then we can rebuild `xorg-libx11` on OSX to get a complete package, and then move forward here.

**Comment by jakirkham** [comment]
To try to start unblocking `xorg-libx11`, you could set [`always_include_files`]( http://conda.pydata.org/docs/building/meta-yaml.html#force-files ). That way it will include the headers from `xorg-libx11` even if `tk` provides them. Eventually I'm guessing they can be dropped once `tk` gets fixed.

**Comment by pkgw** [comment]
Temporarily closing to kick Travis, since I don't think the "Restart build" button is doing anything.

**Comment by pkgw** [comment]
OK — this builds on OSX with the `xorg-libx11` that has the `tk` workaround in place. Once again, would appreciate a quick merge so I can make more progress while the CI systems are in low demand over the weekend.

**Pull request merged**
