### PR TITLE
MOAB

### PR DESCRIPTION
**Pull request by scopatz**
This is a recipe for MOAB, a mesh representation library.  

Perhaps @pshriwise or @gonuke or @vijaysm also have some ideas of who might want to be a maintainer.

### CODE REVIEW

**Comment by scopatz** [comment]
OK this builds now! Any chance someone could take a look please?

**Comment by scopatz** [comment]
Thanks!

**Comment by vijaysm** [comment]
Sorry, a little late to the review here. You can add me as an additional maintainer if needed.

Also, I see that --with-mpi is not specified during configuration, even though mpich is a dependency. This would configure MOAB with only serial support. If this is fine, I don't have a problem. Just wanted to point out that this is inconsistent if you were expecting a parallel MOAB library to be built and installed.

**Comment by scopatz** [comment]
OK great @vijaysm! I am adding you as a maintainer here: conda-forge/moab-feedstock#1.  Please feel free to add anyone else who you think should be a maintainer.  

As per the parallel issue, I was getting build failures when using `--with-mpi` and so I removed it. Maybe this means we should remove the mpich dependency, but I think it would be ideal if someone more familiar with parallel MOAB took a stab at fixing it in the feedstock.  

We could also VTK too, if we wanted. However, my whole goal here was simply to get a package that PyNE could link against.  The current one seems to be good enough for that, and I do welcome improvements!

**Comment by vijaysm** [comment]
@scopatz Thanks. I can take a look at what the issue was with the MPI configuration. Shouldn't be hard to figure out. 

Why do you need VTK ? The only place we need VTK is for creating a visualization plugin for ParaView. While this is good in its own way, it requires you to build Paraview from source. So, that may not be flexible enough depending on the workflow.

We have been working with LLNL to create a native, fully parallel, MOAB plugin for VisIt that should hopefully make it to their next release. There are few minor kinks to work out in the dependency build system but we hope to have that working soon. So when that becomes official, new version of VisIt will be able to read MOAB h5m directly (in parallel) to support your visualization and post-processing needs.

**Comment by scopatz** [comment]
Oh, we don't need VTK, I was just mentioning that a VTK package is available in conda-forge.  The VisIt stuff sounds great too! I would be a great to have a VisIt package as well... maybe I should ping someone about that (Cyrus?).

Thanks for offering to take a look at the MPI issue.  You just need to open an PR against the feedstock repo with the change to have the CI trigger a build.

**Pull request merged**
