### PR TITLE
Add recipe for pyreaddbc

### PR DESCRIPTION
**Pull request by luabida**

### CODE REVIEW

**Comment by xmnlab** [comment]
Thanks for working on that @luabida !
@esloch please confirm you are ok to be listed here as a maintainer pls

**Comment by luabida** [comment]
> * Non noarch packages should have python requirement without any version constraints.

@xmnlab is it ok? Python version is pinned on the package

**Comment by xmnlab** [comment]
@luabida try to use this for the poetry install command: `poetry install --only-root`

**Comment by xmnlab** [comment]
For some reason it seems poetry is using the venv `tmp/tmpurc5w91s/.venv/bin/python`

**Comment by xmnlab** [comment]
Maybe something that you could try would be move back to pip install instead of poetry install .. but adding `--no-deps` to the command

**Pull request closed without merging**
