### PR TITLE
Testinfra

### PR DESCRIPTION
**Pull request by knightdave**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by knightdave** [comment]
@conda-forge-admin, please relint

**Comment by knightdave** [comment]
Hi @conda-forge/core
I think there is a problem with linter. I had to rebase my branch due to use wrong email in commits, and after creation of new MR, linter is dropping always an error.

**Comment by dbast** [comment]
@knightdave please rename the meta.yml to meta.yaml, that should make the linter happy and also make the CIs to actually build the recipe.... Please also remove all the comments in the meta.yaml...

**Comment by knightdave** [comment]
> @knightdave please rename the meta.yml to meta.yaml, that should make the linter happy and also make the CIs to actually build the recipe.... Please also remove all the comments in the meta.yaml...

Done

**Pull request merged**
