### PR TITLE
Add pykerberos

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This adds a recipe for `pykerberos`, mainly to enable having a conda-forge version that can be rebuilt along with the conda-forge version of `krb5`, rather than trying to match up with the anaconda version of `pykerberos`.

This, I think, supersedes #2701.

**I am not a contributor to `pykerberos`, and have no real idea how it works, so if anyone else should be named as a recipe maintainer, please post comments and I will add names.**

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/staged-recipes, @conda-forge/help-c-cpp, this build fails for the same reason as #2701, namely that the `gssapi/gssapi_generic.h` header isn't included in the `krb5` package on windows. I have no idea whether this is 'standard', so would appreciate some advice on whether this is an issue with `krb5`, or whether this package should just `skip: true  # [win]`.

**Comment by duncanmmacleod** [comment]
@nehaljwani, I would like to duplicate your patch from https://github.com/AnacondaRecipes/aggregate/commit/3890c494d6e3ffd16c942a1d6da79e4d660986f1 in this recipe, is there a license for that patch, or can you give me permission to duplicate it?

**Comment by nehaljwani** [comment]
@duncanmmacleod I am no expert on Licenses, but all custom work in that repo would probably fall under: https://github.com/AnacondaRecipes/aggregate/blob/master/LICENSE.txt (although it was added later). In any case, you have my permission to use that anywhere you want.

**Comment by duncanmmacleod** [comment]
@conda-forge/staged-recipes, I think this is ready for review now. I have adde `skip: true  # [win]` in line with the upstream `defaults` package.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
