### PR TITLE
Django braces

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by mwcraig** [comment]
@cshaley -- can you please confirm that you are willing to be listed as a maintainer on this?

**Comment by cshaley** [comment]
yes

**Comment by synapticarbors** [comment]
@cshaley - Are you ok being a co-maintainer on all of the Django related packages that @sannykr has been submitting? I thought you gave approval a while back, but searching the issues, I can't find it. I might have assumed since you submitted two PRs request and then @sannykr started submitting more at the same time with you as co-maintainer, that you two were working together.

**Comment by cshaley** [comment]
yes!

**Comment by synapticarbors** [comment]
@sannykr - I'll try to continue to review your Django PRs, but could you add a note when you submit them that @cshaley has already agreed to be a co-maintainer in case other reviewers get to looking at the PR before me.

**Pull request merged**
