### PR TITLE
Add R noarch package tidymodels

### PR DESCRIPTION
**Pull request by philip-khor**
Recipe created using conda_r_skeleton_helper and conda-build

### CODE REVIEW

**Comment by bgruening** [comment]
@philip-khor r-tidyposterio is not available on WIn as it seems.

**Comment by philip-khor** [comment]
Windows build for r-tidyposterior needs conda-forge/r-rstanarm-feedstock#4 which in turn requires conda-forge/r-rstan-feedstock#5

**Comment by dbast** [comment]
As this is a nonarch package which will be build on linux via the feedstock after merge, the availability of r-tidyposterio should not matter regarding building it...

**Comment by dbast** [comment]
The recipe itself is fine.

**Comment by dbast** [comment]
Thanks!

**Pull request merged**
