### PR TITLE
Add r-languageserver + dependencies

### PR DESCRIPTION
**Pull request by dbast**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

closes https://github.com/conda-forge/staged-recipes/issues/9707

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge/help-r Ready for review :)

**Comment by bollwyvl** [comment]
I tried the helper script, but couldn't read the tea leaves of the conflict failures properly. You good people are magicians!

**Comment by bollwyvl** [comment]
Looks like there were snags rendering the repos after they got created... I assume that will clear itself up...

**Comment by jdblischak** [comment]
> I tried the helper script, but couldn't read the tea leaves of the conflict failures properly.

@bollwyvl Please feel free to open an [Issue](https://github.com/bgruening/conda_r_skeleton_helper/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) on the helper script repo if it's not working smoothly. Our goal is to make it easy for contributors to create and submit R recipes.

**Comment by bollwyvl** [comment]
@jdblischak thanks! i think my issue is that I just don't know enough about `r` packaging, and conda errors are mysterious, which no amount of tooling was going to fix. The `conda` solve errors came back as `unsatisfiable` rather than `missing`, which didn't indicate that i needed to package more things, but just that it was busted in some way which i would be hard-put to untangle.

**Comment by jdblischak** [comment]
@bollwyvl Oh, I see. The issue was missing dependencies, and not something specific to the helper script.

**Comment by bollwyvl** [comment]
> missing dependencies, and not something specific to the helper script.

Right: if the help script could say, "hold up there, <recipe 1> isn't going to work because <recipe 2> and <recipe 3> aren't available from <channel>". Very tricky to tell with transitive dependencies, versions, etc.

**Comment by bollwyvl** [comment]
All the feedstocks are still empty... do we know what's going on?

**Comment by cbrueffer** [comment]
Several people have reported similar problems; I've asked about solutions on Gitter.

**Comment by cbrueffer** [comment]
Looks like it's starting to work now.

**Comment by jdblischak** [comment]
> Right: if the help script could say, hold up there, <recipe 1> isn't going to work because <recipe 2> and <recipe 3> aren't available from <channel>. Very tricky to tell with transitive dependencies, versions, etc.

@bollwyvl So did you try building the recipe? Is this when you saw the errors? The helper script (and `conda skeleton cran`, which does most of the actual work) are able to produce a recipe for an R package even if its dependencies are not yet available as conda packages.

In the future, I'd recommend submitting the recipe directly to staged-recipes instead of trying to build it locally. Then if the build fails, you can link to the exact error message from the CI logs, and someone from the help-r team could help troubleshoot and interpret the error messages.

That being said, it would be possible to grab the dependencies from the recipe and then search for their availability via `conda search`. I don't have the time to implement that at the moment, but if you or someone else is interested it would be a useful addition.

Also note that there is an existing flag `--recursive` to `conda skeleton cran`:

```
   --recursive          Create recipes for dependencies if they do not already
                        exist. (default: False)
```

However, I'm not sure how they define if a recipe "exists". I tried it and it created a recipe for every single recursive dependency, even those that are obviously available from both the conda-forge and defaults channels.

**Comment by bollwyvl** [comment]
Thanks for getting to the bottom of the empty feedstocks!

Yeah I tried the build after the helper. The errors (now lost) are very
similar to the fails on the first build of language server for the older
runtimes on azure... I probably want pulling the newest. Again, forgive me,
I know very little about r, just trying to do the multi-language hustle for
some jupyter stuff!

**Comment by jdblischak** [comment]
> Again, forgive me,
I know very little about r, just trying to do the multi-language hustle for
some jupyter stuff!

@bollwyvl No worries! I know how bewildering it can be when trying to figure out the packaging system of an unfamiliar language. Thanks for all your assistance getting these new R packages on conda-forge!

**Comment by bollwyvl** [comment]
You bet, and thank you! We should have some in-jupyterlab r code assistance
to show for it soon... There's a potential upstream challenge (nothing cf
can do but wait for the next version), fixed on master, but we might be
able to code around it.

Now if I could just figure out Julia...

**Comment by dbast** [comment]
Retriggered some of the CI builds -> upload, given by the order of the dependencies. r-languageserver should be now available for R3.5/R3.6 on linux/osx/win :)

**Pull request merged**
