### PR TITLE
Add numix-icon-theme recipe

### LINKED ISSUE #18602: Package numix-icon-theme
### Package name

numix-icon-theme

### Package version

Newest

### Package website

https://github.com/numixproject/numix-icon-theme

### Package availability

The package can be downloaded from the GitHub release

### Additional comments

The package is already available on debian/ubuntu and fedora packet managers.

|Distro|Install Command/Links|
|:----:|:----:|
|![fedora][fedora]|`sudo dnf install numix-icon-theme`|
|![debian][debian] &nbsp;![ubuntu][ubuntu]|`sudo apt install numix-icon-theme`|

[fedora]: https://user-images.githubusercontent.com/17854950/86288769-c3351a00-bbea-11ea-908c-156c7bf0b778.png
[ubuntu]: https://user-images.githubusercontent.com/17854950/86288823-e069e880-bbea-11ea-9214-4764c5628f39.png
[debian]: https://user-images.githubusercontent.com/17854950/86288828-e4960600-bbea-11ea-9a46-4eb19621b3ae.png

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

This closes #18602 and it is required for #18603

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Hi @traversaro as discussed I added you as an additional maintainer. Let me know if it is fine with you 😃

**Comment by traversaro** [comment]
> Hi @traversaro as discussed I added you as an additional maintainer. Let me know if it is fine with you 😃

Confirmed, it is ok for me!

**Comment by GiulioRomualdi** [comment]
The PR is ready to be reviewed @conda-forge/staged-recipes

**Comment by traversaro** [comment]
FYI @wolfv @Tobias-Fischer this package proved useful for us to fix/workaround missing icons problems in PyQt applications, problems similar to https://github.com/RoboStack/ros-noetic/issues/161 .

**Pull request merged**
