### PR TITLE
add pocean-core

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/pyoceans/pocean-core/issues/20

### CODE REVIEW

**Comment by ericdill** [comment]
Don't the CI services ignore recipes that have already been merged into master but are lingering in the recipes/ dir?

**Comment by ocefpaf** [comment]
> Don't the CI services ignore recipes that have already been merged into master but are lingering in the recipes/ dir?

Not on `CircleCI`. See https://circleci.com/gh/ocefpaf/staged-recipes/551?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

But this is not ready for merge and I only removed that to make it "cleaner" for some people in my group to understand this when they check the branch out.

**Comment by ericdill** [comment]
> Not on CircleCI. See https://circleci.com/gh/ocefpaf/staged-recipes/551?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Ah right. The docker build script only removes the example recipe.

> But this is not ready for merge and I only removed that to make it "cleaner" for some people in my group to understand this when they check the branch out.

Ah I see... *slowly backs out of the room* :wave:

**Comment by ocefpaf** [comment]
> Ah I see... *slowly backs out of the room* :wave: 

Please don't! It is nice to get some oversight here :smile: 

PS: Thanks for the awesome reviews you did in the past 2-days! We really needed that!!

**Comment by ocefpaf** [comment]
One of the dependencies is missing for `Win32`+`PY36`. I am investigating this and re-starting AppVeyor here soon.

**Comment by jakirkham** [comment]
> Not on `CircleCI`.

That's because it is building on your fork and not the org one. If you disabled CircleCI on your fork and repushed, this would fix the issue.

**Comment by jakirkham** [comment]
> > Not on CircleCI.

> That's because it is building on your fork and not the org one. If you disable CircleCI on your fork, then this should work.

Note: This comment appears to have been deleted by @ocefpaf based on the audit log, but I'm unclear why as it was meant to purely informative and helpful. Could you please explain why this comment was deleted?

cc @conda-forge/core

**Comment by ocefpaf** [comment]
> Note: This comment appears to have been deleted by @ocefpaf based on the audit log, but I'm unclear why as it was meant to purely informative and helpful. Could you please explain why this comment was deleted?

:fire: :fire_engine:  OMG a bad mouse click is driving @jekirkham crazy!

**Comment by jakirkham** [comment]
Ok, that's why I wanted to ask. Sorry you are having troubles with your mouse.

**Pull request merged**
