### PR TITLE
Add rstr package to conda-forge

### PR DESCRIPTION
**Pull request by claymcleod**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by claymcleod** [comment]
How should I proceed if the author does not have a Github account and the linter is complaining about not having `extra/recipe-maintainers`?

**Comment by npavlovikj** [comment]
@claymcleod , the recipe maintainer is the person that creates the recipe, which in this case is you. So, you can just add your github username in the recipe. If the package developer has github account and is willing to maintain the recipe in general, they can be added as maintainers, but that is not mandatory.

**Comment by npavlovikj** [comment]
Also, `License.txt` should be `LICENSE.txt`.

**Comment by claymcleod** [comment]
@npavlovikj Great, thank you. This should be ready for review then if the CI comes back clean.

**Comment by npavlovikj** [comment]
LGTM @claymcleod  - thank you for contributing!

**Pull request merged**
