### PR TITLE
Adding R package r-iheatmapr

### PR DESCRIPTION
**Pull request by ctuni**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ctuni** [comment]
@conda-forge/help-r Could someone point me towards what is failing?
What I did was
`conda skeleton cran --all-urls iheatmapr`
`conda-build r-iheatmapr`
The `meta.yaml` file it produced is the one I copied

**Comment by cbrueffer** [comment]
Hi @ctuni, the current recipe contains no actual build instructions (`build.sh`/`bld.bat` files or `script:` build line in `meta.yaml`).

Please regenerate the recipe with https://github.com/bgruening/conda_r_skeleton_helper and commit all three resulting files.

**Comment by ctuni** [comment]
@cbrueffer Thank you very much! I had a lapsus there :sweat_smile: I regenerated all the files using the conda R skeleton helper script and committed all three files.

@conda-forge/r if you'd be so kind to confirm that you agree to be listed as contributors that would be amazing :) (and the linter would pass as well!)

**Comment by cbrueffer** [comment]
No problem! The `conda-forge/r` approval is implicit and the failing Windows build doesn't matter, since the package it `noarch`. Looks all good!

**Review by cbrueffer — APPROVED** [review]

**Pull request merged**
