### PR TITLE
Add json2parquet

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please lint

**Comment by BastianZim** [comment]
@conda-forge/help-python Ready for review, thanks!

**Comment by chrisburr** [comment]
Looks good except for the bot's suggestion (i.e. `python >=2.7` or `python >=3.6` in `host`+`run`).

**Comment by BastianZim** [comment]
Thanks! Yeah not sure what to do there as the package doesn't have a published minimum bound, only their travis setup file has one.
I have contacted them though so should I leave this as a draft until they answer?

**Comment by chrisburr** [comment]
Given Python 2.7 has been out of support for over a year and is no longer officially supported by conda-forge, I would go with `3.6` if you personally don't care about Python 2.7. (The perks of being the one who adds the recipe. 😄)  You can always edit it in the feedstock if needed.

**Comment by BastianZim** [comment]
Haha alright, then I'll go with 3.6 and edit it in case I get some feedback from the maintainers. Thanks for your help!

**Comment by BastianZim** [comment]
Thank you!

**Pull request merged**
