### PR TITLE
Add substrate-interface - WIP: Awaiting other PRs merge

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by MementoRC** [comment]
@conda-forge/help-python-c, @conda-forge/staged-recipe, hello, ready for review

**Comment by xhochy** [comment]
This PR is too large to review. Please split it up into individual packages.

**Comment by MementoRC** [comment]
@xhochy , Understood, I will unclose the separated packages and put this one in WIP until they are merged. Thank you

**Comment by MementoRC** [comment]
@xhochy I realized I may not need to close but update to align with your recommendation. I have re-opened the other individual PRs:
https://github.com/conda-forge/staged-recipes/pull/24340
https://github.com/conda-forge/staged-recipes/pull/24348
https://github.com/conda-forge/staged-recipes/pull/24351
https://github.com/conda-forge/staged-recipes/pull/24352

**Comment by MementoRC** [comment]
@xhochy I have recombined `scalecodec` with `substrate-interface`. Both upstreams have been updated recently. Also, `scalecodec` PR had an issue with a deleted unrelated recipe. Let me know if this is not convenient.

New PR: https://github.com/conda-forge/staged-recipes/pull/25470

**Comment by MementoRC** [comment]
@xhochy I did not realize merging the 2 recipes was not convenient. I am reverting the changes

**Comment by MementoRC** [comment]
@arjanz please comment here at your convenience

**Comment by arjanz** [comment]
> @arjanz please comment here at your convenience

Hi, I'm the maintainer of [py-substrate-interface](https://github.com/polkascan/py-substrate-interface), so makes sense to be in the loop

**Review by xhochy — APPROVED** [review]

**Pull request merged**
