### PR TITLE
Add libjpeg turbo12 from #6842

### PR DESCRIPTION
**Pull request by hmaarrfk**
Pull the recipe from https://github.com/conda-forge/staged-recipes/pull/6842

This will allow somebody to use a migrator to convert packages to libjpeg-turbo12 instead of libjpeg if they choose to.

Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by sdvillal** [comment]
Can this be installed in parallel with libjpeg-turbo and/or libjpeg? Even if there is no file clobbering, will there still be symbol collisions in linux?

Also maybe this should have a PR in the libjpeg-turbo feedstock, making it multioutput.

**Comment by hmaarrfk** [comment]
with `libjpeg-turbo`(8) yes, this is done during the 

image
image
image

I think libjpeg-turbo conflicts with `jpeg`

**Comment by sdvillal** [comment]
But are the library symbols also suffixed? If yes, downstreams need to be modified. If not, we will have segfaults if we install in parallel.

**Comment by hmaarrfk** [comment]
why do we have segfaults if we install in parallel? They will be linked with one library or the other? A library linked with `libjpeg12.so` should not be looking for symbols in `libjpeg.so` right???

<details>

```
$ nm -gD /home/mark/miniconda3/envs/jpeg/lib/libjpeg12.so
                 w __cxa_finalize
                 U exit
                 U ferror
                 U fflush
00000000000441e8 T _fini
                 U fprintf
                 U fread
                 U free
                 U fwrite
                 U getenv
                 w __gmon_start__
0000000000005000 T _init
                 U __isoc99_sscanf
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
0000000000042290 T jcopy_block_row
0000000000042230 T jcopy_sample_rows
0000000000042200 T jdiv_round_up
000000000003f260 T jinit_1pass_quantizer
0000000000042050 T jinit_2pass_quantizer
0000000000006670 T jinit_c_coef_controller
0000000000018170 T jinit_c_main_controller
000000000001aad0 T jinit_c_master_control
0000000000009290 T jinit_color_converter
00000000000289d0 T jinit_color_deconverter
0000000000017f20 T jinit_compress_master
000000000001e630 T jinit_c_prep_controller
00000000000245e0 T jinit_d_coef_controller
000000000002e3f0 T jinit_d_main_controller
0000000000020260 T jinit_downsampler
00000000000360a0 T jinit_d_post_controller
000000000000b0d0 T jinit_forward_dct
000000000002c5d0 T jinit_huff_decoder
0000000000017d10 T jinit_huff_encoder
000000000002d930 T jinit_input_controller
0000000000029ca0 T jinit_inverse_dct
00000000000309c0 T jinit_marker_reader
0000000000019bd0 T jinit_marker_writer
00000000000316f0 T jinit_master_decompress
0000000000043c10 T jinit_memory_mgr
00000000000347f0 T jinit_merged_upsampler
0000000000035c90 T jinit_phuff_decoder
000000000001dff0 T jinit_phuff_encoder
0000000000037020 T jinit_upsampler
000000000001aeb0 T jpeg_abort
0000000000005290 T jpeg_abort_compress
0000000000021520 T jpeg_abort_decompress
000000000001af70 T jpeg_add_quant_table
000000000001af50 T jpeg_alloc_huff_table
000000000001af30 T jpeg_alloc_quant_table
0000000000030ee0 T jpeg_calc_output_dimensions
0000000000021530 T jpeg_consume_input
00000000000210e0 T jpeg_copy_critical_parameters
0000000000005140 T jpeg_CreateCompress
00000000000213a0 T jpeg_CreateDecompress
0000000000021c10 T jpeg_crop_scanline
000000000001b420 T jpeg_default_colorspace
000000000001af00 T jpeg_destroy
0000000000005280 T jpeg_destroy_compress
0000000000021510 T jpeg_destroy_decompress
00000000000377d0 T jpeg_fdct_float
00000000000386e0 T jpeg_fdct_ifast
0000000000038900 T jpeg_fdct_islow
000000000002abd0 T jpeg_fill_bit_buffer
0000000000005370 T jpeg_finish_compress
00000000000218e0 T jpeg_finish_decompress
0000000000022940 T jpeg_finish_output
0000000000043e00 T jpeg_free_large
0000000000043de0 T jpeg_free_small
0000000000017750 T jpeg_gen_optimal_table
0000000000043df0 T jpeg_get_large
0000000000043dd0 T jpeg_get_small
00000000000218b0 T jpeg_has_multiple_scans
000000000002ad80 T jpeg_huff_decode
000000000003b140 T jpeg_idct_10x10
000000000003b600 T jpeg_idct_11x11
000000000003bbe0 T jpeg_idct_12x12
000000000003c1a0 T jpeg_idct_13x13
000000000003c880 T jpeg_idct_14x14
000000000003cf20 T jpeg_idct_15x15
000000000003d620 T jpeg_idct_16x16
000000000003e3e0 T jpeg_idct_1x1
000000000003e120 T jpeg_idct_2x2
000000000003aa10 T jpeg_idct_3x3
000000000003ddd0 T jpeg_idct_4x4
000000000003a110 T jpeg_idct_5x5
0000000000039e70 T jpeg_idct_6x6
0000000000039aa0 T jpeg_idct_7x7
000000000003ace0 T jpeg_idct_9x9
0000000000038be0 T jpeg_idct_float
00000000000390f0 T jpeg_idct_ifast
0000000000039550 T jpeg_idct_islow
0000000000021880 T jpeg_input_complete
0000000000017270 T jpeg_make_c_derived_tbl
0000000000029d40 T jpeg_make_d_derived_tbl
0000000000043e10 T jpeg_mem_available
0000000000022c30 T jpeg_mem_dest
0000000000043e50 T jpeg_mem_init
0000000000022f50 T jpeg_mem_src
0000000000043e60 T jpeg_mem_term
00000000000679c0 R jpeg_natural_order
0000000000031660 T jpeg_new_colormap
0000000000043e40 T jpeg_open_backing_store
000000000001b0b0 T jpeg_quality_scaling
0000000000037380 T jpeg_read_coefficients
0000000000021800 T jpeg_read_header
000000000002ca80 T jpeg_read_icc_profile
0000000000022800 T jpeg_read_raw_data
0000000000021e60 T jpeg_read_scanlines
0000000000030890 T jpeg_resync_to_restart
0000000000030b60 T jpeg_save_markers
000000000001b110 T jpeg_set_colorspace
000000000001b4a0 T jpeg_set_defaults
000000000001b070 T jpeg_set_linear_quality
0000000000030c30 T jpeg_set_marker_processor
000000000001b0e0 T jpeg_set_quality
000000000001b9d0 T jpeg_simple_progression
0000000000021f30 T jpeg_skip_scanlines
0000000000005620 T jpeg_start_compress
0000000000021b10 T jpeg_start_decompress
00000000000228d0 T jpeg_start_output
0000000000037740 T jpeg_std_error
0000000000022bc0 T jpeg_stdio_dest
0000000000022ea0 T jpeg_stdio_src
000000000006e6e0 D jpeg_std_message_table
00000000000052a0 T jpeg_suppress_tables
0000000000020ec0 T jpeg_write_coefficients
0000000000017d70 T jpeg_write_icc_profile
00000000000054b0 T jpeg_write_marker
00000000000055b0 T jpeg_write_m_byte
0000000000005550 T jpeg_write_m_header
00000000000057a0 T jpeg_write_raw_data
00000000000056b0 T jpeg_write_scanlines
00000000000055c0 T jpeg_write_tables
0000000000042210 T jround_up
00000000000422b0 T jzero_far
0000000000000000 A LIBJPEG_6.2
0000000000000000 A LIBJPEGTURBO_6.2
                 U malloc
                 U memcpy
                 U memset
                 U sprintf
                 U __stack_chk_fail
                 U stderr
```
</details>

**Comment by sdvillal** [comment]
Parallel installing different versions of libjpeg (let it be libjpeg-turbo and libjpeg or libjpeg-turbo12) is risky, at best.These symbol names clash across libraries, and the linux dynamic loader does not use library name or version to add a namespace to symbols. 

Let's say your PIL was compiled against libjpeg and your opencv against libjpeg-turbo. If you want to use both in the same process space, where there can be only one version of a symbol with the same name, the actual symbol that ends up used depends on the order in which things happen in your program. This is  error and headache prone.

I would say that to always have a consistent and safe stack, we should make libjpeg-turbo, libjpeg-turbo with support to 12 and 8 bit and libjpeg 8 and 9 mutually exclusive in an environment. We should default to libjpeg-turbo which is what most people would ultimately want. Unfortunately a decision was taken back in the day to make all of conda-forge and defaults be compiled against libjpeg 9, which makes migration hard (every dependency needs to be recompiled).

See also: 
  https://github.com/conda-forge/conda-forge.github.io/issues/673
  https://github.com/regro/cf-scripts/pull/392

**Comment by hmaarrfk** [comment]
please keep open.

**Comment by hmaarrfk** [comment]
please keep open

**Comment by hmaarrfk** [comment]
keep

**Comment by hmaarrfk** [comment]
keep

**Comment by hmaarrfk** [comment]
Keep

**Comment by hmaarrfk** [comment]
not stale

**Pull request closed without merging**
