### PR TITLE
Add recipe for tklib

### PR DESCRIPTION
**Pull request by abloemert**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by abloemert** [comment]
@conda-forge/staged-recipes can this PR be merged?

**Comment by abloemert** [comment]
@isuruf @conda-forge/staged-recipes any news here?

**Comment by isuruf** [comment]
Looks like https://core.tcl-lang.org/tklib/tarball/tklib-0.7.tar.gz is not stable and they change the tarball without increasing the version. Is there a stable version?

**Comment by abloemert** [comment]
Thank you @isuruf, it turns out that I missed the `?uuid=` part to make sure that it points to the actual tag.

**Comment by abloemert** [comment]
Thank you @isuruf

**Pull request merged**
