### PR TITLE
Add rapidgzip

### PR DESCRIPTION
**Pull request by mxmlnkn**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mxmlnkn** [comment]
@ap-- I have added you as maintainer because you also are for the other related packages.

**Comment by mxmlnkn** [comment]
I agree to be a maintainer.

**Comment by ap--** [comment]
Hi @mxmlnkn, I just opened #23901. Let me know which one you want to keep, then I'll apply the changes in the other.

And I agree to be a maintainer.

**Comment by mxmlnkn** [comment]
Then let's use your PR.

 - I have added NASM because without it present, ISA-L is not compiled into rapidgzip. With ISA-L it is ~2-4x faster in many cases.
 - I also have release and used rapidgzip 0.10.1 so that conda Windows builds do not fail with an internal MSVC error, some constexpr stuff seems to be too complex for MSVC.
 - Why did you not use THIRDPARTY.yml this time? I based my PR on your older PRs for indexed_bzip2.

**Comment by ap--** [comment]
> * I have added NASM because without it present, ISA-L is not compiled into rapidgzip. With ISA-L it is ~2-4x faster in many cases.

I added it to the other PR 👍 

> * I also have released and used rapidgzip 0.10.1 in the recipe so that conda Windows builds do not fail with an internal MSVC error, some constexpr stuff seems to be too complex for MSVC.

Also updated 👍 

> * Why did you not use THIRDPARTY.yml this time? I based my PR on your older PRs for indexed_bzip2, which still has it.

Good question. I usually start with a generating a starting template with grayskull, and then go from there. It seems the license detection has gotten better. But to be consistent i now switched back to including the external ones via THIRDPARTY.yml

**Pull request closed without merging**
