### PR TITLE
Torchaudio

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge/staged-recipes this is likely going to need a lot of work and help to get working... Any help folks can provide highly appreciated! @conda-forge/torchvision (I borrowed heavily from yall's recipe)

**Comment by hmaarrfk** [comment]
I really think split recipes introduce unecessary complexity at this stage.

I would suggest removing it

**Comment by thewchan** [comment]
@hmaarrfk Thanks; I'll try that!

**Comment by h-vetinari** [comment]
I had started with this in #17082. Problem that I ran into was https://github.com/conda-forge/kaldi-feedstock/issues/15 (though the issue is also that the kaldi-feedstock currently has a blas setup that's quite incompatible with the rest of conda-forge), which I'm attempting to fix in https://github.com/conda-forge/kaldi-feedstock/pull/25. I've gotten the non-windows builds going, but could use some help with windows.

**Comment by hmaarrfk** [comment]
You are hitting a problem where they expect you to be using git to build
https://github.com/pytorch/audio/tree/main/third_party/kaldi

You can use git, this is somewhat frowned upon, but I had to ensure maintainability of pytorch. 

For 1 package, you might be able to pull exactly the right version and keep things in sync.
https://github.com/conda-forge/staged-recipes/pull/17620/files#diff-18d4986353d397c3b27d7366f7bfa374de054aa475730a8e71dc0d5f09f29ac6R39

Then you should make some noise upstream to both torchaudio and kaldi to release and use real version numbers. They don't have incentives unless they know their users will use them and it brings benefits to them.

**Comment by thewchan** [comment]
@hmaarrfk Thanks for the guidance. It looks like they are using a custom build for Kaldi; would I be able to use git to pull that version of Kaldi from the torchaudio repo? Is that something doable?

**Comment by hmaarrfk** [comment]
Step #1, get things to build.
Step #2. Get things approved. 

Do what you need at this stage.

You might also find this useful: https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/meta.yaml

**Comment by thewchan** [comment]
@hmaarrfk is there a way in meta.yaml to specify the commit hash of a git repo to pull? I can only find how to do this with tags or versions?

**Comment by thewchan** [comment]
Hmm this is some strange C++ error that I'm not familiar with... @conda-forge/help-c-cpp

**Comment by thewchan** [comment]
Running into this error even after I added libblas as a build dependencies

```
CMake Error at /home/conda/staged-recipes/build_artifacts/torchaudio_1647365684713/_build_env/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
  ```

**Comment by hmaarrfk** [comment]
https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=blas#blas
https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/meta.yaml#L76

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/conda_build_config.yaml#L2

**Comment by h-vetinari** [comment]
> It looks like they are using a custom build for Kaldi; would I be able to use git to pull that version of Kaldi from the torchaudio repo? Is that something doable?

... did you see/read my comment further up?

**Comment by thewchan** [comment]
@h-vetinari, yes, can you help me understand how I'd apply what you did in this case?

**Comment by h-vetinari** [comment]
> @h-vetinari, yes, can you help me understand how I'd apply what you did in this case?

* kaldi and sox must (IMO) be unvendored; see my patch in #17082
* kaldi must be fixed in conda-forge to include headers and have a suitable blas setup, see https://github.com/conda-forge/kaldi-feedstock/pull/25

It'd be possible to move forward with a unix-only version of https://github.com/conda-forge/kaldi-feedstock/pull/25, but there shouldn't be the assumption that just by virtue of restarting from scratch, you'll automatically overcome the blockers that someone else already identified. Obviously, help on those blockers would be appreciated.

**Comment by thewchan** [comment]
@conda-forge-admin, please restart ci

**Comment by thewchan** [comment]
@conda-forge-admin, please restart ci

**Pull request closed without merging**
