### PR TITLE
add nauty

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@ocefpaf, ready for review

**Comment by isuruf** [comment]
@ocefpaf, sorry for pinging again. I'd like to get this in before the weekend ends.

**Comment by ocefpaf** [comment]
> @ocefpaf, sorry for pinging again. I'd like to get this in before the weekend ends.

Don't be. (But if I miss it here try gitter.)

**Comment by isuruf** [comment]
Thanks. Can you have a look at https://github.com/conda-forge/staged-recipes/pull/2549 as well?

**Pull request merged**
