### PR TITLE
Openblas

### PR DESCRIPTION
**Pull request by groutr**
Add openblas.

Openblas for windows and mac is still somewhat experimental according to their docs.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for the submission, @groutr. However, there is already a PR ( https://github.com/conda-forge/staged-recipes/pull/364 ) for OpenBLAS. Maybe you could PR relevant changes against it instead.

**Comment by groutr** [comment]
No problem.  There are so many PRs now that it's hard to keep track of all of them (which I guess is a good thing).

**Comment by jakirkham** [comment]
Yeah, it has become a bit of a mess I agree. Though it is probably so because of all the interest in conda-forge, which is a good thing. We need to figure out better strategies to accommodate this growth.

**Comment by jakirkham** [comment]
Went ahead and closed to keep life simple. Please feel free to help us over there.

I am debating just fixing Mac and taking the rest of the issues over to a feedstock. If you have any thoughts on how to fix Mac, they would definitely be appreciated. I think we are close. Windows is just too big of a mess right now to fully fix. Though it includes some controversial dependencies for Linux, which I might need to get some buy in on.

**Pull request closed without merging**
