### PR TITLE
Add fastapi

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Cheers for taking a look @sodre! Feel free to add yourself as a maintainer if you'd like...

**Comment by sodre** [comment]
@dhirschfeld, Thanks for starting the package for fastapi. I was thinking about packaging it myself before I saw your PR.

I patched your PR, to delete the pypackage.toml file, and now it is building. If you are fine with the change, ping help-python or staged-recipes saying that the recipe is ready for review.

**Comment by dhirschfeld** [comment]
ping @conda-forge/help-python! I think this is ready for merge pending review...

**Comment by tiangolo** [comment]
Thanks for doing this! :tada: :rocket:

**Comment by tiangolo** [comment]
Thanks @dhirschfeld !

Yes, please :smile: 

I added the PR here: https://github.com/conda-forge/fastapi-feedstock/pull/1

I'm still not familiar with the conda-forge process, but a conda package is something that I had in mind a while ago, so I think I should get familiar with it :grimacing:

**Comment by dhirschfeld** [comment]
`conda-forge` is pretty slick! The bot monitors pypi and when a new version is published there it will open a PR with the updated version and sha256. All that remains for a maintainer is to ensure any changes to the dependencies are reflected in the [`meta.yaml`](https://github.com/conda-forge/fastapi-feedstock/blob/master/recipe/meta.yaml). I'd suppose you'd be pretty well across any required changes though ;)

If you have any questions they're always very helpful over at [gitter](https://gitter.im/conda-forge/conda-forge.github.io), or you can always ping me directly if I'm about...

**Comment by tiangolo** [comment]
Awesome, thanks for quick intro @dhirschfeld !

**Pull request merged**
