### PR TITLE
adding recipe for r package tcpl

### PR DESCRIPTION
**Pull request by mfakaehler**
Hi @conda-forge/help-r
here is another recipe for an existing CRAN package:

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by mfakaehler** [comment]
@mfakaehler is okay with maintaining this recipe

**Comment by mfakaehler** [comment]
Strange. When I run 
CONFIG=win64 ./.circleci/run_docker_build.sh
on my local machine, I get no errors. @conda-forge/help-r any ideas?

**Comment by cbrueffer** [comment]
No, but it doesn't matter here since the package is `noarch` and those are built on Linux. Please just clean up the lint warnings (change license to GPL-2.0-only), then this looks ready to go.

**Comment by cbrueffer** [comment]
Actually the Windows error looks like a temporary issue accessing a URL.

**Comment by cbrueffer** [comment]
Thanks for the contribution!

**Comment by mfakaehler** [comment]
Thank you for your review!

**Pull request merged**
