### PR TITLE
Add tensorflow 0.7.0 recipe

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
This fails on Linux because Google is shipping shared libraries in their wheel which were build on machine with a newer version of glibc++ than what is installed on the CircleCI docker VM.  Not sure there is much that can be done about this besides building the library from source.

**Comment by pelson** [comment]
Can't say I'm blown away with the idea of taking a binary wheel and converting it to a conda distribution in this way - it doesn't really add anything to the reproducibility of the package. Is the build process a pain to re-implement here?

**Comment by pelson** [comment]
Just wanted to give you a heads up that I've moved the "ready_recipes" folder back to the "recipes" folder now that the automatic conversion of the backlog is complete.

**Comment by jjhelmus** [comment]
@pelson I agree that repacking the wheel is less than idea.  Tensorflow uses bazel for building which requires a [bit of work to set up](http://bazel.io/docs/install.html).  Given a number of issues with the wheels provided I plan of biting the bullet and figuring out how to build from source.  I'm on travel at the moment but will update this recipe once I'm back and have some time to work out all the details of building from source.

**Comment by pelson** [comment]
Whoa. That doesn't sound like fun! How about we merge this, and you can iterate in the feedstock itself?

**Comment by jjhelmus** [comment]
Works for me.  Given the requirements for Bazel a different docker image might be required on CircleCI.  Having a feedstock to iterate on would make this easier. 

tensorflow 0.7.1 has been released that has improved wheel files, I could update this PR to target that version or update this in the feedstock.

**Comment by pelson** [comment]
> tensorflow 0.7.1 has been released that has improved wheel files, I could update this PR to target that version or update this in the feedstock.

That's why we have feedstocks :+1: 

>  Given the requirements for Bazel a different docker image might be required on CircleCI.

Interesting. Would you envisage that being a build only requirement, or a runtime requirement for users?

**Comment by jjhelmus** [comment]
Bazel should only be required for build, not runtime.  The difficulty is that bazel requires Ubuntu 14.04 or 15.10 which will result in the compiled libraries depending on a more recent version of GLIBC than if you use CentOS 5 or 6.

**Comment by jjhelmus** [comment]
The merge of this PR didn't seem to trigger a feedstock.  Any ideas @pelson?

**Comment by pelson** [comment]
> The merge of this PR didn't seem to trigger a feedstock. Any ideas @pelson?

Ah, yes. Sorry - I moved the ```ready_recipes``` folder back to ```recipes``` (and didn't see this one was targeting it). My bad.

I'm happy to make a PR which moves it, or if you are happy to do so, it is just a case of ```git mv ready_recipes/tensor_flow recipes/```

**Pull request merged**
