### PR TITLE
Swarp recipe

### PR DESCRIPTION
**Pull request by teake**
@conda-forge/help-c-cpp

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

The package name is prefixed because there was name collision in a related package, cf. #8693.

### CODE REVIEW

**Comment by scopatz** [comment]
This LGTM.  Is this ready to go?

**Comment by teake** [comment]
Let's wait until the naming issue in #8764 gets resolved, since this is a related package. Same goes for #8763 and #8765. Should I mark those as 'on hold'? If so, how?

**Comment by beckermr** [comment]
Whoops. I merged the scamp one. Sorry!

**Comment by beckermr** [comment]
Honestly though, waiting on these other ones is not going to fix the underlying issue with the source extractor package. We might as well merge them since psfex is already there too.

**Comment by teake** [comment]
@beckermr That would be on me, I probably should have closed the PRs. But since #8765 is now merged, this one and #8763 need no longer wait.

**Pull request merged**
