### PR TITLE
Add intern

### PR DESCRIPTION
**Pull request by stuarteberg**
This adds a recipe for `intern` (Integrated Toolkit for Extensible and Reproducible Neuroscience).  It's a python package for accessing the [Boss storage service from JHU-APL][1].

The `intern` package is pure-python, so this recipe is straightforward.

[1]: https://docs.theboss.io

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by stuarteberg** [comment]
I confirm that I am a maintainer.

**Comment by jtpdowns** [comment]
I confirm that I am a maintainer.

**Comment by stuarteberg** [comment]
This is ready for merge.  Thanks!

@conda-forge/help-python

**Comment by stuarteberg** [comment]
@conda-forge-admin, please add noarch: python

**Comment by stuarteberg** [comment]
This recipe is ready for merging.  Thanks!

@conda-forge/help-python

**Pull request merged**
