### PR TITLE
add ale-py

### PR DESCRIPTION
**Pull request by h-vetinari**
Previously #16488, needed for gym...

### CODE REVIEW

**Comment by h-vetinari** [comment]
```
error: 'path' is unavailable: introduced in macOS 10.15
```

Time to upgrade OSX I guess.

**Comment by mattip** [comment]
This is targeting ale-py 0.7.5. In the mean time 0.8.0 was released :(

**Comment by h-vetinari** [comment]
@mattip 
Sorry, this has slipped on my list of priorities + low on time... 😑

Without expectations, I'll make you collaborator on my fork of staged-recipes, so you can push into these PRs if you feel like it. :)

**Comment by mattip** [comment]
understood, thanks

**Comment by Tobias-Fischer** [comment]
Hi @h-vetinari, any chance to give me access to your fork, too?

**Comment by h-vetinari** [comment]
> Hi @h-vetinari, any chance to give me access to your fork, too?

With pleasure! It's done :)

**Comment by Tobias-Fischer** [comment]
Windows fails in the CI setup, as far as I can tell unrelated to this recipe.

I am not sure what `SDL_DYNLOAD` is all about, and whether it should be `ON` or `OFF` - @traversaro have you seen this before?

https://github.com/mgbellemare/Arcade-Learning-Environment/blob/49154a3e96f0858e5e9a1f41c89cfe18e6741468/src/python/CMakeLists.txt#L49-L71

**Comment by Tobias-Fischer** [comment]
linux-64 and osx-64 seem to be working fine.

**Comment by traversaro** [comment]
> Windows fails in the CI setup, as far as I can tell unrelated to this recipe.

I am not sure this is unrelated. It seems that the recipe is hardcoding the use of vcpkg if `VCPKG_ROOT` is defined, see https://github.com/mgbellemare/Arcade-Learning-Environment/blob/v0.8.0/CMakeLists.txt#L37 . Probably we need to comment out all the block that begins with `if (NOT DEFINED CMAKE_TOOLCHAIN_FILE)`.

**Comment by traversaro** [comment]
> I am not sure what `SDL_DYNLOAD` is all about, and whether it should be `ON` or `OFF` - @traversaro have you seen this before?
> 
> https://github.com/mgbellemare/Arcade-Learning-Environment/blob/49154a3e96f0858e5e9a1f41c89cfe18e6741468/src/python/CMakeLists.txt#L49-L71

I am not sure, but at a first glance it seems to be related to the fact that you can load SDL2 via dlopen at runtime instead of linking it at linking time. As it seems that that option also control several part of the build system related to vendoring SDL2 (see https://github.com/mgbellemare/Arcade-Learning-Environment/blob/679288f1e164bb225f9af65b0080093ab502e6ab/src/python/CMakeLists.txt#L67), I would go for setting `SDL_DYNLOAD` to `OFF`.

**Comment by Tobias-Fischer** [comment]
> > Windows fails in the CI setup, as far as I can tell unrelated to this recipe.
> 
> I am not sure this is unrelated. It seems that the recipe is hardcoding the use of vcpkg if `VCPKG_ROOT` is defined, see https://github.com/mgbellemare/Arcade-Learning-Environment/blob/v0.8.0/CMakeLists.txt#L37 . Probably we need to comment out all the block that begins with `if (NOT DEFINED CMAKE_TOOLCHAIN_FILE)`, or we unsed the `VCPKG_ROOT` and `VCPKG_INSTALLATION_ROOT` env variable.

Good catch - I just created a patch doing this. Thanks :)!

**Comment by Tobias-Fischer** [comment]
> > I am not sure what `SDL_DYNLOAD` is all about, and whether it should be `ON` or `OFF` - @traversaro have you seen this before?
> > https://github.com/mgbellemare/Arcade-Learning-Environment/blob/49154a3e96f0858e5e9a1f41c89cfe18e6741468/src/python/CMakeLists.txt#L49-L71
> 
> I am not sure, but at a first glance it seems to be related to the fact that you can load SDL2 via dlopen at runtime instead of linking it at linking time. As it seems that that option also control several part of the build system related to vendoring SDL2 (see https://github.com/mgbellemare/Arcade-Learning-Environment/blob/679288f1e164bb225f9af65b0080093ab502e6ab/src/python/CMakeLists.txt#L67), I would go for setting `SDL_DYNLOAD` to `OFF`.

Ok - `OFF` is the default so we should be all good. Many thanks for checking!

**Comment by mattip** [comment]
Typically this happens when the dll does not export any symbols. There should be some equivalent of `_declspec(dllexport)` somewhere in the code or headers used to build `ale.dll`.

**Comment by Tobias-Fischer** [comment]
Hmm, I see, thanks @mattip. It seems like in their CI, they just run `pip install`, presumably not building some C++ parts that we are trying to build here. I don't understand enough about the build to progress Windows any further.

Some ideas:
- We could skip Windows for now, and open an issue in the feedstock once it is created
- We could try skipping the cmake stuff we currently run, and instead just go with the `pip install` like in their CI
- We could try properly fixing the DLL exports

Any thoughts?

**Comment by mattip** [comment]
I think duplicating as much as possible whatever upstream does would be the most reliable.

**Comment by h-vetinari** [comment]
> If you have any ideas @h-vetinari @traversaro that would be amazing :)

I would have suggested `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` as you did already, but I have no idea why that CI run failed. The logs just say
```
[170/172] Linking CXX shared library src\ale.dll
FAILED: src/ale.dll src/ale.lib 
```

with no discernible reason why (tried searching for "error" and "failed")

**Comment by Tobias-Fischer** [comment]
I got quite a bit further by setting `BUILD_SHARED_LIBS=OFF` (at least for now), but it seems like the libraries are not installed in the correct location:
```
import: 'ale_py'
Traceback (most recent call last):
  File "C:\bld\ale-py_1670381440321\test_tmp\run_test.py", line 2, in <module>
    import ale_py
  File "C:\bld\ale-py_1670381440321\_test_env\lib\site-packages\ale_py\__init__.py", line 48, in <module>
    from ale_py._ale_py import SDL_SUPPORT, Action, ALEInterface, ALEState, LoggerMode
ModuleNotFoundError: No module named 'ale_py._ale_py'
```

I'm not a Windows expert - if anyone has ideas, that would be great.

**Comment by Tobias-Fischer** [comment]
My best bet is that 
https://github.com/mgbellemare/Arcade-Learning-Environment/blob/db3728264f382402120913d76c4fa0dc320ef59f/setup.py#L42

is wrong

**Comment by h-vetinari** [comment]
It seems nothing actually gets installed (normally that step shows which files are moved to $PREFIX):

```
[172/172] Linking CXX shared module src\python\_ale_py.cp39-win_amd64.pyd

(%BUILD_PREFIX%) %SRC_DIR%\build>if 0 NEQ 0 exit 1 

(%BUILD_PREFIX%) %SRC_DIR%\build>cmake --install . --prefix $PREFIX 
-- Install configuration: "Release"

(%BUILD_PREFIX%) %SRC_DIR%\build>if 0 NEQ 0 exit 1
```

**Comment by Tobias-Fischer** [comment]
This is probably the issue? https://github.com/mgbellemare/Arcade-Learning-Environment/blob/679288f1e164bb225f9af65b0080093ab502e6ab/src/CMakeLists.txt#L69

**Comment by h-vetinari** [comment]
> This is probably the issue? https://github.com/mgbellemare/Arcade-Learning-Environment/blob/679288f1e164bb225f9af65b0080093ab502e6ab/src/CMakeLists.txt#L69

haha, looks like it :)

**Comment by Tobias-Fischer** [comment]
Maybe you have an idea @traversaro?

**Comment by traversaro** [comment]
> Maybe you have an idea @traversaro?

I guess `<prefix>/Lib/site-packages/ale_py`, using conda-build's `SP_DIR` env variable: `%SP_DIR%/ale_py` .

**Comment by Tobias-Fischer** [comment]
This seems to be working fine now, hurray! Thanks everyone.

The only issue left is that it does not build shared libs on Windows. I have no idea what the problem is - are we happy with an exception to the conda guidelines? Shared libs are not tested upstream, and the export all symbols leads to a build fail without error message.

**Comment by Tobias-Fischer** [comment]
Ok I cleaned up the patches a little. What do you think @h-vetinari? Ready for review?

**Review by xhochy — APPROVED** [review]

**Comment by mattip** [comment]
Congrats to all who put the work in, this gets one step closer to packaging gymnasium/gym on conda!

**Pull request merged**
