### PR TITLE
Add recipe for svglib

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@jakirkham decided to drop running the tests, they are also [failing for the source repository](https://travis-ci.org/deeplook/svglib).

**Comment by nicoddemus** [comment]
@conda-forge/staged-recipes Looks like it is now good to go.

**Comment by nicoddemus** [comment]
Thanks @ocefpaf! 👍

**Comment by ocefpaf** [comment]
NP

**Pull request merged**
