### PR TITLE
Adding JSBSim

### PR DESCRIPTION
**Pull request by bcoconni**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bcoconni** [comment]
I hereby confirm that I am willing to be the maintainer of this package.

**Comment by bcoconni** [comment]
@conda-forge/staged-recipes, ready for review!

**Comment by bcoconni** [comment]
Ping @conda-forge/staged-recipes
Hello ? Anyone available for a review ? I have seen that several recipes have been approved since I asked for a review.

**Comment by chrisburr** [comment]
Apologies for this slipping past the net, looks good so LGTM 👍 


Unfortunately the ping for review doesn't work until you're a member of the conda-forge organisation (you'll get an invite within a few hours of this being merged). Explanation from the PR description:

> Due to GitHub limitations first time contributors to conda-forge are unable
to ping these teams. You can [ping the team](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-ping-team) using a special command in
a comment on the PR to get the attention of the `staged-recipes` team. You can
also consider asking on our [Gitter channel](https://gitter.im/conda-forge/conda-forge.github.io)
or on our [Keybase chat](https://keybase.io/team/condaforge.chat)
if your recipe isn't reviewed promptly.

**Comment by bcoconni** [comment]
> Apologies for this slipping past the net, looks good so LGTM :+1:

Thanks :+1: 
> Explanation from the PR description: [...]

Well this explanation is commented out in the PR description and I did not notice that it was any different from your [FAQ#12 - "My pull request passes all checks, but hasn't received any attention. How do I call attention to my PR? What is the customary amount of time to wait?"](https://github.com/conda-forge/staged-recipes#12-my-pull-request-passes-all-checks-but-hasnt-received-any-attention-how-do-i-call-attention-to-my-pr--what-is-the-customary-amount-of-time-to-wait) so I referred to the latter for the procedure to follow.

May I suggest to update your FAQ with the same content than the explanation in the PR ?

**Comment by chrisburr** [comment]
> May I suggest to update your FAQ with the same content than the explanation in the PR ?

Yes please!

**Comment by bcoconni** [comment]
@chrisburr As previously discussed, I just pushed a PR #13830 to update the FAQ in the README with informations for first time contributors. These are currently only available in the commented out section of PR descriptions.

**Pull request merged**
