### PR TITLE
ENH move master to main

### PR DESCRIPTION
**Pull request by beckermr**
This PR moves the default branch from master to main. A member of core needs to change the branch in the repo settings and then merge this PR.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/core @conda-forge/staged-recipes This PR is ready for review!

**Comment by beckermr** [comment]
I bumped a few members of core directly since they have worked on these files recently.

**Comment by chrisburr** [comment]
This seems to have worked surprisingly smoothly. Nice work @beckermr! 🍰

**Comment by beckermr** [comment]
thanks @chrisburr!

**Pull request merged**
