### PR TITLE
WIP: Add recipe to build ROOT and some missing dependencies

### PR DESCRIPTION
**Pull request by chrisburr**
Opening a PR to test integration with conda-forges CI. This recipe has already been extensively tested externally in collaboration with the developer team of ROOT and been shown to be working on Linux. Support for macOS is still a work in progress.

Replaces #6273 and #2833.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Is there a means for root to use the already packaged standalone cling package rather than vendoring cling, clang etc?

**Comment by chrisburr** [comment]
I'm fairly sure ROOT requires a patched version of cling but I'll double check.

**Comment by SylvainCorlay** [comment]
Note that we already have a patched variant of clang and llvm with the patches required by cling.

**Comment by chrisburr** [comment]
Turns out I was wrong so I'll try using them as external dependencies.

**Comment by henryiii** [comment]
Note as to resolution on ROOT's Mattermost: No, you cannot build against external cling. The `cling` option is cling vs. CINT (and CINT has been replaced completely by cling by now). In theory it should be possible, since "the sources of standalone cling are identical to those of ROOT's cling", but ROOT's build system does not support it, and it "won't be possible in the foreseeable future".

**Comment by SylvainCorlay** [comment]
Does this override the potentially installed llvmdev, clangdev, and cling that may be installed in the same environment?

**Comment by msarahan** [comment]
I agree with @SylvainCorlay that the current vendoring approach will cause problems.  That shouldn't prevent this from being available, though.  I recommend merging this now (which I'll do), and @chrisburr please keep an eye on your community to gauge the importance of an unvendoring effort in the future.

**Comment by chrisburr** [comment]
@msarahan Thanks for merging!

@SylvainCorlay The status of the dependencies are:
 * `llvmdev` is a dependency of this recipe.
 * `clangdev` doesn't contain the correct set of patches for this version of ROOT. Ideally `clangdev` should be modified at some point.
 * `cling` It's currently not possible to build ROOT against an external build of cling.

**Comment by mariusvniekerk** [comment]
@msarahan seems the files in this feedstock weren't in recipes

**Comment by msarahan** [comment]
Sure, do whatever you need to do.

**Pull request merged**
