### PR TITLE
add final recipes

### PR DESCRIPTION
**Pull request by bgruening**
last part of https://github.com/bioconda/bioconda-recipes/issues/5582

@daler and @jdblischak if we can get the last 3 PRs merged, we should be done.

### CODE REVIEW

**Comment by bgruening** [comment]
xref: https://github.com/conda-forge/r-htmlwidgets-feedstock/pull/1

**Comment by jdblischak** [comment]
The AppVeyor build failed due to an [HTTP error](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.16795/job/d66d5lkso3ci5hpc#L5035), so I restarted it. The CircleCI build also failed due to an [HTTP error](https://circleci.com/gh/conda-forge/staged-recipes/19595?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), but I appear to have lost the ability to restart PRs on CircleCI.

**Comment by jdblischak** [comment]
The Travis build failed trying to build [r-ploty for R 3.4.1](https://travis-ci.org/conda-forge/staged-recipes/builds/273967476#L1245). One of its dependencies, [r-tidyr](https://github.com/conda-forge/r-tidyr-feedstock), wasn't built for R 3.4.1 on osx. r-tidyr failed to build for R 3.4.1 on osx because of an issue with [r-rcpp](https://travis-ci.org/conda-forge/r-tidyr-feedstock/jobs/266362128#L319).

**Comment by bgruening** [comment]
Part of the problem is that staged-recipes are building for r3.3.1 and the feedstocks don't. @ocefpaf do you know why this happens?

**Comment by jdblischak** [comment]
> Part of the problem is that staged-recipes are building for r3.3.1 and the feedstocks don't.

@bgruening I'm confused. What makes you say that? staged-recipes is building recipes with both R 3.3.2 and R 3.4.1. From the CircleCI build of this PR:

```
Resolved dependencies, will be built in the following order: 
	r-dendextend-1.5.2-r3.3.2_0 (will be built: True)
	r-factominer-1.36-r3.3.2_0 (will be built: True)
	r-factominer-1.36-r3.4.1_0 (will be built: True)
	r-fdrtool-1.2.15-r3.3.2_0 (will be built: True)
	r-fdrtool-1.2.15-r3.4.1_0 (will be built: True)
	r-plotly-4.7.1-r3.3.2_0 (will be built: True)
	r-plotly-4.7.1-r3.4.1_0 (will be built: True)
	r-r.devices-2.15.1-r3.3.2_0 (will be built: True)
	r-r.devices-2.15.1-r3.4.1_0 (will be built: True)
	r-r2html-2.3.2-r3.3.2_0 (will be built: True)
	r-r2html-2.3.2-r3.4.1_0 (will be built: True)
	r-rainbow-3.4-r3.3.2_0 (will be built: True)
	r-rcppgsl-0.3.2-r3.3.2_0 (will be built: True)
	r-rcppgsl-0.3.2-r3.4.1_0 (will be built: True)
	r-rcppparallel-4.3.20-r3.3.2_0 (will be built: True)
	r-rcppparallel-4.3.20-r3.4.1_0 (will be built: True)
	r-rcpptoml-0.1.3-r3.3.2_0 (will be built: True)
	r-rcpptoml-0.1.3-r3.4.1_0 (will be built: True)
	r-rsm-2.8-r3.3.2_0 (will be built: True)
	r-rsm-2.8-r3.4.1_0 (will be built: True)
	r-signal-0.7_6-r3.3.2_0 (will be built: True)
	r-signal-0.7_6-r3.4.1_0 (will be built: True)
	r-skellam-0.2.0-r3.3.2_0 (will be built: True)
	r-skellam-0.2.0-r3.4.1_0 (will be built: True)
	r-som-0.3_5.1-r3.3.2_0 (will be built: True)
	r-som-0.3_5.1-r3.4.1_0 (will be built: True)
	r-d3heatmap-0.6.1.1-r3.3.2_0 (will be built: True)
	r-ggalt-0.4.0-r3.3.2_0 (will be built: True)
	r-ggalt-0.4.0-r3.4.1_0 (will be built: True)
```

The feedstocks are also building recipes for both R 3.3.2 and R 3.4.1. As a recent example, [r-funr-feedstock](https://github.com/conda-forge/r-funr-feedstock) was created yesterday, and binaries for both R versions are now available on Anaconda Cloud:

https://anaconda.org/conda-forge/r-funr/files

**Comment by bgruening** [comment]
I fixed that already, just look at one of the earlier failed travis runs and you will see that the old once where build against 3 different R versions. I rebased this branch against later master and now everything seems to be fine in this regard.

**Comment by jdblischak** [comment]
> I fixed that already, just look at one of the earlier failed travis runs and you will see that the old once where build against 3 different R versions. I rebased this branch against later master and now everything seems to be fine in this regard.

Sorry about that. I didn't realize it had already been fixed.

I looked at the older Travis builds, and didn't see a third version of R. But if you've fixed it, then no need to worry about this further.

https://travis-ci.org/conda-forge/staged-recipes/builds/274087708#L195
https://travis-ci.org/conda-forge/staged-recipes/builds/274084336#L195

**Comment by bgruening** [comment]
ping @ocefpaf  .... 3 ....

**Pull request merged**
