### PR TITLE
add rb-dotenv

### PR DESCRIPTION
**Pull request by rluria14**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rluria14** [comment]
@sodre @adbeda @agcopenhaver do you agree to be maintainers?

**Comment by agcopenhaver** [comment]
I agree

**Comment by rluria14** [comment]
@sodre this recipe is ready for review. I closed the previous PR and created a new one due to a problem with my staged-recipes folder.

**Comment by adbeda** [comment]
I agree

**Comment by rluria14** [comment]
> LGTM. We just need to wait for the all maintainers to respond.

Thanks, both maintainers have agreed.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
