### PR TITLE
Update travis Xcode to 9.4

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by beckermr** [comment]
We should merge this, right @conda-forge/core?

**Comment by hmaarrfk** [comment]
except for the fact that the init script is broken.

**Comment by beckermr** [comment]
Ack. I'm dumb. I think we need to download the proper OSX SDK.

**Comment by beckermr** [comment]
Yep. That's annoying...

**Comment by beckermr** [comment]
Whelp. That's not it.

This line appears in successful builds of xgboost:

https://travis-ci.org/conda-forge/xgboost-feedstock/jobs/473375740#L274

I am not seeing it here.

**Comment by beckermr** [comment]
I think that output is put in by travis? I cannot find it in any of the CI scripts.

**Comment by jakirkham** [comment]
Believe this issue has been fixed by PR ( https://github.com/conda-forge/staged-recipes/pull/7429 ). Have merged that into this PR to check.

**Comment by beckermr** [comment]
Grrrrr. I had the same idea but made the change in the wrong spot! LOL

https://github.com/conda-forge/staged-recipes/pull/7428/commits/a201f07084aaacad7cffbd48e723dcf88e715b54

**Comment by jakirkham** [comment]
We need your fix too. Just for different reasons :)

xref: https://github.com/conda-forge/staged-recipes/pull/7454

**Comment by beckermr** [comment]
LOL

**Comment by beckermr** [comment]
I'm completely baffled as to how that change fixed this issue BTW. I was just guessing...

**Comment by beckermr** [comment]
Any insight on this @jakirkham would be appreciated! ;)

**Comment by jakirkham** [comment]
`conda-forge-ci-setup` 2.* has [this code]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/4bcb68868203db371662cbce51560df980427010/recipe/run_conda_forge_build_setup_osx#L9-L23 ). It's not included in 1.*.

**Comment by beckermr** [comment]
Wow. I looked at that repo but not on the branch! Thanks!

**Comment by jakirkham** [comment]
Thanks @hmaarrfk and @beckermr :)

**Pull request merged**
