### PR TITLE
ptscotch: add recipe

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
Please add @basnijholt and @minrk as reviewers.

**Comment by basnijholt** [comment]
What is wrong with the existing [package](https://github.com/conda-forge/scotch-feedstock/tree/ptscotch) BTW?

**Comment by dalcinl** [comment]
The existing package is OK. This is a new package with the parallel (MPI-based) libraries and headers. If you look at the recipe, you will see that the new `ptscotch` actually runtime-depends on the original, sequential `scotch`. At some point, the original package had a parallel variant, but @minrk eventually removed it in conda-forge/scotch-feedstock@8ee72ce. What I'm proposing here is to have the two packages, the sequential `scotch` can be used for sequential apps/libraries, and `ptscotch` can be used for parallel MPI apps/libraries (e.g. `petsc` which currently has an update on-hold conda-forge/petsc-feedstock#18).

**Comment by minrk** [comment]
ptscotch is already building in a branch on scotch-feedstock: https://github.com/conda-forge/scotch-feedstock/tree/ptscotch

**Comment by dalcinl** [comment]
@basnijholt @minrk Shame on me! I didn't notice! I'll try to backport my changes in that branch.

**Comment by minrk** [comment]
Sorry, I should have mentioned it sooner in your other PRs.

**Pull request closed without merging**
