### PR TITLE
Adept-2

### PR DESCRIPTION
**Pull request by dougalsutherland**
Building off of https://github.com/conda-forge/staged-recipes/pull/4547, but with some fixes.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
Travis failure is:
```
../include/adept/Packet.h:280:37: error: use of undeclared identifier '_mm_undefined_ps'
      __m128 shuftmp= _mm_movehl_ps(_mm_undefined_ps(),
                                    ^
```
I think this is a problem with this older version of Clang, because  `_mm_undefined_ps` is documented as being in `xmmintrin.h` [in the current clang docs](https://clang.llvm.org/doxygen/xmmintrin_8h.html) and is present on my Mac (10.13) in `/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include/xmmintrin.h`.

There's already some workaround code in that file for old versions of GCC; I'll try adding a patch to use that.

**Comment by dougalsutherland** [comment]
Sorry for the long delay on this @arghdos, but I just merged the recipe.

A new feedstock will be created at https://github.com/conda-forge/adept-feedstock/ shortly, and you'll get some automated messages about managing it / joining the conda-forge organization. There'll be some pointers to docs there about how to update things going forward; the most important one is not to push directly to that repo, but instead make a fork and send PRs from there. (Don't make branches on the `conda-forge` repo either!) Feel free to ping me and/or conda-forge/core if you run into any issues.

**Comment by dougalsutherland** [comment]
(For reference, the adept-2 issue I opened about the build error is https://github.com/rjhogan/Adept-2/issues/7.)

**Comment by arghdos** [comment]
@dougalsutherland Thanks!!!  My CI process will finally be fully integrated into conda!

**Pull request merged**
