### PR TITLE
Add inputs via grayskull

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge/help-python - this is ready for review. As it's a noarch package, the osx-64 error does not matter.

**Comment by Tobias-Fischer** [comment]
Kind reminder @conda-forge/help-python @conda-forge/staged-recipes. Thanks :)!

**Comment by ocefpaf** [comment]
> @conda-forge/help-python - this is ready for review. As it's a noarch package, the osx-64 error does not matter.

Not necessarily, this package won't work on osx-64 without `pyobjc-framework-quartz`. See https://github.com/zeth/inputs/blob/a46681dbf77d6ab07834f550e5855c1f50701f99/setup.py#L31.

I'm on the fence between a better users experience and removing the noarch here or letting it "broken" on osx and hope the user knows that they need to install an extra dependency. I'm more inclined to the former though.

**Comment by Tobias-Fischer** [comment]
Just for me to understand: Is the plan to convert `pyobjc-framework-quartz` to a virtual package which leads to an empty package on `win` and `linux`, so we can add it as a dependency for `inputs` (i.e. this PR)?

**Comment by carterbox** [comment]
I'm also confused about how the `__osx` package helps here. Can someone explain? 🤔

This package doesn't qualify for noarch because it has a platform specific dependency. The simplest solution is to remove noarch and use a selector so the additional package is added for osx.

As was suggested, we could also add empty build variants of `pyobjc-framework-quartz`, so that selectors are not needed for this recipe, but this solution also doesn't need us to use `__osx`.

**Review by carterbox — CHANGES_REQUESTED** [review]
Waiting for switch away from noarch or an open PR at https://github.com/conda-forge/pyobjc-framework-quartz-feedstock to add empty metapackages.

**Comment by Tobias-Fischer** [comment]
Ok I moved away from `noarch` and added the osx-specific dependency. It would be great if you could have another look. We can always, later on, change the recipe if `pyobjc-framework-quartz` provides a virtual package in the future.

**Comment by BastianZim** [comment]
By adding an impossible version on osx it couldn't have been installed there. But I just realised that that also obviously applies to the other OSs so this approach is definitely correct — my bad.

**Pull request merged**
