### PR TITLE
matplotlib 1.5

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by scopatz** [comment]
Appveyor is not pleased

**Comment by pelson** [comment]
Has been done as a feedstock in https://github.com/conda-forge/matplotlib-feedstock.

**Comment by ocefpaf** [comment]
@pelson can I close this one and remove matplotlib from staged-recipes?

**Comment by pelson** [comment]
> @pelson can I close this one and remove matplotlib from staged-recipes?

That would be awesome. Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
> can I close this one

Done.

> and remove matplotlib from staged-recipes?

I guess you already did that in a previous PR.

**Pull request closed without merging**
