### PR TITLE
Add gwcs to conda-forge

### PR DESCRIPTION
**Pull request by mwcraig**
@nden -- can you please confirm that you are willing to be a maintainer on this? Builds on conda-forge will be used to populate the astropy conda channel in the future. Being a maintainer doesn't require much, just updating the version and checksum when a new release is made.

### CODE REVIEW

**Comment by mwcraig** [comment]
Failing because it needs asdf  #3469 to be merged first.

**Comment by nden** [comment]
Yes, that's fine. I'm afraid I'm not very versed in this yet. Is there someone I could ask for help in case of a problem?

**Comment by nden** [comment]
Sounds good. Thanks!

**Comment by mwcraig** [comment]
Close/reopen to trigger CI builds now that `asdf` has built.

**Pull request merged**
