### PR TITLE
Add cached-property

### PR DESCRIPTION
**Pull request by adament**

### CODE REVIEW

**Comment by adament** [comment]
So the CI fails because a dependency required for running the tests: freezegun has not been packaged for Python 3.6, I do not know how I should best fix this?

**Comment by dopplershift** [comment]
Open an issue at https://github.com/conda-forge/freezegun-feedstock

Or, for bonus points, submit a PR after you've run `conda smithy rerender` in the repository and committed the results.

**Comment by ocefpaf** [comment]
For even more bonus points add yourself as a maintainer for freezegun
 :-p

On Jan 19, 2017 3:23 PM, "Ryan May" <notifications@github.com> wrote:

Open an issue at https://github.com/conda-forge/freezegun-feedstock

Or, for bonus points, submit a PR after you've run conda smithy rerender in
the repository and committed the results.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/staged-recipes/pull/2234#issuecomment-273856134>,
or mute the thread

**Comment by adament** [comment]
The freezegun rebuild failed for one of the py36 platforms which made this recipe fail. Closing and reopening to force rebuild.

**Comment by adament** [comment]
How can I trigger the CircleCI rebuild?

**Comment by adament** [comment]
A cached-property recipe has now been added, so this pull request is no longer relevant.

**Pull request closed without merging**
