### PR TITLE
Add recipe for r-mockthat

### PR DESCRIPTION
**Pull request by mlondschien**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- x ] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mlondschien** [comment]
@conda-forge/r Please confirm that you'd be OK with being listed as a maintainer here.

**Comment by mfansler** [comment]
> @conda-forge/r Please confirm that you'd be OK with being listed as a maintainer here.

Sounds good! Unfortunately, linter won't recognize our comments - safe to ignore linter complaint about us.

**Comment by mlondschien** [comment]
I built the recipe with https://github.com/bgruening/conda_r_skeleton_helper/. First time I'm using this. Any idea why the windows build is failing?

```
conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {MatchSpec("msys2-conda-epoch==20160418"), MatchSpec("m2w64-fftw==3.3.4=6"), MatchSpec("m2w64-expat==2.1.1=2"), MatchSpec("m2w64-bwidget==1.9.10=2"), MatchSpec("m2w64-bzip2==1.0.6=6")}
Encountered problems while solving:
  - package m2-conda-epoch-20230914-0_x86_64 has constraint msys2-conda-epoch <0.0a0 conflicting with msys2-conda-epoch-20160418-1
  - package m2w64-bwidget-1.9.10-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
  - package m2w64-bzip2-1.0.6-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed
  - package m2w64-expat-2.1.1-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
  - package m2w64-fftw-3.3.4-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed


```

**Comment by mfansler** [comment]
> I built the recipe with https://github.com/bgruening/conda_r_skeleton_helper/. First time I'm using this. Any idea why the windows build is failing?
> 
> ```
> conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {MatchSpec("msys2-conda-epoch==20160418"), MatchSpec("m2w64-fftw==3.3.4=6"), MatchSpec("m2w64-expat==2.1.1=2"), MatchSpec("m2w64-bwidget==1.9.10=2"), MatchSpec("m2w64-bzip2==1.0.6=6")}
> Encountered problems while solving:
>   - package m2-conda-epoch-20230914-0_x86_64 has constraint msys2-conda-epoch <0.0a0 conflicting with msys2-conda-epoch-20160418-1
>   - package m2w64-bwidget-1.9.10-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
>   - package m2w64-bzip2-1.0.6-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed
>   - package m2w64-expat-2.1.1-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
>   - package m2w64-fftw-3.3.4-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed
> ```

Same as #25319. Still unclear what triggers this - will have to skip Windows build for now.

**Comment by mlondschien** [comment]
Thanks @mfansler. Let's merge. @nbenn can add himself as a maintainer later.

**Review by mfansler — APPROVED** [review]
Thanks for submitting this! ❤️

**Pull request merged**
