### PR TITLE
Adding ewah bool utils

### PR DESCRIPTION
**Pull request by neutrinoceros**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
ping @matthewturk

**Comment by matthewturk** [comment]
What's our best path forward here?  We do vendor the underlying EWAH library (in accordance with their license) and I think it's fine if we don't for the purposes of conda, but we will need to pin the version as occasionally upgrading that library has required updating the C++ toolchain etc.

**Comment by neutrinoceros** [comment]
Reading the fine letters it's actually okay to vendor it _as long as we package the license too_, which we already do.

**Comment by neutrinoceros** [comment]
Alright I took a minute to double check and I confirm that we are indeed properly packaging the LICENSE file for the vendored (and modified, as allowed by said license) package.
@matthewturk, do you agree to co-maintain this package with me ? the last thing from the todo list we need is your reply here :)

**Comment by matthewturk** [comment]
I hereby agree

**Comment by neutrinoceros** [comment]
@conda-forge/staged-recipes I think this is ready for review

**Pull request merged**
