### PR TITLE
ndarray-listener

### PR DESCRIPTION
**Pull request by Horta**

### CODE REVIEW

**Comment by Horta** [comment]
It is meant to replace https://github.com/conda-forge/ndarray_listener-feedstock for package name normalization reasons.

**Comment by ocefpaf** [comment]
@Horta ideally we don't create new packages when there is a name change. You can rename it in the old feedstock. The new name will be uploaded, but bare in mind that the feedstock will not be renamed.

**Comment by Horta** [comment]
@ocefpaf but ndarray_listener-feedstock is ugly.

**Comment by ocefpaf** [comment]
> @ocefpaf but ndarray_listener-feedstock is ugly.

that will remain only on the feedstock. You can still rename the package.

However, since you are the main author, it is up to you if you want to remove the old feedstock, packages, etc and merge this one.

**Comment by Horta** [comment]
@ocefpaf but I don't have permission to remove the old feedstock, that is why I'm asking...

**Comment by ocefpaf** [comment]
The thing is that you don't really have to remove it. The feedstock name is nothing to the package name. By deleting old ones and creating new ones you are only putting a burden on @conda-forge/core group.

You can rename the package in the `meta.yaml`  though, and that is the important part if you are worried about style.

**Comment by Horta** [comment]
Ok, I'm happy to do that also. Will create new pull request there then. Thank you!

**Pull request closed without merging**
