### PR TITLE
Adding kedro

### PR DESCRIPTION
**Pull request by lorenabalan**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Hello, I was trying to add ``kedro``some time ago to the ``conda-forge``, but I forgot about that recipe and didn't finish it, I think I faced one problem but I was kinda busy at that time
haha

If you want to you can generate that recipe using [Grayskull :skull: ](https://github.com/marcelotrevisani/grayskull/), it will try to generate a better recipe than ``conda-build``

Grayskull generated the following recipe if you want to use it
```yaml
{% set name = "kedro" %}
{% set version = "0.15.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 310b18c0784c301d2375ca28e50a8967ba56ef3048b461f52ff6b8c31104772a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<3.8
  run:
    - anyconfig <1.0,>=0.9.7
    - azure-storage-blob <2.0,>=1.1.0
    - azure-storage-file <2.0,>=1.1.0
    - azure-storage-queue <2.0,>=1.1.0
    - click <8.0
    - cookiecutter <2.0,>=1.6.0
    - fsspec <0.7.0,>=0.5.1
    - pandas <1.0,>=0.24.0
    - pandas-gbq <1.0,>=0.12.0
    - pip-tools <5.0.0,>=4.0.0
    - pyarrow <1.0.0,>=0.12.0
    - python >=3.5,<3.8
    - python-json-logger <1.0,>=0.1.9
    - pyyaml <6.0,>=4.2
    - requests <3.0,>=2.20.0
    - s3fs <0.4.1,>=0.3.0
    - sqlalchemy <2.0,>=1.2.0
    - tables <3.6,>=3.4.4
    - toposort <2.0,>=1.5
    - xlrd <2.0,>=1.0.0
    - xlsxwriter <2.0,>=1.0.0

test:
  imports:
    - kedro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/kedro/
  summary: Kedro helps you build production-ready data and analytics pipelines
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - lorenabalan
```

**Comment by marcelotrevisani** [comment]
> Hello, I was trying to add `kedro`some time ago to the `conda-forge`, but I forgot about that recipe and didn't finish it, I think I faced one problem but I was kinda busy at that time
> haha
> 
> If you want to you can generate that recipe using [Grayskull skull ](https://github.com/marcelotrevisani/grayskull/), it will try to generate a better recipe than `conda-build`
> 
> Grayskull generated the following recipe if you want to use it
> 
> ```yaml
> {% set name = "kedro" %}
> {% set version = "0.15.9" %}
> 
> 
> package:
>   name: {{ name|lower }}
>   version: {{ version }}
> 
> source:
>   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
>   sha256: 310b18c0784c301d2375ca28e50a8967ba56ef3048b461f52ff6b8c31104772a
> 
> build:
>   number: 0
>   noarch: python
>   script: {{ PYTHON }} -m pip install . -vv
> 
> requirements:
>   host:
>     - pip
>     - python >=3.5,<3.8
>   run:
>     - anyconfig <1.0,>=0.9.7
>     - azure-storage-blob <2.0,>=1.1.0
>     - azure-storage-file <2.0,>=1.1.0
>     - azure-storage-queue <2.0,>=1.1.0
>     - click <8.0
>     - cookiecutter <2.0,>=1.6.0
>     - fsspec <0.7.0,>=0.5.1
>     - pandas <1.0,>=0.24.0
>     - pandas-gbq <1.0,>=0.12.0
>     - pip-tools <5.0.0,>=4.0.0
>     - pyarrow <1.0.0,>=0.12.0
>     - python >=3.5,<3.8
>     - python-json-logger <1.0,>=0.1.9
>     - pyyaml <6.0,>=4.2
>     - requests <3.0,>=2.20.0
>     - s3fs <0.4.1,>=0.3.0
>     - sqlalchemy <2.0,>=1.2.0
>     - tables <3.6,>=3.4.4
>     - toposort <2.0,>=1.5
>     - xlrd <2.0,>=1.0.0
>     - xlsxwriter <2.0,>=1.0.0
> 
> test:
>   imports:
>     - kedro
>   commands:
>     - pip check
>   requires:
>     - pip
> 
> about:
>   home: https://pypi.org/project/kedro/
>   summary: Kedro helps you build production-ready data and analytics pipelines
>   license: Apache-2.0
>   license_file: LICENSE.md
> 
> extra:
>   recipe-maintainers:
>     - lorenabalan
> ```

I just remember the problem which I faced, ``kedro`` had a problem in their ``setup.pt`` and I fixed some days ago, probably my recipe will work then, but if you want to integrate it, please feel free to use ``grayskull``, modify that recipe or you can use the example which I added

**Comment by marcelotrevisani** [comment]
Yeap, it was related to this one
https://github.com/quantumblacklabs/kedro/pull/239

So now it should be fine, you can get the example which I added in the previous message and it should be fine I think. Please modify as you need

**Comment by lorenabalan** [comment]
@marcelotrevisani Thanks for the super quick response! Could your problem be related to `test_requirements`, as per [this user issue](https://github.com/quantumblacklabs/kedro/issues/313)? That's one of the reasons I was trying to use GitHub releases rather than PyPI.

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani Thanks for the super quick response! Could your problem be related to `test_requirements`, as per [this user issue](https://github.com/quantumblacklabs/kedro/issues/313)? That's one of the reasons I was trying to use GitHub releases rather than PyPI.

let me try to run ``conda-build`` locally to see if [Grayskull](url) recipe is working fine.

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani Thanks for the super quick response! Could your problem be related to `test_requirements`, as per [this user issue](https://github.com/quantumblacklabs/kedro/issues/313)? That's one of the reasons I was trying to use GitHub releases rather than PyPI.

hum... I think I fixed that with https://github.com/quantumblacklabs/kedro/pull/239
You might need to add that file in our ``setup.py`` then

**Comment by marcelotrevisani** [comment]
I am getting a conflicting dependency with ``pip-tools`` and ``tables``

**Comment by marcelotrevisani** [comment]
We need to package ``pip-tools`` and ``tables`` first
Let me see if [Grayskull](https://github.com/marcelotrevisani/grayskull/) will do a good job

I will open a PR for them as well

**Comment by marcelotrevisani** [comment]
I opened a PR for ``pip-tools``, I will add ``tables`` after it
I am just a bit busy right now, so it may take a while

**Comment by lorenabalan** [comment]
Thank you so much @marcelotrevisani I'll keep an eye on this, it's not urgent though!

**Comment by synapticarbors** [comment]
Isn't `tables` just:

https://github.com/conda-forge/pytables-feedstock

which is already available?

**Comment by marcelotrevisani** [comment]
> Isn't `tables` just:
> 
> https://github.com/conda-forge/pytables-feedstock
> 
> which is already available?

Yeap, that is already available. We are facing some problems to generate the feedstock for pip-tools. After that we can continue here for kedro

**Comment by marcelotrevisani** [comment]
@lorenabalan , for now you will need to package it using the github release indeed

I think after this PR
https://github.com/quantumblacklabs/kedro/pull/332

You will be able to use the sdist package on ``pypi``

**Comment by marcelotrevisani** [comment]
@lorenabalan , I hope you don't mind but I opened a PR (#11331) to add this recipe, it should work now

**Comment by lorenabalan** [comment]
@marcelotrevisani , no problem, thanks for looking into this. Out of interest, is there a benefit of using pypi over github releases on the regular? We were thinking the second would protect us more in case something goes wrong on pypi, at least the package would be found on conda, and we wouldn't depend on the pypi part of the release process.

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani , no problem, thanks for looking into this. Out of interest, is there a benefit of using pypi over github releases on the regular? We were thinking the second would protect us more in case something goes wrong on pypi, at least the package would be found on conda, and we wouldn't depend on the pypi part of the release process.

Usually, we try to be consistent with ``pypi`` that is why we prefer to use it from the sdist on ``pypi``
and the sdist there are usually smaller when we compare with the ``github`` tarballs. That is because the pip sdist usually does not package the entire repository (because it follows the ``setup.py``, or ``setup.cfg``, ``pyproject.toml``, etc) and a lot of projects package the entire repository on github tarballs
You can check it if you download the sdist package on ``pypi`` and compare with the tarballs on github

But it is your choice as a maintainer to which source you are going to get your project. I don't mind much, I just prefer to use ``pypi`` when it is possible/convenient

**Comment by lorenabalan** [comment]
Makes sense, thank you! I'll go ahead and close this PR now.

**Pull request closed without merging**
