### PR TITLE
Add isort

### PR DESCRIPTION
**Pull request by jakirkham**
Generated with `conda skeleton pypi` and cleaned up after.

### CODE REVIEW

**Comment by dopplershift** [comment]
Um.....https://github.com/conda-forge/isort-feedstock

**Comment by ocefpaf** [comment]
Thanks @dopplershift! I just saw that too with @dharhas script from SciPy! We should get that running as a service here together with the linter...

**Comment by jakirkham** [comment]
Oops, sorry, must have missed that one. Thanks @dopplershift.

> We should get that running as a service here together with the linter...

I feel like that came up in discussion awhile back, but am not finding the reference ATM.

**Comment by dharhas** [comment]
I have an open pr for the actual compare script I built during the sprints here https://github.com/conda-forge/conda-forge.github.io/pull/195

**Pull request closed without merging**
