### PR TITLE
add r-stars

### PR DESCRIPTION
**Pull request by ocefpaf**
Needed for https://github.com/conda-forge/r-mapview-feedstock/pull/5

### CODE REVIEW

**Comment by bgruening** [comment]
@ocefpaf such PRs would really benefit if the building of pkgs follows a DAG that is pre-calcualted before.

**Comment by ocefpaf** [comment]
> @ocefpaf such PRs would really benefit if the building of pkgs follows a DAG that is pre-calcualted before.

Not sure what you mean. What is DAG?

**Comment by bgruening** [comment]
Just a graph of the dependencies (https://en.wikipedia.org/wiki/Directed_acyclic_graph). Essentially you could then put many recipes in one PR

**Comment by ocefpaf** [comment]
Ah, OK. Thanks!

But the issue here is an updated for an existing package:

https://github.com/conda-forge/r-classint-feedstock/pull/2

that will probably open a can of worms on dependencies and pinning. So at the end it will be many PRs to different places.

**Pull request closed without merging**
