### PR TITLE
Add ipympl recipe

### PR DESCRIPTION
**Pull request by SylvainCorlay**
cc @tacaswell @jasongrout

### CODE REVIEW

**Comment by jakirkham** [comment]
Please rebase on current `master`. There is some clutter here that has since been removed.

**Comment by SylvainCorlay** [comment]
Done.

**Comment by SylvainCorlay** [comment]
Apparently, I need to add `conda-forge/label/rc` to get matplotlib 2.0.0b3.

**Comment by SylvainCorlay** [comment]
@jakirkham is this something we can do in conda-forge?

**Comment by jakirkham** [comment]
Not ATM. This actually raises a lot of interesting questions.

**Comment by jakirkham** [comment]
@pelson, how do we feel about enabling the rc channel? My gut feeling is I don't want to just generally enable it. Should we think about a way to enable it per recipe for builds? Where should packages that depend on RCs live?

**Comment by SylvainCorlay** [comment]
Is there a staged-recipes repo for me to add this as an rc package? In any case it is 0.0.2.

**Comment by jakirkham** [comment]
Sorry we still haven't sorted what we do with RCs. So this raises more questions on top of those already unanswered questions.

**Comment by SylvainCorlay** [comment]
Hum, so how did matplotlib get there?

**Comment by tacaswell** [comment]
@pelson did some magic to give mpl a devel branch which pushes to the rc
channel

**Comment by jakirkham** [comment]
See this [comment]( https://github.com/conda-forge/matplotlib-feedstock/pull/24#issuecomment-221496870 ). We definitely we should have a process for this and we should discuss it.

**Comment by jakirkham** [comment]
In other words, the infrastructure is there for conda-forge to do this. Though I would argue that conda still needs some growth (e.g. I want one RC I picked not all RCs). This last point I think is part of the hold up for this happening more.

**Comment by jjhelmus** [comment]
I think there is a big difference between packages which have a release candidate (rc) and packages which depend upon a release candidate of one or more packages.  The latter can be very brittle as changes in the API of the dependency can and should be allowed to break the top level package.

**Comment by SylvainCorlay** [comment]
I would be fine making this one an rc release too.

**Comment by jakirkham** [comment]
That seems like a sensible way to go.

**Comment by SylvainCorlay** [comment]
(or only put this 0.0.2 on the rc channel)

**Comment by jakirkham** [comment]
That was the other thought I was playing with.

**Comment by jjhelmus** [comment]
I think this can be done by adjusting the [`conda-forge.yaml` file in the feedstock](https://github.com/conda-forge/matplotlib-feedstock/blob/devel/conda-forge.yml).  As long as the dependencies and the package itself have the same channel label everything should work when a user goes to install the package. 

As for building the package, you would need to add the extra channel in the CI scripts which is not hard, just has not been done yet as far as I know.

**Comment by SylvainCorlay** [comment]
So how would this work? Let the feedstock be created from this and modify it?

**Comment by jakirkham** [comment]
We would probably want to add a skip here before merging. That way these don't get tossed into `main`. Then yes fix-up in the feedstock.

**Comment by jakirkham** [comment]
> As for building the package, you would need to add the extra channel in the CI scripts which is not hard, just has not been done yet as far as I know.

I want to say there is a setting for that too in `conda-forge.yaml`, but I'm not remembering what it is.

**Comment by jjhelmus** [comment]
> I want to say there is a setting for that too in conda-forge.yaml, but I'm not remembering what it is.

[conda-smithy](https://github.com/conda-forge/conda-smithy) would be the place to look.

**Comment by jjhelmus** [comment]
Looks like you can add additional channels to use during the build using a channel/sources section. So something like the following in the `conda-forge.yaml file`:

``` yaml
channels:
  targets:
    - [conda-forge, rc]
  sources:
    - [conda-forge]
    - [conda-forge, rc]
```

Then run `conda smithy rerender` in the root of the feedstock directory.  The CI scripts should be recreated with the necessary modification.

**Comment by jakirkham** [comment]
`sources`, yes, that sounds right. Thanks for hunting that down.

**Comment by SylvainCorlay** [comment]
> Looks like you can add additional channels to use during the build using a channel/sources section. So something like the following in the conda-forge.yaml file:

That is for the feedstock right? Not on the staged recipes repo?

**Comment by SylvainCorlay** [comment]
> We would probably want to add a skip here before merging

how do we skip?

**Comment by SylvainCorlay** [comment]
@tacaswell we could also wait for mpl 2.0. Is there any major thing you need to change before that?

**Comment by SylvainCorlay** [comment]
@jjhelmus @jakirkham since matplotlib 2.0 was release, we don't need to require the release candidate and this can get in as a regular package.

**Comment by SylvainCorlay** [comment]
Yay success!

**Comment by tacaswell** [comment]
:+1: Thanks @SylvainCorlay

**Comment by SylvainCorlay** [comment]
Now that mapltotlib 2.0 is out, we can revive this :)

**Comment by SylvainCorlay** [comment]
@conda-forge/core are you guys ok with pressing the green?

The "Needs Decision" tag was related to the dependency on matplotlib RC, which is not an issue anymore since we can depend on matplotlib 2.0.

**Comment by scopatz** [comment]
Thanks @SylvainCorlay

**Pull request merged**
