### PR TITLE
Add initial morecantile recipe

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR adds `morecantile` package to `conda-forge`. This is needed for https://github.com/conda-forge/rio-tiler-feedstock/pull/1.

## Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by lsetiawan** [comment]
@ocefpaf please help. I don't quite understand the failure here for the `win_64` build. Thanks for your time! Hope you're doing well :smile: 

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=272072&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77&l=814

**Comment by BastianZim** [comment]
I think the error is because you're not defining `entry_points` as outlined under [noarch python](https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python).
Adding 

```yaml
entry_points:
  - morecantile=morecantile.scripts.cli:cli
```
to your build section should fix it. (Entry points: https://github.com/developmentseed/morecantile/blob/4f1041daae3cadb6dcf6c11eee515c521b637665/setup.py#L43-L46)

Your build should then look like:

```yaml
build:
  number: 0
  noarch: python
  entry_points:
    - morecantile=morecantile.scripts.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
```
(I just had the same problem and this fixed it, I'm not a core member so take this with a grain of salt... 😄)

**Comment by lsetiawan** [comment]
@BastianZim Thanks so much! I'm trying it out :smile:

**Comment by BastianZim** [comment]
Happy to help, glad that it's working! 😄

**Comment by lsetiawan** [comment]
@conda-forge/help-python Please review. Thank you so much for your time!

**Comment by lsetiawan** [comment]
> @ocefpaf please help. I don't quite understand the failure here for the `win_64` build. Thanks for your time! Hope you're doing well smile
> 
> https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=272072&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77&l=814

@ocefpaf: @BastianZim has helped me resolved the problem, I totally missed that this package has a cli and that it needs to go into the recipe.

**Comment by ocefpaf** [comment]
Yep. Thanks @BastianZim! BTW, try [grayskull](https://conda-forge.org/blog/posts/2020-03-05-grayskull/) to create your recipes. It catches things like that for you automatically.

**Comment by BastianZim** [comment]
Happy to help @ocefpaf! Grayskull is currently not able to extract all entry_points, probably because of the way the entry points are defined in this case. 
I had the same problem in https://github.com/conda-forge/staged-recipes/pull/13848 and will create an issue in grayskull once I've verified it with some more packages.

**Comment by BastianZim** [comment]
Grayskull generated YAML:

```yaml
{% set name = "morecantile" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morecantile-{{ version }}.tar.gz
  sha256: 70c2b9f81ea3cb4c67763d1fba1b103979b5aab4d40f82c2864ea3b1229f29b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - pydantic
    - python >=3.0
    - rasterio >=1.1.7

test:
  imports:
    - morecantile
    - morecantile.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/developmentseed/morecantile
  summary: Construct and use map tile grids (a.k.a TileMatrixSet / TMS).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ADD_YOUR_GITHUB_ID_HERE
```

**Comment by ocefpaf** [comment]
> I had the same problem in #13848 and will create an issue in grayskull once I've verified it with some more packages.

Pinging @marcelotrevisani here, the author of grayskull, just for awareness. Please open the issue! Thanks!

**Comment by lsetiawan** [comment]
I second @BastianZim of grayskull problem. This recipe was actually created with that :sweat_smile: .

**Pull request merged**
