### PR TITLE
Adding `ipyvizzu` and `ipyvizzu-story` from PyPI

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sugatoray** [comment]
## Reason for Build Failure: `1/N`

`Observation`:

> :point_right: *Module 'jsonschema' is not available in dependencies.*

- `line number: 1246`: [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=542250&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1246)
- `time elapsed`: `3m:51s`

```sh
import jsonschema  # type: ignore
ModuleNotFoundError: No module named 'jsonschema'
```


<details>
<summary><b>Click to expand</b>: Detailed Error Trace</summary>
<p>

```sh
import: 'ipyvizzu'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/ipyvizzu_1658945304505/test_tmp/run_test.py", line 2, in <module>
    import ipyvizzu
  File "/home/conda/staged-recipes/build_artifacts/ipyvizzu_1658945304505/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/ipyvizzu/__init__.py", line 3, in <module>
    from .chart import Chart
  File "/home/conda/staged-recipes/build_artifacts/ipyvizzu_1658945304505/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/ipyvizzu/chart.py", line 10, in <module>
    from ipyvizzu.animation import Animation, Snapshot, AnimationMerger
  File "/home/conda/staged-recipes/build_artifacts/ipyvizzu_1658945304505/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/ipyvizzu/animation.py", line 8, in <module>
    import jsonschema  # type: ignore
ModuleNotFoundError: No module named 'jsonschema'
Tests failed for ipyvizzu-0.12.0-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/staged-recipes/build_artifacts/broken
WARNING:conda_build.build:Tests failed for ipyvizzu-0.12.0-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/staged-recipes/build_artifacts/broken
TESTS FAILED: ipyvizzu-0.12.0-pyhd8ed1ab_0.tar.bz2

```

</p>
</details>

**Comment by sugatoray** [comment]
## Notes

The build passes for Linux alone (fails for OSX and Windows). But that is okay as the recipe is `noarch: python`. Only successful linux build is sufficient.

**Comment by sugatoray** [comment]
PR is ready. Request for review/merging.

cc: @conda-forge/help-python @ocefpaf @BastianZim

**Comment by ocefpaf** [comment]
> cc: @conda-forge/help-python @ocefpaf @BastianZim

You don't need to ping me or Bastian. We are already part of the python review team.

**Comment by sugatoray** [comment]
> Not necessarily. If it is a missing dependency on those platform we can keep noarch but if it is something that will make the package installable but unusable we cannot. Looks like Windows is the former but I'm not sure what is going on with macOS.

So, what would you suggest here? I am kind of out of my depth here (osx). Could you please ask someone else to also review this PR and see if they can suggest anything about what's going on with macOS?

**Comment by ocefpaf** [comment]
Looks like a restart did the trick.

**Pull request merged**
