### PR TITLE
update shogun-cpp to 6.1.4 and define blas variants

### PR DESCRIPTION
**Pull request by vigsterkr**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by vigsterkr** [comment]
the linter fails because of the `{{ blas_variant }}` section in the requirements.

**Comment by vigsterkr** [comment]
currently i'm not so sure what's happening as i've recreated the very same conda env on an osx and it compiles just fine....

**Comment by vigsterkr** [comment]
cmake 3.16 series has a bug, that basically drops/does not include a lot of include paths specified by `target_include_directories`

**Comment by vigsterkr** [comment]
i'm not so sure what's happening with the win build:
```
%SRC_DIR%>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" ) 
ERROR: The system was unable to find the specified registry key or value.
CMake Error at CMakeLists.txt:27 (project):
  Failed to run MSBuild command:

    MSBuild.exe
```

**Comment by vigsterkr** [comment]
ok the mkl variant works nicely, the problem is currently with openblas variant... for some reason cmake is detecting libopenblas' static lib instead of the dynlib... still on the end the build complains about libgfortran symbol errors

**Comment by scopatz** [comment]
Hi there.  You should be updating the repo https://github.com/conda-forge/shogun-cpp-feedstock

**Comment by vigsterkr** [comment]
@scopatz ayay i'll just do that in a sec then....

**Comment by vigsterkr** [comment]
@scopatz btw while we are at it, there's nothing more i need to add to the meta.yaml that once this gets merged, python3.7 targets will be built automagically right?

**Comment by vigsterkr** [comment]
i mean this is just a simple shared lib but the dependent python lib (shogun) once updated should be built as well for 3.7

**Pull request closed without merging**
