### PR TITLE
Add osgQt recipe

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jcarpent** [comment]
@conda-forge/help-c-cpp, I think this PR is ready for review and merge

**Comment by jcarpent** [comment]
@conda-forge/help-c-cpp, I think this PR is ready for review and merge

**Comment by jcarpent** [comment]
@conda-forge/help-c-cpp, would it possible to merge this PR? Thanks.

**Comment by jcarpent** [comment]
@conda-forge/help-c-cpp, would it possible to merge this PR?

**Comment by nehaljwani** [comment]
@jcarpent Could you please move the patches inside a 'patches' directory and generate them using: `git format-patch` ? And also add reasons in the commit message for each patch? Thank you!

**Comment by ymontmarin** [comment]
@nehaljwani @jcarpent I am taking this to finish the recipe and PR. What is needed to finish the PR  ?

**Comment by jcarpent** [comment]
I think the comment made by @nehaljwani are the one to be handled, otherwise, everything seems to work fine.

**Comment by jcarpent** [comment]
Duplicated with #12771

**Pull request closed without merging**
