### PR TITLE
Add Cylc UI recipe

### PR DESCRIPTION
**Pull request by kinow**
Hi,

this pull request is to add a new recipe for the package Cylc UI. This is the user interface, of Cylc Flow 8, a Python package, already in Conda Forge.

The Cylc UI is a JavaScript application, written with Vue.js. What we have in this recipe, is a simple source URL to a github release (0.1 at the moment). The `build.sh` simply copies the folder `cylc-ui` into the Conda environment's `work` directory.

Then, when `jupyterhub` starts the UI Server (middleware between Cylc Flow & Cylc UI Server), it uses the static files from Cylc UI, from the Conda environment's `work` directory - though not sure if it is considered bad practice to have this sort of files in the work directory.

Thanks!
Bruno

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by kinow** [comment]
Also note: I've added a dummy test after the bot failed due to that. Not sure if there's a better way to test it, as all that we have are just HTML/JS/CSS files inside a ZIP file.

**Comment by marcelotrevisani** [comment]
Shouldn't you install this package using ``npm``?

**Comment by marcelotrevisani** [comment]
Please see if it is applicable 
https://github.com/conda-forge/staged-recipes/wiki/Recipes-that-bundle-javascript-libraries

**Comment by kinow** [comment]
I will have a look at the wiki and try this way too.

Thanks Marcelo!

**Comment by kinow** [comment]
Hi @marcelotrevisani 

This recipe won't exactly bundle a Javascript library. It will put the static files used by a Tornado web application from #9786.

When our development is done in the Vue.js UI application for this package, we then create a production version of the site, with the optimized JS/CSS files, and a simple `index.html`. Plus a few images.

All of this gets included in a ZIP file, and added to a GitHub tag/release.

What we were envisaging on this recipe, was a way to make those static files available to the Tornado application that runs with the recipe from #9786 .

Users running Cylc UI Server installed via `conda install cylc-uiserver` will have a default `jupyterhub_config.py` that specifies the location of these static files.

We didn't create a conventional npm recipe here, because

- we thought the site didn't need to be re-created anywhere else
- the output of Cylc UI never goes to a `node_modules` folder, and is never imported by other JS applications

However, it should be possible to package Cylc UI in a different way. Maybe leaving just the code in the GitHub tag, and then re-building it with this recipe if necessary. That would run some command like `npm install && NODE_ENV=production npm run build -- --modern`. The output would be several `.js` and `.css` files, some `png`s and `ico`'s, and an `index.html`. Ideally we would like to have these files in a location that can be used when starting the other process via JupyterHub, which executes a command like `cylc-uiserver --static $HOME/etc/etc/etc/cylc-ui-0.2/`.

What do you suggest?

**Comment by kinow** [comment]
Oh, and it used to be part of the Cylc metapackage, which is now #10593 

The version deployed in my personal conda channel has this Cylc UI application as part of Cylc.

But we decided that we would like to be able to install a version of the UI, without having to re-deploy everything. That's why we created this separate conda recipe.

**Comment by kinow** [comment]
Thanks @marcelotrevisani !!!

**Pull request merged**
