### PR TITLE
Added findimports 1.5.2.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by moorepants** [comment]
Getting this error on windows:

```
Packaging findimports
INFO conda_build.build:bundle_conda(1451): Packaging findimports-1.5.2-pyh9f0ad1d_0
Packaging findimports-1.5.2-pyh9f0ad1d_0
number of files: 11
WARNING: failed to get_linkages, codefile_type('C:\Miniconda\conda-bld\findimports_1601973694774\_h_env\Scripts\findimports.exe')=EXEfile
   INFO: sysroot: 'C:/Windows/' files: '['winhlp32.exe', 'win.ini', 'twain_32/wiatwain.ds', 'twain_32.dll']'
   INFO (findimports): Interpreted package 'findimports' is interpreted by 'python'
[noarch_python] Noarch package contains binary script: findimports.exe
##[error]Cmd.exe exited with code '1'.
```

**Comment by scopatz** [comment]
Thanks!

**Comment by moorepants** [comment]
We don't need to worry about the windows error?

**Comment by scopatz** [comment]
Not for noarch packages

**Pull request merged**
