### PR TITLE
Adding the Tracy C++ library (and its Python bindings)

### PR DESCRIPTION
**Pull request by ManifoldFR**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jcarpent** [comment]
I accept to be maintainer of this package

**Comment by jorisv** [comment]
I accept to be maintainer of this package

**Comment by ManifoldFR** [comment]
Related: wolfpld/tracy#720

**Comment by ManifoldFR** [comment]
@conda-forge/help-c-cpp, ready for review!

**Comment by jorisv** [comment]
@conda-forge/staged-recipes @conda-forge/help-c-cpp This recipe is ready for review.

**Review by xhochy — APPROVED** [review]

**Comment by ManifoldFR** [comment]
Thank you @xhochy !!

**Comment by bgruening** [comment]
@ManifoldFR @xhochy we have https://anaconda.org/search?q=tracy also in bioconda.

The linter initially caught it: https://github.com/conda-forge/staged-recipes/pull/27506#issuecomment-2334343272

But I think it can not deal with "outputs". Can we rename the "tracy" package on conda-forge?

**Comment by jorisv** [comment]
Hello, the output causing the issue is the « meta package » output (the one installing all the other outputs).
Is there any convention to name a « meta package » in conda-forge ?

Otherwise we can rename this package into tracy-profiler (and tracy-client and tracy-client-python into tracy-profiler-client and tracy-profiler-client-python).

**Comment by xhochy** [comment]
That sounds like a good way forward!

**Comment by jorisv** [comment]
@xhochy What did we have to do on our side ? A PR on the [feedstock](https://github.com/conda-forge/tracy-feedstock/) ?

**Comment by xhochy** [comment]
Yes, and you need to allow the feedstock to use the new names via an [admin-request](https://github.com/conda-forge/admin-requests)

**Comment by bgruening** [comment]
Thanks a lot everyone! Very appreciated!

**Comment by jorisv** [comment]
The [admin-request](https://github.com/conda-forge/admin-requests/pull/1239) had been merged and the package with the new name is released.

**Pull request merged**
