### PR TITLE
add stone recipe

### PR DESCRIPTION
**Pull request by cjmartian**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by BastianZim** [comment]
Just FYI, I have also added stone here https://github.com/conda-forge/staged-recipes/pull/13960 but the tests for windows currently fail. I've opened an issue and they're currently checking where the cause could be. If you'd like to take over, let me know.

**Comment by cjmartian** [comment]
@BastianZim It looks like you're running much more of the test suite than I am.
It may be worth writing a patch to skip that failing `test_whitespace` just on windows. 
I'm open either way. Maybe someone from core can tell us what they'd prefer.
@conda-forge/python

**Comment by BastianZim** [comment]
@cjmartian Yeah I had previously used and tested stone locally and found it to be a bit unpredictable so I wanted to include the upstream tests to make sure that everything's working.
Sure, a patch should be easy. Not sure how urgently you need this but upstream is also aware of this and investigating (https://github.com/dropbox/stone/issues/214) so we could also wait for that.

**Comment by cjmartian** [comment]
@BastianZim I only need it to build dropbox, as it's a requirement now. I'm okay with waiting though. 
Maybe we wait for that and I close out this PR in support of yours.

**Comment by BastianZim** [comment]
Ahh ok, yeah I'm trying to do the same. 😄 
Ok, sounds good. I'll follow up with dropbox in case I don't hear anything in the next couple of days and can keep you in the loop if you want?

**Comment by BastianZim** [comment]
Should I add the maintainer from your PR to mine? Happy to share that (Or hand over) since I also only need it for dropbox.

**Comment by BastianZim** [comment]
Just to add, upstream is only testing on macOS, from what I could find: https://github.com/dropbox/stone/actions/runs/514261108

**Comment by cjmartian** [comment]
That's kind of what I saw too. They didn't seem to test on Windows which leads me to believe that turning that test off would be fine haha
Sure you can add me and keep me in the loop. I can also talk to conda-forge/core on my end and see if we can't push this thing through!
Thanks for starting this conversation @BastianZim I wish I would've looked a little harder to see if there was an existing PR

**Comment by BastianZim** [comment]
Yeah, generally agree. I'd just prefer making sure that the error is in the tests and not in the product... Although from what I can see, the problem shouldn't occur when using this with dropbox so we might just ignore it and add a warning in the meta.yaml. 
What just came to my mind with the PR in conda though, is momentarily restricting the package using `__unix` and then removing that once we have the confirmation from dropbox that windows is fine. Would keep the package `noarch` and not restrict the dropbox development. What do you think? And yes, best practise advice from core is always appreciated 😄!
Cool, have added you!
Ahh no worries, happy to help!

**Comment by cjmartian** [comment]
That's not a bad idea at all! I think restricting it until we have confirmation would be the safe thing to do. That would make dropbox only buildable for unix platforms at that point. Which might be acceptable in the meantime.

**Comment by BastianZim** [comment]
Ok cool, I've added `__unix` so that should restrict it temporarily. Since you offered though, would you mind checking with core if that's the preferred approach? I think we're being quite careful here and just want to double-check that it's not an overkill. 
True but I would accept it since it means that we're on the safe side and changing it back to allowing windows is just a one-line change in this package with no extra work required elsewhere, as dropbox can already be `noarch`. But then again, in the end, it depends on how careful you/Anaconda and conda-forge/core want to be, I'm happy either way since I just need it for dropbox. 😄

**Comment by cjmartian** [comment]
Haha you got it! I'll circle back here once I get something from conda-forge

**Review by marcelotrevisani — APPROVED** [review]

**Comment by BastianZim** [comment]
Thanks for the approval @marcelotrevisani! Just to confirm, this is in response to our concerns above, correct?

**Comment by BastianZim** [comment]
Since the actual PR is at https://github.com/conda-forge/staged-recipes/pull/13960, should I then ping the python staged recipes team there to have this reviewed and merged?

**Comment by ocefpaf** [comment]
@BastianZim and @cjmartian I'm a bit lost in the messages. What is the way forward here?

**Comment by BastianZim** [comment]
@ocefpaf 
In short: The import tests for this package work but running the upstream tests [fails on windows](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=277449&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77). Upstream [does not test](https://github.com/dropbox/stone/actions/runs/514261108) on Windows at all so we have no way of verifying if this is because of 1) The conda test environment, 2) the tests themselves or 3) the underlying software.
I have opened an issue there (https://github.com/dropbox/stone/issues/214) but haven't heard back.
The two options therefore are:

1. Skip the tests on windows
2. Add `__unix` to the package so that it's not available on windows until this is sorted out.  

I would've normally gone with 2. but the dropbox package depends on this so we would prevent a fairly large userbase from installing dropbox without even knowing if the bug would actually affect them. So I just wanted to check if I'm being overly cautious here and if we should just ignore the bug, or if we should accept not having this on windows until upstream replies?

(Also the PR that should get merged is at https://github.com/conda-forge/staged-recipes/pull/13960, we just discussed everything here)

**Comment by BastianZim** [comment]
@ocefpaf Just checking if you're happy with 2.? Dropbox just released a new version so it'd be good if we could have this package available.

**Comment by ocefpaf** [comment]
I would go with `2`, better than shipping a broken package on Windows.

**Comment by BastianZim** [comment]
@ocefpaf Makes sense, thanks for the feedback! Would you then mind merging https://github.com/conda-forge/staged-recipes/pull/13960? Or should I ping staged recipes?

**Pull request closed without merging**
