### PR TITLE
Add num2words

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This adds a recipe for [`num2words`](https://github.com/savoirfairelinux/num2words).

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/help-python, I'm struggling with this one. The [windows build](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22277650) is failing because it can't find the installed executable on the `PATH` (I think):

```
(%PREFIX%) %SRC_DIR%>num2words --help 
'num2words' is not recognized as an internal or external command,
operable program or batch file.
```

The package is just a standard enough `setuptools`-based python install, although I'm not a developer of it, so might have missed something. Can someone help debug this, or suggest the obvious solution that I'm missing?

**Comment by mariusvniekerk** [comment]
You need an entrypoint to get this script

**Comment by duncanmmacleod** [comment]
@mariusvniekerk, thanks, can I configure an entrypoint just in the `meta.yaml`, or do I also need to set things up in `setup.py` etc to call out to a function as normal.

It's strange that this seems to work for other recipes I have used on windows, but maybe I'm just misunderstanding how this whole system works (at least on windows).

**Comment by mariusvniekerk** [comment]
Make one in the meta.yaml.  Its mandatory for noarch python packages that have entry points

**Comment by duncanmmacleod** [comment]
@mariusvniekerk, this package technically doesn't have entry points, it uses the standard `scripts` kwarg to `setuptools.setup` and points at a script distributed under `/bin/`. I'm sorry if just being dumb.

**Comment by duncanmmacleod** [comment]
Or is it just that you can't use `noarch: python` with python packages that use `scripts` (as opposed to `entry_points`?

**Comment by beckermr** [comment]
Yes @duncanmmacleod. The scripts entry is not compatible with noarch python. This is not well documented in the conda-forge docs. When the conda-forge bots issue a PR suggesting noarch, this is in the list of items to check. I have not myself been able to find these items. It would be great if the linter produced them regularly for ppl to see or something.

**Pull request closed without merging**
