### PR TITLE
add sphinxcontrib-napoleon

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://pypi.org/project/sphinxcontrib-napoleon/

### CODE REVIEW

**Comment by ocefpaf** [comment]
This fails b/c https://github.com/conda-forge/pockets-feedstock never got built. Somehow new feedstocks today are not building automatically!

Ping @mariusvniekerk who detected that earlier today.

**Comment by ocefpaf** [comment]
@conda-forge/staged-recipes this is ready for review!

**Comment by xhochy** [comment]
> This fails b/c https://github.com/conda-forge/pockets-feedstock never got built. Somehow new feedstocks today are not building automatically!
> 
> Ping @mariusvniekerk who detected that earlier today.

See https://github.com/conda-forge/conda-forge.github.io/issues/828, no solution/idea yet.

**Comment by ocefpaf** [comment]
> See conda-forge/conda-forge.github.io#828, no solution/idea yet.

That is what I'm doing :wink:

**Comment by jakirkham** [comment]
This seems reasonable to add. Though it is worth noting the following (taken from the PyPI page)...

> As of Sphinx 1.3, the napoleon extension will come packaged with Sphinx under `sphinx.ext.napoleon`. The `sphinxcontrib.napoleon` extension will continue to work with Sphinx <= 1.2.

So this is primarily relevant for legacy cases.

**Pull request merged**
