### PR TITLE
Adding "prrng" and "python-prrng"

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Note: "prrng" is header only library

### CODE REVIEW

**Comment by tdegeus** [comment]
Ready for review @conda-forge/help-c-cpp @conda-forge/help-python-c

Note that "prrng" is a (single header) header-only library.

**Comment by wolfv** [comment]
@tdegeus awesome package! :) are those two packages usually released at the same time / from the same source?
Maybe it would make sense to use two outputs (instead of two feedstocks). Makes things easier.

**Comment by tdegeus** [comment]
@wolfv Sound good. But: (1) How would that work? (2) Even though I'm planning this to never happen, could it occur that a Python build error could become a blocker for the c++ library?

**Comment by wolfv** [comment]
Hey, 

yeah, this could be a decent example: https://github.com/conda-forge/xz-feedstock/blob/master/recipe/meta.yaml
Or maybe this one: https://github.com/conda-forge/openimageio-feedstock/blob/master/recipe/meta.yaml

Yeah, if the python package wouldn't build properly that would mean that the recipe failed and nothing would get uploaded. Up to you to decide if it's worth it :)

**Comment by tdegeus** [comment]
@wolfv I find the idea of having just one feedstock very attractive. However, even though I did things right, the build is not receiving the proper dependencies... Maybe you could have a quick look?

**Comment by tdegeus** [comment]
(Tomorrow of course ;))

**Comment by wolfv** [comment]
yeah, i think you might be hitting some magic conda-build behavior with mutlipel otuputs:

there is a top-level build. That top-level build uses magically `build.sh` and `bld.bat` scripts, if it finds them. You need to rename them to something else...

**Comment by tdegeus** [comment]
That should do it, thanks @wolfv . So two questions: 

1. What confuses me is that with my earlier Python build script I could put `script: python -m pip install . -vv` under `build:`. But when I put the same output of `build:` conda-build thinks that it is a filename. So I had to work-around this by making actual files. Is there a better way?
2. Is there a way that I could merge existing feedstocks (e.g. https://github.com/conda-forge/python-goosefem-feedstock and https://github.com/conda-forge/goosefem-feedstock ), because this will be easier to maintain

**Comment by wolfv** [comment]
yeah, there are some really strange behaviours with multiple outputs. I am trying really hard to fix that in boa :) 
We could also try to fix that in conda-build...

The original idea was to have a top-level build and then split the results into multiple packages. I think that's why there are some surprising behaviours.

As for merging... with the next release you could move to the same repo structure as here for the goosefem feedstock, and then archive (or ask for archiving) of your python-goosefem feedstock. Once archived, the bot won't come anymore.

**Comment by tdegeus** [comment]
Thanks @wolfv . Would be great if things are fixed upstream! And will do for python-goosefem (but indeed I don't think I can archive myself)

**Pull request merged**
