### PR TITLE
Adding solvation_analysis v0.1.5 to conda-forge

### PR DESCRIPTION
**Pull request by orionarcher**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by orionarcher** [comment]
Hi @conda-forge/help-python, I believe this is ready for review!

**Comment by orionarcher** [comment]
@hmacdope could you confirm your willingness to be a co-maintainer?

**Comment by hmacdope** [comment]
> @hmacdope could you confirm your willingness to be a co-maintainer?

Yes I am 😀 cheers.

**Comment by orionarcher** [comment]
@conda-forge-admin, please ping team

**Comment by orionarcher** [comment]
@hmacdope, just released a new version of SA but not sure how to update on conda-forge. Do you have any resources on how to update the feedstock?

**Comment by hmacdope** [comment]
It should be enough to change the Pypi version and PyPi SHA to the new version and reset the build number to 0 in a PR. (All in meta.yaml) Note you have to PR from a fork and then use some comment tag to get a re-render. IIRC the instructions are on the feedstock README but I can check. Ping me if having any issues. :)

**Comment by hmacdope** [comment]
@orionarcher To be clear You don't need to PR against staged recipes again only against the feedstock so you can close this

**Pull request merged**
