### PR TITLE
conda-gitenv fix

### PR DESCRIPTION
**Pull request by bjlittle**
@jakirkham Fix for https://github.com/conda-forge/staged-recipes/pull/1926 the `conda-gitenv` recipe

### CODE REVIEW

**Comment by bjlittle** [comment]
@jakirkham Ping ...

**Comment by bjlittle** [comment]
@ocefpaf Thanks!

The https://github.com/conda-forge/conda-gitenv-feedstock is still empty though ...

**Comment by ocefpaf** [comment]
>
> @ocefpaf <https://github.com/ocefpaf> Thanks!
>
No problem!

> The https://github.com/conda-forge/conda-gitenv-feedstock is still empty
> though ...
>

It may take while.

**Comment by jakirkham** [comment]
Thanks @bjlittle .

Also, not that you would have any way of knowing, but the time this got added would be like 4AM for me hence my unresponsiveness.

**Pull request merged**
