### PR TITLE
Add vmprof recipe

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes It looks like I need `libunwind` for the linux build. Upstream, they get it on travis like this:

https://github.com/vmprof/vmprof-python/blob/master/travis/build-libunwind.sh

Do I need to have a separate recipe for `libunwind` or is there a trick to get it just for this recipe? I'm not sure if `yum_requirements.txt` is a viable/appropriate way to deal with this. Or would it be better to just generate the recipe from the wheels that are provided that pre-bundle it?

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes -- I would appreciate feedback on this PR. Thanks!

**Comment by isuruf** [comment]
You should have a separate `libunwind` conda package which is the recommended way. Not recommended way is to build `libunwind` as a static library and install it into someplace other than `${PREFIX}` and then use that.

**Comment by synapticarbors** [comment]
Attempting to build `libunwind` for linux in https://github.com/conda-forge/staged-recipes/pull/4200

**Comment by synapticarbors** [comment]
Linux build is now passing since I've included `libunwind`. I'm not sure why appveyor is no longer being triggered.

**Comment by synapticarbors** [comment]
Also, is it concerning that the test suite wouldn't run unless I added `toolchain` as a `tests` requirement for linux? Otherwise, it wasn't finding `libunwind.h` or `zlib.h`.

**Comment by scopatz** [comment]
> Also, is it concerning that the test suite wouldn't run unless I added toolchain as a tests requirement for linux?

Yes, that seems to indicate that something isn't getting installed correctly or that the tests are trying to build something (which is less of an issue)

**Comment by synapticarbors** [comment]
The tests use cffi to compile a bunch of stuff that is just part of the tests

**Comment by scopatz** [comment]
hmm interesting, that is probably Ok then.  Have you tested the package out locally? Do you need toolchain installed to run vmprof?

**Comment by synapticarbors** [comment]
I haven't run it locally, but given that `cffi` is only a test requirement according to the `setup.py` and the special `test_requirements.txt`, I don't think that the compiler is regularly needed.

**Comment by scopatz** [comment]
Arighty

**Comment by synapticarbors** [comment]
@scopatz -- looks like this is finally ready to merge.

**Pull request merged**
