### PR TITLE
DEV: first try on prettytable

### PR DESCRIPTION
**Pull request by licode**
Prettytable installation at scipy2016. 
https://github.com/conda-forge/staged-recipes/issues/641

### CODE REVIEW

**Comment by jakirkham** [comment]
Sorry you already put in this effort. We already have `prettytable`. Would you like to be added as a maintainer?

**Comment by ocefpaf** [comment]
> Sorry you already put in this effort. We already have prettytable. Would you like to be added as a maintainer?

This is a sprinter here at SciPy learning how add a recipe @jakirkham. There is nothing to review here.

**Comment by jakirkham** [comment]
Thanks for clarifying, @ocefpaf.

**Comment by licode** [comment]
Please add me as a maintaniner at prettytable. thanks!

**Comment by licode** [comment]
I will send a PR to prettytable-feedstock.

**Pull request closed without merging**
