### PR TITLE
Migrate r-spocc from bioconda

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dpryan79** [comment]
Apparently I need to migrate r-vertnet too and bump r-rgbif

**Comment by dpryan79** [comment]
r-rgbif already had a feedstock but never got built. I've triggered that.

**Comment by dpryan79** [comment]
Waiting on https://github.com/conda-forge/staged-recipes/pull/9952

**Comment by dbast** [comment]
MIT is a combined license (real license text + a file with just names) ... so the entry looks a bit different... I'll just update the PR, which then also retriggers :)

**Comment by dpryan79** [comment]
Thanks!

**Comment by dbast** [comment]
By the way: updating to conda-build 3.18.10 does that license stuff automatically :)

**Comment by dpryan79** [comment]
It's unclear to me where the version conflicts are coming from. All of the packages have build for R 3.5.1 and 3.6.1.

**Comment by mbargull** [comment]
The conflict message from `conda 4.7.10` is not helpful. `conda 4.7.12` seems to do a slightly better job:
```sh
> conda create -c conda-forge -qdnx 'r-base=3.5.1' 'r-crul >=0.3.4' 'r-data.table >=1.9.6' 'r-jsonlite >=1.4' 'r-lubridate >=1.5.0' 'r-rbison >=0.6.0' 'r-rebird >=1.0.0' 'r-rgbif >=1.0.0' 'r-ridigbio >=0.3.5' 'r-rvertnet >=0.7.0' 'r-tibble >=1.2' 'r-whisker >=0.4' 'r-wicket >=0.3.0'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                  
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                                                                                                                                                   



Package r-base conflicts for:
r-lubridate[version='>=1.5.0'] -> r-base[version='3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-data.table[version='>=1.9.6'] -> r-base[version='3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-whisker[version='>=0.4'] -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
r-rebird[version='>=1.0.0'] -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
r-rvertnet[version='>=0.7.0'] -> r-crul[version='>=0.5.2'] -> r-base[version='>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0']
r-rvertnet[version='>=0.7.0'] -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
r-tibble[version='>=1.2'] -> r-base[version='3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-wicket[version='>=0.3.0'] -> r-rcpp -> r-base[version='>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0']
r-rebird[version='>=1.0.0'] -> r-assertthat -> r-base[version='>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0']
r-rbison[version='>=0.6.0'] -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
r-ridigbio[version='>=0.3.5'] -> r-httr -> r-openssl[version='>=0.8'] -> r-askpass -> r-base[version='>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0']
r-jsonlite[version='>=1.4'] -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-wicket[version='>=0.3.0'] -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
r-crul[version='>=0.3.4'] -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.5,<3.6.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
r-crul[version='>=0.3.4'] -> r-curl[version='>=3.1'] -> r-base[version='>=3.5.0,<3.5.1.0a0']
r-rgbif[version='>=1.0.0'] -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
r-ridigbio[version='>=0.3.5'] -> r-base[version='>=3.6,<3.7.0a0']
r-base=3.5.1
r-rbison[version='>=0.6.0'] -> r-crul[version='>=0.7.4'] -> r-base[version='>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0']
r-lubridate[version='>=1.5.0'] -> r-stringr -> r-stringi[version='>=1.1.7'] -> r-base[version='>=3.4.2,<3.4.3.0a0']
r-rgbif[version='>=1.0.0'] -> r-crul[version='>=0.7.4'] -> r-base[version='>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0']
```
=> `r-ridigbio[version='>=0.3.5'] -> r-base[version='>=3.6,<3.7.0a0']`
Looks like `r-ridigbio` is only in `defaults`/`r` for R 3.6 but not in conda-forge.

**Comment by dpryan79** [comment]
Ah, that explains it! I'll see if I can migrate that from bioconda too.

**Comment by dpryan79** [comment]
@conda-forge/help-r This is ready for review

**Pull request merged**
