### PR TITLE
Add py-channelmodel recipe

### PR DESCRIPTION
**Pull request by jdemel**
This commit should add a fully functional conda recipe. Afterwards py-channelmodel should be available on conda-forge.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdemel** [comment]
@conda-forge/help-python Hi! It looks like something is broken in the windows version of the package.

I wonder why and how `channelmodel.exe` ended up in this build. If you could point me into the right direction here, that'd be great.
```
INFO:conda_build.build:Packaging py-channelmodel
Packaging py-channelmodel
INFO:conda_build.build:Packaging py-channelmodel-0.9.3-pyhd8ed1ab_0
Packaging py-channelmodel-0.9.3-pyhd8ed1ab_0
number of files: 19
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
   INFO: sysroot: 'C:/Windows/' files: '['winhlp32.exe', 'win.ini', 'twain_32/wiatwain.ds', 'twain_32.dll']'
   INFO (py-channelmodel,Scripts/channelmodel.exe): Needed DSO C:/Windows/System32/KERNEL32.dll found in $SYSROOT
   INFO (py-channelmodel,Scripts/channelmodel.exe): Needed DSO C:/Windows/System32/SHLWAPI.dll found in $SYSROOT
   INFO (py-channelmodel): Interpreted package 'py-channelmodel' is interpreted by 'python'
[noarch_python] Noarch package contains binary script: channelmodel.exe
##[error]Cmd.exe exited with code '1'.
```

**Comment by ryanvolz** [comment]
I'm guessing you need
```
build:
  entry_points:
    - channelmodel = channelmodel.__main__:main
```
to tell conda to generate the entry point properly for a `noarch: python` package. On Windows, a binary gets created that calls out to Python so that entry points can be run as a command, and since that's platform-specific conda needs to know about it for noarch to work.

Also, hi! I was just checking on a PR of my own and happened to spot your GitHub handle. Good to see others in the radio space contributing to conda-forge!

**Comment by jdemel** [comment]
@ryanvolz hi! Also, thanks for the hint! And I assume @BastianZim you approve this too. I hope it goes through now.

**Comment by jdemel** [comment]
@conda-forge/help-python I hope I could fix everything now. If this is a simple "merge" now, I'd be happy.

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
