### PR TITLE
Add r-tesseract

### PR DESCRIPTION
**Pull request by apcamargo**
Recipe made with `conda_r_skeleton_helper`.

### CODE REVIEW

**Comment by apcamargo** [comment]
Depends on https://github.com/conda-forge/staged-recipes/pull/7475

**Comment by apcamargo** [comment]
@conda-forge/r Can someone take a look at this recipe?

**Comment by dpryan79** [comment]
You might want to add yourself under `conda-forge/r` as a maintainer, otherwise :+1: from me!

**Comment by apcamargo** [comment]
Thanks @dpryan79 ! Waiting for the merge.

**Comment by dbast** [comment]
@apcamargo thanks!

**Pull request merged**
