### PR TITLE
WIP: Package polymake for conda-forge

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@apaffenholz: Feel free to weigh in here :)

**Comment by saraedum** [comment]
```
checking C++ compiler ... C++ compiler g++ says its version is 4.8.2, while the minimal required version is 5.1
```
@isuruf Is there anything I can do about this? (Assuming that we absolutely need gcc5 @apaffenholz?) Should I wait for conda-build upgrades?

**Comment by saraedum** [comment]
conda-forge now has more recent compilers. Let's see what happens.

**Comment by saraedum** [comment]
This requires some perl modules that have not been packaged for conda-forge yet: 
```
WARNING: Please install/check the following perl modules prior to starting polymake: 
         XML::Writer, XML::LibXML, XML::LibXSLT, Term::ReadKey, Term::ReadLine::Gnu
```

**Comment by isuruf** [comment]
You can use `conda skeleton cpan` to generate conda recipes for these.

**Comment by saraedum** [comment]
Thanks for the pointer. I personally don't use polymake so I'll leave this alone for the moment. If somebody wants to continue here, please do so :)

**Pull request closed without merging**
