### PR TITLE
add recipe for scipy-stubs

### PR DESCRIPTION
**Pull request by lucascolley**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by lucascolley** [comment]
@jorenham if you could comment here as well :) (we'll have to wait for the optype PR to get merged first before this will work)

**Comment by jorenham** [comment]
all good!

**Comment by jorenham** [comment]
@lucascolley `optype` is available `conda-forge` now (🎉):
https://anaconda.org/conda-forge/optype

**Comment by lucascolley** [comment]
@jorenham we aren't supposed to be able to `import scipy_stubs`, right? If not, is there an equivalent basic test that the build has succeeded?

**Comment by jorenham** [comment]
> @jorenham we aren't supposed to be able to `import scipy_stubs`, right? If not, is there an equivalent basic test that the build has succeeded?

There's nothing to import actually; it's all static stubs 🤔

**Comment by lucascolley** [comment]
I suppose we could do `poe typetest` instead?

**Comment by jorenham** [comment]
> I suppose we could do `poe typetest` instead?

There's a chance that might only work if `scipy` is also installed, which is currently an optional dependency 🤔... 
But I guess you could give it a shot?

**Comment by jorenham** [comment]
> I suppose we could do `poe typetest` instead?

But if `scipy` is available at that point, then you could also go for a more thorough `poe stubtest`, or even `poe tox`.

**Comment by lucascolley** [comment]
@conda-forge/help-python ready for review, thanks!

**Comment by lucascolley** [comment]
thanks!

**Pull request merged**
