### PR TITLE
Raise recipe render errors in CI.

### PR DESCRIPTION
**Pull request by asford**
_Fixes #9424_

#9318 and #9319 both resulted in build failures post-merge due to missing license files, an error that wasn't caught in review or CI. Follow-up from a conda-forge maintainer in #9318 caught that the CI build for these recipes hadn't run, despite showing tests as passing, because the staged recipes were invalid and failed rendering.

This change updates `.ci_support/compute_build_graph.py` to raise, rather than log and ignore, errors during recipe rendering. This behavior is individually verified in commit a8aaebcbd254533817d7e894efc854fe05c10569, which includes an example recipe that fails rendering. The original error is verified in 5e528f83b7b493cf08eb8b8e7c0f27ba0bb9d2dd, which includes an example recipe with a missing `license_file`.

The final merge only includes the change to `.ci_support/compute_build_graph.py` and minor update to `.circleci/build_steps.sh` to log all staged recipes before pruning merged recipes.

### CODE REVIEW

**Comment by asford** [comment]
@conda-forge/staged-recipes This change updates the CI configuration to raise test failures, rather than silently ignoring, when a staged recipe causes render errors. The update is small, but likely needs a thorough review.

**Comment by isuruf** [comment]
Thanks

**Comment by beckermr** [comment]
I'm confused as to what happens on master if a bad recipe is merged. Does this effect just PRs or the master branch too?

**Comment by isuruf** [comment]
This affects only PRs.

**Comment by asford** [comment]
Just to slightly expand, build_steps.sh prunes the recipes directory, removing any recipes already present in master, so only new recipes in the PR are checked.

**Pull request merged**
