### PR TITLE
Create recipe for R nlmixr

### PR DESCRIPTION
**Pull request by PertuyF**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Created using bgruening/conda_r_skeleton_helper, builds locally.
Relies on #10295 #10296 #10297 #10298 #10299 for dependencies

### CODE REVIEW

**Comment by PertuyF** [comment]
Windows builds fail on:

```
Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined
```

Same as PR #10302 

@conda-forge/help-r @conda-forge/core this seems to be similar to `r-stan`, which ended skipping win builds. Should we do the same here?

**Comment by npavlovikj** [comment]
Not sure if this helps, but looks like `r-rstan` has configuration instructions for Windows, https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-Windows#configuration, which I think can be applied here. If you have a Windows instance you can try add those variables to the `Makevars`.

**Comment by PertuyF** [comment]
@npavlovikj Thanks :) I saw these instructions (and variants) but they are for g++, while windows builds are using vs2008 or vs2015. Don't know what to do here, and as I can't test locally I don't want to waste too much Azure/appveyor time just to explore.

**Comment by npavlovikj** [comment]
@PertuyF , since this is occurring in other feedstocks as well, I think you can skip the Windows build, and if a solution is found for `r-rstan` you can apply the same to the feedstock later.

**Comment by PertuyF** [comment]
Thanks @npavlovikj looks like we're good to go with windows skipped!

**Pull request merged**
