### PR TITLE
Add packaging recipe

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
I believe this package will be needed for setuptools 34.x.x as the vendored version was removed.

**Comment by ocefpaf** [comment]
You are correct, but that already exist as a feedstock: https://github.com/conda-forge/packaging-feedstock

**Comment by jjhelmus** [comment]
Oops, you are correct, I did not search hard enough.

**Comment by jakirkham** [comment]
Feel free to add yourself as a maintainer.

**Pull request closed without merging**
