### PR TITLE
Add mffpy

### PR DESCRIPTION
**Pull request by hoechenberger**
**Upstream PR to include license file in sdist: https://github.com/BEL-Public/mffpy/pull/64**

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble be please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Had to add a patch for `setup.py`. This can be removed once https://github.com/BEL-Public/mffpy/pull/65 has been merged.

**Comment by hoechenberger** [comment]
@conda-forge/staged-recipes This PR is ready for review. Thank you!

**Comment by synapticarbors** [comment]
@hoechenberger -- thanks for putting in the upstream PRs as well.

**Comment by hoechenberger** [comment]
Thanks for merging, @synapticarbors!

**Pull request merged**
