### PR TITLE
[skip ci] [ci skip] Update all hooks

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, shall I run this in a different branch?

**Comment by jakirkham** [comment]
Yeah let's put it in another branch. We probably should get `conda-smithy` released again so we can get all the webhooks we want dealt with.

**Comment by isuruf** [comment]
This was pushed into a new branch "hooks" and was run successfully.

**Comment by jakirkham** [comment]
Thanks for doing this, @isuruf.

**Comment by jakirkham** [comment]
How do we run it? Just restart Travis CI?

**Comment by isuruf** [comment]
Yes, restart the `hooks` branch

**Comment by jakirkham** [comment]
Seems to be failing on feedstocks with a 422 error. Looks a bit odd.

```python
Traceback (most recent call last):
  File "../.CI/update_all_hooks.py", line 47, in <module>
    add_conda_forge_webservice_hooks(owner, repo)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 392, in add_conda_forge_webservice_hooks
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/conda-forge/obvious-ci-feedstock/hooks
```

ref: https://travis-ci.org/conda-forge/staged-recipes/jobs/276589979

**Comment by isuruf** [comment]
See https://github.com/conda-forge/conda-smithy/pull/581

**Comment by jakirkham** [comment]
Thanks for narrowing that down. Sorry for missing it on the review. Double checked all the other event names for good measure and they all checked out FWICT.

**Pull request closed without merging**
