### PR TITLE
Add react

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by dougalsutherland** [comment]
So...there's no build step here, and if you look at e.g. the CircleCI log it says `number of files: 0`. You're just making an empty tarfile.

As a JavaScript library, what are you hoping to get out of this package? Do you just want to repackage the source? (Why?)

**Comment by sannykr** [comment]
@dougalsutherland : Yes, I just want to repackage it. Since this package is not installed, "conda install -c conda-forge react" will not work. But if I repackage it, I should be able to download the tar file from anaconda.org

**Comment by sannykr** [comment]
@dougalsutherland : I can see jquery_static on anaconda.org. Do I need to add _static to the package name if I am simply repackaging it (package is not installable)?

**Comment by dougalsutherland** [comment]
The package name won't magically change anything; you'll need to add some kind of `build` step that copies things over into e.g. `$PREFIX/static`, which is where the `jquery_static` package has things. It should probably also be `noarch: generic`. Here's the `build.sh` from `jquery_static`:

```
#!/bin/bash

npm run build
[[ -d "${PREFIX}"/static ]] && rm -rf "${PREFIX}"/static
mkdir -p "${PREFIX}"/static/${PKG_NAME%_static}/${PKG_VERSION}
cp -rf dist/* "${PREFIX}"/static/${PKG_NAME%_static}/${PKG_VERSION}/
```

I'm not totally sure how I feel about conda-forge packaging lots of static javascript libraries, though....

**Comment by jakirkham** [comment]
@minrk @rgbkrk, any recommendations on how to package JavaScript libraries like this with `conda`?

**Comment by rgbkrk** [comment]
I still find packaging javascript libraries in conda really weird, because node packages can all use their own independent version of a package. I'm unsure how the non-js packages end up using these either, as the jupyter packages all use either npm (nteract, jupyterlab) or bower (jupyter/notebook).

Can someone provide an example of how they intend to use this?

**Comment by rgbkrk** [comment]
> Looking toward the future, as data scientists need to build frontends, they will need to manage js dependencies.

Yeah, I get that. I'm wondering exactly _how_ they'll be able to use these. I can't wrap my head around what they'll use. Are these only the dist files that would get included in a `<script>` tag?

**Comment by cshaley** [comment]
In most cases, yes.  Conda-forge would just be used to manage package dependencies and to make js packages accessible (i.e. available locally) via a conda install command.

**Comment by minrk** [comment]
Following the jsdom discussion in #3049, I've no objection to including js libraries on conda-forge, and there is now at least one precedent of a js *library* being installed via conda-forge. It does seem odd to me, and I would never personally use conda to install a js library. To me, packaging something with conda-forge is the same as installing that same thing with `npm install -g`. Makes perfect sense for *applications*, but is quite unconventional for *libraries* that don't define entrypoints.

In general, the way npm packages should be built with conda is by calling `npm install -g`:

```yaml
build:
  script: npm install -g .
```

**Comment by sannykr** [comment]
@minrk : You have pushed nodejs, and looks like we can install it using "conda install -c conda-forge nodejs".  I have also successfully pushed many js packages on conda-forge, but "conda install -c conda-forge packagename" doesn't work. 
Could you please suggest something. I am trying to make sure I can install it using conda install on command line.

**Comment by minrk** [comment]
@sannykr I'm not sure I understand your question. What specific packages are you trying to install that don't work?

**Comment by sannykr** [comment]
@minrk : I tried to install phosphor using "conda install -c conda-forge phosphor", and I was not able to test the installation using npm list -g. 
But when I used "conda list", then I found that it is installed at /Users/sannykumar/miniconda/pkgs/phosphor-0.7.1-0/lib/node_modules/

I believe that there is a directory .node-module where javascript packages are installed using npm, but I am not able to find the installation in that directory if I install js packages using conda.

**Comment by dougalsutherland** [comment]
See also https://github.com/conda-forge/phosphor-feedstock/issues/1. (It works for me.)

**Pull request closed without merging**
