### PR TITLE
[WIP] add dgl

### PR DESCRIPTION
**Pull request by hadim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hadim** [comment]
This is a first attempt to build dgl on conda-forge. See https://github.com/dmlc/dgl/issues/1855 for context.

Some packages are required before this build can work.

Only building for cpu at the moment (will take care of cuda after).

**Comment by hadim** [comment]
- [ ] the metis version in conda forge is too old a new git tag on upstream `master` should be used to build a new version: https://github.com/conda-forge/metis-feedstock/pull/30
- [ ] gklib is also required for both metis and dgl. See https://github.com/conda-forge/staged-recipes/pull/12547

**Comment by dgasmith** [comment]
This would be fantastic to have in! Can we do anything to help move this along?

**Comment by hadim** [comment]
It's not that easy and probably requires some effort. I don't have a plan to work on this for the moment so feel free to take over.

**Pull request closed without merging**
