### PR TITLE
add deepsearch-glm

### PR DESCRIPTION
**Pull request by hadim**
Continuation of https://github.com/conda-forge/staged-recipes/pull/28093

---

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hadim** [comment]
@h-vetinari I am trying to make `pip check` to work by matching the numpy constraints from upstream (https://github.com/DS4SD/deepsearch-glm/blob/v0.26.1/pyproject.toml#L30-L33).

What is the numpy strategy on c-f since `2.x`? Should I respect the upstream constraints or let it free?

**Comment by hadim** [comment]
It looks like c-f pinning is incompatible:

```yaml
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.22 #3.9
  - 1.22 #3.10
  - 1.23 #3.11
  - 1.26 #3.12
 ```

Is that ok to set `pip check` to false here?

**Comment by h-vetinari** [comment]
> What is the numpy strategy on c-f since `2.x`? Should I respect the upstream constraints or let it free?

We've been migrating for numpy 2.0 for a long time already, but it's not [finished](https://conda-forge.org/status/migration/?name=numpy2) yet, which means you don't get it in staged-recipes. In this case, the upstream constraints are almost certainly wrong resp. too tight, and I would recommend patching them out. Alternatively, you could also use
```yaml
numpy:
  - 2.0
```
in `recipe/conda_build_config.yaml` if you want, to mimick what the numpy 2.0 migrator does (which you can then delete once the migrator comes around).

**Comment by hadim** [comment]
I checked the code and there is nothing specific to numpy so it's safe to let it free. So I simply patched the upstream `pyproject.toml` so `pip check` works.

Let me know what you think @h-vetinari

**Comment by hadim** [comment]
> The error seems like a bug but I am not sure:
> 
> ```
>  │ ╭─ Running package tests
>  │ │ Creating test environment in '/home/conda/staged-recipes/build_artifacts/bld/rattler-build_deepsearch-glm_1732023718/work/test'
>  │ │ Collecting tests from '/home/conda/.cache/rattler/cache/pkgs/deepsearch-glm-0.26.1-py310h65a96e7_0'
>  │ │
>  │ │ ╭─ Running python test(s)
>  │ │ │
>  │ │ │ ╭─ Testing with python 3.9
>  │ │ │ │ 
>  │ │ │ │ Resolving test environment:
>  │ │ │ │   Platform: linux-64 [__unix=0=0, __linux=6.5.0=0, __glibc=2.17=0, __archspec=1=x86_64_v4]
>  │ │ │ │   Channels: 
>  │ │ │ │    - file:///tmp/.tmpMxLukD/
>  │ │ │ │    - file:///home/conda/staged-recipes/build_artifacts/
>  │ │ │ │    - file:///home/conda/staged-recipes/build_artifacts/
>  │ │ │ │    - conda-forge
>  │ │ │ │   Specs:
>  │ │ │ │    - python 3.9.*
>  │ │ │ │    - deepsearch-glm ==0.26.1 py310h65a96e7_0
>  │ │ │ │    - pip
>  │ │ │ │
>  │ │ │ ╰─────────────────── (took 1 second)
>  │ │ │
>  │ │ ╰─────────────────── (took 1 second)
>  │ │
>  │ ╰─────────────────── (took 2 seconds)
>  │
>  ╰─────────────────── (took 7 minutes)
> Error:   × failed to setup test environment: Cannot solve the request because of:
>   │ deepsearch-glm ==0.26.1 py310h65a96e7_0 cannot be installed because there
>   │ are no viable options:
>   │ └─ deepsearch-glm 0.26.1 would require
>   │    └─ python 3.10.* *_cpython, for which no candidates were found.
>   │ The following packages are incompatible
>   │ └─ deepsearch-glm ==0.26.1 py310h65a96e7_0 cannot be installed because
>   │ there are no viable options:
>   │    └─ deepsearch-glm 0.26.1 | 0.26.1 is excluded because due to strict
>   │ channel priority not using this option from: 'file:///home/conda/staged-
>   │ recipes/build_artifacts/'
>   │ 
>   ╰─▶ Cannot solve the request because of: deepsearch-glm ==0.26.1
>       py310h65a96e7_0 cannot be installed because there are no viable options:
>       └─ deepsearch-glm 0.26.1 would require
>          └─ python 3.10.* *_cpython, for which no candidates were found.
>       The following packages are incompatible
>       └─ deepsearch-glm ==0.26.1 py310h65a96e7_0 cannot be installed because
>       there are no viable options:
>          └─ deepsearch-glm 0.26.1 | 0.26.1 is excluded because due to strict
>       channel priority not using this option from: 'file:///home/conda/staged-
>       recipes/build_artifacts/'
> ```
> 
> It happens only here when building in the same CI for multiple python versions.
> 
> Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1084742&view=logs&j=4cabe686-70ae-553a-7fd0-310379f2cbac&t=6a4fc7c9-c31a-5115-eff9-6479d72b69ff

My bad here, the recipe is not `noarch`.

**Comment by hadim** [comment]
LGTM @h-vetinari

**Review by h-vetinari — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
