### PR TITLE
Add requests-magpie

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by Zeitsperre** [comment]
I think that PyPI needs to update its package mirrors. I imagine the package will be up by tomorrow.

**Comment by Zeitsperre** [comment]
@davidcaron in order to check the final requirement box, are you alright witrh being listed as a maintainer.

**Comment by davidcaron** [comment]
Yes, sign me in!

**Comment by davidcaron** [comment]
> 
> 
> I guess the package name is requests-mapgie rather than requests-magpie

Hi, thank you fro pointing this out, it was a typo in the package name in `setup.py`. The proper name is `requests-magpie`.

**Comment by Zeitsperre** [comment]
@jan-janssen This PR is finally good to be merged! Thanks for your help!

**Pull request merged**
