### PR TITLE
A few generic CRAN packages

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by npavlovikj** [comment]
https://github.com/conda-forge/staged-recipes/pull/7564 is a dependency for `r-extremevalues`. Any help with `r-gwidgetstctlk` is welcome!

**Comment by dpryan79** [comment]
Apparently the cache hasn't been updates since `r-gwidgetstcltk` was added, odds are this will work later today then.

**Comment by dbast** [comment]
Seems to be not a cache issue... linux build of https://github.com/conda-forge/r-gwidgetstcltk-feedstock failed -> retriggered, still does not build.

**Comment by dpryan79** [comment]
Figures, thanks for the heads up.

**Comment by npavlovikj** [comment]
`r-gwidgetstcltk` is in the conda-forge channel finally as `noarch` package. @dpryan79 , can you please restart this build and try again?

**Comment by npavlovikj** [comment]
Ah, I have seen the `r-rjava` issue before, and setting `openjdk` to 8 worked for me, https://github.com/conda-forge/r-rjava-feedstock/issues/6.

**Comment by dpryan79** [comment]
I'll just remove that package, r-rjava is one of the packages that still needs rebuilding.

**Pull request merged**
