### PR TITLE
Add regions package to conda-forge

### PR DESCRIPTION
**Pull request by mwcraig**
The license file is not included in the repo at the moment, have opened an issue upstream for that. @bsipocz agreed in a separate PR to be maintainer on any recipe I open.

This needs to be merged before #3420 for that PR to pass.

### CODE REVIEW

**Comment by cdeil** [comment]
👍 , thanks!

---
What's up with this fail?
> appveyor was unable to build non-mergeable pull request

**Comment by bsipocz** [comment]
@cdeil - that must be a transient for this PR, appveyor forums suggest that a close-reopen cycle resolves it.

**Comment by mwcraig** [comment]
Close/open to trigger CI.

**Comment by synapticarbors** [comment]
Could you just remember to add the `license_file` in the feedstock on the next release? Once the feedstock is created, add it as an issue as a reminder.

**Comment by mwcraig** [comment]
Ping @mwcraig to make sure he doesn't forget to do this 😁

**Pull request merged**
