### PR TITLE
Add libsodium

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a recipe to build libsodium on all platforms. Borrows the recipe from conda-recipes. Makes some tweaks for better integration in conda-forge.

### CODE REVIEW

**Comment by msarahan** [comment]
Just a small note here: I last messed with this recipe for building it from source on Windows for Jupyter.  I found it better to just use Jupyter's scripts to build it.  If you have it working, good on you - I seem to remember giving up, since the other way worked better.

**Comment by jakirkham** [comment]
Thanks for the feedback, @msarahan. I borrowed this strategy from [their CI code]( https://github.com/jedisct1/libsodium/blob/master/appveyor.yml#L20 ). Though I haven't tested it on a Windows machine, but will try tomorrow.

BTW, where are the Jupyter recipes/scripts that you are referring to? I am planning on trying to port as much of Jupyter over as I can. So, if I don't have to write something from scratch, that would be nice. :smile:

**Comment by msarahan** [comment]
Here you go: http://lists.zeromq.org/pipermail/zeromq-dev/2014-October/027498.html

It's pyzmq, not jupyter, sorry.

We build it with:

   "%PYTHON%" setup.py configure --zmq=bundled

**Comment by jakirkham** [comment]
Looks like that kind of worked for AppVeyor. I think I need to add selectors for the different versions of MSVC.

**Comment by jakirkham** [comment]
Seems like there would be a way to get this going on Windows as they seem to do [this]( https://github.com/jedisct1/libsodium/blob/master/builds/msvc/build/buildall.bat ).

**Comment by jakirkham** [comment]
Dropping Windows support for now. It can be re-attempted later.

**Comment by jakirkham** [comment]
As CI is passing and this has been backlogged for ages just going to merge. Feedback is of course welcome in the feedstock.

**Comment by jakirkham** [comment]
@minrk, would you be interested in being added as a maintainer on the [libsodium feedstock]( https://github.com/conda-forge/libsodium-feedstock )? Also, do you have any thoughts on the recipe as is? Largely the same as it was in conda-recipes. However, I had to temporarily disable Windows. If you have any thoughts on getting Windows to work, I would be really curious to hear.

**Comment by minrk** [comment]
Sure, feel free to add me. I'm afraid that I don't have much experience getting this to work on Windows, and typically resort to bundling libzmq + tweetnacl on Windows, rather than expressing proper dependencies.

**Comment by jakirkham** [comment]
Thanks @minrk. This PR ( https://github.com/conda-forge/libsodium-feedstock/pull/2 ) will add you as a maintainer to the `libsodium` feedstock. As this is your first one, you will receive an invitation to join conda-forge. In particular, this will add you to the `libsodium` team. Once accepted, you will be given commit privileges on the libsodium [feedstock/repo]( https://github.com/conda-forge/libsodium-feedstock ).

**Comment by jakirkham** [comment]
If you find that tweetnacl is easier to package and have some build scripts lying around, we certainly can give that a go for now. It will be simple to just use tweetnacl for Windows in the zeromq build script and use libsodium for all UNIX cases. What do you think?

**Comment by minrk** [comment]
The reason tweetnacl is easier is that it's extra sources added to zeromq, rather than a DLL dependnecy. But I do think libsodium on non-windows, and tweetnacl on Windows makes sense. The bit that I don't have a solution for, but should be able to figure out, is linking *pyzmq* against libzmq properly on Windows. I think even the official conda packages rely on pyzmq bundling zeromq on Windows, rather than expressing a proper dependency.

**Comment by jakirkham** [comment]
I see. Well, let's worry about it more once we have a working copy of zeromq. The nice thing about tweetnacl is it is so simple we need only a couple command calls before we have built a working DLL.

**Pull request merged**
