### PR TITLE
Add jq

### PR DESCRIPTION
**Pull request by jakirkham**
Adds jq and its dependencies. Builds on Mac and Linux. Recipes borrowed from conda recipes. Cleaned up a bit.

### CODE REVIEW

**Comment by jakirkham** [comment]
Tests passing. Any feedback for this is welcome.

**Comment by ocefpaf** [comment]
Because `jq` depends on `oniguruma` you might need to re-start `jq`'s feedstock CIs after `oniguruma` is build.

**Comment by jakirkham** [comment]
Thanks. I don't know if I can control Travis' with feedstocks. At least, I don't seem to be able to with the existing feedstocks I have access to.

**Comment by ocefpaf** [comment]
I thought that as a member of the feedstock team you could re-start.  If not, just ping me.

**Comment by jakirkham** [comment]
Went ahead and resynced Travis. Now it is working.

**Comment by jakirkham** [comment]
Yeah, Travis shows the button, but won't respond. Circle CI doesn't even give me the option.

**Comment by jakirkham** [comment]
Though I think I haven't been added to either team yet. IIRC @pelson was saying something about adding team members needing to be triggered manually, at present.

**Comment by ocefpaf** [comment]
Weird... I was able to re-start CircleCI, but not Travis-CI.

**Comment by jakirkham** [comment]
Very weird. Maybe Travis CI is just out to lunch.

Thanks for restarting Circle CI. Appears it is already done. :)

**Comment by jakirkham** [comment]
@stedolan, just letting you know we have added `jq` to conda-forge. This will allow users to easily install this with conda (`conda install -c conda-forge jq`). The maintenance burden here is light as all testing releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this repo]( https://github.com/conda-forge/jq-feedstock ). If you have any interest in being added as a maintainer (to make new releases for instance), I can happily add you to the maintainers list.

**Comment by jakirkham** [comment]
@kkos, just letting you know we have added `oniguruma` to conda-forge. This will allow users to easily install this with conda (`conda install -c conda-forge oniguruma`). The maintenance burden here is light as all testing releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this repo]( https://github.com/conda-forge/oniguruma-feedstock ). If you have any interest in being added as a maintainer (to make new releases for instance), I can happily add you to the maintainers list.

**Comment by jakirkham** [comment]
@nicowilliams, noticed you have been doing more of the development on `jq` of late. Just wanted to point this out to you. See the [above comment]( https://github.com/conda-forge/staged-recipes/pull/129#issuecomment-198042735 ) for more details.

**Comment by kkos** [comment]
@jakirkham, thank you. Please add me as a maintainer.
But I don't know nothing about Travis CI.

**Comment by jakirkham** [comment]
> Please add me as a maintainer.

Excellent! Thanks @kkos. Merging this PR ( https://github.com/conda-forge/oniguruma-feedstock/pull/2 ) will add you as a maintainer. I'll provide more details about how everything works in that PR.

> But I don't know nothing about Travis CI.

Fortunately you don't need to know anything about Travis. All of that stuff is maintained automatically for us. Will show you the parts we care about.

**Comment by nicowilliams** [comment]
@jakirkham Hey, thanks for doing this!

**Comment by jakirkham** [comment]
Absolutely, @nicowilliams! :smile:

If you have any interested in getting access to the [repo]( https://github.com/conda-forge/jq-feedstock ) (e.g. to make updates, modify the build procedure, etc.), please let me know and I will happily add you.

**Pull request merged**
