### PR TITLE
Add cmt

### PR DESCRIPTION
**Pull request by jakirkham**
Apparently my description got wiped out when I moved it on ZenHub boards. So, I'm re-writing based on what I remember. :cry:

We have tried to package [`cmt`]( https://github.com/lucastheis/cmt ). This is a brand new recipe. A number of issues were found with the latest release. These have all been submitted upstream. All patches that made sense have been submitted upstream. There is one workaround patch (compiler change for Mac), which has not been submitted upstream. However, an issue has been opened to discuss changes that would make it unnecessary. Below is a list of either PRs (with issues referenced) or issues (if no PR was submitted). Also, a list of otherwise related issues has been compiled below.

Patches:
* https://github.com/lucastheis/cmt/issues/10
* https://github.com/lucastheis/cmt/pull/18
* https://github.com/lucastheis/cmt/pull/17
* https://github.com/lucastheis/cmt/pull/20
* https://github.com/lucastheis/cmt/pull/19

Related issues:

* https://github.com/lucastheis/cmt/issues/8
* https://github.com/lucastheis/cmt/issues/9
* https://github.com/lucastheis/cmt/issues/11
* https://github.com/lucastheis/cmt/issues/13
* https://github.com/lucastheis/cmt/issues/21

### CODE REVIEW

**Comment by jakirkham** [comment]
It seems some of the tests may be too intense for Circle CI. We may need to skip some of them on that platform.

**Comment by jakirkham** [comment]
Anybody have feedback here? Personally, I am ok with this, but maybe there are things that could be improved.

**Comment by jakirkham** [comment]
@ocefpaf, thoughts?

If nothing too serious, I am thinking I will merge this once CI passes. It takes awhile to build and test so I don't want to cut into the build queue time at staged-recipes.

**Comment by jakirkham** [comment]
Feedback welcome at the feedstock.

**Comment by ocefpaf** [comment]
:+1:

**Comment by jakirkham** [comment]
Sorry, was pretty fast on merging.

Glad to hear you approve though. :smile:

**Comment by jakirkham** [comment]
@lucastheis, we are adding `cmt` to [conda-forge]( https://conda-forge.github.io/ ). This is the community packaging system for use with [`conda`]( http://conda.pydata.org/docs/ ). Packages built here are built with CI and deployed to the [conda-forge channel]( https://anaconda.org/conda-forge/ ) automatically after committing on `master` of a feedstock (a repo with the recipe plus automatically maintained CI scripts). Eventually, packages submitted here will be included in the `defaults` channel after some auditing process as [mentioned]( https://github.com/conda-forge/conda-forge.github.io/issues/22#issuecomment-197117472 ). If there is anything here that you see is off or needs to be fixed, please let me know. If you would like to have access to the [cmt feedstock/recipe]( http://github.com/conda-forge/cmt-feedstock/ ), I would happily add you to the maintainers list so you can have commit privileges for this recipe. This would be useful for updating the version for instance. Thanks again for working on such a useful library.

As a side note, there were a few testing issues I ran into, which I have filed issues for. Also, all the patches I have here have been submitted as PRs. Once these are resolved, it would be nice to see a fresh release on `master` so we can get Python 3.x support and fixes to these issues.

**Pull request merged**
