### PR TITLE
add r-tmb

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @daler

**Comment by daler** [comment]
Thanks -- bulk is getting close! 

Even though this is a new recipe, does it need a re-render with the updated conda-smithy? Looks like it's still building (and failing) on R 3.4.2 here.

**Comment by daler** [comment]
Actually https://github.com/conda-forge/staged-recipes/blob/master/.CI/build_all#L45 suggests it should not build for 3.4.2. Any ideas on what to change?

**Comment by bgruening** [comment]
There should be no rerendering needed. I have no clue whats going on here. It worked a few hours ago :(

@isuruf for the rescue!

**Comment by cbrueffer** [comment]
I see the same with #4403

**Comment by isuruf** [comment]
It's because of https://github.com/conda-forge/staged-recipes/blob/master/scripts/run_docker_build.sh#L67

**Comment by bgruening** [comment]
@isuruf I changes it in this PR. This duplicated code is not good. There are two many places were we need to update those. Why was it working yesterday?

Please also note that `--matrix-conditions` vs `--matrix-condition` in both places.

**Comment by isuruf** [comment]
https://github.com/conda-forge/staged-recipes/blob/master/appveyor.yml#L80

**Comment by bgruening** [comment]
I'm crying ;) Give me a sec.

**Comment by bgruening** [comment]
@isuruf does this look ok for you? I would like to merge it as soon as it gets green.

**Comment by isuruf** [comment]
travis-ci passed in the first commit. Later changes are unrelated to osx.

**Comment by bgruening** [comment]
Thanks a lot!

**Pull request merged**
