### PR TITLE
add: pyOMA-2

### PR DESCRIPTION
**Pull request by dfm88**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dfm88** [comment]
👍

**Comment by dfm88** [comment]
@conda-forge-admin, please rerun bot

**Comment by dfm88** [comment]
I confirm I want to be list as maintainer

**Comment by dagghe** [comment]
I confirm I want to be list as maintainer

**Comment by dfm88** [comment]
@conda-forge-admin, please lint

**Comment by dfm88** [comment]
@conda-forge-admin, please lint

**Comment by dfm88** [comment]
@conda-forge/help-python ready for review.
The linting about maintainers confirmation still fails but we both commented. Thank you very much

**Comment by dfm88** [comment]
@dagghe @dfm88 already commented on this pr

**Comment by dfm88** [comment]
@conda-forge-admin, please lint

**Review by xhochy — CHANGES_REQUESTED** [review]
What's the reason this isn't noarch?

**Comment by dfm88** [comment]
> What's the reason this isn't noarch?

hi @xhochy the package can't be noarch for the following reasons (considering that the package supports python >=3.8 <3.13)
- numpy version for python 3.8, due to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), Numpy drops support for active versions of Python before their support ends. Therefore, there are versions of numpy that cannot be installed for certain active versions of Python and this leads to PDM unable to resolve the dependencies, or attempting to install a version of numpy that does not have a wheel. So we need a specific numpy version for python==3.8
- Platform-specific dependencies: The PyQt5 and VTK dependency of pyvista must have os specific installations that are handled in the [toml](https://github.com/dagghe/pyOMA2/blob/main/pyproject.toml) file of the project.

Thanks for your time

**Comment by xhochy** [comment]
These issues sounds like they are related to the PyPI/wheel world and don't apply to the conda-forge setting where the solver is more capable and all builds are binaries.

You should be able to make this noarch by requiring `python >=3.9`, we don't build packages for 3.8 anymore on conda-forge.

**Comment by dfm88** [comment]
> These issues sounds like they are related to the PyPI/wheel world and don't apply to the conda-forge setting where the solver is more capable and all builds are binaries.
> 
> You should be able to make this noarch by requiring `python >=3.9`, we don't build packages for 3.8 anymore on conda-forge.

Ok great, thank you for the insights, I dropped the support for python 3.8 and made it noarch

**Review by xhochy — APPROVED** [review]

**Pull request merged**
