### PR TITLE
Pymc

### PR DESCRIPTION
**Pull request by ocefpaf**
@fonnesbeck I tired to send this as a PR to your fork but somehow my GitHub web-interface  cannot see your fork.

Replaces https://github.com/conda-forge/staged-recipes/pull/2226

### CODE REVIEW

**Comment by ocefpaf** [comment]
The CIs hooks are off this morning. I will try to kick the build again soon.

**Comment by ocefpaf** [comment]
Travis-CI passes too in my own instance: https://travis-ci.org/ocefpaf/staged-recipes/

But conda-forge's one is backlogged and will take a while.

**Comment by fonnesbeck** [comment]
Ah, just saw this now.

**Comment by ocefpaf** [comment]
> Ah, just saw this now.

Fortran extensions are tricky so I decided to put this together. We can try Windows later in the feedstock.
I have some relative success with `mingwpy` on Windows. (Usually Python 2.7 and Win32 works fine.)

**Comment by fonnesbeck** [comment]
Thanks!

**Comment by ocefpaf** [comment]
No problem. Once the feedstock is created we can work on the Windows package.

**Pull request merged**
