### PR TITLE
Added hsluv cassowary and pypng (vispy test dependencies)

### PR DESCRIPTION
**Pull request by hmaarrfk**
cc: @djhoese you should be able to create full `environment.yaml` files to manage all your build time dependencies once these get merged in.

Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by djhoese** [comment]
FYI I hope, with future funding possibly, to remove the cassowary dependency in favor kiwisolver: https://github.com/vispy/vispy/pull/1501

**Comment by hmaarrfk** [comment]
Whatever happen, this would be useful for now.

**Comment by npavlovikj** [comment]
LGTM, thanks @hmaarrfk !

**Comment by hmaarrfk** [comment]
Thanks

**Pull request merged**
