### PR TITLE
Add pint-pandas recipe

### PR DESCRIPTION
**Pull request by znicholls**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by znicholls** [comment]
Copied https://github.com/conda-forge/pint-feedstock/commit/b107bcafd4a8571b416bd06b7c292eccc62ef3fc for the setuptools scm fix

**Comment by dopplershift** [comment]
I'm not sure why exactly it's failing on Windows. Maybe try adding `setuptools` to host requirements as well?

**Comment by znicholls** [comment]
Cheers @dopplershift! Do you want to listed as a maintainer too (would make sense given you maintain the pint recipe?)

**Comment by znicholls** [comment]
@conda-forge/help-python would it be possible to get some advice on why the windows build is failing please?

**Comment by dopplershift** [comment]
Ah, I lost it earlier in the logs. The problem is the use of setting the environment variable on the setup.py line:
```
SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vvv
```
on Windows it shows:
> 'SETUPTOOLS_SCM_PRETEND_VERSION' is not recognized as an internal or external command,
operable program or batch file.

That's fine, since this is noarch Python, we don't need to build on windows (which is why the Pint recipe works fine with that same kind of line). Can you change the pip invocation (keeping `SETUPTOOLS_SCM_PRETEND_VERSION`) to the documented standard:
```
{{ PYTHON }} -m pip install . --no-deps -vv
```
? We don't need the extra output cluttering the log now. At that point I can merge.

**Comment by znicholls** [comment]
done thanks @dopplershift! @hgrecco and @dopplershift  do you want to be listed as maintainers?

**Comment by dopplershift** [comment]
Well, I'm not really a user, but I am happy to help make sure the package stays up-to-date.

**Pull request merged**
