### PR TITLE
r-ncmeta

### PR DESCRIPTION
**Pull request by xhochy**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/help-r any idea why/how this is failing?

```
** byte-compile and prepare package for lazy loading
Error in rbind(info, getNamespaceInfo(env, "S3methods")) : 
  number of columns of matrices must match (see arg 2)
ERROR: lazy loading failed for package ‘ncmeta’
```

**Comment by jdblischak** [comment]
@xhochy Some upstream dependency must have changed because I am also getting a related error about S3methods when trying to load existing R binaries. I was able to run the code below [7 days ago](https://github.com/conda-forge/r-base-feedstock/issues/91#issuecomment-510143734), and neither r-base 3.5.1 nor r-ggplot2 have been updated since then:

```
docker run -it --rm continuumio/miniconda3:latest bash
conda config --set always_yes yes
conda config --add channels conda-forge
conda update --all
conda install r-ggplot2
Rscript -e 'library(ggplot2)'
Error: package or namespace load failed for ‘ggplot2’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)
Execution halted

```

https://anaconda.org/conda-forge/r-base/files?version=3.5.1
https://anaconda.org/conda-forge/r-ggplot2/files

**Comment by dbast** [comment]
After retrigger the error is:
```
The following specifications were found to be incompatible with each other:

  - r-base=3.6
  - r-rnetcdf -> r-base[version='>=3.5.1,<3.5.2.0a0']
```

Looks like this requires r-rnetcdf to be migrated.

**Comment by jdblischak** [comment]
> Looks like this requires r-rnetcdf to be migrated.

That's causing the error for the R 3.6.1 build. The previous error is for the R 3.5.1 build, which presumably still exists (the R 3.6.1 build was attempted first).

**Comment by xhochy** [comment]
@conda-forge/staged-recipes This is ready for review/merge.

**Pull request merged**
