### PR TITLE
[READY4REVIEW] Add Postgres-XL (eXtensible Lattice) to conda-forge

### PR DESCRIPTION
**Pull request by sodre**

### CODE REVIEW

**Comment by dougalsutherland** [comment]
To be clear: this conflicts with the [`postgresql`](https://github.com/conda-forge/postgresql-feedstock) package, yes?

**Comment by ocefpaf** [comment]
I don't think conda has the 'conflicts with' concept yet :-/

**Comment by sodre** [comment]
I can add "conflicts with PostgreSQL" to the summary. 

I hope this is not a reason to not have it merged.

**Comment by ocefpaf** [comment]
@sodre let's trust users, just improve the summary like you suggested and we'll merge this.

**Comment by dougalsutherland** [comment]
(Yep, it looks fine to me otherwise but a line in the summary saying that could be helpful.)

**Comment by dougalsutherland** [comment]
Merged, since it was only a summary change from the last passing commit. Thanks @sodre!

**Pull request merged**
