### PR TITLE
New tk_variant recipe so that a tk variant can be built with freetype

### PR DESCRIPTION
**Pull request by smithsp**
Note that this tk variant is an attempt to move https://github.com/conda-forge/tk-feedstock/pull/40 forward.

Mention @jjhelmus @beckermr who commented on the desired name of the variant , with `_tk_mutex` being the other option.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] ~Source is from official source.~ This is a metapackage
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by beckermr** [comment]
cc @conda-forge/core

**Comment by smithsp** [comment]
Note that the last version failed the `import MDSplus` test (but otherwise built!).  I will push my next attempt.

**Comment by isuruf** [comment]
I don't think we need a separate package like this.

**Comment by smithsp** [comment]
@isuruf Are you suggesting that https://github.com/conda-forge/tk-feedstock/pull/40/files#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2 is sufficient?

**Comment by isuruf** [comment]
Yes

**Comment by smithsp** [comment]
Thanks.  I will close this for now.  We can come back to it if https://github.com/conda-forge/tk-feedstock/pull/40/files doesn't work without it.

**Pull request closed without merging**
