### PR TITLE
Backports.ssl match hostname

### PR DESCRIPTION
**Pull request by scopatz**
needed to address https://github.com/conda-forge/websocket-client-feedstock/issues/10

noarch: python

### CODE REVIEW

**Comment by scopatz** [comment]
@conda-forge/staged-recipes, readyfor review!

**Comment by isuruf** [comment]
https://github.com/conda-forge/ssl_match_hostname-feedstock

**Comment by scopatz** [comment]
Oh thanks for pointing that out.  I think this should be a metapackage, then, and that package doesn't have the correct dependencies.

**Comment by isuruf** [comment]
Can you open an issue in that feedstock then?

**Comment by scopatz** [comment]
Done: https://github.com/conda-forge/ssl_match_hostname-feedstock/pull/7

**Comment by isuruf** [comment]
It's better to do this in the ssl_match_hostname recipe with multiple outputs.

**Comment by scopatz** [comment]
> It's better to do this in the ssl_match_hostname recipe with multiple outputs.

Would you mind putting in a PR then?  Or do you have a conda-forge recipe to use as an example? It wasn't clear to me that conda-forge fully works with multiple outputs yet

**Comment by isuruf** [comment]
There are only 5 recipes, none of which is the same as this case. So, here's a PR https://github.com/scopatz/ssl_match_hostname-feedstock/pull/1

**Pull request closed without merging**
