### PR TITLE
Added py-plumed recipe

### PR DESCRIPTION
**Pull request by GiovanniBussi**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
I think this is failing because plumed recipe is not yet available on conda-forge channel. Will try later.

**Comment by GiovanniBussi** [comment]
@conda-forge/help-python-c I think this is ready for review.

I have a small doubt. This recipe shares a lot with [plumed recipe](https://github.com/conda-forge/plumed-feedstock/blob/master/recipe/meta.yaml) that I pushed a couple of days ago. The two packages are loosely coupled (no need to be in perfect sync). `py-plumed` is just loading with dlopen a dynamic library installed by `plumed` with a stable interface (and can also work without the `plumed` package installed, e.g. loading a library compiled by the user).

__Is it worth trying to merge them in a single recipe playing with `outputs:`?__

Notice that `plumed` recipe has no python in it, so it should not be pinned to the python version (27/36/37), whereas `py-plumed` has no other library included, so it should not be pinned to none of the libraries used by `plumed`. Is there an example where I can copy from? Or should I leave the two packages as two separate recipes?

Thanks!

Giovanni

**Comment by chrisburr** [comment]
If the versions don't need to be kept perfectly in sync I would keep them as separate recipes. (For reference, [here](https://github.com/conda-forge/awkward-feedstock/blob/master/recipe/meta.yaml) is a recipe I maintain where there are multiple outputs with an exact version constraint between them.)

Is there a reason not to include `plumed` as a runtime dependency? In my opinion installing with conda should work out of the box. If a user wants to use a custom build of `plumed` they can set the option/environment variable to override it.

**Comment by GiovanniBussi** [comment]
Thanks for the example, much easier than I thought! I think I will use this idea in the future (I am planning to split plumed in subpackages with additional functionalities, which should then be exactly in sync to have binary compatibility).

I am a bit confused by this comment:
````
# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
````

Does it mean that in my specific case I would have to add python requirement at the top level and thus would have separate plumed-py27/py36/py37 builds (which is what I do not want to have)?

In any case, I will also add plumed as a runtime dependence as you suggest. I see now that this is possible both with two separate packages and with a single package and `outputs:`.

**Comment by chrisburr** [comment]
It’s to tell conda-forge to do one build per Python version. In your case I guess you would want to specify the compiler to ensure that is set up correctly for each platform.

(Due to a quirk of conda smithy there always has to be something there at the top level or you get weird errors. I generally use make if there are no dependencies at all)

**Comment by GiovanniBussi** [comment]
I see thanks! If you do not have objections, I will try to see if I can merge the python interface directly in the `plumed` package. I think future maintenance will be simpler. I thus close this request for now.

If I don't manage to get something I will open it again.

Thanks a lot!

**Pull request closed without merging**
