### PR TITLE
Fix up feedstock conversion

### PR DESCRIPTION
**Pull request by jakirkham**
Corrections for selectors/`skip`(s) in PR ( https://github.com/conda-forge/staged-recipes/pull/2051 ). Details in the commit message and in the original PR's [diff]( https://github.com/conda-forge/staged-recipes/pull/2051/files#diff-004c204b14211e5f314fdf600c713b6fR26 ).

cc @dolfim @ocefpaf

### CODE REVIEW

**Comment by dolfim** [comment]
thanks for looking into it. it was indeed suspicious that it took so long.

**Comment by jakirkham** [comment]
So this fix-up PR doesn't actually build it. That all being said, does this looks right from your end? If so, we can go ahead and get this in.

**Comment by dolfim** [comment]
Yes it looks all right!

**Comment by jakirkham** [comment]
Thanks for the confirmation.

**Pull request merged**
