### PR TITLE
add initial recipe for snowflake-connector-python 1.6.12

### PR DESCRIPTION
**Pull request by hajapy**
The Snowflake Connector for Python provides an interface for developing Python applications that can connect to Snowflake and perform all standard operations. It provides a programming alternative to developing applications in Java or C/C++ using the Snowflake JDBC or ODBC drivers.

The connector is a native, pure Python package that has no dependencies on JDBC or ODBC.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
You can resolve the merge error by force-pushing away https://github.com/conda-forge/staged-recipes/pull/7008/commits/0a3b44db5401f032a827095c1b64492c97914875, now that #7009 is merged.

Also, you should probably add [entry points](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#python-entry-points) for the [entry points in `setup.py`](https://github.com/snowflakedb/snowflake-connector-python/blob/v1.6.12/setup.py#L69-L77). And you should remove `--no-deps --ignore-installed --no-cache-dir` from the `pip` line; `--no-cache-dir` is actually a bad idea, and `conda-build` now sets environment variables to do the others. (We need to fix the `example` recipe to take that out, will make a PR now.) Other than that, the recipe looks good to me.

**Comment by hajapy** [comment]
Regarding those extra args, such as --no-deps, it looks like pip is actually installing the dependencies in the build log without that arg, whereas I want/need the packages to be from conda-forge not pypi.

**Comment by dougalsutherland** [comment]
I was confused by that too; it doesn't actually install them, but [it does cache them](https://github.com/conda-forge/conda-forge.github.io/pull/653#issuecomment-435622143) kind of wastefully. I'm fine with leaving `--no-deps` in to avoid that confusion, personally.

**Comment by hajapy** [comment]
Ok, that's very confusing. It also fills the log with so many unnecessary messages making it harder to read the log file. 

I still don't know why the build succeeded on travis with `--no-deps` and failed without it. I'm waiting to see if the latest branch (with `--no-deps` again) succeeds on travis.

**Comment by hajapy** [comment]
Ah, so indeed the build passes on travis with `--no-deps` and fails without it. Any insights as to why that could happen?

**Comment by dougalsutherland** [comment]
From [the full log](https://api.travis-ci.org/v3/job/452378768/log.txt), because `-vvv` makes it waaay too verbose to see anything (we should drop it to `-vv` or something):

 ```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/travis/miniconda/conda-bld/snowflake-connector-python_1541683071515/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/cryptography/hazmat/bindings/_constant_time.abi3.so (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```

This makes me think that you do actually need `--no-deps`. I can't investigate further right now, but leave it in for now.

**Comment by hajapy** [comment]
Ok thanks, I've done that and incorporated your other suggestions.

**Comment by jakirkham** [comment]
> This makes me think that you do actually need --no-deps.

Confirmed. Raised as issue ( https://github.com/conda/conda-build/issues/3254 ) (though used a different recipe).

**Comment by hajapy** [comment]
@dougalsutherland Is there anything further needed on this PR then?

**Comment by hajapy** [comment]
@conda-forge/staged-recipes could someone review/merge this?

**Pull request merged**
