### PR TITLE
Add tango-controls-tui recipe

### PR DESCRIPTION
**Pull request by beenje**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by SKAJohanVenter** [comment]
Confirming myself as maintainer.

**Comment by SKAJohanVenter** [comment]
Hi @beenje 

Excuse my conda build ignorance...

Please refer to the [Dockerfile](https://github.com/SKAJohanVenter/tango-controls-tui/blob/main/Dockerfile) to see the build steps I used to build the image. 
You need to have `cppTango` and `tango-idl` built and installed to get the required header files required by `tango-client`. See [here](https://crates.io/crates/tango-client).

As for licences I imagine we would need to add:
- cppTango, GNU Lesser General Public License v3.0, https://gitlab.com/tango-controls/tango-idl/-/blob/main/LICENSE
- tango-idl, GNU Lesser General Public License v3.0, https://gitlab.com/tango-controls/cppTango/-/blob/main/LICENSE
- tango-rs, GPL-3.0+, https://crates.io/crates/tango-client
- tango-controls-tui, MIT License, https://github.com/SKAJohanVenter/tango-controls-tui/blob/main/LICENSE

Shout if there's anything else I can help with.

Johan

**Comment by beenje** [comment]
Thanks @SKAJohanVenter.

`cppTango` is defined as build dependency. It is linked dynamically so there is no need to specify the license.

I'm not sure about the rust dependencies as this is my first rust package.
We might have to mention the [tango-client](https://crates.io/crates/tango-client) license. I'll check with the conda-forge team.

**Comment by hardion** [comment]
@SKAJohanVenter, using a GPL3 dependency should force the project to be GPL3 if I am not wrong.

**Comment by SKAJohanVenter** [comment]
@hardion @beenje  I have the same understanding. I updated `tango-controls-tui` to be dual GPL-3.0 and MIT. I initially used MIT since it's the de facto standard for Rust projects. Now you can take your pick.

**Comment by beenje** [comment]
> I updated `tango-controls-tui` to be dual GPL-3.0 and MIT. I initially used MIT since it's the de facto standard for Rust projects. Now you can take your pick.

Thanks @SKAJohanVenter, could you please bump the version?

**Comment by SKAJohanVenter** [comment]
> > I updated `tango-controls-tui` to be dual GPL-3.0 and MIT. I initially used MIT since it's the de facto standard for Rust projects. Now you can take your pick.
> 
> Thanks @SKAJohanVenter, could you please bump the version?

@beenje Done, 0.0.2

**Comment by beenje** [comment]
Thanks @wolfv!

**Pull request merged**
