### PR TITLE
added missMDA

### PR DESCRIPTION
**Pull request by rasmusagren**
This PR was made with the conda_r_skeleton_helper script.

### CODE REVIEW

**Comment by dbast** [comment]
Please nobody merge this. This PR atm contains a recipe on root level.

**Comment by dbast** [comment]
@rasmusagren Thanks for the recipe. The recipe itself looks good, it is just in the wrong folder. After changing this and when CI is fine, it can go in.

**Comment by dbast** [comment]
It is a noarch recipe... it will build fine on linux after feedstock conversion... installation on windows will require r-mice for windows.

**Comment by rasmusagren** [comment]
@dbast Oops :) Fixed now, but it fails to build for Windows, apparently because r-mice isn't built there. How would I go about fixing this? Is it fine to put this as non-windows only or do I have to work my way from r-mice and all the way down its dependency stack? I don't recall building for Windows before, is it a new thing?

**Comment by bgruening** [comment]
> Is it fine to put this as non-windows only or do I have to work my way from r-mice and all the way down its dependency stack?

Yes, this is what you need to do. :(

**Pull request merged**
