### PR TITLE
added recipe for carl ganz's package, rintrojs - needed as a dependen…

### PR DESCRIPTION
**Pull request by federicomarini**
…cy for bioc package in bioconda

### CODE REVIEW

**Comment by federicomarini** [comment]
Thanks @bgruening for appearing 😄 

I'll wait for r-rintrojs to show up in the conda-forge channel and then proceed on the other recipe!

**Comment by dougalsutherland** [comment]
Installation seems to have not worked on Windows: [example log](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.20097/job/wd9i3t5cn8dgn10r)
```
> library('rintrojs')
Error in library("rintrojs") : there is no package called 'rintrojs'
Execution halted
```

**Comment by federicomarini** [comment]
Hi Dougal, being new to this I don't have many clues. Yet, one guess:
since I was migrating this from bioconda, I had to remove the bld.bat file. Should I restore this and probably most of the issues will be gone?
Thanks in advance for any hint!

**Comment by dougalsutherland** [comment]
Aha, yes, I didn't really look at the recipe but that's the reason – the Windows build isn't actually doing anything. :)

**Comment by federicomarini** [comment]
Ok, restored now. Let's wait and see, but this time I can be confident :)

**Comment by federicomarini** [comment]
Too soon to celebrate. 

The failures are only on machines with x86 architecture, but not on x64. Any pointers to what I should check? Is it common to exclude x86 machines for R packages? 

A link to the error-triggering part is here: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.20099/job/xuf6j5y051yytngx#L783

**Comment by dougalsutherland** [comment]
I don't know how R stuff works, really. @bgruening?

**Comment by bgruening** [comment]
We skip the x86 builds for R. That is ok.

**Comment by federicomarini** [comment]
Ok, thanks Björn! I inspected some other packages and could see that in some, but probably it is a standard approach. Is it documented somewhere, out of curiosity (and I did not search well enough)?

**Comment by federicomarini** [comment]
I see the travisCI is the only one missing, but also seems to be stalling. Do I need to re-trigger it somehow or is this just going to mean I will have to wait so long again?

**Comment by bgruening** [comment]
All good, travis for OSX is just super slow atm - there is a huge backlog

**Comment by federicomarini** [comment]
Okiedokie. I'll sit tight ;)

**Comment by dougalsutherland** [comment]
@federicomarini If you'd prefer to get , we can merge it with a skip on Mac and then send a PR to the feedstock to add it later. That would get Linux/Windows builds up now, instead of waiting potentially a while for Travis. Your call.

**Comment by bgruening** [comment]
I take this call up. Lets save some travis build time.

**Comment by federicomarini** [comment]
Good call. Is there something else on my side that I need to do for this?

If no, I'll then wait for the recipe to be available in the forge and then proceed with the other recipe in bioconda.

In any case, thank you guys for the smooth start ;)

**Comment by federicomarini** [comment]
Seems the travisCI status is doing somewhat better:
https://www.traviscistatus.com/incidents/mc9x2wmpnvhg
Do I need to trigger the OSX CI-test - and have the OSX version of the binary built? In this way I could move on for the `ideal` bioconda recipe

**Comment by bgruening** [comment]
You can see it waiting here: https://travis-ci.org/conda-forge/r-rintrojs-feedstock/branches

**Comment by federicomarini** [comment]
It passed a couple of hours ago the travisCI check, so I guess the recipe can be considered finalized.
Up to you to close it? Once again, thanks for assisting me in the first submission ;)

**Pull request merged**
