### PR TITLE
simbody: remove workaround for including GLUT.

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by chrisdembia** [comment]
I do not intend for this to be merged; I am testing a bug fix.

**Comment by moorepants** [comment]
FYI, all pull requests should be wrt to https://github.com/conda-forge/simbody-feedstock

staged-recipes is only used for the initial submission of a recipe.

**Comment by chrisdembia** [comment]
Ooops; that would have been easier. I would still run into the GCC issue on `simbody-feedstock`, right?

**Comment by moorepants** [comment]
Probably. I'm not sure why the latest 4.X version of gcc isn't available.

**Comment by dougalsutherland** [comment]
Closing this, because it belongs on the feedstock.

**Pull request closed without merging**
