### PR TITLE
Added recipe for sentinels

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Added issue about missing manifest - see [issue 3.](https://github.com/vmalloc/sentinels/issues/3)

**Comment by jakirkham** [comment]
Well that got resolved in a real hurry. Maybe we can just wait a little bit and do `1.0.0`. What do you think?

**Comment by pmlandwehr** [comment]
seems to be stuck - close/reopen

**Comment by pmlandwehr** [comment]
(ping @ocefpaf for merge)

**Comment by jakirkham** [comment]
Thanks @pmlandwehr.

**Pull request merged**
