### PR TITLE
Add yacron

### PR DESCRIPTION
**Pull request by mcs07**

### CODE REVIEW

**Comment by mcs07** [comment]
Should `PLATFORM: "32"` be removed from appveyor build matrix?
https://github.com/conda-forge/staged-recipes/blob/master/.appveyor.yml#L9

**Comment by mariusvniekerk** [comment]
@mcs07 This is getting addressed in #5705.

**Comment by jakirkham** [comment]
If you merge with latest `master`, Windows 32-bit will be dropped.

**Comment by mcs07** [comment]
Rebased on master, all checks now pass 😁 

I think this is ready to go

**Comment by jakirkham** [comment]
Thanks @mcs07.

**Pull request merged**
