### PR TITLE
Add recipe for r-mpoly, conda_r_skeleton used

### PR DESCRIPTION
**Pull request by npavlovikj**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by npavlovikj** [comment]
Missing dependencies are in #9524 and #9525 .

**Comment by dbast** [comment]
@npavlovikj How was this generated with conda_r_skeleton, what was the conda-build version? Current conda-build + conda_r_skeleton generate totally different result here.

**Comment by npavlovikj** [comment]
@dbast , "conda_r_skeleton_helper" is up-to-date - I pulled the newest changes when I created the branch on 09/11. On the other hand, the "conda-build" version used is 3.17.8.

**Comment by dbast** [comment]
The newest conda-forge conda-build version is 3.18.9. Can you update to that and update the PR. Thanks.

**Comment by npavlovikj** [comment]
@dbast , I updated conda-build to 3.18.9 and conda to 4.7.12, but I am getting the same recipe as here. Where can the different results you saw be noticed?

**Comment by dbast** [comment]
@npavlovikj Is this really to 100% the output of https://github.com/bgruening/conda_r_skeleton_helper ? Or did you manually remove the cran metadata and templated the sha256?

**Comment by npavlovikj** [comment]
@dbast , the new commit is the complete output I got from "conda_r_skeleton_helper" and conda-build=3.18.9. I did clean "meta.yaml" manually earlier by removing the metadata part.

**Comment by dbast** [comment]
@npavlovikj The recipe looks fine now. There seem to be either some general CI issues (see other PRs) or some issues with transitive dependencies not available/broken. Both to be solved outside of this recipe/pr.

**Comment by npavlovikj** [comment]
Thanks for the feedback @dbast ! I will give it a few days and try to restart the build then. Just curious - has the build system been always using `strict_channel_priority`? I saw that as part of the error message now, so I wonder if that might be part of the reason for the Linux error as well?

**Comment by dbast** [comment]
Yay, it finally builds successful.

**Pull request merged**
