### PR TITLE
add tzdata

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://pypi.org/project/tzdata/#description

@pganssle do you want to be a maintainer here?

### CODE REVIEW

**Comment by pganssle** [comment]
@ocefpaf Sure.

One thing I'll note: I'm not sure how useful the `tzdata` package is on conda forge, because presumably conda-forge can ship the actual time zone data package, no? `tzdata` is a workaround for the fact that there is no cross-platform way to ensure that the system has the time zone database installed, which is why I wouldn't expect proper package managers to need to ship it, and instead they would use the compile-time configuration in CPython to just point `zoneinfo` at wherever their installed time zone data is.

That said, `tzdata` is a package in its own right and other tools may rely on it directly rather than using a "resolve the system time zones first, then use `tzdata`", so I suppose it's worth making it available.

**Comment by ocefpaf** [comment]
> One thing I'll note: I'm not sure how useful the `tzdata` package is on conda forge, because presumably conda-forge can ship the actual time zone data package, no?

We can. (I'm not sure we do already. I need to check.)

`tzdata` is a workaround for the fact that there is no cross-platform way to ensure that the system has the time zone database installed, which is why I wouldn't expect proper package managers to need to ship it, and instead they would use the compile-time configuration in CPython to just point `zoneinfo` at wherever their installed time zone data is.
> 
> That said, `tzdata` is a package in its own right and other tools may rely on it directly rather than using a "resolve the system time zones first, then use `tzdata`", so I suppose it's worth making it available.

Yep. That is why I added it. People will probably specify it as a dependency in python packages and, in that case, having the same package they will get from PyPI, keeps things consistent. Does that make sense?

**Comment by ocefpaf** [comment]
@conda-forge/staged-recipes this is ready for review!

**Comment by ocefpaf** [comment]
Thanks @chrisburr!

**Pull request merged**
