### PR TITLE
Add bitshuffle package

### PR DESCRIPTION
**Pull request by cpcloud**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xmnlab** [comment]
@cpcloud awesome! thanks for working on that. I started a PR for that some days ago https://github.com/conda-forge/staged-recipes/pull/8116 ... but yours seems much better :) thanks!

if you want you can add me as maintainer :+1:

**Comment by xmnlab** [comment]
not sure why tests for win (appveyor) is not passing. maybe you could skip for windows for now and we can try to fix the issue for windows later.

**Comment by xmnlab** [comment]
@cpcloud what do you think about it?

**Comment by xmnlab** [comment]
hey @cpcloud any update about that? if I can help in any way let me know.

**Comment by xmnlab** [comment]
hey @cpcloud any update here? can I help in any way?

**Comment by chrisburr** [comment]
Added by #8116

**Comment by cpcloud** [comment]
@xmnlab I ended up stopping work on this because I didn't think it would be helpful for our goal of being able to build a kudu package for conda-forge. kudu has an extremely bespoke and complex way of using bitshuffle, including custom linking steps during a build.

**Comment by xmnlab** [comment]
@cpcloud thanks for the feedback!
oh I see, I didn't know that .. well I will be back to kudu packaging let me know if you have more thoughts related to kudu packaging.

**Pull request closed without merging**
