### PR TITLE
add tephi package

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by trexfeathers** [comment]
I am happy to be a maintainer

**Comment by bjlittle** [comment]
@ocefpaf Hey fella, hope you and the family are keeping safe and well. If I've peaked your interest, any possibility of reviewing and merging this PR? It would help me out a lot :smile: 

Cheers

**Comment by ocefpaf** [comment]
> @ocefpaf Hey fella, hope you and the family are keeping safe and well.

We are all good. Hope you all are safe too and working from home.

> If I've peaked your interest, any possibility of reviewing and merging this PR? It would help me out a lot 

No problem. Made a minor modification and this is good to go.

BTW, if you ping the `@conda-forge/staged-recipes` you will probably get a review faster than pinging just me. I'm happy to review but I'm slow to respond lately b/c of the baby.

**Comment by bjlittle** [comment]
@ocefpaf Awesome, thanks dude.

We're all good too... and loving working from home.

And congratulations on the baby! New life. It's a truly wonderful and beautiful thing - enjoy my friend 

All the best :smile:

**Pull request merged**
