### PR TITLE
Add recipes for diff-cover and jinja2_pluralize

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Weird, Linux failure seems unrelated:

```
+ conda install --yes --quiet 'conda!=4.6.1' 'conda-forge-ci-setup=2.*' conda-forge-pinning networkx conda-build
+ source run_conda_forge_build_setup
++ export CPU_COUNT=2
++ CPU_COUNT=2
++ export PYTHONUNBUFFERED=1
++ PYTHONUNBUFFERED=1
++ conda config --set show_channel_urls true
++ conda config --set auto_update_conda false
++ conda config --set add_pip_as_python_dependency false
++ export CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts
++ CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts
/opt/conda/bin/run_conda_forge_build_setup: line 15: CONFIG: unbound variable
```

**Comment by nicoddemus** [comment]
Thanks @chrisburr!

I believe this can now be reviewed/merged. 👍

**Comment by chrisburr** [comment]
Yeah, the error was due to bug in the CI scripts: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/59

LGTM 👍

**Comment by nicoddemus** [comment]
I see, Thanks!

**Pull request merged**
