### PR TITLE
Add mne-rsa

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@wmvanvliet The package import fails:

> ImportError: cannot import name '_kendall_dis' from 'scipy.stats.stats' (/home/conda/staged-recipes/build_artifacts/mne-rsa_1645903139898/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/scipy/stats/stats.py)

I couldn't figure out which SciPy version is required. Can you help?

**Comment by wmvanvliet** [comment]
I'm willing to be listed a co-maintainer.

I'll look into `kendall_dis` when I have some time. It's an important part of the package.

**Comment by hoechenberger** [comment]
I think the module has just moved in recent versions of SciPy. Question is, when did this happen / what's the latest version we support.

**Comment by larsoner** [comment]
I'm willing to be listed a co-maintainer.

**Comment by wmvanvliet** [comment]
MNE-RSA updated to version 0.5, should now be compatible with all scipy versions

**Comment by hoechenberger** [comment]
Great, thank you, @wmvanvliet!

**Comment by hoechenberger** [comment]
Windows build failing because of a bug in the package; I've opened an issue at https://github.com/wmvanvliet/mne-rsa/issues/16

**Comment by hoechenberger** [comment]
@conda-forge/staged-recipes, this PR is ready for review. Thank you!

**Review by dopplershift — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thank you, @dopplershift!

**Pull request merged**
