### PR TITLE
Add recipe for bipedal-locomotion-framework

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
The tests are failing with:
~~~
Packaging bipedal-locomotion-framework-python
Reloading output folder: /home/conda/staged-recipes/build_artifacts
Mamba failed to solve:
 - pybind11-abi 4.* hd8ed1ab_3
 - wheel 0.37.1.* pyhd8ed1ab_0
 - pip 22.2.2.* pyhd8ed1ab_0
 - pybind11-global 2.10.0.* py310hbf28c38_0
 - pybind11 2.10.0.* py310hbf28c38_0
 - libbipedal-locomotion-framework 0.9.0.* h21f30a8_0

with channels:
 - local
 - conda-forge
 - conda-forge

The reported errors are:
- Encountered problems while solving:
-   - package libbipedal-locomotion-framework-0.9.0-h21f30a8_0 requires pcl >=1.12.1,<1.12.2.0a0, but none of the providers can be installed
- 
~~~

Not sure it is trying to install openssl 3.0.5 . However, the problem is that there are no qt build with openssl, so eventually this should be fixed by https://github.com/conda-forge/qt-main-feedstock/pull/50 .

**Comment by traversaro** [comment]
@GiulioRomualdi are you interested in mantaining this recipe?

**Comment by traversaro** [comment]
I forgot to package a dependency, [unicycle-footstep-planner](https://github.com/robotology/unicycle-footstep-planner).

**Comment by traversaro** [comment]
> I forgot to package a dependency, [unicycle-footstep-planner](https://github.com/robotology/unicycle-footstep-planner).

I proposed a recipe for this missing package in https://github.com/conda-forge/staged-recipes/pull/20752 .

**Comment by traversaro** [comment]
Linux and macOS tests are failing with:
~~~
import: 'bipedal_locomotion_framework'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/bipedal-locomotion-framework_1666394492512/test_tmp/run_test.py", line 2, in <module>
    import bipedal_locomotion_framework
  File "/home/conda/staged-recipes/build_artifacts/bipedal-locomotion-framework_1666394492512/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/site-packages/bipedal_locomotion_framework/__init__.py", line 1, in <module>
    from .bindings import *
ImportError: arg(): could not convert default argument 'mixed_velocity: manif::SE3Tangent<double>' in method '<class 'bipedal_locomotion_framework.bindings.ik.SE3Task'>.set_set_point' into a Python object (type not registered yet?)
Tests failed for bipedal-locomotion-framework-python-0.9.0-py39hac7f59c_0.tar.bz2 - moving package to /home/conda/staged-recipes/build_artifacts/broken
~~~

**Comment by traversaro** [comment]
Now test is failing with:
~~~
The reported errors are:
- Encountered problems while solving:
-   - package libbipedal-locomotion-framework-0.9.0-h42d203b_0 requires vtk >=9.1.0,<9.1.1.0a0, but none of the providers can be installed
~~~

probably again some issue of ongoing migrations.

**Comment by traversaro** [comment]
> Now test is failing with:
> 
> ```
> The reported errors are:
> - Encountered problems while solving:
> -   - package libbipedal-locomotion-framework-0.9.0-h42d203b_0 requires vtk >=9.1.0,<9.1.1.0a0, but none of the providers can be installed
> ```
> 
> probably again some issue of ongoing migrations.

To avoid the problem, we temporary disable the PCL dependency. We can work on enabling once the recipe has been merged.

**Comment by traversaro** [comment]
> By looking a bit more it seems taht or some raeson `manifpy: 0.0.4-py39h965f727_7` is used, instead of the latest `_8` build, so the issue is due to [ami-iit/bipedal-locomotion-framework#545 (comment)](https://github.com/ami-iit/bipedal-locomotion-framework/issues/545#issuecomment-1168787064), that was fixed by [conda-forge/manif-feedstock#21](https://github.com/conda-forge/manif-feedstock/pull/21) . I re-triggered a manif build ([conda-forge/manif-feedstock#23](https://github.com/conda-forge/manif-feedstock/pull/23)) so that the a build with the latest pinned numpy is produced, to see if this solves the problems.

Even by using the latest manifpy build, the error is still there.

**Comment by traversaro** [comment]
> > By looking a bit more it seems taht or some raeson `manifpy: 0.0.4-py39h965f727_7` is used, instead of the latest `_8` build, so the issue is due to [ami-iit/bipedal-locomotion-framework#545 (comment)](https://github.com/ami-iit/bipedal-locomotion-framework/issues/545#issuecomment-1168787064), that was fixed by [conda-forge/manif-feedstock#21](https://github.com/conda-forge/manif-feedstock/pull/21) . I re-triggered a manif build ([conda-forge/manif-feedstock#23](https://github.com/conda-forge/manif-feedstock/pull/23)) so that the a build with the latest pinned numpy is produced, to see if this solves the problems.
> 
> Even by using the latest manifpy build, the error is still there.

I think the error may be much simpler. Basically the manif type are loaded by this line: https://github.com/ami-iit/bipedal-locomotion-framework/blob/bb20f7e4a267a0eb5c377f43a3e7c278ac48ce4b/bindings/python/bipedal_locomotion_framework.cpp.in#L74 , but that is only compiled in if `FRAMEWORK_USE_manif` is set at the CMake level, but we are not considering that in https://github.com/ami-iit/bipedal-locomotion-framework/pull/564 .

**Comment by traversaro** [comment]
@conda-forge/core the recipe is ready for review

**Review by xhochy — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @xhochy !

**Pull request merged**
