### PR TITLE
Add gilknocker

### PR DESCRIPTION
**Pull request by milesgranger**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Will close https://github.com/milesgranger/gilknocker/issues/13

### CODE REVIEW

**Comment by milesgranger** [comment]
As a note to anyone willing to answer:

Is there a way to simply install the [pre-built wheels from PyPI?](https://pypi.org/project/gilknocker/#files). They have no dependencies and it seems unnecessary to build/maintain two CIs for these binaries. Albeit, it makes sense if packages depend on other packages from conda, but when its completely stand alone, it seems a 'copying' of existing wheels would benefit users and save a bit of compute power.

**Comment by milesgranger** [comment]
@conda-forge/help-python-c, ready for review.

**Comment by milesgranger** [comment]
cc @conda-forge/help-python

**Comment by milesgranger** [comment]
@conda-forge/help-python-c, ready for review.

**Comment by milesgranger** [comment]
@conda-forge/python can you review, or is there someone specific I should ping? :pray:

**Comment by ocefpaf** [comment]
> it seems a 'copying' of existing wheels would benefit users and save a bit of compute power.

Some sort of interoperability of wheels and conda package has been a point of discussion since the beginning of binary artifacts packaging. While appealing, in practice  there are some challenges that make it hard. The main one is that, in conda-forge, all the dependencies are consistent with one-another via a global pinning. That makes it quite hard for the independent wheel model to work b/c package A can use C dependency version 2 while package D can use the same C dependency but version 2.

The other way around, building wheels from conda packages kind of fit both models but that idea was never explored to its full potential.

**Comment by milesgranger** [comment]
Thanks @ocefpaf for the review and the explaination, that his helpful to know. :)

**Pull request merged**
