### PR TITLE
Add Neovim and related libraries

### PR DESCRIPTION
**Pull request by AntoinePrv**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] ~If static libraries are linked in, the license of the static library is packaged.~
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@tdejager

**Comment by tdejager** [comment]
> @tdejager

Hey @AntoinePrv can you maybe add me as a collaborator in your forked repo then I can commit the unibilium stuff. :)

**Comment by AntoinePrv** [comment]
Hi @tdejager,

```
    - test -f "${PREFIX}/usr/local/lib/libunibilium.${SHLIB_EXT}"
    - test -f "${PREFIX}/usr/local/include/libunibilium.h"
```
We'd typically want to have lib installed under `"${PREFIX}/lib"` and headers under `"${PREFIX}/include"`. Do you know if there is a way to achieve that with unibilium? It's surprising that specifying `DESTDIR` add `usr/local` to the path.
If needed we could make a PR there.

**Comment by tdejager** [comment]
Yeah either we could patch the Makefile or send a pull request to make the
make file potentially use the ?= operator for PREFIX instead. What do you
think is best?

**Comment by AntoinePrv** [comment]
A dirty fix could be to install in a local directory, then `mv` the folder to `"${PREFIX}"` (if the install folder is not hard-coded anywhere)

**Comment by tdejager** [comment]
Yeah, that would be great. However `/usr/local/lib` is hardcoded in the
makefile. So I could use the DESTDIR to do something like `../../../foo`,
but that seems a bit dirty.

**Comment by AntoinePrv** [comment]
Looks like it could be done with `PREFIX` rather than `DESTDIR`.
It looks like there is also a `CMakeLists.txt` but `brew` seems to not be using it either so let's roll without for now.

- [ ] There is also a `TERMINFO_DIRS` that default to using `ncurses-config` on Linux. While adding `ncurses` to the build would point to the environment (not on MacOS!), I doubt that this should be the only lookup location (at least until we ship Alacritty on conda-forge!).

**Comment by tdejager** [comment]
Hi @AntoinePrv should I have a look why the osx build fails?

**Comment by AntoinePrv** [comment]
If you can that would be nice!

**Pull request closed without merging**
