### PR TITLE
recursive_diff

### PR DESCRIPTION
**Pull request by crusaderky**

### CODE REVIEW

**Comment by crusaderky** [comment]
@conda-forge-admin, please rerender

**Comment by crusaderky** [comment]
@conda-forge-admin, please rerender

**Comment by crusaderky** [comment]
@conda-forge/staged-recipes please help, I'm stuck. 

This is a pure Python package; however setup.py contains
```
      entry_points={'console_scripts': [
          'ncdiff = recursive_diff.ncdiff:main',
      ]}
```
so I can't use noarch because Windows needs to create ``ncdiff.exe``. Unsure if the recipe is correct now (it's copied from another project with actual C extensions).

I would expect to see py36 and py37 CI builds, but as you can see they're not there.
I understand that I'm supposed to rerender, but the calls to conda-forge-admin don't seem to have any effect. I tried running ``conda smithy rerender`` on my desktop, but it had the effect of completely nuking all CI triggers (it outright deleted appveyor.yml).

**Comment by isuruf** [comment]
See https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#python-entry-points

**Comment by crusaderky** [comment]
@isuruf @conda-forge/staged-recipes  thanks.
From that I desume that noarch should stay?
Please review and possibly merge.

**Comment by scopatz** [comment]
Yep, noarch should stay. Thanks!

**Pull request merged**
