### PR TITLE
Add Clojure

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by MementoRC** [comment]
This recipe simply installs the pre-built Clojure tool published by the Clojure team and seemingly relying upon the Maven  .jar
Building from source seems a bit tricky and more understanding of Clojure/Maven is in progress

The rational for adding this package is that I need it to build Quil, which is needed for QCS. Does this sound useful or an acceptable route for Clojure projects?

**Comment by MementoRC** [comment]
@conda-forge/help-java Hello, ready for review

**Comment by xhochy** [comment]
As with `leinigen`: We need the statically bundled third-party licenses for this. There is at least a maven plugin that can produce these lists, but I'm unsure whether it will work here.

**Comment by MementoRC** [comment]
I initially thought I needed `clojure` to build `quil` and thought it may be useful clojure devs who wants to work within conda, but I did not, so do you feel that it is a valuable addition to `conda-forge`?

I can look into the third-party licenses if this package looks useful to conda-forge

**Comment by xhochy** [comment]
I cannot state how useful this will be as I'm not familiar with the ecosystem. Other people may need to judge this. In the end, it will need somebody maintaining the recipe to make it really useful.

**Comment by MementoRC** [comment]
@xhochy This is ready for review. This one was a bit trickier to build from source. Once there is a versionon conda-forge, it's likely that the recipe can be simplified. Thanks

**Review by xhochy — APPROVED** [review]

**Pull request merged**
