### PR TITLE
Added r-tinytest

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Go home appveyor

**Comment by mariusvniekerk** [comment]
cc @conda-forge/r

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
I was hesitant to click the merge button. I don't have the time for extensive troubleshooting, and I gambled that it might just work. But it didn't.

The Travis build failed due to an error with the Travis API. The feedstock repository was created but not populated.

Commit: https://github.com/conda-forge/staged-recipes/commit/9be84ea0e28f63b84ac76d256fc54d65a53f34de
Travis build error: https://travis-ci.com/github/conda-forge/staged-recipes/builds/190281407#L1053
Feedstock: https://github.com/conda-forge/r-tinytest-feedstock

Notifying @conda-forge/staged-recipes

**Comment by chrisburr** [comment]
It's normal, next time travis runs for staged-recipes it should finish the feedstock creation. (The various CI providers APIs aren't really designed for conda-forge's use pattern and often hit rate limits/delays.)

I've just given travis a manual restart.

**Pull request merged**
