### PR TITLE
Recipe for ete3

### PR DESCRIPTION
**Pull request by pmlandwehr**
`ete3` is the latest version of [The ETE Toolkit](http://etetoolkit.org/), a python framework for the analysis and visualization of trees.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
cc'ing @conda-forge/bioconda-recipes about this build. I'm mostly interested in getting this made because it's a dependency for a more recent version of `girder`, which I try to keep up to date. If y'all are interested in taking this one over it's fine by me...

**Comment by mbargull** [comment]
I'm a bit confused since I couldn't find any reference to `ete3` in https://github.com/girder/girder/search?q=ete3.
*If* there was a dependency from `girder` on `ete3`, that would be a bad case scenario, actually. `conda-forge` should be rather self-contained (apart from a few exceptions coming from `defaults`) and not depend on packages from other channels, even if those channels use `conda-forge` as a base, like `bioconda` does.

**Comment by pmlandwehr** [comment]
My bad! It's a plugin dependency for [`girder_worker`](https://github.com/girder/girder_worker/blob/ec85660a3edc270fe8d51790d4d8942618d4bda1/girder_worker/plugins/types/requirements.txt), which *isn't* a feedstock but maybe someday will be.

**Comment by mbargull** [comment]
Thanks for clarifying!
:anguished: @conda-forge/bioconda-recipes: Overall the case here is that ETE is a toolkit for visualizing phylogenetic trees (hence bio-related) BUT you can, of course, also use it to visualize non-phylogeny-based trees -- hence, it could make sense to transfer `ete3` over...

Pinging contributors of the Bioconda recipe: @nsoranzo @simonvh @karel-brinda

Also, I'm wondering if anyone (@bgruening?) has thoughts what we should do about Biocontainers and Singularity containers on the Galaxy Depot when we transfer bioinf tools to conda-forge (ref: https://github.com/conda-forge/conda-forge.github.io/issues/561).

**Comment by bgruening** [comment]
@mbargull I maintain my own whitelist of interesting conda-forge repos and build containers for it. As soon as I get time I will make this more transparent and put it on github.

**Comment by simonvh** [comment]
@mbargull I did contribute to the ete3 recipe before, but I don't have any strong thoughts on where it fits best. Either conda-forge or bioconda, it's both fine by me...

**Comment by nsoranzo** [comment]
@pmlandwehr If you want to go ahead with moving ete3 to conda-forge, can you check the differences with https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ete3/meta.yaml 

In Bioconda the package is noarch and has additional `host:` and `run:` requirements.

**Comment by ltalirz** [comment]
We also would like to add a recipe for a package to `conda-forge` that depends on `ete3` - we would be fine with depending on `ete3` from a different channel (`etetoolkit` / `bioconda`) but if all dependencies should come from `conda-forge` we would need to add it here.

Is anybody working on this? Do you need help?

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes

**Comment by ltalirz** [comment]
@pmlandwehr Are you still available for being a maintainer of this feedstock?
Can you comment on the differences to the bioconda feedstock mentioned by @nsoranzo above?

**Comment by ltalirz** [comment]
Not sure there's going to be any replies soon, 
so starting another PR for this https://github.com/conda-forge/staged-recipes/pull/7315

**Pull request closed without merging**
