### PR TITLE
recipe for xroms

### PR DESCRIPTION
**Pull request by kthyng**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by kthyng** [comment]
Thanks @ngam! Should I ping on gitter again to get it merged?

**Comment by kthyng** [comment]
Might someone from @conda-forge/help-python be able to push this through? Thank you!

**Comment by rsignell-usgs** [comment]
Or maybe @ocefpaf  would be appropriate!

**Comment by ocefpaf** [comment]
> Might someone from @conda-forge/help-python be able to push this through? Thank you!

For some reason I was not getting the pings form the Python team. I just re-added myself to that team but feel free to also ping the stage-recipes team when submitting a PR here.

**Comment by kthyng** [comment]
@ocefpaf Oh ok I'll try to remember that next time. I did try gitter but didn't hear anything from there — seems like a busy time!

**Comment by kthyng** [comment]
@ocefpaf But thank you!

**Comment by ocefpaf** [comment]
> @ocefpaf Oh ok I'll try to remember that next time. I did try gitter but didn't hear anything from there — seems like a busy time!

Oh. Is gitter still active? I thought it was no longer working due to the migration to element.

It does look like our docs still mention both though :-/

https://conda-forge.org/docs/orga/getting-in-touch.html#gitter-and-element

However, I doubt folks are looking for messages on gitter.

**Comment by kthyng** [comment]
Ah that would explain it. Gitter is active in sort of a one-sided way.

**Pull request merged**
