### PR TITLE
feat: Add func-adl

### PR DESCRIPTION
**Pull request by matthewfeickert**
* c.f. https://github.com/iris-hep/func_adl
* Recipe generated with grayskull via 'grayskull pypi func-adl' and then edited to add additional information.
* Required for https://github.com/ssl-hep/ServiceX_frontend/issues/352

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [N/A] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
@gordonwatts can I please get you to sign off with a comment in the same way that you did for https://github.com/conda-forge/staged-recipes/pull/25914?

**Comment by matthewfeickert** [comment]
@gordonwatts ping on this.

**Comment by xhochy** [comment]
@matthewfeickert in cases where someone doesn't reply, it is common to remove them from the recipe and add them later on the feedstock.

**Comment by matthewfeickert** [comment]
@xhochy thanks. I'm in transit now but I'll remove @gordonwatts if he doesn't respond by this evening and then rebase and rerender this PR and tag for review.

**Comment by matthewfeickert** [comment]
@conda-forge/help-python, ready for review!

**Pull request merged**
