### PR TITLE
Switches to the org image

### PR DESCRIPTION
**Pull request by jakirkham**
Depends on this PR ( https://github.com/conda-forge/docker-images/pull/9 ) and some Docker Hub reconfiguration to be done first.

Switches from `pelson/obvious-ci:latest_x64` to ~~`condaforge/obvious-ci`~~ `condaforge/linux-anvil`. The source for this image is now maintained in this repo ( https://github.com/conda-forge/docker-images ). It is exactly the same source from before it is just moving to the org. In fact, the source was moved over in this PR ( https://github.com/conda-forge/docker-images/pull/5 ). Similar change proposed to conda-smithy in this PR ( https://github.com/conda-forge/conda-smithy/pull/151 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @pelson @ocefpaf @jjhelmus @msarahan

**Comment by ocefpaf** [comment]
@jakirkham I am :+1: to this change, but let's wait for all those you cc'ed above to answer before merging this.

**Comment by jakirkham** [comment]
Added some xrefs to relate this to other PRs and this move in the OP.

**Comment by jakirkham** [comment]
That's fine. I'd like to see this go into `conda-smithy` before we worry about it here. Just making sure we are doing the last bit of the transfer here.

**Comment by pelson** [comment]
:-1: on the name. Other than that, :+1: to moving away from pelson/obvious-ci.

**Comment by jakirkham** [comment]
> :-1: on the name.

Added an issue ( https://github.com/conda-forge/docker-images/issues/8 ) here for that.

> Other than that, :+1: to moving away from pelson/obvious-ci.

Awesome. Let's sort out the name and we can figure this out after.

**Comment by jakirkham** [comment]
The image is going to be renamed. ( https://github.com/conda-forge/docker-images/pull/9 ) Added the new proposed name here just so that we have it updated. As we haven't changed it in the org repo yet, it is failing. Will update once that has changed.

**Comment by pelson** [comment]
I'm :+1: on merging this once the image is available. No need to wait on me once this is passing the circle CI.

**Pull request merged**
