### PR TITLE
added r-pamr

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**

### CODE REVIEW

**Comment by cbrueffer** [comment]
in bioconda

**Comment by MathiasHaudgaard** [comment]
I thought that every cran package on bioconda should be moved to conda-forge. Have I misunderstood something?

**Comment by cbrueffer** [comment]
I don't know, was there a discussion about it? I don't necessarily object, I was just surprised :-) 

That said, thanks adding all those R packages, makes my life much easier!

**Comment by MathiasHaudgaard** [comment]
no problem :-) 
@bgruening is it correct that every cran package on bioconda should be moved to conda-forge? 
I just want to be sure :-)

**Comment by bgruening** [comment]
Discussing this right now. It is not that easy. All non bio-related packages should be moved to conda-forge. Problem is probably how this is defined and how you can you determine this in an automatic way.

Please fix your maintainers (capital start letter?) and the `home:` URL is often missing.

**Comment by MathiasHaudgaard** [comment]
hmm, weird.. I thought I'd fix that. I'll fix that asap :-)
About the home url. What if it isn't specified?
Our code only cleans the conda skeleton cran recipe for comments empty lines and adds maintainers.
So we don't remove the home url.

**Comment by bgruening** [comment]
I think, but please test it, it follows always this pattern: https://cran.r-project.org/web/packages/pamr/index.html

So you could even use the template for it.

**Comment by MathiasHaudgaard** [comment]
So it seems like conda skeleton cran does not always include the home url. I don't know what causes this. I'll just update manually :-)

**Comment by bgruening** [comment]
@MathiasHaudgaard there are a lot of packages with a broken URL :(

**Pull request merged**
