### PR TITLE
add smina

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge/bioconda-recipes:

I am bringing this recipe here for the following reasons:

* Package at bioconda repackages the sourceforge binaries, so there's no provenance
* It's from 2017
* I want to use the tooling at conda-forge for multiarch builds
* I am planning on adding more packages that will depend on smina

Thanks!

**Comment by jaimergp** [comment]
@conda-forge/bioconda-recipes, @conda-forge/help-c-cpp, this is ready for review. See previous [comment](https://github.com/conda-forge/staged-recipes/pull/13793#issuecomment-767767588) for the rationale of this submission.

Some details:

* Official source exists at Sourceforge, which is git based, but doesn't offer a permalink for tarballs. Cloning the repo doesn't work on Windows for some reason. So I mirrored it to my GitHub profile and tagged it accordingly.
* The CMake config needed some tweaks to support Windows.
*  I overrode the `version.cpp` autogeneration so it uses metadata from the recipe, instead of the (non-existing) git data.

**Comment by simonbray** [comment]
Moving this from bioconda seems like a good idea to me. :+1: Don't know if you have any other view @bgruening?

> Official source exists at Sourceforge, which is git based, but doesn't offer a permalink for tarballs.

It seems sourceforge does allows download of a 'snapshot'. For example, the latest revision can be accessed as a ZIP file via https://sourceforge.net/code-snapshots/git/s/sm/smina/code.git/smina-code-cbf423575b585a296171e3ee916d2d0f0d5dfb0a.zip.

**Comment by jaimergp** [comment]
> It seems sourceforge does allows download of a 'snapshot'.

They do, but it "expires" 🤯 See this [log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=269980&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=1025). You have to ask first in the `/tarball` endpoint, which is a dynamic piece of HTML that cannot be checksum'd. I tried the most creative workarounds (low-key [proud of this one](https://github.com/conda-forge/staged-recipes/blob/1c8ce1d318fa8be6278a61c0db4ecba595ab0ccd/recipes/smina/meta.yaml#L9-L15)), but I concluded it created more problems than solved. So I decided to just mirror as needed. It's not that the repo has a huge traffic anyway.

**Comment by simonbray** [comment]
Ah ok, it seems you already investigated this quite thoroughly. :laughing: Then I agree that the GitHub mirror is the best solution.

**Review by chrisburr — APPROVED** [review]
Looks good 👍

Is there anything that needs to be done by @conda-forge/bioconda-recipes before it's merged?

**Comment by simonbray** [comment]
> Is there anything that needs to be done by @conda-forge/bioconda-recipes before it's merged?

I created a PR to remove smina from the bioconda-recipes repo here: https://github.com/bioconda/bioconda-recipes/pull/26483. However, it's fine for this PR to be merged already.

**Comment by jaimergp** [comment]
Thanks @chrisburr and @simonbray!

**Pull request merged**
