### PR TITLE
Added recipe for pep8

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Background for those coming to this for the first time; the package `pep8` was [recently renamed](httphttps://github.com/PyCQA/pycodestyle/issues/466) to `pycodestyle`.

My only question is if this should be its own package or a branch of the pycodestyle feedstock?  

Typically feedstock branchs are used to support older versions or different configuration of a package, should this workflow also be used for renamed packages?

Both packages have entries on PyPI, [pep8](https://pypi.python.org/pypi/pep8) and [pycodestyle](https://pypi.python.org/pypi/pycodestyle/2.0.0), so these might be seen as seperate packages.  It does look like some care has been taken on the versioning of the two so that they do not conflict.  Additionally, using a single feedstock to build both packages may be confusing as the package name in the pep8 recipe would not match the feedstock name.

Personally my vote is for two feedstocks, the already existing pycodestyle feedstock and a new pep8 feedstock, but I would like to see what opinion other have before proceeding.

**Comment by pmlandwehr** [comment]
> Personally my vote is for two feedstocks, the already existing pycodestyle feedstock and a new pep8 feedstock, but I would like to see what opinion other have before proceeding.

I would agree, but I have to admit to being pretty new to conda-forge norms here. Certainly there are still packages out there, like `autopep8`, that depend on the old labeling convention.

**Comment by jakirkham** [comment]
Two feedstocks SGTM too. 👍

**Comment by jjhelmus** [comment]
Three vote for two feedstocks is enough for me, merging.  Thanks for getting this and pycodestyle in @pmlandwehr!

**Pull request merged**
