### PR TITLE
PR: Add package jupyterlab-language-pack-ar-SA

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by goanpeca** [comment]
@blink1073, @fcollonval, @krassowski do you agree to be added as maintainers?

Thanks!

**Comment by blink1073** [comment]
👍🏼

**Comment by krassowski** [comment]
+1 to all language packs

**Comment by fcollonval** [comment]
I agree

**Comment by dbast** [comment]
As upstream is onboard here: Wouldn't it be easier to tag a release in the upstream repo and the package that (instead of the individual files from pypi) via a one single multi-output/jinja2-equiped recipe/feedstock into individual conda packages? All those language packs seem to be pretty much similar regarding dependencies and other meta-data and updating once recipe over time should be easier compared to keep multiple of those in sync. Just thinking... or is there anything preventing that?

**Comment by goanpeca** [comment]
Will try that @dbast 

Thanks for the suggestion!

**Comment by fcollonval** [comment]
At @dbast, thanks for the suggestion. I have one question regarding the multi-packages approach. Is the bot able to update the recipe if only one source on Pypi gets updated?  
The scenario here is that one language package may need to be updated due to new translated strings being added independently.

**Comment by dbast** [comment]
@fcollonval One source definition + multiple outputs recipes are bot-updatable ... that can e.g. be seen here https://github.com/conda-forge/airflow-feedstock/blob/master/recipe/meta.yaml ... and the previous merged PRs: https://github.com/conda-forge/airflow-feedstock/pulls?q=is%3Apr+is%3Aclosed

**Comment by goanpeca** [comment]
Thanks for the info @dbast just checking, so a single release tag (on github) on the single source would trigger the bot?

**Comment by dbast** [comment]
yes. that is my understanding.

Additional to that airflow multi output recipe a jinja2 loop could be potentially used to generate all outputs dynamically based on the 27 languages.

**Pull request closed without merging**
