### PR TITLE
Added recipe for vine

### PR DESCRIPTION
**Pull request by pmlandwehr**
Needed for the latest version of `amqp` (ref. https://github.com/conda-forge/amqp-feedstock/pull/9)

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @pmlandwehr.

**Comment by pmlandwehr** [comment]
An odd rider to this - on anaconda.org, the `vine` package is being list as having been uploaded a month ago. (Ref. https://anaconda.org/conda-forge/vine/files)  This seems abnormal and wrong.

**Comment by jakirkham** [comment]
Oops, yeah, appears there already was a feedstock. Sorry I missed that. :man_facepalming:

Go ahead and submit a PR to that feedstock to update it and add yourself.

**Comment by jakirkham** [comment]
Did you ever end up adding yourself as a maintainer on that feedstock, @pmlandwehr? Do you still want to be a maintainer of `vine`?

**Comment by pmlandwehr** [comment]
Honestly, at this point I don't remember why I was concerned about `vine`; I've probably been building too many packages. Better I stay out of it.

**Pull request merged**
