### PR TITLE
Add recipe for the yarn api client package

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Looks good to me! Waiting the CI to finish

**Comment by marcelotrevisani** [comment]
Thanks for your effort to put this in ``conda-forge`!  :)

**Comment by kevin-bates** [comment]
@ericdill - thank you for your help on this.  @toidi is the author of yarn-api-client, but his Id isn't expanding and since yarn-api-client appears to be rather stale, it probably makes sense to add @lresende and myself as maintainers.  @liukun1016 isn't working on EG these days, so I'll let him request explicitly.

**Comment by toidi** [comment]
I've used corporate email for `yarn-api-client` project on pypi. Now I don't have an access to that mail box and thus don't have a control over `https://pypi.org/project/yarn-api-client/`.

If possible, use another YARN API client.

Tried to contact PyPI admin several times about that concern with no luck.

**Comment by kevin-bates** [comment]
@toidi - thank you for the response.  Which other YARN API client would you recommend?

**Comment by toidi** [comment]
I'll try to restore access to the package https://github.com/pypa/warehouse/issues/4637 .
But don't expect much from it.
I can receive/accept pull request, but can't afford contributions to the project.

And unfortunately I have nothing to suggest you for a replacement, nowadays do not work with yarn.

**Comment by toidi** [comment]
@kevin-bates @ericdill by the way, I restored access to package and uploaded new version.

**Comment by lresende** [comment]
@toidi Great, btw we would love to collaborate and contribute to the package. I have started some updates to the API [here](https://github.com/lresende/yarn-client/commits/master) but sort of stopped as we thought you were not interested/maintaining it anymore. Maybe you could include me and Kevin as collaborators to the repo and also PyPi ?

**Comment by toidi** [comment]
Sure thing,

You look like legit contributors :)
Added to collaborators in github repo.

What are your pypi user names?

**Comment by lresende** [comment]
Thank you.  
For Pypi: lresende and kevin-bates

**Comment by toidi** [comment]
done 👍

**Pull request merged**
