### PR TITLE
Fix for #7163 Moved recipes to their correct location

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Fixes #7163 

These recipes were not in the recipes directory and thus didn't get built

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
cc @chrisburr @SylvainCorlay @msarahan

**Comment by SylvainCorlay** [comment]
I want to reiterate my reservations about this. I would be in favor of not vendoring clangdev and cling in a recipe. We have gone through a lot of iterations and effort to enable variants of clangdev and llvm to prevent this, and I would prefer this not to be discarded.

I would be in favor of patching the sources in the recpe to depend on cling and not vendoring it.

**Comment by SylvainCorlay** [comment]
From my second comment in #7163 

@conda-forge/core please take the message above into consideration. We have put a lot of work into the proper packaging of the interpreted c++ stack (and we maintain over 100 feedstocks).

**Comment by mariusvniekerk** [comment]
@SylvainCorlay i've added you as a collaborator to this recipe.

**Comment by msarahan** [comment]
@SylvainCorlay you're not wrong.  If people use root and cling together, I expect it will break.  That's pain that @chrisburr is responsible for, and since he's the root package maintainer, I expect him to work to monitor and address it.  However, I don't believe @chrisburr should have to fix his cling patches to work with yours if root just isn't going to interact with your cling stuff at all.  That's more of a "would be nice."  As was discussed at https://github.com/conda-forge/staged-recipes/pull/7163#issuecomment-450173479 there are good reasons to have this as it is and work on improving the situation in the future.

**Comment by chrisburr** [comment]
This should probably be closed in favour of #7414 as that also includes some other changes that were missing from the original PR (most importantly fixing XRootD for the macOS 10.9 SDK and disabling ROOT for macOS as it still crashes too often).

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay you're not wrong. If people use root and cling together, I expect it will break. That's pain that @chrisburr is responsible for, and since he's the root package maintainer, I expect him to work to monitor and address it. However, I don't believe @chrisburr should have to fix his cling patches to work with yours if root just isn't going to interact with your cling stuff at all. That's more of a "would be nice." As was discussed at #7163 (comment) there are good reasons to have this as it is and work on improving the situation in the future.

- clangdev patches should be the same in both cling and ROOT.
- I don't think that there is any real obstacle for root to build against an external cling. I think that this is an issue to bring with upstream, even if it takes a while, which I am fine with.

As a side note, ROOT also forcibly disables the export of symbols in its binaries so that you can't link with it unless you are part of the ROOT build system, so it is impossible to build upon cling or any other part if kept in the monolithic ROOT package.

**Pull request closed without merging**
