### PR TITLE
Add ultralytics package

### PR DESCRIPTION
**Pull request by abraha2d**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] ~~If static libraries are linked in, the license of the static library is packaged.~~
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by abraha2d** [comment]
@conda-forge-admin please rerender

**Comment by abraha2d** [comment]
Blocked by getting `thop` onto conda-forge, which is blocked by https://github.com/Lyken17/pytorch-OpCounter/issues/203.

**Comment by abraha2d** [comment]
`ultralytics 8.0.104` removes the dependency on `thop`, which unblocks this PR.

**Comment by abraha2d** [comment]
Windows build is failing due to missing `pytorch` packages (see https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32).
Ignoring as this is a `noarch` package, similar situation to https://github.com/conda-forge/staged-recipes/pull/15917#pullrequestreview-737613735

**Comment by glenn-jocher** [comment]
Hi! Yes I confirm that I'm willing to be a maintainer for the ultralytics conda package.

@ayushexel please confirm as well

**Comment by AyushExel** [comment]
I confirm that I'm willing to be a maintainer of ultralytics package

**Comment by Laughing-q** [comment]
@abraha2d I confirm that I'm willing to be a maintainer of ultralytics package.

**Comment by abraha2d** [comment]
@conda-forge/help-python ready for review!

**Comment by glenn-jocher** [comment]
@conda-forge-admin this PR for Ultralytics YOLOv8 is all ready to merge!

**Comment by glenn-jocher** [comment]
@conda-forge/staged-recipes hi, this PR for Ultralytics YOLOv8 (https://github.com/ultralytics/ultralytics) is ready for review and merge. 

Let us know if there are any changes required and we will implement them rapidly. Thank you!

**Pull request merged**
