### PR TITLE
Add pyslim recipe

### PR DESCRIPTION
**Pull request by winni2k**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by winni2k** [comment]
@conda-forge-admin, please ping team @conda-forge/bioconda-recipes

**Comment by winni2k** [comment]
I am attempting to move the pyslim recipe from bioconda to conda-forge. I have been asked by the package pyslim maintainer to do this because pyslim is part of a larger set of packages that are all on conda-forge, and this simplifies maintenance.

See https://github.com/tskit-dev/pyslim/issues/10#issuecomment-636300825 for reference.

**Comment by winni2k** [comment]
Staged-recipes team, do I need to be put in touch with the bioconda-recipes team for this?

**Comment by bgruening** [comment]
:+1: from the bioconda side. @winni2k please let us know if you need help removing the package from bioconda.

**Comment by npavlovikj** [comment]
@winni2k , can you please try rebasing with master and a force push? CF is not using Circle CI anymore, but looks like your branch still has the configuration for it. Otherwise, the recipe LGTM, so we can merge it after you try rebasing.

**Comment by winni2k** [comment]
@npavlovikj Looks like all tests passed.

**Comment by npavlovikj** [comment]
Great @winni2k , thank you for contributing 🎉

**Pull request merged**
