### PR TITLE
Adding metadsl recipe

### PR DESCRIPTION
**Pull request by xmnlab**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xmnlab** [comment]
@saulshanabrook I have started to play with metadsl in my freet time, and I would like to add it to conda-forge. I am adding you as maintainer, is it ok for you?

**Comment by saulshanabrook** [comment]
Sorry it wasn't tagged properly, but this was the last release: https://github.com/Quansight-Labs/metadsl/commit/4719a02b4b5455938c4740f369fca90b1941a850

It's a monorepo, so does this mean we should have 5 conda forge packages? `typez`, `metadsl` `metadsl_core`, `metadsl_llvm` `metadsl_visualize`?

**Comment by xmnlab** [comment]
I will add more import tests and create build files for each sub-package

**Comment by xmnlab** [comment]
windows job:

> Starting: Build recipe (maybe vs2008)
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\ea2d0508-4e0b-4bd2-b90d-6203b65008d0.cmd""
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING conda_build.config:arch(290): Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING conda_build.config:platform(304): Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Building metadsl with conda-forge/label/main
rendering D:\a\1\s\recipes\metadsl for win-64
Computed that there are 0 distributions to build from 1 recipes
Nothing to do
Finishing: Build recipe (maybe vs2008)

**Comment by xmnlab** [comment]
@saulshanabrook this recipe worked locally in my machine (linux) with success!
for some reason, CI is not building that. I am checking why ...

**Comment by xmnlab** [comment]
@scopatz do you any idea about this problem? thanks!

**Comment by xmnlab** [comment]
it seems it is related to the python version 
`python                    3.7.6           h8356626_5_cpython    conda-forge`

**Comment by xmnlab** [comment]
as it is working locally I am changing it to `ready` ... but I am still need to figure out why it is not working on CI

**Comment by xmnlab** [comment]
using noarch and pinning python >= 3.8 for host and run (metapackage and outputs) raise this error:

```
rendering /home/conda/conda-recipes/metadsl for linux-64
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING conda_build.config:arch(290): Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING conda_build.config:platform(304): Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
rendering /home/conda/conda-recipes/metadsl/meta.yaml for linux-64
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 133, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 66, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 107, in build_folders
    order = list(nx.topological_sort(G))
  File "/opt/conda/lib/python3.7/site-packages/networkx/algorithms/dag.py", line 208, in topological_sort
    raise nx.NetworkXUnfeasible("Graph contains a cycle or graph changed "
networkx.exception.NetworkXUnfeasible: Graph contains a cycle or graph changed during iteration

```

**Comment by xmnlab** [comment]
finally green! it is ready for review! thanks!

**Comment by xmnlab** [comment]
@conda-forge/help-python it is ready for review. thanks!!

**Pull request merged**
