### PR TITLE
Openmesh

### PR DESCRIPTION
**Pull request by ivoflipse**
Here's a first shot at making a package for OpenMesh. We've had some problems with building 5.2 on Windows, so hopefully they fixed some of those issues in 6.0.

### CODE REVIEW

**Comment by ivoflipse** [comment]
So Travis doesn't like our build.sh (obviously), because there are no instructions for Darwin. Any suggestions on how it should be changed?

**Comment by ivoflipse** [comment]
For Windows everything works fine for 2.7, but for 3.4 (and up) there's a failure:

```
C:\Miniconda\conda-bld\work\build>cmake --build . --clean-first --target ALL_BUILD --config Release 
Microsoft (R) Build Engine version 4.6.1055.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.
 
Building the projects in this solution one at a time. 
To enable parallel build, please add the "/m" switch.

Build started 5/4/2016 3:33:20 AM.
Project "C:\Miniconda\conda-bld\work\build\OpenMesh.sln" on node 1 (Clean target(s)).
C:\Miniconda\conda-bld\work\build\OpenMesh.sln.metaproj : error MSB4126: 
The specified solution configuration "Release|x64" is invalid. 
Please specify a valid solution configuration using the Configuration and Platform properties 
(e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") 
or leave those properties blank to use the default solution configuration. 
[C:\Miniconda\conda-bld\work\build\OpenMesh.sln]
Done Building Project "C:\Miniconda\conda-bld\work\build\OpenMesh.sln" (Clean target(s)) 
-- FAILED.
 
Build FAILED.
```

I'm not sure what's exactly going wrong here.

**Comment by jschueller** [comment]
@ivoflipse, in the build.sh I managed to mutualize the call to cmake and get rid of the python detection like this (in-progress):
https://github.com/jschueller/staged-recipes/blob/openturns/recipes/openturns/build.sh

**Comment by ocefpaf** [comment]
@ivoflipse I am just curious does open mesh has python bindings? (I am very interested in mesh decimation.)

**Comment by ivoflipse** [comment]
@ocefpaf It does indeed, though clearly its not the main attraction: http://www.openmesh.org/media/Documentations/OpenMesh-6.0-Documentation/a00036.html

I'm going to contact the devs and see if they want to help out with the recipe

**Comment by ocefpaf** [comment]
> @ocefpaf It does indeed, though clearly its not the main attraction

Thanks! I need to find some time to take a better look into it. It sounds **very** useful. (Ping @rsignell-usgs)

**Comment by ivoflipse** [comment]
For some reason its no longer building on AppVeyor, did I break something unexpectedly?

**Comment by ocefpaf** [comment]
> For some reason its no longer building on AppVeyor, did I break something unexpectedly?

That happens sometimes. I closed and opened in an attempt to re-start AppVeyor, but that did not work :unamused: 

Try pushing another commit to see if you can get AppVeyor to start.

**Comment by jakirkham** [comment]
Sometimes webhooks to AppVeyor fail. I have no idea why, but they do happen sometimes. There were a few failures recently. In these cases, I think it is almost best to ignore the failure on that end. Unless, of course, we really have everything else working and need to test AppVeyor. If this is the case, I have had some luck restarting the build on the AppVeyor end (e.g rebuild PR or similar).

**Comment by ivoflipse** [comment]
Well, I'm hoping to get some input from OpenMesh guys to troubleshoot what's going wrong with the Windows Python bindings and obviously 2.7 remains a nuisance, but thanks for the heads up!

**Comment by jakirkham** [comment]
I have restarted AppVeyor so it will build the latest of this PR (via their interface). However, the webhook may fail again. So, just ping us when you are done making changes and we can do this again.

**Comment by Maxyme** [comment]
@ocefpaf there is an openmesh package for linux here if you are interested in using it:
https://anaconda.org/clinicalgraphics/openmesh/files

**Comment by ocefpaf** [comment]
> @ocefpaf there is an openmeshconda package for linux here with python bindings

Thanks @Maxyme!

**Comment by xantares** [comment]
@jakirkham please close this

**Comment by jakirkham** [comment]
Sure. Closed. Guessing you already took what you could from here.

**Pull request closed without merging**
