### PR TITLE
package blist

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Another dependency of #11160. It's an old package, but seems to be installable on python 3.6+, otherwise [ray](https://github.com/ray-project/ray/blob/master/python/setup.py#L79) wouldn't be able to build their package.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@DanielStutzbach It's probably pointless to ask after the repo hasn't seen activity in so long, but if you want, you're most welcome to participate in maintaining the conda recipe for `blist`.

It would be nice if you could confirm my interpretation that the license corresponds to `BSD-3-Clause`.

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes 

I actually regexed through all the `#if`/ `#endif` pairs in `_blist.c`, but I cannot find anything wrong, and don't understand why windows complains about it:
```
blist/_blist.c(7743): fatal error C1070: mismatched #if/#endif pair in file 'c:\users\vssadministrator\appdata\local\temp\pip-req-build-8w134zjm\blist\_blist.c'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
```

**Comment by h-vetinari** [comment]
@conda-forge/core: any experience with [failing](https://github.com/conda-forge/staged-recipes/pull/11163#issuecomment-605722006) `#if` / `#endif` pairs on MVSC (that are false negatives)?

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes 
I saw that since very recently, the standard feedstock rerendering now uses `vs2017` for windows. Since I cannot rerender in `staged-recipes`, how can I force to build with `vs2017` here?

**Comment by isuruf** [comment]
Can you rebase on master?

**Comment by h-vetinari** [comment]
@isuruf:
Rebased, but appveyor still says:
`error: command 'cl.exe' failed: No such file or directory`

On azure, the package builds for python 3.6, but fails on 3.7:
`blist/_blist.c(7742): fatal error C1070: mismatched #if/#endif pair in file 'c:\users\vssadministrator\appdata\local\temp\pip-req-build-jn69n65s\blist\_blist.c'`

**Comment by h-vetinari** [comment]
@isuruf, I cracked that problems somehow. :)

**Pull request merged**
