### PR TITLE
Add R package gifski

### PR DESCRIPTION
**Pull request by philip-khor**
Retrying #7542 

Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by philip-khor** [comment]
@conda-forge/r this PR is ready for review/merge

**Comment by dpryan79** [comment]
You'll want to ping @conda-forge/help-r, since they're the ones that can merge here :)

**Comment by philip-khor** [comment]
will do @dpryan79, thanks for the heads-up!

**Comment by dbast** [comment]
MIT is a combined License... updated the PR according to https://github.com/conda/conda-build/pull/3616

**Comment by dbast** [comment]
Thx @philip-khor

**Pull request merged**
