### PR TITLE
Remove feedstocked recipes

### PR DESCRIPTION
**Pull request by jakirkham**
This removes several recipes that appear to have generated feedstocks correctly ( cmd2, debtcollector, elasticsearch-dsl, jsonpointer, keystoneauth1, nosexcover, python-mimeparse, rfc3986 ).

xref: https://github.com/conda-forge/staged-recipes/issues/900

cc @msarahan @ocefpaf

### CODE REVIEW

**Comment by jakirkham** [comment]
This should at least simplify the problem we are looking at. Sometimes having a large number of things to feedstock at once is part of the problem itself.

**Comment by jakirkham** [comment]
Seems there are a few more that have cleared and seem to have generated fully functional feedstocks. Have removed them here as well.

**Comment by jakirkham** [comment]
@ocefpaf, do you have any opposition if I merge this?

**Comment by ocefpaf** [comment]
> @ocefpaf, do you have any opposition if I merge this?

Since the feedstocks were created you won't harm the users who sent those recipes. However, if the issue is pertinent to any of those and/or a combination of factors, you will mask it instead of find it.  Either way I cannot look at this issue right now and Travis-CI will be down for a few days for maintenance.

So if you think you have to, go ahead. I would wait for Travis-CI to be fully back online though.

**Comment by jakirkham** [comment]
My suspicion is one of two things is happening.

1. Issues re-registering existing feedstocks with Travis CI.
2. Suffering from Travis CI API issues that @isuruf has pointed out.

If it is 1, this may very well fix the whole problem (or mask it depending on your perspective). If it is 2, removing these won't hide it. Now there may very well be a 3rd possibility that we don't understand like you suggest (though this could overlap or be the same as 1). However, picking these issues apart is slow, tricky, and unpleasant (both for us and those affected). I'm willing to punt on this likely infrequent issue (if it isn't one of the first two) in order to get things moving here again.

In the long, run I think we will want to restructure feedstock generation so that it goes through the whole process with one feedstock and removes it immediately (including pushing the change). Having to manually clear like this periodically is undesirable IMHO. It is also entangles what is wrong making things a bit hazy. It will also eliminate (or significantly reduce the possibility of) 1 happening as it won't generally be needed.

Regarding Travis CI being down. Linux container builds are working and the API is operational. Yes, it may sit a bit behind existing Mac builds in our queue. However, I don't see the difference between merging now and waiting in the queue vs waiting and merging when the queue is cleared (or moving again).

**Comment by RSully** [comment]
> In the long, run I think we will want to restructure feedstock generation so that it goes through the whole process with one feedstock and removes it immediately (including pushing the change). Having to manually clear like this periodically is undesirable IMHO.

:+1:

**Comment by jakirkham** [comment]
Thanks for the support @RSully. I'll try to put it in a proper issue so we remember. 😄

**Comment by jakirkham** [comment]
See this issue ( https://github.com/conda-forge/staged-recipes/issues/915 ) for restructuring feedstock generation process.

**Pull request merged**
