### PR TITLE
package fairscale

### PR DESCRIPTION
**Pull request by h-vetinari**
Necessary for https://github.com/conda-forge/allennlp-feedstock/pull/30

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes
There seems to be a problem with the docker-images:
```
Unable to find image 'quay.io/condaforge/linux-anvil-comp7:latest' locally
docker: Error response from daemon: Get "https://quay.io/v2/": dial tcp: lookup quay.io: No address associated with hostname.
```

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes 
The centos7 build didn't trigger - how can I ensure that it does? Also, is there a way to run the GPU job with glibc 2.17 as well? Pytorch >=1.8 needs it.

**Comment by h-vetinari** [comment]
This now hangs indefinitely also on linux...

Hey @anj-s @blefaudeux @min-xu-ai, I originally wanted to ping you if you want to join as co-maintainers of the conda-forge feedstock once everything builds fine, but I'm a bit stuck with the hangs in the test suite right now (even though the imports work out), so checking in a bit earlier 😋 

The idea is to make fairscale installable through conda-forge (e.g. it is now a dependency of allennlp, see OP), and for ABI-, stability- and other reasons, all dependencies need to be packaged by conda-forge. I'm already doing this for a bunch of packages, including another one from facebookresearch: [faiss](https://github.com/conda-forge/faiss-split-feedstock)

Let me know if you have any question what maintainership entails (generally not much once things are up and running...)

**Comment by blefaudeux** [comment]
> This now hangs indefinitely also on linux...

it's a build issue on the pure CUDA extention that we have, the fused adam optim. I think that it could be left out if that helps, else it might be a cuda toolchain problem (nvcc and the like ?) https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=384870&view=logs&j=232b7f5e-8d64-5438-fada-8478f379d226&t=e8516d7e-1153-5090-5807-53ae833fddd8

**Comment by anj-s** [comment]
Thank you for taking on @h-vetinari! Let us know what we need to do to maintain this build. 
If you do end up leaving the cuda extension would there be a way for users to optionally install it. I know we have existing users who use the fused adam optimizer that is part of FairScale.

**Comment by h-vetinari** [comment]
Hey @blefaudeux @anj-s, thanks for chiming in! :)

I think we could leave out the CUDA extensions for the first go, and add them later. As Benjamin mentioned, the CUDA builds fail already during compilation, but I was more thinking about the CPU-only test suite that seems to hang on linux (and osx, which I had disabled already).

Unfortunately, there's not GPU hardware in the conda-forge CI, so that's one possible failure mode. We also don't _have to_ run the test suite as part of the CI (as I mentioned, the imports work fine), but I consider it best practice and would like to keep it if possible.

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes, this is blocking to build new allennlp-versions. Would be good to merge this, and I'll fix the GPU builds etc. on the feedstock.

**Comment by h-vetinari** [comment]
> 
> 
> @conda-forge/staged-recipes, this is blocking to build new allennlp-versions. Would be good to merge this, and I'll fix the GPU builds etc. on the feedstock.

Can someone please merge this? 🙃

**Comment by h-vetinari** [comment]
Thanks @chrisburr! :)

@blefaudeux @anj-s

I opened up two PRs to follow up re-enabling the test suite (https://github.com/conda-forge/fairscale-feedstock/pull/1) as well as GPU builds (https://github.com/conda-forge/fairscale-feedstock/pull/2) - I'd be very happy to have your support on either or both. :)

**Pull request merged**
