### PR TITLE
Added recipe for Theano

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
One potential issue here is that this install makes no provision for using BLAS or OpenBLAS [(ref)](https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/13973/a-few-tips-to-install-theano-on-windows-64-bits), which might be an issue for windows. Given that `conda` now installs a bunch of OpenBLAS versions of modules this might be solved, but it'll depend how it builds.

**Comment by jakirkham** [comment]
FYI there is already a PR for theano in progress. Please see this PR ( https://github.com/conda-forge/staged-recipes/pull/574 ). It would be better to consolidate our efforts on that one as it is further along.

**Comment by pmlandwehr** [comment]
woops! didn't see it when I searched. Closing...

**Comment by jakirkham** [comment]
No worries. Though I would appreciate your thoughts on it as you seem interested and eager to get something moving. 😄

We should discuss what we want to do with the BLAS and compiler situation. Regarding CUDA and cuDNN, Continuum is already in contact with NVIDIA regarding what is ok to do here. Though `theano` is less affected by these as it builds support for these features at run-time.

**Pull request closed without merging**
