### PR TITLE
Add ezc3d package

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by melund** [comment]
Thanks, @beckermr. I have made the changes you suggested.

**Comment by melund** [comment]
@beckermr It seems the error on travis is now different:

```
-- Found Python3: /Users/travis/miniconda/bin/python3.7 (found version "3.7.1") found components:  Interpreter Development 
-- Could NOT find NUMPY (missing: NUMPY_INCLUDES) 
CMake Error at modules/FindNumpy.cmake:122 (message):
  Could not find NUMPY!
```

Any tips for fixing this?

**Comment by beckermr** [comment]
This is a thing with the build system of the package. I am not very familiar with cmake. Let's ping the rest of the team to see if they have suggestions.

@conda-forge/staged-recipes Can one of y'all help with this build error?

**Comment by scopatz** [comment]
You might need to set the `NUMPY_INCLUDES` environment variable to `$PREFIX/path/to/numpy` on mac...

**Comment by melund** [comment]
@scopatz advice got it a little further. But I don't think the original creators have built ezc3d for Mac. So I will just skip this platform for now. 

Just for reference. I get the following error now: 
```
Undefined symbols for architecture x86_64:
  "_PyArg_ParseTuple", referenced from:
      _wrap_delete_SwigPyIterator(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_value(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_incr(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_decr(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_distance(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_equal(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_copy(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      ...
      ...
  "__Py_NotImplementedStruct", referenced from:
      _wrap_SwigPyIterator___sub__(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_ostream___lshift__(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      _wrap_istream___rshift__(_object*, _object*) in ezc3d_pythonPYTHON_wrap.cxx.o
      SwigPyObject_richcompare(SwigPyObject*, SwigPyObject*, int) in ezc3d_pythonPYTHON_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [binding/python3/_ezc3d.so] Error 1
make[1]: *** [binding/python3/CMakeFiles/_ezc3d.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File ".ci_support/build_all.py", line 134, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, old_comp_folders, arch, channel_urls)
  File ".ci_support/build_all.py", line 124, in build_folders
    conda_build.api.build(list(d.keys()), config=get_config(arch, channel_urls))
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2311, in build_tree
    notest=notest,
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda/conda-bld/ezc3d_1546846572879/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by melund** [comment]
@beckermr This is ready now :)

**Pull request merged**
