### PR TITLE
added r-sm

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks for the recipe, @MathiasHaudgaard! Unfortunately you had some bad timing. We released the fix to the problem you are having (#4320) 57 minutes ago, and you submitted your PR an hour ago!

**Comment by jdblischak** [comment]
@ocefpaf Could you please restart this CircleCI build?

**Comment by bgruening** [comment]
restarted

**Comment by jdblischak** [comment]
The [CircleCI build](https://circleci.com/gh/conda-forge/staged-recipes/21382?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) failed again because it still tried to build with R 3.4.2. Not clear how that is possible.

**Comment by jdblischak** [comment]
@MathiasHaudgaard I noticed you closed this PR and multiple others. There was a technical issue blocking R recipes that finally was resolved this week. In other words, the problem was not with your recipes. Please feel free to re-open your old PRs or create new ones.

And if you'd ever like to trigger CI re-builds yourself, you could amend your commit and then force push to your branch. Please let me know if you have any questions about how to proceed.

**Pull request closed without merging**
