### PR TITLE
Add recipe for libmatio-cpp

### PR DESCRIPTION
**Pull request by traversaro**
Add recipe for [matio-cpp](https://github.com/ami-iit/matio-cpp).

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
Windows build fails with:
~~~
[32/35] Building CXX object test\CMakeFiles\ExogenousConversionsUnitTests.dir\ExogenousConversionsUnitTest.cpp.obj
FAILED: test/CMakeFiles/ExogenousConversionsUnitTests.dir/ExogenousConversionsUnitTest.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\cl.exe  /nologo /TP -DCATCH_CONFIG_DISABLE_MATCHERS -DCATCH_CONFIG_FAST_COMPILE -I%SRC_DIR%\build\test -I%SRC_DIR%\include -I%SRC_DIR%\build\Autogenerated -I%PREFIX%\Library\include -I%PREFIX%\Library\include\eigen3 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fotest\CMakeFiles\ExogenousConversionsUnitTests.dir\ExogenousConversionsUnitTest.cpp.obj /Fdtest\CMakeFiles\ExogenousConversionsUnitTests.dir\ /FS -c %SRC_DIR%\test\ExogenousConversionsUnitTest.cpp
%SRC_DIR%\test\ExogenousConversionsUnitTest.cpp(243): error C2672: 'matioCpp::make_cell_array': no matching overloaded function found
%SRC_DIR%\test\ExogenousConversionsUnitTest.cpp(243): error C2783: 'matioCpp::CellArray matioCpp::make_cell_array(const std::string &,const iterator &,const iterator &)': could not deduce template argument for '__formal'
%SRC_DIR%\include\matioCpp/ExogenousConversions.h(111): note: see declaration of 'matioCpp::make_cell_array'
%SRC_DIR%\test\ExogenousConversionsUnitTest.cpp(244): error C3536: 'toMatioCellFromSet': cannot be used before it is initialized
%SRC_DIR%\test\ExogenousConversionsUnitTest.cpp(244): error C2109: subscript requires array or pointer type
%SRC_DIR%\test\ExogenousConversionsUnitTest.cpp(245): error C2109: subscript requires array or pointer type
%SRC_DIR%\test\ExogenousConversionsUnitTest.cpp(246): error C2109: subscript requires array or pointer type
[33/35] Building CXX object test\CMakeFiles\StructArrayElementUnitTests.dir\StructArrayElementUnitTest.cpp.obj
ninja: build stopped: subcommand failed.
~~~

**Comment by traversaro** [comment]
Switching to VS2019 solved the build problem. Given https://github.com/conda-forge/conda-forge.github.io/pull/1810, I do not think it is particularly problematic to use VS2019.

**Comment by traversaro** [comment]
@conda-forge/help-c-cpp The recipe is ready for review.

**Review by h-vetinari — CHANGES_REQUESTED** [review]
Can we name this `libmatio`, see https://github.com/conda-forge/conda-forge.github.io/issues/1073?.

I'm (re)starting to work through some of the `xyz-cpp` -> `libxyz` renames, but at least we could avoid adding new ones...

I realize that this package is a bit special because it is _literally_ named `matio-cpp`, but we have other packages that diverge from their upstream (or PyPI) names as well and for the consistency of the `lib*` packages, I think this would be a good enough reason IMO. In this particular case, I'd say one could also consider `libmatiocpp`, as that's the (lower-cased) name of the `.so` produced on unix.

**Comment by traversaro** [comment]
The problem is that libmatio already exists (https://github.com/conda-forge/libmatio-feedstock) and is the C library for which this library provides an idiomatic C++ interface.

**Comment by h-vetinari** [comment]
> If you feel strongly about it, I can rename it `libmatiocpp`, even if I feel that it may be less intuitive for users, but that is ok.

First off, I'm just one opinion among (potentially) many. Just wanted to add my $0.02.

> Would `libmatio-cpp` be an option?

Given that there really is a distinction between the C & C++ libs, I'd say that's a perfectly fine choice. It also happens to match what LLVM does for `libclang` vs. `libclang-cpp`.

**Comment by traversaro** [comment]
I renamed the package `libmatio-cpp`.

**Pull request merged**
