### PR TITLE
add odm2 stack

### PR DESCRIPTION
**Pull request by ocefpaf**
@emiliom and @lsetiawan this PR adds the key recipes from the `ODM2` channel to `conda-forge`. I added you both as maintainers so you'll have access to the feedstock, please let me know if you want to add more odm2 folks here.

Once this is merged we should be able to switch from `odm2` to `conda-forge`.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The AppVeyor failure is unrelated to the PR, merging this.

**Comment by lsetiawan** [comment]
Thanks @ocefpaf! This looks great. :smile:

**Comment by emiliom** [comment]
Thanks @ocefpaf!

I assume conda forge will have ODM2 packages starting from current releases; and at the same time we can keep the ODM2 channel around for some time, "frozen", just to serve older releases (in case anyone actually has  dependencies)?

**Comment by ocefpaf** [comment]
> I assume conda forge will have ODM2 packages starting from current releases; and at the same time we can keep the ODM2 channel around for some time, "frozen", just to serve older releases (in case anyone actually has dependencies)?

Correct. We can add older version of the packages to `conda-forge` if we need LTS on them.

**Comment by emiliom** [comment]
> We can add older version of the packages to conda-forge if we need LTS on them.

Cool! We can decide on this on a case by case basis. But we'll try to avoid it.

**Pull request merged**
