### PR TITLE
add  r-nmf  r-pbkrtest  r-quantmod  r-rgl  r-rmarkdown  r-rstan  r-shinyjs  r-vars

### PR DESCRIPTION
**Pull request by bgruening**
xref: https://github.com/conda-forge/staged-recipes/issues/2009
ping @johanneskoester 

r-nmf
 r-pbkrtest
 r-quantmod
 r-rgl
 r-rmarkdown
 r-rstan
 r-shinyjs
 r-vars

### CODE REVIEW

**Comment by johanneskoester** [comment]
Looks like libglu is yours, right? I guess building on osx was not possible? Then, skipping is ok for now I guess.

**Comment by bgruening** [comment]
We needed libglu for BioConda at some point and I tried to get it running on OSX, but since I have no Mac I was not able to get it running :(.

**Comment by johanneskoester** [comment]
Ok, so let's skip it for now. @daler, would it be possible for you to have a look at [libglu-feedstock](https://github.com/conda-forge/libglu-feedstock) and see whether you can build it on your osx machine?

**Comment by bgruening** [comment]
@isuruf thanks for the merge!

**Comment by daler** [comment]
No immediately obvious fix, seems to need libGL:

```
checking whether make supports nested variables... yes
checking for pkg-config... no
checking for GL... no
checking GL/gl.h usability... no
checking GL/gl.h presence... no
checking for GL/gl.h... no
configure: error: GL not found
```
Most information I've found on this ([here](https://groups.cern.ch/group/roottalk/Lists/Archive/Flat.aspx?RootFolder=%2fgroup%2froottalk%2fLists%2fArchive%2fcannot%20find%20libGLU%20with%205%2e3411%20and%20Mavericks&FolderCTID=0x01200200A201AF59FD011C4E9284C43BF0CDA2A4), [here](http://stackoverflow.com/questions/14619739/how-to-install-libgl-on-mac-os-x), [here](http://www.pcl-users.org/libGL-issue-when-running-visualization-apps-on-OSX-td3574302.html)) suggest mesa/X11/XQuartz. Not sure that's a viable option here.

I also found [this](http://stackoverflow.com/questions/18550265/compiling-a-c-program-that-uses-opengl-in-mac-os-x) which will take patching makefile -- will try this next time I get a chance.

**Comment by lpantano** [comment]
Hi,

I am trying something here: https://github.com/lpantano/libglu-feedstock

the dependency for GL is here normally in osx: `/System/Library/Frameworks/OpenGL.framework`, so we can set up GL_CFLAGS and GL_LIBS, but the code is assuming GL/gl.h, so I hacked a little that, maybe not the best solution. 

Other option is to path the code to avoid importing `GL/gl.h` to `gl.h` so then we can import directly `/System/Library/Frameworks/OpenGL.framework/Headers` and ``/System/Library/Frameworks/OpenGL.framework/Libraries`

That part is working on my machine but then I got problems because I have a newer gcc compiler, I am waiting for travis to know what happens there.

**Comment by lpantano** [comment]
some other way is to add `-framework OpenGL ` to GL_CFLAGS/LIBS during `./configure` and patch from `GL/gl.h` to `OpenGL/gl.h`

**Pull request merged**
