### PR TITLE
Adds webcolors

### PR DESCRIPTION
**Pull request by jakirkham**
Simply generated the recipe using the wonderful `conda skeleton pypi`. Made a few tweaks to make it fit nicely in conda-forge.

### CODE REVIEW

**Comment by jakirkham** [comment]
@ubernostrum, any interest in being added as a maintainer here? This will give you commit privileges on the resulting feedstock (repo with recipe). Would allow you to bump the version and have new packages automatically deployed for `conda` to install for instance.

**Comment by pelson** [comment]
I decided to go ahead and merge this PR (as the CI was green, and the recipe looks good).
@ubernostrum - if you would like to have merge rights on the resulting feedstock then we can easily add you as a maintainer at https://github.com/conda-forge/webcolors-feedstock (when the CI on this repo is complete) - it would be great to have your knowledge on board.

**Comment by jakirkham** [comment]
Sounds good. Thanks @pelson.

Also you can just ping me, @ubernostrum, if you are interested in being added.

**Comment by ubernostrum** [comment]
Assuming that I'm completely unfamiliar with Conda and its ecosystem, what would I gain or be able to do with this access in order to want to have it? From a brief look around it seems like Conda is mostly another downstream packager, in the same vein as, say, a Linux distro's package manager, and my relationship with them mostly tends to be watching for bug reports forwarded upstream.

**Comment by jakirkham** [comment]
Thanks for getting back to me, @ubernostrum.

> From a brief look around it seems like Conda is mostly another downstream packager...

Basically, true. It has had a focus on Python, in particular, Scientific Python. Though support for other languages has been added over time. It doesn't necessarily need to know about the language, but it can help with package manager awareness (e.g. knowing what is pip installed).

> ...my relationship with them mostly tends to be watching for bug reports forwarded upstream.

Then you may want to watch this [repo]( https://github.com/conda-forge/webcolors-feedstock ). To see if there are any issues installing.

> ...what would I gain or be able to do with this access in order to want to have it?

You would gain commit privileges on the repo mentioned above.

This would be nice when releasing a new version for instance, which amounts to updating the [version number]( https://github.com/conda-forge/webcolors-feedstock/blob/master/recipe/meta.yaml#L1 ), [checksum]( https://github.com/conda-forge/webcolors-feedstock/blob/master/recipe/meta.yaml#L10 ), and resetting the [build number]( https://github.com/conda-forge/webcolors-feedstock/blob/master/recipe/meta.yaml#L13 ) to `0` after a PyPI release.

To gain access, either you or I would submit a PR to the same repo mentioned above that adds your GitHub username to the [recipe maintainers list]( https://github.com/conda-forge/webcolors-feedstock/blob/master/recipe/meta.yaml#L32 ). Once merged, you will be given commit privileges after a system update is run.

**Pull request merged**
