### PR TITLE
Add dbt-postgres

### PR DESCRIPTION
**Pull request by maresb**
The dbt-postgres package has been split off upstream, so we need a new feedstock.

Since this is already an output of dbt-feedstock, I have taken the following steps:
1. Set the build number to 1 because build 0 of dbt-postgres already exists.
2. Prepared a PR to add this future feedstock for the allowed outputters in https://github.com/conda-forge/feedstock-outputs/pull/71
3. Prepared a PR to make dbt-feedstock a single-output feedstock with just dbt-core in https://github.com/conda-forge/dbt-feedstock/pull/112
4. [Asked for clarification](https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$171552674516416NXnut:matrix.org?via=matrix.org&via=gitter.im&via=cadair.com) in the Matrix chat about whether I also need to create a new dbt-core feedstock

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by maresb** [comment]
@drewbanin @jthandy @maresb @thewchan @rxm7706

Please :+1: this comment and I will add you as a maintainer. If this PR has already been merged, then please open an issue on https://github.com/conda-forge/dbt-postgres-feedstock and I will add you there.

**Comment by maresb** [comment]
@rxm7706, the linter is now requiring a PR  comment

**Comment by rxm7706** [comment]
Willing to maintain !

**Comment by maresb** [comment]
@conda-forge/help-python, ready for review!

**Pull request merged**
