### PR TITLE
Add recipe for picknmix

### PR DESCRIPTION
**Pull request by jamesmyatt**
Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jamesmyatt** [comment]
@Cheukting, can you comment to confirm that you're willing to be listed as a maintainer?

**Comment by jamesmyatt** [comment]
Closes https://github.com/picknmix/picknmix/issues/43

**Comment by Cheukting** [comment]
Thank you @jamesmyatt I am willing to be listed as a maintainer.

**Comment by Cheukting** [comment]
@jamesmyatt looking at the logs, it says picknmix required python 2.7.15 which is not true, do you have any idea why?

**Comment by jamesmyatt** [comment]
No idea. I assume that it's because of the `python_requires` property in setup.py. I'll try something that might fix it.

**Comment by jamesmyatt** [comment]
Judging by https://github.com/conda-forge/dask-core-feedstock/blob/master/recipe/meta.yaml, the python version needs to go in the build requirements section

**Comment by jamesmyatt** [comment]
That looks like it's fixed it, but it's missing an install_requires for numpy. I'll look at it again later this week.

**Comment by Cheukting** [comment]
> That looks like it's fixed it, but it's missing an install_requires for numpy. I'll look at it again later this week.

Thanks! I will have a look as well to make sure I didn't miss any dependency in setup.py.

**Pull request closed without merging**
