### PR TITLE
new noarch python recipes for google-cloud.., atlasclient and analytics-python

### PR DESCRIPTION
**Pull request by BrentDorsey**
New noarch python recipes for:
- [analytics-python](https://github.com/segmentio/analytics-python)
- [atlasclient](https://github.com/jpoullet2000/atlasclient)
- [google-cloud-bigtable](https://github.com/googleapis/google-cloud-python/tree/master/bigtable)
- [google-cloud-language](https://github.com/googleapis/google-cloud-python/tree/master/language)
- [google-cloud-spanner](https://github.com/googleapis/google-cloud-python/tree/master/spanner)
- [google-cloud-translate](https://github.com/googleapis/google-cloud-python/tree/master/translate)
- [google-cloud-vision](https://github.com/googleapis/google-cloud-python/tree/master/vision)

The following 2 packages depend on conda-forge pull request [new conda-forge python recipe for grpc-google-iam-v1-feedstock #8159](https://github.com/conda-forge/staged-recipes/pull/8159) being merged.
- [google-cloud-bigtable](https://github.com/googleapis/google-cloud-python/tree/master/bigtable)
- [google-cloud-spanner](https://github.com/googleapis/google-cloud-python/tree/master/spanner)

The packages in this pull request are requirements for apache-airflow 1.10.1 extras:
- [atlas](https://github.com/apache/airflow/blob/v1-10-stable/setup.py#L133)
- [flask_oauth](https://github.com/apache/airflow/blob/v1-10-stable/setup.py#L191)
- [gcp_api](https://github.com/apache/airflow/blob/v1-10-stable/setup.py#L174)
- [segment](https://github.com/apache/airflow/blob/v1-10-stable/setup.py#L226)

Thanks,

[BrentDorsey](https://github.com/BrentDorsey)
[hill-country-machine-learning](https://github.com/hill-country-machine-learning)

### CODE REVIEW

**Comment by BrentDorsey** [comment]
Apologies for the large number of commits and broken builds, I was having trouble with the selector syntax.

I think the linter rules have changed making the Conda-Forge readthedocs Writing the meta.yaml guidance for [Building noarch packages](https://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages) incorrect.  Specifically, the section:

> Note that while noarch: python does not work with selectors, it does work with version constraints, so skip: True  # [py2k] can sometimes be replaced with a constrained python version in the build/run subsections: say python >=3 instead of just python.

When I pushed the recipe syntax below the linter failed the build.  Maybe I didn't constrain the python version enough and should have used  `python <3` instead of `python >=2.7,<3.5`?
```
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"
  skip: True  # [py>35]

requirements:
  build:
    - python >=2.7,<3.5
    - enum34 >=1.1.6
    ...
  host:
    - python >=2.7,<3.5
    - pip
  run:
    - python >=2.7,<3.5
    - enum34 >=1.1.6
```

### conda-forge-linting service:

> I wanted to let you know that I linted all conda-recipes in your PR (recipes/analytics-python, recipes/atlasclient, recipes/google-cloud-bigtable, recipes/google-cloud-language, recipes/google-cloud-spanner, recipes/google-cloud-translate, recipes/google-cloud-vision) and found some lint.
>
> Here's what I've got...
>
>For recipes/google-cloud-language:
>
>noarch packages can't have selectors. If the selectors are necessary, please remove noarch: python.
>For recipes/google-cloud-vision:
>
>noarch packages can't have selectors. If the selectors are necessary, please remove noarch: python.

**Comment by chrisburr** [comment]
You should use `skip: True   # [py<XY]` or `python >=X.Y` in host/run but not both, e.g. if the recipe is Python 2 only:

```yaml
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - enum34 >=1.1.6
```
or
```yaml
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"
  skip: True  # [py3k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - enum34 >=1.1.6
```

The first should be preferred.

Unrelated, you probably don't want anything in the `build` requirements, those should be used for build tools like compilers, `make`, `sed`. (Unless Python is only being used as a scripting language but that's quite rare.)

**Comment by BrentDorsey** [comment]
Thanks for the detailed explanation. 

I should pay more attention to the announcements [Deprecation notice for Python 3.5](http://conda-forge.org/docs/user/introduction.html#announcements).  Would I be correct in saying python 3.7 is the min python 3 version that can be built going forward?

**CI Build Failure**
I tried using host and run `python: <3` and `python: <3.5` requirements.  With both configurations the CI build is failing while trying to build the package for python 3.7 which is outside the host and run python version requirement `python <3.5`?

> conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {"python[version='>=3.7,<3.8.0a0']", "python[version='<3']"}

**Pull Request Updates**

**google cloud vision and language updates**
- build selectors removed
- build requirements removed
- python version restricted in host and run requirements set to `python <3`

**google cloud all packages updates**
- pin_compatible jinja2 function implemented for run requirements to lookup compatible package version based on host version requirement defined

Am I using pin_compatible correctly?  Andy feedback on the pin_compatible changes I made would be awesome.  Also, I'd love some high level general guidance around when to use pin_compatible and when not to?  

atlasclient and analytics-python packages unchanged

Also, I must be missing an environment variable, conda configuration settings or something ???? that need to be setup to enable using [.circleci/run_docker_build.sh](http://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally) to test changes using local docker builds?

My local environment:

conda 4.6.12
conda config --get
> --set add_pip_as_python_dependency False
> --set always_yes True
> --set anaconda_upload False
> --set auto_update_conda False
> --add channels 'conda-forge'   # lowest priority
> --add channels 'yeti-coolers'
> --add channels 'defaults'   # highest priority
> --set show_channel_urls True

macOS Mojave 10.14.4

Docker Desktop
Version 2.0.0.3 (21259)
Engine: 18.09.2
Compose: 1.23.2
Machine: 0.16.1

`circleci/run_docker_build.sh`
> Containers: 72
>  Running: 7
>  Paused: 0
>  Stopped: 65
> Images: 194
> Server Version: 18.09.2
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
> runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
> init version: fec3683
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.9.125-linuxkit
> Operating System: Docker for Mac
> OSType: linux
> Architecture: x86_64
> CPUs: 6
> Total Memory: 9.743GiB
> Name: linuxkit-025000000001
> ID: 2DJX:YLQN:WBYN:UDYC:ADOH:HSE7:CKP5:TTN4:MEPZ:PPTC:YKQ7:P7AY
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: 80
>  Goroutines: 93
>  System Time: 2019-04-18T16:35:59.261455531Z
>  EventsListeners: 2
> HTTP Proxy: gateway.docker.internal:3128
> HTTPS Proxy: gateway.docker.internal:3129
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine

**Comment by BrentDorsey** [comment]
Also, I must be missing an environment variable, conda configuration settings or something ???? that need to be setup to enable using [.circleci/run_docker_build.sh](http://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally) to test changes using local docker builds?

My local environment:

conda 4.6.12
conda config --get
> --set add_pip_as_python_dependency False
> --set always_yes True
> --set anaconda_upload False
> --set auto_update_conda False
> --add channels 'conda-forge'   # lowest priority
> --add channels 'yeti-coolers'
> --add channels 'defaults'   # highest priority
> --set show_channel_urls True

macOS Mojave 10.14.4

Docker Desktop
Version 2.0.0.3 (21259)
Engine: 18.09.2
Compose: 1.23.2
Machine: 0.16.1

Below are the results from executing run_docker_build.sh from the root of my staged-recipes project:

```
cd ~/github/hiil-country-machine-learning/staged-recipes
ls -la
total 80
drwxr-xr-x  18 bdorsey  staff   576 Apr 17 08:45 .
drwxr-xr-x  11 bdorsey  staff   352 Apr 17 08:45 ..
-rw-r--r--   1 bdorsey  staff  2097 Apr 15 11:24 .appveyor.yml
drwxr-xr-x   5 bdorsey  staff   160 Apr 15 11:24 .azure-pipelines
drwxr-xr-x   8 bdorsey  staff   256 Apr 15 11:24 .ci_support
drwxr-xr-x   7 bdorsey  staff   224 Apr 16 10:30 .circleci
drwxr-xr-x  15 bdorsey  staff   480 Apr 18 11:17 .git
-rw-r--r--   1 bdorsey  staff   108 Apr 15 11:24 .gitattributes
drwxr-xr-x   3 bdorsey  staff    96 Apr 15 11:24 .github
-rw-r--r--   1 bdorsey  staff   141 Apr 15 11:50 .gitignore
-rw-r--r--   1 bdorsey  staff  6624 Apr 15 11:24 .travis.yml
drwxr-xr-x   6 bdorsey  staff   192 Apr 15 11:24 .travis_scripts
-rw-r--r--   1 bdorsey  staff  1488 Apr 15 11:24 LICENSE.txt
-rw-r--r--   1 bdorsey  staff  8135 Apr 15 11:24 README.md
-rw-r--r--   1 bdorsey  staff   191 Apr 15 11:24 azure-pipelines.yml
drwxr-xr-x   8 bdorsey  staff   256 Apr 18 11:47 build_artifacts
-rw-r--r--   1 bdorsey  staff    32 Apr 15 11:24 conda-forge.yml
drwxr-xr-x  10 bdorsey  staff   320 Apr 16 12:12 recipes
CONFIG="linux_" ./.circleci/run_docker_build.sh
```

> Containers: 74
>  Running: 7
>  Paused: 0
>  Stopped: 67
> Images: 194
> Server Version: 18.09.2
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
> runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
> init version: fec3683
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.9.125-linuxkit
> Operating System: Docker for Mac
> OSType: linux
> Architecture: x86_64
> CPUs: 6
> Total Memory: 9.743GiB
> Name: linuxkit-025000000001
> ID: 2DJX:YLQN:WBYN:UDYC:ADOH:HSE7:CKP5:TTN4:MEPZ:PPTC:YKQ7:P7AY
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: 82
>  Goroutines: 95
>  System Time: 2019-04-18T16:53:27.322994319Z
>  EventsListeners: 2
> HTTP Proxy: gateway.docker.internal:3128
> HTTPS Proxy: gateway.docker.internal:3129
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine
> 
> No active host found
> useradd: warning: the home directory already exists.
> Not copying any file from skel directory into it.
> + export PYTHONUNBUFFERED=1
> + PYTHONUNBUFFERED=1
> + cat
> + cp -r /home/conda/staged-recipes/recipes /home/conda/conda-recipes
> + cp -r /home/conda/staged-recipes/.ci_support /home/conda/.ci_support
> + echo 'Finding recipes merged in master and removing them from the build.'
> Finding recipes merged in master and removing them from the build.
> + pushd /home/conda/staged-recipes/recipes
> + '[' False == True ']'
> + git ls-tree --name-only master -- .
> + xargs -I '{}' sh -c 'rm -rf ~/conda-recipes/{} && echo Removing recipe: {}'
> Removing recipe: analytics-python
> Removing recipe: atlasclient
> Removing recipe: example
> Removing recipe: google-cloud-bigtable
> Removing recipe: google-cloud-language
> Removing recipe: google-cloud-spanner
> Removing recipe: google-cloud-translate
> Removing recipe: google-cloud-vision
> + popd
> + export CONDA_NPY=19
> + CONDA_NPY=19
> + conda index /home/conda/staged-recipes/build_artifacts
> Subdir: noarch: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.75it/s]
> + conda install --yes --quiet 'conda!=4.6.1' 'conda-forge-ci-setup=2.*' conda-forge-pinning networkx conda-build
> + source run_conda_forge_build_setup
> ++ export CPU_COUNT=2
> ++ CPU_COUNT=2
> ++ export PYTHONUNBUFFERED=1
> ++ PYTHONUNBUFFERED=1
> ++ conda config --set show_channel_urls true
> ++ conda config --set auto_update_conda false
> ++ conda config --set add_pip_as_python_dependency false
> ++ export CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts
> ++ CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts
> ++ mkdir -p /opt/conda/etc/conda/activate.d
> ++ echo 'export CONDA_BLD_PATH='\''/home/conda/feedstock_root/build_artifacts'\'''
> ++ echo 'export CPU_COUNT='\''2'\'''
> ++ echo 'export PYTHONUNBUFFERED='\''1'\'''
> ++ conda info
> 
>      active environment : base
>     active env location : /opt/conda
>             shell level : 1
>        user config file : /home/conda/.condarc
>  populated config files : /home/conda/.condarc
>           conda version : 4.6.13
>     conda-build version : 3.17.8
>          python version : 3.7.2.final.0
>        base environment : /opt/conda  (writable)
>            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
>                           https://conda.anaconda.org/conda-forge/noarch
>                           https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/linux-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://conda.anaconda.org/yeti-coolers/linux-64
>                           https://conda.anaconda.org/yeti-coolers/noarch
>           package cache : /opt/conda/pkgs
>                           /home/conda/.conda/pkgs
>        envs directories : /opt/conda/envs
>                           /home/conda/.conda/envs
>                platform : linux-64
>              user-agent : conda/4.6.13 requests/2.21.0 CPython/3.7.2 Linux/4.9.125-linuxkit centos/6.10 glibc/2.12
>                 UID:GID : 502:502
>              netrc file : None
>            offline mode : False
> 
> ++ conda config --show-sources
> ==> /home/conda/.condarc <==
> add_pip_as_python_dependency: False
> auto_update_conda: False
> channels:
>   - conda-forge
>   - defaults
>   - yeti-coolers
> show_channel_urls: True
> conda-build:
>   root-dir: /home/conda/staged-recipes/build_artifacts
> 
> ==> envvars <==
> bld_path: /home/conda/feedstock_root/build_artifacts
> 
> ++ conda list --show-channel-urls
> # packages in environment at /opt/conda:
> #
> # Name                    Version                   Build  Channel
> anaconda-client           1.7.2                      py_0    conda-forge
> asn1crypto                0.24.0                py37_1003    conda-forge
> attrs                     19.1.0                     py_0    conda-forge
> beautifulsoup4            4.7.1                 py37_1001    conda-forge
> bzip2                     1.0.6             h14c3975_1002    conda-forge
> ca-certificates           2019.3.9             hecc5488_0    conda-forge
> certifi                   2019.3.9                 py37_0    conda-forge
> cffi                      1.12.2           py37hf0e25f4_1    conda-forge
> chardet                   3.0.4                 py37_1003    conda-forge
> click                     7.0                        py_0    conda-forge
> clyent                    1.2.2                      py_1    conda-forge
> conda                     4.6.13                   py37_0    conda-forge
> conda-build               3.17.8                   py37_1    conda-forge
> conda-env                 2.6.0                         1    conda-forge
> conda-forge-ci-setup      2.2.1                    py37_0    conda-forge
> conda-forge-pinning       2019.04.18                    0    conda-forge
> cryptography              2.6.1            py37h9d9f1b6_0    conda-forge
> curl                      7.64.0               h646f8bb_2    conda-forge
> decorator                 4.4.0                      py_0    conda-forge
> expat                     2.2.5             hf484d3e_1002    conda-forge
> filelock                  3.0.10                     py_0    conda-forge
> gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
> git                       2.21.0          pl526h2882143_0    conda-forge
> glob2                     0.6                        py_0    conda-forge
> gosu                      1.10              h81701ea_1001    conda-forge
> icu                       58.2              hf484d3e_1000    conda-forge
> idna                      2.8                   py37_1000    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> jinja2                    2.10                       py_1    conda-forge
> jsonschema                3.0.1                    py37_0    conda-forge
> jupyter_core              4.4.0                      py_0    conda-forge
> krb5                      1.16.3            h05b26f9_1001    conda-forge
> libarchive                3.3.3             he5c8681_1003    conda-forge
> libcurl                   7.64.0               h541490c_2    conda-forge
> libedit                   3.1.20170329      hf8c457e_1001    conda-forge
> libffi                    3.2.1             he1b5a44_1006    conda-forge
> libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
> libiconv                  1.15              h516909a_1005    conda-forge
> liblief                   0.9.0                h1532aa0_0    conda-forge
> libssh2                   1.8.1                h22169c7_0    conda-forge
> libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
> libxml2                   2.9.8             h143f9aa_1005    conda-forge
> lz4-c                     1.8.1.2                       0    conda-forge
> lzo                       2.10              h14c3975_1000    conda-forge
> markupsafe                1.1.1            py37h14c3975_0    conda-forge
> nbformat                  4.4.0                      py_1    conda-forge
> ncurses                   6.1               hf484d3e_1002    conda-forge
> networkx                  2.3                        py_0    conda-forge
> openssl                   1.1.1b               h14c3975_1    conda-forge
> patchelf                  0.9               hf484d3e_1004    conda-forge
> perl                      5.26.2            h14c3975_1002    conda-forge
> pip                       19.0.3                   py37_0    conda-forge
> pkginfo                   1.5.0.1                    py_0    conda-forge
> psutil                    5.6.1            py37h14c3975_0    conda-forge
> py-lief                   0.9.0            py37hf484d3e_0    conda-forge
> pycosat                   0.6.3           py37h14c3975_1001    conda-forge
> pycparser                 2.19                     py37_1    conda-forge
> pyopenssl                 19.0.0                   py37_0    conda-forge
> pyrsistent                0.14.11          py37h14c3975_0    conda-forge
> pysocks                   1.6.8                 py37_1002    conda-forge
> python                    3.7.2                h381d211_0    conda-forge
> python-dateutil           2.8.0                      py_0    conda-forge
> python-libarchive-c       2.8                   py37_1004    conda-forge
> pytz                      2018.9                     py_0    conda-forge
> pyyaml                    5.1              py37h14c3975_0    conda-forge
> readline                  7.0               hf8c457e_1001    conda-forge
> requests                  2.21.0                py37_1000    conda-forge
> ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
> setuptools                40.8.0                   py37_0    conda-forge
> six                       1.12.0                py37_1000    conda-forge
> soupsieve                 1.8                      py37_0    conda-forge
> sqlite                    3.26.0            h67949de_1001    conda-forge
> tini                      0.18.0            h14c3975_1001    conda-forge
> tk                        8.6.9             h84994c4_1000    conda-forge
> tqdm                      4.31.1                     py_0    conda-forge
> traitlets                 4.3.2                 py37_1000    conda-forge
> urllib3                   1.24.1                py37_1000    conda-forge
> wheel                     0.33.1                   py37_0    conda-forge
> xz                        5.2.4             h14c3975_1001    conda-forge
> yaml                      0.1.7             h14c3975_1001    conda-forge
> zlib                      1.2.11            h14c3975_1004    conda-forge
> zstd                      1.3.3                         1    conda-forge
> + find /home/conda/conda-recipes -mindepth 2 -maxdepth 2 -type f -name yum_requirements.txt
> + grep -v -e '^#' -e '^$'
> + xargs -n1 cat
> + xargs -r /usr/bin/sudo -n yum install -y
> + test 1 == 1
> + python /home/conda/.ci_support/build_all.py /home/conda/conda-recipes
> Found no recipes to build
> + touch /home/conda/staged-recipes/build_artifacts/conda-forge-build-done

>

**Comment by BrentDorsey** [comment]
> You should use `skip: True # [py<XY]` or `python >=X.Y` in host/run but not both, e.g. if the recipe is Python 2 only:
> 
> ```yaml
> build:
>   noarch: python
>   number: 0
>   script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"
> 
> requirements:
>   host:
>     - python <3
>     - pip
>   run:
>     - python <3
>     - enum34 >=1.1.6
> ```
> 
> or
> 
> ```yaml
> build:
>   noarch: python
>   number: 0
>   script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"
>   skip: True  # [py3k]
> 
> requirements:
>   host:
>     - python
>     - pip
>   run:
>     - python
>     - enum34 >=1.1.6
> ```
> 
> The first should be preferred.
> 
> Unrelated, you probably don't want anything in the `build` requirements, those should be used for build tools like compilers, `make`, `sed`. (Unless Python is only being used as a scripting language but that's quite rare.)

The conda-forge linter fails both configurations above when `noarch: python` is set.

`noarch: python` removed from recipe.

**Comment by BrentDorsey** [comment]
Pull Request Updates

**google cloud vision and language updates**
- build selectors removed
- build requirements removed
- python version restricted in host and run requirements set to python <3

**google cloud all packages updates**
- pin_compatible jinja2 function implemented for run requirements to lookup compatible package version based on host version requirement defined

Am I using pin_compatible correctly? Any feedback on the pin_compatible changes I made would be awesome and I'd love some high level general guidance around when to use pin_compatible and when not to?

atlasclient and analytics-python packages unchanged

**Comment by BrentDorsey** [comment]
Updated recipe host and run requirements with undocumented dependencies on:
- enum34   # [py<=34]
- futures   # [py<32]
- six

Removed noarch from all google.cloud packages in this pull request except google.cloud.translate as translate is the only package that doesn't have python major.minor version specific requirements.

**Comment by chrisburr** [comment]
I've pushed some changes to:

 * Add `licence_file` attributes as most licences require a copy of the text to be included with all distributions of the package.
 * Remove `host` dependencies that aren't required for running the `setup.py` script of each package.
 * Remove Python version constraints on packages which aren't flagged as `noarch`. These should be enforced with `skip: True  # [py=XY]` if required but currently conda-forge only builds for 2.7, 3.6 and 3.7 so there is no need to specify anything.

Are you happy with these changes? If so, I'll merge.

> Am I using pin_compatible correctly? Any feedback on the pin_compatible changes I made would be awesome and I'd love some high level general guidance around when to use pin_compatible and when not to?

In general `pin_compatible` is used for defining ABI compatibility. For example if this used the numpy C bindings, `pin_compatible('numpy')` will allow any anything up until numpy 2.0 is released. When this happens there will probably be a [migrator bot](http://conda-forge.org/status/) which goes round rebuilding dependent packages as was recently done for `openssl`. This syntax means that no changes need to be made to the recipes, just rerender and bump the build number.

**Comment by BrentDorsey** [comment]
Apologies, I totally didn't see the updates you pushed until today.

Update Summary:
- google packages that use grpc: refined build to only skip windows py27
- protobuf does not support Visual C++ 2008, windows py27 package not available
- set license_file
- removed pin_compatible from pure python packages
- removed version from pure python package run requirements

Is there an industry standard method/process/cli for evaluating ABI compatibility?
How does setting version bounds on run requirements vs. host requirements impact over depending?

**Comment by chrisburr** [comment]
For the packages you're contributing here ABI concerns don't apply as (I think?) the packages are pure Python and probably don't do anything fancy with `ctypes`. If you were using a compiler you then 

> 1) Is there an industry standard method/process/cli for evaluating ABI compatibility?

Ideally projects should state what their ABI stability and monitor to avoid accidental breakages. In practice many projects don't state it so the best you can do is check trackers such as: https://abi-laboratory.pro/

Conda packages can then use [`run_exports`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=run_exports#export-runtime-requirements) to say "if you build with me as a host dependency you need to pin at runtime with this version constraint".

> 2) How does setting version bounds on run requirements vs. host requirements impact overdepending?

It should have no effect.

> 3) What's the best practice for resolving overdepending warnings like the warning below that's introduced when python is set as a run requirement?

You can ignore it.

**Comment by BrentDorsey** [comment]
@chrisburr - Thank you very much.

**Pull request merged**
