### PR TITLE
Add r-quanteda extra packages via conda_r_skeleton_helper

### PR DESCRIPTION
**Pull request by izahn**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by izahn** [comment]
Waiting on https://github.com/conda-forge/staged-recipes/pull/14584

**Comment by izahn** [comment]
I think this one is ready to go @conda-forge/help-r

**Comment by izahn** [comment]
Would love a review of this if you have time @conda-forge/help-r , and thanks for all your contributions!

**Comment by jakirkham** [comment]
Can you please run?

```
git add --renormalize .
git commit -m "Renormalize recipe EOLs"
```

**Comment by jakirkham** [comment]
Friendly nudge @conda-forge/help-r @conda-forge/staged-recipes 😉

**Comment by jdblischak** [comment]
@izahn The recipes still have the comments from the recipe skeleton. The helper script should have removed these. The formatting in your previous PR #14584 looks good. Could you please try running them through the helper again and open an issue on the helper repo if something has broken? Thanks!

**Comment by jakirkham** [comment]
@jdblischak would it be possible to incorporate this renormalizing step (mentioned above) into the helper script? We've been noticing issue converting recipes into feedstocks (particularly due to how the `bld.bat` files are formatted). It would be great if we could have them formatted in a way that causes minimal issues for conversion

**Comment by izahn** [comment]
Thanks @jdblischak , and sorry for the messiness. I pulled the latest *conda_r_skeleton_helper* and re-ran. Indeed the recipes are much cleaner now -- not sure what went wrong the first time.  I made some other improvements while at it, including pulling out textplots which I have submitted separately at https://github.com/conda-forge/staged-recipes/pull/14810 because it is missing dependencies on Windows.

@conda-forge/help-r I think these are in good shape thanks to @jdblischak  and @jakirkham, but please let me know if there are any additional improvements I should make!

**Comment by jdblischak** [comment]
>  would it be possible to incorporate this renormalizing step (mentioned above) into the helper script? We've been noticing issues converting recipes into feedstocks (particularly due to how the bld.bat files are formatted). It would be great if we could have them formatted in a way that causes minimal issues for conversion

@jakirkham I'm open to it, but I'm not sure how best to do that. The helper script doesn't run any Git commands. The helper  script is setup to be run in its own repo, and then the user copies the recipes to `staged-recipes/`. Thus we don't want to run any Git commands inside the helper script repo. We could run `dos2unix`/`mac2unix`, but those are unlikely to be available on Windows anyways. And where do the problematic line endings get added? It is by `conda skeleton cran` or by the user's Git settings? For example, I know it's possible to configure Git Bash to handle line endings in multiple different ways. Thus even if the helper script tries to fix it, it may get changed later when the user runs `git add`.

**Pull request merged**
