### PR TITLE
Add pyvistaqt

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hoechenberger** [comment]
@conda-forge/staged-recipes This PR is ready for review. I've opened a PR upstream, asking the authors to publish the sdist on PyPI too: https://github.com/pyvista/pyvistaqt/issues/22
Until then, we'll have to download the sources from GitHub.

**Comment by banesullivan** [comment]
@hoechenberger, would you please add myself and @akaszynski to the maintainers list?

**Comment by hoechenberger** [comment]
@banesullivan done.

**Comment by hoechenberger** [comment]
@akaszynski can you please confirm it's okay with you to be listed as a maintainer here?

**Comment by hoechenberger** [comment]
(very!) friendly ping to @akaszynski to confirm being a maintainer for this package is alright with them :)

**Comment by akaszynski** [comment]
Sorry!  Yes, totally fine with being a maintainer.  Thanks for adding me!

**Comment by hoechenberger** [comment]
friendly ping to @conda-forge/staged-recipes: this PR is ready for review. :)

**Pull request merged**
