### PR TITLE
Add openff-evaluator

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by synapticarbors** [comment]
The windows build seems to be blocked by windows builds not available for `packmol` and `openmmtools`. There is an issue open for `packmol`:

https://github.com/conda-forge/packmol-feedstock/issues/7

and I just opened an issue for `openmmtools`:
https://github.com/conda-forge/openmmtools-feedstock/issues/4

**Comment by jaimergp** [comment]
This is a dup of https://github.com/conda-forge/staged-recipes/pull/13790. Let me know if you want me to close that (those) one(s), @SimonBoothroyd

**Comment by jaimergp** [comment]
Also, this is `noarch` so the Windows errors can be ignored. It's ok as long as Linux passes!

**Comment by SimonBoothroyd** [comment]
Thanks @synapticarbors! In general `openff-evaluator` does not offer windows support due to other factors, so the missing dependencies shouldn't be a blocker here. Hopefully then this should be good to go without the windows tick?

**Comment by jaimergp** [comment]
> Hopefully then this should be good to go without the windows tick?

Yep!

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
