### PR TITLE
Add dask-imread

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a package for reading image data into Dask.

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems `pytest` is failing on Windows because it cannot cleanup the temporary directories. More details in these [logs]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.14106 ). Any suggestions @nicoddemus?

**Comment by nicoddemus** [comment]
@jakirkham looking at some of the tests it seems the directories are still being used by the time pytest tries to remove them; this seems to be a common occurrence, code that can safely remove directories in Linux fails to do so in Windows (that's just my impression, never looked too much into it).

**Comment by nicoddemus** [comment]
Hmm [looking at the code](https://github.com/dask-image/dask-imread/blob/master/tests/test_dask_imread.py#L91) that remove call is even necessary because `tmpdir` is removed by pytest automatically at the end of the test anyway. You might consider contributing that patch upstream.

**Comment by jakirkham** [comment]
Thanks for taking a look. Have come to the same conclusion. It would be great to understand why Windows has an issue with that removal though.

**Comment by nicoddemus** [comment]
I don't know about `dask` at all, but perhaps some object used inside `dask_imread.imread` needs to be closed/released somehow? Just a guess.

**Comment by jakirkham** [comment]
I'll give that some thought. Am pretty sure everything that is opened is going through `with` so should be closed. Any tools or techniques that you would recommend debugging this on Windows?

**Comment by nicoddemus** [comment]
Haven't tried myself, but an idea is to stop the process right before the `dirpth.remove()` call (using `raw_input` for example) and see which file/directory is still open at that point: https://serverfault.com/questions/1966/how-do-you-find-what-process-is-holding-a-file-open-in-windows.

**Comment by jakirkham** [comment]
Thanks for the suggestion. Will give that a try.

**Pull request merged**
