### PR TITLE
Add philosopher (proteomics toolkit)

### PR DESCRIPTION
**Pull request by acesnik**
This PR seeks to add `philosopher`, which is an important toolkit for the field of proteomics. https://github.com/Nesvilab/philosopher

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by acesnik** [comment]
@conda-forge/staged-recipes ready for review

**Review by carterbox — CHANGES_REQUESTED** [review]
You don't need to include `License` in `recipes/philosopher` because it is already included in the source distribution. Conda-build will search for the named license file after unpacking the source.

Also, I'm pretty sure that we still require go recipes to compile from source. You recipe is just copying a precompiled binary.

**Comment by carterbox** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L74-L87

Looks like there are two compiler options for go projects depending on whether you need to link to binaries from other languages.

**Comment by carterbox** [comment]
https://github.com/conda-forge/skopeo-feedstock/
https://github.com/conda-forge/podman-feedstock/

Are two examples of feedstocks shipping go programs. Because you are not (probably) using dynamic linking between go binaries, you will need to use `go-licenses` to grab the licences from all the dependencies that are incorporated into your binary.

**Comment by acesnik** [comment]
Thanks for the examples. I'll try to get to revising this within the next couple weeks.

**Pull request closed without merging**
