### PR TITLE
Add recipes for Perl moose deps,  part 1

### PR DESCRIPTION
**Pull request by xileF1337**
This is the first of a row of PRs providing recipes for Perl module Moose and its dependencies. 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xileF1337** [comment]
@conda-forge/bioconda-recipes I'm porting these recipes to CondaForge unless there are any objections from your side.

@cbrueffer Would you give your consent to be a maintainer of these packages? As usual, your review is very welcome!

**Comment by xileF1337** [comment]
@conda-forge/help-perl, ready for review!

**Comment by xileF1337** [comment]
Hey @cbrueffer,

I have fixed all the trailing blank lines and missing shebangs in my open PRs. I thought I fixed that in my scripts earlier, but obviously it didn't work as expected. Sorry for that! 

If you can spare some time to review these PRs, I would really appreciate if you could begin with this one as it contains many dependencies that I need for other modules. Especially `Module::Build` is quite essential, but also some of the test modules. Thank you so much!

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@xileF1337 just noticed that the Bioconda `perl-module-build` contains the following patch; any idea / do you think it's still useful? 

```--- lib/Module/Build/Base.pm    2022-01-23 20:21:14.041673000 +0100
+++ lib/Module/Build/Base.pm.new        2022-01-23 23:18:38.348762700 +0100
@@ -430,6 +430,7 @@
   }
 
   push @cmd, qw(-MConfig=myconfig -e print -e myconfig);
+  return 1;
   return $self->_backticks(@cmd) eq Config->myconfig;
 }
 
@@ -514,7 +515,7 @@
       $thisperl .= $exe unless $thisperl =~ m/$exe$/i;
     }
 
-    if ( -f $thisperl && $proto->_perl_is_same($thisperl) ) {
+    if ( $proto->_perl_is_same($thisperl) ) {
       return $thisperl;
     }
   }
```

**Comment by xileF1337** [comment]
@cbrueffer Thanks for pointing me to this patch. It seems to disable some checks of `Module::Build` concerning the used Perl version. So far I have not encountered any issues without this patch, so I would rather leave it out for now. But I saved a copy of it just in case.

**Pull request merged**
