### PR TITLE
R packages

### PR DESCRIPTION
**Pull request by daler**
First batch of the "singletons" section from https://github.com/bioconda/bioconda-recipes/issues/5582

cc @bgruening

### CODE REVIEW

**Comment by daler** [comment]
`r-zoo` is installed as a dependency, but loading it during the test fails: https://travis-ci.org/conda-forge/staged-recipes/builds/267254601#L4439

Any ideas on how to fix? Skip OSX?

(cc @bgruening)

**Comment by bgruening** [comment]
@daler the reason is that r-zoo comes from `defaults`, this will be fixed as soon as https://travis-ci.org/conda-forge/r-zoo-feedstock/jobs/265406963 gets green. I will trigger a rebuild here as well then.

**Comment by daler** [comment]
Ah, great. Thanks!

**Comment by bgruening** [comment]
And restarted! Lets see how it goes!

**Comment by bgruening** [comment]
@ocefpaf we could need a merge here? :)

**Pull request merged**
