### PR TITLE
test_desolve recipe

### PR DESCRIPTION
**Pull request by sgsokol**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Not sure why the linter is finding a package.

**Comment by hmaarrfk** [comment]
@conda-forge/staged-recipes anybody know r recipes to help here.

**Comment by npavlovikj** [comment]
The name of the package in `meta.yaml` is `r-desolve`, and there is already conda-forge package for `r-desolve`, https://github.com/conda-forge/r-desolve-feedstock/blob/master/recipe/meta.yaml. It looks like it is the same package (not sure why it is named `r-testdesolve` here), so this PR should be closed, and any updates should be done with the feedstock.

**Comment by sgsokol** [comment]
> The name of the package in `meta.yaml` is `r-desolve`, and there is already conda-forge package for `r-desolve`, https://github.com/conda-forge/r-desolve-feedstock/blob/master/recipe/meta.yaml. It looks like it is the same package (not sure why it is named `r-testdesolve` here), so this PR should be closed, and any updates should be done with the feedstock.

@npavlovikj you are right. I wanted just to test if an r package using fortran is able build on mac os. It could but selected r-3.6 with libgfortran-4 not r-3.5 which is linked with libgfortran-3. The latter is problematic as you know from my r-rmumps recipe and some others.
I'll remove this PR shortly.

**Comment by npavlovikj** [comment]
Ah, I see your reasoning - yeah, fortran packages build fine on OSX. Regarding r-base 3.5, looks like there is some dependency issue with the conda-forge package, and the r-base feedstock needs to be updated. Once this passes the tests and is merged, https://github.com/conda-forge/r-base-feedstock/pull/114, hopefully we can just restart the PRs that fail because of it.

**Pull request closed without merging**
