### PR TITLE
Initial attempt at a ncview recipe

### PR DESCRIPTION
**Pull request by zklaus**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by zklaus** [comment]
This build works for linux, but there are two open issues:

- There are no tests. This is because even the simple execution of `ncview -h` depends on the availability of an X11 DISPLAY which seems not to be available in the build environment. Is there a way to change that?
- The build fails for osx and I don't understand why. The output of the azure pipeline suggest that libxaw is missing, but the relevant package `xorg-libxaw` is installed previously. Is there a way to debug this without access to a mac?

@ocefpaf I saw that you were mentioned in an earlier attempt at packaging ncview, would you be willing to help again?

**Comment by ocefpaf** [comment]
@zklaus using the x11 libraries on macOS can be problematic. Can you skip OS X for now? We can get this merged and then we can work on the feedstock to re-add OS X. I have a few ideas that may work but they involve hacking the re-render, which is a no-go on staged-recipes.

**Comment by ocefpaf** [comment]
> What about the absence of even a simple test? Is there something to be done about that?

We can try to check if the binary exist or even try to call `ncview -h` if that returns `0`.
 
> Also, would you like to be entered as a maintainer as well?

Sure.

**Comment by zklaus** [comment]
@ocefpaf great, thanks for your help! This seems ready now.

**Pull request merged**
