### PR TITLE
Add libcudf recipe

### PR DESCRIPTION
**Pull request by prashantkhoje**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by leofang** [comment]
cc: @jakirkham @kkraus14

**Comment by kkraus14** [comment]
@prashantkhoje I believe it's possible to manually use CUDA 11.5 or 11.6 but you need to create a custom `conda_build_config.yaml` file to do so and I'm not sure if staged-recipes supports that.

@conda-forge/core does anyone know?

**Comment by hmaarrfk** [comment]
Builds with cuda 11.2 should be compatible with running on cuda 11.5 and 11.6.

I thought we had cuda builds on staged recipes for cuda now. Not sure why the builds aren't running

**Comment by kkraus14** [comment]
> Builds with cuda 11.2 should be compatible with running on cuda 11.5 and 11.6.
> 
> I thought we had cuda builds on staged recipes for cuda now. Not sure why the builds aren't running

Libcudf requires building with CUDA 11.5+ and then can run on CUDA 11.0+.

**Comment by hmaarrfk** [comment]
not stale

**Pull request closed without merging**
