### PR TITLE
Add pytest-variables recipe

### PR DESCRIPTION
**Pull request by birdsarah**

### CODE REVIEW

**Comment by msarahan** [comment]
@davehunt are you OK with being listed as a maintainer here?

**Comment by birdsarah** [comment]
For context @msarahan, see https://github.com/pytest-dev/pytest-selenium/issues/70 which proposes to add pytest-selenium recipe - with support from the library maintainer @davehunt. I started that a while ago (#2075) but it needed the dependencies pytest-variables, pytest-base-url, pytest-html (which has a dependency of pytest-metadata) - all of which are also @davehunt projects.

**Comment by davehunt** [comment]
I don't know as much as I should about conda, but as the maintainer of this plugin I'm happy for that to extend here.

**Comment by msarahan** [comment]
Thanks @davehunt.  Everything else looks fine to me.  Merging.

**Pull request merged**
