### PR TITLE
Adds r-plyr and r-reshape2 recipes.

### PR DESCRIPTION
**Pull request by jrderuiter**
Adds r-rccp, r-plyr and r-reshape2 recipes (ported from R channel). WIP (want to check linting), more recipes to follow.

### CODE REVIEW

**Comment by johanneskoester** [comment]
@jderuiter no need to manually port these. Check #2009 it gives instruction about the conda build version to use in order to get compatible recipes with conda skeleton.

**Comment by johanneskoester** [comment]
Also, consider to follow out topological sort there. Otherwise, you might have missing dependencies (especially once the feedstocks are built).

**Comment by jakirkham** [comment]
Was this meant to be intentionally closed?

**Comment by jrderuiter** [comment]
Yes, because I wanted to follow the topological build order of the underlying R packages first. Anyhow, these packages have now already been added by other pull requests.

**Pull request closed without merging**
