### PR TITLE
Added recipe for argos - a scientific data viewer

### PR DESCRIPTION
**Pull request by robintw**
Added a recipe for argos, a scientific data viewing program available at https://github.com/titusjan/argos

### CODE REVIEW

**Comment by robintw** [comment]
I'm getting an error through the CI services saying:

```
The following specifications were found to be in conflict:
  - argos 0.2.1 np111py36_0
  - python 3.6*
```

I can't quite work out how this is being caused - it seems to be just for Python 3.6, but I've used the `numpy x.x` specification for both development and build requirements.

Any ideas?

**Comment by ocefpaf** [comment]
@robintw conda is improving but that message it not informative enough yet. If I had to guess the issues lies with `Qt`. Does argo requires `Qt5` only? If so conda-forge may present a problem as we currently pin everything to `Qt4`. The reason for that is because we cannot build `Qt5` yet.

cc.: @mingwandroid who is working on a `Qt5` build that is compatible with `conda-forge`.

**Comment by robintw** [comment]
Ah, that makes sense @ocefpaf. Yes, Argos requires `Qt5`.

@mingwandroid Do you have any idea of a very rough availability date for a `conda-forge` `Qt5` build?

**Comment by mingwandroid** [comment]
You can try the test 5.6.2-3 packages on the Anaconda channel qttesting.

I didn't build these for macOS as we don't use JPEG nor libpng dependencies on that OS and do hopefully are already compatible.

Please let me know how you get on as these builds are brand new.

**Comment by robintw** [comment]
Is there a way to set my conda-forge package to pick up the Qt5 package from the `qttesting` channel, rather than `conda-forge` directly?

**Comment by mingwandroid** [comment]
Since there is no conda-forge Qt5 package there is no way it could be picked up from there (provided you set the dependency specs to qt 5.6.* or so).

If you want to ensure that conda picks Qt5 and only Qt5 from qttesting, copy the tar.bz2 into COMDA_PREFIX/conda-build/PLATFORM then run conda index . in that directory, and do not use the qttesting channel.

**Comment by ocefpaf** [comment]
@robintw and @mingwandroid we can temporally hard-code the `qttesting` in the CIs just to test it and remove it before merging this PR.

**Comment by ocefpaf** [comment]
@mingwandroid it seems that the `Qt5` in `qttesting` is built with `icu 54.*` while `conda-forge` is `icu 56.*` :unamused:

**Comment by mingwandroid** [comment]
`conda-defaults` does not have `icu 56`.

**Comment by ocefpaf** [comment]
> `conda-defaults` does not have `icu 56`.

I know that `Qt5` is a beast, but would you mind creating a version with `icu 56.*`, in fact using all conda-forge dependencies, so we can manually upload that to the `conda-forge`?

Our lack of `Qt5` is starting to block PRs like this one.

**Comment by mingwandroid** [comment]
I've spent the best part of two days on this already and I can't afford to spend any more time :-( I think the goal was to remove the incompatibilities below Qt, and not strictly for Qt itself.

If I were to rebuild ICU and all its dependencies I would prefer to build ICU 58 as it is a significant effort (I would need to rebuild Boost) and the further ahead in versions I can jump the less often I need to do it (since ICU 58 is the last version to support XP and Vista, staying at that one for a while makes a lot of sense).

There's also the option that conda-forge provide an ICU 54 package and another Boost that is linked to that.

I cannot contemplate building `conda defaults` and `conda-forge` packages, it would be unfeasible for me, not only from a time perspective but also because brute force feels like the wrong way to fix this problem.

**Comment by ocefpaf** [comment]
No problem @mingwandroid! Thanks for the effort you already put into this.

I will see if we can get a `icu 56.*` version first. Then maybe we (conda-forge) should work on `icu 58.*` upgrade as you mentioned. However, we should coordinate that so `defaults` and `conda-forge` are in the same page to avoid future pinning mismatch like this one.

**Comment by mingwandroid** [comment]
Yes, we've take a step towards better compat. with png and jpeg here, but we need to keep taking steps as time allows.

> I will see if we can get a icu 56.* version first. 

You mean 54 I guess? If you guys move to 58 I'll push for us doing the same when I have time (Feb, probably).

**Comment by ocefpaf** [comment]
> You mean 54 I guess?

I mean 56 because that is what we have in our [pinning script](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L41)

> If you guys move to 58 I'll push for us doing the same when I have time (Feb, probably).

I will start working on that immediately. I will keep you posted in the PRs.

Thanks @mingwandroid!

**Pull request closed without merging**
