### PR TITLE
Add recipe for enum-compat

### PR DESCRIPTION
**Pull request by stuartcampbell**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
LGTM, although I'm a bit curious how it would be used.

**Comment by stuartcampbell** [comment]
Hey @CJ-Wright  - It's basically a way to always make sure we have the `enum` package, which is obviously in newer pythons, so does nothing.  This way you can have a simple dependency for other packages (you will see in my next PR) 😄 

Now, if there is a way to do version dependent requirements - then I might not need this recipe after all.

**Comment by CJ-Wright** [comment]
There is for conda!
for example these packages are only installed on py2k
https://github.com/conda-forge/staged-recipes/commit/bc3114bc0d7038518bc0620a1ce2303a5c143c4e#diff-7582036a741680a05cc7472b3c8d8c61R31

**Comment by stuartcampbell** [comment]
Thank you - what versions of python does conda-forge support ?  If it's no too many then I can delete this PR and just use this in my next recipe.

**Comment by CJ-Wright** [comment]
2.7, 3.5, and 3.6 actively, we may have recipes for older pythons but I don't think we're going to publish new recipes for 2.6 or 3.4.

**Comment by CJ-Wright** [comment]
You could also have this recipe build only for py2k.
```
build:
  skip: True  # [py3k]
```

**Comment by stuartcampbell** [comment]
Thanks @CJ-Wright I think I will close this, move onto the recipe I really need and come back if required.  Many Thanks.

**Comment by CJ-Wright** [comment]
Feel free to ping me when you put the recipe up.

**Pull request closed without merging**
