### PR TITLE
GDCM

### PR DESCRIPTION
**Pull request by ivoflipse**
Here's our recipe for GDCM, which is very useful for extending the IO capabilities of pydicom

### CODE REVIEW

**Comment by ivoflipse** [comment]
The Travis error is the following:

```
Removing old work directory
Source cache directory is: /Users/travis/miniconda/conda-bld/src_cache
Downloading source to cache: 7c72a07e48c81e364a654e192515adc1e30a23f6.zip
Downloading https://github.com/malaterre/GDCM/archive/7c72a07e48c81e364a654e192515adc1e30a23f6.zip
Success
Extracting download
Package: gdcm-2.6.3-py27_0
source tree in: /Users/travis/miniconda/conda-bld/work/GDCM-7c72a07e48c81e364a654e192515adc1e30a23f6
++ uname
+ '[' Darwin == Linux ']'
+ make -j2
make: *** No targets specified and no makefile found.  Stop.
Command failed: /bin/bash -x -e /Users/travis/build/conda-forge/staged-recipes/recipes/gdcm/build.sh

The command "if [ "$ACTION" = "create-feedstocks-on-merge" ]; 
then echo "Creating feedstocks from the recipe(s) (this simply lints the recipe if this isn't a merged commit to master)."; 
git config --global user.name "Travis-CI on github.com/conda-forge/staged-recipes"; 
git config --global user.email "conda-forge@googlegroups.com"; 
source ./.CI/create_feedstocks; elif [ "$ACTION" = "build-all" ]; 
then echo "Building all recipes."; source ./.CI/build_all; fi" exited with 1.
```

Guess I picked the wrong source perhaps?

**Comment by ivoflipse** [comment]
Also not 100% sure why we picked this specific file and not the one from the release page, since its filename is way nicer

**Comment by ivoflipse** [comment]
Right, after running into the error again, now I understand that our recipe doesn't support OSX yet. Does anyone have a good example of an existing from which I can probably copy/paste most of the required boilerplate?

**Comment by ivoflipse** [comment]
Also I don't understand why Python 2.7 x64 failed on AppVeyor, the error points at CMake not being able to find the compilers:
```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:11 (project):
  No CMAKE_C_COMPILER could be found.
CMake Error at CMakeLists.txt:11 (project):
  No CMAKE_CXX_COMPILER could be found.
```
Am I missing something special here?

**Comment by astrofrog** [comment]
Just wanted to say I'd really like to see GDCM in conda-forge, so +1 to this. I'm not sure what's causing the issues, but I'll try and take a look to see if I have any suggestions.

**Comment by astrofrog** [comment]
So it looks like some of the ``build.sh`` should actually work on MacOS X too. I would actually suggest starting off assuming it will work and then seeing at what points errors are actually raised. Trying to build this locally after removing the if statement to check for linux, it got to 100% of the cmake compilation then crashed with:

```
Scanning dependencies of target _gdcmswig
make[2]: *** No rule to make target `/Users/tom/miniconda3/envs/_build/lib/libpython3.5m.so', needed by `bin/_gdcmswig.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

**Comment by astrofrog** [comment]
@ivoflipse - ok, so I figured it out - on Mac, you can use **exactly** the same ``build.sh`` script as for Linux, except that ``.so`` should be ``.dylib``. So I think you can probably just put the ``if`` statement about that part of the script (``.so`` appears twice). I managed to otherwise build a functional conda package on MacOS X with this!

**Comment by ivoflipse** [comment]
Yeah this recipe got somewhat lost between all the other recipes we've been making, since we already had our own version of the package. But I'm sure we can fix the errors in this recipe based on what we learned there. 

cc @Korijn

**Comment by Korijn** [comment]
Yeah, we recently learned a lot of new things about this. I'll update this recipe asap.

Thanks for test driving the unix side of this one, @astrofrog !

**Comment by Korijn** [comment]
* Updated the recipe to use `ninja`.
* Harmonized the unix and windows build scripts.
* Added in OS X / Unix distinction for `.so`/`.dylib`.

@astrofrog Would you like to be listed as a maintainer in the recipe?

@jakirkham Is there a possibility we could include this muck in the `toolchain`?

```
PYTHON_INCLUDE="${PREFIX}/include/python${PY_VER}"
if [ ! -d $PYTHON_INCLUDE ]; then
    PYTHON_INCLUDE="${PREFIX}/include/python${PY_VER}m"
fi

PYTHON_LIBRARY_EXT="so"
if [ `uname` = "Darwin" ] ; then
    PYTHON_LIBRARY_EXT="dylib"
fi

PYTHON_LIBRARY="${PREFIX}/lib/libpython${PY_VER}.${PYTHON_LIBRARY_EXT}"
if [ ! -f $PYTHON_LIBRARY ]; then
    PYTHON_LIBRARY="${PREFIX}/lib/libpython${PY_VER}m.${PYTHON_LIBRARY_EXT}"
fi
```

**Comment by astrofrog** [comment]
@Korijn - you don't need to add me as a maintainer, but thanks for asking! :) (I don't know enough about this specific package to trust myself with the maintenance of the conda recipes)

**Comment by Korijn** [comment]
* AppVeyor failed on a timeout with github. Looks like I don't have rights to restart that job. @jakirkham or @ocefpaf would you kindly...? :)

**Comment by ocefpaf** [comment]
> AppVeyor failed on a timeout with github. Looks like I don't have rights to restart that job

Done.

PS: I'd rather restart and I will gladly do that for you, but if we don't respond in time the trick is to either send a new commit and/or try to close/open the PR.

**Comment by Korijn** [comment]
Everything passed :tada: except for the `create-feedstocks-on-merge` job on TravisCI which seems to be pending indefinitely...

**Comment by ocefpaf** [comment]
> Everything passed :tada: except for the `create-feedstocks-on-merge` job on TravisCI which seems to be pending indefinitely...

We are having some issues with Travis. I will merge this as soon as we fixe them. Thanks @Korijn!

**Comment by astrofrog** [comment]
Great! Looking forward to using these :)

**Comment by astrofrog** [comment]
@ocefpaf - it looks like Travis finally ran that job... and failed due to a GitHub timeout I think.

**Comment by ocefpaf** [comment]
> @ocefpaf - it looks like Travis finally ran that job... and failed due to a GitHub timeout I think.

I restarted just that test. Let's see if it works now.

**Comment by Korijn** [comment]
Unfortunately:

```
$ git clone --depth=50 https://github.com/conda-forge/staged-recipes.git conda-forge/staged-recipes
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by ocefpaf** [comment]
@Korijn I restarted it again, but Travis-CI is still not 100% operational: https://twitter.com/traviscistatus?lang=en

**Comment by Korijn** [comment]
@ocefpaf :tada:

**Comment by ocefpaf** [comment]
Awesome! @Korijn master Travis-ci is still behind, but I am merging this. Hopefully the recipe won't get deleted before the feedstock is completed.

**Comment by Korijn** [comment]
I'll keep the branch on our fork around to be sure.

**Pull request merged**
