### PR TITLE
Added r-rstac feedstock

### PR DESCRIPTION
**Pull request by TomAugspurger**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Checking with some maintainers of rstac (@gqueiroz, @rolfsimoes, @OldLipe), are any of you interested in being maintainers of this conda-forge recipe? If you've never maintained a conda-forge recipe before, it's pretty hands-off. It's mostly automated by bots watching PyPI / CRAN for releases and then making pull requests with the updated information. https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role. has more information.

If you are interested in helping maintain things, then let me know with a comment here and I'll add you to the maintainers list: https://github.com/conda-forge/staged-recipes/pull/14438/files#diff-14309d740fc807cd461f9367f1f7ce6b33639521b26cb8b0e0b01f538fae2660R57

**Comment by dbast** [comment]
thx!

**Comment by TomAugspurger** [comment]
Thanks Daniel!

**Comment by gqueiroz** [comment]
Hi @TomAugspurger, many thanks for the innitiative! Very Nice!
I have never maintained a conda-forge package but I think it would be a great contribution and we could help also.
Please, you can add myself, @rolfsimoes  and @OldLipe.
Many thanks!

**Comment by TomAugspurger** [comment]
Great! I just opened https://github.com/conda-forge/r-rstac-feedstock/pull/1 adding you all.

**Pull request merged**
