### PR TITLE
Add Bazel recipe

### PR DESCRIPTION
**Pull request by 183amir**
From here: http://blog.abysm.org/2016/06/building-tensorflow-centos-6/

### CODE REVIEW

**Comment by hadim** [comment]
Any news here ?

**Comment by hadim** [comment]
I guess we are waiting for a java package in conda-forge : https://github.com/conda-forge/staged-recipes/pull/476

**Comment by hadim** [comment]
Ok I didn't see the `yum_requirements.txt`... No need for a java package then.

**Comment by 183amir** [comment]
Please see here https://github.com/conda-forge/tensorflow-feedstock/pull/12

**Comment by jakirkham** [comment]
Basically this PR has some issues that no one has had time to figure out. If you have a need to get this working, I'm sure @183amir would welcome PRs.

**Comment by jjhelmus** [comment]
I've opened #3262 with a updated version of Bazel.

**Comment by jakirkham** [comment]
Superceded by PR ( https://github.com/conda-forge/staged-recipes/pull/3262 ). Thanks for giving this a go, @183amir. Also feel free to add yourself to the feedstock should it be of interest.

**Pull request closed without merging**
