### PR TITLE
Add recipe for fastprogress

### PR DESCRIPTION
**Pull request by andersy005**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by andersy005** [comment]
It appears that the previous versions of `fastprogress` weren't packaged properly. Some crucial configuration files weren't specified in `MANIFEST.in`. As a result, the source distributions (tarbar) doesn't have these configuration files. **We will have to wait for the next release**

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by andersy005** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
I realized that I tried to ping the webservice bot to re-render this back at the beginning of March, but that service doesn't work on `staged-recipes`. My apologies for the confusion. You just need to do something like the following while in the branch you are using for this PR (untested):

```
$ git remote add upstream https://github.com/conda-forge/staged-recipes.git
$ git fetch upstream
$ get merge upstream/master
```

and this will pull in updates since this PR was initially made.

**Comment by andersy005** [comment]
Done!

**Pull request merged**
