### PR TITLE
perl recipes batch 1

### PR DESCRIPTION
**Pull request by jerowe**

### CODE REVIEW

**Comment by jerowe** [comment]
@scopatz  - I keep getting an error that perl-app-cpanminus is not in the channels.

```
> anaconda show conda-forge/perl-app-cpanminus
Using Anaconda API: https://api.anaconda.org
Name:    perl-app-cpanminus
Summary: get, unpack build and install modules from CPAN
Access:  public
Package Types:  conda
Versions:
   + 1.7043

To install this package with conda run:
     conda install --channel https://conda.anaconda.org/conda-forge perl-app-cpanminus
```

It does seem to be there though...

**Comment by scopatz** [comment]
@jerowe - hmm that may be because it is only available for OSX-64 for some reason: https://anaconda.org/conda-forge/perl-app-cpanminus  The other platforms aren't present

**Comment by jerowe** [comment]
It is only available on osx!

```
➜  ~ anaconda show conda-forge/perl-app-cpanminus
Using Anaconda API: https://api.anaconda.org
Name:    perl-app-cpanminus
Summary: get, unpack build and install modules from CPAN
Access:  public
Package Types:  conda
Versions:
   + 1.7043

To install this package with conda run:
     conda install --channel https://conda.anaconda.org/conda-forge perl-app-cpanminus
➜  ~ anaconda show conda-forge/perl-app-cpanminus/1.7043
Using Anaconda API: https://api.anaconda.org
version 1.7043
   + osx-64/perl-app-cpanminus-1.7043-pl5.20.3.1_0.tar.bz2
   + osx-64/perl-app-cpanminus-1.7043-pl5.22.0.1_0.tar.bz2
   + osx-64/perl-app-cpanminus-1.7043-pl5.22.2.1_0.tar.bz2
None
```

I nearly broke my head over getting it to build on windows. ;-)

**Comment by jerowe** [comment]
@scoptaz - how do we get perl-app-cpanminus available for linux as well?

**Comment by scopatz** [comment]
A pull request to the perl-app-cpanminus feedstock that bumps the build number in the recipe should trigger a rebuild.

**Comment by scopatz** [comment]
And upload a linux package

**Comment by jerowe** [comment]
@conda-forge/core, any ideas why this is building against     `perl:            5.26.0-hae598fd_0 defaults`   ? It is passing for other perls, but failing on this one.

**Comment by jerowe** [comment]
Summary of my perl5 (revision 5 version 22 subversion 0
`gccversion='4.8.2 20140120 (Red Hat 4.8.2-15)'`

Summary of my perl5 (revision 5 version 22 subversion 2) 
`gccversion='4.8.2 20140120 (Red Hat 4.8.2-15)'`

Summary of my perl5 (revision 5 version 26 subversion 0)
 `gccversion='7.2.0'`

Where is this gcc 7.2.0 coming from?

**Comment by jerowe** [comment]
@conda-forge/core, should this be building against perl 5.26 ? Perl 5.26 is from defaults, and uses a different compiler.

**Pull request closed without merging**
