### PR TITLE
Add r-fs

### PR DESCRIPTION
**Pull request by nick-youngblut**

### CODE REVIEW

**Comment by nick-youngblut** [comment]
@mariusvniekerk & @bgruening, I've skipped the windows build for `r-fs` because the build failed due to a missing R package dependency for windows. Do you want me to try and fix the windows dependency or are you OK with skipping the win build? The same question goes for the PRs for `r-mcmcglmm` (#6000), `r-ggplotify` (#6001), and `r-statnet.common` (#6002). As I stated before, it appears that many R packages on conda-forge are missing a windows build, so it may take a large overhaul of many R package recipes to get all of the needed windows dependencies in the dependency hierarchy.

**Comment by bgruening** [comment]
It would be nice if you can try to fix the windows builds, I hope its easy as rerender the packages with win enabled. If this does not work out, it would be nice to leave a comment why you have skiped the build, meaning which package is missing. I guess someone of us needs to do this at some point :(

**Comment by nick-youngblut** [comment]
Alright, I'll give it a try. I'm guessing that some fundamental R packages were added conda-forge without a win build, which then opened the pandoras box for many subsequent R packages to be added to conda-forge while lacking win builds.

**Comment by nick-youngblut** [comment]
@bgruening the `r-fs` win build failed due to:

```
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - m2-automake
[...]
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'m2-automake'}
```

As far as I can tell `m2-automake` is only available from a non-conda-forge channel (the [mysys2 channel](https://anaconda.org/msys2/m2-automake-wrapper)) and only available for win32 + win64 (which you might expect, given it's purpose). 

The requirements for conda-forge recipes is to have all dependencies on conda-forge (if at all possible). However, conda-forge also requires builds for windows & nix platforms. I could try to create a conda-forge recipe based on the [mysys2 channel recipe](https://anaconda.org/msys2/m2-automake-wrapper), but it only is set up for windows builds. I'm not sure what to do about this.

**Comment by bgruening** [comment]
Hi NIck, thanks for looking into it. conda-forge is allowed to use default packages, and m2 packages are coming from defaults, that should be perfectly fine. So there needs to be an other reason.

**Comment by nick-youngblut** [comment]
I don't know what you mean by "there needs to be another reason".  Should I try to change the dependencies somehow to try and avoid the use of `m2-automake` for win64? This is just going to be trial-and-error on my part. 

In case it helps, the entire failed win build is:

```
Build started
git clone -q https://github.com/conda-forge/staged-recipes.git C:\projects\staged-recipes
git fetch -q origin +refs/pull/6059/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py', 'ff_ci_pr_build.py')"
ff_ci_pr_build -v --ci "appveyor" "%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%" "%APPVEYOR_BUILD_NUMBER%" "%APPVEYOR_PULL_REQUEST_NUMBER%"
Checking to see if this PR build is outdated.
del ff_ci_pr_build.py
echo Finding recipes merged in master and removing them.
Finding recipes merged in master and removing them.
cd recipes
for /f "tokens=*" %%a in ('git ls-tree --name-only master -- .') do rmdir /s /q %%a && echo Removing recipe: %%a
Removing recipe: example
cd ..
rmdir C:\cygwin /s /q
call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
conda.exe config --add channels conda-forge
conda.exe config --set show_channel_urls true
appveyor-retry conda.exe update --yes --quiet conda
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Miniconda36-x64
  added / updated specs: 
    - conda
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2o             |           vc14_0         5.4 MB  conda-forge
    ca-certificates-2018.4.16  |                0         176 KB  conda-forge
    yaml-0.1.7                 |           vc14_0         103 KB  conda-forge
    conda-4.5.4                |           py36_0         650 KB  conda-forge
    certifi-2018.4.16          |           py36_0         143 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.4 MB
The following packages will be UPDATED:
    ca-certificates: 2018.03.07-0      defaults --> 2018.4.16-0      conda-forge
    certifi:         2018.4.16-py36_0  defaults --> 2018.4.16-py36_0 conda-forge
    conda:           4.5.1-py36_0      defaults --> 4.5.4-py36_0     conda-forge
    openssl:         1.0.2o-h8ea7d77_0 defaults --> 1.0.2o-vc14_0    conda-forge [vc14]
The following packages will be DOWNGRADED:
    yaml:            0.1.7-hc54c509_2  defaults --> 0.1.7-vc14_0     conda-forge [vc14]
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
appveyor-retry conda.exe install --yes --quiet conda-forge-pinning conda-forge-ci-setup=1.* networkx
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Miniconda36-x64
  added / updated specs: 
    - conda-forge-ci-setup=1
    - conda-forge-pinning
    - networkx
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    markupsafe-1.0             |           py36_0          26 KB  conda-forge
    filelock-3.0.4             |           py36_0          12 KB  conda-forge
    conda-build-3.10.7         |           py36_1         450 KB  conda-forge
    pyyaml-3.12                |           py36_1         132 KB  conda-forge
    clyent-1.2.2               |           py36_0          18 KB  conda-forge
    conda-forge-pinning-2018.05.22|                0           4 KB  conda-forge
    conda-forge-ci-setup-1.3.5 |                0           8 KB  conda-forge
    jsonschema-2.6.0           |           py36_1          83 KB  conda-forge
    ipython_genutils-0.2.0     |           py36_0          37 KB  conda-forge
    glob2-0.6                  |             py_0          10 KB  conda-forge
    anaconda-client-1.6.14     |             py_0          67 KB  conda-forge
    psutil-5.4.6               |           py36_0         320 KB  conda-forge
    python-dateutil-2.7.3      |             py_0         202 KB  conda-forge
    jupyter_core-4.4.0         |             py_0          44 KB  conda-forge
    vs2008_express_vc_python_patch-1.0.0|                0           3 KB  conda-forge
    pkginfo-1.4.2              |           py36_0          57 KB  conda-forge
    pytz-2018.4                |             py_0         215 KB  conda-forge
    decorator-4.3.0            |             py_0          10 KB  conda-forge
    conda-verify-2.0.0         |           py36_0          60 KB  conda-forge
    networkx-2.1               |           py36_0         1.9 MB  conda-forge
    jinja2-2.10                |           py36_0         184 KB  conda-forge
    nbformat-4.4.0             |           py36_0         160 KB  conda-forge
    traitlets-4.3.2            |           py36_0         132 KB  conda-forge
    beautifulsoup4-4.6.0       |           py36_0         134 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.2 MB
The following NEW packages will be INSTALLED:
    anaconda-client:                1.6.14-py_0   conda-forge
    beautifulsoup4:                 4.6.0-py36_0  conda-forge
    clyent:                         1.2.2-py36_0  conda-forge
    conda-build:                    3.10.7-py36_1 conda-forge
    conda-forge-ci-setup:           1.3.5-0       conda-forge
    conda-forge-pinning:            2018.05.22-0  conda-forge
    conda-verify:                   2.0.0-py36_0  conda-forge
    decorator:                      4.3.0-py_0    conda-forge
    filelock:                       3.0.4-py36_0  conda-forge
    glob2:                          0.6-py_0      conda-forge
    ipython_genutils:               0.2.0-py36_0  conda-forge
    jinja2:                         2.10-py36_0   conda-forge
    jsonschema:                     2.6.0-py36_1  conda-forge
    jupyter_core:                   4.4.0-py_0    conda-forge
    markupsafe:                     1.0-py36_0    conda-forge
    nbformat:                       4.4.0-py36_0  conda-forge
    networkx:                       2.1-py36_0    conda-forge
    pkginfo:                        1.4.2-py36_0  conda-forge
    psutil:                         5.4.6-py36_0  conda-forge
    python-dateutil:                2.7.3-py_0    conda-forge
    pytz:                           2018.4-py_0   conda-forge
    pyyaml:                         3.12-py36_1   conda-forge
    traitlets:                      4.3.2-py36_0  conda-forge
    vs2008_express_vc_python_patch: 1.0.0-0       conda-forge
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
appveyor-retry run_conda_forge_build_setup
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64 already exists.
        1 file(s) copied.
     active environment : base
    active env location : C:\Miniconda36-x64
            shell level : 1
       user config file : C:\Users\appveyor\.condarc
 populated config files : C:\Users\appveyor\.condarc
          conda version : 4.5.4
    conda-build version : 3.10.7
         python version : 3.6.5.final.0
       base environment : C:\Miniconda36-x64  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
                          C:\Users\appveyor\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
==> C:\Users\appveyor\.condarc <==
add_pip_as_python_dependency: False
auto_update_conda: False
channels:
  - conda-forge
  - defaults
show_channel_urls: True
==> envvars <==
bld_path: C:\\bld\\
# packages in environment at C:\Miniconda36-x64:
#
# Name                    Version                   Build  Channel
anaconda-client           1.6.14                     py_0    conda-forge
asn1crypto                0.24.0                   py36_0    defaults
beautifulsoup4            4.6.0                    py36_0    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h945400d_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
clyent                    1.2.2                    py36_0    conda-forge
conda                     4.5.4                    py36_0    conda-forge
conda-build               3.10.7                   py36_1    conda-forge
conda-env                 2.6.0                h36134e3_1    defaults
conda-forge-ci-setup      1.3.5                         0    conda-forge
conda-forge-pinning       2018.05.22                    0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.2.2            py36hfa6e2cd_0    defaults
decorator                 4.3.0                      py_0    conda-forge
filelock                  3.0.4                    py36_0    conda-forge
glob2                     0.6                        py_0    conda-forge
idna                      2.6              py36h148d497_1    defaults
ipython_genutils          0.2.0                    py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
menuinst                  1.4.11           py36hfa6e2cd_0    defaults
nbformat                  4.4.0                    py36_0    conda-forge
networkx                  2.1                      py36_0    conda-forge
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
pip                       9.0.3                    py36_0    defaults
pkginfo                   1.4.2                    py36_0    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pysocks                   1.6.8                    py36_0    defaults
python                    3.6.5                h0c2934d_0    defaults
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pywin32                   223              py36hfa6e2cd_0    defaults
pyyaml                    3.12                     py36_1    conda-forge
requests                  2.18.4           py36h4371aae_1    defaults
ruamel_yaml               0.15.35          py36hfa6e2cd_1    defaults
setuptools                39.0.1                   py36_0    defaults
six                       1.11.0           py36h4db2310_1    defaults
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2008_express_vc_python_patch 1.0.0                         0    conda-forge
vs2015_runtime            14.0.25123                    3    defaults
wheel                     0.31.0                   py36_0    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
python .ci_support\build_all.py recipes --arch %PLATFORM%
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
rendering C:\projects\staged-recipes\recipes\r-fs for win-64
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Dependency m2-automake, version any is not installable from your channels: ['local', 'conda-forge', 'defaults', 'conda-forge', 'defaults'] with subdir win-64.  Seeing if we can build it...
Dependency m2-automake, version any is not installable from your channels: ['local', 'conda-forge', 'defaults', 'conda-forge', 'defaults'] with subdir win-64.  Seeing if we can build it...
Computed that there are 2 distributions to build from 1 recipes
Resolved dependencies, will be built in the following order:
    r-fs-1.2.3-c_compiler_vs2015-cxx_compiler_vs2015-on-win-64
    r-fs-1.2.3-c_compiler_vs2008-cxx_compiler_vs2008-on-win-64
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from C:\Miniconda36-x64\conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from C:\Miniconda36-x64\conda_build_config.yaml
Adding in variants from C:\projects\staged-recipes\.ci_support\win64.yaml
INFO:conda_build.variants:Adding in variants from C:\projects\staged-recipes\.ci_support\win64.yaml
Attempting to finalize metadata for r-fs
INFO:conda_build.metadata:Attempting to finalize metadata for r-fs
Solving environment: ...working... failed
Leaving build/test directories:
  Work:
 C:\bld\work 
  Test:
 C:\bld\test_tmp 
Leaving build/test environments:
  Test:
source activate  C:\bld\_test_env 
  Build:
source activate  C:\bld\_build_env 
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 717, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Miniconda36-x64\lib\site-packages\conda\common\io.py", line 46, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda36-x64\lib\site-packages\conda\plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\solve.py", line 505, in solve_for_transaction
    force_remove, force_reinstall)
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\solve.py", line 438, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\solve.py", line 318, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 705, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 254, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "C:\Miniconda36-x64\lib\site-packages\conda\resolve.py", line 172, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - m2-automake
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".ci_support\build_all.py", line 83, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 73, in build_all
    conda_build.api.build(list(d.keys()), config=config)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2177, in build_tree
    notest=notest,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1202, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 666, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 1969, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 698, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 456, in finalize_metadata
    exclude_pattern)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 333, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 321, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 124, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 719, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'m2-automake'}
```

Is there a good way to search through the AppVeyor build history for specific PRs? For fixing the win builds of other R package PRs, I need to look at the failed win builds which ran many days ago (or re-run the checks).

**Comment by bgruening** [comment]
@nick-youngblut we just fixed a bug in the r_skeleton helper script, that might address the windows errors which you have seen.

**Comment by nick-youngblut** [comment]
@bgruening It appears that I'm still getting the same error when using conda-build 3.10.9-py36_0 and the most up-to-date version of `conda_r_skeleton_helper`: 

```
conda.exceptions.ResolvePackageNotFound: 
  - m2-automake
[...]
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'m2-automake'}
```

Also, the version of `conda_r_skeleton_helper` added `build_merge_host` to the `meta.yaml` file, which causing problems with the conda-forge-linter.

**Comment by bgruening** [comment]
Narf, to my knowledge the `build_merge_host` is needed to prevent the other error, so it seems we need to fix the linter?
ping @conda-forge-admin any other idea?

**Comment by nick-youngblut** [comment]
@bgruening any progress on fixing the linter? I'm guessing that I'm going to have the same issue will adding any new R package until this linter issue is fixed.

**Comment by bgruening** [comment]
I don't know, I think it is fixed.

**Pull request merged**
