### PR TITLE
adding apptainer

### PR DESCRIPTION
**Pull request by ngam**
Adding apptainer (singularity's replacement)

https://apptainer.org/news/community-announcement-20211130

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge/staged-recipes ready to go but be aware of the drama surrounding singularity: see my pr for singularityce for more details: https://github.com/conda-forge/staged-recipes/pull/17084 and the discussion in singularity-feedstock: https://github.com/conda-forge/singularity-feedstock/issues/49

**Comment by ngam** [comment]
@conda-forge/staged-recipes, gentle reminder to review and merge this at your convenience :)

**Comment by ngam** [comment]
@conda-forge/staged-recipes / @conda-forge/core, another gentle reminder to review and merge this, thanks

**Comment by ngam** [comment]
@ocefpaf gentle nudge to review/merge this if you can, thanks!

**Comment by ocefpaf** [comment]
> @ocefpaf gentle nudge to review/merge this if you can, thanks!

Not the best reviewer for go, sorry. I'll leave this one to the go experts.

**Comment by ngam** [comment]
> > @ocefpaf gentle nudge to review/merge this if you can, thanks!
> 
> Not the best reviewer for go, sorry. I'll leave this one to the go experts.

Thank you still. Enjoy the holidays!

**Comment by ngam** [comment]
@chrisburr apptainer is the followup to singularity (in this prerelease form, it is almost identical to hpcng singularity. However, they're making a looooooooot of changes, and so I wanted to get us ahead of the divergence, as I mentioned in the singularity feeedstock). Could you review and merge when you have a chance? Thanks!

**Comment by ngam** [comment]
@conda-forge/staged-recipes, this has been ready for while, please review/merge, thanks

**Comment by ngam** [comment]
Hi @conda-forge/staged-recipes, I would like us to get this to a feedstock so that we can start making the necessary edits and testing. The upstream has a release candidate now: https://github.com/apptainer/apptainer/releases

@chrisburr, are you interested in being a maintainer here too? This project will essentially replace singularity proper (you're the maintainer of that feedstock).

**Comment by ngam** [comment]
[closing due to inactivity.]

**Pull request closed without merging**
