### PR TITLE
package cached_path

### PR DESCRIPTION
**Pull request by h-vetinari**
Necessary for https://github.com/conda-forge/allennlp-feedstock/pull/31

### CODE REVIEW

**Comment by h-vetinari** [comment]
So the upstream declaration on `overrides >=3.1,<6.2` is actually not correct, because it _doesn't_ work with 3.1, but unfortunately the feedstock seems pretty dead. I'll try reviving it...

**Comment by h-vetinari** [comment]
Needs https://github.com/conda-forge/overrides-feedstock/pull/20

**Comment by h-vetinari** [comment]
CC @conda-forge/allenlp @dirkgr @AkshitaB @epwalsh 

Just FYI that I'm packaging `cached_path` for conda-forge (not least since it became a dependency in allennlp 2.8). Anyone interested to participate in the feedstock is welcome. 🙃

**Comment by h-vetinari** [comment]
@AkshitaB  @epwalsh @dirkgr, I'm guessing windows is not really explicitly supported so far? E.g.
```
ValueError: unable to parse %SRC_DIR%\test_fixtures\does_not_exist\fake_file.tar.gz as a URL or as a local path
```
would seem to be avoidable, but not implemented yet?

The test suite results on windows actually don't look too bad:
```
=========================== short test summary info ===========================
FAILED tests/cached_path_test.py::TestCachedPathHttp::test_http_200 - ValueEr...
FAILED tests/file_lock_test.py::TestFileLock::test_locking - PermissionError:...
ERROR tests/file_lock_test.py::TestFileLock::test_locking - PermissionError: ...
============= 2 failed, 26 passed, 5 warnings, 1 error in 16.57s ==============
```

The two `PermissionErrors` on the locking are not surprising to me, and I would propose to skip them - could you please confirm? For parsing paths with backslashes as a "local path", I could patch that in, but would prefer for you to do that upstream, and skip the test in the meantime.

**Comment by epwalsh** [comment]
Hey @h-vetinari, thanks for digging into this. It would be great if we could support windows, especially if it doesn't take much effort. Would you be interested in making a PR in cached-path with those changes? If not I might be able to get to it tomorrow.

**Comment by h-vetinari** [comment]
Hey @epwalsh, I'm skipping windows here for now to unblock allennlp 2.8 (which is not yet building for windows yet anyway due to missing pytorch for windows in conda-forge), but we can follow up on this of course.

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes, this is ready, please review when possible. :)

**Pull request merged**
