### PR TITLE
Blast 2.2.26

### PR DESCRIPTION
**Pull request by sjanssen2**
Here is a conda recipe for the legacy blast version 2.2.26 a heuristic pairwise alignment problem to search genes/proteins in huge sequencing databases: https://en.wikipedia.org/wiki/BLAST

We need one specific feature for this rather old version of the program for the Microbiome Immunity Project: https://www.worldcommunitygrid.org/research/mip1/overview.do

This is my very first conda recipe that I PR to conda-forge. Please be thorough in you review to give me the chance how to do it correct. I am planning to push a couple of other bioinformatics programs as well.

### CODE REVIEW

**Comment by jakirkham** [comment]
Is the plan to move this to conda-forge from bioconda, @bgruening?

**Comment by sjanssen2** [comment]
@jakirkham not exactly. We want to migrate our recipes from https://anaconda.org/biocore/. We found that conda-forge might be the better place than bioconda due to it's larger community and better infrastructure.
Bioconda right now hosts an older version https://github.com/bioconda/bioconda-recipes/tree/master/recipes/blast-legacy/2.2.22 with some issues in their recipe. No useful test, no setting of the important environment variables, i.e. no proper relocation.

**Comment by bgruening** [comment]
I will stay out of this discussion. We tried to get in contact with biocore a few times to join forces but got no answer.

> Bioconda right now hosts an older version https://github.com/bioconda/bioconda-recipes/tree/master/recipes/blast-legacy/2.2.22 with some issues in their recipe.

We do appreciate help/issues and PRs to improve the bioconda packages or our infrastructure. Always eager to discuss your issues @sjanssen2 :)

That said we moved more than 500 packages from bioconda to conda-forge and if @sjanssen2 things this is the best way we don't mind and will help to maintain it here.

**Comment by jakirkham** [comment]
Ah ok. My bad. I saw Blast and knew what it was and just assumed bioconda was involved, but did not check. Sorry for the confusion. 😞

That said, bioconda uses conda-forge as an upstream source and am guessing biocore would like to do the same. So still would like to check in and make sure what we add will work for everyone.

**Pull request closed without merging**
