### PR TITLE
Add recipe for zeep

### PR DESCRIPTION
**Pull request by adament**
Add the Zeep SOAP library. This is a modern and actively maintained SOAP library for Python based on the lxml library.

### CODE REVIEW

**Comment by adament** [comment]
@mvantellingen are you okay with zeep being packaged for conda on conda-forge?

**Comment by mvantellingen** [comment]
@adament Sure, how does it work when I release a new version. Will this be updated automatically?

**Comment by jakirkham** [comment]
Thanks @adament.

**Comment by jakirkham** [comment]
Here are the [details]( https://github.com/conda-forge/staged-recipes#10-what-does-being-a-conda-forge-feedstock-maintainer-entail ) about being a maintainer, @mvantellingen. Currently releases are done by submitting a PR with a version bump and updated checksum from one's forked feedstock repo. Pretty straightforward though not automated. While we are interested in automating it, we have not done that yet. If this seems ok, please add yourself as a maintainer on the feedstock once it is created.

**Comment by mvantellingen** [comment]
Thanks for the reply @jakirkham. Since i'm not using conda forge myself I'll be not maintaining this. Are you interested in doing this for the project @adament ?

**Comment by adament** [comment]
Yes that was my intention. I just found it prudent to make sure you were not opposed to the inclusion of zeep into separate distribution channels from PyPI.

**Pull request merged**
