### PR TITLE
Add itkwidgets recipe

### PR DESCRIPTION
**Pull request by hadim**

### CODE REVIEW

**Comment by hadim** [comment]
@thewtex do you want to be added as a maintainer to this recipe?

**Comment by thewtex** [comment]
> @thewtex do you want to be added as a maintainer to this recipe?

Yes, that would be great.

**Comment by hadim** [comment]
@scopatz can I get a review, please? (who should I ping for review? conda-forge/core?)

**Comment by scopatz** [comment]
You should ping @conda-forge/staged-recipes  :)

**Pull request merged**
