### PR TITLE
Add gdstk

### PR DESCRIPTION
**Pull request by wshanks**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

A few notes:
* ~This is a very new project (the successor to a previous project called) gdspy. The upstream packaging is a little rough. It might be best to wait for a new release so the conda recipe can be more standard (no patches).~ -- no patches needed now.
* ~The patches correct some mistakes that were made in packaging the first source release to PyPI~ -- no patches needed now.
* The recipe builds from the source release on PyPI. The GitHub source tarball is also listed in order to pull down the tests. In the future, perhaps the tests could be skipped and just the PyPI source used. I wanted to make sure the all the builds passed at least one time (they did).

### CODE REVIEW

**Comment by willsALMANJ** [comment]
@conda-forge/help-python-c This PR is ready for review. The main question from me is if it is okay to list the PyPI and GitHub sources and to run the unit tests. The test suite takes 0.3 seconds to run now, so it is not much of a burden. The library is mostly written in C++ and links against LAPACK, so I wanted to make sure it built and linked properly on all architectures, but just doing `import gdstk` checks most of that.

**Comment by willsALMANJ** [comment]
@conda-forge/help-python-c Could we get a review for this?

**Comment by dopplershift** [comment]
Seems reasonable. @willsALMANJ ok with being a maintainer for this recipe?

**Comment by wshanks** [comment]
Oh, I changed my user name from willsALMANJ to wshanks yesterday and haven't gotten everything on GitHub updated yet. I just updated the recipe here.

**Comment by dopplershift** [comment]
@heitzmann are you ok with being a maintainer of this package recipe?

**Comment by wshanks** [comment]
Sorry, I should have called out that @heitzmann said he was willing to be a maintainer in this comment: https://github.com/heitzmann/gdstk/pull/7#issuecomment-707960395

**Review by dopplershift — APPROVED** [review]

**Comment by heitzmann** [comment]
> @heitzmann are you ok with being a maintainer of this package recipe?

Yes, sure! I'd be glad to!

**Pull request merged**
