### PR TITLE
add waybackpy_3.0.2

### PR DESCRIPTION
**Pull request by rafaelrdealmeida**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by rafaelrdealmeida** [comment]
new PR with requested adjustments on old PR see: https://github.com/conda-forge/staged-recipes/pull/17634

**Comment by rafaelrdealmeida** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=446875&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b

**Comment by rafaelrdealmeida** [comment]
@conda-forge/core, please help

**Comment by rafaelrdealmeida** [comment]
> Looks like this might be related to this blob: https://github.com/akamhy/waybackpy/blob/4408c5e2ca8b875fff8db13d8172c5f025b1127e/waybackpy/cli.py#L172-L179

Hi, thanks for the reply!

Any suggestion on how to resolve?

Would I be able to do a test before doing a PR in waybackpy?

cheers

**Comment by akamhy** [comment]
> remove the ASCII art with a patch or skip the test.

I have replaced the art (https://github.com/akamhy/waybackpy/commit/5ea1d3ba4f8f3ba75a47d12c3126ea21970d7c7c), also the problematic art was not really ASCII art. The problem was probably caused because it was not ASCII but Unicode.

And @rafaelrdealmeida I have uploaded a new release to PyPI with the figlet changed.

The newer version is : `3.0.2`
and sha256 is : `4a8b66c5de6c1a62076de798a8b7000cad9782ec7de45ac5dc71cc00a4674c35`

You may either update the values on this PR/create a patch or just skip the tests.

**Comment by rafaelrdealmeida** [comment]
thanks @wolfv, @bollwyvl, @akamhy!

**Pull request merged**
