### PR TITLE
New receipe -- sphinxcontrib-autodoc_doxygen

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by mwcraig** [comment]
@rmcgibbo -- could you please set up circle-ci building on your fork to enable those tests? Documentation at http://conda-forge.github.io/docs/ciservices.html#circleci-linux

**Comment by scopatz** [comment]
Any luck with Circle @rmcgibbo?

**Comment by rmcgibbo** [comment]
Np. I'll give it a try when I get a chance.

**Comment by scopatz** [comment]
Gonna try closing and reopening

**Comment by rmcgibbo** [comment]
(Just enabled circle)

**Comment by scopatz** [comment]
LGTM Thanks!

**Pull request merged**
