### PR TITLE
Add itemloaders

### PR DESCRIPTION
**Pull request by Gallaecio**
[New dependency of Scrapy](https://github.com/conda-forge/scrapy-feedstock/pull/43).

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
  (cc: @wRAR, @dangra, @rmax)
- [x] Tests pass

### CODE REVIEW

**Comment by rmax** [comment]
I confirm being a maintainer of this package.

**Comment by Gallaecio** [comment]
Note: The license file needs to be added manually until a new version of itemloaders with https://github.com/scrapy/itemloaders/pull/18 is released.

**Comment by dangra** [comment]
I confirm being a maintainer for this package.

**Comment by wRAR** [comment]
I'm fine with being a maintainer for itemloaders.

**Comment by Gallaecio** [comment]
@conda-forge/help-python Ready for review!

**Comment by synapticarbors** [comment]
I see the license file was added to the `MANIFEST.in`. When new releases come out, just remember to use the one that comes in the source distribution once it's there.

**Pull request merged**
