### PR TITLE
Move recipes from #7163 to recipes/

### PR DESCRIPTION
**Pull request by chrisburr**
@mariusvniekerk @msarahan This moves the files that were merged in #7163 to the `recipes/` directory and pulls in a few patches that were missing.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I want to reiterate my reservations about this. I would bebin favor of not vendoring clangdev and cling in a recipe. We have gone through a lot of iteration and effort to enable variants of clangdev and llvm to prevent this, and I would prefer this not to be discarded.

I would be in favor of patching the sources in the recpe to depend on cling and not vendoring it.

**Comment by SylvainCorlay** [comment]
@conda-forge/core please take the message above into consideration. We have put a lot of work into the proper packaging of the interpreted c++ stack (and we maintain over 100 feedstocks).

**Comment by scopatz** [comment]
I am a little unsure of what is going on here?  Was a PR merged improperly?

**Comment by SylvainCorlay** [comment]
It was merged while the recipe was added in the wrong directory.

But my reservations and remarks were about this package vendoring clangdev and cling instead of depending on the already existing packages.

**Comment by chrisburr** [comment]
@scopatz #7163 was merged but the recipes were in the base directory of this repository instead of the `recipes/` directory.

@SylvainCorlay I definitely want to get this `ROOT` recipe to depend on the external `clangdev` and `cling` recipes but I think it is going to take a while. Both the `clangdev` and `cling` packages will need to be updated before this is even possible without reverting back to an older version of `ROOT`. While this is being done I would prefer for this package to be available.

**Comment by JohanMabille** [comment]
@chrisburr I understand the difficulties in making `ROOT` depend on external `clangdev` and `cling`, and your will to have this package available soon; however I strongly agree with @SylvainCorlay, a lot of effort has been put in the packaging of `cling` and the built of the interpreted C++ stack on conda-forge. If building `ROOT` against an external `cling` is not possible yet, I think that at least the `clangdev` package could be updated so `ROOT` does not have to vendor it.

**Comment by CJ-Wright** [comment]
Would it be possible to have a print statement at `ROOT` install time, noting that this won't play nice with other cpp projects? At least then people could be aware about potential issues. More extreme versions of this would be some sort of exclusion which causes `cling` and friends to cause an unsolvable graph with `ROOT`.

**Comment by SylvainCorlay** [comment]
I don't think that there is any blocker in the current state of things to use the conda package for clangdev with the clang_variant mutex package.

I don't think that vendoring is really acceptable in general for a package manager. Patching the sources to use external cling looks like the preferable option to me.

**Comment by chrisburr** [comment]
I think this is ready to be merged.

 * The extra patches that are needed have been added to `clangdev` and this recipe no longer vendors it.
 * I'll discuss with the ROOT/cling devs for how to make `cling` an external dependency though this is going to take a while as it will require an updated `cling` package and non-trivial patches to ROOT.
 * I've marked `root` as being in conflict with `cling` for now.

**Comment by SylvainCorlay** [comment]
Awesome! Does it really conflict with cling? I have not looked at the installed files, but it might work since uses a static build of cling.

**Comment by chrisburr** [comment]
I quickly tried at and both ROOT and cling[1] appear to work when installed together. That said the packages have 3 identically named files[2] with different contents and conda just keeps whichever is installed first. I suspect everything is okay provided nobody tries to build against cling but I'd rather be conservative for now.


[1] It's unrelated to this to this but `cling` appears to be broken as it doesn't try to get headers from conda's sysroot and relies on them being available on the host. ROOT's internal cling is okay so I think this will be fixed once there is a new release of cling.

[2] `find /opt/conda/pkgs/ -name 'libcling*'`
```bash
/opt/conda/pkgs/cling-0.5-h6bb024c_1001/lib/libclingUtils.a
/opt/conda/pkgs/cling-0.5-h6bb024c_1001/lib/libclingUserInterface.a
/opt/conda/pkgs/cling-0.5-h6bb024c_1001/lib/libclingMetaProcessor.a
/opt/conda/pkgs/cling-0.5-h6bb024c_1001/lib/libclingInterpreter.a
/opt/conda/pkgs/cling-0.5-h6bb024c_1001/lib/libcling.a
/opt/conda/pkgs/root-6.14.06-py37_blas_openblash33ec4a3_0/lib/libclingUtils.a
/opt/conda/pkgs/root-6.14.06-py37_blas_openblash33ec4a3_0/lib/libclingMetaProcessor.a
/opt/conda/pkgs/root-6.14.06-py37_blas_openblash33ec4a3_0/lib/libclingInterpreter.a
```

**Comment by SylvainCorlay** [comment]
Regarding the incompatibility, I think we need to mark them as incompatible then. We rely on some fixes in the core cling packages that were added as patches to the conda recipe (and were already merged upstream).

**Comment by SylvainCorlay** [comment]
On the subject of cling using system headers, which headers are you refering to? I have not experienced this issue with our build on QuantStack.

**Comment by chrisburr** [comment]
I'll make an issue about it in the `cling-feedstock` repository shortly.

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
:tada:

**Pull request merged**
