### PR TITLE
Add recipe for r-clustersim

### PR DESCRIPTION
**Pull request by npavlovikj**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

I used `conda_r_skeleton_helper` script to create this recipe.

### CODE REVIEW

**Comment by dbast** [comment]
Please re-add the toolchain and ignore the linter. Looks like also `skip: True  # [osx]` is required.

**Comment by npavlovikj** [comment]
Thanks @dbast . Considering the "osx" build, will adding the xorg-* packages help, or I should skip it all together?

**Comment by dbast** [comment]
Well, r-rgl is not available for osx .... see, https://github.com/conda-forge/r-rgl-feedstock/blob/master/recipe/meta.yaml

**Comment by npavlovikj** [comment]
Hmm, looks like the newest version is not available on "osx", but there are older version available in "defaults" that are used for this build.

If you check the older "osx" build log, https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=27706, you will see that "r-rgl=0.99.16=r351hf21c5ad_0" is used here.

**Comment by npavlovikj** [comment]
The "osx" error is:
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error: X11 not found; XQuartz (from www.xquartz.org) is required to run rgl.
ERROR: lazy loading failed for package ‘clusterSim’
(which I don't get when I locally install "r-rgl" via conda).

I tried adding the "mesa" and "libGLU" and "libGL" packages in "yum_requirements.txt", but that didn't work. That is why I was wondering if there is some familiar fix for this type of error.

**Comment by dbast** [comment]
from build log: `r-rgl:              0.99.16-r351hf21c5ad_0     defaults` ... so that osx r-rgl was loaded from defaults not from the conda-forge channel... that is afaik not expected to work ...there is no conda-forge r-rgl packge since long... see https://anaconda.org/conda-forge/r-rgl/files

**Comment by npavlovikj** [comment]
Many thanks for the clarification @dbast , that makes sense now.

**Pull request merged**
