### PR TITLE
parmetis: add recipe

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by isuruf** [comment]
Here's what I got from the website.

> ParMETIS is copyrighted by the Regents of the University of Minnesota. It can be freely used for educational and research purposes by non-profit institutions and US government agencies only. Other organizations are allowed to use ParMETIS only for evaluation purposes, and any further uses will require prior approval. The software may not be sold or redistributed without prior approval. One may make copies of the software for their use provided that the copies, are not sold or distributed, are used under the same terms and conditions.
As unestablished research software, this code is provided on an "as is'' basis without warranty of any kind, either expressed or implied. The downloading, or executing any part of this software constitutes an implicit agreement to these terms. These terms and conditions are subject to change at any time without prior notice.

I don't think we can have this package given that the statement, `The software may not be sold or redistributed without prior approval.` makes it pretty clear we can't.

cc @conda-forge/metis

**Comment by cekees** [comment]
I see. I was thinking you were just hosting the recipes, but I guess the generated binary packages are the issue, correct?

**Comment by isuruf** [comment]
Yes, the binaries can't be distributed.

**Comment by cekees** [comment]
I guess there's no way to turn off exposing the binaries in the conda-forge infrastructure?

**Comment by ocefpaf** [comment]
> I guess there's no way to turn off exposing the binaries in the conda-forge infrastructure?

You can skip all builds. But please add a HUGE warning in the recipe and in the description.

**Comment by jakirkham** [comment]
I suppose you could ask the developers if they/their institution would permit its inclusion into conda-forge. Though would be pretty clear that this means anyone can download the binaries anywhere for any purpose. We lack any control over who can get access and I'm not sure we would want that control even if it were possible.

**Comment by ocefpaf** [comment]
Closing this until we get a permission to re-distribute the binaries.

**Comment by dalcinl** [comment]
@knepley, @minrk, and @dalcinl emailed the author asking for permission to distribute binary packages within the conda-forge effort, and the author agreed. What should I do not to get this PR accepted?

**Comment by jakirkham** [comment]
Looks like this is being pursued again in PR ( https://github.com/conda-forge/staged-recipes/pull/4193 ).

**Pull request closed without merging**
