### PR TITLE
add ete3

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by ltalirz** [comment]
@CJ-Wright As requested, here comes the alternative PR for `ete3`.
Now contains dependencies from recipe over at https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ete3/meta.yaml plus a few more tests.

**Comment by scopatz** [comment]
Thanks!

**Comment by ltalirz** [comment]
Thanks for reviewing!

**Comment by ltalirz** [comment]
I guess that means https://github.com/conda-forge/staged-recipes/pull/5885 should be closed

**Comment by scopatz** [comment]
Yep, thanks!

**Pull request merged**
