### PR TITLE
add recipes/r-bindr, recipes/r-bindrcpp, recipes/r-glue, recipes/r-pkgconfig

### PR DESCRIPTION
**Pull request by bgruening**
requested in https://github.com/conda-forge/conda-forge.github.io/issues/234#issuecomment-325780716

### CODE REVIEW

**Comment by jdblischak** [comment]
Looks good to me

**Comment by isuruf** [comment]
It looks like some of the dependencies are pulled in from defaults. They need to be rerendered before this PR.

**Comment by bgruening** [comment]
Which is strange because r-tibble was rerendered 10 days ago and a 3.4.1 packages seems to be here https://anaconda.org/conda-forge/r-tibble/files

**Comment by bgruening** [comment]
@isuruf I don't understand why OSX is not getting the conda-forge package. The only thing I see is that defaults has 1.3.3 of r-tibble and conda-forge only 1.3.0 ... but the channel priority should give us the one from conda-forge isn't it?

**Comment by jdblischak** [comment]
> defaults has 1.3.3 of r-tibble and conda-forge only 1.3.0 ... but the channel priority should give us the one from conda-forge isn't it?

@bgruening [dbplyr 1.1.0](https://cran.r-project.org/package=dbplyr) requires tibble > ≥ 1.3.0.9007, which the conda-forge package does not satisfy

**Comment by bgruening** [comment]
I'm already on this and update the PR to update it to 1.3.3

**Comment by bgruening** [comment]
@ocefpaf can we get this merged please? Thanks :)

**Comment by bgruening** [comment]
Thanks Filipe!

**Pull request merged**
