### PR TITLE
adding surelog / uhdm

### PR DESCRIPTION
**Pull request by timkpaine**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by timkpaine** [comment]
keep note for reference:
https://github.com/chipsalliance/Surelog/issues/515
https://github.com/SymbiFlow/conda-packages/issues/105

**Comment by timkpaine** [comment]
lots of vendoring, I will need to fix upstream:
xrefs:
https://github.com/chipsalliance/UHDM/pull/856

**Comment by timkpaine** [comment]
gtest is now vendored, see https://github.com/conda-forge/gtest-feedstock/issues/66

**Comment by timkpaine** [comment]
@conda-forge/help-c-cpp well im stumped, can't get it to stop yelling about:
```
['  ERROR (uhdm,bin/uhdm-cmp): $RPATH/libuhdm.so not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (uhdm,bin/uhdm-dump): $RPATH/libuhdm.so not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (uhdm,bin/uhdm-hier): $RPATH/libuhdm.so not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']

```
which seems fine

**Comment by carterbox** [comment]
This error is because you are installing to `$PREFIX/lib/uhdm/libuhdm.so` instead of `$PREFIX/lib/libuhdm.so`. When conda edits the dynamic links to make your binaries portable, it cannot find libuhdm.so because it is not in the expected place. You should move your library instead of ignoring this error.

**Comment by timkpaine** [comment]
Ok let me try that, thanks!

**Comment by timkpaine** [comment]
breaking out into https://github.com/conda-forge/staged-recipes/pull/23614

**Pull request closed without merging**
