### PR TITLE
add bjoern

### PR DESCRIPTION
**Pull request by carlodri**
https://github.com/jonashaag/bjoern

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
@carlodri there is no point here to rerender that. The rerender just can be done in feedstock. Because you already using the latest configuration of the CI using the staged-recipes.  :)

**Comment by marcelotrevisani** [comment]
Please, do not delete the others recipes. We have some problems with the CI and we are trying to solve them.

**Comment by carlodri** [comment]
@marcelotrevisani oops, sorry for the mess! I thought I needed to rerender to effectively skip the `win` builds, and sorry, I thought that removing the other recipes did not affect `master`....

should I merge back `master` into this branch? or what do you suggest?

**Comment by marcelotrevisani** [comment]
Hi @carlodri , yes, please revert the deletion which you did and that should be good  :)

**Comment by carlodri** [comment]
@marcelotrevisani I merged from staged-recipes/master since I was having trouble undeleting the stuff, is this ok?

**Comment by carlodri** [comment]
@marcelotrevisani is this ready to be merged?

**Comment by marcelotrevisani** [comment]
@carlodri , sorry for my delay

Could you please rebase it to the master of staged-recipes? just to avoid any kind of problem, or give me access to your fork and I will try to do it

**Comment by carlodri** [comment]
@marcelotrevisani not sure about what's going on here on OSX...

**Comment by marcelotrevisani** [comment]
it is missing some symbols, I don't have much experience in compiling project in ``osx```. So, I can't help you much here

**Comment by carlodri** [comment]
after looking around, I have the feeling it's related to this: https://github.com/conda-forge/python-feedstock/issues/201

**Comment by marcelotrevisani** [comment]
Indeed, it looks like
But if you want to you can skip the ``osx`` for now and when they solved the problem you can create packages for ``osx`` again

**Comment by carlodri** [comment]
@marcelotrevisani looks like re-booting the CI solved it... You can merge when you wish!

Thanks!

**Comment by marcelotrevisani** [comment]
Looks good to me!

Thanks for adding this in ``conda-forge`` ! :tada:

**Pull request merged**
