### PR TITLE
Added recipe for Faker

### PR DESCRIPTION
**Pull request by pmlandwehr**
Renamed version of the package formerly known as `fake-factory`, and a good thing too, given the import name. Required for `factory_boy`.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Whats still missing here?

**Comment by mariusvniekerk** [comment]
Looks like the circleci pending status is a lie.

**Comment by mariusvniekerk** [comment]
@synapticarbors

**Comment by synapticarbors** [comment]
It looks like @pmlandwehr needs to clean up a bunch of files and update from `0.7.7` to `0.7.9`. @pmlandwehr if you get a chance, can you comment on the general status of this PR?

**Comment by mariusvniekerk** [comment]
Feels like it needs a rebase or something

**Comment by pmlandwehr** [comment]
Yeah - I've been surprised by this, and am a bit confused. All of the commits got pulled in *after* my rebase. That is - I rebased my master on  conda-forge's master, and then rebased my fork for faker on my updated local master, and here we are.

**Comment by pmlandwehr** [comment]
Most likely going to close, remake, and resubmit.

**Comment by jakirkham** [comment]
Please do when you have a chance.

**Pull request closed without merging**
