### PR TITLE
Added recipe for diskcache

### PR DESCRIPTION
**Pull request by pmlandwehr**
Pinging @grantjenks in case they'd like to be added as a maintainer to the `diskcache` builder on [conda-forge](http://conda-forge.github.io), a library of community-built [`conda`](http://conda.pydata.org) packages. The maintenance burden here is light: all testing and releases are built and deployed automatically with CI. Changes to how the package is being built can be controlled by changing the recipe which will be located at https://github.com/conda-forge/diskcache-feedstock shortly after this PR is finished and merged. If you aren't interested in helping maintain the build, that's entirely fine too.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Crashout seems to be due to an internal travis CI issue. Closing and reopening.

**Comment by pmlandwehr** [comment]
Welp! Not that.

**Comment by jakirkham** [comment]
I submitted this issue ( https://github.com/travis-ci/travis-ci/issues/6341 ) to Travis CI.

**Comment by jakirkham** [comment]
Thanks @pmlandwehr.

**Pull request merged**
