### PR TITLE
Adding qsv (rust), a tool to work with csv data

### PR DESCRIPTION
**Pull request by adRn-s**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

The tool is installable in 3 flavours, here I bundled two recipes. One is the full version, though it doesn't have python. The other one is the lightweight version (and has a different binary too: `qsvlite`).

### CODE REVIEW

**Comment by adRn-s** [comment]
Why would `osx` build fail? [error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=589816&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=1835)

**Comment by adRn-s** [comment]
@conda-forge-admin, please ping someone who can help me debug the `osx` error. Possibly, this is related to #13622 ...

**Comment by adRn-s** [comment]
With SDK 12.5 I had a new [error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=590619&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=1084) no. Apparently, this one is before the one I had originally...

```
100     9  100     9    0     0     22      0 --:--:-- --:--:-- --:--:--    22
tar: Error opening archive: Unrecognized archive format
Missing CONDA_BUILD_SYSROOT: /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.5.sdk
Traceback (most recent call last):
  File "/Users/runner/work/1/s/.ci_support/build_all.py", line 223, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/Users/runner/work/1/s/.ci_support/build_all.py", line 115, in build_all
    subprocess.run("run_conda_forge_build_setup", shell=True, check=True)
  File "/Users/runner/mambaforge/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'run_conda_forge_build_setup' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
```

**Comment by adRn-s** [comment]
@conda-forge-admin, please ping @conda-forge/staged-recipes, ready for review!

**Review by carterbox — CHANGES_REQUESTED** [review]
Looks like you are building the same package with different features enabled. [These are "build variants".](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html)

You should have one recipe with two variants. Use the jinja templates to change how the packge is built in each variant. The different variants can be selected by adding text to a custom build string.

Also, 'nopython' implies 'withpython'. With conda-forge packages we expect all of the dependencies to be installed, so if the 'withpython' variant requires python it should include python in the dependencies somewhere.

**Pull request closed without merging**
