### PR TITLE
PR for oracle-jdk in the conda-forge channel

### PR DESCRIPTION
**Pull request by abhi18av**
This is an effort to include the Oracle-jdk distribution in the conda-forge channel

### CODE REVIEW

**Comment by abhi18av** [comment]
Hi guys, I'm currently only  focusing on the linux build on Circle-CI and the the error log throws this error 

```

tarfile.ReadError: file could not be opened successfully

```

I'm a bit clueless here, could you help me out?

**Comment by abhi18av** [comment]
@nehaljwani I noticed that you're quite involved with `conda` so could you help me out with this PR ?

I'd really appreciate it :)

**Comment by nehaljwani** [comment]
@abhi18av You can't directly download the URL:

```
(root) [root@8a840e4386e3 oracle-jdk]# curl -sLO http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz
(root) [root@8a840e4386e3 oracle-jdk]# file jdk-8u144-linux-x64.tar.gz 
jdk-8u144-linux-x64.tar.gz: HTML document text
```

It returns the tarball only if a cookie is set (in HTTP headers):
```
 "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
```

Conda Build has no way of doing that right now. Also, these URLs keep changing on their website and the older ones become obsolete, or change, idk.

**Comment by abhi18av** [comment]
@nehaljwani thanks for looking into it. 

I'm looking into https://github.com/shyiko/jabba and https://anaconda.org/cyclus/java-jdk as inspiration.

**Comment by phreed** [comment]
@conda-forge-admin, please ping team

I am interested in completing this package / recipe but I am not the creator.
I have a few questions.

- [  ] How do I take over this PR? 
  - [ ] Create a new PR?
  - [ ] Something else? 
- [ ] What is the recommendation for sourcing such a flakey tarball? The url changes frequently, cookies are required, etc.
  - Is there a mechanism for prompting the operator during the `conda install`? 
  - I am thinking that the best approach is to require the operator to retrieve the tarball out-of-band and place it in a prescribed location.

**Pull request closed without merging**
