### PR TITLE
Add DSSP

### PR DESCRIPTION
**Pull request by lilyminium**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by lilyminium** [comment]
@cbaakman are you still happy to maintain this recipe?

**Comment by cbaakman** [comment]
> 
> 
> @cbaakman are you still happy to maintain this recipe?

It looks good. The license is included and the build script seems OK.

**Comment by cabb99** [comment]
Hi @lilyminium and @cbaakman,
I was going through some of the old PRs and noticed this one related to the dssp recipe. It appears the discussion halted late 2020, but I believe it may be an important addition to conda-forge since it would allow me to add recipes with the dssp dependence. It seems it may only need checking the "GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there" box

**Comment by cbaakman** [comment]
I'm sorry, I don't fully understand. Who would be meant with "GitHub users listed in the maintainer section"?

By the way, I am not the maintainer of the latest dssp repo. It's currently maintained here:
https://github.com/PDB-REDO/dssp

I only maintained version 3, but the latest is 4.

**Comment by lilyminium** [comment]
I think anyone can volunteer to maintain the conda recipe for a package, although it's most commonly the developers of the package itself. Given that DSSP has now moved onto version 4, this recipe is probably very out of date and the best way forward would be to make an entirely new recipe for conda. @cabb99 you're welcome to do so if you like, or to ask the folks at PDB-REPO do so!

**Pull request closed without merging**
