### PR TITLE
Adding pygtrie

### LINKED ISSUE #2473: Add pygtrie
Probably a small thing, but a trie implementation from Google seems handy...

### PR DESCRIPTION
**Pull request by efiop**
Fixes #2473

Hi @conda-forge/help-python ! Please take a look when you'll have time. Thank you! pray

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by efiop** [comment]
@Suor @shcheklein Could you please confirm with a comment that you are agreeing to become maintainers for this feedstock repo?

**Comment by Suor** [comment]
Confirm.

**Comment by shcheklein** [comment]
I confirm! thanks @efiop @synapticarbors .

**Comment by efiop** [comment]
Thank you @synapticarbors ! :pray:

**Pull request merged**
