### PR TITLE
Add scikit-hep-testdata

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by chrisburr** [comment]
This is ready to review.

The failing tests are due to incompatibilities with Windows and have been reported in https://github.com/scikit-hep/scikit-hep-testdata/issues/23 but this is `noarch` so it doesn't matter.

**Comment by chrisburr** [comment]
@conda-forge/staged-recipes, this is ready for review

**Comment by ocefpaf** [comment]
Do you care about the Windows failures here?

**Comment by chrisburr** [comment]
It’s noarch so it won’t affect the feedstock and it’s been fixed upstream for he next release

**Pull request merged**
