### PR TITLE
Added r-minerva recipe

### PR DESCRIPTION
**Pull request by khughitt**
Generated via the conda r skeleton helper script.

Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vend other packages
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dbast** [comment]
Requires minepy to be added to conda-forge.

**Comment by dbast** [comment]
It builds now... This is a compiled R package wrapping a compiled python package. Could we add one of the examples from https://github.com/rsamantha/minerva to run as test to check that the package really works?

**Comment by khughitt** [comment]
Sure thing - that sounds like a pretty good idea. I'll try and add it tomorrow if I can find the time.. Should not take long.

**Comment by khughitt** [comment]
Okay, finally got around to adding the tests. Checked with conda-build, and all of the tests appear to pass fine for me!

**Comment by dbast** [comment]
Wow, nice. Thanks!

**Pull request merged**
