### PR TITLE
Add chebfun package

### PR DESCRIPTION
**Pull request by janniklasrose**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] ~If static libraries are linked in, the license of the static library is packaged.~
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by markrichardson** [comment]
Confirming I am happy to be a maintainer

**Comment by janniklasrose** [comment]
@conda-forge/help-python I am curious how I could specify different requirements for external libraries and if that is the right way to do.

This package uses either `pyfftw` or, as fallback option, `numpy`. (A similar behaviour exists for `matplotlib` too, with fallback option to not support `.plot` methods). Both of these are runtime dependencies.

Should this be done similar to e.g. `numpy` does it with MKL? Or is it simply up to the user to install `pyfftw` and/or `matplotlib` if they want the additional support? In that case, how would we specify version conflicts?

**Comment by scopatz** [comment]
You can use run_constrains for specifying those conflicts

**Comment by janniklasrose** [comment]
Thanks, that is helpful. Should be ready for merging now.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
