### PR TITLE
Add oss2, aliyun-python-sdk-kms, aliyun-python-sdk-core, aliyun-pytho…

### PR DESCRIPTION
**Pull request by MaxRis**
…n-sdk-core-v3

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by MaxRis** [comment]
Build fails due to missed Python 3.7 build of `crcmod` dep.

**Comment by MaxRis** [comment]
@shcheklein @efiop could you please confirm with the comment that you are fine to become maintainers for new created feedstock repos

**Comment by shcheklein** [comment]
confirmed!

**Comment by MaxRis** [comment]
[PR](https://github.com/conda-forge/crcmod-feedstock/pull/5) to add missed Python 3.7 build for `crcmod`.

**Comment by efiop** [comment]
Confirmed :slightly_smiling_face:

**Comment by MaxRis** [comment]
@conda-forge/help-python this PR should be ready for merging, could you please take a look! Thanks

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
