### PR TITLE
Add a recipe for ragged

### PR DESCRIPTION
**Pull request by hmaarrfk**
Just fyi: cc: @conda-forge/awkward 

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/rattler-build is this noarch recipe correct? when i had numpy spcified, i had 3 conda files generated.

**Review by marcelotrevisani — APPROVED** [review]

**Comment by wolfv** [comment]
@hmaarrfk I filed an issue in `rattler-build` for the numpy-variant problem for noarch packages that you observed. I actually don't know how pins are taken into account for `noarch` packages...

**Comment by hmaarrfk** [comment]
> @hmaarrfk I filed an issue in rattler-build for the numpy-variant problem for noarch packages that you observed. I actually don't know how pins are taken into account for noarch packages...

wow you took a deep dive on my commit history! Thanks for that.

It was pretty cool to see rattler build things so fast!!!

**Comment by hmaarrfk** [comment]
> Are there docs on using ratter-build with conda-forge, specifically on how to convert packages over? :)

Not to my knoweldge. I used the `recipe.yaml` as sample syntax and went from ther.

**Comment by wolfv** [comment]
We have some conversion tips here: https://prefix-dev.github.io/rattler-build/latest/converting_from_conda_build/

However, we still need a little bit of time to enable uploading the packages to the main conda-forge channel. Right now, a feedstock is created, but the upload is disallowed :) 

The first feedstock that has the new recipe format is: https://github.com/conda-forge/jolt-physics-feedstock/ :)

**Pull request merged**
