### PR TITLE
add package ogs

### PR DESCRIPTION
**Pull request by bilke**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bilke** [comment]
@conda-forge/help-c-cpp Ready for review. Windows builds are disabled because the project does not compile on it at the moment.

**Review by wolfv — APPROVED** [review]

**Comment by wolfv** [comment]
Everything loosk good but I saw that for some reason `ogs` installs some "linux" dependencies (libm.so, libresolv.so, ...):

```
-- file(GET_RUNTIME_DEPENDENCIES) will install: /lib64/ld-linux-x86-64.so.2;/lib64/libc.so.6;$PREFIX/lib/././././libcom_err.so.3;$PREFIX/lib/././././././libcrypto.so.3;$PREFIX/lib/./libcurl.so.4;/lib64/libdl.so.2;$PREFIX/lib/./././libdouble-conversion.so.3;$PREFIX/lib/././libexpat.so.1;$PREFIX/lib/././././././././././libgcc_s.so.1;$PREFIX/lib/libgomp.so.1;$PREFIX/lib/././libgssapi_krb5.so.2;$PREFIX/lib/libhdf5.so.310;$PREFIX/lib/./libiconv.so.2;$PREFIX/lib/./././libicudata.so.73;$PREFIX/lib/./libicui18n.so.73;$PREFIX/lib/././libicuuc.so.73;$PREFIX/lib/././././libk5crypto.so.3;$PREFIX/lib/././././././libkeyutils.so.1;$PREFIX/lib/./././libkrb5.so.3;$PREFIX/lib/./././././libkrb5support.so.0;$PREFIX/lib/./././liblz4.so.1;$PREFIX/lib/./././liblzma.so.5;/lib64/libm.so.6;$PREFIX/lib/././libnghttp2.so.14;/lib64/libpthread.so.0;$PREFIX/lib/./././././libpugixml.so.1;$PREFIX/lib/libpython3.12.so.1.0;/lib64/libresolv.so.2;/lib64/librt.so.1;$PREFIX/lib/././libssh2.so.1;$PREFIX/lib/././libssl.so.3;$PREFIX/lib/./././././././././libstdc++.so.6;$PREFIX/lib/./libsz.so.2;/lib64/libutil.so.1;$PREFIX/lib/./././libvtkCommonColor-9.3.so.1;$PREFIX/lib/././././libvtkCommonComputationalGeometry-9.3.so.1;$PREFIX/lib/./././././././libvtkCommonCore-9.3.so.1;$PREFIX/lib/././././././libvtkCommonDataModel-9.3.so.1;$PREFIX/lib/././././././libvtkCommonExecutionModel-9.3.so.1;$PREFIX/lib/././././././libvtkCommonMath-9.3.so.1;$PREFIX/lib/./././././libvtkCommonMisc-9.3.so.1;$PREFIX/lib/./././././libvtkCommonSystem-9.3.so.1;$PREFIX/lib/./././././libvtkCommonTransforms-9.3.so.1;$PREFIX/lib/././././././libvtkFiltersCore-9.3.so.1;$PREFIX/lib/./libvtkFiltersExtraction-9.3.so.1;$PREFIX/lib/././././libvtkFiltersGeneral-9.3.so.1;$PREFIX/lib/./././././libvtkFiltersGeometry-9.3.so.1;$PREFIX/lib/./libvtkFiltersHybrid-9.3.so.1;$PREFIX/lib/././libvtkFiltersHyperTree-9.3.so.1;$PREFIX/lib/./libvtkFiltersModeling-9.3.so.1;$PREFIX/lib/libvtkFiltersParallel-9.3.so.1;$PREFIX/lib/./././libvtkFiltersSources-9.3.so.1;$PREFIX/lib/././libvtkFiltersStatistics-9.3.so.1;$PREFIX/lib/./libvtkFiltersTexture-9.3.so.1;$PREFIX/lib/././././libvtkFiltersVerdict-9.3.so.1;$PREFIX/lib/././././libvtkIOCore-9.3.so.1;$PREFIX/lib/././././libvtkIOLegacy-9.3.so.1;$PREFIX/lib/./././libvtkIOXML-9.3.so.1;$PREFIX/lib/./libvtkIOXMLParser-9.3.so.1;$PREFIX/lib/./././libvtkImagingCore-9.3.so.1;$PREFIX/lib/././libvtkImagingSources-9.3.so.1;$PREFIX/lib/./././libvtkParallelCore-9.3.so.1;$PREFIX/lib/././libvtkParallelDIY-9.3.so.1;$PREFIX/lib/././libvtkRenderingCore-9.3.so.1;$PREFIX/lib/././././libvtkfmt-9.3.so.1;$PREFIX/lib/./././././././libvtkkissfft-9.3.so.1;$PREFIX/lib/././././././././libvtkloguru-9.3.so.1;$PREFIX/lib/././././././././libvtksys-9.3.so.1;$PREFIX/lib/./././././libvtkverdict-9.3.so.1;$PREFIX/lib/libxml2.so.2;$PREFIX/lib/./././libz.so.1;$PREFIX/lib/././libzstd.so.1
-- Installing: $PREFIX/lib/ld-linux-x86-64.so.2
-- Installing: $PREFIX/lib/ld-2.17.so
-- Installing: $PREFIX/lib/libc.so.6
-- Installing: $PREFIX/lib/libc-2.17.so
-- Installing: $PREFIX/lib/libdl.so.2
-- Installing: $PREFIX/lib/libdl-2.17.so
-- Installing: $PREFIX/lib/libm.so.6
-- Installing: $PREFIX/lib/libm-2.17.so
-- Installing: $PREFIX/lib/libpthread.so.0
-- Installing: $PREFIX/lib/libpthread-2.17.so
-- Installing: $PREFIX/lib/libresolv.so.2
-- Installing: $PREFIX/lib/libresolv-2.17.so
-- Installing: $PREFIX/lib/librt.so.1
-- Installing: $PREFIX/lib/librt-2.17.so
-- Installing: $PREFIX/lib/libutil.so.1
-- Installing: $PREFIX/lib/libutil-2.17.so
```

Can you disable that?

**Review by wolfv — CHANGES_REQUESTED** [review]
need to disable vendoring linux deps

**Comment by wolfv** [comment]
Ok, looks better!

Still some strange files:

?rw-rw-r-- 0/0        255 2024-06-24 06:42:31 README.txt 
?rw-rw-r-- 0/0     107731 2024-06-24 06:42:31 share/info/CMakeCache.txt 
?rw-rw-r-- 0/0      84052 2024-06-24 06:42:31 share/info/third_party_licenses.txt 

the thirD_party_licenses should ideally be moved into the `info/licenses` folder which you can do in teh about section. I can reference some Golang or Rust recipes that do that.

?rw-rw-r-- 0/0     393114 2024-06-24 07:02:53 lib/libGKlib.a 
?rw-rw-r-- 0/0     971854 2024-06-24 06:44:00 lib/libtet.a 

You are compiling static libraries. On conda-forge we prefer shared libraries. Is that an option that can be easily enabled?

**Comment by bernt-matthias** [comment]
Hi @bilke can you update the branch?

**Comment by bernt-matthias** [comment]
Hi @bilke. We are just trying to reproduce this locally and will inform you in case we are successful.

**Comment by carterbox** [comment]
> I still have some runtime error (undefined symbol). How can I inspect the created binaries? I locally build with `python3 build-locally.py` but I do not see where the build results end up.

The build-locally script should be dumping all of the conda-build artifacts into a newly created directory this project directory called build_artifacts. You can also just build the recipe outside of a container like you would normally using the variant file from .ci. e.g. conda-build -m .ci/linux64.yaml recipe/ogs. Then any failed builds would be located in $CONDA_PREFIX/conda-bld

**Comment by bernt-matthias** [comment]
Thanks for the comment @carterbox. `python build-locally.py linux64` indeed seems to work. One just needs to remove the example directories, otherwise it fails with 

```
...
+ echo 'Building all recipes'
Building all recipes
+ python /home/conda/staged-recipes-copy/.ci_support/build_all.py
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 340, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 97, in build_all
    raise ValueError("Mixing meta.yaml and recipe.yaml recipes is not supported")
ValueError: Mixing meta.yaml and recipe.yaml recipes is not supported
Traceback (most recent call last):
  File "/home/berntm/projects/conda-forge/staged-recipes/build-locally.py", line 101, in <module>
    main()
  File "/home/berntm/projects/conda-forge/staged-recipes/build-locally.py", line 95, in main
    run_docker_build(ns)
  File "/home/berntm/projects/conda-forge/staged-recipes/build-locally.py", line 33, in run_docker_build
    subprocess.check_call([script])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```

**Comment by bilke** [comment]
@wolfv, @bernt-matthias I have resolved the runtime error and this is ready from my side.

**Comment by bernt-matthias** [comment]
@wolfv may I ask again for a review?

**Review by bgruening — APPROVED** [review]
Thanks everyone! This looks good to me.

**Pull request merged**
