### PR TITLE
rabbitmq server 

### PR DESCRIPTION
**Pull request by scopatz**
Somewhat surprising that this didn't exist yet.

### CODE REVIEW

**Comment by jakirkham** [comment]
Doesn't this require Erlang?

Also could you please rebase this on a commit in `master` that doesn't have existing recipes?

**Comment by jakirkham** [comment]
For instance, this commit ( https://github.com/conda-forge/staged-recipes/commit/61fb5b3461b2472623b30f81e33f260ab5eba94b ) should be fine.

**Comment by scopatz** [comment]
Yeah sorry about that @jakirkham

**Comment by jakirkham** [comment]
No worries. You are welcome to rebase in your PRs if you like as the history here is mainly for you. Most PRs have little meaning in the larger context.

**Pull request closed without merging**
