### PR TITLE
Recipe for Bottle

### PR DESCRIPTION
**Pull request by sbassi**
This library is not available to install with Conda, so here is my recipe. First time I do a recipe.

### CODE REVIEW

**Comment by jakirkham** [comment]
Hi @sbassi, thanks for the PR. We actually do have a copy of `bottle` in this [feedstock]( https://github.com/conda-forge/bottle-feedstock ). Though admittedly we have a lot of stuff here so it is easy to miss. 😄 Would you be interested in being a maintainer?

**Comment by sbassi** [comment]
Hello @jakirkham. I am not familiar with this system. I don't get why if you have a copy I can install it with conda, I get this:

PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - bottle

Close matches found; did you mean one of these?

    bottle: bottleneck, bottlechest

You can search for packages on anaconda.org with

    anaconda search -t conda bottle

**Comment by synapticarbors** [comment]
@sbassi 

Try:

```
conda search -c conda-forge bottle
```

When I tried to search using `anaconda search -t conda bottle` it printed a bunch of packages, but the list must have been cutoff because I didn't see the conda-forge one.

**Comment by jakirkham** [comment]
Going to close this out, but please raise an issue if you are still having trouble, @sbassi. Perhaps on the `bottle` feedstock. If that doesn't go anywhere, feel free to raise an issue here at staged-recipes.

**Pull request closed without merging**
