### PR TITLE
add cbsyst

### PR DESCRIPTION
**Pull request by ocefpaf**
ping @oscarbranson 

I am packaging `cbsyst` in `conda-forge`.

### CODE REVIEW

**Comment by oscarbranson** [comment]
Great! Is there a way to automate this for future builds? Or could I add this to me 'distrbution' script (currently builds a wheel and uploads to pypi - I'm not familiar with conda-forge).

**Comment by ocefpaf** [comment]
> Great! Is there a way to automate this for future builds?

At the moment no. We are looking into automating using the PyPI packages though.

> Or could I add this to me 'distrbution' script (currently builds a wheel and uploads to pypi

About that... It would be nice if you also upload the source distribution too.

> I'm not familiar with conda-forge).

If you are curious take a look at refs [1](http://wesmckinney.com/blog/conda-forge-centos-moment/) and [2](https://www.continuum.io/blog/developer-blog/community-conda-forge), but the TL;DR version is that conda-forge helps when installing non-python or non-pure python modules.

**Comment by oscarbranson** [comment]
Thanks for the tips. This is my first attempt at distributing a module, so any advice welcome!

Working on uploading an sdist now, but it's giving me some grief. Keeps including files (large data files in test_data) that I don't want included! Will hopefully appear in the next day or two, once I work it out.

**Comment by oscarbranson** [comment]
I'd like to add conda-forge forge installation instructions to the readme. Is this correct?

    conda config --add channels conda-forge
    conda install cbsyst

**Comment by ocefpaf** [comment]
>  Is this correct?

Yep. If user don't want to add the `conda-forge` channel permanently they can do:

`conda install cbsyst -c conda-forge`

**Pull request merged**
