### PR TITLE
Add recipe for deltalake library

### LINKED ISSUE #21102: Package request: deltalake
### Package name

deltalake

### Package version

Newest

### Package website

https://delta-io.github.io/delta-rs/python/
https://github.com/delta-io/delta-rs

### Package availability

Available on PyPI and GitHub Releases
https://pypi.org/project/deltalake/
https://github.com/delta-io/delta-rs/releases/

### Additional comments

This package enables access to Delta Lake tables on S3/ADLS from Python. It produces `pyarrow` datasets that can then be queried by `duckdb` - creating a _very_ powerful "local" data lake query option.

An old (closed) attempt at a PR is here: https://github.com/conda-forge/staged-recipes/pull/16045

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

### PR DESCRIPTION
**Pull request by craustin**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Resolves #21102

### CODE REVIEW

**Comment by craustin** [comment]
broken by https://github.com/conda/conda-build/issues/4787

**Comment by dhirschfeld** [comment]
```
RuntimeError: SHA256 mismatch
```

**Review by jrbourbeau — COMMENTED** [review]
Thank you for working on this @craustin. Just wanted to check in to see is there are any blockers here at the moment. Anything I can do to help?

**Comment by jakirkham** [comment]
Recently @charlesbluca picked this up in PR ( https://github.com/conda-forge/staged-recipes/pull/23386 ). Maybe folks here would like to review that PR?

**Comment by craustin** [comment]
Superseded by #23386

**Pull request closed without merging**
