### PR TITLE
mp-time-split with hyphens instead of underscores

### PR DESCRIPTION
**Pull request by sgbaird**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

@conda-forge/help-python

### CODE REVIEW

**Comment by beckermr** [comment]
We cannot just remove packages. Have you considered adding outputs to the existing feedstock?

**Comment by sgbaird** [comment]
@beckermr good to know, I was going off of:
> During the review process, please make certain to note that the package is renamed and contact a member of conda-forge/core to remove the old feedstock (and potentially package, if needed). ([source](https://conda-forge.org/docs/orga/guidelines.html#renaming-packages))

I haven't used the outputs section before. Going off of [the docs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section), my inclination would be to have a separate section:
```yaml
outputs:
  - name: mp-time-split
  - name: mp_time_split
```
Does this make it so it appears on `conda-forge` both as `mp-time-split` and `mp_time_split`?

@BastianZim does this accomplish the same thing as [the `meta.yaml` that you linked](https://github.com/BastianZim/coin-or-cbc-feedstock/blob/7ca6bb653193dba43ab8ab83ff959c677b06feb9/recipe/meta.yaml) except for the fact that everything about the package is identical? Or do I need to copy the same information (except for `name`) twice under a parent `outputs` section?

**Comment by sgbaird** [comment]
Based on the [failed test](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=519386&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823), I'll try going with everything under a `parent` section (in the existing feedstock per @beckermr 's [comment](https://github.com/conda-forge/staged-recipes/pull/19215#issuecomment-1151471078))

**Comment by BastianZim** [comment]
You’ll need to do it like in the linked meta.yaml. Just adding the name doesn‘t work.

**Comment by sgbaird** [comment]
@BastianZim thanks for clarifying!

**Comment by BastianZim** [comment]
@sgbaird can this be closed?

**Comment by sgbaird** [comment]
Yes! Thanks for checking in

**Pull request closed without merging**
