### PR TITLE
Add conda noarch require packages

### PR DESCRIPTION
**Pull request by isuruf**
cc @conda-forge/staged-recipes

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Would it be possible to add a requirement for 2k vs 3k?

**Comment by isuruf** [comment]
Python constraints can enforced by adding it to `python` like `python <3` or `python > 3`, right?

**Comment by CJ-Wright** [comment]
Not for `noarch` to the best of my knowledge.

**Comment by isuruf** [comment]
It does work for `noarch`. @msarahan mentioned that it worked. @jakirkham should know more

**Comment by jakirkham** [comment]
It should work, but it is not tested in `conda-build` or documented. Was trying to add tests, but haven't had time to return to it. PR ( https://github.com/conda/conda-build/pull/2487 ) includes these tests.

**Comment by jakirkham** [comment]
Could you explain the purpose of this package a bit more @isuruf? Just trying to grep this now.

**Comment by isuruf** [comment]
For noarch, `skip: True # [not unix]` doesn't work. So, instead of doing that we can add `require-unix` to the run requirements which is only built for unix.
Somebody mentioned this strategy as `requirements` packages in gitter, but I can't remember who.

**Comment by jakirkham** [comment]
Maybe @jjhelmus?

**Comment by jakirkham** [comment]
So are there some use cases that you know of that are motivating this?

**Comment by isuruf** [comment]
https://github.com/conda-forge/xdg-feedstock/pull/1 was one I saw recently.

**Comment by isuruf** [comment]
After browsing conda-forge issues, looks like there aren't many use-cases for this.

**Comment by jakirkham** [comment]
Happy to revisit if that changes.

**Pull request closed without merging**
