### PR TITLE
[skip ci] add gcc based on gcc-5 from conda-recipes

### PR DESCRIPTION
**Pull request by msarahan**
Just getting started here.  Not compiling so far on Mac.

@frol @jakirkham @jjhelmus @mingwandroid I have listed you as maintainers based on your past contributions.  If you want off, let me know.

I welcome anyone submitting PRs against this branch, or forking this and running with it.  I will try to follow this one to completion, though.

I do not anticipate that this will build on our CI services.  I still want it to live at conda-forge somehow, if possible.

### CODE REVIEW

**Comment by frol** [comment]
@msarahan Please, merge the last 4 commits from our GCC-6 recipe to fix OS X compilation: https://github.com/salford-systems/conda-recipes/commits/master/gcc-6

The packages for Linux-64, Linux-32, and OS X are already on our [Salford Systems channel](https://anaconda.org/salford_systems/gcc-6/files), so you can install and test them:

```
$ conda install -c conda-forge -c salford_systems gcc-6
```

We also have `libgcc-6`, and `gcc-5`/`libgcc-5` (GCC 5.4.0) packages.

**Comment by frol** [comment]
FYI, you may notice that I have removed explicit `-j"$CPU_COUNT"`, it is due to the fact that recent `conda-build` passes through `MAKEFLAGS` environment variable, so it can be set outside of `build.sh`. In fact, I have tested `export MAKEFLAGS=--jobs 64` on our build server.

**Comment by frol** [comment]
FYI, `gcc-4.8` recipe on `conda-recipes` repo has received more updates since I created `gcc-5` recipe (the most important one is https://github.com/svenpeter42/conda-recipes/commit/853f506ca2a3fe8f763428dd645c7a70da380aa8). I haven't had a chance to backport them to `gcc-5` and `gcc-6` I maintain in `salford_systems` repo due to the fact that we have been using these packages on our build servers, and since they work for us, we don't have enough resources to experiment with the changes introduced in `gcc-4.8` recipe.

**Comment by astrofrog** [comment]
Just a quick note - I think that the recipe should include a test of compilation with gcc and gfortran and a test to make sure the resulting binaries can run (to prevent this kind of issue: https://github.com/conda/conda/issues/3241)

**Comment by isuruf** [comment]
Moving to 7.2

**Pull request closed without merging**
