### PR TITLE
feat: add sciris

### PR DESCRIPTION
**Pull request by kjappelbaum**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sgbaird** [comment]
```python
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - pip
 - memory_profiler
 - openpyxl
 - pandas
 - line_profiler
 - dill
 - gitpython
 - numpy >=1.10.1
 - psutil
 - matplotlib-base >=2.2.2
 - colorama
 - ansicolors
 - jsonpickle
 - xlsxwriter
 - python >=3.9
 - jellyfish
 - multiprocess

with channels:
 - local
 - conda-forge
 - conda-forge

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested ansicolors
- 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 223, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 120, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 179, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2128, in build
    create_build_envs(top_level_pkg, notest)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2006, in create_build_envs
    raise e
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 1985, in create_build_envs
    environ.get_install_actions(m.config.test_prefix,
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 133, in mamba_get_install_actions
    raise err
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("ansicolors")}
##[error]Bash exited with code '1'.
```
Hopefully not too many others that packaging.

Also I'm noticing `python >=3.9`. With `xtal2png`, I try to expose a lot of the examples and functionality through Colab (Python 3.7) and installing a custom Python environment on Colab can take up to 20-30 minutes to complete in my experience.

**Comment by kjappelbaum** [comment]
The sciris devs promised to remove the ansicolors dependency (https://github.com/sciris/sciris/issues/332). If it's not done this week, I'll make a PR. All the other things should be on conda.

**Comment by sgbaird** [comment]
@kjappelbaum oh cool, nice!

**Comment by kjappelbaum** [comment]
the missing dependency: https://github.com/conda-forge/staged-recipes/pull/19885

**Review by kjappelbaum — COMMENTED** [review]
chore: bump version

**Review by kjappelbaum — COMMENTED** [review]
remove ansicolors

**Comment by cliffckerr** [comment]
Confirming that I approve of this recipe being added to conda! cc @kjappelbaum

**Comment by cliffckerr** [comment]
Hi @kjappelbaum! Thanks for your help with getting this set up. I wasn't able to cherry-pick your commits unfortunately, but I used your PR (this one) and Grayskull to create a new PR here: https://github.com/conda-forge/staged-recipes/pull/22662

**Pull request closed without merging**
