### PR TITLE
Adding ploomber

### PR DESCRIPTION
**Pull request by RoyalTS**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by RoyalTS** [comment]
@edublancas, would you please confirm you're okay with being listed as a maintainer of this recipe? If you'd like me to come along for the ride, also let me know.

**Comment by RoyalTS** [comment]
@conda-forge/help-python This depends on `ploomber-scaffold`, which is more of a supporting module rather than one in its own right. Is there a preferred way of handling such cases?

**Comment by edublancas** [comment]
I'm ok being listed as maintainer. This is the first time I upload to conda-forge, I'd appreciate it if you come along as well. Thanks, @RoyalTS!

**Comment by RoyalTS** [comment]
Repinging @conda-forge/help-python: The build fails because the module depends on `ploomber-scaffold`, which is more of a supporting module rather than one in its own right. Is there a preferred way of handling such cases?

**Comment by edublancas** [comment]
Now that https://github.com/conda-forge/staged-recipes/pull/14868 has been merged, does that mean this should work now? @RoyalTS

**Comment by xhochy** [comment]
Let's see what the CI says 😉

**Comment by xhochy** [comment]
> Let's see what the CI says 😉

Fails with an import error.

**Comment by RoyalTS** [comment]
```
ModuleNotFoundError: No module named 'ploomber.executors.serial'
```

@edublancas, you're more likely to know what that's about.

**Comment by edublancas** [comment]
That's a weird error. I'll take a look later today.

**Comment by edublancas** [comment]
Hi @RoyalTS, can you switch to ploomber version 0.10.3. Let's see if that fixes the problem.

**Comment by edublancas** [comment]
@conda-forge/help-python please close this, this is a duplicate of #15372

**Comment by dopplershift** [comment]
Superseded by #15372.

**Pull request closed without merging**
