### PR TITLE
Add recipe perl-math-random-mt-auto for Perl module Math::Random::MT::Auto

### PR DESCRIPTION
**Pull request by xileF1337**
This adds a recipe perl-math-random-mt-auto for the Perl module Math::Random::MT::Auto and its dependencies.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xileF1337** [comment]
For some reasons, I could build this locally... `perl-devel-stacktrace` is missing here, and it is part of another PR (#20878).

@conda-forge/bioconda-recipes  I'm porting these recipes to CondaForge unless there are any objections from your side.

@cbrueffer  Would you give your consent to be a maintainer of these packages? As usual, your review is very welcome!

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
I approved this without noticing the build errors, ECOFFEE. I'll look into the other referenced PR first, then we can revisit this one.

**Comment by cbrueffer** [comment]
Nice!

**Comment by xileF1337** [comment]
@cbrueffer Just for the record, I received the feedstock registration notification for `perl-math-random-mt-auto` just now, 20h after the merge above, and the packages are still not built/indexed. So there obviously is a little patience required here ... Or have you been kicking the CI again to start and do something?

**Pull request merged**
