### PR TITLE
Add recipe for PyPI package invariant-point-attention

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

https://pypi.org/project/invariant-point-attention/
https://github.com/lucidrains/invariant-point-attention

### CODE REVIEW

**Comment by jdblischak** [comment]
@eliottpark Please confirm here that you are willing to be a co-maintainer for the invariant-point-attention recipe

**Comment by jdblischak** [comment]
@conda-forge-admin, please lint

**Comment by jdblischak** [comment]
This is a noarch recipe, so I don't think it matters that it can't be built on Windows (pytorch isn't available for Windows)

**Review by dopplershift — APPROVED** [review]
Recipe looks good. Ignoring noarch Windows build failure due to missing dependency.

Just need @eliottpark to confirm they are willing to be listed as a maintainer for this recipe.

**Comment by eliottpark** [comment]
I am willing to be a co-maintainer for this recipe.

**Pull request merged**
