### PR TITLE
Add alpha_vantage

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

_Created with grayskull_

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge/help-python Ready for review 😊 

The package is also available for 2.7 but I'm not sure how to specify that using  `python >=`. Since it's not officially supported by Conda anymore, from what I could find googling, I skipped it, is that the correct approach?

**Comment by mariusvniekerk** [comment]
Given that python 2.7 has been eol for more than a year now, probably best to just use a minimum bound of 3.6

**Comment by BastianZim** [comment]
Ok, sounds good. Support starts at 3.4 so should I leave that bound there or use 3.6?

**Comment by BastianZim** [comment]
@mariusvniekerk Just to check, is there anything else besides the lower bound that should be changed?

**Pull request merged**
