### PR TITLE
Adding mlir-python-bindings

### PR DESCRIPTION
**Pull request by jim22k**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

NOTE: I originally attempted to add this to the [mlir-feedstock](https://github.com/conda-forge/mlir-feedstock), but it has a python+numpy matrix aspect which doesn't play nice with the non-python builds for MLIR. This borrows some of the cross-compiling tricks from that repo.

### CODE REVIEW

**Comment by makslevental** [comment]
>@jim22k
[Add all platforms back](https://github.com/conda-forge/staged-recipes/pull/21954/commits/464d0a3dc934edd65242d4c553b0f925d5277c5a)

🙌✊🥳🎉👏

**Comment by makslevental** [comment]
@jim22k sorry for the n00b question but I can't quickly surmise: does this build for M1 as well as x86 mac? Also do you know if there is a way to point `conda install` at your branch (i.e., is there a way to try out this PR locally)?

**Comment by jim22k** [comment]
> does this build for M1 as well as x86 mac? Also do you know if there is a way to point `conda install` at your branch (i.e., is there a way to try out this PR locally)?

I am not sure if this is actually building cross platform yet. It seems like the initial check for feedstock viability may not do everything that a proper feedstock will do. And I don't see a way to extract the built packages from Azure until that happens.

Let me say that I'm glad to know others want to play with the MLIR Python bindings.

I have been trying to get these [built for awhile now](https://github.com/conda-forge/mlir-feedstock/issues/23), without success. One of the MLIR feedstock maintainers tried to build the python bindings after I failed, and he ran into cross platform issues. I need clarification from him on whether he wants to include the bindings in that feedstock or whether I should go forward with this PR and make it a separate feedstock. So I'm in a holding pattern for now.

**Comment by jim22k** [comment]
@makslevental If you want to try the bindings out, I have two solutions available right now.

1. Look at my [python-mlir-graphblas](https://github.com/python-graphblas/python-mlir-graphblas) repo. There are instructions in the README for building on Mac. Look at notebooks/MLIR Python Bindings.ipynb for example usage where I learned how the bindings work in prep for my GraphBLAS project.
2. I have linux-64 and osx-64 builds of MLIR 15 on [my anaconda.org channel](https://anaconda.org/jim22k/mlir-python-bindings/files). If you are on M1 Mac, you can create a conda environment that runs in x86 mode.

```
conda create -n x64env
conda activate x64env
conda config --env --set subdir osx-64
# Now install the package I built
conda install -c jim22k -c conda-forge mlir-python-bindings
```

Note that if you go with Option #2, the notebook I sent won't work without some changes because it was built with MLIR 16 in mind. The line with `engine = execution_engine...` needs to remove the `shared_libs=`. Also the passmanager line needs to remove "builtin.module(" and the closing ")". Those were added in MLIR 16. Otherwise it should mostly just work.

**Comment by makslevental** [comment]
@jim22k 

>you can create a conda environment that runs in x86 mode

I'm not super familiar with conda envs (outside the kind of standard `conda create -n` flow) but I imagine this means everything will run through the Rosetta emulator?

Regarding 1: I currently have my own rube-goldberg-esque build system going [here](https://github.com/makslevental/llvm-releases) but (ofc) I was looking forward to switching over to your `mlir-feedstock` and your bindings. Incidentally, the way I [cross-compile for m1](https://github.com/makslevental/llvm-releases/blob/main/build_llvm.sh#L132) might be relevant for you.

**Comment by jim22k** [comment]
@conda-forge/staged-recipes Can someone take a look at this PR?

There is another effort to get this package [built as part of the mlir-feedstock](https://github.com/conda-forge/mlir-feedstock/pull/33), but that is stalled and I haven't heard back from @isuruf on whether he wants to keep pursuing that PR.

I would love to get this turned into a feedstock. Thanks!

**Comment by makslevental** [comment]
@conda-forge-manager just chiming in that lots of people in the community would find this very useful.

**Pull request merged**
