### PR TITLE
add less (closes #22777)

### LINKED ISSUE #22777: Package request: less
### Package name

less

### Package version

Newest

### Package website

https://github.com/gwsw/less

### Package availability

Github releases

### Additional comments

_No response_

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

### PR DESCRIPTION
**Pull request by tetov**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- ~If static libraries are linked in, the license of the static library is packaged.~
- ~Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Closes #22777

### CODE REVIEW

**Comment by tetov** [comment]
@conda-forge-admin, please restart ci

**Comment by tetov** [comment]
@conda-forge-admin, please lint

**Comment by tetov** [comment]
@conda-forge-admin, please restart ci

**Comment by tetov** [comment]
@conda-forge/help-c-cpp: Ready for review!

CI fails when trying to clone so hopefully that goes away. Build for all platforms works locally.

**Comment by tetov** [comment]
@conda-forge-admin, please restart ci

**Comment by tetov** [comment]
Failure related to https://github.com/conda-forge/conda-forge.github.io/issues/2346 ?

Will try empty and non-empty commit later today.

**Comment by tetov** [comment]
@conda-forge-admin, please lint

**Comment by tetov** [comment]
Running the linter locally gives same error as in CI:

```
conda smithy recipe-lint --conda-forge .
Traceback (most recent call last):
  File "C:\Users\tetov\scoop\apps\mambaforge\current\envs\smithy\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\tetov\scoop\apps\mambaforge\current\envs\smithy\Lib\site-packages\conda_smithy\cli.py", line 758, in main
    args.subcommand_func(args)
  File "C:\Users\tetov\scoop\apps\mambaforge\current\envs\smithy\Lib\site-packages\conda_smithy\cli.py", line 636, in __call__
    lints, hints = linter.main(
                   ^^^^^^^^^^^^
  File "C:\Users\tetov\scoop\apps\mambaforge\current\envs\smithy\Lib\site-packages\conda_smithy\lint_recipe.py", line 680, in main
    results, hints = lintify_meta_yaml(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tetov\scoop\apps\mambaforge\current\envs\smithy\Lib\site-packages\conda_smithy\lint_recipe.py", line 301, in lintify_meta_yaml
    conda_recipe_v1_linter.lint_package_version(meta, lints)
  File "C:\Users\tetov\scoop\apps\mambaforge\current\envs\smithy\Lib\site-packages\conda_smithy\linter\conda_recipe_v1_linter.py", line 144, in lint_package_version
    version = get_recipe_version(recipe_content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tetov\scoop\apps\mambaforge\current\envs\smithy\Lib\site-packages\conda_smithy\linter\conda_recipe_v1_linter.py", line 121, in get_recipe_version
    rendered_context_recipe.get("package", {}).get("version", "").strip()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by claudiushaag** [comment]
Hey,
I'm not a maintainer, just stumbled across your PR... I think your version needs to be a string, not a number. That's why the 'strip()'-method results in an error.
Enclosing the version in parentheses should do the trick.

**Comment by tetov** [comment]
@claudiushaag: Thanks! I noticed it too and submitted a PR (https://github.com/conda-forge/conda-smithy/pull/2130) to make the linter handle it. Since the build can handle the integer version number the linter should as well :).

**Comment by tetov** [comment]
@conda-forge-admin, please lint

**Comment by tetov** [comment]
@conda-forge-admin, please lint

**Review by xhochy — APPROVED** [review]

**Pull request merged**
