### PR TITLE
Adding perl packages from cpan

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by tdegeus** [comment]
I think I'm giving up. The number of dependencies is overwhelming and I see no light at the end of the tunnel. Can you comment @conda-forge/help-perl

**Comment by timsnyder** [comment]
@tdegeus I did some work on `conda skeleton cpan` in https://github.com/conda/conda-build/pull/3671 last August when I needed to build a big tree of Perl packages.  However, it didn't get merged before I was laid off from my previous employer and I've since not needed to worry about Perl.

Are you just wanting the 4 packages from your initial commit 8204270 and all of their dependencies?

I could try to refresh my PR and see if it will resolve all of the deps.  Are you wanting them all to be in conda-forge or can we add only the ones that bioconda is missing?  I'm not sure about the exact hierarchy of things.  Someone like @marcelotrevisani or @jerowe might know more.

**Comment by tdegeus** [comment]
Hi @timsnyder . I'm not a regular Perl user, I just wanted to add https://github.com/cmhughes/latexindent.pl to conda-forge (and maybe also https://github.com/ftilmann/latexdiff in the future). For *latexindent.pl* I need 
```none
 - cpanm YAML::Tiny
 - cpanm File::HomeDir
 - cpanm Unicode::GCString
 - cpanm Log::Log4perl
 - cpanm Log::Dispatch::File
```
I started adding them, and got in this hopelessly deep dependency tree.

**Comment by timsnyder** [comment]
Thanks for the background info on your intent @tdegeus.  Refreshing my branch to latest conda-build appears push button (it rebased cleanly). I'll see what happens if I feed it your list of requirements for `latexindent.pl`.  

Once we understand all of the recipes that are needed, maybe someone from @conda-forge/perl or larger conda-forge or bioconda communities will have an opinion on where all of the recipes and packages should live.

**Comment by timsnyder** [comment]
`conda skeleton cpan --recursive YAML::Tiny File::HomeDir Unicode::GCString Log::Log4perl Log::Dispatch::File` from my rebased PR branch ran for 22.5m generating 105 package recipes before it hit an unrecoverable error.  Although 29 of them are Dist::Zilla packages that are probably spurious dependencies.  Dist::Zilla is typically only required when building the CPAN distribution and uploading it to CPAN.  

The error hit was while processing the dependencies for Package::Stash.  It has something called `inc::MMPackageStash` in it's dependency metadata that the skeleton code wasn't able to lookup.

The recipes generated also have a few issues:

- license_file is missing in some
- license is usually not a SPDX identifier.  I hacked conda-smithy to spit out what is being used and I should be able to do some cheeseball mapping or use something like [difflib.get_closest_matches](https://stackoverflow.com/questions/10018679/python-find-closest-string-from-a-list-to-another-string) to suggest legal strings. Looking at what is being used, a cheesball dict that is coded could get us pretty far:
```
[I] ➜ grep -h 'license:' perl*/*/meta.yaml | sort | uniq -c
   9   license: apache_2_0
   5   license: artistic_2
   2   license: lgpl_2_1
   1   license: mit
   2   license: open_source
  81   license: perl_5
   5   license: unknown
```
- skeleton doesn't put the `extra.recipe_maintainers` in meta.yaml.  This is easy to tack on the end.
- `conda skeleton cpan` puts the recipes in a two level directory hierarchy.  This is also easy to flatten.
- It generates recipes without regard to whether there is already a conda-forge or bioconda recipe.  This is also easy to delete the recipes after the fact.

Seems like it will take me a few hours to dig into the `inc::MMPackageStash` dependency error and get it straightened out.  I might be able to get to that in the next week or so.

**Comment by dpryan79** [comment]
On behalf of Bioconda we would be very happy if someone succeeded in migrating these packages to conda-forge. On our side there are few if any active contributors who want to touch perl packages, so the copies of these on our channel are unmaintained at the moment. If someone can get the process started I expect we could help a little, but I've noticed that at least some of the perl packages (as currently implemented) have circular dependencies, which will make this process very difficult.

**Comment by scopatz** [comment]
Looks like there are conflicts now

**Comment by tdegeus** [comment]
Since it is becoming a bigger project than I originally intended, a better strategy might be needed. I propose to first integrate a number of bioconda's perl packages here, and then take it further from there. A question beforehand: is there hope of enabling Windows too?

**Comment by tdegeus** [comment]
In terms of maintainability: I don't suppose that cpan is automatically scanned for updates?

**Comment by tdegeus** [comment]
For now I don't see 'light at the end of the tunnel', so I'm closing for now.

**Pull request closed without merging**
