### PR TITLE
add sklearn

### PR DESCRIPTION
**Pull request by Silun**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
@conda-forge/core We do not have a specific policy about this, but the name of this recipe is within a common namespace of scikit-learn IIRC.

**Comment by beckermr** [comment]
scikit-learn is the first google result for sklearn for example: https://www.google.com/search?q=sklearn&oq=sklearn&aqs=chrome..69i57j0i433j0j0i433l3j69i61l2.1268j0j7&sourceid=chrome&ie=UTF-8

**Comment by mbargull** [comment]
https://pypi.org/project/sklearn/
> Project description
>
> Use [scikit-learn](https://pypi.python.org/pypi/scikit-learn/) instead.

https://github.com/KeithGalli/sklearn
> sklearn
>
> Data & Code associated with my tutorial on the sci-kit learn machine learning library in python

Also, https://pypi.org/project/sklearn and https://github.com/KeithGalli/sklearn are not the same, contrary to what this recipe indicates.

I see no reason why we should add this because the package description says "Use [scikit-learn](https://pypi.python.org/pypi/scikit-learn/) instead".

**Review by xhochy — CHANGES_REQUESTED** [review]
The URL and the PyPI don't even match.

**Comment by xhochy** [comment]
We could be nice and add a `sklearn` to the scikit-learn feedstock but this is definitely misleading.

**Comment by Silun** [comment]
I am honestly confused about this package. I already asked the maintainer if he would consider switching to scikit-learn directly, but I wouldn't bet on it. I am just trying to get `pdpipe` on conda-forge, and this package was confusing in more than just one way. Not trying to mislead anybody, it was my best guess.

**Comment by beckermr** [comment]
No worries! We are not blaming anyone and are as confused as you are. However, we won't be merging this PR in its current form.

**Comment by mbargull** [comment]
> I am just trying to get `pdpipe` on conda-forge

AFAICT, depending on `scikit-learn` should do be all you need: https://github.com/pdpipe/pdpipe/blob/v0.0.52/setup.py#L45

**Comment by Silun** [comment]
I'll try that over on https://github.com/conda-forge/staged-recipes/pull/13097

**Comment by beckermr** [comment]
Great! I am going to close this one for now.

**Comment by mbargull** [comment]
To give more context:
The distribution package on PyPI is called `scikit-learn` but the actual Python package that you get when you install `scikit-learn` is called `sklearn`, i.e., `import sklearn` is what you'd do in dependent code.
The Conda package is also called `scikit-learn`, hence the `scikit-learn` requirement in `meta.yaml` will give you all you need.

**Comment by Silun** [comment]
Thank you for the explanation. I removed sklearn from the meta.yaml of https://github.com/conda-forge/staged-recipes/pull/13097 and now it passes all checks. 🎉

**Comment by ocefpaf** [comment]
I've seen these before, specially in the django world, packages that only "reserves" a name and installs another package. But the metadata on this one is odd to say the least. Just for fun, this is the `setup.py`:


```python
# encoding: utf8

from setuptools import setup


setup(
    author='UNKNOWN',
    author_email="UNKNOWN\nblas_opt_info:\nblas_mkl_info:\n  FOUND:\n    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']\n    library_dirs = ['/Users/filo/anaconda/lib']\n    define_macros = [('SCIPY_MKL_H', None)]\n    include_dirs = ['/Users/filo/anaconda/include']\n\n  FOUND:\n    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']\n    library_dirs = ['/Users/filo/anaconda/lib']\n    define_macros = [('SCIPY_MKL_H', None)]\n    include_dirs = ['/Users/filo/anaconda/include']\n\nUNKNOWN",
    description='A set of python modules for machine learning and data mining',
    install_requires=['scikit-learn'],
    long_description='''Use `scikit-learn <https://pypi.python.org/pypi/scikit-learn/>`_ instead.''',
    maintainer='UNKNOWN',
    maintainer_email="UNKNOWN\nblas_opt_info:\nblas_mkl_info:\n  FOUND:\n    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']\n    library_dirs = ['/Users/filo/anaconda/lib']\n    define_macros = [('SCIPY_MKL_H', None)]\n    include_dirs = ['/Users/filo/anaconda/include']\n\n  FOUND:\n    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']\n    library_dirs = ['/Users/filo/anaconda/lib']\n    define_macros = [('SCIPY_MKL_H', None)]\n    include_dirs = ['/Users/filo/anaconda/include']\n\nUNKNOWN",
    name='sklearn',
    platforms=['all'],
    py_modules=['wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141'],
    url='https://pypi.python.org/pypi/scikit-learn/',
    version="0.0",
    zip_safe=False,
)
```

The main issue with these packages are the bad version number. If this is really necessary, we can do better with multiple outputs on scikit-learn to create an sklearn from it. But I do not recommend that unless it is really necessary! (Which does not seem to be the case here.)

**Pull request closed without merging**
