### PR TITLE
add cvxpy

### PR DESCRIPTION
**Pull request by dougalsutherland**
Split from #6076.

Depends on #6078, #6079, #6080.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for taking this on, @dougalsutherland :)

**Comment by SteveDiamond** [comment]
@dougalsutherland cvxpy is Apache 2.0

**Comment by dougalsutherland** [comment]
> cvxpy is Apache 2.0

Not according to https://github.com/cvxgrp/cvxpy/blob/master/COPYING, https://github.com/cvxgrp/cvxpy/blob/master/copyright.txt, or https://github.com/cvxgrp/cvxpy/blob/master/setup.py#L66....

**Comment by SteveDiamond** [comment]
This is very amusing. I accidentally undid the conversion to Apache 2.0 when I merged in the 1.0 branch. We will fix this.

**Comment by dougalsutherland** [comment]
@conda-forge/staged-recipes Ready for review! :)

**Comment by scopatz** [comment]
Thanks @dougalsutherland!

**Pull request merged**
