### PR TITLE
Add epics base

### PR DESCRIPTION
**Pull request by CJ-Wright**
Take over of #640
based off of the recipe in lightsource2-recipes

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes I could use some help with the missing g++ on linux.

**Comment by scopatz** [comment]
You need to add gcc and toolchain to the build deps, an libgcc to run deps

**Comment by isuruf** [comment]
It's looking for `g++` in a hard-coded place. Why don't you upgrade to the latest stable release to see if this has been fixed.

**Comment by CJ-Wright** [comment]
Thwarted once again. Closing for now ad I don't need this immediately.  Attn: @stuartcampbell

**Comment by CJ-Wright** [comment]
@stuartcampbell

**Pull request closed without merging**
