### PR TITLE
Add gms_preprocessing

### PR DESCRIPTION
**Pull request by danschef**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by danschef** [comment]
@conda-forge/staged-recipes 

This is ready for review.

**Comment by asford** [comment]
@ocefpaf @danschef Isn't the redis recipe included here already present in conda-forge as redis-py?

https://github.com/conda-forge/redis-py-feedstock

Now duped as:

https://github.com/conda-forge/redis-feedstock

**Comment by ocefpaf** [comment]
Yep I just opened on issue to track that. I'll remove the package but I'll wait for @danschef to archive the feedstock. xref: https://github.com/conda-forge/redis-feedstock/issues/1

**Comment by danschef** [comment]
@ocefpaf @asford 

First, thanks for merging!

Sorry for submitting a duplicate - I am not the author of redis-py but just always used `from redis import Redis` in my codes. Since I could not find 'redis' on conda-forge, I added a recipe. However, it is quite misleading that the PyPI package redis is not the same like the conda redis package from the defaults channel. To install redis-py one has to either use `pip install redis` or `conda install -c conda-forge redis-py`.

I will just use redis-py in the run requirements of my recipes now but the linting bot will then complain that I use 'import redis' in my codes although only redis-py is listed in the recipe.

**Comment by chrisburr** [comment]
> linting bot will then complain that I use 'import redis' in my codes although only redis-py is listed in the recipe.

Do you have an example of this? Conda-forge doesn't aim to be fully compatible with PyPI's namespace so it shouldn't be a lint error.

**Comment by ocefpaf** [comment]
> Sorry for submitting a duplicate - I am not the author of redis-py but just always used `from redis import Redis` in my codes. Since I could not find 'redis' on conda-forge, I added a recipe.

No problem. That happens a lot.

> However, it is quite misleading that the PyPI package redis is not the same like the conda redis package from the defaults channel. To install redis-py one has to either use `pip install redis` or `conda install -c conda-forge redis-py`.

Well. PyPI names can clobber c-libs that they wrap b/c PyPI is a publishing platform only for Python packages. Conda-forge is not! So when there is a name clash we must choose which one to keep.

Note that the redis in defaults is the actual redis server! You probably need that to use `redis-py` but it is not a direct dependency b/c in the past people used redis-py with system installed redis.

See https://github.com/andymccurdy/redis-py/#installation for more info on that dependency.

> I will just use redis-py in the run requirements of my recipes now but the linting bot will then complain that I use 'import redis' in my codes although only redis-py is listed in the recipe.

You mean the experimental dependency inspection? If so, that is safe to ignore. (Pinging @CJ-Wright here who authored that.)

**Comment by danschef** [comment]
> PyPI is a publishing platform only for Python packages. Conda-forge is not!

Right, good to have some reviewers who find such duplicates!

> You mean the experimental dependency inspection? If so, that is safe to ignore.

Yes, exactly. I like this inspection but how does it deal with naming discrepancies between the way a library is imported in Python and the name of the same library in the recipe (e.g. 'import redis' vs. 'redis-py' in the meta.yaml)? I guess, there is some kind of a mapping because it does not complain about scikit-learn, for example, which is imported with 'import sklearn'.

**Comment by ocefpaf** [comment]
> Right, good to have some reviewers who find such duplicates!

We have a linter and a human. Both failed here :smile: and the latter was me ;-p

> Yes, exactly. I like this inspection but how does it deal with naming discrepancies between the way a library is imported in Python and the name of the same library in the recipe (e.g. 'import redis' vs. 'redis-py' in the meta.yaml)? I guess, there is some kind of a mapping because it does not complain about scikit-learn, for example, which is imported with 'import sklearn'.

Yep. There is a mapping. When I was developing it it [was here](https://github.com/ericdill/depfinder/blob/master/depfinder/pkg_data/pkg_data.yml). I know people have ideas of factoring that out though. @CJ-Wright knows more.

**Comment by danschef** [comment]
Nice, so I could file a pull request that adds 'redis: redis-py' there, right?

**Comment by ocefpaf** [comment]
Yep.

**Pull request merged**
