### PR TITLE
Initial recipe for lume-impact

### PR DESCRIPTION
**Pull request by ChristopherMayes**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by ChristopherMayes** [comment]
@conda-forge/help-python This is ready for review.

**Comment by CJ-Wright** [comment]
This seems to remove another recipe, can you please rebase?

**Comment by CJ-Wright** [comment]
Otherwise this looks in order

**Comment by ChristopherMayes** [comment]
@CJ-Wright What recipe? `lume-impact` seems unique to me.

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/staged-recipes/pull/10649/files#diff-00234dd2d7e13560aaba7c1603129ba2
This seems to remove a recipe

**Comment by ChristopherMayes** [comment]
@CJ-Wright Oh, that was another of my recipes that I copied and cleaned up. But does that matter now? This is a clean recipe.

**Comment by CJ-Wright** [comment]
I'm confused, was that recipe already accepted? We've had issues in the past with recipes being unintentionally removed and they weren't built into feedstocks

**Comment by ChristopherMayes** [comment]
@CJ-Wright Yes, https://github.com/conda-forge/openpmd-beamphysics-feedstock was accepted.

**Comment by CJ-Wright** [comment]
I'm surprised that this isn't getting merge conflicts, since it should have been deleted in a different commit.

**Pull request merged**
