### PR TITLE
Add lightly recipe

### PR DESCRIPTION
**Pull request by adamjstewart**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@conda-forge/help-python, ready for review!

**Comment by adamjstewart** [comment]
Update: not yet ready, need to first add a lightly-utils recipe...

**Comment by adamjstewart** [comment]
Not really sure what to do about the failing Windows tests. There are many other PyTorch extensions that don't seem to have this issue. Would appreciate guidance on this.

**Comment by ocefpaf** [comment]
> Not really sure what to do about the failing Windows tests. There are many other PyTorch extensions that don't seem to have this issue. Would appreciate guidance on this.

We don't have pytorch on Windows but it is still preffered to keep this noarch and let the solver prevent the Windows installation.

**Comment by guarin** [comment]
Hi @adamjstewart, I just checked the anaconda package repository and could only find `lightly-utils`, is this expected?

We'll have to check how much effort it is to maintain the conda version as we do weekly releases. Is there an automated workflow to update the version and hash on every release?

**Comment by adamjstewart** [comment]
Lightly is now there as well: https://anaconda.org/conda-forge/lightly

What happened was that both repos were created at the same time. The lightly-utils repo passed, but the lightly repo failed because no lightly-utils binary existed yet. I just had to add a newer version of lightly (or bump the recipe to build version 1) to get lightly to pass.

There is an automated workflow to update the version and hash on every release, see https://github.com/conda-forge/lightly-feedstock/pull/1 for an example. It also suggests:

> If you want these PRs to be merged automatically, make an issue with `@conda-forge-admin, please add bot automerge` in the title and merge the resulting PR. This command will add our bot automerge feature to your feedstock.

The only work you would need to do is to update the dependencies when necessary.

We also have a [Spack recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-lightly/package.py) if you want to help maintain that. Unfortunately there's no automated workflow for that.

**Comment by guarin** [comment]
Thanks for detailed explanation! This sounds good from my side, feel free to add me to the maintainers list.

> We also have a [Spack recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-lightly/package.py) if you want to help maintain that. Unfortunately there's no automated workflow for that.

I think we'll pass on Spack for now and first look how much effort the conda version is. But happy to look at it again at a later date :)

**Pull request merged**
