### PR TITLE
Add Playwright

### PR DESCRIPTION
**Pull request by rxm7706**
https://github.com/microsoft/playwright-python/blob/main/meta.yaml

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by rxm7706** [comment]
Error
  - nothing provides requested auditwheel 5.4.0.*
Pending
  - https://github.com/conda-forge/auditwheel-feedstock/pull/51

**Comment by BastianZim** [comment]
@rxm7706 The new playwright version should now be available. https://github.com/conda-forge/auditwheel-feedstock/pull/55

**Comment by BastianZim** [comment]
@conda-forge-admin, please restart ci

**Comment by mxschmitt** [comment]
Hey, Playwright maintainer here. We are considering moving to conda-forge instead of publishing to a custom conda channel.

As of today we publish 5 wheels - for each OS we support - would something like that be supported with conda-forge as well?

See here: https://github.com/microsoft/playwright-python/blob/main/.github/workflows/publish.yml

**Comment by rxm7706** [comment]
@mxschmitt @BastianZim - I will add you to the recipe as maintainers - so we can try to get this working 
@mxschmitt I see this error now - might be a good idea to start with publishing the source to pypi - versus needing to depend on pre-built wheels / source from git -- https://pypi.org/project/playwright/#files 
Source Distributions
No source distribution files available for this release.See tutorial on [generating distribution archives](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives).

```
  LookupError: setuptools-scm was unable to detect version for /home/conda/staged-recipes/build_artifacts/playwright-python_1715375624843/work.

  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```

**Comment by BastianZim** [comment]
Thanks @rxm7706!

**Comment by BastianZim** [comment]
Hi @mxschmitt thanks for stopping by – publishing it here would be great for the conda-forge ecosystem as there are some major packages that require Playwright.

> As of today we publish 5 wheels - for each OS we support - would something like that be supported with conda-forge as well?

Generally, we publish for Linux, MacOS and Windows and the [supported](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html#managing-python) python versions, so one package for each combination of version and platform. 

As @rxm7706 mentioned, having a source distribution would be great as that allows us to build off of that. 
The other thing is the `download_driver` section in your setup.py which seems to download something prebuilt? Would you mind elaborating on what that is as conda-forge tries to build everything ourselves and not just redistribute it.

**Comment by mxschmitt** [comment]
`download_driver` is the combination out of official Node.js + the [microsoft/playwright Node.js project](https://github.com/microsoft/playwright) bundled together into a zip, so that the Playwright Python project can easily consume it and launch it as a sub-process internally.

It's versioned by a version number which we'll upload to our CDN. And for our 5 platforms (win, mac-intel, mac-silicon, linux-arm64, linux-amd64), we put the right Node.js into the wheel, so that e.g. if you are on macOS-arm64, your wheel does not contain a Windows Node.js executable.

**Comment by jan-janssen** [comment]
@mxschmitt I build a linux version in https://github.com/conda-forge/staged-recipes/pull/26597 . Basically I disable the download during the setup and install the node.js package as a separate dependency. In addition, I just patched the version number to work around the setuptools related issue. Hope this is helpful.

**Pull request closed without merging**
