### PR TITLE
Add maskrcnn_benchmark recipe

### PR DESCRIPTION
**Pull request by hadim**
Ping @fmassa.

DO NOT MERGE.

### CODE REVIEW

**Comment by hadim** [comment]
I don't know how it's possible to add a custom channel to the recipe (I am not even sure it's allowed...). We need pytorch 1.0 to this recipe but the package is only available in the pytorch Anaconda channel at https://anaconda.org/pytorch.

Also, how is it possible to use a more recent C++ compiler, we need G++ >= 4.9?

Also yacs, currently does not have a conda package. I am working on it.

**Comment by hadim** [comment]
yacs package should be available soon. Now I don't understand why the CI are all green: https://circleci.com/gh/conda-forge/staged-recipes/31319?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by scopatz** [comment]
Thanks for putting this in. It looks like it is failing CI

**Comment by hadim** [comment]
Currently waiting for https://github.com/conda-forge/staged-recipes/pull/6952 to be merged but there is other issues as said above:

- The package requires the pytorch 1.0 package that is not in conda forge but in another channel called `torch`. Any chance I can add this channel as a dep during building?
- Also, how is it possible to use a more recent C++ compiler, we need G++ >= 4.9?

**Pull request closed without merging**
