### PR TITLE
add face-recognition

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by BastianZim** [comment]
Isn't this a duplicate of https://github.com/conda-forge/face_recognition-feedstock

**Comment by ocefpaf** [comment]
> Isn't this a duplicate of https://github.com/conda-forge/face_recognition-feedstock

Looks like it. Our dup lint ia failing again :-/

I'll remove the feedstock.

**Comment by isuruf** [comment]
It wasn't. The linter warned in https://github.com/conda-forge/staged-recipes/pull/20633#issuecomment-1265927541

**Comment by synapticarbors** [comment]
My apologies for overlooking the linter warning when I merged it. Do we have a way of making some linting errors register a failure rather than just a suggestion? That would make it harder to miss.

**Comment by ocefpaf** [comment]
> My apologies for overlooking the linter warning when I merged it. Do we have a way of making some linting errors register a failure rather than just a suggestion? That would make it harder to miss.

Been there, done that. Not a big deal and easy to fix. However I agree, we should make that am error. Better merge with a lint failure but sure it is a false positives than a warning we don't pay attention to.

**Pull request merged**
