### PR TITLE
add tobler

### PR DESCRIPTION
**Pull request by knaaptime**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by knaaptime** [comment]
@sjsrey would you mind commenting here that you agree to co-maintain with me?

**Comment by knaaptime** [comment]
this is failing from a numpy conflict and i have no idea why

**Comment by knaaptime** [comment]
(i was putting the dependencies under `host` instead of `run` 🤦‍♂️)

**Comment by npavlovikj** [comment]
@ sjsrey, are you ok being listed as a maintainer for this recipe?

**Comment by knaaptime** [comment]
@npavlovikj in case the "thumbs up" didnt trigger a notification, @sjsrey has agreed to co-maintain :)

**Comment by npavlovikj** [comment]
> @npavlovikj in case the "thumbs up" didnt trigger a notification, @sjsrey has agreed to co-maintain :)

I do not get notifications for that, so thank you for pinging me :)

**Comment by npavlovikj** [comment]
Thank you for contributing @knaaptime 🎉

**Pull request merged**
