### PR TITLE
Tmaptools

### PR DESCRIPTION
**Pull request by agcopenhaver**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0

### CODE REVIEW

**Comment by agcopenhaver** [comment]
need lwgeom to be accepted before this will build

**Comment by agcopenhaver** [comment]
@conda-forge/staged-recipes just reopened this after a few days and figured I'd give you a ping

**Comment by dbast** [comment]
Looks good. Some remarks:
* Please use for creating a bit cleaner R recipes: https://github.com/bgruening/conda_r_skeleton_helper
* Please in the future ping @conda-forge/help-r for getting a review of a R recipe. By naming the PR topic like r-$pkgname it would get more obvious.
* Please also include @conda-forge/r as recipe maintainers.

**Comment by dbast** [comment]
This looks like it could be noarch... so definitely update by applying https://github.com/bgruening/conda_r_skeleton_helper

**Comment by dbast** [comment]
@agcopenhaver Thanks!

**Pull request merged**
