### PR TITLE
Add correctionlib

### PR DESCRIPTION
**Pull request by lgray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

@conda-forge/help-python
@conda-forge/help-c-cpp

@nsmith- @pieterdavid @IzaakWN

### CODE REVIEW

**Comment by lgray** [comment]
@nsmith- @pieterdavid @IzaakWN - could each of you please confirm that you OK with being a maintainer of this conda package?

**Comment by pieterdavid** [comment]
> @nsmith- @pieterdavid @IzaakWN - could each of you please confirm that you OK with being a maintainer of this conda package?

Fine with me

**Comment by IzaakWN** [comment]
> @nsmith- @pieterdavid @IzaakWN - could each of you please confirm that you OK with being a maintainer of this conda package?

Hey @lgray, I haven't really contributed to this part of `correctionlib`, but I don't mind for "just in case".

**Comment by nsmith-** [comment]
Ok for me

**Comment by lgray** [comment]
@nsmith- @pieterdavid whichever one of you maintains the CI for correctionlib - apparently you can go ahead and add windows. Neat.

**Comment by lgray** [comment]
FYI @conda-forge/help-python @conda-forge/help-c-cpp this one looks ready to go!

**Comment by nsmith-** [comment]
correctionlib CI already tests windows

**Comment by lgray** [comment]
Ah ok - just didn't catch that it did! Thanks!

**Pull request merged**
