### PR TITLE
add scifem

### PR DESCRIPTION
**Pull request by minrk**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

### CODE REVIEW

**Comment by minrk** [comment]
@finsberg @jorgensd if you can comment here, I've added you as maintainers of the recipe

**Comment by jorgensd** [comment]
I can be maintainer:)

**Comment by finsberg** [comment]
I can also be a maintainer😎

**Comment by minrk** [comment]
Skipped Python 3.9 builds here due to https://github.com/scientificcomputing/scifem/pull/41

Can re-add them with a patch or on next release on the feedstock.

Linux test `test_singular_poisson[4-2-float64]` is failing with an `allclose` check missing atol by 2%:

```python
assert np.isclose(np.float64(1.8175143966085475e-12), 0, atol=np.float64(1.7763568394002505e-12))
```

Not sure if the test tolerance is just a little too strict or if there's a real issue here.

**Comment by minrk** [comment]
@conda-forge/help-python-c ready for review

**Review by xhochy — APPROVED** [review]

**Pull request merged**
