### PR TITLE
Add chemml

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jan-janssen** [comment]
`wget` is not available for windows, still I would prefer this package to be `noarch`.

**Comment by jan-janssen** [comment]
As `tensorflow` does not fulfill `pip check` - the pip check is removed. 
```
tensorflow 2.4.1 has requirement six~=1.15.0, but you have six 1.16.0.
tensorflow 2.4.1 has requirement typing-extensions~=3.7.4, but you have typing-extensions 3.10.0.0.
```

**Comment by jan-janssen** [comment]
@conda-forge/staged-recipes, ready for review

**Comment by ocefpaf** [comment]
> `wget` is not available for windows, still I would prefer this package to be `noarch`.

If wget is an optional dependency maybe you can remove it and this will work on Windows too. If not, there are ways to get wget on Windows and a recipe for it would be nice.

**Pull request merged**
