### PR TITLE
add django-cachalot

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by helloreuben** [comment]
@sannykr spelling of the package is wrong in the meta.yaml .. {% set name = "djnago-cachalot" %} it should be django-cachalot not djnago

**Comment by sannykr** [comment]
@helloreuben: Thanks. I will correct it

**Comment by sannykr** [comment]
@jakirkham : windows check is running forever. Should I close and reopen the pull request?

**Comment by jakirkham** [comment]
It seems the build was canceled and the status was not updated here. Have restarted the build.

**Pull request merged**
