### PR TITLE
Added recipe for hover 0.6.0 [ready for review]

### PR DESCRIPTION
**Pull request by phurwicz**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by haochuanwei** [comment]
This is Haochuan Wei (haochuanwei), willing to be listed as a maintainer.

**Comment by phurwicz** [comment]
This is Pavel Hurwicz (phurwicz), willing to be listed as a maintainer.

All maintainers (2 of 2) have commented.

**Comment by phurwicz** [comment]
@conda-forge-admin This recipe is ready. The Windows build failed because [`pytorch` on conda-forge](https://anaconda.org/conda-forge/pytorch) happens to be missing a Windows distribution.

**Comment by haochuanwei** [comment]
@conda-forge-admin please ping conda-forge/help-python

**Comment by phurwicz** [comment]
Aborting this PR due to too many commits. Creating a new one with the same diff.

**Comment by carterbox** [comment]
@phurwicz, if you want to rebase, then you can just force-push to this same branch. If you open a new PR, then your collaborators have to recomment.

**Comment by phurwicz** [comment]
> @phurwicz, if you want to rebase, then you can just force-push to this same branch. If you open a new PR, then your collaborators have to recomment.

@carterbox Thanks for the advice! We will force push next time. Was thinking that we ought to make it cleaner for review.
New PR with re-comments here: https://github.com/conda-forge/staged-recipes/pull/18038

**Pull request closed without merging**
