### PR TITLE
Pytest sugar

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by mwcraig** [comment]
Close/reopen to trigger CI

**Comment by mwcraig** [comment]
The remaining failures are real (tests need termcolor): https://travis-ci.org/conda-forge/staged-recipes/builds/263349989#L302

**Comment by sannykr** [comment]
@mwcraig : Thanks for your help. I have added the requirements, but I don't understand why it doesn't work. Could you please look at it.

**Comment by sannykr** [comment]
@mwcraig : I can't see python 3.5 and 2.7 files for windows. Do I need to re-render the feedstock?

**Comment by sannykr** [comment]
@mwcraig : python 27 and 35 for windows are still not on conda-forge. Could you please retrigger the build.

**Comment by sannykr** [comment]
@synapticarbors : Although it is available on conda-forge, python 27 and 36 files are missing for windows. Will it be helpful if build is retriggered?

**Pull request merged**
