### PR TITLE
Add R package RcppZiggurat.

### PR DESCRIPTION
**Pull request by jdblischak**
CRAN R package [RcppZiggurat](https://cran.r-project.org/package=RcppZiggurat). Recipe created with conda-build 2.1.18 and [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper).

### CODE REVIEW

**Comment by jdblischak** [comment]
It's not able to find gsl.

Linux:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/conda/staged-recipes/build_artifacts/r-rcppziggurat_1522158356941/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/R/library/RcppGSL/libs/RcppGSL.so':
  libgsl.so.23: cannot open shared object file: No such file or directory
```

macOS:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/travis/miniconda/conda-bld/r-rcppziggurat_1522158620573/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/RcppGSL/libs/RcppGSL.so':
  dlopen(/Users/travis/miniconda/conda-bld/r-rcppziggurat_1522158620573/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/RcppGSL/libs/RcppGSL.so, 6): Library not loaded: @rpath/libgsl.23.dylib
  Referenced from: /Users/travis/miniconda/conda-bld/r-rcppziggurat_1522158620573/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/RcppGSL/libs/RcppGSL.so
```

**Comment by jdblischak** [comment]
I'm going to need some assistance troubleshooting this recipe. It is failing somewhere during the linking of RcppZiggurat -> RcppGSL -> libgsl.

@bgruening Any ideas?

**Comment by jdblischak** [comment]
I rebased against master to incorporate the conda-build 3 updates to see if that changes anything.

**Comment by dbast** [comment]
Done via https://github.com/conda-forge/staged-recipes/pull/8957

**Pull request closed without merging**
