### PR TITLE
sdl2_image (new PR because the last one caused conflicts)

### PR DESCRIPTION
**Pull request by dschreij**
I have to make a small change (just removed a line in CMakeLists.txt), because Github otherwise said the master branch and my one were identical. In the process, I also discovered that I didn't call make check, which jakirkham has advised me to do a couple of times. So I changed that too.

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...we lost the linter. 😕 Maybe this will wake it up.

**Comment by scopatz** [comment]
Looks like this one has conflicts now too

**Comment by dschreij** [comment]
@scopatz @jakirkham I see that a feedstock has been created for this recipe. Did you already solve the conflicts? Should I still fix this PR?

**Comment by jakirkham** [comment]
I think I missed the part where conflicts showed up, but yes I agree @dschreij . The feedstock is out there and operational. So I don't think we need this.

**Pull request closed without merging**
