### PR TITLE
Adding ipynbname recipe

### PR DESCRIPTION
**Pull request by msm1089**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by msm1089** [comment]
Package author here, willing to maintain recipe

**Comment by msm1089** [comment]
@conda-forge-admin, please ping team

Hi, I got an invite to join conda-forge following a recent release of a package on PyPi. The email I got did not really explain what I should do. After reading the README for `staged-recipes` I have tried following the instructions to add a recipe but all the CI is failing. I think I must be doing something wrong, but also I think the recipe may have already been added, so that I do not actually need to add it myself...could you help me out with what I am supposed to be doing after accepting the invite, if anything?

> Hi! This is the friendly automated conda-forge-linting service.
> 
> I wanted to let you know that I linted all conda-recipes in your PR (`recipes`) and found some lint.
> 
> Here's what I've got...
> 
> For **recipes**:
> 
> * *Feedstock with the same name exists in conda-forge*.
> * Please do not delete the example recipe found in `recipes/example/meta.yaml`.
> 
> For **recipes**:
> 
> * *A conda package with same name (ipynbname) already exists*.

**Comment by ocefpaf** [comment]
The name of the recipe file must be `meta.yaml`.

**Comment by msm1089** [comment]
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I wanted to let you know that I linted all conda-recipes in your PR (`recipes/ipynbname`) and found some lint.
> 
> Here's what I've got...
> 
> For **recipes/ipynbname**:
> 
> * Feedstock with the same name exists in conda-forge.
> 
> For **recipes/ipynbname**:
> 
> * A conda package with same name (ipynbname) already exists.

@conda-forge-admin, please ping team

So I fixed the recipe name. The lints suggest to me that the recipe already exists. As I said in previous message, I am not sure what (if any) action I should be taking after accepting the invite I got by email. Assumed I needed to add the recipe, but cannot. Could someone let me know what is going on? :)

**Comment by ocefpaf** [comment]
> So I fixed the recipe name. The lints suggest to me that the recipe already exists. As I said in previous message, I am not sure what (if any) action I should be taking after accepting the invite I got by email. Assumed I needed to add the recipe, but cannot. Could someone let me know what is going on? :)

I missed that part. You don't need to re-submit the recipe, closing this one.

You should have access to https://github.com/conda-forge/ipynbname-feedstock/ already. If not, you can update the team there with the bot command: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-update-team

**Pull request closed without merging**
