### PR TITLE
Add datalad-installer

### PR DESCRIPTION
**Pull request by jwodder**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jwodder** [comment]
@conda-forge/help-python How do I make a test script present in the recipe directory available when running tests?

**Comment by dopplershift** [comment]
[This section](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=test#source-files) from the `conda-build` docs should have what you need.

**Comment by jwodder** [comment]
@dopplershift That appears to be about copying files from the sdist tarball, whereas I need to use the `test.sh` file I added to this recipe directory.  I can't use the test script from the sdist, as it calls tox (which is a no-go here, as it requires the entire package source be available rather than installed), and I assume I can't express the script as `test.commands` elements, as I expect individual commands to be run in separate subshells, which doesn't work with the test script, as it needs to set some environment variables.

**Comment by jwodder** [comment]
@conda-forge/help-python Do you have any recommendations for debugging conda-forge build failures without having to make release after release?  Specifically, at the moment, I'd like a way to see the full contents of the pytest temp directory for the failing tests.

**Comment by dopplershift** [comment]
If you install `conda-build` locally, you can run `conda build /path/to/recipe/dir` and examine the output in e.g. `~/miniconda3/conda-bld`.

**Comment by jwodder** [comment]
@yarikoptic I believe the only thing keeping the tests from passing is that bash is not available on the Windows environment.  Thus, we need a `.bat` file for running the tests instead that does the equivalent of the following:

```
mkdir -p /c/tmp
export TMPDIR='C:\tmp'
exec python -m pytest -vv --ci -m 'not miniconda' test
```

**Comment by yarikoptic** [comment]
why not to make `bash` not required on windows, and then have a dedicated `test.bat` for windows?

**Comment by jwodder** [comment]
@yarikoptic Yes, that's what I'm suggesting.  The problem is that I don't know what such a `test.bat` would look like.

**Comment by yarikoptic** [comment]
have a look among those already there? https://github.com/search?q=org%3Aconda-forge+filename%3Atest.bat

**Comment by yarikoptic** [comment]
tried to resolve

<details>
<summary>with the following patch to just have run_test.{bat,sh}</summary> 

```diff
commit 026be53b4ad4bfa7650c85a9e3785bef3f802828
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Mon Jul 19 17:28:15 2021 -0400

    BF?: try to just have run_test.{bat,sh} files without explicit listing/command

diff --git a/recipes/datalad-installer/meta.yaml b/recipes/datalad-installer/meta.yaml
index 0168bc2c53..0c9bd683be 100644
--- a/recipes/datalad-installer/meta.yaml
+++ b/recipes/datalad-installer/meta.yaml
@@ -31,16 +31,11 @@ test:
     - pytest
     - pytest-cov
     - pytest-mock
-  files:
-    - test.sh
   source_files:
     - test
     - tox.ini
   imports:
     - datalad_installer
-  commands:
-    - bash test.sh  # [not win]
-    - test.bat  # [win]
 
 about:
   home: https://github.com/datalad/datalad-installer
diff --git a/recipes/datalad-installer/test.bat b/recipes/datalad-installer/run_test.bat
similarity index 100%
rename from recipes/datalad-installer/test.bat
rename to recipes/datalad-installer/run_test.bat
diff --git a/recipes/datalad-installer/test.sh b/recipes/datalad-installer/run_test.sh
similarity index 100%
rename from recipes/datalad-installer/test.sh
rename to recipes/datalad-installer/run_test.sh

```
</details>
but can't push to your fork, so diff is above @jwodder

**Comment by yarikoptic** [comment]
woohoo, it's green , thank you @jwodder.  I have double checked -- it did run tests on windows: "67 passed, 2 skipped, 8 deselected in 56.75s "

**Comment by yarikoptic** [comment]
And please consider this comment as the comment for "confirming they are willing to be listed there.", so that checkbox should be checked now somehow (I have no authority, @jwodder?)

Dear @dopplershift if you have time/authority to review/accept this feedstock -- would be very much appreciated. It is as green as you must like it ;)

**Comment by yarikoptic** [comment]
FTR: pinged gitter to bring attention to this PR.

**Comment by yarikoptic** [comment]
ping @conda-forge-coordinator  -- please advise on how to facilitate review/merge of this PR

**Comment by carterbox** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
