### PR TITLE
ENH adding psfex

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds psfex to conda-forge. 

@esheldon for viz

### CODE REVIEW

**Comment by beckermr** [comment]
A PR for moving the license file upstream is here: https://github.com/esheldon/psfex/pull/13

**Comment by beckermr** [comment]
I think we need a new name for this package in conda. I don't want to stomp on the `psfex` namespace since we could ship this too: https://github.com/astromatic/psfex

**Comment by beckermr** [comment]
Ideas:

py-psfex - not so great since it might imply a full python interface to psfex which is not what this is

psfex-reader - differs a lot from the upstream package but descriptive 

psfex-interface - same as last one

If the three above psfex-reader is the least worst. 

Comments anyone?

**Comment by beckermr** [comment]
An issue about renaming to psfex-reader is here: https://github.com/esheldon/psfex/issues/15

**Comment by esheldon** [comment]
psfex the original is a stand alone binary, it would never be useful to ship as a conda package

**Comment by beckermr** [comment]
Standalone binaries are shipped all the time with conda! It's a brave new world. You can get emacs with conda now. ;p

**Comment by scopatz** [comment]
Thanks @beckermr

**Comment by beckermr** [comment]
I guess the ship sailed in the name change. Ohhhh welll. We can fix later.

**Pull request merged**
