### PR TITLE
Add pylint

### PR DESCRIPTION
**Pull request by jakirkham**
Generated with `conda skeleton pypi` and cleaned up after. PyLint the well known Python linting program.

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems the build is failing for an odd reason related to `pkg_resources`. Opened upstream issue ( https://github.com/PyCQA/pylint/issues/1067 ).

**Comment by ericdill** [comment]
You need to add setup tools as a runtime dependency to astroid since Python 3.5 from conda forge does not include it. See this comment and the ones following it for more discussion on this subject https://github.com/conda-forge/staged-recipes/pull/687#issuecomment-238652704

**Comment by jakirkham** [comment]
So it should be fixed by your addition to `astroid`, correct @ericdill? I think I was mainly thrown by the error, `AttributeError: module 'pkg_resources' has no attribute '_namespace_packages'`, as opposed to something more straightforward like `ImportError: No module named pkg_resources`.

**Comment by jakirkham** [comment]
Transient download issue from anaconda.org on AppVeyor as can be seen in the [build log]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.5827/job/ny0p7kxobl458gbg#L212 ). Restarting...

**Comment by jakirkham** [comment]
Now passing. 💚

Any more thoughts on this one or is it good to go? Also do you want to be a maintainer on `pylint` as well, @ericdill?

**Comment by msarahan** [comment]
Merging. @ericdill, happy to add you in the feedstock.

**Comment by msarahan** [comment]
Thanks @jakirkham

**Comment by jakirkham** [comment]
@PCManticore @sthenault @godfryd @lmedioni @brettcannon, just letting you know that we have added `pylint` to [conda-forge]( http://conda-forge.github.io/ ). This will allow users to easily install this with [`conda`]( http://conda.pydata.org/docs/ ) ( [`conda install -c conda-forge pylint`]( http://anaconda.org/conda-forge/pylint ) ). The maintenance burden here is light as all releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this feedstock (repo)]( https://github.com/conda-forge/pylint-feedstock ). If any of you have any interest in being added as a maintainer (to make new releases for instance), we would be more than happy to add any of you to the maintainers list. Thanks for your work on this great project. 😄

**Pull request merged**
