### PR TITLE
add shogun mkl variant

### PR DESCRIPTION
**Pull request by vigsterkr**
this recipe adds Shogun with MKL backend.

### CODE REVIEW

**Comment by vigsterkr** [comment]
@dougalsutherland i hope you dont mind putting your name there, but it seemed to be the most appropriate.. windows part needs some love but then we could build a python package on top of this :)

**Comment by jakirkham** [comment]
Maybe it makes more sense to combine with the existing `shogun-cpp` feedstock?

**Comment by dougalsutherland** [comment]
Hey @vigsterkr, sorry I didn't see this earlier. This should definitely be a variant of `shogun`/`shogun-cpp` and not a separate recipe. I'll look into adapting it there sometime soon, after my looming paper deadline. :)

**Comment by vigsterkr** [comment]
@dougalsutherland conda-forge people told me that i should do this way as the variant is phasing out... so i reckon we should not do the variant ;)

**Comment by dougalsutherland** [comment]
@vigsterkr Variants aren't phasing out, as far as I know, though the way you do them changed a little while ago. If we combine the recipe, we can also probably use ccache to save a lot of time between the two builds. I'll put something together to unify it next week. :)

**Pull request closed without merging**
