### PR TITLE
Add r-dtwclust

### PR DESCRIPTION
**Pull request by dpryan79**
Made with the wrapper.

### CODE REVIEW

**Comment by dbast** [comment]
Hm... maybe '- {{posix}}findutils  [win]' get this building on windows?

**Comment by dpryan79** [comment]
@dbast It's a worth a try, I'll update and see.

**Comment by dpryan79** [comment]
That seems to have fixed things (not sure why windows on Azure has issues).

**Comment by dbast** [comment]
Appveyor windows build is succeeding now, fine. Azure windows build failed once ... now retriggered ...

**Comment by dpryan79** [comment]
Windows on Azure is still failing for some reason, but everything else is green.

**Comment by dbast** [comment]
The recipe looks good... what to do with the azure build, ignore it for now and merge?

**Comment by dpryan79** [comment]
I guess so.

**Pull request merged**
