### PR TITLE
Add r-huge

### PR DESCRIPTION
**Pull request by nick-youngblut**

### CODE REVIEW

**Comment by nick-youngblut** [comment]
I'm getting a weird error:

```
+ /home/conda/feedstock_root/build_artifacts/r-huge_1526925798348/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/R -e 'library('\''huge'\'')'
/home/conda/feedstock_root/build_artifacts/r-huge_1526925798348/test_tmp/run_test.sh: line 7: /home/conda/feedstock_root/build_artifacts/r-huge_1526925798348/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/R: No such file or directory
```

...and I'm not sure why R can't be found. I build the recipe with `conda skeleton cran` (conda-build v 3.10.4) just like the last R package recipe that I created. I searched through other PRs, but I can't find anyone that had the same problem. 

Any ideas?

**Comment by umarbrowser** [comment]
Please remove build.sh and bld.dat no need on conda-forge building see https://github.com/conda-forge/staged-recipes#8-do-i-need-bldbat-andor-buildsh

**Comment by nick-youngblut** [comment]
Thanks @umarbrowser for the suggestion! However, it didn't seemed to have helped. This is an R package, not a python package, and many R package feedstocks do contain at least a build.sh file (eg., the [ade4 feedstock](https://github.com/conda-forge/r-ade4-feedstock)). Any other ideas?

**Comment by umarbrowser** [comment]
Let me check for your

**Comment by CurtLH** [comment]
Have you seen [conda r skeleton helper](https://github.com/bgruening/conda_r_skeleton_helper)?  I use this to do the most of the work when creating r-recipes.  Most times there is some clean up required, like cleaning up the description or fixing the license, but this is a good way to start with a r-recipe.

**Comment by bgruening** [comment]
@nick-youngblut I have seen this error in a few other PRs lately. This is really wired. Need to look at it closer as soon as I'm back.
Maybe @jdblischak or @cbrueffer can help?

**Comment by cbrueffer** [comment]
Indeed, I've seen this problem all over the place in the last week or so. Haven't had time to look into it yet unfortunately.

**Comment by bgruening** [comment]
Thanks Nick!

**Pull request merged**
