### PR TITLE
Adding srt

### PR DESCRIPTION
**Pull request by gauranshkumar**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by gauranshkumar** [comment]
@conda-forge/staged-recipes Can you please review this and merge, Thanks!

**Comment by ndevenish** [comment]
You seem to have added `isosurfaces` both here and in https://github.com/conda-forge/staged-recipes/pull/19141 (and https://github.com/conda-forge/staged-recipes/pull/19143, but that isn't ready for review yet).

Since this is ready for review also, did you want to close the one on it's own and have them both merged in here (as per https://conda-forge.org/docs/maintainer/adding_pkgs.html#adding-multiple-packages-at-once)?

**Comment by gauranshkumar** [comment]
Sure, I was unfamiliar with the multiple package at once but I can close #19141 and have, both the packages here in this PR only.

**Comment by gauranshkumar** [comment]
Also, #19143 is a PR for different package which is not complete yet so I will remove other recipes from there and will keep only for the one that it intends to.
For now please merge this PR if everything seems fine to you @ndevenish

**Comment by ndevenish** [comment]
It's not really a problem, just that:
- If this gets merged first, the other one is redundant. If the other gets gets merged this one is fine.
- Having this dependent on the other requires two reviews, which can take longer :)

Also, it looks like the pypi package for srt includes the LICENSE file, so you don't need to include `recipes/srt/LICENSE` in this recipe, as it is clever enough to realise that `license_file: LICENSE` is inside the downloaded tarball. isosurfaces doesn't appear to have the LICENSE file included in the pypi tarball, so should be left in here.

**Comment by ndevenish** [comment]
> Also, #19143 is a PR for different package which is not complete yet so I will remove other recipes from there and will keep only for the one that it intends to.

The other one is fine to leave in for working on, until this is merged. Just multiple competing PRs is likely to generate a race condition

> For now please merge this PR if everything seems fine to you @ndevenish

That'll have to wait for someone official :)

**Comment by gauranshkumar** [comment]
Thanks for the review, I will remove the License from `srt` and then you can merge this, and as the remaining one i.e. #19143 is for a completely different package I will add a review request later as soon as it's ready.

**Comment by gauranshkumar** [comment]
https://github.com/orgs/conda-forge/teams/staged-recipes Can you please review this and merge, Thanks!

**Comment by gauranshkumar** [comment]
@conda-forge/staged-recipes Can you please review this and merge, Thanks!

**Comment by BastianZim** [comment]
Thanks for the initial review @ndevenish

**Pull request merged**
