### PR TITLE
Add jupyterlab-latex - again

### PR DESCRIPTION
**Pull request by jan-janssen**
I created https://github.com/conda-forge/staged-recipes/pull/11153 unfortunately I made a mistake, which caused the package to be named `juputerlab_latex` rather than  `juputerlab-latex` - so here we go again. 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge/staged-recipes, ready for review

**Comment by tadeu** [comment]
Here is the original PR: https://github.com/conda-forge/staged-recipes/pull/11153

It was merged, but I didn't find the feedstock (or packages). Has the feedstock for the wrong `jupyter_latex` already been removed?

**Comment by jan-janssen** [comment]
As I explained about above the issue is the name: 
https://github.com/conda-forge/jupyterlab_latex-feedstock 

But it should be `jupyterlab-latex` rather than `jupyterlab_latex`

**Comment by tadeu** [comment]
Ahh, sorry, I was looking for `jupyter_latex` instead of `jupyterlab_latex`, that's why I didn't find it 😊

**Comment by tadeu** [comment]
> As I explained about above the issue is the name:
> https://github.com/conda-forge/jupyterlab_latex-feedstock

> But it should be `jupyterlab-latex` rather than `jupyterlab_latex`

Ok, in this case it seems good to first delete the `jupyterlab_latex` feedstock and the packages: https://anaconda.org/conda-forge/jupyterlab_latex/files ([guidelines](https://conda-forge.org/docs/orga/guidelines.html#renaming-packages))

@conda-forge/core, could someone do this, please?

**Comment by jan-janssen** [comment]
Can you still merge it? I had another case some time ago and there merging was possible before the other recipe was removed: 
https://github.com/conda-forge/staged-recipes/pull/10107

It would help me to continue with updating the dependencies.

**Comment by tadeu** [comment]
Sure, just please keep track that the wrong feedstock and packages will be deleted

**Comment by jan-janssen** [comment]
Btw. If you do not mind, can you also review two more of my pull requests? 
https://github.com/conda-forge/staged-recipes/pull/11180
https://github.com/conda-forge/staged-recipes/pull/11187

**Pull request merged**
