### PR TITLE
Craftr

### PR DESCRIPTION
**Pull request by dfroger**

### CODE REVIEW

**Comment by dfroger** [comment]
- [ ] fix the traceback:

```
Fixing permissions
Fixing permissions
Detected hard-coded path in text file bin/craftr
'lib/python3.4/site-packages/craftr/stl/craftr.utils.git/Craftrfile' not in tarball
'lib/python3.4/site-packages/craftr/stl/craftr.utils.git/manifest.json' not in tarball
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build-all", line 6, in <module>
    sys.exit(conda_build_all.cli.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/cli.py", line 90, in main
    b.main()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 267, in main
    built_dist_location = self.build(meta, build_config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 204, in build
    conda_build.api.build(meta.meta, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 86, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1427, in build_tree
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1103, in build
    built_package = bundlers[output.get('type', 'conda')](output, m, config, env)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 840, in bundle_conda
    tarcheck.check_all(tmp_path)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/tarcheck.py", line 90, in check_all
    x.info_files()
  File "/opt/conda/lib/python3.5/site-packages/conda_build/tarcheck.py", line 55, in info_files
    raise Exception('info/files')
Exception: info/files
```

- [ ] some build requirements must be removed : there are only requirements need.

**Comment by dfroger** [comment]
I'm waiting for https://github.com/conda/conda-build/pull/1657 which fix the above exception.

**Comment by dfroger** [comment]
close and reopen to test with conda-build 2.1.2

**Comment by dfroger** [comment]
After [removing some build requriements](https://github.com/conda-forge/staged-recipes/pull/2189/commits/88d68bf02981344acc7416725cd3a73549d4f9ec), i get [erros](https://circleci.com/gh/dfroger/staged-recipes/23) that I don't understand:

``` python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 676, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/opt/conda/lib/python3.5/site-packages/conda/plan.py", line 484, in install_actions
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/opt/conda/lib/python3.5/site-packages/conda/resolve.py", line 871, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/opt/conda/lib/python3.5/site-packages/conda/resolve.py", line 908, in solve
    dists, new_specs = self.get_dists(specs)
  File "/opt/conda/lib/python3.5/site-packages/conda/resolve.py", line 517, in get_dists
    raise UnsatisfiableError(save_unsat)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - craftr 2.0.0.dev5 py36_0
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by dfroger** [comment]
Maybe just some dependencies that are not yet built for python 3.6

**Comment by dfroger** [comment]
For me, it's ready to be merge!

**Comment by jjhelmus** [comment]
LGTM, thanks @dfroger

**Pull request merged**
