### PR TITLE
Add django-reversion-compare

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@conda-forge-admin : Could you please review and merge.

**Comment by sannykr** [comment]
@conda-forge/staged-recipes : Could you please review and merge

**Comment by scopatz** [comment]
Thanks!

**Comment by jakirkham** [comment]
So this got added to the `example` directory. 😕 Also means that the recipe was not actually tested on CI. @sannykr, could you please submit a PR to move this out of the `example` directory?

**Comment by scopatz** [comment]
Oh Dang! Sorry I missed that @jakirkham

**Pull request merged**
