### PR TITLE
Bulk added R recipes for migration from bioconda (6)

### PR DESCRIPTION
**Pull request by jenzopr**
Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vend other packages
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

See also https://github.com/bioconda/bioconda-recipes/issues/13964

### CODE REVIEW

**Comment by jenzopr** [comment]
Ping @conda-forge/r for a review :-)

**Comment by dpryan79** [comment]
@conda-forge/help-r See above :)

**Comment by cbrueffer** [comment]
Done; thanks guys!

**Comment by bgruening** [comment]
I'm just too slow ... :) Thanks all!

**Comment by dbast** [comment]
This will also require retriggers to build + upload in the created feedstocks...

**Comment by cbrueffer** [comment]
Get your act together @bgruening! :-P

**Comment by dbast** [comment]
Retriggers done :)

**Pull request merged**
