### PR TITLE
feat: add ansys-tools-visualization-interface

### PR DESCRIPTION
**Pull request by RobPasMue**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by RobPasMue** [comment]
@AlejandroFernandezLuces - please add a comment saying you are willing to be this package's maintainer

**Comment by AlejandroFernandezLuces** [comment]
Yes, I'll be a maintainer of this repository

**Comment by RobPasMue** [comment]
@conda-forge-admin, please lint

**Comment by RobPasMue** [comment]
@conda-forge/help-python - do you have an idea why this might be failing? Are the runners missing libGL.so? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=947790&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1167

**Review by AlejandroFernandezLuces — APPROVED** [review]

**Comment by ocefpaf** [comment]
> @conda-forge/help-python - do you have an idea why this might be failing? Are the runners missing libGL.so? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=947790&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1167

Yep. You have to request it. See https://conda-forge.org/docs/maintainer/maintainer_faq/#how-do-i-fix-the-libglso1-import-error

**Comment by RobPasMue** [comment]
@conda-forge-admin, please re-render

**Comment by RobPasMue** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=947812&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=7c0f8eae-6d6f-51bf-636f-73a1a7fb1bc4&l=2067

Looks like VTK has some issues on Windows... this is very weird

**Comment by RobPasMue** [comment]
@conda-forge-admin, please rerender

**Comment by RobPasMue** [comment]
Looks like the issue is related to this... https://github.com/conda-forge/vtk-feedstock/pull/324

**Comment by RobPasMue** [comment]
@ocefpaf - is there anything we can do since the issue is related to a dependency's metadata?

**Comment by ocefpaf** [comment]
> @ocefpaf - is there anything we can do since the issue is related to a dependency's metadata?

The issue is:

```
WARNING: Skipping C:\bld\ansys-tools-visualization-interface_1717481759000\_test_env\Lib\site-packages\vtk-9.2.6.egg-info due to invalid metadata entry 'name'
pyvista 0.43.8 requires vtk, which is not installed.
```

If you are sure you have the right dependencies and that is a metadata problem upstream, you can skip pip-check and open an issue where the problem is.

**Comment by RobPasMue** [comment]
> > @ocefpaf - is there anything we can do since the issue is related to a dependency's metadata?
> 
> The issue is:
> 
> ```
> WARNING: Skipping C:\bld\ansys-tools-visualization-interface_1717481759000\_test_env\Lib\site-packages\vtk-9.2.6.egg-info due to invalid metadata entry 'name'
> pyvista 0.43.8 requires vtk, which is not installed.
> ```
> 
> If you are sure you have the right dependencies and that is a metadata problem upstream, you can skip pip-check and open an issue where the problem is.

Yes, you correctly identified the issue. That's also what I saw in the logs - and there is a related issue open: https://github.com/conda-forge/vtk-feedstock/pull/324. I will skip the pip-check

**Pull request merged**
