### PR TITLE
Add R recipes singletons

### PR DESCRIPTION
**Pull request by souravsingh**
Ping @bgruening 

This PR add the following recipes-
1)r-corrplot
2)r-nleqslv
3)r-rann
4)r-rgraphics
5)r-rtsne
6)r-shinyace
7)r-sparql

### CODE REVIEW

**Comment by souravsingh** [comment]
xref https://github.com/bioconda/bioconda-recipes/issues/5582

**Comment by souravsingh** [comment]
Ping @bgruening @daler

**Comment by bgruening** [comment]
@souravsingh the tests are failing and can you please use https://github.com/bgruening/conda_r_skeleton_helper to create recipes.

**Comment by souravsingh** [comment]
Thanks for the reply @bgruening.

**Comment by jdblischak** [comment]
> The error is coming from shinyAce, which needs investigating.

@souravsingh I took a quick look. r-shinyace built for R 3.3.2 but not 3.4.1 on macOS. Based on the [error message](https://travis-ci.org/conda-forge/staged-recipes/builds/270985179#L2328), I think the issue is r-httpuv. r-httpuv is only available for R 3.4.1 on Anaconda Cloud for linux-64:

https://anaconda.org/conda-forge/r-httpuv/files

And this is because [r-httpuv-feedstock](https://github.com/conda-forge/r-httpuv-feedstock
) failed to build on osx-64 and win-64 for R 3.4.1.

osx-64: https://travis-ci.org/conda-forge/r-httpuv-feedstock/jobs/265839903
win-64: https://ci.appveyor.com/project/conda-forge/r-httpuv-feedstock/build/1.0.2/job/h0b4na64komy1o7q

The AppVeyor error was the typical http error, so I restarted it (unclear to me how r-shinyace built for R 3.4.1 on win-64 even though it is also missing r-httpuv). The Travis [error](https://travis-ci.org/conda-forge/r-httpuv-feedstock/jobs/265839903#L252) was also due to failing to download r-httpuv from CRAN, so I restarted it, too.

Hopefully once r-httpuv for R 3.4.1 is available on Anaconda Cloud, then r-shinyace will be able to build.

**Comment by jdblischak** [comment]
AppVeyor actually ran really quickly for once, so r-httpuv for R 3.4.1 on win-64 was just uploaded to Anaconda Cloud a few minutes ago.

**Comment by souravsingh** [comment]
@jdblischak I think the PR is ready to merge once the CI tests pass.

**Comment by jdblischak** [comment]
>  I think the PR is ready to merge once the CI tests pass.

@souravsingh I'm glad the CI builds have passed! However, there's not much more I can do for this PR. I was just helping with troubleshooting.

@bgruening Could you please review and approve this PR?

**Comment by bgruening** [comment]
It seem these recipes are not made with our small helper script :(
Comments needs to be cleaned up and a few maintainers are missing. Also we need to look at the recipes I think a few of them are maybe already build. Sorry about this.

**Pull request closed without merging**
