### PR TITLE
Add c-kzg-4844: WIP awaiting `libblst` recipe

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by step21** [comment]
@MementoRC Hey, not sure if you already know this, but for some of those build questions, the matrix channel of conda-forge might be a good point to ask. (unless you already tried that ofc) Generally ppl there are very helpful and knowledgeable.

**Comment by MementoRC** [comment]
@step21 Ok, I did not know, how to get there? The whole thing should be very close now. - once it passes, I may have to separate `libblst` from this recipe, it looks like conda-build does not infer the dependencies correctly with `outputs`
That windows is from another world though! Or I am, we are anti-counterparts - Now, of course, linux tries to make a liard out of me

**Comment by MementoRC** [comment]
@xhochy Help! - `linux` build is now strangely failing with the build/host environment seemingly not installed and thus `gcc` not found for the compilation
Additionally, I do have to masquerade the package name. Apparently, the dependencies script fails to see the `libblst-0` output and fails on osx and win, but I need to run through the win recipe to finalize it

**Comment by step21** [comment]
> @step21 Ok, I did not know, how to get there? The whole thing should be very close now. - once it passes, I may have to separate `libblst` from this recipe, it looks like conda-build does not infer the dependencies correctly with `outputs` That windows is from another world though! Or I am, we are anti-counterparts - Now, of course, linux tries to make a liard out of me

https://app.element.io/#/room/#conda-forge-space:matrix.org

**Comment by MementoRC** [comment]
Transferred to: https://github.com/conda-forge/staged-recipes/pull/27490

**Pull request closed without merging**
