### PR TITLE
Add splore

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
@conda-forge/help-python ( / @conda-forge/help-nodejs ?) I think this should be ready for review. It is a simple noarch python app that also contains a few HTML pages built with angular.

Do I need to include `build.bat` if this is a `noarch` package? Presumably this is why the windows CI is failing.

**Comment by HeavyTony2** [comment]
You're sha256 isn' the right one.  For your 0.0.3 version it is 042a84ac16d724f747dd629ad261c1f8bf3a88273386ac0f1620139444c2ce70 Also, you could add your two license files in recipe directory since this is apparently why the Win_64 test fail

**Comment by SimonBoothroyd** [comment]
Thanks @AxelHenningsson, @HeavyTony2 for the comments. The `LICENSE-3RD-PARTY` is automatically generated by the Angular build process and is then copied to the correct location in `build.sh`. 

On windows the `cp` command isn't available so the copy fails and then because of this the license is not found. In principle this could be fixed I guess by adding a `build.bat`, but because this is a `noarch` package I'm not sure that would be neccessary?

> You're sha256 isn' the right one

I'm not sure why but GitHub seems to change these occasionally, in this case some time since the PR was opened... thanks for catching this! This should be fixed by c69f5a9

**Comment by HeavyTony2** [comment]
@SimonBoothroyd I found the solution for Windows.  That bld.bat (source https://github.com/AnacondaRecipes/conda-feedstock/blob/master/recipe/bld.bat) alllow the build.sh to be executed on Windows. Without that file, the building was incomplete on Windows and that's why there as an error message about having no module called splore.

Despite being "no arch" a script is still required. Your script is too complex to be integrated to the meta.yaml. So, that's why you need the pair build.sh/bld.bat 

I tested it twiced on my PC (Windows 10) and it dit work.

**Comment by SimonBoothroyd** [comment]
Thanks @HeavyTony2, but as `noarch` packages are only built on linux I don't think an extra `build.bat` file will be needed once the feedstock is created.

Could someone from @conda-forge/help-python please weigh in and review?

**Comment by HeavyTony2** [comment]
@SimonBoothroyd  I get your point, but you need it to be buildable on Windows to have the feedstock created, so that's why you need the bat and the sh.

**Comment by SimonBoothroyd** [comment]
@wolfv it seems this PR was merged but no feedstock was created - do you know what went wrong here?

**Pull request merged**
