### PR TITLE
Add PyPI package parquet-tools

### PR DESCRIPTION
**Pull request by jdblischak**
The license situation is a bit of a mess. I'd appreciate advice on how to to address these issues.

* The [`pyproject.toml` file specifies the package is MIT licensed](https://github.com/ktrueda/parquet-tools/blob/dc9df2857d627f5b5f020af972a36800fb70666d/pyproject.toml#L6), but there is no actual license file included in the repository
* It vendors the Apache licensed file [`parquet.thrift`](https://github.com/ktrueda/parquet-tools/blob/274a66a1aba6b711c52ac87629a7b5b863626787/parquet_tools/parquet.thrift)

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdblischak** [comment]
I manually added a file with the MIT license. Should I also add a file with the Apache license?

**Comment by goanpeca** [comment]
Hi @jdblischak thanks for submitting the recipe.

Could you open an issue https://github.com/ktrueda/parquet-tools and ask about the License status?

In the meantime maybe we should have it dual-licensed? Thoughts @conda-forge/staged-recipes ?

On another note, the CI is showing the following error:
`RuntimeError: Could not download https://pypi.io/packages/source/p/parquet-tools/parquet-tools-0.2.6.tar.gz` That URL indeed does not work

**Comment by isuruf** [comment]
`https://pypi.io/packages/source/p/parquet-tools/parquet-tools-0.2.6.tar.gz` -> `https://pypi.io/packages/source/p/parquet-tools/parquet_tools-0.2.6.tar.gz`

**Comment by jdblischak** [comment]
A quick update on how I handled the licensing situation. Fortunately the maintainer was receptive and helpful. I sent PR https://github.com/ktrueda/parquet-tools/pull/16 to

* add the file `LICENSE.txt` with the MIT license text (poetry automatically keeps this file during the build process, so no need for a `MANIFEST.in`)
* exclude `parquet.thrift` from the built tarball. This Apache-licensed script is for code generation. It isn't needed for building or running the package code. So I removed it to avoid any issue with the Apache license

The maintainer published these changes on PyPI, and then I updated the feedstock in https://github.com/conda-forge/parquet-tools-feedstock/pull/1

**Pull request merged**
