### PR TITLE
adding r-randomcolor

### PR DESCRIPTION
**Pull request by valscherz**

### CODE REVIEW

**Comment by apcamargo** [comment]
As I understand, you're trying to include r-v8 in this recipe, right? You should submit a separate recipe for it first. After it is merged, you can trigger this build again.

Please, use [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper) to create your R recipes. It will automatically generate a recipe that follows conda-forge standards.

**Comment by valscherz** [comment]
Hi,
Thanks for your message ! 

Indeed I first did that wrong. However I corrected for that by letting only the recipe for r-randomcolor in my final push already a week ago... And somehow the automatic testing was functioning by then.

Today, I tried to rebuild the recipe with the skeleton as requested but I cannot make it work for some reason. Lack of available r-v8 seems the reason. However, it is available on another channel (https://anaconda.org/russh/r-v8), which I tried to add as source...

In another attempt I tried to build r-v8 first to have it on your depository but I have not sucessed...

So basically I am stuck.. ;-)

**Comment by valscherz** [comment]
https://github.com/conda-forge/staged-recipes/pull/6982

**Comment by dbast** [comment]
@valscherz v8 + r-v8 were added to conda-forge... So you can update this, if you still need it.

**Comment by valscherz** [comment]
> @valscherz v8 + r-v8 were added to conda-forge... So you can update this, if you still need it.

Yep thank, I have been following the great work by @xhochy. I would still benefit from it and hope to find the time to update the receipe soon.

**Comment by valscherz** [comment]
@dbast I have it a fresh try in https://github.com/conda-forge/staged-recipes/pull/8985.

**Pull request closed without merging**
