### PR TITLE
add new recipe for PartsGenieClient v1.0.1

### PR DESCRIPTION
**Pull request by kenza12**
**PartsGenieClient** : an integrated tool for optimizing and sharing synthetic biology parts

Development repository: https://github.com/neilswainston/PartsGenieClient/

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by kenza12** [comment]
@conda-forge-admin, please ping team

**Comment by breakthewall** [comment]
Hi, I'm one of the maintainers of this recipe. Thank you!

**Comment by kenza12** [comment]
@conda-forge-admin, please ping team

**Review by beckermr — CHANGES_REQUESTED** [review]
We cannot accept pre-built binaries. The missing DSO whilelist needed means the package likely has them.

**Comment by kenza12** [comment]
@conda-forge-admin, please ping team

**Comment by kenza12** [comment]
@conda-forge-admin, please ping team

**Comment by kenza12** [comment]
@conda-forge-admin, please ping team

**Pull request merged**
