### PR TITLE
pandoc-crossref

### PR DESCRIPTION
**Pull request by kiwi0fruit**

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
related discussion: https://github.com/lierdakil/pandoc-crossref/issues/213

**Comment by kiwi0fruit** [comment]
Test pass but there is one more thing to do: windows build should be built against pandoc 2.5 not 2.4 as it's now.

**Comment by beckermr** [comment]
This appears to be repackaged binaries. I know nothing about haskell or if it is even possible to build this directly. @bgruening is this something you might know about?

I don't actually know what conda-forge should or does do in these cases. You may want to inquire about this on the gitter channel. Sorry for being out of my depth here!

**Comment by kiwi0fruit** [comment]
It's actually the same as in https://github.com/conda-forge/pandoc-feedstock

**Comment by beckermr** [comment]
Ahhh OK. Thanks for the tip!

**Pull request merged**
