### PR TITLE
add peakdetect

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by raybellwaves** [comment]
No license file in https://github.com/avhn/peakdetect

**Comment by dopplershift** [comment]
Without a license, we can't distribute this package. I see upstream is archived, but maybe you could try to find some way to reach the original creator?

Any other thoughts @ocefpaf @beckermr?

**Comment by beckermr** [comment]
No license is a no go.

**Comment by ocefpaf** [comment]
Yep. I have a similar probable with the awesome pyEddyTracker. I cannot package it b/c there is no license for one of its dependencies.

However, if you are willing to dig into this. The package is based on [1], which is licensed under a (surprinsgly) SPDX [valid license](https://spdx.org/licenses/WTFPL.html). Adn [1] was based on [2], which is public domain.

So, if you are willing to create your own peakdetect based on [1] and [2] you could re-publish it and add a proper license that is compatible with Public Domains and/or WTFPL.

[1] https://gist.github.com/sixtenbe/1178136

[2] https://gist.github.com/endolith/250860#file-peakdet-m-L17 and https://gist.github.com/endolith/250860#file-peakdetect-py-L25-L26

**Comment by ocefpaf** [comment]
PS: are you familiar with https://peakutils.readthedocs.io/? Would that help you achieve what you need? peakutils is in conda-forge.

**Comment by raybellwaves** [comment]
> PS: are you familiar with https://peakutils.readthedocs.io/? Would that help you achieve what you need? peakutils is in conda-forge.

Thanks for sharing. I eventually opted for https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_peak_local_max.html

**Pull request closed without merging**
