### PR TITLE
Add a recipe for Kuyruk

### PR DESCRIPTION
**Pull request by frol**
[Kuyruk](http://kuyruk.readthedocs.io/en/latest/) ([github](https://github.com/cenkalti/kuyruk)) is a simple and easy way of distributing tasks to run on servers.

It uses RabbitMQ as message broker and depends on `amqp` which is a pure-Python RabbitMQ client library. Compatible with Python 2.7+ and 3.4+.

All design decisions are based on simplicity. Speed is not the first priority. Kuyruk only supports RabbitMQ and does not plan to support any other backend.

Kuyruk requires no change in client code other than adding a decorator on top of a function in order to convert it to a Task. Also, sensible defaults have been set for configuration options and can be run without configuring during the development of your application.

Kuyruk is designed for long running mission critical jobs. For this reason, Kuyruk sends acknowledgement only after the task is fully processed.

### CODE REVIEW

**Comment by frol** [comment]
@jakirkham Hi! Do you happen to know why CI and linter don't check my PR?

**Comment by jakirkham** [comment]
There is some sort of DDoS attack against one of the DNSes that is impacting GitHub. This is affecting GitHub's ability to trigger CIs and in some case its availability. Should also note that this will likely result in CI backlogs for most of the day.

**Comment by jakirkham** [comment]
Hmm...was hoping that might get the linter back.

**Comment by frol** [comment]
@jakirkham Thank you!

Just for your info, I have PRed the fix to the Kuyruk upstream to make `pkg_resource` optional, so we don't need to include a useless `setuptools` run dependency: https://github.com/cenkalti/kuyruk/pull/45

**Comment by mwcraig** [comment]
@frol -- thanks, merging now that tests pass. Normally we ask that you remove comments form the recipe, but I think it makes more sense to leave them in in this case. 

Shortly after this is merged a new repo, `conda-forge/kuyruk-feedstock` will be created and the initial build/upload will happen there.

**Pull request merged**
