### PR TITLE
submitting ngboost

### PR DESCRIPTION
**Pull request by ericmjl**
cc: `@conda-forge/help-python`

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by ericmjl** [comment]
@avati would you be kind enough to leave a comment here on whether you’d like to be a maintainer? 

Same goes for @tonyduan and @dingdaisy, this package is the fruit of your labours, and I’d love to have you all involved in seeing it distributed wide!

**Comment by ericmjl** [comment]
cc: @conda-forge/python I think the build is going to work (passing on macOS and Linux are good signs for me). The only thing I am not sure how to debug is the CircleCI build. Would you be kind enough to help out please?

**Comment by ocefpaf** [comment]
> cc: @conda-forge/python I think the build is going to work (passing on macOS and Linux are good signs for me). The only thing I am not sure how to debug is the CircleCI build. Would you be kind enough to help out please?

I'm pretty sure you can ignore CircleCI here. Right @conda-forge/staged-recipes.

**Comment by avati** [comment]
Though I'm new to the conda ecosystem, I'm happy to help!

**Comment by ericmjl** [comment]
Woohoo! Thanks for merging, @chrisburr :tada: 

How long on average does it take for a package to be installable by conda-forge post-merge? (I tried doing `conda search -c conda-forge ngboost` just now but didn't see anything, and a [query on anaconda.org](https://anaconda.org/search?q=ngboost) didn't yield it either.)

**Comment by chrisburr** [comment]
Normally about an hour (assuming the package build itself doesn't take long) but there is an issue with feedstock creation that is causes recipes to be [stuck in master](https://github.com/conda-forge/staged-recipes/tree/master/recipes).

I'll reply to https://github.com/conda-forge/staged-recipes/issues/10001 with more technical details about the issue in a moment.

**Comment by ericmjl** [comment]
Ah, I see! Thanks for your work doing maintenance on this, by the way.

**Pull request merged**
