### PR TITLE
Add json-lsp

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by wolfv** [comment]
Can you make it noarch?

**Comment by martinRenou** [comment]
I tried, but it complained because it's generating a `.exe` on Windows, which apparently make it non-noarch

**Comment by wolfv** [comment]
Can you use proper entry points for that?

**Comment by wolfv** [comment]
Yeah I just checked your setup.cfg and I think you just need to add the entry points to the recipe. Conda forge knowledge base should have some info

**Comment by wolfv** [comment]
There is a second entry point in setup.cfg that might also have to be added

**Comment by martinRenou** [comment]
Even though it's not a console-script one? The second one does not generate an executable

**Comment by wolfv** [comment]
Ok sorry, I might have not read carefully enough! Then probably no :)

**Comment by martinRenou** [comment]
No worries! I didn't know you needed to add console-scripts entry points to the recipe. There always something to learn on those recipes :)

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
