### PR TITLE
keras_applications and keras_preprocessing

### LINKED ISSUE #6039: Package Keras-Applications
Would be good to package [`keras-applications`]( https://pypi.org/project/Keras-Applications/ ). This is become a required dependency of `keras` as of 2.2.0.

ref: https://github.com/keras-team/keras/blob/2.2.0/setup.py#L40

### LINKED ISSUE #6040: Package Keras-Preprocessing
Would be good to package [`keras-preprocessing`]( https://pypi.org/project/Keras-Preprocessing/ ). This is become a required dependency of `keras` as of 2.2.0.

ref: https://github.com/keras-team/keras/blob/2.2.0/setup.py#L41

### PR DESCRIPTION
**Pull request by jjhelmus**
Two new dependencies for Keras

closes #6039 
closes #6040

### CODE REVIEW

**Comment by jjhelmus** [comment]
Note that I used the underscores in the package names, `keras_applications`, rather than a hyphenated name, `keras-applications`, to match the names in the keras setup.py file.  This also matches the filenames on PyPI but not the project name.  I'm happy to change these to hyphenated packages if that seems more reasonable.

**Comment by jakirkham** [comment]
Thanks @jjhelmus :)

IDK Python’s a mess with `_`/`-` in package names. Happy to do whatever is reasonable here.

**Comment by CurtLH** [comment]
Both Keras-Preprocessing (PR #6049) and Keras-Applications (PR #6050 ) have already been added.  If you would like to become a maintainer of either of the existing feedstocks, I'm happy to add you. 

https://github.com/conda-forge/keras-preprocessing-feedstock
https://github.com/conda-forge/keras-applications-feedstock

**Comment by jjhelmus** [comment]
@CurtLH Thanks for pointing out that these packages are already in conda-forge and for packaging them!  I'll close this PR and add myself to the existing feedstocks.

**Pull request closed without merging**
