### PR TITLE
Adds plenoptic and pyrtools

### PR DESCRIPTION
**Pull request by billbrod**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

plenoptic depends on pyrtools, and I'm the maintainer of both. They are used in visual neuroscience for building and understanding computational models of neurons and/or perception.

### CODE REVIEW

**Comment by billbrod** [comment]
@conda-forge-admin, please ping conda-forge/help-python

I don't understand the lint error I'm getting for `pyrtools` -- should I remove the `python >= 3.7` version constraint under `requirements:host` and `requirements:run` (I'm assuming that's why the error shows up twice). But my package does require a minimum python version of 3.7 -- is there another way to indicate thta?

**Comment by billbrod** [comment]
The Windows build is failing and I thought it was because I require pytorch, which is hosted on the `pytorch` channel. Looking at [this other PR](https://github.com/conda-forge/staged-recipes/pull/24864), it looks like it's okay that the Windows build fails and that I shouldn't specify the pytorch channel here? (And then my installation instructions should tell people to try adding that channel if the installation fails?)

**Comment by BastianZim** [comment]
Yes, you can just ignore the failure.
You can inform your users but conda/mamba will tell someone when installing, that the package could not be found on the specific channel. If they then go to the pytorch website, they will find the necessary instructions.
Just as a note: we don't recommend installing from multiple channels because there can be differences in compilation etc that can cause unexpected issues.

**Comment by billbrod** [comment]
Okay, that makes sense. What are my next steps then? Is there some way to fix the failing OSX build or should I ignore that as well?

And if you don't recommend installing from multiple channels, what do you recommend doing for pytorch?

**Comment by billbrod** [comment]
@conda-forge/staged-recipes I believe this is ready to be merged: I have fixed all the linters issues and my OSX and Linux builds are succeeding. The Windows build is still failing, because it requires https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32, so will not succeed for now.

Let me know if there are any other changes I need to make!

**Comment by billbrod** [comment]
@conda-forge/help-python is the proper team to notify, I believe.

**Review by xhochy — COMMENTED** [review]
Can you please separate these packages? As only one is noarch I'm hesitant to merge with failing Windows CI.

**Comment by billbrod** [comment]
Okay. Since plenoptic (which also relies on pytorch and thus has the failing windows build) depends on pyrtools, is the way to do this to remove plenoptic from this PR, merge pyrtools, and then open a new PR with plenoptic?

**Comment by xhochy** [comment]
Yes!

**Comment by billbrod** [comment]
Alright, I went ahead and removed plenoptic!

**Review by xhochy — APPROVED** [review]

**Pull request merged**
