### PR TITLE
add ghc haskell compiler

### PR DESCRIPTION
**Pull request by notestaff**

### CODE REVIEW

**Comment by isuruf** [comment]
This relies on `libgmp.so.3` being available in the system. It is true for the docker image we have, but it's not present in newer linux distributions

**Comment by isuruf** [comment]
I have a WIP branch here, https://github.com/isuruf/staged-recipes/tree/notestaff-is-new-add-ghc, but that'll timeout in CI

**Comment by scopatz** [comment]
@isuruf - so is there a decision on this?

**Comment by notestaff** [comment]
Just to note, I don't know Haskell, so someone who does should be co-maintainer of any feedstock.

**Pull request closed without merging**
