### PR TITLE
r-tmap

### PR DESCRIPTION
**Pull request by agcopenhaver**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0

### CODE REVIEW

**Comment by agcopenhaver** [comment]
waiting for lwgeom then tmaptools to get accepted before this will work

**Comment by agcopenhaver** [comment]
@conda-forge/r this one isn't building for windows, but that appears to be fairly common for noarch packages, right?

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
Oh, staged-recipes, silly me. Yes, failing on windows is expected.

**Comment by dpryan79** [comment]
I wonder if the folder needs to be renamed to r-tmap or if feedstock creation scripts get the name from the package name instead.

**Comment by agcopenhaver** [comment]
@dpryan79 I believe it comes from the package name

**Comment by dbast** [comment]
The usual noarch R win failure.

**Pull request merged**
