### PR TITLE
Add python-prctl

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/staged-recipes this is ready for review, but requires cos7 build images. I don't know how to do that on the staged recipes PR.

Is it OK if i touch this up afterward?

**Comment by ocefpaf** [comment]
> Is it OK if i touch this up afterward?

You can add a conda-forge.yml to test it here. See this commit as an example: https://github.com/conda-forge/staged-recipes/commit/678ec5822145876d9e0eb674faec82c9e5add678

**Comment by hmaarrfk** [comment]
hmmm i guess i thought i did, but didn't check the logs to verify the error.

**Comment by hmaarrfk** [comment]
@ocefpaf it seems that testing it on staged recipes isn't working at the moment. the caio recipe failed with the same error:

image

https://github.com/conda-forge/staged-recipes/pull/16869

**Comment by ocefpaf** [comment]
> @ocefpaf it seems that testing it on staged recipes isn't working at the moment. the caio recipe failed with the same error:

`linux_64_centos7` is passing but I did not check the logs. Let me know if you want to merge this and fix in the feedstock or work it out here.

**Comment by hmaarrfk** [comment]
oh. cool. i didn't realize it was a different build.

should I add a skip? cos6 won't work with this package.

**Comment by ocefpaf** [comment]
> should I add a skip? cos6 won't work with this package.

Probably no need. It will only render for cos7 in the feedstock. Merging...

**Pull request merged**
