### PR TITLE
Added recipe for jupyterthemes

### PR DESCRIPTION
**Pull request by pmlandwehr**
`jupyterthemes` is a package that helps customize jupyter notebooks.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Added a patch that I think fixes the string issue; if successful can submit to main repo; if unsuccessful can remove.

**Comment by pmlandwehr** [comment]
Hey @conda-forge/idna / @conda-forge/staged-recipes any idea what's up here? My build of this new package appears to be failing for windows b/c the CI can't find `idna 2.6` for `py35` for the inital setup, even though it appears to be on conda-forge. (This package doesn't require `idna` and should be platform agnostic.)

**Comment by jakirkham** [comment]
@conda-forge-admin, please lint.

**Comment by jakirkham** [comment]
That's an old issue, @pmlandwehr. It should now be resolved after CI runs again.

**Comment by pmlandwehr** [comment]
Merge this? All green now.

**Pull request merged**
