### PR TITLE
add r-trackdown

### PR DESCRIPTION
**Pull request by brendanf**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by brendanf** [comment]
@conda-forge/help-r Ready to merge

**Comment by cbrueffer** [comment]
This recipe could use some cleanup, particularly of the comments; easiest to regenerate it using `https://github.com/bgruening/conda_r_skeleton_helper`.

**Comment by brendanf** [comment]
@cbrueffer I initially tried to generate it from `conda_r_skeleton_helper`, as I always have in the past for R packages, but the newest version fails with error `"GPL-3" license not valid. See https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions"`.

 I originally thought this was simply an error in translating the license to SPDX (because it's not clear from parsing the package description whether this is `GPL-3.0-only` or `GPL-3.0-or-later`).  However, I now see that neither variant of GPL-3.0 is included at all in the list of available licenses.  Is [the list given in the link](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions) intended to be comprehensive?  Is GPL-3 not acceptable (anymore?) for Conda-Forge packages?  If so, there are a lot of packages that will need to be removed.

If the list is intended to be illustrative, then other acceptable alternatives will need to be added to `conda_r_skeleton_helper`.   Even if that is done, then there still needs to be some way to tell `conda_r_skeleton_helper` the correct SPDX license in cases where the license given in DESCRIPTION is not directly parseable to SPDX.

If the latter, then I can file an issue at `conda_r_skeleton_helper`.

**Comment by cbrueffer** [comment]
Yeah, the license code in the helper is broken, I've just commented it out. The new version looks good, thanks.

**Pull request merged**
