### PR TITLE
Add dotnet core

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

---- 

- [x] Add activate scripts for cmd
- [x] Enable Linux/OSX
- [x] Add activate scripts for bash
- [x] Fix path for `[not win]`

### CODE REVIEW

**Comment by dhirschfeld** [comment]
This PR is a continuation/extension of #12857.

Currently it works perfectly on Windows and with some minimal changes it *should* also work for OSX and Linux.

This recipe uses the SDK source, which packages the SDK and all the runtimes, and splits them all into individual packages so e.g. someone who just wants to run a pre-built app in a container can only install the `dotnet-runtime` package and doesn't need to pay the hundreds-of-MB cost of installing the full SDK.

**Comment by ZimmerA** [comment]
Hi, nice to see you're working on this too. Is there a reason you're opening a new PR instead of working on this together?

**Comment by dhirschfeld** [comment]
:wave:

I've got the Windows build working and you've got the Linux build working so we've effectively been tackling different sides of the same problem. Put them together and we've got a working `dotnet` runtime across all platforms!

I'm trying to incorporate your linux config to also get linux/osx support with my PR. The main important difference from your PR is that I'm breaking the monolithic SDK into its constituent parts which allows you to independently install just the runtime for smaller, faster containers. The scaffolding for doing so is in-place and works on Windows, it's just a matter getting it working on Linux as well and since I'm (mostly) a Windows user I've just cribbed your config for that.

Working independently just gives more freedom to move quickly and try things out without stepping on anyone's toes. If you get a working linux config I'll happily make use of it! For my use however, separating the runtime from the SDK is important.

**Comment by dhirschfeld** [comment]
`icu` is required:
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
```

**Comment by dhirschfeld** [comment]
Tests fail on osx
```
+ dotnet --version
/Users/runner/miniforge3/conda-bld/dotnet_1603031312056/test_tmp/run_test.sh: line 7: dotnet: command not found
```

Will disable for now. If someone with a mac wants to enable osx they can do so on the actual feedstock.

**Comment by dhirschfeld** [comment]
Removed the `WIP` since linux & win are both working.

This currently relies on putting all missing deps in `missing_dso_whitelist` but, from #12857 it seems it may be possible to remove a number of those by specifying host/run deps. I was not able to get that to work, but if that's desirable it can perhaps be iterated on in the feedstock...

**Comment by isuruf** [comment]
> I was not able to get that to work, but if that's desirable it can perhaps be iterated on in the feedstock...

It's a requirement actually that we rely on conda packages and not on system libraries except for a few libraries like glibc.

**Comment by dhirschfeld** [comment]
ping @conda-forge/core, also @mariusvniekerk (for the `cos7` work-around).

I'd like to have this merged to make the .NET Core language available from `conda-forge`. 

***Note:*** This *does not* compile the language from source! This is merely a re-packaging of the official binaries. This does go against official `conda-forge` recommendations however it wouldn't be unique in doing so and *requiring* it to be built from source will simply mean it's not available on `conda-forge` at all since the intersection of people able to compile it and interested in using .NET via `conda` is pretty close to nil.

Perfect is the enemy of shipped, and so, in this case I'd like the binary repackaging restriction waived. I think the benefits of having it available from `conda-forge` outweigh the potential problems this can cause. If there are problems in practice it may motivate a user to submit a PR to compile it from source.

**Comment by beckermr** [comment]
We'll need to discuss this at a core meeting I expect. I agree with @isuruf but am not knowledgeable enough to know how hard this build actually is.

**Comment by isuruf** [comment]
It's not that I don't like binary repackaging (it's fine as a last resort). Issue here is that, the dependencies of the binary package is not using conda packages. Looks like https://github.com/conda-forge/staged-recipes/pull/12857 adds the correct dependencies.

**Comment by dhirschfeld** [comment]
I'm pretty certain that #12857 is also just a binary repackaging so, IIUC it doesn't use any of the dependencies specified?

i.e. my understanding is that it will use whatever it was compiled with irrespective of whether or not `conda` versions happen to be installed in the same environment - is the that not correct?

**Comment by isuruf** [comment]
> I'm pretty certain that #12857 is also just a binary repackaging so

Yes, it is

> IIUC it doesn't use any of the dependencies specified?

It adds dependencies like `lttng-ust`.

> i.e. my understanding is that it will use whatever it was compiled with irrespective of whether or not conda versions happen to be installed in the same environment - is the that not correct?

Nope, since conda-build sets up rpath correctly, if they are in the same environment, they'll be picked up.

**Comment by dhirschfeld** [comment]
Thanks for the explanation @isuruf! It shouldn't be too hard to add the deps from #12857. I just wasn't sure if it was worthwhile so I didn't want to invest too much effort up front...

**Comment by ZimmerA** [comment]
> Thanks for the explanation @isuruf! It shouldn't be too hard to add the deps from #12857. I just wasn't sure if it was worthwhile so I didn't want to invest too much effort up front...

You should be able to just copy the requirements out of my recipe, delete the missing_dso_whitelist and we're good to go.
Also, while you're at it, you can add me to the maintainers list if you want.

**Comment by dhirschfeld** [comment]
Obviously I'm still missing something 🤔 

<details>

```
ERROR (dotnet-runtime,lib/dotnet/host/fxr/3.1.9/libhostfxr.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/host/fxr/3.1.9/libhostfxr.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/host/fxr/3.1.9/libhostfxr.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/host/fxr/3.1.9/libhostfxr.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/host/fxr/3.1.9/libhostfxr.so): /lib64/ld-linux-x86-64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/dotnet): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/dotnet): /lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/dotnet): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/dotnet): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/dotnet): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/dotnet): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/dotnet): /lib64/ld-linux-x86-64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.IO.Compression.Native.so): /lib64/libz.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.IO.Compression.Native.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Security.Cryptography.Native.OpenSsl.so): /lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Security.Cryptography.Native.OpenSsl.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Net.Http.Native.so): /lib64/libcurl.so.4 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Net.Http.Native.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/librt.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordaccore.so): /lib64/ld-linux-x86-64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordbi.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordbi.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordbi.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libmscordbi.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/librt.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libclrjit.so): /lib64/ld-linux-x86-64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/createdump): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/createdump): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/createdump): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/createdump): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Net.Security.Native.so): /lib64/libgssapi_krb5.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Net.Security.Native.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/librt.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libdbgshim.so): /lib64/ld-linux-x86-64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Globalization.Native.so): /lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Globalization.Native.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Native.so): /lib64/librt.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Native.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/librt.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclr.so): /lib64/ld-linux-x86-64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclrtraceptprovider.so): $RPATH/liblttng-ust.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclrtraceptprovider.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclrtraceptprovider.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclrtraceptprovider.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libcoreclrtraceptprovider.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libhostpolicy.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libhostpolicy.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libhostpolicy.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libhostpolicy.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
ERROR (dotnet-runtime,lib/dotnet/shared/Microsoft.NETCore.App/3.1.9/libhostpolicy.so): /lib64/ld-linux-x86-64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']
```
</details>

**Comment by ZimmerA** [comment]
> Obviously I'm still missing something 🤔

I'm a bit confused aswell...

**Comment by isuruf** [comment]
You need them in host as well.

**Comment by isuruf** [comment]
I meant host in each individual output.

**Comment by ZimmerA** [comment]
>  Needed DSO lib/libstdc++

Do you have to add the build requirements for every output aswell?

**Comment by ZimmerA** [comment]
Finally 🥳 ! What a wild ride 😄
One thing i noticed were these warnings in the dotnet sdk build, should be easy to fix though:

> WARNING (dotnet-sdk): run-exports library package conda-forge::zlib-1.2.11-h516909a_1010 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (dotnet-sdk): dso library package conda-forge::lttng-ust-2.10-hfb453c0_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (dotnet-sdk): run-exports library package conda-forge::libcurl-7.71.1-hcdd3856_8 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (dotnet-sdk): run-exports library package conda-forge::krb5-1.17.1-hfafb76e_3 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)

**Comment by dhirschfeld** [comment]
> Finally 🥳 ! What a wild ride 😄

Yep - got there thanks to you figuring out the required deps on linux! I thought that the outputs would inherit common config from the top but that seems not to be the case.

**Comment by ZimmerA** [comment]
I suggest we fix the warnings on the feedstock so i can test it on my local machine instead of you having to wait for the CI a couple more times.

**Comment by dhirschfeld** [comment]
Now the CI is passing I'll revert the `cos7` changes and skip the build

**Comment by dhirschfeld** [comment]
Thanks for your help @isuruf & @ZimmerA! The correct  config from  #12857 has been ported over so we've now got a working `dotnet` on both Windows and Linux with no missing dso hacks! :tada:

I think this is ready to merge if @conda-forge/core are happy with it?

**Comment by wolfv** [comment]
Looks good to me! Do you want to squash commits a bit? Do we do that on staged recipes?

**Comment by dhirschfeld** [comment]
I *think* commits are squashed automatically but I can do so...

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks all!

**Pull request merged**
