### PR TITLE
perl-common-sense recipe ported from bioconda

### PR DESCRIPTION
**Pull request by vinjana**
Required for perl-json-create (indirectly).

### CODE REVIEW

**Comment by vinjana** [comment]
Don't get it. Travis and CircleCI succeeded. But on Appveyor the output says in the test, that version 3.73 is returned instead of the expected version 3.74. The correct tar-ball was downloaded and when I check the tar-ball on my system it only 3.74 in the `$VERSION` field in `sense.pm`. 

So what is going on on Appveyer? Is there another Common::Sense version preinstalled and earlier in the search path?

I need some assistance here by your CI experts!

**Comment by isuruf** [comment]
You only have a `build.sh`, there's no script here for building in windows. You need a `bld.bat` file and the commands there

**Comment by vinjana** [comment]
Hm, I cannot write a bld.bat in a reasonable time. Is it possible to skip the windows builds for my PRs? Maybe s.b. else is fluent enough to update the builds for Windows?

**Comment by vinjana** [comment]
Do you think I can leave out the Windows builds for now and someone more expert (and frankly: more interested) could take over? I'd do that then for this and all related PRs.

**Pull request closed without merging**
