### PR TITLE
add conda-forge-pinning

### PR DESCRIPTION
**Pull request by croth1**
@jakirkham, this splits the pinnings into a new `conda-forge-pinning` package.

It replaces `from conda_smithy import pinning` by `from cf_pinning import pinnings`. What do you think?

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems like a good idea. Could let us use it for linting, pinning, and maybe docs too while avoiding redundancy? What does @conda-forge/core think of this idea?

**Comment by scopatz** [comment]
I am +1 for this.  The pinning procedure right now is a bit add hoc and this helps formalize it.

**Comment by croth1** [comment]
@conda-forge/core, since there's no more comments/discussion here, shall we go ahead and merge this?

**Comment by jakirkham** [comment]
Couple more points that probably deserve discussion.

1. Do we want the pinning in a separate repo as shown or as part of this recipe (like `conda-forge-build-setup` or the `toolchain`)?
2. Also what does the update process look like?
3. If a separate repo, how do we plan to transfer that to the org?
4. Finally do we want this to depend on Python or do we just want a bare JSON file?
5. Are we happy with the current pinning format?

Opinions: Regarding 1/2 there is some value in having everything self contained to make the update process simpler. Though if we like the utility scripts that may make it less clear on how it is built/works hence the question in 4. Admittedly there could be duplication of effort between things that want to use the pinnings, but am hoping there is not too much work. Regarding 3 this is sort of something we need to do. It is doable, but we do need to make sure we are all on the same page about this. Considering 4 and 5 IMHO a simple JSON file would be better and maybe the format should change. In particular, I don't think there is a need to include the package name in the version pinning. It is easy enough to combine them ourselves and makes the meaning of the file much clearer. As another consideration, adding Python results in an increase in build time if we make Python a dependency. That said, we should discuss this before we start having lots of things depend on the current format.

**Comment by croth1** [comment]
> 1. Do we want the pinning in a separate repo as shown or as part of this recipe (like conda-forge-build-setup or the toolchain)?

No strong opinion on that.

> 2. Also what does the update process look like?

Updating pinnings is usually not very time critical. We could push a new version directly when we change the pinnings. We could as well update in a fixed interval. Again no strong opinion on that.

> 3. If a separate repo, how do we plan to transfer that to the org?

I can give you admin rights so you can transfer it. Creating a new repository in conda-forge and taking the commits is also fine.

> 4. Finally do we want this to depend on Python or do we just want a bare JSON file?

IMO, we should definitely depend on python. If the pinnings are not readily importable, we have to copy the parsing logic in all repositories that use the pinnings. I want to avoid that.

> 5. Are we happy with the current pinning format?

Currently we support pinning of build and run dependencies, potentially different versions (I saw that this was requested in some issue). Are there any other features that we definitely want?

> Considering 4 and 5 IMHO a simple JSON file would be better

I don't see how this would help. If someone needs the json file, they can still get the versioned tarball and find it there. 

> In particular, I don't think there is a need to include the package name in the version pinning

This is the old format isn't it, I changed it a little bit.

> As another consideration, adding Python results in an increase in build time if we make Python a dependency.

Is this critical? I guess we will build this package at most a handful times per month and all packages that are currently candidates to use it (smithy, linter, conda-forge.io) already have a python dependency.

**Comment by croth1** [comment]
@conda-forge/core any more comments/opinions on this? Is there general interest in persuing this idea?

**Comment by croth1** [comment]
@jakirkham, any update?

**Comment by jakirkham** [comment]
Sorry I have been really busy. Is it ok if we keep this open?

**Comment by croth1** [comment]
@jakirkham, sure - assumed that we go for an alternative route.

**Comment by croth1** [comment]
@jakirkham, hmhm, I think we should eventually decide if we take this route or abandon it.

**Comment by croth1** [comment]
@jakirkham do you think we can merge that? would make it possible to move on and check the smithy pull request.

**Comment by jakirkham** [comment]
Considering as all the pinning parsing logic is in `conda-smithy`, could we just include the pinning file in the recipe directory itself? This would make it very simple to update a pinning and make a release. What do you think?

**Comment by croth1** [comment]
> could we just include the pinning file in the recipe directory itself?

I am sorry, I don't seem to understand. What recipe directory exactly? You mean distributing it to the feedstocks via rerender? Or do you mean including it in smithy somehow?

**Comment by jakirkham** [comment]
I mean in the recipe in this PR.

**Comment by croth1** [comment]
I guess that would work indeed.

**Comment by croth1** [comment]
@jakirkham, thought briefly about it: how would you place/find the file in the environment? I could install it somewhere in `$PREFIX/share/`, but what is a good way to find the file path again in my python package?

**Comment by jakirkham** [comment]
Installing it in `$PREFIX/share/` is a good idea. As far as finding it, `sys.prefix` is the same as `$PREFIX`. So doing `os.path.join(sys.prefix, "share")` should give that directory.

**Comment by mwcraig** [comment]
Seems like this should be checked against the changes to conda build planned for `3.0`? IIRC it provides for a clean method of pinning and a list of standard places it will look for pinning files.

**Comment by jakirkham** [comment]
Good point. Though my understanding was it looked for pinnings in the recipe directory itself. Not a global location. Or am I mistaken?

**Comment by mwcraig** [comment]
I don't recall...I did a quick review of the doc PR a few weeks ago and that detail has slipped my mind. I believe, though, that it provided for both a global and per-recipe pinning.

**Comment by croth1** [comment]
I don't see any new pinning support, apart from pinning in condarc, which should not affect this. If there are no concerns, I would like to push this further ahead. This is being on hiatus for months now. I would really like to get this off my back.

**Comment by croth1** [comment]
xref: https://github.com/conda/conda-docs/pull/414/ don't think this affects us either.

**Comment by mwcraig** [comment]
I think [this bit](https://github.com/conda/conda-docs/pull/414/files#diff-d1a5dbb2f223de4935d93990676c7074R757) is relevant, but in any event is fairly far off, since I assume the migration to conda build 3, once it is released, will be done slowly in conda-forge.

@ocefpaf -- you gave a thumbs up to https://github.com/conda-forge/conda-smithy/pull/482, are you good with this too?

**Comment by ocefpaf** [comment]
> @ocefpaf -- you gave a thumbs up to conda-forge/conda-smithy#482, are you good with this too?

@mwcraig I don't have time to evaluate this PR this week but I'd rather if pinning was a `conda-smithy` feature instead of an external module.

Does that makes sense to you @croth1?

**Comment by msarahan** [comment]
@croth1 @jakirkham sorry if the docs are not clear.  There is a hierarchical approach to pinning configuration files in conda-build 3.  Here is the description of the search path: https://github.com/conda/conda-docs/pull/414/files#diff-d1a5dbb2f223de4935d93990676c7074R287

If/when you phase in conda-build 3, it can probably replace conda-forge-pinning.  I don't do linting, though - so maybe that would be a good thing to port to conda-verify eventually?

**Comment by croth1** [comment]
@msarahan, thanks for the link. This could indeed make my effort here redundant. I currently don't have the time to review the implications thoroughly though.
@ocefpaf, @jakirkham are there already plans when this will be adopted by conda-forge? Do you think it makes sense to continue here? I'd be fine with closing this.

**Comment by jakirkham** [comment]
Even if this might be redundant eventually, I'd still be ok with merging this. Combined with your other fixes, we should be able to get the pinning maintenance bot working again. Configuring all of these same things to work with `conda-build` 3 will take a while.

**Comment by croth1** [comment]
either way is fine for me. If you feel we should continue here, please give it a final review 👍

**Comment by jakirkham** [comment]
Have added it to the meeting agenda. Would be great if you could come @croth1 so that we can discuss and resolve this. There is a [poll]( https://groups.google.com/forum/#!topic/conda-forge/1zLBSOPRDhk ) open to determine the date and time. Please let us know your availability if you can.

**Comment by croth1** [comment]
@jakirkham, thanks! I'm super busy at the moment, and probably will not make it in the next few weeks, though.

**Comment by msarahan** [comment]
This seems fine to me.  To make the transition to conda-build 3 easier, you may want to consider changing from JSON to a YAML file.  Conda-build 3 allows arbitrary keys, each of which have list values.  There are some special keys that are not lists, but anything outside of those has to be a list.  Your pinnings here would be single-item lists.  Conda-build allows lists and will loop over the cartesian product of all lists.

It doesn't matter where the file gets installed - share is fine.  Conda-build has an argument to direct it to wherever you want.

Aside from switching the file to YAML (which is by no means mandatory - it just might make migration to conda-build 3 easier in the future), I recommend merging this PR.

**Comment by gqmelo** [comment]
As discussed on ```https://github.com/conda-forge/conda-forge.github.io/pull/245#issuecomment-307001880``` separate pinnings for build and run dependencies are necessary. Defining equal pinnings for both build and run can lead to problems cited in https://github.com/conda-forge/conda-forge.github.io/pull/245

**Pull request closed without merging**
