### PR TITLE
WIP: Add remote when we have no token?

### PR DESCRIPTION
**Pull request by jakirkham**
I'm a bit confused by one line in `create_feedstocks.py` as it assumes the `GH_TOKEN` is defined. However, elsewhere we don't make this assumption. I don't know the right way to handle it (or perhaps if it needs to be handled at all). This PR tries to use a fallback of not using a token. Though I suppose one might argue it should raise an error or do something else. I'm not sure when the `GH_TOKEN` would be undefined; so, am a bit mystified as to how to address this, but I did want to raise the issue.

cc @pelson

### CODE REVIEW

**Comment by pelson** [comment]
The only place this script is called is in https://github.com/conda-forge/staged-recipes/blob/master/.CI/create_feedstocks#L15, which guards against not having a GH_TOKEN.

Have I missed an issue crop up on this?

**Comment by jakirkham** [comment]
Well, I'm a bit confused honestly. I don't really understand the history of this script, which would really answer whether this is needed or not.

It seems like there are lots of checks for tokens being present in this script. So if we are checking in all those other places, we should be checking here too. Perhaps all the checks should be removed if they are not needed.

Is this intended to be run locally in some cases (e.g. debugging)? If so, we probably need the other checks and this one too.

**Comment by pelson** [comment]
So I'm reluctant to merge this, not because it would break anything, but because I fear it would make it *harder* to understand what is going on in the script. I 100% accept that it is an under commented and poorly structured script and it could do with some love if anybody other than me is going to be able to look at this and maintain it.

The guards that are in here relate to a number of situations:

 * merged PR on master (has GH_TOKEN)
 * merged PR on another branch (has GH_TOKEN)
 * proposed PR  (has no GH_TOKEN)

There is a sneaky `continue` at https://github.com/jakirkham/staged-recipes/blob/274fb3c2aa569256bad620f0f135e617b90d7878/.CI/create_feedstocks.py#L123 which breaks the loop if we are not on master and have GH_TOKEN, and so even if somebody ran this manually, they wouldn't get to the GH_TOKEN usage within the remote.

Sorry if this doesn't make an awful lot of sense - I'd definitely be up for spending a bit of time in a hangout if you wanted to talk through it.

Hope it works for you, but this is a wont-merge.

Cheers!

**Comment by jakirkham** [comment]
Honestly this bordered on a strawman proposal for me. I just wanted to make you were aware of this block. Perhaps of my general ignorance of how much of this works too. 😆

**Pull request closed without merging**
