### PR TITLE
Add r-grr.

### PR DESCRIPTION
**Pull request by roryk**
Alternative Implementations of Base R Functions. Alternative implementations of
some base R functions, including sort, order, and match. Functions are
simplified but can be faster or have other advantages.

There are some packages which depend on this, so it is useful to have as a feedstock.

### CODE REVIEW

**Comment by bgruening** [comment]
@roryk this will help you a little bit: https://github.com/bgruening/conda_r_skeleton_helper
Can you recreate it with this script?

**Comment by roryk** [comment]
Thanks @bgruening, you are magic. I see, I had the `bld.bat` named wrong, so it wasn't getting built on Windows.

**Comment by bgruening** [comment]
Super! Thanks @roryk!

**Comment by roryk** [comment]
Thanks a ton for all of your awesome work.

**Pull request merged**
