### PR TITLE
libxml2 (pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
Builds off of this PR ( https://github.com/conda-forge/staged-recipes/pull/266 ) and includes a minor fix.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I just merged that and saw this one. What is the difference?

**Comment by jakirkham** [comment]
We forgot to drop the Python import. It was causing the tests to fail.

**Comment by ocefpaf** [comment]
I fixed that already.

**Comment by jakirkham** [comment]
Really? I must have missed that go in then.

**Comment by ocefpaf** [comment]
I need another Yoda meme :stuck_out_tongue_winking_eye:

**Comment by jakirkham** [comment]
Weren't you going to bed? :smirk:

**Comment by ocefpaf** [comment]
Can't sleep util I make some progress with netcdf :sob:

**Comment by jakirkham** [comment]
Ouch! Yeah, I have to go play with Caffe some more.

**Pull request merged**
