### PR TITLE
Add new package: cgat-core

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
It seems that it depends of ``ruffus``, you will have to package that first
https://pypi.org/project/ruffus/

**Comment by sebastian-luna-valero** [comment]
Thanks, discussing that in https://github.com/bioconda/bioconda-recipes/pull/10969

**Comment by marcelotrevisani** [comment]
cc: @bgruening

**Comment by sebastian-luna-valero** [comment]
Closing this in favour of https://github.com/bioconda/bioconda-recipes/pull/10969

**Pull request closed without merging**
