### PR TITLE
r-skat

### PR DESCRIPTION
**Pull request by bsennblad**
I propose adding a conda recipe for the R-package SKAT. Recipe is created using conda skeleton cran.

@bgruening  For my previously committed recipes, Björn Grüning offered/requested to be added as maintainer. Does this offer/request still stands -- should I add Björn as maintainer for this recipe, as well. I'm not up-to-date on the the standard practice for this.

### CODE REVIEW

**Comment by bsennblad** [comment]
recipe fails to build on windos (continuous-integration/appveyor/pr  is win build right?).

sampled a number of existing conda-forge r-recipes and all of these seem to have 

skip: true  # [win32]

in their meta.yaml. Is this standard practice? It would solve my build problems above. 
I am not working on windows myself, so I'll be extremely grateful for any huidance.

Thanks,

Bengt

**Comment by jdblischak** [comment]
@bsennblad Thanks for the recipe! The easiest way to get an R recipe approved and merged is to use the [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper). It adds extra maintainers (everyone gets busy, so having more maintainers means its more likely any issue can get solved quicker), handles the license properly for GPL'd software, and formats the recipe so that is passes the linter.

Looking at your recipe, I don't see any obvious reason why this shouldn't build on Windows.

**Comment by bsennblad** [comment]
@jdblischak Thanks for the input. I had a very quick look at the conda_r_skeleton_helper run.sh script and saw that it indeed seems to skip win builds. I will definitely use it in the future.

Recipe seems to build now (with win skipped). I'll add the extra maintainers from conda_r_skeleton_helper, and then maybe it can be merged?

(BTW, I got the impression from the appveyor logs that the error messages for the win build was not directly recipe-related.)

**Comment by jdblischak** [comment]
> Thanks for the input. I had a very quick look at the conda_r_skeleton_helper run.sh script and saw that it indeed seems to skip win builds. I will definitely use it in the future.

It doesn't skip all win builds. It only skips 32-bit Windows builds (`win32`).

https://github.com/bgruening/conda_r_skeleton_helper/blob/master/run.sh#L17
https://support.microsoft.com/en-us/help/15056/windows-7-32-64-bit-faq

> Recipe seems to build now (with win skipped). I'll add the extra maintainers from conda_r_skeleton_helper, and then maybe it can be merged?

It would really help us out if you used the helper script (and removed the license file with `git rm recipes/r-skat/LICENSE.txt`). There are 500+ R packages on conda-forge, and the more consistent the recipes, the easier for us it is to maintain. Also, you are skipping the Windows build for no reason.

> (BTW, I got the impression from the appveyor logs that the error messages for the win build was not directly recipe-related.)

Your intuition is correct. In your original recipe, the first 3 failed because they were building for 32-bit Windows. Builds 4 and 6 passed because they were built with 64-bit Windows. The 5th failed spuriously due to a connection timeout, and would pass if restarted.

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18973
Example of 32-bit build: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18973/job/w51jh6k0k9pukf9c#L121
Example of HTTP error: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18973/job/bw927coaexb2ow2g#L733

**Comment by bsennblad** [comment]
@jdblischak Thanks for your help! All files are now generated with conda_r_skeleton_helper and the license file is removed (when adding my previous recipe, r-bookdown , I was requested to add a LICENSE-file, so I thought I should be pro-active this time:). I missed that it just said skip win32 -- careless reading -- definitely my bad; sorry. It would be great if everything builds now and can be merged, as I need the package for a collaborative project.

Some feedback on the conda_r_skeleton_helper run.sh:
I work on macosx and apparently macosx sed (based on FreeBSD I think) is different from gnu sed, so all sed commands in the script failed with either these error messages:
-sed: -i may not be used with stdin
-sed: -e: No such file or directory
I solved this by creating a dedicated  conda_r_skeleton_helper conda environment containing the conda-forge sed (the bioconda  4.2.3.dev0 seems to be broken on macosx, complains on missing libintl). 
Also, I had to install gedit from MacPorts as there were no gedit conda package, which felt a bit unnecessary as there were a lot of dependencies also installed. ONe solution could be to provide a gedit conda package (or why not just add a comment in the run.ch-script and the README.rmd files that one can change gedit to ones favorite editor).
You could perhaps provide a small pre-made conda environment (as a requirement.txt file and perhaps a convenience script with the necessary conda commands for creating the environment) in the conda_r_skeleton_helper repository. I use this approach when providing bioinfo tools in my collaborative projects.
I hope you don't take this as complaints, I meant it as feedback for the improvement of this really handy tool.

Best wishes,

Bengt

**Comment by jdblischak** [comment]
> Thanks for your help! All files are now generated with conda_r_skeleton_helper

@bsennblad Awesome! I just approved the recipe.

>  and the license file is removed (when adding my previous recipe, r-bookdown , I was requested to add a LICENSE-file, so I thought I should be pro-active this time:).

That was the right idea. GPL'd software need to have the license file included with the distributed binary (i.e. the conda package created by the recipe). We have automated this process with the helper script. Instead of including a LICENSE file manually, the recipe copies the GPL license that is shipped with `r-base`.

> I missed that it just said skip win32 -- careless reading -- definitely my bad; sorry.

No worries! conda-forge has a lot of moving parts.

> It would be great if everything builds now and can be merged, as I need the package for a collaborative project.

@bgruening This recipe is ready to merge.

> Some feedback on the conda_r_skeleton_helper run.sh:
> I work on macosx and apparently macosx sed (based on FreeBSD I think) is different from gnu sed, so all sed commands in the script failed with either these error messages:
-sed: -i may not be used with stdin
-sed: -e: No such file or directory

Yes, I agree this is inconvenient. I had looked into this briefly previously but couldn't see an obvious way to make a single command that would work with both versions of `sed`. My solution for when I am working on macOS is to login to my university's HPC cluster.

> I solved this by creating a dedicated conda_r_skeleton_helper conda environment containing the conda-forge sed (the bioconda 4.2.3.dev0 seems to be broken on macosx, complains on missing libintl).
> Also, I had to install gedit from MacPorts as there were no gedit conda package, which felt a bit unnecessary as there were a lot of dependencies also installed. ONe solution could be to provide a gedit conda package (or why not just add a comment in the run.ch-script and the README.rmd files that one can change gedit to ones favorite editor).
> You could perhaps provide a small pre-made conda environment (as a requirement.txt file and perhaps a convenience script with the necessary conda commands for creating the environment) in the conda_r_skeleton_helper repository. I use this approach when providing bioinfo tools in my collaborative projects.
> I hope you don't take this as complaints, I meant it as feedback for the improvement of this really handy tool.

I agree we could make this script more user-friendly. It's original purpose was to be a quick-and-dirty script to help us create consistent R recipes for conda-forge. Now that more and more people are using it, we could at the very least improve the documentation. Please feel free to open an Issue (or submit a PR) on that repo.

**Comment by bgruening** [comment]
@bsennblad @jdblischak can you try this one? https://github.com/bgruening/conda_r_skeleton_helper/pull/9

**Comment by bgruening** [comment]
Thanks looks good to me!

**Pull request merged**
