### PR TITLE
Add PyPI package ablang

### PR DESCRIPTION
**Pull request by jdblischak**
* Created with online [grayskull recipe generator](https://www.marcelotrevisani.com/grayskull)
* I added `dev_url` since confusingly there are [two source repos](https://github.com/search?utf8=%E2%9C%93&q=ablang%20language%3Apython) (I added the one with the most recent commit)

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdblischak** [comment]
Looking for potential reviewers and/or co-maintainers:

* @TobiasHeOl - As the developer of ablang, would you like to be listed as a maintainer on this conda-forge recipe? This is typically a minimal commitment. Whenever you push a new release to PyPI, a conda-forge bot will automatically detect this and open a new PR to update the conda recipe repository (known as a feedstock). As long as the CI passes (and you didn't change the dependencies), you would only have to click the Merge button

* @sdvillal - From your comment https://github.com/facebookresearch/fairseq/issues/3535#issuecomment-1072715388, I see that you know a lot about one of ablang's key dependencies. Do you think I need to set any min/max restrictions on the fairseq dependency? Would you like to help me co-maintain this package?

xref: https://github.com/TobiasHeOl/AbLang/issues/2, https://github.com/oxpig/AbLang/issues/1, https://github.com/conda-forge/fairseq-feedstock/pull/17

**Comment by jdblischak** [comment]
The [Windows build failed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=560563&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=2fb5b0a7-737c-5f5c-8f3f-f6db6174bacf&l=299) because pytorch isn't available:

```sh
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested pytorch >=1.6
-   - nothing provides pytorch needed by fairseq-0.10.1-py36he38d939_0
```

This appears to be a long-standing Issue: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32 Unless anyone else can suggest a workaround, I plan to skip the Windows build

**Comment by jdblischak** [comment]
@conda-forge/help-python PyPI recipe ready for review

**Comment by sdvillal** [comment]
Hi John,

I cannot tell if ablang will become incompatible with newer versions of fairseq. I would not pin it until such incompatibility happens (which maybe could be detected by adding a simple test embedding some antibody sequence). But that is a matter of preference.

We should disable windows builds, as our deps are not all available in winworld.

I am alright to become a co-maintainer.

**Comment by jdblischak** [comment]
> I cannot tell if ablang will become incompatible with newer versions of fairseq. I would not pin it until such incompatibility happens

Great. Thanks for confirming

> (which maybe could be detected by adding a simple test embedding some antibody sequence). But that is a matter of preference.

Having a real test of its functionality would be great if it is quick-running and requires minimal extra data to be stored. This section from the docs on [testing](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-section) explains how you can add a `run_test.py` that will be automatically run. Let's save this for after the feedstock is created, since then it will be easier for you to submit a PR

> We should disable windows builds, as our deps are not all available in winworld.

Agreed, though it's not necessary to explicitly define this. This package is noarch because it has no compiled code. That means that in the feedstock, it will only be built once on Linux. If you look above in the thread, you'll see that the linter failed when I tried to add `skip: True  # [win]`.

> I am alright to become a co-maintainer.

Wonderful! Thanks so much. Just added you

**Comment by jdblischak** [comment]
@conda-forge/help-python Ready for review

**Comment by jdblischak** [comment]
@conda-forge/staged-recipes Ready for review

**Comment by jdblischak** [comment]
@sdvillal If you have the bandwidth, a [PR to the feedstock](https://github.com/conda-forge/ablang-feedstock/pulls) with a simple [test](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-section) would be a great addition

**Comment by jdblischak** [comment]
@TobiasHeOl If you decide you'd like to be a co-maintainer, please open an [Issue on the feedstock repo](https://github.com/conda-forge/ablang-feedstock/issues)

**Pull request merged**
