### PR TITLE
add jupyter_packaging

### PR DESCRIPTION
**Pull request by timkpaine**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by timkpaine** [comment]
@vidartf @blink1073 you ok with this?

**Comment by blink1073** [comment]
Yep.  Hi Tim!

**Comment by vidartf** [comment]
LGTM 👍

**Comment by timkpaine** [comment]
@conda-forge/help-python all set!

**Comment by npavlovikj** [comment]
Thank you for contributing @timkpaine 🎉

**Comment by timkpaine** [comment]
@npavlovikj do you know how long it takes for this recipe to be consumable by the other ones that require it? I assume once I get the notifications about the feedstock being created, im good to go.

Thanks!

**Comment by npavlovikj** [comment]
Yes, once you receive the e-mail that the feedstock has been created and the index is updated, one can search/use the package. This usually takes ~30 minutes, so I would give it an hour if everything works well.

**Pull request merged**
