### PR TITLE
Remove `py-graphviz`  [ci skip]

### PR DESCRIPTION
**Pull request by jakirkham**
We already have this as a feedstock. It is called `graphviz` instead. Given this, remove this recipe for it to avoid having another feedstock with the same name.

xref: https://github.com/conda-forge/staged-recipes/pull/6532

cc @conda-forge/core

### CODE REVIEW

**Comment by jakirkham** [comment]
Ack! Wasn't fast enough apparently. How should we proceed?

**Comment by scopatz** [comment]
maybe just turn this one into a meta-package

**Comment by mbargull** [comment]
@scopatz, it's the same package as `conda-forge::python-graphviz` just with another name. Happened "by accident", I'd say. We had it under the `py-` name in Bioconda due to historical reasons. But we nwo use `python-graphviz`, so everything in order.
@jakirkham, due to that `ruamel.yaml`-`conda` incompatibility thing we have going on until the docker image is rebuilt, the commit on that feedstock didn't generate any package :+1:. So we just need to remove the feedstock. Who has permissions to do so?

**Comment by scopatz** [comment]
I think all members of core can remove the feedstock, but we'll also need to remove the package from anaconda.org

**Comment by mbargull** [comment]
I'm a core member but no "maintainer"/"owner" or what GitHub's term is, so I can't :wink:.
And due to that CI issue no package has been build, so we don't have to remove anything on `anaconda.org`.

**Comment by scopatz** [comment]
flipped the bit, you are an owner now :)

**Comment by mbargull** [comment]
Haha, thanks! Well then, I did my duty and removed it :wink:

**Comment by jakirkham** [comment]
Removed it from the feedstocks repo ( https://github.com/conda-forge/feedstocks/pull/50 ) and the webpage listing ( https://github.com/conda-forge/feedstocks/pull/51 ).

**Comment by mbargull** [comment]
Oh, the "webpage listing" would have definitely been something I would've forgotten, thanks!

**Comment by jakirkham** [comment]
No worries. Thanks for taking care of the feedstock.

Was mainly mentioning the feedstocks repo so other people beyond me know about it. 😄

**Pull request merged**
