### PR TITLE
Add cythonbiogeme.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by moorepants** [comment]
It seems as if this new version requires building against NumPy 2.0 and can't be built against NumPy 1 anymore.

**Comment by moorepants** [comment]
I see:
```
Resolved dependencies, will be built in the following order:
    cythonbiogeme-1.0.3-numpy_1.23-python_3.11.* *_cpython-on-linux-64
    cythonbiogeme-1.0.3-numpy_1.22-python_3.10.* *_cpython-on-linux-64
    cythonbiogeme-1.0.3-numpy_1.26-python_3.12.* *_cpython-on-linux-64
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
```

Maybe numpy 2 needs to be specififed in `conda_build_config.yaml`.

**Comment by moorepants** [comment]
@conda-forge/help-python-c This is ready for review.

It has to be built against NumPy 2.0 and I assume I've done that correctly in the configuration, but maybe it needs adjustments.

The license is a custom license that does not have an SPDX identifier. The author gave consent to package for conda forge in #26374. I used "Custom" as the license name and the license is packaged.

We are hoping to get this included in our annual software deployment at my university before classes start Sept 1, so if this can be merged soon, that would be much appreciated. I can iterate in the feedstock if there are any other issues.

**Review by mwcraig — CHANGES_REQUESTED** [review]
@moorepants -- thanks for contributing this! A couple things:

1. I don't see the license file in the pull request; can you please add it?
2. I followed your link for the package author's consent to package this for conda-forge but didn't see the consent there. Can you please link to a specific comment?

Other than that the recipe seems good. Please mention me when you have updated it so I can get it merged quickly for you.

**Comment by moorepants** [comment]
> I don't see the license file in the pull request; can you please add it?

The license file is packaged in the PyPi tarball.

@michelbierlaire can you give explicit consent to distribute your package here on Conda Forge? You gave it via email to Sander van Cranenburgh (as far as I understand). Thanks.

**Comment by michelbierlaire** [comment]
> On 2 Aug 2024, at 21:53, Jason K. Moore ***@***.***> wrote:
> 
> 
> I don't see the license file in the pull request; can you please add it?
> The license file is packaged in the PyPi tarball.
> @michelbierlaire can you give explicit consent to distribute your package here on Conda Forge?

Yes, I confirm. 

By the way, I am about to release the next version of biogeme and cythonbiogeme that should be stable. I am finalizing all the tests and validations before pushing it. 

Michel


> You gave it via email to Sander van Cranenburgh (as far as I understand). Thanks.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

Michel Bierlaire
Transport and Mobility Laboratory
School of Architecture, Civil and Environmental Engineering
EPFL - Ecole Polytechnique Fédérale de Lausanne
http://transp-or.epfl.ch
http://people.epfl.ch/michel.bierlaire

**Comment by moorepants** [comment]
@mwcraig Is all sufficient now?

**Comment by moorepants** [comment]
Thanks @michelbierlaire!

**Comment by mwcraig** [comment]
> > I don't see the license file in the pull request; can you please add it?

> The license file is packaged in the PyPi tarball.

Apologies, I misunderstood -- I thought you meant for it to be packaged with the recipe.

Thanks to both of you for getting this onto conda-forge, about to merge...

**Review by mwcraig — APPROVED** [review]

**Comment by moorepants** [comment]
Thanks!

**Comment by michelbierlaire** [comment]
I have just released 
cythonbiogeme  1.0.4
biogeme-optimization 0.0.10
biogeme 3.2.14
If you give me the instructions, I am happy to package it for conda as well.

**Comment by moorepants** [comment]
The cythonbiogeme feedstock is already present: https://github.com/conda-forge/cythonbiogeme-feedstock and we've built binaries for 1.0.3 and 1.0.4: https://github.com/conda-forge/cythonbiogeme-feedstock.

@FGarridoV is making the recipes for biogeme and biogeme-optimization here: https://github.com/conda-forge/staged-recipes/pull/26374 I think he is close to it working. You can help by commenting on that PR.

**Comment by moorepants** [comment]
@michelbierlaire biogeme, biogeme-optimization, and cythonbiogeme are now available for all three main OSs via conda and the conda-forge channel. FYI

**Comment by michelbierlaire** [comment]
Amazing. Thanks a lot. 
What instructions can I post on the Biogeme webpage if people want to use it?
Also, can you give me instructions to that I can generate the same for future releases?

**Comment by moorepants** [comment]
The instructions for installing each package are on their feedstock readme's. But, in general, you have to `conda install -c conda-forge biogeme`.

If you want to help maintain the feedstocks then you should request to be added as a maintainer to each of the three feedstocks.

**Pull request merged**
