### PR TITLE
Add r-glassofast using conda_r_skeleton_helper

### PR DESCRIPTION
**Pull request by cpauvert**
Adjust the license after the helper

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by cpauvert** [comment]
Dear reviewers, here is a suggestion of integration of the CRAN R package `glassoFast`. This addition is intended to fullfill the dependency of #13031. 
 
Dear @JClavel, do you accept to be added to the list of the maintainer of this recipe?

Best, 
Charlie

**Comment by JClavel** [comment]
Dear Charlie,

Yes you can add me to the list of maintainer of the glassoFast package (it's already the case on CRAN)
Regards,

Julien

________________________________
De : Charlie Pauvert <notifications@github.com>
Envoyé : lundi 2 novembre 2020 18:13
À : conda-forge/staged-recipes <staged-recipes@noreply.github.com>
Cc : JClavel <julien.clavel@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [conda-forge/staged-recipes] Add r-glassofast using conda_r_skeleton_helper (#13060)


Dear reviewers, here is a suggestion of integration of the CRAN R package glassoFast. This addition is intended to fullfill the dependency of #13031<https://github.com/conda-forge/staged-recipes/pull/13031>.

Dear @JClavel<https://github.com/JClavel>, do you accept to be added to the list of the maintainer of this recipe?

Best,
Charlie

**Comment by cpauvert** [comment]
Thanks Julien for your quick answer. You're added to the list!

**Comment by cpauvert** [comment]
Thank @dbast the quick merge!

**Pull request merged**
