### PR TITLE
add ripfind package

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/staged-recipes

**Comment by beenje** [comment]
1. Windows build is failing. For it to pass, you have to create a `bld.bat` file.
Or you could skip windows build, but I believe rust projects should compile on windows without much work.

2. For rust projects, the license of all dependencies should be included. See https://github.com/conda-forge/conda-forge.github.io/issues/1052
You can check https://github.com/conda-forge/ripgrep-feedstock which uses `cargo-bundle-licenses` or https://github.com/conda-forge/rage-feedstock
You can also look at the windows build there.

**Comment by matthiasdiener** [comment]
> 1. Windows build is failing. For it to pass, you have to create a `bld.bat` file.
>    Or you could skip windows build, but I believe rust projects should compile on windows without much work.
> 2. For rust projects, the license of all dependencies should be included. See [Rust/Go packages license issues conda-forge.github.io#1052](https://github.com/conda-forge/conda-forge.github.io/issues/1052)
>    You can check https://github.com/conda-forge/ripgrep-feedstock which uses `cargo-bundle-licenses` or https://github.com/conda-forge/rage-feedstock
>    You can also look at the windows build there.

Thanks @beenje, I think I addressed your comments in the updated PR.

**Comment by beenje** [comment]
@conda-forge/staged-recipes, this recipe looks good to me!

**Pull request merged**
