### PR TITLE
add anndata recipe

### PR DESCRIPTION
**Pull request by JakaKokosar**
Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vend other packages
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by pavlin-policar** [comment]
This is going to require some maintenance :smile:

**Comment by JakaKokosar** [comment]
@conda-forge/staged-recipes Can we merge this?

**Comment by beckermr** [comment]
Yup! You should add the license file to the upstream package if you can.

**Comment by JakaKokosar** [comment]
@beckermr on it! https://github.com/theislab/anndata/issues/202

Thanks!

**Comment by flying-sheep** [comment]
I recently pushed a change that includes putting the license in the source tarball.

Heads-up: The next version will also require Python 3.6+

**Comment by beckermr** [comment]
Once the next version lands, you should be able to remove the license file from the feedstock repo.

**Comment by beckermr** [comment]
Thanks @flying-sheep! When that happens @JakaKokosar, you can add a version limit to the feedstock.

**Comment by pavlin-policar** [comment]
@flying-sheep would you be opposed to being added as a package maintainer on here as well? I know you guys already have a conda package on bioconda, so you may not be interested in maintaining this as well, but if you're pushing our releases, it's really easy to push things out simultaneously. If not, that's fine as well, @JakaKokosar and I will keep this up to date.

**Comment by chrisburr** [comment]
The `bioconda` channel builds on top of `conda-forge` and has a lower priority. I might be wrong but I think packages are supposed to be removed from `bioconda` if they're added to `conda-forge`?

**Comment by flying-sheep** [comment]
If someone knows a package/script on how to (semi-)automate our release process I’ll consider it. (I.e. bump versions where necessary and check for inconsistencies before doing anything).

**Comment by chrisburr** [comment]
Generally it's just a matter of merging PRs made by the bot. For example here is a recent update to a feedstock I maintain: https://github.com/conda-forge/uproot-feedstock/pull/38

The main intervention I end up needing to do it editing the version constraints when they change. (Eventually the bot should do this automatically for PyPI packages, but not yet.)

**Comment by pavlin-policar** [comment]
@flying-sheep As @chrisburr pointed out, it's generally very easy. Once you push a release onto PyPI, the conda-forge bot will automatically open a PR on the feedstock, and most of the time, it's just a matter of pressing "Merge PR". Since `anndata` is a sdist-only package, there really should never be any issues building the packages.

If `anndata` had extensions which would need to be compiled and/or have special build steps, we would think twice about this, because setting up and maintaining that can be quite a headache. But a pure python package should be easy going.

**Comment by flying-sheep** [comment]
Sure, just add us. Can’t promise I’ll be quick but if there’s GitHub notifications I usually react :wink:

**Pull request merged**
