### PR TITLE
Add cramjam==1.2.0

### PR DESCRIPTION
**Pull request by milesgranger**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by martindurant** [comment]
I appears that pip-installing the wheel is not happening, and I can't tell why (says no matching version, but the wheels do seem to cover all of py35-38 and OSs). I don't know if conda-forge prefers recompilation, even for a case like this where you are not linking against python.

@mariusvniekerk this might interest you.

**Comment by martindurant** [comment]
I think I am right in saying that `pip` should be in the "host" section of build.

**Comment by mariusvniekerk** [comment]
We have a rust compiler, so we should be able to just build this

**Comment by milesgranger** [comment]
Thanks, I saw there was a rust compiler. However, I struggle a bit to understand why, if the wheels on PyPi are already statically compiled, one needs to set up yet another compilation process just to be listed on conda-forge? The documentation seems to elude that installing `.whl` files via pip is an acceptable approach, perhaps I'm mistaken in my interpretation, however.

**Comment by martindurant** [comment]
Just include "rust" in the build section, and change script to `maturin build --release --out wheels` ?

@milesgranger , does this depend on maturin or cffi?

**Comment by milesgranger** [comment]
maturin

**Comment by martindurant** [comment]
@mariusvniekerk , I think this would have been a valuable addition, is there any chance of you or someone else helping restart this and get it across the line? As I also maintain python-snappy, and it is constantly failing in many new and interesting ways, I would love to hav a simple-to-install alternative.

**Comment by martindurant** [comment]
cc @conda-forge-admin - if anyone else might be interested in helping

**Pull request closed without merging**
