### PR TITLE
7zip

### PR DESCRIPTION
**Pull request by wolfv**
This is 7zip for windows. 
I could only find m2-p7zip and p7zip otherwise, which are (unmaintained) POSIX derivatives from 7zip.

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by wolfv** [comment]
@conda-forge/staged-recipes ready for review & merge!

**Comment by scopatz** [comment]
This likely conflicts with the 7za package that already exists, CC @conda-forge/7za @conda-forge/staged-recipes @conda-forge/core

**Comment by wolfv** [comment]
Ah, i didn't see that (but I did look extensively). 7za is severely outdated (10 years) and a binary repackaging so I hope that this one is better.

**Comment by beckermr** [comment]
Either way, @wolfv you need to be adding run constraints on both to avoid buggy envs. 

You'll need to make a repo data patch for older versions too.

**Comment by beckermr** [comment]
We also need to make sure the outputs records for feedstocks are correct so that the maintainers of the older package can still perform uploads.

**Comment by isuruf** [comment]
What? The only thing to do is add `run_constrained` to `7zip` so that it conflicts with `7za` and mark the first `7zip` build as broken. No need to add contraints to `7za` or change anything in `7za`

**Comment by beckermr** [comment]
That may be sufficient. It depends on exactly what is in both recipes.

**Comment by wolfv** [comment]
the other package is called `7za`. 

The outputs don't conflict.

We can add a run_constrains to the `7zip` package to prevent parallel installation with `7za` although. I think `7za` should be archived though (@scopatz happy to add you as a maintainer on `7zip`.
I don't mind a little clobberwarning but yeah I can make these changes tomorrow.

**Comment by jakirkham** [comment]
I think what Matt means is they both supply a `7za` executable. So they will clobber each other if they are both installed.

cc @mingwandroid

**Comment by beckermr** [comment]
This package is only windows so it doesn't conflict now for OS X and Linux. However I think we should put the run constraint in now. Inevitably we are all going to forget this conversation, some other maintainer will add the other platforms, and then we will have an actual conflict on the other platforms. 

We may have a conflict on windows already.

**Comment by wolfv** [comment]
All other packages use p7zip

There is also m2-p7zip whcih probably clobbers with both (7zip and 7za)? Not sure how m2-* packages work in this regard.

**Comment by wolfv** [comment]
I just checked, no package in conda-forge depends on 7za. phew! :)

**Pull request merged**
