### PR TITLE
Add nbqa

### PR DESCRIPTION
**Pull request by s-weigand**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by s-weigand** [comment]
@MarcoGorelli @girip11 please confirm that you are willing to be a maintainer of the conda-forge feestock for `nbqa`

**Comment by MarcoGorelli** [comment]
Looks good to me, thanks for spearheading this!

Shall we also add @neomatrix ? (Mani, please confirm if you're OK with this)

**Comment by s-weigand** [comment]
> Shall we also add @neomatrix ? (Mani, please confirm if you're OK with this)
Sure, if he wants to.

**Comment by girip11** [comment]
> please confirm that you are willing to be a maintainer of the conda-forge feestock for nbqa

Yes I am willing to be a maintainer.

**Comment by MarcoGorelli** [comment]
@s-weigand if we make a new release on PyPI, is it easy enough to port over to conda-forge?

**Comment by s-weigand** [comment]
@MarcoGorelli the bot will pick up new releases on PyPi and make a PR on the conda-forge feedstock.
If you want to make a Release before this PR is merged, I need to change the `version` and `sha256` in this recipe before it is merged. At least I don't know how the bot behaves if a new release was made before the feedstock was added.

Anyway, I think this PR is ready for review and merge. If  @neomatrix wants to be a maintainer, we could also add him from the feedstock.

**Comment by MarcoGorelli** [comment]
@s-weigand sounds good, thanks! Sure, let's go :rocket:

**Comment by s-weigand** [comment]
@conda-forge/help-python We are ready for review 😄

**Comment by dbast** [comment]
Nice tool. Thanks!

**Comment by MarcoGorelli** [comment]
Thanks @dbast , and thanks @s-weigand for taking this on!

**Pull request merged**
