### PR TITLE
add argopy

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://github.com/euroargodev/argopy

### CODE REVIEW

**Comment by ocefpaf** [comment]
Needs https://github.com/euroargodev/argopy/pull/29

**Comment by gmaze** [comment]
Hi @ocefpaf 
Not sure you still have comments from the merged PR.

It seems that the presence of the MANIFEST.in file creates an error when uploading the new argopy release with twine.
After:
```python setup.py sdist bdist_wheel bdist_egg```

When I try to run the ``twine upload``, I have the following error:
```bash
Uploading distributions to https://test.pypi.org/legacy/
Traceback (most recent call last):
  File "/Users/gmaze/anaconda/envs/obidam36/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/twine/__main__.py", line 28, in main
    result = cli.dispatch(sys.argv[1:])
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/twine/cli.py", line 82, in dispatch
    return main(args.args)
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/twine/commands/upload.py", line 151, in main
    return upload(upload_settings, parsed_args.dists)
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/twine/commands/upload.py", line 86, in upload
    _make_package(filename, signatures, upload_settings) for filename in uploads
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/twine/commands/upload.py", line 86, in <listcomp>
    _make_package(filename, signatures, upload_settings) for filename in uploads
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/twine/commands/upload.py", line 58, in _make_package
    package = package_file.PackageFile.from_filename(filename, upload_settings.comment)
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/twine/package.py", line 84, in from_filename
    meta = DIST_TYPES[dtype](filename)
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/pkginfo/bdist.py", line 11, in __init__
    self.extractMetadata()
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/pkginfo/distribution.py", line 108, in extractMetadata
    data = self.read()
  File "/Users/gmaze/anaconda/envs/obidam36/lib/python3.6/site-packages/pkginfo/bdist.py", line 38, in read
    raise ValueError('No PKG-INFO in archive: %s' % fqn)
ValueError: No PKG-INFO in archive: /Users/gmaze/git/github/euroargodev/argopy/dist/argopy-0.1.4-py3.6.egg
```

Any ideas on how to fix this ?

**Comment by gmaze** [comment]
Hi @ocefpaf 
I think it's the ``prune *.egg-info`` line that leads to this error
Is it safe to remove it for ``pip install argopy --no-binary :all:`` to work ?

**Comment by ocefpaf** [comment]
I'll send a PR upstream to you to check the tarball and the upload. The `prune` part is "standard" and should not be a problem.

**Comment by gmaze** [comment]
It should be ok now.

**Comment by ocefpaf** [comment]
@conda-forge/staged-recipes this is ready for review!

**Comment by gmaze** [comment]
@ocefpaf 
On July 10th I release version 0.1.5 of argopy but it seems that conda still install 0.1.4:
```
    $ conda create --yes -n argopy-tests python=3.6 xarray dask numpy pytest future
    $ conda activate argopy-tests
    $ conda install -c conda-forge argopy
    $ python -c 'import argopy; print(argopy.__version__);'
    $ conda deactivate
    $ conda env remove --yes -n argopy-tests
```

how is the automatic update made ?
g

**Comment by ocefpaf** [comment]
The bot should've picked it up. Let me check.

Let's follow up on the feedstock at: https://github.com/conda-forge/argopy-feedstock/blob/master/recipe/meta.yaml

**Comment by chrisburr** [comment]
The issue is that you didn't upload an sdist to pypi: https://pypi.org/project/argopy/#files

**Comment by ocefpaf** [comment]
Yep. Only wheels. I'll send a PR upstream to automate the publication of artifacts on PyPI. We can use GH actions for that.

**Comment by gmaze** [comment]
great, thank you both
@ocefpaf note that this should take place in: https://github.com/euroargodev/argopy/blob/master/.github/workflows/pythonpublish.yml

**Comment by ocefpaf** [comment]
Done! https://github.com/euroargodev/argopy/pull/45

BTW, Oceanhackweek is happening right now, we need that version ;-p

**Comment by gmaze** [comment]
Just uploaded the sdit files at https://pypi.org/project/argopy/0.1.5/#files

**Comment by gmaze** [comment]
About Oceanhackweek, I've seen Joseph Gum has tried to contact me to set this up for argopy, but I came back too late from summer break to work on this... Are you involved @ocefpaf ?

**Comment by ocefpaf** [comment]
> About Oceanhackweek, I've seen Joseph Gum has tried to contact me to set this up for argopy, but I came back too late from summer break to work on this... Are you involved @ocefpaf ?

Yep. @asx- and I are some of the organizer of it. It would be awesome to have you onboard. Argopy certainly is ;-p

**Comment by gmaze** [comment]
what would that imply ?

**Comment by ocefpaf** [comment]
> what would that imply ?

Let's talk in another venue. If you use gitter send me a message. Or maybe an email (copying Joseph so he can help me explain). My username is always ocefpaf.

**Comment by gmaze** [comment]
> > what would that imply ?
> 
> Let's talk in another venue. If you use gitter send me a message. Or maybe an email (copying Joseph so he can help me explain). My username is always ocefpaf.

Sent you a message on gitter

**Pull request merged**
