### PR TITLE
On Travis CI use Linux for pushes and Mac for PRs

### PR DESCRIPTION
**Pull request by jakirkham**
Select which operating system to use for the VM based on whether the build is a PR build or not. For PRs, use macOS as we are presumably trying to build a recipe. For everything else, this should be a feedstock conversion job. So using Linux in this case should be fine. This uses Travis CI's new conditional matrix syntax to select the OS. Hopefully can process conversions a bit faster.

ref: https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

### CODE REVIEW

**Comment by isuruf** [comment]
Is this still WIP?

**Comment by jakirkham** [comment]
Yeah. In fact, in its current state, it is unmergeable as the conditions are reversed. Also seems like it still runs on macOS with the conditions reversed. 😕 If you want to play with it, feel free to. There might be a setting we can change in Travis CI's beta features. Also different condition checks might work better.

**Comment by jakirkham** [comment]
Alright this seems to be working. Going to give it a go.

**Comment by jakirkham** [comment]
Hmm...`master` is being slow to start, which makes me think it is still using macOS. 😒 Going to have to rip it back out unfortunately. 😩

**Comment by jakirkham** [comment]
Reverting in PR ( https://github.com/conda-forge/staged-recipes/pull/4166 ).

**Pull request merged**
