### PR TITLE
Add Python package radian.

### PR DESCRIPTION
**Pull request by jdblischak**
I created a recipe for the PyPI package [radian](https://pypi.org/project/radian/) with grayskull version 0.8.4.

xref: https://github.com/randy3k/radian/issues/244

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdblischak** [comment]
@randy3k A few items:

* Please acknowledge you are willing to be a maintainer
* I added a [run constraint](https://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=run_constrained#defining-non-dependency-restrictions) for jedi. Basically, jedi doesn't have to be installed, but if it is, it has to be below 0.18.
* Shouldn't radian depend on prompt_toolkit? It appears to be directly referenced in the radian package files (i.e. not via lineedit). When I tried to build this locally, it failed because it couldn't find prompt_toolkit.

**Comment by jdblischak** [comment]
```
import: 'radian'
import: 'radian.latex'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/radian_1612922263942/test_tmp/run_test.py", line 5, in <module>
    import radian.latex
  File "/home/conda/staged-recipes/build_artifacts/radian_1612922263942/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.8/site-packages/radian/latex/__init__.py", line 2, in <module>
    from prompt_toolkit.completion import Completion
ModuleNotFoundError: No module named 'prompt_toolkit'
Tests failed for radian-0.5.10-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/staged-recipes/build_artifacts/broken
WARNING conda_build.build:tests_failed(2955): Tests failed for radian-0.5.10-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/staged-recipes/build_artifacts/broken
TESTS FAILED: radian-0.5.10-pyhd8ed1ab_0.tar.bz2
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=276013&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=786

**Comment by randy3k** [comment]
> @randy3k A few items:
> 
> 
> 
> * Please acknowledge you are willing to be a maintainer
> 
> * I added a [run constraint](https://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=run_constrained#defining-non-dependency-restrictions) for jedi. Basically, jedi doesn't have to be installed, but if it is, it has to be below 0.18.
> 
> * Shouldn't radian depend on prompt_toolkit? It appears to be directly referenced in the radian package files (i.e. not via lineedit). When I tried to build this locally, it failed because it couldn't find prompt_toolkit.

Thanks again for your work. 

promot_toolkit is vendored in line edit. You will need to import lineedit first before importing radian.latex.

**Comment by jdblischak** [comment]
> we actually don’t need to specify it as a dependency. It is vendored in lineedit.

OK. I removed it as a dependency and imported lineedit before radian.latex.

Out of curiosity (I'm not a Python expert), couldn't you avoid this issue by having radian specifically reference the vendored prompt_toolkit within lineedit? As an example, replace

```
from prompt_toolkit.utils import is_windows
```

with

```
from lineedit.deps.prompt_toolkit.utils import is_windows
```

**Comment by randy3k** [comment]
It will work for a single file module. However promot_toolkit is a multi file module and there are a lot of absolute imports in itself ( 
those `import promot_toolkit` statements). In order to make it work, we will need to modify a large amount of code (ie. change all those `import promot_toolkit` to `import lineedit.path_to_pt.promot_toolkit`) and it will make upgrading prompt_toolkit more difficult.

**Comment by jdblischak** [comment]
@randy3k Thanks for the explanation!

**Comment by jdblischak** [comment]
@conda-forge/staged-recipes Ready for review

**Pull request merged**
