### PR TITLE
add recipe for jupyter_latex_envs

### PR DESCRIPTION
**Pull request by jcb91**

### CODE REVIEW

**Comment by jcb91** [comment]
@jfbercher seems from the output that installing using `--sys-prefix` flag doesn't work. I've tried to use the command

python setup.py install --single-version-externally-managed --record=record.txt --sys-prefix

**Comment by jfbercher** [comment]
I do not know what happens. 
Indeed, on the command line, `python ./setup.py install --sys-prefix` fails. 
I tested the cmd for `jupyter_contrib_nbextensions` and it does the same
image
Curious?

**Comment by jcb91** [comment]
So I think it's just because --sys-prefix isn't a recognised argument of the setuptools install command. Since `jupyter_contrib_nbextensions` still keeps a two-step install process, this isn't a problem, as the `--sys-prefix` flag is only meanigful for the second part of the install. However, `latex_envs` is attempting to roll both the setuptools install (doesn't like `--sys-prefix`) and the nbextension install (needs `--sys-prefix` to work with anaconda) into one. To keep the one-step install for latex_envs, I think you'd need to strip the `--sys-prefix` out of `sys.argv` and set the appropriate variable _before_ running `setup(...`.

**Comment by jfbercher** [comment]
Ok. 
I have simply dropped the "one step install" and updated the version both on pypi and github.

**Comment by jcb91** [comment]
Ok, I'll try to have another stab at the conda recipe this afternoon

**Comment by jcb91** [comment]
apologies for the delay, I've just managed to push an updated recipe using the new two-step install (the conda recipe performs both steps as part of its own install, the python package gets done by th main install command in the `meta.yaml` file, while the nbextension gets installed/uninstalled in the post-link/pre-unlink scripts).

**Comment by jcb91** [comment]
right, I think this works ok now, finally 😄

**Comment by scopatz** [comment]
Thanks!

**Comment by jfbercher** [comment]
@jcb91 Thanks a lot

**Pull request merged**
