### PR TITLE
Pyfmmlib

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
This is ready to review.

**Comment by isuruf** [comment]
I fixed the osx build and pushed to your branch. It was a `numpy.distutils` issue. (`conda-build` and `toolchain` was setting `LDFLAGS` and `numpy.distutils` was using that value instead of appending.)
`toolchain3` fixes this issue.

**Comment by inducer** [comment]
@isuruf Awesome, thanks!

If you're curious: [This](https://gitlab.tiker.net/inducer/pytential/merge_requests/60) is what prompted the excitement. :)

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
