### PR TITLE
added qtkeychain recipe

### PR DESCRIPTION
**Pull request by gillins**
This is needed for `qgis` 3.x.

@ceholden I assume you would be happy to be a maintainer?

### CODE REVIEW

**Comment by ceholden** [comment]
Looks great! Thank you and I would be happy to be maintainer.

**Comment by gillins** [comment]
Hmmm: https://travis-ci.org/conda-forge/staged-recipes/builds/267879179#L350

Anyone have any ideas?

**Comment by ocefpaf** [comment]
> Anyone have any ideas?

Maybe it is something similar to https://github.com/leouieda/gmt-feedstock/blob/52818a27764471d142b4704a6b7515ecbcc703ce/recipe/build.sh#L44-L69

**Comment by gillins** [comment]
Thanks @ocefpaf does look like the same thing. I will investigate...

**Comment by gillins** [comment]
That was it! Thanks. I think this one is good to go...

**Pull request merged**
