### PR TITLE
Add sbcl - WIP: issue with GLIBC 2.28

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by MementoRC** [comment]
@xhochy This is the recipe that has the `__glibc` issue that I don't understand, if you find some time to browse through it

**Comment by MementoRC** [comment]
@xhochy At your convenience, do you understand why the packaging fails:
```
Packaging sbcl
Packaging sbcl-2.4.4-hed3a728_0
number of files: 52
Warning: rpath /home/conda/staged-recipes/build_artifacts/sbcl_1714693210817/_build_env/lib is outside prefix /home/conda/staged-recipes/build_artifacts/sbcl_1714693210817/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh (removing it)
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 261, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 151, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 207, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3762, in build_tree
    packages_from_this = build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2839, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 1974, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 1782, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/post.py", line 1729, in post_build
    check_overlinking(m, files, host_prefix)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/post.py", line 1554, in check_overlinking
    return check_overlinking_impl(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/post.py", line 1414, in check_overlinking_impl
    all_needed_dsos, needed_dsos_for_file = _collect_needed_dsos(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/post.py", line 847, in _collect_needed_dsos
    needed = get_linkages_memoized(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/os_utils/liefldd.py", line 1191, in __call__
    value = self.func(*args, **kw)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/os_utils/liefldd.py", line 1220, in get_linkages_memoized
    return get_linkages(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/os_utils/liefldd.py", line 630, in get_linkages
    result_lief = inspect_linkages_lief(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/os_utils/liefldd.py", line 509, in inspect_linkages_lief
    uniqueness_key = get_uniqueness_key(binary)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/os_utils/liefldd.py", line 370, in get_uniqueness_key
    return str(file)
MemoryError: std::bad_alloc
```

**Comment by MementoRC** [comment]
Note that this run fails because (I think) the tests that I run during the build are run in the _h_env that does not seem to have GLIBC 2.28. It passed before when I had sysroot in host. I can patchelf the `sbcl` used then, but eventually, I don't want to run the tests during the build, but in the recipe tests.

The packaging error is the one that I don't know now to resolve locally. It seemed to have coincided with using the cbc.yaml to define glibc

**Comment by xhochy** [comment]
As this is already a feedstock, can you open the PR over there? On feedstocks, it is much easier to work with the newer `glibc` requirement. I can help over there then.

**Pull request closed without merging**
