### PR TITLE
Added art as a package

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge/staged-recipes and @conda-forge/bioconda-recipes 
This is ready review; although maybe this is already available on bioconda? Not sure what the protocol is then

**Review by BastianZim — CHANGES_REQUESTED** [review]
Just one small thing

**Comment by thewchan** [comment]
@BastianZim do I do that or someone on the core team do that? If the former what's the protocol?

**Comment by BastianZim** [comment]
No that is up to the bioconda team. Since they're pinged we just need to wait now.

**Comment by thewchan** [comment]
@BastianZim @conda-forge/staged-recipes no news about this?

**Comment by BastianZim** [comment]
@bgruening Would you mind having a look as you‘re the most active Bioconda member?

**Comment by jtpio** [comment]
Thanks all for working on this!

Looks like `art` would also be needed for `samila`: https://github.com/conda-forge/staged-recipes/pull/20098

cc @sepandhaghighi

**Comment by thewchan** [comment]
@BastianZim @conda-forge/core @bgruening Just pinging this again, any next steps from our end?

**Review by bgruening — DISMISSED** [review]

**Comment by bgruening** [comment]
Please proceed here I will take care and remove it from bioconda.

Thanks.

**Comment by bgruening** [comment]
Or wait ... its unfortunately not the same tool.

**Comment by bgruening** [comment]
It seems those are different tools - so its not a replacement - its a name clash.

Can we change the name here? Maybe `ascii-art` or `art-python`?

**Comment by jaimergp** [comment]
Oh, good catch! We need to pick a different name then!

* Bioconda's ART comes from https://www.niehs.nih.gov/research/resources/software/biostatistics/art/
* This ART is for ASCII Art generation

So something like `art-ascii` or similar?

**Comment by jaimergp** [comment]
Hah, 🧠 ⚡

**Comment by thewchan** [comment]
Do I push a different from my end?

**Comment by jaimergp** [comment]
Yes, @thewchan, just pick a different name at `{% set name = "art" %}`, but leave the other instances like they are.

**Comment by bgruening** [comment]
@thewchan you can change the name here in the recipe. That would solve it.

**Comment by sepandhaghighi** [comment]
Hi
I'm Sepand the main developer of [art](https://github.com/sepandhaghighi/art) project.
First of all, I want to say thanks all for your efforts 💯 
I have a fundamental question, do `conda-forge` and `bioconda` use a common name repository? (For example, is it not possible to add package-x to `conda-froge` when there is a package with the exact same name in `bioconda`?)
If it is not possible to add this library to `conda-forge` under the name of art, I prefer `ascii-art` .

SH

**Comment by ocefpaf** [comment]
> I have a fundamental question, do `conda-forge` and `bioconda` use a shared repository? (For example, is it not possible to add package-x to `conda-froge` when there is a package with the exact same name in `bioconda`?)

@sepandhaghighi in conda-forge we have a policy of "first come first served" for names. However, b/c conda-forge and bioconda are sister orgs and we rely on each other. In a way, the name was first used there, so the namespace was also blocked here.

I'd love a better solution for this but you know, the 2 hardest problem in CS: cache validation, naming things, and off by 1 errors!

**Comment by thewchan** [comment]
@BastianZim @ocefpaf @bgruening @jaimergp @sepandhaghighi 
The proposed package has been renamed

**Comment by thewchan** [comment]
@BastianZim @ocefpaf @bgruening @jaimergp @sepandhaghighi @conda-forge/staged-recipes All test passes

**Review by bgruening — APPROVED** [review]

**Pull request merged**
