### PR TITLE
add bioformats_jar

### PR DESCRIPTION
**Pull request by tlambert03**
This is a companion package that provides a jar and minimal jpype wrapper for other libraries to use.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by tlambert03** [comment]
i'm a little stumped on this one and could use some input @conda-forge/help-python.   This is a very simple noarch package and it's building fine on mac and linux ... but fails on windows because of a [missing dependency requirement](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=379936&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77&l=3998).  My only two direct dependencies however (jpype and openjdk) both provide windows packages on conda-forge.

The only thing I can think of that is somewhat different here is that this is a pep 517-style package with no setup.py (only pyproject.toml and setup.cfg).  Is that something that has had issues elsewhere?

**Comment by jakirkham** [comment]
I think that is unrelated because of this line where it appears to be building a different package. Not entirely sure why that happened, but let's just rerun CI

```
BUILD START: ['ldrb-2021.0.1-pyhd8ed1ab_0.tar.bz2']
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=379936&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77&l=3910

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart CI

**Comment by tlambert03** [comment]
Oh, ha!  Thanks @jakirkham!

**Comment by tlambert03** [comment]
all set for review @conda-forge/help-python

**Comment by jakirkham** [comment]
cc @joshmoore (for awareness 🙂)

**Pull request merged**
