### PR TITLE
Add edt PyPI package

### PR DESCRIPTION
**Pull request by william-silversmith**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by ma-sadeghi** [comment]
@conda-forge/staged-recipes Can you please take a look to see why it's failing? It complains about overlinking...

**Comment by nehaljwani** [comment]
Add `- {{ compiler('c') }}` in the build section, so that you can get a run-time dependency on `libgcc-ng`

Also, you might want to update the list of imports in the test section.

**Comment by william-silversmith** [comment]
Thank you for the advice! I gave it a try but I still seem to get errors. :-/ I even added the c compiler to the run section.

["  ERROR (edt,lib/python3.6/site-packages/edt.cpython-36m-x86_64-linux-gnu.so): .. but ['libstdcxx-ng'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (edt,lib/python3.6/site-packages/edt.cpython-36m-x86_64-linux-gnu.so): .. but ['libgcc-ng'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]

**Comment by william-silversmith** [comment]
The interesting thing is that it appears to have successfully built the binary now. I guess it's moving onto testing?

**Comment by synapticarbors** [comment]
@william-silversmith Thank you for your contribution to conda-forge. If you run into any issues once the feedstock is built, please don't hesitate to ping me or the conda-forge team.

**Pull request merged**
