### PR TITLE
Add Htslib library

### PR DESCRIPTION
**Pull request by matuskosut**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Review by mbargull — CHANGES_REQUESTED** [review]
Hi @matuskosut,

we maintain Conda packages for HTSlib over at https://github.com/bioconda/bioconda-recipes/blob/master/recipes/htslib/meta.yaml for the `bioconda` channel.
Since HTSlib one of those base libraries that many other bioinformatics projects depend on, moving it over from Bioconda to conda-forge is a rather big change that we should not do lightly.
Is `bioconda::htslib` sufficient for your usage intentions?

Cheers,
Marcel

**Comment by matuskosut** [comment]
Hi @mbargull,

is it a question of moving or could it be available in both? As library it could also be used within builds that have a lot more dependencies in conda-forge if available in both. I am not sure how conda-forge is doing with such builds when dependency is in bioconda, do you have any experience with it? Could I just put `bioconda::htslib` in dependencies in meta.yaml?

**Comment by matuskosut** [comment]
@mbargull added discussion in https://github.com/orgs/conda-forge/teams/bioconda-recipes/discussions/7

**Comment by mbargull** [comment]
Hi @matuskosut,

> is it a question of moving or could it be available in both?

We try to avoid adding duplicate package to both channels, so it'd be move rather than replicate. (Though, with essential things like HTSlib we probably would even need a certain transitioning phase in which we'd duplicate to avoid breaking user setups.)

> As library it could also be used within builds that have a lot more dependencies in conda-forge if available in both. I am not sure how conda-forge is doing with such builds when dependency is in bioconda, do you have any experience with it? Could I just put `bioconda::htslib` in dependencies in meta.yaml?

The relationship between Bioconda and conda-forge is that the former heavily depends on the non-bioinformatics packages from the latter. Both projects collaborate closely (hint: I'm in the core teams of both ;).). The reason why we have these split channels is mostly historic (both were started independently in the same year) and due to some conceptual differences.
We keep conda-forge pretty much self-contained (apart from possibly a handful dependencies from Anaconda's `defaults` channels due to historic/licensing reasons). Which means we do not allow conda-forge packages to depend on packages from Bioconda.
Bioconda on the other hand uses general purpose package from conda-forge and has nearly all of the bioinformatics packages. As such it's preferable to submit bioinf-related packages to Bioconda. (We have some non-bioinf ones in Bioconda, but that's mostly due to historic reasons.)

By trying to package HTSlib here, I assume you want to package other bioinf packages, right? I'd like to encourage you to submit them to Bioconda for now. (Using Bioconda by your users is as easy as just adding an additional channel to install packages from, like `conda install -c conda-forge -c bioconda your-package` or `conda config --append channels bioconda`.)
I've brought up your pull request in yesterday's Bioconda/core meeting and we agreed that this change can be quite disruptive to downstream projects so that we'd prefer to keep HTSlib in Bioconda for the time being. If we'd move it to conda-forge we have to carefully plan that which would take a non-negligible amount of effort and time -- what I'm trying to say is that currently it'd be faster to make your packages available via `bioconda`;).

**Comment by matuskosut** [comment]
thanks @mbargull ! Sounds reasonable.

**Comment by mbargull** [comment]
Happy to hear that!
Thanks for your contributions -- to either project that is :).

**Comment by matuskosut** [comment]
@mbargull I sent a member request to bioconda group, but maybe this one here within conda-forge is not the best place. Is there a good place to join for some discussions?

**Comment by mbargull** [comment]
I've sent you an invite for Bioconda.
The conda-forge/bioconda-recipes group is only for managing/avoiding conflicting packages between both channels -- probably not what you're after ;).
You can open PRs to https://github.com/bioconda/bioconda-recipes , find our Gitter at https://gitter.im/bioconda/Lobby and docs at https://bioconda.github.io/.

**Pull request closed without merging**
