### PR TITLE
Add dust

### PR DESCRIPTION
**Pull request by jonashaag**
based on https://github.com/conda-forge/staged-recipes/pull/18008, fyi @peterjc

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by peterjc** [comment]
Hat tip @jonashaag on whose original PR my effort was based. It looks like there is a better way to handle the 3rd party licenses now which is where I got stuck.

I'm happy to see this get packaged, but I don't need to be listed as a maintainer

**Comment by jonashaag** [comment]
Do you want to be removed?

**Comment by Zeitsperre** [comment]
Hi there, it would be great to see this get merged in (I have systems where it's easier to install a conda package than a rust toolchain). Any chance of moving forward on this?

**Comment by xhochy** [comment]
This needs a new MacOS SDK setting and then it should be good to go.

**Comment by Zeitsperre** [comment]
@xhochy Is there anything I can do to help? Or is this something that needs to be updated on the conda-forge side?

**Comment by xhochy** [comment]
See this announcement: https://conda-forge.org/news/2024/01/29/rust-175-osx-sdk/ Adding the file and the run requirement should be enough.

**Comment by Zeitsperre** [comment]
@jonashaag

I've made a Pull Request to update your proposed recipe. I don't mind being a maintainer if that's of interest to you.

**Comment by xhochy** [comment]
@Zeitsperre Feel free to redirect your PR to `conda-forge/staged-recipes`. Then I can review and merge it directly.

**Pull request merged**
