### PR TITLE
Add mock

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a recipe to build mock. Based off the recipe in conda-recipes. This is cleaned up a bit. Has some other dependencies in some cases. Also, a more recent version is used.

### CODE REVIEW

**Comment by jakirkham** [comment]
Any interest in being added as a maintainer, @dan-blanchard? Also, any thoughts on the recipe as it is?

**Comment by pelson** [comment]
👍

**Comment by dan-blanchard** [comment]
I realized I should have asked this earlier, but with your wonderfully fancy conda-forge setup, what does being a recipe maintainer really entail?  You've got so much automation in place that I wonder if you even have things to try to automatically bump up the templated version number and see if that just works.

**Comment by jakirkham** [comment]
> I realized I should have asked this earlier, but with your wonderfully fancy conda-forge setup, what does being a recipe maintainer really entail?

At present, with something this simple, bumping version numbers. If you want a 2.x release, we might do 2 branches. Not sure what breaks are introduced there.

> You've got so much automation in place that I wonder if you even have things to try to automatically bump up the templated version number and see if that just works.

Haha, yeah, not at present, but we're thinking about it quite a bit. See these issues and comments ( https://github.com/conda-forge/conda-forge.github.io/issues/51 ) ( https://github.com/conda-forge/conda-forge.github.io/issues/89 ) ( https://github.com/conda-forge/staged-recipes/pull/323#discussion_r59427662 ) It is also [scheduled]( https://conda-forge.hackpad.com/conda-forge-meeting-notes-copied-2YkV96cvxPG#:h=2016-04-28 ) for our next meeting (was meant to happen at the last one), which I should add everyone is invited to. While there isn't any agreement yet on *how* this happens or to what *extent* it happens, I would say there does seem to be interested in making it happen.

**Comment by pelson** [comment]
> I would say there does seem to be interested in making it happen.

Indeed. We can totally automate some of it. There will always be a need for somebody to curate, verify and merge PRs. Adding tests for failing cases when they get fixed, removing/adding dependencies etc. is always going to need some degree of maintenance, though for some of the pure python packages, this could very easily tend towards zero work.

**Comment by jakirkham** [comment]
> There will always be a need for somebody to curate, verify and merge PRs.

Definitely true. Though I bet I will do most of that here.

> Adding tests for failing cases when they get fixed...

Also, true. Particularly of more complex compiled packages. Doubting this is an issue with `mock` though.

> ...removing/adding dependencies etc. is always going to need some degree of maintenance...

Depending on how we automate version bumps, this dependency management could be automated too. Think something like `conda skeleton pypi`.

> ...though for some of the pure python packages, this could very easily tend towards zero work.

Yep. Ideally, `mock` would be one of these in the long run.

**Comment by pelson** [comment]
> Think something like conda skeleton pypi.

Oh absolutely, it is high on my mind at the moment 😉

**Pull request merged**
