### PR TITLE
Add rich-toolkit

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by synapticarbors** [comment]
required by https://github.com/conda-forge/fastapi-cli-feedstock/pull/5

**Comment by synapticarbors** [comment]
@conda-forge/help-python, ready for review!

**Review by mariusvniekerk — APPROVED** [review]

**Comment by mariusvniekerk** [comment]
Think linter wants homepage in the about

**Comment by synapticarbors** [comment]
Ok, I'll add it, although https://github.com/conda-forge/staged-recipes/pull/28451#issuecomment-2518894756 seemed to indicate that everything was satisfied and it looked like maybe the reporting out was incorrect.

**Comment by synapticarbors** [comment]
The linter doesn't seem to recognize v1 recipe usage of `python_min`

**Comment by synapticarbors** [comment]
@conda-forge/help-python can someone take a look at this? I think it should be good to merge, but the linter is complaining about what I think are false positives

**Comment by synapticarbors** [comment]
@conda-forge/help-python friendly request for a review since this has been sitting for a while and is needed for a feedstock.

**Comment by ocefpaf** [comment]
@synapticarbors Marius is a core member and approved your PR. It is OK to merge it after that. He probably did not merge b/c he was busy/forgot or on mobile phone.

**Comment by synapticarbors** [comment]
@ocefpaf -- thanks for the merge! I just have a personal policy of not merging my own PRs

**Comment by ocefpaf** [comment]
> @ocefpaf -- thanks for the merge! I just have a personal policy of not merging my own PRs

We usually don't watch approved PRs where only core members are involved. You'll have to ask for merges on zulip then.

**Pull request merged**
