### PR TITLE
Add openapi codec

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @lsetiawan.

Needed in https://github.com/conda-forge/staged-recipes/pull/7986

### CODE REVIEW

**Comment by lsetiawan** [comment]
You are so fast! Thanks!

**Comment by ocefpaf** [comment]
> You are so fast! Thanks!

Nope. I just used `conda skeleton pypi openapi-codec`.
BTW, should I put out on the hook as a maintainer here?

**Comment by lsetiawan** [comment]
Put out?

**Comment by ocefpaf** [comment]
> Put out?

Damn auto-correct! Check again :smile:

**Comment by lsetiawan** [comment]
Oh yea haha sounds good :smile:

**Comment by ocefpaf** [comment]
This is noarch and CircleCI is passing. Merging it to unlock https://github.com/conda-forge/staged-recipes/pull/7986

**Comment by lsetiawan** [comment]
Woo! It's like a game! We went through the first hoop now the final push haha :smile_cat:

**Pull request merged**
