### PR TITLE
Add recipe for editdistance-s

### PR DESCRIPTION
**Pull request by nicoddemus**
Now required by identify:

https://github.com/conda-forge/identify-feedstock/pull/84

### CODE REVIEW

**Comment by nicoddemus** [comment]
Failed with:

```
error: command '/home/conda/staged-recipes/build_artifacts/editdistance-s_1618412652079/_build_env/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
```

However the recipe does include a C compiler... any hints?

**Comment by marcelotrevisani** [comment]
I am not sure, but ``cc1plus`` should be in theory be available with the ``c++`` compilers, I added it to the recipe, lets see if it is going to fix it

**Comment by marcelotrevisani** [comment]
and looking to the code we should be installing the ``c++`` compiling, but for Linux I believe it will not make any difference

https://github.com/asottile/editdistance-s/blob/master/_editdistance.cpp#L29

**Comment by nicoddemus** [comment]
Seems to do the trick (sorry I looked at `x86_64-conda-linux-gnu-cc` and didn't realize it was a C++ compiler). 👍

**Comment by marcelotrevisani** [comment]
> Seems to do the trick (sorry I looked at `x86_64-conda-linux-gnu-cc` and didn't realize it was a C++ compiler).

The error is a bit above of that line which you sent, it was complaining about ``cc1plus``
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=303754&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=719

I believe we can remove the ``compiler('c')`` then and just let the ``cxx`` :)

**Comment by nicoddemus** [comment]
> I believe we can remove the compiler('c') then and just let the cxx :)

Let's see. 👍

**Comment by marcelotrevisani** [comment]
For some reason, it didn't trigger the CI, so I closed and reopened the PR to retrigger it

**Review by marcelotrevisani — APPROVED** [review]

**Comment by marcelotrevisani** [comment]
:tada: :tada: :tada:  everything is green, so we can merge it!
thanks for adding this project! :)

**Pull request merged**
