### PR TITLE
Add recipes required for brightway and activity-browser

### PR DESCRIPTION
**Pull request by m-rossi**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

This PR combines various requests in https://github.com/brightway-lca/brightway2/issues/47 and the PRs https://github.com/conda-forge/staged-recipes/pull/20201, https://github.com/conda-forge/staged-recipes/pull/20203, https://github.com/conda-forge/staged-recipes/pull/20208, https://github.com/conda-forge/staged-recipes/pull/20209, https://github.com/conda-forge/staged-recipes/pull/20210, https://github.com/conda-forge/staged-recipes/pull/20211 which can be closed if this PR succeeds.

### CODE REVIEW

**Comment by michaelweinold** [comment]
I agree to be a (co-)maintainer

**Comment by m-rossi** [comment]
@conda-forge/staged-recipes These recipes are ready for review!

**Comment by ocefpaf** [comment]
@m-rossi I'm going to be super honest with your here. While submitting many recipes is not against any rules and it is easier for you. The chances of getting a fast review is reduced. This is the second time I get here, see all those recipes, and close the tab b/c I'm too busy for this at the moment. If you break this up, many staged-recipes reviewers can help you by reviewing the pieces.

**Comment by m-rossi** [comment]
@ocefpaf No problem, then I will submit PRs for the individual recipes. Thanks for the honesty!

**Pull request closed without merging**
