### PR TITLE
Adding r-rjdbc

### PR DESCRIPTION
**Pull request by fhoehle**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by fhoehle** [comment]
@conda-forge/help-r ready to review.

**Comment by xhochy** [comment]
@fhoehle Can you use the `conda_r_skeleton_helper` to create this recipe?

**Comment by xhochy** [comment]
See https://github.com/bgruening/conda_r_skeleton_helper

**Comment by fhoehle** [comment]
> @fhoehle Can you use the `conda_r_skeleton_helper` to create this recipe?

Thanks for remembering me, done.

**Comment by cbrueffer** [comment]
Noticed too late that the recipe was in the top level, not the `recipes` directory. PR https://github.com/conda-forge/staged-recipes/pull/10290 moves it to the proper place.

**Comment by fhoehle** [comment]
> Noticed too late that the recipe was in the top level, not the `recipes` directory. PR #10290 moves it to the proper place.

@cbrueffer thanks! Sorry for the mess.

**Comment by cbrueffer** [comment]
No worries @fhoehle , this is a learning opportunity for both of us :-D

**Pull request merged**
