### PR TITLE
Adding decoupler

### PR DESCRIPTION
**Pull request by PauBadiaM**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by PauBadiaM** [comment]
Hi @conda-forge/bioconda-recipes , I am aware that decoupler is already in `bioconda` but we want to keep maintaining it in `conda-forge` instead, is that okay?

**Comment by PauBadiaM** [comment]
@conda-forge/help-python, ready for review!

**Comment by PauBadiaM** [comment]
@conda-forge/help-python, ready for review, thank you for your time

**Review by synapticarbors — COMMENTED** [review]
I'm happy to merge this, but I'm not sure if we should be waiting on a formal response from @conda-forge/bioconda-recipes

**Comment by PauBadiaM** [comment]
Hi @synapticarbors, since there is no response, would it be possible to still merge? Thanks!

**Comment by xhochy** [comment]
I think the best is to name this package `python-decoupler` to not conflict with bioconda.

**Comment by PauBadiaM** [comment]
I'd rather keep the same name, if possible. Couldn't we instead just stop updating the one in bioconda? Something like scanpy did: [bioconda](https://anaconda.org/bioconda/scanpy), [conda-forge](https://anaconda.org/conda-forge/scanpy).

**Comment by xhochy** [comment]
I'll need someone else to chime in/review then.

**Comment by PauBadiaM** [comment]
Hi @conda-forge/bioconda-recipes , could I get some help/points on how to have a different conda-forge name than the pypi one? Thanks!

**Comment by PauBadiaM** [comment]
Hi @xhochy, @synapticarbors, @conda-forge/help-python, finally managed to make it work with a different name, ready for review, thank you for your time.

**Comment by PauBadiaM** [comment]
Hi @conda-forge/help-python, sorry to ask this but could please someone else review this? It has been months since I've opened this PR. Many thanks!

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks, we take care about the Bioconda side.

**Pull request merged**
