### PR TITLE
Save travis-token in create_feedstocks.py

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
IIRC we do write it out after the first time we acquire it from Travis CI. The thing is getting the token itself is expensive. So we want it stored securely for multiple session use.

**Comment by isuruf** [comment]
> IIRC we do write it out after the first time we acquire it from Travis CI. 

Where?

**Comment by jakirkham** [comment]
Sorry was on my phone earlier.

ref: https://github.com/conda-forge/conda-smithy/blob/v3.1.4/conda_smithy/ci_register.py#L54-L69

**Comment by jakirkham** [comment]
Would almost suggest caching this value, but the cache is likely insecure.

**Pull request closed without merging**
