### PR TITLE
Add Sanic-HTTPAuth v0.2.0

### PR DESCRIPTION
**Pull request by patricksnape**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by patricksnape** [comment]
@conda-forge/python This is a bit of a weird one - this package packages things a bit strangely and using setuptools py_modules to install two modules that are not under a shared namespace. One of them fails to import which is what's confusing me.

Any ideas?

**Comment by patricksnape** [comment]
@ocefpaf Not sure if you've ever seen an issue with setuptools and this py_modules stuff before? I've never seen it used in the wild until now - pip works locally though

**Comment by ocefpaf** [comment]
> @ocefpaf Not sure if you've ever seen an issue with setuptools and this py_modules stuff before? I've never seen it used in the wild until now - pip works locally though

I'm not sure what is going on, probably some issues with new pyproject.toml and conda. Falling back to old setup.py works but we should investigate why it failed in the first place.

**Comment by ocefpaf** [comment]
Sorry @patricksnape! I forgot to merge it!

**Pull request merged**
