### PR TITLE
Add r kml3d

### PR DESCRIPTION
**Pull request by leej3**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mfansler** [comment]
@leej3 I believe the preferred thing to do here is *not to skip* the **osx** build; rather, just let that build fail. And point out to the reviewer(s) that this is a `noarch` packages and the failure is a missing dependency. 

When the package goes to feedstock, it will only build on **linux-64** and then publish as **noarch**.  Those on **osx** will see it and it will technically be compatible, just that they can't solve the `r-kml` dependency.

**Comment by leej3** [comment]
Thanks for the the explanation @mfansler; I wasn't sure how to deal with that. This is ready for review then (@conda-forge/help-r)

**Review by dbast — APPROVED** [review]

**Comment by dbast** [comment]
exactly as explained by @mfansler

**Comment by dbast** [comment]
thanks

**Pull request merged**
