### PR TITLE
Add compas_fab recipe

### PR DESCRIPTION
**Pull request by gonzalocasas**
A package for robotic fabrication that builds upon [COMPAS Framework](https://compas-dev.github.io/) ([already in conda](https://anaconda.org/conda-forge/compas)). The strict version pinning on the `compas` dependency is due to the fact that compas itself is still pre-1.0 release and the API is still very much in motion, with regular breaking changes.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes -- Something looks off with the build of this package and I'm not immediately spotting it. All of the builds are erroring with messages like: "invalid recipe dir: /home/conda/conda-recipes/compas_fab - skipping"

**Comment by pkgw** [comment]
Wild guess, but maybe the package requirements as currently stated are unsatisfiable and so the render step can't find any actual versions of the package to build?

**Comment by synapticarbors** [comment]
@pkgw -- it looks like you're correct that `compass` and `roslibpy` are missing so will need to be added. I just don't remember seeing an error message like this and I thought missing packages typically had a more explicit message.

@gonzalocasas -- You're going to have to add `compass` and `roslibpy` (you can do it in this same PR) before this will build.

**Comment by gonzalocasas** [comment]
@synapticarbors ah! `roslibpy` is not on conda, only pip. That is likely the problem, right? I'll prepare a conda recipe for `roslibpy` then...!

**Comment by gonzalocasas** [comment]
Alright, the problem was a space between the operator (`==` or `>=`) and the version number. `conda-verify` did show it as an error. Now the recipes are building everything required, but there's an error on one of the imports. I'll fix and hopefully this will finally succeed building.

**Comment by gonzalocasas** [comment]
Thanks @synapticarbors !

**Pull request merged**
