### PR TITLE
Add r-profvis

### PR DESCRIPTION
**Pull request by halldc**
Adding a recipe for the [profvis](https://cran.r-project.org/web/packages/profvis/index.html) R package. This was created using the [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper).

This is relevant to @conda-forge/help-r.

### CODE REVIEW

**Comment by halldc** [comment]
@bgruening I'm not sure why this failed the Azure Windows check, but the Appveyor check passed just fine. What are these Azure CI checks doing?

**Comment by chrisburr** [comment]
@halldc The Azure Windows test can be ignored for now as it's know to be broken.

Can you try and move to using the newer syntax for specifying the compiler and toolchain? (I think you can just remove all the lines containing `{{native}}` and `{{posix}}`.)

**Comment by dbast** [comment]
@chrisburr This PR was fully generated with the current R skeleton helper and afaik the linter can be ignored for R packages for the time being ...

**Comment by dbast** [comment]
@halldc Reverting your last commit should make it build again.

**Pull request merged**
