### PR TITLE
GDAL 1.11.4

### PR DESCRIPTION
**Pull request by ocefpaf**
Fiona is broken in the default channel because it installs GDAL 2.0, which fiona is not ready to use yet.

See https://github.com/Toblerity/Fiona/issues/239 and https://github.com/ContinuumIO/anaconda-issues/issues/401.

Note to self: rasterio seems to be OK with GDAL 2.0 https://github.com/mapbox/rasterio/pull/505.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Travis is failing due to:

> The log length has exceeded the limit of 4 MB 

Even in a feedstock by itself gdal will still go over the 4 MB limit, unless we reduce the build matrix to only one Python/NumPy version at a time :unamused:

**Comment by pelson** [comment]
> Even in a feedstock by itself gdal will still go over the 4 MB limit, unless we reduce the build matrix to only one Python/NumPy version at a time :unamused:

Ouch. I thought there was a way of building GDAL without its python bindings, and then providing python bindings independently. Is that an option?

**Comment by ocefpaf** [comment]
> I thought there was a way of building GDAL without its python bindings, and then providing python bindings independently.

There is.  I was avoiding it for two reason:  (a) laziness and (b) to avoid dealing with naming things.

I can solve (a) with :coffee:, (b) on the other hand, is more complicated.

I don't like the fact that the default channel names gdal (the executable files, the non-python bindings, and the libs) `libgdal` while naming calls `gdal` the python bindings only.  However, for consistent, I guess we'll have do the same.  Ideas? (Maybe naming the former `gdal`, the latter `python-gdal` and break consistency with the default channel? Not sure if that is the better way to go.)

>  Is that an option?

I am testing that right now.  I will send the PR probably later today.

**Comment by jjhelmus** [comment]
Could you redirect some of the build output (say the results of ./configure and make install) to a file to limit the log size?  These logs could be made available as artifacts if they are really needed.

**Comment by ocefpaf** [comment]
> Could you redirect some of the build output (say the results of ./configure and make install) to a file to limit the log size?

I tried that before and I think that Travis-CI by passes the redirection. (I read somewhere that there is a way to do that using some ruby config magic, but I am not sure it is worth it.)

I am closing #51 and I will try again here. Even without the python bindings the logs/timeout still blow Travis-CI out. So, since re-starting Travis-CI is inevitable, I believe that keeping one recipe for gdal is the way to go.

**Comment by pelson** [comment]
> I believe that keeping one recipe for gdal is the way to go

But then we have a *huge* install for py27, py34 and py35. Surely we are better off with one *huge* install and 3 little py27, 34, and 35 distributions for the py bindings?

**Comment by ocefpaf** [comment]
> But then we have a huge install for py27, py34 and py35. Surely we are better off with one huge install and 3 little py27, 34, and 35 distributions for the py bindings?

Yes, the download is big... The main reason I went that route is to do the same as the `osgeo` channel (the most popular channel for gdal), and because I failed miserably to build a `libgdal` only on Windows.

I kept getting a `Hint: libgdal has unsatisfiable dependencies (see 'conda info libgdal')` even though all dependencies were consistent with each other and I could install the "broken" tarball (and it worked!).

I will try again...

**Comment by pelson** [comment]
I've just remembered about the fact we need to compile for each VS *anyway* (see https://github.com/conda-forge/staged-recipes/pull/79#issuecomment-193316623) so this approach is fine! :+1:

**Comment by ocefpaf** [comment]
>  so this approach is fine!

OK. So, unless you have a suggestion for the AppVeyor [failure](https://ci.appveyor.com/project/pelson/staged-recipes/build/1.0.327/job/gbjkh6d986y4abse) I will skip Windows+PY35 and end this. (My computer handle another gdal build :wink:)

**Comment by pelson** [comment]
```
...
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition 
c:\miniconda\conda-bld\work\gdal-1.11.4\port\cpl_config.h(20): note: see previous definition of 'snprintf' 
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration 
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.EXE"' : return code '0x2'
Stop.
 
C:\Miniconda\conda-bld\work\gdal-1.11.4>if errorlevel 1 exit 1 
```

http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti

Looks like a patch may be necessary (unless it has already been fixed in GDAL upstream)

**Comment by ocefpaf** [comment]
> Looks like a patch may be necessary (unless it has already been fixed in GDAL upstream)

gdal 1.11.4 is the latest on the 1.X series (release in January 2016 together with gdal 2.0.2). So guess it is not patched.

I will take a look at making one but, if you agree, I would like to get this merged first to get the Linux and OS X packages out there.

**Comment by pelson** [comment]
> I will take a look at making one but, if you agree, I would like to get this merged first to get the Linux and OS X packages out there.

Oh, completely! Merge as soon as you are happy - I don't need this to have 3 green ticks to move forwards. :+1: :+1: :+1: :+1: :+1:

**Comment by pelson** [comment]
P.S. For now, just skip the 3.5 build - only do it when we have a need? Maybe just capture the information in an issue on the feedstock...

**Comment by ocefpaf** [comment]
> P.S. For now, just skip the 3.5 build - only do it when we have a need? Maybe just capture the information in an issue on the feedstock...

Will do.

**Comment by ocefpaf** [comment]
@pelson I will keep this PR open because I realized I cannot access AppVeyor's logs for the feedstocks (For example [this](https://ci.appveyor.com/project/conda-forge/mingwpy-feedstock/branch/master) returns `Project not found or access denied.`)

PS: Can you enable AppVeyor's [rolling-builds](https://www.appveyor.com/docs/build-configuration#rolling-builds) option. I will be sending a series of tests PRs and that option will save a lot of time.

**Comment by ocefpaf** [comment]
The last commit introduces some code I "stole" from `gdal 2.0.0` that got us a little closer to compiling `gdal 1.11.4` on AppVeyor and Microsoft Visual Studio 14.0, but my googling skills are lacking and I cannot solve the last issue.

```
odbccp32.lib(dllload.obj) : error LNK2019: unresolved external symbol __vsnwprintf_s referenced in function _StringCchPrintfW
gdal111.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.EXE"' : return code '0x460'
```

**Comment by msarahan** [comment]
@ocefpaf looks like https://connect.microsoft.com/VisualStudio/feedback/details/1134693/vs-2015-ctp-5-c-vsnwprintf-s-and-other-functions-are-not-exported-in-appcrt140-dll-breaking-linkage-of-static-libraries

Not sure about a total solution, though - looks like MS needs to release a newer SDK or something.

**Comment by ocefpaf** [comment]
> Not sure about a total solution, though - looks like MS needs to release a newer SDK or something.

Yep. I guess we need to wait :unamused: 

Thanks!

**Pull request merged**
