### PR TITLE
Add dask-ml feedstock

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
If anyone has insight on the failure [here](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18092/job/khlgcrio152ukcs3#L486) I'd appreciate it.

```
TEST START: C:\bld\win-32\dask_ml-0.2.3-py27_0.tar.bz2
Deleting work directory, C:\bld\dask_ml_1508854364624\work\dask_ml-0.2.3
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-all-script.py", line 5, in <module>
    exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build_all\cli.py", line 93, in main
    b.main()
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 277, in main
    built_dist_location = self.build(meta, build_config)
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 209, in build
    conda_build.api.build(meta.meta, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1549, in build_tree
    .format(recipe) + error_str + "\n" + extra_help)
RuntimeError: Can't build {'requirements_path': u'C:\\projects\\staged-recipes\\recipes\\dask-ml\\requirements.txt', 'meta_path': u'C:\\projects\\staged-recipes\\recipes\\dask-ml\\meta.yaml', 'meta': {u'source': {u'url': u'https://pypi.io/packages/source/d/dask_ml/dask_ml-0.2.3.tar.gz', u'sha256': u'5f3c05b5e5052f3f5035516362d94f6bcf438849ba6966d621c06f41ec7ea455', u'fn': u'dask_ml-0.2.3.tar.gz'}, u'about': {u'dev_url': u'https://github.com/dask/dask-ml', u'description': u'Distributed and parallel machine learning using dask.\n', u'license': u'BSD-3-Clause', u'license_family': u'BSD', u'summary': u'Distributed and parallel machine learning using dask.', u'home': u'http://github.com/dask/dask-ml', u'license_file': u'LICENSE.txt', u'doc_url': u'http://dask-ml.readthedocs.io/'}, u'requirements': {u'run': [u'dask', u'dask-glm', u'dask-searchcv', u'dask-xgboost', u'numpy >=1.9.*', u'pandas', u'python', u'scikit-learn', u'scipy', u'setuptools', u'six', u'xgboost'], u'build': [u'python', u'toolchain', u'setuptools', u'setuptools_scm', u'cython', u'numpy 1.9.*']}, u'build': {u'number': u'0', u'script': u'python setup.py install --single-version-externally-managed --record record.txt'}, u'package': {u'version': u'0.2.3', u'name': u'dask_ml'}, u'test': {u'imports': [u'dask_ml', u'dask_ml.utils', u'dask_ml.xgboost']}, u'extra': {'final': True, u'recipe-maintainers': [u'TomAugspurger']}}, 'path': u'C:\\projects\\staged-recipes\\recipes\\dask-ml', 'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x052870B0>} due to environment creation error:
  - dask_ml 0.2.3 py27_0
  - dask-xgboost
  - xgboost
  - dask-xgboost
  - xgboost
  - xgboost
Command exited with code 1
```

Is the issue the multiple `xgboost`s in that list? I'm not sure why that would be. `dask_ml` does have a module `dask_ml.xgboost`, so a potential name conflict?

Either way, that's an optional module, so I'll try excluding it for now, and seeing if things work.

**Comment by mariusvniekerk** [comment]
typically it means that some dep you need doesn't exist

**Comment by TomAugspurger** [comment]
Ah, thanks. https://anaconda.org/conda-forge/xgboost doesn't have packages for windows. OK, I'll just leave that optional dependency out.

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18094 passed btw, though the checkmark hasn't updated here.

**Comment by TomAugspurger** [comment]
OK, Travis has finished and I think Appveyor is done, but maybe Github missed the notification that it passed since it hasn't updated here.

**Comment by jjhelmus** [comment]
LGTM.

**Comment by TomAugspurger** [comment]
Thanks!

**Comment by TomAugspurger** [comment]
Hmm, it seems like the `dask-ml` feedstock hasn't show up yet. https://github.com/conda-forge/staged-recipes/commits/master?after=63b77ac7d7aabc344a2016ac3bd0e4c2f381f293+69 removed the recipe from `staged-recipes`, but https://anaconda.org/conda-forge/dask-ml and https://github.com/conda-forge/dask-ml-feedstock don't exist yet. Is there anything I can do to debug why? Should I submit another PR with this recipe?

**Comment by TomAugspurger** [comment]
Looks like the build on master failed: https://travis-ci.org/conda-forge/staged-recipes/builds/293311604#L630

**Comment by TomAugspurger** [comment]
@jakirkham noticed that I set the wrong package name. The official project name is `dask-ml`, and it's imported as `dask_ml`.

Is it a big hassle to migrate (or delete) a repository? Should I make another PR with the correct name? Sorry for mixing this up!

**Comment by jakirkham** [comment]
np. Let's do a fresh PR to staged-recipes. That should be the easiest way to fix this.

**Pull request merged**
