### PR TITLE
Add vmtk (Vascular Modelling Toolkit)

### PR DESCRIPTION
**Pull request by ramtingh**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Review by ryanvolz — COMMENTED** [review]
See https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl for how to build against libGL on Linux.

You'll also need to rename `build.bat` to `bld.bat` to get the Windows build started.

**Comment by ramtingh** [comment]
@lassoan I'd like to have vmtk available on conda-forge for convenience/accessibility, this has been planned for a few years (vmtk/conda-recipes#2) but seems to have stalled out before. Do you think the current master branch is in a reasonable state for release? 

All that would be needed is merging the below pull request in vmtk to fix a cmake bug, and preferably tagging the current master branch
 vmtk/vmtk/pull/414

**Comment by lassoan** [comment]
Awesome, thank you! I just added a minor comment to that pull request.

Do you have experience with pip packaging, too? Is that feasible to do similarly to conda-forge? Do you build VTK in the recipe?

**Comment by ramtingh** [comment]
conda-forge is specific to the anaconda ecosystem. In this case VTK is built separately (https://github.com/conda-forge/vtk-feedstock/). I don't have much experience with pip, I can have a go at it once I'm done setting this up.

I was hoping to finish this today but I'm running into extremely strange error on windows where i get different results with identical build log and compiled files, so I'll probably finish it in the next few days and update the cmake pull request. Linux builds seem to be working fine

**Comment by ramtingh** [comment]
@conda-forge-admin, please lint

**Comment by ramtingh** [comment]
@conda-forge-admin, please ping team
Could you please have a look at if current recipe looks appropriate, I still need to update the tarball to the offical repo rather than my fork, but I don't expect any changes in the build process considering the code is identical

**Comment by ramtingh** [comment]
@conda-forge-admin, please lint

**Pull request merged**
