### PR TITLE
Add recipe for eicu-demo

### PR DESCRIPTION
**Pull request by mlondschien**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mlondschien** [comment]
@conda-forge/r @mfansler Thanks for helping with https://github.com/conda-forge/staged-recipes/pull/25650. This is the other dataset I'm interested in. This time the tarball is ~55mb.

**Comment by mlondschien** [comment]
@conda-forge/r could you have a look?

**Review by mfansler — APPROVED** [review]
@conda-forge/core this recipe satisfies our technical expectations, but I wanted to check in regarding it being a large tarball (~55MB). I'm unsure if there are any concerns with generating/hosting large artifacts. It should be noted this package doesn't have regular updates and is noarch, so the expectation would be this should only need rebuilding during R version migrations. If no issue, then this is ready to merge. Thanks for your input!

**Comment by mfansler** [comment]
I reviewed the CF documentation and couldn't find any explicit exclusion rules for size. I'll merge tomorrow unless I hear otherwise.

(feel free to ping me in case I forget!)

**Pull request merged**
