### PR TITLE
Add redis

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
@conda-forge/help-c-cpp it would be great to get help with a couple of questions:

* the `redis-py` package was originally named `redis` and so had a `redis-feedstock` which I think is causing the linting error - is there any way to work around this? 
* it seems that `redis` builds a [number of dependencies](https://github.com/redis/redis/tree/unstable/deps) (some of which contain non-standard changes) and doesn't give the option to link against existing libraries. Would the Makefile need to be patched to target C-F deps or should `redis` continue to build its own deps?

**Comment by SimonBoothroyd** [comment]
> it seems that redis builds a number of dependencies (some of which contain non-standard changes) and doesn't give the option to link against existing libraries. Would the Makefile need to be patched to target C-F deps or should redis continue to build its own deps?

Per @wolfv's comments on gitter it seems we should be safe not to do any patching here.

**Comment by wolfv** [comment]
Just curious -- why go back to an older version?
Do you know what's going on with these link errors on macOS?

**Comment by wolfv** [comment]
PS: this is the homebrew recipe: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/redis.rb

**Comment by SimonBoothroyd** [comment]
> Just curious -- why go back to an older version?

I was seeing some build errors:

```
networking.c:3438:5: error: builtin functions must be directly called
    atomicSetWithSync(io_threads_pending[i], count);
    ^
./atomicvar.h:150:56: note: expanded from macro 'atomicSetWithSync'
    while(!__sync_bool_compare_and_swap(&var,var,value,__sync_synchronize)); \
                                                       ^
```

and was curious if dropping back to the old version would be an easy fix as the atomic operations are new in 6.x.x as far as I can tell!

It seems like the older versions have a different linking issues however...

It's strange as `homebrew` doesn't seem to have build issues. Could this be caused by clang vs gcc differences?

**Comment by wolfv** [comment]
a difference could be the required macOS SDK version... although I googled a bit and couldn't find anything. conda-forge uses a pretty old macOS SDK to be compatible with old macOS versions -- but that can be configured.

**Comment by SimonBoothroyd** [comment]
Ah I think you're absolutely right - it seems `stdatomic` support [wasn't included until 10.12](https://stackoverflow.com/questions/26440606/xcode-and-c11-stdatomic-h)

**Comment by SimonBoothroyd** [comment]
Thanks @wolfv - that as well as forcing C11 on OSX seems to resolve the build issues. 

Running the make tests on linux currently raise an unexpected exception, however, looking over the `redis` GH issues it seems that the test suite can be a bit flaky so I think this is probably fine for now?

@conda-forge/help-c-cpp this should be ready for review

**Comment by wolfv** [comment]
@SimonBoothroyd when I looked at the Fedora recipe it seemed that they move some redis configuration files to certain places. Also in homebrew. Did you have a look at that?

Otherwise looks good to me (except for the lint!)

**Comment by SimonBoothroyd** [comment]
Ah great catch - those should be added in c640b99! 

> Otherwise looks good to me (except for the lint!)

@wolfv do you have any suggestions for how to move forward with the lint issues? Presumably the [archived existing feedstock](https://github.com/conda-forge/redis-feedstock) needs to be removed / renamed by one of the C-F team?

**Comment by SimonBoothroyd** [comment]
@conda-forge/help-c-cpp the linter seems to be happy now - this should be ready for review!

**Comment by SimonBoothroyd** [comment]
Thanks so much @wolfv!

**Pull request merged**
