### PR TITLE
Add r-httpgd

### PR DESCRIPTION
**Pull request by nsandau**
Recipe generated with conda_r_skeleton_helper

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mfansler** [comment]
Had a few minutes waiting for my recipe to render, so I peeked at the failed OSX build. Looks like [`ld` couldn't `-lgobject-2.0`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=379857&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=1335). This likely means you need to add `libglib` to your requirements (host and run) for `[osx]` builds.

**Comment by nsandau** [comment]
Thanks, @mfansler! 
I had to add glib to make it build as per this issue in the glib-feedstock: conda-forge/glib-feedstock#104 

Now I just have to get the windows build to work.

**Comment by nsandau** [comment]
@conda-forge/help-r

I am having trouble compiling this package on Windows. 
The developer suggests using an updated C++ compiler that supports nested namespaces. 
Is that possible?

Thank you!

**Comment by mfansler** [comment]
The CI shows it's still on Linux image compiling with `gcc`. I think you also need a `conda-forge.yml` to get a native Windows instance and compile with `vs2019`. See [Knowledge Base](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-vs2019).

**Comment by nsandau** [comment]
@mfansler, thank you for your comment. 
I tried adding a conda-forge.yml file with the contents as specified in the documentation but I still get the same error. 
Any suggestions for how to proceed from here?

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by nsandau** [comment]
@conda-forge-admin please rerender

**Comment by nsandau** [comment]
@conda-forge-admin, please rerender

**Comment by nsandau** [comment]
@conda-forge-admin please rerender

**Comment by nsandau** [comment]
@mfansler, thank you for your suggestions. 

I tried triggering a rerender a few times throughout the day but it doesn't seem to respond to me either?

**Comment by nsandau** [comment]
@conda-forge-admin, please restart ci

**Comment by nsandau** [comment]
I think I have figured out the issue.
The httpgd package uses Rccp which requires the g++ compiler to be used.
However, the m2w64 stack is currently not being maintained (https://github.com/conda-forge/toolchain-feedstock/issues/60) and therefore not updated to a version that supports nested namespaces.  
So the only solution I can see right now is to skip the windows build until a new version of g++ becomes available?

**Comment by nsandau** [comment]
@conda-forge/help-r ready for review

**Comment by mfansler** [comment]
@nsandau While I don't think Rcpp is the issue, I think it's fine to skip the **win-64** build for now and maybe revisit it in the feedstock.

@conda-forge/staged-recipes please review

**Comment by nsandau** [comment]
@conda-forge-admin, please ping team

**Comment by dbast** [comment]
Thanks!

**Pull request merged**
