### PR TITLE
Add recipe for mypy-boto3-redshift-data

### PR DESCRIPTION
**Pull request by xylar**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge/help-python, this is ready to review.

A few notes:
* I have followed the naming convention on pypi (https://pypi.org/project/mypy-boto3-redshift-data/) but there are other feedstocks on conda-forge using underscores instead of dashes (e.g. https://github.com/conda-forge/mypy_boto3_sqs-feedstock).  My preference is to stick with the pypi convention nonetheless.
* The pypi package doesn't explicitly depend on `boto3` but that seems like a bug.  Other `mpypy_boto3_*` packages on conda-forge also depend on `boto3` (see the same example above).

**Comment by BastianZim** [comment]
> I have followed the naming convention on pypi (https://pypi.org/project/mypy-boto3-redshift-data/) but there are other feedstocks on conda-forge using underscores instead of dashes (e.g. https://github.com/conda-forge/mypy_boto3_sqs-feedstock). My preference is to stick with the pypi convention nonetheless.

That decision is still ongoing but your choice is fine. :)

**Comment by BastianZim** [comment]
> The pypi package doesn't explicitly depend on boto3 but that seems like a bug. Other mpypy_boto3_* packages on conda-forge also depend on boto3 (see the same example above).

That is mentioned in the readme: https://github.com/vemel/mypy_boto3_builder#locally But yes it should be listed in the setup.py as well.

**Comment by xylar** [comment]
@BastianZim, thanks for your comments and for merging.

**Pull request merged**
