### PR TITLE
Add coin-or-bonmin

### PR DESCRIPTION
**Pull request by jschueller**
Adds the following packages:
- coin-or-bcp
- coin-or-bonmin
- coin-or-cbc -> replaces existing coincbc
- coin-or-cgl
- coin-or-clp
- coin-or-coinutils 
- coin-or-mp -> replaces existing coinmp
- coin-or-osi
- coin-or-vol

Note that every package is split: the existing coincbc and coinmp bundles all required sub-packages, so coincbc and coinmp already conflict each other.
The ipopt package also comes from coin-or but I was reluctant to rename it as was widely used by other packages.
cc @bgruening @scopatz @gidden @whart222 @jjhelmus

win support could be investigated (later, in feedstocks) with
https://github.com/ycollet/coinor-cmake

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by scopatz** [comment]
this seems to be totally separate from the other coin package that already exists.

**Comment by jschueller** [comment]
yes, it renames coincbc and coinmp

**Comment by jschueller** [comment]
@scopatz First I dont want the package to clobber each other, then I dont know if they sync properly their subprojects bundles across each projects for these clobbering packages to work properly together.

**Comment by scopatz** [comment]
My question is, "Does this duplicate the libraries in the `coincbc` package that is already on conda-forge?"  I suspect the answer is yes, which is why my next question "why not just use that package?"

**Comment by jschueller** [comment]
yes, it has all that coincbc, but I preferred to use their packages names (look for the rpms)

an alternative is to use the existing coinxxx naming pattern, then I would first submit the packages that cbc depends on, wire cbc to them, them submit the rest

**Comment by scopatz** [comment]
I think this might be better as a PR into the existing coincbc repo, adding multiple outputs to a single recipe than making a tone of new feedstocks.

**Pull request closed without merging**
