### PR TITLE
Use GitHub releases rather than archives

### PR DESCRIPTION
**Pull request by jan-janssen**
Based on https://github.com/easybuilders/easybuild-easyconfigs/issues/5151

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge/core Can you take a look at this?

**Comment by mbargull** [comment]
IMHO, we should have both, `releases` as well as `archive`, in there.
We should tell people to prefer `releases` if they are available (they often are not!) and use `archive` if not.

**Comment by jan-janssen** [comment]
@conda-forge/staged-recipes Can you merge this?

**Comment by scopatz** [comment]
Thanks @jan-janssen!

**Pull request merged**
