### PR TITLE
Add r-climate4r.value package

### PR DESCRIPTION
**Pull request by cofinoa**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dbast** [comment]
@cofinoa Is this the last package of the climate4r series?

**Comment by cofinoa** [comment]
@dbast, yes this is the last one.

**Comment by cofinoa** [comment]
@conda-forge/help-r, please review and merge.

**Comment by cofinoa** [comment]
@dbast, sorry I missed this one #19039 

Thank you

**Comment by dbast** [comment]
@cofinoa Ok. Good to know! The climate4r packages are know after 2 previous attempts the biggest set of non-cran R packages on conda-forge. The recipes are all fine or have been updated to be so. The R code within the packages could benefit from being contributed to CRAN, as CRAN provides lots of QA feedback which helps to improve the code/packages.

**Pull request merged**
