### PR TITLE
Add recipe for pyvirtualdisplay, pytest-xvfb and qt_style_sheet_inspector

### PR DESCRIPTION
**Pull request by prusse-martin**

### CODE REVIEW

**Comment by prusse-martin** [comment]
Unfortunately the build is failing because the packages are being constructed in this order:

1. `pyvirtualdisplay`
2. `qt_style_sheet_inspector`
3. `pytest-xvfb`

And the correct order should be:

1. `pyvirtualdisplay`
2. `pytest-xvfb`
3. `qt_style_sheet_inspector`

Because `pytest-xvfb` is *test* dependency of `qt_style_sheet_inspector`. 

Is there something else that must be done with the recipes for them to be built in the correct order? Should I open separate PRs for the libraries?

**Comment by prusse-martin** [comment]
cc @nicoddemus

**Comment by ReimarBauer** [comment]
My last version did successfully build 

https://github.com/conda-forge/staged-recipes/pull/3005

**Comment by nicoddemus** [comment]
Thanks @ReimarBauer. As soon as #3005 merges this recipe can be updated to remove `pyvirtualdisplay`.

**Pull request closed without merging**
