### PR TITLE
add Cockroach

### PR DESCRIPTION
**Pull request by rluria14**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rluria14** [comment]
@conda-forge/help-go @sodre Cannot get to build on any platform. Running into an error with one of the cdeps `jemalloc` --> `error: redefinition of 'aligned_alloc'` on linux. Also added a patch to try and deal with the errors on osx. 

Can you provide some help on this?

**Comment by rluria14** [comment]
@conda-forge/help-go @sodre please review when possible. thanks!

**Comment by mwilson8** [comment]
I also tried to build this; had no issue building locally from source but encountered problems when testing within staged-recipes docker build. 
> @conda-forge/help-go @sodre please review when possible. thanks!
Re-ping @conda-forge/help-go @sodre

**Comment by rluria14** [comment]
> I also tried to build this; had no issue building locally from source but encountered problems when testing within staged-recipes docker build.
> 
> > @conda-forge/help-go @sodre please review when possible. thanks!
> 
> Re-ping @conda-forge/help-go @sodre

@conda-forge/help-c-cpp there are also a slew of c-deps submodules included that will need patching.

**Pull request closed without merging**
