### PR TITLE
Add pycromanager recipe

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- ~[ ] If static libraries are linked in, the license of the static library is packaged.~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by goanpeca** [comment]
@henrypinkard do you want to be added as a maintainer?

**Comment by henrypinkard** [comment]
Yes please. Thanks for doing this!

**Comment by henrypinkard** [comment]
What do I actually have to do to maintain it?

**Comment by goanpeca** [comment]
>What do I actually have to do to maintain it?

Whenever there is a new pypi release, an PR will be created automatically. Similar to [this one](https://github.com/conda-forge/napari-feedstock/pull/41). 

The maintenance is making sure the recipe is up to date, which means (usually) keeping the run dependencies in sync.

**Comment by goanpeca** [comment]
This one is ready for review @conda-forge/staged-recipes

**Comment by henrypinkard** [comment]
Yes it works via ZMQ and yes there are java deps at runtime on the other side of the ZMQ bridge. People are only using this in practice right now after manually installing a corresponding application that has all the java deps

**Comment by jaimergp** [comment]
Perfect, thanks!

**Comment by henrypinkard** [comment]
Thanks for adding!

**Pull request merged**
