### PR TITLE
WIP: Add historydict

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
@jakirkham This one seems to be failing in the same way on python 3.5 on windows as #663... methinks something else is afoot

**Comment by jakirkham** [comment]
Yep, you're right. See this [comment]( https://github.com/conda-forge/staged-recipes/issues/666#issuecomment-221125814 ) for a workaround.

**Comment by ericdill** [comment]
This is waiting on Nikea/historydict#28 to be merged and then a new tag made and then I will update this recipe to use that new tag

**Comment by jakirkham** [comment]
If you need to use a patch from that PR for the near term, that is totally ok.

**Comment by ericdill** [comment]
I mean it is one of our projects, so I just need a code review.  Shouldn't take too long

**Comment by ericdill** [comment]
@ocefpaf @jakirkham historydict was tagged and this recipe has been verison bumped to reflect that. This is ready to go, could you give it another review?

**Comment by ericdill** [comment]
Thanks!

**Comment by jakirkham** [comment]
Now it's not WIP. 😉

**Pull request merged**
