### PR TITLE
add R packages

### PR DESCRIPTION
**Pull request by rvalieris**
this PR add a few missing packages that are dependencies for [Seurat](https://cran.r-project.org/web/packages/Seurat/index.html)

ping @bgruening , @daler, @johanneskoester  ( I added you as maintainers )

### CODE REVIEW

**Comment by bgruening** [comment]
@rvalieris can it be that you really need to depend on some X libraries?
https://groups.google.com/a/continuum.io/forum/#!topic/conda/LHeifquVyOo

**Comment by rvalieris** [comment]
I am not sure, doesnt look like it links with any X lib:
```
$ ldd libs/SDMTools.so
	linux-vdso.so.1 (0x00007ffc06cf5000)
	libR.so => /usr/lib/R/lib/libR.so (0x00007f1b8b16d000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f1b8adb5000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f1b8ab5f000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f1b8a813000)
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f1b8a5c5000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f1b8a352000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f1b8a12c000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f1b89f1c000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f1b89d05000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f1b89afd000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1b898f9000)
	libicuuc.so.60 => /usr/lib/libicuuc.so.60 (0x00007f1b89540000)
	libicui18n.so.60 => /usr/lib/libicui18n.so.60 (0x00007f1b8909d000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f1b88e6f000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1b88c51000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f1b8b9a5000)
	libgfortran.so.4 => /usr/lib/libgfortran.so.4 (0x00007f1b88875000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f1b8863d000)
	libicudata.so.60 => /usr/lib/libicudata.so.60 (0x00007f1b86a95000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f1b8670e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1b864f7000)
	libquadmath.so.0 => /usr/lib/../lib/libquadmath.so.0 (0x00007f1b862b7000)
	libtinfo.so.6 => /usr/lib/libtinfo.so.6 (0x00007f1b8608b000)
```

**Comment by rvalieris** [comment]
so... funny story, there is a bug on patchelf... https://github.com/NixOS/patchelf/issues/45

**Comment by rvalieris** [comment]
looks like the travis build finally completed !

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
