### PR TITLE
added a simple script for getting the sha256 of a file. 

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
Pretty trivial, but I spent WAY too much time getting this to work right just now. So I thought it would be good to make it available.

This is probably not the right place for it -- but it would be nice if folks building recipes could find it.

Do we need a conda-forge-utils package???

### CODE REVIEW

**Comment by jakirkham** [comment]
Can add `[skip lint]` or `[lint skip]` to your commit message to get rid of that annoying error.

**Comment by jakirkham** [comment]
Anyone have thoughts on this?

cc @conda-forge/core

**Comment by mwcraig** [comment]
The idea seems fine. Instead of a script, though, how about adding the guts of this to the README in the section on generating checksums? Seems like the instructions boil down to:

```python
import hashlib
print(hashlib.sha256(open('my_source_package.tgz', 'rb').read()).hexdigest())
```

**Comment by scopatz** [comment]
For what it is worth, this is the xonsh alias I use for getting sha256s from github

```
# sha256 conda forge
def _shatar(args, stdin=None):
    oldpwd = $PWD
    cd /tmp
    curl -L -O @("https://github.com/{0}/{1}/archive/{2}.tar.gz".format(*args))
    sha, _ = $(sha256sum @('{}.tar.gz'.format(args[2]))).split()
    print(sha)
    cd @(oldpwd)

aliases['shatar'] = _shatar
```

**Comment by ChrisBarker-NOAA** [comment]
For what it is worth, this is the xonsh alias I use for getting sha256s
from github

Hmm -/ if I read that right, it's downloading the hash from github itself.
So it will always match the one on gitHub.

But if we are being pedantic about security--  don't you want compute the
has yourself against the actual file you have tested?

Just in case gitHub got hacked?

Granted, the hack would have to happen at just the right moment for this to
be an issue..

-CHB


# sha256 conda forge
def _shatar(args, stdin=None):
    oldpwd = $PWD
    cd /tmp
    curl -L -O @("https://github.com/{0}/{1}/archive/{2}.tar.gz".format(*args))
    sha, _ = $(sha256sum @('{}.tar.gz'.format(args[2]))).split()
    print(sha)
    cd @(oldpwd)

aliases['shatar'] = _shatar

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/staged-recipes/pull/1097#issuecomment-254060927>,
or mute the thread

**Comment by ocefpaf** [comment]
Closing as "stale."

**Pull request closed without merging**
