### PR TITLE
Add CRAN R package esaBcv.

### PR DESCRIPTION
**Pull request by jdblischak**
CRAN R package [esaBcv](https://cran.r-project.org/package=esaBcv). Recipe created with conda-build 3.16.3 and [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper).

### CODE REVIEW

**Comment by jdblischak** [comment]
The AppVeyor build [failed](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20659234#L791) during the test phase because it couldn't find the R executable:

```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\bin\R" -e "library('esaBcv')" 
The system cannot find the path specified.
```

**Comment by bgruening** [comment]
@jdblischak I think we can simply remove the `     - {{posix}}zip               # [win] ` this should not be needed anymore.

**Comment by jdblischak** [comment]
> I think we can simply remove the - {{posix}}zip # [win] this should not be needed anymore.

@bgruening I see. So the linter only cares about selectors in the requirements. Thanks for the fix!

Unfortunately it is still failing for some reason on Windows.

**Comment by bgruening** [comment]
@jdblischak any idea why the resolution of `"\"%R%\"`is returning different values depending on `noarch`?

**Comment by jdblischak** [comment]
> any idea why the resolution of \"%R%\"is returning different values depending on noarch?

@bgruening Short answer: no

Long answer: Sorry, I don't understand what you are referring to. Do you mean the `%R%` in `bld.bat`? It looks the same to me for both types of recipes. For example, in r-generics current noarch build, it is:

```
(%BUILD_PREFIX%) %SRC_DIR%>"%BUILD_PREFIX%\Scripts\R.exe" CMD INSTALL --build . 
```

https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20877203#L676

But in the earlier build when noarch was removed, it was the same:

```
(%BUILD_PREFIX%) %SRC_DIR%>"%BUILD_PREFIX%\Scripts\R.exe" CMD INSTALL --build .
```

https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20874330#L681

**Comment by jdblischak** [comment]
@bgruening We need to make a decision on how to proceed with noarch R recipes. They are going to fail on AppVeyor, but I think this is fine. Is it ok to go ahead and merge noarch R recipes with failing AppVeyor builds?

**Comment by bgruening** [comment]
I'm fine with merging and fixing on the feedstock if this is a problem.

Btw. this error here is different from the r-generics. For some reason you get this path `%SRC_DIR%>"%PREFIX%\bin\R" -e "library('generics')"` for the noarch build. In contrast to `%SRC_DIR%>"%PREFIX%\Scripts\R" -e "library('generics')"` for non-noarch builds.

**Comment by jdblischak** [comment]
> I'm fine with merging and fixing on the feedstock if this is a problem.

OK. I'll merge a few and monitor the feedstocks. I'll let you know how it goes.

> Btw. this error here is different from the r-generics. For some reason you get this path %SRC_DIR%>"%PREFIX%\bin\R" -e "library('generics')" for the noarch build. In contrast to %SRC_DIR%>"%PREFIX%\Scripts\R" -e "library('generics')" for non-noarch builds.

I apologize if I'm being dense, but I still can't figure out what you are referring to. Would you be able to send a link to the line in the AppVeyor log where you observed `%SRC_DIR%>"%PREFIX%\bin\R" -e "library('generics')"`?

**Comment by bgruening** [comment]
Of course: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20877203#L810

**Comment by jdblischak** [comment]
> OK. I'll merge a few and monitor the feedstocks. I'll let you know how it goes.

Quick update: r-esabcv and r-xmlparsedata were both successfully packaged after merging.

> Of course: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20877203#L810

Thanks! Now I see. When the recipe is noarch, it fails with during the test phase (my problem was that I was looking at the build phase):

```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\bin\R" -e "library('generics')" 
The system cannot find the path specified.
```

And if the recipe is not noarch, it passes the test with:

```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\Scripts\R.exe" -e "library('generics')" 
```

like here: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20874330#L811

This is really strange. They both set the same value for `"R"` at the beginning:

noarch: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20877203#L309
arch: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20874330#L314

They both build the package using this version of R:

noarch: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20877203#L676
arch: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20874330#L681

But then after the recipe fails to find `zip`, the noarch package then goes on to use the wrong version.

https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/20877203#L719

So I'm not sure what is causing it.

**Comment by bgruening** [comment]
Jupp, I'm super confused about this as well.

**Pull request merged**
