### PR TITLE
R multinet

### PR DESCRIPTION
**Pull request by agcopenhaver**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vend other packages
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dbast** [comment]
@agcopenhaver What are you trying to do?

To bring this recipe it should be enough:
* One commit created with the output of https://github.com/bgruening/conda_r_skeleton_helper 
* One commit with `skip: True  # [win]` after seeing the windows CI builds fail due to compilers being too old for C++14 (Makewars.win patching does not solve this).

(the osx build seems to fail due to other not related issues)

Would you be fine, if the package would be not available for windows?

**Comment by agcopenhaver** [comment]
something is wrong with clang

**Comment by agcopenhaver** [comment]
> @agcopenhaver What are you trying to do?
> 
> To bring this recipe it should be enough:
> 
> * One commit created with the output of https://github.com/bgruening/conda_r_skeleton_helper
> * One commit with `skip: True  # [win]` after seeing the windows CI builds fail due to compilers being too old for C++14 (Makewars.win patching does not solve this).
> 
> (the osx build seems to fail due to other not related issues)
> 
> Would you be fine, if the package would be not available for windows?

@dbast in regards to building for windows, is this a situation where we just wait for new compilers to become available or is there anything I can do as a maintainer?

**Comment by dbast** [comment]
Good question. Afaik for R recipes an update of the m2w64-toolchain and thus of m2w64-gcc etc. would be required.

**Comment by agcopenhaver** [comment]
Thanks @dbast

**Pull request merged**
