### PR TITLE
Adding XStatic-Font-Awesome 

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
Oh, no, another setuptools issue

**Comment by BastianZim** [comment]
Can you try it again with the newest setup tools and re-run the CI?

**Comment by ReimarBauer** [comment]
Hmm, locally in a recent conda environment, when I install it by pip it is not crashing

```
(denv) reimar@infinity:~$ pip install xstatic-font-awesome
Collecting xstatic-font-awesome
  Downloading XStatic_Font_Awesome-6.2.1.1-py3-none-any.whl (6.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 2.4 MB/s eta 0:00:00
Installing collected packages: xstatic-font-awesome
Successfully installed xstatic-font-awesome-6.2.1.1
(denv) reimar@infinity:~$ python
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xstatic.pkg import font_awesome as xs
>>> xs
<module 'xstatic.pkg.font_awesome' from '/home/reimar/mambaforge/envs/denv/lib/python3.12/site-packages/xstatic/pkg/font_awesome/__init__.py'>
```

**Comment by BastianZim** [comment]
Hmm that is strange. Maybe file an issue with upstream or setup tools?

**Comment by ReimarBauer** [comment]
@conda-forge/help-python, ready for review!

**Review by xhochy — APPROVED** [review]

**Pull request merged**
