### PR TITLE
Add `solara`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Cool, but see https://github.com/conda-forge/staged-recipes/pull/22935 :)

**Comment by maartenbreddels** [comment]
Multi output can only have 1 source? So we cannot have 1 recipe that depends on 2 pypi tarballs and produces 2 outputs?

**Comment by dhirschfeld** [comment]
> Multi output can only have 1 source? So we cannot have 1 recipe that depends on 2 pypi tarballs and produces 2 outputs?

You can have multiple sources - you just specify the `folder` to extract to (then cd to it before building).

I'll get `solara` building correctly before adding `solara-assets` as a 2nd output.

**Comment by dhirschfeld** [comment]
Not sure why `pip` is installing deps - I thought `--no-deps` got automatically added by `conda-forge` 🤔

**Comment by dhirschfeld** [comment]
@maartenbreddels - would you like me to add you as a maintainer?

**Comment by dhirschfeld** [comment]
I think we're hitting this issue - https://github.com/conda/conda-build/issues/4415

In any case, the build hash is different between the packages so, IIUC we can use `pin_subpackage`

**Comment by maartenbreddels** [comment]
[🤦](https://github.com/conda-forge/staged-recipes/pull/23413/commits/3d066c8244f52d31862aec45e7936ff2f4d39a2f) 😂

**Comment by dhirschfeld** [comment]
@conda-forge/help-python` I think this is ready to merge!

**Pull request merged**
