### PR TITLE
Add recipe for manif

### PR DESCRIPTION
**Pull request by traversaro**
Add recipe for [manif, a small C++11 header-only library for Lie theory](https://github.com/artivis/manif). 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
@artivis Hi again, sorry for always disturbing you with packaging related stuff. I am trying to add manif to conda-forge as it is the only dependency missing for bipedal-locomotion-framework (see https://github.com/dic-iit/bipedal-locomotion-framework/issues/219#issuecomment-788904119). As in the vcpkg case adding manif to conda-forge does not mean any kind of backward compatibility promise for the library, while differently from vcpkg in this case the full test suite and exampes of manif is compiled an run for all the supported compilers (on Windows VS2017), so we are reasonable sure that a version of manif is uploaded only if it works as expected. If in any case you have a reason for which you prefer manif not to be in conda-forge, feel free to let us know, thanks!

**Comment by traversaro** [comment]
@conda-forge/help-c-cpp the recipe is massing the tests and should be ready for review.

**Comment by artivis** [comment]
Hi @traversaro,

no problem seeing `manif` added to conda-forge on my side. Thanks for doing this!

ps- the failing tests could definitely be slightly relaxed.

**Comment by traversaro** [comment]
Thanks @artivis, that's great. 

@wolfv This library is a ~500 start repo on GitHub and is quite oriented toward robotics use, it is the last one of the dependencies for our walking controllers ( see https://github.com/dic-iit/bipedal-locomotion-framework/pull/221) missing from conda-forge.

**Comment by traversaro** [comment]
Thanks @xhochy !

**Comment by wolfv** [comment]
@traversaro awesome! we need to make some tweets :)

**Pull request merged**
