### PR TITLE
Adding `ecco` and `captum` from PyPI

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged. `NA`
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sugatoray** [comment]
## Added `captum` recipe to conda-forge

The package `ecco` depends on `captum`, which is only available on `pytorch` channel. So, adding `captum` to conda-forge as well.

Build failure [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=433941&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=922)

```sh
920		The reported errors are:
921		- Encountered problems while solving:
922		-   - nothing provides requested captum ~=0.4
```

**Comment by sugatoray** [comment]
PR is ready. Request for review/merging. 

cc: @conda-forge/help-python @BastianZim @isuruf @beckermr @jaimergp

**Comment by sugatoray** [comment]
## Reason for Windows build failure

The package `captum` requires `pytorch`, which is only available for `linux` and `osx` on `conda-forge`. this is why windows build of `captum` fails, and in turn, it fails the entire windows build.

**Review by xhochy — APPROVED** [review]

**Comment by sugatoray** [comment]
Thank you for your review and help in merging the PR.

cc: @xhochy

**Pull request merged**
