### PR TITLE
add recipe for r-greta from conda-r-skeleton-helper

### PR DESCRIPTION
**Pull request by brendanf**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by brendanf** [comment]
Linux build seems to get stuck after
```
Collecting package metadata (repodata.json): ...working... done
```
after installing build/host dependencies.

**Comment by brendanf** [comment]
@conda-forge/help-r Ready to merge.

**Comment by brendanf** [comment]
On second thought, don't merge this yet.  I want to add a test to make sure it plays nice with tensorflow.

**Comment by brendanf** [comment]
Tensorflow is loading without error (some warnings) in Python on Windows, but not being discovered in R.

**Comment by brendanf** [comment]
I forgot this was never finished... I don't have a Windows machine to test on, so I'm really not sure how to progress.  Installation of the package itself works, but it doesn't seem to be able to fin the TensorFlow installation.  I'll trigger a rebuild to verify it's still a problem, but otherwise I'm not sure how to progress.  Any thoughts @conda-forge/help-r ?

**Comment by brendanf** [comment]
@conda-forge-admin, please re-render

**Comment by jdblischak** [comment]
@brendanf Thank you for continuing to work on this. Could you please rebase your commits again onto the latest commit?

@conda-forge/help-r Do we have a policy for R packages that interface with Python via reticulate? This recipe directly adds Python and Python packages as dependencies, but neither [r-tensorflow](https://github.com/conda-forge/r-tensorflow-feedstock/blob/master/recipe/meta.yaml) nor [r-keras](https://github.com/conda-forge/r-keras-feedstock/blob/master/recipe/meta.yaml) do this. I see arguments for both approaches, but I think it's most important to be consistent. @brendanf What do you think? I like that you added tests, but you can still keep these by specifying Python and tensorflow to the [test requirements](https://conda-forge.org/docs/maintainer/adding_pkgs.html#test-requirements).

**Comment by brendanf** [comment]
@jdblischak It's now rebased.

I assumed it would be best to include python and TensorFlow as dependencies, since the package has essentially no functionality without them, and also requires a specific version.  But now that you mention it, I had to do a [bit of work on the TensorFlow conda-forge build](https://github.com/conda-forge/tensorflow-feedstock/pull/105) to get it up to a compatible version, and it seems that maintaining that recipe is quite difficult; no recent update has successfully been built.  It might be easier to just let users be responsible for installing whichever TensorFlow they want/can.  If that's the best way forward, I can remove the dependencies here.  I would like to also get the test working on Windows, but maybe that can wait.

**Comment by jdblischak** [comment]
>  It might be easier to just let users be responsible for installing whichever TensorFlow they want/can.

I see adding system dependencies it as a tradeoff between convenience and flexibility. As a counterexample, we specify pandoc as a dependency for r-rmarkdown. To me this is the right decision because rmarkdown users don't really care which exact version of pandoc is installed as long as it works (especially since RStudio also bundles pandoc). But in this case, I think a conda user may want to decide how they install tensorflow. And really, if any R package is going to depend on tensorflow, it should be r-tensorflow, not r-greta.

>  I would like to also get the test working on Windows, but maybe that can wait.

I agree getting this working on Windows would be ideal. But we also have to be realistic. A few months I tried to help a data analyst troubleshoot getting R's tensorflow package to work on Windows, and I eventually had to give up.

For now, I recommend you move the Python requirements to the testing section. Having them here also makes the strict pins less restrictive.

```
test:
  requires:
    - python >=2.7.0
    - tensorflow =1.14.0
    - tensorflow-probability =0.7.0
```

And then maybe another maintainer might be able to advise.

**Comment by brendanf** [comment]
@jdblischak As you suggested, I moved python and tensorflow to test:requires.  I also disabled the test of tensorflow functionality on Windows; instead it merely uses the default `conda build skeleton cran` test which only loads the package.  The test for functionality is still performed on linux and osx.

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
This seems like a reasonable strategy to me.

I've been out of the loop recently, especially in regards to how to properly specify the licenses, so I'll let another maintainer merge.

**Pull request closed without merging**
