### PR TITLE
Add pybedtools and pysam to conda-forge from bioconda

### PR DESCRIPTION
**Pull request by LiterallyUniqueLogin**
These are bioconda packages and should be reviewed by the appropriate people. I've copied the recipes from [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pybedtools/) and [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pysam) (only changes are adding myself as a maintainer)

This is my first time contributing to conda (as well as my first time having contributed a package to PyPI)! Please let me know if there's anything I could improve.

I'm submitting this request so that I can upload a package of my own to conda-forge that depends on pybedtools (which depends on pysam). My package's pull request (and failing build) is [here](https://github.com/conda-forge/staged-recipes/pull/11681)

### CODE REVIEW

**Comment by cbrueffer** [comment]
Is there a specific reason you're adding the recipes here, instead of adding your software to Bioconda? 

`pysam` is an important piece of infrastructure in Bioconda, and moving it may have unintended consequences, e.g. because of pinnings.

Pinging @bgruening and @dpryan79 here who will definitely know more.

**Comment by LiterallyUniqueLogin** [comment]
@cbrueffer Thanks for the response. I started adding it here because I didn't realize it had bioconda dependencies. Is the correct decision tree: 
* Try to add package to conda-forge
* If it happens to have bioconda dependencies, stop and try adding it there instead
?

As a user, I don't (yet) understand why I would want my package in bioconda instead of conda-forge. But I can understand that might be helpful for maintenance purposes. 

Thanks!

**Comment by cbrueffer** [comment]
It depends; typically bioinformatics software lands in bioconda, unless e.g. you need a Windows build (bioconda only supports Linux/macOS at the moment). I assume your software falls into that category, since you need pybedtools/pysam.

**Comment by dpryan79** [comment]
Any package needing pysam is more appropriate on bioconda.

**Comment by LiterallyUniqueLogin** [comment]
Thanks for the advice, @cbrueffer @dpryan79 . I've got a [PR](https://github.com/bioconda/bioconda-recipes/pull/22406) to add trtools to bioconda now instead. I've got some issues with bioconda's mulled tests on that PR, but aside from that this makes sense.

**Pull request closed without merging**
