### PR TITLE
a metapackage for building cyclus

### PR DESCRIPTION
**Pull request by scopatz**
My guess is that the linter will fail because this is a sourceless package

### CODE REVIEW

**Comment by scopatz** [comment]
> I just wanted to let you know that I linted all conda-recipes in your PR (recipes/cyclus-build-deps) and found it was in an excellent condition.

Well that is a pleasant suprise

**Comment by SylvainCorlay** [comment]
> > I just wanted to let you know that I linted all conda-recipes in your PR (recipes/cyclus-build-deps) and found it was in an excellent condition.

> Well that is a pleasant suprise

The bot should totally respond to that!

**Comment by jakirkham** [comment]
Metapackages are things. 😀

I think we fixed the bot a long time ago when we added the `blas` metapackage.

**Comment by scopatz** [comment]
@jakirkham awesome

**Comment by scopatz** [comment]
Looks like CI is done

**Comment by scopatz** [comment]
Tagging @ocefpaf for a merge :)

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
