### PR TITLE
Added recipe for backports.ssl_match_hostname

### PR DESCRIPTION
**Pull request by pmlandwehr**
Missing requirement for #1010 and likely future builds...

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pmlandwehr we have that packaged in https://github.com/conda-forge/ssl_match_hostname-feedstock

@pelson we never addressed the package name space issue here. Should we do it now?

**Comment by pelson** [comment]
No, anaconda also calls it `ssl_match_hostname` rather than `backports.ssl_match_hostname`.

**Comment by ocefpaf** [comment]
> No, anaconda also calls it `ssl_match_hostname` rather than `backports.ssl_match_hostname`.

Forgot about that :unamused: 

@pmlandwehr I am closing this then. Your contribution in https://github.com/conda-forge/ssl_match_hostname-feedstock is highly welcomed!

**Comment by pelson** [comment]
> Your contribution in https://github.com/conda-forge/ssl_match_hostname-feedstock is highly welcomed!

Definitely! If you are happy to do so, please go ahead and add yourself as a maintainer in the recipe. 👍

**Pull request closed without merging**
