### PR TITLE
add r-showtext

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dpryan79** [comment]
I think the R skeleton should be changed to add gzip and tar under windows.

**Comment by dpryan79** [comment]
@conda-forge/help-r This is ready for review

**Comment by dbast** [comment]
That said: the recipe itself looks good.

**Comment by jdblischak** [comment]
Shouldn't this recipe include [freetype](https://anaconda.org/conda-forge/freetype) as a dependency? It gets installed on Linux and macOS because it is installed with `r-base`:

https://github.com/conda-forge/r-base-feedstock/blob/554c57f28fa678d9ffd2d4fea6bc13ed065cdddf/recipe/meta.yaml#L93

But it's skipped on Windows. There is a build for Windows on Anaconda Cloud. Does it not work?

**Comment by dbast** [comment]
That could work after patching `Makevars.win` of the package.

**Pull request merged**
