### PR TITLE
r-smatr

### PR DESCRIPTION
**Pull request by jsignell**
I really appreciate the help I have gotten on previous PRs. Hopefully this one is more straightforward.

### CODE REVIEW

**Comment by jdblischak** [comment]
I restarted the Travis and Appveyor builds now that conda-smithy 2.4.3 has been released.

**Comment by jdblischak** [comment]
Restarted again.

**Comment by jdblischak** [comment]
@jsignell Please update your recipe using https://github.com/bgruening/conda_r_skeleton_helper to add more maintainers and add the GPL license.

**Comment by cbrueffer** [comment]
Added in #4970

**Pull request closed without merging**
