### PR TITLE
mysql-connector-cpp: add recipe for v8.0.19

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by nehaljwani** [comment]
cc @synapticarbors

**Comment by synapticarbors** [comment]
@nehaljwani Thanks for putting this together. I had started to look at this yesterday, but you've obviously made a lot more progress. 

Have you seen the PR I've been working on for `mysql-connector-c` (https://github.com/conda-forge/mysql-connector-c-feedstock/pull/9)? I think the issue there is pertinent to how this is built since it has a similar `WITH_SSL` config option. Do you have any thoughts on the discussion there?

**Comment by synapticarbors** [comment]
Also, is it possible to build this on Windows, especially if it is going to be a dependency for `mysql-connector-python` and `mysqlclient`?

**Comment by nehaljwani** [comment]
I'll add the Windows support tonight.

**Comment by nehaljwani** [comment]
@synapticarbors This feedstock is ready now. I am aware that the initial problem with ssl on macOS has been resolved with an updated patch, but doesn't hurt to move forward with this one anyway.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
