### PR TITLE
Added recipe for openpolicedata generated from grayskull and PyPi. 

### PR DESCRIPTION
**Pull request by potto216**
I added the recipe for openpolicedata generated from grayskull and PyPi. It looks like we will need to add dependency packages arcgis and sodapy on conda-forge. Is making those dependencies available something we should do first? I assume it would be a matter of running grayskull on both arcgis and sodapy and  submitting each as a pull request on coda-forge and notifying the package maintainers of arcgis and sodapy that we did that.

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by potto216** [comment]
Hi, Do I need to have all the check errors passing for the submission to be approved? It looks like the main issue is that conda-forge does not have the dependencies `sodapy` and `arcgis`. Do I need to add those and submit separate requests for them? Thanks!

**Comment by potto216** [comment]
Hi @conda-forge/core what should I do to get openpolicedata added? Two of the packages that openpolicedata needs are arcgis and sodapy which are not on conda-forge but on anaconda and PyPi (https://anaconda.org/esri/arcgis, https://anaconda.org/ucd-dnp/sodapy). Is this what is blocking the PR? If so do I need to use add their recipes with grayskull from anaconda or PyPi to my PR?  Thanks!  Paul

**Comment by dopplershift** [comment]
Yes, you'll need to add recipes for sodapy and arcgis, either in this or a separate PR.

**Comment by potto216** [comment]
Decided to hold off on this.

**Pull request closed without merging**
