### PR TITLE
create python-mint feedstock

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
  - See this [comment](https://github.com/conda-forge/staged-recipes/pull/14354#issuecomment-804911929) below
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] ~If static libraries are linked in, the license of the static library is packaged.~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bjlittle** [comment]
@apeltzer Do you have specific OSX flags set for building `python-mint` that I should know about?

Also are you happy for me to add you to the recipe maintainers list?

**Comment by bjlittle** [comment]
@pletzer Once https://github.com/pletzer/mint/pull/26 is merged, then I can change the `source` `url` and `sha256`

**Comment by pletzer** [comment]
no special flag on mac os x beyond -std=c++11 (to my recollection)

**Comment by bjlittle** [comment]
@ocefpaf Hey how's it going fella? Hope you and your family are all keeping safe and well.

I know that you're super busy, as always, but any change of a merge to bootstrap this feedstock?

I'm collaborating with colleagues down under at [NIWA](https://niwa.co.nz/) and this would help them out big time :smile:

**Comment by bjlittle** [comment]
Hi @xhochy, fancy taking this PR on? :pray: 

Apologies for spamming you :wink:

**Comment by bjlittle** [comment]
@ocefpaf Also, how can I best help you guys out? 

Do you need an extra gun for hire? i.e., how do I work towards becoming a core dev for conda-forge?

I can totally see the benefit of making the time to do that, both selfishly for myself, but also to help out and contribute back to the `conda-forge` community. Let me know what you think :+1:

**Comment by bjlittle** [comment]
@pletzer Can you just explicitly confirm that you're happy being explicitly referenced as a recipe maintainer of `mint`, thanks :+1:

**Review by ocefpaf — APPROVED** [review]
Just waiting on @pletzer confirmation to merge. Thanks @bjlittle!

**Comment by bjlittle** [comment]
@ocefpaf I've just dropped @pletzer temporarily as a maintainer. I'll add him at a later date.

Are you happy to merge as is now?

I'm keen to have the feedstock up and running and the `mint` package available on the `conda-forge` channel, as I want to demo the capability to NIWA early next week.

Cheers dude 👍

**Comment by bjlittle** [comment]
@ocefpaf Thank you so much! :smile: 

Super awesome as usual :beers:

**Pull request merged**
