### PR TITLE
Add mdolab-baseclasses

### PR DESCRIPTION
**Pull request by whophil**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by whophil** [comment]
@nwu63 could you please comment here to confirm the following? Thanks!

> GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

**Comment by nwu63** [comment]
I can confirm that I am willing to be a maintainer of this package.

Just wondering, do we need to have a separate copy of the license file? The original repository provides a license file already, which should be in the tarball.

**Comment by whophil** [comment]
> Just wondering, do we need to have a separate copy of the license file? The original repository provides a license file already, which should be in the tarball.

I was following a pattern from other recipes. It seems to be strongly encouraged [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#checklist). I don't know if it's possible to get the license file from source.

As of right now, I don't think `mdolab-baseclasses` packages the LICENSE.md file into the wheel.

**Comment by whophil** [comment]
@nwu63 saw your comment in https://github.com/mdolab/pyoptsparse/pull/261 about other maintainers. You are welcome to add them (and any others) yourself, I have given you push access to this branch.

**Comment by nwu63** [comment]
> I was following a pattern from other recipes. It seems to be strongly encouraged [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#checklist). I don't know if it's possible to get the license file from source.
> 
> As of right now, I don't think `mdolab-baseclasses` packages the LICENSE.md file into the wheel.

From [this page](https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually) they say
```
The license should only be shipped along with the recipe if there is no license file in the downloaded archive. If there is a license file in the archive, please set license_file to the path of the license file in the archive.
```

and I did check that the tarballs contain the entire repo including the license file. So I think we are okay here? But I have no experience with conda so not sure what we should do.

Lastly, @eirikurj can you comment here and confirm that you are okay with being a maintainer for this package?

**Comment by eirikurj** [comment]
I can confirm that I am willing to be a maintainer of this package.

**Comment by whophil** [comment]
@conda-forge-admin, please ping team

**Pull request merged**
