### PR TITLE
pycryptodome 3.4.11

### PR DESCRIPTION
**Pull request by holgern**
https://pypi.python.org/pypi/pycryptodome
https://github.com/Legrandin/pycryptodome

### CODE REVIEW

**Comment by holgern** [comment]
How can i prevent installation of pycrypto besides pycrytodome?

**Comment by jakirkham** [comment]
So we already have [`pycryptodomex`]( https://github.com/conda-forge/pycryptodomex-feedstock ), which should satisfy this need. Would rather not add `pycryptodome` as it conflicts with `pycrypto` (using the same namespace), which we have packaged as well.

**Comment by holgern** [comment]
I know, but the demand for pycryptodome is there. 
https://anaconda.org/pdrops/pycryptodome has 2898 downloads.

pyCrypto is unmaintained and should not be used anymore! So why not let the user decide...

**Comment by jakirkham** [comment]
@conda-forge-admin, please relint.

**Pull request closed without merging**
