### PR TITLE
add yaqd-thorlabs

### PR DESCRIPTION
**Pull request by untzag**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by untzag** [comment]
@ksunden please comment if you are willing to maintain

**Comment by untzag** [comment]
I now recognize that `thorlabs-apt-protocol` isn't currently in conda-forge, so this will be WIP until I can get that package distributed

**Comment by ksunden** [comment]
Yes, willing to maintain (currently rereleasing the referenced dependency to pypi)

**Comment by untzag** [comment]
see #12265

**Comment by untzag** [comment]
@conda-forge/help-python this is ready for review

I don't understand why I'm failing on windows---any hints would be appreciated

**Comment by beckermr** [comment]
This recipe is noarch python. It fails on windows because not all deps are available on windows. We can merge it now and build it. (It only builds on linux.) Should the windows deps ever become available, it will install there.

**Comment by ksunden** [comment]
Looking at the error, seems to be due to `treegp`, the dependencies referenced in the error have nothing to do with this package

**Comment by beckermr** [comment]
Which error? treegp is no longer being built

**Comment by ksunden** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=191417&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=26d9c833-f81c-502c-87bc-0cb0be44f838&l=28

It was on the last commit to this PR

**Comment by beckermr** [comment]
ah

**Comment by beckermr** [comment]
So weird that it thought one was a dep of the other - we have had a lot of trouble with this

**Pull request merged**
