### PR TITLE
Add r-propr package

### PR DESCRIPTION
**Pull request by jacodela**

### CODE REVIEW

**Comment by jacodela** [comment]
@conda-forge/help-r Can someone take a look at this recipe?

**Comment by jacodela** [comment]
@conda-forge/help-r Can someone take a look at this recipe?

**Comment by dbast** [comment]
The recipe looks good. I just wonder if it would make more sense to bring it to bioconda?

**Comment by dbast** [comment]
@jacodela Do you still need this?

**Comment by jacodela** [comment]
@dbast Yes, but I never figured out how to deal with the linter test failing. What else should I do?

**Comment by dbast** [comment]
@jacodela The recipe is according to `condas-keleton cran ...` or even better https://github.com/bgruening/conda_r_skeleton_helper and fine for now... even though the linter is not fully happy.

**Comment by ocefpaf** [comment]
The linter failures here hid a real failure that prevent the feedstock creation, the un-escaped `:` in the summary. See #8077 

Regarding the those linter failures there have:

- Selectors are suggested to take a <two spaces>#<one space>[<expression>] form. See lines [56]
- Using toolchain directly in this manner is deprecated. Consider using the compilers outlined here.

The former must be fixed but the latter is a false positive for `r` recipes b/c that toolchain has nothing to do with the deprecated toolchain the message refers to. We need to fix the linter.

**Comment by dbast** [comment]
@ocefpaf oh, sry, somehow I did not read the linter careful enough. Thanks for taking care and fixing.

**Comment by ocefpaf** [comment]
> @ocefpaf oh, sry, somehow I did not read the linter careful enough. Thanks for taking care and fixing.

You did nothing wrong @dbast. Sorry I was not clear but my theory is that those two lint failures prevent us from saying the actual failure, the `:`, or we are not even catching that with the linter.

PS: and we do have a false positive to fix, the toolchain lint for r recipes is incorrect.

**Pull request merged**
