### PR TITLE
WIP: Add pytest-benchmark recipe

### PR DESCRIPTION
**Pull request by Juanlu001**
To support https://github.com/conda-forge/staged-recipes/pull/214.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Oops, the master branch contains now other recipes. May I base the branch on an older starting point?

**Comment by ocefpaf** [comment]
@Juanlu001 we are experiencing some turbulence due to (#221). You can base off at an older starting point or wait until we solve this.

**Comment by Juanlu001** [comment]
`git push -f`

r7teqpa

**Comment by Juanlu001** [comment]
Travis CI interacted in a strange way with my `push -f`, I'm closing this and opening a new PR.

**Pull request closed without merging**
