### PR TITLE
add tinyxml2

### PR DESCRIPTION
**Pull request by wolfv**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vend other packages
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by wolfv** [comment]
This is part of the ROS stack -- but part of the ROS independent packages.

**Comment by wolfv** [comment]
ping @lesteve

**Comment by lesteve** [comment]
FYI There is already a tinyxml2 recipe in conda-forge https://github.com/conda-forge/tinyxml2-feedstock.

How does this recipe compare and why not do a PR in the tinyxml2-feedstock if that's appropriate?

**Comment by wolfv** [comment]
You're totally right.I didn't see it (only searched through PR's on staged-recipes and probably didn't select closed).

**Comment by lesteve** [comment]
The reason I knew about it is because I did `conda search tinyxml` at the time I was still hoping `tinyxml` would already be in conda-forge. Finding `tinyxml2` threw me into a `tinyxml` vs `tinyxml2` tangent ...

**Comment by wolfv** [comment]
yeah, it didn't exist when I started building ROS recipes with conda. I am really happy! :)

**Comment by lesteve** [comment]
That's what I guessed as well. Timing is everything ;-)!

**Pull request closed without merging**
