### PR TITLE
conda_r_skeleton_helper of r-rlumshiny

### PR DESCRIPTION
**Pull request by winni2k**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by winni2k** [comment]
This is a missing prerequisite for r-treespace.

**Comment by winni2k** [comment]
@conda-forge/help-r I want to get `r-treespace` into conda-forge, but I appear to be descending into unmet dependency hell. Is there an automated way of getting CRAN packages into conda-forge?

If not, is there a way of pulling packages directly from CRAN in a conda environment.yaml file? I am hoping for something like the [`pip` install trick](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually)?

**Comment by cbrueffer** [comment]
If there is I'm not aware of it. In any case, there is value in having the dependencies in conda-forge so I'd not be a fan of it in any case. So, you'll have to bite the bullet and add dependencies manually; I've gotten started with https://github.com/conda-forge/staged-recipes/pull/12610

**Comment by winni2k** [comment]
Hmmm, "treespace" has 164 dependencies according to packrat's recursive dependency search. Many of those are probably already available in the conda-forge or r channels, but this sounds like a big task that I don't have the resources for right now. Sorry :/

[tmp.txt](https://github.com/conda-forge/staged-recipes/files/5201993/tmp.txt)

**Comment by cbrueffer** [comment]
From my quick look it's a handful of packages that are missing, two of which I just added. Generally that will be true for any CRAN package.

**Pull request merged**
