### PR TITLE
Fix xorg-libxft folder name

### PR DESCRIPTION
**Pull request by epruesse**
PR #2592 used the wrong name for the recipe folder.

Hope a second PR is the correct way to fix this for the bots to do their thing correctly.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please verify that this name is ok, @pkgw? Not sure if distros tend to use `lib` in the name here or not.

**Comment by epruesse** [comment]
@jakirkham 
 - Debian/Ubuntu use [libxft2](https://packages.debian.org/sid/libxft2) 
 - Fedora/Centos/SuSE/... use [libxft](https://rpmfind.net/linux/rpm2html/search.php?query=libXft.so.2)
 - Homebrew uses [libxft](https://github.com/Linuxbrew/homebrew-xorg/blob/master/libxft.rb)

**Comment by epruesse** [comment]
@jakirkham I've opened PR conda-forge/conda-smithy#499 to add a lint check for this type of error. Apologies for the hassle I created here.

**Comment by jakirkham** [comment]
Appreciate your thinking about the naming issue, @epruesse. Also agree with your conclusion.

**Comment by jakirkham** [comment]
No worries, @epruesse. This naming issue happens. While not very often, it does happen enough to deserve some kind of fix. Sadly no one has really had time to take it on and fix it properly. Definitely appreciate you spending time thinking about this issue and trying to find a fix. Unfortunately `conda-smithy` isn't really the right place to fix this. That said getting a real fix shouldn't be difficult if you are interested. Please see issue ( https://github.com/conda-forge/staged-recipes/issues/1073 ) for some discussion and this [comment]( https://github.com/conda-forge/staged-recipes/issues/1073#issuecomment-279176096 ) in particular for an outline of the fix.

**Comment by pkgw** [comment]
Nice follow-through, @epruesse.

**Pull request merged**
