### PR TITLE
Adding gmso

### PR DESCRIPTION
**Pull request by bdice**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by bdice** [comment]
I am willing to be listed as a maintainer.

**Comment by justinGilmer** [comment]
I am willing to be listed as a maintainer.

**Comment by bdice** [comment]
This PR is waiting on https://github.com/mosdef-hub/gmso/pull/329 to be released. Then this PR can be updated for the new release, and it should be deployable.

**Comment by synapticarbors** [comment]
@bdice -- it looks like the PR that was holding this up was merged. I'm happy to help get this PR merged if you're still interested in pursuing it.

**Comment by bdice** [comment]
@synapticarbors Thanks so much for reaching out! I am not the primary developer of this software but I collaborate closely with their team. The PR in question has been merged, but it doesn't look like there has been a release with those changes yet. I'll reach out to their team and see what the timeline is for the next release. It may be better to close this PR and start a new PR with the latest conda-forge build scripts / etc. If you agree, please close this PR and I'll start a fresh one.

**Comment by synapticarbors** [comment]
You can either close this one, or just pull or rebase from upstream. Either way is fine with me. If you do close this and open a new PR, don't hesitate to ping me once it's ready for review if you aren't getting a response.

**Comment by justinGilmer** [comment]
Sorry about this, I saw this and then forgot to message. We are currently waiting on one additional PR for our package before we plan to release to conda-forge. I am confident that this will be merged in and ready to go way before the 1 month date arrives, I will make sure we rebase the feedstock, and make any other changes necessary.

Thank you @synapticarbors  and @bdice for the help and patience!

**Comment by synapticarbors** [comment]
superseded by https://github.com/conda-forge/staged-recipes/pull/12968

**Pull request closed without merging**
