### PR TITLE
add cli11

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
@henryiii are you interested in co-maintaining this feedstock? I'd be more than happy to add you. Planning to use this in micromamba.

**Comment by henryiii** [comment]
Sure, I'd be happy to.

Currently, only tests are built - the library is header only. However, that will change in 2.0 and there will be an optional compiled piece, which we can enable here when that is released.

**Comment by henryiii** [comment]
Can't this be made universal for now? If it's not universal, you probably will want to disable Python 2.7 + Windows via setting a VS limit - VS 2008 does not support C++11 (for obvious reasons ;) )

**Comment by wolfv** [comment]
hmm, I don't think we should make this noarch: python. If anything, we should make it `noarch: generic` but I don't think this is generally done for header only libraries. 
One thing I am also not sure about how this would handle the difference between Windows and Unix with the %LIBRARY_PREFIX% vs $PREFIX, and I am not sure if cmake search files could have OS specific stuff in them? Anyways, the usual trick (that I forgot) is to do `skip: true  # [win and vs<14]`

**Comment by henryiii** [comment]
I wouldn't worry about `noarch: generic` then - partially since 2.0 hopefully won't even use it, probably would be best to stay general here.

**Pull request merged**
