### PR TITLE
Add go-task

### PR DESCRIPTION
**Pull request by AntoinePrv**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@conda-forge/staged-recipes do you know what is missing to get the go executable in the correct location?
 I tried a few different variations but could not figure where it went (trying to build outside of Docker brings compilation error before).
 
 I took inspiration from @conda-forge/fzf  for the go recipe.

**Comment by dbast** [comment]
more extensive recipe as example is e.g. https://github.com/conda-forge/lazygit-feedstock

**Comment by AntoinePrv** [comment]
@dbast thanks! I was missing some internal path to the executable.
This is ready for review.

**Comment by dbast** [comment]
Unfortunately fzf/lazygit are not good examples regarding license handling. go-lang binaries are mostly static compiled and so packages require to contain potentially all licenses. This can be done by running go-licenses during build and referencing the outcome under `license_files: ...`, see e.g. https://github.com/conda-forge/kubo-feedstock/blob/main/recipe/meta.yaml (the existing go feedstocks are to be updated to also do that similarly).

**Pull request closed without merging**
