### PR TITLE
absl-py, requirement for tensorflow 1.5.0

### PR DESCRIPTION
**Pull request by jjhelmus**
Recipe for absl-py, a requirement for tensorflow 1.5.0

### CODE REVIEW

**Comment by bgruening** [comment]
could this be a noarch package?

**Comment by dhirschfeld** [comment]
Would be good to see this merged as I'm very keen to deploy tensorflow 1.5!
conda-forge/tensorflow-feedstock/pull/50

**Comment by dhirschfeld** [comment]
ping!

> *could this be a noarch package?*

I don't know the answer to that question, but I wouldn't let perfect be the enemy of shipped.

**Comment by jjhelmus** [comment]
Sorry for missing out on the early discussion, I had incorrectly set my notification levels for this repo.

I've added `noarch: python` to this recipes.

**Comment by dhirschfeld** [comment]
Is there anything preventing this recipe being merged?

**Comment by mariusvniekerk** [comment]
@conda-forge/staged-recipes ping

**Pull request merged**
