### PR TITLE
Added recipe for uritemplate

### PR DESCRIPTION
**Pull request by pmlandwehr**
Pinging @mnot in case they'd like to be added as a maintainer to the `uritemplate` builder on [conda-forge](http://conda-forge.github.io), a library of community-built [`conda`](http://conda.pydata.org) packages. The maintenance burden here is light: all testing and releases are built and deployed automatically with CI. Changes to how the package is being built can be controlled by changing the recipe which will be located at https://github.com/conda-forge/uritemplate-feedstock shortly after this PR is finished and merged. If you aren't interested in helping maintain the build, that's entirely fine too.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pmlandwehr we have a feedstock for `uritemplate.py` at https://github.com/conda-forge/uritemplate.py-feedstock. Feel free to add yourself as a maintainer there and improve it.

**Comment by pmlandwehr** [comment]
@ocefpaf True - but `uritemplate` is actually distinct from `uritemplate.py`. Same purpose, but a different build dep w/ different versioning.

**Comment by ocefpaf** [comment]
Had no idea. Thanks for the clarification.

PS: I am merging one at a time to reduce the load, so I will merge this as soon as the others clear.

**Comment by pmlandwehr** [comment]
@ocefpaf no rush

**Comment by mnot** [comment]
That's OK, thanks.

**Pull request merged**
