### PR TITLE
add the sparsehash recipe

### PR DESCRIPTION
**Pull request by vgauthier**

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems CircleCI didn't start. 😕

**Comment by jakirkham** [comment]
Going to try opening and closing again.

**Comment by jakirkham** [comment]
Really confused as to why CircleCI is totally missing this.

**Comment by jakirkham** [comment]
Oh, I know. It is because you are PRing from your `master` branch. Could you please add a different branch and PR from that instead?

**Comment by vgauthier** [comment]
Ok I will try to do the pull-request from a branch

**Pull request closed without merging**
