### PR TITLE
Remove wrong LICENSE. It's in LICENSE.txt

### PR DESCRIPTION
**Pull request by isuruf**
cc @conda-forge/staged-recipes, @conda-forge/core

### CODE REVIEW

**Comment by isuruf** [comment]
This was added in https://github.com/conda-forge/staged-recipes/pull/24591. cc @ocefpaf

**Comment by ocefpaf** [comment]
> This was added in #24591. cc @ocefpaf

Ugh. I need to stop reviewing stuff on my phone. Thanks for fixing it!

PS: We could also harden our files a bit. Not sure what it the best approach here.

**Comment by isuruf** [comment]
> Ugh. I need to stop reviewing stuff on my phone. Thanks for fixing it!

Nah. Keep reviewing on the phone. :smile:

**Comment by jakirkham** [comment]
Maybe we can add a test to check if files were change outside of `recipes`?

Admittedly sometimes we do want to change files outside of `recipes`, but a lot of things (weird CI changes, etc.) can be caught that way

**Comment by BastianZim** [comment]
How about a linter warning if something outside of the "recipes" folder is changed in staged-recipes?

Something like https://github.com/conda-forge/conda-smithy/blob/7a6269113a525205dbef32140280f14d74479c8d/conda_smithy/lint_recipe.py#L908 but for everything.

**Comment by BastianZim** [comment]
> Maybe we can add a test to check if files were changed outside of recipes?

Ahh you were faster 😄

I think a linter warning or linter failure is a good compromise. It can be ignored if staged-recipes member do something.

**Comment by jakirkham** [comment]
Yeah maybe warning from the linter is the right level

We also can skip the linter when we know we don't want linting. So it can be ignored that way as well

**Comment by beckermr** [comment]
I thought we already had a linter warning for stuff outside the recipes. lol.

**Comment by jakirkham** [comment]
Well the linter didn't warn: https://github.com/conda-forge/staged-recipes/pull/24591#issuecomment-1827177717

Is there something we need to configure for the warning to work?

**Comment by BastianZim** [comment]
I think we only have it for “example”, nothing else.

**Pull request merged**
