### PR TITLE
Add a recipe for mpas_tools

### PR DESCRIPTION
**Pull request by xylar**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xylar** [comment]
@jhkennedy, please confirm that you're okay with being a maintainer of the mpas_tools package.

**Comment by jhkennedy** [comment]
@xylar , absolutely! Confirmed.

**Comment by xylar** [comment]
Thanks @jhkennedy!

I was too fast with the PR and the dependency wasn't yet available.  I'll have to tweak something to get it to rebuild.

**Comment by xylar** [comment]
@jhkennedy, I realized that we *are* vendorizing the legacy NetCDF c++.  How did you get away with this for tempest-remap?  Perhaps there was some discussion when you submitted the recipe?

I'm having trouble with compilers at the moment.  When I set up jigsaw, I ended up having to use cmake, which might be my solution here, too.

**Comment by jhkennedy** [comment]
The legacy netCDF C++ API was just directly incorporated into tempest-remap, so I suppose we did vendorize it. Since the legacy API won't ever be available on conda-forge, and doesn't conflict with the new netCDF C++ API (as far as I'm aware), I don't think this will be a problem. 

Really, the "correct" way to handle the netCDF C++ API is to update to the newest version, but because they are so radically different, the development burden to do so is rather large. So, I think vendorizing is the best option currently.

**Comment by jhkennedy** [comment]
I think you might be able to get the legacy API through the tempest-remap package -- that way only one package is vendorizing it. Though if tempest-remap updates the API (don't see this happening anytime soon), you'd then be forced to vendorize or upgrade at that point.

**Comment by xylar** [comment]
> I think you might be able to get the legacy API through the tempest-remap package

I don't think that's possible because neither tempest-remap nor this package is creating a NetCDF-C++ library, we're both just incorporating the code into each executable.  In that way, I wonder if this even counts as "vendorizing".  I'll ask one of the conda-forge admins once I get the build working.

**Comment by xylar** [comment]
I'm having to patch enough things that it seems worth making these fixes upstream and doing another release.

**Comment by xylar** [comment]
@conda-forge/help-c-cpp and @conda-forge/help-python, this recipe is ready for review.  There is a c++ component (`mesh_conversion_tools`) and a python component (the `mpas_tools` package, which includes wrappers around the c++).

We note that we include a copy of the legacy NetCDF c++ 4.2 source in our repo and build directly with that source but we do not build or install a NetCDF c++ library.  Therefore, we think we do not "vendorize" anything and that this package shouldn't conflict with any others.

**Comment by xylar** [comment]
Thanks @chrisburr!

**Pull request merged**
