### PR TITLE
add apptools

### PR DESCRIPTION
**Pull request by grlee77**
Add apptools as required by #285.

This PR will require both #391 and #394 to be merged first

### CODE REVIEW

**Comment by jakirkham** [comment]
Restarting the CIs here now that the dependencies are available.

**Comment by jakirkham** [comment]
Does this support Python 3 or is Python 2 only?

**Comment by patricksnape** [comment]
It should support Python 3 as well - the problem seems to be it isn't picking up the new pyface 3.x builds yet.

**Comment by jakirkham** [comment]
Good point. The Windows packages are not released yet. So, let's wait for that to happen. Will check back later and restart AppVeyor.

**Comment by grlee77** [comment]
Is it desirable to run the full package test suite rather than just the import tests done here?  The tests themselves only take about a second to complete.

If so, I can update the test section to something like the following:  

```yaml
test:
  requires:
    - nose
    - numpy
    - pandas
    - pytables
  commands:
    - python -m nose.core -v apptools
```
 (for this package, the tests have a number of additional requirements that are available through the default channel).

I could do the same for the traits-feedstock, etc. that were already merged

**Comment by jakirkham** [comment]
So, it is generally good to run tests. However, I have tried to use the following rule of thumb. If it is compiled, try to run the tests (or at least some subset that reasonably exercises the code). Particularly, try to do so for anything where numeric accuracy is important (e.g FFTW). If it is Python only and they do CI, I am far less concerned about testing and generally skip it. Importing a bunch of things tends to be just as effective at catching most of the errors you will see (missing dependencies or syntax issues).

**Comment by grlee77** [comment]
okay, let's leave this one as is then.  Can someone restart the CI?

**Comment by jakirkham** [comment]
I think I had, but I don't think everything had been released yet. I have restarted the CIs again. Let's see how this goes.

**Comment by jakirkham** [comment]
Looks like there are some requirements issues that need to be addressed here. That is the cause of the CI failure.

**Comment by grlee77** [comment]
The Appveyor failure seems to be a time out, but the CirceCI one I need help with.
It looks like maybe it is trying to fetch the `traitsui` dependency from the default channel instead of cond-forge?

**excerpts from the log:**

The following looks okay, with conda-forge listed as the source for pyface & traitsui
```
The following NEW packages will be INSTALLED:

    apptools:   4.4.0-py27_0  file:///opt/conda/conda-bld/linux-64/
    configobj:  5.0.6-py27_0  defaults       
    .
    .
    . 
    pyface:     5.0.0-py27_0  conda-forge
    traitsui:   5.0.0-py27_0  conda-forge                             
```

but then this error occurs
```
conda.resolve.Unsatisfiable: The following specifications were found to be in conflict:
  - python 3.4*
  - traitsui -> pyface 4.3.0|4.4.0|4.5.2
  - traitsui -> python 2.7*
```
The default channel only constains a `traitsui` in the default channel for Python 2.7, and that seems to be what it is finding.  Is there a way to work around this?

The conda-forge packages all exist here:
https://ci.appveyor.com/project/conda-forge/traitsui-feedstock

**Comment by grlee77** [comment]
Okay, I think I see the problem is that `traitsui` is listed as failed at:
https://conda-forge.github.io/feedstocks.html

so I have to fix that one first.  I thought it had passed before we merged it

**Comment by jakirkham** [comment]
Yeah, I think some of the `pyface` packages weren't released when the `traitsui` Linux build started. If you just restarted the `traitsui` build on Linux, you should be good to go.

**Comment by grlee77** [comment]
Okay, I fixed the Linux build for traitsui, so this is ready to try again.

also, both pyface and traitsui released v5.1.0 earlier today.  I will wait a bit for them to show up on pypi before updating the feedstocks.

**Comment by jakirkham** [comment]
Fair enough, restarted the CIs here to make sure everything works.

**Comment by jakirkham** [comment]
Weird. Still seeing a failure on Windows, but only on Python 3.4 64-bit.

**Comment by grlee77** [comment]
I don't see any obvious error messages during the build, but it does say:
```
writing list of installed files to 'record.txt'
number of files: 0
```
which would explain why it fails to import


Any idea if that might be related to the problem?

The succeeding cases seem to be building into `C:\Miniconda-x64\envs\_build\Lib` 

but in the failing Python 3.4 64-bit build things are building in `C:\Miniconda-x64\Lib\`  (why no `_build` environment?)

**Comment by grlee77** [comment]
The only other thing that looks like an error occurs higher up in the log, but seems related to visual studio, which we aren't using in this recipe:
```
C:\Miniconda-x64\conda-bld\work\apptools-4.4.0>call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /Release 
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.1\.
Targeting Windows 7 x64 Release
 
The specified configuration type is missing.  The tools for the
configuration might not be installed.
 
```

**Comment by jakirkham** [comment]
Yeah the fact that it is installing to `C:\Miniconda-x64\Lib\` is very strange indeed. @patricksnape and @msarahan, I am totally out of my depth here. Is there any reason that on the Python 3.4 64-bit build the wrong install location (`C:\Miniconda-x64\Lib\`) is being used?

**Comment by jakirkham** [comment]
Workarounds in place for the Python 3.4 64-bit Windows issue. AppVeyor has been restarted.

**Comment by grlee77** [comment]
thanks.  ready to merge?
once this one is available it will be possible to finish #396

**Comment by jakirkham** [comment]
Absolutely! Thanks for being so patient.

**Comment by jakirkham** [comment]
Well, we are not exactly sure why, but this is not getting converted to a feedstock correctly. See this issue ( https://github.com/conda-forge/staged-recipes/issues/458 ).

**Pull request merged**
