### PR TITLE
Add jpeg recipe with custom CMake file.

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/staged-recipes/pull/355

Simply takes ( https://github.com/conda-forge/staged-recipes/pull/355 ) and squashes it into one commit. Also added executable permissions to the build scripts (`bld.bat` and `build.sh`), which doesn't really matter, but is nice.

cc @gillins @patricksnape @msarahan @ocefpaf

### CODE REVIEW

**Comment by jakirkham** [comment]
Once CI passes would you like to do the honors, @ocefpaf?

**Comment by ocefpaf** [comment]
Thanks @jakirkham!

**Comment by jakirkham** [comment]
Thanks for keeping an eye on this, @ocefpaf. We should rebuild `hdf4` once this is released to see how it goes.

**Comment by ocefpaf** [comment]
> We should rebuild `hdf4` once this is released to see how it goes.

I am on it.

**Comment by dopplershift** [comment]
Rebuild jasper as well, since it's linked against jpeg8 (conda-forge/jasper-feedstock#1). Otherwise, installing conda-forge's jasper package out of the box is broken now.

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/jasper-feedstock/pull/3

**Comment by dopplershift** [comment]
I wish there were some way not to pin the package to a particular version of jpeg, but to note that it needs the version it built against.

**Comment by msarahan** [comment]
@dopplershift I think that's similar to the ideas in https://github.com/conda/conda-build/pull/848 and other related PRs - you should weigh in there with your request and any ideas for implementation.

**Pull request merged**
