### PR TITLE
example

### PR DESCRIPTION
**Pull request by Sebastianborszcz**

### CODE REVIEW

**Comment by synapticarbors** [comment]
@Sebastianborszcz I'm unclear what this PR is for. It looks like you're just creating another copy of the example recipe.

**Comment by Sebastianborszcz** [comment]
yes I'm sorry if I put unneeded stuff online, but I'm new to github and just want to learn how it works.
But I don't understand, why all checks have failed. I really just copied the example recipe. Why didn't it work?

**Comment by synapticarbors** [comment]
It looks like there is in indentation issue in the final line of the maintainers. Not sure if that's the exact problem. You can also test locally by running `conda build <recipe directory>`, where `<recipe directory>` is the path to the recipe directory on your machine.

**Comment by jakirkham** [comment]
Should prefix the directory name with `example` if it is meant to be a new example. Also any thoughts on putting all of the example recipes under a directory called `examples`? Would help avoid having everything get cluttered down the line.

**Pull request closed without merging**
