### PR TITLE
Add r-epigenr

### PR DESCRIPTION
**Pull request by lucymli**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rpanai** [comment]
Hi Lucy, did you followed these [guidelines](https://github.com/bgruening/conda_r_skeleton_helper)? I did so on a recent [PR]( https://github.com/conda-forge/staged-recipes/pull/12423) and I didn't have problems with failed checks.

**Comment by lucymli** [comment]
> Hi Lucy, did you followed these [guidelines](https://github.com/bgruening/conda_r_skeleton_helper)? I did so on a recent [PR](https://github.com/conda-forge/staged-recipes/pull/12423) and I didn't have problems with failed checks.

I used that link but could not follow all the steps as I want to submit an R package that I maintain on Github but not CRAN. I used `conda skeleton cran https://github.com/lucymli/EpiGenR` to generate the meta.yaml, and manually edited to 1) remove comments, 2) add the _extra_ section, and 3) add an URL for the tarball.

If this is not the right approach for Github R packages, please let me know what the best alternative approach is. Thanks!

**Comment by rpanai** [comment]
> > Hi Lucy, did you followed these [guidelines](https://github.com/bgruening/conda_r_skeleton_helper)? I did so on a recent [PR](https://github.com/conda-forge/staged-recipes/pull/12423) and I didn't have problems with failed checks.
> 
> I used that link but could not follow all the steps as I want to submit an R package that I maintain on Github but not CRAN. I used `conda skeleton cran https://github.com/lucymli/EpiGenR` to generate the meta.yaml, and manually edited to 1) remove comments, 2) add the _extra_ section, and 3) add an URL for the tarball.
> 
> If this is not the right approach for Github R packages, please let me know what the best alternative approach is. Thanks!

Unfortunately I don't have idea. Once I tried to follow [this](https://stackoverflow.com/a/52475507/4819376) and the issue mentioned there.

**Comment by dbast** [comment]
Requires r-phyclust to be added to conda-forge.

**Pull request closed without merging**
