### PR TITLE
Add recipe for biopython

### PR DESCRIPTION
**Pull request by souravsingh**
This PR add a recipe for biopython.

Pinging @peterjc for review and issue with license.

### CODE REVIEW

**Comment by peterjc** [comment]
I would regard the linting warning as a false positive:

> The recipe license should not include the word "License".

The license really is know as the "Biopython License Agreement".

**Comment by peterjc** [comment]
Should this in some way acknowledge that it is based on the BioConda recipe (which does not currently get built for Windows):
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/biopython/meta.yaml

Cross reference https://github.com/bioconda/bioconda-recipes/issues/5292

**Comment by souravsingh** [comment]
I think it should be possible to skip the lint check for the recipe. Someone from @conda-forge/staged-recipes confirm this.

**Comment by johanneskoester** [comment]
Can you explain the rationale of putting this into conda-forge? It is clearly bio-related, and we have it already on bioconda. Is it only because you want to have the windows support?

**Comment by johanneskoester** [comment]
Sorry, I found the original issue with the explanation! Forget my question!

**Comment by peterjc** [comment]
Yes, the goal here is Windows support (something not currently catered to in BioConda).

**Comment by souravsingh** [comment]
In that case, should we build the recipe only for Windows? (since bioconda handles the binaries for Linux and Mac and is regularly updated)

**Comment by peterjc** [comment]
Unless the conda-forge people think Windows only is a good idea, I'd do all the platforms as not everyone will have the bioconda channel installed.

(BioConda might then choose to stop doing Biopython packages in future, which would be fine).

**Comment by souravsingh** [comment]
@johanneskoester All the tests for the recipe pass. Would it be possible to skip the lint check for license?

**Comment by souravsingh** [comment]
@synapticarbors Is the recipe ready for merging?

**Comment by scopatz** [comment]
Yep this is good. Sorry for the delay!

**Pull request merged**
