### PR TITLE
Update the TRAVIS_TOKEN for conda-forge-manager user

### PR DESCRIPTION
**Pull request by pelson**
To get this value, I:

```

$ travis login
Username: conda-forge-manager
Password for conda-forge-manager: ###
Two-factor authentication code for conda-forge-manager: #

$ travis token
Your access token is ###

$ travis encrypt TRAVIS_TOKEN="###"
Please add the following to your .travis.yml file:

  secure: "<The super long ecrypted secret...>"

```

## Note

I'm only ~75% confident that I've done this right. Hopefully the commit message will increase my confidence next time this needs to be done. When it comes to Travis tokens, I can't remember how one scopes them, or sets the expiry on them, so I've just got the defaults.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @pelson. Guessing you quoted the secure token when running `travis encrypt`, correct?

**Comment by jakirkham** [comment]
> When it comes to Travis tokens, I can't remember how one scopes them, or sets the expiry on them, so I've just got the defaults.

Don't think they have scopes. Think we were wondering the same thing about when they expired last time (not aware of any option to set that). Appears they expire in 2 years.

**Comment by pelson** [comment]
I didn't. I've now updated (and the commit message).

**Comment by jakirkham** [comment]
Thanks all. Let's give it a try. :)

**Pull request merged**
