### PR TITLE
Add recipe for gz-math

### PR DESCRIPTION
**Pull request by traversaro**
The ignition robotics libraries, that are currently packaged in conda-forge under the `libignition-*`, have been renamed to Gazebo libraries (see https://community.gazebosim.org/t/a-new-era-for-gazebo/1356).

To avoid confusion related to the feedstock name in the future, we are re-submitting all the `libignition-` recipes to conda-forge to have descriptive and coherent names that start with `gz-`, as described in https://github.com/conda-forge/libignition-cmake0-feedstock/issues/26#issuecomment-1255871405 . 

This PR creates a new `gz-math-feedstock` to package [`gz-math`](https://github.com/gazebosim/gz-math), using the recipe already available in https://github.com/conda-forge/libignition-math4-feedstock, appropriately modify to separate the C++ and Python packages in different conda packages, as discussed in https://github.com/conda-forge/libignition-cmake0-feedstock/issues/26#issuecomment-1255871405 .

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by j-rivero** [comment]
Probably requires #20593 before the CI can pass.

Out of curiosity: the way of compiling the python bindings seems uncommon and probably not very easy to maintain. I assume that there is a good reason to make it that way (go to the pything directory and run the make from them) instead of using plan cmake + make <python_target>.

**Comment by traversaro** [comment]
> Out of curiosity: the way of compiling the python bindings seems uncommon and probably not very easy to maintain. I assume that there is a good reason to make it that way (go to the pything directory and run the make from them) instead of using plan cmake + make <python_target>.

The main reason is that typically on conda-forge you need to build for several (3/4) Python versions, so if you want to have different packages for the C++ library and its Python bindings you need either to:
* Option 1: Make them different subpackages each one with its own build script, meaning that you need to have a way to build just the python bindings linking against an already existing and installed C++ library 
* Option 2: Build 3/4 times the C++ libraries and the Python bindings, then separating on a file name basis the file that will go in the C++ package and the files that will go in the different Python packages

To be honest, I was never able to get Option 2 to work properly, and I found always quite easy to patch CMake projects to permit to build bindings independently from the rest of the project (see https://github.com/conda-forge/staged-recipes/pull/18234 for the first time I struggled with this). Option 1 has also the nice advantage that you build the C++ library only once, that for big libraries or libraries with many variants or platforms is a good use of CI resources.

**Comment by traversaro** [comment]
* @wolfv:  https://github.com/conda-forge/staged-recipes/pull/20547#issuecomment-1261908808
* @j-rivero:  https://github.com/conda-forge/staged-recipes/pull/20593#issuecomment-1262510486

**Comment by traversaro** [comment]
@conda-forge/help-c-cpp @conda-forge/help-python-c The PR is ready for review.

**Pull request merged**
