### PR TITLE
Initial release of MaFreDo

### PR DESCRIPTION
**Pull request by RubendeBruin**
Initial release for MaFreDo (Marine Frequency Domain calculations)

meta.xml created from pip using conda skeleton 
GitHub users listed in the maintainer section: only me
No static libraries
Pure python (noarch: python), 

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [X] If static libraries are linked in, the license of the static library is packaged. : NA
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by RubendeBruin** [comment]
Fails at using "Build recipe" when executing 
python setup.py egg_info

no idea why. Will try again tomorrow.

**Comment by npavlovikj** [comment]
The error message is:
```
ERROR: Could not find a version that satisfies the requirement pyscaffold (from versions: none)
ERROR: No matching distribution found for pyscaffold
```
so you should add `pyscaffold` as host/run dependency.

**Comment by npavlovikj** [comment]
Thank you for contributing @RubendeBruin 🎉

**Comment by RubendeBruin** [comment]
@npavlovikj  Thanks for the support!

**Pull request merged**
