### PR TITLE
Adding rockstar galaxy/halo finder

### PR DESCRIPTION
**Pull request by cphyc**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by cphyc** [comment]
Thanks for the feedback.

The issue is that I do not have direct access to the original repository (https://bitbucket.org/pbehroozi/rockstar-galaxies/) nor its GitHub fork (https://github.com/jwise77/rockstar-galaxies). The reason for this recipe is to ease the compilation procedure.

Should I submit a PR on either the GitHub version or the original repository including changes I made to my local fork (to ease compilation as a conda package) and update the recipe afterwards?

**Comment by beckermr** [comment]
You can add the diff between your fork and upstream as a patch on the feedstock.

**Comment by beckermr** [comment]
Also Peter used to maintain his own copy of the source (bitbucket maybe). Why is there another repo on GitHub?

**Comment by cphyc** [comment]
The version on GitHub is already a modified version of Peter's that add fixes for Enzo (as far as I can tell). I can always use Peter's version and ship in the patch if that is the way to go!

**Comment by beckermr** [comment]
Yes the upstream source is here: https://bitbucket.org/pbehroozi/rockstar-galaxies/src/main/

**Comment by cphyc** [comment]
@beckermr I think this is now ready, using the upstream source! Thanks for the feedback.

**Comment by beckermr** [comment]
The patch is quite intrusive, going beyond simple changes in build scripts. Seeing the extent of the differences, I am hesitant to merge.

**Comment by beckermr** [comment]
Sorry. Meant to comment!

The patch is very intrusive, more so than I thought, so I am hesitating.

**Comment by beckermr** [comment]
In particular I see
 
 - changes to default settings in the .pl
 - changes in function signatures
 - new scripts that look to be work/site-specific

We can't in good faith call this rockstar-galaxies since it is a heavily modified version of it.

**Comment by cphyc** [comment]
I have stripped down the patch as much as possible to remove any change not strictly required for this recipe to compile, including the slight function signature changes.

**Comment by beckermr** [comment]
Let me look again.

**Comment by beckermr** [comment]
The version needs to be a real version and not a commit, unless that happens to be how Peter has been doing things? Otherwise, the patch looks great.

**Comment by cphyc** [comment]
Unfortunately, there are no tag or release as far as I could tell on the repository (https://bitbucket.org/pbehroozi/rockstar-galaxies/downloads/?tab=downloads). There is however a version file (https://bitbucket.org/pbehroozi/rockstar-galaxies/src/main/VERSION) that mentions 0.99.9-RC3-newA. Should I use this as the version and hardcode the source URL?

15 Aug 2023 16:39:48 Matthew R. Becker ***@***.***>:

**Comment by beckermr** [comment]
Yes, let's use that version. We may need to reformat in order to be consistent with conda's version spec: https://docs.conda.io/projects/conda/en/stable/user-guide/concepts/pkg-specs.html#version-ordering

**Comment by beckermr** [comment]
Actually no, that version has not been updated since 2016 and Peter made commits in 2020. We need to ask Peter to tag a version.

**Comment by cphyc** [comment]
OK. I have contacted Peter, the original author of rockstar-galaxies, to bump the version and issue a release and/or tag.

**Comment by cphyc** [comment]
Hey @beckermr, Peter made a new release together with a git tag. I've updated the recipe to reflect this so hopefully, everything should be good now!

**Pull request merged**
