### PR TITLE
Add R package wesanderson.

### PR DESCRIPTION
**Pull request by jdblischak**
CRAN R package [wesanderson](https://cran.r-project.org/package=wesanderson). Recipe created with conda-build 2.1.18 and [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper).

### CODE REVIEW

**Comment by jdblischak** [comment]
@bgruening Please review

**Comment by jdblischak** [comment]
ping @bgruening

**Comment by bgruening** [comment]
Sorry for the late reply.

**Comment by jdblischak** [comment]
No worries, @bgruening! Much appreciated.

**Pull request merged**
