### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Closes https://github.com/conda-forge/staged-recipes/issues/15327

### CODE REVIEW

**Comment by BastianZim** [comment]
Some info: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by BastianZim** [comment]
Some info: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by BastianZim** [comment]
@beckermr That would be my initial attempt.

**Comment by jakirkham** [comment]
Awesome thanks for doing this Bastian and thanks for the review Matt! 😄

**Comment by BastianZim** [comment]
Happy to John! This was actually because you had mentioned it somewhere months ago, I think. But just didn't have the time until now... 
By the way, I only used those two templates because that's what most issues are but should more be added?

**Comment by jakirkham** [comment]
Yeah that seems believable. Have certainly thought about this before, but hadn't had time to look into it

I think that is fine to start. We can expand the list as needed. The big step is really having this framework in place, which should make all of that work easier going forward 🙂

**Comment by BastianZim** [comment]
In case you're interested, new version in #17366

**Pull request merged**
