### PR TITLE
add r-chorddiag

### PR DESCRIPTION
**Pull request by rluria14**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rluria14** [comment]
@oblute @benhuff agree to maintain?

**Comment by rluria14** [comment]
@conda-forge/help-r ready for review

**Comment by npavlovikj** [comment]
I assume you used `conda_r_skeleton` for the recipe and cleaned if afterwards? Let's wait to hear back from @benhuff if he is willing to be maintainer, and we can merge this afterwards.

**Comment by rluria14** [comment]
> I assume you used `conda_r_skeleton` for the recipe and cleaned if afterwards? Let's wait to hear back from @benhuff if he is willing to be maintainer, and we can merge this afterwards.

Certainly did! Also, @benhuff just agreed to maintain.

**Comment by npavlovikj** [comment]
Many thanks for adding the recipe @rluria14 - LGTM!

**Pull request merged**
