### PR TITLE
Remove .DS_Store from recipes directory on local tests

### LINKED ISSUE #13823: Do not import .DS_Store with .ci_support/build_all.py
Hi,

Currently, when testing packages locally (As described in https://conda-forge.org/docs/maintainer/adding_pkgs.html#running-tests-locally-for-staged-recipes) the `.ci_support/build_all.py` script imports all files and folders in the `recipes` directory when building the packages. 
This generally isn't a problem because only recipe folders should be added to the directory in the first place, but macOS automatically and continuously creates [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store) files in every folder, which are then also included and cause the build to fail.

Error output:
```zsh
...
python /home/conda/staged-recipes-copy/.ci_support/build_all.py
Building .DS_Store with conda-forge/label/main
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING conda_build.config:arch(318): Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 177, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 101, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 139, in build_folders
    G = construct_graph(recipes_dir, worker=worker, run='build',
  File "/home/conda/staged-recipes-copy/.ci_support/compute_build_graph.py", line 400, in construct_graph
    raise ValueError("Specified folder {} does not exist".format(recipe_dir))
ValueError: Specified folder /home/conda/staged-recipes-copy/recipes/.DS_Store does not exist

```

I thought I had fixed this with https://github.com/conda-forge/staged-recipes/pull/13555 but it is still happening. 
As far as I understand the code, there are two ways to exclude them:

1. Remove all `.DS_Store` files from `staged-recipes-copy` by adding `find ~/staged-recipes-copy -name ".DS_Store" -delete` in line 26 at https://github.com/conda-forge/staged-recipes/blob/d1e97aceeaf20b7fa1b2738fcb3476518fad0c45/.scripts/build_steps.sh#L24-L27
2. Make `python /home/conda/staged-recipes-copy/.ci_support/build_all.py` only import directories.

The first option is fairly easy to implement and clean because it also removes `.DS_Store` files added to the recipe folders and subfolders themselves but it takes quite some time to execute, since it needs to scan the whole directory and all subdirectories.

I would therefore suggest the second option where it could be implemented like this:
```python
with os.scandir(recipes_dir) as dir_list:
    folders = [dir_obj.name for dir_obj in dir_list if dir_obj.is_dir()]
```
which could be included instead of https://github.com/conda-forge/staged-recipes/blob/d1e97aceeaf20b7fa1b2738fcb3476518fad0c45/.ci_support/build_all.py#L28

There are multiple ways to check if something is a file or folder but `os.scandir`seems to be the fastest: https://stackoverflow.com/a/59938961/9599354

If there is any interest, I'd be happy to create a PR for either option.

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Closes #13823

### CODE REVIEW

**Comment by BastianZim** [comment]
@isuruf Like so?

**Comment by isuruf** [comment]
Does it work for you?

**Comment by BastianZim** [comment]
Yes, successfully verified it locally, just two comments:

1. Not sure why I need to specify `-maxdepth 1` since the current directory is `~/staged-recipes-copy/recipes` and `-maxdepth 0` [means](https://man7.org/linux/man-pages/man1/find.1.html) that it applies the actions to the starting points, which, to my understanding, should be all elements in `recipes`. Yet, when I use that, it fails. Is that correct behaviour or should I specify the path differently?
2. macOS recreates `.DS_Store` files after some time. I don't know the frequency here so I cannot guarantee that the files are not recreated before they are copied by `build_all.py`. I have personally not observed this happening in such a short time but I cannot guarantee it. Is there someone on the team that might know this?

**Comment by chrisburr** [comment]
>     1. Not sure why I need to specify `-maxdepth 1` since the current directory is `~/staged-recipes-copy/recipes` and `-maxdepth 0` [means](https://man7.org/linux/man-pages/man1/find.1.html) that it applies the actions to the starting points, which, to my understanding, should be all elements in `recipes`. Yet, when I use that, it fails. Is that correct behaviour or should I specify the path differently?

"starting points" in this context means the `~/staged-recipes-copy/recipes` folder itself.

>     2. macOS recreates `.DS_Store` files after some time. I don't know the frequency here so I cannot guarantee that the files are not recreated before they are copied by `build_all.py`. I have personally not observed this happening in such a short time but I cannot guarantee it. Is there someone on the team that might know this?

IRRC It's something to do with then you enter the folder in finder. As this is being applied to a copy which only exists inside a docker container they shouldn't ever be re-created.

**Comment by BastianZim** [comment]
> "starting points" in this context means the ~/staged-recipes-copy/recipes folder itself.

Ahh ok makes sense, thanks!

> IRRC It's something to do with then you enter the folder in finder. 

Didn't know that, TIL.

**Pull request merged**
