### PR TITLE
Add dbt-core

### PR DESCRIPTION
**Pull request by maresb**
# Context

There is currently a [dbt feedstock](https://github.com/conda-forge/dbt-feedstock) which is outdated because [it has been split into separate packages](https://github.com/conda-forge/dbt-feedstock/issues/27#issuecomment-944997539). The "core" PyPI package now consists of the main program. The dbt PyPI package is now a parent package which installs dbt-core plus the following plugins:

- dbt-postgres
- dbt-redshift
- dbt-snowflake
- dbt-bigquery

**This staged recipe is working towards reproducing the aforementioned PyPI structure on conda-forge.**

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by maresb** [comment]
@thewchan, could I add you as a maintainer here?

**Comment by maresb** [comment]
@conda-forge/help-python ready for review!

**Comment by thewchan** [comment]
Oh nice! Yeah I think I was in the middle of making something like this but I got distracted. Yes please feel free to add me @maresb

**Comment by maresb** [comment]
@thewchan, just so that I don't have to ask n times, could I also add you as a maintainer on all the plugins?

**Comment by maresb** [comment]
Sorry, just starting to change my mind on this...

I think I want to put everything into the original dbt repo with multiple outputs since the versions are all pinned to each other.

I'll reopen if I change my mind back.

**Comment by thewchan** [comment]
@maresb oh interesting, okay keep me on whatever you decided in the end, thanks

**Comment by maresb** [comment]
@thewchan, I'm thinking that I want to avoid the situation of boto3-stubs.

On the other hand, I'm not sure that the autotick bot can compute the sha256 sums for multiple sources.

Do you have any thoughts? Maybe we try both ways and then we understand the respective benefits and disadvantages.

**Comment by thewchan** [comment]
@maresb 
I think for packages such as this one and boto3-stubs, where are they so many optional versions of the package it will be difficult to avoid that hassle if we do want to deliver a pip like experience, i.e. each of the optional version is available. I'm okay with that; core team has warned me on a different project that packages like these are pretty notorious in terms of maintainability

**Pull request closed without merging**
