### PR TITLE
add pyctm to conda-forge

### PR DESCRIPTION
**Pull request by adbeda**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by adbeda** [comment]
@kzhai and @fdtomasi . thank you for your collaboration on this mini-project.
I added you too as co-maintainers of this recipe, which will grant you the access to merge future pull requests. for any update you two will make on the releases hosted on github, you will have the privilege to merge the change on conda-forge too. 
If you w'd like to co-maintain this, please add a comment below saying that you would like to do so, so that people who will review this PR knows the deal.

**Comment by fdtomasi** [comment]
Awesome! I would be happy to collaborate on this. Thank you.

**Comment by adbeda** [comment]
coo @fdtomasi. @kzhai are you in? lol please comment below if you want to maintain this package in the future with " yes, I would like to be added as maintainer". If you'll be busy, thats cool. we got you!

**Comment by kzhai** [comment]
Sure, please include me as a maintainer too. Glad to be a part of this. Thanks.

**Comment by adbeda** [comment]
@conda-forge/help-python, this recipe is ready for review. crushing it today!

Thanks!

**Pull request merged**
