### PR TITLE
Add fpylll

### PR DESCRIPTION
**Pull request by isuruf**
@malb, I'm packaging fpylll for conda. Larger goal is to package sagemath. Would you like to help in maintaining this conda recipe?

### CODE REVIEW

**Comment by malb** [comment]
Hi, I have zero experience with conda, but I'm happy to make changes upstream etc. to make things easier.

**Comment by isuruf** [comment]
@malb, any idea why there are symbol not found errors [here](https://travis-ci.org/isuruf/staged-recipes/builds/199650806#L778-L787)?
If it's any help, here's the libfplll log, https://travis-ci.org/conda-forge/fplll-feedstock

**Comment by isuruf** [comment]
Related to https://github.com/fplll/fplll/commit/f372182bbe0f0597e7d6e39f8d23f18a21d1d500

**Comment by malb** [comment]
Are you using fplll 5.0.3 or a recent git revision? The check in you're referring to got in after 5.0.3

**Comment by isuruf** [comment]
I'm using 5.0.3. I added the patch here, https://github.com/conda-forge/fplll-feedstock/pull/1/files.
Travis-ci is pretty backlogged these days. I'll let you know how it goes.

**Comment by malb** [comment]
We can also cut a new release if that makes things easier

**Comment by isuruf** [comment]
@malb, any idea what is going on here, https://travis-ci.org/isuruf/staged-recipes/builds/200427654#L781-L788 ? It works fine on Linux, but fails on OSX

**Comment by malb** [comment]
Sorry, I haven't seen this error before. This is with the current master of fplll/fpylll?

**Comment by isuruf** [comment]
@malb, this is with the last releases of both fplll and fpylll.  fplll/fplll@f372182 was backported for fplll.
I'll try with the current master and let you know.

**Comment by isuruf** [comment]
@malb, I tried with the current master of both and the same error popped up.

**Comment by malb** [comment]
Can you give instructions how to reproduce the issue from a plain OSX box? Error doesn't immediately ring a bell.

**Comment by isuruf** [comment]
Steps would be,
1. Clone the following repo and checkout to the fpylll2 branch, https://github.com/isuruf/staged-recipes/tree/fpylll2
2. Run the following set of commands from the repo root. Note that this will install miniconda to `~/miniconda`

```
# Install Miniconda.
echo ""
echo "Installing a fresh version of Miniconda."
curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > ~/miniconda.sh
bash ~/miniconda.sh -b -p ~/miniconda
source ~/miniconda/bin/activate root

# Configure conda.
echo ""
echo "Configuring conda."
conda config --add channels conda-forge
conda config --set show_channel_urls true
conda install --yes --quiet conda-build-all
conda install --yes --quiet conda-forge-build-setup
source run_conda_forge_build_setup

# We just want to build all of the recipes.
export CONDA_PY=27
conda-build-all recipes/
```

**Comment by malb** [comment]
I believe to have fixed the bug upstream, can you try again?

**Comment by isuruf** [comment]
Thanks. Tests on osx are running now, I'll let you know how that goes.

Master is failing on linux with 
```

=================================== FAILURES ===================================
________________________________ test_bkz_init _________________________________

    def test_bkz_init():
        for m, n in dimensions:
            A = make_integer_matrix(m, n)
            for float_type in float_types:
                M = GSO.Mat(copy(A), float_type=float_type)
                lll_obj = LLL.Reduction(M)
>               param = BKZ.Param(block_size=3, strategies=BKZ.DEFAULT_STRATEGY)

tests/test_bkz.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/fpylll/fplll/bkz_param.pyx:456: in fpylll.fplll.bkz_param.BKZParam.__init__ (build/src/fpylll/fplll/bkz_param.cpp:7198)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: Type '<class 'int'>' of '47' not supported.

src/fpylll/fplll/bkz_param.pyx:384: TypeError
_________________________________ test_bkz_bkz _________________________________

    def test_bkz_bkz():
        for m, n in dimensions:
            if m < 2 or n < 2:
                continue
            A = make_integer_matrix(m, n)
            b00 = []
            for float_type in float_types:
                B = copy(A)
                M = GSO.Mat(B, float_type=float_type)
                lll_obj = LLL.Reduction(M)
>               param = BKZ.Param(block_size=min(m, 40), strategies=BKZ.DEFAULT_STRATEGY)

tests/test_bkz.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/fpylll/fplll/bkz_param.pyx:456: in fpylll.fplll.bkz_param.BKZParam.__init__ (build/src/fpylll/fplll/bkz_param.cpp:7198)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: Type '<class 'int'>' of '47' not supported.

src/fpylll/fplll/bkz_param.pyx:384: TypeError
```

**Comment by isuruf** [comment]
In OSX, the crash is not there anymore, but the same problem as Linux is there

**Comment by malb** [comment]
Should be fixed now.

**Comment by isuruf** [comment]
It works. Thanks. Do you have a timeline on when the next release is going to be? If it is far away, I'll try and backport this bugfix to the last release.

**Comment by isuruf** [comment]
nvm, last release with the patches from master works fine.

**Comment by isuruf** [comment]
@ocefpaf, @jakirkham, ready for review

**Comment by isuruf** [comment]
Thanks

**Comment by isuruf** [comment]
@malb, thanks for helping.

**Comment by isuruf** [comment]
@malb, linux packages are uploaded now. (OSX ones are still in a queue).

Instructions to install are for
```
conda config --add channels conda-forge
conda install fpylll
```

Python 2.7, 3.5 and Numpy 1.11, 1.12 against openblas are available.

**Comment by malb** [comment]
@isuruf Great! I've added a link to fpylll's README.

**Pull request merged**
