### PR TITLE
Add recipe for Python package rchitect.

### PR DESCRIPTION
**Pull request by jdblischak**
I created a recipe for the PyPI package [rchitect](https://pypi.org/project/rchitect/) with grayskull version 0.8.4.

xref: https://github.com/randy3k/radian/issues/244

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdblischak** [comment]
@randy3k I've started the process to add rchitect (and next radian) to conda-forge. Each recipe on conda-forge requires maintainers. Could you please comment below that you agree to be a maintainer for rchitect? It is very low maintenance because conda-forge has automated everything for standard Python packages on PyPI. Everytime you release a new version on PyPI, the conda-forge bots will automatically send a PR with the updated recipe and then merge if all the tests pass.

**Comment by randy3k** [comment]
Thank you for initiating the work.

**Comment by jdblischak** [comment]
The linux build is failing due to missing `gcc`.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=274121&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=720

```
    gcc -pthread -B /home/conda/staged-recipes/build_artifacts/rchitect_1612532665852/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Irchitect/src -I/home/conda/staged-recipes/build_artifacts/rchitect_1612532665852/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/python3.8 -c build/temp.linux-x86_64-3.8/rchitect._cffi.c -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/rchitect._cffi.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    Running setup.py install for rchitect: finished with status 'error'
ERROR: Command errored out with exit status 1: /home/conda/staged-recipes/build_artifacts/rchitect_1612532665852/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wy1kgnaq/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wy1kgnaq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-59_yrz31/install-record.txt --single-version-externally-managed --compile --install-headers /home/conda/staged-recipes/build_artifacts/rchitect_1612532665852/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/python3.8/rchitect Check the logs for full command output.
```

I am quite confused. This package clearly contains [compiled C code](https://github.com/randy3k/rchitect/tree/master/rchitect/src). Why did `grayskull pypi rchitect` mark it as `noarch: python` instead of including C compilers in the build requirements? Also, why did the macOS and Windows builds passed? Shouldn't they also have failed due to missing a C compiler?

**Comment by jdblischak** [comment]
@conda-forge/help-python-c Ready for review

**Comment by jdblischak** [comment]
@conda-forge/staged-recipes Ready for review

**Pull request merged**
