### PR TITLE
Add qt6 packages

### PR DESCRIPTION
**Pull request by jschueller**
cc @marcelotrevisani @conda-forge/qt

### CODE REVIEW

**Comment by ccordoba12** [comment]
@andfoy is working right now to update the Qt/PyQt recipes to 5.15.

So I'd say it's a good idea to wait until he finishes because then we'll have a much better foundation to start with Qt 6.

**Comment by jschueller** [comment]
good luck to @andfoy
i like the idea to split packages
seems with qt6 they're raising the requirements quickly so maybe its worth experimenting too
for now it seems I have base+svg building on both osx & linux

**Comment by marcelotrevisani** [comment]
> @andfoy is working right now to update the Qt/PyQt recipes to 5.15.
> 
> So I'd say it's a good idea to wait until he finishes because then we'll have a much better foundation to start with Qt 6.

I don't think we need to wait, if he got it working first we can create a separated branch for Qt5

**Comment by jschueller** [comment]
will fix #13573

**Comment by jschueller** [comment]
hello @ccordoba12 @andfoy @conda-forge/qt @conda-forge/pyside2,
I've got a most packages working on all platforms, plus the pyside6 bindings
What do you think ?

**Comment by jschueller** [comment]
The old patches werent needed, maybe the new cmake system makes things easy.
Did not try aarch64 or arm64 since the CI does not build it, I guess it can be enabled from the feedstock.

**Comment by jschueller** [comment]
@isuruf, what do you think ?

**Comment by isuruf** [comment]
Can we make this into one recipe with multi-outputs?

> The old patches werent needed

Please don't do this. Just because a patch is not needed at build time, doesn't mean that it's not needed.
For eg: disabling new dtags is crucial for conda binaries.

**Comment by jschueller** [comment]
@isuruf 
Ok, for the dtags flags: they have a cmake option for that now
Do you know any other mandatory change ? The other patches seem to be build-system fixes but I may be wrong.

I wanted to split this into several recipes because of the build time, with base/declarative/tools/multimedia taking ~45min,
also webengine should be big.

**Comment by ccordoba12** [comment]
I think this work should be moved to the qt-main feedstock for all libraries except webengine. Qt-main could be then a metapackage for those libraries.

**Comment by looooo** [comment]
It would be nice to have qt6 available, as it helps to make the transition to python 3.10 via pyside2. Also with qt5.15 pyside2 needs to be patched to work with python 3.10. So directly going to qt6 is the best option in my eyes.

**Comment by ccordoba12** [comment]
> these are separate recipes so they need several feedstocks isnt it ?

Not necessarily. You can build multiple packages in a single recipe, like it's done here:

https://github.com/conda-forge/gstreamer-feedstock/blob/master/recipe/meta.yaml

There you can see that the same recipe is creating packages for `gstreamer` and its plugins.

> but I still think its worthy to split into several recipes to reduce build time

Compiling all Qt libraries (except Webengine) is passing in CIs already, as you can check in `qt-main`. So I don't see much need for it, but you can still split them in multiple conda packages if you want.

**Comment by jschueller** [comment]
it would be useless to keep multiple packages into a single recipe because its still one CI job
and what about aarch64 & arm64, do these build into the time constraints ? it seems to fail atm

**Comment by ccordoba12** [comment]
Aarch64 is the only one that fails.

**Comment by jschueller** [comment]
moved to https://github.com/conda-forge/qt-main-feedstock/pull/14

**Comment by isuruf** [comment]
@jschueller, any reason, why the packages are not split anymore in https://github.com/conda-forge/qt-main-feedstock/pull/14? I'd like to see split packages.

**Comment by jschueller** [comment]
I unsplitted the packages because in the end there will be a single CI job if we get that into qt-main.

**Comment by isuruf** [comment]
True. I think your approach is better in the end as we'd be able to get cross compiling working if we have smaller components.

**Pull request closed without merging**
