### PR TITLE
Add flask multistatic

### PR DESCRIPTION
**Pull request by AdMax18**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by AdMax18** [comment]
@mxr-conda

can you comment/accept to be maintainer on this one

**Comment by AdMax18** [comment]
License not included because part of the source package

**Comment by beenje** [comment]
Why did you close https://github.com/conda-forge/staged-recipes/pull/16984 and opened a new PR?

@mxr-conda had confirmed there he wanted to be listed as maintainer, so I consider it's ok.

@conda-forge/help-python, this recipe looks good to me.

**Comment by AdMax18** [comment]
@conda-forge/help-python is it possible to get this reviewed so it can be merged soon?

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
