### PR TITLE
[R4R] add sphinxcontrib-httpexample

### PR DESCRIPTION
**Pull request by carlodri**
https://github.com/collective/sphinxcontrib-httpexample

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge/staged-recipes this can be reviewed and merged if ok, thanks!

**Comment by carlodri** [comment]
yikes! @conda-forge/core I got an unsolicited, and very angry linter review! Does this come from this https://github.com/conda-forge/conda-smithy/pull/872 issue?

**Comment by scopatz** [comment]
Yeah the linter is broken right now

**Comment by dougalsutherland** [comment]
Just to check: @conda-forge-admin, please re-lint

**Pull request merged**
