### PR TITLE
Add Deepmind/Optax

### PR DESCRIPTION
**Pull request by PhilipVinc**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
@mathss please comment here acknowledging that you will be listed as a maintainer of the recipe

> GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

**Comment by hbq1** [comment]
I agree to be listed a maintainer of this recipe.

**Comment by PhilipVinc** [comment]
@conda-forge/help-python This recipe would be ready for review, even though it's failing for `conda.exceptions.ResolvePackageNotFound` errors that I do not understand. The recipe is almost identical to https://github.com/conda-forge/chex-feedstock/blob/master/recipe/meta.yaml and has no binary dependencies.

**Comment by hbq1** [comment]
I think meta.yaml should specify v0.0.6 rather than v0.0.5?

**Comment by PhilipVinc** [comment]
I bumped the optax version, but that's not it.
It's failing during environment resolution with the error

```python
Traceback (most recent call last):
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda_build/environ.py", line 802, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 565, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/home/filippovicentini/anaconda3/lib/python3.8/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - jax[version='>=0.1.55']
  - chex[version='>=0.0.4']
  - jaxlib[version='>=0.1.37']
```

which should happen if the dependencies are not on conda, but they are.

**Comment by PhilipVinc** [comment]
The recipe works now, but fails on windows because of 
```python

**Comment by PhilipVinc** [comment]
```

Jaxlib is not available on windows, so conda should not run the build on that platform.

**Comment by PhilipVinc** [comment]
@conda-forge/help-python Why is this noarch recipe failing because of a missing dependency which does not exist on windows?

**Comment by beckermr** [comment]
We need a comment from @mtthss

**Comment by beckermr** [comment]
Ahhh nvm. LGTM!

**Pull request merged**
