### PR TITLE
Add neovim recipe (pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/staged-recipes/pull/2836

Rebased version of the content in PR ( https://github.com/conda-forge/staged-recipes/pull/2836 ). Could you please double check that this looks ok @curtisalexander?

### CODE REVIEW

**Comment by curtisalexander** [comment]
@jakirkham Yes, this looks ok. How should I address the fact that I accidentally removed the `LICENSE` file from the `staged-recipes` directory? Or will this PR supplant [#2836](https://github.com/conda-forge/staged-recipes/pull/2836)?

**Comment by jakirkham** [comment]
This is intended to supplant it.

**Comment by jakirkham** [comment]
Is it alright if I merge this @curtisalexander?

**Comment by curtisalexander** [comment]
@jakirkham Yes, feel free to merge and feel free to close [#2836](https://github.com/conda-forge/staged-recipes/pull/2836) as well.

**Comment by jakirkham** [comment]
Thanks @curtisalexander.

**Pull request merged**
