### PR TITLE
pixman: Add pixman recipe

### PR DESCRIPTION
**Pull request by jakirkham**
Adds the pixman recipe from conda recipes. ( https://github.com/conda/conda-recipes/tree/master/pixman )

@ccordoba12, as you have added some changes and it sounds like everything is moving to conda forge, I have noted you as a maintainer on this one. If you would prefer not to be, I can change it.

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs some tests. Probably can just check to see if the libraries are installed.

**Comment by pelson** [comment]
> Needs some tests. Probably can just check to see if the libraries are installed.

:+1:

**Comment by pelson** [comment]
Otherwise, once CI passes, I'm :+1:

**Comment by jakirkham** [comment]
So, has Mac/Linux tests. Not totally sure about the Windows test.

**Comment by jakirkham** [comment]
The windows build doesn't seem to work. Fine print says something about msys. As everything else is working, I am going to strip it out and rebuild. We can always try to add once there is a working copy of msys in conda.

**Comment by jakirkham** [comment]
All tests are passing. :)

**Comment by pelson** [comment]
Awesome. Thanks @jakirkham

**Comment by ccordoba12** [comment]
It's fine to leave me as a maintainer :-)

I have one question: doesn't Appveyor come with Msys? I think I read that somewhere...

**Comment by jakirkham** [comment]
Ok, thanks for confirming @ccordoba12. Sorry to be a bit sneaky here.

Maybe so. I am not as familiar with AppVeyor.

Would this result in some additional bits that we would need to distribute somehow? If so, we might want a separate package for that purpose and then add it as a runtime dependency for packages using MSYS from AppVeyor.

**Comment by ccordoba12** [comment]
Pixman needs GNU make to compile it but it doesn't need MSYS at runtime.

**Comment by jakirkham** [comment]
Ok, thanks for that info @ccordoba12. I'll look at adding this back.

**Comment by jakirkham** [comment]
Added an issue ( https://github.com/conda-forge/pixman-feedstock/issues/1 ) to track adding Windows support.

**Pull request merged**
