### PR TITLE
Added xxhash

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Closes https://github.com/conda-forge/staged-recipes/issues/4487

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@jakirkham so this seems to vendor in the xxhash c implementation.  would you prefer i call this python-xxhash ?

**Comment by jakirkham** [comment]
My preference would be to add a `python-` prefix to the Python package. That said, we could add `lib` or `c-` before the C library. There is precedent for both. What do you think?

**Comment by jakirkham** [comment]
Otherwise LGTM.

**Comment by mariusvniekerk** [comment]
@jakirkham renamed

**Comment by jakirkham** [comment]
Pushed two minor commits to drop unneeded comments.

**Comment by jakirkham** [comment]
Thanks @mariusvniekerk.

**Pull request merged**
