### PR TITLE
Apache Maven 3.3.9

### PR DESCRIPTION
**Pull request by johanneskoester**
This PR adds a recipe for the build tool Apache Maven.
Supercedes #2589 and #2580.

### CODE REVIEW

**Comment by johanneskoester** [comment]
@jakirkham this is crazy. Now it complains that circle.yml is not there:
(see [here](https://circleci.com/gh/johanneskoester/staged-recipes/30?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). But it is there.

**Comment by johanneskoester** [comment]
When I ssh into the CircleCI build, there is no source code in the staged-recipes folder...

**Comment by johanneskoester** [comment]
I think I solved it. [This](https://surendrans.wordpress.com/2014/12/01/circle-ci-fix-for-git-command-i-returned-128/) did the trick. CircleCI does not seem to be a very reliable service.

**Comment by jakirkham** [comment]
It sounds like you got really unlucky, @johanneskoester. Beyond that one user that had to go through the revoking procedure that you did, there really haven't been issues at the user level with CircleCI. Sorry you are having such a rough time. Glad to see it is turning around though.

**Comment by johanneskoester** [comment]
Good to hear that this seems to be an exception @jakirkham. Given that the windows and OSX builds went fine in commit 7cbccfc, feel free to merge this with your admin rights ;-).

**Comment by johanneskoester** [comment]
All tests have passed. @conda-forge/core could you please merge this?

**Comment by johanneskoester** [comment]
Thank you, @ocefpaf!

**Pull request merged**
