### PR TITLE
Resurrect `vs2008_runtime` and `vs2010_runtime`

### PR DESCRIPTION
**Pull request by jakirkham**
Resurrect `vs2008_runtime` and `vs2010_runtime` recipes that were proposed and merged in PR ( https://github.com/conda-forge/staged-recipes/pull/809 ). However were not generated due to PR ( https://github.com/conda-forge/staged-recipes/pull/824 ) getting merged, which had included the same content with `vs2008_runtime` and `vs2010_runtime` recipes removed. Hence this readds both recipes to properly generate packages for them in `conda-forge`.

### CODE REVIEW

**Comment by jakirkham** [comment]
@msarahan @jjhelmus @bollwyvl, if any of you could please take a look, that would be very much appreciated. 😄

**Comment by jakirkham** [comment]
Also if you have time to look @mingwandroid, would appreciate your feedback here.

**Comment by mingwandroid** [comment]
Can we hold off on this until `CB 3` is adopted? Then you can use our recipes:

https://github.com/AnacondaRecipes/aggregate/tree/master/vs2008
https://github.com/AnacondaRecipes/aggregate/tree/master/vs2010

**Comment by jakirkham** [comment]
My interest in resurrecting this now was to revitalize the `conda-forge` installer effort.

Spent a little time on the holiday pushing the installer forward. It seems `vs2008_runtime` is one missing piece for Windows Python 2.7. Also need `menuinst` for Windows generally. Everything else seems to already be packaged.

Would be fine leaving `vs2010_runtime` alone as we don't really support it in `conda-forge` any more. It would only be added for legacy reasons.

**Comment by jakirkham** [comment]
Replacing with PR ( https://github.com/conda-forge/staged-recipes/pull/4728 ) for just `vs2008_runtime`.

**Pull request closed without merging**
