### PR TITLE
Add patchelf

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a recipe to build `patchelf`. Based off of the recipe from conda-recipes. Cleaned up a bit to fit into conda-forge.

### CODE REVIEW

**Comment by jakirkham** [comment]
@mjuric @tpn, we are adding `patchelf` to [conda-forge]( https://conda-forge.github.io/ ). This is the community packaging system for use with [`conda`]( http://conda.pydata.org/docs/ ). Packages built here are built with CI and deployed to the [conda-forge channel]( https://anaconda.org/conda-forge/ ) automatically after committing on `master` of a feedstock (a repo with the recipe plus automatically maintained CI scripts). Eventually, packages submitted here will be included in the `defaults` channel after some auditing process as [mentioned]( https://github.com/conda-forge/conda-forge.github.io/issues/22#issuecomment-197117472 ). If there is anything here that you see is off or needs to be fixed, please let me know. If you would like to have access to the [patchelf feedstock/recipe]( http://github.com/conda-forge/patchelf-feedstock/ ) (not yet generated), I would happily add you to the maintainers list so you can have commit privileges for this recipe. This would be useful for updating the version for instance. Thanks again for helping put together this useful recipe.

**Comment by jakirkham** [comment]
@dan-blanchard, I saw you also contributed to this recipe for `patchelf`. Thanks for doing that. Would you have any interest in being added as a maintainer?

**Comment by mjuric** [comment]
@jakirkham Thanks, I'd be happy to help maintaining. The updated patchelf had been working well for us.

**Comment by jakirkham** [comment]
Excellent, thanks @mjuric. I will add you.

I bumped the version to 0.9 as that was released at the end of February and is not yet in the `defaults` channel so this is the newest version of `patchelf`.

**Comment by jakirkham** [comment]
This PR ( https://github.com/conda-forge/patchelf-feedstock/pull/1 ) will add you, @mjuric, as a maintainer once merged. As this is your first time being added as a maintainer, you will receive an invite to join conda-forge. Once accepted, you will be added to the patchelf team. This will give you commit privileges over this feedstock (repo). This way you can propose maintenance fixes and version updates. Just keep in mind that you must fork the feedstock (repo) and PR changes back here. Any other feedstocks (repos) that you add yourself or others add you (with permission of course) will automatically add you to the proper maintenance teams and give you commit privileges over those feedtsocks (repos) automatically and will require no action on your part going forward. If you have any questions, please don't hesitate to ask.

**Pull request merged**
