### PR TITLE
Add recipe for Modin

### PR DESCRIPTION
**Pull request by devin-petersohn**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by h-vetinari** [comment]
I'd be interested in helping with this. I can either open a new PR, or you could make me a collaborator on your fork of `staged-recipes`, @devin-petersohn?

**Comment by devin-petersohn** [comment]
Thanks @h-vetinari, I have added you as a collaborator

**Comment by h-vetinari** [comment]
Alright, cool @devin-petersohn! I'll keep your commits, of course, but if you don't mind, I'll force-push to rebase on current master.

But first, let's see what ails the CI.

**Comment by h-vetinari** [comment]
@devin-petersohn, I see that you're pinning pandas in https://github.com/modin-project/modin/blob/master/setup.py. I'm guessing this is desired for the installation through conda as well?

I.e. modin 0.7.1 *must* install pandas 0.25.3?

**Comment by h-vetinari** [comment]
Ok, this builds now, and the imports pass, but apparently, dask tries to start something awaitable that we're not waiting for, and the resulting error hangs the build (this is from a local build; it was the same in the azure logs, but I can't scroll far enough to see it anymore):

```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\asyncio\tasks.py:623> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\asyncio\tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\site-packages\distributed\nanny.py", line 242, in start
    response = await self.instantiate()
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\site-packages\distributed\nanny.py", line 325, in instantiate
    result = await self.process.start()
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\site-packages\distributed\nanny.py", line 513, in start
    await self.process.start()
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\site-packages\distributed\process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\site-packages\distributed\process.py", line 202, in _start
    process.start()
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Miniconda3\envs\builder\conda-bld\modin_1583516411818\_test_env\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by h-vetinari** [comment]
Also note there is an open PR for ray (which I've offered to support as well): #10637

**Comment by devin-petersohn** [comment]
Thanks @h-vetinari! We do pin the pandas version to guarantee the drop in replacement, because of changes in the API. 

I'm releasing a new version of Modin compatible with pandas 1.0, and it should be on pypi in an hour or two.

The Dask issue is related to trying to run Dask multiprocessing in script mode. I still am not sure that there is a simple fix to this. `import modin.pandas` also imports Dask and starts a multiprocessing environment.

Ray should be possible now that they do not also build their own arrow distribution.

Thanks again for helping with this! I'm still finalizing the release, but feel free to ping with any questions.

**Comment by h-vetinari** [comment]
> @devin-petersohn: Thanks @h-vetinari! We do pin the pandas version to guarantee the drop in replacement, because of changes in the API.
> 
> I'm releasing a new version of Modin compatible with pandas 1.0, and it should be on pypi in an hour or two.

OK, I think that means we should definitely be pinning pandas in the recipe as well, but since they're planning to follow semver starting with 1.0.0, we probably don't have to pin further down than minor-level.

**Comment by h-vetinari** [comment]
> @devin-petersohn: The Dask issue is related to trying to run Dask multiprocessing in script mode. I still am not sure that there is a simple fix to this. `import modin.pandas` also imports Dask and starts a multiprocessing environment.

Yes, I was just looking at https://github.com/modin-project/modin/blob/0.7.1/modin/pandas/__init__.py to try to understand what's happening. @conda-forge/dask can someone please advise what's best in this situation?

**Comment by TomAugspurger** [comment]
That's the standard exception you get when trying to start a subprocess at the top-level of a module: https://stackoverflow.com/questions/60232708/dask-fails-with-freeze-support-bug

**Comment by jcrist** [comment]
> I still am not sure that there is a simple fix to this. import modin.pandas also imports Dask and starts a multiprocessing environment.

Is there any way to not do this? It's generally frowned upon to do expensive things on import of a package, and allocating a dask cluster is definitely not cheap. If possible I recommend relying on users having already initialized dask themselves.

**Comment by devin-petersohn** [comment]
>Is there any way to not do this?
 
It is there as a convenience. If a Dask Client exists it will be connected to, otherwise it will start one for the user.

**Comment by TomAugspurger** [comment]
It's probably not something people actually want, otherwise distributed
would do that :)

**Comment by devin-petersohn** [comment]
@TomAugspurger It is all abstracted away from users because they do not care about what is running underneath or how. I know my users well and none of them have every even mentioned this. The advanced users will create their own environment beforehand. `distributed` cannot do this because, as middleware, it needs some configuration from the user. Modin exists at the application layer so it is reasonable to abstract away details the user doesn't care about and provide an interface for those that do.

@h-vetinari With the import tests, we can try to import using the pure non-parallel python engine, which won't start any pool of workers.  `os.environ["MODIN_ENGINE"] = "python"` before importing modin ill do it.

**Comment by h-vetinari** [comment]
@jcrist @TomAugspurger 
thanks a lot for the help!

@devin-petersohn 
We could do that - or equivalently -, patch out the start of the dask cluster. I tend to agree that this is not something for a simple library import, but it's your library. Will give this a try later.

**Comment by h-vetinari** [comment]
@devin-petersohn 
Finally got around to doing this (the ping from your new release helped ;-)).

I added some patches that should solve the problems we had last time. All but the first could be upstreamed IMO. Let me know what you think.

@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes 
Any idea why patching doesn't seem to work in appveyor anymore?
The [build](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/31299458) a month ago (with the exact same filename of the patch) had:
```
[...]
Extracting download
Applying patch: 'C:\\projects\\staged-recipes\\recipes\\modin\\patches/0001-remove-setup-requires.patch'
Trying to apply patch as-is
INFO conda_build.source:apply_patch(598): Trying to apply patch as-is
patching file setup.py
[..]
```
whereas now I get:
```
[...]
Extracting download
Applying patch: 'C:\\projects\\staged-recipes\\recipes\\modin\\patches/0001-remove-setup-requires.patch'
Trying to apply patch as-is
INFO conda_build.source:apply_patch(598): Trying to apply patch as-is
Traceback (most recent call last):
  File ".ci_support\build_all.py", line 135, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support\build_all.py", line 125, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2868, in build_tree
    notest=notest,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1925, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 639, in try_download
    source.provide(metadata)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\source.py", line 700, in provide
    apply_patch(src_dir, join(metadata.path, patch), metadata.config, git)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\source.py", line 599, in apply_patch
    check_call_env([patch] + patch_args, cwd=src_dir, stdout=stdout, stderr=stderr)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 395, in _func_defaulting_env_to_os_environ
    subprocess.check_call(_args, **kwargs)
  File "C:\Miniconda36-x64\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Miniconda36-x64\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Miniconda36-x64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Miniconda36-x64\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Command exited with code 1
```

**Comment by h-vetinari** [comment]
Interestingly, appveyor and the azure windows agent are timing out while trying to download from PyPI (reproducibly).

**Comment by devin-petersohn** [comment]
Thanks @h-vetinari, I will take it from here.

There are some updates you have made that I do not agree with, including adding yourself as a maintainer of the build. Since you have never contributed directly to Modin I would not feel comfortable adding you as a maintainer of the conda forge build.

I appreciate your help in this process so far. I will be removing your push access to the repo and will take over from here. Thank you again for pushing things along!

**Comment by h-vetinari** [comment]
> There are some updates you have made that I do not agree with, including adding yourself as a maintainer of the build. Since you have never contributed directly to Modin I would not feel comfortable adding you as a maintainer of the conda forge build.

Shared recipe maintainership is extremely common (and helpful), and has nothing to do with how modin itself is developed. Fair enough that you have a different opinion on some of the choices I made, that's precisely why I asked you. I don't think it's a measured reaction...

Note: after changing the source urls, the hash needs to be updated too (my push of that just failed): `b6bcea0589a6b2c2b2f9cc3e0cb8c265340275601294132ff9be45c1be91e1ff`

**Comment by h-vetinari** [comment]
PS. I spent more than half my day working towards picking up #10637 again (so we could use ray for modin in conda as well), but with such an attitude, I'm in no mood to continue contributing.

**Comment by mrocklin** [comment]
I suspect that @devin-petersohn just may not be familiar with conventions around distribution channels, and that nothing personal was meant by it. 

Devin, it's quite common for folks other than maintainers to maintain distribution channels.  It ends up being a different skill set and it's a thankless job.  For example, for channels like Debian or the Anaconda defaults conda channel I personally don't even have rights for the Dask packages.  Other folks manage it.  I encourage you to relax constraints here and accept an "all the help you can get" approach until that burns you (which i suspect it never will).

Now I'm going to disappear back into the ether ... good luck all

**Comment by devin-petersohn** [comment]
@mrocklin You are correct, I wasn't aware that other-than-maintainers commonly maintained the distribution channels for open source projects.

@h-vetinari I apologize that it appeared as if there was some hostility attached to the comments above, I did not intend to offend or appear as if I had an attitude. I was surprised to see you added yourself and acted in defense of the build, I am sensitive to such security and access-related concerns. It was not personal and I hope you will see that.

I would prefer to discuss your role offline, if you are still willing and interested. Feel free to reach out to devin@eecs.berkeley.edu and we can go from there.

**Comment by h-vetinari** [comment]
No harm done. I intended no hostility in return. Will write per mail.

Thanks @mrocklin for the kind words!

**Comment by devin-petersohn** [comment]
Close and continue with #11161

**Pull request closed without merging**
