### PR TITLE
Added recipe for leidenalg.

### PR DESCRIPTION
**Pull request by vtraag**

### CODE REVIEW

**Comment by vtraag** [comment]
Ping @conda-forge/staged-recipes

**Comment by vtraag** [comment]
I'm not sure if anybody @conda-forge/staged-recipes could take a look at this PR and merge it?

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes

**Comment by scopatz** [comment]
Thanks @vtraag!

**Comment by emkahuda** [comment]
Hi, I tried to install Louvain package but failed. When I tried to solve this issue I got information that one will be a better choice is to use Leiden package instead. I have no idea how to install it. I tried installing it using "pip3 install leidenalg" and got "Could not download and compile the C core of igraph".  Then I tried to install "brew install igraph" and
"pip -v install python-igraph==0.7.1.post6", as well as "sudo python setup.py develop --c-core-url https://github.com/igraph/igraph/archive/master.tar.gz" (can't )but still it didn't work. Could anyone help since I have no idea about this something new (I am a new user of python). Thank you very much.

**Comment by scopatz** [comment]
Hi there @emkahuda - So when you use pip or brew, you often need to have a full development environment set up, including C, C++, and sometimes even Fortran compilers.  

This package here is for the conda package manager on the community developed `conda-forge` channel. You can install conda (and its Python distribution) here: https://conda.io/en/latest/miniconda.html and configure it to use conda-forge with instructions here: http://conda-forge.org/#about

**Pull request merged**
