### PR TITLE
Add recipe gepetto-viewer-corba

### PR DESCRIPTION
**Pull request by ymontmarin**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jcarpent** [comment]
Fine for me to appear on the list of mainteners.

**Comment by jcarpent** [comment]
@conda-forge-admin, please restart ci

**Comment by jcarpent** [comment]
Seems to work well. Nice fix @ymontmarin!

**Comment by jcarpent** [comment]
@ymontmarin Do you think that the recipe should be cleaned from all the 'cdt' ?

**Comment by ymontmarin** [comment]
@jcarpent Yes, I just pushed a version with simplified recipe now that the fix work: namely removed run cdt and yum_requirements. Build cdt are needed to build against gepetto.
I also add proper testing of the DL.

If checks pass, I think the PR is ready to merge. Do you agree ?

**Comment by jcarpent** [comment]
It seems you removed by mistake the patch.

**Comment by ymontmarin** [comment]
@conda-forge/help-c-cpp, I think this PR is now ready to merge ! Thank you

**Comment by jcarpent** [comment]
@wolfv If you have time to review this PR, we would really appreciate it. Thanks in advance.

**Comment by wolfv** [comment]
congrats!

**Comment by jcarpent** [comment]
Thank you very much for fast merging!

**Pull request merged**
