### PR TITLE
segregation package: update to 1.1.0 version

### PR DESCRIPTION
**Pull request by renanxcortes**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by renanxcortes** [comment]
@knaaptime and @sjsrey, please comment here if you're fine to be a maintainer of segregation.

**Comment by renanxcortes** [comment]
@conda-forge/core could you double-check if the conflict is a bug? I don't see how this commit could be causing the checks to fail. Also, please let me know how could I help if I am missing something,

**Comment by renanxcortes** [comment]
Closing this PR in favor of https://github.com/conda-forge/segregation-feedstock/pull/1.

**Comment by jakirkham** [comment]
In general we just submit PRs to feedstocks to make updates. Thanks for helping keep things up-to-date. Please consider adding yourself as a maintainer on that feedstock if it is of interest. 🙂

**Pull request closed without merging**
