### PR TITLE
Add recipe for concurrent-log-handler (a maintained for of ConcurrentLogHandler)

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Guessing ez_setup probably needs to be patched out of the setup.py

**Comment by scopatz** [comment]
Or maybe just added to conda-forge. It does sound like they intended to build with it

**Comment by mariusvniekerk** [comment]
Added a patch since using ez_setup failed in fun antique horrible ways.  Noarch so only linux matters.  Rest complain about not being able to apply the patch

**Comment by scopatz** [comment]
Thanks @mariusvniekerk

**Pull request merged**
