### PR TITLE
pyfilesystem2

### PR DESCRIPTION
**Pull request by ReimarBauer**
version 2.0.10

### CODE REVIEW

**Comment by ReimarBauer** [comment]
py3.6 issue

```
TEST START: /staged-recipes/build_artefacts/linux-64/pyfilesystem2-2.0.10-py36_0.tar.bz2
Deleting work directory, /staged-recipes/build_artefacts/pyfilesystem2_1506436672412/work/pyfilesystem2-2.0.10
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1530, in build_tree
    test(pkg, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1336, in test
    create_env(config.test_prefix, specs, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 675, in create_env
    actions = install_actions(prefix, index, specs)
  File "/opt/conda/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/opt/conda/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 809, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 864, in solve
    self.find_conflicts(specs)
  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - pyfilesystem2 2.0.10 py36_0
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build-all", line 6, in <module>
    exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build_all/cli.py", line 93, in main
    b.main()
  File "/opt/conda/lib/python3.6/site-packages/conda_build_all/builder.py", line 277, in main
    built_dist_location = self.build(meta, build_config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build_all/builder.py", line 209, in build
    conda_build.api.build(meta.meta, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1549, in build_tree
    .format(recipe) + error_str + "\n" + extra_help)
RuntimeError: Can't build {'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7fbb0cd6bba8>, 'meta_path': '/root/conda-recipes/pyfilesystem2/meta.yaml', 'path': '/root/conda-recipes/pyfilesystem2', 'requirements_path': '/root/conda-recipes/pyfilesystem2/requirements.txt', 'meta': {'package': {'name': 'pyfilesystem2', 'version': '2.0.10'}, 'source': {'fn': 'pyfilesystem2-2.0.10.tar.gz', 'url': 'https://github.com/PyFilesystem/pyfilesystem2/archive/v2.0.10.tar.gz', 'sha256': '3c5d600d1b1fbc78e05c61a9c7f1fc9c175128b1ea2f3a9dd829e7c3c9fafde0'}, 'build': {'number': '0', 'script': 'python setup.py install --single-version-externally-managed --record record.txt'}, 'requirements': {'build': ['python', 'setuptools'], 'run': ['python', 'setuptools', 'appdirs 1.4.0', 'enum34 1.1.6', 'pytz', 'six 1.10.0']}, 'test': {'imports': ['fs']}, 'about': {'home': 'https://github.com/PyFilesystem/pyfilesystem2', 'license': 'MIT', 'license_family': 'MIT', 'license_file': 'LICENSE', 'summary': "Python's filesystem abstraction layer", 'description': '\nWork with files and directories in archives, memory, the cloud etc. as easily as your local drive. Write code now, decide later where the data will be stored; unit test without writing real files; upload files to the cloud without learning a new API; sandbox your file writing code; etc.\n', 'doc_url': 'https://docs.pyfilesystem.org/en/latest/', 'dev_url': 'https://github.com/PyFilesystem/pyfilesystem2'}, 'extra': {'recipe-maintainers': ['ReimarBauer'], 'final': True}}} due to environment creation error:
The following specifications were found to be in conflict:
  - pyfilesystem2 2.0.10 py36_0
Use "conda info <package>" to see the dependencies for each package.

Exited with code 1
```

**Comment by ReimarBauer** [comment]
conda search enum34 | grep 1.1.6
enum34                       1.1.6                    py27_0  conda-forge     
                             1.1.6                    py34_0  conda-forge     
                             1.1.6                    py35_0  conda-forge     
                             1.1.6                    py27_1  conda-forge     
                          *  1.1.6                    py27_0  defaults

**Comment by synapticarbors** [comment]
This appears to duplicate the effort already underway in https://github.com/conda-forge/staged-recipes/pull/3922

If you would like to be involved with maintaining this package on conda-forge, I recommended pinging that PR.

**Comment by ReimarBauer** [comment]
Thx @synapticarbors added a note there, lets see how far this setup runs.

**Comment by ReimarBauer** [comment]
Appveyor has the idna issue for this package too

**Comment by ocefpaf** [comment]
@ReimarBauer this is the same as `fs`, from #3922, right? Let's close as a duplicate and you can add yourself to the `fs` team when the feedstock is created.

**Pull request closed without merging**
