### PR TITLE
Add PyPI package reportseff

### PR DESCRIPTION
**Pull request by jdblischak**
* https://pypi.org/project/reportseff/
* https://github.com/troycomi/reportseff
* recipe created with grayskull 2.1.0

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdblischak** [comment]
@troycomi I created a recipe for your package `reportseff` and submitted it to conda-forge. If you'd like to be a recipe co-maintainer, please comment below. Being a [recipe maintainer](https://conda-forge.org/docs/maintainer/updating_pkgs.html) is low maintenance. A bot auto-opens a PR whenever you push a new update to PyPI. As long as the package dependencies don't change, all you have to do is click to merge the PR once the tests have passed.

**Comment by jdblischak** [comment]
Does `grayskull` not have the equivalent flag `--noarch-python` as `conda skeleton pypi` has? This seems like it should be a noarch recipe to me

**Comment by jdblischak** [comment]
@conda-forge/help-python PyPI recipe ready for review

**Comment by troycomi** [comment]
Hi @jdblischak you can add me as a co-maintainer.

**Comment by jdblischak** [comment]
@conda-forge/staged-recipes PyPI recipe ready for review

**Pull request merged**
