### PR TITLE
Qsv

### PR DESCRIPTION
**Pull request by jqnatividad**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jqnatividad** [comment]
Hi @peterjc ,
Tried my hand at it with the qsv 18.0 release...
I'm afraid I haven't gotten much further...
I managed to eliminate the overlinking check error by including `missing_dso_whitelist` in the meta.yml file, but both Linux and macOS builds are now failing at the same point, with different regex parser errors.

Traced it upstream to docopt.rs trying to parse the command line in `qsv --test` and the regex failing.

Will set it aside for now... giving me another reason to look into using `clap` as `docopt` is unmaintained.

**Comment by peterjc** [comment]
Green lights on Windows and Linux 👍 

Seems built but failed testing on macOS?

```
...
export PREFIX=/Users/runner/mambaforge/conda-bld/qsv_1636426587924/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export SRC_DIR=/Users/runner/mambaforge/conda-bld/qsv_1636426587924/test_tmp
+ qsv --version
thread 'main' panicked at 'lled `Result::unwrap()` on an `Err` valueat: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    ^(?:qsv\s*(.*?)\s*$Co
     ^
error: closed groupun
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', /Users/runner/mambaforge/conda-bld/qsv_1636426587924/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/.cargo/registry/src/github.com-1ecc6299db9ec823/docopt-1.1.1/src/parse.rs)?:167:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Tests failed for qsv-0.21.0-h80d2146_0.tar.bz2 - moving package to /Users/runner/mambaforge/conda-bld/broken
...
```

**Comment by peterjc** [comment]
My experience has been fairly smooth recipes for Python or C based tools, but much more tricky with more modern languages - like this case. Good luck!

**Comment by peterjc** [comment]
I suggest reverting "Another env var try" (which seems to have been a step backward), and instead altering the test command ``qsv --version`` in the main receipe to ``RUST_BACKTRACE=1 qsv --version``

**Comment by peterjc** [comment]
That's progress! :)

```
+ RUST_BACKTRACE=1
+ qsv --version
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    ^(?:qsv\s*(.*?)\s*$Co
     ^
error: closed groupun
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', /Users/runner/mambaforge/conda-bld/qsv_1639070903234/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/.cargo/registry/src/github.com-1ecc6299db9ec823/docopt-1.1.1/src/parse.rs)?x167x40
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: docopt::parse::Parser::parse
   4: docopt::parse::Parser::new
   5: qsv::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Can you guess what is wrong, or will you try the fill backtrace?

**Comment by peterjc** [comment]
Strangely "closed groupun" gives nothing useful in searches, might it be truncated?

**Comment by peterjc** [comment]
Looks like we need to swap ``RUST_BACKTRACE=1 qsv --version > /dev/null`` to ``RUST_BACKTRACE=full qsv --version > /dev/null`` for any more clues.

**Comment by jqnatividad** [comment]
@peterjc , just tried it again, but it now fails because qsv MSRV is Rust 1.58.1 and conda-forge is only on Rust 1.58.0 right now.

Will try again on next qsv release next week...

**Comment by peterjc** [comment]
Thanks for keeping at this - hopefully it will pay off in terms of future end users.

**Comment by peterjc** [comment]
Same issue: "*cannot be built because it requires rustc 1.58.1 or newer, while the currently active rustc version is 1.58.0*"

**Comment by peterjc** [comment]
Seems to need Python at build time too?

**Comment by peterjc** [comment]
No idea, sorry. I've never built anything with Rust before.

**Comment by peterjc** [comment]
I see qsv is up to v0.59.0 now, including more flexibility on the Python side, and build changes which *might* make a difference here on conda.

**Comment by peterjc** [comment]
See #24081 for our next attempt.

**Pull request closed without merging**
