### PR TITLE
Add pytools

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://pypi.python.org/pypi/pytools. (Pytools is a PyOpenCL dependency.)

### CODE REVIEW

**Comment by jakirkham** [comment]
Does this mean you are packaging PyOpenCL?

**Comment by ocefpaf** [comment]
Maybe... :wink:

**Comment by jakirkham** [comment]
@inducer, just letting you know that we have added `pytools` to [conda-forge]( http://conda-forge.github.io/ ). This will allow users to easily install this with [`conda`]( http://conda.pydata.org/docs/ ) ( [`conda install -c conda-forge pytools`]( http://anaconda.org/conda-forge/pytools ) ). The maintenance burden here is light as all releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this feedstock (repo)]( https://github.com/conda-forge/pytools-feedstock ). If you have any interest in being added as a maintainer (useful for making new releases for instance), we would be more than happy to add you to the maintainers list.

**Comment by inducer** [comment]
Sure, I'd be happy to be along for the ride, although I'd likely only jump in in an emergency. At any rate, thanks for packaging `pytools`, and thanks for letting me know!

**Comment by jakirkham** [comment]
Thanks @inducer. It's great to have you on-board. Please see this PR ( https://github.com/conda-forge/pytools-feedstock/pull/1 ), which will add you to `pytools`.

**Pull request merged**
