### PR TITLE
Skip feedstocks that fail CI registration

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/staged-recipes/issues/915

Ideally we would run the full conversion process on each recipe independently. That way we are guaranteed to bank our progress with each one. So if something goes wrong with the conversion of one recipe, it doesn't cost us our progress. However, this appears not to work due to some issues with doing the full Travis CI sync. Still that does not lessen the need for some ability to do partial conversions.

The biggest driver for this is that CI registration can be flaky sometimes. While the ideal solution would be to figure out the underlying CI issue and solve the problem or at least workaround it, in practice this is a challenging ask. There are many reasons for this, but they ultimately hinge on the fact that we don't know how the CIs are doing things under the hood and so we can't be sure what corner cases we might be hitting. The other is that we are only one group of users on these very popular services. So we may need to wait in the queue for
awhile until we actually get time spent on our issue. In the interim, these CI issues persist. Improved resilience on our part will help limit our vulnerability.

In order to solve this issue, we implement the simplest way to bank our progress during feedstock conversion. Basically if a feedstock fails CI registration, we note the failure and skip over it. This way if it is something funny with that feedstock we can still get the other ones out so we can look at that one more closely. However, if it is something else like a limitation on how many we can process at a time, we can at least get a few out so that we will have less to work through next time. Once we have tried to convert and remove everything, we then mark the build as failed. This way we are alerted to the fact there is a problem still, but we have cut down the amount of work that we have to do. Perhaps a simple restart will be sufficient. Especially with PR ( https://github.com/conda-forge/staged-recipes/pull/1373 ). 😉

### CODE REVIEW

**Comment by pelson** [comment]
But doesn't this result in recipes being deleted even if they haven't been converted? That doesn't sound good...

**Comment by jakirkham** [comment]
Nope shouldn't. Deletion is later in the same `for`-loop. As we `continue`, we should skip everything else for that recipe in that loop.

**Comment by jakirkham** [comment]
FYI here's the [deletion line]( https://github.com/jakirkham/staged-recipes/blob/82d15c2944b1647a08d18243738171c71199ebcb/.CI/create_feedstocks.py#L243 ). Tried to link the line in the diff, but GitHub dropped the ball on showing the line.

**Comment by jakirkham** [comment]
In the light of the comments above, does this now make sense? If not, please ask more questions.

Otherwise it would be nice if we either merge or close this. If close, please propose another solution to issue ( https://github.com/conda-forge/staged-recipes/issues/915 ) as this problem hurts. Just was affected by it again today.

**Comment by jakirkham** [comment]
Thoughts on this, @pelson? Any more questions? What can we do so that we can fix this problem?

**Comment by jakirkham** [comment]
Toggled to test another case with the linter to see if it would pick up the conversion pending recipes, which it did not. Further evidence that PR ( https://github.com/conda-forge/conda-forge-webservices/pull/53 ) is working as intended.

**Comment by jakirkham** [comment]
Oops. Sorry for the noise.

**Comment by jakirkham** [comment]
As a demo of this behavior please see this [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/164296585 ) that converted on recipe and then failed to convert any others. This [subsequent build]( https://travis-ci.org/conda-forge/staged-recipes/builds/164297880 ) was then triggered after doing a partial conversion.

**Pull request merged**
