### PR TITLE
Add recipe for goodtables-pandas-py 0.1.1

### PR DESCRIPTION
**Pull request by ezwelty**
@conda-forge/help-python

Source: https://pypi.org/project/goodtables-pandas-py/0.1.1

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Thank you in advance for your review!

### CODE REVIEW

**Comment by ezwelty** [comment]
I'm puzzled by the error raised by all tests:

```bash
goodtables 2.5.2 requires statistics, which is not installed.
```

`statistics` is part of the standard python library (https://docs.python.org/3.8/library/statistics.html). How can it not be installed?

**Comment by zaneselvans** [comment]
The statistics dependency is a weird holdover from Python 2 IIRC. I have statistics 1.0.3.5 installed via `pip` and it's described as "A Python 2.* port of 3.4 Statistics Module" but I think it shouldn't be required anymore since it's only a Python 2.x thing.  It looks like it's been removed from the [frictionless-py requirements](https://github.com/frictionlessdata/frictionless-py/blob/master/setup.py) in but is still listed as a requirement in the [conda-forge packaging](https://github.com/conda-forge/goodtables-feedstock/blob/master/recipe/meta.yaml) for goodtables. I'll ping @roll here and make an issue over in the frictionless repo.

**Comment by roll** [comment]
Hi @ezwelty, @zaneselvans,

I had the same error (super confusing) trying to publish `frictionless` until I realized that `statistics` is not needed for Python3. 

The problem that `goodtables` needs this as it's Python2 compatible. TBH I don't understand how goodtables recipe works if it doesn't work for other recipes.

Maybe we can ask for assistance from the Conda's Python team.

BTW have you considered migrating the project to Frictionless?

**Comment by ezwelty** [comment]
@roll My guess here is that the issue is not the use of `statistics` for Python 2 support, but that `statistics` is not flagged as being applicable only to Python 2. I see comment syntax like `# [py<3]` in some recipes (e.g. [coconut](https://github.com/conda-forge/coconut-feedstock/blob/234b5d3e57f8ce4d01526a4564361ba75cb20216/recipe/meta.yaml#L34), but can't it mentioned in the `conda-forge` documentation, so it may not change how the recipe is interpreted.

**Comment by roll** [comment]
@ezwelty 
Let's ask for help :smiley:  My first time I was publishing a package here Conda folks really helped me

**Comment by ezwelty** [comment]
@roll I like help :) Where does one find `@conda-forge/help-python` ?

Actually, just found it under "selectors": https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=selectors#preprocessing-selectors
It might be enough to flag your `statistics` line as Python 2 only using `# [py2k]`.

**Comment by zaneselvans** [comment]
Ah, it won't let you tag @conda-forge/help-python unless you've already contributed to the repo.

I think you're right though @ezwelty about using the `[py2k]` selector -- I've seen those applied to other sections of the recipes, and it does look like the python version selection is common in the requirements sections of many recipes.

**Comment by roll** [comment]
@ezwelty 
It's marked - https://github.com/conda-forge/goodtables-feedstock/edit/master/recipe/meta.yaml

Maybe it's possible to publish `goodtables-pandas` just for Py3?

**Comment by ezwelty** [comment]
@roll Darn, I thought I was onto an easy fix with the `py2k`! And yeah, already flagged as Python 3 only, with `python >=3.6,<4.0` in the recipe. The CI tests that failed are for Python 3.8.6. So I'm back to being puzzled why the dependencies work out with `pip` and `poetry` but break for `conda build`.

**Comment by ezwelty** [comment]
@roll I'm looking at migrating to `frictionless` as a longer term fix, but as written, `frictionless.validate` provides no way that I can find to limit the number of table rows validated by `frictionless.validate_table`. Even if I limit the errors to just, say, `missing-header`, it goes through every row of the table, even though it has already found the header. `goodtables-pandas` currently uses `goodtables.validate(..., row_limit=0)` to avoid checking rows past the header, then proceeds with `pandas` to check the body of the file. Could a similar option be added to `frictionless.validate`?

**Comment by roll** [comment]
Hi @ezwelty,

This kind of options is now grouped as Table Query - https://colab.research.google.com/drive/1is_PcpzFl42aWI2B2tHaBGj3jxsKZ_eZ#scrollTo=mt6TqSTlyAxb

BTW Feel free to create an issue of missing functionally that blocks you and I will add it to Frictionless (if the above doesn't help)

**Comment by roll** [comment]
Also, I think you can drop the `validate` call completely if you just need a header validation. You can do something like this:

```python
from frictionless import Resource

resource = Resource(path='table.csv')
header = resource.read_header() # will not read more that a data sample
header.errors # will have all the header errors (goodtables-like error with code/message/etc)  
```

**Pull request closed without merging**
