### PR TITLE
add conda-dev

### PR DESCRIPTION
**Pull request by cshaley**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by cshaley** [comment]
@conda-forge/help-python I think this is ready to merge.  Can someone please review when available?

**Comment by isuruf** [comment]
@conda-forge/core, do we have a `conda dev` command already?

**Comment by jaimergp** [comment]
We have `conda develop`, which might be confusing?

**Comment by cshaley** [comment]
Issue driving of creation of this package: https://github.com/conda/conda/issues/6788

Should I just give this a completely unrelated-to-conda name, given there isn't necessarily intent for it to become a core part of conda or to evolve beyond a few steps past where its at?  I just wanted an easy way to install dev/test dependencies from meta.yaml into a conda environment for local development purposes, so I packaged code linked to in the above issue.  And conda / conda-develop don't solve for that problem, and from reading threads it sounds like they don't intend to.

**Pull request closed without merging**
