### PR TITLE
add DateTime

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes -- this PR is ready for review.

**Comment by isuruf** [comment]
`datetime` is a terrible name for a python package due to the `datetime` module builtin.

cc @conda-forge/core

**Comment by synapticarbors** [comment]
I know, but it's a missing dependency from `pycaret`, which we have on `conda-forge`.

**Comment by isuruf** [comment]
Looks like `pycaret` want `datetime` from python builtin and not this `DateTime` package.

**Comment by synapticarbors** [comment]
That's what I said after grep'ing through the source code in the linked issue, but the developer seems to indicate that it's needed.

@pycaret -- can you clarify the need for this package?

**Comment by scopatz** [comment]
I think the name is not ideal, but it is not that bad. It is not a CoC violation in any way.

**Comment by beckermr** [comment]
Agreed. @synapticarbors seemed to indicate some confusion on which package is needed.

**Comment by synapticarbors** [comment]
We can put this on hold until @pycaret clarifies the need for this. There's a lot of confusion over at https://github.com/pycaret/pycaret/issues/21 that I've tried to clarify, but it's not clear if it's been fully digested. It seems like this package has a very specific use case and it's not clear if the `pycaret-feedstock` actually needs it (it's hard to tell as someone who doesn't use it combined with the non-informative import tests).

**Comment by jakirkham** [comment]
Did we have any luck working with upstream on naming?

**Pull request closed without merging**
