### PR TITLE
Add itk-core

### PR DESCRIPTION
**Pull request by thewtex**
This is the first package that breaks down the *itk* monolithic package
into smaller dependent packages. Based on the package breakdown on PyPI,
this gives users more flexibility over what to install, and it should
help avoid conda-forge CI timeouts.

@conda-forge/help-python
@ericdill 
@scopatz 
@msarahan 
@ocefpaf 
@mariusvniekerk 
@hmaarrfk

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
could we avoid repacking the wheels and build this instead ?

**Comment by hmaarrfk** [comment]
I second marius' comment. I am curious to see how one can actually build itk.

**Comment by thewtex** [comment]
We cannot build directly because we will run into build timeouts, even with Azure Pipelines.

**Comment by mariusvniekerk** [comment]
How long does a build take?

**Comment by thewtex** [comment]
We currently have CI builds on Azure for Python (see the README here for links):

https://github.com/InsightSoftwareConsortium/ITK

These include C++ test builds, which add ~1HR, which could be removed. But they are already clocking in at:

Linux - 5.5 hours
macOS - 2.5 hours
Windows - 1.5 hours -- this only includes the "Core" group because all groups were exceeding the 6 hour Azure Pipelines limit.

This is for a single version of Python.

**Comment by hmaarrfk** [comment]
Why is Linux taking so much longer?

**Comment by thewtex** [comment]
I think the Linux VM just has fewer than the macOS VM. On Windows, I suspect the speed of MSVC is the issue.

**Comment by hmaarrfk** [comment]
I see. Yeah. Itk was taking for ever to build for me too when I tried a year ago.

I wouldn't delete this recipe, but the beauty of doing this through the conda-forge sactionned compilers is that we are also working to port it to non standard architectures. 

Maybe we can try to launch some builds and see how far they go. You can maybe try to skip 2.7 and 3.6 here and just build 3.7. In the feedstock, you can worry about doing the multi platform builds separately.

**Comment by thewtex** [comment]
It may take a while because [the current package build configuration](https://github.com/InsightSoftwareConsortium/ITKPythonPackage) is set up to build the entire toolkit in one pass, then generate the separate sub-packages, i.e. *itk-core*, *itk-filtering*, *itk-segmentation*, etc. from the same build tree.

**Comment by scopatz** [comment]
Maybe we could just add it to our secret machines?

**Comment by thewtex** [comment]
An update:

WIP to build from source is here:

 https://github.com/thewtex/itk-core-feedstock-dev

Todo: the Windows configuration.

**Comment by thewtex** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
