### PR TITLE
Add termcolor2 recipe

### PR DESCRIPTION
**Pull request by saibhargav1508**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

I am willing to be maintained as the contributor to this recipe.

### CODE REVIEW

**Comment by saibhargav1508** [comment]
@conda-forge/help-python Could you please review this PR
I am willing to be listed as the maintainer

**Comment by dopplershift** [comment]
I don't understand, where did this license file come from? It's not contained in the upstream repository.

**Comment by synapticarbors** [comment]
It's probably best to use another one of the author's MIT license files for reference:

https://github.com/v2e4lisp/pdf417-text-mode-decoder/blob/master/LICENSE

but ideally, it would be from the upstream source.

**Comment by dopplershift** [comment]
I'm not sure that's an "ideally". While the upstream `setup.py` says "MIT", you need a written license that actually spells out the terms of the copyright. It's my understanding that without it, the assumption is that nobody has any rights--I don't think pulling from a separate work is a legally defensible strategy. I'll defer to somebody else here, though.

**Comment by saibhargav1508** [comment]
since termcolor2 is a wrapper on termcolor, then is it ok to add termcolor's license file here because the author does not have any license file for this package

**Comment by synapticarbors** [comment]
I don't think using another package's license in place of the one that would be included with this one is the right thing to do. 

I've opened an issue (https://github.com/v2e4lisp/termcolor2/issues/2) to hopefully resolve it, although this project doesn't look like it is actively maintained (it's a single file package, so there's not a lot to maintain, so it's understandable).

**Comment by saibhargav1508** [comment]
Hello @synapticarbors Just wanted to know what to do, hypothetically, if the author doesn't respond to the issue even after 2-3 weeks.
Background: I'm running a script which mirrors packages from conda forge to an environment.

So, if the termcolor2 recipe can't be added, I will start looking for alternate packages.

**Comment by synapticarbors** [comment]
The package author just added a license to the upstream repository so you can use that now:

https://github.com/v2e4lisp/termcolor2/blob/master/LICENSE

**Comment by saibhargav1508** [comment]
Thank you @synapticarbors 
Changed the license file accordingly

**Pull request merged**
