### PR TITLE
Add sage-flatsurf

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@slel @videlec: Could you please state here that you are fine with being maintainers of this (or say otherwise, and I'm happy to remove you)

**Comment by videlec** [comment]
fine

**Comment by saraedum** [comment]
@videlec: Any clue why this would not work:
```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/test_tmp/run_test.py", line 2, in <module>
    import flatsurf
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/flatsurf/__init__.py", line 3, in <module>
    from .geometry.polygon import polygons
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/flatsurf/geometry/polygon.py", line 36, in <module>
    from sage.categories.fields import Fields
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/sage/categories/fields.py", line 23, in <module>
    import sage.rings.ring
  File "sage/rings/ring.pyx", line 2199, in init sage.rings.ring (build/cythonized/sage/rings/ring.c:21900)
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/sage/categories/algebras.py", line 26, in <module>
    from sage.categories.associative_algebras import AssociativeAlgebras
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/sage/categories/associative_algebras.py", line 13, in <module>
    from sage.categories.magmatic_algebras import MagmaticAlgebras
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/sage/categories/magmatic_algebras.py", line 20, in <module>
    from sage.categories.modules import Modules
  File "/home/conda/feedstock_root/build_artifacts/sage-flatsurf_1565295793007/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/sage/categories/modules.py", line 26, in <module>
    from sage.categories.fields import Fields
ImportError: cannot import name Fields
```

**Comment by saraedum** [comment]
Probably wrong import order in SageMath.

**Comment by saraedum** [comment]
The usual `import sage.all` did not help here.

**Comment by slel** [comment]
Fine.

**Comment by saraedum** [comment]
@isuruf: Since this is SageMath related, you might want to have a look?
I first wanted to skip for Windows but since this should really be `noarch: python`, I guess it's fine that testing fails on Windows since a dependency cannot be satisfied?

**Comment by saraedum** [comment]
@conda-forge/help-python @isuruf: What's the right way to forward the Python limitations of surface-dynamics here (it does not support Python 3.5)? Add it to host & run as done here? Or only to one of the two? Or should I somehow use `skip`?

**Comment by saraedum** [comment]
Apart from that, this is ready for review.

**Comment by saraedum** [comment]
The patch is upstreamed at https://github.com/videlec/sage-flatsurf/pull/15 btw.

**Comment by isuruf** [comment]
> What's the right way to forward the Python limitations of surface-dynamics here (it does not support Python 3.5)? Add it to host & run as done here?

Yes, add it to host and run

**Comment by isuruf** [comment]
I mean you can add `surface-dynamics` to `host` and `run` without `python` constraints and it should work.

**Pull request merged**
