### PR TITLE
Add sounddevice

### PR DESCRIPTION
**Pull request by chohner**

### CODE REVIEW

**Comment by chohner** [comment]
Is there a straightforward way to have [portaudio](http://www.portaudio.com) available on the CI machines?

**Comment by kastman** [comment]
Funny, just fighting with this on #2216 yesterday. Commenting to follow this discussion.

I found a travis config from [Julia wrappers for portaudio](https://github.com/JuliaAudio/PortAudio.jl/blob/master/.travis.yml) that look like they don't actually use them on travis, so I"m guessing no, but maybe there's a way?

**Comment by chohner** [comment]
Ah nice! I think both libs also do very similar things.

`conda install portaudio` does fetch the dylibs on my osx machine and places them in `_t_env/lib/libportaudio.dylib` but unfortunately cffi can't seem find them there. Not sure how to make it discoverable except explicitly setting something like `DYLD_LIBRARY_PATH` which is probably not a good way.

**Comment by kastman** [comment]
Just out of curiosity, did you ever get anywhere? I'm assuming not since this PR is still open like mine is, but I thought I'd check since I'm swinging back to a number of others.

**Comment by chohner** [comment]
No news but I haven't really looked into it again to be honest. Anything on your end?

**Pull request closed without merging**
