### PR TITLE
r packages from cran

### PR DESCRIPTION
**Pull request by jsignell**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jsignell there some lints in these recipes that need addressing but before you do here are two things we need to consider:

- conda-forge should be able to handle R packages but we neve did that before and some tooling may be in order. I believe that @mingwandroid is the expert in R packaging for continuum, so he is probably the guy to help us here. (But he is quite busy.)

- usually we avoid sending many recipes at once b/c it make the PR hard to review and creates a race condition during the feedstock creation if package depends on each other

I try to open a discussion for R-packages some time ago but we neve got anywehere: https://github.com/conda-forge/staged-recipes/pull/586

Maybe it is time for someone from the community to add this item to the [agenda](https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG) and make the request :smile:

**Comment by jakirkham** [comment]
Are you still interested in this @jsignell? We have been working on porting R to conda-forge.

xref: https://github.com/conda-forge/staged-recipes/issues/2009

**Comment by jsignell** [comment]
@jakirkham I don't have the time at the moment. But I think this effort would be hugely popular.  Some of the R conda packages on my channel on anaconda.org have several thousand downloads.

**Comment by bgruening** [comment]
@jsignell the following packages have been added in the last weeks:

* recipes/r-circstats
* recipes/r-distillery
* recipes/r-fastcluster
* recipes/r-fields
* recipes/r-spam
* recipes/r-waveslim

These are still missing:
* recipes/r-turboem
* recipes/r-spatstat
* recipes/r-smoothie
* recipes/r-smatr
* r-spatialvx

Maybe you can use: https://github.com/bgruening/conda_r_skeleton_helper 
This will help you with the linting problems and so on....

**Comment by cbrueffer** [comment]
All missing packages have been added now.

**Comment by bgruening** [comment]
Awesome @cbrueffer!

**Pull request closed without merging**
