### PR TITLE
Adding fftlog recipe

### PR DESCRIPTION
**Pull request by prisae**
Checklist
- [x] Title of this PR is meaningful
- [x] License file is packaged
- [x] Source is from official source
- [x] Package does not vendor other packages.
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by prisae** [comment]
I think this is ready to go @conda-forge/help-python.

I excluded windows, as those builds failed and I have no idea why and also no possibility to check/test locally.

**Comment by prisae** [comment]
(If anyone knows *why* the windows-build fails then any input would be appreciated too: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=166353&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=78a0099b-3f13-5ae9-c1f0-24f71d1eac20)

**Comment by prisae** [comment]
Thought I'd ping you @nehaljwani, as you were the one to look at https://github.com/conda-forge/staged-recipes/pull/11638 too, which is sort of related.

Thanks!

**Comment by prisae** [comment]
Thanks @chrisburr

**Comment by nehaljwani** [comment]
@prisae I have opened a PR for Windows support at https://github.com/conda-forge/fftlog-feedstock/pull/3

**Pull request merged**
