### PR TITLE
Add r-magick.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by jdblischak** [comment]
@cbrueffer See this PR for our previous effort to build r-magick: #4613 Also this issue on imagemagick options: https://github.com/conda-forge/imagemagick-feedstock/issues/6

@dhimmel You've done a lot of investigating for r-magick. Interested in giving it another look? Any advice you could provide would be much appreciated.

**Comment by cbrueffer** [comment]
Turns out it's easier for me to work on this here.

**Comment by cbrueffer** [comment]
Back to the error where it installs imagemagick without magick++:

```
** package ‘magick’ successfully unpacked and MD5 sums checked
Package Magick++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lMagick++-6.Q16
```

**Comment by dhimmel** [comment]
I don't have a preference which PR adds `r-magick`, either https://github.com/conda-forge/staged-recipes/pull/4613 (mine) or https://github.com/conda-forge/staged-recipes/pull/5351 (this one). I ended up getting stuck on a Travis [timeout issue](https://github.com/conda-forge/staged-recipes/pull/4613#issuecomment-354866798).

@cbrueffer best of luck! Looks like you're adding windows binaries which would be a plus.

**Comment by jenzopr** [comment]
Hey @cbrueffer ,
one of my packages (r-multipanelfigure) was bumped upstream to 2.0 and now relies on r-magick.
Can I help you with the build here?

Best,
Jens

**Comment by cbrueffer** [comment]
Hi @jenzopr, absolutely! I've added you as a "collaborator", so hopefully you have push access now.

**Comment by halldc** [comment]
@cbrueffer The macOS builds fail because the `imagemagick` package is missing a `pkg-config` build requirement. See https://github.com/conda-forge/imagemagick-feedstock/issues/29.

**Comment by cbrueffer** [comment]
Thanks @halldc , let's see how it goes!

**Comment by halldc** [comment]
@cbrueffer This PR will need to wait for https://github.com/conda-forge/imagemagick-feedstock/pull/30 to be merged.

**Comment by halldc** [comment]
@cbrueffer Now that the new `imagemagick` package is available, you could try restarting the CI builds.

**Comment by davidchall** [comment]
Build failures are because [these lines](https://github.com/ropensci/magick/blob/master/configure#L18-L24)  of the `magick` configure script take a different route since adding `pkg-config` as a dependency.

**Comment by halldc** [comment]
Build failures are because [these lines](https://github.com/ropensci/magick/blob/v1.9/configure#L18-L24) of the magick configure script take a different route since adding pkg-config as a dependency.

@cbrueffer Could you add me as a collaborator, in case I am able to fix this?

**Comment by cbrueffer** [comment]
I've added you @halldc , thanks for the help so far!

**Comment by halldc** [comment]
@conda-forge/staged-recipes This is ready to merge

**Comment by cbrueffer** [comment]
Thanks everyone!

**Comment by jenzopr** [comment]
Great job @cbrueffer and @halldc 🎉

**Pull request merged**
