### PR TITLE
Pickleshare

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by synapticarbors** [comment]
A feedstock for this package already exists:

https://github.com/conda-forge/pickleshare-feedstock

Also it looks like this was already discussed here:
https://github.com/conda-forge/staged-recipes/pull/3500#issuecomment-321705763

I encourage you to put in a pull request on the feedstock to add yourself as a co-maintainer or to make any updates to the recipe.

**Comment by sannykr** [comment]
@synapticarbors : I had made a pull request to update the feedstock, but it didn't fix the problem. I was told to made a pull request with a new recipe. They told me to look at the following link:  
https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876

**Comment by synapticarbors** [comment]
The co-maintainers of the feedstock should submit a PR in `staged-recipes` with the existing recipe. Your PR makes substantial changes to the recipe and excludes the original co-maintainers. 

Please confer with the feedstock co-maintainers if you need that recipe updated. 

cc/ @ocefpaf

**Comment by ocefpaf** [comment]
The original recipe won't be overwritten so this is "fine" in a way. But it would be nice if you submit the original recipe instead.

**Comment by sannykr** [comment]
@ocefpaf @synapticarbors   Thanks. I have submitted the original recipe.

**Pull request closed without merging**
