### PR TITLE
re-add libdrs_f to see if we can fix the tokens

### PR DESCRIPTION
**Pull request by ocefpaf**
@dnadeau4 let's see if re-adding we can get a fresh `conda-forge.yml` and fix https://github.com/conda-forge/libdrs_f-feedstock/pull/13

### CODE REVIEW

**Comment by ocefpaf** [comment]
No need to wait for the CIs on this one.

**Comment by jakirkham** [comment]
Interestingly seems that conversion of other recipes is now working with this change. Was there something else that happened behind the scenes?

**Comment by beckermr** [comment]
^ this!

**Comment by beckermr** [comment]
This is not fixed:

```
Distribution /Users/travis/miniconda3/conda-bld/osx-64/camb-0.1.8.1-ha44fe06_0.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing.
Distribution /Users/travis/miniconda3/conda-bld/osx-64/pycamb-0.1.8.1-py36ha44fe06_0.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing.
Distribution /Users/travis/miniconda3/conda-bld/osx-64/pycamb-0.1.8.1-py27ha44fe06_0.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing.
```

from the camb-feedstock.

**Comment by beckermr** [comment]
and other errors: https://travis-ci.org/conda-forge/camb-feedstock

**Pull request merged**
