### PR TITLE
initial push for new package r-mdmr

### PR DESCRIPTION
**Pull request by mcornwell1957**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

First time addition to conda-forge! 
I used the conda_r_skeleton_helper script to expedite my process
please let me know if there are any other things I need to do! thank you

### CODE REVIEW

**Comment by mcornwell1957** [comment]
This failed for the windows step and I am not entirely sure why - let me know if I can help!

**Comment by mcornwell1957** [comment]
@daler @bgruening Sorry for the direct ping - but is this all set for merge? If not - let me know how I can help or what else I can do! Thank you!

**Comment by dbast** [comment]
@mcornwell1957 All fine. noarch R generic builds currently fail on windows, but that is not a problem to solve here. After merge, the created feedstock will build and upload it on linux.

**Comment by dbast** [comment]
@mcornwell1957 Thanks and welcome to conda-forge.

**Pull request merged**
