### PR TITLE
Add pydl to conda-forge

### PR DESCRIPTION
**Pull request by mwcraig**
@weaverba137 -- can you please confirm that you are willing to be a maintainer on this? There isn't much to it, but would mean that you can update the version when you do a release.

`bsipocz` agreed in another PR to be maintainer on this set of incoming recipes.

### CODE REVIEW

**Comment by weaverba137** [comment]
Sure, but as you've already noticed, right now there are some astropy 2 issues that I still need to fix. Is there any documentation on how to do this for astropy-affiliated packages?

**Comment by mwcraig** [comment]
Good question...pinging @bsipocz.

**Comment by bsipocz** [comment]
@weaverba137 - do you have a list for the issues? e.g. the argparse one opened my @mwcraig is simple, use the argparse module directly rather than importing it from the compatibility module of astropy.utils (we only had it there for py2.6 support).

**Comment by weaverba137** [comment]
@bsipocz, that's not actually the question I was asking.  What I meant was: Is there any documentation for how to create and maintain conda-forge recipes specifically for astropy-affiliated packages?

**Comment by bsipocz** [comment]
Creating is the same as for any other package, conda-forge has docs on it. The only trick is to use ``--offline`` for packages that use ``astropy-helpers``.

Maintenance is usually only requires to update the version and hash values for new versions.

**Comment by mwcraig** [comment]
Merging since this has been approved and all maintainers have confirmed.

**Pull request merged**
