### PR TITLE
hpccm: new conda recipe

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@chrisburr Any thoughts on why this is failing on Azure CI win64?

**Comment by marcelotrevisani** [comment]
That is not a problem, we have facing some issues with azure on windows

**Comment by tschoonj** [comment]
Thanks!

**Comment by marcelotrevisani** [comment]
Thanks for added this package to ``conda-forge``! 🎉 🎉 🎉

**Pull request merged**
