### PR TITLE
Add CRAN package seAMLess

### PR DESCRIPTION
**Pull request by eonurk**
This is my first time contributing to conda-forge, so please excuse my inexpertness.

This is the first PR for CRAN package [seAMLess](https://cran.r-project.org/package=seAMLess), I used `conda_r_skeleton_helper` to create this fork and followed the instructions on the maintainers' guide.

Thank you for your effort,

@conda-forge-admin, please ping team, and for the sake of completeness @conda-forge/help-r.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by eonurk** [comment]
Can someone help me with this? :) 

I wrote the package and published on CRAN, and since two of the libraries were not available neither in CRAN nor in bioconductor, I had to implement it via `drat` package, and serve those two libraries on my own github. I found one of them (r-music) on anaconda but I don't know how to add it as it is not available in conda-forge. I edited the conda-forge.yml to have the default channels as I thought that the default channels would include anaconda.

**Comment by dbast** [comment]
@eonurk All dependencies of a conda-forge package have to be available via conda-forge ... adding other channels (defaults, main, bioconda) to  conda-forge recipes is not supported. Packages that depend on bioconda packages are better added to bioconda to avoid duplication of their dependencies on conda-forge.

**Comment by eonurk** [comment]
Thank you @dbast. I see but then how about some of the dependencies are available within one channel but not in the others, and vice versa? Then, what would be the way to proceed? Simply, if I write a recipe for bioconda would I be able to depend on packages that are only available on conda-forge for instance, or such a package does not exist?

**Comment by dbast** [comment]
Yes, each project defines that by itself... so bioconda allows depending on conda-forge packages...

**Comment by eonurk** [comment]
Thanks @dbast, closing this one.

**Pull request closed without merging**
