### PR TITLE
added lastools receipe

### PR DESCRIPTION
**Pull request by gillins**
This adds the `lastools` package for reading and writing .las LiDAR files. Upstream does not provide releases so I have made this recipe from my fork which does provide releases when the LAS_TOOLS_VERSION define is updated. My fork also provides `cmake` support. Let me know if this is ok or not.

@danclewley are you ok to be a maintainer? I spoke to @armstonj on the phone, he was happy to be a maintainer also.

### CODE REVIEW

**Comment by danclewley** [comment]
> @danclewley are you ok to be a maintainer?

Yes happy with this.

You might want to add something in the summary about this only being the open source component of LAStools, hopefully prevent questions about why it doesn't include all the tools.

How about:

"LASlib and LASzip libraries plus open source utilities from LAStools for manipulating LiDAR data in LAS format"

**Comment by gillins** [comment]
Ah good point... Thanks Dan.

**Comment by ocefpaf** [comment]
@gillins is this ready to be merged?

**Comment by gillins** [comment]
Yes 😁

**Pull request merged**
