### PR TITLE
alternative Suitesparse recipe

### PR DESCRIPTION
**Pull request by grlee77**
I realize there is already a Suitesparse PR in #655, but this is a bit simpler in implementation and is using the most recent release.  This recipe builds shared as opposed to static libraries and I tested that it works with scikit-umfpack (which I can submit a separate PR for).  

I have used both OpenMP and TBB in the builds, but this is optional.  I had problems with openblas on OS X, so I have disabled the BLAS feature on OS X for now.  The build seemed to always want to set "-framework Accelerate" when on mac even when BLAS=-lopenblas was specified.

There is no windows build here, but I found that the menpo channel has such a [recipe](https://github.com/menpo/conda-suitesparse).  They were able to achieve this by basing off of a Suitesparse fork where the build system was changed to cmake.

### CODE REVIEW

**Comment by jakirkham** [comment]
@grlee77, the reason I have proposed the older version of SuiteSparse is we need it for cvxopt. The main developer on cvxopt is unsure whether using this newer version of SuiteSparse will work for it. Though as you have been playing a bit with building it, I would really appreciate your feedback on PR ( https://github.com/conda-forge/staged-recipes/pull/655 ). We can always add this after creating the feedstock. To be honest that PR does build locally for Mac and Linux, however we need to make some tweaks to CI here as this form of building for Linux does not mesh with SuiteSparse for some reason.

**Comment by grlee77** [comment]
I think the version built in #655 should also be fine for scikit-umfpack, but unfortunately I believe it requires shared libraries rather than the static ones built there.  It seemed that shared libraries are built by default in the most current release.  I was unaware of the cvxopt constraint, but I think it will be possible to get a version that works for both.

The scikit-umfpack instructions point to the following place for some advice on building:  http://fuertinger.lima-city.de/research.html#building-numpy-and-scipy
It sounds like `make library` is the command needed to get the shared libs.

**Comment by jakirkham** [comment]
Again we can have multiple versions in one feedstock by using branches. Please see [numpy]( https://github.com/conda-forge/numpy-feedstock/ ). We supply 1.10.x and 1.11.x. The situation with SuiteSparse will be no different. We will have two branches with two versions on the same feedstock.

**Comment by jakirkham** [comment]
Here's a [ref]( https://github.com/cvxopt/cvxopt/issues/58#issuecomment-220971823 ) on cvxopt.

**Comment by grlee77** [comment]
The error in the linux build here is related to linking to libgfortran

It may be that OpenBLAS would work on OS X now that I properly pass the LAPACK variable in build.sh (fixed in d7ff6a0 above). not sure if it is preferable to do that or stick with Accelerate

**Comment by grlee77** [comment]
closing this for now in favor of #655.  will revisit in the feedstock.

**Comment by jakirkham** [comment]
Thanks @grlee77. We will definitely pick this up again. I'm also interested in 4.5.3 as well.

**Comment by jakirkham** [comment]
As the feedstock is now out, please fork it and add your changes to a branch on your fork. Once completed, please PR this back to `master`.

**Pull request closed without merging**
