### PR TITLE
Add pyca recipe.

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vend other packages
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hhslepicka** [comment]
`@conda-forge/help-python-c`, sorry to disturb you but I am a bit stuck with the following error:
```
conda_build.exceptions.OverLinkingError: overlinking check failed 
['  ERROR (pyca,lib/python3.7/site-packages/pyca/pyca.cpython-37m-x86_64-linux-gnu.so): lib/python3.6/site-packages/epicscorelibs/lib/libca.so.7.0.3.99.1 not found in any packages']
##[error]Bash exited with code '1'.
```

I have another library, which is very similar to this one which does not present this issue.

Thank you for looking here and giving some tips.

**Comment by hhslepicka** [comment]
Problem with the overlinking is due to some leftovers of the build system when building multiple python versions on the same environment.
That was solved with the `missing_dso_whitelist`. When this gets merged and becomes its own recipe I will remove the `missing_dso_whitelist` since the builds will happen in a proper matrix.

**Comment by hhslepicka** [comment]
@conda-forge/help-python-c this one is ready for a review. Thank you for your time.

**Comment by hhslepicka** [comment]
@conda-forge/staged-recipes this one is ready to go...

**Comment by isuruf** [comment]
> Problem with the overlinking is due to some leftovers of the build system when building multiple python versions on the same environment.

Can you explain this please?

**Comment by hhslepicka** [comment]
@isuruf looking at the log, this issue happens because somehow the build matrix is not cleaning up properly.
I noticed that by looking at the build logs. Sometimes py36 comes before py37 and vice versa.
With that I noticed that whoever goes first, the build, test and linking check happens without problems. For the second one, the build system ends up finding the py36 version of my other libraries (libca and libCom) which causes the issue.
I am 100% sure that this will not happen when it gets merged due to the fact that the builds will happen in isolated environments.
It is somehow related on how staged-recipes uses the build matrix and this is not used at the feedstocks.

I have another package (p4p) using the same set of dependencies as a feedstock and no issues happen there.

Thank you for taking the time to look into this.

**Comment by isuruf** [comment]
Can you try to reproduce locally and open a conda-build issue?

**Comment by hhslepicka** [comment]
what do you mean by reproduce locally?
Before submitting the PR for the recipe I was able to run conda build but not with the matrix.

**Comment by isuruf** [comment]
Did you try running conda-build with the `conda_build_config.yaml` from conda-forge-pinning package in your computer? Did that have the same error?

`conda build recipes/pyca -e /path/to/conda_build_config.yaml --error-overlinking`

**Comment by hhslepicka** [comment]
I will give that a try and report back.

**Comment by hhslepicka** [comment]
@isuruf I don't have the `-e ` option at my conda build.
`conda-build 3.0.19`

**Comment by hhslepicka** [comment]
@isuruf all worked fine when running the command locally.
Can we merge this?

**Comment by hhslepicka** [comment]
Thank you!

**Pull request merged**
