### PR TITLE
add r-bstats via conda_r_skeleton_helper

### PR DESCRIPTION
**Pull request by izahn**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by izahn** [comment]
ready for review @conda-forge/help-r

**Comment by dbast** [comment]
A non CRAN recipe. CRAN serves as a good quality gate for packages. Any strong reasons why this should be packaged here, even though it is not on CRAN (yet?). Does it e.g. have a big user group or does is it unlock a broad variety of things?

**Comment by izahn** [comment]
Yeah, I'm not happy about this not being on CRAN either. I'm trying to package it here because it is a dependency of JASP which I am packaging in https://github.com/conda-forge/staged-recipes/pull/15529

**Comment by dbast** [comment]
Are you sure that this is the right bstats package?... There also was https://cran.microsoft.com/snapshot/2014-09-08/web/packages/bstats/index.html ... mirrored here https://github.com/cran/bstats ... there should be some old cran notes somewhere with a comment why it got removed from cran.

**Comment by izahn** [comment]
Yes, it is the right bstats (I was confused about that for a while too). I generated the dependency list from the `local-cran` and `local-github` directories of the JASP flatpak package at http://static.jasp-stats.org/flatpak_archive.tar.gz, following the recommendation of the JASP developers in https://github.com/jasp-stats/jasp-issues/issues/1353

**Comment by dbast** [comment]
ok. seems reasonable.

**Pull request merged**
