### PR TITLE
fix folder in example

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes please merge when possible.

**Comment by isuruf** [comment]
Tests fail

**Comment by CJ-Wright** [comment]
I'm not certain why.

**Comment by CJ-Wright** [comment]
It seems that the build fails before even hitting the tests.

**Comment by isuruf** [comment]
It's because the license file is not in the place specified

**Comment by CJ-Wright** [comment]
Yep the pypi package doesn't contain the license.

**Comment by CJ-Wright** [comment]
If possible it would be nice to have the linter check that the recipe lives in the correct folder.

**Comment by CJ-Wright** [comment]
@stuartcampbell I'm going to pull this from GH tag if that is ok

**Comment by CJ-Wright** [comment]
@isuruf ready for more review! Sorry about this happening in the first place :disappointed:

**Pull request merged**
