### PR TITLE
Add recipe for Perl module Moose and its dependencies

### PR DESCRIPTION
**Pull request by xileF1337**
Third and final batch of recipes including -- finally -- Moose itself.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xileF1337** [comment]
@conda-forge/bioconda-recipes I'm porting these to conda-forge unless there are obligations from your side!

@cbrueffer Finally, we arrived at Moose itself ... Could you please review this last monster PR? Thank you so much ;-)

**Comment by xileF1337** [comment]
@conda-forge/help-perl ready for review!

**Comment by xileF1337** [comment]
@cbrueffer Happy new year! Have you had a look at this PR already? Thanks for your efforts!

**Comment by xileF1337** [comment]
@cbrueffer Sorry for nagging you, but I would really appreciate to get this done in the near future. It would be awesome if you could review this PR in January, would that be possible? Thank you very much for your commitment!

**Comment by cbrueffer** [comment]
Sorry for the delay, I'm back from christmas vacation and catching up on things. Will look at this asap.

**Pull request merged**
