### PR TITLE
Adding ndarray-psana, psana1 recipes

### PR DESCRIPTION
**Pull request by valmar**
@chrisburr can you please take a look at the recipes?

Notes:

- ndarray-psana is a very small header-only library needed only by psana1, even internally. The original internal ndarray library had the same name as an already existing package (ndarray). Because of this, I changed the name to ndarray-psana
- the source of psana1 should compile as it is with both py2 and py3
- this work is preliminary and not ready for submission yet. For example, the assigned license is tentative

Thank you for your help

EDIT: typo

### CODE REVIEW

**Comment by bkpoon** [comment]
Hi @valmar, I helped @phyy-nx update `psana1` to work in Python 3 and we are making some of our tools available on `conda-forge` as well (`cctbx`). Here are some questions/suggestions for this recipe.

1. Do you need macOS and Windows builds? If not, you can add `skip: True  # [win or osx]` to the `build` section. We have only been testing `psana1` and `cctbx.xfel` on linux.
2. Do you need to build with RHEL/CentOS 7? If so, you would need to add an entry to the `build` section as described [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7). Otherwise, I believe CentOS 6 is used for the CDTs.
3. You may need to pin the version of `boost` so that when someone installs `psana1`, they install the same version of `boost` that was used for building. I'm not sure if this is necessary anymore since I cannot find recent documentation about it. But it would look like the pinning for `numpy` as described [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#linking-numpy).
4. Activation/deactivate scripts have a preferred name as described [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#activate-scripts). Basically, the format is something like `${PKG_NAME}-activate.sh` and I suspect this is to avoid name clobbering.
5. There is a bot that can update recipes when there are updated versions. I'm not sure if it can handle `git_rev` in `ndarray-psana/meta.yaml`. Also, a source tarball is [preferred](https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos). Maybe you can set variables for the major, minor, and patch values and then construct the source tarball name. I think you can add leading zeroes with something like `{{ 'V%02d-%02d-%02d.tar.gz' % (major, minor, patch) }}` or some other Jinja [syntax](https://conda-forge.org/docs/maintainer/adding_pkgs.html#jinja-templating).

**Comment by valmar** [comment]
Thank you @bkpoon , it's great to have your help. I will work through all your suggestions. Just a question:

2. Won't the build that uses cos6 CDT work on CentOS7 too? I thought the CDT system was forward compatible.

Thank you again!

**Comment by bkpoon** [comment]
Yes, it should, but I think there are local channels at LCLS for RHEL 6 and RHEL 7, so I wasn't sure if there is something specific to RHEL 7 that you wanted. If the CentOS 6 CDTs work, then that's fine!

**Comment by bkpoon** [comment]
Also, for point 5 about versioning, I don't really know how the bot looks for versions, so I'm not certain about any changes for `ndarray-psana` that would map `version=1.1.8` to `V01-01-08.tar.gz`.

**Comment by valmar** [comment]
@bkpoon ndarray-psana is a frozen dependency. It will probably never see a new version. psana1, on the other hand, is still seeing updates, even though for LCLS-II we will use psana2

**Comment by bkpoon** [comment]
Oh, then you can set the `source` section to point to the `V01-01-08.tar.gz` tarball and add the hash.

LCLS-II is very exciting. NERSC is going to be busy.

**Pull request closed without merging**
