### PR TITLE
UQpy recipe

### PR DESCRIPTION
**Pull request by volpatto**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

**Extra infos:**

This is a pure Python lib. Unfortunately, there is no MANIFEST.in file including the LICENSE file when the lib is packaged. Hence, I included the LICENSE from the original repository in the recipe directory (see [here](https://github.com/SURGroup/UQpy/blob/master/LICENSE)).

### CODE REVIEW

**Comment by chrisburr** [comment]
LGTM 👍 

For the licence file, could you make an issue or PR upstream so it's fixed for future releases? It's preferable as it ensures conda-forge's copy of the licence is never outdated.

**Comment by volpatto** [comment]
> LGTM 
> 
> For the licence file, could you make an issue or PR upstream so it's fixed for future releases? It's preferable as it ensures conda-forge's copy of the licence is never outdated.

Thanks, @chrisburr! Sure thing, I can do it. The most preferable way would be where? I could do it in the feedstock with rerender or PR there?

**Comment by chrisburr** [comment]
The PR would need to be made to https://github.com/SURGroup/UQpy.

Then, after the make a new release, the update bot will make a update PR to the feedstock. You can then manually edit it to delete the licence file in the feedstock.

**Comment by volpatto** [comment]
Ah, got it, you refer to the package release itself. I understand now. I'm already think of submitting and PR there to update installation instruction. I will suggest also improvements in their packing, which includes the license issue. Thanks again, @chrisburr!

**Pull request merged**
