### PR TITLE
Add ngspice

### PR DESCRIPTION
**Pull request by stuarteberg**
This adds `ngspice`, a circuit simulator.

- http://ngspice.sourceforge.net
- https://en.wikipedia.org/wiki/Ngspice

---
Checklist

- [x] Title of this PR is meaningful
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by stuarteberg** [comment]
This recipe is ready for review.

@conda-forge/help-c-cpp

**Comment by stuarteberg** [comment]
This recipe says `skip: true  # [win]`, but the Windows build is somehow failing.  Can it be merged anyway?

**Comment by jakirkham** [comment]
Interested to hear what you are using this for 😉

**Comment by stuarteberg** [comment]
Lou has been using it to simulate the electrical timing properties of neurons in our current dataset.  Steve is exploring how we might add Lou's code to the [Python library][1] for our [connectome analysis database][2].

[1]: https://github.com/connectome-neuprint/neuprint-python
[2]: https://neuprint.janelia.org/?dataset=hemibrain:v1.0.1&qt=findneurons

**Comment by jakirkham** [comment]
Interesting. Thanks for the context 🙂

**Pull request merged**
