### PR TITLE
A few more Pyramid support packages

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
@conda-forge/help-python: it looks like . only AppVeyor is failing -- can this be merged?

**Comment by npavlovikj** [comment]
@daf , are you ok being listed as a maintainer in these recipes?

**Comment by daf** [comment]
@npavlovikj sure, this and anything @ChrisBarker-NOAA makes I'm fine to help with.

**Comment by npavlovikj** [comment]
Thanks @daf , I will remember this for future merges :)

**Comment by npavlovikj** [comment]
@ChrisBarker-NOAA , thank you so much  for contributing all these recipes 🎉

**Pull request merged**
