### PR TITLE
Add heudiconv

### PR DESCRIPTION
**Pull request by kastman**
Here's a first try for heudiconv. It specifically does **not** test the heuristics_monitor script, which requires inotify and tinydb (inotify at least is pip-installable only and has no conda package).

Since monitor is a specialized sub-function, I think it's ok to leave out, but let me know if you think it's worth inclucding.

### CODE REVIEW

**Comment by kastman** [comment]
@yarikoptic I just built a conda-forge package for `heudiconv 0.5.1` to close https://github.com/conda-forge/staged-recipes/issues/4358 and https://github.com/nipy/heudiconv/issues/242 ; listed you as a maintainer as well. Anyone else from nipy that should be included? Maybe @mgxd ?

n.b. this conda-forge package currently fails if using the `heuristics_monitor` cli because of extra dependencies (`inotify` for linux, `tinydb`...). Is it worth it to you to add them here?

**Comment by kastman** [comment]
@yarikoptic I just built a conda-forge package for `heudiconv 0.5.1` to close https://github.com/conda-forge/staged-recipes/issues/4358 and https://github.com/nipy/heudiconv/issues/242 ; listed you as a maintainer as well. Anyone else from nipy that should be included? Maybe @mgxd ?

n.b. this conda-forge package currently fails if using the `heuristics_monitor` cli because of extra dependencies (`inotify` for linux, `tinydb`...). Is it worth it to you to add them here?

**Comment by yarikoptic** [comment]
Probably not... Inotify iirc is linux specific. I thought we made them optional for testing, would need to check and do so if not yet

**Comment by mgxd** [comment]
I'm fine with leaving out monitor as well. Thanks for this @kastman !

**Comment by kastman** [comment]
I just used the default `conda skeleton pypi` test, which is to check the imports and run `heudiconv --help` and `heudiconv_monitor --help` (because they're listed as the entrypoints in setup.py, so for testing they're not strictly required).

In that case, I think this is ready to merge. @mgxd did you want to be added as a conda-forge maintainer? Alright if not, I just realized I hadn't included you. Thanks both!

**Comment by mgxd** [comment]
@kastman yes

**Comment by marcelotrevisani** [comment]
Looks good to me! I'm going to merge this!

Thanks to put this in ``conda-forge`` !  :)

**Pull request merged**
