### PR TITLE
Add bidict recipe

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
Waiting on @jab to give the ok on this as a co-maintainer (and original author of the library)

**Comment by jab** [comment]
This is great, thanks so much @synapticarbors!

**Comment by jab** [comment]
Thanks for merging!

Forgive the Conda-n00b question, but now that this is merged, is it possible to get this to appear by default in the search results when a user runs `anaconda search bidict` from a fresh conda install? Currently I still get only the ancient versions:
```
$ ./bin/anaconda search bidict
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     auto/bidict               |    0.1.1 | conda           | linux-64, linux-32
                                          : http://bitbucket.org/jab/bidict
     neurokernel/bidict        |          | conda           | linux-64
                                          : 2-way dict with convenient slice syntax: d[65] = 'A' -> d[:'A'] == 65
     pypi/bidict               |    0.2.1 | pypi            |
                                          : 2-way dict with convenient slice syntax: d[65] = 'A' -> d[:'A'] == 65
Found 3 packages
```
Thanks again!

**Comment by jab** [comment]
(My goal in [writing to the mailing list](https://groups.google.com/a/continuum.io/d/msg/anaconda/mf6SDLBxFEk/63DyOyViAgAJ) which prompted this PR was to make it so that by default users searching for my software would be able to download the most up-to-date version.)

**Comment by synapticarbors** [comment]
@jab It might have been that the feedstock had not finished generating the binaries and uploaded them to anaconda.org yet. Now I get the following:

```
$ anaconda search bidict
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     auto/bidict               |    0.1.1 | conda           | linux-64, linux-32
                                          : http://bitbucket.org/jab/bidict
     conda-forge/bidict        |   0.12.0 | conda           | linux-64, win-32, win-64, osx-64
     neurokernel/bidict        |          | conda           | linux-64
                                          : 2-way dict with convenient slice syntax: d[65] = 'A' -> d[:'A'] == 65
     pypi/bidict               |    0.2.1 | pypi            |
                                          : 2-way dict with convenient slice syntax: d[65] = 'A' -> d[:'A'] == 65
Found 4 packages
```

So you can see the packages are all there now. All of the files are here along with download stats for future reference:

https://anaconda.org/conda-forge/bidict/files

**Comment by jab** [comment]
Just reproduced myself so that must have been the case - fantastic, thank you!

Regarding the ancient versions, I'm curious, is it possible to:
1. see whether they're actually still getting any downloads,
2. contact whoever originally published them to see whether they're still using/maintaining them? (I assume not since they've left them stuck at such old versions.) If not, is there a policy for purging unmaintained packages? If they are still maintaining them, if I can find out their contact info, I'd be interested to get in touch and ask if there's a reason they haven't been publishing more up-to-date versions and if they'd be willing to start.

Finally, I noticed the old versions include a [now-no-longer-true](https://github.com/jab/bidict/issues/19) description ("2-way dict with convenient slice syntax...") and a [now-out-of-date source URL](https://bitbucket.org/jab/bidict), but the 0.12.0 package that was just published contains no description or source URL. Concerned that might throw people off and wondering if anything can be done, if unpublishing the old packages isn't an option.

**Comment by jab** [comment]
Also, not sure if there's any existing logic that can detect that the results for the "bidict" search all correspond to different versions of the same library, but if so, would it be useful if the search results could be sorted by most recent version, rather than alphabetically?

**Comment by synapticarbors** [comment]
Here are links to show you the other versions:

https://anaconda.org/neurokernel/bidict/files
https://anaconda.org/auto/bidict/files
https://anaconda.org/pypi/bidict/files

I'm not sure how best to get in contact with the owners of those anaconda channels. `neurokernel` at least has some contact info, although the others do not:

https://anaconda.org/neurokernel

I don't think there is a purge policy to avoid breaking automated workflows. If a user doesn't have a channel specified in their `.condarc` config file or don't make it explicit in `conda install -c <channel>`, then they aren't going to grab some random version. They would have to explicitly ask for packages from a particular channel. 

I'm not sure if it is possible to configure conda-forge to put the source url on the anaconda.org page. I'll ask on the conda-forge gitter, because I think it's a good idea. There is info on the github page, but most users will never go there:

https://github.com/conda-forge/bidict-feedstock

**Comment by jakirkham** [comment]
So anaconda.org is really the wild west when it comes to packaging. One signs up and puts whatever artifacts they want in their account. They can also pay to keep their packages hidden or pay for additional storage. There is really no requirement that the recipe be open sourced or that there even be a recipe at all. Even if the recipe is available somewhere, there is no guarantee that the recipe matches the binary package on anaconda.org. Additionally there is the problem of combining various other channels resulting in unpredictable results. It is really because of all of these problem that conda-forge was formed.

**Comment by jakirkham** [comment]
You should get an email that invite you to join conda-forge, @jab. Once accepted you will be added to a team with the same name as this recipe. Those will give you permissions on the feedstock (repo) for this recipe.

Make sure when proposing any change that you go through the typical GitHub workflow of forking the feedstock and making changes in your fork that you PR back. Once merged CIs will build and deploy any changes you make. Please let us know if you have any questions and welcome to conda-forge.

**Comment by jab** [comment]
Thank you both for all that info! (And I contacted the maintainer listed on https://neurokernel.github.io - thanks for that hint too.) I did see the invite to join conda-forge (which came right around this time yesterday) and accepted it immediately. Thanks for the warm welcome!

**Pull request merged**
