### PR TITLE
add r-shinythemes  r-sparklyr  r-strucchange  r-th.data  r-threejs  r-tidyr  r-ttr  r-visnetwork

### PR DESCRIPTION
**Pull request by bgruening**
xref: https://github.com/conda-forge/staged-recipes/issues/2009
ping @johanneskoester 

r-shinythemes
 r-sparklyr
 r-strucchange
 r-th.data
 r-threejs
 r-tidyr
 r-ttr
 r-visnetwork

I can only work today on this and would like to prepare everything. Ideally we can just rerun the builds as soon as the feedstock creation is fixed.

### CODE REVIEW

**Comment by isuruf** [comment]
Looks good to me. It seems the `bld.bat` and `build.sh` files are not needed anymore. Following should work.
```
build:
   script: R CMD INSTALL --build .
```

**Comment by bgruening** [comment]
Is this a general recommendation from conda-forge. I know that @johanneskoester raised some concerns about mixing code and metadata.

**Comment by bgruening** [comment]
Thanks for the merge!

**Comment by isuruf** [comment]
Ah, if you've had discussions before then that's fine. It was just a thought after reviewing this PR.

**Pull request merged**
