### PR TITLE
Added r-gdalcubes

### PR DESCRIPTION
**Pull request by TomAugspurger**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Failure on an "overlinking" check:

```

   INFO: sysroot: '/home/conda/staged-recipes/build_artifacts/r-gdalcubes_1620654875132/_build_env/x86_64-conda-linux-gnu/sysroot/' files: '['/home/conda/staged-recipes/build_artifacts/r-gdalcubes_1620654875132/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/zone.tab', '/home/conda/staged-recipes/build_artifacts/r-gdalcubes_1620654875132/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/tzdata.zi', '/home/conda/staged-recipes/build_artifacts/r-gdalcubes_1620654875132/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/right/Zulu', '/home/conda/staged-recipes/build_artifacts/r-gdalcubes_1620654875132/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/right/WET']'
   INFO (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): Needed DSO lib/libgdal.so.27 found in conda-forge::libgdal-3.1.4-h38ff51b_8
  ERROR (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): Needed DSO lib/libnetcdf.so.18 found in ['libnetcdf']
  ERROR (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): .. but ['libnetcdf'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
   INFO (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): Needed DSO lib/R/lib/libR.so found in conda-forge::r-base-3.6.3-hbffa01f_7
   INFO (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): Needed DSO lib/libstdc++.so.6 found in conda-forge::libstdcxx-ng-9.3.0-h6de172a_19
   INFO (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libm.so.6 found in CDT/compiler package conda-forge::sysroot_linux-64-2.12-h77966d4_13
   INFO (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): Needed DSO lib/libgcc_s.so.1 found in conda-forge::libgcc-ng-9.3.0-h2828fa1_19
   INFO (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge::sysroot_linux-64-2.12-h77966d4_13
WARNING (r-gdalcubes): run-exports library package conda-forge::proj-7.2.0-h277dcde_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-gdalcubes): plugin library (R) package conda-forge::r-jsonlite-1.7.2-r36hcfec24a_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-gdalcubes): interpreted library (R) package conda-forge::r-rcppprogress-0.4.2-r36h6115d3f_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-gdalcubes): plugin library (R) package conda-forge::r-rcpp-1.0.6-r36h03ef668_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-gdalcubes): run-exports library package conda-forge::tiledb-2.2.8-h91fcb0e_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (r-gdalcubes): plugin library (R) package conda-forge::r-ncdf4-1.17-r36h4fa2c38_4 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 175, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 100, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 156, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2351, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 1644, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 1490, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/post.py", line 1317, in post_build
    check_overlinking(m, files, host_prefix)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/post.py", line 1223, in check_overlinking
    return check_overlinking_impl(m.get_value('package/name'),
  File "/opt/conda/lib/python3.8/site-packages/conda_build/post.py", line 1206, in check_overlinking_impl
    raise OverLinkingError(overlinking_errors)
conda_build.exceptions.OverLinkingError: overlinking check failed 
["  ERROR (r-gdalcubes,lib/R/library/gdalcubes/libs/gdalcubes.so): .. but ['libnetcdf'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]
```

I have `r-ncdf4` in the host / runs. I wonder if I just need `libnetcdf` too?

**Comment by izahn** [comment]
@TomAugspurger is this ready for review?

**Comment by TomAugspurger** [comment]
Yep, I believe it is.

**Comment by izahn** [comment]
>> @TomAugspurger is this ready for review?

> Yep, I believe it is.

@conda-forge/help-r

**Pull request merged**
