### PR TITLE
Conda package for gcovr

### PR DESCRIPTION
**Pull request by tovrstra**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by tovrstra** [comment]
@conda-forge/help-python Could someone help me with solving `Could not install packages due to an EnvironmentError` on Windows, please? This is a rather generic message and I have no idea how to address it. GCovr is a pure python package that should work for py27 and py>=34, on all platforms.

**Comment by tovrstra** [comment]
@conda-forge/staged-recipes, this PR is ready for review.

**Comment by chrisburr** [comment]
Looks good to me, LGTM 👍

**Comment by tovrstra** [comment]
@chrisburr  Thanks for merging!

**Pull request merged**
