### PR TITLE
Try to fix travis

### PR DESCRIPTION
**Pull request by ocefpaf**
Not sure what is going on but Travis-CI is trying to build `python-eccodes` on Windows even with the `skip` flag.

```shell
conda.resolve.NoPackagesFound:  Packages missing in current win-32 channels: 
  - jasper
  - eccodes 0.13.0
```

Maybe I am missing something obvious. Let's see if this PR fixes it:

### CODE REVIEW

**Comment by ocefpaf** [comment]
Something is amiss with `master` staged-recipes. Now I am getting:

```shell
Resolving distributions from 2 recipes...  
Traceback (most recent call last): 
  File "C:\Miniconda\Scripts\conda-build-all-script.py", line 9, in <module>
    load_entry_point('conda-build-all==0.13.0', 'console_scripts', 'conda-build-all')()
  File "C:\Miniconda\lib\site-packages\conda_build_all\cli.py", line 85, in main
    b.main()
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 212, in main
    all_distros = self.compute_build_distros(index, recipe_metas)
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 193, in compute_build_distros
    self.matrix_conditions)
  File "C:\Miniconda\lib\site-packages\conda_build_all\resolved_distribution.py", line 106, in resolve_all
    cases = sorted(vn_matrix.special_case_version_matrix(meta, index))
  File "C:\Miniconda\lib\site-packages\conda_build_all\version_matrix.py", line 215, in special_case_version_matrix
    add_case_if_soluble(case)
  File "C:\Miniconda\lib\site-packages\conda_build_all\version_matrix.py", line 186, in add_case_if_soluble
    r.solve(specs)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 909, in solve
    dists, new_specs = self.get_dists(specs)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 399, in get_dists
    specs, removes, optional, features = self.verify_specs(specs)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 393, in verify_specs
    raise NoPackagesFound(bad_deps)
conda.resolve.NoPackagesFound:  Packages missing in current win-32 channels: 
  - bob.ip.draw
  - bob.io.base
  - bob.core
  - bob.ip.base
  - bob.extension
  - bob.blitz
  - bob.ip.color
  - bob.io.image
  - pkg-config
```

**Comment by jakirkham** [comment]
So, this happening on Travis CI when running Linux on `master`. See [log]( https://travis-ci.org/conda-forge/staged-recipes/jobs/136449353#L281-L283 )

```
conda.resolve.NoPackagesFound:  Packages missing in current win-32 channels:
  - jasper
  - eccodes 0.13.0
```

cc @msarahan

**Comment by ocefpaf** [comment]
@msarahan since `Environment: TARGET_ARCH=x64, CONDA_PY=34, PY_CONDITION=python >=3.4,<3.5` is passing and I believe that is pinned to an old `conda-build`, so maybe this is a conda-build bug?

**Comment by ocefpaf** [comment]
Closing as my tests here are useless now that master has changed its state.

> AppVeyor was unable to build non-mergeable pull request

**Pull request closed without merging**
