### PR TITLE
Add kedro

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Recipe generated with [grayskull](https://github.com/marcelotrevisani/grayskull)  :skull: 

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
grayskull is not getting the metadata from ``sdist`` because it is missing a file in sdist, the file which is missing it ``test_requirements.txt``.

**Comment by npavlovikj** [comment]
@marcelotrevisani , this is weird, but I didn't merge this... Is it possible that this got merged when pytest json got merged too?

**Comment by marcelotrevisani** [comment]
Don't worry, it is because I deleted it, but it was not merged

**Comment by npavlovikj** [comment]
Oh ok, I got a mini heart-attack when I saw this :)

**Pull request merged**
