### PR TITLE
Add recipe for cbflib

### PR DESCRIPTION
**Pull request by bkpoon**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

This adds `cbflib`, which is a library for reading Crystallographic Binary Files (CBF) and Image-supporting CIF (imgCIF). There will be another output for `pycbf` which wraps `cbflib` for Python.

@yayahjb is the project maintainer, please confirm if you wish to be a maintainer for this recipe.
@Anthchirp @phyy-nx please confirm if you wish to be a maintainer for this recipe.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Thanks for picking this up.
I'm not sure having two outputs is worth it here - I'd just install both, this will be the default use case anyway.

Happy to be maintainer. Please also add @graeme-winter to the list.

**Comment by graeme-winter** [comment]
Am also happy / keen to be a maintainer as I have an interest in this as a package

I also agree that cbflib + Python bindings would be a sensible single combined package to the average end user.

**Comment by phyy-nx** [comment]
Confirmed to be a maintainer.  Thanks.

**Comment by ndevenish** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
I don't think the bot will listen to you.

@conda-forge-admin, please rerender

**Comment by ndevenish** [comment]
I'm happy to be listed as a maintainer

**Comment by Anthchirp** [comment]
@conda-forge-admin please restart ci

**Comment by yayahjb** [comment]
I am happy to be a maintainer.  I will make an official release for this condo package.

**Comment by phyy-nx** [comment]
Hi, still a priority, so commenting to keep this PR open.

**Pull request closed without merging**
