### PR TITLE
Create recipes for R tmod and deps

### PR DESCRIPTION
**Pull request by PertuyF**
Creates recipes using bgruening/conda_r_skeleton_helper for packages:
* `r-plotwidgets`
* `r-tagcloud`
* `r-tmod`

R packages from CRAN, by January Weiner.

### CODE REVIEW

**Comment by PertuyF** [comment]
@conda-forge/core Windows build fails with some path problem while testing `r-plotwidgets`.
Looks like `(base) %SRC_DIR%>call "C:\Miniconda36-x64\Scripts\activate.bat" "%PREFIX%"` does not work properly as it activates envrironment `%PREFIX%` instead of `C:\bld\r-plotwidgets_1552660031300\_test_env`.


Details below:
```
TEST START: C:\bld\noarch\r-plotwidgets-0.4-r351h6115d3f_0.tar.bz2
Renaming work directory,  C:\bld\r-plotwidgets_1552660031300\work  to  C:\bld\r-plotwidgets_1552660031300\work_moved_r-plotwidgets-0.4-r351h6115d3f_0_noarch
Collecting package metadata: ...working... done
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\bld\r-plotwidgets_1552660031300\_test_env
The following NEW packages will be INSTALLED:
    _r-mutex:                1.0.0-anacondar_1    defaults   
    m2w64-bwidget:           1.9.10-2             defaults   
    m2w64-bzip2:             1.0.6-6              defaults   
    m2w64-expat:             2.1.1-2              defaults   
    m2w64-fftw:              3.3.4-6              defaults   
    m2w64-flac:              1.3.1-3              defaults   
    m2w64-gcc-libgfortran:   5.3.0-6              defaults   
    m2w64-gcc-libs:          5.3.0-7              defaults   
    m2w64-gcc-libs-core:     5.3.0-7              defaults   
    m2w64-gettext:           0.19.7-2             defaults   
    m2w64-gmp:               6.1.0-2              defaults   
    m2w64-gsl:               2.1-2                defaults   
    m2w64-libiconv:          1.14-6               defaults   
    m2w64-libjpeg-turbo:     1.4.2-3              defaults   
    m2w64-libogg:            1.3.2-3              defaults   
    m2w64-libpng:            1.6.21-2             defaults   
    m2w64-libsndfile:        1.0.26-2             defaults   
    m2w64-libtiff:           4.0.6-2              defaults   
    m2w64-libvorbis:         1.3.5-2              defaults   
    m2w64-libwinpthread-git: 5.0.0.4634.697f757-2 defaults   
    m2w64-libxml2:           2.9.3-4              defaults   
    m2w64-mpfr:              3.1.4-4              defaults   
    m2w64-openblas:          0.2.19-1             defaults   
    m2w64-pcre:              8.38-2               defaults   
    m2w64-speex:             1.2rc2-3             defaults   
    m2w64-speexdsp:          1.2rc3-3             defaults   
    m2w64-tcl:               8.6.5-3              defaults   
    m2w64-tk:                8.6.5-3              defaults   
    m2w64-tktable:           2.10-5               defaults   
    m2w64-wineditline:       2.101-5              defaults   
    m2w64-xz:                5.2.2-2              defaults   
    m2w64-zlib:              1.2.8-10             defaults   
    msys2-conda-epoch:       20160418-1           defaults   
    r-base:                  3.5.1-hfa6e2cd_1005  conda-forge
    r-plotwidgets:           0.4-r351h6115d3f_0   local      
Preparing transaction: ...working... done
Verifying transaction: ...working... ERROR:conda.stderr:
SafetyError: The package for r-base located at C:\Miniconda36-x64\pkgs\r-base-3.5.1-hfa6e2cd_1005
appears to be corrupted. The path 'lib/R/doc/html/packages.html'
has an incorrect size.
  reported size: 6062 bytes
  actual size: 3395 bytes
done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
Found sh test file on windows.  Ignoring this for now (PRs welcome)
WARNING:conda_build.build:Found sh test file on windows.  Ignoring this for now (PRs welcome)
set PREFIX=C:\bld\r-plotwidgets_1552660031300\_test_env
set SRC_DIR=C:\bld\r-plotwidgets_1552660031300\test_tmp
(base) %SRC_DIR%>call "%SRC_DIR%\conda_test_env_vars.bat" 
(base) %SRC_DIR%>call "C:\Miniconda36-x64\Scripts\activate.bat" "%PREFIX%" 
(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1 
(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1 
(%PREFIX%) %SRC_DIR%>call "%SRC_DIR%\run_test.bat" 
(%PREFIX%) %SRC_DIR%>"%PREFIX%\bin\R" -e "library('plotwidgets')" 
The system cannot find the path specified.
(%PREFIX%) %SRC_DIR%>IF 3 NEQ 0 exit /B 1 
(%PREFIX%) %SRC_DIR%>IF 1 NEQ 0 exit 1 
Tests failed for r-plotwidgets-0.4-r351h6115d3f_0.tar.bz2 - moving package to C:\bld\broken
WARNING:conda_build.build:Tests failed for r-plotwidgets-0.4-r351h6115d3f_0.tar.bz2 - moving package to C:\bld\broken
TESTS FAILED: r-plotwidgets-0.4-r351h6115d3f_0.tar.bz2
Command exited with code 1
```

**Comment by dbast** [comment]
@PertuyF Failing windows builds for `noarch: generic` R packages can be ignored. Also currently the linter can be ignored in favor of the conda_skeleton_helper output, which means your second commit is not required. 

All in all it would be better to split out r-tagcloud into a separate PR to see that it successfully compiles and tests on windows, while the windows build failure is ignored for other two packages.

**Comment by PertuyF** [comment]
@dbast OK, so I'll split all three and submit PRs sequentially (`r-tmod` depends on `r-tagcloud` which depends on `r-plotwidgets`...)

**Comment by PertuyF** [comment]
See:
* `r-plotwidgets` #7992
* `r-tagcloud` #7993

**Pull request closed without merging**
