### PR TITLE
Adding keyboard library.

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dopplershift** [comment]
Please don't modify the other projects because that will create conflicts when the machinery takes care of creating those feedstocks.

**Comment by hhslepicka** [comment]
@dopplershift I apologize for the mistake. I reverted the change.

**Comment by hhslepicka** [comment]
@dopplershift I am getting the following error: RuntimeError: Wrong version of PyObjC C API (got 21, expected 20).
Any idea what I could do?
The package is this one: https://github.com/boppreh/keyboard
Link to error on CI: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=335748&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=1065

Thanks!

**Comment by hhslepicka** [comment]
@conda-forge admin, please restart vi

**Comment by isuruf** [comment]
`pyobjc-framework-quartz` needs an update for the new `pyobjc-core`

**Comment by hhslepicka** [comment]
@isuruf quartz got merged and now this one passes. Would you mind a review and merge? Thanks

**Comment by hhslepicka** [comment]
@dopplershift @isuruf could we get this merged? Tests are passing now. Thank you!

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
