### PR TITLE
clickhouse recipes: driver, cityhash, sqlalchemy, pyquicklz

### PR DESCRIPTION
**Pull request by kszucs**
Initially generated with `conda skeleton pypi`.

ref https://github.com/mymarilyn/clickhouse-driver/issues/6
 
I've added @xzkostyan to the recipe maintainers section, I hope You don't mind!

cc @cpcloud

### CODE REVIEW

**Comment by synapticarbors** [comment]
Please do not delete the other recipes that were in the `recipes` directory. Especially at issue is you deleted the `example` recipe.

**Comment by kszucs** [comment]
@synapticarbors there is some cloning issue with circleci, I've tried to enable some for+PR related setting in my circleci build and reopen the PR, but doesn't work. How could I fix that?

**Comment by kszucs** [comment]
@synapticarbors can I request a review / help with circleci?

**Comment by synapticarbors** [comment]
I've never seen this error message before. @conda-forge/staged-recipes any thoughts about what might be going on?

**Comment by isuruf** [comment]
@kszucs, can you remove your fork from circleci by unfollowing?

**Comment by kszucs** [comment]
@isuruf done

**Comment by kszucs** [comment]
@conda-forge/staged-recipes I need a little help here.

**Pull request closed without merging**
