### PR TITLE
Adding pyleco recipe (python package)

### PR DESCRIPTION
**Pull request by BenediktBurger**
@conda-forge/help-python, ready for review!

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by synapticarbors** [comment]
We'll need to create a recipe for `uuid7`. It also looks like you'll need a recipe for `openrpc` as well. You can open them up as separate PRs, or include them here with the caveat listed here:
https://conda-forge.org/docs/maintainer/adding_pkgs/#adding-multiple-packages-at-once

**Comment by BenediktBurger** [comment]
Thanks for the quick response.

The pyleco package contains a fallback for openrpc, because pyleco supports python 3.8, while openrpc is for python>3.9.
In this case, we could do without openrpc.
I'll think about adding `uuid7` to conda-forge.

**Comment by BenediktBurger** [comment]
I noticed, that `uuidv7` is not compliant to the current UUIDv7 definition.
Therefore, I do not want to add it to conda-forge and have to rework pyleco first.
Once that has happened, I will continue this PR.

**Comment by BenediktBurger** [comment]
@conda-forge-admin, please ping conda-forge/help-python, I need help

The pipeline fails with
~~~
   python:           3.12.3-hab00c5b_0_cpython conda-forge
    python_abi:       3.12-4_cp312              conda-forge
    pyzmq:            26.0.3-py312h8fd38d8_0    conda-forge
    readline:         8.2-h8228510_1            conda-forge
    setuptools:       69.5.1-pyhd8ed1ab_0       conda-forge
    tk:               8.6.13-noxft_h4845f30_101 conda-forge
    tzdata:           2024a-h0c530f3_0          conda-forge
    uuid6:            2024.1.12-pyhd8ed1ab_0    conda-forge
    wheel:            0.43.0-pyhd8ed1ab_1       conda-forge
    xz:               5.2.6-h166bdaf_0          conda-forge
    zeromq:           4.3.5-h75354e8_3          conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/staged-recipes/build_artifacts/pyleco_1715607132222/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
export SRC_DIR=/home/conda/staged-recipes/build_artifacts/pyleco_1715607132222/test_tmp
import: 'pyleco'
import: 'pyleco'
+ pip check
pyleco 0.3.2 has requirement uuid6>=2024.1.12, but you have uuid6 0.0.0.dev0.
~~~

It seems, that it does not recognize the installed uuid6 version.
Could you advise, what I should change in order to make the dependency work?
Thanks!

**Comment by ocefpaf** [comment]
Looks like you do have `uuid6>=2024.1.12` but the metadata in that package is probably wrong. I would disable `pip check` for now.

**Comment by BenediktBurger** [comment]
> Looks like you do have `uuid6>=2024.1.12` but the metadata in that package is probably wrong. I would disable `pip check` for now.

Thanks, I'll try it.

Note: pip check disabled as uuid6 metadata seems not to be up to date.

**Comment by ocefpaf** [comment]
BTW, unless you are building from a git checkout, you won't get the right version reported for that package:

https://github.com/oittaa/uuid6-python/blob/4f879849178b8a7a564f7cb76c3f7a6e5228d9ed/setup.py#L15-L19

I have no idea why people do that :-/
I would open a but report upstream but skip pip-check for now.

**Comment by BenediktBurger** [comment]
Thanks for your feedback, @ocefpaf , now the tests succeeded, would you mind reviewing the PR?

**Pull request merged**
