### PR TITLE
Add spechomo and specclassify

### PR DESCRIPTION
**Pull request by danschef**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by danschef** [comment]
The spechomo package depends on [nested_dict](https://pypi.org/project/nested_dict/) which is not on conda-forge yet and from which I am not the author. How can this be handled?

**Comment by scopatz** [comment]
@danschef - please just put in a PR for nested_dict if you would like to see that (or any other) package on conda-forge. You need not be the original author

**Comment by danschef** [comment]
Can I also push the recipe for nested dict here?

**Comment by danschef** [comment]
> For recipes/nested_dict:
> 
>     Failed to even lint the recipe

Is this probably due the package name featuring an underscore? Do I have to rename it to nested-dict?

**Comment by danschef** [comment]
@conda-forge/staged-recipes

This is ready for review.

**Comment by danschef** [comment]
Thanks @scopatz!

**Pull request merged**
