### PR TITLE
Added engarde recipe

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @phobson

**Comment by TomAugspurger** [comment]
Fixing the license issue now.

**Comment by synapticarbors** [comment]
I think that the license file is missing from the distribution since it isn't included in the `MANIFEST.in`.

**Comment by TomAugspurger** [comment]
Should be there now (just released 0.3.2 w/ the license included). Last commit was looking for `LICENSE.txt` instead of `LICENSE`. I hope this one passes.

**Comment by synapticarbors** [comment]
ok, just didn't see the changes reflected on github. I downloaded the tarball from pypi.io and it looks to be there so hopefully that should fix it.

**Comment by TomAugspurger** [comment]
> ok, just didn't see the changes reflected on github. 

Huh. I guess `git push --tags` doesn't push new commits, just tags.

All green now.

**Comment by scopatz** [comment]
Hi @TomAugspurger, can you please enable CircleCI on your fork of staged recipes? The PR won't run on linux without it

**Comment by TomAugspurger** [comment]
Enabled circle, and we're all green 🎉

**Comment by scopatz** [comment]
LGTM, thanks!

**Pull request merged**
