### PR TITLE
Miktex portable

### PR DESCRIPTION
**Pull request by janschulz**
miktex is a Latex environment for windows.

These packages are based on the ones found at
https://github.com/ClinicalGraphics/conda-recipes/tree/master/miktex-portable
https://github.com/ClinicalGraphics/conda-recipes/tree/master/miktex

related to https://github.com/conda-forge/staged-recipes/issues/359

CC: @jakirkham @ivoflipse @Korijn @ocefpaf

Closes: https://github.com/conda-forge/staged-recipes/pull/469

### CODE REVIEW

**Comment by janschulz** [comment]
JFYI: So, this should contain all commits in the old PR and includes now three new commits: more installed latex packages (and silent post-link.bat, even on update), rename to miktex (`s/-portable//` in most cases) and a fix if the env path contains a space. 

The packages was tested locally by building (and having the tests succeed) and by installing into the root environment and running a nbconvert.

**Comment by janschulz** [comment]
Thanks fr merging :-)

**Comment by jakirkham** [comment]
We should delete the `miktex-portable` team as we have renamed the feedstock `miktex` and everyone is on that team. Sound good, @ocefpaf?

**Comment by ocefpaf** [comment]
Sure.

**Pull request merged**
