### PR TITLE
Added pylyzer as a package

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge/rust @conda-forge/staged-recipes Need some rust help with the following error:

```
error[E0658]: use of unstable library feature 'unzip_option': recently added
     --> /home/conda/staged-recipes/build_artifacts/pylyzer_1680888250565/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_compiler-0.6.10-nightly.1/lower.rs:672:30
      |
  672 | ...                   .unzip();
      |                        ^^^^^
      |
      = note: see issue #87800 <[https://github.com/rust-lang/rust/issues/87800>](https://github.com/rust-lang/rust/issues/87800%3E) for more information
```

**Comment by timkpaine** [comment]
@thewchan https://github.com/rust-lang/rust/issues/87800 says its an unstable feature as of rust `1.65` which is what was used in this PR, so it would need a feature flag.

**Comment by thewchan** [comment]
@timkpaine Is it possible to specify `rust >= 1.66` now in the recipe? Or do I need to wait for it to be "stabilized"?

**Comment by timkpaine** [comment]
> Is it possible to specify `rust >= 1.66` now in the recipe? Or do I need to wait for it to be "stabilized"?

Its the feature that was stabilized in the rust language as of rust version 1.66, nothing to do with conda. Just conda defaults rust to 1.65 when using `compiler('rust')`

**Comment by thewchan** [comment]
Am I doing something wrong here @timkpaine I thought I did use `rust >=1.66`?

**Comment by timkpaine** [comment]
can you see if it rerenders

**Comment by thewchan** [comment]
@conda-forge/staged-recipes ready for review

**Pull request merged**
