### PR TITLE
Adding kats

### PR DESCRIPTION
**Pull request by rohanfb**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by rohanfb** [comment]
Hello, it looks like https://libraries.io/conda/kats has a automatic build of our Kats library on conda which unfortunately has errors when it is installed. Is there a way we can replace this with our PR here?

**Comment by rohanfb** [comment]
Any guidance on getting our build to be compliant as well with the current requirements would be much appreciated. A conda install has been heavily requested by our users. Thank you!

**Comment by rohanfb** [comment]
@conda-forge-admin, please ping team

Please see above, would appreciate any guidance you can provide here. Thank you!

**Comment by rohanfb** [comment]
@conda-forge-admin, please ping team

Just a follow up to above regarding Meta's Kats library. Thanks!

**Comment by carterbox** [comment]
Hi @rohanfb, conda-forge is not affiliated in any way with https://libraries.io/. If you have problems with the exisiting kats package on conda-forge please open an issue at the existing[ kats feedstock](https://github.com/conda-forge/kats-feedstock).

**Pull request closed without merging**
