### PR TITLE
Add mlir-{tblgen,linalg-ods-gen} as separate feedstocks

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xhochy** [comment]
@isuruf I was annoyed by the dependency of `mlir` on `clang-activation` to be bumped to the same version. Adding these two separate feedstocks enables cross-compilation without the need of `llvmdev` in the `build` section of `mlir`. Along with https://github.com/conda-forge/mlir-feedstock/pull/10 I was able to fully build this for `osx-64` and `osx-arm64` on my Intel Mac. This would greatly help me maintaining the `mlir` feedstock and would also enable builds of specific `mlir` commits that we could then reuse in Tensorflow or JAX to trim down the build time significantly.

**Comment by isuruf** [comment]
> I was annoyed by the dependency of mlir on clang-activation to be bumped to the same version. 

I don't understand this part. What are you trying to achieve?

**Comment by xhochy** [comment]
> > I was annoyed by the dependency of mlir on clang-activation to be bumped to the same version.
> 
> I don't understand this part. What are you trying to achieve?

The following line https://github.com/conda-forge/mlir-feedstock/blob/41f5c04ee6261e4a790cfefd90e2cd8199af6fd9/recipe/meta.yaml#L25 introduces a dependency on `llvmdev {{ version }} -> llvm-tools {{ version }}` while at the same time the compiler (clang) on `osx-*` depends via `clangxx_* {{ cxx_compiler_version }} -> clang {{ cxx_compiler_version }} -> llvm-tools {{ cxx_compiler_version }}`.

**Comment by isuruf** [comment]
Can we do something like https://github.com/conda-forge/blas-feedstock/blob/7dc8c1800face87c364de873299d5fe9b58a3fda/recipe/build.sh#L28-L34 ?

**Comment by isuruf** [comment]
Or just use `clang_bootstrap` instead of `clang`

**Comment by xhochy** [comment]
Used `clang_bootstrap`.

**Pull request closed without merging**
