### PR TITLE
Add werkzeug recipe

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by jakirkham** [comment]
LGTM.

**Comment by goanpeca** [comment]
Merge @jakirkham :-) ?

**Comment by jakirkham** [comment]
Yeah, I'm trying to give Travis CI some time to resolve the current backlogged. So I'm going to hold off on merging for a bit. Once that issue clears up I'll be happy to merge.

**Comment by jakirkham** [comment]
Seems the queue has shortened a bit. Am going to try to put this and a few other things in while activity is (relatively 😉) low.

**Pull request merged**
