### PR TITLE
Added recipe for openstacksdk

### PR DESCRIPTION
**Pull request by pmlandwehr**
The [`python-openstacksdk`](https://github.com/openstack/python-openstacksdk) is a collection of libraries for building applications to work with OpenStack clouds. Despite the `python-` prefix, it's tracked in pypi as [`openstacksdk`](https://pypi.python.org/pypi/openstacksdk)

### CODE REVIEW

**Comment by ocefpaf** [comment]
LGTM

**Comment by jakirkham** [comment]
This is stuck too.

**Comment by jakirkham** [comment]
Though it appears to have converted correctly. So, we can remove it manually.

**Comment by jakirkham** [comment]
@TerryHowe @briancurtin @rtheis @tengqm, just letting you know we have added `openstacksdk` to [conda-forge]( http://conda-forge.github.io/ ). This will allow users to easily install this with [`conda`]( http://conda.pydata.org/docs/ ) (`conda install -c conda-forge openstacksdk`). The maintenance burden here is light as all testing releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this repo]( https://github.com/conda-forge/openstacksdk-feedstock ). If you have any interest in being added as a maintainer (to make new releases for instance), we would love to have you on board. Thanks for your work on `openstacksdk`. 😄

**Pull request merged**
