### PR TITLE
Add custom-inherit-2.2.1 recipe

### PR DESCRIPTION
**Pull request by rsokl**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vend other packages
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rsokl** [comment]
Note that the generated pypi url was not correct. I commented on this [here](https://github.com/conda-forge/staged-recipes/issues/9619), on an issue that seems to have been closed prematurely.

**Comment by Zeitsperre** [comment]
Yes, I just noted this as well. Really strange.

**Comment by Zeitsperre** [comment]
It seems to be working now with your work-around. What's missing here is that the license needs to be added to the Manifest file.

**Comment by rsokl** [comment]
@Zeitsperre I believe I just had the path wrong

**Comment by Zeitsperre** [comment]
Looking at the tarfile file available on PyPI shows that the License.md file isn't in the package. Conda-forge builds directly off of the package available in PyPI. The easiest way to handle this is to add the License.md to the Manifest.in and push a new version with the original filepath that was in the recipe.

**Comment by rsokl** [comment]
Yep! You're totally right. Was looking at the wrong tarball. I'll have to loop back on this later.

Thanks for the help!

**Comment by rsokl** [comment]
Closed in favor of #9858

**Pull request closed without merging**
