### PR TITLE
Add package rust-src

### PR DESCRIPTION
**Pull request by sshockwave**
`rust-src` is a `rustup` component. Needed when using `rust-analyzer` with editors like VSCode.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sshockwave** [comment]
@conda-forge/staged-recipes ready for review! It's a noarch package so I suppose that failing builds on Win & OSX can be ignored?

**Comment by pkgw** [comment]
Thanks! CC @conda-forge/rust.

**Comment by sshockwave** [comment]
Oops, I didn't know the rust team exists. Maybe time to update the PR template 😉

Thanks for the link to the existing issue!

**Comment by isuruf** [comment]
I think it's better if this was an output in `rust-feedstock`

**Comment by sshockwave** [comment]
> I think it's better if this was an output in `rust-feedstock`

But not every installation of rust needs the source. The source is ~28.1MB (3.5MB gzipped), which does not seem negligible.

**Comment by isuruf** [comment]
I mean as a different output in the same recipe, not in the same package.

**Comment by sshockwave** [comment]
I see. I agree with you.

**Comment by sshockwave** [comment]
The default source of rust distribution [does not bundle `rust-src`]. If we add this to the `rust` feedstock, the recipe will need more sources and become messier. Any suggestions? @isuruf

**Comment by isuruf** [comment]
It's one more source, I don't see how it becomes messier. `source` can be a list of sources instead of just one.

**Comment by sshockwave** [comment]
Alright, I'll add a PR there.

**Pull request closed without merging**
