### PR TITLE
Add recipe for requests-mock

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge/staged-recipes I've opened a discussion with @conda-forge/bioconda-recipes in https://github.com/orgs/conda-forge/teams/bioconda-recipes/discussions/1, is there anything else I should be doing?

**Comment by ocefpaf** [comment]
Don't worry. Even though that is listed as a lint failure it is more of a suggestion.

(I'll fix that in the linter.)

@bgruening are you OK with us merging this?

**Comment by ocefpaf** [comment]
xref.: https://github.com/conda-forge/conda-smithy/pull/809

**Comment by nicoddemus** [comment]
Thanks @ocefpaf!

**Pull request merged**
