### PR TITLE
Add cos7 CDTs for libGL

### PR DESCRIPTION
**Pull request by jayfurmanek**
@conda-forge/staged-recipes 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jayfurmanek** [comment]
Needed to get gstreamer finally building for the cos7 arches (aarch64/ppc64le)

**Comment by jayfurmanek** [comment]
@hmaarrfk FYI

**Comment by jayfurmanek** [comment]
This adds:
`libglvnd-cos7-aarch64-feedstock`
`libglvnd-cos7-ppc64le-feedstock`
`libglvnd-glx-cos7-aarch64-feedstock`
`libglvnd-glx-cos7-ppc64le-feedstock`
`mesa-khr-devel-aarch64-feedstock`
`mesa-khr-devel-ppc64le-feedstock`
`mesa-libgl-cos7-ppc64le-feedstock`
`mesa-libglapi-cos7-ppc64le-feedstock`

**Comment by scopatz** [comment]
CC @isuruf

**Comment by hmaarrfk** [comment]
Is there a way for us to merge the different architectures into one feedstock?

**Comment by isuruf** [comment]
You could, if you wanted to. Do you want to take a stab or shall I merge this as is?

**Comment by jayfurmanek** [comment]
I agree it would be nice to have multi-arch recipes, but I don't have the time currently to rework these.
The only thing of note with these as it is now is I added a libGL.so sym link to point to the real lib - that was missing from the RPM, but needed in the gstreamer recipe.

**Pull request merged**
