### PR TITLE
Add pdbfixer

### PR DESCRIPTION
**Pull request by hadim**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hadim** [comment]
I am confused about why `openmm` is not available. See:

- https://github.com/conda-forge/openmm-feedstock
- https://anaconda.org/conda-forge/openmm

ping @conda-forge/staged-recipes

**Comment by hadim** [comment]
Ping @conda-forge/openmm

**Comment by beckermr** [comment]
Try a constraint for py36 or greater.

**Comment by jaimergp** [comment]
`openmm` is not officially available in `conda-forge` yet. We are releasing experimental packages in the `testing` label for now. There are some blocking issues (how we handle OpenCL) that will need to be solved before we publish to `main`. See these issues for more details:

- https://github.com/conda-forge/openmm-feedstock/pull/7
- https://github.com/conda-forge/conda-forge-enhancement-proposals/issues/17

Also, once we have pushed `openmm` to `main`, all packages in the `omnia` channel (including `pdbfixer`) will follow. Until then, I think it's better if we wait... sorry!

**Comment by hadim** [comment]
Sounds good to me. Should I close this PR then since you plan to integrate `omnia`? Or should I let it open and wait for an `openmm` to be in `main`?

**Comment by peastman** [comment]
Please hold off on this.  We're currently reconsidering whether we actually want to move OpenMM to conda-forge or not.  If we decide not to, then PDBFixer won't get moved either, so any steps in that direction are premature.

**Comment by hadim** [comment]
Ok.

*My two cents*: For what it's worth I prefer to have as must as packages possible in a single channel (`conda-forge`) than spread over multiple channels.

**Comment by peastman** [comment]
Understood!  But it's also become clear that moving to conda-forge would impose severe restrictions on how we could develop OpenMM in the future, so we're currently having offline conversations about this.

**Comment by hadim** [comment]
I understand your point. In any case, let us know your decision.

**Comment by jchodera** [comment]
Thanks for creating this! A lot of us are quite excited for the potential of having `openmm` and `openmm`-dependent tools available on conda-forge.

**Comment by simonbray** [comment]
Any progress on this front? Would be great to see pdbfixer and other omnia tools in conda-forge.

**Comment by jaimergp** [comment]
I'd say we are close to making CF builds available. Some more testing is needed, but after that we will start migrating packages from omnia!

**Comment by jaimergp** [comment]
For those following this conversation, we are almost there! Check https://github.com/conda-forge/openmm-feedstock/issues/37 for more information about how to test `openmm` before we move to `main`. The additional ecosystem will be added once that happens (check https://github.com/conda-forge/staged-recipes/pull/13234).

**Pull request closed without merging**
