### PR TITLE
HoloPy [WIP]

### PR DESCRIPTION
**Pull request by barkls**
We are preparing an upcoming release of our package to analyse holographic microscopy images. While we are finishing things up, we would like to get it running smoothly on conda-forge. We have some fortran code, and we would ideally like to distribute across all platforms. What is the current status of compiling fortran on Windows? @conda-forge-manager

### CODE REVIEW

**Comment by jakirkham** [comment]
So the best that we can offer is using `m2w64-gcc-fortran`, which AFAIK is a `conda` repackaging of the MinGW-w64 'gfortran` compiler as provided by MSYS2. This will also require adding `m2w64-gcc-libgfortran` as a run time dependency. @mingwandroid should be able to say more (and correct any misspeaks on my part :wink:).

Also as FYI `@conda-forge-manager` is a bot. Please use `@conda-forge/core` or `@conda-forge/staged-recipes` for the Core team or staged-recipes review team respectively.

**Comment by barkls** [comment]
Thanks for the quick response. Is there another recipe you can point me to that has implemented this solution? I suspect I need a bld.bat, but I'm not sure what to put in it.

**Comment by barkls** [comment]
I'm  don't know why appveyor has stopped picking this up...

**Comment by barkls** [comment]
I've tried a few things and haven't been able to get this to work. Any advice @jakirkham @mingwandroid ? Are there examples of recipes that have successfully compiled fortran on windows using m2w64-gcc-fortran?

**Comment by jakirkham** [comment]
Ray is the expert here. I'll let him respond. 😉

**Pull request closed without merging**
