### PR TITLE
Add sardana recipe

### PR DESCRIPTION
**Pull request by beenje**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

I added the LICENSE to the recipe because it wasn't part of the Python package. I created a PR https://github.com/sardana-org/sardana/pull/1490 so it's included in next release.

### CODE REVIEW

**Comment by beenje** [comment]
@cpascual and @reszelaz, could you please check the recipe and confirm you want to be listed as maintainers?

**Comment by cpascual** [comment]
> @cpascual and @reszelaz, could you please check the recipe and confirm you want to be listed as maintainers?

I confirm thaat I agree to be listed as maintainer

**Comment by cpascual** [comment]
I also checked the recipe and it all looks ok to me. 

Note: why do the builds fail for win and osx? Does it have to do with pytango not being available for those platforms? In such case, should they be disabled in the sardana recipe, or just allow to fail until pytango becomes available?

**Comment by reszelaz** [comment]
> @cpascual and @reszelaz, could you please check the recipe and confirm you want to be listed as maintainers?

I'm willing to be listed as maintainer.

**Comment by beenje** [comment]
@cpascual thanks for the check! Indeed the build fails on OSX and Windows because `pytango` is only available on Linux.
`noarch: python` recipes are only built on Linux once converted to an official feedstock. It's only under staged recipes that they are built on all platforms. So the build failure on Windows and OSX doesn't matter.

People won't be able to install `sardana` on those platforms as long as `pytango` isn't available. Once it is, it will be possible to install `sardana` without having to update the recipe. This is what I was told for the `itango` recipe :-)

**Comment by beenje** [comment]
@conda-forge/help-python, this PR is ready for review!

**Comment by stanislaw55** [comment]
Hi all,
just wanted to throw my $0.02.
How about splitting sardana package into multiple ones? Just like it was done with `taurus`
Example of what packages could be separated
* `sardana-core` - well, core of Sardana
* `sardana-spock` - Spock command line client
* `sardana-taurus` - all Taurus widgets and other GUIs
* `sardana-tango` - MacroServer, Pool and Sardana Device Servers
* `sardana` - meta package depending on all others, for compatibility

**Comment by beenje** [comment]
@stanislaw55, it could definitively be done. I see that the PRs you mention aren't in the current release (3.0.3).
So I propose that the current recipe stays as is for 3.0.3.
We can take the decision on splitting and how for next release. Can you maybe open an issue on the [sardana](https://github.com/sardana-org/sardana) repo to keep track on this?

Or do you have another opinion @reszelaz?

**Comment by reszelaz** [comment]
> How about splitting sardana package into multiple ones?

It makes sense to me! If I understands correctly the split will only affect the dependencies and scipts installations? All the sardana python modules will be installed regardless which `sardana-...` package will be installed? 

As @beenje said we would need to wait for sardana 3.1 (which will come in a month or so) to try this.

Regarding the naming of packages I agree with @stanislaw55. When reading them I stopped for a while on on `sardana-taurus` and though about an alternative name: `sardana-qt`. But I don't have a clear preference between them.

**Comment by stanislaw55** [comment]
> It makes sense to me!

Glad you like it.

> If I understands correctly the split will only affect the dependencies and scipts installations? All the sardana python modules will be installed regardless which `sardana-...` package will be installed?

That's one way to do it. I'm not conda expert so I do not know how it was done for Taurus. For me, it would make more sense to split the package itself, along with scripts from entrypoints in different conda packages. That would probably require more effort.

Waiting for release 3.1 makes sense to me as well. Should I create issue to keep track of this idea in sardana-org/sardana repository, @reszelaz?

**Comment by reszelaz** [comment]
> Waiting for release 3.1 makes sense to me as well. Should I create issue to keep track of this idea in sardana-org/sardana repository, @reszelaz?

Sure, go ahead! Thanks!

**Comment by stanislaw55** [comment]
I've created https://github.com/sardana-org/sardana/issues/1493

**Comment by beenje** [comment]
@conda-forge/help-python, sorry to ping again, but I think this PR might have been lost due to the discussion about splitting the recipe in subpackages.
This will have to wait for a new release upstream.

We'd like the recipe to stay as it for this version. Thanks!

**Pull request merged**
