### PR TITLE
r-* packages finalize subdag 1

### PR DESCRIPTION
**Pull request by bgruening**
finalize subdag 1 from https://github.com/bioconda/bioconda-recipes/issues/5582

cc @daler and @jdblischak

### CODE REVIEW

**Comment by jdblischak** [comment]
This PR needs PR https://github.com/conda-forge/staged-recipes/pull/3828 to be merged first. Waiting on r-deldir, r-expm, and r-gmodels.

**Comment by bgruening** [comment]
mh, seems we missed r-expm, there is no feedstock :(

**Comment by bgruening** [comment]
ok, looks better!

**Comment by bgruening** [comment]
Wuhu, its green!
ping @ocefpaf

**Pull request merged**
