### PR TITLE
Add font-ttf-dejavu package

### PR DESCRIPTION
**Pull request by rhpvorderman**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
@conda-forge/staged-recipes  Sorry to bother you all. This is a font package and as such does not fall into any language category.

Conda-forge currently has not a font package that fullfills the following requirements:
- A proper collection of sans, serif and monospace fonts
- Proper integration with fontconfig

font-ttf-ubuntu does have all the fonts, but it does not install the fontconfig files. 

The DejaVu fonts are available under a free license, support a wide range of symbols (including math symbols) and have serif, sans and monospace fonts.

This is useful for packages that render fonts. Such as r-ggplot2

**Comment by rhpvorderman** [comment]
@conda-forge/help-r 
Can you have a look at this repository? Currently all plots generated with r-ggplot2 in biocontainers do not output characters in the rendered plots but square rectangles instead. 
afbeelding

This is because most docker containers do not include fonts.

**Comment by rhpvorderman** [comment]
Can somebody please merge this? As stated, having a full-fledged font package in conda-forge would be very useful.

**Comment by jonashaag** [comment]
@rhpvorderman In the readme it say to ping @conda-forge/staged-recipes

So, @conda-forge/staged-recipes, ready :)

**Comment by rhpvorderman** [comment]
Thank you! I will keep that in mind for next time :).

**Pull request merged**
