### PR TITLE
Adding pyfit-sne

### PR DESCRIPTION
**Pull request by yihming**
This recipe includes a python wrapper of FIt-SNE package. There is already a similar recipe `fit-sne` on conda-forge, but since it only includes the CPP binding and cannot be directly used in Python, we decide to submit this recipe. The python wrapper is also from FIt-SNE team's official source.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by yihming** [comment]
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I just wanted to let you know that I linted all conda-recipes in your PR (`recipes/pyfit-sne`) and found it was in an excellent condition.
> 
> I do have some suggestions for making it better though...
> 
> For **recipes/pyfit-sne**:
> 
> * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.
> 
> Documentation on acceptable licenses can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions).

The license is set to be consistent with `fit-sne` recipe on conda-forge at https://github.com/conda-forge/fit-sne-feedstock/blob/master/recipe/meta.yaml#L29.

**Review by dopplershift — APPROVED** [review]
Looks good. @bli25broad are you ok with being a maintainer on this recipe?

**Comment by bli25broad** [comment]
Yes, I'm OK.

Best,
Bo

Bo Li, Ph.D.
Assistant Professor of Medicine, Harvard Medical School
Director, Bioinformatics and Computational Biology Program, Center for
Immunology and Inflammatory Diseases, Massachusetts General Hospital
Associate Member, Broad Institute of MIT & Harvard
149 13th Street, Room 8214, Charlestown, MA 02129

**Comment by yihming** [comment]
@dopplershift Bo has agreed to be a maintainer of this recipe.

**Pull request merged**
