### PR TITLE
Readd vaex

### PR DESCRIPTION
**Pull request by maartenbreddels**
Requesting new token, see https://github.com/conda-forge/conda-forge.github.io/issues/426

### CODE REVIEW

**Comment by maartenbreddels** [comment]
should this ci failure be fixed here, or when the new token is in the vaex-feedstok? (this is the master from vaex-feedstock btw)

**Comment by mwcraig** [comment]
I'd say fix it in the feedstock -- what is the underlying cause of the error?

**Comment by maartenbreddels** [comment]
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
It's been built with numpy 1.13, but can only install 1.12 since one of the dependencies is only done for 1.12.

**Comment by maartenbreddels** [comment]
This should be the guilty one: https://github.com/conda-forge/staged-recipes/pull/3667

**Comment by maartenbreddels** [comment]
great, resolved!

**Pull request merged**
