### PR TITLE
add gmpacket

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@emthompson-usgs and @mhearne-usgs this package is needed in https://github.com/conda-forge/gmprocess-feedstock/pull/81 but nothing seems to provide `seis_prov_validate`. Do you have any pointers for us here?

**Comment by emthompson-usgs** [comment]
Thanks @ocefpaf we didn't catch this issue before. Here is the page for the seis prov validator: 
http://seismicdata.github.io/SEIS-PROV/validation.html#official-validator
To my knowledge there's no conda or pip package.

**Comment by ocefpaf** [comment]
> To my knowledge there's no conda or pip package.

Or a GitHuib tag :-/

The package is quite old and a bit hard to build without a proper release. Nor sure how to proceed here.

**Comment by emthompson-usgs** [comment]
I think the best thing will be for me and @mhearne-usgs to figure out how to remove the dependency. It will probably be something that we can't get to right away though.

**Comment by ocefpaf** [comment]
> It will probably be something that we can't get to right away though.

NP. We can try again when this is done. I'll leave this PR open.

**Comment by ocefpaf** [comment]
This version still relies on something that is not shipping with it:

```
+ gmpformat --help
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/gmpacket_1679315367016/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/gmpformat", line 7, in <module>
    from gmpacket.bin.gmpformat import main
  File "/home/conda/staged-recipes/build_artifacts/gmpacket_1679315367016/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/gmpacket/bin/gmpformat.py", line 4, in <module>
    from gmpacket.gmpformat import run_gmpformat
  File "/home/conda/staged-recipes/build_artifacts/gmpacket_1679315367016/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/gmpacket/gmpformat.py", line 6, in <module>
    from gmpacket.scan import scan_gmp
  File "/home/conda/staged-recipes/build_artifacts/gmpacket_1679315367016/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/gmpacket/scan.py", line 8, in <module>
    from gmpacket.validate import gmp_validate
  File "/home/conda/staged-recipes/build_artifacts/gmpacket_1679315367016/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/gmpacket/validate.py", line 9, in <module>
    from seis_prov_validate import validate
ModuleNotFoundError: No module named 'seis_prov_validate'
```

**Comment by emthompson-usgs** [comment]
Thanks @ocefpaf, we need to remove that dependency. We will do so in the next release.

**Comment by gferragu** [comment]
Hi @ocefpaf, just wanted to update you on the status of `gmpacket`. We decided the easiest way to get around the `seis-prov` dependency issues was to just remove the CLI program `gmpformat.py` from the package. Hopefully that allows the`gmpacket` recipe to go smoothly. It is not yet updated on PyPi but should be soon.

**Comment by gferragu** [comment]
@ocefpaf, the new version 0.1.3 is available now via PyPi 👍

**Comment by ocefpaf** [comment]
@conda-forge/staged-recipes this one is ready to go!

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
