### PR TITLE
posix-win

### PR DESCRIPTION
**Pull request by kiwi0fruit**

### CODE REVIEW

**Comment by beckermr** [comment]
This will need to be discussed with @conda-forge/core.

**Comment by kiwi0fruit** [comment]
Hm, yes. I guess that would be a bad precedent. What is needed is an extension of the noarch options.

**Comment by msarahan** [comment]
This is an OK workaround for selectors not being usable in noarch recipes.  A better fix is to have proper support in conda for conditional dependencies, so that selectors or something like them could be valid in noarch packages.  The right place for that discussion is the conda repo.  PRs towards design or implementation would be welcome.

**Comment by kiwi0fruit** [comment]
@msarahan Thanks!

@beckermr please merge.

**Comment by kiwi0fruit** [comment]
I guess `bash` on windows depending on `posix` metapackage is preferable as it's almost always needs a big portion of ecosystem. What do you think?

**Comment by kiwi0fruit** [comment]
But such a dendense will also introduce a mess about bash version: it would be inconsystent for win and unix.

**Comment by isuruf** [comment]
@kiwi0fruit, if your package depends on other tools, they should be included in unix packages like `sed`.

Send a PR to bash-feedstock to change the version to `4.3.042` which is what is available in `m2-bash`. We can merge that to a separate branch

**Comment by beckermr** [comment]
Let’s not merge until we work this out. I’ll leave this one to @isuruf to review and merge!

**Comment by kiwi0fruit** [comment]
@igortg in general case it's unknown what tools a bash script will use. Even now I should inspect at least activate and deactivate scripts to see what they. Need. But that's only my use-case. If the package to be useful it should be applicable to lots of use -cases. And tie toghether incrementally (when needed) msys2 and unix packages... Maybe it's a OK idea. But it seems rather inconvenient.

I know that I need bash, so it's a `m2-bash`. But I also need cygpath but I have no idea in what package it is.

**Comment by kiwi0fruit** [comment]
@igortg what about adding `posix` package for linux and macos for conda-forge that does absolutely nothing?

**Comment by isuruf** [comment]
>  in general case it's unknown what tools a bash script will use. Even now I should inspect at least activate and deactivate scripts to see what they. Need. But that's only my use-case. If the package to be useful it should be applicable to lots of use -cases.

If a package needs other tools, then the package should depend on them.

> what about adding posix package for linux and macos for conda-forge that does absolutely nothing?

I'm not a fan of that package doing nothing. It should at least depend on bash and other tools that the windows package depends on.

**Comment by kiwi0fruit** [comment]
@isuruf added win bash feedstock: https://github.com/conda-forge/bash-feedstock/pull/3

**Comment by kiwi0fruit** [comment]
@isuruf [patching bash](https://github.com/conda-forge/staged-recipes/pull/7649) is totally useless for me. I need to depend on posix metapackage, not just bash. So I'm only interested in this posix [unix only] package.

**Comment by kiwi0fruit** [comment]
> I'm not a fan of that package doing nothing

it's simply a workaround for the limitations of the noarch specification

**Comment by kiwi0fruit** [comment]
@conda-forge/core Will this be merged or it's definitely a no-go?

**Comment by kiwi0fruit** [comment]
> It should at least depend on bash and other tools that the windows package depends on.

But that seems redundant. If we are already on posix system why install all this again? I guess there can be reasons but do not align with the reason of this PR. Mixing the following use-cases is a bad idea:

* the need to have posix tools from conda on unix
* have posix on windows and write noarch package

**Comment by kiwi0fruit** [comment]
Or may be `posix-win` that depends on `posix  # [win]` and dummy otherwise would be better? so that there is no expectations that it would install conda-compiled posix tools on unix?

**Comment by kiwi0fruit** [comment]
`posix` metapackage also works unsatisfactory for me. presumably it messes with antivirus...

**Pull request closed without merging**
