### PR TITLE
Add recipe for brax

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by erikfrey** [comment]
Happy to help maintain this.  Thank you @traversaro !

**Comment by traversaro** [comment]
> I do not know why such an old jaxlib is installed.

The problem is grpc. Installing grpcio brings in grpcio 1.48, but the current pin for grpc is 1.47 .

**Comment by traversaro** [comment]
To ensure that a compatible jaxlib is availale, I added the constraint `jaxlib >=0.3.7`, and I opened the issue https://github.com/conda-forge/jax-feedstock/issues/102 to report the issue upstream.

**Comment by traversaro** [comment]
@conda-forge/help-python The recipe is ready for review, as this is a noarch python package, and the as the Windows failure is caused by missing dependencies, it can be safely ignored.

**Review by dopplershift — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks a lot @dopplershift and @ngam !

**Pull request merged**
