### PR TITLE
Add shade (openstack-ansible interaction library)

### PR DESCRIPTION
**Pull request by brainstorm**
Breaking up dependencies for PR #3421 (OpenStack+Ansible)

### CODE REVIEW

**Comment by brainstorm** [comment]
Depends on PR #3433 being merged/uploaded.

**Comment by brainstorm** [comment]
Woho! Just one more pullrequest to merge to have Ansible 2.x in conda-forge! @conda-forge/staged-recipes, can you merged this one so that I can move on to #3435 ?

**Comment by synapticarbors** [comment]
@brainstorm -- Happy to merge this, but it looks like the package should support python 3. Any reason why you're skipping it?

**Comment by brainstorm** [comment]
@synapticarbors I would like to check the ansible-shade functionality first (1 remaining PR) to assess a pipeline I'm working on. Ansible python3 support is still experimental so no big upfront benefit of putting tons of time on oslo.utils and others behaving with python3 (version pinning nightmare ahead).

Happy to revisit it (or some other contributor) when things are integrated/merged in for py2 first (thinking of a [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product), then iterate/polish later if it works).

**Comment by brainstorm** [comment]
@synapticarbors It seems like some [TravisCI/CircleCI process failed after creating the feedstock](https://circleci.com/gh/conda-forge/shade-feedstock)? There's no `shade` to be found when searching for it after 11 hours :-S

```
$ conda search shade --channel conda-forge
Fetching package metadata .............
datashader                   0.1.0                    py27_0  defaults
                             0.1.0                    py34_0  defaults
                             0.1.0                    py35_0  defaults
                             0.2.0                    py27_0  defaults
                             0.2.0                    py34_0  defaults
                             0.2.0                    py35_0  defaults
                             0.3.0                    py27_0  defaults
                             0.3.0                    py34_0  defaults
                             0.3.0                    py35_0  defaults
                             0.4.0                    py27_0  defaults
                             0.4.0                    py34_0  defaults
                             0.4.0                    py35_0  defaults
                             0.4.0                    py36_0  defaults
```

**Comment by brainstorm** [comment]
Poking at it via PR https://github.com/conda-forge/shade-feedstock/pull/1

**Pull request merged**
