### PR TITLE
Add biom-format

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Looks good to me  :)

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes -- I think this is ready for a review and hopefully a merge.

**Comment by isuruf** [comment]
@conda-forge/bioconda-recipes, what do you think? Should we package biology related packages in conda-forge?

**Comment by jakirkham** [comment]
FWIW this sort of discussion has come up before. ( https://github.com/conda-forge/staged-recipes/pull/4112 ) There are some biology packages in conda-forge already. Off the top of my head `scikit-allel` and `scikit-bio`. That said, this would be a good discussion to have. We can save it for a meeting if people prefer or maybe open a webpage issue.

**Comment by cbrueffer** [comment]
Generally I can see two good reasons for some bio packages to live in conda-forge instead of bioconda: 1. to provide Windows packages (see e.g. biopython), 2. they are needed as dependency for other packages that are outside bioconda's domain, e.g. some general purpose R packages have bioconductor dependencies.

**Comment by scopatz** [comment]
I agree with the sentiment that a PR to staged-recipes is not the best forum for us to have large scale discussions about what class of recipes we should accept. 

This is a perfectly valid recipe which is blocking another PR. I am merging in order to keep things moving.

If you would like to have a broader discussion, please open an issue at https://github.com/conda-forge/conda-forge.github.io/issues

**Comment by bgruening** [comment]
@scopatz we do have rules for this. And the linter has even failed and warned a few days ago. This is a regression. Be aware that with this merge you are breaking many potential environments. These packages are now duplicated in two dependent channels :(

This should be discussed with the bioconda people. And a PR should be places in bioconda to remove at least the recipe from there github repo. Which will for sure trigger a discussion.

**Comment by scopatz** [comment]
@bgruening - feel freel to revert if needed!

**Comment by johanneskoester** [comment]
I vote for removing biom-format from conda-forge then. 
How is reverting technically done? Delete the repo, and remove the package from the channel I guess? @bgruening do you have the rights for that?

**Comment by dougalsutherland** [comment]
The package that depends on this, calour (https://github.com/conda-forge/staged-recipes/pull/5756), seems entirely like a bio thing as well ("exploratory and interactive microbiome analyses based on heatmaps"). It seems to me like just removing `biom-format` from conda-forge would be easiest, to avoid clashes with bioconda.

We should probably come up with some clearer guidelines for these things, though.

**Comment by scopatz** [comment]
> We should probably come up with some clearer guidelines for these things, though.

@dougalsutherland - yes I agree. As a reveiwer, I found this very confusing, because generally it seems like we shouldn't restrict any valid recipe.

**Comment by bgruening** [comment]
@johanneskoester I do have these rights I think. But I would like to have a broader discussion at first and some rules in place before I go ahead.

**Pull request merged**
