### PR TITLE
Add Fortran package manager recipe

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by certik** [comment]
Thanks for working on this! Let me know if you need any help.

**Comment by wolfv** [comment]
Cool! Happy to see this coming to conda-forge :)

**Comment by wolfv** [comment]
@certik maybe it would be good if you're a co-maintainer of that recipe?

**Comment by awvwgk** [comment]
Sure, @certik let me know if you are okay to co-maintain this recipe.

**Comment by certik** [comment]
Sure, go ahead and put me in.

Re windows: @wolfv, we currently need a more recent GFortran compiler (@awvwgk verison 8?). What do you recommend we do?

**Comment by wolfv** [comment]
unfortunately I don't know too much about the gfortran story on windows. Is it part of the m2 toolchain? (e.g m2w64-gcc-libgfortran ?)

If yes, these are somehow centrally generated and I think they are indeed in need of an update. But it's a bit of a task ... @xhochy or @isuruf might know more

**Comment by awvwgk** [comment]
There is https://anaconda.org/conda-forge/m2w64-gcc-fortran available via `{{ compiler('m2w64_fortran') }}`, but GCC 5 is tricky if not explicitly tested upstream since it is missing a lot of features for Fortran. We could work toward supporting flang, which seems to be the preferred solution (?), but this requires work upstream as well, at least one part of the program will break down horribly when build with flang.

The relevant issue might be: https://github.com/conda-forge/conda-forge.github.io/issues/1044

**Comment by xhochy** [comment]
> If yes, these are somehow centrally generated and I think they are indeed in need of an update. But it's a bit of a task ... @xhochy or @isuruf might know more

For the MinGW side, we definitely need https://github.com/conda-forge/conda-forge.github.io/issues/1044 to come to a more stable toolchain but otherwise I need to refer to @isuruf on the fortran-on-Windows topic.

**Comment by awvwgk** [comment]
Building on Windows with GCC 5 fails as expected, usually missing class polymorphic support like this:
```
fpm-0.1.4.f90:14509:12:

             cmd_settings=fpm_run_settings(&
            1
Error: Assignment to an allocatable polymorphic variable at (1) is not yet supported
```

I would suggest we just skip the Windows build for now and try to find a solution with the available toolchains upstream first.

**Pull request merged**
