### PR TITLE
Add rdkit-postgresql recipe

### PR DESCRIPTION
**Pull request by peterbygrave**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by peterbygrave** [comment]
I am willing to be a maintainer

**Comment by mfansler** [comment]
Is this just `rdkit` but with different build parameters? If so, I think it would be more appropriate to have [the existing rdkit-feedstock](https://github.com/conda-forge/rdkit-feedstock) generate it as an output, rather than having an independent feedstock.

**Comment by mfansler** [comment]
RDKit is not my expertise, but note that separate "package" does not require a separate recipe/feedstock. From looking over the `meta.yaml`, it looks like the source download is identical, which makes me think it would make sense that have one feedstock should track the `rdkit` source releases and then build the multiple versions.

Maybe @conda-forge/rdkit maintainers can chime in? Or consider dropping the feedstock an Issue to discuss it.

**Comment by peterbygrave** [comment]
> RDKit is not my expertise, but note that separate "package" does not require a separate recipe/feedstock. From looking over the `meta.yaml`, it looks like the source download is identical, which makes me think it would make sense to have one feedstock that tracks the `rdkit` source releases and then build the multiple versions/components.
> 
> Maybe @conda-forge/rdkit maintainers can chime in? Or consider dropping the feedstock an Issue to discuss it.

Thanks for advice, I have posted over there: https://github.com/conda-forge/rdkit-feedstock/issues/128

Build is now passing. There is an issue with `libcxx v16` (released 1 day ago). It drops support for `std::binary/unary_function`. Unclear whether that is rdkit-postgresql or boost issue at this point.

**Comment by peterbygrave** [comment]
Closing in favour of adding multiple outputs to the rdkit-feedstock repo https://github.com/conda-forge/rdkit-feedstock/issues/128

Thanks for all the feedback everyone!

**Pull request closed without merging**
