### PR TITLE
add recipe for spaghetti

### PR DESCRIPTION
**Pull request by jGaboardi**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jGaboardi** [comment]
@knaaptime Will you be co-maintainer?

**Comment by knaaptime** [comment]
I'm happy to help maintain this package

**Comment by jGaboardi** [comment]
pysal/spaghetti#265

**Comment by jGaboardi** [comment]
@conda-forge/staged-recipes. As per [#12 in README](https://github.com/conda-forge/staged-recipes#12-my-pull-request-passes-all-checks-but-hasnt-received-any-attention-how-do-i-call-attention-to-my-pr--what-is-the-customary-amount-of-time-to-wait), this recipe is ready to go.

**Comment by chrisburr** [comment]
Thanks for the reminder, LGTM 👍

**Comment by jGaboardi** [comment]
@chrisburr, thanks!

**Comment by jGaboardi** [comment]
@chrisburr I think I accidentally closed this PR. Did I screw something up or is everything OK?

**Pull request merged**
