### PR TITLE
Add mold recipe

### PR DESCRIPTION
**Pull request by ahadnagy**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ahadnagy** [comment]
@conda-forge/help-c

first-time conda-forge committer here. I need some help as I can't for the life of me figure out what's wrong with the Linux build for the package in this PR. It seems like a sysroot issue, but I haven't been able to get any closer than that.

The issue:
```
ninja: error: '/home/conda/feedstock_root/build_artifacts/mimalloc_1650029780752/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/libpthread.so', needed by 'mold', missing and no known rule to make it
```

This builds fine in every other environment I've tried. Also, if I build and link to the bundled `mimalloc` it works, but that's probably not what we want.

Any suggestions?

**Comment by ahadnagy** [comment]
@conda-forge-admin, please ping conda-forge/help-c conda-forge/staged-recipes

**Comment by ahadnagy** [comment]
Sorry, wrong team.

@conda-forge-admin, please ping conda-forge/help-python-c

**Comment by carterbox** [comment]
The fact that ninja is searching in a directory that it should not know anything about (`/home/conda/feedstock_root/build_artifacts/mimalloc_1650029780752/_build_env`) which is a path that only exists in the build environment of the mimalloc package means that mimalloc is broken.

**Comment by carterbox** [comment]
Please ping again when the issues with mimalloc are resolved or if you patch / delete the incorrect paths in the CMake files so your build completes.

**Pull request closed without merging**
