### PR TITLE
[wip] Added kudu-cpp recipe

### PR DESCRIPTION
**Pull request by xmnlab**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by cpcloud** [comment]
@xmnlab It looks like you somehow need to obtain the bitshuffle library. It looks like [there is a conda recipe for it](https://github.com/kiyo-masui/bitshuffle/tree/master/conda-recipe) though it appears to be about 3 years old. Unfortunately, it doesn't appear that it was ever brought into conda-forge.

**Comment by cpcloud** [comment]
I'm going to look into adding bitshuffle to conda-forge.

**Comment by cpcloud** [comment]
Looks like kudu is building its own object file: https://github.com/apache/kudu/blob/628322523420c6024f911357dec33626af9a915a/thirdparty/build-definitions.sh#L557 and not going through any kind of standard install process.

I've created https://github.com/kiyo-masui/bitshuffle, but I'm not sure it's sufficient to provide what kudu needs.

**Comment by xmnlab** [comment]
@cpcloud thanks for working on the bitshuffle package! I added some comment there! we are skipping here for windows, so I think you can skip there also and we can try to fix the issue for windows later.

**Pull request closed without merging**
