### PR TITLE
Re-add numpy-indexed for feedstock conversion

### PR DESCRIPTION
**Pull request by jakirkham**
This shouldn't be merged until we sort out the naming.

### CODE REVIEW

**Comment by jakirkham** [comment]
@ivoflipse @ EelcoHoogendoorn @Korijn, could you please let me know what this is suppose to be named? Appears to be a bit of confusion on this.

**Comment by ivoflipse** [comment]
I'd be in favor of numpy-indexed, since that's also what the scikit-packages use.

**Comment by Korijn** [comment]
:+1:

**Comment by jakirkham** [comment]
@EelcoHoogendoorn, thoughts on naming?

**Comment by EelcoHoogendoorn** [comment]
Right... I chose a dash for the package name, since i like dashes better than underscores, but then ofcourse you need an underscore for module names... so no particularly deep thoughts there. 

There is something to be said for using underscores for all names for consistency; i like being able to install with the same name that i encounted in a code sample; but alternatively one might opt to use dashes whereever possible. But unlike scitkits.image, we cant write import numpy.indexed as npi.

Or can we? Is it possible to package npi as a subpackage of numpy? not sure if pip digs this, and i would prefer to stay pip-compatible, but i imagine setting up your package this way is perfectly possible with conda. Though i can imagine that hyjacking another projects' namespace in this way is considered bad style.

Unlike what the git repo name suggests, ive pretty much let go of the idea of making a numpy EP out of this, since its still being iterated far too rapidly for it to make sense to tie it down to the numpy release schedule. But a numpy subpackage that is seperately maintained makes sense to me.

**Comment by ivoflipse** [comment]
scikit-image and scikit-learn use `skimage`/`sklearn` as their package name. You could do the same by naming it `npindexed` ;-) Also, similarly to pandas, you frequently abbreviate it to `npi`

But I'd still be in favor of numpy-indexed as the name

**Comment by EelcoHoogendoorn** [comment]
@jakirkham : could you articulate what exactly the issue is wrt naming? is it just that you are aesthetically bothered by the package/module _- thing, (as am I), or does this break some kind of requirement of the conda-forge system? if only the former, I think I am also in favor of keeping things the way they are.

**Comment by jakirkham** [comment]
The issue with naming is that it fails to convert to a feedstock when the directory name does not match the package name in `meta.yaml`. So, we have to pick one that matches.

If we are all happy with `-`, I will change it.

Sorry, I've been a bit caught up in other things around here today.

**Comment by jakirkham** [comment]
Is this ok, @EelcoHoogendoorn?

**Comment by jakirkham** [comment]
Admittedly this constraint (directory name matching `meta.yaml` package name) may be a bit silly and I don't know that it was intentional. We could probably go back through the code and just make it use the package name from `meta.yaml` for everything. Would that be preferable?

**Comment by EelcoHoogendoorn** [comment]
Ah got it; no its fine the way it is now id say, thanks!

**Comment by jakirkham** [comment]
Thanks everyone. This has been renamed to match what seems to be the unanimously decided name. Will happily merge once it passes CI. Sorry for the hold up.

**Comment by ivoflipse** [comment]
Hardly a hold up! Thank for all your hard work!

**Comment by jakirkham** [comment]
Of course.

Now let's get this one out the door. 😄

**Pull request merged**
