### PR TITLE
add keybase chat links

### PR DESCRIPTION
**Pull request by scopatz**
This is not a recipe PR

### CODE REVIEW

**Comment by scopatz** [comment]
CC @conda-forge/staged-recipes

**Comment by jakirkham** [comment]
This is meant to be a public chat room?

**Comment by scopatz** [comment]
Yep, it is! Anyone can join the `condaforge.chat` subteam

**Comment by jakirkham** [comment]
Yeah I'm neutral atm. I agree with Isuru's point. Though don't really object as long as people are willing to provide support there. I guess this is you volunteering to help in that forum @scopatz? 😉

**Comment by scopatz** [comment]
I would rather move to a secure communication channel and gitter basically doesn't work on mobile

**Comment by scopatz** [comment]
> I guess this is you volunteering to help in that forum @scopatz?

Yep exactly! :wink:

**Comment by beckermr** [comment]
I'm there too!

I have the same worries as @isuruf but am also very unhappy with gitter

**Comment by jakirkham** [comment]
Seem ok to me then.

(Should add I probably won't change due to technical inertia 😉)

**Pull request merged**
