### PR TITLE
firelight

### PR DESCRIPTION
**Pull request by constantinpape**
Recipe for firelight:
small library for nice pytorch tensor visualisations in Tensorboard:
https://github.com/inferno-pytorch/firelight/issues

@conda-forge/help-python
This is a python noarch package.
It depends on `pytorch`, which is not on `conda-forge` yet. That's why I am not running any
tests, but just try to import the pacakge (which should not pull in pytorch).

@imagirom: As main author of this package, I have added you to the maintainers here.
Please confirm if you would like to be added.

### CODE REVIEW

**Comment by constantinpape** [comment]
I am a bit confused by the tests:
- This is a `noarch: python` package, so I thought tests should only run on CircleCI ?
- The tests fail because the `pytorch` runtime dependency cannot be found. Indeed, `pytorch` is not on conda-forge. However, there are other packages which have a `pytorch` runtime dependency and are built successfully, e.g.:
https://github.com/inferno-pytorch/inferno-feedstock/blob/master/recipe/meta.yaml

**Comment by beckermr** [comment]
Test failures are fine here. Once all maintainers have confirmed we can merge!

Thanks for the contribution!

**Comment by imagirom** [comment]
@constantinpape I am confirming that I would like to be added as a recipe maintainer.

**Comment by constantinpape** [comment]
@beckermr 
Thanks for the review and merging this :).

**Pull request merged**
