### PR TITLE
Add recipe for PtvPy

### PR DESCRIPTION
**Pull request by lagru**
Dear devs,

I'd like to add this recipe to the conda-forge channel. One thing I wasn't sure about is whether running the full test suite is okay or whether that's to extensive.

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by lagru** [comment]
@conda-forge/help-python I'm unsure how to proceed. The package in question requires Python 3.6 or greater. I'm not supposed to use the selector `# [py<36]` together with `noarch: python` but without it the rest of the CI fails...

**Comment by lagru** [comment]
I think this is ready to merge now. Sorry for the long hiatus.

**Comment by lagru** [comment]
@conda-forge-admin, please ping team

**Comment by chrisburr** [comment]
Thank you for resurrecting this @lagru and I'm sorry that is was missed first time.

Running the test suite is fine provided as it doesn't take an excessively long time, especially if the package is `noarch` (as there is only 1 build instead of 12+).

**Comment by lagru** [comment]
@chrisburr No worries. Thanks for the feedback and reviewing this.

**Pull request merged**
