### PR TITLE
Add conda dependencies

### PR DESCRIPTION
**Pull request by jakirkham**
Broken out from PR ( https://github.com/conda-forge/staged-recipes/pull/656 ).

Adds recipes that either I wrote or used `conda skeleton pypi` to generate and then modified. Having some issue getting the `conda` recipe to build. The rest seem to be doing ok. Maybe we can break out the working ones and merge them first.

@msarahan, I have added you and myself as maintainers on all of these. Please let me know if that is ok. I don't feel a strong need to be a maintainer here, but I thought my handle should be on them as I wrote them.

### CODE REVIEW

**Comment by msarahan** [comment]
OK with me. Please add @kalefranz and @mcg1969 also if they are OK with it.

**Comment by jakirkham** [comment]
Do these recipes seem ok to you? I did something kind of hacky for `conda-env`, but am not sure if there is a better strategy.

**Comment by mcg1969** [comment]
@msarahan, what's the rationale for having `conda-env` not depend on `conda`? It clearly does.

**Comment by msarahan** [comment]
@mcg1969 is right.  Until conda 4.1 is fully released, the dependency is circular, due to activation scripts living in conda-env.

**Comment by mcg1969** [comment]
But the dependency solver has no trouble with circular dependencies.

**Comment by jakirkham** [comment]
So, I reverse engineered the `conda-env` recipe from packages I found in the `anaconda` channel. They did not list `conda` as a dependency.

**Comment by mcg1969** [comment]
Oh, I know, like I said above---our recipe doesn't have a conda dependency, either. This was just the first cause I had to look at either one.

**Comment by jakirkham** [comment]
I see. Sorry, I missed that.

**Comment by jakirkham** [comment]
I've pushed `conda-env` back into PR ( https://github.com/conda-forge/staged-recipes/pull/656 ) so this is less controversial and as it seems those may be circular dependencies that need more thought.

Also, I have updated the maintainers list here. @pelson [asked]( https://github.com/conda-forge/staged-recipes/pull/656#issuecomment-221485958 ) to be added so is included. I've also added @mcg1969 and @kalefranz here too. It would be good if you guys could confirm this is ok.

Unless there is anything wrong with these dependencies as is, this should be an easy merge and will get us a little closer to our end goal here.

**Comment by mcg1969** [comment]
I see no obvious issues; conda has pretty light dependencies for obvious reasons.

**Comment by jakirkham** [comment]
Sending these out into the wild. 🐅 Thanks everyone.

**Pull request merged**
