### PR TITLE
Add hiredis

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by synapticarbors** [comment]
A feedstock for this project already exists:

https://github.com/conda-forge/hiredis-feedstock

**Comment by sannykr** [comment]
@synapticarbors : Thanks for letting me know. I looked at the link and found that it built for only python 27 on linux. Will it build for other OS and versions of python if you retrigger the build?

**Comment by synapticarbors** [comment]
There should be other versions beyond linux py27. See:

https://anaconda.org/conda-forge/hiredis/files

Also, I just put in a PR to re-render the feedstock:

https://github.com/conda-forge/hiredis-feedstock/pull/6

**Comment by sannykr** [comment]
@synapticarbors : Thanks. I was looking at wrong channel. But if it supports python 36, that would be great.

**Pull request closed without merging**
