### PR TITLE
WIP: Add nss and nspr

### PR DESCRIPTION
**Pull request by jakirkham**
Adds recipes to build `nss` and `nspr`. The are used by Mozilla's Firefox to handle various security protocols. Some of them are not supported by OpenSSL. It comes with some useful tools to work with certs of various kinds too.

This is still WIP and I'm not sure if I want to carry this forward at this point. Though I'm putting this out there in case someone else feels compelled to carry it forward.

### CODE REVIEW

**Comment by jakirkham** [comment]
Just bringing this to your attention, @msarahan.

**Comment by msarahan** [comment]
Got it, thanks.  I haven't come across these before.  Good to be aware of them.

**Comment by jakirkham** [comment]
`nspr` is more of a base level runtime library. `nss` is the security side of things. `nss` could be used to generate certs as well.

**Comment by jakirkham** [comment]
For some reason, on Mac this will pick up `g++` during some testing with gtest. I think it is hard-coded in there somewhere. This is causing the build failure as we are using `clang++`. The simple solution would be just to use `g++`. However, we need C++0x for some parts of the build. So, `clang++` is the only choice. This may require a patch or two to overcome.

**Comment by jakirkham** [comment]
As mentioned above, not planning to carry these forward at this time. Merely providing what I was able to accomplish locally here so that people are free to carry them forward. Hence remove the `Awaiting author contribution` label as it doesn't seem appropriate in this instance.

**Comment by scopatz** [comment]
ping @jakirkham

**Comment by jakirkham** [comment]
No longer pursuing these. Have raised issue ( https://github.com/conda-forge/staged-recipes/issues/4100 ) to track adding them to conda-forge.

**Comment by jakirkham** [comment]
Have been subsequently added with PR ( https://github.com/conda-forge/staged-recipes/pull/5754 ) and PR ( https://github.com/conda-forge/staged-recipes/pull/5751 ).

**Pull request closed without merging**
