### PR TITLE
Clear broken packages from `master`

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/staged-recipes/issues/746

Sorry guys. I don't what is wrong with these, but we cannot have them clogging up `master` right now as we are trying to do some maintenance. Going to remove them. Please add new PRs with these packages so we can sort them out there. Sorry for the inconvenience everyone.

cc @pelson @ocefpaf @kmuehlbauer @183amir @mariusvniekerk

### CODE REVIEW

**Comment by ocefpaf** [comment]
I was working on fixing the issue :unamused: Oh well...

**Comment by 183amir** [comment]
what was the issue?

**Comment by jakirkham** [comment]
@pelson is trying to make some changes to the bot here. I would feel really bad if we have him workaround this issue too while he is trying to head out to vacation. Plus, appears there may be issues with `setuptools`. So, that will need to be packaged and shipped too. These will have to wait for a little bit.

**Comment by ocefpaf** [comment]
> @pelson is trying to make some changes to the bot here. I would feel really bad if we have him workaround this issue too while he is trying to head out for vacation.

I don't think that self-merging something like that is healthy for the community. I also believe that the issue was easily fixable, but no one can react to such a things at your time-table. Please, be more considered next time and allow us some time to react.

**Comment by jakirkham** [comment]
There are several and we will need to disentangle them. One is something funky with channels used by `conda`. Not sure what the cause is there.

Another is `setuptools` appears to be broken somehow. We may need to just package our own and get it out the door.

Not sure what other issues there are.

**Comment by jakirkham** [comment]
Normally I would agree with you @ocefpaf. Unfortunately, there are multiple people that were struggling because things were broken in staged-recipes. We have an obligation to try to keep system critical things functioning. Leaving things broken packages does not feel like a good course of action IMHO and does not hold up to this obligation.

Given they were not building properly in your PR either, I think it is ok for us to remove them and try fresh PRs to see if we can get them to build cleanly.

**Comment by ocefpaf** [comment]
> We have an obligation to try to keep system critical things functioning

I agree! I just disagree on how you are doing it. staged-recipes is an assembly line. You don't clear the clutter and let more stuff come in. You fix the assemble line.

People will understand if you ask to hold on while we fix the problem.

**Comment by jakirkham** [comment]
If it were just staged-recipes that was broken, I would probably have been more forgiving and let this run its course a bit longer. However, @pelson was trying to fix another issue here and he has a short time table. I wanted to give him time and a clear space to do so. If that were not the case, I would certainly be more patient.

> I agree! I just disagree on how you are doing it. staged-recipes is an assembly line. You don't clear the clutter and let more stuff come in. You fix the assemble line.

I'm sorry you feel that way @ocefpaf and I'm sorry I have disturbed your work. However, I had no plan of merging anything new. I definitely think we should hold off on merging for a bit. Many of these issues can be explored outside of `master` and even outside of `staged-recipes`.

Many of us have cleared staged-recipes in a real hurry because of a broken package before. The fact that this is becoming a controversial issue is new to me. In any event, I will try to be more accommodating to this mentality in the future. We should try to find a balance between fixing things and minimizing disruption for others.

> I also believe that the issue was easily fixable, but no one can react to such a things at your time-table.

Your PR ( https://github.com/conda-forge/staged-recipes/pull/745 ) demonstrated that `setuptools` was not working as is evidenced by this [line]( https://travis-ci.org/conda-forge/staged-recipes/jobs/136471787#L717 ). See this [SO answer]( http://stackoverflow.com/questions/22148144/python-importerror-no-module-named-pkg-resources ) that explains the link to `setuptool`. This was going to continue to cause problems until we had a fixed copy of `setuptools`. It is unclear to me that this didn't affect other things.

There were other concerning issues like packages missing from `win-32` that should not be an issue. Both of these can be worked on out of band and do not require messing up `master` for everyone.

<br>
This all being said, I have not generally been so pushy with staged-recipes. The situation here was unique. In general, I'm happy to let people play with fixes that must be done in `master`.

**Comment by kmuehlbauer** [comment]
Is the source of this behaviour located and sorted out now? Why was/is travis looking/searching in win-32 channels? What caused this? This remaining unknown isn't good at all.

I can resend the PR from a fresh master-copy anytime.

**Comment by 183amir** [comment]
Sorry guys for the issue in the master. Everything was green on my pull request before I merged it but it broke master once it was merged.

**Comment by jakirkham** [comment]
Go ahead and resend the PRs, @kmuehlbauer @183amir. We might hold off on merging for a bit though. This will at least give us somewhere to sort this out a bit more.

**Comment by jakirkham** [comment]
No worries, @183amir. The issue only cropped up earlier today. Other merges seemed ok before that.

**Comment by ocefpaf** [comment]
> Many of us have cleared staged-recipes 

Not true. Check the history and you'll see that you did most of such actions. Even under protest of other core devs.

>  I'm sorry I have disturbed your work.

Here is where you are wrong. You did not disturb my work. Very much like the jpeg downgrade this actually helps **me**. However, conda-forge is not about **me**, it is about the community. Please be more patient next time and wait for some responses.

Again, I do not think the world will end if `stage-recipes` remains broken for a few hours.

**Comment by ocefpaf** [comment]
> Your PR ( #745 ) demonstrated that setuptools was not working

I know. That was what I was fixing but never got he chance :unamused: 
I was downgrading `setuptools` to get that, and all the remaining feedstoks, out. Anyways, that does not matter now :unamused:

**Comment by jakirkham** [comment]
>> Many of us have cleared staged-recipes

> Not true. Check the history and you'll see that you did most of such actions. Even under protest of other core devs.

Not really interested in pointing fingers or keeping count. To be honest, keeping things running should not be considered a problem or a subject worthy of protest. I really don't know how we got here, but am deeply concerned by it and feel it is the real problem that needs discussion.

> Again, I do not think the world will end if stage-recipes remains broken for a few hours.

This is a proposal that is very frustrating for our users. I think we need to understand the difference between mission critical problems that need to be fixed ASAP and proposals up for discussion. Leaving key infrastructure broken during peak usage times for extended stretches is simply not ok. Especially when the fix is clear.

Even if those of us doing merges here decide we are ok with this, other users that have no idea what is going on begin to panic. This is bad for the community as it suggests a lack of concern for keeping things working here and a lack of concern for how it affects others. Also, it makes it hard for us to focus on the problem at hand.

>> Your PR ( #745 ) demonstrated that setuptools was not working

> I know. That was what I was fixing but never got he chance :unamused: 
> Anyways... That does not matter now :unamused: 

It should not be up to you to fix everyone else's issues, @ocefpaf. I say this with the deepest respect for what you do here. Backing out clearly broken recipes and pinging people to fix them should save you lots of unnecessary stress.

It should also reduce the pressure on anyone who's work broke `master`. Leaving it in `master` and letting them bear the heat of the community's frustration is not good for anyone. Taking it out of band so that they can work on it some more without added stress will make it easier for them to focus on solving the problem at hand.

> Please be more patient next time and wait for some responses.

As stated before.

In any event, I will try to be more accommodating to this mentality in the future. We should try to find a balance between fixing things and minimizing disruption for others.

**Comment by ocefpaf** [comment]
> Not really interested in pointing fingers or keeping count. 

And yet you are...

All I am asking is patience, avoid self merges, avoid hasty actions. In other words: basic community practices.

> other users that have no idea what is going on begin to panic. 

Really!!??? Nothing here was urgent! Everybody reacted to a problem normally and asked what is going on. That is not an endorsement to  a mission that you should fix ASAP. BTW no PR got merge after that. Again, the world will not end if staged-recipes waits a few hours.

Also, your `setuptools` fix turned out to be a red-herring. The @183amir should the `bob.<packages>` issue and the real issue remains to be resolved: https://github.com/conda-forge/staged-recipes/pull/750/files#r66495313

Please. I am begging you. Be patient. Consult with the other members of the community. Do not act like a lone wolf who is out to save to world.

When I embarked in conda-forge I brought some GIS and Met-Ocean communities here. In the past weeks I presented to them the work we do here and I had a hard time to convince them that our governance model is safe. That the community voice will be heard. That no once will act by themselves. You **are** making my job very hard. It is not the first time you merge something unnecessary in a matter of minutes.

I won't respond anymore as you are clearly failing to step into others shoes and you are worried only about justifying your acts. However, again, I beg of you: be patient and do not act like that or I will loose my community. They won't adopt conda-forge if such things keep happening.

**Comment by pelson** [comment]
For me this thread is more troubling than the problem itself. I agree with the sentiments of both of you (we should try to fix things when they come up, but some downtime is acceptable provided we are clear that we are doing something about it) but most of all, we have to come out of the adversity as a stronger community.

It is completely reasonable to request that the manner in which a problem is resolved be consistent and (ideally) pre-agreed, however there are comments above which are unhealthily close to attacks on personality which will impact future interactions and inevitably leave the conda-forge community in a weaker place. This is all the more disheartening as you have both played pivotal roles in making the conda-forge community great, and it is not inaccurate to say that without your contributions conda-forge would be infinitely poorer.

I take responsibility for staged-recipes being somewhat flaky at the moment, particularly with regards to the rate limiting. I simply haven't had the cycles to do an awful lot about the problem, but I do expect to start looking at the wider infrastructure requirements of conda-forge when I get back from vacation. I hope that this thread is just an overflow of staged-recipes frustration from both of you.

I'm glad we have the "Basic community practices when PR-ing to staged-recipes" item on the agenda. I suspect speaking face-to-face (even via VOIP) will be less divisive than GH comments and look forward to a healthy debate at which I'm sure we will converge on a healthy solution.

**Pull request merged**
