### PR TITLE
Add linux-pam

### PR DESCRIPTION
**Pull request by sshockwave**
Related issues / PRs:

- https://github.com/conda-forge/cdt-builds/pull/55
- https://github.com/conda-forge/staged-recipes/pull/16911
- https://github.com/conda-forge/staged-recipes/issues/13424

Some optional libraries are not in this PR. They are planned to be enabled after they are added to conda-forge:

- [libprelude](https://www.prelude-siem.org/projects/libprelude/repository)
- [libeconf](https://github.com/openSUSE/libeconf)
- [libtirpc](https://sourceforge.net/projects/libtirpc/)
- [libaudit](https://github.com/linux-audit/audit-userspace) https://github.com/conda-forge/staged-recipes/pull/21957
- `libdb` conda-forge has this, but it is not compiled with `ndbm`-compatible API.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sshockwave** [comment]
@conda-forge/help-c-cpp ready for review!

@h-vetinari Would you mind me adding your name to the maintainers' list? The work is based on your branch.

**Comment by sshockwave** [comment]
@conda-forge-admin please restart ci

**Comment by h-vetinari** [comment]
Thanks for picking this up again!

> @h-vetinari Would you mind me adding your name to the maintainers' list? The work is based on your branch.

You can add me to maintainers, though I continue to think that despite the strong trend against CDTs, this is a case where we should really stay with the distro packages, because it's very security sensitive and we cannot reasonably test all parts of the package.

**Comment by carterbox** [comment]
Why would shipping this library be any different than shipping opensll or openssh?

**Comment by h-vetinari** [comment]
> Why would shipping this library be any different than shipping openssl or openssh?

Because it's wired more deeply into the OS layer than either of those. I don't remember the details, but there are some tests that we can't run because they're doing destructive things like resetting OS-level settings. I wouldn't know how to ensure that we're not exposing untested/unavailable functionality.

I remember that @chenghlee had similar reservations at the time.

**Comment by carterbox** [comment]
@sshockwave, I talked with some of the core team members at the community meeting today. It seems that a majority would prefer that this package is shipped as a CDT.

As a side note, there were many questions about what downstream conda packages would need to link to libpam (i.e. what is the utility of this package for conda) and even whether this non-CDT libpam package would function on non-selinux distros. Please be prepared to answer these types of questions, so the core team can help package this library appropriately.

**Comment by h-vetinari** [comment]
There's an outstanding PR for the CDT already: https://github.com/conda-forge/cdt-builds/pull/55

It stalled at the time over indecision whether it should be a CDT or not, so I'm glad to hear that there's now direction for this!

The main reason we started down this road was to package rstudio-server, I'm not currently aware of other packages that require this.

**Comment by sshockwave** [comment]
@h-vetinari @carterbox Good to hear your feedbacks! The CDT PR had gone stale so this PR tried to provide an alternative.

**Pull request closed without merging**
