### PR TITLE
Create meta.yaml

### PR DESCRIPTION
**Pull request by bwinkel**
Added a cygrid recipe for use with conda-forge.

### CODE REVIEW

**Comment by bwinkel** [comment]
Note that using
```
script: "{{ PYTHON }} -m pip install .
```
is unfortunately not possible, as cygrid uses the [astropy package template](https://github.com/astropy/package-template). See also discussion in: https://github.com/conda-forge/staged-recipes/pull/7102

**Comment by bwinkel** [comment]
> You need to use llvm-openmp for the new compilers

Thanks a lot @beckermr for you help! The MacOS build complains about `omp.h` not found. Do you happen to know if this can be solved by adding another package to the `meta.yaml` - or do I need to change my package's setup? (I already had a tough time to get it work with clang and openmp under MacOS.)

**Comment by beckermr** [comment]
Yep. Add llvm-openmp to the build section too

**Comment by bwinkel** [comment]
Awesome, 

> Yep. Add llvm-openmp to the build section too

Awesome, that did it. Thanks so much for your kind support, @beckermr.

**Comment by bwinkel** [comment]
Sorry, I accidentally closed the PR.

**Comment by DanielLenz** [comment]
Thanks for the help, looking forward to having this on conda-forge!

>  @DanielLenz should comment here that they are ok being a maintainer

I am!

**Comment by beckermr** [comment]
Thanks again!

**Pull request merged**
