### PR TITLE
Add highspy package

### PR DESCRIPTION
**Pull request by adament**
conda-forge already carries a highs package for the C++ library and executable. This is a package for the python library with the same name as the pypi package. Even though the C++ package builds a shared library on non-windows platforms, it seems that upstream only supports linking the python module statically against the library code. So without major surgery to the upstream build system, I think this is the best I can do.

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by adament** [comment]
@conda-forge/help-python I think this is ready for review.

@julian-belina do you have any comments?

**Comment by julian-belina** [comment]
@adament this looks promising. Does this recipe also compile the original code? The only installation command I can find installs the python package of the library. Unfortunately, I was not able recreate the highs pip package on conda-forge

**Comment by adament** [comment]
It compiles the C++ code of the original library as object files and links them into the finale python module, which is equivalent to a linking statically against the original library. This replicates to the best of my understanding how the pip packages are built. All of this under the assumption that I understand the cmake code correctly.

So the highs and highspy packages should now be separate and independent, with the highspy package being equivalent to the pip package and the highs package with the C++ library, headers and standalone executable.

**Comment by julian-belina** [comment]
I have another library that depends on highs and will test if it works as expected. Thank you for creating the recipe

**Pull request merged**
