### PR TITLE
add bigquery-magics package

### PR DESCRIPTION
**Pull request by tswast**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [N/A] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ACK] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by tswast** [comment]
@conda-forge/help-python, ready for review!

**Comment by tswast** [comment]
Not sure what's going on with the linter. This PR doesn't touch the example folder.

**Comment by itsxdamdam** [comment]
Hi @tswast I am having the same errors too 
Please share how you solved it

**Comment by ocefpaf** [comment]
> Edit: Moved to `recipies/bigquery-magics`. Not sure why `grayskull` didn't put it there.

Grayskull creates a directory fo your recipe with the recipe's name. It doesn't know about the system where you are.

With that said, the linter message is misleading b/c it thinks you are in the recipe directory and can't see the examples folder. @BastianZim I believe you wrote that lint, right? If not, sorry for the ping.

**Comment by itsxdamdam** [comment]
thanks @ocefpaf I figured that as well.

However, I still have some errors on check. I'd appreciate it if you can take a look  #26787

**Comment by BastianZim** [comment]
Hi @ocefpaf, yes when it was a GitHub action here but it seems to have been moved to the linter a while ago.
I'll have a look, but am limited by train internet currently... Might take a sec.

**Comment by BastianZim** [comment]
Seems like we have an overlap because this is the one I wrote: https://github.com/conda-forge/staged-recipes/blob/main/.github/workflows/do_not_edit_example.yml

But this one exists as well: https://github.com/conda-forge/conda-smithy/blob/main/conda_smithy/lint_recipe.py#L1215

Where do we prefer it?

**Pull request merged**
