### PR TITLE
added librosa recipe

### PR DESCRIPTION
**Pull request by bmcfee**
This will be blocked until #1057 is merged.

### CODE REVIEW

**Comment by jakirkham** [comment]
So, that is merged, but it might be a minute before it generates packages. Feel free to ping me to restart CIs once they are up.

**Comment by bmcfee** [comment]
Thanks! Pinging as requested.

**Comment by bmcfee** [comment]
The circle build failed here because of upstream problems with the circle build for `audioread`.  This should all be resolved now, so one more restart ought to do it.

**Comment by mwcraig** [comment]
Restarting...

**Comment by jakirkham** [comment]
So, I saw a comment about entry points. Could we please test the entry points using the `command` section? Getting the version or help should be sufficient.

**Comment by bmcfee** [comment]
> So, I saw a comment about entry points. Could we please test the entry points using the commands section? Getting the version or help should be sufficient.

Do you mean I should fix that here in this PR?  Or is this a general comment for the example recipe?

**Comment by jakirkham** [comment]
I'm referring to `setuptools` showing up in `requirements/run`. Normally this is only needed if one has entry points. So, we should try to test them if there are any. If not, we should try to figure out why `setuptools` is needed. AFAICT it is not imported anywhere other than `setup.py` by `librosa`.

**Comment by bmcfee** [comment]
Librosa uses pkg_resources to access the included example file.

I suppose we could add a test for `librosa.util.example_audio_file()`, but that's already included in the package's own unit tests, so I didn't bother here.

**Comment by jakirkham** [comment]
I see. Thanks for clarifying.

**Comment by jakirkham** [comment]
LGTM

**Comment by jakirkham** [comment]
Thanks @bmcfee.

**Pull request merged**
