### PR TITLE
Add pytest-html recipe

### PR DESCRIPTION
**Pull request by birdsarah**
This isn't going to pass until #3028 is merged and available

### CODE REVIEW

**Comment by birdsarah** [comment]
ping @davehunt - you good with being a maintainer?

**Comment by davehunt** [comment]
👍

**Comment by msarahan** [comment]
#3028 is merged.  When it is available, close and re-open this PR to run the CI again.  Please ping me when it passes.

**Comment by birdsarah** [comment]
ping @msarahan - it passed - woot woot!

**Pull request merged**
