### PR TITLE
add r-bit64 r-brglm r-catools r-coda r-config r-foreach r-gdata

### PR DESCRIPTION
**Pull request by bgruening**
r-bit64
r-brglm
r-catools
r-coda
r-config
r-foreach
r-gdata

xref: https://github.com/conda-forge/staged-recipes/issues/2009

### CODE REVIEW

**Comment by isuruf** [comment]
`r-gtools-feedstock` had an appveyor failure due to network issues. `r-gtools` is a dependency of `r-gdata`. When feedstocks are created, please check that the builds succeed and restart them if they fail due to network errors.

**Comment by bgruening** [comment]
@isuruf can you please also look at `r-openssl-feedstock` this also seems to have an error.

**Comment by johanneskoester** [comment]
r-foreach should be removed here. I needed it for PR 2890 (a package in their had changed dependencies since last version).

**Comment by bgruening** [comment]
@johanneskoester removed!

**Comment by isuruf** [comment]
`r-coda` failed. You'll have to readd the recipe.

**Comment by bgruening** [comment]
@isuruf thanks, see here: https://github.com/conda-forge/staged-recipes/pull/2899

**Pull request merged**
