### PR TITLE
Stop building PRs on travis and circleci

### PR DESCRIPTION
**Pull request by isuruf**
cc @conda-forge/staged-recipes

### CODE REVIEW

**Comment by scopatz** [comment]
Is there any reason to keep building on appveyor?

**Comment by isuruf** [comment]
@scopatz, yes. there are issues with cmake on windows with azure. (I've been waiting for more than 2 weeks for reviews, but no luck)

**Comment by ocefpaf** [comment]
> @scopatz, yes. there are issues with cmake on windows with azure. (I've been waiting for more than 2 weeks for reviews, but no luck)

Can you point me to where you need a review?

PS: as far as I remember if we move to `vc 14.1` we should be OK with Azure, no?

**Comment by isuruf** [comment]
https://github.com/AnacondaRecipes/aggregate/pull/138

**Comment by scopatz** [comment]
Sorry, yeah, google killing inbox destroyed my workflow.

**Pull request merged**
