### PR TITLE
add plotly-orca

### PR DESCRIPTION
**Pull request by rluria14**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by rluria14** [comment]
@oblute @ndratpac agree to be maintainers?

**Comment by rluria14** [comment]
@conda-forge/help-nodejs any ideas on how to get to build on windows?

**Comment by rluria14** [comment]
@dhirschfeld I see you came across the same issue here on [typescript](https://github.com/conda-forge/typescript-feedstock/pull/34). Did you ever figure out how to build on windows?

**Comment by rluria14** [comment]
@conda-forge/help-nodejs @conda-forge/staged-recipes this recipe is ready for review

**Comment by dhirschfeld** [comment]
I never did get to the bottom of the typescript issue.

I think it might require manually putting a custom `tsc.cmd in `%BUILD_PREFIX%/Scripts`.

**Comment by rluria14** [comment]
> I never did get to the bottom of the typescript issue.
> 
> I think it might require manually putting a custom `tsc.cmd` in `%BUILD_PREFIX%/Scripts`.

Was able to build via:

`  - npm pack  # [unix]
    - npm install -g {{ name }}-{{ version }}.tgz  # [unix]
    - call npm pack  # [win]
    - call npm install -g {{ name }}-{{ version }}.tgz  # [win]`

**Comment by rluria14** [comment]
@conda-forge/staged-recipes this recipe is ready for review

**Pull request merged**
