### PR TITLE
Adding esi-utils-geo package, from a grayskull generated recipe

### PR DESCRIPTION
**Pull request by mhearne-usgs**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mhearne-usgs** [comment]
@ocefpaf I think this is just waiting on a merge from a maintainer, correct?

**Comment by ocefpaf** [comment]
> @ocefpaf I think this is just waiting on a merge from a maintainer, correct?

You need to ask for a review b/c we don't monitor the PRs anymore (too many and most of them not ready).

Folks need to ping the staged-recipes reviewer team or use the bot's command in https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-ping-team

**Comment by mhearne-usgs** [comment]
@ocefpaf Great, thank you! Perhaps this documentation could be updated? Currently, it indicates that users should just wait for someone to pick up the PR: "Once you finished your PR, all you have to do is wait for feedback from our review team." https://conda-forge.org/docs/maintainer/adding_pkgs.html#feedback-and-revision

**Comment by ocefpaf** [comment]
Yep. We need to update that!

**Pull request merged**
