### PR TITLE
tidy_headers

### PR DESCRIPTION
**Pull request by untzag**

### CODE REVIEW

**Comment by untzag** [comment]
oops, I think I didn't want to close 😐

**Comment by bgruening** [comment]
General Q @untzag ... have you considered to create a noarch package out of it?

**Comment by untzag** [comment]
@bgruening it is noarch, as far as I know

**Comment by synapticarbors** [comment]
Merged this. The one thing that surprised me was that it passed without `pytest-runner` as a `build` requirement since it's listed in the `setup_requires` in the `setup.py`.

**Comment by untzag** [comment]
@synapticarbors I think that's because I'm not having conda run my tests, only test for successful import

thanks for the merge 👍

**Pull request merged**
