### PR TITLE
Adding nzpy

### PR DESCRIPTION
**Pull request by mcg1969**
The following is a conda recipe for nzpy, a DB-API driver for the IBM Netezza database. Unfortunately the GitHub repository does not use tags, so we must rely on the PyPi source.

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mcg1969** [comment]
@conda-forge/help-python this should be ready to go!

@aniket-s-kulkarni  @abhishekjog this repository enables the automatic building of a conda package for nzpy, to be added to the conda-forge package ecosystem. If you would like, we can add you as a "maintainer" of this repository, which would allow you to, for instance, approve updated builds when you push a new version of the PyPi package. You are in no way obligated to say "yes"! But if you do, I will add you to the maintainer list. Here is more information: https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role

**Comment by mcg1969** [comment]
@sagar-sandbhor @shabbir10july pinging you as well, to see if you are interested in being listed as an official maintainer of this conda packaging feedstock for the nzpy package. More information here: https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role

**Comment by mcg1969** [comment]
@synapticarbors thank you for the quick merge—and yet it looks like the GitHub action that creates the feedstock silently failed, as the nzpy-feedstock repo is now empty... that seems odd to me.
https://github.com/conda-forge/staged-recipes/runs/4201714606

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes -- Does anyone know the procedure for when I feedstock is created but not populated? It looks like the error was:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cloud.drone.io/api/repos/conda-forge/nzpy-feedstock
```

**Comment by mcg1969** [comment]
The fact that the job completes "successfully" despite a traceback is concerning too; I assume the shell is inadvertently swallowing an error.

**Comment by mcg1969** [comment]
But it looks all good now. Thanks @synapticarbors

**Pull request merged**
