### PR TITLE
ENH bump staged recipes team on PRs

### PR DESCRIPTION
**Pull request by beckermr**
Hi @conda-forge/staged-recipes!

What do we think of this?

It would bump all of us when a new PR is made. Too much noise? Just right? It is better than watching the repo I think.

### CODE REVIEW

**Comment by xhochy** [comment]
-1, I would consider this too much noise. There often a lot attempts happening to build a recipe against CI that would spam our inbox before there is actually "review work". I think it is better to notify staged-recipes once the recipe has come to a stable point.

**Comment by beckermr** [comment]
It only sends a note once per PR, but yeah for sure I understand your concerns @xhochy !

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests. For more information about draft pull requests, see "About pull requests."

**Comment by xhochy** [comment]
Normally, once the team was mentioned, you get a mail/notification per comment or commit on the PR. Thus we would also get mails for all the test-against-CI commits.

**Comment by beckermr** [comment]
Ohhhh really? I have not experience that before but alright. Then this is truly a horrible idea! Closing!

**Pull request closed without merging**
