### PR TITLE
Add mnelab

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

PR to include license file upstream: https://github.com/cbrnr/mnelab/pull/30

### CODE REVIEW

**Comment by hoechenberger** [comment]
@conda-forge/staged-recipes Not sure why these two dependencies cannot be found, maybe I'll just have to wait a little longer for the mirrors to sync (the two packages that cannot be resolved were just added to `conda-forge` a short while ago today)

**Comment by chrisburr** [comment]
It takes a little while, generally it's within an hour of the files appearing here:
https://anaconda.org/conda-forge/python-picard/files
(New packages seem to take a little longer but it might be superstition)

You can check if it is available yet using:
```bash
$ conda search python-picard
Loading channels: done
No match found for: python-picard. Search: *python-picard*
```

If it hasn't appeared within a few hours the best solution is ask on [Gitter](https://gitter.im/conda-forge/conda-forge.github.io) so the Anaconda Inc. people are aware.

**Comment by hoechenberger** [comment]
Thanks!

**Comment by chrisburr** [comment]
I restarted the builds now the CDN is up to date.

Spoiler: The `setup.py` script isn't compatible Python 2.

**Comment by hoechenberger** [comment]
> Spoiler: The `setup.py` script isn't compatible with Python 2.

Haha, I knew it :D Will let the upstream authors know.

**Comment by chrisburr** [comment]
As I still had this open, you need to make a file called `yum_requirements.txt` in the recipe directory containing the packages listed here:
https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#core-dependency-tree-packages-cdt

(There's no need for `requirements` listed there unless you're compiling.)

**Comment by hoechenberger** [comment]
Yep, just realized that. Will do later tonight. Thanks!

**Comment by hoechenberger** [comment]
@chrisburr All set now. :)

**Pull request merged**
