### PR TITLE
PYPY a new recipe

### PR DESCRIPTION
**Pull request by mictadlo**

### CODE REVIEW

**Comment by xoviat** [comment]
PyPy may pose problems because of its exceedingly-long build time.

**Comment by mictadlo** [comment]
Is there any other way to get PyPy into conda-forge?

**Comment by xoviat** [comment]
I'd just make the URL on of the nightly archives here: http://buildbot.pypy.org/nightly/trunk/

The build script can consist of copying the files to the correct locations.

**Comment by mictadlo** [comment]
Could you please provide an example how to do it?

**Comment by dougalsutherland** [comment]
https://github.com/conda-forge/tensorflow-feedstock does that. It's really not ideal, though; in fact we can't even load the official tensorflow build on our CI Docker image. :|

Is it definitely going to be a problem, though? Looks like current build script errored for actual-failure reasons.

**Comment by xoviat** [comment]
> Is it definitely going to be a problem, though?

Half the PyPy project is a compiler implemented in Python -- you can see why this would take so long to build.

**Comment by mictadlo** [comment]
There is a stable binary build for Linux (`https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.10.0-linux64.tar.bz2`) and it has the following folder structure:
```
$ ls
LICENSE		
bin
include		
lib-python	
lib_pypy	
site-packages
```
How a `build.sh` would like to copy the package folder to right places?

Thank you in advance.

Michal

**Pull request closed without merging**
