### PR TITLE
Advise making a new branch

### PR DESCRIPTION
**Pull request by peterjc**
This is a tiny tweak to the instructions which currently perhaps assume to much familiarity with git and GitHub?

### CODE REVIEW

**Comment by CurtLH** [comment]
I'm not sure that I follow your recommendation on advising contributors to create a branch.  When I fork the staged-recipes repo, I add my recipe to the master branch of my forked copy of the repo.  There is no need to create a separate branch on your forked repo unless maybe you're working with others to develop the recipe.

**Comment by peterjc** [comment]
Sure for their first pull request they can just use the master branch, but hopefully new contributors will in future make additional new recipes - and this gets messy if their local master branch has diverged.

**Comment by CurtLH** [comment]
Good point @peterjc.  As a new contributor myself, I didn't even think about creating a separate branch for each recipe. After my first recipe was merged, I deleted my fork and re-forked staged-recipes for my next recipe.  I can now see how including the branch part would help people such as myself.

**Comment by peterjc** [comment]
Yes, that's exactly what I've seen happen in other projects, and hope to pre-empt.

If you know git, you can delete the diverged ``master`` branch and then checkout the upstream repository's ``master`` instead, but deleting the entire repository and re-forking on GitHub is simpler for beginners (and far easier to explain).

**Comment by CurtLH** [comment]
Thanks for the explanation!

**Comment by peterjc** [comment]
I think this proposal still has merit - would anyone like to give a second opinion?

**Pull request closed without merging**
