### PR TITLE
Add ecl

### PR DESCRIPTION
**Pull request by isuruf**
@embray, would you like to help maintain this conda recipe? I only kept one of the patches from sage as the others seem to be fixed in 16.1.3. Correct me if I'm wrong.

### CODE REVIEW

**Comment by isuruf** [comment]
Anybody know the reason for the failure in https://api.travis-ci.org/jobs/200268608/log.txt?deansi=true ?

**Comment by isuruf** [comment]
@ocefpaf, ready for review. Note that I cancelled appveyor because windows is skipped.

**Comment by embray** [comment]
@isuruf Sorry, I missed this earlier.  Is there a good way of listing myself as a willing co-maintainer?  Having gained some experience now with ecl I can certainly help.  Thanks for doing this!

**Comment by isuruf** [comment]
@embray, thanks for volunteering. Can you send a PR editing this and add your github handle, https://github.com/conda-forge/ecl-feedstock/blob/master/recipe/meta.yaml#L52 ?
There's a nightly script that will give you the permissions, once the PR is merged.

**Pull request merged**
