### PR TITLE
Add frosted

### PR DESCRIPTION
**Pull request by jakirkham**
Generated with `conda skeleton pypi` and cleaned up after. This still needs a few dependencies. So is still WIP. Just placing it here so I don't forget it.

### CODE REVIEW

**Comment by ericdill** [comment]
Woah, why is appveyor trying to build for python 1.0??

**Comment by jakirkham** [comment]
> Woah, why is appveyor trying to build for python 1.0??

Not sure. Guessing it is some kind of fluke. Made some small changes and rebased. Let's see if it works.

**Comment by jakirkham** [comment]
Seems to work now. 😄

**Comment by msarahan** [comment]
Thanks @jakirkham

**Pull request merged**
