### PR TITLE
Added R package rje

### PR DESCRIPTION
**Pull request by jenzopr**
Dear all,

I added the R package rje via `conda skeleton cran` and `bioconda-utils clean-cran-skeleton`.
I also added myself to the list of maintainers.

Best,
Jens

### CODE REVIEW

**Comment by jenzopr** [comment]
Just for curiosity: I get some warnings at the end of the build protocol:

```WARNING (r-rje,lib/R/library/rje/libs/rje.so): Needed DSO lib/libintl.8.dylib found in ['gettext']
WARNING (r-rje,lib/R/library/rje/libs/rje.so): .. but ['gettext'] not in reqs/run, i.e. it is overlinked (likely) or a missing dependency (less likely)
   INFO (r-rje,lib/R/library/rje/libs/rje.so): Needed DSO lib/R/lib/libR.dylib found in conda-forge::r-base-3.4.1-4
   INFO (r-rje,lib/R/library/rje/libs/rje.so): Needed DSO /usr/lib/libSystem.B.dylib found in the whitelist
WARNING (r-rje,lib/R/library/rje/libs/rje.so): Needed DSO lib/libgfortran.3.dylib found in ['gcc', 'libgfortran']
WARNING (r-rje,lib/R/library/rje/libs/rje.so): .. but ['gcc', 'libgfortran'] not in reqs/run, i.e. it is overlinked (likely) or a missing dependency (less likely)
   INFO (r-rje,lib/R/library/rje/libs/rje.so): Needed DSO /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation found in the whitelist```

Can someone explain what this means?

The error why the build fails comes a bit later:
```
ValueError: License file given in about/license_file does not exist in source root dir or in recipe root dir (with meta.yaml)
```
Any ideas?
Best and thanks,
Jens

**Comment by jenzopr** [comment]
Help appreciated! 🏳️  @conda-forge/r

**Comment by bgruening** [comment]
Please use the latest version of https://github.com/bgruening/conda_r_skeleton_helper. This needs to be adopted to conda-build3.

**Comment by jenzopr** [comment]
Magic, @bgruening ! Thanks a lot 👍

**Comment by bgruening** [comment]
Your welcome!

**Pull request merged**
