### PR TITLE
add Polyglot

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by FernandezMathieu** [comment]
@dopplershift Hello, can you merge ?

**Comment by FernandezMathieu** [comment]
@conda-forge-linter restart ci

**Comment by dopplershift** [comment]
The build output shows: 

> ModuleNotFoundError: No module named 'six'

I'm not sure how the dependency list in this recipe was generated, but it looks like you're missing everything listed [upstream](https://github.com/aboSamoor/polyglot/blob/master/requirements.txt).

**Comment by dopplershift** [comment]
Those [dependencies](https://github.com/aboSamoor/polyglot/blob/master/requirements.txt) needed to be added under the `run` section, not `test`.

**Comment by dopplershift** [comment]
> conda.exceptions.ResolvePackageNotFound: 
>  - pycld2[version='>=0.3']

Looks like you'll need to submit a recipe for `pycld2`.

**Pull request closed without merging**
