### PR TITLE
Add X11 package xorg-libxcvt recipe

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please ping conda-forge/help-c-cpp, ready for review!

**Comment by ehfd** [comment]
Details: this contains libxcvt and a cvt executable, which is bundled within the repository.

Meson + Ninja was combined with MSYS2 (VC had issues) for Windows.

**Comment by ehfd** [comment]
@pkgw I've added you to this recipe. Please comment to confirm.

**Review by hmaarrfk — APPROVED** [review]
I think this looks good. I'm just behind on the "best practices for windows" if somebody else can chime in within 1 week that would be nice. 

Otherwise i can merge.

**Review by baszalmstra — APPROVED** [review]

**Comment by ehfd** [comment]
Looks like it was approved.

**Comment by ehfd** [comment]
@hmaarrfk I think this is everything I can optimize for "best practice".

`MESON_ARGS` was the last thing but is redundant to the current configuration and actually doesn't play that well.

**Comment by hmaarrfk** [comment]
MESON_ARGS should be preferred as these things typically help with cross compilation and other related tools.

**Comment by hmaarrfk** [comment]
can you add it back so we can study the failure?

**Comment by ehfd** [comment]
@hmaarrfk The failure itself came from overlapping libdir, which can be easily fixed (https://github.com/conda-forge/staged-recipes/runs/25697760649), but the issue is that I'm not getting `%MESON_ARGS%` in Windows at all.

**Comment by hmaarrfk** [comment]
Let's add it back for Unix. 

Again. I'm no expert in windows. So maybe somebody else can chime in to get a better answer.

**Comment by ehfd** [comment]
@baszalmstra Any insight on the windows part of this discussion?

@hmaarrfk I changed it in Unix.

**Comment by hmaarrfk** [comment]
Can you please add the meson ARGS to windows so that we can inspect the logs? It's hard to always look at past logs on azure.

**Comment by hmaarrfk** [comment]
Sometimes I just give up on windows. So I felt uneasy about holding you to higher standards.

**Pull request merged**
