### PR TITLE
Add r-botor

### PR DESCRIPTION
**Pull request by oblute**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by oblute** [comment]
@rluria14 @benhuff agree to maintain?

**Comment by oblute** [comment]
@conda-forge/help-r @conda-forge/staged-recipes this is ready for review

**Comment by cbrueffer** [comment]
Hi @oblute, thanks for the PR! Since this package doesn't require compilation it should be marked  `noarch` (`noarch: generic` in the build section, see https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds). if you use an up to date version of `https://github.com/bgruening/conda_r_skeleton_helper` to generate recipes it should do the right thing automatically.

**Comment by oblute** [comment]
@cbrueffer thanks! I did use the updated version of conda skeleton cran, but I had made some alterations during this process to try to skip earlier r-base versions. just added it 👍

**Comment by cbrueffer** [comment]
Thanks for the change! Speaking of pinning, instead of explicitly pinning to r-base 3.6, could you add the following to the build section instead? `skip: True  # [r_base == "3.5.1"]` This way when we move to R 3.7 this package should rebuild correctly.

**Comment by oblute** [comment]
@cbrueffer awesome, thanks so much! i'm new to R recipes and couldn't find any documentation on the selectors. I was hoping some one would make a suggestion on it. wouldn't it no longer be noarch?

**Comment by cbrueffer** [comment]
Argh, yes, you're right. We've been having some trouble coming up with a way to reliably skip R 3.5, doing so in the requirements lead to some Windows build failures. In this case I think being future-proof is preferable, thanks for the change.

**Comment by oblute** [comment]
Yep - I saw that when i was trying to pin >3.5 on r-base, windows failed. thanks for your help!

**Pull request merged**
