### PR TITLE
Add lalapps

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR adds a recipe for `lalapps`. This includes a small patch to disable a flaky test, and a large one to update a bunch of python syntax for python3.

cc: @skymoo.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@skymoo, can you give this a once over?

**Comment by skymoo** [comment]
Looks good to me, is the `weave` test issue something we need to address upstream?

**Comment by duncanmmacleod** [comment]
Yes, I believe this was already discussed [here](https://git.ligo.org/lscsoft/lalsuite/issues/105).

**Comment by duncanmmacleod** [comment]
Yes, I presumed it was related to dependency versions, numpy or astropy, or similar, but the root cause of 'flaky test' suggests we just need to improve the test.

**Comment by duncanmmacleod** [comment]
@conda-forge/help-python-c, I think this recipe is ready for review, thanks.

**Comment by duncanmmacleod** [comment]
@conda-forge/staged-recipes, is someone available to review this? thanks.

**Comment by scopatz** [comment]
@skymoo - are you OK with being a maintainer here?

**Comment by skymoo** [comment]
I'm OK with being listed as maintainer.

**Comment by scopatz** [comment]
Thanks!

**Comment by duncanmmacleod** [comment]
thanks @scopatz!

**Pull request merged**
