### PR TITLE
Add metapackage recipe for CCTBX dependencies

### PR DESCRIPTION
**Pull request by bkpoon**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by bkpoon** [comment]
@conda-forge/staged-recipes , please review.

This is a metapackage for dependencies, so the recipe does not download any official sources, which is why I left the checkbox empty.

We're currently building our software using dependencies from conda-forge, and this is the first step towards moving CCTBX into conda-forge.

Thanks!

**Comment by isuruf** [comment]
Why do you need a metapackage for dependencies? Note that when you a meta package like this and if you use this to build another package, `run_exports` and other useful features will not be used by conda-build.

**Comment by bkpoon** [comment]
We were hoping to use this package for development so that developers could install one package in their environment for building sources locally, outside of conda-build.

Also for reproducibility, we want an easy way to construct an environment and store the versions and builds of each dependency from `conda list`. We'll be archiving the packages on a separate channel in case they get deleted in the main `conda-forge` channel.

So for the main CCTBX package, I would need to copy the requirements section to get the `pin_compatible` functionality? We're still deciding if we really need that for `numpy` or if we just need some recent version. The `outputs` section would not be needed for the main CCTBX package so we would not need the `pin_subpackage` functionality.

**Comment by isuruf** [comment]
> We were hoping to use this package for development so that developers could install one package in their environment for building sources locally, outside of conda-build.

You could do `conda install cctbx --only-deps` to install the dependencies.

> So for the main CCTBX package, I would need to copy the requirements section to get the pin_compatible functionality? 

Not only that, you need to copy it for pinning of other build time deps that you link to. Besides `pin_compatible` doesn't make sense without the same dep appearing in `host`.

**Comment by bkpoon** [comment]
Oh I see, I'll close this and keep all the dependencies in the main CCTBX package recipe. We're still learning how to use `conda`, so thanks for the suggestions!

**Comment by bkpoon** [comment]
@isuruf Hi again,

Thinking about dependencies some more, we have developers that work on other software, let's say "Program A", that depend on CCTBX and will have additional dependencies. If they build "Program A"  as a conda package, they would add CCTBX as a requirement and things should work fine.

But if they want to have a development build with just the dependencies for CCTBX and "Program A", but not CCTBX, would that be possible with the `--only-deps` flag? I read through the discussion at https://github.com/conda/conda/issues/1543 for the `--no-deps` and `--only-deps` flags and it's not clear if that's possible. We would like to be able to build the sources of both CCTBX and "Program A."

I tried to test this with `conda install --only-deps matplotlib-base numpy`, and `numpy` is installed because it is a dependency for `matplotlib-base`. Is there a mechanism that would let me not have `numpy` installed?.

A further feature that is useful with a metapackage is that when we run `conda update --all`, the package updates would satisfy the constraints in the metapackage.

Let me know if there is a better solution. Otherwise, I would like to reopen this pull request. Thanks!

**Comment by bkpoon** [comment]
Hi @isuruf , just following up to see if this package can be reviewed again. Thanks!

**Comment by jakirkham** [comment]
If you are looking for some kind of feature in Conda, would recommend raising a new issue over there.

**Pull request closed without merging**
