### PR TITLE
trying to build git-annex for MacOS

### PR DESCRIPTION
**Pull request by notestaff**
This PR attempts to extend PR #4141 by enabling a MacOS build.  Making it a separate PR to avoid messing up #4141 , which should be ready to merge.

### CODE REVIEW

**Comment by notestaff** [comment]
@joeyh -- any thoughts on why the MacOS build of git-annex fails?

https://travis-ci.org/conda-forge/staged-recipes/builds/315444536?utm_source=github_status&utm_medium=notification

**Comment by jakirkham** [comment]
Isn't there a `git-annex` feedstock now? Any thoughts about migrated this PR over to that feedstock?

**Comment by notestaff** [comment]
looks like macos builds on travis-ci aren't working right now?

**Comment by jakirkham** [comment]
Right, so it's not really worthwhile to debug this here since the PR would still have to be moved anyways.

**Comment by yarikoptic** [comment]
so I guess this could be closed... I can't close this one but will close #29270 then

**Comment by yarikoptic** [comment]
my conda newbee question is -- is there a way to replicate the travis OSX build on a local OSX box?

**Comment by joeyh** [comment]
stack downloads a binary of ghc which needs a specific version of the
iconv library. Something in the conda build process is apparently
forcing ghc to run with a different version of iconv.

It seems likely to be related to the uses of LIBRARY_PATH in build.sh

-- 
see shy jo

**Comment by notestaff** [comment]
@joeyh thanks; which exact version of iconv does ghc need?

**Comment by notestaff** [comment]
@jakirkham do you to be added as a co-maintainer of git-annex-feedstock?

**Comment by jakirkham** [comment]
Do I want to be a maintainer of `git-annex`? No thanks. Sorry, too busy and I'm not using it currently.

**Comment by joeyh** [comment]
Ilya Shlyakhter wrote:
> @joeyh thanks; which exact version of iconv does ghc need?

It's supposed to use the version of iconv that ships with OSX.

	datalads-imac:~ joey$ otool -L .stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2/base-4.9.1.0/libHSbase-4.9.1.0-ghc8.0.2.dylib | grep libiconv
		/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)

If you google for "stack _iconv" you'll find lots of people who have had
similar problems due to some other version of iconv being used.

-- 
see shy jo

**Comment by joeyh** [comment]
Looks like conda-forge-pinning pulls in libiconv. 
libiconv/README.md says it's only intended for systems that don't have
their own libiconv.

If I understand correctly, the files from libiconv end up in PREFIX, and
git-annex-feedstock build.sh instructs the linker to use libraries from
there via -optl-L${PREFIX}/lib

So, perhaps this can be worked around by excluding libiconv from
conda-forge-pinning on OSX, or by somehow excluding libiconv from PREFIX
during the git-annex build.

-- 
see shy jo

**Comment by joeyh** [comment]
I've tried several ways to make the git-annex build not use conda's libiconv, but in fact haskell programs on OSX get linked dynamically to libiconv.2.dylib, and so even if it built, it would later not run in an environment where conda's version of that library is being used.

I feel that the only approaches likely to work are either to make conda on OSX use the system libiconv and not its own, or to have conda build its own ghc toolchain using conda's libiconv, or to download a git-annex binary release instead of building it from source.

Note that currently the conda package of stack uses a binary release of it, which in turn downloads a prebuilt ghc, which is really the root of the problem since that ghc is assuming something about the system libiconv that conda's version of the library does not provide.

**Comment by jakirkham** [comment]
This work can continue on [the feedstock]( https://github.com/conda-forge/git-annex-feedstock ).

**Pull request closed without merging**
