### PR TITLE
Added recipe for QtPy

### PR DESCRIPTION
**Pull request by astrofrog**
cc @ccordoba12 @goanpeca

Anyone else that should be added as a maintainer?

### CODE REVIEW

**Comment by ccordoba12** [comment]
I think @Nodd should be added too (unless he doesn't want to :-)

**Comment by astrofrog** [comment]
This is now ready :)

**Comment by ocefpaf** [comment]
Thanks @astrofrog! The recipe is in great condition and  I believe @ccordoba12 already agreed to be a maintainer. As soon as we gear from @goanpeca and @Nodd we can merge this.

Or, if you wish, we can remove them for now and re-add them later in the feedstock once we have their OK.

**Comment by goanpeca** [comment]
@goanpeca, I am in :-p, thanks @astrofrog

**Comment by Nodd** [comment]
Fine with me, thanks !

**Comment by jakirkham** [comment]
Thanks everyone.

**Pull request merged**
