### PR TITLE
Add r-metaplus

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dpryan79** [comment]
Xref: https://github.com/conda-forge/r-statsexpressions-feedstock/pull/6

**Comment by npavlovikj** [comment]
Looks like only your PR is missing the other tests :/ Can you try empty commit maybe?

**Comment by npavlovikj** [comment]
@conda-forge-admin, please restart build

**Comment by npavlovikj** [comment]
@conda-forge-admin, please restart ci

**Comment by dpryan79** [comment]
github hiccup I guess

**Comment by dpryan79** [comment]
@conda-forge/help-r This is ready for review. It's `noarch: generic`, so I'm jumping the gun a bit and not waiting for the windows tests to finish.

**Comment by cbrueffer** [comment]
Interesting, the exact same recipe errored out for me a few weeks ago: https://github.com/conda-forge/staged-recipes/pull/10741

Glad to see it working now!

**Pull request merged**
