### PR TITLE
Add tensorboard-data-server

### PR DESCRIPTION
**Pull request by mdraw**
Required for https://github.com/conda-forge/tensorboard-feedstock/pull/51
See https://github.com/tensorflow/tensorboard/pull/4676

~This is currently only the noarch dummy package, which should be used as a fallback.~
TODO: provide the actual platform-specific packages where possible:

- [x] mac x86_64
- [x] linux x86_64.

TODO:
- [x] Rename to tensorboard-data-server (name of the PyPI package)

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mdraw** [comment]
conda-forge-admin, please restart ci

**Comment by mdraw** [comment]
@conda-forge-admin, please restart ci

**Comment by mdraw** [comment]
Hi @conda-forge/help-python, could you please help me with this recipe? The linux build fails with `conda_build.exceptions.OverLinkingError: overlinking check failed`, I assume because the Python package is built around a compiled rust library that's included in the source wheel. I found this conversation about a similar issue in the gitter chat here: https://gitter.im/conda-forge/conda-forge.github.io?at=5deeaa8355066245989a31be but I'm not sure if I can safely add something like

    missing_dso_whitelist:
        - '*'

to the build section like in https://github.com/conda-forge/staged-recipes/pull/10407 or if this should be solved in another way. Most of the overlinking errors seem to be about common packages that should exist in almost any linux system, so implicitly requiring them should be fine, right?

I know that in theory the best solution would be to re-build the whole package including the rust parts inside of the conda-forge runners, but I am not sure how to do this, given its complicated build setup.

**Comment by mdraw** [comment]
@conda-forge/staged-recipes All builds work now. Ready for review.

**Comment by mdraw** [comment]
@conda-forge/staged-recipes Can someone please review this PR? This new package is needed to update tensorboard.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
