### PR TITLE
Add pycbc

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This adds a recipe for [`pycbc`](https://pycbc.org). Notes:

- @ahnitz, can you please post whether you agree to be a maintainer of this recipe
- the missing license file, and the necessity for the patch have already been fixed upstream.

### CODE REVIEW

**Comment by ahnitz** [comment]
@duncanmmacleod Yes, I agree to be a maintainer.

**Comment by duncanmmacleod** [comment]
@conda-forge/help-python, I think this recipe is now ready for review, thanks.

**Comment by beckermr** [comment]
LGTM! Thanks!

**Comment by ahnitz** [comment]
:+1:

**Pull request merged**
