### PR TITLE
add ansicon

### PR DESCRIPTION
**Pull request by hadim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hadim** [comment]
Needed by https://github.com/conda-forge/staged-recipes/pull/11696

**Comment by hadim** [comment]
LGTM @marcelotrevisani

**Comment by hadim** [comment]
ping @conda-forge/help-python

**Comment by hmaarrfk** [comment]
This bundles a C library. Are you sure you don't want to build the C library yourself?

**Comment by hadim** [comment]
It's entirely part of the Python package and are not build during the installation process so I don't think I want tot do it myself. Windows dll are also known to be extremely stable across Windows versions.

**Comment by marcelotrevisani** [comment]
The problem here is that, there is no other way to install it, because the project itself it is bundling the dll, if you check on their github there are 2 dll there, for 32 and 64bits
I think we can merge it for now, any problem we can change on the feedstock

**Pull request merged**
