### PR TITLE
Add r-libcoin.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by jdblischak** [comment]
@cbrueffer libcoin requires R >= 3.4.0. You'll need to add the selector `r-base >=3.4.1` to the recipe.

https://travis-ci.org/conda-forge/staged-recipes/builds/343720759#L287

**Comment by cbrueffer** [comment]
The build matrix would still try to build it with R 3.3.0, is that desirable? Wouldn't it be better to skip the build akin to [not py27] or so?

**Comment by jdblischak** [comment]
> The build matrix would still try to build it with R 3.3.0, is that desirable?

I am pretty sure it won't. I've seen other recipes use this strategy. It's not ideal, but it works.

> Wouldn't it be better to skip the build akin to [not py27] or so?

Yes, that would be better, but I don't think such a mechanism exists for R.

**Comment by cbrueffer** [comment]
OK, I'll give it a try, thanks!

**Comment by jdblischak** [comment]
@cbrueffer Here's the other example I was thinking of:

https://github.com/conda-forge/r-uniqueatommat-feedstock/blob/master/recipe/meta.yaml#L27

**Comment by cbrueffer** [comment]
Interesting and good to know, thanks John!

**Pull request merged**
