### PR TITLE
Adding a recipe for the starry package

### PR DESCRIPTION
**Pull request by dfm**
https://github.com/rodluger/starry

cc @rodluger

### CODE REVIEW

**Comment by dfm** [comment]
It looks to me like this is good to go whenever an admin gets a chance to look. Thanks!

**Comment by dfm** [comment]
Ok thanks! @rodluger: want to confirm that you are willing to be a maintainer of this feedstock?

**Comment by rodluger** [comment]
I'm willing to be a maintainer. Thanks!

**Comment by dfm** [comment]
@synapticarbors thanks!

**Comment by dfm** [comment]
@synapticarbors it looks like something went wrong with the merge: https://travis-ci.org/conda-forge/staged-recipes/builds/405824505

Do you know what happened there? It doesn't seem like a problem with this recipe, but I can't quite figure it out.

**Comment by synapticarbors** [comment]
Since I'm not going to be able to look at this for a bit, I'm pinging @conda-forge/staged-recipes to see if someone else can investigate sooner.

**Comment by CJ-Wright** [comment]
Staged is currently held up due to an issue with travis. As soon as the issue is fixed the system will create feedstocks/packages properly. Sorry for the delay!

**Comment by dfm** [comment]
@CJ-Wright: no worries! Thanks for letting us know.

**Pull request merged**
