### PR TITLE
add recipe for legendgram

### PR DESCRIPTION
**Pull request by slumnitz**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

maintainers are @ljwolf and @darribas

### CODE REVIEW

**Comment by knaaptime** [comment]
yo @darribas and @ljwolf just want to confirm you two are willing to help maintain this package. If you don't feel like it, we will offer other devs in sacrifice :P

**Comment by chrisburr** [comment]
> yo @darribas and @ljwolf just want to confirm you two are willing to help maintain this recipe. If you don't feel like it, we will offer other devs in sacrifice :P

Ping @ljwolf and @darribas

**Comment by knaaptime** [comment]
@slumnitz per the gitter chat, i think it'll be easiest if just you and I maintain this recipe. would you mind adding a commit dropping @ljwolf and @darribas?

**Comment by knaaptime** [comment]
thanks @chrisburr !

**Pull request merged**
