### PR TITLE
add atheris 2.0.7

### LINKED ISSUE #13406: Package atheris
Google opensourced a python-fuzzer called atheris, see [announcement](https://opensource.googleblog.com/2020/12/announcing-atheris-python-fuzzer.html).

It's LLVM-based, so it sounds like conda(-forge) would be excellently positioned to package this as an easy fuzzing integration experience for the CI of various projects (already utilizing conda).

Here's the [repo](https://github.com/google/atheris), and of course it's already on [PyPI](https://pypi.org/project/atheris/).

CC @beckermr @isuruf @jakirkham @scopatz

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Notes:
- fixes #13406
- re-attempt of #16333, #16590

### CODE REVIEW

**Comment by bollwyvl** [comment]
@synapticarbors @thewchan any thoughts on some of the build errors? interest in co-maintaining.

**Comment by thewchan** [comment]
@bollwyvl I tried this before and couldn't get it to work; but I can try to take a look

**Comment by bollwyvl** [comment]
[osx](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=453753&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2002):
```
 Failed to find libFuzzer archive in search path
  Failed to find libFuzzer; you may be building using Apple Clang. Apple Clang does not come with libFuzzer.
  Please download and build the latest version of Clang:
      git clone https://github.com/llvm/llvm-project.git
      cd llvm-project
      mkdir build
      cd build
      cmake -DLLVM_ENABLE_PROJECTS='clang;compiler-rt' -G "Unix Makefiles" ../llvm
      make -j 100  # This step is very slow
  Then, set $CLANG_BIN="$(pwd)/bin/clang" and run pip again.
  You should use this same Clang for building any Python extensions you plan to fuzz.
```

**Comment by bollwyvl** [comment]
Well, `linux-64` ain't bad! Could certainly use some @conda-forge/help-c-cpp here: 
- linux-64
  -  lots of [warnings](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=453769&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1507)
    - maybe needs some more stuff from `build` available in `host`? 
- osx-64
  - I don't have any way to further debug
    - it complains about "clang too old"
      - maybe just needs a newer SDK? 
- win-64 :rofl: 
  - upstream doesn't have windows, and don't think we should block on it
  - i can't imagine fuzzing on window is very much fun/efficient
  - i'm inclined to push that off until someone who really cares comes along

**Comment by bollwyvl** [comment]
welp, i don't know how to make osx try with clang 12... but if possible, maybe that would work?

**Comment by h-vetinari** [comment]
> welp, i don't know how to make osx try with clang 12... but if possible, maybe that would work?

You can add a `conda_build_config.yaml` with:
```
c_compiler_version:            # [osx]
  - 12                         # [osx]
cxx_compiler_version:          # [osx]
  - 12                         # [osx]
```
~and rerender~ (just remembered that's not necessary in staged-recipes).

**Comment by h-vetinari** [comment]
> there were a lot of [IS NOT AN ELF](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=455074&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2059) warnings

Those are "normal" and (to the best of my knowledge) can be ignored. Excellent to hear that this went so smoothly! 🙃

**Comment by bollwyvl** [comment]
@conda-forge/staged-recipes @conda-forge/help-c-cpp ready for review on Linux and OSX (thanks to @h-vetinari)!

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/staged-recipes @conda-forge/help-c-cpp @conda-forge/help-python ready for review

**Pull request merged**
