### PR TITLE
Create recipe for sqlalchemy-migrate

### PR DESCRIPTION
**Pull request by mariusvniekerk**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@jakirkham  Are windows builds down atm?

**Comment by jakirkham** [comment]
Have a fix for it in PR ( https://github.com/conda-forge/staged-recipes/pull/2648 ). Will need to see how PR ( https://github.com/conda-forge/conda-smithy/pull/489 ) shakes out.

**Comment by mariusvniekerk** [comment]
@jakirkham :shipit: ?

**Comment by jakirkham** [comment]
Thanks @mariusvniekerk.

**Pull request merged**
