### PR TITLE
Adding OpenSesame recipes

### PR DESCRIPTION
**Pull request by dschreij**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dschreij** [comment]
@conda-forge/help-python, the Qt recipes fail on Linux because they cannot find libGL.so.1. As far as I know I have added all required CDTs (according to: https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl)

```
requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]# [linux]

  host:
    - xorg-libxfixes  # [linux]
...
```
Is there anything else (i.e. a CDT) I am forgetting? How can I make libGL available to the build environment on Linux?

Thanks!

**Comment by scopatz** [comment]
That seems like the right way to do it...

**Comment by beckermr** [comment]
You could try yum requirements maybe?

**Comment by dschreij** [comment]
@beckermr I haven't but will do that! I also saw there were some syntactical inconsistencies with my selector usage (which the linter didn't pick up, so I don't know if it matters), which I corrected first and will see if that works. I don't expect it to and will use yum_requirements next.

**Comment by dschreij** [comment]
@beckermr the yum_requirements.txt did the trick. I completely overlooked the fact that this error occurred during the testing phase, and the docs explicitly mentioned that you need this textfile to make libGL available during the test.

**Comment by beckermr** [comment]
Let's fix the recipe lints and decide if we want to run on windows or skip it.

**Comment by dschreij** [comment]
The windows builds will work. The only struggle I'm left with (on all platforms) is a circular dependency but I'm in contact with the developer of these packages on how to solve this.

**Comment by dschreij** [comment]
@smathot. The build process now halts on higher versions on pyqode that do not seem to have been released yet (or are at least not released on conda-forge yet). What's the origin of these versions?

**Comment by dschreij** [comment]
@conda-forge/helpme @conda-forge/help-python I'm suddenly getting an error that outputs at seemlingly random locations on different platforms:
```
ValueError: Incompatible component merge:
  - 'cp38'
  - '*_cp38'
```
For Windows this occurs before the build of the first recipe has even started, during creation and activation of the environment.

Is this anything that is caused by my changes or an incorrect configuration?

**Comment by vsoch** [comment]
helpme is a python library, not an alias to get help. Sorry for the misunderstanding!

**Comment by vsoch** [comment]
Try @conda-forge-admin

**Comment by vsoch** [comment]
Also try the @conda-forge/help- prefix aliases, you can choose based on your language.

**Comment by isuruf** [comment]
@dschreij, please try again in 20 minutes. This was due to a broken python package which was removed.

**Comment by dschreij** [comment]
@isuruf Thanks for the update! Will try again later
@vsoch. Sorry for pinging you incorrectly. That is indeed an inconveniently chosen name. I hope I'm not one of many to make this mistake 😆

**Comment by vsoch** [comment]
No worries @dschreij you are the first! If I had a quick answer I'd also have been happy to help.

**Comment by dschreij** [comment]
@conda-forge-admin, please rerender

**Comment by dschreij** [comment]
@conda-forge-admin, please restart ci

**Comment by dschreij** [comment]
@conda-forge/help-python-c I am getting the error
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
during test phase on the linux build for one the packages (rapunzel). Could you provide some advice on how to solve this? Am I missing a CDT, or can I pass an environment flag (as suggested in https://github.com/ContinuumIO/anaconda-issues/issues/1806#issuecomment-305972263) to set the render target to offscreen?

**Comment by dschreij** [comment]
@conda-forge/python Somehow the windows build fails after successfully completing the test of package with a compatibility conflict with regard to openssl: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=128147&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=78a0099b-3f13-5ae9-c1f0-24f71d1eac20&l=4821. I cannot determine which package this relates to (as it appears to occur between building of packages). Can you advise me on how to proceed?

**Comment by dschreij** [comment]
@conda-forge-admin, please restart ci

**Comment by dschreij** [comment]
Closing this PR and reopening as a new one as the commit history has become a mess...

**Pull request closed without merging**
