### PR TITLE
add recipe for r-taxizedb

### PR DESCRIPTION
**Pull request by jessicaparks**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jessicaparks** [comment]
@conda-forge-admin, please ping team

**Comment by cbrueffer** [comment]
Hi @jessicaparks, could you re-generate the recipe using `https://github.com/bgruening/conda_r_skeleton_helper`? It's a helper script we recommend for conda-forge R packages which does some post-processing on the recipe coming out of conda skeleton. You can also remove the LICENSE file from the recipe; the file is included in the CRAN tarball and the entry under `license_files` will make sure it gets packaged.

**Comment by jessicaparks** [comment]
@cbrueffer Thanks for the help! I re-created the recipe using `conda_r_skeleton_helper` as you suggested and removed the LICENSE file. Let me know if there's anything else to be done.

**Comment by cbrueffer** [comment]
Looks fine now! If you like, please add yourself to the maintainer section.

**Comment by jessicaparks** [comment]
@cbrueffer I don't need to be added as a maintainer, since I'm only working with this package for a short time as a consultant. Thanks for your help!

**Pull request merged**
