### PR TITLE
add ghp-import2

### PR DESCRIPTION
**Pull request by ickc**
@conda-forge/help-python

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by patricksnape** [comment]
What's the difference to this package: https://github.com/conda-forge/ghp-import-feedstock

**Comment by ickc** [comment]
Sorry, I don't know. I just package it as it is an extra dependencies from Nikola: <https://github.com/getnikola/nikola/blob/9141d6ed67a29675e2d164e209244259d2ee8d3e/requirements-extras.txt>.

@Kwpolska from Nikola, could you answer this question from @patricksnape about the diff between ghp-import2 and ghp-import?

Or @ionelmc from ghp-import2 itself, could you answer this question from @patricksnape about the diff between ghp-import2 and ghp-import?

Thanks all.

**Comment by ionelmc** [comment]
Hello everyone, ghp-import2 is basically ghp-import + proper packaging and a couple integration tests. Looks like ghp-import is maintained as of last year and has some bugfixes and the prefix option (packaging and testing is still trash tho). I don't really want to maintain ghp-import2 - I just made it cause ghp-import was dead and horrendously broken packaging-wise 4 years ago.

**Comment by ickc** [comment]
@patricksnape, as far as Nikola's dependency is concerned, https://github.com/getnikola/nikola/issues/3499 is opened about this.

In general, some packages may depends on ghp-import2 just like Nikola did so it may be a good idea to package that here. May be we can add a description in meta.yaml to point out that they are advised to install ghp-import instead.

What do you think?

**Comment by patricksnape** [comment]
@conda-forge/python What is the procedure when two packages name conflict like this?

**Comment by ocefpaf** [comment]
> @conda-forge/python What is the procedure when two packages name conflict like this?

We don't have a policy in place for this but looking into other packaging communities te rules usually are:

- first come first served, so regarding the name the current on get ghp-import;
- however, this one is named `ghp-import2`, so that will avoid naming issue, there is the clobbered endpoint. We can "break" the API by rename the endpoint or just let conda handle the warnings if people try to install them both togehter.

IMO I would work with upstream, this is a complicated case b/c we have 3 upstreams (nikola as a user and the two version of ghp-import), to solve this somehow. Nikola could vendor what they need or the fork could try to work their changes back into the original project. But that is probably a long shot...

**Comment by ickc** [comment]
I agree working with upstream is the ideal situation.

But as far as packaging is concern, shouldn't it be "allowing the namespace claimed in PyPI by default"?

ghp-import2 is far from the only example that a fork, or even an independent package, sharing the same import module name but with a different PyPI packaging name. PyPI has no restriction over this, why should it be restricted in conda-forge?

(I even see package name in conda-forge that is different from that in PyPI, perhaps to avoid name conflicts from non-python packages.)

**Comment by ocefpaf** [comment]
> PyPI has no restriction over this, why should it be restricted in conda-forge

The namespace in conda is agnostic, so PyPI rules don't really map 1-to-1 here. With that said, the main issue is clobbering the entrypoint, right? As far as I checked the package name has the 2. (While that is confusing it is "fair game.")

If that is correct the problem would be a clobber message in conda when installing both. As long as we are OK with that we can merge this.

Pinging @isuruf here b/x he usually has a good opinion/action on these matters.

**Comment by isuruf** [comment]
I don't see why we need to have a `ghp-import2` if it's just a matter of,

> ghp-import2 is basically ghp-import + proper packaging and a couple integration tests. 

I would just use `ghp-import` then. With conda-forge, we want to have packages play nicely with each other which we don't have in PyPI.

**Comment by ickc** [comment]
> With conda-forge, we want to have packages play nicely with each other which we don't have in PyPI.

I think this is a good goal. But how should we deal with situation like Nikola that (optionally i.e. `run_constraint`) on this other fork? In terms of packaging, the upstream only "support" a fork. As a maintainer of a conda-forge package which is not endorsed by the upstream itself, I don't think changing its dependencies is appropriate IMO.

(In this case it might not be a big deal for various reasons. But we should think about this matter in general, not for Nikola or ghp-import in particular.)

Also, there are cases (e.g. pyexiftool) where the original package is no longer maintained. So asking "forks to work with upstream" is not an option. I believe this is also exactly the same situation in ghp-import2 (that ghp-import was not maintained when ghp-import2 is created.)

**Comment by isuruf** [comment]
> we should think about this matter in general, not for Nikola or ghp-import in particular.

In my experience, discussions about matters in general go nowhere.

> Also, there are cases (e.g. pyexiftool) where the original package is no longer maintained. 

In that case, it's fine to use a fork.

> I believe this is also exactly the same situation in ghp-import2 (that ghp-import was not maintained when ghp-import2 is created.)

In this case it's not okay because,
1. the original package seems to be working
2. the author of the fork said they are not interested in maintaining it anymore.

**Comment by ickc** [comment]
To put it in perspective, this is the line of run_constraints: <https://github.com/conda-forge/nikola-feedstock/blob/master/recipe/meta.yaml#L54>. The goal is to represent and only represent exactly those in nikola's `setup.py`.

I don't know what's the practical solution to this, without "overriding" an upstream decision as a conda-forge recipe maintainer, and at the same time guarantee the right version is used in the dependencies.

**Comment by ickc** [comment]
> In my experience, discussions about matters in general go nowhere.

I understood this as "it should be a case by case study" which sounds good to me.

> 2\. the author of the fork said they are not interested in maintaining it anymore.

But the package that depends on it isn't making that change (on depending on ghp-import instead of a now unmaintained fork ghp-import2.) I think the important point is there was a point in time ghp-import is the unmaintained one, and at that point of time other packages are depending on ghp-import2 already. So I think we need to put that into perspective, that we are not necessarily supporting packages that choose to depend on ghp-import2 now, but those that are possibly stagnant and still depends on ghp-import2, which at the time of their decision was a good decision.

**Comment by ickc** [comment]
Moving discussion from here to https://github.com/conda-forge/nikola-feedstock/issues/2 as it is clear there's no interest in merging this.

**Pull request closed without merging**
