### PR TITLE
Adding `orbit-ml` from PyPI

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sugatoray** [comment]
PR is ready. Request for review/merging.

cc: @conda-forge/help-python

**Comment by sugatoray** [comment]
## Reason for Windows Build Failure

One of the dependencies in `pytorch`, which is not available for windows on conda-forge channel.

**Comment by HeavyTony2** [comment]
> ## Reason for Windows Build Failure
> One of the dependencies is `pytorch`, which is not available for windows on conda-forge channel.

Pytorch is avalaible on Conda-forge as Pytorch-CPU.
https://github.com/conda-forge/pytorch-cpu-feedstock/blob/master/recipe/meta.yaml

**Comment by sugatoray** [comment]
@HeavyTony2 It is the same feedstock that produces the [`pytorch` package on conda-forge](https://anaconda.org/conda-forge/pytorch).

Please run the following search and see here: https://conda-forge.org/feedstock-outputs/

image

image

**Comment by sugatoray** [comment]
These are my previously merged PRs (so far > 30 packages), and quite a few of them require pytorch. What you see in this PR, is quite common. If someday, the pytorch package on conda-forge happens to support windows OS as well, all these packages will show that.

https://github.com/conda-forge/staged-recipes/pulls?q=is%3Apr+author%3Asugatoray+sort%3Aupdated-desc+is%3Amerged+

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
