### PR TITLE
Adds conda-forge recipes for various Django apps.

### PR DESCRIPTION
**Pull request by swainn**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by swainn** [comment]
I agree to be a maintainer.

**Comment by sdc50** [comment]
I agree to be a maintainer.

**Comment by swainn** [comment]
Hey @conda-forge/help-python team, I need help understanding the current error that I'm getting on the OSX and Windows builds. 

See: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=375604&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2176

It appears to be trying to build `opentelemetry-instrumentation-django` (and failing), but that isn't one of the packages that I've provided a recipe for.

**Comment by swainn** [comment]
> Hey @conda-forge/help-python team, I need help understanding the current error that I'm getting on the OSX and Windows builds.
> 
> See: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=375604&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2176
> 
> It appears to be trying to build `opentelemetry-instrumentation-django` (and failing), but that isn't one of the packages that I've provided a recipe for.



> Hey @conda-forge/help-python team, I need help understanding the current error that I'm getting on the OSX and Windows builds.
> 
> See: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=375604&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2176
> 
> It appears to be trying to build `opentelemetry-instrumentation-django` (and failing), but that isn't one of the packages that I've provided a recipe for.

@sdc50 have you ever seen an issue like this?

**Comment by swainn** [comment]
Splitting into separate PRs

**Pull request closed without merging**
