### PR TITLE
add envisage

### PR DESCRIPTION
**Pull request by grlee77**
Add envisage as required by #285.

This PR will require #391, #394 and #395 to be merged first

### CODE REVIEW

**Comment by grlee77** [comment]
I listed the license here as BSD 3-clause, but upon further inspection there are a handful of icon images that are under a variety of other licenses.  See the details in this file:  
https://github.com/enthought/envisage/blob/38c1ffc40cdd0b9a2e19faed80c8f253a08c553c/image_LICENSE.txt

**Comment by jakirkham** [comment]
Could you please cherry-pick this commit ( https://github.com/conda-forge/staged-recipes/commit/aa7a93b8f9588c172969663e664a6fb59db70592 ) that will fix the Windows build failure?

**Comment by jakirkham** [comment]
Once the cherry-pick is done and CI passes, am more than happy to merge this.

**Comment by grlee77** [comment]
looks like this is now good to go

**Comment by jakirkham** [comment]
Thanks @grlee77.

**Pull request merged**
