### PR TITLE
Pytest django

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by mwcraig** [comment]
I think this is missing a dependency (setuptools_scm)

**Comment by sannykr** [comment]
@mwcraig : Thanks. I have added setuptools_scm in the requirements/build section of the yaml file.

**Comment by mwcraig** [comment]
Weird, it is still raising the same error (trying to download setuptools_scm). Are you able to build this recipe locally (on your machine)?

**Comment by jakirkham** [comment]
Thanks for the contribution, @sannykr. However we already have a [`pytest-django` feedstock]( https://github.com/conda-forge/pytest-django-feedstock ). Could you please send your contributions to that feedstock directly? Thanks.

**Comment by sannykr** [comment]
@mwcraig : Is it possible to reopen this pull request? I want to look at the CI log.  I tried to update the feedstock, but it didn't fix the problem. It didn't build for python 3.6 and the build failed.

**Comment by jakirkham** [comment]
The right way to do this is to debug the feedstock PR. Would recommend asking for help on gitter if you are stuck. Left [one comment]( https://github.com/conda-forge/pytest-django-feedstock/pull/7#issuecomment-323123036 ) on that PR about the Python 3.6 issue though it may fix other issues too.

**Pull request closed without merging**
