### PR TITLE
Apache Maven 3.3.9

### PR DESCRIPTION
**Pull request by johanneskoester**
#2580 seemed to suffer from a broken CI. This is just the same PR in new.

### CODE REVIEW

**Comment by johanneskoester** [comment]
@jakirkham @ocefpaf still no CircleCI, but at least appveyor is back.

**Comment by jakirkham** [comment]
Can you please try revoking permissions to CircleCI and readding them? I have only seen this with one other user and their permissions with CircleCI were totally corrupted somehow. This was how we had fixed it.

**Comment by johanneskoester** [comment]
@jakirkham you were right! Revoking and granting helped.

**Comment by johanneskoester** [comment]
Now it says `master is configured as a blacklisted branch`. Does this mean that I need to create this PR from a different branch?

**Comment by johanneskoester** [comment]
Closing in favor of #2600.

**Pull request closed without merging**
