### PR TITLE
Add recipe for r-msm, migrating from bioconda (used conda_r_skeleton_helper)

### PR DESCRIPTION
**Pull request by npavlovikj**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by npavlovikj** [comment]
I was told in a different PR to keep "toolchain" and ignore the linter, so hopefully that is ok here as well.

**Comment by dbast** [comment]
Recipe looks good!

@npavlovikj Just wondering, what is your motivation to bring this from bioconda to conda-forge?

@conda-forge/bioconda-recipes are you fine with that migration?

**Comment by bgruening** [comment]
:+1: from my site

**Comment by npavlovikj** [comment]
Thanks for the feedback @dbast !
There are some recipes in "bioconda" that are not directly related to bioinformatics and should be migrated to "conda-forge", e.g. https://github.com/bioconda/bioconda-recipes/issues/13964. I would like to help with this migration, and that is the reason for the few PRs I have here.

**Comment by dbast** [comment]
Ah. Thanks for the reference.

**Pull request merged**
