### PR TITLE
Revert "Remove auditwheel and pyelftools"

### PR DESCRIPTION
**Pull request by pelson**
Reverts conda-forge/staged-recipes#180

### CODE REVIEW

**Comment by jakirkham** [comment]
Did these not ship right? Sorry. :fearful:

Things got a bit goofed earlier. ( https://github.com/conda-forge/staged-recipes/issues/179 ) I saw repos for them so assumed they went through properly. Maybe I should have taken a closer look.

**Comment by pelson** [comment]
No worries. Easy to revert, and will help us to see the problem (if they don't go through straight away).

**Comment by jakirkham** [comment]
Seems like they are not going right away ( https://travis-ci.org/conda-forge/staged-recipes/jobs/117879072#L316 ).

**Comment by pelson** [comment]
That is because the token has been revoked. I'll fix that in a second with the latest conda-smithy (v0.6.1) :wink: .

**Pull request merged**
