### PR TITLE
Add spherical-geometry to conda-forge 

### PR DESCRIPTION
**Pull request by mwcraig**
@bernie-simon and @pllim do you mind being added as maintainers? Being a maintainer will allow you to update the built version when a new version is released. No need for experience on Windows or any other platform you are unfamiliar with.

### CODE REVIEW

**Comment by mwcraig** [comment]
@bsipocz -- This will replace astropy/conda-channel-astropy#160 once this is merged.

**Comment by pllim** [comment]
@bernie-simon is the actual "spherical_geometry" maintainer. I just like to pester him from time to time but I don't mind being added if Bernie is unavailable.

**Comment by bernie-simon** [comment]
> On Jul 31, 2017, at 4:27 PM, Matt Craig <notifications@github.com> wrote:
> 
> @bernie-simon and @pllim do you mind being added as maintainers? Being a maintainer will allow you to update the built version when a new version is released. No need for experience on Windows or any other platform you are unfamiliar with.

I've maintained the package ever since Mike left the Institute. I guess it would be a good idea to have @pliim as a backup in case I'm drying out from a drunken binge.

**Comment by bsipocz** [comment]
I believe this is not win compatible, so no wonders the appveyor build has failed.

**Comment by pllim** [comment]
Looks like it died in compiling the C extension but only for Python 3 env of the Windows build. We do not test that package under Windows in-house. @bernie-simon , do you have any insights?

**Comment by bernie-simon** [comment]
The error is because Mike turned on the quad precision math, which is C code. It's a third party library, not ours. It looks like the error that stopped the build is:

'max': is not a member of 'std'

I'll have a try at fixing it, but since I don't have a Windows machine available to test on, it's sort of like scratching an itchy foot with my shoe on.

**Comment by pllim** [comment]
c/c @mdboom -- any input on how to fix quad precision math on Windows?

**Comment by mwcraig** [comment]
How about if we skip the windows build for now and get it fixed in the feedstock (the repository created once this is merged)? 

The qd package is on conda-forge, but not for Windows, and we never built for Windows on the astropy conda channel.

**Comment by bernie-simon** [comment]
My recent change should fix the Windows build issue, but I can't be sure, as I don't have a Windows system to test it on. There might be another issue that was hidden by the std::max bug.

**Comment by mwcraig** [comment]
Can you do another release and we'll bump the version number here to see if it builds? That, or I can fire up a Windows VM later tonight or tomorrow and give it a try....

**Comment by bernie-simon** [comment]
I've bumped the version on github to 1.0.12

**Comment by mwcraig** [comment]
It looks like that doesn't include astropy helpers...could you please publish it to pypi?

**Comment by bernie-simon** [comment]
I've just now made a new source distribution (1.0.12), verified that it contains astropy_helpers, and uploaded it to PyPi.

**Comment by mwcraig** [comment]
The remaining windows failure is due to an issue I've hit before with specific update of Visual Studio 2015, which is used to build python >=3.5. 

To move this forward, I'll push an update which restricts the windows build to python 2.7. Once the feedstock is created we can change the build worker image on appveyor to the one we need...but we need the repo to be created before we can do that.

If the next push passes, this is ready to be merged.

**Comment by pllim** [comment]
Passed 🎉

**Pull request merged**
