### PR TITLE
Adding vaex-ui (Generated by releash)

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
This also depends on the other vaex-* packages that are now open PR's

**Comment by dougalsutherland** [comment]
```
+ /staged-recipes/build_artefacts/vaex-ui_1514981280715/_t_env/bin/python -s /staged-recipes/build_artefacts/vaex-ui_1514981280715/test_tmp/run_test.py
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "/staged-recipes/build_artefacts/vaex-ui_1514981280715/_t_env/lib/python3.6/site-packages/vaex/__init__.py", line 442, in <module>
    add_namespace = entry.load()
  File "/staged-recipes/build_artefacts/vaex-ui_1514981280715/_t_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/staged-recipes/build_artefacts/vaex-ui_1514981280715/_t_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/staged-recipes/build_artefacts/vaex-ui_1514981280715/_t_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'futures>=2.2.0' distribution was not found and is required by vaex-core
```

Is this a `vaex-core` packaging bug?

**Comment by maartenbreddels** [comment]
Seems like it.. odd that didn't show up before, how did you trigger this? Just install vaex-core from py3.6?

**Comment by maartenbreddels** [comment]
Ok, it is ok in the conda recipe:
https://github.com/conda-forge/vaex-core-feedstock/blob/master/recipe/meta.yaml
But should not be in the install_require in https://github.com/maartenbreddels/vaex/blob/master/packages/vaex-core/setup.py
Not sure why vaex-core installs/builds fine then. But everything from conda-forge seems to install fine, so this doesn't seem to cause any trouble.
Can we merge this now, or does it cause issues?

**Comment by dougalsutherland** [comment]
This was from the CircleCI log ([here](https://circleci.com/gh/conda-forge/staged-recipes/22475?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), scroll to bottom of the `./scripts/run_docker_build.sh` section). Because it was in a thread or something it didn't make the build fail, but it seems like a problem?

**Comment by maartenbreddels** [comment]
It doesn't seem to cause any issues, everything from conda-forge seems to work just fine. And all packages that depend on it seem to build fine. It just installed vaex-core and vaex-distributed (which was just merged) in a clean conda env (python 3.6) and it all installs as expected.

**Comment by dougalsutherland** [comment]
`vaex-distributed` didn't have that error on the CI either ([log](https://circleci.com/gh/conda-forge/staged-recipes/22474?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). But `vaex-astro` [did](https://circleci.com/gh/conda-forge/staged-recipes/22436?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), and if I install that in a test environment then I get the same error on `import vaex`:

```
$ python -c 'import vaex; print("hi")'
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "/nfs/nhome/live/dougals/anaconda/envs/tmp3/lib/python3.6/site-packages/vaex/__init__.py", line 442, in <module>
    add_namespace = entry.load()
  File "/nfs/nhome/live/dougals/anaconda/envs/tmp3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/nfs/nhome/live/dougals/anaconda/envs/tmp3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/nfs/nhome/live/dougals/anaconda/envs/tmp3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'futures>=2.2.0' distribution was not found and is required by vaex-core
hi
```

So it seems like the `vaex-core` is hitting an error on either [this line](https://github.com/maartenbreddels/vaex/blob/97337c60ad2edb5f9af3971ff52729c4b36fba0a/packages/vaex-core/vaex/__init__.py#L437) or [this one](https://github.com/maartenbreddels/vaex/blob/97337c60ad2edb5f9af3971ff52729c4b36fba0a/packages/vaex-core/vaex/__init__.py#L445); I can't easily tell which, because of  https://github.com/maartenbreddels/vaex/pull/56 / https://github.com/maartenbreddels/vaex/issues/57.

I don't know whether that matters or not.

**Comment by dougalsutherland** [comment]
Anyway, this isn't a `vaex-ui` issue, so I made https://github.com/conda-forge/staged-recipes/pull/4627#issuecomment-355025715, and am merging this now.

**Comment by maartenbreddels** [comment]
Ok, great. Thanks for looking into this. It seems that accessing the entry points will valiate the requirements again. Will make a new release of vaex-core asap.

**Pull request merged**
