### PR TITLE
clang 3.9.0: Add recipe for clang for OS X

### PR DESCRIPTION
**Pull request by yesimon**
I'm not quite familiar with the conda-feedstock process or how to test this locally. The docs don't seem to say anything about it.

### CODE REVIEW

**Comment by yesimon** [comment]
The CI logs are failing with:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 200, in build
    conda_build.api.build(meta.meta, config=config)
AttributeError: module 'conda_build' has no attribute 'api'
```

I don't think this is an error with my recipe but rather the current conda_build package?

**Comment by jakirkham** [comment]
So there is already a `clang` recipe in good shape in PR ( https://github.com/conda-forge/staged-recipes/pull/1481 ). We just have to upgrade the OS X image which we plan to do anyways.

**Comment by yesimon** [comment]
Is it really necessary to build clang from source? The binary packages should work well across platforms and should be much easier to maintain. At the very least consider the possibility of also having a simple binary distribution of clang without building from source?

**Comment by jakirkham** [comment]
This is build from source packaging effort. We try in all cases to build from source of at all possible. As it is clearly possible here, we should absolutely build from source.

**Comment by yesimon** [comment]
Ok, I understand if it's possible and there's an active maintainer that this will be built from source

**Pull request closed without merging**
