### PR TITLE
Add CDTs for `libibcm` and `libibcm-devel`

### PR DESCRIPTION
**Pull request by jakirkham**
This adds CDTs for `libibcm` and `libibcm-devel`, which is used to provide InfiniBand support.

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jakirkham** [comment]
As these are CDTs, Windows can be ignored. Only the Linux build is relevant.

**Comment by jakirkham** [comment]
@conda-forge/staged-recipes, these are ready for review! 😄

**Comment by isuruf** [comment]
Looks good to me. I've no idea whether this library should be a CDT or a real package. Can you explain?

**Comment by jakirkham** [comment]
It's part of the suite of RDMA libraries. Much like `librdmacm` ( https://github.com/conda-forge/staged-recipes/pull/8631 ) and `libibverbs` ( https://github.com/conda-forge/staged-recipes/pull/8630 ), which we packaged CDTs of before.

These require specialized hardware for network IO and link directly with drivers involved in the communication. Given this, it seems reasonable to just provide CDTs and allow other networking libraries built on top of them to use this API.

**Comment by pentschev** [comment]
Thanks for taking care of this @jakirkham !

**Comment by jakirkham** [comment]
@conda-forge/staged-recipes, any other thoughts here? 🙂

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
