### PR TITLE
WIP: re-add libmo_unpack

### PR DESCRIPTION
**Pull request by ocefpaf**
We need to wait for the new `conda-smithy` to merge this.

### CODE REVIEW

**Comment by jakirkham** [comment]
Yep, I totally missed it before. Glad to see this. :+1:

**Comment by jakirkham** [comment]
Alright, let's see what happens. Hoping it works. :four_leaf_clover:

**Comment by ocefpaf** [comment]
Fingers crossed!

**Comment by jakirkham** [comment]
They really should have an emoticon for that...or is there one?

**Comment by jakirkham** [comment]
Passes. :tada:

**Pull request merged**
