### PR TITLE
Add r-wordspace recipe.

### PR DESCRIPTION
**Pull request by tdido**
Checklist

- [x ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x ] Source is from official source
- [x ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x ] Build number is 0
- [x ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by mbargull** [comment]
Hi, this is missing build scripts, i.e., `build.sh` and `bld.bat`.
You should be able to auto generate them via
```sh
conda-skeleton cran wordspace
```
`conda-skeleton` is part of the `conda-build` package. Be sure to use a recent version of `conda-build`.
If you are on Linux, this works too:
```sh
# replace "podman" with "docker" if you rather use the latter
podman pull condaforge/linux-anvil-comp7
podman run --rm -i condaforge/linux-anvil-comp7 sh -lic 'conda-skeleton cran r-wordspace >&2 && tar -c -O r-wordspace' | tar -
ls -lA r-wordspace
```

**Comment by tdido** [comment]
Right, I did indeed use conda-skeleton, I was under the wrong impression that those weren't needed. Thanks!

**Comment by tdido** [comment]
@mbargull I've been trying to figure out the error with the osx checks to no avail. If you could give me some hints I'd be very grateful.

**Comment by mbargull** [comment]
Honestly, I don't really know. R and macOS are not my area of expertise.
But maybe adding `llvm-open` as a dependency in https://github.com/conda-forge/staged-recipes/pull/10147/commits/b494fed75b33c301833f06fe1d676d2881594ab6 suffices?

**Comment by mbargull** [comment]
> maybe adding `llvm-open`

Looks like that did the trick.

**Comment by npavlovikj** [comment]
For future reference, you can use `conda_r_skeleton_helper`, https://github.com/bgruening/conda_r_skeleton_helper, to create conda-forge recipes for CRAN packages. The helper runs `conda-skeleton cran` plus some additional clean-up suitable for conda-forge, including adding `conda-forge/r` as one of the maintainers.

**Comment by mbargull** [comment]
Thanks for chiming in @npavlovikj, appreciated! Having more expertise than me on this, do you think this is PR is ready as is or do we need anything else?

**Comment by cbrueffer** [comment]
Looks good; as @npavlovikj said please use `conda_r_skeleton_helper` next time :-)

**Pull request merged**
