### PR TITLE
WIP: Adds mkl-nonfree

### PR DESCRIPTION
**Pull request by 183amir**
So, Let's discuss this :)

### CODE REVIEW

**Comment by 183amir** [comment]
@conda-forge/core @mcg1969 This is finally working.
related to: https://github.com/conda-forge/staged-recipes/issues/80
`bob.math` recipe is there to test.
So my questions are:
can we release `mkl-nonfree` as a package?
If not, can we add its recipe to our feedstocks and release packages built with it?

**Comment by jjhelmus** [comment]
I believe that the license agreement that governs distribution of the community MKL software is the [End User License Agreement for the Intel(R) Software Development Products](https://software.intel.com/sites/default/files/managed/c0/5f/Master-EULA-for-Intel-Sw-Development-Products-March-2015.pdf).  I

I think we should discuss if conda-forge as an organization can or wants to follow the terms for redistribution laid out in that agreement.

**Comment by jakirkham** [comment]
In addition to everything @jjhelmus has nicely said, it seems Travis CI is failing and there are some linter issues. Also, I'm not sure if we want to look at Windows or not.

**Comment by 183amir** [comment]
For now, I am more concerned about license issues. There is no mac or windows builds.

**Comment by ocefpaf** [comment]
Closing as "stale."

**Pull request closed without merging**
