### PR TITLE
Add conda recipe for pymt_sedflux.

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds a conda recipe for the `pymt_sedflux` package, which brings the sedflux c libraries into Python as plugins for the pymt modeling framework.

### CODE REVIEW

**Comment by mcflugen** [comment]
This is ready for a review. Only the Windows build is failing but I'm skipping Windows anyway. It appears to fail building `parambokeh` (?) (@ocefpaf that seems to be your recipe, any idea why your recipe causes my build to fail?).

**Comment by ocefpaf** [comment]
`parambokeh` is deprecated and I added as a 1-time things to satisfy some dependencies for an old project. I don't recommend you relying on it! See the comments here https://github.com/conda-forge/staged-recipes/pull/6802#issuecomment-428282019

**Comment by mcflugen** [comment]
@ocefpaf I don't use it. It's just that the only build that failed for this recipe was the AppVeyor build (which my recipe is skipping, anyway). Looking through the logs, it appeared that it was trying to build recipes other than mine (?!), which included `parambokeh`. Since `parambokeh` failed, I got an ❌for my build.

**Comment by ocefpaf** [comment]
The CIs must be stuck on it. I'll check it later. Thanks for reporting!

**Comment by mcflugen** [comment]
@ocefpaf Thanks! I tried rerunning the builds to see what would happen. Linux and Mac pass. AppVeyor is queued, I could cancel the build if you think it would help.

**Comment by ocefpaf** [comment]
@mcflugen I just added two minor changes and skipped Appveyor. It should be good to go as soon as the CIs are green again.

PS: I just realized what your are packaging now and that took me back to 20 years ago when, as an undergrad, I had to run a sediment flux Fortran model! I would love to have this back then :smile:

**Comment by mcflugen** [comment]
@ocefpaf Thanks! That was my experience as well, which is why we're doing this. I hope you don't mind if I quote you in our next annual report to NSF!

**Comment by ocefpaf** [comment]
> I hope you don't mind if I quote you in our next annual report to NSF!

Not at all. BTW, if `conda-forge` makes your life as a scientist easier please tweet about it to `@condaforge`. We could use some "user experiences stories."

**Pull request merged**
