### PR TITLE
Add recipe for quickfix package

### PR DESCRIPTION
**Pull request by michael-doubez**
There is already a quickfix conda package but it is outdated.
https://anaconda.org/josh/quickfix

The license is a modified BSD 3 clause license (2 clauses added) named `The QuickFIX Software License, Version 1.0`; the meta linter didn't let me use "license" so I did  a mix

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by michael-doubez** [comment]
It seems the lack of Windows support is a known issue
https://github.com/quickfix/quickfix/issues/198

**Comment by michael-doubez** [comment]
@conda-forge/help-python-c pull request seems ready. At you leisure. Thank you

**Comment by scopatz** [comment]
You can add Gohlke's changes as a patch here if you need/want

**Comment by scopatz** [comment]
LGTM! Do you want it to go in as-is, or do you want to try adding in windows support via a patch?

**Comment by michael-doubez** [comment]
@scopatz Many thanks. I'd rather go as it is and work out the windows build later.

I have yet to make it work on my side and propose the fix to quickfix guys.
Best case, it will be integrated in the python package. If it takes too long, I'll add the patch in the repo.

**Comment by scopatz** [comment]
Great thanks!

**Pull request merged**
