### PR TITLE
Adding mapequation/infomap

### PR DESCRIPTION
**Pull request by vinisalazar**
Hi,

I need some help with this one as it is my first time building a recipe. [I am not a contributor for this package](https://github.com/mapequation/infomap/issues/88) but wanted it available through conda as a dependency for other package.

The build is very simple: simply run `make`

However, being unfamiliar with conda builds, I am not sure what I'm doing wrong. In my `build.sh` file, I want to run `make` and copy the generated binary `./Infomap` to my conda `bin/` directory to have it available in PATH.

My test command `./Infomap -h` also fails to run.

If I install it from source, simply running `make` allows me to run `./Infomap -h` with the generated binary.

Thank you for any assistance you can provide,

V

@conda-forge/help-c-cpp @ocefpaf 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there  [# pending](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66)

### CODE REVIEW

**Comment by ocefpaf** [comment]
This is passing on OS X and it passes on linux for me locally. Not sure what is going on here:

```
WARNING :: get_rpaths_raw()=['/home/conda/staged-recipes/build_artifacts/infomap_1583526075510/_build_env/lib'] and patchelf=[['/home/conda/staged-recipes/build_artifacts/infomap_1583526075510/_build_env/lib']] disagree for /home/conda/staged-recipes/build_artifacts/infomap_1583526075510/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/Infomap :: 
Warning: rpath /home/conda/staged-recipes/build_artifacts/infomap_1583526075510/_build_env/lib is outside prefix /home/conda/staged-recipes/build_artifacts/infomap_1583526075510/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla (removing it)
  ERROR (infomap,bin/Infomap): Needed DSO lib/libgomp.so.1 found in ['_openmp_mutex']
  ERROR (infomap,bin/Infomap): .. but ['_openmp_mutex'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
   INFO (infomap,bin/Infomap): Needed DSO lib/libstdc++.so.6 found in conda-forge::libstdcxx-ng-9.2.0-hdf63c60_2
   INFO (infomap,bin/Infomap): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_5
   INFO (infomap,bin/Infomap): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_5
   INFO (infomap,bin/Infomap): Needed DSO lib/libgcc_s.so.1 found in conda-forge::libgcc-ng-9.2.0-h24d8f2e_2
   INFO (infomap,bin/Infomap): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-hd420e75_5
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 135, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 125, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2863, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2150, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1504, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1363, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1175, in post_build
    check_overlinking(m, files, host_prefix)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1107, in check_overlinking
    m.config.enable_static)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1069, in check_overlinking_impl
    raise OverLinkingError(overlinking_errors)
conda_build.exceptions.OverLinkingError: overlinking check failed 
["  ERROR (infomap,bin/Infomap): .. but ['_openmp_mutex'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]
```

**Comment by vinisalazar** [comment]
Thanks @ocefpaf I'll wait a bit and see if any suggestions come up

**Comment by timsnyder** [comment]
Looks like the overlinking check didn't fail again after being merged?  I went to go look at the feedstock and it doesn't seem like it's fully populated yet.

Nice shark @vinisalazar !

**Comment by ocefpaf** [comment]
> Looks like the overlinking check didn't fail again after being merged?

Nope. It was fixed in https://github.com/conda-forge/staged-recipes/pull/11004/commits/e0ef474ee58db1813944a88e4579b5f0abaa9f0b and passed here too.

> I went to go look at the feedstock and it doesn't seem like it's fully populated yet.

Indeed. Not sure what is going on. But the recipe is still on staged-recipes, it was not cleared. It could be that something else is failing on master. Checking it now...

> Nice shark @vinisalazar !

Yep. Kudos on your first recipe!

**Comment by vinisalazar** [comment]
@ocefpaf and @timsnyder thank you very much for the help.

> Yep. Kudos on your first recipe!

Hopefully there will be more to come

**Comment by vinisalazar** [comment]
@ocefpaf and @timsnyder thank you very much for the help.

> Yep. Kudos on your first recipe!

Hopefully there will be more to come

**Pull request merged**
