### PR TITLE
ENH add NaMaster

### PR DESCRIPTION
**Pull request by beckermr**

### CODE REVIEW

**Comment by beckermr** [comment]
@damonge Can you help me diagnose the test error here?

Also, I am moving to get NaMaster onto conda-forge. :) 

If you would like to be one of the maintainers, let me know and I can add you!

**Comment by beckermr** [comment]
I mean the osx test error. The linux build has a linking error which I don't understand but I will fix.

**Comment by beckermr** [comment]
Discussion of moving the patches upstream are here: https://github.com/LSSTDESC/NaMaster/issues/34

**Comment by beckermr** [comment]
OK. All patches have been submitted upstream. They will be removed once the next version is released. This PR is good to merge!

Pinging @conda-forge/staged-recipes for review!

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
