### PR TITLE
Add r-sroc.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by bgruening** [comment]
@cbrueffer I'm wondering why this was missing in the first place? is https://github.com/bgruening/conda_r_skeleton_helper broken?

**Comment by cbrueffer** [comment]
What are you referring to @bgruening ?

**Comment by bgruening** [comment]
Are you using this helper script? https://github.com/bgruening/conda_r_skeleton_helper 
It automatically skips win32 builds and generates you a recipes that is conda-forge compliant.

**Comment by cbrueffer** [comment]
Ah! No, I use the stock conda skeleton. Thanks for the hint, I'll give this a try.

**Comment by bgruening** [comment]
Your recipes already look very good, so I was assuming your are already using it :)

**Comment by cbrueffer** [comment]
Haha, no, that was handywork. Didn't anticipate adding so many R packages to conda-forge!

**Comment by bgruening** [comment]
Hehe, get used to it. I started as you and now we maintain 400+ ;)

**Comment by cbrueffer** [comment]
Down the rabbit hole... :-P Thanks for committing this stuff so quickly!

**Pull request merged**
