### PR TITLE
Create recipe for django-cors-headers

### PR DESCRIPTION
**Pull request by lsetiawan**
@ocefpaf 

Trying to create recipe for [`django-cors-headers`](https://github.com/ottoyiu/django-cors-headers) so I can use in a project. Please review, hopefully I am doing this correctly. Thanks! :smile:

### CODE REVIEW

**Comment by ocefpaf** [comment]
No problem :wink:

**Comment by ocefpaf** [comment]
> @ocefpaf why is the feedstock for this still empty? [conda-forge/django-cors-headers-feedstock](https://github.com/conda-forge/django-cors-headers-feedstock)

Investigating... There are a few recipes in the queue as well.
(Ping @isuruf who maybe is already on the case.)

**Comment by isuruf** [comment]
https://github.com/conda-forge/r-forge-feedstock is giving 500 error code. Not sure why. I asked github support. Waiting for reply.

**Comment by lsetiawan** [comment]
Thanks @ocefpaf and @isuruf for all the help! :+1:

**Pull request merged**
