### PR TITLE
Add zeroc-ice

### PR DESCRIPTION
**Pull request by hadim**

### CODE REVIEW

**Comment by ericdill** [comment]
@hadim Thanks for your patience while we work through our backlog on conda-forge. Are you still interested in getting this package building for conda-forge? If so, I'll help you make the necessary changes to get this recipe building and distributed with conda-forge

**Comment by hadim** [comment]
To be honest, I don't remember what project I needed it... But I guess this package could be useful for many people.

Feel free push the necessaries commits if you want.

**Comment by ericdill** [comment]
> To be honest, I don't remember what project I needed it... 

Fair enough.

> But I guess this package could be useful for many people.

Yes, but it needs someone who wants to maintain the conda package. The primary responsibility of the `recipe-maintainers` is to keep the conda package from the conda-forge channel in sync with releases. If you are no longer interested in maintaining this package then let's just close this PR. It is 100% ok if you are no longer interested! People's interests change and that is ok :)

> Feel free push the necessaries commits if you want.

I am not interested in maintaining the zeroc-ice package. As a reviewer of `staged-recipes`, my role is to guide people through the conda-forge packaging process, not to do it for them. I already have plenty of packages that I am already responsible for 😀 .

**Comment by hadim** [comment]
Ok I understand @ericdill .

I'll close the PR for now and get back to it (or someone else), if I need it again.

**Pull request closed without merging**
