### PR TITLE
Add geomstats package recipe

### PR DESCRIPTION
**Pull request by ymontmarin**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ymontmarin** [comment]
@dopplershift @conda-forge/python
This a a reopen PR related to work done here that was ininactive: https://github.com/conda-forge/staged-recipes/pull/18613

PR is ready and recipe has been optimized to match @dopplershift  recommandations. Update has been made on upstream repository to avoid using any patch.

@nguigs @nmiolane @lpereira95, can you confirm again you agree to be maintainer as well ?

Thank you very much for your help.

**Comment by lpereira95** [comment]
I agree @ymontmarin. Thanks again for this!

**Comment by saraedum** [comment]
@ymontmarin there seem to be version requirements for the dependencies. At least, there are requirements listed in the `setup.cfg`. Should these be added?

I don't think we need the other maintainers to accept here again since they already did in #18613.

https://www.marcelotrevisani.com/grayskull produces a very nice recipe for this package with the correct requirements. You could just want to use that instead if you don't want to fill the dependencies in manually.

**Comment by ymontmarin** [comment]
@ocefpaf , as @saraedum  mentioned, @nguigs and @ninamiolane already agree to be mainteners in the original PR here https://github.com/conda-forge/staged-recipes/pull/18613 . I can contact them outside github if you really need them to confirm here again.

**Comment by ocefpaf** [comment]
> I can contact them outside github if you really need them to confirm here again.

No need, I did not see the other PR.

**Pull request merged**
