### PR TITLE
Directory name fix

### PR DESCRIPTION
**Pull request by jakirkham**
So, it looks like the directory and package have different names. I'm going to propose renaming the directory to match the package. Once this is merged, it should clear up the issues in staged-recipes.

cc @pelson @ocefpaf @ccordoba12 @jjhelmus

xref: https://github.com/conda-forge/staged-recipes/pull/1059

### CODE REVIEW

**Comment by ccordoba12** [comment]
@jakirkham, thanks for the quick fix and sorry for screwing it up ;-)

I didn't know that the directory and recipe name should match. It doesn't matter for conda-build and the linter didn't complain about it.

**Comment by jakirkham** [comment]
Yeah, honestly, I think it is a bug on our end. It really should just honor the package name and fix the directory if needed.

**Comment by jakirkham** [comment]
I added this issue ( https://github.com/conda-forge/staged-recipes/issues/1073 ) so we can properly track this issue on our end and be better about resolving it.

**Comment by jakirkham** [comment]
It's now cleared.

**Pull request merged**
