### PR TITLE
add minify-html

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge/staged-recipes, ready for review

**Comment by jan-janssen** [comment]
@conda-forge/help-rust

**Comment by jan-janssen** [comment]
Mac OS fails with:
```
 error: linking with `x86_64-apple-darwin13.4.0-clang` failed: exit status: 1
    |
    = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/bin:/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/.cargo/bin:/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/bin:/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin:/Users/runner/Miniforge3/condabin:/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/bin:/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin:/Users/runner/Miniforge3/bin:/Users/runner/Miniforge3/condabin:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:.:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.ghcup/bin" VSLANG="1033" ZERO_AR_DATE="1" "x86_64-apple-darwin13.4.0-clang" "-arch" "x86_64" "-m64" "/tmp/rustcyJTwEi/symbols.o" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/work/target/release/build/pyo3-build-config-84783ff7d2f76e04/build_script_build-84783ff7d2f76e04.build_script_build.34b03a20597f5d2a-cgu.0.rcgu.o" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/work/target/release/build/pyo3-build-config-84783ff7d2f76e04/build_script_build-84783ff7d2f76e04.lz82lhcx6lfg0vc.rcgu.o" "-L" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/work/target/release/deps" "-L" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/work/target/release/deps/libtarget_lexicon-d12b1395d74c9930.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/work/target/release/deps/libpython3_dll_a-5154ee723ed546de.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libstd-2ad7f97be9e16ca5.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-8ce93eee8bf4c86e.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libobject-0e1339b212cc7409.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libmemchr-925e672b3deb429c.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-e92d517a950bccd8.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libgimli-de95e5c2a2ace281.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-37f4c48e230f618e.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libstd_detect-dfeb4bb0652b6b8e.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-0e3ea0ec18336be2.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-39dd3003e36d7872.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libminiz_oxide-5ea1513e08ee15e0.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libadler-2967159221f4860d.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libunwind-b70656709e3eca11.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-cc5626b2e0399737.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/liblibc-8378684dba6ab463.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/liballoc-0ff05b9b25b786cc.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-9a6da74aeab39c54.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libcore-1638dc700d175798.rlib" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-7f42af62722c8f43.rlib" "-lSystem" "-lc" "-lm" "-L" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_build_env/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/work/target/release/build/pyo3-build-config-84783ff7d2f76e04/build_script_build-84783ff7d2f76e04" "-Wl,-dead_strip" "-nodefaultlibs"
    = note: Undefined symbols for architecture x86_64:
              "_getentropy", referenced from:
                  std::sys::pal::unix::rand::hashmap_random_keys::hcc27ed0e9fd421d6 in libstd-2ad7f97be9e16ca5.rlib(std-2ad7f97be9e16ca5.std.73125d0ae810e61b-cgu.0.rcgu.o)
            ld: symbol(s) not found for architecture x86_64
            clang-16: error: linker command failed with exit code 1 (use -v to see invocation)


  error: could not compile `pyo3-build-config` (build script) due to 1 previous error
  warning: build failed, waiting for other jobs to finish...
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python" PYTHON_SYS_EXECUTABLE="/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python" "cargo" "rustc" "--target" "x86_64-apple-darwin" "--message-format" "json-render-diagnostics" "--manifest-path" "/Users/runner/Miniforge3/conda-bld/minify-html_1715309020846/work/minify-html-python/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/minify_html.cpython-311-darwin.so"`
```

**Comment by ocefpaf** [comment]
@xhochy has more experience with Rust package than I do so let's wait for his input on the osx failure.

**Comment by xhochy** [comment]
You need to set c_stdlib_version to 10.13 for osx64 to fix this.

**Comment by xhochy** [comment]
You should add that to conda_build_config.yaml as we used to do with MACOSX_DEPLOYMENT_TARGET before.

**Comment by jan-janssen** [comment]
@xhochy Thanks a lot - that fixed the Mac test. This pull request is now again ready to be reviewed.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
