### PR TITLE
[WIP] Submitting jaxlib

### PR DESCRIPTION
**Pull request by ericmjl**
Redoing the PR of jaxlib.

cc: @conda-forge/help-python, @ocefpaf, @mattjj and @alexbw.

### CODE REVIEW

**Comment by mwcraig** [comment]
@ericmjl -- I've just restarted the job

**Comment by ericmjl** [comment]
@mattjj was wondering if you might have any insight as to what is happening with the macOS build here?

**Comment by ocefpaf** [comment]
> @mattjj was wondering if you might have any insight as to what is happening with the macOS build here? The Travis CI logs reveal that the build was stuck at:
> 
> ```
> Fixing linking of /usr/lib/libobjc.A.dylib in /Users/travis/miniconda/conda-bld/jaxlib_1546735899512/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/jaxlib/_pywrap_xla.so
> New link location is None
> ```


Maybe we need to use `install_name_tool`, not sure. Pinging @isuruf here for an expert opinion :grimacing:

**Comment by ericmjl** [comment]
@isuruf sorry to bother you about this, I understand you're probably busy with things - just wondering if you might have a few spare cycles to look at this?

**Comment by isuruf** [comment]
You can't fix this without compiling from source. You could do,
```yaml
build:
  binary_relocation: False  # [osx]
```
which skips relocation logic in conda-build, but not sure what would happen when you install it.

**Comment by ericmjl** [comment]
Ok, thanks for the pointer. Looks like I'll have to re-evaluate.

**Comment by isuruf** [comment]
Wait, I was mixing up this issue with another. I'm not sure why the build is stuck there.

**Comment by ericmjl** [comment]
Ok, thanks @isuruf, just updated the PR to see if this works out.

**Comment by ericmjl** [comment]
@isuruf thanks for your help the last time round! It looks like this is failing at another step. Do you have any advise on how to fix this one? (Sorry if that's too vague - this is my first time doing a PR that isn't non-standard.)

**Pull request closed without merging**
