### PR TITLE
Add sortedcollections recipe

### PR DESCRIPTION
**Pull request by mrocklin**
cc @grantjenks do you consent to being listed as maintainer of this conda-forge recipe?

### CODE REVIEW

**Comment by grantjenks** [comment]
What does it mean to be a maintainer? I tried to figure out what conda forge was once but got confused. I think I'm a maintainer for a sortedcontainers recipe but I got so many github notifications I turned them off :/

I generally upload a wheel to PyPI. It would also work as a source distribution. The versions are also tagged on github if you want to pull from there.

**Comment by mrocklin** [comment]
Conda-forge is like PyPI, but also includes non-python dependencies that the numeric computing world cares about.  The fact that we need to duplicate efforts here is somewhat suboptimal, but also fairly free of long-term pain.

This recipe just pulls your source from PyPI, verifies that it compiles on Linux, Mac, and Windows (trivial since it's just pure Python) and emits binary packages similar to wheels (but distinct).

Assuming that you don't frequently use a lot of C in `sortedcollections` then this should not require any maintenance effort from you (presumably you haven't had to do anything for `sortedcontainers` either).

If you want to ignore notifications that's fine.  I can list myself as maintainer as well.  This is just offering you privileges should you desire them.  You can also decline.  This is like being listed as an owner of a Package on PyPI.

**Comment by grantjenks** [comment]
Thank you. That is a helpful explanation.

I am happy to be a maintainer.

**Comment by jakirkham** [comment]
Thanks everyone.

**Pull request merged**
