### PR TITLE
conda 4.4->4.3 downgrade workaround

### PR DESCRIPTION
**Pull request by mbargull**
followup to #5239

### CODE REVIEW

**Comment by mbargull** [comment]
I'll open an issue upstream.

**Comment by mbargull** [comment]
https://github.com/conda/conda/issues/6906

**Comment by mbargull** [comment]
@isuruf / @jakirkham: Wanna give this a try. This should fix your issue.

**Comment by isuruf** [comment]
Thanks

**Comment by jakirkham** [comment]
Thanks all.

Seems we have [a new issue]( https://travis-ci.org/conda-forge/staged-recipes/builds/344356485 ) though. Looks like the downgrade is leading to a broken install. :/

**Comment by mbargull** [comment]
Well, I forgot the `root` -> `base` rename before. https://github.com/conda-forge/staged-recipes/pull/5242 avoids dealing with that.

**Comment by jakirkham** [comment]
No worries. Thanks @mbargull.

**Pull request merged**
