### PR TITLE
add mdanalysis recipe

### PR DESCRIPTION
**Pull request by kain88-de**
A molecular dynamics analysis program

### CODE REVIEW

**Comment by kain88-de** [comment]
@richardjgowers & @orbeckst Are you OK with being mentors on this recipe as well.

**Comment by orbeckst** [comment]
Yes, I am.

> On 2 Apr, 2017, at 03:24, Max Linke <notifications@github.com> wrote:
> 
> @richardjgowers & @orbeckst Are you OK with being mentors on this recipe as well.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by richardjgowers** [comment]
@ericdill yep LGTM

**Comment by ericdill** [comment]
Thanks @richardjgowers @orbeckst and @kain88-de

**Pull request merged**
