### PR TITLE
add gunicorn

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://pypi.python.org/pypi/gunicorn

### CODE REVIEW

**Comment by ocefpaf** [comment]
The failure here is quite odd. `openssl` is not installed when `conda-build-all` goes for the `PY34` build. However, everything works, `openssl` is installed, if I try to build it separately by manually exporting `CONDA_PY=34`.

**Comment by ocefpaf** [comment]
If I build the packages for `PY27`, `PY34`, `PY35` separately, without `conda-build-all` everything works. However, with `conda-build 1` the matrix item after the first successful fails to install some dependencies. In this case `Python 3.4` fails to pull `openssl`.

I belive it is the same issue @jochym, @souravsingh and others are experiencing with `numpy` and `openblas` in their PRs. However, if I change to `conda-build 2` everything works!

@msarahan do you have a clue about what is going on here?

PS: Same problem is seen at https://github.com/conda-forge/staged-recipes/pull/2096

**Comment by scopatz** [comment]
LGTM @ocefpaf! Just waiting for Travis!

**Comment by ocefpaf** [comment]
I would not merge this yet. We should make that change in conda-build-setup.

**Comment by scopatz** [comment]
OK. I don't think I have rights over there, though.

**Comment by ocefpaf** [comment]
> OK. I don't think I have rights over there, though.

The problem is not about rights. We are trying to make the move to `conda-build 2` for a while now. I believe only @jjhelmus is on top of things.

**Comment by ocefpaf** [comment]
@scopatz on second thought this is bring so much grief that I guess we should merge this one and modify it back once people finally figure out what to do with `conda-build-setup`.

**Pull request merged**
