### PR TITLE
[WIP] Added a libgecode recipe.

### PR DESCRIPTION
**Pull request by moorepants**
- I copied and modified the bioconda recipe for this package which is MIT licensed. Is there a protocol for showing the bioconda license? https://github.com/gwcbi/bioconda-recipes/tree/master/recipes/gecode
- gmp may be an optional dependency
- Should this be called `libgecode` or `gecode`?

### CODE REVIEW

**Comment by moorepants** [comment]
I'm getting a permissions error:

```
+ ls -al
total 3348
drwx------ 1 root root     368 Jun 28 08:12 .
drwxr-xr-x 1 root root      24 Jun 28 08:12 ..
-rw-r--r-- 1 root root  198020 Jun 28 08:12 changelog.in
-rw-r--r-- 1 root root   13541 Jun 28 08:12 CMakeLists.txt
-rwxrw-rw- 1 root root     563 Jun 28 08:12 conda_build.sh
-rw-r--r-- 1 root root  414600 Jun 28 08:12 configure
-rw-r--r-- 1 root root   10680 Jun 28 08:12 configure.ac
-rw-r--r-- 1 root root   10552 Jun 28 08:12 configure.ac.in
drwx------ 1 root root      50 Jun 28 08:12 contribs
drwx------ 1 root root      56 Jun 28 08:12 doxygen
drwx------ 1 root root    1496 Jun 28 08:12 examples
drwx------ 1 root root     332 Jun 28 08:12 gecode
-rw-r--r-- 1 root root   50173 Jun 28 08:12 gecode.m4
-rw-r--r-- 1 root root    9233 Jun 28 08:12 install-sh
-rw-r--r-- 1 root root    1278 Jun 28 08:12 LICENSE
-rw-r--r-- 1 root root    3310 Jun 28 08:12 Makefile.contribs
-rw-r--r-- 1 root root 2620229 Jun 28 08:12 Makefile.dep
-rw-r--r-- 1 root root   67197 Jun 28 08:12 Makefile.in
drwx------ 1 root root     614 Jun 28 08:12 misc
drwx------ 1 root root     472 Jun 28 08:12 test
drwx------ 1 root root      16 Jun 28 08:12 tools
+ mkdir build
+ cd build
+ ../configure --prefix=/staged-recipes/build_artefacts/libgecode_1498637557904/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl --disable-qt -with-mpfr-include=/staged-recipes/build_artefacts/libgecode_1498637557904/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -with-mpfr-lib=/staged-recipes/build_artefacts/libgecode_1498637557904/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib
/staged-recipes/build_artefacts/libgecode_1498637557904/work/gecode-5.0.0/conda_build.sh: line 8: ../configure: Permission denied
```

Do I have to use `sudo`? I haven't seen that in other conda build scripts.

**Comment by moorepants** [comment]
@isuruf Do you have a recommendation here?

**Comment by isuruf** [comment]
`chmod +x configure`?

**Comment by moorepants** [comment]
It is owned by root though. I'm not sure why it is.

**Comment by isuruf** [comment]
I think the docker container is run as root, so the user would have permissions. You just need to mark the file as executable.

**Comment by moorepants** [comment]
Got it. I was confused. I thought the permissions were already executable but the ownership was wrong. On a local download of the tarball the permissions are preserved and configure is executable. I'm not sure why that is different on CircleCI.

Also, is there a way to use linux build tools to build on windows? This lib recommends cygwin, for example.

**Comment by isuruf** [comment]
http://www.gecode.org/download.html mentions visual studio. There's also a `CMakeLists.txt`. Maybe we can try that one.

**Comment by moorepants** [comment]
This document say MS Visual C++ but then says they require cygwin tools: http://www.gecode.org/doc-latest/MPG.pdf. Page 30.

I can try cmake too. If that works, great!

**Comment by moorepants** [comment]
cmake note: http://www.gecode.org/pipermail/users/2013-February/003772.html

**Comment by moorepants** [comment]
The windows builds seem to get empty tar balls:
```
Source cache directory is: C:\bld\src_cache
Downloading source to cache: gecode-5.0.0.tar.gz
Downloading http://www.gecode.org/download/gecode-5.0.0.tar.gz
Success
Package: libgecode-5.0.0-vc14_0
source tree in: C:\bld\libgecode_1498696847055\work\gecode-5.0.0
number of files: 0
Fixing permissions
Fixing permissions
C:\bld\win-64\libgecode-5.0.0-vc14_0.tar.bz2
```
I'm confused about that.

**Comment by moorepants** [comment]
Got it. The bld.bat was in the root of the repo.

**Comment by moorepants** [comment]
Getting this error on the Windows builds now:

```
(C:\bld\libgecode_1498709648624\_b_env) C:\bld\libgecode_1498709648624\work\gecode-5.0.0\build>cmake --build . --target install --config Release -- 
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj
```

**Comment by isuruf** [comment]
Try removing `--target install`. Looks like there's no target step. Youll have to manually copy the artifacts to the prefix

**Pull request closed without merging**
