### PR TITLE
New recipe for "helper"

### PR DESCRIPTION
**Pull request by frol**
[helper](http://helper.readthedocs.io/en/latest/index.html) is a command-line/daemon application wrapper package with the aim of creating a consistent and fast way to creating applications.

It is a dependency of Rejected project: #492.

### CODE REVIEW

**Comment by frol** [comment]
@gmr Would you like to be a maintainer of this Helper recipe (package) for [Conda-Forge repository](https://conda-forge.github.io/)?

**Comment by frol** [comment]
@jakirkham OK, since no response from the package author so far, I have removed him from the list of this recipe maintainers. Can we merge now?

**Comment by jakirkham** [comment]
LGTM. Thanks @frol.

**Comment by jakirkham** [comment]
Normally, I'll write a message to the maintainers like this [one]( https://github.com/conda-forge/staged-recipes/pull/511#issuecomment-216111333 ) after we have got it in so they can sign up (or be signed up with explicit permission) as maintainers, contact me when updates are made, list the package on their website, and/or simply be aware of the fact that we have done this. Sometimes I will cc a few.

It's a mixed bag of what you will get, but it's always worth trying. I find explaining (and referencing) what [`conda`]( http://conda.pydata.org/docs/ ) and [conda-forge]( http://conda-forge.github.io/ ) are helps significantly. Some people live in a very pip friendly world if it is a Python developer or are stuck using Linux package mangers or in house build systems if they are writing C/C++ code. So, they may have no clue what `conda` is even.

Also, if you got the recipe from [conda-recipes]( https://github.com/conda/conda-recipes ) or there is a recipe in there, I'll try to cc people who contributed to the recipe and explain conda-forge and how it relates to conda and the packaging effort as a whole as done in this [comment]( https://github.com/conda-forge/staged-recipes/pull/188#issuecomment-201492836 ). Though I try not to bug ex-Continuum employees if possible. Still a few have interest in this effort, but are only interested in a smaller subset of recipes than they had initially contributed.

**Pull request merged**
