### PR TITLE
Adding pyapetnet (with meta.yaml from grayskull pypi)

### PR DESCRIPTION
**Pull request by gschramm**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by gschramm** [comment]
Right now, I have no clue why the win_64 check failed. (only tested linux_64 build locally). I will try on win_64 as well.

**Comment by gschramm** [comment]
I just run 
```
CONFIG=win64 ./.scripts/run_docker_build.sh
```
on my local linux_64 system and it completed without errors, so I don't really understand why the win_64 check failed.

**Comment by gschramm** [comment]
Just realized that on conda-forge there is only tensorflow v1.14 and I need >=2.2.
Is anybody trying to get more recent TF versions for windows on conda-forge? Or should I exclude Windows (which would be a pity).

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
We definitely want to get a more recent tensorflow for Windows, but that's [been challenging](https://github.com/conda-forge/tensorflow-feedstock/issues/124). More help there is always welcome.

As far as this package is concerned, we can ignore the Windows failure due to to missing torch since this is noarch. The nice part is as soon as tensorflow >=2.2 is available for Windows, this package will become installable on Windows.

**Pull request merged**
