### PR TITLE
create bowtie-py conda package for pypi bowtie package

### PR DESCRIPTION
**Pull request by jwkvam**
avoiding collision with package in bioconda also named bowtie

#5116 can be deleted: https://github.com/conda-forge/bowtie-feedstock/

Ref: https://github.com/bioconda/bioconda-recipes/issues/7574

### CODE REVIEW

**Comment by bgruening** [comment]
@jwkvam thanks a lot!

**Comment by dougalsutherland** [comment]
@conda-forge/core, someone should delete https://github.com/conda-forge/bowtie-feedstock/ now that https://github.com/conda-forge/bowtie-py-feedstock/ exists.

**Comment by jwkvam** [comment]
Maybe when someone deletes that repo, they can unblock the master branch from failing? I think that is causing the bowtie-py feedstock not to appear?

**Comment by jakirkham** [comment]
`bowtie` has been removed.

**Pull request merged**
