### PR TITLE
Add r-magick to conda-forge

### PR DESCRIPTION
**Pull request by dhimmel**
Details on the `magick` package for R at:

+ https://cran.r-project.org/web/packages/magick/index.html
+ https://github.com/ropensci/magick

Pinging @jdblischak who provided advice in https://github.com/conda-forge/r-cowplot-feedstock/pull/4#issuecomment-351222532.

### CODE REVIEW

**Comment by dhimmel** [comment]
Getting the [build error](https://circleci.com/gh/conda-forge/staged-recipes/22128):

```
Configuration failed because Magick++ was not found. Try installing:
 - deb: 'libmagick++-dev' (Debian, Ubuntu)
 - rpm: 'ImageMagick-c++-devel' (Fedora, CentOS, RHEL)
 - csw: 'imagemagick_dev' (Solaris)
On MacOS it is recommended to use homebrew and install ImageMagick-6:
   brew remove imagemagick
   brew reinstall imagemagick@6 --with-fontconfig --with-librsvg
   brew link --force imagemagick@6
```

Tagging [`imagemagick-feedstock`](https://github.com/conda-forge/imagemagick-feedstock) contributor @ocefpaf. How should we go about installing Magick++?

**Comment by jdblischak** [comment]
@dhimmel A few thoughts:

1. The recipe looks good!
1. Please strongly consider adding yourself as a [maintainer](https://conda-forge.org/docs/recipe.html#maintainer-role) for recipes you submit or update. This will give you write-access to the repository (and you'll get notified of any future Issues or PRs to the feedstock)
1. Looking at the build script for imagemagick, I think this [line](https://github.com/conda-forge/imagemagick-feedstock/blob/a73d6918b23e73885271980ecb1bbc9e4c38aed9/recipe/build.sh#L40) needs to be changed to `--with-magick-plus-plus=yes`. I'll let @ocefpaf decide if making that change is feasible.

**Comment by ocefpaf** [comment]
> Looking at the build script for imagemagick, I think this [line](https://github.com/conda-forge/imagemagick-feedstock/blob/a73d6918b23e73885271980ecb1bbc9e4c38aed9/recipe/build.sh#L40) needs to be changed to `--with-magick-plus-plus=yes`. I'll let @ocefpaf decide if making that change is feasible.

We can try, I don't recall why I removed that in the first place. Do you want to send a PR?

**Comment by dhimmel** [comment]
@conda-forge-admin, please lint

Note this is not necessary but I want to kick off new CI builds since https://github.com/conda-forge/imagemagick-feedstock/pull/5 has been merged. Assuming by time the Travis CI builds runs, the mac binary will have been deployed to https://anaconda.org/conda-forge/imagemagick/files

**Comment by jdblischak** [comment]
To restart the builds, recreate your most recent commit, e.g.:

```
cd staged-recipes
git checkout r-magick
git commit --amend
git push -f origin r-magick
```

**Comment by dhimmel** [comment]
## Failing builds

The [macOS build](https://travis-ci.org/conda-forge/staged-recipes/builds/317100200) failed due to the following error:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/travis/miniconda/conda-bld/r-magick_1513396611438/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/magick/libs/magick.so':
  dlopen(/Users/travis/miniconda/conda-bld/r-magick_1513396611438/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/magick/libs/magick.so, 6): Symbol not found: _AdaptiveSharpenImageChannel
  Referenced from: /Users/travis/miniconda/conda-bld/r-magick_1513396611438/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/magick/libs/magick.so
  Expected 
Error: loading failed
Execution halted
ERROR: loading failed
```

The [Circle CI Build](https://circleci.com/gh/conda-forge/staged-recipes/22204) failed with:

```
ERROR: configuration failed for package ‘magick’
* removing ‘/staged-recipes/build_artefacts/r-magick_1513369364393/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/magick’
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build-all", line 6, in <module>
    exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build_all/cli.py", line 93, in main
    b.main()
  File "/opt/conda/lib/python3.6/site-packages/conda_build_all/builder.py", line 297, in main
    built_dist_location = self.build(meta, build_config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build_all/builder.py", line 227, in build
    output_paths = conda_build.api.build(meta.meta, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/staged-recipes/build_artefacts/r-magick_1513369364393/work/magick/conda_build.sh']' returned non-zero exit status 1.
Exited with code 1
```

**Comment by jdblischak** [comment]
I think the problem is conflicting dependencies between r-base and imagemagick. r-base 3.3.2_5 requires zlib 1.2.8. The most recent imagemagick that is pinned with zlib 1.2.8 is imagemagick-7.0.6-pl5.22.2.1_0, which is why it is getting selected. libpng may also be a problem.

**Comment by dhimmel** [comment]
Ah yes, the [imagemagick dependencies](https://github.com/conda-forge/imagemagick-feedstock/blob/a3effa0d28aa14cd9b000c6cbffe4d85d5c2dd20/recipe/meta.yaml#L17-L38) appear to be very specific. I wonder if they could be relaxed? @ocefpaf any insights here? From my limited experience, it seems that it's common for `meta.yaml` files to specify a minimum version, but it's rare to pin specific versions and that this pinning should be avoided unless necessary?

**Comment by dhimmel** [comment]
r-base=3.4.1 dependency pins were updated in https://github.com/conda-forge/r-base-feedstock/pull/27. r-base=3.3.2 dependency pins are not updated yet. The CircleCI and [Travis](https://travis-ci.org/conda-forge/staged-recipes/builds/317100200#L267) builds use 3.3.2, so I'll wait to restart CI until those pins have been updated.

**Comment by jdblischak** [comment]
Updated pins for R 3.3.2 are pending in https://github.com/conda-forge/r-base-feedstock/pull/28

**Comment by jdblischak** [comment]
I just restarted the Travis build. I can't restart the CircleCI build because I don't have write access to staged-recipes.

**Comment by jdblischak** [comment]
The good news is that the correct version of imagemagick was pulled!

https://travis-ci.org/conda-forge/staged-recipes/builds/317100200#L242

The bad news is that there was a random HTTP error.

https://travis-ci.org/conda-forge/staged-recipes/builds/317100200#L307

Restarted yet again.

**Comment by dhimmel** [comment]
The [CircleCI build](https://circleci.com/gh/conda-forge/staged-recipes/22439) has passed, which I believe is the Linux build.

The following R output was provided:

```
> library('magick')
Linking to ImageMagick 7.0.7.11
Enabled features: fontconfig, freetype, fftw, pango, webp, x11
Disabled features: cairo, ghostscript, lcms, rsvg
Attention: the 'magick' package has been compiled with ImageMagick-7 which is known to have problems.
Rebuilding against ImageMagick-6 is recommended.
```

See https://github.com/conda-forge/imagemagick-feedstock/issues/6 regarding `Disabled features: cairo, ghostscript, lcms, rsvg`.

Travis CI still running... a previous one had timed out.

**Comment by jdblischak** [comment]
@dhimmel @cbrueffer I think the build script needs to be updated to link to magick++. The travis build timed out because it was trying to install Imagemagick via Homebrew (even though it was already installed with conda):

```
/Users/travis/miniconda/conda-bld/r-magick_1514933435526/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/Magick++-config: line 44: --cflags: command not found
/Users/travis/miniconda/conda-bld/r-magick_1514933435526/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/Magick++-config: line 56: --libs: command not found
Auto-brewing imagemagick in /tmp/build-imagemagick...
```

I think this can be fixed by specifying `--cflags` and `--libs` in `build.sh`.

It built fine on Linux because somehow it managed to find these flags:

```
Found pkg-config cflags and libs!
```

**Comment by jdblischak** [comment]
@dhimmel That's not going to work. Sorry I wasn't more explicit in my last message. I'm not exactly sure how to solve this.

It will likely need to end up looking similar to the [build.sh for r-gsl](https://github.com/conda-forge/r-gsl-feedstock/blob/master/recipe/build.sh):

```
#!/bin/bash

export CFLAGS="$(gsl-config --cflags)"
export LDFLAGS="$(gsl-config --libs)"

# For whatever reason, it can't link to gsl correctly without this on OS X.
export DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib

$R CMD INSTALL --build .
```

Looking at the [configure script for magick](https://github.com/ropensci/magick/blob/master/configure), my first guess would be to replace `gsl-config` in the above recipe with `Magick++-config`.

**Comment by dhimmel** [comment]
> That's not going to work.

Amended the last commit so its now https://github.com/conda-forge/staged-recipes/pull/4613/commits/0eb88602270581459958f8e0d6ac52a22989666c. Let's see if that works.

**Comment by halldc** [comment]
@dhimmel I think this can be closed now that https://github.com/conda-forge/staged-recipes/pull/5351 is merged?

**Comment by dhimmel** [comment]
> @dhimmel I think this can be closed now that #5351 is merged?

Fantastic! Thanks everyone who figured this out.

**Pull request closed without merging**
