### PR TITLE
Add JASP recipe

### PR DESCRIPTION
**Pull request by izahn**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge/staged-recipes the `cos7` build is failing here because somehow it uses `cos6` packages, e.g., https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=348847&view=logs&j=35904a6b-5404-55c5-26d9-f2fb250157bf&t=f869e631-70a1-522d-dae3-fa8b231d712d&l=829 . Maybe there is something unusual about this package that causes staged-recipes to use `cos6` `cdt` packages even for the `linux_64_centos7` build?

This recipe does build correctly with `cos7`. Building https://github.com/izahn/jasp-recipe with `python build-locally.py` works, as shown in the build logs at https://gist.github.com/izahn/72ac17005d16450ef324b4730d279127 and https://gist.github.com/izahn/7efc3cf032ac4a2b69055b3aab260e39. Build artifacts are available at https://anaconda.org/izahn/jasp and I have tested that they install and run correctly.

**Comment by izahn** [comment]
@conda-forge-admin restart ci

**Comment by izahn** [comment]
Ready for review  @conda-forge/staged-recipes

This does need to be built with `cos7` `cdt` packages, the the failing `linux_64` build is expected.

**Comment by izahn** [comment]
@boutinb and @vandenman please comment here if you are willing to be listed as co-maintainers of this JASP conda package. Duties are typically light, as described in https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role

**Comment by izahn** [comment]
@conda-forge-admin please restart ci

**Comment by izahn** [comment]
After nearly a month-long effort to package all dependencies this recipe is finally in good shape and ready for review 
@conda-forge/help-r @conda-forge/help-c-cpp

**Comment by izahn** [comment]
Because this package is large and has a huge dependency list I built it locally and uploaded it to my personal `izahn` channel. This allows us to install  (Linux only for now) and run it locally to make sure it works before merging. I've done this on RHEL 7 and Archlinux, and everything appears to work correctly.

**Comment by dbast** [comment]
This is far beyond the average CRAN recipe, which @conda-forge/r normally agrees to co-maintain. Would be nice if it finds some other co-maintainers.

**Comment by izahn** [comment]
Yes, finding co-maintainers would be good. I reached out to the JASP community in https://github.com/jasp-stats/jasp-issues/issues/1353 and was hopeful that @boutinb or @vandenman would be up for it, but no takers yet.

**Comment by Naeemkh** [comment]
Hi @izahn, I would like to become  co-maintainers on this project. I would be grateful if you could add me to the mailing list.

**Comment by izahn** [comment]
@conda-forge-admin please restart ci

**Comment by izahn** [comment]
@dbast My colleague @Naeemkh has joined me as a co-maintainer! I'm happy to remove @conda-forge/r from the maintainers list, or leave it, as you prefer. The good news in terms of maintenance is that this is way out at the tip of the dependency tree. Nothing will conceivably depend on it, so in the worst case it shouldn't break anything else if maintenance were to lapse for some unforeseen reason. I'm confident that @Naeemkh and I can keep it in good shape.

**Comment by izahn** [comment]
@conda-forge/help-r anyone else want to weigh in on removing vs. keeping @conda-forge/r in the maintainers list? Other than that  this is ready for review and merge.

**Pull request merged**
