### PR TITLE
add pynacl

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
pending pretend update.

**Comment by CJ-Wright** [comment]
Re triggering builds

**Comment by CJ-Wright** [comment]
Re triggering builds

**Comment by CJ-Wright** [comment]
@conda-forge/core Can someone with windows experience tell me what went wrong/how to fix it?

**Comment by CJ-Wright** [comment]
@conda-forge/core Ready for review, windows build is having some weird stuff happening with it so I'll try to fix it as a feedstock.

**Comment by CJ-Wright** [comment]
@dstufft @reaperhulk @warner would any of you be interested in being maintainers?

**Comment by dstufft** [comment]
Given I don't use Conda, I would probably be a poor maintainer of a conda package.

**Comment by scopatz** [comment]
LGTM, thanks @CJ-Wright

**Comment by CJ-Wright** [comment]
@conda-forge/core This doesn't seem to have been [rendered as a feedstock yet.](https://github.com/conda-forge?utf8=%E2%9C%93&q=pynacl&type=&language=) Is that normal?

**Comment by reaperhulk** [comment]
I don't have the bandwidth to maintain packaging here, sorry. If you run into problems building PyNaCl on windows I can help though. Just mention me and I should be able to provide some context.

**Pull request merged**
