### PR TITLE
Remove binary wave file from recipe for now

### PR DESCRIPTION
**Pull request by ericdill**
xref: https://github.com/conda-forge/conda-smithy/issues/500

attn @hbredin @thomasfillon. Will need to re-add the .wav file after the feedstock is created.

### CODE REVIEW

**Comment by thomasfillon** [comment]
Perfect ! Thanks @ericdill

**Comment by thomasfillon** [comment]
Hi @ericdill 

Yaafe feedstock on conda-forge is still empty.
Is something still missing to get Yaafe into Conda-forge feedstock ?

**Comment by ericdill** [comment]
> Yaafe feedstock on conda-forge is still empty.

Yes.

> Is something still missing to get Yaafe into Conda-forge feedstock ?

Yes. Our auto-feedstock creation mechanism is not working at the moment. We are looking in to it.

**Comment by thomasfillon** [comment]
Ok . Thank you very much for your response.

**Pull request merged**
