### PR TITLE
add r-uniprotr recipe via conda_r_skeleton_helper

### PR DESCRIPTION
**Pull request by taylorreiter**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by taylorreiter** [comment]
@conda-forge/help-r I wasn't sure, is the SPDX for GPL-3 `GPL-3.0-only`?

**Comment by cbrueffer** [comment]
Yes, `GPL-3.0-only`

**Comment by taylorreiter** [comment]
@conda-forge/help-r 

Windows fails with `conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {MatchSpec("r-magick"), MatchSpec("r-base==3.5.1=h0c8e037_1006")}`

Does this mean the PR can't be merged into conda-forge, or is it ok for a package to only be available for linux and osx?

**Comment by dbast** [comment]
The windows failure can be ignored as it is a noarch package, which finally will be build on linux before upload. Though it will be only installable for platforms where the dependencies are available.

**Comment by dbast** [comment]
@taylorreiter thanks!

**Pull request merged**
