### PR TITLE
Add texlab 0.2.2

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/staged-recipes should I be concerned about the CircleCI failure?

is @conda-forge/help-rust a thing?

**Comment by bollwyvl** [comment]
I had been working off a much-too-old `master`... have manually merged and force pushed

**Comment by isuruf** [comment]
See https://github.com/conda-forge/conda-forge.github.io/issues/1052 about a license issue with Rust packages

**Comment by bollwyvl** [comment]
> license issue with Rust packages

Ooh, that sounds brutal! I'll read more in depth over there.

**Comment by bollwyvl** [comment]
Using the techniques from conda-forge/conda-forge.github.io#1052 and [pysyntect-feedstock](https://github.com/conda-forge/pysyntect-feedstock/blob/master/recipe/check_licenses.py), i've gotten it down to the following that will have to be tracked down by hand:

```
Licenses for the following dependencies are not being packaged:
* bytemuck (Zlib) -> https://github.com/Lokathor/bytemuck
* cesu8 (Apache-2.0 OR MIT) -> https://github.com/emk/cesu8-rs
* fuchsia-zircon-sys (BSD-3-Clause) -> https://fuchsia.googlesource.com/garnet/
* kernel32-sys (MIT) -> https://github.com/retep998/winapi-rs
* mac (Apache-2.0 OR MIT) -> https://github.com/reem/rust-mac.git
* siphasher (Apache-2.0 OR MIT) -> https://github.com/jedisct1/rust-siphash
* siphasher (Apache-2.0 OR MIT) -> https://github.com/jedisct1/rust-siphash
* strum (MIT) -> None
* strum_macros (MIT) -> None
* utf-8 (Apache-2.0 OR MIT) -> https://github.com/SimonSapin/rust-utf8
* void (MIT) -> https://github.com/reem/rust-void.git
* winapi-build (MIT) -> https://github.com/retep998/winapi-rs
* winapi-i686-pc-windows-gnu (Apache-2.0 OR MIT) -> https://github.com/retep998/winapi-rs
* winapi-x86_64-pc-windows-gnu (Apache-2.0 OR MIT) -> https://github.com/retep998/winapi-rs
* ws2_32-sys (MIT) -> https://github.com/retep998/winapi-rs
```

Still a fair amount, but less than 200 or whatever it started with...

**Comment by bollwyvl** [comment]
Now running into this on windows:

```
python dep present in build but not host requirements
```

... since we use python to do the munging/checking, but don't want any build cruft. 

i found [this gitter](https://gitter.im/conda/conda-build?at=5d4d9d717d56bc6080242d75) from @isuruf... how'd you "properly" get around this issue?

For now I'm skipping the python-based stuff on windows, as all the win-64 stuff gets pulled in on linux, anyway.

**Comment by bollwyvl** [comment]
Skipping the license check on windows seems to work fine:
```
(%PREFIX%) %SRC_DIR%>texlab --version 
texlab 2.2.0

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit /B 1 

(%PREFIX%) %SRC_DIR%>exit /B 0 

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1 

Resource usage statistics from testing texlab:
   Process count: 1
   CPU time: unavailable
   Memory: 1.5M
   Disk usage: 535B
   Time elapsed: 0:00:02.0

TEST END: C:\Miniconda\conda-bld\win-64\texlab-2.2.0-he32d670_0.tar.bz2

```

**Comment by bollwyvl** [comment]
huzzah, back to green with all the licenses.

@conda-forge/staged-recipes have ticked all the boxes i can now...

**Comment by scopatz** [comment]
Wow! You are a beast @bollwyvl!

**Comment by isuruf** [comment]
How is checking in unix enough? If there are windows only dependencies, the licenses will be missed?

**Comment by bollwyvl** [comment]
It pulls a number of win-rs packages (see licenses) that I assume are
windows only.... We could take the ten minute hit to build/install the
license tester, dump out the json and compare to other architectures. All
the checks are just commented out, and do work, but raise that python build
dep issue.

**Comment by isuruf** [comment]
You can fix that by adding `compiler('c')` to build.

**Comment by bollwyvl** [comment]
Awesome! Good to know. Will investigate restoring the checks on feedstock.

**Pull request merged**
