### PR TITLE
fix: add recipe for Yaafe

### PR DESCRIPTION
**Pull request by hbredin**
@ericdill this recipe depends on the other three (libsndfile, mpg123, and argtable2)

### CODE REVIEW

**Comment by hbredin** [comment]
@ericdill now that all three dependencies are available, how can I force CI to try again?

**Comment by ericdill** [comment]
A rebase onto origin/master should do it. If that doesn't work, I can manually restart the CI builds for this PR

**Comment by hbredin** [comment]
If you don't mind, that would be great. 
Otherwise it will wait until next week when I can access a terminal.

**Comment by ericdill** [comment]
@hbredin Restarted all three services. 🤞

**Comment by thomasfillon** [comment]
From the details in CircleCI build log, I think the[ `libsnd` recipe](https://github.com/hbredin/staged-recipes/blob/feature/libsndfile/recipes/libsndfile/meta.yaml#L18) lacks of run requirements.
requirements:
```
requirements:
  build:
    - toolchain
    - libflac
    - libvorbis
    - libogg
```
You may need to add:
```
  run:
    - libflac
    - libvorbis
    - libogg

```
to requirement.
I don't know if `toolchain` is also require for running.

you may also have a look at the recipe here: https://anaconda.org/trung/libsndfile/files

**Comment by hbredin** [comment]
I am out of office. Can you do a pull request on libsndfile-feedstock?

**Comment by thomasfillon** [comment]
yes of course.

**Comment by hbredin** [comment]
Looks like that solved the issue.

**Comment by ericdill** [comment]
Nice catch @thomasfillon !  Thanks @hbredin and @thomasfillon

**Pull request merged**
