### PR TITLE
Revert "add silx, need to figure out deps"

### PR DESCRIPTION
**Pull request by scopatz**
Reverts conda-forge/staged-recipes#3339

### CODE REVIEW

**Comment by CJ-Wright** [comment]
why?

**Comment by scopatz** [comment]
The build is failing on master now :(

**Comment by scopatz** [comment]
NM it went to a feedstock.

**Comment by CJ-Wright** [comment]
Sorry :(
Do you have a like to the build failure so I can debug it?

**Comment by scopatz** [comment]
Yeah you can look at the commits https://github.com/conda-forge/staged-recipes/commits/master

**Pull request closed without merging**
