### PR TITLE
Adding recipe for my new package BubbleDet

### PR DESCRIPTION
**Pull request by og113**
@conda-forge/help-python, ready for review!

### CODE REVIEW

**Comment by og113** [comment]
The checks are failing due to a missing dependency: the cosmoTransitions Python package. I have added cosmoTransitions in PR #23728.

**Comment by og113** [comment]
PR #23728 has now been merged, so retrying checks.

**Comment by og113** [comment]
Another dependency is missing: the Python package findiff (https://findiff.readthedocs.io/en/latest/). Next job is to write a recipe for that.

**Comment by og113** [comment]
Pull request for findiff version 0.10.0 is here: https://github.com/conda-forge/findiff-feedstock/pull/6

**Comment by og113** [comment]
Findiff pull request now merged. Will retry checks.

**Comment by og113** [comment]
I've resolved the checks (by adding dependencies to conda-forge). @conda-forge/help-python, ready for review!

**Comment by og113** [comment]
@joonashir and @AndreasEkstedt can you please confirm if you are happy to be added as maintainers for BubbleDet?

**Comment by joonashir** [comment]
Happy to be added as a maintainer for BubbleDet

**Comment by joonashir** [comment]
I am happy to be added as a maintainer for BubbleDet?

**Comment by AndreasEkstedt** [comment]
I am also happy to be added as a maintainer

**Pull request merged**
