### PR TITLE
Fix AppVeyor build failures after upgrade to Miniconda 4.4.10

### PR DESCRIPTION
**Pull request by sodre**

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please get the `conda build-all` call in `test_script` as well?

**Comment by sodre** [comment]
done

**Comment by sodre** [comment]
It looks like AppVeyor has updated their version of Miniconda36 install from 4.3 to 4.4. Empirical evidence is looking at the AppVeyor build logs for #5328 and this PR. 

I noticed that we control the version of miniconda in the linux-anvil docker container. Why don't we do the same for Windows?  Is it just a matter of creating the PR and updating the `conda-smithy rerender` command?

**Comment by jakirkham** [comment]
There was some interest in reusing what AppVeyor provided us to save some CI time. It has mostly worked for ~2yrs. Periodically issues crop up, but they have been very responsive to us. That said, if you would rather install it directly to have some more control, that's fine by me.

**Comment by sodre** [comment]
I am still investigating why the same issue is not happening on feedstock builds.

**Comment by jakirkham** [comment]
Seems the `conda-smithy` development version is vulnerable to the same issue.

ref: https://ci.appveyor.com/project/conda-forge/python-snappy-feedstock/build/1.0.27/job/x05cxqvxlym6c5lt

**Comment by jakirkham** [comment]
My guess is that by updating `conda` first we are side stepping some potentially problematic version of `conda`. Maybe that would work here too?

**Comment by sodre** [comment]
that is what I was going to try next...

**Comment by sodre** [comment]
@jakirkham, 

The AppVeyor issue is fixed in this PR now and ready for you to merge/review. The change that made the difference was to add `-n root` on the calls to `conda install`.

Here is a link to the appveyor build logs from my branch https://ci.appveyor.com/project/sodre/staged-recipes.

**Comment by jakirkham** [comment]
Was just looking at that. Good catch!

`conda` 4.4 changes it to `base` instead of `root`. So think that is the crux of the issue.

Thanks for working on this @sodre.

**Pull request merged**
