### PR TITLE
Add icub-models

### PR DESCRIPTION
**Pull request by traversaro**
This PR adds a recipe for the [icub-models package](https://github.com/robotology/icub-models), a package that contains the kinematic and dynamic models for several versions of the [iCub humanoid robot](https://icub.iit.it/).

The models are in textual format commonly used in robotics world (URDF) but it also includes a C++ and Python helper library to easily access the models. Furthermore, the activation scripts set the environment variable to make sure that the models can easily be found when using robotics libraries such as ROS, ROS2, Gazebo and YARP.

The activation and deactivation scripts are generated in the receipe build dscritp from `.msh` files using [multisheller](https://github.com/mamba-org/multisheller) (fyi @wolfv).

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
The wrong python is found:
~~~
2022-03-03T18:35:55.1350694Z -- Found PythonInterp: $BUILD_PREFIX/bin/python (found version "3.10.2") 
2022-03-03T18:35:55.1859558Z -- Found PythonLibs: python3.10
~~~

**Comment by traversaro** [comment]
> The wrong python is found:
> 
> ```
> 2022-03-03T18:35:55.1350694Z -- Found PythonInterp: $BUILD_PREFIX/bin/python (found version "3.10.2") 
> 2022-03-03T18:35:55.1859558Z -- Found PythonLibs: python3.10
> ```

Solved by backporting https://github.com/robotology/icub-models/pull/137 .

**Comment by traversaro** [comment]
@conda-forge/help-c-cpp @conda-forge/help-python-c The recipe is ready for review.

**Comment by wolfv** [comment]
cool! Really happy to see that the multisheller stuff is useful :)

**Pull request merged**
