### PR TITLE
Rename b2 to backblaze-b2

### PR DESCRIPTION
**Pull request by freundTech**
@isuruf 

Renamed b2 to b2-tools, same name as in homebrew.

Ref: https://github.com/conda-forge/staged-recipes/pull/27965#discussion_r1811204762

EDIT: Looks like this was too late. The CI went through with creating the feedstock as `b2`, despite the revert.

### CODE REVIEW

**Comment by freundTech** [comment]
Renamed to backblaze-b2.

Small problem: The workflow is already at work creating the repositories, despite the revert. rst2ansi and b2sdk repos already exist.

**Comment by freundTech** [comment]
B2 feedstock now also exists: https://github.com/conda-forge/b2-feedstock

**Comment by isuruf** [comment]
I'm archiving b2-feedstock now.

**Comment by freundTech** [comment]
CI here now fails because I removed the already created recipes, but the built packages aren't yet synced to the channel.
Will retry later.

**Pull request merged**
