### PR TITLE
Add pyephem to conda-forge

### PR DESCRIPTION
**Pull request by mwcraig**
@brandon-rhodes -- would you be willing to be a maintainer on this? 

There is not much involved with being a maintainer...if this is merged, a new github repo will (automatically) be created at https://github.com/conda-forge/pyephem-feedstock

When a new version is released, the version number and checksum need to be updated in the recipe. @bsipocz and I are also maintainers...adding you means that you can also update when releases are made.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Alas! I am far enough behind on pull requests and issues for my existing projects that I can't take on further responsibilities at this point, but I'll let you know if that ever changes.

**Comment by mwcraig** [comment]
No problem; I'll keep an eye out for new releases! (and thanks for some terrifically useful software!)

**Comment by mwcraig** [comment]
Approving, since it has been approved.

**Comment by ocefpaf** [comment]
A tale of two packages :smile: 

https://github.com/conda-forge/ephem-feedstock/blob/master/recipe/meta.yaml

**Comment by mwcraig** [comment]
D'oh!!! What now? I did check the feedstocks and didn't see a `pyephem` 😦 . Looking at the pypi page for pyephem, though, I now see *both* `pip install ephem` and `pip install pyephem` will work.

This is an odd case...

**Comment by mwcraig** [comment]
@brandon-rhodes -- what is your preference for the package name going forward: `pyephem` or `ephem` or both?

**Comment by ocefpaf** [comment]
I opened https://github.com/conda-forge/pyephem-feedstock/issues/1 to discuss that.

Many years ago I package `ephem` in lieu of `pyephem` for OpenSUSE b/c they have a name preference for the `import` name. However, it would be nice to know the author's preference :smile:

**Pull request merged**
