### PR TITLE
Adding datarobot-bp-workshop

### PR DESCRIPTION
**Pull request by danna-naser**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by danna-naser** [comment]
I agree to maintain

**Comment by danna-naser** [comment]
@conda-forge/help-python this is ready for review

**Comment by carterbox** [comment]
> 2. RESTRICTIONS ON USE OF THE TOOL AND UTILITY SOFTWARE
You shall not, and shall not permit any third party to, except as may be allowed by any applicable law which is incapable of exclusion by agreement between the parties and except as permitted under this Agreement:
    (a) attempt to backup, copy, modify, create derivative works from, or distribute any part of the Tool and Utility Software;

This proprietary license does not allow conda-forge to redistribute this software. It must be republished by Datarobot with a license that allows redistribution by at least conda-forge.

**Review by carterbox — CHANGES_REQUESTED** [review]
Software license does not allow conda-forge to redistribute code.

**Comment by danna-naser** [comment]
@carterbox would removing "distribute" from (a) as shown below works for you?
> (a)     attempt to backup, copy, modify, create derivative works from any part of the Tool and Utility Software;

**Comment by carterbox** [comment]
I am not a lawyer, but distribution of a conda package does also require backup, copy, and sometimes modification (to fix bugs) of the package source.

I cannot, in good faith, accept this package with single word edits to the license. Especially since it is not clear that you are an official representative of Datarobot. Datarobot is free to create their own conda channel if they wish to keep their license while making it available for conda.

**Comment by carterbox** [comment]
@datarobot

**Comment by danna-naser** [comment]
@carterbox we've updated the license to a Modified 3-Clause BSD

**Comment by danna-naser** [comment]
@carterbox the license has been updated in pypi and changed to the new version here. Author contribution should no longer be necessary

**Pull request closed without merging**
