### PR TITLE
Add configs from pypi

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge/help-python This is ready for review. I packaged a copy of the MIT license since it's not part of the file on pypi, let me know if that's not OK.

**Comment by npavlovikj** [comment]
@dpryan79 , I would suggest you to open an issue upstream for adding the license file in the pypi tarball. If we don't hear back from the developer, we can go ahead and merge the recipe - everything else looks good to me.

**Comment by dpryan79** [comment]
Will do, though since it hasn't been updated in 4 years it's unlikely anything will ever come of that.

**Comment by npavlovikj** [comment]
Yeah, I noticed that. However, let's give it a try, and we can merge this later.

**Comment by chrisburr** [comment]
It can be merged now and fixed in the feedstock as part of the update bot's PR.  Thanks @dpryan79 and @npavlovikj!

**Pull request merged**
