### PR TITLE
Added a recipe for pyinstrument_cext.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
https://github.com/conda-forge/gawk-feedstock/issues/1 seems related but I don't understand what the fix is.

**Comment by moorepants** [comment]
Figured it out. There was no license file in the source tar ball.

**Comment by moorepants** [comment]
Once tests pass, this is ready for review and merging.

**Comment by synapticarbors** [comment]
It looks like the `license_file` should be in the next release judging from the github repo. When the feedstock builds, could you just put in an issue so that next update of the recipe you look for the license file being distributed with the source?

**Comment by moorepants** [comment]
Thanks, will do.

**Pull request merged**
