### PR TITLE
Add r-softimpute

### PR DESCRIPTION
**Pull request by apcamargo**
The recipe was created using `conda_r_skeleton_helper`.

### CODE REVIEW

**Comment by apcamargo** [comment]
Hey @conda-forge/staged-recipes , can someone take a look at this?

**Comment by cbrueffer** [comment]
@apcamargo looks good! Could you add the following people as co-maintainers?

```
  - johanneskoester
  - bgruening
  - daler
  - jdblischak
  - cbrueffer
```

**Comment by apcamargo** [comment]
Sure!

**Comment by apcamargo** [comment]
@cbrueffer Is every package require to have this set of default maintainers? Recently, a recipe of mine was accepted and I'm the [sole maintainer of the repository](https://github.com/conda-forge/r-aggregation-feedstock/blob/master/recipe/meta.yaml). Should I add those maintainers and trigger a new build?

**Comment by cbrueffer** [comment]
@apcamargo it's not required, but it's a good idea. At least most R packages have this set of maintainers, which means PRs get acted on quickly, and sweeping changes such as the compiler definition changes from last week get done quickly.

**Pull request merged**
