### PR TITLE
added recipe for `pybids`

### PR DESCRIPTION
**Pull request by sarthakpati**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by effigies** [comment]
I agree to be a maintainer.

**Comment by adelavega** [comment]
I agree to be maintainer

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Ignoring noarch Windows build failure due to missing dependency.

**Comment by jakirkham** [comment]
We ran into some unexpected issues converting this particular recipe into a feedstock. Have filed an issue with GitHub Support. In the interim, we may need to move this recipe into a different directory to ensure other recipes can still convert to feedstocks (since this is unfortunately blocking them).

**Comment by jakirkham** [comment]
For more context, the repository [cannot be found by GitHub's API]( https://github.com/conda-forge/staged-recipes/actions/runs/3660554705/jobs/6187829606 ). Though it does exist, when logged in it appears to be offline

Screen-Shot-2022-12-09-at-12 25 39-PM

**Comment by jakirkham** [comment]
Yeah I see that if I'm not logged in to GitHub

**Comment by jakirkham** [comment]
Haven't heard back from GitHub

Managed to rename this to [`pybids-feedstock_old`]( https://github.com/conda-forge/pybids-feedstock_old ), which may help

**Comment by jakirkham** [comment]
That [failed conversion]( https://github.com/conda-forge/staged-recipes/actions/runs/3690900467/jobs/6248389840#step:6:810 ) too unfortunately

However was able to create a new empty repo named [`pybids-feedstock`]( https://github.com/conda-forge/pybids-feedstock ), which shows up. Will give that a try

**Comment by jakirkham** [comment]
While conversion of this feedstock isn't done, [the conversion job ran all the way through]( https://github.com/conda-forge/staged-recipes/actions/runs/3690900467/jobs/6248460430 ). It had the usual sorts of errors (Travis API 403s). These usually clear with some time. Will keep an eye on this, but expect this should clear out overnight.

**Comment by jakirkham** [comment]
Sadly this still doesn't seem to be working. Once CI registration is reached for this feedstock, the conversion job ends abruptly without a traceback.

**Comment by jakirkham** [comment]
Nvm looks like we get the same failure even when this recipe is absent. Moving it back to `recipes` ( https://github.com/conda-forge/staged-recipes/commit/440981da820ee09447ce69737c8b95f0ab8688c0 ). Though it appears conversion is blocked.

**Comment by jakirkham** [comment]
Huzzah! 🎉

It is converted ( https://github.com/conda-forge/pybids-feedstock )

**Comment by jakirkham** [comment]
GitHub just let me know they deleted [`pybids-feedstock_old`]( https://github.com/conda-forge/pybids-feedstock_old ) (the corrupted repo). The functional feedstock is still here. So this closes out this issue.

**Pull request merged**
