### PR TITLE
Added recipe r-rmdformats for CRAN pckage rmdformats

### PR DESCRIPTION
**Pull request by fgp**
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] Recipe matches output of `conda_r_skeleton_helper`

### CODE REVIEW

**Comment by dbast** [comment]
Hi @fgp, have a look at https://github.com/bgruening/conda_r_skeleton_helper ... that helps to create the recipe in a bit cleaner way and also adds the group conda-forge/r to receipe maintainers (you can still add yourself).

**Comment by fgp** [comment]
> Hi @fgp, have a look at https://github.com/bgruening/conda_r_skeleton_helper ... that helps to create the recipe in a bit cleaner way

I did that, and the only non-whitespace change was to add `noarch: generic` to the `build` section. Not sure what that does exactly, but I trust that `conda_r_skeleton_helper` knows what it's doing.

> and also adds the group conda-forge/r to receipe maintainers (you can still add yourself).
The recipe now contains only conda-forge/r, that probably makes more sense.

**Comment by fgp** [comment]
I believe this should be merge-able now

**Comment by dbast** [comment]
LGTM. @conda-forge/help-r @conda-forge/r ready for review.

**Pull request merged**
