### PR TITLE
feat: add new r-nanoparquet recipe

### PR DESCRIPTION
**Pull request by dlaehnemann**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dlaehnemann** [comment]
@conda-forge/r Is it OK to list you for this R package recipe? (Not sure how a team can confirm this, but I hope someone here does know).

**Comment by johanneskoester** [comment]
> @conda-forge/r Is it OK to list you for this R package recipe? (Not sure how a team can confirm this, but I hope someone here does know).

Yes, I confirm that this is OK.

**Review by johanneskoester — APPROVED** [review]

**Comment by dlaehnemann** [comment]
Until the linter is fixed for teams of maintainers, we will have to ignore the above linter error. For the respective issue, see:
https://github.com/conda-forge/conda-smithy/issues/1817

**Comment by mfansler** [comment]
I wouldn't bother with Windows here, which only builds R 4.1. Rather the R 4.4 migrator will come along and turn it back on for the feedstock.

**Comment by dlaehnemann** [comment]
Thanks for chiming in. So should we simply skip windows altogether in the meta.yaml, or ignore the failing build test, here? Which do you think would be better handled by the R 4.4 migrator?

I did have a different error message a few commits back,  and with the conda-forge outage and now this different error, I am not sure if my changes since then fixed this. The error was this:
```
In file included from ./thrift/transport/TTransportException.h:25:0,
                 from thrift/transport/TTransportException.cpp:20:
./thrift/numeric_cast.h: In function 'Dst apache::thrift::numeric_cast(Src)':
./thrift/numeric_cast.h:56:11: error: 'bad_cast' is not a member of 'std'
     throw std::bad_cast();
           ^
./thrift/numeric_cast.h:60:11: error: 'bad_cast' is not a member of 'std'
     throw std::bad_cast();
           ^
make: *** [thrift/transport/TTransportException.o] Error 1
C:/bld/r-nanoparquet_1721298640894/_h_env/lib/R/etc/x64/Makeconf:245: recipe for target 'thrift/transport/TTransportException.o' failed
ERROR: compilation failed for package 'nanoparquet'
* removing 'C:/bld/r-nanoparquet_1721298640894/_h_env/lib/R/library/nanoparquet'
Traceback (most recent call last):
  File "D:\a\1\s\.ci_support\build_all.py", line 261, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "D:\a\1\s\.ci_support\build_all.py", line 151, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "D:\a\1\s\.ci_support\build_all.py", line 207, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "C:\Miniforge\lib\site-packages\conda_build\api.py", line 250, in build
    return build_tree(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 3638, in build_tree
    packages_from_this = build(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 2462, in build
    windows.build(
  File "C:\Miniforge\lib\site-packages\conda_build\windows.py", line 339, in build
    check_call_env(
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 405, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 381, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
``

But I guess for now, I would just revert the last commit, to get back to the more generic `epoch` problem you mention in #25319.

**Comment by dlaehnemann** [comment]
OK, that rebase might have been unnecessary. And I wasn't expecting it to mess up the commit hashes. But here we go...

**Comment by dlaehnemann** [comment]
Also, I don't have write access. So could you merge this, once the tests pass again, @mfansler ?

**Comment by dlaehnemann** [comment]
Added one more thing: I realized the LICENSE file references the `inst/COPYRIGHTS` file. So we should include this in the recipe.

**Review by mfansler — APPROVED** [review]
I think this is good for now to merge, but it would be appropriate to attempt swapping out the zstd and any other vendoring with dynamic links to Conda Forge builds. Since this is often non-trivial for R packages, I'm okay to postpone until feedstock. Could you be sure to make an issue for this on the feedstock?

**Comment by dlaehnemann** [comment]
Many thanks again, and I was suspecting that this should be done. So here's the tracking issue:
https://github.com/conda-forge/r-nanoparquet-feedstock/issues/1

At the same time, I think having everything bundled in the nanoparquet repo is kind of the idea behind this, being a minimum external dependencies package. So I guess this is nanoparquet vs. conda-forge philosophy here...

**Pull request merged**
