### PR TITLE
Including GMSO to conda-forge

### PR DESCRIPTION
**Pull request by justinGilmer**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by umesh-timalsina** [comment]
I am willing to be listed as a maintainer.

**Comment by justinGilmer** [comment]
I am willing to be listed as a maintainer

**Comment by daico007** [comment]
I am willing to be listed as a maintainer.

**Comment by rmatsum836** [comment]
I am willing to be listed as a maintainer

**Comment by uppittu11** [comment]
I am willing to be listed as a maintainer

**Comment by justinGilmer** [comment]
@bdice I initially tried to push to your PR, but permissions did not allow that, I found it easier to just make a new branch and PR from a detached head state of that branch itself.

**Comment by bdice** [comment]
I am willing to be listed as a maintainer. Thanks all!

**Comment by justinGilmer** [comment]
@synapticarbors Hello again, this is an update to the initial PR #10978 . I think once the win64 test has completed, this should be good to go!

**Pull request merged**
