### PR TITLE
Add csvtk

### PR DESCRIPTION
**Pull request by apcamargo**
This PR adds [`csvtk`](https://github.com/shenwei356/csvtk/).

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by apcamargo** [comment]
@conda-forge/help-go any idea how to figure out why the build is failing? The error message is not really informative (or I'm missing something obvious).

```
source tree in: /home/conda/staged-recipes/build_artifacts/csvtk_1728674681752/work
export PREFIX=/home/conda/staged-recipes/build_artifacts/csvtk_1728674681752/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
export BUILD_PREFIX=/home/conda/staged-recipes/build_artifacts/csvtk_1728674681752/_build_env
export SRC_DIR=/home/conda/staged-recipes/build_artifacts/csvtk_1728674681752/work
+ go build -buildmode=pie -trimpath -o=/home/conda/staged-recipes/build_artifacts/csvtk_1728674681752/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/csvtk '-ldflags=-s -w -X main.Version=0.30.0'
no Go files in /home/conda/staged-recipes/build_artifacts/csvtk_1728674681752/work
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2555, in build
    utils.check_call_env(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
    packages_from_this = build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2563, in build
    raise BuildScriptException(str(exc), caused_by=exc) from exc
conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/home/conda/staged-recipes/build_artifacts/csvtk_1728674681752/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by xhochy** [comment]
You might need to `cd` into a subdirectory of the source tree for this command to run successfully.

**Comment by apcamargo** [comment]
@conda-forge/help-go, ready for review!

**Comment by apcamargo** [comment]
@xhochy can you take a look at this recipe?

**Review by xhochy — APPROVED** [review]

**Pull request merged**
