### PR TITLE
Trigger rebuild with `travis-ci.com`

### PR DESCRIPTION
**Pull request by jakirkham**
cc @conda-forge/core @conda-forge/staged-recipes

### CODE REVIEW

**Comment by beckermr** [comment]
@ocepaf was it related to api keys?

**Comment by beckermr** [comment]
I might have spelled that wrong. Apologies.

**Comment by jakirkham** [comment]
I see. Thanks for the context.

Looks like commit ( https://github.com/conda-forge/staged-recipes/commit/9d29a0faedf643dab78bc506028ecd940800b7d5 ) is relevant. @chrisburr, do you recall why this needed to be reverted?

**Comment by beckermr** [comment]
OTOH it appears we are building with travis-ci.com right now, so maybe this is fixed?

**Comment by jakirkham** [comment]
That's what I'm thinking too. Plus it's easy to try and revert if it doesn't work.

**Comment by beckermr** [comment]
I saw this on a job:

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.com/auth/github
```

**Comment by jakirkham** [comment]
I don't think that is related.

**Comment by jakirkham** [comment]
Can see [this job was started with the script]( https://travis-ci.com/conda-forge/staged-recipes/builds/145982946 ).

**Comment by jakirkham** [comment]
Sorry made a few edits to my comments above to include examples. Happy to discuss further as needed 🙂

**Comment by beckermr** [comment]
No worries! This appears to be working but we are out of API requests. So we simply have to wait!

**Comment by jakirkham** [comment]
Yeah I think Drone syncs through all of our repos each time, which exhaust our GitHub requests.

**Pull request merged**
