### PR TITLE
PR: Add decorator package

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by goanpeca** [comment]
@synapticarbors any comments?

**Comment by synapticarbors** [comment]
I believe there is already a feedstock for this package:
https://github.com/conda-forge/python-decorator-feedstock/blob/master/recipe/meta.yaml

**Comment by goanpeca** [comment]
Hmmm, ok but why did they change the name of the package? I thought we always favored keeping pypi original names

**Comment by synapticarbors** [comment]
See the discussion in the original `staged-recipes` PR: 

https://github.com/conda-forge/staged-recipes/pull/697

**Pull request closed without merging**
