### PR TITLE
Add recipe for IlmBase

### PR DESCRIPTION
**Pull request by npavlovikj**
Add recipe for IlmBase

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Is it possible to build this project without the support of ``C++14`` ?

**Comment by npavlovikj** [comment]
@marcelotrevisani , many thanks for the detailed feedback! The current support of c++14 was the reason why I used "gcc_linux-64" instead of "{{ compiler('c') }}" initially. The earlier version of the package used c++11, so I will see if I can patch the Makefile.

**Comment by npavlovikj** [comment]
@marcelotrevisani , it turned out there is a "--enable-cxxstd=11" flag I added for the Linux build. One of the errors I saw for the Windows build is "ERROR: The system was unable to find the specified registry key or value.". Is this is the main error, or the tests are the reason for the failing?

**Comment by marcelotrevisani** [comment]
That was related to the tests in windows, I just added some tests for windows. I think that should be fine now

**Comment by marcelotrevisani** [comment]
@npavlovikj , the problem is just I don't know how the libraries are build in windows, actually what are the names. I don't have a windows machine (just linux). However, I will try find a windows machine here to fix the tests

**Comment by marcelotrevisani** [comment]
I will run just the windows CI to get the right extensions of the libraries

**Comment by npavlovikj** [comment]
hah, sounds good @marcelotrevisani  :) I will see if I can replicate the Windows errors myself.

**Comment by npavlovikj** [comment]
@marcelotrevisani , with "cmake" on Windows there is only "include" dir, and not "lib", and therefore the failure (I was able to locally replicate this). Do you know if there is some flag that needs to be set with "cmake" or "ninja"?

**Comment by marcelotrevisani** [comment]
Usually ``-DCMAKE_PREFIX_PATH=%PREFIX%`` do the job for you, but the ``CMakelists`` may override that.
Let's skip windows for now and you can fix it in the feedstock, open a PR and mark me

**Comment by marcelotrevisani** [comment]
Thanks for adding this to conda forge!

**Comment by npavlovikj** [comment]
@marcelotrevisani , thank you SO MUCH for your tremendous help with this package - I really appreciate it! This is one of the dependencies for building the main "openexr" package, so hopefully the others will go smoother :)

**Pull request merged**
