### PR TITLE
Add fastscapelib f2py

### PR DESCRIPTION
**Pull request by jcfr**
This PR is follow-up of https://github.com/conda-forge/staged-recipes/pull/8430 attempting to address remaining issues.

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by benbovy** [comment]
Hmm looks like it is tricky to avoid f2py using gfortran installed on Windows.

What are the advantages using VC/Flang over mingw here?  I'm sure there are pros/cons but I'm not really aware of it.

Maybe a cleaner solution would be updating ``CMakeLists.txt`` [here](https://github.com/fastscape-lem/fastscapelib-fortran/blob/607b3c0f212d5470fb7a8bd1642b826fdddd5c2a/CMakeLists.txt#L161) and set the C and Fortran compilers from cmake variables using f2py's ``--fcompiler`` and ``--compiler`` options? (or alternatively remove the ``-c`` option and let cmake configure the build system).

Of course this would require making a new release, but I'm not in a hurry and I'm willing to do it before enabling windows builds with conda-forge, unless you think this could be easily fixed here (looks like you're almost there).

**Comment by jcfr** [comment]
Compiler is properly detected, that said .. the call to f2py fails.

To reproduce locally on windows:

1. install python 3.7. From a powershell started with admin right (see [here](https://scikit-ci-addons.readthedocs.io/en/latest/addons.html#install-python-ps1) for more details):

```
Set-ExecutionPolicy Unrestricted -Force
[System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192 -bor 48

$pythonVersion = "3.7"
$pythonArch = "64"
$pythonPrependPath = "0"
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/scikit-build/scikit-ci-addons/master/windows/install-python.ps1'))
```

2. install flang. From a powershell started with admin right (see [here](https://scikit-ci-addons.readthedocs.io/en/latest/addons.html#install-flang-ps1) for more details):

```
Set-ExecutionPolicy Unrestricted -Force
[System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192 -bor 48

iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/scikit-build/scikit-ci-addons/master/windows/install-flang.ps1'))
```

3. Create a virtual env and activate

```
C:\Python37-x64\Scripts\virtualenv.exe %HOME%\fastscapelib-f2py-venv-37-x64
%HOME%\fastscapelib-f2py-venv-37-x64\Scripts\activate.bat
```

4. clone source

```
cd %HOME%
git clone git://github.com/jcfr/fastscapelib-fortran.git -b 2.7.0
```

5. prepare fortran env.

```
pip install scikit-build cmake ninja

set BUILD_PREFIX=C:\Miniconda3\envs\flang-env

set FC=%BUILD_PREFIX%\Library\bin\flang.exe
set CC=%BUILD_PREFIX%\Library\bin\clang-cl.exe
set CXX=%BUILD_PREFIX%\Library\bin\clang-cl.exe

set LIB=%BUILD_PREFIX%\Library\lib
```

5. attempt to build the project 

```
cd %HOME%\fastscapelib-fortran

python setup.py build

# ===> It will fail
```

6. To reproduce the error

```
set F2PY_EXE=%HOME%\fastscapelib-f2py-venv-37-x64\Scripts\f2py.exe
set BUILD_PREFIX=C:\Miniconda3\envs\flang-env
set SRC_DIR=%HOME%\fastscapelib-fortran

%F2PY_EXE% --f90exec=%BUILD_PREFIX%/Library/bin/flang.exe -m _fastscapelib_fortran -c %SRC_DIR%/src/Advect.f90 %SRC_DIR%/src/Diffusion.f90 %SRC_DIR%/src/FastScape_api.f90 %SRC_DIR%/src/FastScape_ctx.f90 %SRC_DIR%/src/LocalMinima.f90 %SRC_DIR%/src/Strati.f90 %SRC_DIR%/src/StreamPowerLaw.f90 %SRC_DIR%/src/VTK.f90 %SRC_DIR%/Flexure2D_v1.0/src/flexure2D.f90 %SRC_DIR%/Flexure2D_v1.0/src/four1.f %SRC_DIR%/Flexure2D_v1.0/src/realft.f %SRC_DIR%/Flexure2D_v1.0/src/sinft.f
```


### errors

```
[...]
flang.exe:f90: D:/T/fastscapelib-fortran/src/FastScape_ctx.f90
flang.exe: warning: argument unused during compilation: '-fno-second-underscore' [-Wunused-command-line-argument]
F90-W-0093-Type conversion of expression performed (D:/T/fastscapelib-fortran/src/FastScape_ctx.f90: 705)
  0 inform,   1 warnings,   0 severes, 0 fatal for run_strati
compiling Fortran sources
Fortran f77 compiler: C:/Miniconda3/envs/flang-env/Library/bin/flang.exe -Wall -g -ffixed-form -fno-second-underscore -O3 -funroll-loops
Fortran f90 compiler: C:/Miniconda3/envs/flang-env/Library/bin/flang.exe -Wall -g -fno-second-underscore -O3 -funroll-loops
Fortran fix compiler: C:/Miniconda3/envs/flang-env/Library/bin/flang.exe -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -O3 -funroll-loops
creating C:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\Release\T\fastscapelib-fortran\Flexure2D_v1.0
creating C:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\Release\T\fastscapelib-fortran\Flexure2D_v1.0\src
compile options: '-IC:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\src.win-amd64-3.7 -Id:\t\fastscapelib-f2py-venv-37-x64\lib\site-packages\numpy\core\include -Ic:\python37-x64\include -Ic:\python37-x64\include -c'
extra options: '-JC:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\Release\ -IC:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\Release\'
flang.exe:f90: D:/T/fastscapelib-fortran/src/Advect.f90
flang.exe: warning: argument unused during compilation: '-fno-second-underscore' [-Wunused-command-line-argument]

F90-F-0004-Unable to open MODULE file fastscapecontext.mod (D:/T/fastscapelib-fortran/src/Advect.f90: 3)
F90/x86-64 Windows Flang - 1.5 2017-05-01: compilation aborted
error: Command "C:/Miniconda3/envs/flang-env/Library/bin/flang.exe -Wall -g -fno-second-underscore -O3 -funroll-loops -IC:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\src.win-amd64-3.7 -Id:\t\fastscapelib-f2py-venv-37-x64\lib\site-packages\numpy\core\include -Ic:\python37-x64\include -Ic:\python37-x64\include -c -c D:/T/fastscapelib-fortran/src/Advect.f90 -o C:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\Release\T\fastscapelib-fortran\src\Advect.o -JC:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\Release\ -IC:\Users\DASHBO~1\AppData\Local\Temp\tmp3spekbt2\Release\" failed with exit status 1
```

**Comment by benbovy** [comment]
Many thanks @jcfr for having tried hard and for all those details! I see [in the logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=38096&view=logs&jobId=240f1fee-52bc-5498-a14a-8361bde76ba0&taskId=23010c01-6a9d-5f94-9037-792618644b77&lineStart=1733&lineEnd=1733&colStart=1&colEnd=55) another linker error `flang.exe: error: unknown argument: '-mlong-double-64'`.

Honestly, I don't know if there is easy fixes for these errors. Flang is a young project so I wouldn't be surprised if f2py has no good support for it yet. I think it will be easier for me to go with mingw, which is already used [for ci](https://github.com/fastscape-lem/fastscapelib-fortran/blob/master/.appveyor.yml).

**Comment by jcfr** [comment]
@benbovy  we use flang to build complex project like https://github.com/Reference-LAPACK/lapack without problem.

> f2py has no good support for it yet.

Indeed, the problem is that the current use of f2py also expect it to compile the code which we should instead delegate to CMake.

This two topics are an attempt to achieve this:
* https://github.com/scikit-build/scikit-build/compare/master...jcfr:add-UseF2PY-and-UsePythonExtensions
* https://github.com/fastscape-lem/fastscapelib-fortran/compare/master...jcfr:2.7.0-python-module-support-flang

(Background, this reuse some work done by an other contributor to improve scikit-build and use it to build scipy.)

With this topics, the remaining error on the windows build is:

```
-- Configuring done
-- Generating done
-- Build files have been written to: D:/T/fastscapelib-fortran/_skbuild/win-amd64-3.7/cmake-build
[1/1] Linking Fortran shared module _fastscapelib_fortran.pyd
FAILED: _fastscapelib_fortran.pyd
cmd.exe /C "cd . && D:\T\fastscapelib-f2py-venv-37-x64\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_d
ll --intdir=CMakeFiles\_fastscapelib_fortran.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x86\rc.exe --mt=C
:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\M
SVC\1415~1.267\bin\Hostx86\x64\link.exe /nologo CMakeFiles\_fastscapelib_fortran.dir\src\Advect.f90.obj CMakeF
iles\_fastscapelib_fortran.dir\src\Diffusion.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\FastScape_api.f9
0.obj CMakeFiles\_fastscapelib_fortran.dir\src\FastScape_ctx.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\
LocalMinima.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\Strati.f90.obj CMakeFiles\_fastscapelib_fortran.d
ir\src\StreamPowerLaw.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\VTK.f90.obj CMakeFiles\_fastscapelib_fo
rtran.dir\Flexure2D_v1.0\src\flexure2D.f90.obj CMakeFiles\_fastscapelib_fortran.dir\Flexure2D_v1.0\src\four1.f
.obj CMakeFiles\_fastscapelib_fortran.dir\Flexure2D_v1.0\src\realft.f.obj CMakeFiles\_fastscapelib_fortran.dir
\Flexure2D_v1.0\src\sinft.f.obj CMakeFiles\_fastscapelib_fortran.dir\_fastscapelib_fortranmodule.c.obj CMakeFi
les\_fastscapelib_fortran.dir\_fastscapelib_fortran-f2pywrappers.f.obj  /out:_fastscapelib_fortran.pyd /implib
:_fastscapelib_fortran.lib /pdb:_fastscapelib_fortran.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO  _f2p
y_runtime_library.lib c:\python37-x64\libs\python37.lib  && cd ."
LINK: command "C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1415~1.267\bin\Hostx86\x64\link.exe /nologo CM
akeFiles\_fastscapelib_fortran.dir\src\Advect.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\Diffusion.f90.o
bj CMakeFiles\_fastscapelib_fortran.dir\src\FastScape_api.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\Fas
tScape_ctx.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\LocalMinima.f90.obj CMakeFiles\_fastscapelib_fortr
an.dir\src\Strati.f90.obj CMakeFiles\_fastscapelib_fortran.dir\src\StreamPowerLaw.f90.obj CMakeFiles\_fastscap
elib_fortran.dir\src\VTK.f90.obj CMakeFiles\_fastscapelib_fortran.dir\Flexure2D_v1.0\src\flexure2D.f90.obj CMa
keFiles\_fastscapelib_fortran.dir\Flexure2D_v1.0\src\four1.f.obj CMakeFiles\_fastscapelib_fortran.dir\Flexure2
D_v1.0\src\realft.f.obj CMakeFiles\_fastscapelib_fortran.dir\Flexure2D_v1.0\src\sinft.f.obj CMakeFiles\_fastsc
apelib_fortran.dir\_fastscapelib_fortranmodule.c.obj CMakeFiles\_fastscapelib_fortran.dir\_fastscapelib_fortra
n-f2pywrappers.f.obj /out:_fastscapelib_fortran.pyd /implib:_fastscapelib_fortran.lib /pdb:_fastscapelib_fortr
an.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO _f2py_runtime_library.lib c:\python37-x64\libs\python37.
lib /MANIFEST /MANIFESTFILE:_fastscapelib_fortran.pyd.manifest" failed (exit code 1120) with the following out
put:
   Creating library _fastscapelib_fortran.lib and object _fastscapelib_fortran.exp
_fastscapelib_fortranmodule.c.obj : error LNK2019: unresolved external symbol f2pyinitfastscapecontext_ refere
nced in function f2py_init_fastscapecontext
_fastscapelib_fortranmodule.c.obj : error LNK2001: unresolved external symbol union_bn_
_fastscapelib_fortran.pyd : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.

```

**Comment by benbovy** [comment]
Could https://github.com/ninja-build/ninja/pull/1521 solve this remaining error?

**Comment by jcfr** [comment]
### ninja with fortran support

It turns I was using the ninja package that I maintained [on pypi](https://pypi.org/project/ninja/), and it is already integrating these changes (it is based of https://github.com/kitware/ninja#readme). 

As a side note, I have been working on updating the ninja conda package as well but this is a work in progress and the maintainer of the feedstock would prefer a new official release of ninja :disappointed:  (see https://github.com/conda-forge/ninja-feedstock/pull/12 and https://github.com/conda-forge/ninja-feedstock/pull/13)

### same link errors using NMake

All of that said, the same link errors are reported without ninja (scikit-build default to using NMake generator if ninja is not found):

```
29 warnings generated.
[ 94%] Building Fortran object CMakeFiles/_fastscapelib_fortran.dir/_fastscapelib_fortran-f2pywrappers.f.obj
[100%] Linking Fortran shared module _fastscapelib_fortran.pyd
LINK: command "C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1415~1.267\bin\Hostx86\x64\link.exe /nologo MakeFiles\_fastscapelib_fortran.dir\objects1.rsp /out:_fastscapelib_fortran.pyd /implib:_fastscapelib_fortranlib /pdb:D:\T\fastscapelib-fortran\_skbuild\win-amd64-3.7\cmake-build\_fastscapelib_fortran.pdb /dll /version
0.0 /machine:x64 /INCREMENTAL:NO _f2py_runtime_library.lib c:\python37-x64\libs\python37.lib /MANIFEST /MANIFSTFILE:_fastscapelib_fortran.pyd.manifest" failed (exit code 1120) with the following output:
   Creating library _fastscapelib_fortran.lib and object _fastscapelib_fortran.exp
_fastscapelib_fortranmodule.c.obj : error LNK2019: unresolved external symbol f2pyinitfastscapecontext_ referenced in function f2py_init_fastscapecontext
_fastscapelib_fortranmodule.c.obj : error LNK2001: unresolved external symbol union_bn_
_fastscapelib_fortran.pyd : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: 'D:\T\fastscapelib-f2py-venv-37-x64\Lib\site-packages\cmake\data\bin\cmake.exe' :
eturn code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\1
.15.26726\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\1
.15.26726\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
Traceback (most recent call last):
  File "d:\t\scikit-build\skbuild\setuptools_wrap.py", line 589, in setup
    cmkr.make(make_args, env=env)
  File "d:\t\scikit-build\skbuild\cmaker.py", line 482, in make
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while building with CMake.
  Command:
    "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
  Source directory:
    D:\T\fastscapelib-fortran
  Working directory:
    D:\T\fastscapelib-fortran\_skbuild\win-amd64-3.7\cmake-build
Please see CMake's output for more information.
```

### the `union_bn` link error (fixed see below)

Reading though the code of scipy, I found this [code snippet](https://github.com/scipy/scipy/blob/be97f1a038ef6e3055cfbc83b9550492052ba76b/scipy/linalg/_cython_signature_generator.py#L46-L48):

```
def make_signature(filename):
    info = crackfortran.crackfortran(filename)[0]
    [...]
    # Eliminate strange variable naming that replaces rank with rank_bn.
    args = args.replace('rank_bn', 'rank')
return '{0} {1}({2})\n'.format(return_type, name, args)
```

the appending of `_bn` is done by `crackfortran` module (part of f2py), see [numpy/f2py/crackfortran.py#L250-L262](https://github.com/numpy/numpy/blob/4d51ffb70559653acb6c6c62959413bb9df31662/numpy/f2py/crackfortran.py#L250-L262)

I think the rational for this list is to avoid issues with c/c++ when a reserved keyword is used on the fortran side.

All that said, since union in a c++ keyword and not a C one, I tried to remove `union` from the list and that first link error is gone.

Note: This is an incremental progress and should not be considered the final solution. 

### unresolved external symbol f2pyinitfastscapecontex

I am not sure what is causing this one yet.

**Comment by benbovy** [comment]
> unresolved external symbol f2pyinitfastscapecontext_

FWIW:

- I've tried building only a simple fortran ``module`` (single f90 file) using the same configuration and it failed with the same error

- Still using the same configuration but removing all source related to the fortran module, it compiles without error

- I've successfully compiled the whole thing (module included) as a fortran static library using flang / clang-cl

Maybe there is something missing in the scikit-build's cmake modules used here to support fortran `.mod` files?

**Comment by jcfr** [comment]
### re: unresolved external symbol `f2pyinitfastscapecontext_` (fixed  see below)

This is now fixed in https://github.com/scikit-build/scikit-build/compare/master...jcfr:add-UseF2PY-and-UsePythonExtensions

```
[...]
[35/35] Linking Fortran shared module _fastscapelib_fortran.pyd
   Creating library _fastscapelib_fortran.lib and object _fastscapelib_fortran.exp
```

Note that removing `union` from [numpy/f2py/crackfortran.py#L250-L262](https://github.com/numpy/numpy/blob/4d51ffb70559653acb6c6c62959413bb9df31662/numpy/f2py/crackfortran.py#L250-L262) is still needed. I tried reverting the change .. but I get back a single link  error related to the `union_bn` symbol.

### import of fastscapelib_fortran

After copying the 3 libraries `flang.dll`, `flangrti.dll` and `libomp.dll` along side the python module, I was able to import the module.

This should **not** be needed  within the conda package because the environment will already include flang libraries.


image


```python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pprint import pprint as pp
>>> import fastscapelib_fortran as m
>>> pp(dir(m))
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_fastscapelib_fortran',
 'advect',
 'compute_basins',
 'connect_basins',
 'correct_receivers',
 'correct_receivers_v2',
 'diffusion',
 'distance_to_shore',
 'fastscape_copy_basement',
 'fastscape_copy_catchment',
 'fastscape_copy_chi',
 'fastscape_copy_drainage_area',
 'fastscape_copy_erosion_rate',
 'fastscape_copy_f',
 'fastscape_copy_h',
 'fastscape_copy_lake_depth',
 'fastscape_copy_total_erosion',
 'fastscape_debug',
 'fastscape_destroy',
 'fastscape_execute_step',
 'fastscape_get_fluxes',
 'fastscape_get_sizes',
 'fastscape_get_step',
 'fastscape_init',
 'fastscape_init_f',
 'fastscape_init_h',
 'fastscape_reset_cumulative_erosion',
 'fastscape_set_all_layers',
 'fastscape_set_basement',
 'fastscape_set_bc',
 'fastscape_set_dt',
 'fastscape_set_erosional_parameters',
 'fastscape_set_h',
 'fastscape_set_nx_ny',
 'fastscape_set_precip',
 'fastscape_set_u',
 'fastscape_set_v',
 'fastscape_set_xl_yl',
 'fastscape_setup',
 'fastscape_strati',
 'fastscape_view',
 'fastscape_vtk',
 'fastscapecontext',
 'find_mult_rec',
 'find_stack',
 'find_stack_recursively',
 'flexure',
 'four1',
 'loc_min_3_find_donors',
 'loc_min_3_find_receivers',
 'loc_min_3_find_stack',
 'loc_min_3_find_stack_recursively',
 'loc_min_3_indexx',
 'localminima',
 'mst_kruskal',
 'order_tree',
 'os',
 'platform',
 'realft',
 'sinft',
 'slope',
 'strati',
 'streampowerlaw',
 'sys',
 'tridag',
 'union',
 'unionfind',
 'unionfindinit',
 'update_fake_topography',
 'vocal',
 'vtk',
 'vtk_cube']
```

### next steps

* [ ] understand of the issue with  `union` symbol on windows. 
* [ ] finalize the integration of the `add-UseF2PY-and-UsePythonExtensions` topic in scikit-build. See https://github.com/scikit-build/scikit-build/compare/master...jcfr:add-UseF2PY-and-UsePythonExtensions
* [ ] finalize update of fastscapelib-fortran. See https://github.com/jcfr/fastscapelib-fortran/commits/2.7.0-python-module-support-flang

**Comment by benbovy** [comment]
This is great! I'm looking forward the next scikit-build release for this feature.

Regarding the `union` issue, there is actually a subroutine called `Union` in the fastscapelib library, which likely causes some conflict. I've renamed it and it solved the issue. This might not be a clean solution either, but as this is an  internal subroutine I don't mind renaming it, it's better than editing ``crackfortran.py` I think.

Many thanks @jcfr for all the work and the clear explanations!

**Comment by jcfr** [comment]
> I'm looking forward the next scikit-build release for this feature.

Will keep you posted.

> Regarding the union issue, there is actually a subroutine called Union in the fastscapelib library
> I don't mind renaming it

Good catch. 

Renaming makes sense, generally speaking, avoiding naming function after language keyword may be sensible.

**Pull request closed without merging**
