### PR TITLE
Remove --no-deps flag (fixed in conda-build 3.17.0)

### PR DESCRIPTION
**Pull request by bdice**
The temporary fix by @hajapy of adding `--no-deps` seems fixed with conda-build 3.17.0. This PR removes that flag and warning. I also fixed a few typos in the example recipe.

https://github.com/conda/conda-build/issues/3254
https://github.com/conda/conda-build/pull/3271

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge/staged-recipes, this PR is ready for review. Thanks!

**Comment by scopatz** [comment]
We aren't using conda-build 3.17 yet

**Comment by bdice** [comment]
@scopatz Oops, sorry about that! I'll check back later.

**Comment by chrisburr** [comment]
We're using conda-build 3.17 now so I think this can be merged?

**Comment by bdice** [comment]
@chrisburr Would you like me to merge in the current `conda-forge:master` and make sure this PR is up to date?

**Comment by chrisburr** [comment]
@bdice Yes please!

**Comment by bdice** [comment]
@chrisburr It's up to date now. Thanks!

**Comment by bdice** [comment]
@conda-forge/staged-recipes This PR should be ready to merge - let me know if I should do anything else. I know this repo is super busy. Thanks! 👍

**Comment by scopatz** [comment]
I am not sure this is needed any more.

**Comment by chrisburr** [comment]
This seems to work so LGTM. Thank you @bdice! 🍰

**Pull request merged**
