### PR TITLE
add libusb-package recipe

### PR DESCRIPTION
**Pull request by rudispr**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by rudispr** [comment]
@conda-forge-admin, please ping conda-forge/help-python
 Can you please review and merge if it's ok?

**Comment by rudispr** [comment]
@conda-forge-admin, please ping conda-forge/help-python
Could someone please have a look and merge if it's ok?

**Comment by rudispr** [comment]
@conda-forge-admin, please ping conda-forge/help-python

**Comment by rudispr** [comment]
@conda-forge-admin, please ping conda-forge/staged-recipes

**Comment by carterbox** [comment]
@ocefpaf, this package should not have been merged. It is revending @conda-forge/libusb, but doesn't include the license of libusb (which is a different license than this package).

**Comment by carterbox** [comment]
On further investigation, it seems that this build is different from the wheels on PYPI. It does not include a copy of `libusb.so`, it only includes the python functions to locate `libusb`, but then it should still be depending on `libusb` at runtime?

**Comment by rudispr** [comment]
@carterbox and @ryanvolz thanks for looking at the repo and apologies for any confusion. I was not aware that it was only going to help in locating an already existing libusb. I added it in the first place because another package I wanted to add (pyocd) had a dependency on libusb-package.

**Pull request merged**
