### PR TITLE
Add strawberryfields ecosystem

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge/help-python This would be ready for review, thanks!

**Comment by BastianZim** [comment]
Gentle ping here @conda-forge/staged-recipes

**Review by carterbox — CHANGES_REQUESTED** [review]
Please look at CI pipelines of the source repositories for each of these packages and implement their tests in the test section of the recipe. If the tests are not included in the pypi source distrbution, then switch to the GitHub source release.

https://conda-forge.org/docs/maintainer/adding_pkgs.html#test

**Comment by dopplershift** [comment]
@carterbox FYI, generally we don't require running the unit test suite for packages, because they can be long and require more dependencies (can create problems doing migrations later). Good import tests (where the imports actually pull in parts  of the package) and/or `pip check` is sufficient to validate that the package isn't broken. It's up to the discretion of the maintainers whether they want to do more.

**Comment by BastianZim** [comment]
Thanks for the suggestion @carterbox I agree that running the tests is generally good practice but as @dopplershift mentioned isn't always the best idea. Especially when the tests require additional dependencies which means that the `pip check` won‘t be able to accurately verify that all dependencies are installed. 
In the end, the conda-forge tests should only verify that the package is correctly built and installable. Whether the package itself is working should always be tested by upstream.

**Comment by dopplershift** [comment]
Interesting that our docs say:
> It is good to run some other tests of the code itself (the test suite) if possible.

But I almost never follow that. 🤷‍♂️ And honestly, I've seen that cause more problems with the 3.10 migration (introduces circular dependencies).

**Review by dopplershift — APPROVED** [review]

**Comment by BastianZim** [comment]
I'd say it definitely makes sense for heavier stuff like Tensorflow etc. but otherwise, it just produces problems (Have seen tests require Numpy quite often and then `pip check` missing that). I'll make a mental note to fix that. 

Thanks for merging!

**Comment by carterbox** [comment]
> verify that the package is correctly built

In this case, `thewalrus` is compiled by conda-forge and not by upstream, so I don't see how upstream would be responsible for ensuring that this build is working correctly. For the rest which are noarch, I can see how import tests may be sufficent.

> honestly, I've seen that cause more problems with the 3.10 migration
Then perhaps the documentation should change to reflect policy? 😄

**Comment by dopplershift** [comment]
I think it's generally been safe to verify compilation based on successful importation of the module. The place where running the test suite matters is if you think compilation options/versions can tweak math and only break numerical  results that tests would catch.

**Pull request merged**
