### PR TITLE
added ray recipe

### PR DESCRIPTION
**Pull request by Matt-BF**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by apcamargo** [comment]
@conda-forge/staged-recipes The `ray` recipe in bioconda is for a [genome assembler](http://denovoassembler.sourceforge.net/index.html), while this one is for a [Python package for distributed execution framework](https://github.com/ray-project/ray).

Should the name of this recipe be changed for something like `ray-py`?

**Comment by jakirkham** [comment]
Typically we have gone for something like `python-ray` in these cases.

**Comment by jakirkham** [comment]
Should add `ray` would be a welcome addition if you are still interested, @Matt-BF 🙂

**Comment by Matt-BF** [comment]
> Should add `ray` would be a welcome addition if you are still interested, @Matt-BF
Sure thing! I'll try it again soon

**Comment by Matt-BF** [comment]
#8163
Hi! I'm encountering some dificulties on building the package. It appears `setup.py` is inside a `python` folder, however, when passing this path, the build fails because it is trying to find `README.rst` one folder back instead of on the CWD

**Pull request closed without merging**
