### PR TITLE
Revert "NEW: Add default values for cuda_compiler on osx and windows"

### PR DESCRIPTION
**Pull request by beckermr**
Reverts conda-forge/staged-recipes#27547

### CODE REVIEW

**Comment by beckermr** [comment]
@carterbox can we push the fix from @isuruf to this PR?

**Comment by carterbox** [comment]
🤞🏼

**Comment by carterbox** [comment]
Apparently, I need to be even more agressive with the selectors?

**Comment by jakirkham** [comment]
Think this was due to a bug in conda-build 24.7, which has since been fixed in conda-build 24.9

More details in comment: https://github.com/conda-forge/staged-recipes/pull/27547#issuecomment-2372469699

Thank you all for working around these warts in my absence! 🙏

**Pull request merged**
