### PR TITLE
Add freeimage

### PR DESCRIPTION
**Pull request by jakirkham**
Builds on all platforms. Added from conda recipes. Made some minor tweaks to make it acceptable for conda forge.

### CODE REVIEW

**Comment by jakirkham** [comment]
@almarklein @msarahan @ccordoba12 @mutirri, interest in being added as maintainers?

**Comment by msarahan** [comment]
Sure.  @almarklein and I wrote a better recipe that is currently internal.  I'll add it to my list of stuff to migrate over.

**Comment by jakirkham** [comment]
Sounds cool. Should we add this first and then add your changes to it after it is a feedstock? Or would you rather we wait for the improvements?

**Comment by msarahan** [comment]
Go ahead with this.  I'll integrate it sometime soon.

**Comment by jakirkham** [comment]
Alright, sounds good. Thanks @msarahan.

**Comment by almarklein** [comment]
I'm also happy to keep an eye out for new versions of FI and update when necessary.

**Comment by jakirkham** [comment]
Added you to the maintainers, @almarklein.

**Comment by jakirkham** [comment]
Seems the Windows build fails on certain platforms. Anybody have any thoughts as to why this might be?

**Comment by almarklein** [comment]
@msarahan made several improvements to the Windows build. maybe just wait for that.

**Comment by pelson** [comment]
> @msarahan made several improvements to the Windows build. maybe just wait for that.

Or for the time being, perhaps we can just skip the failing cases and fix in the feedstock itself?

**Comment by jakirkham** [comment]
I have temporarily removed the Windows portion so we can get the Linux and Mac portions deployed. The Windows portions can be PR'd to the feedstock when they are ready.

**Comment by jakirkham** [comment]
Passing. :)

**Comment by jakirkham** [comment]
Thanks everyone.

**Pull request merged**
