### PR TITLE
Add a recipe for make

### PR DESCRIPTION
**Pull request by asmeurer**
@scopatz I'm making you a recipe maintainer. 

I'm allowing "edit for maintainers" for the PR so feel free to push up fixes.

### CODE REVIEW

**Comment by asmeurer** [comment]
Looks like a linter bug (fails when you use the wrong key).

**Comment by asmeurer** [comment]
Seems to have worked. Don't know if you want to add a more extensive test to the recipe.

**Comment by jakirkham** [comment]
Wow! We are really going to the bottom of the stack. Just curious, do you have special use cases for a `conda` package of `make` or is this more an attempt to package the world? FWIW I'm ok with it.

We probably should run `make check` since it is `make`.

**Comment by asmeurer** [comment]
Ah, I tried `make test` but that didn't work. Didn't realize it was `make check`.

**Comment by scopatz** [comment]
@jakirkham we ran into a situation today where we the default debian docker container doesn't come with make.  @asmeurer realized it would be easy to make a package for :)

**Comment by asmeurer** [comment]
I'm surprised I've never built it before. And yes, I do want to package everything (or at least everything that I would ever want to install).

**Comment by scopatz** [comment]
Thanks @asmeurer!

**Pull request merged**
