### PR TITLE
add pynmeagps package

### PR DESCRIPTION
**Pull request by semuadmin**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by semuadmin** [comment]
@conda-forge/help-python

I am unclear why this recipe is failing on the osx installation test but succeeding on linux and windows - the package installs perfectly on all MacOS Intel and Apple platforms from 11 onwards using pip. I can find no obvious resolution in the KB.

```
  File "/Users/runner/mambaforge/lib/python3.10/site-packages/boa/core/solver.py", line 80, in to_action
    entry = lookup_dict[get_url_from_channel(c)]
KeyError: 'https://conda.anaconda.org/conda-forge'
##[error]Bash exited with code '1'.
Finishing: Run OSX build
```

**Comment by synapticarbors** [comment]
I'm not sure what's going on there. I'm re-runing the osx CI just to see if it was a transient issue.

**Comment by semuadmin** [comment]
> I'm not sure what's going on there. I'm re-runing the osx CI just to see if it was a transient issue.

apparently not :-( ???

**Comment by mikemhenry** [comment]
Seeing the same issue here: https://github.com/conda-forge/staged-recipes/pull/23919

**Comment by mikemhenry** [comment]
And like ~5 others I checked so it looks like an issue with staged-recipes

**Comment by semuadmin** [comment]
@conda-forge/help-python, ready for review!

I can confirm that I am the maintainer of the GitHub repo and am happy to be the feedstock maintainer for this Conda package.

**Comment by semuadmin** [comment]
@conda-forge-admin @conda-forge/python - I've had two staged-recipes PRs merged earlier today (package names `pynmeagps` and `pyrtcm`) but I've only received notification of the `pyrtcm` feedstock? Is there any particular reason why `pynmeagps` is not yet available as a feedstock?

**Pull request merged**
