### PR TITLE
Add airflow-provider-great-expectations

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @xylar I see you have done most of the Airflow Providers. Could you help with a few clarifications. 
1) Looking at your prior work, it seems its ok to have windows failing but having a noarch package is preferred. 
https://github.com/conda-forge/staged-recipes/pull/18479
2) The PiP package and Github Repo are called airflow-provider-great-expectations, should I keep the same name for the conda package - or make it consistent to rest of Apache-Airflow-Providers-<> and rename the Conda package to be "apache-airflow-providers-great-expectations"
i.e. add prefix of Apache and change from provider to provider(s)

**Comment by xylar** [comment]
@rxm7706, it seems like this is not one of the official Airflow providers from Apache, so I think it is appropriate to keep the same name as on PyPI.  Note that it is also named "provider" instead of "providers".

Yes, it is expected that windows builds fail (because Airflow itself doesn't support Windows, at least not on conda-forge).  And, yes, the package should be `noarch: python` as you have it.

**Comment by rxm7706** [comment]
@conda-forge-help-python, this is ready to review. The Windows failures are expected because apache-airflow doesn't support Windows.

**Comment by rxm7706** [comment]
@conda-forge/staged-recipes  ready for review

**Comment by xylar** [comment]
@rxm7706, let me know if you run into any trouble or need help maintaining this package.

**Comment by rxm7706** [comment]
> @rxm7706, let me know if you run into any trouble or need help maintaining this package.

@xylar Would love to have the help. I will add you to the feed stock.

**Pull request merged**
