### PR TITLE
Added recipe for census

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Fixed builds of `us`, trying again.

**Comment by pmlandwehr** [comment]
one more try...

**Comment by pmlandwehr** [comment]
Hmm, I don't get it. Once more...

**Comment by jakirkham** [comment]
Think it was just `us` not being built on Linux. Appears that is now addressed. Restarting the CI has corrected this issue.

**Comment by jakirkham** [comment]
Thanks @pmlandwehr.

**Pull request merged**
