### PR TITLE
Add `python-graphblas` (renamed from `grblas`)

### PR DESCRIPTION
**Pull request by eriknw**
We have renamed `grblas` to `python-graphblas`, and I think it's probably easiest/cleanest to make a new feedstock.  This recipe was copied and modified from:
- https://github.com/conda-forge/grblas-feedstock

Question: should we do anything with `grblas-feedstock`?

@jim22k, please confirm that you are willing to be a maintainer.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by eriknw** [comment]
@jakirkham is there any common practice for renaming packages?  Other than this question, I think this PR should be quick to review/merge.

**Comment by jakirkham** [comment]
Sure we can add this and archive the existing feedstock

cc @conda-forge/core (in case others have thoughts on this)

**Comment by eriknw** [comment]
Thanks conda-forge linter!  That's 'cause I got impatient and released `python-graphblas` via the `grblas` feedstock.

I bumped the build number on this PR so as to not conflict, and I'm still happy to merge this to have a feedstock where everything is named "python-graphblas".  Or I could try renaming things manually.  No strong preference.

**Comment by jakirkham** [comment]
@conda-forge/core, is there anything else we need to do here? 🙂

**Pull request merged**
