### PR TITLE
add mpl-template

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Pending https://github.com/austinorr/mpl-template/issues/10

**Comment by ocefpaf** [comment]
> @ocefpaf Re: other checklist items -> are there other items on this checklist that are incomplete and require my attention, besides the license file?

Nope. I was just lazy and did not check those. Don't worry about them.

**Comment by austinorr** [comment]
Ok great, and thanks again! Please reach out if there's anything else I can do to support this.

**Comment by ocefpaf** [comment]
> if there's anything else I can do to support this.

If you want I can add you as a maintainer for this recipe. We have a bot that fetches new releases and creates pull request to update the package here.  As a maintainer you would be able to review that PR and merge it.

**Comment by ocefpaf** [comment]
@conda-forge/staged-recipes this one is ready for review!

**Comment by austinorr** [comment]
@ocefpaf I’d be happy to help maintain this recipe. I’ve never dealt with conda-forge recipes before, so I look forward to learning. Thanks again!

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
