### PR TITLE
Add recipe for OMSimulator

### PR DESCRIPTION
**Pull request by thealanjason**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by thealanjason** [comment]
@conda-forge/help-python-c  @conda-forge/help-python 
I'm having issues with [/lib64/libdl.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=877279&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=971) and many similar errors. 
Any help is appreciated, since I'm new to building conda-recipes. 
I have used `grayskull` to build this recipe from a pypi project.

**Comment by ocefpaf** [comment]
@thealanjason  this package source distribution is empty. You can test that by installing with from PyPI with pip in a fresh environment. The acutal package files are missing:

```
 4.0K Nov 25  2022 OMSimulator.egg-info/
  621 Nov 25  2022 PKG-INFO
  245 Nov 25  2022 README.md
   38 Nov 25  2022 setup.cfg
 5.7K Nov 25  2022 setup.py

./OMSimulator.egg-info:
total 24K
   1 Nov 25  2022 dependency_links.txt
   1 Nov 25  2022 not-zip-safe
 621 Nov 25  2022 PKG-INFO
   9 Nov 25  2022 requires.txt
 226 Nov 25  2022 SOURCES.txt
  12 Nov 25  2022 top_level.txt
```

Please report it upstream, there is nothing we can do without the source code.

**Comment by thealanjason** [comment]
@ocefpaf Thank you for the quick response. I understand your concern. However, if you look at the contents of `setup.py` [here](https://github.com/OpenModelica/OMSimulator/blob/c66d7124d32b8902abe74c09896c0c506c129a3b/src/pip/setup.py#L71C1-L87C1), the pre-compiled binaries and libraries are downloaded based on the platform. So I'm thinking that by running the `setup.py` during installation, the necessary libraries would be present in the necessary folders. I base this assumption on the passing build on [MacOS](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_build/results?buildId=877279&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7)
Would it just help if I add these libraries to the `missing_dso_whitelist`?

**Comment by ocefpaf** [comment]
> However, if you look at the contents of setup.py here, the pre-compiled binaries and libraries are downloaded based on the platform

Ouch. That is a big no-no in packaging. Repackaging is ok in rare occasions but it should be explicit!

**Comment by thealanjason** [comment]
Would I then have to check the licenses of the offending libraries, and see if the source need to be shipped with the binaries? When not need to ship source, would it then be enough to add the License files of these dependencies to this package?

Sorry if my questions are very naive, I'm new to this world of conda-forge and packaging in general.

**Comment by ocefpaf** [comment]
> Sorry if my questions are very naive, I'm new to this world of conda-forge and packaging in general.

I'm not a lawyer and I cannot recommend anyting on the license stuff. All I can say is that they "may" be infringing a license if that license demandas the source to be shipped as well. With that said, regardless of the license, downloading a binary from a 3rd party source at install time is not OK and we cannot ship that package unless you figure out a way to build everything from source.

**Pull request closed without merging**
