### PR TITLE
Readd ipdb

### PR DESCRIPTION
**Pull request by sannykr**
I am readding the recipe to get a new token in the feedstock. This is the link that is relevant:
https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876

### CODE REVIEW

**Comment by sannykr** [comment]
@jakirkham: I have added the same recipe that is on feedstock. Could you please review merge.

**Comment by sannykr** [comment]
@mwcraig: Could you please review and merge.

**Comment by sannykr** [comment]
@mwcraig : I can't see the python 3.6 build for linux on conda-forge. Is it possible to retrigger the build?

**Comment by mwcraig** [comment]
restarted it, not sure what the issue was...

**Pull request merged**
