### PR TITLE
added r-pscbs

### PR DESCRIPTION
**Pull request by MathiasHaudgaard**

### CODE REVIEW

**Comment by MathiasHaudgaard** [comment]
The two dependencies missing are in the bioconda repo. I'm not sure if I should put the two dependencies on conda-forge?

**Comment by MathiasHaudgaard** [comment]
@bgruening 
This package fails because it depends on two packages from bioconductor. Should I put this package on bioconda instead?

**Comment by bgruening** [comment]
Yes please :)

**Comment by MathiasHaudgaard** [comment]
Oh it's already on bioconda. 🤐

**Pull request closed without merging**
