### PR TITLE
Add DBAdapter

### PR DESCRIPTION
**Pull request by synapticarbors**
This is an open sourced subset of the functionality of IOPro. There is no official release so unfortunately I'm building from a git revision.

### CODE REVIEW

**Comment by synapticarbors** [comment]
I think I might need some assistance from @conda-forge/help-python-c on this PR for DBAdapter.

**Comment by synapticarbors** [comment]
Addresses #8133

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes I'm having a difficult time understanding exactly what the error is for the one failing CI build. Any suggestions would be most appreciated.

**Comment by scopatz** [comment]
It looks like it is not linking in numpy properly

**Comment by synapticarbors** [comment]
I switched over to using a release tarball from github and it looks like conda is failing on Windows due to a symbolic link that doesn't resolve to a real file (`docs/release-notes.rst`):

```
Processing c:\bld\dbadapter_1560879832598\work
  Created temporary directory: c:\users\appveyor\appdata\local\temp\1\pip-req-build-mpurzp
ERROR: Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\site-packages\pip\_internal\commands\install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\site-packages\pip\_internal\operations\prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\site-packages\pip\_internal\download.py", line 873, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\site-packages\pip\_internal\download.py", line 778, in unpack_file_url
    shutil.copytree(link_path, location, symlinks=True)
  File "C:\bld\dbadapter_1560879832598\_h_env\lib\shutil.py", line 222, in copytree
    raise Error, errors
Error: [('C:\\bld\\dbadapter_1560879832598\\work\\docs\\release-notes.rst', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-mpurzp\\docs\\release-notes.rst', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\dbadapter_1560879832598\\\\work\\\\docs\\\\release-notes.rst'")]
```

What's the best way to work around this?

Also, I'm still not sure what the numpy linking issue is on linux. Thoughts on how to debug that would be appreciated.

**Comment by scopatz** [comment]
Does this package support windows? If so maybe copy the file over from its symlinked location (or patch the refernce to it)

**Comment by synapticarbors** [comment]
It should support windows. I guess maybe it's easiest to make a windows-specific override to just delete that file. I'll give that a try

**Pull request closed without merging**
