### PR TITLE
Add asdf to conda-forge

### PR DESCRIPTION
**Pull request by mwcraig**
@drdavella  -- are you OK with being listed as a maintainer here? Builds on conda-forge will be used to populate the astropy conda channel in the future. Being a maintainer doesn't require much, just updating the version and checksum when a new release is made.

bsipocz agreed on another PR to be maintainer.

### CODE REVIEW

**Comment by drdavella** [comment]
Yes that's fine with me. Will I be notified when I need to make an update?

**Comment by mwcraig** [comment]
Updates will only be needed when you make a new release of asdf, and can be done at any point after you have uploaded a new release to PyPI.

Once this recipe is merged here a new github repo called https://github.com/conda-forge/asdf-feedstock with administrative rights for everyone listed as a maintainer in the recipe. That is the repo on which a PR should be opened when a new version of asdf is released. 

@bsipocz and I will help with this, but if you could add it your list of to-dos after you make a new release that would be great!

**Comment by bsipocz** [comment]
btw @mwcraig is there a tool you use to create these recipes (e.g. extruder), or simply start of the example one?

**Comment by mwcraig** [comment]
@bsipocz -- `conda skeleton pypi` now generates `meta.yaml` files that are ready for adding to conda-forge (except for adding maintainers and maybe cleaning up other metadata in the about section). Works with Python 3.6 (ordered `dict`s)  + conda build > 3.0.7.

I'm in the car for another ~6 hours today, should get through the rest of the astropy channel.

**Pull request merged**
