### PR TITLE
Add rb-iruby

### PR DESCRIPTION
**Pull request by kozo2**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by sodre** [comment]
@kozo2, we only need the runtime dependencies for the gem packages. According to [ruby gems](https://rubygems.org/gems/iruby), they should be:
- bond ~> 0.5
- data_uri ~> 0.1
- mimemagic ~> 0.3
- multi_json ~> 1.11

**Comment by kozo2** [comment]
@sodre Thank you for your comment.
That means we need to create
- rb-bond
- rb-data_uri
- rb-mimemagic
- rb-multi_json
conda packages. Right?

**Comment by sodre** [comment]
@kozo2, that is correct. My suggestion is to start with sample recipe from #9320 when building the dependencies. 

Let me know if you get stuck!

**Comment by sodre** [comment]
@kozo2, It will probably take 30minutes-1hour for the packages to propagate to Anaconda's CDN, once that is done we should be able to restart this build.

**Comment by kozo2** [comment]
@sodre I'm sorry, could you please wait for this merge to conda-forge a little?
It seems that `iruby` needs zeromq adapter(cztop or ffi-rzmq) for RUNTIME DEPENDENCIES.
It seems that `iruby` maintainers want to make it selectable.
So the zeromq adapter for `iruby` is not in RUNTIME DEPENDENCIES.
Could you give me some time to negotiate with them (to add ffi-rzmq to RUNTIME DEPENDENCIES)?

**Comment by sodre** [comment]
Of course! Just ping me when the recipe is ready for review.

**Comment by kozo2** [comment]
Sorry @sodre . `iruby` maintainer denied to change their code (==iruby.gemspec) for conda-forge packaging. I close this issue once.

**Comment by bgruening** [comment]
@kozo2 you can apply a patch as part of this recipe if you like. iruby would be nice to have in conda-forge imho.

**Comment by sodre** [comment]
@kozo2, I can help you get the recipe fixed if you are still interested. In particular, conda allows us to add runtime dependencies that are not necessarily in the gem itself. 

When I mentioned to you earlier that we usually only need the gem's runtime deps, it was because I was trying to avoid you from packaging developer dependencies for all the ruby dependencies, because that would be a lot of work.

**Comment by kozo2** [comment]
@sodre Yes, I'm still interested.
I would like to know how to add runtime dependencies that are not necessarily in the gem itself.

**Comment by bgruening** [comment]
@kozo2 you can simply add then under the `run` section.

**Pull request closed without merging**
