### PR TITLE
Run `setup_conda_rc` as part of all builds

### PR DESCRIPTION
**Pull request by jakirkham**
This was already being handled for macOS (see below). Here we handle the rest of the platforms.

https://github.com/conda-forge/staged-recipes/blob/1a5216f73723c2318566e96c3cca61fa78e37543/.azure-pipelines/azure-pipelines-osx.yml#L42

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge/core @conda-forge/staged-recipes, could you please take a look?

**Comment by CJ-Wright** [comment]
seems reasonable to me, although I may not be a great judge.

**Comment by jakirkham** [comment]
AFAICT `setup_conda_rc` is just adding channels based on those in the config in `.ci_support`. So should be ok I think. Just found it odd we were only running this on macOS here.

**Comment by beckermr** [comment]
Yep. A lot fo the staged-recipes tooling is very ad hoc and not very well maintained. I made a new issues to discuss how we can clean some of this up. #9869

**Comment by isuruf** [comment]
This is not necessary as the important part is done in https://github.com/conda-forge/staged-recipes/blob/46ccb39288b02dbaa2e617ca74e7f723bfc35ea9/.ci_support/build_all.py#L63

**Comment by jakirkham** [comment]
Wouldn't it be better to have this handled in a consistent manner as with the feedstocks? It seems like we can avoid extra maintenance burden by keeping them more closely aligned. 🙂

**Comment by scopatz** [comment]
Let's move ahead with this PR while we also have the other discussion about how to improve staged-recipes over all

**Comment by isuruf** [comment]
> Wouldn't it be better to have this handled in a consistent manner as with the feedstocks?

No. We allow to change the channels in the feedstocks and we have to do that per recipe.

**Pull request merged**
