### PR TITLE
Add aws xray sdk

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge/help-python Would be ready for review, thanks!

**Review by mariusvniekerk — CHANGES_REQUESTED** [review]
we already have https://github.com/conda-forge/aws-xray-sdk-feedstock

**Comment by mariusvniekerk** [comment]
Can you make that as a PR on that repo and ping me?

**Comment by BastianZim** [comment]
Ahh sorry, should have searched more thoroughly. On a side note, doesn't the linter normally catch that, or is that only for bioconda similarity?

**Comment by BastianZim** [comment]
> Can you make that as a PR on that repo and ping me?

Will do, would you like me to add myself as a maintainer? Just to merge future versions.

**Comment by mariusvniekerk** [comment]
@BastianZim that would be fantastic!

**Comment by mariusvniekerk** [comment]
As for the linter, might only be a bioconda thing, but likely makes sense for conda-forge as well at this point.

**Comment by BastianZim** [comment]
> As for the linter, might only be a bioconda thing, but likely makes sense for conda-forge as well at this point.

Ahh ok. Should I create an issue for that? Not sure if I can do a full PR...?

**Comment by BastianZim** [comment]
@mariusvniekerk PR has been created at https://github.com/conda-forge/aws-xray-sdk-feedstock/pull/5

**Comment by BastianZim** [comment]
> On a side note, doesn't the linter normally catch that, or is that only for bioconda similarity?

Hmm, should've actually been caught, not sure what went wrong there.

https://github.com/conda-forge/conda-smithy/blob/6eef64fe666f706e39dfe2409773303062b88fde/conda_smithy/lint_recipe.py#L699-L727

**Pull request closed without merging**
