### PR TITLE
pandas-plink

### PR DESCRIPTION
**Pull request by Horta**

### CODE REVIEW

**Comment by Horta** [comment]
Please, someone help me.

Not matter what I do I cannot get libffi.so.6 visible to my package:

`+ python setup.py install --single-version-externally-managed --record record.txt
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    setup_package()
  File "setup.py", line 56, in setup_package
    setup(**metadata)
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/site-packages/setuptools/dist.py", line 318, in __init__
    _Distribution.__init__(self, attrs)
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/site-packages/setuptools/dist.py", line 376, in finalize_options
    ep.load()(self, ep.name, value)
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/site-packages/cffi/setuptools_ext.py", line 187, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "bed_reader_build.py", line 3, in <module>
    ffibuilder = FFI()
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/site-packages/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
Command failed: /bin/bash -x -e /staged-recipes/build_artefacts/work/pandas_plink-1.0.6rc12/conda_build.sh

./scripts/run_docker_build.sh returned exit code 1`

**Comment by Horta** [comment]
I'm lost :/

**Comment by jakirkham** [comment]
Should this be closed in favor of PR ( https://github.com/conda-forge/staged-recipes/pull/2045 )?

**Comment by Horta** [comment]
Yes, please. @jakirkham would you mind having a look at ci/circleci outpus? It looks like
there must be wrong with conda-smithy: my package works for the first python version that the ci/circle build (it can see the libffi.so.6), but does not work for the others I try. And it is not about python version, it is about trying to build my package for more than one python version in the same ci/circle session.

**Comment by Horta** [comment]
In other words, #2045 only passed the tests because I selected a single python version for ci/circleci specifically because of this bug. I'm 100% sure that my packages works for py27, py34, and py35.

**Pull request closed without merging**
