### PR TITLE
ENH add sacc

### PR DESCRIPTION
**Pull request by beckermr**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

I have made a PR for putting the license file in the sdist here https://github.com/LSSTDESC/sacc/pull/39

### CODE REVIEW

**Comment by beckermr** [comment]
Alright @conda-forge/staged-recipes This one is ready to merge! A straight forward noarch python recipe.

**Comment by beckermr** [comment]
Alright @conda-forge/staged-recipes This one is ready to merge! A straight forward noarch python recipe.

**Comment by npavlovikj** [comment]
@beckermr , should the AppVeyor error be ignored?

**Comment by beckermr** [comment]
Yup. This is  noarch:python so only linux has to pass.

**Comment by beckermr** [comment]
We good to merge @npavlovikj ?

**Comment by npavlovikj** [comment]
Thanks @beckermr  - both for the PR and the AppVeyor clarification :)

**Pull request merged**
