### PR TITLE
Add thinkx

### PR DESCRIPTION
**Pull request by koverholt**
@AllenDowney, would you like me to add you as a recipe maintainer here (in addition to myself)? If not, I'm happy to be the maintainer for this recipe.

### CODE REVIEW

**Comment by patricksnape** [comment]
@pelson What is the linter on about with all those recipes?

**Comment by koverholt** [comment]
I seem to have synced my fork after those recipes were merged but before they were moved out. Hopefully that doesn't cause any issues.

**Comment by patricksnape** [comment]
It shouldn't be a problem, unlucky that you hit that exact gap!

**Comment by jakirkham** [comment]
If you want to clean up a bit, feel free to rebase on or merge with `conda-forge/master`.

**Comment by koverholt** [comment]
Thanks! Rebased.

**Comment by AllenDowney** [comment]
@koverholt No need to make me a maintainer for now.  Thanks very much for your help with this!

**Comment by koverholt** [comment]
@AllenDowney, got it. Thanks for the package and the great books!

**Comment by jakirkham** [comment]
LGTM.

**Comment by jakirkham** [comment]
Thanks @koverholt.

**Pull request merged**
