### PR TITLE
Add latest javabridge recipe

### PR DESCRIPTION
**Pull request by drpatelh**
Adding the latest version of `javabridge` due to incompatibility issues with `openjdk`. See
https://github.com/bioconda/bioconda-recipes/pull/13430

The recipe was generated with:
```
conda skeleton pypi javabridge
```

### CODE REVIEW

**Comment by drpatelh** [comment]
@conda-forge/help-java HELP! I have drawn a blank with this PR after making a number of changes to the recipe - some of which may not be necessary. I dont think the `openjdk` addition has made a difference to the tests. I suspect this may require some environment variables to be set but I only really have experience of working with Linux installations. Any advice is more that welcome.

**Comment by mariusvniekerk** [comment]
The osx failure looks like a real one?

**Comment by drpatelh** [comment]
> 
> 
> The osx failure looks like a real one?

Thanks for helping @mariusvniekerk . To be honest, I dont know! This is my first recipe and I havent really installed anything on macosx or windows. Not sure why it cant be imported...

Does the recipe look ok to you?

These are the installation instructions for the package:
https://pythonhosted.org/javabridge/installation.html#install-using-pip

**Comment by chrisburr** [comment]
I haven't made any progress with fixing it but it only happens with conda's build of Python and is easily reproducible outside of `conda-build`. Searching around it looks like it's a common issue but I didn't find a solution.

Steps to reproduce locally outside `conda-build`:
```bash
conda create --name debug-javabridge python=3.7 openjdk
export JAVA_HOME=$CONDA_PREFIX
export JDK_HOME=$CONDA_PREFIX
python -m pip install --no-cache javabridge
python -c 'import javabridge'
```
The error shown when importing is:
```bash
Could not find Java JRE compatible with x86_64 architecture
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$CONDA_PREFIX/lib/python3.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "$CONDA_PREFIX/lib/python3.7/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen($CONDA_PREFIX/lib/python3.7/site-packages/javabridge/_javabridge.cpython-37m-darwin.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: $CONDA_PREFIX/lib/python3.7/site-packages/javabridge/_javabridge.cpython-37m-darwin.so
  Expected in: flat namespace
 in $CONDA_PREFIX/lib/python3.7/site-packages/javabridge/_javabridge.cpython-37m-darwin.so
```

**Comment by drpatelh** [comment]
> ```shell
> debug-javabridge
> ```

Thanks @chrisburr .  I also found this post in the link you sent which suggests that it may be a conda issue:
https://github.com/LeeKamentsky/python-javabridge/issues/136

This is as far as I can get with the build and tests working properly on linux. 

@dpryan79 Sorry to pull you in on this but would you have any suggestions? Any other options to get the build below to work?
https://github.com/bioconda/bioconda-recipes/pull/13430

**Comment by dpryan79** [comment]
@drpatelh No suggestions from me, I don't pretend to know why Cython is doing this under OSX.

**Comment by chrisburr** [comment]
There is an issue with the `setup.py` that is causing the compiler arguments to be detected incorrectly. This patch below is enough to workaround the issue but someone should look into why `-framework CoreFoundation` isn't being added automatically despite it being printed if I run `python3.6-config --ldflags`, see [here](https://docs.python.org/3/extending/embedding.html#embedding-python-in-c).

```patch
diff --git a/setup.py b/setup.py
index 10f8908..30e59b9 100644
--- a/setup.py
+++ b/setup.py
@@ -268,7 +268,7 @@ class build_ext(_build_ext):
             library_dirs=library_dirs,
            libraries=libraries,
             export_symbols=export_symbols,
-            extra_postargs=extra_postargs)
+            extra_postargs=extra_postargs+['-framework', 'CoreFoundation'])
         if needs_manifest:
             temp_dir = os.path.dirname(objects[0])
             manifest_name = lib_name +".manifest"
```

**Comment by drpatelh** [comment]
@chrisburr I added the patch but its till failing. Due to these lines?

https://github.com/LeeKamentsky/python-javabridge/blob/ba5232911b4695b620a7843cd6d66bfbab20cf7f/setup.py#L260-L261

Would the patch require some OSX specific definition of `needs_manifest`?

**Comment by chrisburr** [comment]
@drpatelh I suggest discussing it upstream as this is a bug in their install process that keeps coming up:
 * https://github.com/LeeKamentsky/python-javabridge/issues/111
 * https://github.com/LeeKamentsky/python-javabridge/issues/136
 * https://github.com/LeeKamentsky/python-javabridge/issues/143
 * https://github.com/LeeKamentsky/python-javabridge/issues/151

Hopefully these comments (https://github.com/conda-forge/staged-recipes/pull/7701#issuecomment-460980889 https://github.com/conda-forge/staged-recipes/pull/7701#issuecomment-460980889) are enough for them to figure how what needs to be done to fix it properly. I think the issue is ultimately that conda's macOS `python` binaries are statically linked.

For hackily fixing the recipe, editing the this variation of the patch _might_ work provided it's only applied for `macOS`:

```diff
diff --git a/setup.py b/setup.py
index 10f8908..30e59b9 100644
--- a/setup.py
+++ b/setup.py
@@ -268,7 +268,7 @@ class build_ext(_build_ext):
             library_dirs=library_dirs,
            libraries=libraries,
             export_symbols=export_symbols,
-            extra_postargs=extra_postargs)
+            extra_postargs=['-framework', 'CoreFoundation'])
         if needs_manifest:
             temp_dir = os.path.dirname(objects[0])
             manifest_name = lib_name +".manifest"
```

**Comment by drpatelh** [comment]
@LeeKamentsky would you mind having a look at this please? 

This all came about by my need to update `CellProfiler` in Anaconda. Also, there currently isnt a version on `bioconda`.

Thanks in advance.

**Comment by LeeKamentsky** [comment]
Unfortunately, I don't have a Mac. I may be able to get this working by branching, pushing tentative changes and checking the results in Travis, but if anyone is both motivated and has a Mac, they may be in a better position to fix this.

**Comment by drpatelh** [comment]
Thanks @LeeKamentsky . Unfortunately, I dont have any experience with OSX either, or Windows for that matter. I got the linux build working!

If you have any immediate suggestions or lightbulb moments I dont mind giving them a go here.

Failing some OSX help, this seems like quite a frustrating dead end...

**Comment by LeeKamentsky** [comment]
I have a change to the setup.py.patch file here:
https://github.com/LeeKamentsky/staged-recipes/blob/javabridge/recipes/javabridge/setup.py.patch

I am not sure whether I should be creating my own PR to trigger the build process.

**Comment by drpatelh** [comment]
Amazing! Thanks. Ive replaced the old patch with your suggestion and triggered the build. Are you able to edit the files in this PR? If so, I have no problem with you doing this if it helps to get things working. I suspect it will involve little tweaks here or there.

**Comment by drpatelh** [comment]
Im closing this PR because this is more of a low-level issue with the way `java` is found during the build. Found another solution to build the `Cellprofiler` `conda` environment.

**Comment by bgruening** [comment]
> Im closing this PR because this is more of a low-level issue with the way java is found during the build. Found another solution to build the Cellprofiler conda environment.

There is some interest in getting Cellprofiler in to conda-forge. Are you also still interested in this?

**Comment by LeeKamentsky** [comment]
I'm the wrong person to ask - I'm no longer affiliated with CellProfiler. You should contact their team at https://cellprofiler.org/

**Pull request closed without merging**
