### PR TITLE
Example of new AppVeyor setup **DO NOT MERGE**

### PR DESCRIPTION
**Pull request by jjhelmus**
Just for demonstration of the new features of PR #19

### CODE REVIEW

**Comment by jjhelmus** [comment]
[AppVeyor Results](https://ci.appveyor.com/project/pelson/staged-recipes/build/1.0.79) 

[Sample Artifacts](https://ci.appveyor.com/project/pelson/staged-recipes/build/1.0.79/job/b0io9j9gvaij63co/artifacts)

**Comment by pelson** [comment]
:+1: - just wondering if you have a plan for the build artefacts? Obviously they are also going to anaconda.org, so I don't want to put unnecessary strain on AppVeyor if we don't need to.

**Comment by jjhelmus** [comment]
The build artifacts would be for testing and instance gratification as @danielballan mentioned.  Also I wanted to see if it could be done.  This can be made optional to reduce the strain on AppVeyor but leaving the commented lines in the yaml file probably would make sense so that it can easily be turned back on.

**Comment by pelson** [comment]
Merged as part of #19 and #15 I think. I'll close this then - re-open if I'm wrong. :+1:

**Pull request closed without merging**
