### PR TITLE
readd libhdfs3 [ci ckip] [skip ci]

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by isuruf** [comment]
Recipe should be in `recipes` folder, not in the root of the repo.

**Comment by martindurant** [comment]
Sorry @isuruf - is it best for me to do this again?

**Comment by ocefpaf** [comment]
No problem @martindurant (we all did that at some point :smile: )

I already fixed it. Don't worry.

**Comment by martindurant** [comment]
Thank you, @ocefpaf ! Is that also true for hdfs3?

**Comment by ocefpaf** [comment]
> Is that also true for hdfs3?

Yep.

**Pull request merged**
