### PR TITLE
Added recipe for libdynd

### PR DESCRIPTION
**Pull request by izaid**
DyND is a C++ library for dynamic, multidimensional arrays. It is inspired by NumPy, the Python array programming library at the core of the scientific Python stack, but tries to address a number of obstacles encountered by some of its users. Examples of this are support for variable-sized string, ragged array types, and convenient usage from C++. 

See www.libdynd.org

### CODE REVIEW

**Comment by izaid** [comment]
Alright, so I would love to get DyND's conda packages building in the conda-forge toolchain. This is also a pretty good stress chain for conda-forge as we use pretty much modern everything.

**Comment by izaid** [comment]
First obstacle encountered: DyND needs GCC 4.9 or greater. I'm only picking up GCC 4.8 on Circle CI. See https://circleci.com/gh/conda-forge/staged-recipes/6085

cc @msarahan @conda-forge/core @wesm @njsmith @insertinterestingnamehere @mwiebe

**Comment by izaid** [comment]
Should I be using a gcc from conda? Is there a gcc >=4.9 available?

**Comment by jakirkham** [comment]
Hi @izaid, so we are aware of this issue and it has been under discussion for awhile actually. A few weeks back we came to the conclusion that we should package a modern version of `gcc`. See this PR ( https://github.com/conda-forge/staged-recipes/pull/873 ). Until that is done it might be best to hold on this.

Though if you are very eager to get in we could discuss using `devtoolset-4` in the Docker image, which would work for you. Also, we are using XCode 6 on OS X, which I believe should has C++14 support, but may require a flag to enable it. The real trick is Visual Studio. It appears the VS 2015 has incomplete C++14 [support]( https://msdn.microsoft.com/en-us/library/hh567368.aspx#cpp14table ). So, I'm not sure how well that will work.

**Comment by izaid** [comment]
@jakirkham I think my real question here is *how* does conda-forge want me to build DyND? Over at www.github.com/libdynd/libdynd, we've got DyND building perfectly fine on Travis CI (with OS X) and Appveyor. So I can tell you what we needed to do to overcome these issues.

Would it be better get the right compilers on Travis CI / Circle CI / Appveyor (which we already know how to do) or hold off until the modern gcc is available?

**Comment by jakirkham** [comment]
I think our long term plan is to build `gcc`.

However, personally I have no problem adding `devtoolset-4`, which should have no other effect than to get this to build. Though there may need to be some discussion on that point.

OTOH these things can be done now. Mac is really just a matter of following what was added in this PR ( https://github.com/conda-forge/thrift-cpp-feedstock/pull/4 ) and tacking on `-std=c++14` in the `CXXFLAGS`. I simply don't know whether VS will work for you or not, but if it will then adding `skip: true # [win and not py35]` should do the trick of putting you on VS 2015. Also will need `python` in `requirements/build` and `requirements/test`. Please see this [wiki]( https://github.com/conda-forge/staged-recipes/wiki/VC-features ) for details.

**Comment by jakirkham** [comment]
What do you for DyND on Windows now?

**Comment by izaid** [comment]
@jakirkham Okay, so it seems the only real issue is linux. Can we add devtoolset-4 to the image? That would be great.

**Comment by izaid** [comment]
As for Appveyor, we are just using one of their Visual Studio 2015 images and it is all fine. https://github.com/libdynd/libdynd/blob/master/appveyor.yml

**Comment by izaid** [comment]
@jakirkham Can we devtoolset-4? What needs to be done to make that happen?

**Comment by jakirkham** [comment]
I can propose the addition, but a change of that sort will require discussion. Though I don't expect any serious opposition. Maybe for now we can add `skip: true  # [linux]` until that is resolved and try to fix up the Mac and Windows builds. It seems there is still some work to do there anyways.

**Comment by jakirkham** [comment]
See this PR ( https://github.com/conda-forge/docker-images/pull/22 ) for the proposal to switch to `devtoolset-4`.

**Comment by izaid** [comment]
Sounds great, I'll push ahead with Mac and Windows, while keeping an eye on that other PR.

**Comment by izaid** [comment]
@jakirkham Re: OS X. We've found that the default OS X image on Travis CI is not sufficient for C++14 (despite the claim that it fully supports it), but everything works is we use `osx_image: xcode6.4`. XCode 6.1 does not actually support the `-std=c++14` flag, for instance. So we'd need to boost the XCode version as well.

**Comment by izaid** [comment]
Appveyor just works though! :)
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.4683

Conclusion: We need `osx_image: xcode6.4` for OS X and `devtoolset-4` for Linux. That's it, and that should smoothly enable C++14 across the board.

**Comment by izaid** [comment]
@jakirkham I have updated .travis.yml to use XCode 6.4. With that change, everything but Linux works. Is this cool?

**Comment by jakirkham** [comment]
I think it should be ok. Though can we please break that commit out into its own PR and then rebase this on top of it?

**Comment by izaid** [comment]
Alright, let me close this and reopen 2 PRs.

**Pull request closed without merging**
