### PR TITLE
add erroranalysis

### PR DESCRIPTION
**Pull request by bgalvao**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bgalvao** [comment]
@janjagusch shall we turn this into noarch?
(PS: almost all PRs are opened)

**Comment by janjagusch** [comment]
> @janjagusch shall we turn this into noarch? (PS: almost all PRs are opened)

I'm afraid we can't build this as `noarch` for now, as we have architecture-specific build instructions in our recipe. For that, we would need to have the `requirements.txt` as part of the `sdist`, which is something we should certainly fix upstream, but maybe after we have the first package releases ready.

So yeah, for now, please remove the version constraint on the Python dependency to make the linter happy, please.

> (PS: almost all PRs are opened)

Awesome! Could you reference them in the original PR and then close it, please?

**Comment by bgalvao** [comment]
@janjagusch the linter is happy :)

**Review by janjagusch — APPROVED** [review]
This also looks good to me.

@xhochy, if you could give this a final review, that would be much appreciated.

Some notes:

- The `requirements.txt` is used inside the `setup.py` but missing in the `sdist`
- We can't add a separate source with the `requirements.txt` from GitHub, as the GitHub repo versioning and the PyPI repo versioning are not aligned
- That's why we have to create an empty `requirements.txt` during the build
- As creating empty files differs between Windows and Unix, we have to have separate build scripts, meaning we can't make this a `noarch` build
- In arch-specific builds the linter tells us not to pin the Python version

@bgalvao and I will add the `requirements.txt` (and the license file, for that matter) to the `sdist` in an upstream PR and adjust the feedstock afterward.

**Comment by janjagusch** [comment]
@bgalvao, the new version (`0.3.4`) now contains the license file. Could you please re-run `grayskull`?

**Comment by janjagusch** [comment]
@conda-forge-bot, please restart ci.

**Comment by janjagusch** [comment]
@bgalvao, could you trigger the CI again, now that `raiutils` has been forged, please?
One way to do that would be to push an empty commit. Also, there is a bot command to do so, but I can't remember the right syntax.

**Comment by janjagusch** [comment]
@conda-forge-admin, please restart ci

**Comment by janjagusch** [comment]
nevermind, found the commands: https://conda-forge.org/docs/maintainer/infrastructure.html

**Comment by janjagusch** [comment]
@conda-forge/python, could you take a look at this, please? 🙏

**Pull request merged**
