### PR TITLE
Adding arosics

### PR DESCRIPTION
**Pull request by danschef**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by danschef** [comment]
The [arosics-feedstock](https://github.com/conda-forge/arosics-feedstock) repo was already created before I actually submitted the PR. The repo belongs this PR but version [0.9.23](https://github.com/conda-forge/arosics-feedstock/blob/master/recipe/meta.yaml) did not pass the local build tests. So I fixed that, updated the meta.yaml and created this PR.

Could somebody fix the linter check or update the already existing [arosics-feedstock](https://github.com/conda-forge/arosics-feedstock)?

**Comment by rluria14** [comment]
@danschef https://github.com/conda-forge/arosics-feedstock/pull/3 the latest version, v0.9.24, has just been merged. thanks

**Comment by danschef** [comment]
Thanks @rluria14! Is there anything else needed from my side to get this PR merged?

**Comment by rluria14** [comment]
@danschef No problem! You can probably close this PR now since it's already a feedstock.

**Comment by danschef** [comment]
Ok nice! But shouldn´t I be a maintainer of the [arosics-feedstock](https://github.com/conda-forge/arosics-feedstock) to be able to update the repo, etc.? Same applies to the [geoarray-feedstock](https://github.com/conda-forge/geoarray-feedstock) and [py_tools_ds-feedstock](https://github.com/conda-forge/py_tools_ds-feedstock) from which I am the developer and which have been created while adding arosics to conda-forge.

**Comment by rluria14** [comment]
> Ok nice! But shouldn´t I be a maintainer of the [arosics-feedstock](https://github.com/conda-forge/arosics-feedstock) to be able to update the repo, etc.? Same applies to the [geoarray-feedstock](https://github.com/conda-forge/geoarray-feedstock) and [py_tools_ds-feedstock](https://github.com/conda-forge/py_tools_ds-feedstock) from which I am the developer and which have been created while adding arosics to conda-forge.

Gotcha! I will make a PR and add you as a maintainer.

**Comment by rluria14** [comment]
@danschef ok I've just added you as maintainer for all three of those feedstocks.

**Comment by danschef** [comment]
Thanks! Then I close this PR.

**Pull request closed without merging**
