### PR TITLE
More django stuff

### PR DESCRIPTION
**Pull request by ocefpaf**
@kwilcox these recipes are from the IOOS channel and they were added either directly by you or to satisfy some dependency on software you used. So added you as a maintainer in all of them :wink:

### CODE REVIEW

**Comment by pelson** [comment]
Wow. I think that is the longest list of recipes the bot has had to deal with. :smile: 

:+1:

**Comment by jakirkham** [comment]
`luigi`? That's not Django stuff.

**Comment by jakirkham** [comment]
@erikbern @Tarrasch @daveFNbuck @freider, just letting you know that we have added `luigi` to [conda-forge]( http://conda-forge.github.io/ ). This will allow users to easily install this with [`conda`]( http://conda.pydata.org/docs/ ) ( [`conda install -c conda-forge luigi`]( http://anaconda.org/conda-forge/luigi ) ). The maintenance burden here is light as all releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in [this feedstock (repo)]( https://github.com/conda-forge/luigi-feedstock ). If you have any interest in being added as a maintainer (useful for making new releases for instance), we would be more than happy to add you to the maintainers list.

**Comment by daveFNbuck** [comment]
Does conda do continuous rather than periodic releases? Seems like that
could cause some maintenance issues, as not every merge is suitable for
general use.

**Comment by kwilcox** [comment]
@daveFNbuck You would need to submit a pull request for any new `luigi` versions to be packaged. The CI on each pull request will test the package against a matrix of `python version X OS` combintations. When the PR is merged it will create the actual packages in available in `conda-forge`. The [feedstock repository](https://github.com/conda-forge/luigi-feedstock) isn't tied directly to the `luigi` repository at all. It is a manual process to  submit a PR to bump the version.  I'm long on luigi and use it in production... I will maintain the feedstock for the foreseeable future... but I could use another maintainer to merge PRs so I am not forced to self merge them (https://github.com/conda-forge/luigi-feedstock/pull/5)!

Did I understand and answer your question?

**Comment by ocefpaf** [comment]
> . but I could use another maintainer to merge PRs so I am not forced to self merge them (conda-forge/luigi-feedstock#5)!


Self-merging updates is fair game in a feedstock. Specially if you are only update the version. (But help is always welcome :smile:)

**Comment by Tarrasch** [comment]
@kwilcox, thanks for taking the leading the condafying of luigi process. To assist you, I've just started to Watch the feedstock repository, so I should be notified on PRs+Issues.

**Pull request merged**
