### PR TITLE
Do not mention conda skeleton in README

### PR DESCRIPTION
**Pull request by astaric**
While nice in theory, conda skeleton produces a recipe that will need to be modified a lot (it does not use template variables, puts all dependencies in both build and run, uses md5 hash, uses build scripts for simple python packages, ...). It might be a better idea to just start with the example recipe and change where change is needed.

Most of the comments in #2289 referred to the lines generated by `conda skeleton`.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please add `[skip ci]` to your commit. CI is not necessary here for doc changes.

**Comment by ocefpaf** [comment]
@astaric I agree in principle. with this. Remove from the README but add something about skeleton in the docs. (I am planning to add conda-forge skeleton as a GSoC project.)

**Comment by ericdill** [comment]
(definitely did not mean to click "Request changes" on this one. My mistake)

**Comment by ocefpaf** [comment]
Thanks @astaric and @ericdill.

**Pull request merged**
