### PR TITLE
A third attempt to add package qsv (rust-based tool to work with csv data)

### PR DESCRIPTION
**Pull request by holtgrewe**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

**Also See**

- #24081
- #20773

### CODE REVIEW

**Comment by holtgrewe** [comment]
**Linux Failure**

after compilation:

```
2023-11-22T15:13:37.5199344Z + qsv --version
2023-11-22T15:13:37.5223781Z thread 'main' panicked at /home/conda/staged-recipes/build_artifacts/qsv_1700664681719/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/qsv_docopt-1.4.0/src/utils.rs:20:63:
2023-11-22T15:13:37.5226379Z called `Result::unwrap()` on an `Err` valueusSyntax(
2023-11-22T15:13:37.5228843Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-11-22T15:13:37.5229455Z regex parse error:
2023-11-22T15:13:37.5230098Z     (?s)(?i:usage):\s*(?P<prog>\S+)(?P<pats>.*?)(?:$|\n\s*\n)
2023-11-22T15:13:37.5230590Z      ^
2023-11-22T15:13:37.5230933Z error: repetition operator missing expression
2023-11-22T15:13:37.5231494Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-11-22T15:13:37.5231977Z e
2023-11-22T15:13:37.5232277Z stack backtrace:
2023-11-22T15:13:37.5232696Z    0us    a 55b654e63eaf - <unknown>
2023-11-22T15:13:37.5233147Z    1us    a 55b654a101bc - <unknown>
2023-11-22T15:13:37.5233576Z    2us    a 55b654e278ad - <unknown>
2023-11-22T15:13:37.5234008Z    3us    a 55b654e6542e - <unknown>
2023-11-22T15:13:37.5234590Z    4us    a 55b654e65033 - <unknown>
2023-11-22T15:13:37.5235050Z    5us    a 55b654e65fc3 - <unknown>
2023-11-22T15:13:37.5235484Z    6us    a 55b654e65a92 - <unknown>
2023-11-22T15:13:37.5235909Z    7us    a 55b654e659f6 - <unknown>
2023-11-22T15:13:37.5236341Z    8us    a 55b654e659e1 - <unknown>
2023-11-22T15:13:37.5236777Z    9us    a 55b65469a652 - <unknown>
2023-11-22T15:13:37.5237218Z   14us    a 55b65469aa89 - <unknown>
2023-11-22T15:13:37.5237653Z   15us    a 55b6546bbd5f - <unknown>
2023-11-22T15:13:37.5238080Z   16us    a 55b6546bbb5e - <unknown>
2023-11-22T15:13:37.5238511Z   17us    a 55b654c3a8d6 - <unknown>
2023-11-22T15:13:37.5238955Z   18us    a 55b654c3a3ba - <unknown>
2023-11-22T15:13:37.5239396Z   19us    a 55b654988fc2 - <unknown>
2023-11-22T15:13:37.5239826Z   20us    a 55b654756c33 - <unknown>
2023-11-22T15:13:37.5240251Z   21us    a 55b65499bbd0 - <unknown>
2023-11-22T15:13:37.5254283Z thread panicked while processing panic. aborting.
2023-11-22T15:13:37.7443206Z /home/conda/staged-recipes/build_artifacts/qsv_1700664681719/test_tmp/run_test.sh: line 7:  4341 Aborted                 (core dumped) RUST_BACKTRACE=full qsv --version > /dev/null
2023-11-22T15:13:38.4282176Z WARNING: Tests failed for qsv-0.114.0-he8a937b_0.conda - moving package to /home/conda/staged-recipes/build_artifacts/broken
2023-11-22T15:13:38.4698415Z TESTS FAILED: qsv-0.114.0-he8a937b_0.conda
2023-11-22T15:13:44.2466172Z ##[error]Bash exited with code '1'.
2023-11-22T15:13:44.2522990Z ##[section]Finishing: Run docker build
```

**Windows Failure**

A build failure:

```
2023-11-22T15:08:15.4715380Z    Compiling calamine v0.22.0
2023-11-22T15:16:39.7285350Z error: linking with `x86_64-apple-darwin13.4.0-clang` failed: exit status: 1
2023-11-22T15:16:39.7287590Z   |
2023-11-22T15:16:39.7316350Z   = note: LC_ALL="C" PATH="/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/rustlib/x86_64-apple-darwin/bin:/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_build_env/bin:/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/.cargo/bin:/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin:/Users/runner/Miniforge3/condabin:/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_build_env/bin:/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin:/Users/runner/Miniforge3/bin:/Users/runner/Miniforge3/condabin:.:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.ghcup/bin" VSLANG="1033" ZERO_AR_DATE="1" "x86_64-apple-darwin13.4.0-clang" "-arch" "x86_64" "-m64" "/tmp/rustcVE1TMh/symbols.o" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/deps/qsv-0d99ec4fb7505b3b.qsv.89fd2b511cb43c8a-cgu.0.rcgu.o" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/deps" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/release/deps" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/build/bzip2-sys-2dd08d67dfbff92a/out/lib" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/build/zstd-sys-ab02a7b20803676b/out" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/build/decimal-17142cd161d1fb1c/out" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/build/ring-f753175a6ae052bd/out" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/build/psm-166fa7fc00b0e856/out" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/rustlib/x86_64-apple-darwin/lib" "/tmp/rustcVE1TMh/libpsm-07004cc9a18d3d67.rlib" "/tmp/rustcVE1TMh/libzstd_sys-93fd46c5a310a1cf.rlib" "/tmp/rustcVE1TMh/libbzip2_sys-3b2b4d3a65dc3dfe.rlib" "/tmp/rustcVE1TMh/libring-d32364e347468693.rlib" "/tmp/rustcVE1TMh/libdecimal-0fe4150a9c53216a.rlib" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-9c90a2632a379147.rlib" "-framework" "IOKit" "-framework" "CoreFoundation" "-framework" "Security" "-framework" "CoreFoundation" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target/x86_64-apple-darwin/release/deps/qsv-0d99ec4fb7505b3b" "-Wl,-dead_strip" "-nodefaultlibs" "-Wl,-rpath,@loader_path"
2023-11-22T15:16:39.7345520Z   = note: Undefined symbols for architecture x86_64:
2023-11-22T15:16:39.7346140Z             "_kCFURLVolumeAvailableCapacityForImportantUsageKey", referenced from:
2023-11-22T15:16:39.7347650Z                 _$LT$sysinfo..apple..system..System$u20$as$u20$sysinfo..traits..SystemExt$GT$::new_with_specifics::hfff8074ec3d7c2dc in qsv-0d99ec4fb7505b3b.qsv.89fd2b511cb43c8a-cgu.0.rcgu.o
2023-11-22T15:16:39.7348900Z           ld: symbol(s) not found for architecture x86_64
2023-11-22T15:16:39.7349760Z           clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
2023-11-22T15:16:39.7350550Z           
2023-11-22T15:16:39.7350760Z 
2023-11-22T15:16:39.9173160Z error: could not compile `qsv` (bin "qsv") due to previous error
2023-11-22T15:16:39.9496390Z error: failed to compile `qsv v0.114.0 (/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work)`, intermediate artifacts can be found at `/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/target`.
2023-11-22T15:16:39.9498440Z To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
2023-11-22T15:16:41.4251820Z Traceback (most recent call last):
2023-11-22T15:16:41.4252890Z   File "/Users/runner/work/1/s/.ci_support/build_all.py", line 228, in <module>
2023-11-22T15:16:41.4254270Z     build_all(os.path.join(root_dir, "recipes"), args.arch)
2023-11-22T15:16:41.4254990Z   File "/Users/runner/work/1/s/.ci_support/build_all.py", line 118, in build_all
2023-11-22T15:16:41.4256160Z     build_folders(recipes_dir, folders, arch, channel_urls)
2023-11-22T15:16:41.4257510Z   File "/Users/runner/work/1/s/.ci_support/build_all.py", line 174, in build_folders
2023-11-22T15:16:41.4258500Z     conda_build.api.build([recipe], config=get_config(arch, channel_urls))
2023-11-22T15:16:41.4259750Z   File "/Users/runner/Miniforge3/lib/python3.10/site-packages/conda_build/api.py", line 253, in build
2023-11-22T15:16:41.4283690Z     return build_tree(
2023-11-22T15:16:41.4284760Z   File "/Users/runner/Miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 3804, in build_tree
2023-11-22T15:16:41.4298200Z     packages_from_this = build(
2023-11-22T15:16:41.4299530Z   File "/Users/runner/Miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 2673, in build
2023-11-22T15:16:41.4304690Z     utils.check_call_env(
2023-11-22T15:16:41.4305790Z   File "/Users/runner/Miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 445, in check_call_env
2023-11-22T15:16:41.4314060Z     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
2023-11-22T15:16:41.4316350Z   File "/Users/runner/Miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 421, in _func_defaulting_env_to_os_environ
2023-11-22T15:16:41.4317750Z     raise subprocess.CalledProcessError(proc.returncode, _args)
2023-11-22T15:16:41.4319220Z subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/Miniforge3/conda-bld/qsv_1700665032439/work/conda_build.sh']' returned non-zero exit status 101.
2023-11-22T15:16:47.8387280Z ##[error]Bash exited with code '1'.
```

**Comment by holtgrewe** [comment]
Hello @conda-forge/core. I believe that I need to require macOS 10.13+ because of the need for `_kCFURLVolumeAvailableCapacityForImportantUsageKey`. I hope that I can use this to resolve the linker error that I have been seeing. Please tell me if I'm on the right track here.

**Comment by holtgrewe** [comment]
This appears to be a related issue in nix:

- https://github.com/FuelLabs/fuel.nix/issues/64

Aparently, the problematic symbol is only available on macOS 10.13+

- https://developer.apple.com/documentation/corefoundation/kcfurlvolumeavailablecapacityforimportantusagekey

**Comment by holtgrewe** [comment]
@jqnatividad -- could you have a look at the following failure from the linux build?

```
2023-11-22T16:35:16.4341912Z 
2023-11-22T16:35:28.9156453Z Preparing transaction: ...working... done
2023-11-22T16:35:32.0011322Z Verifying transaction: ...working... done
2023-11-22T16:35:34.5423817Z Executing transaction: ...working... done
2023-11-22T16:35:34.5808151Z export PREFIX=/home/conda/staged-recipes/build_artifacts/qsv_1700669466194/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
2023-11-22T16:35:34.5810946Z export SRC_DIR=/home/conda/staged-recipes/build_artifacts/qsv_1700669466194/test_tmp
2023-11-22T16:35:35.1629602Z + RUST_BACKTRACE=full
2023-11-22T16:35:35.1665623Z + qsv --version
2023-11-22T16:35:35.1673666Z thread 'main' panicked at /home/conda/staged-recipes/build_artifacts/qsv_1700669466194/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/qsv_docopt-1.4.0/src/utils.rs:20:63:
2023-11-22T16:35:35.1677206Z called `Result::unwrap()` on an `Err` valueusSyntax(
2023-11-22T16:35:35.1677806Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-11-22T16:35:35.1678319Z regex parse error:
2023-11-22T16:35:35.1678707Z     (?s)(?i:usage):\s*(?P<prog>\S+)(?P<pats>.*?)(?:$|\n\s*\n)
2023-11-22T16:35:35.1679135Z      ^
2023-11-22T16:35:35.1679443Z error: repetition operator missing expression
2023-11-22T16:35:35.1680282Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-11-22T16:35:35.1681728Z e
2023-11-22T16:35:35.1681984Z stack backtrace:
2023-11-22T16:35:35.1682427Z    0us    a 55aea264fbbf - <unknown>
2023-11-22T16:35:35.1682918Z    1us    a 55aea21f435c - <unknown>
2023-11-22T16:35:35.1683402Z    2us    a 55aea261348d - <unknown>
2023-11-22T16:35:35.1683854Z    3us    a 55aea265113e - <unknown>
2023-11-22T16:35:35.1685150Z    4us    a 55aea2650d43 - <unknown>
2023-11-22T16:35:35.1685624Z    5us    a 55aea2651c63 - <unknown>
2023-11-22T16:35:35.1686051Z    6us    a 55aea2651732 - <unknown>
2023-11-22T16:35:35.1686444Z    7us    a 55aea2651696 - <unknown>
2023-11-22T16:35:35.1687011Z    8us    a 55aea2651681 - <unknown>
2023-11-22T16:35:35.1687411Z    9us    a 55aea1e6d492 - <unknown>
2023-11-22T16:35:35.1687811Z   14us    a 55aea1e6d8c9 - <unknown>
2023-11-22T16:35:35.1688188Z   15us    a 55aea1e8ed4f - <unknown>
2023-11-22T16:35:35.1688585Z   16us    a 55aea1e8eb4e - <unknown>
2023-11-22T16:35:35.1688979Z   17us    a 55aea241c066 - <unknown>
2023-11-22T16:35:35.1689380Z   18us    a 55aea241bb4a - <unknown>
2023-11-22T16:35:35.1689761Z   19us    a 55aea216ab72 - <unknown>
2023-11-22T16:35:35.1690335Z   20us    a 55aea1f26a13 - <unknown>
2023-11-22T16:35:35.1690749Z   21us    a 55aea217f370 - <unknown>
2023-11-22T16:35:35.1727963Z thread panicked while processing panic. aborting.
2023-11-22T16:35:35.4434165Z /home/conda/staged-recipes/build_artifacts/qsv_1700669466194/test_tmp/run_test.sh: line 7:  4570 Aborted                 (core dumped) RUST_BACKTRACE=full qsv --version > /dev/null
2023-11-22T16:35:36.5915057Z WARNING: Tests failed for qsv-0.118.0-he8a937b_0.conda - moving package to /home/conda/staged-recipes/build_artifacts/broken
2023-11-22T16:35:36.6594204Z TESTS FAILED: qsv-0.118.0-he8a937b_0.conda
2023-11-22T16:35:46.0561508Z ##[error]Bash exited with code '1'.
2023-11-22T16:35:46.0629760Z ##[section]Finishing: Run docker build
```

Full logs are here:

- https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/829062/logs/17

**Comment by jqnatividad** [comment]
Please keep this issue open. I'll attempt to update the recipe after the next qsv release...

**Comment by ocefpaf** [comment]
> Please keep this issue open. I'll attempt to update the recipe after the next qsv release...

Don't mind the stale bot. If it closes either open a fresh PR or ping us to reopen this one if you cannot.

**Comment by peterjc** [comment]
Superseded by #27064 (which was merged), this can be closed now.

**Pull request closed without merging**
