### PR TITLE
adding r-hexview

### PR DESCRIPTION
**Pull request by PackageCondaDataScience**
hi @conda-forge/help-r 
please add r-hexview to conda-forge project

### CODE REVIEW

**Comment by PackageCondaDataScience** [comment]
@conda-forge/help-r : I don't understand why the checks were not successful. I use conda skeleton to create the recipe and there was no error when I have used conda-build on my computer.  
Assistance welcome :)

**Comment by cbrueffer** [comment]
Please use https://github.com/bgruening/conda_r_skeleton_helper to generate the recipe; we can take it from there.

**Comment by dbast** [comment]
@PackageCondaDataScience This is not a full update with https://github.com/bgruening/conda_r_skeleton_helper ... lots of comments would be removed by it and the build scripts are also missing.

**Comment by PackageCondaDataScience** [comment]
@dbast thanks for helping. I made a new pull request with the exact copy of the recipe. All checks have passed

**Pull request closed without merging**
