### PR TITLE
Add morphops Python package

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hakonanes** [comment]
@vaipatel, could you take a look at the `meta.yml` file, suggest any changes, and state whether you can be a recipe maintainer or not?

After this recipe has been successfully merged, a `morphops-feedstock` will be created ([example of a package I maintain](https://github.com/conda-forge/kikuchipy-feedstock/)), and morphops should be downloadable via `conda install morphops --channel conda-forge`. Every time a new PyPI release is available, a bot will set up a PR to the feedstock, and if no dependency changes or other changes to the `meta.yml` file are desired, this PR can just be merged, and the new PyPI version will be available via the `conda-forge` channel!

**Comment by beenje** [comment]
Job is failing because `setup_requires=['numpy >= 1.13.3']` is defined in the `setup.py` of the package.
This is a pure  python package. numpy isn't needed to create the package, only at runtime.

**Comment by hakonanes** [comment]
Thanks again @beenje, a fix will hopefully be released shortly (https://github.com/vaipatel/morphops/pull/18).

**Comment by beenje** [comment]
> I am willing to be listed as maintainer for this recipe.

I had missed that. Thanks for confirming!

**Comment by hakonanes** [comment]
Thanks @beenje and @ocefpaf :)

**Pull request merged**
