### PR TITLE
Django fsm

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@synapticarbors  
Hi, 
I think I have imported everything in the run_test.py, but it didn't work. Could you please look at it and suggest something to make it work.

Regards
Sanny

**Comment by synapticarbors** [comment]
@sannykr I'm not sure where you got the `sha256` from, but it should be `13da2fbec4284dcf2235157c299306f67b788bd39126bed3cdbcc6a8f17575e9` when I look at https://pypi.org/project/django-fsm/#files

**Comment by sannykr** [comment]
Thanks. I downloaded the zip from github, that's why got a different sha.

**Comment by synapticarbors** [comment]
It looks like the license isn't included in the source distribution because the library doesn't have the proper `MANIFEST.in`. Please put in a PR/raise an issue upstream and put a link in the recipe as a comment so there is a reminder for future updates to check. Then you can package the license manually:

https://conda-forge.org/docs/meta.html#packaging-the-license-manually

**Comment by sannykr** [comment]
@synapticarbors : Hi Joshua, could you please tell me how I can update a conda-forge package. Do I need to replace it with the new one?

Regards
Sanny

**Comment by synapticarbors** [comment]
@sannykr I'm not sure what you mean by update a conda-forge package. Do you mean that there is a feedstock for a package that has already been created but you need a newer version of that package? In that case you would make a pull request against the feedstock to update the recipe.

**Comment by sannykr** [comment]
@synapticarbors: Yes. there is a package "django-viewflow". At that time the latest version was 1.0.1, but now on PyPI the latest one is 1.0.2.    I am trying to update the one at conda-forge to the latest version.

Regards
Sanny

**Comment by synapticarbors** [comment]
See the following for instructions: https://github.com/conda-forge/django-viewflow-feedstock#updating-django-viewflow-feedstock

**Comment by sannykr** [comment]
@synapticarbors : could you please merge it.

**Pull request merged**
