### PR TITLE
add OSQP

### PR DESCRIPTION
**Pull request by dougalsutherland**
Split from #6076.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
cc @bstellato

**Comment by dougalsutherland** [comment]
@conda-forge/help-c-cpp, this is ready for review:

- Will figure out Windows on the feedstock; Circle and Travis passed on the previous commit.
- Linter error is fixed by https://github.com/conda-forge/conda-smithy/pull/792; `master` is happy.

**Comment by dougalsutherland** [comment]
Might as well ping @conda-forge/staged-recipes since apparently @conda-forge/help-c-cpp is tiny....

**Comment by scopatz** [comment]
Thanks @dougalsutherland!

**Pull request merged**
