### PR TITLE
Add "gepetto-viewer" recipe

### PR DESCRIPTION
**Pull request by ymontmarin**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by ymontmarin** [comment]
@conda-forge/help-c-cpp 

After the decision to focus on gepetto-viewer only in this recipe and after some work done on the X11 and OpenGL dependencies I finally managed to converge to a simple recipe that succeed to build Linux package.

However, after trying few workarounds, I cant manage to get it done  for osx. I got the error:
```
/Users/runner/miniforge3/conda-bld/gepetto-viewer_1602451873289/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/X11/Xlib.h:1686:1: error: unknown type name '_X_DEPRECATED'
```
during compilation. From what I found, the most similar error was in recipe discussion: https://github.com/conda-forge/ambertools-feedstock/pull/18 which also about a gui on MacOs. It seems related to the issue https://github.com/conda-forge/tk-feedstock/issues/15 about interference between `tk` and `X11` with `tk` overiding some `X11` headers with an incomplete ones. I am not familiar with those kind of issue.

Could you help and advice on this issue ?

**Comment by ymontmarin** [comment]
ping @jcarpent : update on recipe situation.

Do you accept to also be a maintainer ?

**Comment by jcarpent** [comment]
Fine to be considered as a maintener

**Comment by ymontmarin** [comment]
@conda-forge/help-c-cpp 
### Workaround found
After digging on a MacOS VM the behaviour of tk and X11 and how they install conflict headers, and all the conda-forge threads about this interaction, the cleanest warkaround i found is to alias the X11 of root include (which is corrupt by the tk installation which is required) to let the compiler use the host include folder X11 which is not corrupted. I restore the aliasing after compilation to respect folder structure for conda-build.

### Next step
I think this PR is then ready to merge, @conda-forge/help-c-cpp

**Comment by ymontmarin** [comment]
@conda-forge/help-c-cpp could it be possible to review the PR ? Recipe looks finish, checklist is done and CI is ok. Thanks !

**Comment by ymontmarin** [comment]
@conda-forge/help-c-cpp , I squashed and rebase the PR branch to make it more readable for review.
I think the PR is ready for merge. Could it be possible to review the PR ? Thank you !

**Comment by jcarpent** [comment]
@conda-forge/help-c-cpp We would need this package to be inside conda-forge before adding additional packages. Would you have time to review this PR and merge it?
Thanks in advance,
Best,

Justin

**Comment by jcarpent** [comment]
@wolfv Sorry to directly ask you this, but we would need this PR to be merged, but we do not have any feedback from the maintainers. I guess they are all occupied, but if you have the rights, would you have time to handle this PR?
Thanks in advance for your help.

**Comment by jcarpent** [comment]
@conda-forge-admin, please ping team

**Comment by wolfv** [comment]
thanks for the contribution!

**Comment by ymontmarin** [comment]
@wolfv Thank you for the merge !

**Comment by jcarpent** [comment]
Thanks @wolfv for the quick merge.

**Comment by wolfv** [comment]
btw @ymontmarin not sure if you deliberately chose `gnu++11` vs `c++11`. Also the conda-forge default is C++17 on OS X and Linux. So that line might not be totally necessary.

**Comment by ymontmarin** [comment]
@wolfv you are right ! I change it on the feedstock.

**Pull request merged**
