### PR TITLE
Add enblend + enfuse

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@nehaljwani on windows it is having a hard time finding the `gsl` linked libraries.

On OSX, it is having a hard timing linking with `filesystem` which seems to be a recent addition. Maybe I need to add an OSX minimum version in the feedstock?

**Comment by nehaljwani** [comment]
@hmaarrfk I have a working build on all platforms via https://github.com/nehaljwani/staged-recipes/pull/7/commits/4ea3e95040cffcb55c52ff5ad9630f3eb1700838 at https://github.com/nehaljwani/staged-recipes/pull/7

**Comment by hmaarrfk** [comment]
Wow. Super awesome. I'll try building here when I have the chance to get back home ;)

**Comment by hmaarrfk** [comment]
Cool stuff.

I had found that `filesystem` commit too in the history. Good to know that I was on the right track. I just didn't have the guts to rip it out like you did.

The windows flags, I did not know about!

Thanks a ton for your help!

Crossing my fingers for this one!

**Comment by hmaarrfk** [comment]
@conda-forge/help-c-cpp @conda-forge/staged-recipes kind ping for a review

**Comment by hmaarrfk** [comment]
many thanks!

**Pull request merged**
