### PR TITLE
Request to upload ndvi2gif

### PR DESCRIPTION
**Pull request by Digdgeo**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by Digdgeo** [comment]
@conda-forge/help-python It is ready for review. Thanks.

**Comment by Digdgeo** [comment]
Hi @giswqs I am trying to do this, but I am not sure that my ping to @conda-forge/help-python is working, it seems that user doesn't exist.

**Comment by giswqs** [comment]
It should be working. See https://github.com/orgs/conda-forge/teams/help-python

**Comment by Digdgeo** [comment]
Does the link works for you? If I try to open the url taht you have pasted, I get a 404 error. Also, when I mention you here I can see your name in bold text and it creates a link to your account, but that not happens with @conda-forge/help-python (at least for me)

**Comment by giswqs** [comment]
Yes, the links works fine for me.

**Comment by Digdgeo** [comment]
I just can't see it, so when I ping @conda-forge/help-python I don't even see that like a github account, just like a normal string. I ask someone else to open the link and get he same error than I. 
I saw that I am not yet in conda-forge/people. Maybe that is the reason...

condateam

**Comment by nehaljwani** [comment]
Thanks @Digdgeo !

**Comment by Digdgeo** [comment]
Hi @nehaljwani, thanks you!

But I think it's not really working. I've created a clean conda environment and try to install on it and it says that find conflicts. 

DeepinScreenshot_20200518120826

**Comment by nehaljwani** [comment]
Works for me in a new environment:
```
conda create -p ./dev --dry-run -c conda-forge ndvi2gif
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /tmp/nwani_1589798874/dev

  added / updated specs:
    - ndvi2gif


The following packages will be downloaded:

 ...

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  beautifulsoup4     conda-forge/linux-64::beautifulsoup4-4.9.1-py37hc8dfbb8_0
  bleach             conda-forge/noarch::bleach-3.1.5-pyh9f0ad1d_0
  bqplot             conda-forge/noarch::bqplot-0.12.11-pyh9f0ad1d_0
  branca             conda-forge/noarch::branca-0.3.1-py_0
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py37h8f50634_1000
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.4.5.1-hecc5488_0
  cachetools         conda-forge/noarch::cachetools-3.1.1-py_0
  certifi            conda-forge/linux-64::certifi-2020.4.5.1-py37hc8dfbb8_0
  cffi               conda-forge/linux-64::cffi-1.14.0-py37hd463f26_0
  chardet            conda-forge/linux-64::chardet-3.0.4-py37hc8dfbb8_1006
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  colour             conda-forge/noarch::colour-0.1.5-py_0
  cryptography       conda-forge/linux-64::cryptography-2.9.2-py37hb09aad4_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  earthengine-api    conda-forge/noarch::earthengine-api-0.1.221-pyh9f0ad1d_0
  entrypoints        conda-forge/linux-64::entrypoints-0.3-py37hc8dfbb8_1001
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  folium             conda-forge/noarch::folium-0.11.0-py_0
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0
  future             conda-forge/linux-64::future-0.18.2-py37hc8dfbb8_1
  geeadd             conda-forge/noarch::geeadd-0.4.9-py_0
  geemap             conda-forge/noarch::geemap-0.6.10-pyh9f0ad1d_0
  geocoder           conda-forge/noarch::geocoder-1.38.1-py_1
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.64.2-h6f030ca_1
  google-api-core    conda-forge/linux-64::google-api-core-1.17.0-py37hc8dfbb8_0
  google-api-python~ conda-forge/noarch::google-api-python-client-1.8.3-pyh9f0ad1d_0
  google-auth        conda-forge/noarch::google-auth-1.14.3-pyh9f0ad1d_0
  google-auth-httpl~ conda-forge/noarch::google-auth-httplib2-0.0.3-py_3
  google-cloud-core  conda-forge/noarch::google-cloud-core-1.3.0-py_0
  google-cloud-stor~ conda-forge/noarch::google-cloud-storage-1.28.1-pyh9f0ad1d_0
  google-resumable-~ conda-forge/noarch::google-resumable-media-0.5.0-py_1
  googleapis-common~ conda-forge/linux-64::googleapis-common-protos-1.51.0-py37hc8dfbb8_2
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.5-h0935bb2_2
  gstreamer          conda-forge/linux-64::gstreamer-1.14.5-h36ae1b5_2
  httplib2           conda-forge/noarch::httplib2-0.17.3-pyh9f0ad1d_0
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  idna               conda-forge/noarch::idna-2.9-py_1
  importlib-metadata conda-forge/linux-64::importlib-metadata-1.6.0-py37hc8dfbb8_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.6.0-0
  ipyfilechooser     conda-forge/noarch::ipyfilechooser-0.3.4-pyh9f0ad1d_0
  ipykernel          conda-forge/linux-64::ipykernel-5.2.1-py37h43977f1_0
  ipyleaflet         conda-forge/noarch::ipyleaflet-0.12.6-pyh9f0ad1d_0
  ipynb-py-convert   conda-forge/noarch::ipynb-py-convert-0.4.5-py_0
  ipython            conda-forge/linux-64::ipython-7.14.0-py37hc8dfbb8_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.5.1-py_0
  jedi               conda-forge/linux-64::jedi-0.17.0-py37hc8dfbb8_0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  jsonschema         conda-forge/linux-64::jsonschema-3.2.0-py37hc8dfbb8_1
  jupyter_client     conda-forge/noarch::jupyter_client-6.1.3-py_0
  jupyter_core       conda-forge/linux-64::jupyter_core-4.6.3-py37hc8dfbb8_1
  kiwisolver         conda-forge/linux-64::kiwisolver-1.2.0-py37h99015e2_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_0
  libblas            conda-forge/linux-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-16_openblas
  libclang           conda-forge/linux-64::libclang-9.0.1-default_hde54327_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_6
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006
  liblapack          conda-forge/linux-64::liblapack-3.8.0-16_openblas
  libllvm9           conda-forge/linux-64::libllvm9-9.0.1-he513fc3_1
  libopenblas        conda-forge/linux-64::libopenblas-0.3.9-h5ec1e0e_0
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_1
  libprotobuf        conda-forge/linux-64::libprotobuf-3.11.4-h8b12597_0
  libsodium          conda-forge/linux-64::libsodium-1.0.17-h516909a_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc7e4089_6
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libwebp-base       conda-forge/linux-64::libwebp-base-1.1.0-h516909a_3
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxkbcommon       conda-forge/linux-64::libxkbcommon-0.10.0-he1b5a44_0
  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0
  llvm-openmp        conda-forge/linux-64::llvm-openmp-10.0.0-hc9558a2_0
  logzero            conda-forge/linux-64::logzero-1.5.0-py37hc8dfbb8_1002
  lz4-c              conda-forge/linux-64::lz4-c-1.9.2-he1b5a44_1
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py37h8f50634_1
  matplotlib         conda-forge/linux-64::matplotlib-3.2.1-0
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.2.1-py37h30547a4_0
  mistune            conda-forge/linux-64::mistune-0.8.4-py37h8f50634_1001
  nbconvert          conda-forge/linux-64::nbconvert-5.6.1-py37hc8dfbb8_1
  nbformat           conda-forge/noarch::nbformat-5.0.6-py_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  ndvi2gif           conda-forge/linux-64::ndvi2gif-0.0.2-py37hc8dfbb8_0
  notebook           conda-forge/linux-64::notebook-6.0.3-py37hc8dfbb8_0
  nspr               conda-forge/linux-64::nspr-4.25-he1b5a44_0
  nss                conda-forge/linux-64::nss-3.47-he751ad9_0
  numpy              conda-forge/linux-64::numpy-1.18.4-py37h8960a57_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1g-h516909a_0
  packaging          conda-forge/noarch::packaging-20.1-py_0
  pandas             conda-forge/linux-64::pandas-1.0.3-py37h0da4684_1
  pandoc             conda-forge/linux-64::pandoc-2.9.2.1-0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  parso              conda-forge/noarch::parso-0.7.0-pyh9f0ad1d_0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  pexpect            conda-forge/linux-64::pexpect-4.8.0-py37hc8dfbb8_1
  pickleshare        conda-forge/linux-64::pickleshare-0.7.5-py37hc8dfbb8_1001
  pillow             conda-forge/linux-64::pillow-7.1.2-py37h718be6c_0
  pip                conda-forge/noarch::pip-20.1-pyh9f0ad1d_0
  prometheus_client  conda-forge/noarch::prometheus_client-0.7.1-py_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.5-py_0
  protobuf           conda-forge/linux-64::protobuf-3.11.4-py37h3340039_1
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  ptyprocess         conda-forge/noarch::ptyprocess-0.6.0-py_1001
  pyasn1             conda-forge/noarch::pyasn1-0.4.8-py_0
  pyasn1-modules     conda-forge/noarch::pyasn1-modules-0.2.7-py_0
  pycparser          conda-forge/noarch::pycparser-2.20-py_0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pyqt               conda-forge/linux-64::pyqt-5.12.3-py37h8685d9f_3
  pyrsistent         conda-forge/linux-64::pyrsistent-0.16.0-py37h8f50634_0
  pyshp              conda-forge/noarch::pyshp-2.1.0-py_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py37hc8dfbb8_1
  python             conda-forge/linux-64::python-3.7.6-h8356626_5_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  pyzmq              conda-forge/linux-64::pyzmq-19.0.1-py37hac76be4_0
  qt                 conda-forge/linux-64::qt-5.12.5-hd8c4c69_1
  ratelim            conda-forge/noarch::ratelim-0.1.6-py_2
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  requests           conda-forge/noarch::requests-2.23.0-pyh8c360ce_2
  rsa                conda-forge/noarch::rsa-4.0-py_0
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  setuptools         conda-forge/linux-64::setuptools-46.3.1-py37hc8dfbb8_0
  simplejson         conda-forge/linux-64::simplejson-3.17.0-py37h8f50634_1
  six                conda-forge/noarch::six-1.14.0-py_1
  soupsieve          conda-forge/linux-64::soupsieve-2.0.1-py37hc8dfbb8_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  terminado          conda-forge/linux-64::terminado-0.8.3-py37hc8dfbb8_1
  testpath           conda-forge/noarch::testpath-0.4.4-py_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  tornado            conda-forge/linux-64::tornado-6.0.4-py37h8f50634_1
  traitlets          conda-forge/linux-64::traitlets-4.3.3-py37hc8dfbb8_1
  traittypes         conda-forge/noarch::traittypes-0.2.1-py_1
  uritemplate        conda-forge/noarch::uritemplate-3.0.1-py_0
  urllib3            conda-forge/noarch::urllib3-1.25.9-py_0
  wcwidth            conda-forge/noarch::wcwidth-0.1.9-pyh9f0ad1d_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  widgetsnbextension conda-forge/linux-64::widgetsnbextension-3.5.1-py37_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zeromq             conda-forge/linux-64::zeromq-4.3.2-he1b5a44_2
  zipp               conda-forge/noarch::zipp-3.1.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
  zstd               conda-forge/linux-64::zstd-1.4.4-h6597ccf_3



DryRunExit: Dry run. Exiting.
```

**Comment by Digdgeo** [comment]
Now it works to me too... kind of weird. Anyway, thanks a lot. This is my first conda package and I am happy now :)

**Pull request merged**
