### PR TITLE
added videohash package

### PR DESCRIPTION
**Pull request by step21**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by HeavyTony2** [comment]
@conda-forge/staged-recipes There are currently three open PRs with a recipe for yt-dlp.
https://github.com/conda-forge/staged-recipes/pull/16494 (This one) Which comes with videohash
https://github.com/conda-forge/staged-recipes/pull/17785 (Mine) Which comes with Moe and Mediafile
https://github.com/conda-forge/staged-recipes/pull/17804 (The most recent) Which only contains yt-dlp.

I've no problem at all about removing yt-dlp from mine if it's added from another one.

**Comment by step21** [comment]
Well, I don't mind either way. I do not remember why it was not merged, probably it was forgot about. I can retry checks and then ping on conda forge gitter to check about merging

**Comment by HeavyTony2** [comment]
YT-DLP is now on Conda-Forge https://github.com/conda-forge/staged-recipes/pull/17785

**Comment by step21** [comment]
k, thanks. Gonna remove it from here later and then leave videohash ok?

**Comment by HeavyTony2** [comment]
> k, thanks. Gonna remove it from here later and then leave videohash ok?

Perfect!

**Comment by step21** [comment]
thanks!

**Pull request merged**
