### PR TITLE
Add libidn11

### PR DESCRIPTION
**Pull request by epruesse**
Libidn is a package for internationalized string handling based on the
    Stringprep, Punycode, IDNA and TLD specifications.

 - It's in bioconda, but missing in conda.
 - Using `libidn11` as package name to reflect so-version and avoid run-time binding issues at a later time.
 - Name also avoids override by weirdly versioned bioconda package (7.x).

### CODE REVIEW

**Comment by epruesse** [comment]
@conda-forge/core Ready for review :)

**Comment by epruesse** [comment]
Just noticed that AppVeyor didn't run. Will push dummy commit to try triggering it. If it doesn't work -- defer win support to feedstock?

**Comment by epruesse** [comment]
Re win: waiting to see what [AppVeyor](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.14253) does on first commit, only added Maintainer after that.

**Comment by scopatz** [comment]
Hmm odd, appveyor still didn't run.

**Comment by epruesse** [comment]
@scopatz It's that thing where it sometimes just doesn't. I need to push a patch anyway: AppVeyor finally ran on an earlier commit and I've got a mistake to fix.

**Comment by epruesse** [comment]
@conda-forge/core All tests have passed. Can someone review?

**Comment by scopatz** [comment]
Thanks a ton!

**Pull request merged**
