### PR TITLE
r-brew  r-chron  r-colorspace  r-ctv  r-curl  r-data.table  r-dbi  r-deoptimr  r-dichromat

### PR DESCRIPTION
**Pull request by johanneskoester**
xref: #2009

### CODE REVIEW

**Comment by johanneskoester** [comment]
The single test on windows failed because cran seems to be a bit unreliable at the moment. @conda-forge/core could someone please restart that build?

**Comment by johanneskoester** [comment]
Never mind, I have found a way.

**Comment by ocefpaf** [comment]
@johanneskoester please rebase with `master` to make it easier to review.

**Comment by johanneskoester** [comment]
Done.

**Comment by johanneskoester** [comment]
Thanks!

**Comment by ocefpaf** [comment]
No problem. Let's keep an eye on master and hold off the merges of many recipes like these until the  feedstocks are cleared.

**Comment by bgruening** [comment]
Mh ... `r-deoptimr` seems to be missing from the channel: https://travis-ci.org/conda-forge/staged-recipes/#L895

**Comment by isuruf** [comment]
See https://github.com/conda-forge/r-deoptimr-feedstock. Travis-CI build failed due to a network error. Can you restart the travis-CI build?

**Comment by bgruening** [comment]
Ok, done! Thanks!

**Pull request merged**
