### PR TITLE
WIP: Add ROOT

### PR DESCRIPTION
**Pull request by chrisburr**
Work in progress for now

### CODE REVIEW

**Comment by jakirkham** [comment]
So we have ROOT, but it's called `root5`. Though it looks like these are other things that are nice to have with ROOT. Is that accurate?

**Comment by chrisburr** [comment]
@jakirkham ROOT v5.XX.YY is not very old and the latest (and far more widely used) major version is ROOT 6. Most package managers have “root” for v6 and “root5” for v5.

I had this working locally with a “root” recipe also added using conda-build 3 (for a newer compiler). Am I correct in thinking conda-forge hasn’t migrated yet?

**Comment by jakirkham** [comment]
Sure open to having more versions if it helps. @conda-forge/root5, thoughts?

Not yet no. This is a hard problem generally as a lot of stuff needs to be rebuilt and we have resource limitations.

**Comment by giacomov** [comment]
I started working on the root6 recipe, but stopped because it's a piece of work and things keep changing (pinned versions, build system, compilers). Conda is a moving target and the time I can devote to this is limited. 

It would help a lot if things could get settled a bit...

Anyway, I got pretty far with root 6 using cmake.

**Pull request closed without merging**
