### PR TITLE
Proposal: Provide a mechanism for installing/documenting yum requirements (with examples)

### PR DESCRIPTION
**Pull request by jakirkham**
This is a very simple proposal that comes out of this discussion on this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/82 ) and this proposed PR ( https://github.com/conda-forge/conda-smithy/pull/135 ).

What we do here is allow for a `yum_requirements.txt` file to be included in each recipe. If present, we install anything listed in there with `yum`.

An example is provided to demonstrate/test that this works as intended in a case where installing `yum` requirements is necessary for a build to work.

### CODE REVIEW

**Comment by pelson** [comment]
Ok, let's go for it. It is easy enough to change in the future. In general, I want it to be very clear that it is not appropriate to use ```yum_requirements.txt``` in many situations (the example in qimage2array could be done better in other ways I believe), but there are some approved situations (OpenGL is currently the only one) where that is a sensible thing to do.

Now that we have working code, would you mind tidying up the PR (the recipes need removing, comment about "better", the commented out code etc.) and we can merge this.

Thanks @jakirkham!

**Comment by jakirkham** [comment]
Thanks @pelson. Will get this tidied up in the morning. Did you have a chance to look at the conda-smithy PR ( https://github.com/conda-forge/conda-smithy/pull/134 ) related to this?

**Comment by jakirkham** [comment]
> the example in qimage2array could be done better in other ways I believe...

How do you think this could be done better? The issue with `qimage2array` is that it requires Qt. The `qt` package is linked against X11 on Linux. This is the [same strategy]( https://github.com/ContinuumIO/docker-images/pull/10/files ) used by Continuum in their Docker containers to resolve [Qt issues]( https://github.com/ContinuumIO/docker-images/issues/8 ). If there is a better way, I'd be curious to know your thoughts. Or is it that there is another issue you are concerned with in regards to `qimage2array`?

**Comment by pelson** [comment]
> How do you think this could be done better?

X11 is part of [manylinux](https://www.python.org/dev/peps/pep-0513/) and should be available as vanilla in the dockerfile. Apologies if I've missed one of the dependencies not listed there though.

**Comment by jakirkham** [comment]
Oops, linked the wrong PR in the comment above. I meant have you had a chance to look at this PR ( https://github.com/conda-forge/conda-smithy/pull/135 ). It basically does the same thing for each feedstock.

**Comment by jakirkham** [comment]
I see. Thanks for the link. Didn't realize there was a formal PEP for manylinux. Though I guess it is only a few months old.

However, we aren't really the same as manylinux as we use CentOS 6 and we also package `ncurses` so I don't know what our policy is for having that version versus the system version there, but if your meaning is that we should provide the same base libraries that sounds reasonable to me (with the exception of `ncurses` where that might not work). At the time when I proposed qimage2ndarray that was not the case though. Admittedly now things have changed.

**Comment by jakirkham** [comment]
This is being replaced with this PR ( https://github.com/conda-forge/staged-recipes/pull/346 ). Keeping this one around as is (will close though) for the history and examples. This at least is a place to point people to in order to explain how to do this properly.

**Pull request closed without merging**
