### PR TITLE
[WIP] Dependencies for r-dartr update

### PR DESCRIPTION
**Pull request by jenzopr**
Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages
- [X] Build number is 0
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

This is work-in-progress to add dependencies for r-dartr https://github.com/bioconda/bioconda-recipes/pull/14917

@bgruening can I add you as maintainer?

### CODE REVIEW

**Comment by jenzopr** [comment]
Ping @bgruening - please have a look :-)

**Comment by dbast** [comment]
Hi @jenzopr,

can you please use https://github.com/bgruening/conda_r_skeleton_helper to create/update the PR? That cleans some stuff and also adds conda-forge/r group as maintainers.

Thanks

**Comment by dbast** [comment]
The windows builds are expected to fail because of noarch. So all fine.

**Comment by jenzopr** [comment]
Thanks, Daniel. Somehow I forget every time about the `conda_r_skeleton_helper` 🙄

**Pull request merged**
