### PR TITLE
submitting pandocattributes

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
Submitting this to build dependency for https://github.com/conda-forge/staged-recipes/pull/3453

**Comment by mdehollander** [comment]
I think you can trigger a rebuild because the appveyor failed because a download timed out:
```
Downloading https://pypi.io/packages/source/p/pandoc-attributes/pandoc-attributes-0.1.7.tar.gz
Error: HTTP 503 BACKEND IS UNHEALTHY for url <https://pypi.io/packages/source/p/pandoc-attributes/pandoc-attributes-0.1.7.tar.gz>
```
I guess rerunning would continue the x64 build

**Comment by ericmjl** [comment]
@mdehollander Just restarted. Thanks for the ping!

**Comment by mdehollander** [comment]
@ericmjl, another ping that the build was now successful.

**Comment by ericmjl** [comment]
ping @jakirkham @ocefpaf: I think it's ready to merge!

**Pull request merged**
