### PR TITLE
Add recipe for sphinxcontrib-bibtex

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by souravsingh** [comment]
Fixes #3617

**Comment by croth1** [comment]
@souravsingh, this package is a bit nasty, as it has several dependencies that are not yet in conda-forge. If you don't mind I will spend some time to add them now.

**Comment by souravsingh** [comment]
@croth1 I can handle creating recipes for a few dependencies

**Comment by croth1** [comment]
@souravsingh as you wish - thanks a lot 👍

**Comment by souravsingh** [comment]
There is a problem with one of the dependencies-``oset`` is only present as a read-only mirror in [https://gitorious.org/](https://gitorious.org/), so it is not possible to obtain the ``LICENSE`` file for the same.

**Comment by souravsingh** [comment]
Closing.

**Pull request closed without merging**
