### PR TITLE
Add grayskull-generated recipe for `distrax` Python package

### PR DESCRIPTION
**Pull request by flferretti**
This is a simple Grayskull-generated recipe for the `distrax` Python library.

Repo: https://github.com/google-deepmind/distrax
PyPI: https://pypi.org/project/distrax/

This follows up from https://github.com/conda-forge/staged-recipes/pull/23226 and solves https://github.com/conda-forge/staged-recipes/issues/23157 (from @ngam)

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

C.C. @traversaro

### CODE REVIEW

**Comment by traversaro** [comment]
xref previous attempt: https://github.com/conda-forge/staged-recipes/pull/23226 .

**Comment by traversaro** [comment]
> 
> 
> C.C. @traversaro

I agree on being added as a mantainer of this recipe.

**Comment by traversaro** [comment]
Build fails with:
~~~
ImportError: cannot import name 'bijectors' from partially initialized module 'tensorflow_probability.substrates.jax' (most likely due to a circular import) (/home/conda/staged-recipes/build_artifacts/distrax_1694677063455/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/__init__.py)
~~~

**Comment by flferretti** [comment]
@traversaro I noticed that the version on conda-forge of tf-probability (20.0) is not updated to the latest PyPI release (21.0). This causes the circular import error

**Comment by traversaro** [comment]
> @traversaro I noticed that the version on conda-forge of tf-probability (20.0) is not updated to the latest PyPI release (21.0). This causes the circular import error

So basically this is blocked by https://github.com/conda-forge/tensorflow-probability-feedstock/pull/46 that itself is blocked by https://github.com/conda-forge/tensorflow-feedstock/pull/329 .

**Comment by traversaro** [comment]
> @traversaro I noticed that the version on conda-forge of tf-probability (20.0) is not updated to the latest PyPI release (21.0). This causes the circular import error
> 
> https://github.com/conda-forge/tensorflow-probability-feedstock

Interestingly, I tried to install the same version of jax mentioned by tf-probability 20.0 docs (https://github.com/tensorflow/probability/releases/tag/v0.20.0), via pypi as with conda-forge there is an abseil version incompatibility, and I still get the same error:
~~~
(draxtestoldjax) traversaro@IITICUBLAP257:~$ python -c "import distrax"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/traversaro/miniforge3/envs/draxtestoldjax/lib/python3.11/site-packages/distrax/__init__.py", line 18, in <module>
    from distrax._src.bijectors.bijector import Bijector
  File "/home/traversaro/miniforge3/envs/draxtestoldjax/lib/python3.11/site-packages/distrax/_src/bijectors/bijector.py", line 26, in <module>
    tfb = tfp.bijectors
          ^^^^^^^^^^^^^
  File "/home/traversaro/miniforge3/envs/draxtestoldjax/lib/python3.11/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 53, in __getattr__
    module = self._load()
             ^^^^^^^^^^^^
  File "/home/traversaro/miniforge3/envs/draxtestoldjax/lib/python3.11/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 40, in _load
    module = importlib.import_module(self.__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/traversaro/miniforge3/envs/draxtestoldjax/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/traversaro/miniforge3/envs/draxtestoldjax/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/__init__.py", line 41, in <module>
    from tensorflow_probability.substrates.jax import bijectors
ImportError: cannot import name 'bijectors' from partially initialized module 'tensorflow_probability.substrates.jax' (most likely due to a circular import) (/home/traversaro/miniforge3/envs/draxtestoldjax/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/__init__.py)
(
~~~

mamba list:
~~~
(draxtestoldjax) traversaro@IITICUBLAP257:~$ mamba list
# packages in environment at /home/traversaro/miniforge3/envs/draxtestoldjax:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.4.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.5           py311h459d7ec_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py311hd4cff14_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h409f033_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
chex                      0.1.82             pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
cryptography              41.0.3          py311h63ff55d_0    conda-forge
cuda-version              11.8                 h70ddcb2_2    conda-forge
cudatoolkit               11.8.0              h4ba93d1_12    conda-forge
cudnn                     8.8.0.121            h838ba91_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distrax                   0.1.3                    pypi_0    pypi
dm-tree                   0.1.8           py311hbec7ed6_0    conda-forge
flatbuffers               23.5.26              h59595ed_1    conda-forge
frozenlist                1.4.0           py311h459d7ec_0    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
google-auth               2.23.0             pyh1a96a4e_0    conda-forge
google-auth-oauthlib      1.0.0              pyhd8ed1ab_1    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.54.3          py311hcafe171_0    conda-forge
h5py                      3.9.0           nompi_py311h3839ddf_102    conda-forge
hdf5                      1.14.2          nompi_h4f84152_100    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
jax                       0.4.8                    pypi_0    pypi
jaxlib                    0.4.7                    pypi_0    pypi
keras                     2.12.0             pyhd8ed1ab_0    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           18_linux64_openblas    conda-forge
libcblas                  3.9.0           18_linux64_openblas    conda-forge
libcurl                   8.3.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_0    conda-forge
libgfortran-ng            13.2.0               h69a702a_0    conda-forge
libgfortran5              13.2.0               ha4646dd_0    conda-forge
libgomp                   13.2.0               h807b86a_0    conda-forge
libgrpc                   1.54.3               hb20ce57_0    conda-forge
libjpeg-turbo             2.1.5.1              hd590300_1    conda-forge
liblapack                 3.9.0           18_linux64_openblas    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               3.21.12              hfc55251_2    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
markdown                  3.4.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py311h459d7ec_0    conda-forge
ml_dtypes                 0.2.0           py311h320fe9a_1    conda-forge
multidict                 6.0.4           py311h2582759_0    conda-forge
nccl                      2.18.5.1             h6103f9b_1    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
numpy                     1.25.2          py311h64a7726_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
protobuf                  4.21.12         py311hcafe171_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.5          hab00c5b_0_cpython    conda-forge
python-flatbuffers        23.5.26            pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
scipy                     1.11.2          py311h64a7726_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
tensorboard               2.12.3             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py311h9b4c7bb_0    conda-forge
tensorflow-base           2.12.1          cuda112py311hb0f8ee9_0    conda-forge
tensorflow-probability    0.20.0             pyhd8ed1ab_0    conda-forge
termcolor                 2.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
werkzeug                  2.3.7              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
wrapt                     1.15.0          py311h2582759_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.9.2           py311h459d7ec_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
~~~

**Comment by flferretti** [comment]
> So basically this is blocked by [conda-forge/tensorflow-probability-feedstock#46](https://github.com/conda-forge/tensorflow-probability-feedstock/pull/46) that itself is blocked by [conda-forge/tensorflow-feedstock#329](https://github.com/conda-forge/tensorflow-feedstock/pull/329) .

Actions fail also after the two PRs that introduced `tensorflow-probability==0.21.0` on conda-forge. The problem does not show with the same version on `pip`


Output of:
```python
diff -rwx "*.pyc" tensorflow_probability_conda tensorflow_probability_pip | grep -v "test"
```
<details>
<summary>diff</summary>

```diff
Only in tensorflow_probability_conda/python/distributions: discrete_rejection_sampling.py
Only in tensorflow_probability_conda/python/distributions/internal: correlation_matrix_volumes_lib.py
Only in tensorflow_probability_conda/python/distributions/internal: correlation_matrix_volumes.py
Only in tensorflow_probability_conda/python/distributions: vector_exponential_linear_operator.py
Only in tensorflow_probability_conda/python/experimental/mcmc: internal
Only in tensorflow_probability_conda/python/experimental/mcmc: run.py
Only in tensorflow_probability_pip/python/internal/backend: jax
Only in tensorflow_probability_conda/python/mcmc: eight_schools_hmc.py
diff --color -rwx '*.pyc' tensorflow_probability_conda/python/version.py tensorflow_probability_pip/python/version.py
36a37
> if __version__.endswith('dev'): __version__ += '20230804'
Only in tensorflow_probability_pip/substrates/jax: bijectors
Only in tensorflow_probability_pip/substrates/jax: distributions
Only in tensorflow_probability_pip/substrates/jax: experimental
Only in tensorflow_probability_pip/substrates/jax: glm
Only in tensorflow_probability_pip/substrates/jax: internal
Only in tensorflow_probability_pip/substrates/jax: math
Only in tensorflow_probability_pip/substrates/jax: mcmc
Only in tensorflow_probability_pip/substrates/jax: monte_carlo
Only in tensorflow_probability_pip/substrates/jax: optimizer
Only in tensorflow_probability_pip/substrates/jax: random
Only in tensorflow_probability_pip/substrates/jax: stats
Only in tensorflow_probability_pip/substrates/jax: sts
Only in tensorflow_probability_pip/substrates/jax: util
Only in tensorflow_probability_pip/substrates/jax: vi
Only in tensorflow_probability_pip/substrates/numpy: bijectors
Only in tensorflow_probability_pip/substrates/numpy: distributions
Only in tensorflow_probability_pip/substrates/numpy: experimental
Only in tensorflow_probability_pip/substrates/numpy: glm
Only in tensorflow_probability_pip/substrates/numpy: internal
Only in tensorflow_probability_pip/substrates/numpy: math
Only in tensorflow_probability_pip/substrates/numpy: mcmc
Only in tensorflow_probability_pip/substrates/numpy: monte_carlo
Only in tensorflow_probability_pip/substrates/numpy: optimizer
Only in tensorflow_probability_pip/substrates/numpy: random
Only in tensorflow_probability_pip/substrates/numpy: stats
Only in tensorflow_probability_pip/substrates/numpy: sts
Only in tensorflow_probability_pip/substrates/numpy: util
Only in tensorflow_probability_pip/substrates/numpy: vi
```

</details>

**Comment by traversaro** [comment]
> After some investigation I found out that the files inside substrates/ were not installed due to a patch on tfp feedstock. In fact, applying that patch before installing with pip brings to the same error.

Thanks for investigating, this explains also https://github.com/conda-forge/staged-recipes/pull/23973#issuecomment-1719059296 I think.

**Comment by traversaro** [comment]
> @conda-forge/tensorflow-probability do you have any suggestion on that

If you can reproduche issue simply with: 

~~~
from tensorflow_probability.substrates.jax import bijectors
~~~

or a similar command, probably you can just open an issue on tensorflow-probability-feedstock repo for better visibility?

**Comment by flferretti** [comment]
This should be solved as soon as https://github.com/conda-forge/tensorflow-probability-feedstock/pull/50 gets merged

**Comment by traversaro** [comment]
There is still a pip check failure, but I guess it is tensorflow related, so we can just remove the pip check

**Comment by traversaro** [comment]
The Windows failure is expected, as this is a `noarch: python` package whose some of the deps are not available on Windows. The failure will not be present in the generated feedstock as only Linux CI runs for `noarch: python` packages, thanks @flferretti for all the work! @conda-forge/help-python @conda-forge/staged-recipes the PR is ready for review, thanks!

**Review by awvwgk — CHANGES_REQUESTED** [review]
Note that this currently also installs things outside of the distrax namespace ([log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=814526&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1113)):

````
  adding 'examples/flow.py'
  adding 'examples/hmm.py'
  adding 'examples/vae.py'
  adding 'requirements/requirements-examples.txt'
  adding 'requirements/requirements-tests.txt'
  adding 'requirements/requirements.txt'
````

Those should be removed from the conda package as they don't belong in the distribution.

**Comment by flferretti** [comment]
Thanks @awvwgk, ready for review

**Pull request merged**
