### PR TITLE
add xlayers

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @cspencerjones and @tjcrone.

xref.: https://github.com/pangeo-data/pangeo-cloud-federation/pull/491

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge/stage-recipes team, what is going on with this numpy mkl conflict?

**Comment by npavlovikj** [comment]
I think part of the error is that `dask-core` is built with `python >=3.6`, https://github.com/conda-forge/dask-core-feedstock/blob/master/recipe/meta.yaml. In this recipe, you don't restrict the Python version and the conflicts occur for Python 2.7. Looks like `xlayers` is Python 3, https://pypi.org/project/xlayers/, so maybe try skipping Python 2.7?

**Comment by ocefpaf** [comment]
> I think part of the error is that `dask-core` is built with `python >=3.6`, [conda-forge/dask-core-feedstock:recipe/meta.yaml@`master`](https://github.com/conda-forge/dask-core-feedstock/blob/master/recipe/meta.yaml) [](/conda-forge/dask-core-feedstock/blob/HEAD@{2020-01-11T01:30:59Z}/recipe/meta.yaml). In this recipe, you don't restrict the Python version and the conflicts occur for Python 2.7. Looks like `xlayers` is Python 3, [pypi.org/project/xlayers](https://pypi.org/project/xlayers/), so maybe try skipping Python 2.7?

That is probably it. Thanks @npavlovikj! (I forget we no longer have a build matrix here so we can inspect each Python version in its own CI log.)

**Comment by tjcrone** [comment]
Thank you @ocefpaf!!

**Comment by ocefpaf** [comment]
@conda-forge/staged-recipes this is ready for review. I'll work on the Windows build in the feedstock. (Fortran on Windows is always annoying. It may be worth re-writing this in cython instead @cspencerjones. Take a look at [this fortran-cython exercise](https://github.com/ioos/ciso/blob/master/ciso/_ciso.pyx) as an example.)

**Comment by ocefpaf** [comment]
Thanks @npavlovikj for the save and @chrisburr for the merge!

**Comment by npavlovikj** [comment]
Glad to help @ocefpaf  :)

**Pull request merged**
