### PR TITLE
Add pydocstyle package

### PR DESCRIPTION
**Pull request by goanpeca**
Pinging @nurdok in case they'd like to be added as a maintainer to the pydocstyle package on conda-forge, a library of community-build conda packages.

The maintenance burden here is light: all testing and releases are built and deployed automatically with CI. Changes to how the package is being built can be controlled by changing the recipe which will be located at https://github.com/conda-forge/pydocstyle-feedstock shortly after this PR is finished and merged.

If you aren't interested in helping maintain the build, that's entirely fine too.

----

## pydocstyle

Python docstring style checker

(formerly pep257)

pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.

pydocstyle supports most of PEP 257 out of the box, but it should not be considered a reference implementation.

The framework for checking docstring style is flexible, and custom checks can be easily added, for example to cover NumPy docstring conventions.

### CODE REVIEW

**Comment by goanpeca** [comment]
@ocefpaf, I thought this url was supposed to work...


https://pypi.io/packages/source/i/pydocstyle/pydocstyle-{{ version }}.zip
https://pypi.io/packages/source/i/pydocstyle/pydocstyle-1.0.0.zip

**Comment by ocefpaf** [comment]
> @ocefpaf, I thought this url was supposed to work...
`https://pypi.io/packages/source/i/pydocstyle/pydocstyle-{{ version }}.zip`
https://pypi.io/packages/source/i/pydocstyle/pydocstyle-1.0.0.zip

Change the `i` to `p`and it will work.

https://pypi.io/packages/source/p/pydocstyle/pydocstyle-1.0.0.zip

**Comment by goanpeca** [comment]
:+: will do

**Comment by goanpeca** [comment]
How much time is reasonable to wait for the original author to respond regarding co-maintenace of the package?

**Comment by ocefpaf** [comment]
> How much time is reasonable to wait for the original author to respond regarding co-maintenace of the package?

Good question. Ideally you don't add s/he until you have an answer. So you can remove the GitHub handle and, if you get an answer eventually, you or themselves can add it back in the feedstock. That way we don't hold the package here.

**Comment by goanpeca** [comment]
Ok then this one should be good to go :-)

**Comment by Nurdok** [comment]
Hi, 

First of all, I'm very happy to see folks interested in pydocstyle and integrating with it. 
Regarding the listing here - I don't mind being listed as maintainer so I will have a "last resort" way of helping if some change in pydocstyle breaks this recipe.

**Comment by ocefpaf** [comment]
>  I don't mind being listed as maintainer so I will have a "last resort" way of helping if some change in pydocstyle breaks this recipe.

Awesome! Thanks @Nurdok!!

@goanpeca

You can use `[skip ci]` when re-adding the maintainer so we can merge this quick.

**Comment by ocefpaf** [comment]
> Hmmmm circleci ignore the `[skip ci]`

Yeah. That one likes to run no matter what :smile: we can merge it anyways. Thanks @goanpeca and @Nurdok!

**Comment by goanpeca** [comment]
@ocefpaf I think it would be very helpful if we had a Pull request template like

https://github.com/blog/2111-issue-and-pull-request-templates

```markdown
Pinging <@authors> in case they'd like to be added as a maintainer(s) to the <package-name>
package on [conda-forge](https://conda-forge.github.io/), a library of community-build conda packages.

The maintenance burden here is light: all testing and releases are built and deployed
automatically with CI. Changes to how the package is being built can be controlled by
changing the recipe which will be located at https://github.com/conda-forge/<package-name>-feedstock shortly after this PR is finished and merged.

If you aren't interested in helping maintain the build, that's entirely fine too.

---

# <package-name>
Package description
```

**Comment by goanpeca** [comment]
@nurdok, no problem, actually is a good opportunity for you to see how it works :-)

**Comment by ocefpaf** [comment]
> @ocefpaf I think it would be very helpful if we had a Pull request template like

Yeah. I think that @183amir was working on that, but I guess it feel under the cracks. It is definitely worth doing.

**Comment by jakirkham** [comment]
Could we please add `pep257` for backcompat too?

**Comment by goanpeca** [comment]
Sure, will do in a minute

**Pull request merged**
