### PR TITLE
Add sdsl-lite-vgteam recipe

### PR DESCRIPTION
**Pull request by cartoonist**
This is [vgteam's](https://github.com/vgteam) fork of the Succinct Data Structure Library (SDSL). The original [SDSL 2](https://github.com/simongog/sdsl-lite) is already on [conda-forge](https://github.com/conda-forge/sdsl-lite-feedstock), but the project is no longer maintained. This is one of the active forks until SDSL 3 is released.

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by cartoonist** [comment]
@conda-forge/help-c-cpp, ready for review.

**Comment by cartoonist** [comment]
@conda-forge-admin, please ping team

**Comment by carterbox** [comment]
Please standby we will be discussing how to handle forks of abandoned packages at the next conda-forge community meeting.

**Comment by carterbox** [comment]
@cartoonist, We finally had a discussion about publishing forks with the conda-forge core team. A summary of this discussion [is above](https://github.com/conda-forge/conda-forge.github.io/issues/1851).

As mentioned in the discussion, although this package could be merged with name `vgteam-sdsl-lite`, strongly prefer that you rebrand or move to take ownership over the upstream project. This is because using the same library name will cause file/namespace conflicts which cannot be fully mitigated.

**Comment by cartoonist** [comment]
@carterbox Thanks for the clarification!

Actually, I am not the author of this library, so rebranding is not an option for me. I will let the authors know to decide about it. Now that you mentioned it, I wonder if it is acceptable to distribute others' projects on conda without their explicit permission?

The reason I am creating this recipe is that this fork is one of the dependencies of my project which I want to distribute it via conda. However, I came to know about the other fork (`sdsl3`) mentioned in the discussion you sent (#17965). That might be a viable alternative for me without publishing another fork on conda.

**Comment by carterbox** [comment]
> is acceptable to distribute others' projects on conda without their explicit permission?

Only if the project has a license which allows redistribution. GPL allows this.

**Pull request closed without merging**
