### PR TITLE
first stab at a python-metar recipe

### PR DESCRIPTION
**Pull request by phobson**
attn: @akrherz

### CODE REVIEW

**Comment by akrherz** [comment]
thanks @phobson , I need to get pypi sorted out yet with Tom as he likely still owns that project there.

**Comment by akrherz** [comment]
Ah, @natemara maintains the pypi project.  Wonder what the procedure is to get me added as a maintainer there or to see if he wants to effort this work :)

**Comment by natemara** [comment]
I'm not really familiar with this conda-forge project, but let me know if there's something that I could do to help.

**Comment by akrherz** [comment]
Hi @natemara ! Thanks for the comment.  I think we just need your help with the `python-metar` project on pypi, can I be made a maintainer too or can you effort uploading releases there when we make releases :)

**Comment by ocefpaf** [comment]
Thanks @phobson!

**Comment by natemara** [comment]
@akrherz Sure, what's your username on PyPi?

**Comment by akrherz** [comment]
@natemara thank so much!  I'm @akrherz there too :smile_cat:

**Comment by natemara** [comment]
No problem, I added you as a maintainer.

**Comment by phobson** [comment]
Thanks for the merge, @ocefpaf

**Comment by ocefpaf** [comment]
> Thanks for the merge, @ocefpaf

My pleasure.

**Pull request merged**
