### PR TITLE
Adding bincopy module

### PR DESCRIPTION
**Pull request by nisharai1**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by nisharai1** [comment]
Hi @davidbrochart, @martinRenou , @SylvainCorlay ,  @wolfv 
Could you please help me to know why this build is failing only for osx.
The error is: <strong>modulenotfound: conda-build, but I can see conda-build is available in rb-conda channel.</strong>
Thank you in advance!

**Comment by nisharai1** [comment]
Hi @conda-forge/help-python Could you please help me understand why this build is failing only for osx
Thank you for your time!

**Comment by synapticarbors** [comment]
@nisharai1 -- apologies for this PR's review request not being replied to. Could you push an empty commit to your branch to re-trigger the CI (or possibly merge in the latest `main` from upstream)? I'm unable to re-run it manually for some reason. The original error message is gone, so I want to see if it fails again and why.

**Comment by nisharai1** [comment]
Hi @synapticarbors 
I appreciate your response. I've added an empty commit to this branch to initiate the CI process again and highlight the failure. Could you kindly provide insights into the cause of this failure?

**Comment by nisharai1** [comment]
Hi @synapticarbors 
The build has now passed, and I'm unsure why it was failing initially. Nevertheless, everything appears to be functioning correctly now. Would you kindly merge the PR so that I can incorporate this module into my project? 
Thank you!

**Pull request merged**
