### PR TITLE
add COIN OR recipes

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by wolfv** [comment]
this is in preparation of adding google-or tools (https://github.com/google/or-tools)

**Comment by isuruf** [comment]
Duplicate of https://github.com/conda-forge/coincbc-feedstock

**Comment by wolfv** [comment]
thanks for finding that @isuruf! 

Hmm, I'll try to coordinate with the folks on that recipe to split the packages up ...

**Comment by tkralphs** [comment]
Actually, there seem to be quite a few recipes out there.

https://anaconda.org/search?q=cbc

It would be great to have a definitive one that we are in the loop on and will promote as "the way" to install cbc on conda. But yes, it would be great to have it split up by individual projects so that we can also eventually have recipes for other solvers installed that have the same dependencies. As a template, once could use the existing homebrew recipes:

https://github.com/coin-or-tools/homebrew-coinor

**Comment by wolfv** [comment]
I have nice recipes that split the packages and use cmake as a build tool. I’ll make a or combining them into one recipe of multiple outputs.

**Pull request closed without merging**
