### PR TITLE
add libxfoil

### PR DESCRIPTION
**Pull request by looooo**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by looooo** [comment]
@isuruf anay idea why this works for liblapack-feedstock but not with this feedstock? `dumpbin` seems to be not available.
ref.: https://github.com/conda-forge/lapack-feedstock/blob/master/recipe/bld.bat#L23L29

**Comment by isuruf** [comment]
You need a compiler activation package like vs2008_win-64 for the env to be correctly set up.

**Comment by looooo** [comment]
@conda-forge/core please review and merge
windows didn't work out, but I think we can do this later if someone wants windows support.

**Comment by looooo** [comment]
Thx.

**Pull request merged**
