### PR TITLE
Add xorg-makedepend

### PR DESCRIPTION
**Pull request by epruesse**

### CODE REVIEW

**Comment by epruesse** [comment]
@conda-forge/core Package should be ready. Could you review && merge?

(BTW: I'm not sure why AppVeyor isn't running on this PR.)

**Comment by pkgw** [comment]
Once more, ping @ocefpaf @jakirkham ; this one is also missing an AppVeyor run though.

**Comment by ocefpaf** [comment]
And one more close/open :wink:

**Comment by ocefpaf** [comment]
@pkgw we got AppVeyor running in your two previous ping but it did not start here. Let's wait a little bit and we can try closing/opening it again.

We get rate limited easily due to the large number of MNT re-rendering issued at night to catch up with conda-smithy changing six for half a dozen :unamused:

**Comment by pkgw** [comment]
Ah. Is there any straightforward way to keep tabs on the AppVeyor rate-limiting status? I know that I've seen similar diagnostic output in the jobs that turn staged-recipes PRs into feedstocks ...

**Comment by ocefpaf** [comment]
I usually have the `AppVeyor` site openned in a tab to check that but I am not sure if there is a better way. Ideally `AppVeyor` should send a "failure to start: message back in the PR.

**Comment by epruesse** [comment]
@ocefpaf The other checks came through. Still no AppVeyor though.

**Comment by ocefpaf** [comment]
> @ocefpaf The other checks came through. Still no AppVeyor though.

Just started it manually. Fingers crossed.

**Comment by epruesse** [comment]
@ocefpaf Can you restart individual AppVeyor builds out of the matrix? The py36 one exited with some random API failures:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.12916/job/sfdipxapbpeq0a51#L95

**Comment by ocefpaf** [comment]
I restarted the the PR for you. (We can't restart a single one on AppVeyor.)

**Comment by epruesse** [comment]
Now it says it's an outdated PR... guess I'll rebase.

**Comment by jakirkham** [comment]
That must be an old build that updated the status. It was still running [here]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.12968 ).

**Comment by epruesse** [comment]
It had been looking at build [1.0.12967](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.12967/)... Why is [1.0.12968](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.12968) running on the same commit?

**Comment by jakirkham** [comment]
That's what happens when a build gets restarted. Is there something more to this question? 😕

**Comment by epruesse** [comment]
@jakirkham I meant why there were two consecutive builds as a consequence of the restart, ...67 and ...68. Doesn't matter though. All checks passed so all is good.

Would you have time to review and merge this and [my other X11 PRs](https://github.com/conda-forge/staged-recipes/pulls/epruesse) so that I an get to work on the second stage/dependent packages?

**Comment by pkgw** [comment]
I can take a look at these and merge them if you'd like ... although, to the best of my understanding, it won't do much good until the initialization of new feedstocks is fixed (cf [this status issue](https://github.com/conda-forge/status/issues/32)).

**Comment by epruesse** [comment]
I know. :( Wish I could do sth about that, but Travis is tricky enough when it's your own recipe collection you try to build.

Still, I'd appreciate if you could review & merge. That way all that's left is waiting for the Travis registration thing to be fixed.

**Comment by jakirkham** [comment]
Travis CI at staged-recipes is extremely close to the time limit. If we merge anything else, it won't clear at all because it will be unable to run through the all the backlogged recipes in the time limit. Not to mention this will force us to back out some of the recipes. While I understand that people are eager to see their recipes merged, until we can make a significant dent in the backlog, additional merges will just complicate the problem to no one's benefit. So please be patient.

**Comment by jakirkham** [comment]
So I think we have resolved the underlying issue that was causing the backlog. A good chunk (though not all) of the recipes have cleared out of staged-recipes.

Should be fine to start merging things again. Just note that CIs may be a bit slow given the large number of feedstock additions that are occurring.

**Comment by pkgw** [comment]
Yup, looks like things are moving again. Here we go.

**Comment by epruesse** [comment]
Thx guys! :)

**Pull request merged**
