### PR TITLE
Add 46 more Apache Airflow providers

### PR DESCRIPTION
**Pull request by xylar**
This PR continues #13958

The providers in these recipes depend on `apache-airflow >=2.0.0`, which has just been added in https://github.com/conda-forge/airflow-feedstock/pull/63.  All other dependencies are already available on conda-forge.

Several remaining providers will be added in a later PR, after dependencies are added or issues with dependencies are addressed.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xylar** [comment]
The `win` build failure is expected, since `apache-airflow` is not available for `win`.

**Comment by xylar** [comment]
@conda-forge/help-python, this is a monster but I think it's ready to review.  Please let me know if it would be more helpful for you if it were multiple PRs.

**Comment by beckermr** [comment]
I'm ok with this. It is going to hammer on staged recipes for a while, but that seems fine.

**Comment by chrisburr** [comment]
😨 This should be an interesting stress test for the CI... 😆

**Comment by beckermr** [comment]
here we go!

**Comment by xylar** [comment]
Thanks @beckermr and @chrisburr!  So far, so good (I'm getting a lot of notices).

**Comment by beckermr** [comment]
yeah I bet w/ 46 feedstocks - you might consider automerge....

**Comment by xylar** [comment]
It'll be closer to 60 some in the end.  I'll get a sense for how much they update but likely it'll be a flurry all at once a few times a year.

**Pull request merged**
