### PR TITLE
Add `opentrons` recipes

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge/staged-recipes, ready for your review.

**Comment by mrakitin** [comment]
FYI: the suggested patch in https://github.com/Opentrons/opentrons/pull/8154 was merged by the code developers.

The build commands are based on the steps in https://github.com/Opentrons/opentrons/blob/edge/Dockerfile, that's why I had to build wheels first, and then install from them.

Is there anything I can do to improve it? I'd like to have it merged soon, as it's a missing dependency of https://github.com/conda-forge/lixtools-feedstock/pull/1 that was not discovered during our work on #15648 with @kbeeperez.

**Comment by mrakitin** [comment]
I see one improvement that can be done: combining two `meta.yaml` files into one as it uses the same source. But I am not sure how to properly do it with the [`outputs`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section) feature. Do you have any good examples where it's done, so that I could use it here too? Not sure how to deal with two sets of `build.sh` & `bld.bat` in this case though... Suggestions are welcome and highly appreciated.

**Comment by dopplershift** [comment]
The [matplotlib feedstock](https://github.com/conda-forge/matplotlib-feedstock) has a decent example of how to handle it. You can have the different sets of build scripts under different names and manually list them in `meta.yaml`.

**Comment by mrakitin** [comment]
This is a really good example from my co-worker, thanks @dopplershift! I see how it can be done now and will work on it tomorrow.

**Comment by mrakitin** [comment]
@dopplershift, ready for your review! Thanks.

**Comment by mrakitin** [comment]
@conda-forge/staged-recipes, ready for review! https://github.com/conda-forge/lixtools-feedstock/pull/1 needs this missing dependency. Thank you.

**Comment by mrakitin** [comment]
@conda-forge/staged-recipes friends, could this please be merged soon? We plan to test the packages at NSLS-II next week (Wednesday, August 4), it would be great to have the packages from this PR available. Thanks a lot for your cooperation and help!

**Review by dopplershift — APPROVED** [review]

**Comment by mrakitin** [comment]
Thank you, @dopplershift!

**Pull request merged**
