### PR TITLE
Add abc classroom to Conda Forge

### PR DESCRIPTION
**Pull request by lwasser**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks!

**Comment by lwasser** [comment]
hi there @scopatz  👋  the last commit was still failing CI on the windows side of things.  i'm just curious. did you somehow fix it? i didn't understand the error message but that list below is each of our CLI commands. the message was:
```
WARNING: failed to get_linkages, codefile_type('C:\Miniconda\conda-bld\abc-classroom_1599781120730\_h_env\Scripts\abc-new-template.exe')=EXEfile
WARNING: failed to get_linkages, codefile_type('C:/Miniconda/conda-bld/abc-classroom_1599781120730/_h_env\Scripts\abc-clone.exe')=EXEfile
WARNING: failed to get_linkages, codefile_type('C:/Miniconda/conda-bld/abc-classroom_1599781120730/_h_env\Scripts\abc-update-template.exe')=EXEfile
WARNING: failed to get_linkages, codefile_type('C:/Miniconda/conda-bld/abc-classroom_1599781120730/_h_env\Scripts\abc-quickstart.exe')=EXEfile
WARNING: failed to get_linkages, codefile_type('C:/Miniconda/conda-bld/abc-classroom_1599781120730/_h_env\Scripts\abc-feedback.exe')=EXEfile
WARNING: failed to get_linkages, codefile_type('C:/Miniconda/conda-bld/abc-classroom_1599781120730/_h_env\Scripts\abc-init.exe')=EXEfile
   INFO: sysroot: 'C:/Windows/' files: '['winhlp32.exe', 'win.ini', 'twain_32/wiatwain.ds', 'twain_32.dll']'
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=207648&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77&l=775

**Comment by scopatz** [comment]
noarch python recipes only need to pass on Linux

**Comment by scopatz** [comment]
And also hi @lwasser! :wave:

**Comment by lwasser** [comment]
thank you @scopatz that sounds great! i didn't realize i only needed the linux green light.
Many thanks. Have a terrific weekend!

**Pull request merged**
