### PR TITLE
rename mu-repo

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by ericdill** [comment]
Does the folder have to match the package/name field?

**Comment by ocefpaf** [comment]
I don't think this is still necessary b/c @minrk submitted a PR to fix this some time ago... But it was worth a try and I am not in the mood to debug the CI log early in the morning :smile:

**Comment by ericdill** [comment]
> I don't think this is still necessary b/c @minrk submitted a PR to fix this some time ago.

Ah cool. I'm going to have a bajillion questions like this as I get fully up to speed

> But it was worth a try and I am not in the mood to debug the CI log early in the morning 

I can't imagine why not 😆

**Comment by minrk** [comment]
I submitted the PR, but it's still open: #2313

**Comment by ocefpaf** [comment]
> I submitted the PR, but it's still open: #2313

Sorry @minrk I thought that was already merged a long time ago.
I just merged it and I will be testing it soon.

**Pull request merged**
