### PR TITLE
Remove VS 2008 64-bit workaround

### PR DESCRIPTION
**Pull request by jakirkham**
This reverts the changes made in this PR ( https://github.com/conda-forge/staged-recipes/pull/251 ). `conda-build` 1.20.1 includes a fix that @patricksnape and @msarahan worked on that addresses this problem. We have tested that this does indeed fix it by trying to build Eigen without this workaround using only `conda-build` 1.20.1 ( https://github.com/conda-forge/eigen-feedstock/pull/6 ). As this was the first use case that required the workaround here, demonstration that it no longer needs it shows it has been corrected. Thus we can safely remove the workaround from staged-recipes.

Thanks everyone for their hard work in helping fix this tricky problem on Windows.

### CODE REVIEW

**Comment by jakirkham** [comment]
Ignoring the linter as there are intentionally no recipes here.

**Comment by scopatz** [comment]
Looks good to me, but I am not enough of a windows dev to judge.

**Comment by jakirkham** [comment]
Basically the conclusion reached at our meeting earlier today was test Eigen first (as it suffered from the problem that required this workaround), if we found that worked with only the new conda-build we would rip out these workarounds. That has been what we have found so this is just me holding up my end of the bargain.

**Comment by jakirkham** [comment]
Has anyone told you about the hackpad yet? ( https://conda-forge.hackpad.com/ )

If not, that is how we are organizing future meetings. Today's meeting was mainly about a Windows issue and was a special session one off for that topic. Normally we are trying to have them every other week on Friday at 1400 UTC. So, the next one is the general meeting. Feel free to tack on any topic you want discussed. If we don't address it in that meeting, it gets rolled over to the next meeting.

**Comment by scopatz** [comment]
Yeah, I know about the hackpad @jakirkham, but thanks for checking :).  I have been juggling too much lately to show up.  It is approaching finals.

**Comment by jakirkham** [comment]
No worries. Just wanted to make sure you were in the loop.

**Comment by pelson** [comment]
Super. Thanks for doing this @jakirkham

**Comment by jakirkham** [comment]
Unfortunately, as we have downgraded conda-build ( https://github.com/conda-forge/staged-recipes/pull/452 ), we may need this back. Though let's wait until we see an actual use case (e.g. a recipe that needs the workaround). Doing this add/remove dance burns cycles that could be better used.

**Comment by jakirkham** [comment]
Actually, never mind, I retract that comment.

We shouldn't need to bring the workaround back as the pinning should only be needed for Python 3.4. This means that Python 2.7 builds should still proceed correctly as they can still use conda-build 1.20.1.

**Pull request merged**
