### PR TITLE
Added recipe for fake-factory/faker

### PR DESCRIPTION
**Pull request by pmlandwehr**
Pinging @joke2k and @fcurella in case they'd like to be added as maintainers to the `fake-factory` builder on [conda-forge](http://conda-forge.github.io), a library of community-build [`conda`](http://conda.pydata.org) packages. The maintenance burden here is light: all testing and releases are built and deployed automatically with CI. Changes to how the package is being built can be controlled by changing the recipe which will be located at https://github.com/conda-forge/fake-factory-feedstock shortly after this PR is finished and merged. If you aren't interested in helping maintain the build, that is entirely fine too.

NOTE: In September, `fake-factory` will take over the namespace currently occupied by `faker` (no conda-forge feedstock). When that happens we'll need to fork and rename the feedstock.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
@ocefpaf do we need to include a `build.bat` to fix the issue environment variable issue causing the crash here?

**Comment by patricksnape** [comment]
Current failure is due to UTF8 encoding on Linux

**Comment by ocefpaf** [comment]
> @ocefpaf do we need to include a `build.bat` to fix the issue environment variable issue causing the crash here?

I believe you solved that. right? You should not need the `bld.bat` in this case.

**Comment by pmlandwehr** [comment]
Not sure that we want to set systemwide `PYTHONIOENCODING` on linux, so just tweaking it for the test run.

**Comment by patricksnape** [comment]
Looks good to me now

**Pull request merged**
