### PR TITLE
Added recipe for Perl module Pod::Escapes

### PR DESCRIPTION
**Pull request by xileF1337**
CondaForge port of recipe for Perl module Pod::Escapes. (It is currently on Bioconda only, but is a general-purpose module.)

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by xileF1337** [comment]
@conda-forge/bioconda-recipes any objections against porting this to CondaForge?

**Comment by xileF1337** [comment]
I'm skipping the Windows build as current Perl seems to be unavailable:
```
- nothing provides perl >=5.32.1,<6.0a0 *_perl5 needed by perl-extutils-makemaker-7.36-pl5321hd8ed1ab_0
- nothing provides perl >=5.32.1,<6.0a0 *_perl5 needed by perl-exporter-5.72-pl5321hd8ed1ab_0
```

**Comment by xileF1337** [comment]
@conda-forge/help-perl, ready for review!

**Comment by fgiacomoni** [comment]
@xileF1337 You are still stuck here...?

**Comment by fgiacomoni** [comment]
@conda-forge-admin we need a review here

**Comment by xileF1337** [comment]
> @xileF1337 You are still stuck here...? Same for me... No review on my recipe...

Hey @fgiacomoni , well, I kind of abandoned this recipe because I realized that it is a Perl core module only after I opened the PR. Core modules are already included in the perl package and do not need to be specified as separate requirements. 

Concerning your own recipe, feel free to mention @conda-forge/perl-packagers to get a review. Only few people from the  conda-forge team are using Perl, so it can take a moment. Currently, we are only two people in the perl-packagers team.

I'm closing this PR since the recipe should probably not be merged.

**Comment by xileF1337** [comment]
I take it you refer to https://github.com/conda-forge/staged-recipes/pull/22648 .

**Pull request closed without merging**
