### PR TITLE
ENH testing package for the bot subteam

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

FYI, the creation of this package was discussed at the bot subteam meeting so I have added them to the maintainers section.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/bot Does this seem good to you all? Did I miss anything?

**Comment by CJ-Wright** [comment]
Do we want a url so that the update bot can create PRs into it?

**Comment by beckermr** [comment]
I was thinking that but didn't know where to point it. I guess we can make a dummy package in the regro account and bump releases there. Will do.

**Comment by beckermr** [comment]
This is done. Merging.

**Pull request merged**
