### PR TITLE
re-parse nbgrader

### PR DESCRIPTION
**Pull request by ocefpaf**
[skip ci]

Closes https://github.com/conda-forge/nbgrader-feedstock/issues/18

Ping @jhamrick

### CODE REVIEW

**Comment by jhamrick** [comment]
Thanks @ocefpaf ! It looks like this is the recipe for 0.5.2 rather than 0.5.3, though. Should I resubmit another PR for 0.5.3?

**Comment by ocefpaf** [comment]
No need. The recipe here has no bearing (besides the name of the package) on what is going to happen next. The token will be refreshed and the `feedstock` will be re-rendered, but the recipe will remain unchanged.

**Comment by jhamrick** [comment]
Oh, ok, awesome. Thanks a lot!

**Comment by ocefpaf** [comment]
No problem. (Travis-CI is a bit overloaded lately, so it may take a while for the changes to appear in the feedstock.)

**Comment by jhamrick** [comment]
Ok, thanks for the heads up---that shouldn't be a problem.

**Pull request merged**
