### PR TITLE
Added recipe for matlab_kernel

### PR DESCRIPTION
**Pull request by stanmart**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] Source is from official source
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble be please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks @stanmart!  I'm happy to be added as a maintainer.  I think the license file in the recipe itself is supposed to be the conda-forge [one](https://github.com/conda-forge/jupyterlab-feedstock/blob/395ea5c428abd8b096279d4fe833692d42b7536b/LICENSE.txt).

**Comment by stanmart** [comment]
@conda-forge-admin, please rerender

**Comment by stanmart** [comment]
Ah, true, thanks! Reverted back to the original.

**Comment by stanmart** [comment]
@conda-forge-admin, please restart ci

**Comment by stanmart** [comment]
Hi @conda-forge/help-python, this recipe is ready for review.

**Pull request merged**
