### PR TITLE
added recipe for bioimageio.spec

### PR DESCRIPTION
**Pull request by k-dominik**
This PR adds the `bioimageio.spec` package, with tools to read/write bioimageio spec-compliant neural network specifications (among other cool stuff). 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by k-dominik** [comment]
Hey @oeway, @FynnBe, @constantinpape - could you please confirm (by commenting here) that you are willing to act as a maintainer for this package?

Cheers!

**Comment by oeway** [comment]
> Hey @oeway, @FynnBe, @constantinpape - could you please confirm (by commenting here) that you are willing to act as a maintainer for this package?

Yes, I confirm!

**Comment by constantinpape** [comment]
Happy to be listed here.

**Comment by FynnBe** [comment]
me too 👍

**Comment by k-dominik** [comment]
Hello @conda-forge/help-python, this PR is ready for review! Let me (us) know if we need to change anything. Thank you :)

**Review by dopplershift — APPROVED** [review]

**Comment by k-dominik** [comment]
thx @dopplershift for the review and the merge :)

**Pull request merged**
