### PR TITLE
Add recipe for crick

### PR DESCRIPTION
**Pull request by jcrist**

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @jcrist, can you please enable CircleCI for your fork of staged-rceipes. That way this PR will build on linux, Otherwise this looks good to me!

**Comment by jcrist** [comment]
@scopatz, thanks. I've enabled (or at least think I have) CircleCI on my fork, but can't seem to get it to build by closing and reopening the PR. Any docs/references you can point me too, or is this it? 

Also, out of curiousty, I remember CircleCI building for my PRs to conda forge in the past - when/why did this change occur?

**Comment by jakirkham** [comment]
It will require a new commit to trigger CircleCI.

**Comment by scopatz** [comment]
np @jcrist, this is the only documentation we have on this issue: http://conda-forge.github.io/docs/ciservices.html#enabling-circle-on-your-fork But I am not sure it will help you much at this point.

Earlier this month CircleCI "fixed" a bug where building is based off of the head, rather than the base, fork. This is now "fixed" across all of github and has since bit me elsewhere too.  I think conda-forge is uniquely affected by it though.

**Comment by jcrist** [comment]
Thanks for the information. This should be good to go now.

**Comment by mrocklin** [comment]
Is there anything else that needs to be done here?

**Comment by jcrist** [comment]
Should be good, just waiting on a merge. I assume people were/are off for the weekend/holiday.

**Pull request merged**
