### PR TITLE
Add bob.ip.flandmark recipe

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
This depends on https://github.com/conda-forge/opencv-feedstock/issues/5

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/opencv-feedstock/pull/16 ).

**Comment by 183amir** [comment]
The dependency on `opencv` has been removed.
I think this is good to be merged now.

**Comment by 183amir** [comment]
I'm going to merge this. Please let me know if you want changes in the feedstock.

**Comment by 183amir** [comment]
So I merged this and build failed on travis : https://travis-ci.org/conda-forge/staged-recipes/jobs/136459550
```
conda.resolve.NoPackagesFound:  Packages missing in current win-32 channels: 
  - bob.ip.draw
  - bob.ip.color
  - bob.core
  - bob.io.image
  - bob.io.base
  - bob.ip.base
  - bob.extension
  - bob.blitz
  - pkg-config
```
why is it looking for `win-32 channels`?
cc: @conda-forge/core

**Pull request merged**
