### PR TITLE
Added yeadon recipe.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
I'm not quite sure how to deal with this error:

```
===== testing package: yeadon-1.3.0-py27_0 =====
import: 'yeadon'
run_test.py: cannot connect to X server 
TESTS FAILED: yeadon-1.3.0-py27_0
```

This package imports mayavi and I think it must through this error because mayavi needs an X server. I added the same yum_requirements.txt as the mayavi recipe but that didn't seem to help.

**Comment by moorepants** [comment]
Maybe this is somehow a solution: http://stackoverflow.com/a/8606231/467314

**Comment by moorepants** [comment]
Getting this version conflict:

```
TEST START: yeadon-1.3.0-py35_0

Deleting work directory, /Users/travis/miniconda/conda-bld/yeadon_1485713609431/work/yeadon-1.3.0

...WARNING conda_build.build:create_env(725): failed to create env, retrying.  exception was: The following specifications were found to be in conflict:

  - mayavi >=4.0 -> numpy 1.7*|1.8*

  - mayavi >=4.0 -> python 2.7*

  - yeadon 1.3.0 py35_0
```

**Comment by moorepants** [comment]
On osx mayavi is only available for numpy 1.7, 1.8, and 1.9 with python 2.7.

**Comment by moorepants** [comment]
There also seems to be no python 3.6 support on any platform.

**Comment by moorepants** [comment]
@conda-forge/core This is ready for review.

**Comment by scopatz** [comment]
Thanks @moorepants!

**Comment by moorepants** [comment]
The merge seems to have failed on master. What do we do about that?

**Comment by scopatz** [comment]
Looks like the feedstock and package were uploaded.

**Comment by moorepants** [comment]
Yes, everything looks good not. Seems like a new merged PR forced the build again. Thanks!

**Pull request merged**
