### PR TITLE
add dbxfs and a bunch of deps

### PR DESCRIPTION
**Pull request by dougalsutherland**
This adds the alternative Dropbox client dbxfs, along with a bunch of dependencies, all of which are `noarch: python`.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
@conda-forge/staged-recipes, ready for review.

`fusepyng` needs `libfuse` to work / when imported, so ideally we'd set up a CDT package for that, but that's not a thing conda-forge really knows how to do yet. This is why the Travis build fails, because libfuse isn't present, but it's `noarch: python` so that's okay. (We can't package `libfuse`, it needs root.)

**Comment by scopatz** [comment]
Thanks @dougalsutherland!

**Comment by rianhunter** [comment]
This may need to patch out this code: https://github.com/rianhunter/dbxfs/blob/master/dbxfs/main.py#L120

**Comment by dougalsutherland** [comment]
Eh, I think it's probably fine...out-of-date warnings are a good thing for a package like this, it just does tells you the wrong update step if you're installing with conda.

By the way @rianhunter, if you want to be added as a maintainer to some of these packages (so you can push out version updates on conda too yourself), just let me know. (We have a bot that sends PRs when a new version comes out, e.g. https://github.com/conda-forge/dbxfs-feedstock/pull/1, the recipe just needs to be tweaked if a dependency changed and then hit merge.)

**Comment by rianhunter** [comment]
No thanks, I have enough on my plate :)

**Pull request merged**
