### PR TITLE
added mesmerize-core

### PR DESCRIPTION
**Pull request by kushalkolar**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by kushalkolar** [comment]
@conda-forge-admin, please ping conda-forge/core

One of my dependencies, `caiman`, requires `tensorflow`. However `tensorflow` windows builds do not exist in `conda-forge`.

This is the `caiman` feedstock if that helps: https://github.com/conda-forge/caiman-feedstock

Thanks!

**Comment by dopplershift** [comment]
Since this is noarch, we can ignore any build failures on Windows due to missing dependencies. Still need to fix the builds on the other platforms, though.

**Comment by kushalkolar** [comment]
How do we resolve the issue with conda-forge/tensorflow not having a windows package though? The default anaconda channel does have a tensorflow windows package. With the current recipe, linux & mac do build if I remove the `conda_build_config.yml` (I added this file to attempt to add additional channels, based on what I saw in the `caiman` conda-feedstock)

**Comment by dopplershift** [comment]
You don't need to resolve it. As a noarch package, it's only ever going to be built on linux. If the user is on a platform with tensorflow (including having their own conda installed configured to pull packages from defaults), then it will install fine. If not, the user will get an error about a missing dependency.

Either way, we just ignore the CI Windows failure here.

**Comment by dopplershift** [comment]
The error you're getting is about `conda_build_config.yml` being malformed. I'd say just remove it.

**Comment by kushalkolar** [comment]
ah ok, I thought this tested build & installation. Linux is passing now with removal of `conda_build_config.yaml` so it should be good to go! Thanks a lot for the help!!

**Comment by kushalkolar** [comment]
@conda-forge-admin, please ping conda-forge/help-python

ready for review!

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
