### PR TITLE
Adding crispresso2 package

### PR DESCRIPTION
**Pull request by mbowcut2**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Colelyman** [comment]
@conda-forge/bioconda-recipes There certainly is a [`crispresso2` recipe](https://anaconda.org/bioconda/crispresso2) in the bioconda channel, however the bioconda channel doesn't provide builds for ARM architecture. We were hoping to have an ARM-only build on `conda-forge` to make ARM installation easier. Is this something reasonable that we can do?

**Comment by Colelyman** [comment]
Also, with respect to the license, we have a custom license that allows for free non-commercial use (academic, non-profit, etc.) but a license fee is required for commercial use. Does the license have to be an SPDX identifier?

**Comment by mbowcut2** [comment]
@conda-forge/staged-recipes ready for review.

**Comment by carterbox** [comment]
> Also, with respect to the license, we have a custom license that allows for free non-commercial use (academic, non-profit, etc.) but a license fee is required for commercial use.

The license of this project does not allow us to redistribute the software.

> Does the license have to be an SPDX identifier?

Strictly no, but licenses from that list allow us to do what we need on this channel.

**Pull request closed without merging**
