### PR TITLE
Add meteor

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@conda-forge/staged-recipes : Aren't we allowed to use '-' in the version?

**Comment by isuruf** [comment]
https://conda.io/docs/user-guide/tasks/build-packages/package-spec.html#info-index-json

**Comment by sannykr** [comment]
@isuruf : Thanks. I have removed the "beta" from the version and added it to the url.

**Comment by isuruf** [comment]
That's wrong. Replace `-` with `.`

**Comment by sannykr** [comment]
@isuruf : Thanks. But, that url will now work now because it had -

**Comment by sannykr** [comment]
@isuruf : If I replace - with ., then it doesn't download that version.

**Comment by isuruf** [comment]
Yes, don't replace `-` in the url.

**Pull request closed without merging**
