### PR TITLE
Add recipe for Snap

### LINKED ISSUE #5849: Package SNAP for Python
According to http://snap.stanford.edu/snappy/index.html:

> Snap.py is a Python interface for SNAP. SNAP is a general purpose, high performance system for analysis and manipulation of large networks. SNAP is written in C++ and optimized for maximum performance and compact graph representation. It easily scales to massive networks with hundreds of millions of nodes, and billions of edges.
> 
> Snap.py provides performance benefits of SNAP, combined with flexibility of Python. Most of the SNAP functionality is available via Snap.py in Python. 

Here is the GitHub repo for [snap-python](https://github.com/snap-stanford/snap-python) and [snap](https://github.com/snap-stanford/snap).  However, I'm not sure on the proper way to bundle C++ code within the recipe.

### PR DESCRIPTION
**Pull request by CurtLH**
Closes #5849

### CODE REVIEW

**Comment by CurtLH** [comment]
@conda-forge/bioconda-recipes -- it appears as though this proposed recipe conflicts with the [Snap recipe in bioconda]()https://anaconda.org/bioconda/snap). However, based on the description, I believe these are two different recipes.

*Bioconda Snap*
> Semi-HMM-based Nucleic Acid Parser -- gene prediction tool

*This Snap*
> General purpose, high performance system for analysis and manipulation of large networks

**Comment by mbargull** [comment]
Ugh, a four-letter name collision... Any thoughts or naming suggestions for either package, @conda-forge/bioconda-recipes @conda-forge/core?
The SNAP from Bioconda is marginally older (but also obviously outdated) acc. to the dates given in http://korflab.ucdavis.edu/Software/ and renaming packages is never the nicest thing to do.
But he SNAP from this PR has more recent/consistent releases (http://snap.stanford.edu/releases/) and is likely more relevant.

**Comment by scopatz** [comment]
@mbargull @CurtLH - are they in different languages? That would be one way to disambiguate

**Comment by CurtLH** [comment]
For the naming conflict, I propose `cpp-snap`.  I think this makes sense given the direction of conversation in [this issue](https://github.com/conda-forge/conda-forge.github.io/issues/590) and [this proposal](https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1).

**Comment by mbargull** [comment]
Oh, I'd be all-in for `cpp-*` due to overall consistency, too :smile:.
But for C++ it looks like we have more `*-cpp` or `*cpp` packages on conda-forge (albeit, not many overall, see output below) and the project itself talks about "SNAP for C++" and "Snap.py`, i.e., using suffixes rather prefixes.

IMHO, due to the reason you put out and also considering `*-something` suffixes are used for split packages, `cpp-*` is preferable. But I'd rather have someone else from @conda-forge/core give their opinion on this, too.

<details open><summary>

```bash
for chan in conda-forge bioconda; do                                                                                                          
    for x in cpp perl python py r; do
        for glob in "$x-*" "*-$x" "$x*" "*$x"; do
            echo -n "${chan}::${glob} "
            conda search --json "${chan}::${glob}" | jq 'if has("exception_name") then 0 else keys|length end'\
        done
    done
done | column -tR2
```
</summary>

```
conda-forge::cpp-*        0
conda-forge::*-cpp        9
conda-forge::cpp*         4
conda-forge::*cpp        17
conda-forge::perl-*       2
conda-forge::*-perl       0
conda-forge::perl*        3
conda-forge::*perl        1
conda-forge::python-*    80
conda-forge::*-python    14
conda-forge::python*     84
conda-forge::*python     23
conda-forge::py-*         5
conda-forge::*-py        16
conda-forge::py*        442
conda-forge::*py        116
conda-forge::r-*       1077
conda-forge::*-r          0
conda-forge::r*        1190
conda-forge::*r         377
bioconda::cpp-*           0
bioconda::*-cpp           0
bioconda::cpp*            0
bioconda::*cpp            3
bioconda::perl-*        531
bioconda::*-perl          5
bioconda::perl*         531
bioconda::*perl          10
bioconda::python-*       17
bioconda::*-python        6
bioconda::python*        19
bioconda::*python         8
bioconda::py-*            1
bioconda::*-py            3
bioconda::py*            85
bioconda::*py            39
bioconda::r-*           402
bioconda::*-r             1
bioconda::r*            494
bioconda::*r            466
```
</details>

**Comment by CurtLH** [comment]
Good point @mbargull.  I agree, lets wait and see what others think.

**Comment by CurtLH** [comment]
Any thoughts from @conda-forge/staged-recipes on the naming conflict?  I'm happy with either `snap-cpp` or `cpp-snap`.  🙂

**Comment by scopatz** [comment]
`snap-cpp` is my vote

**Comment by CurtLH** [comment]
Can someone from @conda-forge/staged-recipes help me with this recipe on Windows.  I'm not sure if there is a problem in building the Windows version or if the problem is just with my test.

This is the test that I'm using that appears to work as expected on Linux/OSX:

```
cd examples/graphgen && ./graphgen -g:w -n:1000 -k:4 -p:0.1 -o:smallworld.txt
```
I've tried altering the test command to be just for `# [win]`, and have tried many combinations of replacing `/` with `\` and removing `.`, but nothing seems to help. 

```(C:\bld\snap-cpp_1528771675369\_test_env) C:\bld\snap-cpp_1528771675369\test_tmp>cd examples/graphgen   && ./graphgen -g:w -n:1000 -k:4 -p:0.1 -o:smallworld.txt 
'.' is not recognized as an internal or external command,
operable program or batch file.
(C:\bld\snap-cpp_1528771675369\_test_env) C:\bld\snap-cpp_1528771675369\test_tmp\examples\graphgen>IF 9009 NEQ 0 exit /B 1 
```

---
## [SNAP on Windows with Visual Studio](http://snap.stanford.edu/snap/install.html)

Make sure that Visual Studio is installed on your system. Start Visual Studio and open the solutions file SnapExamples in the examples directory.

Configure Visual Studio for use with SNAP, which requires that the character set is set to Multi-byte and that the locations of SNAP include directories are specified.

To set the character set to Multi-byte, right-click on your project, go to Properties --> Configuration Properties --> General --> Projects Defaults --> Character Set --> Select "Use Multi-Byte Character Set".

To specify the location of SNAP include directories, go to Options --> Preferences --> C++ Directories --> Include Directories and add the paths on your system to SNAP folders glib-core, snap-core and snap-adv.

Be aware that your version of Visual Studio might have the settings at slightly different locations than used above, so the navigation steps to find them need to be adjusted appropriately.

Once Visual Studio is configured, build your solution, which compiles the core SNAP library all the examples.

**Comment by mbargull** [comment]
> I'm not sure if there is a problem in building the Windows version or if the problem is just with my test.

It's a problem with the build, see https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.25423#L703.
But I can't help any further since I have no idea what one is supposed to do about turning those Visual Studio build instructions into a bunch of CLI calls and https://github.com/snap-stanford/snap/blob/73cea49aa35ad16cfbfaf987b906476393853639/Makefile.config indicates that only Linux, macOS, or Cygwin are supported for doing a `make`...

**Comment by CurtLH** [comment]
Thanks for looking into this @mbargull.  I guess we can skip the Windows build, but I'd like to get it to build if possible. 

From looking at [recent contributors](https://github.com/snap-stanford/snap/graphs/contributors) to the [snap repo](https://github.com/snap-stanford/snap/), maybe someone there knows how to build the Windows version through some means other than using Visual Studio.

cc: @roks, @mohanaprasad1994, @scoutsaachi, @vid-koci, @arbenson, @hyin-stanford

**Comment by CurtLH** [comment]
This recipe is ready for review @conda-forge/staged-recipes.

Given the issues with building this recipe for Windows, I think it's best to skip Windows for now, and revisit in the feedstock.

**Pull request merged**
