### PR TITLE
Add bob.db.replay recipe

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
This depends on https://github.com/conda-forge/staged-recipes/pull/415
Sorry it was created earlier. When that is merged, could you please restart builds on this one.

**Comment by 183amir** [comment]
Could someone with access please restart the CI on this?

**Comment by pelson** [comment]
I did do a few hours ago, and have done again.

**Comment by 183amir** [comment]
Thanks, it is working now.

**Pull request merged**
