### PR TITLE
add python-geotiff recipe

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@KipCrossing and @cehbrecht 

Please feel free to leave a message here indicating that you would want to be maintainers on this recipe. Thanks!

**Comment by ngam** [comment]
Why not add the license file manually and this will then pass?

**Comment by KipCrossing** [comment]
I want to be a maintainer on this recipe

@Zeitsperre

**Comment by cehbrecht** [comment]
> Please feel free to leave a message here indicating that you would want to be maintainers on this recipe. Thanks!

@Zeitsperre  I like to be a maintainer.

**Comment by cehbrecht** [comment]
@KipCrossing @Zeitsperre the license file is not part of the pypi package, does it need `MANIFEST.in`?, like:
https://github.com/bird-house/birdy/blob/master/MANIFEST.in 

We could use as source the github tag ... but last tag is 0.2.1 ... tags for 0.2.2 and 0.2.3 are missing.

**Comment by KipCrossing** [comment]
https://github.com/KipCrossing/geotiff/pull/37

I'll merge this if it looks good.

**Comment by ngam** [comment]
> [KipCrossing/geotiff#37](https://github.com/KipCrossing/geotiff/pull/37)
> 
> I'll merge this if it looks good.

You could also just include the license here to avoid a rebuild (or if there are potential problems elsewhere). An example, though to be clear, I am not trying to be a maintainer, since I have no idea what this package does: https://github.com/Zeitsperre/staged-recipes/pull/1/files

**Comment by Zeitsperre** [comment]
> You could also just include the license here to avoid a rebuild (or if there are potential problems elsewhere). An example, though to be clear, I am not trying to be a maintainer, since I have no idea what this package does: https://github.com/Zeitsperre/staged-recipes/pull/1/files

Thanks for the patch and the concern @ngam, but I think it's better to adjust this information in the PyPI package as well, so it makes more sense to make the changes upstream in the package.

(As an FYI, the package allows python developers to use `geotiff` (the typical format for satellite images/remote sensing) without installing some really heavy dependencies. @KipCrossing is building it, and we think it's a great addition to some projects that are built in conda)

**Comment by ngam** [comment]
> (As an FYI, the package allows python developers to use `geotiff` (the typical format for satellite images/remote sensing) without installing some really heavy dependencies. @KipCrossing is building it, and we think it's a great addition to some projects that are built in conda)

That's why it caught my attention. I've been struggling with GOES-17 data for a while (full transparency, I am associated with NOAA, but not working directly with satellites stuff), and I thought this might be just related. I will definitely be checking it out soon. I am interested in exploring ways to deal with the annoying netcdf data, especially for ML/AI applications. I may also be interested in contributing to the development :)

**Comment by KipCrossing** [comment]
@Zeitsperre Enjoy version `0.2.4` with those latest changes.

Also on pypi: https://pypi.org/project/geotiff/

**Comment by Zeitsperre** [comment]
@conda-forge/help-python This is good to go! Thanks for the help, everyone!

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
