### PR TITLE
Add recipe for ZodiPy

### PR DESCRIPTION
**Pull request by MetinSa**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by MetinSa** [comment]
This PR is to make [ZodiPy](https://github.com/Cosmoglobe/zodipy) conform to the pyOpenSci packaging guidelines (see https://github.com/pyOpenSci/software-submission/issues/161).

**Comment by MetinSa** [comment]
@conda-forge/help-python, ready for review! (Not sure if the CI failing is an issue with the recipe)

**Comment by lpsinger** [comment]
The build is failing due to https://github.com/conda-forge/healpy-feedstock/issues/64.

**Comment by dhomeier** [comment]
Thanks for the pointer; perhaps @mwcraig can advise?
Another issue is that healpy is not available on Windows, so other packages depending on it have disabled the Windows build, but I am not sure what's the best way to go about this.

**Comment by lpsinger** [comment]
> > ZodiPy is a bit different in that it has a minimum version requirement, but in my macOS miniforge installation conda/mamba indeed identify the healpy version correctly; it's just pip reporting it as 0.0.0.
> 
> I generated the `meta.yaml` file using [grayskull](https://github.com/conda/grayskull) and saw that it set both lower and upper bounds for many of the dependencies. I was not sure if this was required or not by conda-forge, so I didnt change it. I did not set a minimum requirement for healpy in `pyproject.toml` so i could try to relax this in the `meta.yaml` file and try again if you think that could help?

One moment. I am looking into the issue with healpy.

**Comment by lpsinger** [comment]
> One moment. I am looking into the issue with healpy. It would be better if we could fix that bug.

https://github.com/conda-forge/healpy-feedstock/pull/65 should fix it.

**Comment by lpsinger** [comment]
Fixed. Please try again.

**Comment by MetinSa** [comment]
The non-windows builds work now, thanks! I am going to see if it still builds with a more relaxed dependency configuration matching the`pyproject.toml`.

**Comment by MetinSa** [comment]
I have finally gotten around to releasing the v1.0.0 version of ZodiPy. Healpy is no longer a requirement so the windows build is now also working. I am not sure if there is anything else missing before the review, but i am pinging the bot again.

@conda-forge/help-python, ready for review!

**Comment by MetinSa** [comment]
Just pinging since it's been a while.

@conda-forge-admin, please ping team

**Pull request merged**
