### PR TITLE
add xscen recipe

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@aulemahal @juliettelavoie @RondeauG

Can you all confirm that you wish to be maintainers? Thanks!

**Comment by Zeitsperre** [comment]
@aulemahal Am I correct in assuming that xesmf does not support Widnows?

**Comment by aulemahal** [comment]
You are correct.

**Comment by Zeitsperre** [comment]
@conda-forge/help-python 

Should I be skipping windows explicitly, or should I leave this as `noarch: python`?

This PR is otherwise ready!

**Comment by aulemahal** [comment]
We could remove `xESMF` as a hard dependency and make the whole "regrid" submodule optional. I would do that only on windows though, not sure if that's a good `conda-forge` practice.

**Comment by Zeitsperre** [comment]
You can set optional dependencies depending on the platform. This is very much allowed in conda-forge. The question is whether we would want to add this to the `xscen` package. It's entirely doable, and it would enable Windows users to use (most) of the functionality.

We could open an issue about this in xscen.

**Comment by aulemahal** [comment]
I just found out that windows build are made for ESMF since February. Sorry for the false alarm, xscen seems to be usable on all three OSs!

**Comment by aulemahal** [comment]
The CI failure seems to be due to https://github.com/esmf-org/esmf/issues/117.

It is interesting that this doesn't happen on the cool OSs.

But anyway, this bug is fixed on ESMF 8.5 which is on the way for a conda-forge release.

**Comment by ocefpaf** [comment]
> I just found out that windows build are made for ESMF since February. Sorry for the false alarm, xscen seems to be usable on all three OSs!

conda-forge doesn't build ESMF on Windows yet. We couldn't make it work. You can still publish this as noarch and leave the Windows to "error out" at install time, or make ESMF optional internally with some lazy import and make `xscen` partially funcional on Windows. It all depends on how important ESMF is for this package.

**Comment by aulemahal** [comment]
Hum, on our part making (x)ESMF optional is quite easy, but I think we have one dependency (clisops) that also required xESMF.

But, I was able to install ESMF on a windows machine using mamba a few minutes ago.  And a win-64 build is listed here : https://anaconda.org/conda-forge/esmf. Were those uploaded manually rather then through the automated conda-forge process ?

The Windows build fails because of a missing environment variable, but the package was indeed installed before that error.

**Comment by ocefpaf** [comment]
> But, I was able to install ESMF on a windows machine using mamba a few minutes ago. And a win-64 build is listed here : https://anaconda.org/conda-forge/esmf. Were those uploaded manually rather then through the automated conda-forge process ?

Nope. My memory failed me. It was added a while back in https://github.com/conda-forge/esmf-feedstock/pull/65

In theory you are good to go here.

**Comment by Zeitsperre** [comment]
@ocefpaf 

I think we can adjust the remaining changes needed within xscen. Our target OS is primarily *nix, so if we can get Windows working within the next release of xscen, that's a bonus. All maintainers have indicated their intent to manage this library. Please feel free to merge!

Thanks!

**Pull request merged**
