### PR TITLE
Add nutpie

### PR DESCRIPTION
**Pull request by aseyboldt**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by aseyboldt** [comment]
And I agree to be listed as maintainer :-)

**Comment by BastianZim** [comment]
Not a rust reviewer so I cannot comment on the compiler but please follow the docs about adding the rust licenses: https://conda-forge.org/docs/maintainer/adding_pkgs.html#licenses-of-included-dependencies

**Comment by aseyboldt** [comment]
@BastianZim Thanks, I fixed the missing licenses.

**Comment by aseyboldt** [comment]
@conda-forge/staged-recipes Would be great to have it merged soon :-)

**Comment by carterbox** [comment]
> I've got a small packaging question as well though: This is a mixed python/rust package using maturin to package.
I had to include a build dependency of {{ compiler("c") }} though to avoid an error about missing libgcc-ng as a dependency, even though I'm not using a C compiler, but only the rust compiler. Does this maybe indicate that {{ compiler('rust') }} is missing something?

I think some rust programs will link to libc depending on whether they make certain system calls. Not sure when rust will implement its own library to replace these calls.

**Review by carterbox — CHANGES_REQUESTED** [review]
There are [some warnings during your test phase that you may want to addresss.](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=527413&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1832) It seems that your package may need a compiler at runtime and maybe blas?

Either way please respond explicitly.

**Comment by aseyboldt** [comment]
> I think some rust programs will link to libc depending on whether they make certain system calls. Not sure when rust will implement its own library to replace these calls.

Makes sense.

The compiler warning and missing blas are due to the runtime dependency on aesara, which can call a compiler to speed up graph computations. This functionality isn't used in this package at all. I think there are some discussions to split aesara into two packages, one that doesn't use a compiler, and one that does. If this does indeed happen, nutpie would only depend on that base package.
Anyway, this failure occurs if aesara is imported, and it disables some optimizations in response to it. So I don't think there is much I can do about this from this package.

**Comment by aseyboldt** [comment]
Although aesara itself does actually depend at runtime on a c and c++ compiler. (https://github.com/conda-forge/aesara-feedstock/blob/main/recipe/meta.yaml#L30). So maybe this actually is an issue in the aesara package, where it doesn't locate the compiler provided by conda. The same error also appears in the most recent [aesara build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=523596&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=1060)

**Pull request merged**
