### PR TITLE
Add dummy pyqt-impl

### PR DESCRIPTION
**Pull request by hmaarrfk**
@ccordoba12 you can see my previous attempt where the post-link script would attempt to uninstall the package cleaning up the environment.

I think this is a just middle that people can use.

Closes https://github.com/conda-forge/pyqt-feedstock/issues/121

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/pyqt let me know what you think.

**Comment by ccordoba12** [comment]
I guess you agreed with my [previous comment](https://github.com/conda-forge/pyqt-feedstock/issues/121#issuecomment-1186349598) on this topic by creating this package, right?

The only thing I don't understand is why it can't be generated as an additional output of the PyQt recipe and instead needs its own feedstock.

**Comment by hmaarrfk** [comment]
You can.

**Comment by hmaarrfk** [comment]
I mostly tried to create a package that could uninstall itself

**Comment by hmaarrfk** [comment]
this also doesnt creare new versions evwry time. one package. no builds for a while

**Comment by ccordoba12** [comment]
> I mostly tried to create a package that could uninstall itself

Ok, I'm +1 with this then.

> this also doesnt creare new versions evwry time. one package. no builds for a while

Right. Another good reason to create it too.

**Comment by hmaarrfk** [comment]
> Ok, I'm +1 with this then.

I have to be clear, It didn't work.

**Comment by hmaarrfk** [comment]
Yea.... i think a package that removes itself is just plain wrong. We might as well add it to the pyqt recipe.

**Comment by ccordoba12** [comment]
It just had the wrong name, i.e. it should have been named `pyqt` from the beginning.

**Comment by hmaarrfk** [comment]
Yeah. I'm not excited about adding an output. But i feel like this issue is likely widespread. But i can't quantify how much

**Comment by ccordoba12** [comment]
> But i can't quantify how much

Since Matplotlib depends on PyQt directly, I'd say it's quite widespread.

**Pull request closed without merging**
