### PR TITLE
Add r-fportfolio

### PR DESCRIPTION
**Pull request by janjagusch**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by janjagusch** [comment]
@conda-forge/r, this is my first R feedstock, so a review would be much appreciated. 🙏

**Comment by janjagusch** [comment]
> Thanks for this submission! Could you please regenerate the recipes using [`conda_r_skeleton_helper`](https://github.com/bgruening/conda_r_skeleton_helper)? There are several common patterns that are currently not implemented in these recipes and `conda_r_skeleton_helper` script will incorporate these automatically.
> 
> Summarily, there a multiple points for improvement:
> 
> * all these packages should be `noarch`
> * `conda-forge/r` should always be recipe maintainers
> * the licenses all should be `GPL-2.0-or-later`
> * a couple are missing `r-mass` dependencies
> * the commented DESCRIPTION file be retained with submission

Thanks for the feedback, @mfansler. The output rendered by [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper) is much more useful than what I got from grayskull. 👏 

> Also, please only submit one recipe per Pull Request.

Is it okay to submit multiple recipes in this PR as they depend on each other?

**Review by mfansler — CHANGES_REQUESTED** [review]
Looking good! Just some minor things to touch up with the licenses, then should be ready to go.

RE: multiple recipes - yes, totally fine to submit multiple recipes in a single PR when they are interdependent. I will note that too many recipes in one (say, more than 5) can be burdensome for the reviewer and may lead reviewers to skip because they don't have the time to parse through each one.

Only other thing to keep in mind is that when the recipes get turned into feedstocks, they will no longer be synchronized and therefore the first CI run can fail because the dependencies aren't indexed on Anaconda Cloud yet. I'll keep tabs on this and can point out for you how to restart the CI.

**Review by mfansler — APPROVED** [review]
Thanks again for the contribution! ❤️

**Pull request merged**
