### PR TITLE
Adding diffpy.srmise

### PR DESCRIPTION
**Pull request by bobleesj**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bobleesj** [comment]
@sbillinge 

Could you please write a comment here (as instructed) that you would be willing to be listed there as a maintainer?

**Comment by sbillinge** [comment]
> @sbillinge
> 
> Could you please write a comment here (as instructed) that you would be willing to be listed there as a maintainer?

I am willing to be a maintainer on this project

**Comment by bobleesj** [comment]
@conda-forge/help-python, ready for review!

For windows, we are encountering an error message, which appears to be related to dynamic versioning. I checked that the version is correctly parsed from our GitHub's release tags.

```

    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 1, in <module>
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools\__init__.py", line 117, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools\_distutils\core.py", line 145, in setup
      _setup_distribution = dist = klass(attrs)
                                   ^^^^^^^^^^^^
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools\dist.py", line 283, in __init__
      _Distribution.__init__(self, dist_attrs)
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools\_distutils\dist.py", line 279, in __init__
      self.finalize_options()
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools\dist.py", line 635, in finalize_options
      ep(self)
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools_git_versioning.py", line 256, in infer_version
      version = version_from_git(dist.metadata.name, **config, root=root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\site-packages\setuptools_git_versioning.py", line 494, in version_from_git
      lines = pkg_info.read_text().splitlines()
              ^^^^^^^^^^^^^^^^^^^^
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\pathlib.py", line 1028, in read_text
      return f.read()
             ^^^^^^^^
    File "C:\bld\diffpy.srmise_1728095290645\_h_env\Lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5499: character maps to <undefined>
  [end of output]
```

This error did not occur for one of the other package that was recently merged to conda-forge a few days ago: https://github.com/conda-forge/staged-recipes/pull/27265 Could you please help?

**Comment by synapticarbors** [comment]
It looks like there is a bad character in the `README.rst` that the os encoding in windows doesn't like:

```
with open('README.rst', encoding='cp1252') as f:
    data = f.read()
```

I'm having trouble finding the exact location, but maybe you can spot it.

**Comment by sbillinge** [comment]
@bobleesj please look for a misbehaving utf-8 symbol in the readme.  It is almost certainly a day or a whitespace or sth in text that was copy-pasted from pdf or sth like that. At least, that's the first place to look.  The reference from the paper maybe?

**Comment by bobleesj** [comment]
> It looks like there is a bad character in the `README.rst` that the os encoding in windows doesn't like:
> 
> ```
> with open('README.rst', encoding='cp1252') as f:
>     data = f.read()
> ```

Thank you. Fixed! 

@conda-forge/help-python @synapticarbors ready for review! 

We are submitting as a pre-release version (rc) as instructed here: https://github.com/conda-forge/cfep/blob/main/cfep-05.md

**Pull request merged**
