### PR TITLE
Fix r-boot 2

### PR DESCRIPTION
**Pull request by jakirkham**
Builds off PR ( https://github.com/conda-forge/staged-recipes/pull/2361 ).

Unfortunately we seem to be unable to create `r-boot` the expected way as our tooling is getting hung up on Windows 32-bit. Am proposing we add a hack that hides the `requirements` section on Windows 32-bit. This appears to work for me locally and was seeing the same issue locally that we see on staged-recipes of [`r-base` unsatisfiable on `osx-64`]( https://travis-ci.org/conda-forge/staged-recipes/builds/198760898#L300-L301 ). So it should work on staged-recipes too. This issue actually is with Window 32-bit, but `conda` is misreporting the platform, for which we are searching for packages.

cc @johanneskoester @ocefpaf

### CODE REVIEW

**Comment by jakirkham** [comment]
Let's see how this goes.

**Comment by johanneskoester** [comment]
There is already a skip for win. Shouldn't that be enough? I don't really like the idea to add this hack to hundreds of r packages...

**Comment by jakirkham** [comment]
Should it? Yes. Is it? No.

That said, I agree this is not pretty and don't particularly like it, but lack a better option given my current time pressures and your desire to see a near term progress. If you figure out a better fix that will solve this problem, I'm all ears.

**Comment by johanneskoester** [comment]
OK. Thanks a lot for your help. I wished I could reproduce the error locally. Then I'd be able to debug it myself. Maybe I should try with the docker container.

**Comment by jakirkham** [comment]
That would be a good option. Also trying with the versions of packages used on Travis CI. Sorry I can't help more.

FWIW this does seem to have worked and there is now an [`r-boot` feedstock]( https://github.com/conda-forge/r-boot-feedstock ). So this should at least give you some path forward with R in the interim.

**Comment by johanneskoester** [comment]
I get the following error in the docker container:
```
conda-smithy init r-boot
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Fetching package metadata ...........
Traceback (most recent call last):
  File "/opt/conda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/opt/conda/lib/python3.5/site-packages/conda_smithy/cli.py", line 116, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory, meta)
  File "/opt/conda/lib/python3.5/site-packages/conda_smithy/cli.py", line 34, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/opt/conda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 644, in main
    render_run_docker_build(env, config, forge_dir)
  File "/opt/conda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 77, in render_run_docker_build
    forge_config.get('channels', {}).get('sources', tuple())
  File "/opt/conda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 565, in compute_build_matrix
    mtx = special_case_version_matrix(meta, index)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 230, in special_case_version_matrix
    r_vn = index[r_pkg.fn]['version']
KeyError: 'r-base-3.1.2-0.tar.bz2'
```
Any idea what I need to configure (it seems to look for an old R version).

**Pull request merged**
