### PR TITLE
Add kfp-pipeline-spec

### PR DESCRIPTION
**Pull request by chensun**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by chensun** [comment]
> @chensun - can work on this be restarted?

Sorry, I thought I would be able to free up some time to look deeper into this. But there's still quite some higher priority work on my plate. Please feel free to take over this if you have bandwidth.

**Comment by akchinSTC** [comment]
@chensun - I opened a PR in the kfp repo to support creation of a source tar. Are you by chance a reviewer there?

**Comment by manuelwalserqc** [comment]
Hi @chensun, are you still interested to act as a maintainer for this package. If yes, I am very happy to include you in one of the following commits. I will proceed to create an up-to-date version of kfp.

**Comment by chensun** [comment]
Hi @manuelwalserqc, thanks for taking over the effort and finishing it. Yes, I can be a maintainer. 

> I will proceed to create an up-to-date version of kfp.

For my education, are you not blocked by the lacking of tarball package? 
https://github.com/kubeflow/pipelines/pull/7165 was adding the tarball (sdist), but we haven't made a new release after that change yet.

**Comment by manuelwalserqc** [comment]
Hi @chensun, ok, I will add you as maintainer.
No, I was not blocked because you can build a conda package from a wheel as well. A colleague pointed me to the existing tensorboard as an example.

**Pull request closed without merging**
