### PR TITLE
Adding `sigstore` from PyPI

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sugatoray** [comment]
## Reason for Build Failure: `1/N`

`Observation`:

> :point_right: *Create new conda-forge package for `securesystemslib`*

- `line number: 2116`: [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=549850&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=2116)
- `time elapsed`: `3m:27s`

```sh
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested securesystemslib
```

**Comment by sugatoray** [comment]
## Reason for Build Failure: `2/N`

`Observation`:

> :point_right: *Add `flit-core` to host dependencies.*

- `line number: 2790`: [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=549852&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=2790)
- `time elapsed`: `3m:51s`

```sh
ModuleNotFoundError: No module named 'flit_core'
```

**Comment by sugatoray** [comment]
PR is ready. Request for review/merging.

cc: @conda-forge/help-python

**Comment by sugatoray** [comment]
## Reason for Build Failure: `3/N` | `windows`

`Observation`:

> :point_right: *Noarch package contains binary script: `sigstore.exe`*

- `line number: 3645`: [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=549857&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=2fb5b0a7-737c-5f5c-8f3f-f6db6174bacf&l=3645)
- `time elapsed`: `6m:0s`

```sh
[noarch_python] Noarch package contains binary script: sigstore.exe
   INFO: sysroot: 'C:/Windows/' files: '['winhlp32.exe', 'win.ini', 'twain_32/wiatwain.ds', 'twain_32.dll']'
```


<details>
<summary><b>Click to expand</b>: Detailed Error Trace</summary>
<p>

```sh
Successfully built sigstore
Installing collected packages: sigstore

Successfully installed sigstore-0.6.3
Removed build tracker: 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pip-build-tracker-r6t5omqq'

Resource usage statistics from building sigstore:
   Process count: 3
   CPU time: Sys=0:00:00.7, User=0:00:00.8
   Memory: 49.8M
   Disk usage: 155.1K
   Time elapsed: 0:00:08.1


INFO:conda_build.build:Packaging sigstore
Packaging sigstore
number of files: 35
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
Unknown format
[noarch_python] Noarch package contains binary script: sigstore.exe
   INFO: sysroot: 'C:/Windows/' files: '['winhlp32.exe', 'win.ini', 'twain_32/wiatwain.ds', 'twain_32.dll']'

```

</p>
</details>

---

### Question for Reviewer(s) :bulb: 

Can this windows build be successfully built?

**Comment by BastianZim** [comment]
It’s using scripts so it cannot be noarch: https://github.com/sigstore/sigstore-python/blob/19bf98f1e59690c9ddc776d01cac8ca9110fe7bd/pyproject.toml#L40

These kinds of windows exe files are normally a good indicator that an entry point was missed or that it has scripts.

**Pull request closed without merging**
