### PR TITLE
Adding numpyro Package

### PR DESCRIPTION
**Pull request by freddyaboulton**
This is noarch but `jaxlib` is not available on Windows so it's ok to merge without passing the windows ci.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by fehiepsi** [comment]
Thanks, @freddyaboulton! The PR looks good to me. I guess the requirement `python >= 3.7` comes from `jax` recipe?

@ericmjl @ocefpaf Could the requirement `python >= 3.7` be relaxed in `jax`?

**Comment by ocefpaf** [comment]
> Thanks, @freddyaboulton! The PR looks good to me. I guess the requirement `python >= 3.7` comes from `jax` recipe?
> 
> @ericmjl @ocefpaf Could the requirement `python >= 3.7` be relaxed in `jax`?

[It is `>=3.6`](https://github.com/google/jax/blob/master/setup.py#L29). I don't recall why we used 3.7. Let's give it a try. See https://github.com/conda-forge/jax-feedstock/pull/48

**Comment by fehiepsi** [comment]
Awesome! Thanks, @ocefpaf!

**Comment by freddyaboulton** [comment]
Thanks @ocefpaf ! I updated this recipe to use 3.6!

**Comment by freddyaboulton** [comment]
@conda-forge/python This is ready for review!

**Pull request merged**
