### PR TITLE
Move svglib into recipes

### PR DESCRIPTION
**Pull request by jakirkham**
Was in the wrong directory. :(

xref: https://github.com/conda-forge/staged-recipes/pull/3033

### CODE REVIEW

**Comment by nicoddemus** [comment]
Ouch, sorry!

**Comment by jakirkham** [comment]
Hmm...seems to be timing out on the Linux and macOS builds. Do you mind opening a fresh PR to investigate, @nicoddemus? I think I'll remove the directory from `staged-recipes` in `master` for now.

**Comment by nicoddemus** [comment]
Sure, will do, thanks!

**Comment by jakirkham** [comment]
Thanks. Sorry for the hassle.

**Comment by jakirkham** [comment]
Resolved by PR ( https://github.com/conda-forge/staged-recipes/pull/3057 ).

**Pull request closed without merging**
