### PR TITLE
add testing.postgresl and testing.common.database

### PR DESCRIPTION
**Pull request by msarahan**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by msarahan** [comment]
@tk0miya I wanted to let you know that I'm adding your packages to conda-forge.  If you'd like, I will list you as a maintainer.  That role gives you permissions on the repository that this recipe will create when merged.  You can be added at any later time.  Maintenance here mostly means merging the PR's that our bot submits for updates.

**Comment by isuruf** [comment]
Shouldn't there be a package called `testing` so that the top level `<site-packages>testing/__init__.py` file is not repeated in the two packages?

**Comment by msarahan** [comment]
Yep, thanks.  That's the proper way to do namespace packages.

**Comment by msarahan** [comment]
This is expected to fail on windows.  I only wrote the recipe for unix, since it will be noarch.

**Comment by isuruf** [comment]
Shouldn't there also be a `testing.common` package?

**Comment by msarahan** [comment]
Not sure.  database is the only thing in that namespace: https://github.com/tk0miya?utf8=%E2%9C%93&tab=repositories&q=testing&type=source&language=

but I suppose it probably should be done correctly regardless.

**Comment by msarahan** [comment]
@conda-forge-admin please rerender

**Comment by tk0miya** [comment]
@msarahan Thank you for letting me know. It's my pleasure to add my package to conda!

**Comment by msarahan** [comment]
Thanks @tk0miya.  You will see some invitations soon.  Thanks for your work on the valuable testing.* packages.

**Comment by tk0miya** [comment]
Thank you for inviting. But I've never use conda. So privilege of maintainer is too much to me. I'll ask you again if I need to work for conda.

**Comment by msarahan** [comment]
Sure thing.  Sorry I misunderstood you.  Once this PR is merged, it will create "feedstock" repositories, such as https://github.com/conda-forge/testing.postgresql-feedstock.  File an issue there for any concerns, or if you want to be a maintainer.

**Pull request closed without merging**
