### PR TITLE
Add pyexasol

### PR DESCRIPTION
**Pull request by dbast**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

The requirements contain also the most convenient extras (pandas, pyopenssl, python-rapidjson), which could be reduced.

The LICENSE.txt file will be included in later pypi releases and can then be used from there, see https://github.com/badoo/pyexasol/pull/27

### CODE REVIEW

**Comment by dbast** [comment]
@morazow Are you fine being co-maintainer of the recipe?

@wildraid Do you want to be co-maintainer of the recipe?

Thanks

**Comment by morazow** [comment]
Hey @dbast ,

Thanks for this!

But Vitaly (@wildraid) is main maintainer of this project. 

@wildraid please let me know if you want me to ask here for additional maintainers.

**Comment by dbast** [comment]
Hey @morazow,

well, it is about the co-maintainership of the conda-forge recipe here, not the upstream code.

Makes sense?

**Comment by morazow** [comment]
ahh okay, sure.

I confirm, I am fine being co-maintainer of this recipe.

**Comment by dbast** [comment]
@conda-forge/staged-recipes Ready for review. Thanks!

**Comment by wildraid** [comment]
Hi @dbast ,

Thank you for raising this. I do not have any experience with conda from developer perspective at this moment, so I have two simple questions:

1) Are there any advantages to having a dedicated conda recipe VS just using a simple `pip` call? That's how we installed `pyexasol` with conda before:

```
dependencies:
...
  - pip:
...
    - pyexasol==0.5.1
```

2) I am not sure about dependencies. The only hard dependencies are `websocket-client` and `rsa`. Everything else is situational and normally not needed for most of people.

Thank you.

**Comment by dbast** [comment]
Hi @wildraid,

The feedstock is now created, see https://github.com/conda-forge/pyexasol-feedstock ... and the resulting package is uploaded to https://anaconda.org/conda-forge/pyexasol

1. Advantage of having it as conda package is, that all the dependencies are then also handled via conda during dependency resolution / installation... a `pip: ...` entry may get some dependency via pypi even though they would be available via conda....

2. Some other packages like https://github.com/conda-forge/turbodbc-feedstock/blob/master/recipe/meta.yaml also do some data optionated selection of some of the extra requirements to create a good fast and secure data experience :) 

That can be changed and you are always welcome as recipe maintainer over here https://github.com/conda-forge/pyexasol-feedstock

Thanks

**Comment by wildraid** [comment]
@dbast , o-o-okay, do I have to do anything extra when I update pyexasol on PyPi?

I guess, this part should be updated somehow:
```
{% set version = "0.6.0" %}
```

Thank you.

**Comment by dbast** [comment]
That is all automated :) ... so you just upload to pypi ... after that a bot gets triggered that opens a Pull Request to the feedstock updating the version and sha256 (and the all the CI code around in case that is outdated). CI is then triggered and after review the PR can be merged. Sometimes manual updates are done to the PR of the bot in case of requirements have to change with a new version etc. ... See e.g. https://github.com/conda-forge/sqlalchemy_exasol-feedstock/pull/1/files#diff-e178b687b10a71a3348107ae3154e44c ... 2 commits, one updating the version+sha256 and one the CI code around.

With the next update PR, I would e.g. remove the LICENSE.txt which is now stored with the feedstock as it then comes via the pypi tarball.

**Pull request merged**
