### PR TITLE
Adding pycobertura

### PR DESCRIPTION
**Pull request by gro1m**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by gro1m** [comment]
@aconrad Please leave a comment that you are willing to be listed in the maintainers section.
Another thing I wonder: Why is there already a package with the same name? Hmm…

**Comment by gro1m** [comment]
@synapticarbors Apparently you took the responsibility to publish pycobertura to conda-forge. That‘s nice, but it looks like the PyPI maintainer of the package @aconrad was not informed and it slipped me as well. Furthermore, it would be nice to discuss the workflow of updating the conda-forge repo as soon as a new version on the pypi project has been released, so that the two projects are linked. To be done here: https://github.com/aconrad/pycobertura/blob/master/release.sh. So how should we proceed here? For this PR I am ultimately going to close it, but before would like to know about maintenance and how we are going about linking the PyPI and the conda-forge project.

**Comment by aconrad** [comment]
@gro1m yeah I'm good to be listed as maintainer. Feel free to add yourself as well.

**Comment by gro1m** [comment]
@aconrad It already has been done for us. I asked over on gitter: https://app.gitter.im/#/room/#conda-forge:matrix.org. So you might also want to join the conversation if you want to have more information on it.
In principle, conda-forge is publisher-driven and there are volunteers like @synapticarbors that build conda-forge packages from PyPI packages...
So `conda install conda-forge::pycobertura` should work and we can add this to the README if we want, because we maintain the ground truth.
With this I am going to close this PR.

**Pull request closed without merging**
