### PR TITLE
add mathics3

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by wolfv** [comment]
@rocky @GarkGarcia @mmatera are you fine with being additional maintainers of this package? Please leave a quick comment. Also please check the deps and version constraints (this was generated automatically from the wheel using a tool called `grayskull`).

Also I am not sure, we might have to add a couple of licenses here for MathJax & co.

Once this recipe is merged, a "feedstock" is created and all of you will have full ownership rights there. From the feedstock one can make new releases that are built on Azure CI and pushed to the anaconda.org/conda-forge channel. 

Once this recipe is merged, people will be able to install mathics using `conda install mathics3 -c conda-forge`.

**Comment by rocky** [comment]
I'm okay with being a maintainer. 

The dependencies look fine, but I'll note that those that aren't pegged on the upper bound may break in the future. This kind of thing is a judgement call because while allowing new versions has its advantages, there is sometimes incompatibility and/or breakage. Not all packages follow a semantic versioning scheme or respect that. And there's nothing we can do about that.  (I am guessing that conda packages and versions are totally independent of other ones, right? If so then pegging upper version is probably the safest thing to do - it works now with these versions so don't take the chance of pulling in a new version when it comes out.)

As far as I know, with respect to tick 3, there are no vendored packages in Mathics.

**Comment by wolfv** [comment]
@rocky did you see the failure on Windows before? Should I disable that test?

```
(%PREFIX%) %SRC_DIR%>mathicsscript --help 
error: cannot find mathics shell
```

**Comment by mmatera** [comment]
I am also OK to be added as a maintainer.

**Comment by rocky** [comment]
> @rocky did you see the failure on Windows before? Should I disable that test?
> 
> ```
> (%PREFIX%) %SRC_DIR%>mathicsscript --help 
> error: cannot find mathics shell
> ```

I have not seen this error before, however after release I did try this for the first time on MS Windows. [This commit](https://github.com/Mathics3/mathicsscript/commit/eb87d916066a6444dda678ef0590a9ab05c72c16) was the result of that. 

Depending on how/where you work on Windows mathicsscript does work. 

Disable test for now. I'll fix up mathicsscript down the line.

**Comment by rocky** [comment]
> @rocky did you see the failure on Windows before? Should I disable that test?
> 
> ```
> (%PREFIX%) %SRC_DIR%>mathicsscript --help 
> error: cannot find mathics shell
> ```

Another thought - `mathicsscript` is not bundled with Mathics. That is a separate package. The bare-bones `mathics` is what is bundled with Mathics.

**Comment by rocky** [comment]
@wolfv as I think about this more. There should be one package for Mathics, and a separate package for mathicsscript. If you just install mathicsscript it will install Mathics as a dependency. @GarkGarcia was working on splitting of Django from Mathics. And as always the Jupyter interface that @mmatera may work on over the new year will be in separate repository too.

**Pull request merged**
