### PR TITLE
NO MERGE, testing

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, is the linter down?

**Comment by jakirkham** [comment]
So I'd take a look at the Heroku logs and see if they provide any clues.

**Comment by isuruf** [comment]
Heroku is not using the conda environment and can't find conda-smithy. I'll have a look

**Comment by isuruf** [comment]
Okay, it's finally working. It found that the recipe exists and that the maintainer does not exist. Yay.

**Comment by jakirkham** [comment]
Nice work @isuruf! This should save a lot of time.

**Pull request closed without merging**
