### PR TITLE
adding `traitlets_paths`

### PR DESCRIPTION
**Pull request by jgunstone**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jgunstone** [comment]
getting this error:

```sh
ValueError: License file given in about/license_file (D:\a\1\s\recipes\traitlets_paths\LICENSE.txt) does not exist in source root dir or in recipe root dir (with meta.yaml)
```

i think this is the relevant section in the `meta.yaml`:
```yaml
about:
  home: https://github.com/Zsailer/traitlets_paths
  summary: Traitlets module for pathlib.
  license: MIT
  license_file: LICENSE.txt
```

and there is a `LICENSE.txt` file in the root dir of the source repo: https://github.com/Zsailer/traitlets_paths

**Comment by jgunstone** [comment]
I got it working by copying the LICENSE.txt file from the source directory to the feedstock directory and it worked... 
but shouldn't it be able to find the LICENSE.txt in the source directory?

**Review by dopplershift — APPROVED** [review]
The license file isn't contained in the PyPI tarball, so that's why you had to manually add a copy here.

**Comment by jgunstone** [comment]
gotcha - thanks very much :)

**Pull request merged**
