### PR TITLE
Add jupyter_bokeh feedstock

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

### CODE REVIEW

**Comment by philippjfr** [comment]
@mattpap I've included you as recipe maintainer.

**Comment by philippjfr** [comment]
My apologies, this already exists.

**Comment by dhirschfeld** [comment]
@philippjfr - where does this exist already? I can't seem to find `jupyter-bokeh` on `conda-forge`? It is on the `bokeh` channel but IMHO it would be great to have it in `conda-forge` so as to not require another channel.

**Comment by dhirschfeld** [comment]
Looks like it's right here - https://github.com/conda-forge/jupyter_bokeh-feedstock

I did a search for `bokeh` on GitHub and it didn't turn up. Strange.

Sorry for the noise...

**Pull request closed without merging**
