### PR TITLE
R silvermantest

### PR DESCRIPTION
**Pull request by khughitt**
Created using a package generated via the conda r skeleton helper as a template, however, this package is not available on CRAN, so the helper could not be used directly.

This is my first time adding a recipe for an R package available only on Github -- I tried to include/modify all appropriate sections, but let me know if I missed anything.

Checklist

- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vend other packages
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jenzopr** [comment]
Hi! I'm still trying to reach one of the authors - luckily he's professor just a few kilometers away and I at least reached his secretary today. If he agrees, I will submit it to CRAN.
Would a tagged release be sufficient for an initial conda package?

**Comment by dbast** [comment]
I would say a tagged release is a prerequisite, but more arguments to directly release from github would be nice.

With cran as source there is another party behind a package, who does some QA-checks and tests with new R releases including feedback to the original package author(s) and noting down if the former is orphaned etc.

@jenzopr Maybe having you also as additional feedstock author here would be already a statements that there is some support behind the package.

@conda-forge/r What do you think?

**Comment by jenzopr** [comment]
I have the OK from Hajo Holzmann, one of the original authors, to submit to CRAN and put myself as maintainer. I will let you know here, once the CRAN submission was successful.

**Comment by khughitt** [comment]
Great! Thank you, both! I'll close this PR so that you can open a new one using the CRAN recipe (the conda-forge cran skeleton helper script makes it very easy to build recipes, if you haven't already used it).

**Comment by jenzopr** [comment]
Thanks a lot for your persistence, Keith! Without it, I guess, I would never have put it to CRAN. It is submitted now, by the way :-)

**Comment by khughitt** [comment]
@jenzopr No problem! And that great! Thanks for taking the time to put together this package and make it available to the public :)

**Pull request closed without merging**
