### PR TITLE
Adding modzy-sdk

### PR DESCRIPTION
**Pull request by DataScienceDeconstructed**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by modzyopensource** [comment]
I agree to be the maintainer.

**Comment by modzyopensource** [comment]
@timsnyder  After some internal discussion, I am working on removing "tests" and "samples" from our packaging manifest. I will ping you when we have merged those changes into our base git repo and pushed the new distribution to PyPi.

**Comment by DataScienceDeconstructed** [comment]
@timsnyder recipe updated and checks passed. let us know if there is anything else that needs to be addressed.

**Review by timsnyder — APPROVED** [review]
@conda-forge/staged-recipes , this looks ready to merge to me.

**Comment by modzyopensource** [comment]
great news @timsnyder
Who performs the merge / what is the general timeline for that? This is my first conda package and I just want to make sure there is nothing else that needs to occur prior to the merge on my end.

**Review by dopplershift — APPROVED** [review]

**Comment by modzyopensource** [comment]
@dopplershift ... The modzyopensource git account is a collective account for maintainers of the Modzy SDK package. @DataScienceDeconstructed is one of the maintainers and volunteered to shepherd the packaging process through the conda forge process. notifications to modzyopensource will reach all maintainers and allow us the quickest resolution to any problems or issues with the SDK.

**Pull request merged**
