### PR TITLE
add r-webchem

### PR DESCRIPTION
**Pull request by mfakaehler**
@conda-forge-admin, please ping @conda-forge/help-r

This is my first contribution to conda-forge. Not sure whether I got the subtleties right yet 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by mfakaehler** [comment]
@mfakaehler is okay with maintaining the recipe

**Comment by cbrueffer** [comment]
@mfakaehler could you re-generate the recipe with `https://github.com/bgruening/conda_r_skeleton_helper`?

**Comment by mfakaehler** [comment]
I have already re-generated the yaml with the conda_r_skeleton_helper in the above commit. Is there anything more to it?

**Comment by cbrueffer** [comment]
The helper generates `bld.bat` and `build.sh` as well, please update those too.

**Comment by mfakaehler** [comment]
Yes, I see! Thank you

**Comment by cbrueffer** [comment]
Looks good, thanks!

**Pull request merged**
