### PR TITLE
added clang-format as a package

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge/staged-recipes ready for review!

**Comment by dopplershift** [comment]
I don't understand. This package seems to only provide pip-installable Python script out of LLCM/clang-format. In the conda-forge world, what is this providing over just doing `conda install clang`?

**Comment by thewchan** [comment]
> 
> 
> I don't understand. This package seems to only provide pip-installable Python script out of LLCM/clang-format. In the conda-forge world, what is this providing over just doing `conda install clang`?

That's a good point; if you think there isn't any value in adding this one I can just close it? @dopplershift let me know

**Comment by dopplershift** [comment]
@thewchan Well I think that really depends on: What was the motivation for you submitting this in the first place? 😉

**Comment by isuruf** [comment]
There's already a `clang-format` package.

**Comment by thewchan** [comment]
> 
> 
> @thewchan Well I think that really depends on: What was the motivation for you submitting this in the first place? 😉

Oh just mostly thought it's pretty cool to be able to install a clang-based formatting via conda, but if that's already possible by just getting clang in conda I can see why that's redundent

**Comment by thewchan** [comment]
@isuruf @dopplershift not sure how I missed that; I'll go ahead and close this one. Thanks!

**Comment by ocefpaf** [comment]
> @isuruf @dopplershift not sure how I missed that; I'll go ahead and close this one. Thanks!

The linter should've have caught that. Is our check for duplicate packages broken?

**Comment by isuruf** [comment]
It checks only for duplicated feedstocks, not duplicated outputs.

**Pull request closed without merging**
