### PR TITLE
R batch03

### PR DESCRIPTION
**Pull request by croth1**
:tada:

xref: https://github.com/conda-forge/staged-recipes/issues/2009

### CODE REVIEW

**Comment by croth1** [comment]
@johanneskoester, i recall that you managed to stop the download failures by increasing the timeout delay of conda. Is this already online for all PRs?

**Comment by johanneskoester** [comment]
@croth1 I tried something, but it turned out to not work. Conda has some facilities to modifiy the timeout, but they are not yet exposed.

**Comment by croth1** [comment]
hmhm, so what's the strategy now - are we trying to merge them? Can we expect a fix in the near future?

**Comment by johanneskoester** [comment]
Same story, one of the three equivalent appveyor jobs passes, the others fail with the well known timeout problem.

**Pull request merged**
