### PR TITLE
Add various CRAN packages

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by dpryan79** [comment]
r-opencpu needs r-evaluate

**Comment by bgruening** [comment]
I fixed it in the feedstock, rerunning.

**Comment by bgruening** [comment]
New error: 
```
configure: error: "Cannot find mpi.h header file"
checking for mpi.h... no
ERROR: configuration failed for package ‘Rmpi’
```

**Comment by SylvainCorlay** [comment]
Out of curiosity, the build.sh

```
 if [[ $target_platform =~ linux.* ]] || [[ $target_platform == win-32 ]] || [[ $target_platform == win-64 ]] || [[ $target_platform == osx-64 ]]; then
   export DISABLE_AUTOBREW=1
   $R CMD INSTALL --build .
 else
    // [many things]
fi
```

appears to be the same in many R packages. What is the deal with the linux platform? Can't we just do `R CMD INSTALL --build .`?

I am looking at packaging `RInside`, hence the question.

**Comment by dpryan79** [comment]
Apparently I didn't need to remove r-rmpi, who knew that'd actually work.

**Comment by bgruening** [comment]
Thanks @dpryan79!

**Pull request merged**
