### PR TITLE
Add pyspnego

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dhirschfeld** [comment]
```python-traceback
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    ], language_level=3, compiler_directives={'linetrace': cython_linetrace})
  File "C:\Miniconda\conda-bld\pyspnego_1598480598479\_h_env\lib\site-packages\Cython\Build\Dependencies.py", line 972, in cythonize
    aliases=aliases)
  File "C:\Miniconda\conda-bld\pyspnego_1598480598479\_h_env\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\Miniconda\conda-bld\pyspnego_1598480598479\_h_env\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'spnego\_sspi_raw\sspi.pyx' doesn't match any files
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    ], language_level=3, compiler_directives={'linetrace': cython_linetrace})
  File "C:\Miniconda\conda-bld\pyspnego_1598480598479\_h_env\lib\site-packages\Cython\Build\Dependencies.py", line 972, in cythonize
    aliases=aliases)
  File "C:\Miniconda\conda-bld\pyspnego_1598480598479\_h_env\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\Miniconda\conda-bld\pyspnego_1598480598479\_h_env\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'spnego\_sspi_raw\sspi.pyx' doesn't match any files

```

**Comment by krisevans** [comment]
I'm happy to be a maintainer.

**Comment by rzillman** [comment]
I am happy to be a maintainer.

**Comment by dhirschfeld** [comment]
Same error:
```
ValueError: 'spnego\_sspi_raw\sspi.pyx' doesn't match any files
```

...which is weird since the file *does* exist!
https://github.com/jborean93/pyspnego/blob/main/spnego/_sspi_raw/sspi.pyx

**Comment by dhirschfeld** [comment]
Looks like a packaging error by the author - the cython files don't appear to be included in the sdist:
image

**Comment by dhirschfeld** [comment]
It seems to want to download `cryptography` even though it's listed as a dep:
```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/cryptography/
```

**Comment by dhirschfeld** [comment]
Thanks @chrisburr! Unfortunately, it looks like the repo wasn't created properly:
https://github.com/conda-forge/pyspnego-feedstock

**Pull request merged**
