### PR TITLE
Add constantly, hyperlink and incremental

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/staged-recipes, this is ready for a review

**Comment by isuruf** [comment]
Thanks

**Comment by ocefpaf** [comment]
No problem. BTW, I am a little bit absent due to the day job but I can review and merge stuff if you ping. Just be persistent if I miss the first ping :smile:

**Comment by isuruf** [comment]
Thanks. I've got some PRs at conda-forge-webservices and conda-smithy, I'll ping you once CI passes.

**Pull request merged**
