### PR TITLE
Updated travis token again

### PR DESCRIPTION
**Pull request by pelson**
To get this value, I:

```

$ travis login
Username: conda-forge-manager
Password for conda-forge-manager: ###
Two-factor authentication code for conda-forge-manager: #

$ travis token
Your access token is ###

$ travis encrypt TRAVIS_TOKEN="###"
Please add the following to your .travis.yml file:

  secure: "<The super long ecrypted secret...>"

```

Relates to #6119

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for doing this Phil. 😄

cc @isuruf

**Comment by jakirkham** [comment]
Merged PR ( https://github.com/conda-forge/staged-recipes/pull/6098 ) to test.

**Comment by jakirkham** [comment]
That's weird. Apparently it started out with the [rate limit used up]( https://travis-ci.org/conda-forge/staged-recipes/builds/394608056#L826-L827 ). Will need to recheck in a half hour.

**Comment by jakirkham** [comment]
So, when it reset, it appears the GitHub token only has [59 uses available]( https://travis-ci.org/conda-forge/staged-recipes/builds/394626256#L825-L826 ), which makes it seem like the GitHub token is not working. Maybe we need to replace it as well?

**Comment by isuruf** [comment]
Looks like it. Unauthenticated github api calls gets 60 uses, but Github tokens should get 5000

**Comment by pelson** [comment]
Don't see why this has occurred. I've generated another token, just in case. Will be interesting to see what comes out of it. #6132.

**Comment by isuruf** [comment]
Travis token doesn't work now. @pelson, can you login to travis-ci and get the token from the profile page?

**Pull request merged**
