### PR TITLE
NEW: Add default values for cuda_compiler on osx and windows

### PR DESCRIPTION
**Pull request by carterbox**
Fixing broken feedstock rendering from https://github.com/conda-forge/staged-recipes/pull/26580

@beckermr, is this what you mean? The pinnings here always lag behind the channel-wide pinnings.

https://github.com/conda-forge/admin-requests/actions/runs/10816201902

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by carterbox** [comment]
Or did you want something like this:

```yaml
{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}
```

added to the recipes?

**Comment by beckermr** [comment]
we should ask @jakirkham or someone who knows the cuda stack better on @conda-forge/core

**Comment by carterbox** [comment]
I'm going to merge now and ask for @jakirkham's opinion later because I believe he's out of the office.

**Comment by isuruf** [comment]
`cuda_compiler_version` is set https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L56-L57. I don't understand why this is necessary.

**Comment by beckermr** [comment]
See this error: https://github.com/conda-forge/admin-requests/actions/runs/10816556957/job/30007974762

**Comment by beckermr** [comment]
This might be the wrong solution, but this is what we are trying to fix.

**Comment by isuruf** [comment]
The correct way is https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/meta.yaml#L74

**Comment by carterbox** [comment]
IMHO, we shouldn't have to do that because this recipe is CUDA only, so the cuda compiler version should be defined.

**Comment by beckermr** [comment]
We should separate the issues out. Let's push an immediate fix to unblock staged recipes by using the current way cuda is done. We can discuss changes to how cuda is done as another issue.

**Comment by jakirkham** [comment]
Sorry for the slow reply. As Daniel noted I was out for some time

Likely the issue that was encountered is the same one we have seen elsewhere with `conda-build` version `24.7` (not in `24.5` or earlier): https://github.com/conda-forge/conda-smithy/issues/2011

Recently Michael fixed this error in PR ( https://github.com/conda/conda-build/pull/5458 ), which was included in `conda-build` version `24.9.0`

Have tried re-rendering both recipes locally using PR ( https://github.com/conda-forge/staged-recipes/pull/26580 )'s merge commit ( https://github.com/conda-forge/staged-recipes/commit/8d2e5e34a798798f874137d481588ec8fd329640 ) and `conda-build` version `24.9.0`. This works correctly locally

**Pull request merged**
