### PR TITLE
r-v8 created with skeleton for CRAN 

### PR DESCRIPTION
**Pull request by valscherz**
Trying again to build my first recipe

### CODE REVIEW

**Comment by valscherz** [comment]
@conda-forge/staged-recipes

**Comment by bgruening** [comment]
@valscherz can you please use this script to generate the recipes? https://github.com/bgruening/conda_r_skeleton_helper It will add a few additional things like the r-* team as contributors if you like.

**Comment by valscherz** [comment]
> @valscherz can you please use this script to generate the recipes? https://github.com/bgruening/conda_r_skeleton_helper It will add a few additional things like the r-* team as contributors if you like.

Hi @bgruening. Thanks for your message. As indicated in the title of my PR, I DID use your skeleton to build this recipe. My only changes brought to it afterwards were to add the license as indicated here (https://conda-forge.org/docs/meta.html#packaging-the-license-manually). I also first kept only myself as maintainers. Since I felt that maybe that's why you made me this comment, I just re-added all the IDs that were first as maintainers.

**Comment by bgruening** [comment]
@valscherz the license file, we can use from the tarball that is ok. It looks great to me know. Just one question, the license file you added and the one from the tarball do not specify the MIT license. Could you ping the upstream developer to fix that upstream?

**Comment by valscherz** [comment]
@bgruening Thanks for your help. 

As you may have noticed, I am new... So I happy to take any comment. However, referring to https://www.r-project.org/Licenses/MIT, it is my understanding that the licensing on the CRAN is what is expected for this type of license. There (https://cran.r-project.org/web/packages/V8/index.htm),  "MIT" links to a generic template. Indications contained in this generic template seems here to have been followed (precisely to indicate "MIT + file LICENSE"), where *file LICENSE* links to a file just containing two lines : *YEAR:* and *<COPYRIGHT HOLDER>*, as found in the tarball. 

As an example, I could find the same setting for other packages (e.g. https://cran.r-project.org/web/packages/spiderbar/index.html). 

That said, I believe that the content of the tareball is correct and therefore nothing should be done upstream. My subsidary question is : should we on the conda-forge side include the content of this MIT template somewhere? Do you have examples to follow for that matter?

Thanks for you help!


Valentin

**Comment by cbrueffer** [comment]
While the package builds, it has a system requirement on the v8 library that's not reflected in the recipe dependencies. Doesn't seem like the actual package is going to work without that.

**Comment by jdblischak** [comment]
>  the license file you added and the one from the tarball do not specify the MIT license. Could you ping the upstream developer to fix that upstream?

The author followed the CRAN convention of referring to a template license plus an external file with name and year.

> should we, on the conda-forge side, include the content of this MIT template somewhere? Do you have examples to follow for that matter?

We could never come to a conclusion on how to handle the template licenses like MIT on conda-forge. Licenses like GPL-3 are straight-forward because they can be verbatim copied from the `licenses` directory shipped with `r-base`. If you'd like to restart the discussion on R licenses, I think that should be done in #3234. Another option: some maintainers have chosen to include the template file with `license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'`. Either way (i.e. including the template file or the file with the name/year), it's not a complete license.

**Comment by valscherz** [comment]
Thanks @jdblischak for confirming that the CRAN author did as expected and your clear explanations regarding what to do. Now... I am basically stuck since I don't know how to handle the issue pointed by @cbrueffer .. Quite a bit of learning to do but not sure when I will have the time to..

**Comment by jdblischak** [comment]
> Thanks @jdblischak for confirming that the CRAN author did as expected and your clear explanations regarding what to do.

@valscherz No problem. However, for this conda recipe, I'd prefer if you deleted the line with `license_file`. That file ([here](https://github.com/jeroen/V8/blob/master/LICENSE)) is not a complete license, so I think it is misleading to include it in the package. Also, that will make it easier for us in the future to update recipes if we ever decide on a strategy for R packages that use license templates. Please ping me if you have any difficulty doing this, and I can make the change.

> Now... I am basically stuck since I don't know how to handle the issue pointed by @cbrueffer .. Quite a bit of learning to do but not sure when I will have the time to..

I agree that it is ideal to include system dependencies in the conda recipe. Unfortunately in this case, I don't think libv8 is available on Anaconda Cloud (at least I couldn't find it). I'd be ok with merging this recipe as is, and then updating it if libv8 becomes available on conda-forge. @cbrueffer what are your thoughts?

**Comment by valscherz** [comment]
> @valscherz No problem. However, for this conda recipe, I'd prefer if you deleted the line with `license_file`. That file ([here](https://github.com/jeroen/V8/blob/master/LICENSE)) is not a complete license, so I think it is misleading to include it in the package. Also, that will make it easier for us in the future to update recipes if we ever decide on a strategy for R packages that use license templates. Please ping me if you have any difficulty doing this, and I can make the change.

Done

>I agree that it is ideal to include system dependencies in the conda recipe. Unfortunately in this case, I don't think libv8 is available on Anaconda Cloud (at least I couldn't find it). I'd be ok with merging this recipe as is, and then updating it if libv8 becomes available on conda-forge. @cbrueffer what are your thoughts?

Well I do agree that it would make much more sense to have everything on conda... But no, libv8 is not on any conda channel. Now, v8 is available from source (https://chromium.googlesource.com/v8/v8.git/+/3.14.5.8) or as a packages (for instance https://packages.ubuntu.com/bionic/libv8-3.14-dev) but I don't have the knowledge to turn that into a recipe... 

Interestingly I am in fact not the first facing this wall.. (https://github.com/conda-forge/staged-recipes/pull/6340)

**Comment by jdblischak** [comment]
@cbrueffer Could you please let us know if you are ok with the plan to merge this recipe and then update later if libv8 is able to be packaged?

**Comment by cbrueffer** [comment]
Sorry for the delay; I think if the package as is adds some value, by all means please commit it. I just wonder whether packages that depend on this one will work given the lack of a crucial dependency.

**Comment by jdblischak** [comment]
> I just wonder whether packages that depend on this one will work given the lack of a crucial dependency.

@cbrueffer Good point. This package does have a decent number of reverse dependencies.


Reverse imports: | ajv, colormap, concaveman, daff, dagitty, DiagrammeRsvg, DOT, geojsonio, geojsonlint, gfer, ical, js, jsonld, jsonvalidate, lawn, lutz, minimist, randomcoloR, rchess, rchie, rjade, rmapshaper, suncalc, uaparserjs, wellknown
-- | --
Reverse suggests: | dqshiny, RDML, reactR, shinyjs
Reverse enhances: | d3r

**Comment by jdblischak** [comment]
Actually, now I am confused how this recipe even builds. I tried building in the Docker container [continuumio/miniconda3](https://hub.docker.com/r/continuumio/miniconda3/), and it failed because it was missing libv8.

```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because  was not found. Try installing:
 * deb: libv8-3.14-dev (formerly: libv8-dev) (Debian, Ubuntu)
 * rpm: v8-314-devel (formerly: v8-devel) (Fedora, EPEL)
 * brew: v8@3.15 (OSX) -- NOT regular v8! Tap from homebrew/versions
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
```

Looking at the [CircleCI build logs](https://circleci.com/gh/conda-forge/staged-recipes/32043), it unexpectedly exits early without attempting to build the recipe.

```
+ python /home/conda/.ci_support/build_all.py /home/conda/conda-recipes
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
rendering /home/conda/conda-recipes/r-v8 for linux-64
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Computed that there are 0 distributions to build from 1 recipes
Nothing to do
+ touch /home/conda/staged-recipes/build_artifacts/conda-forge-build-done
```

Why was the macOS build skipped? Was it because it tried to build the recipe and failed? I no longer think we should merge this recipe.

**Comment by valscherz** [comment]
> Why was the macOS build skipped? Was it because it tried to build the recipe and failed? I no longer think we should merge this recipe.

I don't remember what was the error of CircleCI with macOS but it was indeed failing..  It definitely requires libv8-3.14-dev already installed. I have tested to uninstall it from my machine and it is then not working anymore… That said and from what I have learnt here, I agree that it does not make sense to make it available on conda.

**Comment by jdblischak** [comment]
I restarted the AppVeyor and CircleCI builds to get them to build the recipe.

**Comment by jdblischak** [comment]
> I restarted the AppVeyor and CircleCI builds to get them to build the recipe.

Something is wrong with this recipe. It keeps getting skipped on both AppVeyor and CircleCI. I suspect the issue is the double selectors:

```
  skip: true  # [win32][osx-64]
```

I think this should instead be:

```
  skip: true  # [win32 or osx]
```

Note that I don't think `osx-64` is an option for [preprocessing selectors](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#preprocessing-selectors).

**Comment by jdblischak** [comment]
I tried pushing the changes myself, but I don't have permission (presumably b/c I am only a [child team member for staged-recipes](https://github.com/orgs/conda-forge/teams/staged-recipes/members?utf8=%E2%9C%93&query=+membership%3Achild-team)).

**Comment by valscherz** [comment]
> I tried pushing the changes myself, but I don't have permission (presumably b/c I am only a [child team member for staged-recipes](https://github.com/orgs/conda-forge/teams/staged-recipes/members?utf8=%E2%9C%93&query=+membership%3Achild-team)).

@jdblischak I hope it is what you had in mind...and with that it fails... and it must from my current understanding (learning by doing...) since when installed the r-v8 package checks for the presence of v8.

```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because  was not found. Try installing:
 * deb: libv8-3.14-dev (formerly: libv8-dev) (Debian, Ubuntu)
 * rpm: v8-314-devel (formerly: v8-devel) (Fedora, EPEL)
 * brew: v8@3.15 (OSX) -- NOT regular v8! Tap from homebrew/versions
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```

**Comment by jdblischak** [comment]
@valscherz Looks good! It is failing as expected. I don't see any reason to close it. We want this recipe to be merged, we just need V8 to be built for conda-forge first.

Here's the to-do list for anyone returning to this PR:
- [ ] Build V8 for conda-forge
- [ ] Add V8 as a dependency for r-v8
- [ ] Don't skip on macOS

**Comment by valscherz** [comment]
OK. Thanks anyways  jdblischak for your help!


> Here's the to-do list for anyone returning to this PR:
> * [ ]  Build V8 for conda-forge



https://github.com/conda-forge/staged-recipes/issues/4523 could be a starting point for the ones who would like to look into it.

**Comment by valscherz** [comment]
OK. Thanks anyways  jdblischak for your help!


> Here's the to-do list for anyone returning to this PR:
> * [ ]  Build V8 for conda-forge



https://github.com/conda-forge/staged-recipes/issues/4523 could be a starting point for the ones who would like to look into it.

**Comment by valscherz** [comment]
OK. Thanks anyways  jdblischak for your help!


> Here's the to-do list for anyone returning to this PR:
> * [ ]  Build V8 for conda-forge



https://github.com/conda-forge/staged-recipes/issues/4523 could be a starting point for the ones who would like to look into it.

**Pull request closed without merging**
