### PR TITLE
add libxmlsec1, xmlsec and python3-saml recipes

### LINKED ISSUE #13879: RDkit 2020.09.4 release issues with Conda-forge build and other modules (Python3-saml)
What:
Fresh install on Ubuntu 20.04 with miniconda3, python 3.7 RDKit installs ok but Python3-saml has become incompatible.
First noted with 2020.09.04 but after experiments found first version where break occurred - 2020.03.6

Terse:
Demonstrated with
python3-saml

Some issues with rpy2 but:

$ conda install -c conda-forge rpy2
appears to install and work ok on Ubuntu 20.04 (not Mac OSX)

TERSE:
Up to, and including rdkit==2019.09.3 python3-saml==1.9.0 would install and work together

With a python 3.7 condo env:

$ conda install -c conda-forge rdkit==2020.03.6 -y
$ conda install -c conda-forge python3-saml
Python3-saml failed to install with multiple conflicts
- there are references to Python 3.8 - did we miss something and RDkit is Python3.8 now?

rdkit==2020.09.3 and rdkit==2020.09.4 also are incompatible

Good News - There is compatibility with (this is a section of our build script)

pip install mod_wsgi==4.7.1
pip install -i https://pypi.anaconda.org/OpenEye/simple OpenEye-toolkits
conda install -c conda-forge rpy2 -y
conda install -c conda-forge scikit-learn==0.21.3 -y
conda install -c conda-forge matplotlib==3.3.3 -y
For addition clarity:

pip install python3-saml

does not work - this is PEP517 related but it does reveal that libxml2 and libxmlsec might be the issue
[Spent about a day try to work around this one without success]
These are the results on Ubuntu 20, on Mac OSX Catalina things are worse (that will required another day of experimentation - Rdkit 2018 appears stable here with all other module combinations)

Issue also logged on Github rdkit/conda-forge

Tagging @jaimergp as requested

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

[Bringing over recipes from Anaconda, as provided by @jjhelmus](https://github.com/AnacondaRecipes/aggregate/commit/bfa0c5028babcc55199fba87ca90a199923440ba) (I added you as a maintainer, let me know if you want it that way or not!)

(Hopefully) closes #13879

### CODE REVIEW

**Comment by jaimergp** [comment]
@jjhelmus Can you confirm whether you want to be a maintainer here? No need to become one if you don't want, but I figured I should ask first given that you authored the original recipe. Thanks!

**Comment by jjhelmus** [comment]
I would prefer not to be a maintainer.

**Comment by jaimergp** [comment]
@conda-forge/help-python-c This is ready for review, thanks!

**Comment by jaimergp** [comment]
Thanks @ocefpaf!

**Pull request merged**
