### PR TITLE
ADD: glfw

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
ping @hmaarrfk

**Comment by hmaarrfk** [comment]
cool. does glfw build on OSX?
Why did you blanket skip windows? windows should be able to build with modern compilers. Just not for python 2.7

**Comment by kmuehlbauer** [comment]
@hmaarrfk No, I just thought I skip osx and win for the first round. Aren't all CI run in staged anyway?

**Comment by kmuehlbauer** [comment]
Anyway, something is not good here...

**Comment by hmaarrfk** [comment]
I think they all run in parallel, but it is difficult for humans to keep up ;)

**Comment by hmaarrfk** [comment]
i never cared for OSX, so I don't know if it would on it :/

**Comment by kmuehlbauer** [comment]
Any idea for why Circle breaks like this? Will catch up tomorrow.

**Comment by kmuehlbauer** [comment]
@mariusvniekerk rebased onto master.

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please lint

**Comment by hmaarrfk** [comment]
you can just remove mesalib then. 

two binutils is normal

**Comment by kmuehlbauer** [comment]
Ping @conda-forge/help-c-cpp, this is ready for review.

**Pull request merged**
