### PR TITLE
Libtool

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @msarahan want to be a maintainer? (If you have some nice recipes for bison, byacc, etc let me know.)

### CODE REVIEW

**Comment by jakirkham** [comment]
I think I have some or have added some to conda recipes that can be ported over.

**Comment by msarahan** [comment]
Happy to be a maintainer.  We do not have existing recipes for bison or yacc.  I can work on putting them together.  Which ones exactly do we need?

In looking at the docker image, I have found that bison (from yum) depends on perl - might have a circular dependency there.

**Comment by ocefpaf** [comment]
> Happy to be a maintainer.

Thanks!

> We do not have existing recipes for bison or yacc.  I can work on putting them together.  Which ones exactly do we need?

To be honest I am not sure.  Usually the configure scripts look for all of them (bison, byacc, yacc) and end up using only one.  Not sure if there is a preference.

**Comment by jakirkham** [comment]
I am adding a recipe for bison.

**Comment by jakirkham** [comment]
Here is the PR for bison ( https://github.com/conda-forge/staged-recipes/pull/119 ). If either of you wanted to be added as maintainers, please let me know and I will add you.

**Comment by jakirkham** [comment]
Can add me too.

**Comment by ocefpaf** [comment]
> Can add me as a maintainer too.

Done!

Note that if we forget to add maintainers here people can always add themselves with a PR to the feedstock.

**Comment by jakirkham** [comment]
> Note that if we forget to add maintainers here people can always add themselves with a PR to the feedstock.

That will automatically add them to the team also?

**Comment by ocefpaf** [comment]
> That will automatically add them to the GitHub team also?

It should.

**Comment by pelson** [comment]
>> That will automatically add them to the GitHub team also?

> It should.

To confirm, it should, and it does when the Travis job from https://github.com/conda-forge/conda-forge.github.io runs.

**Pull request merged**
