### PR TITLE
Add `outdated`

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by hoechenberger** [comment]
PR to include license file upstream: https://github.com/alexmojaki/outdated/pull/4

**Comment by hoechenberger** [comment]
Requires #10636 to be merged first.

**Comment by npavlovikj** [comment]
Thank you again @hoechenberger !

**Comment by hoechenberger** [comment]
Thanks for your swift action, @npavlovikj! Really appreciate it.

**Pull request merged**
