### PR TITLE
[skip CI][skip appveyor] WIP: add qt5 recipe

### PR DESCRIPTION
**Pull request by msarahan**
This is a WIP - not sure if it will build on CI's here anyway.

Current status on Windows: builds Qt5 core, and webkit OK.  Fails on webengine, with output that points to some paths not being created properly, feeding the gyp input for webengine.

@jdreaver @ccordoba12 @ddale - I have listed you as maintainers because of your contributions to this recipe on conda-recipes.  Please confirm that you are OK with this.

### CODE REVIEW

**Comment by jdreaver** [comment]
I'm okay with this, thanks for working on it! Last I remember I got this working on Linux, but always ran into trouble on Windows. I'm not at all experienced compiling Qt on Windows, so that's probably why I failed. It looks like you've already got farther than we did on Windows though.

Good luck!

**Comment by msarahan** [comment]
Note to self: I think we want to have this be simply "qt" - and then handle versions as branches.  Need to rename the folder before merge.  Not sure how to reconcile that with the need to have qt4 and qt5 installable side-by-side - probably need more logic in build scripts.

**Comment by ddale** [comment]
Confirming ok.

I remember running into some path error problems when building on Windows, due to long paths of nested directories in the qt5 source tree conflicting with path length constraints in the Windows compiler. I think this was an issue with webengine, but it was a long time ago. The solution for me was to install anaconda in c:\conda, rather than some much longer path.

**Comment by msarahan** [comment]
Thanks @ddale - yes, my base path is C:\MC3x64 - annoying, but at least it works!

**Comment by ddale** [comment]
Concerning "qt" vs "qt4" and "qt5", Last I checked (some time ago) all of the Linux distributions I know of used the latter, as did macports

**Comment by msarahan** [comment]
yeah, this is sort of uncharted territory to me.  I like the concept, and I respect that we're trying to keep everything (even Python) consistent with that policy.  I don't think we have enough high-use packages in play to judge its success yet.  GDAL is one example of this approach: https://github.com/conda-forge/gdal-feedstock

**Comment by ccordoba12** [comment]
> I think we want to have this be simply "qt" - and then handle versions as branches

Mike, since Qt/Qt5 are already installable side by side, I think we should leave them as separate packages with their own names and recipes.

Trying to mix things in a single feedstock seems to add an additional complication that we really don't need to get into at this point :-)

**Comment by ccordoba12** [comment]
And to avoid creating two packages for all projects that depend on Qt (like `spyder-qt` and `spyder-qt5`), we could just change `qt` for `qt5` in their run deps.

Most people will not notice the change. And those who would want to use `qt` along with (or instead of) `qt5` could easily do it :-)

**Comment by msarahan** [comment]
I have no horse in this race, but I think the precedent that needs to be followed is the community precedent here.

Cc @ocefpaf @jakirkham @pelson

**Comment by ocefpaf** [comment]
@ccordoba12 I don't have an educated opinion on the problem, so I usually ask WDMLDD (What Does My Linux Distro Do ;-)

OpenSUSE does rename like you recommend. So I am :+1:

**Comment by ccordoba12** [comment]
@ocefpaf, yeah, we followed the Linux example here (Ubuntu does the same :-)

**Comment by jakirkham** [comment]
> I don't have an educated opinion on the problem. So I usually ask: WDMLDD (What Does My Linux Distro Do ;-)

That would also mean having `python3`. 😦

> I have no horse in this race, but I think the precedent that needs to be followed is the community precedent here.

By this do you mean having one feedstock? This could be another case where subenvironments should be employed.

**Comment by msarahan** [comment]
> By this do you mean having one feedstock? This could be another case where subenvironments should be employed.

Yes, that's what I meant.  Though Qt is different from many things in that it really is a case where having both in one environment is not intrinsically conflicting (aside from things like qt.conf).

Keeping the number on the package name facilitates installing both versions.  But that's really a hack to overcome the limitations of conda as only being able to install one package with a given name at a time.

**Comment by jakirkham** [comment]
> Keeping the number on the package name facilitates installing both versions. But that's really a hack to overcome the limitations of conda as only being able to install one package with a given name at a time.

I guess I really don't understand the use case driving this. Is there actually some value in having both Qt's in the same environment?

**Comment by astrofrog** [comment]
I thought I ran into incompatibilities in the past when trying to use ``qt`` and ``qt5`` in the same environment, so it might make sense to give them the same name in that respect to avoid that situation. I'll try and see if I can reproduce the issues I was seeing before.

**Comment by ccordoba12** [comment]
> I thought I ran into incompatibilities in the past when trying to use qt and qt5 in the same environment

True, but we're creating new qt/pyqt packages that work correctly with qt5/pyqt5.

**Comment by ccordoba12** [comment]
@msarahan, could you close this one? I'll add our Qt5 recipe to the Qt feedstock :-)

**Comment by msarahan** [comment]
Sure.

**Comment by ccordoba12** [comment]
Thanks!

**Pull request closed without merging**
