### PR TITLE
Use new issue format

### PR DESCRIPTION
**Pull request by BastianZim**
This is a followup to #15328 using the new [issue template format](https://gh-community.github.io/issue-template-feedback/structured/). The template is in beta but GitHub is using it itself in their [docs](https://github.com/github/docs/tree/main/.github/ISSUE_TEMPLATE) so I would consider it stable enough.

This should primarily reduce the wall of text that can currently be found in the package request issues, there is no big change of content. 

I have created two test issues here:
1. https://github.com/BastianZim/test-repo/issues/7
2. https://github.com/BastianZim/test-repo/issues/6

Feel free to open more to see the flow.

Before this gets merged, a `General` label would have to be created by someone with write access.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge/core When you have a second.

**Comment by jaimergp** [comment]
I love how it [looks like](https://github.com/BastianZim/test-repo/issues/new/choose)! This would be awesome for `conda-forge/conda-forge.github.io` too!

image

**Comment by BastianZim** [comment]
@jaimergp Happy to add that. Do you know of any other question categories we can use there besides “General”? Don't know of one but I guess we can also add them later whenever we find one.

**Comment by BastianZim** [comment]
@conda-forge/core Were there any discussions in the last meeting as mentioned in https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2357#issuecomment-1005501863

**Comment by jaimergp** [comment]
Ahhh I missed this! Sorry! I will bring it up.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@conda-forge/core , any other thoughts here? 🙂

**Review by ocefpaf — APPROVED** [review]
No strong option. The new format seems to be a better option.

**Comment by BastianZim** [comment]
@conda-forge/core

We now have 

* https://github.com/conda-forge/.github/pull/9
* https://github.com/conda-forge/conda-forge.github.io/pull/1578
* https://github.com/conda-forge/staged-recipes/pull/17366

Any other place where this should be added or any comments?

**Comment by beckermr** [comment]
I guess we could do admin-requests?

**Comment by BastianZim** [comment]
Sure, but the template there is currently empty. What kind of data do we need to ask for in the survey?

**Comment by beckermr** [comment]
ohhh woops. We only use the Pr template there. NVM.

**Review by beckermr — APPROVED** [review]

**Pull request merged**
