### PR TITLE
added recipe for pybcpy

### PR DESCRIPTION
**Pull request by sarthakpati**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sarthakpati** [comment]
Hi @synapticarbors, 

I have added a patch with the updated version (which should hopefully fix the missing files from the build) but I am getting an error when trying to do the package import in the test. But I see that the package has been installed:

```bash
The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main
    _openmp_mutex:    4.5-1_gnu
    bzip2:            1.0.8-h7b6447c_0
    ca-certificates:  2021.9.30-h06a4308_1
    certifi:          2021.5.30-py310h06a4308_0
    ld_impl_linux-64: 2.35.1-h7274673_9
    libffi:           3.3-he6710b0_2
    libgcc-ng:        9.3.0-h5101ec6_17
    libgomp:          9.3.0-h5101ec6_17
    libstdcxx-ng:     9.3.0-hd4cf53a_17
    libuuid:          1.0.3-h7f8727e_2
    ncurses:          6.2-he6710b0_1
    openssl:          1.1.1l-h7f8727e_0
    pip:              21.2.4-py310h06a4308_0
    pybcpy:           0.0.16-py_0               local
    python:           3.10.0-h12debd9_1
    readline:         8.1-h27cfd23_0
    setuptools:       58.0.4-py310h06a4308_0
    sqlite:           3.36.0-hc218d9a_0
    tk:               8.6.11-h1ccaba5_0
    tzdata:           2021a-h5d7bf9c_0
    wheel:            0.37.0-pyhd3eb1b0_1
    xz:               5.2.5-h7b6447c_0
    zlib:             1.2.11-h7b6447c_3

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/sarthakpati/projects/venv_graskull/conda-bld/pybcpy_1634398279288/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
export SRC_DIR=/home/sarthakpati/projects/venv_graskull/conda-bld/pybcpy_1634398279288/test_tmp
Traceback (most recent call last):
  File "/home/sarthakpati/projects/venv_graskull/conda-bld/pybcpy_1634398279288/test_tmp/run_test.py", line 2, in <module>
    import pybcpy
ModuleNotFoundError: No module named 'pybcpy'
import: 'pybcpy'
Tests failed for pybcpy-0.0.16-py_0.tar.bz2 - moving package to /home/sarthakpati/projects/venv_graskull/conda-bld/broken
WARNING:conda_build.build:Tests failed for pybcpy-0.0.16-py_0.tar.bz2 - moving package to /home/sarthakpati/projects/venv_graskull/conda-bld/broken
WARNING conda_build.build:tests_failed(2956): Tests failed for pybcpy-0.0.16-py_0.tar.bz2 - moving package to /home/sarthakpati/projects/venv_graskull/conda-bld/broken
TESTS FAILED: pybcpy-0.0.16-py_0.tar.bz2
```

Any idea why this is happening? Would it make sense to simply remove the tests related to the package?

**Comment by synapticarbors** [comment]
I'm not sure, but maybe instead of `python3` in the command test, use `{{ PYTHON }} -m pybcpy -h`. That might find the correct path on windows?

**Comment by xylar** [comment]
Seems worth a try.

**Comment by xylar** [comment]
It seems to be using the wrong python.

**Comment by xylar** [comment]
I think it would really be better to make this an entry point.

**Comment by xylar** [comment]
Alternatively, you could just let the Windows test fail.  Since this package is `noarch: pyhton`, it will build fine once you have a feedstock.  I don't know exactly what the syntax would need to be for a windows user to invoke the command-line interface and that's where I would think an entry point would be better.

**Comment by sarthakpati** [comment]
Ah okay; I have removed the CLI test, for now. Hope this helps!

**Pull request merged**
