### PR TITLE
Added stateplane 0.2.4.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
This has noarch specified. I'm not sure why it is running on travis and appveyor.

**Comment by moorepants** [comment]
@conda-forge-admin please rerender

**Comment by moorepants** [comment]
@conda-forge/staged-recipes I don't know why this is building on appveyor and travis. it is a noarch package. Any way to fix that?

**Comment by ocefpaf** [comment]
> @conda-forge/staged-recipes I don't know why this is building on appveyor and travis. it is a noarch package. Any way to fix that?

Staged-recipes builds everything. You can skip appveyor though with a `[skip appveyor]` text on your commit message.

**Pull request merged**
