### PR TITLE
added pangaea recipe

### PR DESCRIPTION
**Pull request by snowman2**

### CODE REVIEW

**Comment by snowman2** [comment]
@conda-forge/core I tried re-forking the repo and adding the recipe. But it is still not being found.

**Comment by synapticarbors** [comment]
Try renaming `meta.yml` to `meta.yaml`.

**Comment by snowman2** [comment]
@synapticarbors thanks! Guess it helps if I spell the file name correctly.

**Comment by snowman2** [comment]
Ready to merge!

**Pull request merged**
