### PR TITLE
Adding kedro-neptune

### PR DESCRIPTION
**Pull request by Raalsky**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Raalsky** [comment]
@aniezurawski @HubertJaworski @pitercl @shnela @pkasprzyk can you all confirm you are willing to be maintainers for this recipe? I do.

**Comment by pkasprzyk** [comment]
confirming

**Comment by pitercl** [comment]
I confirm

**Comment by HubertJaworski** [comment]
I confirm

**Comment by HubertJaworski** [comment]
@Raalsky Adam Niezurawski is on vaccation currently - he ill not be available for the next two week. Can you remove him from mainteners list for now to not block this?

**Comment by Raalsky** [comment]
@HubertJaworski sure. Got it. Pipeline is failing due to lack of latest `neptune-client` package `0.10.3` as it was published a few moments ago :wink:

**Comment by shnela** [comment]
I do

**Comment by Raalsky** [comment]
@conda-forge-admin, please ping team

**Pull request merged**
