### PR TITLE
Add python recipe in debug mode

### PR DESCRIPTION
**Pull request by dfroger**
Hello,

I would like to add a package for Python built in debug mode.

My use case in the [cython debugger](http://docs.cython.org/src/userguide/debugging.html#running-the-debugger), but it should be usefull in other situations.

This is exactly the same recipe as the [Python recipe](https://github.com/conda-forge/python-feedstock/tree/bbc8ed6f1a3d8d641f9c2d887afbcb81d5ff2a61/recipe) except that:
- in `build.sh`, `./configure` is passed `--with-pydebug`.
- in `bld.bat`, `build.bat` is passed `-d`.
- in `meta.yaml`, `debug` feature is added.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Hi @dfroger I wonder if that should be a branch in existing python `feedstock` (ping @jjhelmus) instead of its own `feedstock`. Although we will definitely need a different name for the package (`python-dbg` seems fine to me BTW) to avoid clashing.

Ping @edisongustavo who may be interested in this recipe.

**Comment by dfroger** [comment]
Hi @ocefpaf, I think it's a good idea to have it in a branch of the existing python `feedstock`, it would simplify maintenance.

It could (should?) actually be the same package name, but with the `debug` [feature](http://conda.pydata.org/docs/building/meta-yaml.html#id1).

**Comment by ocefpaf** [comment]
> It could (should?) actually be the same package name, but with the `debug` [feature](http://conda.pydata.org/docs/building/meta-yaml.html#id1).

That makes sense! Let's see that our main python guy @jjhelmus has to say.

**Comment by jjhelmus** [comment]
@dfroger I would definitely be interested in having this recipe in the [python-feedstock](https://github.com/conda-forge/python-feedstock).  I can make a `debug` branch for these builds.  I'm not sure which will be a better solution to differentiate between the debug and non-debug builds.  Setting a feature is an option as is using a different package name.  I need to run some tests to see which I would prefer.

**Comment by jakirkham** [comment]
cc @pelson

**Comment by pelson** [comment]
Let's move over to the python-feedstock. If the addition of the debug feature is a trivial tweak to the existing build, then we even have strategies to integrate that directly into the `master` feedstock branch. I think we should probably asses how much difference there is between a debug build by putting forwards a PR first, if that is ok @dfroger?

Thanks!

**Comment by edisongustavo** [comment]
Hi all, has the discussion moved to the python feedstock?

I've talked with @ocefpaf during the SciPyLA on this matter and I would like to share my experience with the python debug builds.

I work at ESSS (http://www.esss.com.br) and we have "pydebug" python builds for windows (32 and 64 bits). I will speak mostly about "pydebug" for windows:

We've crushed our heads against a brick wall a LOT because on this subject. The are many many problems when mixing debug/release on windows. Our current approach (which works quite well) is this:

## Main problem

As I said earlier, windows is not friendly to **mixing debug/release** together. This is **NOT supported** at all. Mixing debug/release occurs if a debug package (eg.: VTK) is used with a release version of python (or any other library).

This situation may have changed after VS 2015 due to [UWP](https://msdn.microsoft.com/en-us/windows/uwp/get-started/whats-a-uwp), but I don't have experience there, so I *might* be wrong.

## Strategy

We decided to rely on [conda features](http://conda.pydata.org/docs/building/meta-yaml.html#features) to use debug.

Features work well for this problem because if I want to work on "pydebug" I can simply: `conda install debug` and conda will switch all packages to having the `debug` feature.

While working, we usually have 2 environments:

- `env-debug`
- `env-release`

## The python debug package

When python is compiled in "pydebug" it generates the `python_d` executable. We create a link `python.exe => python_d.exe` so that people can still use the regular `python` command and everything will (should) work.

### Output showing number of refs for python < 3.4

One problem in "pydebug" is that python will output a new string with the number of refs at the end. For example:

```
c:\> python_d.exe -c "print('Test')"
Test
[9183 refs]
```

The problem here is that many tools invoke python when compiling and grab its output. This extra string can be a problem for some utilities and we had to create these methods to handle them:

```python
def IsPythonDebug():
    '''
    Returns True if it is running under a debug version of the python interpreter
    (i.e., compiled with macro Py_DEBUG defined, generally the python_d executable).
    '''
    import sys

    return hasattr(sys, 'gettotalrefcount')  # Only exists in debug versions

def StripDebugRefs(text, end_only=True):
    """
    Strips the ref count text that is printed by the debug version of the python interpreter after
    program exit ("[1209 refs]" for example).

    Should be used by tests that capture output from a debug python interpreter, because it will
    print this characters resulting in different output when compared to the output produced
    by the release version of the interpreter.

    :param unicode text: text to strip debug information

    :param bool end_only: if True, only strips debug info from the end of the string, otherwise will
        search and strip the entire string from debug references.

    :rtype: str
    :return: stripped text
    """
    import re
    if IsPythonDebug():
        pattern = r'(\[\d+ refs\]\r?\n?)'
        if end_only:
            pattern += '$'
        return re.sub(pattern, '', text)
    return text
```

This changed in [python 3.4](https://bugs.python.org/issue17323) so it shouldn't be a problem there.

## Meta.yaml

We have a template for `meta.yaml` of the form:

```yaml

{%- set debug = environ.get('CONDA_BUILD_DEBUG', '0') != '0' %}
...
 
build:
  number: 0
  features:
{% if debug %}
    - debug
{% endif %}
 
...
 
requirements:
  build:
{% if debug %}
    - debug
{% endif %}
  
test:
  requires:
{% if debug %}
    - debug
{% endif %}
```

With this template, to compile in pydebug mode it is simply a matter of setting the environment variable  `CONDA_BUILD_DEBUG=1`.

### Important things to remember

- Never add `- debug` to the run section, otherwise the package will try to install the debug feature, even if it isn't requested!

## The bld.bat files

`bld.bat` files which have compilation, will handle debug and release by using if statements.  For example:

```batch
if "%CONDA_BUILD_DEBUG%" LSS "1" (
    "%PYTHON%" setup.py build install --old-and-unmanageable
) else (
    "%PYTHON%" setup.py build --debug install --old-and-unmanageable
)
if errorlevel 1 exit 1
```

or

```batch
if "%CONDA_BUILD_DEBUG%" GEQ "1" set CFG_DEBUG_FLAGS=--with-debug=1 CFLAGS=-MDd
 
python configure.py ^
  --a-lot ^
  --of ^
  --configuration ^
  --flags ^
  %CFG_DEBUG_FLAGS%
```

## Testing

A very useful test is to test if each compiled python module (`*.pyd`) files didn't mix the debug/release runtime.

To do that, we created a package with [dependency-walker](http://www.dependencywalker.com/) and use it to see if the wrong runtime is present.

### Example (our pillow recipe):

`meta.yaml`:

```yaml
..
test:
  requires:
    {% if debug %}
    - debug
    {% endif %}
    - dependency-walker # [win]
```

`run_test.bat`:

```batch
python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())" > temp_site_packages.txt
set /p SITE_PACKAGES=<temp_site_packages.txt

set VS_MAJOR=10
if "%CONDA_BUILD_DEBUG%" LSS "1" (
	set UNDESIRED_RUNTIME=MSVCR%VS_MAJOR%0D
) else (
	set UNDESIRED_RUNTIME=MSVCR%VS_MAJOR%0
)

REM Check _imaging.pyd

if "%CONDA_BUILD_DEBUG%" LSS "1" (
	set FILENAME=_imaging
) else (
	set FILENAME=_imaging_d
)
start /WAIT depends /c /a:1 /ot:dependency-walker-log-%FILENAME%.txt %SITE_PACKAGES%\PIL\%FILENAME%.pyd
grep -i '%UNDESIRED_RUNTIME%.DLL' dependency-walker-log-%FILENAME%.txt && exit 1
REM If grep 'fails' it sets the errorlevel to 1, but it's fine since grep looks for the 'unwanted' DLL
exit 0
```

## Current conda problems

- https://github.com/conda/conda/issues/2384

**Comment by jakirkham** [comment]
Thanks @edisongustavo for the info. The `debug` feature sounds reasonable. Though I would like to suggest we pick naming that is a bit more specific (lest we turn an entire users environment into debug packages) and call it something like `python-debug` or similar.

**Comment by edisongustavo** [comment]
I agree @jakirkham . I want to bring to attention that on Windows, debug and release don't mix well together. This isn't true on linux, however.

**Comment by tadeu** [comment]
We are very interested in adding this feature! Although we can't currently use it for our (bizarre) version of Python (built with MSVC 2010), this feature will be important for when we move into Python 3. As @edisongustavo nicely pointed out, we already have a workflow built internally in the company, and it may aid as a "quick start" :).

Also, now and then we find bugs on the debug version of packages, and it would be nice to have a "central" location for the debug recipe, and (semi-)official debug packages that can be used in other packages continuous integration.

Just to clear things out: this is for the "pydebug" version of Python (the one that builds to a `python_d.exe` on Windows, and loads binary modules by appending `_d` to the filename, such as `_ctypes_d.pyd`) and it works *only* with binary modules compiled with "pydebug" too, because it changes the memory layout of `PyObject`s (this is why it must be a "feature") -- this is true both on Windows and on Linux.  What @edisongustavo was saying is that it is ok to mix _non-python_ binaries in Linux. (Also, @jakirkham idea of naming the feature `python-debug` makes sense in view of this, but here in the company we use the `debug` feature for C++ debug packages too).

I don't know how the CI would be done for packages other than `python` itself, but because of the requirement of needing dependencies in debug too, it makes sense to view "win64 debug" and "linux64 debug" as two new supported platforms... so this would need a change in `conda-forge` itself, right?  In this case, I don't know if `python-feedstock` would be the ideal place for the discussion (of course, the discussion in `python-feedstock` would be useful for details of the `python debug` recipe).

**Comment by tadeu** [comment]
@pelson, are you moving the discussion? Do you think `conda-smithy` would be a better place for it?

**Comment by tadeu** [comment]
Another note: although `Anaconda` does not seem to have "official" debug packages, `conda` already has an official `debug` meta-package, and it already defines the `debug` feature, as is described here: http://conda.pydata.org/docs/building/environment-vars.html#environment-variables-to-set-build-features

When we started doing our recipes, this still didn't exist, so we created the `CONDA_BUILD_DEBUG` environment variable, but it seems that to use `FEATURE_DEBUG` would be the proper one ;)

**Comment by pelson** [comment]
> @pelson, are you moving the discussion? Do you think conda-smithy would be a better place for it?

All of the information above is indicating that the change is low risk, and is essentially a python package "feature". As such, I'm inclined to suggest a PR in python-feedstock is probably going to be reasonably easy to move forwards with. If I have missed a danger/risk with having python built with the debug flags as a conda feature however, it would be useful to continue the discussion here (since we now have an awful lot of context).

**Comment by jjhelmus** [comment]
How does conda's dependency resolver decide between two packages which differ only in features?  For example if we have python-3.5.2-1 which does not have the `debug` feature and a python-3.5.2-2 package which does have the `debug feature` which packages gets installed with the command `conda install python=3.5`?  

If conda maximized the number of features or ignores them completely I can imagine that having a package with a different name might be preferable.

**Comment by edisongustavo** [comment]
@jjhelmus It depends. There are 2 scenarios:

1. if your environment has already an installed metapackage which provides the `debug` feature:
In this case, `conda install python=3.5` will install `python-3.5.2-2_debug`.
1. if your environment does NOT have such metapackage. In this case:
In this case, `conda install python=3.5` will install `python-3.5.2-1`.

The metapackage package could be called `debug`, for example. This is how we do it.

I want to highlight some points to say why I think that a debug feature is the better approach:

1. It doesn't let you mix debug/release since you can't have both installed syde-by-side. I'm assuming that the libraries have their proper `debug` package.
1. Many libraries don't have their build system ready to handle the `_d` suffix required when using `pydebug` (VTK I'm looking at you).

**Comment by tadeu** [comment]
Note that the Anaconda distribution have an official `debug` meta-package in the `linux 64` channel:

http://repo.continuum.io/pkgs/free/linux-64/debug-1.0-0.tar.bz2

The only thing it does is to track the `debug` feature.

**Pull request closed without merging**
