### PR TITLE
Add 'cvauc' R package to conda-forge

### PR DESCRIPTION
**Pull request by krinsman**
Seems self-explanatory from the title. Please let me know if additional information is required -- I've never done this before.

### CODE REVIEW

**Comment by cbrueffer** [comment]
Hi @krinsman , please consider using https://github.com/bgruening/conda_r_skeleton_helper for creating conda-forge R packages. It calls ```conda skeleton cran```, mostly cleans the result and adds some standard maintainers.

**Comment by krinsman** [comment]
@cbrueffer I appreciate you taking the time to help me. Yes I've done that before, this attempted recipe is actually modified from the result of `conda skeleton cran cvauc`.

There isn't enough time in my schedule right now to fix this recipe (it's obviously broken). In any case it obviously isn't reasonable for me to expect any action to be taken until I do get around to fixing it.

**Comment by cbrueffer** [comment]
No worries! If you like I can have a look at it (been adding a lot of recipes lately, so it'll be quick).

**Comment by krinsman** [comment]
@cbrueffer I don't want to waste your time. Plus, it would be a valuable learning experience for me to fix it myself.

**Comment by cbrueffer** [comment]
It's definitely good experience. Let me know if there's anything I can help with.

**Comment by cbrueffer** [comment]
Added in #6438

**Pull request closed without merging**
