### PR TITLE
add r-showtextdb

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dpryan79** [comment]
r-sysfonts-feedstock hasn't been created yet :(

**Comment by dbast** [comment]
Instead of including the license file, you could also reference `inst/fonts/LICENSE_Apache2.txt` inside the package source. Otherwise looks good and should build now -> retriggered.

**Comment by dbast** [comment]
Currently connection issues to https://cran.r-project.org ... Sometimes thinking switching to https://cran.rstudio.com/ which is cloudfront / cdn based would make sense ...

**Comment by dpryan79** [comment]
Thanks for the cran.rstudio.com suggestion, I just used that to get the remaining packages I need for an analysis since the rproject DNS servers are down :)

**Comment by dpryan79** [comment]
At least OSX seems to have had a conda 4.7-related error this time.

**Comment by dpryan79** [comment]
@conda-forge/help-r The CRAN mirrors happen to be accessible at the moment, so it's currently passing CI testing.

**Comment by dbast** [comment]
Looks good. Merging. Hope that will survive feedstock conversion.

**Pull request merged**
