### PR TITLE
Added recipe for PsiTurk

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Not skipping windows might be premature. If this breaks, will go back to skipping.

**Comment by pmlandwehr** [comment]
Skipping Windows because we don't have a build of `gunicorn` or `sh` for it.

**Comment by ericdill** [comment]
@pmlandwehr looks like this was failing due to user-agents not having a conda package ~3 hours ago.  That has cleared and the circle-ci build should hopefully pass now if you push another commit up

**Comment by pmlandwehr** [comment]
One more time....

**Comment by pmlandwehr** [comment]
Hmm, close/reopen doesn't seem to be forcing circle CI to rebuild @ericdill?

**Comment by ocefpaf** [comment]
> Hmm, close/reopen doesn't seem to be forcing circle CI to rebuild @ericdill?

I re-started them manually and things are green now. Thanks @pmlandwehr.

**Pull request merged**
