### PR TITLE
Add glue-jupyter

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by martinRenou** [comment]
@astrofrog @maartenbreddels would you agree to be added as maintainers?

**Comment by astrofrog** [comment]
Yes sounds good! Thanks!

**Comment by trungleduc** [comment]
> @astrofrog @maartenbreddels @trungleduc would you agree to be added as maintainers?

Yes

**Comment by maartenbreddels** [comment]
👍 thanks!

**Comment by martinRenou** [comment]
Thanks! I'll add you

`pip check` is failing with
```
glue-core 1.9.0 requires openpyxl, which is not installed.
glue-core 1.9.0 requires pvextractor, which is not installed.
bqplot 0.12.37 has requirement pandas<2.0.0,>=1.0.0, but you have pandas 2.0.0.
mpl-scatter-density 0.7 has requirement fast-histogram>=0.3, but you have fast-histogram 0.0.0.
glue-core 1.9.0 has requirement echo>=0.6, but you have echo 0.5.
```

I understand these are issues with glue-core, bqplot and mpl-scatter-density recipes. So I'll remove the pip check for now and update those recipes.

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
