### PR TITLE
Move pysnmp to recipes directory

### PR DESCRIPTION
**Pull request by jakirkham**
Follow-up to PR ( https://github.com/conda-forge/staged-recipes/pull/4571 ).

Moves the `pysnmp` recipe into the `recipes` directory.

cc @nehaljwani @synapticarbors

### CODE REVIEW

**Comment by synapticarbors** [comment]
@jakirkham my apologies for missing that. Maybe the linter shouldn't allow for recipes that aren't in `recipes` so others don't overlook this when focusing on the actual `meta.yaml` file.

**Comment by jakirkham** [comment]
No worries. This is a somewhat common problem. It really just shows that our workflow is suboptimal here as this could be easily detected by a bot and/or CI as you have noted. It's not really worthwhile to trouble human reviewers with these minor details.

Could you please raise an issue on the staged-recipes repo describing this issue and ping core? Then we can discuss how best to address this.

**Comment by jakirkham** [comment]
Windows build fails on Python 2.7 as `trollius` is not present. Maybe this can't be a `noarch: python` package as it has a Python 2.7 specific dependency. Admittedly the `trollius` dependency could be included on Python 3 as well (as it does support Python 3 FWICT), but it likely won't be used there as `asyncio` is available in recent Python 3 versions (hence the lack of failures there). Thoughts @nehaljwani?

**Comment by nehaljwani** [comment]
I am very sorry for this mess, again.

@jakirkham I don't see any downside of adding trollius as a dependency without selector. It's a lightweight package with very less dependencies. So, if we want noarch, it shouldn't be a trouble. I also think that we should include twisted as well as a runtime dependency and remove it as test-only dependency. There are many examples in the examples directory which are using it.

**Comment by jakirkham** [comment]
No worries. As mentioned to Joshua above, this situation does occur with some regularity and we need better automation to catch it.

Ok, have added `trollius` and moved `twisted` to `run`. Assuming this passes, would you like to do the final review @synapticarbors?

**Comment by jakirkham** [comment]
Looks like this converted ok. So should be good to go, @nehaljwani.

**Comment by nehaljwani** [comment]
Thank you @jakirkham and @synapticarbors !

**Pull request merged**
