### PR TITLE
Added r-terra

### PR DESCRIPTION
**Pull request by TomAugspurger**
Note, this is failing for me locally with an error like

```
checking GDAL: linking with --libs and --dep-libs... no
/home/taugspurger/miniconda3/envs/grayskull/conda-bld/debug_1620784683056/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libtbb.so.2, needed by /home/taugspurger/miniconda3/envs/grayskull/conda-bld/debug_1620784683056/_h_env/lib/libtiledb.so.1.7, not found (try using -rpath or -rpath-link)
```

This sounds somewhat like https://github.com/conda-forge/gdal-feedstock/issues/396#issuecomment-831560963, though I haven't verified that it has the same cause yet.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
> Note, this is failing for me locally with an error like

Seems to just be an issue affecting me locally. 

@conda-forge/help-r this should be ready for review. Thanks!

**Comment by cbrueffer** [comment]
Thanks @TomAugspurger; looks good, but please clean up the recipe some more. Basically all comments in the files can be removed.

**Comment by TomAugspurger** [comment]
Thanks will do. Do you prefer that I leave the original CRAN metadata starting at https://github.com/conda-forge/staged-recipes/pull/14880/files#diff-24cdbce6dd2a1c013ae37e87ccd9aa173594a8c8a9315aab92fa7a8c85689e00R97?

**Comment by cbrueffer** [comment]
Usually I leave it in due to laziness, but I don't think it's particularly useful and tends to get stale very quickly.

**Comment by TomAugspurger** [comment]
Thanks, cleaned up. I'll ping when CI finishes again.

**Comment by TomAugspurger** [comment]
All green!

**Pull request merged**
