### PR TITLE
Add lektor recipe

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by goanpeca** [comment]
Still missing **ndg-httpsclient** and **pyopenssl** packages

**Comment by jakirkham** [comment]
Feel free to open a new issue for each of the missing dependencies.

**Comment by goanpeca** [comment]
https://github.com/conda-forge/staged-recipes/pull/1353

https://github.com/conda-forge/staged-recipes/pull/1352

**Comment by goanpeca** [comment]
@jakirkham any ideas on why the travis build is failing?

**Comment by jakirkham** [comment]
Replaced by PR ( https://github.com/conda-forge/staged-recipes/pull/1836 )

**Comment by jakirkham** [comment]
Also seems `exifread` OS X packages were not uploaded due to an old issue. Have restarted the CIs to see if they will upload successfully now.

**Pull request closed without merging**
