### PR TITLE
Add PIconnect to conda-forge

### PR DESCRIPTION
**Pull request by Hugovdberg**
As this package relies on `pandas` and `pythonnet` and is a wrapper for Windows only SDK, it makes sense to publish it on conda-forge as well. I hope this meets the required standards.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Hugovdberg** [comment]
@conda-forge-admin, please ping team

I don't get why it fails. For some reason the `pycparser` is not installed automatically as a dependency `pythonnet`. Should I include it in the `meta.yaml` just to fix the build?

**Comment by xhochy** [comment]
> @conda-forge-admin, please ping team
> 
> 
> 
> I don't get why it fails. For some reason the `pycparser` is not installed automatically as a dependency `pythonnet`. Should I include it in the `meta.yaml` just to fix the build?


This should be fixed in the feedstock of pythonnet instead of here as it is a dependency of that.

**Comment by Hugovdberg** [comment]
It is weird that it fails, as `pycparser` is in the dependencies of `pythonnet` if I interpret this correctly. Or is it a matter of `pycparser` being listed as a `host` dependency instead of `run` dependency? I don't exactly get the subtleties of those yet.

**Comment by Hugovdberg** [comment]
@m-rossi do you have some insights on why the `pythonnet` build succeeds but this build still misses the dependency?

**Comment by m-rossi** [comment]
> It is weird that it fails, as `pycparser` is in the dependencies of `pythonnet` if I interpret [this ](https://github.com/conda-forge/pythonnet-feedstock/blob/a56b3c0cab117ccb636a61ba7316c485cedbe5e5/recipe/meta.yaml#L16-L22) correctly. Or is it a matter of `pycparser` being listed as a `host` dependency instead of `run` dependency? I don't exactly get the subtleties of those yet.

I rechecked the dependencies of pythonnet (https://github.com/pythonnet/pythonnet/blob/v2.5.2/setup.py#L638) and it looks like we made a mistake here. I will create a PR to move `pycparser` up to the runtime dependencies.

Furthermore I have to note we currently have no support for linux and osx in the conda-forge version of pythonnet: https://github.com/conda-forge/pythonnet-feedstock/issues/9, I will try to look into that again over the weekend

**Comment by Hugovdberg** [comment]
This package doesn't really need OS X and Linux support from `pythonnet`, as the SDK it wraps is a .NET Framework 4.6 assembly. But as the code I wrote isn't really platform dependent, I didn't want to exclude the hacker who got that SDK running in mono or something. However, if it would prevent the builds from succeeding here on conda-forge I wil restrict it to windows only for the time being.

**Comment by m-rossi** [comment]
> This package doesn't really need OS X and Linux support from `pythonnet`, as the SDK it wraps is a .NET Framework 4.6 assembly. But as the code I wrote isn't really platform dependent, I didn't want to exclude the hacker who got that SDK running in mono or something. However, if it would prevent the builds from succeeding here on conda-forge I wil restrict it to windows only for the time being.

Yes, do that. As I said, I will try to look into that issue again this weekend. Once this PR for PIconnect is merged open an issue in the new repository referencing [the issue from the pythonnet-feedstock](https://github.com/conda-forge/pythonnet-feedstock/issues)

For reference here is the PR: https://github.com/conda-forge/pythonnet-feedstock/pull/12

**Comment by Hugovdberg** [comment]
@conda-forge-admin, please restart ci

**Comment by Hugovdberg** [comment]
I guess I restarted just too soon, let's try again.

@conda-forge-admin, please restart ci

**Comment by Hugovdberg** [comment]
How soon can I expect these builds to pick up a new version on conda-forge? Anaconda.org says the new version is only already, but the CI still picks up the older version.

**Comment by Hugovdberg** [comment]
@conda-forge-admin, please ping team

**Comment by xhochy** [comment]
> How soon can I expect these builds to pick up a new version on conda-forge? Anaconda.org says the new version is only already, but the CI still picks up the older version.

You need to wait 1-2h until they are available on the CDN

**Comment by Hugovdberg** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
