### PR TITLE
Add recipe for pygsp

### PR DESCRIPTION
**Pull request by mdeff**
Currently from git to test the build. Will make a new PyPI release once it works.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
You could build from the github tarball if you don't want to wait for pypi.

**Comment by mdeff** [comment]
Thanks! Though my problem is not waiting on PyPI, but being sure that I don't have to modify the package for conda before releasing it.

Waiting on travis is however painful... Any way around that?

**Comment by CJ-Wright** [comment]
You could put Travis-CI on your fork, which should give faster feedback. (thanks @jakirkham)

**Comment by mdeff** [comment]
Thanks I will try that if it's not built by tomorrow.

**Comment by mdeff** [comment]
[Travis passed on my fork](https://travis-ci.org/mdeff/staged-recipes/builds/316932904)

**Comment by mdeff** [comment]
@CJ-Wright can we merge?

**Pull request merged**
