### PR TITLE
Added `neptune` package

### PR DESCRIPTION
**Pull request by Raalsky**
We're in the process of renaming our package from neptune-client to neptune. As an intermediate step, we'll be updating both neptune-client and neptune packages.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Raalsky** [comment]
@conda-forge/bioconda-recipes, Hey, could you take a look? We're about to add a `neptune` recipe in the process of renaming `neptune-client`.

**Comment by troda** [comment]
@conda-forge/bioconda-recipes , to add more context to @Raalsky . We are from neptune.ai - Experiment tracker and model registry, relatively widely used tool in MLOps space.
As he mentioned, we renamed package from `neptune-client` to `neptune` (e.g. link to PyPI: https://pypi.org/project/neptune/ ). We maintain releases both in PyPI and Conda. And just noticed, thanks to warning, the same name recipe exists in Bioconda (we checked Conda beforehand, but not other Conda related package management places). We checked that package and it seems it is not maintained in the last 5-6 years.

We wonder if it would be possible to proceed with with adding our package `neptune` to Conda. It would be great for the consistency with PyPI. Could you help us here? Thanks!

**Comment by Raalsky** [comment]
Hey, @aniezurawski @HubertJaworski @pitercl @PatrykGala can you all confirm you are willing to be maintainers for this recipe? I do.

**Comment by pitercl** [comment]
I agree.

**Comment by HubertJaworski** [comment]
I agree.

**Comment by PatrykGala** [comment]
I agree.

**Comment by aniezurawski** [comment]
I agree.

**Comment by Raalsky** [comment]
@conda-forge/help-some-language, ready for review!

**Comment by Raalsky** [comment]
@conda-forge/help-python, ready for review!

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
