### PR TITLE
Add recipe for betfairlightweight

### PR DESCRIPTION
**Pull request by synapticarbors**
@liampauling has agreed to be a co-maintainer on this recipe

### CODE REVIEW

**Comment by synapticarbors** [comment]
The appveyor failures detected some windows-specific bugs that I'm fixing upstream. I'll update the recipe to a newer version of the package once they get merged.

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes Travis seems to be failing on python 3.4 because it's missing OpenSSL in the base build environment. Is this purposeful? It looked like other versions have it.

**Comment by jjhelmus** [comment]
> Travis seems to be failing on python 3.4 because it's missing OpenSSL in the base build environment. Is this purposeful?

Not intentional and very strange.  The `conda-forge` Python 3.4.5 package does list openssl as a dependency.  Specifically the `index.json` file from the `osx-64-python-3.4.5-2.tar.bz2` package:

``` json
{
  "arch": "x86_64",
  "build": "2",
  "build_number": 2,
  "depends": [
    "openssl 1.0.*",
    "readline 6.2*",
    "sqlite 3.13.*",
    "tk 8.5.*",
    "xz 5.2.*",
    "zlib 1.2.*"
  ],
  "license": "PSF",
  "name": "python",
  "platform": "osx",
  "subdir": "osx-64",
  "version": "3.4.5"
```

I restarted the Travis build to see if the issue persists.

**Comment by jjhelmus** [comment]
The issue is repeatable.  Let me try to debug this locally once I have access to a Mac.

**Comment by synapticarbors** [comment]
@jjhelmus Thanks for taking a look into this. How do you typically debug conda-forge build issues locally?

**Comment by jjhelmus** [comment]
I'm was just going to run the build locally on my Mac and see if I am getting the same packages being installed in the build environment.

**Comment by ocefpaf** [comment]
@synapticarbors and @jjhelmus see https://github.com/conda-forge/staged-recipes/pull/2112#issuecomment-268607530

I am not sure what is going on but changing to `conda-build 2` solves the problem.

**Comment by scopatz** [comment]
@ocefpaf - I think I am seeing something similar on cymetric #2091

**Comment by ocefpaf** [comment]
> @ocefpaf - I think I am seeing something similar on cymetric #2091

Looks similar. You can try to add the changes from https://github.com/conda-forge/staged-recipes/pull/2112/commits/0d396ffd2d5231251b6fe0e9106dba19837ecc91 to test it.

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes This recipe is ready for review. Pinging since it's an old recipe that I've recently fixed up.

**Pull request merged**
