### PR TITLE
Add snappy (Pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/staged-recipes/pull/193

Borrows the wonderful work from @groutr to add `snappy` and carries it the rest of the way.

* Templates the versions better.
* Adds the build number explicitly.
* Fixes some spacings to be aligned.
* Add myself as a maintainer.
* Skip Windows for now.

### CODE REVIEW

**Comment by jakirkham** [comment]
Just as FYI @groutr, it appears the VC project file [doesn't support]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.1418/job/n4c7ar7rkgmfv8w1#L216 ) the intended OS version.

**Comment by jakirkham** [comment]
This should be good to go whenever.

**Comment by ocefpaf** [comment]
> This should be good to go whenever.

:+1:

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Comment by jakirkham** [comment]
@groutr, as this is your first time being added as a maintainer here, I'm going to explain our Rube Goldberg machine of CIs and what it will do next. Once your name is added to this recipe, another batch script will run on a CI and pick up your handle from this list in this feedstock. It will then add you as a maintainer. This will cause GitHub to send you an email inviting you to join conda-forge. Once accepted this will add you to the `snappy` team, which has commit privileges on this repo. Going forward, anywhere you add your GitHub handle or it is added (with your permission) will automatically lead to you getting commit privileges on those repos. There will be no other action required on your behalf.

Thanks for helping us maintain `snappy` and welcome to conda-forge. 😄

**Pull request merged**
