### PR TITLE
Adding `mangum` from PyPI

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sugatoray** [comment]
## Notes for the reviewer

This is necessary in another PR: https://github.com/conda-forge/staged-recipes/pull/19349

There is another similar recipe for `mangum` there in #19349. It will be removed once this PR is merged.

**Comment by sugatoray** [comment]
PR is ready. Request for review/merging.

cc: @conda-forge/help-python

**Comment by sugatoray** [comment]
cc: @BastianZim

**Comment by BastianZim** [comment]
Duplicate of #19386

**Comment by sugatoray** [comment]
@BastianZim Thanks for pointing out the other one. But to me it seems that it (#19386) is a duplicate of this one. The other PR was opened on June 24 (yesterday), and this one was opened on 3 days ago (June 22).

I had also posted on the gitter channel about this one. I am a bit surprised as to why the other PR was not notified of this one?!!

Not only that, I had another recipe in https://github.com/conda-forge/staged-recipes/pull/19349 since June 21st.

I recall that were occasions when I was notified of another PR for the same package and mine was the duplicate back then. But clearly here #19386 was a duplicate of #19362. 

The first time I asked for review in the gitter channel, was on June 22.

image

Then I once again asked for review on June 24.

image

Surprisingly, it's quite a coincidence the author of #19386, `@thewchan` pushed the PR on the same day.

image


cc: @ocefpaf I am copying you here as you merged #19386.

**Comment by BastianZim** [comment]
Yes the other one was indeed later but merged first so I cannot mark it a duplicate. 

We don't have a mechanism for duplicate PRs, just duplicate feedstocks unfortunately. 

Sometimes duplicate PRs just happen and one gets merged first. There really is no way to prevent that unfortunately, as the number of PRs is so big that it is difficult to track everything. 

If you want, you can open an issue on the feedstock and ask if you can be added as a maintainer.

**Comment by sugatoray** [comment]
Could there be at least a required step for checking in open list of PRs, if another PR exists for the same package? I believe it doesn't take that long to run a quick search in GitHub for open PR's with the name of the package.

**Comment by ocefpaf** [comment]
In our distributed way of reviewing it is quite hard to mark PRs as duplicated b/c no one can look at all PRs. However, you can add yourself as a maintainer of the merged one.

**Pull request closed without merging**
