### PR TITLE
Add recipe for `sqlx-cli`

### PR DESCRIPTION
**Pull request by borchero**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by borchero** [comment]
Agree to be listed as maintainer ✅

**Comment by xhochy** [comment]
Let's wait for https://github.com/conda-forge/staged-recipes/pull/26081 and then the comment from there can be applied here.

**Comment by xhochy** [comment]
The checks say that `openssl` is not used. Does it work if you omit it?

**Comment by borchero** [comment]
@xhochy seems to be required:

```
Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.101
```

I'm re-adding the dependency.

**Comment by borchero** [comment]
> The checks say that openssl is not used

I'm not sure why this would be the case though. Would the check vanish if I add `openssl` to something other than the host dependencies?

**Comment by borchero** [comment]
@conda-forge/help-rust this is ready for review :smile:

**Review by xhochy — APPROVED** [review]

**Pull request merged**
