### PR TITLE
WIP: Zeroc ice36 python

### PR DESCRIPTION
**Pull request by manics**
Adds Zeroc Ice 3.6

This was originally packaged in bioconda as a dependency of OMERO, which is being moved to conda-forge: https://github.com/bioconda/bioconda-recipes/pull/15831

This recipe is based on https://github.com/ome/conda-zeroc-ice36-python/tree/9350c567e0f1aee6726a413ccee51f5c9a656bd3 currently published on https://anaconda.org/ome/zeroc-ice36-python

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] ~~If static libraries are linked in, the license of the static library is packaged.~~
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by manics** [comment]
Ice 3.6.5 requires Mac OS X 10.13. I've tried to set this following https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks but it didn't work. I then tried overriding `CONDA_BUILD_SYSROOT` but that still hasn't worked.

**Comment by manics** [comment]
@conda-forge/staged-recipes Could I have some help please? This is a follow-up to https://github.com/bioconda/bioconda-recipes/pull/15831 where we decided to move the relevant packages from bioconda to conda-forge.

Ice 3.6.5 supports TLS 1.3, and won't build on older versions of OS X.

I tried to [follow the instructions for requiring a newer OS X SDK](https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks) in https://github.com/conda-forge/staged-recipes/pull/10324/commits/9a6b0d3b395390b3dcbfc471e870f028fe0ef517 but that didn't work.

Subsequent commits https://github.com/conda-forge/staged-recipes/pull/10324/commits/cc7a2caa7e9a490d661b338afb5b3732db61df92 and https://github.com/conda-forge/staged-recipes/pull/10324/commits/96bfbde8585309458ed055d92af766d1c5f3a486 were me trying random stuff, without success

**Comment by jakirkham** [comment]
Reopening as it looks like this just hasn't been reviewed.

Would someone from @conda-forge/staged-recipes be able to take a look? 🙂

**Comment by jakirkham** [comment]
Sorry actually I may have misunderstood, @manics. Is this just the same as [`zeroc-ice`]( https://github.com/conda-forge/zeroc-ice-feedstock )? In which case, maybe we should just go ahead with PR ( https://github.com/conda-forge/zeroc-ice-feedstock/pull/6 ) and close this?

**Comment by manics** [comment]
Yes, both PRs ended up being opened at the same time so we can close this. I'll look into the error on https://github.com/conda-forge/zeroc-ice-feedstock/pull/6

**Comment by jakirkham** [comment]
Thanks Simon! 😀

**Pull request closed without merging**
