### PR TITLE
add batman recipe

### PR DESCRIPTION
**Pull request by tupui**

### CODE REVIEW

**Comment by tupui** [comment]
Thanks @scopatz 😃

**Comment by tupui** [comment]
@scopatz Hi, I'm not sure what I did wrong but I am not able to do `conda install -c conda-forge batman`. It says the package does not exists. Also, on https://github.com/conda-forge/batman-feedstock all build status are not correct. Thanks for you help!

**Comment by bgruening** [comment]
The windows build is not done and all other are deactivated, so you still need to wait as it seems.

**Comment by tupui** [comment]
@bgruening OK but why is there a windows build? My package does not work on windows. This is why I set `[not win]` and in the commit here and on the feedstock `[skip appveyor]`.

**Comment by scopatz** [comment]
@tupui maybe try rerendering the project locally

**Comment by bgruening** [comment]
You sayed [not win] to skip build. This means you skipped all build except of Windows. In conjunction with `add batman recipe [skip appveyor]` you actually never did test your recipe. So this should never be merged I think.

**Comment by isuruf** [comment]
`skip: True # [not win]` skips platforms that are not windows. You need `skip: True # [win]` which skips windows

**Comment by tupui** [comment]
@bgruening @isuruf  oh I see. All check passed so I did not see the bug, sorry!

**Pull request merged**
