### PR TITLE
Add pycrypto

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a recipe to build `pycrypto`. Basically used `conda skeleton pypi` and made some tweaks after.

Please share thoughts and feedback. Maintainers welcome.

cc @pelson @ocefpaf @kalefranz @msarahan @mcg1969

### CODE REVIEW

**Comment by jakirkham** [comment]
Currently trying to get it to pickup GMP or MPIR on Windows. Not having much luck at present. Suggestions welcome.

**Comment by jakirkham** [comment]
Seeing a fun test failure on Windows. Traceback below. See this [log]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.2898/job/yi0wanyiw6k3px5i ) for details. Any thoughts on this would be appreciated.

```
======================================================================
ERROR: runTest (Crypto.SelfTest.Random.test__UserFriendlyRNG.RNGMultiprocessingForkTest) 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build\lib.win32-2.7\Crypto\SelfTest\Random\test__UserFriendlyRNG.py", line 132, in runTest
    manager = multiprocessing.Manager()
  File "C:\Miniconda\envs\_build\lib\multiprocessing\__init__.py", line 99, in Manager
    m.start()
  File "C:\Miniconda\envs\_build\lib\multiprocessing\managers.py", line 524, in start
    self._process.start()
  File "C:\Miniconda\envs\_build\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Miniconda\envs\_build\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Miniconda\envs\_build\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.
 
            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:
 
                if __name__ == '__main__':
                    freeze_support()
                    ...
 
            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
 
---------------------------------------------------------------------- 
Ran 1034 tests in 103.281s 
 
FAILED (errors=1) 
Traceback (most recent call last): 
  File "<string>", line 1, in <module>
  File "C:\Miniconda\envs\_build\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Miniconda\envs\_build\lib\multiprocessing\forking.py", line 509, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Miniconda\conda-bld\work\pycrypto-2.6.1\setup.py", line 456, in <module>
    core.setup(**kw)
  File "C:\Miniconda\envs\_build\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Miniconda\envs\_build\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Miniconda\envs\_build\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\conda-bld\work\pycrypto-2.6.1\setup.py", line 336, in run
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, config=self.config)
  File "build\lib.win32-2.7\Crypto\SelfTest\__init__.py", line 74, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=1034 errors=1 failures=0>)
E........................... 
====================================================================== 
ERROR: runTest (Crypto.SelfTest.Random.test__UserFriendlyRNG.RNGMultiprocessingForkTest) 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build\lib.win32-2.7\Crypto\SelfTest\Random\test__UserFriendlyRNG.py", line 132, in runTest
    manager = multiprocessing.Manager()
  File "C:\Miniconda\envs\_build\lib\multiprocessing\__init__.py", line 99, in Manager
    m.start()
  File "C:\Miniconda\envs\_build\lib\multiprocessing\managers.py", line 528, in start
    self._address = reader.recv()
EOFError
 
----------------------------------------------------------------------
Ran 1034 tests in 388.921s 
 
FAILED (errors=1)
```

**Comment by jakirkham** [comment]
I'm guessing `conda-build` forks and then `pycrypto` forks in this test and that causes the problem. So, we cannot run the fork test then. Maybe we can skip it?

**Comment by jakirkham** [comment]
Canceled the AppVeyor build as they are hanging post-test failure now.

**Comment by jakirkham** [comment]
So, the patch seemed to work, but for some reason the tests appear to have been run twice and they fail the second time. Going to figure out what is going on.

**Comment by jakirkham** [comment]
🎉 Windows builds fixed 🎉

Will update to note upstream PRs.

**Comment by jakirkham** [comment]
All AppVeyor builds passed, but one, which failed due to a download issue. Unfortunately, we will have to restart them all. 😝

**Comment by jakirkham** [comment]
Should add all changes have been submitted upstream.

**Comment by jakirkham** [comment]
Yet another download [error]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.2977/job/9554ua5s8atdafnp#L1052 ). Restarting again.

**Comment by jakirkham** [comment]
Passing. 😄

**Comment by jakirkham** [comment]
Feedback welcome. Some questions I have. Do we want to `python-` prefix this? It is a standard package in Miniconda so is in `defaults`. Still we do want to start moving towards `python-`. Please let me know what you guys think. Similar discussion started happening with `funcsigs` ( https://github.com/conda-forge/staged-recipes/pull/712 ).

**Comment by patricksnape** [comment]
It feels like this `python-` prefix decision should be one that is quite central to conda itself. I'm not opposed to it as Debian follows the same pattern but we definitely need to make sure we are consistent. I'm not sure how else you would solve it though - another piece of filterable metadata like tags? Features doesn't feel like the right tool for the job.

**Comment by jakirkham** [comment]
Sure, I agree we should do it. My only concern is compatibility as some things expect to find `pycrypto` currently.

@msarahan and I were playing with a metapackage that has the old name, but starts out deprecated. In that case, the metapackage would be `pycrypto`, but `python-pycrypto` would be the actual package. So, I don't know how people feel about that. It seemed that in our meeting last week that some people wanted metapackages for existing things in `defaults`. Not quite sure what the expiration is on that, but it wouldn't be forever.

**Comment by patricksnape** [comment]
So would that be with an eye to, at somepoint, remove the metapackage once people are 'used' to the `python-` prefixed names? Not necessarily the worst idea, though I can foresee a lot of things breaking upon the expiration of that metapackage!

**Comment by jakirkham** [comment]
> Not necessarily the worst idea, though I can foresee a lot of things breaking upon the expiration of that metapackage!

We can also have breakage by switching now. In the end, I think we are going to have to go this way anyways due to the proliferation of Python packages without prefixing and special cases like `numpy` that need to be converted over.

**Comment by mcg1969** [comment]
Our design for namespaces is intended to prevent the need for prefixing on a wide scale. I consider it imperative that PyPi and conda package names remain identical whenever possible.

**Comment by mcg1969** [comment]
To be clear, that imperative applies to the command line; e.g. `conda install numpy` should never become `conda install python-numpy`. How that translates to file names is more fungible.

**Comment by msarahan** [comment]
My interpretation of this is that the package: name field in meta.yaml should never have a prefix. Recipe folders may have prefixes. 

Is that correct @mcg1969? 

@jakirkham, until conda supports namespaces properly, can we limit python- prefixing to only conflicting packages like graphviz, where the native package name and some derivative language (python) have the same name?

**Comment by mcg1969** [comment]
That's a good way of putting it, @msarahan. The problem, however, is that the assumption that the filename begins with the `package: name` field is baked into conda throughout. You know I wish that were not the case---that filenames were not parsed, but used only as keys into the index---but that's the world we inherited. So no matter how the namespace notion is finalized, something is going to have to change in conda.

I freely admit that prefixing is the only way *now* to separate ecosystems, and because of our insistence on preserving a prefix-free experience (to the extent possible) for Python, that means other ecosystems like R are going to be treated differently. Such is the perk of being first past the post. Our stated goal with namespaces however is to level the playing field---not by worsening the Python experience, but by improving the others.

**Comment by msarahan** [comment]
But the filename includes some suffix for language - py27, r33, etc., so we
should be able to ignore file overlaps, right?

**Comment by mcg1969** [comment]
Right. Filename collisions aren't the problem. The problem is that the current versions of conda assume that the value of `filename.rsplit('-',2)[0]` is unique to a single logical package family. Thus if you have `graphphiz-*-native.tar.bz22`, `graphviz-*-python.tar.bz2`, and `graphviz*-r.tar.bz2`, conda 4.1 and earlier will assume they are from the same package group, and only one of them will be installable.

With namespaces, conda will know that each of these packages can be installed alongside each other.

**Comment by msarahan** [comment]
Got it.  Thanks for clarifying.

**Comment by jakirkham** [comment]
> @jakirkham, until conda supports namespaces properly, can we limit python- prefixing to only conflicting packages like graphviz, where the native package name and some derivative language (python) have the same name?

Whether or not I comment on this, I know @pelson is going to want to share some thoughts as well. I guess this is going back on the agenda.

That all being said, my general feeling about prefixing is I don't want to spend any more cycles thinking about it. Having the addition of the prefix being conditional leads to the question of "should it be here?" and related "why?", which ends up not only being tedious, but tends to lead to rancorous debate. Just adding it everywhere keeps life simple.

**Comment by jakirkham** [comment]
Though I should add we are probably going to have to go back fix a lot of feedstocks.

**Comment by mcg1969** [comment]
We're not adopting the `python-` convention globally in the defaults channel. We are maintaining our convention to mirror the PyPi package name in conda, so that anyone who knows they could do `pip install xxx` can confidently do `conda install xxx` instead. We will deal with the exceptions like `graphviz` on a case by case basis, even though it causes extra work for the package maintainers, because that's the better experience for users.

Yes, this means we're favoring Python. We are striving for conda to be cross-platform, true. Heck, I've seen some crazy talk about getting it to the point where you could build a Linux distribution on it. But it is not there yet. But we don't want to get there by damaging the user experience. We want people utilizing other package ecosystems to get the same general experience that Python users are already enjoying. Seeking for the least common denominator fails that test.

The namespace solution is going to take some work, yes, but it's going in the right direction: not degrading the Python experience, but elevating the others. And it shouldn't add significant burden (if any) to the package maintainer, either. Typical Python packages will automatically be classified as members of the `python` space by virtue of their dependency on Python---no change to the recipe needed to get the benefits of namespace separation. Same goes for any other package ecosystem.

**Comment by jakirkham** [comment]
Don't really want to get into the whole namespacing discussion here as I feel that it belong in an issue dedicated to that (probably at `conda`/`conda-build`). Having it here will simply result in dispersed information that will be hard to track down later. Suffice it to say I have lots of questions about it and will save them for the appropriate issue. Nor do I want to get into a discussion about potential differences between `defaults` and `conda-forge` channels. Even if/when we go the prefixing direction anyway, I don't see us avoiding a bunch of renames on existing feedstocks. I would be ok with addressing `pycrypto` in this same process so that we can get this recipe out into the open sooner.

If there are no complaints with this recipe, let's get this merged.

**Comment by jakirkham** [comment]
Alright, it's been a day and I haven't heard any discussion about anything w.r.t. the recipe (other than its name). I'm going to go ahead and merge this as is. Feedback welcome in the feedstock.

**Pull request merged**
