### PR TITLE
Package PyCUDA

### PR DESCRIPTION
**Pull request by inducer**
Fixes https://github.com/conda-forge/staged-recipes/issues/3178

### CODE REVIEW

**Comment by inducer** [comment]
Not sure how to get the relevant dev files installed. They're non-free, and `cudatoolkit` doesn't have them.

**Comment by inducer** [comment]
* Has something changed regarding the packaging of `cudatoolkit`? If not, then you should start by packaging the relevant Nvidia dev files.
* It looks like the package needs a rerender, maybe

**Comment by jakirkham** [comment]
FWIW this may be more approachable today. 🙂

**Comment by jakirkham** [comment]
Tried to fix this up so this works with CUDA support in conda-forge. Going to keep an eye out for the packages to be produced and test them out locally to make sure they work ok

**Comment by inducer** [comment]
Thanks for working on this!

**Comment by inducer** [comment]
(Happy to serve as co-maintainer if you'd like me to.)

**Comment by jakirkham** [comment]
Ofc thanks for getting this started and answering questions on the way 🙂

That would be great! 😄

**Pull request merged**
