### PR TITLE
Remove scp

### LINKED ISSUE #838: Master is broken at the moment
@pelson not sure what is going on. The `scp` feedstock was created properly. So I will remove the recipe manually for now. Is that OK? (See https://travis-ci.org/conda-forge/staged-recipes/jobs/139270697)

```shell
CI support files regenerated. These need to be pushed to github!
[master 9b6f864] Re-render the feedstock after CI registration.
 2 files changed, 7 insertions(+), 7 deletions(-)
 rewrite conda-forge.yml (85%)
rm 'recipes/scp/meta.yaml'
HEAD detached at b193d4a
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
	deleted:    recipes/scp/meta.yaml
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Miniconda3-latest-MacOSX-x86_64.sh
	bootstrap-obvious-ci-and-miniconda.py
Previous HEAD position was b193d4a... Merge pull request #830 from ocefpaf/add_scp
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
	Miniconda3-latest-MacOSX-x86_64.sh
	bootstrap-obvious-ci-and-miniconda.py
nothing added to commit but untracked files present
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 264, in <module>
    subprocess.check_call(['git', 'commit', '-m', msg])
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'Removed recipe (scp) after converting into feedstock. [ci skip]']' returned non-zero exit status 1
```

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #838

### CODE REVIEW

**Comment by jakirkham** [comment]
I don't think we need this as it appears to already be removed. ( https://github.com/conda-forge/staged-recipes/commit/baf5c2521aa2bf5f92d5518069cc86d8965b5cd0 )

**Comment by ocefpaf** [comment]
It seems that Travis-CI has finally caught up!

**Comment by jakirkham** [comment]
Yay!

So, fun fact, it turns out the OS X builds and Linux container builds share the same queue. This caused some of the hold-up we experienced over the last day or so.

**Comment by jakirkham** [comment]
They just announced that the issue is [resolved]( https://www.traviscistatus.com/incidents/nf3tg08pqg2d ).

**Pull request closed without merging**
