### PR TITLE
NO MRG: CheMPS2

### PR DESCRIPTION
**Pull request by loriab**
This is a conda-forge translation of a recipe for CheMPS2 (http://sebwouters.github.io/CheMPS2/index.html). I've a number of macOS and linux recipes (ambit, chemps2, pychemps2, dftd3, pcmsolver, psi4 at https://github.com/psi4/psi4meta/tree/master/conda-recipes hosted at https://anaconda.org/psi4). conda-forge isn't really suitable for the linux recipes because we like special compilers, but I thought it might be useful for the macOS ones.

These recipes are combinations of python, c++, and fortran. Some special considerations are:
- we like building with gcc over clang for parallelism
- there's fortran involved, so we need gfortran
- we've hit serious issues upon mixed linking against `libstdc++` and `libc++` 

Upon advice, while _this_ package might be suitable for conda-forge, I don't know if it'll be suitable for all the psi4 ecosystem packages.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@loriab thanks for the recipe. As we discussed here at SciPy (unfortunately) conda-forge decisions make it hard for you to send you packages as you need `gcc` on OS X instead of `clang`.

I will bring that up in our next meeting and we can resurrect the discussion. Maybe we will find a long term solution for this.

BTW do you want this merged anyways? I believe it may be a bad idea as it can get in the way when you mix your channel with `conda-forge`?

**Comment by jakirkham** [comment]
Thanks @loriab. We currently have been building with `clang` to satisfies various people's needs here and to work around certain problems we had encountered with the `gcc` package. After discussions a month back, we agreed on switching to a newer `gcc` package that will hopefully satisfy everyone's needs. I'm hopefully that the new `gcc` package will satisfactorily work for everyone. It is merely of having the resource to complete that task. This all being said, I see no issues with the choice to use `gcc` here.

**Comment by loriab** [comment]
Thanks, @jakirkham, a switch to gcc would be very useful from my perspective. @ocefpaf, I agree that merging this PR could cause considerable channel tangles while being of minor benefit. So please don't merge it or even delete it.

**Comment by jakirkham** [comment]
So there is some discussion on the addition of `gcc` in this issue ( https://github.com/conda-forge/staged-recipes/issues/872 ). Also this is a PR ( https://github.com/conda-forge/staged-recipes/pull/873 ) that contains a `gcc` recipe that is in the works. We still have quite a bit of ground to cover, but we are at least in agreement that this is what needs to be done.

**Pull request closed without merging**
