### PR TITLE
Adding `numpydantic`

### PR DESCRIPTION
**Pull request by apcamargo**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by apcamargo** [comment]
@sneakers-the-rat would you like to be included as a maintainer of the conda-forge feedstock?

**Comment by apcamargo** [comment]
@conda-forge/help-python, ready for review!

**Comment by sneakers-the-rat** [comment]
Sure! Ive never done so, but I shall figure out what thay entails :)

**Comment by apcamargo** [comment]
Great! Thank you

**Comment by apcamargo** [comment]
Not sure why the linter is complaining. The only change in the last commit was the addition of a maintainer.

**Comment by sneakers-the-rat** [comment]
As I said I havent maintained a conda forge package before, but lmk if theres anything I need to change in the repo to make this work - curious to learn

**Comment by apcamargo** [comment]
Right now the library is been pulled from PyPI and everything seems ok. The package is building and passing the test :)

**Comment by apcamargo** [comment]
Thanks @hmaarrfk! Out of curiosity, why would grayskull make the recipe in my other PR (https://github.com/conda-forge/staged-recipes/pull/27389) `noarch` but not this one? None contained compiled code.

Also, the linter didn't complain in my original commit. Only after I added a contributor to the recipe.

**Comment by hmaarrfk** [comment]
maybe because of the typing-extensions???

**Comment by sneakers-the-rat** [comment]
ok question for y'all - do i need to do something in my CI (have yet to set up CD, but this would be a good reason to do so) to update the feedstock when i release a new version, or will conda-forge do that automatically? trying to both be a cooperative maintainer here and also learn a bit how this works :)

**Comment by synapticarbors** [comment]
When a new version gets released to pypi, the regro-bot should issue a pull request that updates the version, hash and rerenders the recipe. See:
https://conda-forge.org/docs/maintainer/updating_pkgs/#pushing-to-regro-cf-autotick-bot-branch

The bot can also be configured to use grayskull to look for dependency changes using `inspection: update-grayskull` in:
https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot

**Comment by apcamargo** [comment]
For most updates, the bot should pull the release from PyPI and create a PR automatically. The most common scenarios where we need to actively change the recipe (the `.yaml` file that describes how to build and test the library) are when there are changes in the dependencies or when the build fails for some reason.

**Comment by sneakers-the-rat** [comment]
Gotcha. Thx for the docs links ill take a read.

There shouldnt ever be new required deps added to this (purposefully low-dep) package, but there will probably be bumps to minimum versions at some point. Ill make sure CI keeps those in sync.

**Pull request merged**
