### PR TITLE
Add opencv-python-headless

### PR DESCRIPTION
**Pull request by roaldarbol**
Checklist
- [ x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by traversaro** [comment]
See also https://github.com/conda-forge/opencv-feedstock/issues/293 .

**Comment by synapticarbors** [comment]
Looking through https://github.com/conda-forge/opencv-feedstock/issues/293, given it's age and the general conclusion that the maintainers didn't want to add this in that feedstock, is there an issue with moving ahead with a separate feedstock for this? There have been other PRs that have needed this (e.g https://github.com/conda-forge/staged-recipes/pull/25298). I'm not that familiar with OpenCV. Would another alternative be just to add a patch to the recipes that require the headless one to just grab the full version instead?

**Comment by traversaro** [comment]
> Looking through [conda-forge/opencv-feedstock#293](https://github.com/conda-forge/opencv-feedstock/issues/293), given it's age and the general conclusion that the maintainers didn't want to add this in that feedstock, is there an issue with moving ahead with a separate feedstock for this? There have been other PRs that have needed this (e.g #25298). I'm not that familiar with OpenCV. Would another alternative be just to add a patch to the recipes that require the headless one to just grab the full version instead?

Just to understand, what does "other PRs that have needed this" mean in this context? `opencv-python` is a superset of `opencv-python-headless`, so if the problem is just to ensure that `pip check` does not complain when it finds `opencv-python` and not `opencv-python-headless`, a possible solution is just to patch the upstream's setup.py to refer to `opencv-python` instead of `opencv-python-headless`.

**Comment by hmaarrfk** [comment]
We’ve added configs to opencv to this.

**Pull request closed without merging**
