### PR TITLE
add pynetcf

### PR DESCRIPTION
**Pull request by cpaulik**
Since we have pygeogrids and pygeobase now in conda-forge I'm continuing with our next package.

### CODE REVIEW

**Comment by cpaulik** [comment]
@conda-forge/core This might be a bug with the linter. At least I can not find a reason why it ignores the `pynetcf` folder.

**Comment by jakirkham** [comment]
That's strange. Going try closing and reopening the PR to see if the issue persists.

**Comment by jakirkham** [comment]
The CIs actually aren't building the recipe either. It looks like it is in the right directory. Must be missing something here. 😕 

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/220574974#L207-L209

**Comment by cpaulik** [comment]
:sweat_smile:   :man_facepalming: I've looked at this 5 times without seeing that. Thanks.

**Pull request closed without merging**
