### PR TITLE
Only build R recipes with r-base versions provided by conda-forge.

### PR DESCRIPTION
**Pull request by jdblischak**
cc @isuruf @ocefpaf @bgruening @Cashalow 

xref: https://github.com/conda-forge/staged-recipes/issues/4320 https://github.com/conda-forge/conda-smithy/pull/604 https://github.com/conda-forge/conda-smithy/issues/603

### CODE REVIEW

**Comment by bgruening** [comment]
Oh, here as well? Interesting good to know!
Thanks for finding this!

**Comment by isuruf** [comment]
@jdblischak, shall I cancel the appveyor build you triggered here for the PRs? We need to test this and get this in before those PRs are tested.

**Comment by jdblischak** [comment]
> shall I cancel the appveyor builds you triggered here for the r package PRs?

@isuruf Yes, you can cancel any pending builds for R recipes.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
