### PR TITLE
Adding wcstools

### PR DESCRIPTION
**Pull request by jhunkeler**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jhunkeler** [comment]
I am willing to be listed as a maintainer

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
Joe, you should have stopped when it was green. 😆

**Comment by pllim** [comment]
Green now! Is this ready? Should I ping @mwcraig to merge?

**Comment by jhunkeler** [comment]
Not yet. I realized last night the ancient libwcs provided by wcstools is in conflict with the real `wcslib` package, so I need to do some renaming to make them coexist properly. So `libwcs.so` will be `libwcstools.so` and the headers will get dumped into `include/wcstools/`

Always something :tm:

**Comment by jhunkeler** [comment]
I can install `wcslib` and `wcstools` into the same environment now. I think we're good.

**Comment by mwcraig** [comment]
Looks good -- Thanks for including the libwcs license.

**Pull request merged**
