### PR TITLE
Added spaCy PT model.

### PR DESCRIPTION
**Pull request by JIVJGFJZKF**

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/core It looks like this was never converted into a feedstock despite disappearing from the master branch? 😕

**Comment by scopatz** [comment]
Not sure what happened here.  Can you try putting in another PR with this @JIVJGFJZKF @chrisburr? Thanks!

**Comment by chrisburr** [comment]
Will do, thanks for taking look.

**Comment by scopatz** [comment]
Yeah, I looked for the correct commit to rerun, but couldn't find it.  Probably some weird state/interference with another PR

**Comment by chrisburr** [comment]
And it has [worked this time](https://github.com/conda-forge/spacy-model-pt-feedstock). Thanks again!

**Pull request merged**
