### PR TITLE
Eigen3 recipe

### PR DESCRIPTION
**Pull request by mjscosta**
- c/c++ `@conda-forge/help-c-cpp`

### CODE REVIEW

**Comment by mjscosta** [comment]
Hi, let me know if every thing is ok @conda-forge/help-c-cpp.
Cheers

**Comment by beckermr** [comment]
I'm going to close this PR. Please make an issue on eigen feedstock to get what you need, or simply use the version we have.

**Comment by mjscosta** [comment]
@beckermr Thanks, my bad!

**Comment by beckermr** [comment]
No worries! Happy eigening and thank you so much for taking the time to submit something you needed but could not find!

**Pull request closed without merging**
