### PR TITLE
Adding recipe for pygalmesh

### PR DESCRIPTION
**Pull request by flothesof**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by flothesof** [comment]
@conda-forge-admin, please ping team @conda-forge/help-python-c

Dear @conda-forge/help-python-c team, I would love to have some feedback on this.

So far @nschloe  and I have been discussing this here: https://github.com/nschloe/pygalmesh/issues/81

Best regards,

Florian

**Comment by nehaljwani** [comment]
@flothesof If you look at the raw logs and search for the keyword: `error:` you'll be able to see the actual error.

https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/152248/logs/28

```
2020-05-02T18:17:20.6852216Z   src/generate.cpp:180:9:   required from here
2020-05-02T18:17:20.6859239Z   /home/conda/staged-recipes/build_artifacts/pygalmesh_1588443296184/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include/CGAL/Mesh_criteria_3.h:120:78: error: no matching function for call to 'CGAL::Mesh_cell_criteria_3<CGAL::Mesh_3_regular_triangulation_3_wrapper<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_data_structure_3<CGAL::Mesh_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Mesh_domain_with_polyline_features_3<CGAL::Labeled_mesh_domain_3<CGAL::Epick> >, CGAL::Regular_triangulation_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Compact_mesh_cell_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Mesh_domain_with_polyline_features_3<CGAL::Labeled_mesh_domain_3<CGAL::Epick> >, void>, CGAL::Sequential_tag> >, CGAL::Mesh_3::Cell_criteria_visitor_with_features<CGAL::Mesh_3_regular_triangulation_3_wrapper<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_data_structure_3<CGAL::Mesh_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Mesh_domain_with_polyline_features_3<CGAL::Labeled_mesh_domain_3<CGAL::Epick> >, CGAL::Regular_triangulation_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Compact_mesh_cell_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Mesh_domain_with_polyline_features_3<CGAL::Labeled_mesh_domain_3<CGAL::Epick> >, void>, CGAL::Sequential_tag> > > >::Mesh_cell_criteria_3(const double&, const pygalmesh::generate_with_sizing_field(const std::shared_ptr<pygalmesh::DomainBase>&, const string&, const std::vector<std::vector<std::array<double, 3> > >&, double, bool, bool, bool, bool, double, double, double, double, double, const std::shared_ptr<pygalmesh::SizingFieldBase>&, bool)::<lambda(CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>::Point_3, int, const Index&)>&)'
2020-05-02T18:17:20.6864344Z                                     | args[parameters::sizing_field | FT(0)] ] ])
2020-05-02T18:17:20.6864869Z                                                                                 ^
```

If you look further closely, you'll see that the cgal library being used is:
```
    cgal-cpp:         4.14.1-h261e690_0         conda-forge
```

Other observations:

- You don't need numpy during build time.
- You need cgal-cpp (the header only c++ package) and not the cgal python package.
- You also need mpfr and gmp as build time dependencies.
- pybind11 is a header only library. You don't need it at runtime.
- meshio is required at runtime by this package.
- The sdist on pypi doesn't have a license file. Please open a bug report with the authors, mention it here and till they fix it, you can follow: https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually
- It seems that v0.6.2 of pygalmesh is not compatible with cgap-cpp 4.14.1. You'll need v5.x.y.

Try the following diff:
```diff
diff --git a/recipes/pygalmesh/meta.yaml b/recipes/pygalmesh/meta.yaml
index 29928c490..966c5aa38 100644
--- a/recipes/pygalmesh/meta.yam.
+++ b/recipes/pygalmesh/meta.yaml
@@ -20,21 +20,20 @@ requirements:
     - python
     - pip
     - eigen
-    - cgal
+    - cgal-cpp >=5.0.0,<6
     - pybind11
-    - numpy
+    - mpfr
+    - gmp
   run:
     - python
-    - eigen
-    - cgal
-    - pybind11
-    - {{ pin_compatible('numpy') }}
+    - meshio

 test:
   imports:
     - pygalmesh
   requires:
     - pytest
+    - numpy
   source_files:
     - test
   commands:
@@ -44,7 +43,7 @@ about:
   home: https://github.com/nschloe/pygalmesh/
   license: GPL-3.0
   license_family: GPL
-  license_file: LICENSE
+  #license_file: LICENSE
   summary: 'A Python frontend to CGAL’s 3D mesh generators.'
   description: |
     pygalmesh is a Python frontend to CGAL’s 3D mesh generation capabilities. pygalmesh makes it easy to create high-quality 3D volume meshes, periodic volume meshes, and surface meshes.
```

**Comment by flothesof** [comment]
Thank you so much for your feedback, @nehaljwani ! This was exactly the sort of expertise I was hoping for. I'll look into all of the points you mentioned and try to work on them.

Regards,
Florian

**Comment by flothesof** [comment]
@nehaljwani following the modifications you suggested, the current status now is:
- builds succeding on linux and osx but failing unit tests (one on linux, two on osx)
- build not succeeding on windows due to the fact that gmp does not exist for windows

I'm going to discuss the unit tests failing on the original repo. Regarding the gmp issue on windows, do you have any suggestion? I'm also wondering how you determined that gmp and mpfr need to be included in the build dependencies. Is that something due to cgal-cpp? 

Anyways, thank you very much for your help!

**Comment by nschloe** [comment]
I've updated pygalmesh to 0.6.3, it now includes the license file.

And yes, it's okay to put me in the maintainers section of this recipe.

**Comment by nschloe** [comment]
@flothesof In 0.6.4, I've updated the license specifier to a SPDX string.

**Comment by nehaljwani** [comment]
@flothesof , take a look at: https://github.com/nehaljwani/staged-recipes/pull/3/commits/ca71869a371c524e48f66a384e8c6b19b771b49c for the changes required for the windows build to pass. (You can ignore the tolerance related changes)

**Comment by nehaljwani** [comment]
In that change, I use mpir instead of gmp on Windows. I'll send a PR upstream for the changes in setup.py

**Comment by nschloe** [comment]
@flothesof Try 0.6.5, it includes @nehaljwani's changes.

**Comment by nschloe** [comment]
Tolerances need to be relaxed for windows even more. Will take care of it.

**Comment by flothesof** [comment]
@nehaljwani Would you care to review? Thanks again for your help in getting things to work :)

**Comment by nehaljwani** [comment]
As far as I can tell, nothing is being linked in statically, explicitly. There are some header only dependencies which get used inside the final extension, but I don't think there is any specific policy (by conda-forge) in terms of licensing for them. 

This LGTM. Merging !

**Comment by nehaljwani** [comment]
Thank you for your time and effort @flothesof and @nschloe !

**Pull request merged**
