### PR TITLE
Add recipe for r-spray, conda_r_skeleton used

### PR DESCRIPTION
**Pull request by npavlovikj**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by npavlovikj** [comment]
Missing dependency is in #9524 .

**Comment by dbast** [comment]
@npavlovikj Please update your conda-build and conda_r_skeleton versions... see the update commit.

**Comment by npavlovikj** [comment]
Thanks @dbast , I appreciate the info!

**Comment by dbast** [comment]
The recipe is now 100% generated via conda_r_skeleton_helper https://github.com/bgruening/conda_r_skeleton_helper (using a recent conda-build version) ... the linter is now fine and also the CI builds are fine -> merging.

**Pull request merged**
