### PR TITLE
Adding `eval_type_backport` recipe

### PR DESCRIPTION
**Pull request by tasansal**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by tasansal** [comment]
@alexmojaki I also added you as a maintainer here, can you please leave a comment to confirm you are willing to be listed as a maintainer.

**Comment by alexmojaki** [comment]
:+1: I am willing to be listed as a maintainer.

**Comment by tasansal** [comment]
@conda-forge/help-python, ready for review!

**Comment by tasansal** [comment]
@ocefpaf quick question. Just realized this. The package on pypi is `eval-type-backport` and the Python module is `eval_type_backport`. 

In here, should we rename the `pagkage::name` section to the one with hyphens for consistency? or does conda not care if its hyphen or underscore?

TIA.

**Comment by ocefpaf** [comment]
> In here, should we rename the `pagkage::name` section to the one with hyphens for consistency? or does conda not care if its hyphen or underscore?

A package name doesn't necessarily have to be the same as its import name. With that said, it is nice to use the name that the upstream devs used to publish it. However, in Python land, specifically PyPI, both `-` and `_` versions are OK for installing a package. That is not true for conda b/c conda is not a Python package manager and name-something is different from name_something. What we can do to mimic PyPI's name handling is to publish another package, using multiple outputs, with the name variant. See https://github.com/conda-forge/importlib_resources-feedstock/blob/main/recipe/meta.yaml for an example.

**Comment by tasansal** [comment]
> > In here, should we rename the `pagkage::name` section to the one with hyphens for consistency? or does conda not care if its hyphen or underscore?
> 
> A package name doesn't necessarily have to be the same as its import name. With that said, it is nice to use the name that the upstream devs used to publish it. However, in Python land, specifically PyPI, both `-` and `_` versions are OK for installing a package. That is not true for conda b/c conda is not a Python package manager and name-something is different from name_something. What we can do to mimic PyPI's name handling is to publish another package, using multiple outputs, with the name variant. See https://github.com/conda-forge/importlib_resources-feedstock/blob/main/recipe/meta.yaml for an example.

ok I see. Is it ok to reuse the feedstock that was created from this PR? Or should we make a new one and archive the old one?

**Comment by ocefpaf** [comment]
> ok I see. Is it ok to reuse the feedstock that was created from this PR?

Yep. That is preferable. No need to create a new one.

**Comment by alexmojaki** [comment]
Why do both of these work already?

- https://anaconda.org/conda-forge/eval-type-backport
- https://anaconda.org/conda-forge/eval_type_backport

**Comment by tasansal** [comment]
> Why do both of these work already?
> 
> * https://anaconda.org/conda-forge/eval-type-backport
> * https://anaconda.org/conda-forge/eval_type_backport

I have modified the package name in https://github.com/conda-forge/eval_type_backport-feedstock to make it work with hyphens. We now just need to modify the recipe `meta.yaml` there per @ocefpaf's suggestion to make sure it updates both. Right now it will only update the one with hyphens.

**Pull request merged**
