### PR TITLE
Add r-pak and dependencies

### PR DESCRIPTION
**Pull request by xhochy**
Built packages using `conda_r_skeleton_helper`.

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by dbast** [comment]
+1

**Comment by dbast** [comment]
This will require re-triggering builds after feedstock creation, as r-pak will only build some time after the dependencies are available. Will monitor this.

@xhochy wondering what is the usecase ofd r-pak. are going to use r-pack in combination with conda envs? ... that sounds tricky

**Comment by xhochy** [comment]
> This will require re-triggering builds after feedstock creation, as r-pak will only build some time after the dependencies are available. Will monitor this.
> 
> @xhochy wondering what is the usecase ofd r-pak. are going to use r-pack in combination with conda envs? ... that sounds tricky

Yes but only for packages that are not yet on CRAN or conda-forge. It works but I definitely won't recommend it to anyone.

**Comment by dbast** [comment]
Package them all with conda :) we are ready to review your recipes or just upload to a private channel :)

... compared to install.packages()/remotes::install_*()/drat conda is quite a relieve.

**Pull request merged**
