### PR TITLE
add geovista-slam

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] ~If static libraries are linked in, the license of the static library is packaged.~
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bjlittle** [comment]
I confirm that the army of me is willing to maintain this package :smile:

**Comment by bjlittle** [comment]
@conda-forge/help-python, ready for review!

**Comment by ocefpaf** [comment]
> BTW are you going to scipy 2023 this year?

Sadly no. I'm still out of the conference scenario for a while.
(I dropped the ball with my passport and visa during the pandemic and now I'm too lazy to face the endless lines and fees to renew it.)

**Comment by bjlittle** [comment]
@ocefpaf Awh mate. Sorry you won't be there. Totally understandable though.

However, I'm sure there'll be other opportunities.

Thanks for the merge btw. Next time we cross paths, the beers are totally on me for sure :beers:

**Pull request merged**
