### PR TITLE
Added PyDy.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
@conda-forge/core This is ready to be merged.

**Comment by scopatz** [comment]
Thanks @moorepants!

**Comment by moorepants** [comment]
I just realized that I already created a feedstock for pydy 6 months ago.

https://github.com/conda-forge/staged-recipes/pull/1033
https://github.com/conda-forge/pydy-feedstock

Does merging this cause any issues?

**Comment by scopatz** [comment]
Oof yeah, it might mess things up. I am not sure how though. It looks like staged recipes was cleared out and no longer has pydy in it. So we actually might be in the clear. A new feedstock likely won't be created, though.

**Comment by moorepants** [comment]
I haven't noticed any issues yet. It did add a new commit to the feedstock. Maybe it's ok.

**Pull request merged**
