### PR TITLE
pyOCCT conda-forge recipe

### PR DESCRIPTION
**Pull request by trelau**

### CODE REVIEW

**Comment by trelau** [comment]
@looooo any tips for this error? looks familiar to what you had...

https://travis-ci.org/conda-forge/staged-recipes/builds/382932177#L403

**Comment by trelau** [comment]
@looooo thanks. how do we build on Circle-CI only? it seems you're still using Travis-CI for SMESH? It wasn't obvious to me how OCCT was done using Circle-CI only.

**Comment by looooo** [comment]
@trelau I don't know if this is possible for staged recipes. maybe @isuruf knows if it is possible to build a staged recipe with circle-ci for osx.

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by jf---** [comment]
> building on circle-ci or adding these line on top of the build.sh should work:

@looooo  this was very helpful thx ( when building from `ci/conda`  /  `pyOCCT` ) 

___

Onto the next little hurdle: when building on `osx` `TBB` is linked, but not a dependency in `meta.yaml`. 

In file included from ../src/BVH.cpp:44:
In file included from /Users/jelleferinga/miniconda3/conda-bld/pyocct_1536760976964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include/opencascade/BVH_DistanceField.hxx:146:
/Users/jelleferinga/miniconda3/conda-bld/pyocct_1536760976964/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include/opencascade/BVH_DistanceField.lxx:27:12: fatal error: 'tbb/tbb.h' file not found
  #include <tbb/tbb.h>
           ^~~~~~~~~~~

**Comment by looooo** [comment]
@jf--- it should be a run-dependency of occt:
https://github.com/conda-forge/occt-feedstock/blob/master/recipe/meta.yaml#L33

at least for occt7.3

**Comment by jf---** [comment]
thx @looooo , so `meta.yaml` of `pyOCCT` suggest `OCCT` 7.2.
The thing though was that I commented out `DPTHREAD_INCLUDE_DIRS` or `DENABLE_SMESH` in `build.sh`

**Pull request closed without merging**
