### PR TITLE
Add  recipe for OpenSCM Two-layer Model

### PR DESCRIPTION
**Pull request by znicholls**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by znicholls** [comment]
@conda-forge/help-python I believe this is ready to go. For further context, the package is currently undergoing a review in JOSS (https://github.com/openjournals/joss-reviews/issues/2766).

**Review by dopplershift — COMMENTED** [review]
We don't normally package rc versions on the main channel, especially when regular releases are available. Could you change to version 0.2.1 instead?

**Comment by znicholls** [comment]
No worries. v0.2.1 didn't include the LICENSE. I'll wait a couple of days to give https://github.com/openjournals/joss-reviews/issues/2766 a chance to go through then will merge relevant PRs and release v0.2.2, update and ping you. Thanks for your help!

**Comment by dopplershift** [comment]
Sounds great. Thanks @znicholls.

**Comment by znicholls** [comment]
@dopplershift I think this is good to go

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
