### PR TITLE
Add thrift_sasl 0.2.1

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
Ah. Right. Blocked by pure-sasl being stuck in master. I now remember why I hadn't submitted this PR yet. 🤦‍♂️

**Comment by ericdill** [comment]
@mariusvniekerk Do you want to be a maintainer of this?

**Comment by mariusvniekerk** [comment]
Sure

**Comment by ocefpaf** [comment]
LGTM. Should I merge it or are you still working on it @ericdill?

**Comment by ericdill** [comment]
All done @ocefpaf . Thanks for the review.

**Comment by ericdill** [comment]
Just going to self-merge so this can start making its way through the feedstock creation process

**Pull request merged**
