### PR TITLE
Add the xhydro recipe

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@TC-FF @RondeauG @SebastienLanglois

Please let me know in a comment here if you'd like to be (or not be) a maintainer on this package. Thanks!

**Comment by RondeauG** [comment]
I agree to be maintainer.

**Comment by sebastienlanglois** [comment]
I agree to be maintainer.

**Comment by Zeitsperre** [comment]
@RondeauG and @sebastienlanglois

The package could benefit from fixes to its testing suite before being merged. These are all being progressively rolled out. Perhaps we can release a patch with these fixes as the first candidate for conda-forge?

I'll keep this PR open and update it once we have a v0.4.1 release.

**Comment by Zeitsperre** [comment]
Except for a handful of tests on Windows, everything is working fine!

To be explored later, but the issues are coming directly from `RavenHydroFramework` so not related to `xhydro`. For reference:
```
=========================== short test summary info ===========================
FAILED tests/test_calibration.py::TestRavenpyModelCalibration::test_ravenpy_gr4jcn_calibration - OSError: Raven Error (code: 3221225477)
FAILED tests/test_calibration.py::TestRavenpyModelCalibration::test_ravenpy_hmets_calibration - OSError: Raven Error (code: 3221225477)
FAILED tests/test_calibration.py::TestRavenpyModelCalibration::test_ravenpy_mohyse_calibration - OSError: Raven Error (code: 3221225477)
FAILED tests/test_calibration.py::TestRavenpyModelCalibration::test_ravenpy_sacsma_calibration - OSError: Raven Error (code: 3221225477)
FAILED tests/test_ravenpy_models.py::TestRavenpyModels::test_ravenpy_gr4jcn - OSError: Raven Error (code: 3221225477)
FAILED tests/test_ravenpy_models.py::TestRavenpyModels::test_ravenpy_hmets - OSError: Raven Error (code: 3221225477)
FAILED tests/test_ravenpy_models.py::TestRavenpyModels::test_ravenpy_mohyse - OSError: Raven Error (code: 3221225477)
FAILED tests/test_ravenpy_models.py::TestRavenpyModels::test_ravenpy_sacsma - OSError: Raven Error (code: 3221225477)
```

This package doesn't call for architecture-separated builds, so I'm comfortable moving forward with this.

**Comment by Zeitsperre** [comment]
@conda-forge/help-python This is ready for review! Thanks!

**Comment by ocefpaf** [comment]
If I had to guess, those Windows errors are due to Windows aggressive file lock. It may be just a test bug where files are not opened/closed properly.

**Pull request merged**
