### PR TITLE
Recipe for libmbd

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by awvwgk** [comment]
Linux build is failing due to incredible high memory usage, can confirm that the build is failing locally by crashing the host machine.

Therefore, closing this PR.

**Comment by awvwgk** [comment]
@conda-forge/staged-recipes this recipe for an MPI-aware Fortran library (OSX and Linux) is ready for review.

**Comment by jhrmnn** [comment]
After jhrmnn/libmbd#15 was fixed, this could be now hopefully switched back from Ninja to the Make generator

**Comment by awvwgk** [comment]
@jhrmnn Could have been done, probably, but since this is just a change in the build dependency (`-ninja/+make`) it does not seem too important to me. Also, after the fact that `libmbd` is merged now, feel free to open a PR at the [feedstock repo](https://github.com/conda-forge/libmbd-feedstock).

**Pull request merged**
