### PR TITLE
Add python-flint

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
cc @fredrik-johansson

**Comment by fredrik-johansson** [comment]
Thanks! Note: Arb on conda has to be upgraded to 2.15.

**Comment by isuruf** [comment]
Arb was updated in https://github.com/conda-forge/arb-feedstock/commit/5e262af7d4a022c6df6d42c7538b7773b4d5880e

**Comment by isuruf** [comment]
@conda-forge/staged-recipes, ready for review

**Comment by scopatz** [comment]
LGTM! Feel free to merge when CI passes.

**Comment by isuruf** [comment]
Thanks @ocefpaf, @scopatz

**Pull request merged**
