### PR TITLE
adds r-stratifyr

### PR DESCRIPTION
**Pull request by mfansler**
Adds CRAN package `stratifyR` as `r-stratifyr`. Recipe generated with `conda_r_skeleton_helper`.

# Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] ~~If static libraries are linked in, the license of the static library is packaged.~~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by mfansler** [comment]
GitHub doesn’t seem to be registering the CI pipeline: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=432884&view=results

**Comment by mfansler** [comment]
@conda-forge/staged-recipes ready for review 🙏

Note that checks appear not to be syncing correctly, but [all builds (R 4.0/4.1 on osx, linux, win) have passed CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=432884&view=results).

**Comment by dbast** [comment]
Looks like this can be `noarch: generic` even though cran meta data tells `# NeedsCompilation: yes`, there are no compilers in the recipe and the package is 100% pure R code.

**Comment by mfansler** [comment]
@dbast thanks for catching that! I’ve converted to **noarch** and all builds are passing. Should be good to go.

**Pull request merged**
