### PR TITLE
Added ipywidgets, jupyter_client, jupyter_console and nbformat.

### PR DESCRIPTION
**Pull request by pelson**
ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.

Notebooks come alive when interactive widgets are used. Users gain control of their data and can visualize changes in the data.

------

jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels.

----

jupyter_console: A terminal-based console frontend for Jupyter kernels. This code is based on the single-process IPython terminal.

-----

nbformat contains the reference implementation of the Jupyter Notebook format, and Python APIs for working with notebooks.

### CODE REVIEW

**Comment by pelson** [comment]
Seems to be failing on Linux:

```
+ python setup.py install
running install
running build
running build_py
running jsdeps
npm WARN package.json ipython-widget-deps@4.0.0 license should be a valid SPDX license expression

> spawn-sync@1.0.15 postinstall /opt/conda/conda-bld/work/ipywidgets-4.1.1/node_modules/spawn-sync
> node postinstall

npm WARN cannot run in wd ipython-widget-deps@4.0.0 npm run bower && npm run build (wd=/opt/conda/conda-bld/work/ipywidgets-4.1.1)
clean-css@3.4.12 node_modules/clean-css
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── source-map@0.4.4 (amdefine@1.0.0)

spawn-sync@1.0.15 node_modules/spawn-sync
├── os-shim@0.1.3
└── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6)

rimraf@2.5.2 node_modules/rimraf
└── glob@7.0.3 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)

typescript@1.5.3 node_modules/typescript

less@2.6.1 node_modules/less
├── graceful-fs@4.1.3
├── mime@1.3.4
├── image-size@0.4.0
├── source-map@0.5.3
├── errno@0.1.4 (prr@0.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── promise@7.1.1 (asap@2.0.3)
└── request@2.71.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.10, form-data@1.0.0-rc4, bl@1.1.2, aws4@1.3.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)

bower@1.7.9 node_modules/bower

> ipython-widget-deps@4.0.0 build /opt/conda/conda-bld/work/ipywidgets-4.1.1
> npm run css && npm run buildtests


> ipython-widget-deps@4.0.0 precss /opt/conda/conda-bld/work/ipywidgets-4.1.1
> rimraf ./ipywidgets/static/widgets/css/


> ipython-widget-deps@4.0.0 css /opt/conda/conda-bld/work/ipywidgets-4.1.1
> node build_css.js

> lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css
FileError: '/components/bootstrap/less/variables.less' wasn't found. Tried - /components/bootstrap/less/variables.less,/opt/conda/conda-bld/work/ipywidgets-4.1.1/ipywidgets/static/widgets/less/components/bootstrap/less/variables.less,/opt/conda/conda-bld/work/ipywidgets-4.1.1/less_include/components/bootstrap/less/variables.less in /opt/conda/conda-bld/work/ipywidgets-4.1.1/ipywidgets/static/widgets/less/widgets.less on line 2, column 1:
1 // minimal imports from bootstrap - only variables and mixins
2 @import "/components/bootstrap/less/variables.less";
3 @import "/components/bootstrap/less/mixins.less";

`lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css` failed with status=1

npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/opt/conda/envs/_build/bin/node" "/opt/conda/envs/_build/bin/npm" "run" "css"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 css: `node build_css.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipython-widget-deps@4.0.0 css script 'node build_css.js'.
npm ERR! This is most likely a problem with the ipython-widget-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build_css.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipython-widget-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/conda/conda-bld/work/ipywidgets-4.1.1/npm-debug.log

npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/opt/conda/envs/_build/bin/node" "/opt/conda/envs/_build/bin/npm" "run" "build"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 build: `npm run css && npm run buildtests`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipython-widget-deps@4.0.0 build script 'npm run css && npm run buildtests'.
npm ERR! This is most likely a problem with the ipython-widget-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run css && npm run buildtests
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipython-widget-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/conda/conda-bld/work/ipywidgets-4.1.1/npm-debug.log
rebuilding js and css failed
missing files: ['/opt/conda/conda-bld/work/ipywidgets-4.1.1/ipywidgets/static/widgets/css/widgets.min.css', '/opt/conda/conda-bld/work/ipywidgets-4.1.1/ipywidgets/tests/bin']
installing build dependencies with npm
```

And on Windows:

```
rebuilding js and css failed 
missing files: ['C:\\Miniconda\\conda-bld\\work\\ipywidgets-4.1.1\\ipywidgets\\static\\widgets\\css\\widgets.min.css', 'C:\\Miniconda\\conda-bld\\work\\ipywidgets-4.1.1\\ipywidgets\\tests\\bin']
error: [Error 2] The system cannot find the file specified
```

**Comment by pelson** [comment]
@SylvainCorlay - I'd be happy enough to rule out building ipywidgets from source and taking the compiled js (```.tar.gz```) version in pypi if we can't find a solution, but I'm also interested in being able to reproduce that file directly from source. Have you got any ideas for the Linux failure? Is the windows failure an issue with not being able to build the npm deps on Windows?

**Comment by pelson** [comment]
OK, sorry, I was completely missing the fact that I hadn't installed the dev dependencies. I've been able to build on my local docker instance, so should be good there. I've cracked open my old Windows laptop and will take a look at that one.

**Comment by pelson** [comment]
So it all builds nicely on Linux and OSX at this point, but failing to ```npm install --only dev``` on Windows:

```
onda\\envs\\_build\\node_modules\\npm\\bin\\npm-cli.js" "install" "--only" "dev"

npm ERR! node v4.4.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 prepublish: `npm run bower && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipython-widget-deps@4.0.0 prepublish script 'npm run bowe
r && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipython-widget-deps p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipython-widget-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\_miniconda\conda-bld\work\ipywidgets-4.1.1\npm-debug.log

C:\_miniconda\conda-bld\work\ipywidgets-4.1.1>node_modules\.bin\lessc
lessc: no input files

usage: lessc [option option=parameter ...] <source> [destination]

If source is set to `-' (dash or hyphen-minus), input is read from stdin.

options:
  -h, --help               Prints help (this message) and exit.
  --include-path=PATHS     Sets include paths. Separated by `:'. `;' also suppor
ted on windows.
  -M, --depends            Outputs a makefile import dependency list to stdout.
  --no-color               Disables colorized output.
  --no-ie-compat           Disables IE compatibility checks.
  --no-js                  Disables JavaScript in less files
  -l, --lint               Syntax check only (lint).
  -s, --silent             Suppresses output of error messages.
  --strict-imports         Forces evaluation of imports.
  --insecure               Allows imports from insecure https hosts.
  -v, --version            Prints version number and exit.
  --verbose                Be verbose.
  --source-map[=FILENAME]  Outputs a v3 sourcemap to the filename (or output fil
ename.map).
  --source-map-rootpath=X  Adds this path onto the sourcemap filename and less f
ile paths.
  --source-map-basepath=X  Sets sourcemap base path, defaults to current working
 directory.
  --source-map-less-inline Puts the less files into the map instead of referenci
ng them.
  --source-map-map-inline  Puts the map (and any less files) as a base64 data ur
i into the output css file.
  --source-map-url=URL     Sets a custom URL to map file, for sourceMappingURL c
omment
                           in generated CSS file.
  -rp, --rootpath=URL      Sets rootpath for url rewriting in relative imports a
nd urls
                           Works with or without the relative-urls option.
  -ru, --relative-urls     Re-writes relative urls to the base less file.
  -sm=on|off               Turns on or off strict math, where in strict mode, ma
th.
  --strict-math=on|off     Requires brackets. This option may default to on and
then
                           be removed in the future.
  -su=on|off               Allows mixed units, e.g. 1px+1em or 1px*1px which hav
e units
  --strict-units=on|off    that cannot be represented.
  --global-var='VAR=VALUE' Defines a variable that can be referenced by the file
.
  --modify-var='VAR=VALUE' Modifies a variable already declared in the file.
  --url-args='QUERYSTRING' Adds params into url tokens (e.g. 42, cb=42 or 'a=1&b
=2')
  --plugin=PLUGIN=OPTIONS  Loads a plugin. You can also omit the --plugin= if th
e plugin begins
                           less-plugin. E.g. the clean css plugin is called less
-plugin-clean-css
                           once installed (npm install less-plugin-clean-css), u
se either with
                           --plugin=less-plugin-clean-css or just --clean-css
                           specify options afterwards e.g. --plugin=less-plugin-
clean-css="advanced"
                           or --clean-css="advanced"

-------------------------- Deprecated ----------------
  --line-numbers=TYPE      Outputs filename and line numbers.
                           TYPE can be either 'comments', which will output
                           the debug info within comments, 'mediaquery'
                           that will output the information within a fake
                           media query which is compatible with the SASS
                           format, and 'all' which will do both.
  -x, --compress           Compresses output by removing some whitespaces.
                           We recommend you use a dedicated minifer like less-pl
ugin-clean-css

Report bugs to: http://github.com/less/less.js/issues
Home page: <http://lesscss.org/>

C:\_miniconda\conda-bld\work\ipywidgets-4.1.1>lessc
lessc: no input files

usage: lessc [option option=parameter ...] <source> [destination]

If source is set to `-' (dash or hyphen-minus), input is read from stdin.

options:
  -h, --help               Prints help (this message) and exit.
  --include-path=PATHS     Sets include paths. Separated by `:'. `;' also suppor
ted on windows.
  -M, --depends            Outputs a makefile import dependency list to stdout.
  --no-color               Disables colorized output.
  --no-ie-compat           Disables IE compatibility checks.
  --no-js                  Disables JavaScript in less files
  -l, --lint               Syntax check only (lint).
  -s, --silent             Suppresses output of error messages.
  --strict-imports         Forces evaluation of imports.
  --insecure               Allows imports from insecure https hosts.
  -v, --version            Prints version number and exit.
  --verbose                Be verbose.
  --source-map[=FILENAME]  Outputs a v3 sourcemap to the filename (or output fil
ename.map).
  --source-map-rootpath=X  Adds this path onto the sourcemap filename and less f
ile paths.
  --source-map-basepath=X  Sets sourcemap base path, defaults to current working
 directory.
  --source-map-less-inline Puts the less files into the map instead of referenci
ng them.
  --source-map-map-inline  Puts the map (and any less files) as a base64 data ur
i into the output css file.
  --source-map-url=URL     Sets a custom URL to map file, for sourceMappingURL c
omment
                           in generated CSS file.
  -rp, --rootpath=URL      Sets rootpath for url rewriting in relative imports a
nd urls
                           Works with or without the relative-urls option.
  -ru, --relative-urls     Re-writes relative urls to the base less file.
  -sm=on|off               Turns on or off strict math, where in strict mode, ma
th.
  --strict-math=on|off     Requires brackets. This option may default to on and
then
                           be removed in the future.
  -su=on|off               Allows mixed units, e.g. 1px+1em or 1px*1px which hav
e units
  --strict-units=on|off    that cannot be represented.
  --global-var='VAR=VALUE' Defines a variable that can be referenced by the file
.
  --modify-var='VAR=VALUE' Modifies a variable already declared in the file.
  --url-args='QUERYSTRING' Adds params into url tokens (e.g. 42, cb=42 or 'a=1&b
=2')
  --plugin=PLUGIN=OPTIONS  Loads a plugin. You can also omit the --plugin= if th
e plugin begins
                           less-plugin. E.g. the clean css plugin is called less
-plugin-clean-css
                           once installed (npm install less-plugin-clean-css), u
se either with
                           --plugin=less-plugin-clean-css or just --clean-css
                           specify options afterwards e.g. --plugin=less-plugin-
clean-css="advanced"
                           or --clean-css="advanced"

-------------------------- Deprecated ----------------
  --line-numbers=TYPE      Outputs filename and line numbers.
                           TYPE can be either 'comments', which will output
                           the debug info within comments, 'mediaquery'
                           that will output the information within a fake
                           media query which is compatible with the SASS
                           format, and 'all' which will do both.
  -x, --compress           Compresses output by removing some whitespaces.
                           We recommend you use a dedicated minifer like less-pl
ugin-clean-css

Report bugs to: http://github.com/less/less.js/issues
Home page: <http://lesscss.org/>

C:\_miniconda\conda-bld\work\ipywidgets-4.1.1>npm install --only dev

> ipython-widget-deps@4.0.0 prepublish C:\_miniconda\conda-bld\work\ipywidgets-4
.1.1
> npm run bower && npm run build


> ipython-widget-deps@4.0.0 bower C:\_miniconda\conda-bld\work\ipywidgets-4.1.1
> bower install --config.interactive=false


> ipython-widget-deps@4.0.0 build C:\_miniconda\conda-bld\work\ipywidgets-4.1.1
> npm run css && npm run buildtests


> ipython-widget-deps@4.0.0 precss C:\_miniconda\conda-bld\work\ipywidgets-4.1.1

> rimraf ./ipywidgets/static/widgets/css/


> ipython-widget-deps@4.0.0 css C:\_miniconda\conda-bld\work\ipywidgets-4.1.1
> node build_css.js

> lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.l
ess ./ipywidgets/static/widgets/css/widgets.css
C:\_miniconda\conda-bld\work\ipywidgets-4.1.1\build_css.js:16
    process.stdout.write(p.stdout.toString());
                                 ^

TypeError: Cannot read property 'toString' of null
    at run (C:\_miniconda\conda-bld\work\ipywidgets-4.1.1\build_css.js:16:34)
    at Object.<anonymous> (C:\_miniconda\conda-bld\work\ipywidgets-4.1.1\build_c
ss.js:25:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Windows_NT 6.0.6001
npm ERR! argv "C:\\_miniconda\\envs\\_build\\Library\\bin\\node.exe" "C:\\_minic
onda\\envs\\_build\\node_modules\\npm\\bin\\npm-cli.js" "run" "css"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 css: `node build_css.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipython-widget-deps@4.0.0 css script 'node build_css.js'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipython-widget-deps p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build_css.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipython-widget-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\_miniconda\conda-bld\work\ipywidgets-4.1.1\npm-debug.log

npm ERR! Windows_NT 6.0.6001
npm ERR! argv "C:\\_miniconda\\envs\\_build\\Library\\bin\\node.exe" "C:\\_minic
onda\\envs\\_build\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 build: `npm run css && npm run buildtests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipython-widget-deps@4.0.0 build script 'npm run css && np
m run buildtests'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipython-widget-deps p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run css && npm run buildtests
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipython-widget-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\_miniconda\conda-bld\work\ipywidgets-4.1.1\npm-debug.log

npm WARN ipython-widget-deps@4.0.0 license should be a valid SPDX license expres
sion
npm ERR! Windows_NT 6.0.6001
npm ERR! argv "C:\\_miniconda\\envs\\_build\\Library\\bin\\node.exe" "C:\\_minic
onda\\envs\\_build\\node_modules\\npm\\bin\\npm-cli.js" "install" "--only" "dev"

npm ERR! node v4.4.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! ipython-widget-deps@4.0.0 prepublish: `npm run bower && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipython-widget-deps@4.0.0 prepublish script 'npm run bowe
r && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipython-widget-deps p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipython-widget-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipython-widget-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\_miniconda\conda-bld\work\ipywidgets-4.1.1\npm-debug.log

C:\_miniconda\conda-bld\work\ipywidgets-4.1.1>
```

At this point, I'm going to revert to just using the pypi source tarball.

**Comment by jakirkham** [comment]
Aren't you glad that @ocefpaf fixed `_`?

**Pull request merged**
