### PR TITLE
Add pyhull

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
I am not able to get it working for windows, so I excluded windows for now. 

`src\_pyhull.c(32) : fatal error C1083: Cannot open include file: 'libqhull.h': No such file or directory
1813    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2`

**Comment by jan-janssen** [comment]
@isuruf I included the patch - but I had to remove the windows version as somehow windows seems to have issues with finding qhull. So we can either build the windows version with qhull from the vendor version or we exclude windows. At least these are the options I see at the moment.

**Comment by isuruf** [comment]
You need changes from https://github.com/materialsvirtuallab/pyhull/pull/15 for windows

**Comment by jan-janssen** [comment]
@isuruf I am sorry for the delay - I tried to apply the corresponding patch but was not able to get it working.

**Comment by jakirkham** [comment]
Maybe worth giving this another go 😉

**Pull request closed without merging**
