### PR TITLE
Add camelot-py recipe

### PR DESCRIPTION
**Pull request by vinayak-mehta**

### CODE REVIEW

**Comment by vinayak-mehta** [comment]
@conda-forge/staged-recipes Travis fails with `OSError: dlopen(/Users/travis/miniconda/lib/libarchive, 6): image not found`. Why did it raise this error and is there anything I can do to fix this?

**Comment by isuruf** [comment]
cc @conda-forge/staged-recipes

**Comment by vinayak-mehta** [comment]
Thanks for the tag @isuruf!

I have a fix for the Appveyor build, need to downgrade numpy and opencv versions. But I have no idea why Travis failed, would appreciate any pointers! Can push both fixes in a single commit, if Travis requires a fix in the recipe.

**Comment by vinayak-mehta** [comment]
@isuruf Does this need any changes?

**Comment by mariusvniekerk** [comment]
Can you address this?

> Whenever possible python packages should use pip. See https://conda-forge.org/docs/meta.html#use-pip

**Comment by vinayak-mehta** [comment]
@mariusvniekerk I changed it to `python setup.py install` after posting an issue on the conda-build issue tracker (conda build was failing on Windows for me) and getting these comments: https://github.com/conda/conda-build/issues/3200#issuecomment-427802328 and https://github.com/conda/conda-build/issues/3200#issuecomment-427839443.

**Comment by vinayak-mehta** [comment]
Ping @mariusvniekerk.

**Comment by scopatz** [comment]
Thanks @vinayak-mehta!

**Comment by vinayak-mehta** [comment]
Thanks for the merge @scopatz!

**Pull request merged**
