### PR TITLE
add r-g* packages from bioconda

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by jdblischak** [comment]
r-gdtools-0.1.5-r3.3.2_0 failed on macOS. On CRAN it lists cairo as a system requirement, so maybe adding cairo as a dependency would fix it?

**Comment by bgruening** [comment]
@jdblischak cairo is already installed: https://travis-ci.org/conda-forge/staged-recipes/builds/268265833#L1049

The error is:
```
  dlopen(/Users/travis/miniconda/https://travis-ci.org/conda-forge/staged-recipes/builds/268265833#L1049conda-bld/r-gdtools_1503855318643/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/library/gdtools/libs/gdtools.so, 6): Symbol not found: _XML_ErrorString
```

Which makes me wonder why r-gdtools is not installed :(

**Comment by jdblischak** [comment]
> cairo is already installed: https://travis-ci.org/conda-forge/staged-recipes/builds/268265833#L1049

I see, so cairo must be a dependency of one of its dependent packages? I admit I am confused by cairo. I assumed it would be a dependency of r-base, but instead of listing it as a dependency in the recipe, it is specified in a patch ([source](https://github.com/conda-forge/r-base-feedstock/search?utf8=%E2%9C%93&q=cairo&type=)). Also, even though cairo is listed as being installed by conda, it appears to be being installed with homebrew.

> Which makes me wonder why r-gdtools is not installed :(

I can confirm that I receive the exact same error when trying to build the r-gdtools recipe on my laptop running macOS 10.10.5. Prior to failing, there is a popup window that says I need to install the Java Runtime Environment with a [download link](https://www.java.com/en/download/mac_download.jsp). So maybe Java is a dependency? This would be consistent with the [search results of the error message](https://duckduckgo.com/?q=Symbol+not+found%3A+_XML_ErrorString&t=ffsb&atb=v46-5&ia=qa).

But after doing some more searching, I do still think that adding cairo as a dependency is the way to go, but you don't have to make my word for it :-) https://github.com/bioconda/bioconda-recipes/pull/4292/files#diff-1c9b0983e4a17668a716390eacc3c82cR46

**Comment by bgruening** [comment]
@jdblischak I still get this error:
```
fatal error: 'ft2build.h' file not found
#include <ft2build.h>
```
Not sure if I will find time in the next days, feel free to have a look.

**Comment by jdblischak** [comment]
I'm not sure how much help I can be. Here's some more diagnostic information:

The error on all 3 builds is due to the dependency [FreeType](https://en.wikipedia.org/wiki/FreeType) for r-gdtools. There is an open issue on [freetype-feedstock](https://github.com/conda-forge/freetype-feedstock/issues/12) that could explain the failure on Windows. I also checked the gdtools GitHub repo and found this Issue that dealt with [ft2build.h on Windows](https://github.com/davidgohel/gdtools/issues/19).

**Comment by bgruening** [comment]
@ocefpaf this is the last one of our large migration. 300 packages are so are done if you merge it :)
I will probably have some single ones later ... but we will now start to rebuild our stack when this is merged.

**Comment by ocefpaf** [comment]
@bgruening the R-ecosystem is virtually all on the back for 3-4 maintainers. We should create tools to help updating the recipes directly from CRAN and recruit more people if we want them to no get stale.

With that said, it was quite an impressive work! R is finally a first class citizen in conda-forge! Thanks!!

**Comment by bgruening** [comment]
Thanks. I hope that we get a few Bioconda contributors to update these recipes and I will try to work on an update/rerender script for cran. But maybe we should wait for conda-build-3?

**Comment by jdblischak** [comment]
> We should create tools to help updating the recipes directly from CRAN and recruit more people if we want them to no get stale.

@ocefpaf @bgruening I am interested in helping with this. I already have an R script that identifies all conda-forge R packages that are outdated:

https://gist.github.com/jdblischak/a857a109035f43c42846d59729cebcd4

**Comment by ocefpaf** [comment]
@jdblischak cool!

**Comment by bgruening** [comment]
@jdblischak awesome. Can we chat about this at some point?

**Comment by jdblischak** [comment]
> Can we chat about this at some point?

@bgruening  Yes! I was planning on sending you an email about this. Should be arriving in your inbox now.

**Pull request merged**
