### PR TITLE
Add lokern package for R

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Please @conda-forge/staged-recipes review.

**Comment by bgruening** [comment]
@sebastian-luna-valero can you use the following script to generate these r packages.
Are are a few things that needs to be addressed that this script is taking care of: https://github.com/bgruening/conda_r_skeleton_helper

Also you can put all the recipes in one PR if you don't mind.

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening 

Why isn't that script part of the staged-recipes folder and/or explained in the docs?

Also, before splitting up these recipes I did ask what approach was best and the answer I got from the team was to split them up. Please see discussion here https://github.com/conda-forge/staged-recipes/issues/3424. In addition to that, I created a PR to clarify the documentation https://github.com/conda-forge/conda-forge.github.io/pull/424 but the team has not looked into that yet.

**Comment by scopatz** [comment]
> Why isn't that script part of the staged-recipes folder and/or explained in the docs? 

Please feel free to put in a PR!

**Comment by bgruening** [comment]
@sebastian-luna-valero this script is really a hack. And just used for our mass migrations. It is implementing the conda-forge recommendations and has hard-coded maintainers ...

**Comment by sebastian-luna-valero** [comment]
Thanks both. New PR with all these recipes created using @bgruening script here https://github.com/conda-forge/staged-recipes/pull/3872

I am sure others must have proposed the following already but I will try anyway: would it be sensible to consider creating an **automatic** process to convert all R packages published in CRAN into `conda-forge` packages with every new R release? The same question goes for Bioconductor packages.

**Comment by scopatz** [comment]
Should this PR be closed then, in favor of #3782

**Comment by sebastian-luna-valero** [comment]
Thanks @scopatz 

Presumably you mean https://github.com/conda-forge/staged-recipes/pull/3872

Indeed, I think it should be closed in favour of it. The same goes for:
* https://github.com/conda-forge/staged-recipes/pull/3446
* https://github.com/conda-forge/staged-recipes/pull/3447
* https://github.com/conda-forge/staged-recipes/pull/3448
* https://github.com/conda-forge/staged-recipes/pull/3449
* https://github.com/conda-forge/staged-recipes/pull/3450

As I was asked to put them all in the same PR.

**Comment by sebastian-luna-valero** [comment]
Closing in favour of https://github.com/conda-forge/staged-recipes/pull/3872

**Pull request closed without merging**
