### PR TITLE
adding `sourmash_plugin_directsketch` (python/rust)

### PR DESCRIPTION
**Pull request by bluegenes**
[sourmash_plugin_directsketch](https://github.com/sourmash-bio/sourmash_plugin_directsketch/) - download and sketch FASTA/FASTQ files

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ctb** [comment]
happy to join as maintainer!

**Comment by bluegenes** [comment]
```
INFO: pip is looking at multiple versions of sourmash-plugin-directsketch to determine which version is compatible with other requirements. This could take a while.
Will try a different candidate, due to conflict:
    sourmash-plugin-directsketch 0.3.1 depends on Python >=3.10
ERROR: Package 'sourmash-plugin-directsketch' requires a different Python: 3.8.19 not in '>=3.10'
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "$PREFIX/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "$PREFIX/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 439, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=RequiresPythonRequirement('>=3.10'), parent=LinkCandidate('file://$SRC_DIR/target/wheels/sourmash_plugin_directsketch-0.3.1-cp38-cp38-linux_x86_64.whl'))]
```

**Comment by ctb** [comment]
weird - this is clearly looking for a higher minimum version of Python, not sure where something as low as Python 3.8 is coming from anyway, on the conda-forge side. The [sourmash_plugin_branchwater recipe](https://github.com/conda-forge/sourmash_plugin_branchwater-feedstock/blob/main/recipe/meta.yaml) doesn't seem to specify a minimum Python version... 🤔

**Comment by ctb** [comment]
@conda-forge-admin, please rerender

**Comment by ctb** [comment]
@bluegenes you might need to be the person to request the rerender.

**Comment by bluegenes** [comment]
@conda-forge-admin, please rerender

**Comment by ctb** [comment]
> @conda-forge-admin, please rerender

weird, maybe that only works once it's been merged into its own separate feedstock...

**Comment by ctb** [comment]
Maybe try:
```
build:
    skip: true  # [py<310]
```

**Comment by ctb** [comment]
ah! yes, this was in the branchwater feedstock, not sure how I missed it first time through 😆 
```
  skip: true  # [win or py<310]
```

**Comment by bluegenes** [comment]
@conda-forge/help-python ready for review!

Starting with linux-only builds and will work on osx and win later

**Comment by ocefpaf** [comment]
> @conda-forge-admin, please rerender

Rerender works only in the feedstock. In staged-recipes we already have the latest config always.

**Pull request merged**
