### PR TITLE
Add Kokkos

### PR DESCRIPTION
**Pull request by carterbox**
This is a recipe for Kokkos, a C++ parallel processing framework. https://github.com/kokkos/kokkos

Windows is skipped because this package requires MSVC>=14.29, but as far as I can tell conda-forge is still on 14.16

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by BastianZim** [comment]
@carterbox Would you still be interested in this? I’m requiring this as a dep for a different package so would be happy to help (Or take over?) where possible.

**Comment by BastianZim** [comment]
@carterbox Gentle ping if you have some time. :)

**Comment by carterbox** [comment]
I abandoned this project because conda-forge doesn't yet have the infrastructure to make build variants based on instruction sets or like fine-grained hardware architectures. For example, Kokkos require that you target a specific CUDA architecture, you cannot build once for all cuda archs.

**Comment by carterbox** [comment]
We could reopen and merge this PR, but it would definitely be without CUDA support, and definitely without any architecture optimizations. I also found out from upstream developers that you cannot target multiple CPU archs simutaneously (even though I try to do that in this PR).

https://github.com/kokkos/kokkos/issues/4953

**Comment by BastianZim** [comment]
Ok thank you for the summary. Some of your points seems to be included now https://github.com/kokkos/kokkos/issues/4964 but I haven't checked if everything is working. 

As I'd need this as a dependency I'd already be happy about a minimal set of features as I'm otherwise fully blocked. So would you like to open it again or should I create a new PR based on your commits?

**Comment by carterbox** [comment]
@BastianZim, we can just use this same PR. I think all that's left is to figure out the correct optimization/CMAKE args for conda-forge. I would double check that conda-forge still doesn't meet the minimum Windows compiler requirement?

**Comment by carterbox** [comment]
Windows compiler is still 14.16, so no Windows builds allowed.

**Comment by carterbox** [comment]
@BastianZim, just double check that the package version and CMake args are what you want, then I think this recipe is ready for review.

**Comment by BastianZim** [comment]
Thanks @carterbox! CMake args are fine, I would just need 3.6.00 instead of 3.5.00. From a quick glance  haven't seen any significant changes in the changelog (https://github.com/kokkos/kokkos/compare/3.5.00...3.6.00) but would probably be good to first update and then see.

**Comment by BastianZim** [comment]
Hmm, this is looking good. I’d be happy with it. Anything else you want to change?

**Review by BastianZim — APPROVED** [review]

**Comment by carterbox** [comment]
@conda-forge/help-c-cpp, please review

**Comment by BastianZim** [comment]
@ocefpaf This isn't python so a bit bigger to review but if you have a sec it would be great to get a review. Thanks :)

**Comment by BastianZim** [comment]
Thank you! :)

**Pull request merged**
