### PR TITLE
simpletal for python2

### PR DESCRIPTION
**Pull request by stuertz**

### CODE REVIEW

**Comment by stuertz** [comment]
Hi @conda-forge/staged-recipes, please have a look. I think it's ready for merging.

**Comment by pkgw** [comment]
Can you confirm that the `setup.py` invocation should *not* supply the `--single-version-externally-managed --files=files.txt` options?

**Comment by synapticarbors** [comment]
@pkgw - I downloaded the source and it doesn't use `setuptools` in `setup.py` so this is appropriate. 

@stuertz -- do you plan on updating the feedstock to support Python3 via v5?

**Comment by stuertz** [comment]
@pkgw - It doesn't use setuptools, so the extra args are neither necessary, nor working.
@synapticarbors - If you are interested in, I could also add a recipe for that.

**Pull request merged**
