### PR TITLE
Add formulas (and schedula)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
  - > the pypi source doesn't contain enough stuff, due to install-time use of sphinx, etc.
- [x] Package does not vendor other packages
- [x] Build number is 0
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

Adds [formulas](https://github.com/vinci1it2000/formulas) and its primary dependency [schedula](https://github.com/vinci1it2000/schedula).

These both have a large number of optional dependencies... i'm tempted to add `openpyxl` to formulas, but i suppose there is a reason you'd want to do something with excel AST that wasn't coming from an _actual_ excel file...

### CODE REVIEW

**Comment by bollwyvl** [comment]
Windows builds hitting https://github.com/conda-forge/python-graphviz-feedstock/issues/25

**Comment by ankostis** [comment]
@bollwyvl  have 2 improvements on this recipe:

Although  both `formulas` & `schedula` are PY>=3.5 only, you can still apply the `noarch: python` trick described in conda/conda#5971 and exemplified in https://github.com/conda-forge/pyscaffold-feedstock/blob/02b91712d911c593f0b9933fcd27a37aa7b0d9d2/recipe/meta.yaml.

Another point is that `conda-build-4.4.0+` can express version-boundaries for pip's _optional-extras_ with conda-build's undocumented(conda/conda-docs#580) `run_constrained` feature(conda/conda#4982).

Do you want me to provide a PR for these 2 packages?

**Comment by bollwyvl** [comment]
> Do you want me to provide a PR for these 2 packages?

sure, fire away! 

I had had some issues as late as a few months ago with specifying python verions in `noarch: python` packages, good to know that has been cleared up.

It's not so much a `run_constrained` thing, as they aren't exotic, it's more, _I don't know whether to force the optional dependencies_, because I don't know how useful it is without them. But constraining them would be fine.

**Comment by bollwyvl** [comment]
@ankostis ha, wait, they already are `noarch: python`. I don't think the other deps are really worthwhile even bothering with pinning, etc. We could consider adding meta-packages, e.g. `schedula-web` but that shouldn't block review. Which reminds me:

@conda-forge/help-python please take a :eye: :nose: :eye: !

**Comment by chrisburr** [comment]
Ouch that's a lot of host dependencies...

Looks good, LGTM 👍

**Comment by bollwyvl** [comment]
I know, right? Thanks for the merge!

**Pull request merged**
