### PR TITLE
polar-codes: Add recipe for polar-codes

### PR DESCRIPTION
**Pull request by jdemel**
The `polar-codes` project provides low latency high throughput encoders and decoders for polar codes, a recent type of FEC.

Currently, it is tested on Linux x64. Hopefully, it works on MacOS and Windows too.
Besides, the projects requires a CPU AVX2 support. Thus, it may only be built on x86_64.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by jdemel** [comment]
TCLAP and CppUnit are not available on Windows. Thus, this package should not be available on Windows either. For some reason, the MacOS compiler `x86_64-apple-darwin13.4.0-clang++` throws an error:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=643613&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2258
i.e. it does not support `aligned_alloc` (a C11 feature). Thus, this package may not be available on MacOS for now.

Is there a faster way to achieve
```yaml
  skip: True  # [not linux64]
```
than this? The build pipeline is started anyways.

**Comment by jdemel** [comment]
@conda-forge/help-python-c It would be great to get feedback from you.

**Comment by carterbox** [comment]
> Is there a faster way to achieve
> 
> ```yaml
>   skip: True  # [not linux64]
> ```
> 
> than this? The build pipeline is started anyways.

The other builds will be removed when this recipe is issued it's own feedstock.

**Review by carterbox — CHANGES_REQUESTED** [review]
Will every user of your package want to use python? If not, your PR should contain two recipes. One for the CXX library and the other for the Python module. The python package depends on the CXX library.

The python package should be called `pypolar` and the CXX package `libpolarcode`?

**Comment by carterbox** [comment]
Conda also doesn't yet support checking whether the host machine implements a given instruction set, so there is no way to tell if the end-user has an AVX2 compatible processor.

**Pull request closed without merging**
