### PR TITLE
Fix recipe dir name

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @ericdill 

boostrap :ghost:

### CODE REVIEW

**Comment by jakirkham** [comment]
FYI we are pretty low on our GitHub API rate limit. Though it should reset in ~15mins. So, just retry the build in a bit if you get rate limited.

**Comment by ericdill** [comment]
@jakirkham thanks for the heads up. I remember you adding something recently to show how much is left of the rate limit. Is that logged in the CI builds or somewhere else maybe?

**Comment by jakirkham** [comment]
Yep, see an [example]( https://travis-ci.org/conda-forge/staged-recipes/jobs/140791797#L710-L713 ). Though the location is not great and I have realized that having a before and after count helps. So, I added this PR ( https://github.com/conda-forge/staged-recipes/pull/867 ), which should make it easier to find and easier to track usage per run.

**Pull request merged**
