### PR TITLE
Added biorbd-viz-casadi

### PR DESCRIPTION
**Pull request by pariterre**

### CODE REVIEW

**Comment by pariterre** [comment]
@conda-forge-admin, please rerender

**Comment by pariterre** [comment]
@conda-forge/staged-recipes 
Hello! I have added biorbd-viz with backend casadi. So here are the limitations: 
- casadi Windows is not compiled on conda-forge (but it is something I plan to do in the future), so skip win
- It can't be tested on Linux since it uses pyqt which won't work on the CI (We have had the same problem with biorbd with eigen backend). We could not find any solution for that.
- python >3.8 doesn't run when I try to compile casadi on python3.8, someone told me today that it is normal and will be fixed by conda-forge in the future. When it is, I will readjust here
- python <3.7 fails for biorbd-casadi because of a weird thing caused by numby when compiling. 

That explains the limitation in the yaml file 

Thanks!

**Comment by pariterre** [comment]
@conda-forge/staged-recipes 
up :)

**Comment by nehaljwani** [comment]
What does `-casadi` refer to, in the feedstock name?

**Comment by pariterre** [comment]
Hello @nehaljwani,

The CasADi

**Comment by pariterre** [comment]
Hello @nehaljwani

The -casadi refers to the backend used by biorbd. The normal backend would be eigen. Unfortunately, these two backend must bee compiled separately. 

This package is required for BiobrdOptim which is my ultimate goal :)

**Comment by isuruf** [comment]
Can the `casadi` backend and `eigen` backend be installed into the same environment?

**Comment by pariterre** [comment]
@isuruf 
No, they can't, one would override they other one (for example, they are both called on Python using "import biorbd")

**Comment by isuruf** [comment]
Then this should be a variant of the other. Not different conda packages.

**Comment by pariterre** [comment]
Oh!
Didn't know this existed, do you have any example to implement this and, as used, to select the desired variant?

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/maintainer/knowledge_base.html#build-matrices

**Comment by pariterre** [comment]
This PR is no longer required as it is now included in biorbd-viz-feedstock (https://github.com/conda-forge/biorbd-viz-feedstock/pull/12). 
Thanks for your help @isuruf 

We still have to remove the two -casadi repo (rbdl-casadi-feedstock and biorbd-casadi-feedstock) which are no longer required. How should we proceed?

**Pull request closed without merging**
