### PR TITLE
Add new maintainers to the all-members team

### PR DESCRIPTION
**Pull request by jakirkham**
Related https://github.com/conda-forge/staged-recipes/pull/733

This code collects all the maintainers from all the recipes merged and adds them to the `all-members` team at the end. It also prints a welcome message in CI log with their handles.

cc @pelson

### CODE REVIEW

**Comment by jakirkham** [comment]
It seems like this should just work. However, I have no real way to test it at present. If someone knows of a person proposing a PR at staged-recipes, who is not already a conda-forge member, please ping me so we can coordinate getting this in and trying it out.

**Comment by jakirkham** [comment]
Debating just putting this in and letting people ping me if it goes wrong. Thoughts, @ocefpaf?

**Comment by ocefpaf** [comment]
> Debating just putting this in and letting people ping me if it goes wrong. Thoughts, @ocefpaf?

I missed most of the discussion about this so I don't feel qualified to say. However, I am :+1: to ask for forgiveness instead of permission. (Let's just back up if people do complain about it!)

**Comment by jakirkham** [comment]
Basically, we have just been trying to decouple as much as possible from the team update/feedstocks script so that we don't get rate limited here as often. This is one of the last pieces we can do now (and I feel fairly confident on). There are other things we can add, but I don't think they are ready.

**Comment by jakirkham** [comment]
Alright, going to give it a little bit so we can get some test cases warmed up. Probably will take all of this for a spin this evening. That way, if we need to make a few fixes on `master`, it shouldn't have too much of a negative impact.

**Comment by jakirkham** [comment]
Alright, I'm feeling ambitious and have some time. Going to give this a try.

**Comment by jakirkham** [comment]
I have merged in two PRs with recipes that should test this code. Let's see how this goes. Will know soon if it works or not.

**Comment by jakirkham** [comment]
Tested and this appears to be working correctly. Added two members to the `all-members` team. 😄

**Pull request merged**
