### PR TITLE
Add webpack

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@conda-forge/staged-recipes : Could you please review and merge. It is a noarch and has already passed circleci check.

**Comment by dougalsutherland** [comment]
@mwcraig npm handles dependencies differently than python: it bundles all of them for each package. We've decided (in some other PR, not sure where...maybe a page about this should go on the wiki?) that for npm packages, the reasonable thing to do is to bundle all of them in the install. Thus conda-forge recipes for npm modules generally shouldn't declare any conda dependencies other than `nodejs`.

That said: sometimes, as with `node-sass` or `fsevents`, node packages have binaries included that mean that package *can't* be noarch. Since it's not always obvious with node, I suggested a while ago (https://github.com/conda-forge/staged-recipes/pull/4300#issuecomment-340538343) that @sannykr start adding a check for that in the default script. You haven't done that; please do. I think the following would be better:

```
build:
  number: 0
  noarch: generic
  script: npm install -g --production .
  # note the --production; devDependencies shouldn't be needed in conda packages

requirements:
  build:
    - nodejs
# packages that install a command line, e.g. gulp, also need nodejs at runtime
  
test:
  requires:
    - nodejs
  commands:
    - npm list -g {{ name }}
    # Check that no native bindings are installed.
    - [[ -z $(find $PREFIX/lib/node_modules -name binding.gyp) ]]  # [unix]
```

**Comment by mwcraig** [comment]
@dougalsutherland -- thanks for the explanation...I had a feeling there was something fundamental I wasn't understanding and the fact that `npm` installs all dependencies was it.

I've added a wiki page at: https://github.com/conda-forge/staged-recipes/wiki/Recipes-that-bundle-javascript-libraries

**Comment by mwcraig** [comment]
@dougalsutherland -- one other question: what do you recommend in terms of skipping builds on appveyor and/or travis?

**Comment by dougalsutherland** [comment]
@mwcraig Re: skipping builds, I don't know. If it's truly pure-javascript, it should work everywhere and so be fine to skip (and would lighten CI load, esp. on Travis, to do that). But if it's a generic package, would also be nice to know that it actually works elsewhere....

**Comment by mwcraig** [comment]
I restarted Windows to see if that is is just something intermittent (since the same build passed yesterday).

@dougalsutherland -- any insight into the fail on osx (here: https://travis-ci.org/conda-forge/staged-recipes/builds/309624477#L254) or on circleCI?

Those builds had passed before adding `--production` to the build script.

**Comment by dougalsutherland** [comment]
Hmm, some weird npm symlinking thing...this is where it would be useful if I were more than a casual node user. :|  I'll try to investigate a bit but might be pretty busy in the near future.

Note that this recipe **shouldn't** be `noarch`, because of the `fsevents` dependency.

**Comment by scopatz** [comment]
@mwcraig @dougalsutherland - It would be great if that wiki page could go into the docs

**Pull request closed without merging**
