### PR TITLE
Added python.app recipe from anaconda-recipes

### PR DESCRIPTION
**Pull request by Korijn**
As a follow-up to the discussion here: https://github.com/conda-forge/wxpython-feedstock/issues/2

I've decided to just go ahead and submit this package to conda-forge for review. I know there is a lot of discussion around this one, but it would be good if we can postpone that to the feedstock once it exists, so that we can first get to a "working state".

cc @cpbotha @ChrisBarker-NOAA I've added you as maintainers

### CODE REVIEW

**Comment by Korijn** [comment]
@conda-forge/core can we merge this? 

It's blocking https://github.com/conda-forge/wxpython-feedstock/pull/9

**Comment by scopatz** [comment]
@cpbotha @ChrisBarker-NOAA are you OK with being maintainers here?

**Comment by ChrisBarker-NOAA** [comment]
Sure -- feel free to add me.

**Comment by ChrisBarker-NOAA** [comment]
One of these days, we really should build python on the mac with an executable that works for this, rather than this hack (one hack for another...)

The problem is that the only build script that will do that ties it into the "Framework" build, which we don't want. There's no technical reason for that, but those are how it's built by python.org, so that's what's there.

One of these days.....

**Comment by cpbotha** [comment]
I'm happy to join @ChrisBarker-NOAA in maintaining this.

**Comment by ChrisBarker-NOAA** [comment]
And Thanks for getting this in, @Korijn !

**Pull request merged**
