### PR TITLE
Add some ppc64le cdts needed for qt

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

needed for qt:  https://github.com/conda-forge/qt-feedstock/pull/150

### CODE REVIEW

**Comment by scopatz** [comment]
CC @conda-forge/staged-recipes

**Comment by scopatz** [comment]
Is this the same as #11022?

**Comment by jayfurmanek** [comment]
`cups` was the same, so I've removed it. The others are new.

**Comment by hmaarrfk** [comment]
I guess somebody needs to adapt these for Aarch as well

**Comment by jayfurmanek** [comment]
yeah, I didn't do the aarch ones yet. Basicaly, even with all the CDTs, `qt` still wasn't building al the way, so I was spending some time there to see if some more were needed, with the plan of revisiting for aarch64.

**Comment by hmaarrfk** [comment]
well i had done them https://github.com/conda-forge/staged-recipes/pull/11042

so i think we are good if we pull in both PR's.

Looking at that one, i think I just ripped them from yours

**Pull request merged**
