### PR TITLE
New recipe for 'ncdata'

### PR DESCRIPTION
**Pull request by pp-mo**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by pp-mo** [comment]
@conda-forge/help-python now ready to go, I hope !

**Comment by pp-mo** [comment]
Hi @ocefpaf would you have an interest in this ?
So I'm basically trying to build a better "bridge" between Iris + Xarray. https://github.com/SciTools/iris/issues/4994
I have a PyPi presence now, once this is in conda-forge I will tidy a few more things + cut a v0.1.

**Comment by ocefpaf** [comment]
> Hi @ocefpaf would you have an interest in this ?

Sounds useful! I'll play with it to see if I can adopt it at the day job. Thanks for bring it to my attention!

**Comment by pp-mo** [comment]
> > Hi @ocefpaf would you have an interest in this ?
> 
> Sounds useful! I'll play with it to see if I can adopt it at the day job. Thanks for bring it to my attention!

Thanks so much @ocefpaf  !

**Pull request merged**
