### PR TITLE
New: iprogress, text progress bar

### PR DESCRIPTION
**Pull request by chapmanb**
Dependency for cameo metabolic engineering toolkit in bioconda.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml" 
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by chapmanb** [comment]
@conda-forge/help-python Please review and merge this small python dependency PR. Thanks much.

**Comment by chapmanb** [comment]
Thanks so much for the merge, I really appreciate it. Could you also please help with the creation of the feedstock? The skeleton got created:

https://github.com/conda-forge/iprogress-feedstock

But didn't get populated with the recipe so it's also not getting built and available on anaconda.org yet. I've been patiently waiting hoping it would work through whatever happened but it appears like it's not going to finish up on it's own. Thank you again.

**Comment by chapmanb** [comment]
Thanks again, the feedstock got unstuck and is all built. I appreciate all the help.

**Comment by npavlovikj** [comment]
I think @mariusvniekerk clicked the magic buttons :)
From what I was told - travis-ci has an issue and can only generate one feedstock per hour. I hope you don't get an empty feedstock in future, but if you do, please try re-running the travis-ci build.

**Pull request merged**
