### PR TITLE
Add sh

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by scopatz** [comment]
Seems reasonable to me, though the package name is a bit misleading. Should we change it to python-sh to be clear?

**Comment by jakirkham** [comment]
I know what you mean. However two counterpoints.

1. `sh` is the name in `defaults`.
2. The shell `sh` is normally provided with `bash` so it would be `bash` that would be installed.

The first point is the real kicker. We tried prefixing things that came from `defaults` and that broke a lot of stuff. Examples include [`simplegeneric`]( https://github.com/conda-forge/python-simplegeneric-feedstock/issues/1 ) and [`decorator`]( https://github.com/conda-forge/conda-forge.github.io/issues/188 ). This messed with people's ability to install a working copy of the `notebook`. This has basically all been reverted as a consequence. The suggestion to resolve these issues is @mcg1969 's [namespace]( https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1 ) suggestion. That is still not done.

Thankfully we have the second point. `sh` is not the typical thing to package any more. Instead `bash` is packaged and it contains some sort of symlink or shim (I forget which off the top of my head) that redirects to `sh`. As a result, there shouldn't be a need to worry about collision in this case.

**Comment by scopatz** [comment]
Yeah, I grok it.  sh is a spec not a program, so people will always install the implementation of sh that goes by another name.  Your point about consistency with defaults is valid. I think the name has to stay, then.

**Comment by jakirkham** [comment]
Thanks @scopatz .

**Comment by scopatz** [comment]
no problem, thanks

**Pull request merged**
