### PR TITLE
add jupyterlab-markup 1.0.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@agoose77 anything else i mighta missed? Also any interest in co-maintaining?

**Comment by agoose77** [comment]
Thanks @bollwyvl ! I'm happy to co-maintain, though not sure how much use I would be ;) I'll take a look.

**Comment by bollwyvl** [comment]
@agoose77 cool, added you!

@jakirkham sorry i haven't gotten back to you on https://github.com/conda-forge/conda-forge.github.io/issues/1421! some notes from this one:
- removing `pyproject.toml` was required, as it specifies some of the fancy `jupyter-packaging` options that (apparently) override the ability to disable `npm` activity during the build?
- moved the CLI version validation to nasty inline `python` from `grep` so we see at least works _this once_ on windows

**Comment by bollwyvl** [comment]
if the quotes don't work, i'll move it to `run_test.py`, but it's way easier to cargo-cult one file...

**Comment by bollwyvl** [comment]
Haha, "ok" is lower case on windows. Will put back in meta.yaml...

**Comment by bollwyvl** [comment]
@conda-forge/staged-recipes @conda-forge/help-python ready for review!

**Comment by bollwyvl** [comment]
Woo thanks 😊

**Pull request merged**
