### PR TITLE
Add requests-ntlm

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
Depends on https://github.com/conda-forge/staged-recipes/pull/4172

**Comment by synapticarbors** [comment]
@conda-forge/staged-recipes I closed and re-opened this PR to re-trigger the builds after a dependency was available. CircleCI did not re-trigger automatically so I clicked "rebuild" there. It created a new "check", but the old failed one is still there. 

I think this should be good to merge, but someone with more experience should double check.

**Comment by jakirkham** [comment]
Yeah CircleCI 2.0 isn't great with restarting. The restart button shown for the log actually isn't the one that should be pressed. Instead one has to navigate through the workflow link above the log. This will show a different page on which one needs to select Rerun > Rerun from the beginning. Doing this should fix the failed build. Have gone ahead and done that here.

**Comment by jakirkham** [comment]
Thanks @synapticarbors!

**Pull request merged**
