### PR TITLE
Add recipe for pytest-csv

### PR DESCRIPTION
**Pull request by teake**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by teake** [comment]
Note that this is also in defaults (https://anaconda.org/anaconda/pytest-csv) and the recipe is an almost verbatim copy of the recipe of that package. (Strangely it's not present in https://github.com/AnacondaRecipes though).

**Comment by chrisburr** [comment]
> Strangely it's not present in https://github.com/AnacondaRecipes though

It's in `aggregate`, not all Anaconda recipes have their own repository: https://github.com/AnacondaRecipes/aggregate/blob/master/pytest-csv-feedstock/recipe/meta.yaml

**Comment by teake** [comment]
> It's in `aggregate`, not all Anaconda recipes have their own repository: [...]

Ah ok, that makes sense. Thanks for pointing that out! @conda-forge/help-python ready for review.

**Comment by chrisburr** [comment]
Looks good other than the bot's comment:
> noarch: python recipes are recommended to have a lower bound on the python version. This recommendation will become a requirement in the future.

**Comment by teake** [comment]
I had somehow missed that 🤦 . The upstream minimal Python version is 2.7. Does conda-forge still support that? Also, I guess the lower bound should go only into the `run` requirements?

**Comment by mariusvniekerk** [comment]
it may as well go into both

**Comment by beckermr** [comment]
> it may as well go into both

If a package is noarch, it will get built with 3.6 in host. If we have `>=2.7` in run, it will fail on 2.7 machines IIUIC. This problem is part of why we have this lint/hint in the first place. 

I think we need to have them match and both be `>=3.6` or maybe `>=3`.

**Comment by teake** [comment]
> If a package is noarch, it will get built with 3.6 in host. If we have `>=2.7` in run, it will fail on 2.7 machines IIUIC. This problem is part of why we have this lint/hint in the first place.
> 
> I think we need to have them match and both be `>=3.6` or maybe `>=3`.

Went for the latter. Perhaps it's an idea to expand the linter message a bit, and the example meta.yaml? It wasn't quite clear what was expected or why.

**Pull request merged**
