### PR TITLE
add SCS

### PR DESCRIPTION
**Pull request by dougalsutherland**
Split from #6076.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
@dougalsutherland thanks so much for doing this! Making a conda recipe for SCS is harder than it seems at first glance. It must link properly with LAPACK. I've made this work through trial and error, but it will build without LAPACK support so it can be confusing.

**Comment by dougalsutherland** [comment]
@SteveDiamond `openblas` includes a `lapack` (https://github.com/xianyi/OpenBLAS/issues/203#issuecomment-15296123 and https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/build.sh#L16), which I think it is using appropriately: `-DUSE_LAPACK` is in the compile options, and `-lopenblas` in the linker options. Is there anything more to it than that?

**Comment by dougalsutherland** [comment]
Hmm, Windows will need a bit of attention....

**Comment by dougalsutherland** [comment]
@conda-forge/help-c-cpp, this is ready for review. (Will figure out Windows on the feedstock; Circle and Travis passed on the first commit.)

**Comment by SteveDiamond** [comment]
@dougalsutherland I suspect ``openblas`` will be enough. Perhaps this is all obvious to someone more expert, but please actually test it after it's built to see if it linked properly.

**Comment by dougalsutherland** [comment]
The recipe was already running [`test_scs_basic`](https://github.com/bodono/scs-python/blob/master/test/test_scs_basic.py), but I just changed it to run the full test suite; if I understand right, lapack is needed for SDPs and so `test_scs_sdp` should definitely test that it's working properly.

**Comment by dougalsutherland** [comment]
Might as well ping @conda-forge/staged-recipes since apparently @conda-forge/help-c-cpp is tiny....

**Comment by SteveDiamond** [comment]
@dougalsutherland that's right! If it passes ``test_scs_sdp``, it's working.

**Pull request merged**
