### PR TITLE
adding entk conda recipe 

### PR DESCRIPTION
**Pull request by vivek-bala**
@iparask @andre-merzky please verify if you want to be maintainers for this package. 

 @marcelotrevisani Please see this new PR in place of https://github.com/conda-forge/staged-recipes/pull/6648

### CODE REVIEW

**Comment by iparask** [comment]
Yes, I want to be a maintainer

**Comment by andre-merzky** [comment]
Same for me!  Thanks, Andre.

**Comment by iparask** [comment]
We were asked from @marcelotrevisani in #6648 to create a new pull request, since he reverted that one in #6651. Although, as I pointed in #6648 the `feedstock` repo exists and it is empty.

**Comment by jakirkham** [comment]
Thanks all. Have gone ahead and merged. Please keep us apprised of any new developments with the feedstock.

**Comment by jakirkham** [comment]
It looks like the feedstock was populated and builds triggered. So should have packages soon. 😄

FYI the issue that caused the original conversion to fail may trackback to an [older conversion problem]( https://github.com/conda-forge/staged-recipes/issues/6659#issuecomment-421088527 ).

**Comment by vivek-bala** [comment]
Great! Thanks for taking a look at this!

**Pull request merged**
