### PR TITLE
Add Blender Mac and Linux

### PR DESCRIPTION
**Pull request by matter-it-does**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
NOTE Avoids rate limits by using official Github Mirrors.
- [x] Source is from official source.
NOTE Pre compiled libraries are used which are built with patches and will be a pain to build.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by ngam** [comment]
@matter-it-does --- this is pretty amazing and impressive. I've been trying to build openfoam (unrelated package) and I was running into these linking and packaging problems. If you're interested in helping, lmk. Otherwise, I will just look at what you did and learn from it :)

**Comment by matter-it-does** [comment]
@conda-forge-admin please ping team.

**Comment by matter-it-does** [comment]
@conda-forge-admin, please ping team

**Comment by matter-it-does** [comment]
@ngam I can take a look after this is reviewed, and I'm sure that changes like this are accepted.

**Comment by beckermr** [comment]
@conda-forge-admin please ping team

**Comment by ngam** [comment]
@matter-it-does a quick question: why add a relatively large folder (darwin.zip) with random dependencies that conda-forge already has? I see boost, ffmpeg, fftw3, jpeg, llvm, openmp, and even python in that folder... 

Would it not make more sense to use already available pkgs/mods from conda-forge?

**Comment by matter-it-does** [comment]
@ngam they're built with flags [1] and patches [2]. 

[1]
- https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/cmake/python.cmake
[2]
- https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/patches/python_unix.diff
- https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/patches/llvm.diff

**Comment by xhochy** [comment]
These patches don't look like they are relevant. You should be able to use the conda-forge packages here.

**Comment by ngam** [comment]
I understand the point. Not that my opinion should matter much, but I would generally concur with @xhochy about using conda-forge packages. The other thing is, and this is not to distract you from this pretty solid work, is you could try to do these extras more transparently (rather than packaging them in a zip in your github repo). An example (actually from @xhochy incidentally!) is [here]( https://github.com/conda-forge/vowpalwabbit-feedstock/blob/a7132ceece1833245ff541ae730bab8d488928f5/recipe/meta.yaml#L10-L20)

**Comment by matter-it-does** [comment]
> These patches don't look like they are relevant. You should be able to use the conda-forge packages here.

The two were just examples [1]. This is in official build docs and has saved plenty of developer hours spent debugging build errors on so many systems with their own quirks. https://wiki.blender.org/wiki/Building_Blender/Linux/Generic_Distro#Download_Libraries

[1]
https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/patches/
https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/cmake/

>  you could try to do these extras more transparently (rather than packaging them in a zip in your github repo). 

I'd rather not hammer svn.blender.org servers on every build attempt. One can see there were dozens in just these PRs. 

I see three ways out:
- blender deps (llvm usd etc) are built in conda itself. The code to build it is in `build_environment` mentioned above. If we get the host environment right (compiler, OS version etc), it's merely a matter of running `make deps`.
- blender releases precompiled libraries on a new GH mirror. 
- Just do binary repackaging instead of building from source (;

CC @brechtvl  (feel free to unsubscribe from future updates)

**Comment by ngam** [comment]
> I'd rather not hammer svn.blender.org servers on every build attempt

[genuine question] is this really a serious issue? how do their contributors interact with the servers?

**Comment by matter-it-does** [comment]
> > I'd rather not hammer svn.blender.org servers on every build attempt
> 
> [genuine question] is this really a serious issue? how do their contributors interact with the servers?

They don't checkout the libraries 51 times in 4 days (; . So it's alright. Plus they're far slower than GH.

**Comment by ngam** [comment]
> I see three ways out

Eh, you can also just edit stuff later once you get this working in a feedstock.

**Comment by xhochy** [comment]
> If you're not intending to link against system packages as Linux package managers do,

One of the core things of conda-forge is to actually link to system packages (system packages = conda-forge packages).

**Comment by isuruf** [comment]
@matter-it-does, almost all the dependencies are in conda as pre-built conda packages. I'd rather you use those prebuilt conda packages and build blender from source.

>  If you're not intending to link against system packages as Linux package managers do

That's exactly what we want. We want to link against conda packages.

**Comment by ngam** [comment]
thanks @brechtvl for the comment and explanation! 

To be clear, @matter-it-does, I believe conda-forge already has many of these deps pkgs (obviously, without the specific patches). I believe there is some policy about repackaging the binaries --- @xhochy can say more.

**Comment by ngam** [comment]
Yep, exactly like the veterans said. Since I personally have been keeping a close look at this as I am interested in adding openfoam to conda-forge, I like what you've done so far and I am looking to see how you can slowly tease these deps and simplify this build :) 

Then maybe you can help me with my openfoam build 😵‍💫

**Comment by matter-it-does** [comment]
Thanks everyone. Will revisit this.

**Comment by ngam** [comment]
> Downloading the full precompiled libraries often would indeed not be great for the Blender servers. Better would be to keep them around and svn update instead. I don't know anything about the conda-forge build system, but that's what the Blender Buildbot does and I've also seen people set this up with GitHub CI.

@brechtvl just to make sure: Why not have a public read-only mirror (or just the zips) on github to simplify this then if this is a potential issue for the servers?

**Comment by brechtvl** [comment]
I should also mention that the Blender build system on macOS and Windows only supports precompiled libraries currently. There is no mechanism for linking against system packages, that's only for Linux.

**Comment by ngam** [comment]
@matter-it-does are you going to push this further notwithstanding the issues with repackaging vs building from source?

**Comment by matter-it-does** [comment]
- Some dependencies are not present in conda so  would rather do that first than using a mixture of conda and  precompiled libs.
- I know little of linux and way lesser of Windows, so beyond the lucky edits I have done so far using wiki instructions, I don't think I'd be able to maintain or debug, hell even troubleshoot build issues if I were to use conda packages. As brecht said, windows and mac would need plenty of patching for error handling of missing packages, version specification, etc. Not having a local machine to test such code on is a big hurdle.
- GPU support needs installing stuff on the builder machine and I don't know anything about that either. 
- Judging  from brew cask installation numbers of blender, I don't expect .app  to be that in-demand. There's little possibility that I might work on getting bpy.so in. Although it has almost the same issues but since it's not distributed officially, I expect it to be useful for scripting.

**Comment by ngam** [comment]
@matter-it-does but it seems this is almost ready, and so I would just try to get it approved (without any further work) and then the community can work together to fix the deps, add other stuff, etc.

See this for example: https://github.com/conda-forge/firefox-feedstock

I am sorry to see this slip 😢 especially that it is really impressive and decent work, and you should give yourself credit for what you've done! I highly encourage you to reconsider reopening this PR and seeking approval from the reviewers (I am not one, to be clear) as is. They will likely ask for edits and then you can see how much you can do to satisfy their concerns and move on accordingly. Basically, my view is that you don't have to improve much and the rest of improvement and work can be done later once this is in its separate own feedstock. Just my 2c.

**Pull request closed without merging**
