### PR TITLE
use metadata name instead of directory name when creating feedstocks

### LINKED ISSUE #2311: Last three recipes have failed on merge into master
Seems like we've hit an api limit in:

https://travis-ci.org/conda-forge/staged-recipes/builds/196331121

```
GitHub API Rate Limit Info:

---------------------------

Currently remaining 5000 out of 5000.

Will reset in 0:59:59.349455.

Calculating the recipes which need to be turned into feedstocks.

No local changes to save

Current branch master is up to date.

No stash found.

On branch master

Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

GitHub API Rate Limit Info:

---------------------------

Currently remaining 5000 out of 5000.

Will reset in 0:59:58.597998.
```

### PR DESCRIPTION
**Pull request by minrk**
conda-smithy appears to already do this, but create_feedstocks.py was using the directory name instead, causing a mismatch between what repo was created and what repo was looked for in a later step.

should fix #2311
Fixes https://github.com/conda-forge/staged-recipes/issues/1073

### CODE REVIEW

**Comment by minrk** [comment]
I'm not 100% sure there aren't any other instances of using the folder name inconsistently. It might be simplest to include CI/lint checks that the folder name and recipe name match.

**Comment by jakirkham** [comment]
Please add `[ci skip]` to the commit message.

**Comment by jakirkham** [comment]
LGTM. Should save some time on an irrelevant detail. Thoughts @conda-forge/core @conda-forge/staged-recipes?

**Comment by jakirkham** [comment]
Would also try to fix these lines.

* https://github.com/conda-forge/staged-recipes/blob/e7d8e81dc94f98a5517a592fe762aa2aff0dbeeb/.CI/create_feedstocks.py#L161
* https://github.com/conda-forge/staged-recipes/blob/e7d8e81dc94f98a5517a592fe762aa2aff0dbeeb/.CI/create_feedstocks.py#L165
* https://github.com/conda-forge/staged-recipes/blob/e7d8e81dc94f98a5517a592fe762aa2aff0dbeeb/.CI/create_feedstocks.py#L229

**Comment by minrk** [comment]
Oops, I forgot to push before. It's actually done now.

**Comment by ocefpaf** [comment]
Let's give this a try. Thanks @minrk!

**Pull request merged**
