### PR TITLE
Add globus toolkit

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR adds recipes for (a subset of) the globus toolkit. 

@bbockelm, can you post to indicate you are ok being named as a maintainer of these recipes (for the record)?

Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vend other packages
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your
      recipe (see
      [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos)
      for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by bbockelm** [comment]
Hi!  Definitely willing to be listed as co-maintainer.  Great to see this work start to land!

**Comment by chrisburr** [comment]
I think this already exists? https://github.com/conda-forge/gct-feedstock

I'm happy to accept modifications to `gct` and add others as maintainers.

**Comment by duncanmmacleod** [comment]
> I think this already exists? https://github.com/conda-forge/gct-feedstock

aha, I see it does. I'm not a globus expert, but will ask downstream users whether having a monolithic `gct` package is just as good as having the separate ones proposed here (@bbockelm?).

**Comment by chrisburr** [comment]
I'm also not particularly knowledgeable about globus so external input is very welcome. From a quick glance this PR might actually be a better approach so `gct` could be archived or converted to a metapackage.

**Comment by bbockelm** [comment]
At least in RHEL / Fedora / Ubuntu / Debian, the tradition has been to break things into a one-package-per-module -- despite the fact the toolkit is tagged all at once.

@ellert - I think you've been doing the packaging of this particular software stack the longest.  What are your thoughts on having a single big package versus the more targeted approach in this PR?

**Pull request closed without merging**
