### PR TITLE
Add r-thinkr.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by bgruening** [comment]
Not going to wait for appveyor these days :)

**Comment by ericdill** [comment]
@bgruening this is not in the `recipes/` subdir. Is our tooling smart enough to find this recipe if it's not in the `recipes/` subdir?

**Comment by cbrueffer** [comment]
@ericdill argh, good spotting! I don't think it is smart enough.

**Comment by dougalsutherland** [comment]
Moved into the right place in ee98c1a43. I think that should fix it.

**Pull request merged**
