### PR TITLE
add pytest-profiling and pytest-capturelog

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by patricksnape** [comment]
```
conda.resolve.NoPackagesFound: Package missing in current linux-64 channels: 
  - gprof2dot
```

**Comment by msarahan** [comment]
Thanks.  I'm using these to develop conda-build 2.0, and have installed them with pip.  I'll work on this PR (chase the dependency tree) as I have time.

**Comment by jakirkham** [comment]
Would you be interested in picking these up @nicoddemus ?

**Comment by nicoddemus** [comment]
@jakirkham thanks for the ping.

`pytest-capturelog` is actually considered deprecated in favor of [pytest-catchlog](https://pypi.python.org/pypi/pytest-catchlog) because the latter is being actively maintained. `pytest-catchlog` already has a [feedstock](https://github.com/conda-forge/pytest-catchlog-feedstock) and its interface is compatible with `pytest-capturelog`, so IMHO we shouldn't add `pytest-capturelog` to conda-forge as it will only add to the confusion around the subject. 😅

**Pull request closed without merging**
