### PR TITLE
add landlab

### LINKED ISSUE #6571: Package landlab
Hey @ocefpaf,

Could you please help @jphuong and I with packaging [`landlab`](https://github.com/landlab/landlab) into conda-forge. Seems like it's not here yet. I can pull from [landlab channel](https://anaconda.org/landlab/landlab) but I'm weary of mixing channels due to the recent issues. Thanks.

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #6571

@lsetiawan I could not get this to complied correctly, some `cython` error, I'l investigate it later but here is in the PR in case you want to try to debug it.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf is this something easy to fix?

```
 cythoning landlab/graph/sort/ext/remap_element.pyx to landlab/graph/sort/ext/remap_element.c

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef extern from "math.h":
        double atan2(double y, double x) nogil


    from .spoke_sort import sort_spokes_at_wheel
    from .argsort cimport argsort_int
    ^
    ------------------------------------------------------------

    landlab/graph/sort/ext/remap_element.pyx:13:0: 'landlab/graph/sort/ext/argsort.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef extern from "math.h":
        double atan2(double y, double x) nogil


    from .spoke_sort import sort_spokes_at_wheel
    from .argsort cimport argsort_int
    ^
    ------------------------------------------------------------

    landlab/graph/sort/ext/remap_element.pyx:13:0: 'landlab/graph/sort/ext/argsort/argsort_int.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef _argsort_links(long * links, int n_links, long * nodes, long * ordered):
        cdef int n_nodes = 2 * n_links
        cdef int * index = <int *>malloc(n_nodes * sizeof(int))

        try:
            argsort_int(nodes, n_nodes, index)
           ^
    ------------------------------------------------------------

    landlab/graph/sort/ext/remap_element.pyx:174:8: 'argsort_int' is not a constant, variable or function identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef _argsort_links(long * links, int n_links, long * nodes, long * ordered):
        cdef int n_nodes = 2 * n_links
        cdef int * index = <int *>malloc(n_nodes * sizeof(int))

        try:
            argsort_int(nodes, n_nodes, index)
                       ^
    ------------------------------------------------------------

    landlab/graph/sort/ext/remap_element.pyx:174:20: Cannot convert 'long *' to Python object

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef _argsort_links(long * links, int n_links, long * nodes, long * ordered):
        cdef int n_nodes = 2 * n_links
        cdef int * index = <int *>malloc(n_nodes * sizeof(int))

        try:
            argsort_int(nodes, n_nodes, index)
                                       ^
    ------------------------------------------------------------

    landlab/graph/sort/ext/remap_element.pyx:174:36: Cannot convert 'int *' to Python object
    building 'landlab.graph.sort.ext.remap_element' extension
    creating build/temp.linux-x86_64-3.5/landlab/graph/sort
    creating build/temp.linux-x86_64-3.5/landlab/graph/sort/ext
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -m64 -fPIC -I/home/conda/feedstock_root/build_artifacts/landlab_1535475992059/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -fPIC -I/home/conda/feedstock_root/build_artifacts/landlab_1535475992059/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.5/site-packages/numpy/core/include -I/home/conda/feedstock_root/build_artifacts/landlab_1535475992059/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.5m -c landlab/graph/sort/ext/remap_element.c -o build/temp.linux-x86_64-3.5/landlab/graph/sort/ext/remap_element.o
    landlab/graph/sort/ext/remap_element.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
    error: command 'gcc' failed with exit status 1
error
```

**Comment by mcflugen** [comment]
@ocefpaf, @lsetiawan I have a working recipe for this that's ready to go. I haven't sent a pull request yet as I've been waiting for the go ahead for the rest of the landlab team, of which I am part. I wanted to make sure everybody is on board to moving this to conda-forge. I'm pretty sure they will be but wanted to double-check first.

**Comment by ocefpaf** [comment]
> I have a working recipe for this that's ready to go

Cool.

> I wanted to make sure everybody is on board to moving this to conda-forge

Let me know if you need any help. Note that your recipe may still suffer from the issue above due to compilers, flags, etc.

**Comment by isuruf** [comment]
sdist in pypi doesn't have the pxds. See https://github.com/landlab/landlab/blob/master/MANIFEST.in#L3

**Comment by ocefpaf** [comment]
> sdist in pypi doesn't have the pxds. See landlab/landlab:MANIFEST.in@master#L3

Thanks @isuruf! I should've have noticed that :grimacing:

**Comment by mcflugen** [comment]
@ocefpaf Is it OK if I submit a separate pull request for this recipe? As part of the core development team for this package, I have a more up-to-date recipe and that has the proper metadata.

**Comment by ocefpaf** [comment]
> @ocefpaf Is it OK if I submit a separate pull request for this recipe? 

Sure.

**Comment by mcflugen** [comment]
Thanks. See #6576.

**Comment by ocefpaf** [comment]
Closing in favor of #6576.

**Pull request closed without merging**
