### PR TITLE
Moving pyrfa to the recipes folder

### PR DESCRIPTION
**Pull request by pmgrafe**
Sorry.  I accidentally put pyrfa in the root directory rather than the recipes folder.  This commit is just to move it into the recipes folder.

### CODE REVIEW

**Comment by pmgrafe** [comment]
@chrisburr I had inadvertently put my recipe into the root folder.  This PR moves it to the recipes folder and disables the Linux import test.  This is unfortunate, but the CI VM appears to be quite old (Ubuntu 14.04.5) and the wheels were built with a more recent version of gcc.  This was the error I was getting in Linux:

ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found

**Comment by chrisburr** [comment]
cc #8111 for the sake of linking issues together.

> ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found

This has nothing to do with GCC. The problem is that conda uses the host machine's `glibc` and supports RHEL6/CentOS 6 like systems or newer. `GLIBC_2.14` is only available on RHEL7/CentOS 7 like systems and I suspect the wheels have been built there.

Conda-build (pseudo)cross-compiles with a CentOS 6 like sysroot to make it possible to build backward compatible binaries on newer systems. Am I correct in thinking `pyrfa` is closed source? If so, there isn't much that can be done to fix it.

**Comment by pmgrafe** [comment]
From my understanding, it is closed source.  Would it be preferred to remove the import test or simply remove support for Linux altogether?

**Comment by chrisburr** [comment]
Like this is fine.

**Pull request merged**
