### PR TITLE
R packages from bioconda, subdag 1

### PR DESCRIPTION
**Pull request by daler**
xref https://github.com/bioconda/bioconda-recipes/issues/5582

### CODE REVIEW

**Comment by jdblischak** [comment]
[Appveyor build](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.16405/job/n1eqbqvor9ak2y88#L3013) failed because it was missing r-rttf2pt1. That package was recently merged, so I restarted the build.

**Comment by jdblischak** [comment]
[CircleCI](https://circleci.com/gh/conda-forge/staged-recipes/19219?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and [Travis](https://travis-ci.org/conda-forge/staged-recipes/builds/268763676#L3038) both failed because `compilation failed for package ‘leaps’`

**Comment by bgruening** [comment]
@jdblischak this usually happens when a few packages are used from defaults. I triggered a lot of failed builds in the feedstocks the last days. Let's see if it is better now.

**Comment by bgruening** [comment]
@daler something is wrong here. r-leaps is also part of https://github.com/conda-forge/staged-recipes/pull/3827

**Comment by daler** [comment]
@bgruening thanks, good catch. Not sure what happened there. I will split #3827, and when I do I will remove r-leaps from it so that it only remains here (and this PR will remain unchanged).

**Comment by bgruening** [comment]
restarted again

**Comment by bgruening** [comment]
Wuhu! Nice. ping @ocefpaf

**Pull request merged**
