### PR TITLE
add qtypes

### PR DESCRIPTION
**Pull request by untzag**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by ksunden** [comment]
Yes, willing to be a maintainer

**Comment by ksunden** [comment]
Error seems to be libGL related, on pyqtgraph, we have a `yum_requirements.txt` that specifies:

```
mesa-libGL
libX11-devel
```

**Comment by untzag** [comment]
@conda-forge/help-python could you help me understand why CI is failing? From what I can tell, the problem is that I don't get any qt bindings installed during the test stage [1]

I very well may be misunderstanding `run_constrained`. How can I ensure that qt bindings are installed at test time?

[1] https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=218089&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=975

**Comment by untzag** [comment]
Well, looks like just adding to the tests: require fixed it... silly me :confounded:

**Comment by untzag** [comment]
I still don't understand `run_constrained`---what I'm trying to do is specify that I need either `PyQt` OR `PySide2`, is this the right approach?

**Comment by mariusvniekerk** [comment]
Run constrained is a way of imposing constraints on optional deps. Eg if you install pyside (or install it into an environment containing pyside) it must adhere to those constraints.

**Comment by untzag** [comment]
Thanks @mariusvniekerk that makes sense. I guess I do want run constrained.

Assuming there isn't any way to specify that I need PyQt OR PySide2, this recipe is ready for review.

**Pull request merged**
