### PR TITLE
Adding xrayvision 0.0.6

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by jakirkham** [comment]
Feel free to rebase. `slicerator` should be cleared.

**Comment by ericdill** [comment]
Any idea why travis is complaining about mismatching Qt library versions here?

```
Traceback (most recent call last):
  File "/Users/travis/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import xray_vision
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/xray_vision/__init__.py", line 60, in <module>
    from matplotlib.backends.qt4_compat import QtCore, QtGui
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/qt4_compat.py", line 4, in <module>
    from .qt_compat import *
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: dlopen(/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/PyQt4/QtGui.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/travis/miniconda/envs/_test/lib/libQtGui.4.8.7.dylib
  Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 38.0.0
```

**Comment by grlee77** [comment]
The Qt/libpng error above seems to be caused by the current qt 4.8.7 build 3 from defaults.  I encountered this same thing today on another recipe and had to set `- qt ==4.8.7 2` to get it to run.  Will have to check if this issues has already been reported at anaconda

**Comment by grlee77** [comment]
Actually, the problem is that `libpng >=1.6.22` is needed.  There is no bug in anaconda as long as both the libpng and qt libs from defaults are used.

**Comment by ericdill** [comment]
@grlee77 That is fantastic information. Thanks so much. I'll follow #862 and once that is resolved, kick off this CI again.

**Comment by patricksnape** [comment]
This currently builds on my OSX machine (locally) - though the `sha256` seems wrong?

**Comment by ericdill** [comment]
Well that's a super weird error that I'm getting here:

```
import: 'xray_vision.qt_widgets'
Traceback (most recent call last):
  File "/opt/conda/conda-bld/test-tmp_dir/run_test.py", line 47, in <module>
    import xray_vision.qt_widgets
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/xray_vision/qt_widgets/__init__.py", line 40, in <module>
    from ..messenger.mpl.cross_section_2d import CrossSection2DMessenger
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/xray_vision/messenger/mpl/cross_section_2d.py", line 47, in <module>
    from ...backend.mpl.cross_section_2d import CrossSection2DView
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/xray_vision/backend/mpl/cross_section_2d.py", line 41, in <module>
    from mpl_toolkits.axes_grid1 import make_axes_locatable
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/mpl_toolkits/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
AttributeError: module 'pkg_resources' has no attribute 'declare_namespace'
TESTS FAILED: xray-vision-0.0.6-py35_0
```

I can reproduce this locally on my linux machine by [setting add_pip_as_python_dependency to false] (https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_linux#L10). What I am failing to understand is where pkg_resources is coming from.  `pkg_resources` is definitely ending up in the `_test` environment, some how, but I'm not sure from where:

```
$ ls -la ~/miniconda/envs/_test/lib/python3.5/site-packages/ | grep pkg_resources
drwxrwxr-x  5 eric eric   4096 Aug  9 14:41 pkg_resources
```

Any ideas?

I can "fix" this build by adding setuptools as a test dependency, but that (a) feels wrong and (b) still will result in a broken python package when/if that built package is installed without setuptools.

**Comment by ocefpaf** [comment]
> I can "fix" this build by adding setuptools as a test dependency, but that (a) feels wrong and (b) still will result in a broken python package when/if that built package is installed without setuptools.

You need to add `setuptools` everything `pkg_resources` is used b/c `conda-forge` made `setuptools` an explicit dependency now. I know that is weird, specially now that `pip` and `setuptools` are slowly becoming more and more integrated with Python itself :unamused:

**Comment by ericdill** [comment]
Well *my* package isn't the one that needs setuptools :grinning:  Since matplotlib is the one that is actually failing, should we be adding setuptools to matplotlib's runtime requirements?

**Comment by ericdill** [comment]
(also thanks lots for chiming in @ocefpaf  :grinning: )

**Comment by ocefpaf** [comment]
> Well *my* package isn't the one that needs setuptools :grinning:  Since matplotlib is the one that is actually failing, should we be adding setuptools to matplotlib's runtime requirements?

Yeah... `matplotlib` is "broken." We never noticed b/c we all have `setuptools` locally and I guess we do not import `mpl_toolkits` in the tests.

**Comment by ericdill** [comment]
> Yeah... matplotlib is "broken." We never noticed b/c we all have setuptools locally and I guess we do not import mpl_toolkits in the tests.

I just realized that too.  Adding a mpl_toolkits import in the mpl test suite to expose this broken-ness.  I'll submit a PR with that and a setuptools runtime requirement

**Comment by ocefpaf** [comment]
> I just realized that too. Adding a mpl_toolkits import in the mpl test suite to expose this broken-ness. I'll submit a PR with that and a setuptools runtime requirement

Thanks! I was going to do that, but please go ahead :grimacing:

**Comment by ericdill** [comment]
@ocefpaf conda-forge/matplotlib-feedstock#50

**Comment by ericdill** [comment]
This PR is waiting on a new build of matplotlib that includes `setuptools` in the runtime. This is being done in conda-forge/matplotlib-feedstock#50

**Comment by ericdill** [comment]
@ocefpaf this seems to be working as expected now. Thanks for working through the mpl issue with me.

**Comment by ericdill** [comment]
Thanks!

**Pull request merged**
