### PR TITLE
Readd pytest-xdist [ci skip] [skip ci]

### PR DESCRIPTION
**Pull request by nicoddemus**
[ci skip] [skip ci]

Re-adding recipe to get new token (conda-forge/conda-forge.github.io#426)

### CODE REVIEW

**Comment by nicoddemus** [comment]
ping @ocefpaf as requested 👍

**Comment by nicoddemus** [comment]
Thanks @ocefpaf! Should I do anything from my side to trigger a new build in `pytest-xdist-feedstock`, or an update to that repository is scheduled and I should just wait for it to catch up?

**Comment by ocefpaf** [comment]
No action needed. You can see that the CIs were already triggered.

**Comment by nicoddemus** [comment]
Oops indeed, sorry for the noise.

**Comment by ocefpaf** [comment]
No problem. Ping me if you need to re-add more recipes.
(We are still looking into a better solution, but it may take a while...)

**Comment by nicoddemus** [comment]
Will do, thanks!

**Pull request merged**
