### PR TITLE
Add batch of R packages.

### PR DESCRIPTION
**Pull request by jdblischak**
Adds the following 13 R packages:

r-bmp
r-clue
r-contrast
r-ecp
r-feature
r-geepack
r-mcmc
r-mcmcpack
r-moments
r-polspline
r-readbitmap
r-rms
r-wavethresh

I created the recipes using [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper) and conda-build 3.0.13.

cc @bgruening

### CODE REVIEW

**Comment by jdblischak** [comment]
The build fails on Windows and macOS because [feature](https://cran.r-project.org/package=feature) requires [ks](https://cran.r-project.org/package=ks), which requires [rgl](https://cran.r-project.org/package=rgl). [r-rgl-feedstock](https://github.com/conda-forge/r-rgl-feedstock) is only built for Linux, and has the [note](https://github.com/conda-forge/r-rgl-feedstock/blob/master/recipe/meta.yaml#L19):

> \# libglu and/or X-server not available for windows and osx

That was back in May, but [r-ks-feedstock](https://github.com/conda-forge/r-ks-feedstock) was just added 14 days ago, and it also skips win and osx because of r-rgl.

Has anything changed that would make it worth reinvestigating building r-rgl for win and osx? If not, I'll update the r-feature recipe to also skip them.

**Comment by bgruening** [comment]
@jdblischak looks good to me. `libglu` is unfortunately only available for Linux, so you need to skip dependent packages for the moment. I'm not aware of any updates in this regard during the last month.

**Comment by jdblischak** [comment]
> libglu is unfortunately only available for Linux, so you need to skip dependent packages for the moment.

@bgruening OK. Recipe updated.

> I'm not aware of any updates in this regard during the last month.

Yeah, I figured as much, but I had to ask because I collaborate with macOS users, and this will prevent us from using the same `environment.yaml` file.

**Comment by jdblischak** [comment]
@bgruening Please review

**Comment by jdblischak** [comment]
ping @bgruening

**Comment by jdblischak** [comment]
@bgruening I added the path to the license file for the GPL3 and GPL2 packages. For my future reference (and it case it could useful to others submitting R packages):

```
for f in recipes/r-*/meta.yaml
do
  echo $f
  grep license_family $f
  # Add GPL-3
  sed -i s/"  license_family: GPL3"/"  license_family: GPL3\n  license_file: '{{ environ[\"PREFIX\"] }}\/lib\/R\/share\/licenses\/GPL-3'   # [unix]\n  license_file: '{{ environ[\"PREFIX\"] }}\\\R\\\share\\\licenses\\\GPL-3'   # [win]"/ $f
  # Add GPL-2
  sed -i s/"  license_family: GPL2"/"  license_family: GPL2\n  license_file: '{{ environ[\"PREFIX\"] }}\/lib\/R\/share\/licenses\/GPL-2'   # [unix]\n  license_file: '{{ environ[\"PREFIX\"] }}\\\R\\\share\\\licenses\\\GPL-2'   # [win]"/ $f
done
```

**Comment by jdblischak** [comment]
@ocefpaf This one is ready.

The CircleCI failed build is strange. I think it was caused by a failed build on my fork (I have CircleCI setup to build my fork). When I restart it, it just restarts that other CircleCI build (which has already passed twice now). Please let me know if you have any questions about this.

**Pull request merged**
