### PR TITLE
Package pytools [WIP]

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by jakirkham** [comment]
I believe this already [exists]( https://github.com/conda-forge/pytools-feedstock ), no?

**Comment by inducer** [comment]
Whoops. I'll update that instead then. :)

**Comment by inducer** [comment]
Forgot to say: thanks for helping me spot that.

**Comment by jakirkham** [comment]
No worries. Even yours truly has done this a couple of times.

We talked awhile ago about have a bot check for dups here at staged-recipes. Maybe we need to bring that back up.

**Pull request closed without merging**
