### PR TITLE
adding geohexviz

### PR DESCRIPTION
**Pull request by martinfleis**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by martinfleis** [comment]
Hey @mrempel and @tony-zeidan, I am adding a recipe for your geohexviz to have it installable from conda (xref https://github.com/openjournals/joss-reviews/issues/5073#issuecomment-1416382670 and https://github.com/mrempel/geohexviz/issues/6). I've added you as maintainers and need a comment from you both here to make sure it is fine.

I have copied requirements from your files but it seems that there's a lot of stuff that is not actually necessary (e.g. rtree) so I'd suggest some revision.

**Comment by mrempel** [comment]
@martinfleis I am OK with being added as a maintainer for the package to be installable from conda.

**Comment by tony-zeidan** [comment]
@martinfleis I am OK with being added as a maintainer for the package on conda-forge as well. Thank you.

**Comment by martinfleis** [comment]
@conda-forge/help-python, ready for review!

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
