### PR TITLE
package tango

### PR DESCRIPTION
**Pull request by h-vetinari**
Gonna be necessary for the allennlp-stack, see e.g. [here](https://github.com/allenai/allennlp/pull/5482#issuecomment-983212102)

### CODE REVIEW

**Comment by h-vetinari** [comment]
@dirkgr @epwalsh could you have a look here?
I'm already skipping `TestMetadata` (because checking whether `allenai/tango` is a remote really makes no sense outside of your development setup), but I cannot determine whether the following failure (OSX-only) is relevant:
```
        # Check metadata.
        metadata_path = self.TEST_DIR / "hello_world" / "executor-metadata.json"
        assert metadata_path.is_file()
        metadata_params = Params.from_file(metadata_path)
        metadata = ExecutorMetadata.from_params(metadata_params)
        assert metadata.config == {
            "type": "concat_strings",
            "string1": {"type": "ref", "ref": "hello"},
            "string2": "World!",
            "join_with": ", ",
        }
>       assert metadata.git.commit is not None
E       AttributeError: 'NoneType' object has no attribute 'commit'
```

Seems that `ExecutorMetadata` does not create a member `metadata.git`, but I'm not sure if that's relevant?

**Comment by dirkgr** [comment]
I think it's possible that this test can't run outside of a git directory. I'm taking a look.

**Comment by h-vetinari** [comment]
> I think it's possible that this test can't run outside of a git directory.

I have git running in the test environment, and the test passes on linux, but not on osx for some reasons.

> I'm taking a look.

Thanks!

**Comment by dirkgr** [comment]
Skipping `TestMetadata` makes sense, but it would be nice if we could keep `test_deterministic_experiment`. Is there an environment variable we could look for that's set in conda builds?

**Comment by dirkgr** [comment]
Actually, I can check for the presence of the `.git` directory. If it's there, those members should be filled.

**Comment by dirkgr** [comment]
@h-vetinari, how about https://github.com/allenai/tango/pull/99?

**Comment by h-vetinari** [comment]
> @h-vetinari, how about [allenai/tango#99](https://github.com/allenai/tango/pull/99)?

Fine by me! :)

**Comment by h-vetinari** [comment]
@conda-forge/staged-recipes 
This one should be ready.

**Review by xhochy — COMMENTED** [review]
Should this have a `pip check` somewhere?

**Comment by h-vetinari** [comment]
> Should this have a `pip check` somewhere?

Let me ask differently - given a passing test suite, what useful information does `pip check` still cover? I get that it's used often where the upstream test suite is not run, but would you consider it necessary (or even just best practice) if the test suite is being run already?

(not against adding a `pip check`, just trying to clarify)

**Comment by xhochy** [comment]
"but for packages consuming it." … and have a `pip check` but no tests.

**Pull request merged**
