### PR TITLE
Add geographiclib.

### PR DESCRIPTION
**Pull request by QuLogic**
@cffk: I've listed you as a maintainer; please let me know if you don't want to be. GeographicLib seems straightforward enough for me to maintain myself, otherwise.

### CODE REVIEW

**Comment by QuLogic** [comment]
@cffk: There appears to be a problem with 32-bit Windows on Python 2.7. All the other platforms appear to be alright. Seems to be a very small precision error:

```pytb
======================================================================
FAIL: test_GeodSolve61 (geographiclib.test.test_geodesic.GeodSolveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bld\geographiclib_1489358685603\_t_env\lib\site-packages\geographiclib\test\test_geodesic.py", line 360, in test_GeodSolve61
    self.assertAlmostEqual(dir["lon2"], -180, delta = 0.5e-5)
AssertionError: 180.0 != -180 within 5e-06 delta
```

**Comment by cffk** [comment]
I noticed an error in the python tests yesterday.  Could you try applying the
following patch?  (The next version of GeographicLib makes a bunch of
other changes that will affect the treatment of angles near +/- 180.)

~~~~
--- a/python/geographiclib/test/test_geodesic.py
+++ b/python/geographiclib/test/test_geodesic.py
@@ -360,7 +360,7 @@ class GeodSolveTest(unittest.TestCase):
     self.assertAlmostEqual(dir["lon2"], -180, delta = 0.5e-5)
     self.assertAlmostEqual(dir["azi2"], -180, delta = 0.5e-5)
     line = Geodesic.WGS84.InverseLine(45, 0, 80, -0.000000000000000003)
-    dir = line.Position(1e7)
+    dir = line.Position(1e7, Geodesic.STANDARD | Geodesic.LONG_UNROLL)
     self.assertAlmostEqual(dir["lat2"], 45.30632, delta = 0.5e-5)
     self.assertAlmostEqual(dir["lon2"], -180, delta = 0.5e-5)
     self.assertAlmostEqual(dir["azi2"], -180, delta = 0.5e-5)
~~~~

**Comment by QuLogic** [comment]
Unfortunately, that doesn't appear to have worked. I also don't have this kind of system, so I really can't do much in the way of debugging.

**Comment by cffk** [comment]
OK, I found the problem.  In fact I had already run into the same
problem with the C++ library with old versions of Visual Studio on
(32-bit).  This bug is that
~~~~
  math.fmod(-0.0, 360)
~~~~
gives +0.0 instead of -0.0.  Here's the fix (this also includes the
patch to test_geodesic.py I sent you earlier)

~~~~
diff --git a/python/geographiclib/geomath.py b/python/geographiclib/geomath.py
index 74d2c39..d5a535b 100644
--- a/python/geographiclib/geomath.py
+++ b/python/geographiclib/geomath.py
@@ -129,9 +129,12 @@ class Math(object):
   def AngNormalize(x):
     """reduce angle to [-180,180)"""
 
-    x = math.fmod(x, 360)
-    return (x + 360 if x < -180 else
-            (x if x < 180 else x - 360))
+    y = math.fmod(x, 360)
+    # On Windows 32-bit with python 2.7, math.fmod(-0.0, 360) = +0.0
+    # This fixes this bug.  See also Math::sincosd in the C++ library.
+    y = x if x == 0 else y
+    return (y + 360 if y < -180 else
+            (y if y < 180 else y - 360))
   AngNormalize = staticmethod(AngNormalize)
 
   def LatFix(x):
@@ -162,6 +165,9 @@ class Math(object):
       s, c = 0.0-s, 0.0-c
     elif q == 3:
       s, c = 0.0-c,     s
+    # On Windows 32-bit with python 2.7, math.fmod(-0.0, 360) = +0.0
+    # This fixes this bug.  See also Math::sincosd in the C++ library.
+    s = x if x == 0 else s
     return s, c
   sincosd = staticmethod(sincosd)
 
diff --git a/python/geographiclib/test/test_geodesic.py b/python/geographiclib/test/test_geodesic.py
index 16b4dcf..902a6e0 100644
--- a/python/geographiclib/test/test_geodesic.py
+++ b/python/geographiclib/test/test_geodesic.py
@@ -360,7 +360,7 @@ class GeodSolveTest(unittest.TestCase):
     self.assertAlmostEqual(dir["lon2"], -180, delta = 0.5e-5)
     self.assertAlmostEqual(dir["azi2"], -180, delta = 0.5e-5)
     line = Geodesic.WGS84.InverseLine(45, 0, 80, -0.000000000000000003)
-    dir = line.Position(1e7)
+    dir = line.Position(1e7, Geodesic.STANDARD | Geodesic.LONG_UNROLL)
     self.assertAlmostEqual(dir["lat2"], 45.30632, delta = 0.5e-5)
     self.assertAlmostEqual(dir["lon2"], -180, delta = 0.5e-5)
     self.assertAlmostEqual(dir["azi2"], -180, delta = 0.5e-5)
~~~~

**Comment by QuLogic** [comment]
For some reason, I missed that this had worked. Thanks @cffk!

**Comment by cffk** [comment]
Sure thing...!

**Comment by QuLogic** [comment]
Good to go @conda-forge/core?

**Comment by ocefpaf** [comment]
Thanks @QuLogic!

**Comment by cffk** [comment]
The patch to geomath.py is incorporated into GeographicLib 1.48 which
I released today.

**Pull request merged**
