### PR TITLE
WIP: re-add libatomic_ops

### PR DESCRIPTION
**Pull request by ocefpaf**
Do not merge until we have the new conda-smithy.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @jakirkham!

**Comment by jakirkham** [comment]
Absolutely. :smile:

**Comment by pelson** [comment]
Man, you two are ruthlessly efficient! Amazing @ocefpaf and @jakirkham! :+1:

**Comment by ocefpaf** [comment]
This is from the *dark zen of python*:

    If you don't do it right now it'll never be done!

**Pull request merged**
