### PR TITLE
Rm -prerelease

### PR DESCRIPTION
**Pull request by gidden**
Should fix the issue raised in #5904 

Cc @jakirkham @isuruf @mariusvniekerk

### CODE REVIEW

**Comment by gidden** [comment]
It looks like the litter is failing because it isn't a new recipe?

**Comment by gidden** [comment]
Do I need to bump the build number?

**Comment by gidden** [comment]
Cc @conda-forge/staged-recipes

**Comment by scopatz** [comment]
Thanks @gidden!

**Pull request merged**
