### PR TITLE
Adding finlogic from PyPI

### PR DESCRIPTION
**Pull request by crdcj**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by crdcj** [comment]
Publishing FinLogic/PyPI on Conda-Forge

**Comment by crdcj** [comment]
Hi @conda-forge/staged-recipes, PR is ready.
Just one point. I release today version 0.2.1 and this PR was made with version 0.2.0. Should I make a new PR?

**Comment by beenje** [comment]
> Hi @conda-forge/staged-recipes, PR is ready.
> Just one point. I release today version 0.2.1 and this PR was made with version 0.2.0. Should I make a new PR?

This recipe looks good to me.
Just change the version to 0.2.1 and push to your branch to update this PR.

**Comment by beenje** [comment]
Don't  forget to update the `sha256` after bumping the version

**Comment by crdcj** [comment]
> Don't forget to update the `sha256` after bumping the version

Ops, sorry beenje.

**Comment by crdcj** [comment]
I made the adjustments, Benjamin. I think now it's Ok.

**Comment by crdcj** [comment]
Thanks for your help and review, @beenje.

**Pull request merged**
