### PR TITLE
Remove libmo_unpack

### PR DESCRIPTION
**Pull request by ocefpaf**
Workaround #221

### CODE REVIEW

**Comment by pelson** [comment]
Did this get added back in the end?

**Comment by jakirkham** [comment]
I don't think so, but it really should sit in a new PR so we don't forget about it.

**Comment by ocefpaf** [comment]
> I don't think so, but it really should sit in a new PR so we don't forget
about it.

I'll send it first thing tomorrow.

**Comment by jakirkham** [comment]
Did this happen? I might just not be finding the right one.

**Comment by jakirkham** [comment]
Was added in this PR ( https://github.com/conda-forge/staged-recipes/pull/245 ).

**Pull request merged**
