### PR TITLE
Added recipe for pykerberos

### PR DESCRIPTION
**Pull request by pmlandwehr**
I'm a bit concerned about the quality of this build because info seems to be scanty. Appears to be needed for `pymongo`. (ref. https://github.com/conda-forge/pymongo-feedstock/pull/1)

### CODE REVIEW

**Comment by pmlandwehr** [comment]
`krb5`, though not explitly in the reqs, would seem to be required; the circle CI build can't go forward without it and there are commands in `setup.py` referencing it.

**Comment by ericdill** [comment]
Why did only the windows build expose the krb5 runtime dependency? That seems strange

**Comment by pmlandwehr** [comment]
[The `krb5` feedstock](https://github.com/conda-forge/krb5-feedstock) specifically skips builds for `py36` on windows, which is why that caused the break.

A *different* question that this does raise, I think, is why the Travis CI build succeeded without `krb5`. Is kerberos support native to Mac OS?

**Comment by ericdill** [comment]
If I'm reading the CI services correctly;

1. mac always works
2. linux works with krb5 as a build dep but not a run dep
3. windows only works with krb5 as a build dep and a run dep, but not for py36

That's super weird... :man_shrugging:

**Comment by isuruf** [comment]
For python 2.7, you need `msinttypes` package. (Maybe this should be declared a run dependency of `krb5`)

> The krb5 feedstock specifically skips builds for py36 on windows

For python3.6 on `krb5`, there's no need for a separate build since python 3.5 and 3.6 both use vc14 and it is not a python package.

Your issue seems to be a missing `gssapi/gssapi_generic.h`  on `krb5` for windows. I've no idea why that header is not getting installed in windows in `krb5` build.

>  Is kerberos support native to Mac OS?

Yes, kerberos is shipped with Mac OS.

**Comment by jakirkham** [comment]
> Your issue seems to be a missing `gssapi/gssapi_generic.h`  on `krb5` for windows. I've no idea why that header is not getting installed in windows in `krb5` build.

Did an issue get raised with the `krb5` feedstock?

**Pull request closed without merging**
