### PR TITLE
Add Prefect azure

### PR DESCRIPTION
**Pull request by pascal-holy**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by dbast** [comment]
pinging members of @conda-forge/prefect who maybe want to co-maintain this.

**Comment by madkinsz** [comment]
Hey @dbast — thanks for all your work here!

These are managed by our integrations team whereas the @conda-forge/prefect team manages our core library. Is there a good way for us to have a team designated for our integrations team? Maybe we should create a team internally? Otherwise we could add them to @conda-forge/prefect and use that as the maintainer for all these?

**Comment by dbast** [comment]
@madkinsz yes, you can add conda-forge/prefect as maintainer to all prefect-* feedstocks .. maintainers can be individuals or groups... another possibility would be creating a new meta-package like *prefect-integrations* that depends on all prefect-* integration packages and serves as maintainer group added to all integration packages...

**Comment by desertaxle** [comment]
Thanks for the suggestion @dbast!

We'd be interested in setting up a meta-package for managing prefect integration packages. Do you have any instructions on how to do that? Also, we have an existing GitHub group for our integrations maintainers. Would we be able to use that group as the maintainer group for conda-forge packages?

**Comment by dbast** [comment]
@desertaxle meta packages are also created via contributing a recipe with meta.yaml to staged_recipes. meta packages are packages with no source section (there is nothing to build) and just having run-dependencies... there are many meta packages... examples are https://github.com/conda-forge/r-feedstock/blob/main/recipe/meta.yaml or https://github.com/conda-forge/fonts-conda-forge-feedstock/blob/main/recipe/meta.yaml

(the build dependencies in those meta packages are some leftovers when conda-build failed due to empty build section)

**Comment by pascal-holy** [comment]
Thanks @dbast then I'm going to leave the task of creating a meta-package to you @desertaxle

**Pull request closed without merging**
