### PR TITLE
added v 3.4.1.0 of XStatic-jQuery

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by ReimarBauer** [comment]
Hi
@conda-forge/help-python
@conda-forge/staged-recipes

I have no idea how to solve the OpenJS license request not matching a SPDX identifier.

Is this mandatory? 

cheers
Reimar

**Comment by chrisburr** [comment]
Please check the text, but I think that's `MIT`?

**Comment by ReimarBauer** [comment]
looking here it is MIT https://jquery.org/license/ 

The raw file has this OpenJS statement
https://github.com/jquery/jquery/blob/master/LICENSE.txt


but the major part on top is also MIT, I change the string to that.

**Comment by ReimarBauer** [comment]
for a moment I forgot that MIT is a shortcut for an Institute and of course some other party wants to have its name there ;)

**Comment by chrisburr** [comment]
Yeah the first line is the copyright notice: https://opensource.org/licenses/MIT

Thanks for the contribution, LGTM! :)

**Pull request merged**
