### PR TITLE
rename openkimmodels to openkim-models

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist

- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by jan-janssen** [comment]
On all other package managers the openkim models are distributed as `openkim-models` rather than `openkimmodels`. Therefore we decided to rename the package https://github.com/conda-forge/openkimmodels-feedstock/issues/5

**Comment by jan-janssen** [comment]
@ellio167 Can you quickly comment on this Pullrequest that you agree to join me in maintaining it.

**Comment by ellio167** [comment]
@jan-janssen Indeed, I'll be happy to help maintain this.  Thanks for your efforts.

**Comment by jan-janssen** [comment]
@conda-forge/staged-recipes, ready for review

**Comment by beckermr** [comment]
This appears to be a copy-paste, so LGTM! 

@conda-forge/core will need to take care of the old feedstock.

**Pull request merged**
