### PR TITLE
Added recipe for xmltodict

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
I'm not sure why travis-ci is failing now. All four checks passed when I submitted the first commit in this branch. They I realized that the `versioneer` recipe was present in my branch, but was removed in `master`, so I merged the `upstream` and now I'm getting this failure.

Suggestions welcome.

**Comment by synapticarbors** [comment]
I closed the PR and then re-opened it, forcing the checks to re-run and they all now pass. Not sure what the issue was previously.

**Comment by patricksnape** [comment]
Looks good!

**Comment by jakirkham** [comment]
You should get an email that invite you to join conda-forge, @synapticarbors. Once accepted you will be added to a team with the same name as this recipe. Those will give you permissions on the feedstock (repo) for this recipe.

Make sure when proposing any change that you go through the typical GitHub workflow of forking the feedstock and making changes in your fork that you PR back. Once merged CIs will build and deploy any changes you make. Please let us know if you have any questions and welcome to conda-forge.

**Comment by synapticarbors** [comment]
@jakirkham Thanks. I actually got the email when the unidecode feedstock was accepted a few days back. I have another recipe in the `staged-recipe` repo that is ready to go when you or any of the other core members have a chance:

- #1295 (flask-httpauth)

I also have a recipe that passes all of the build tests, but the conda-forge linter is failing:

- #1307 (mechanize)

**Comment by jakirkham** [comment]
I think we have handled those now. Thanks for bringing them to our attention.

**Pull request merged**
