### PR TITLE
Adding `polars` to conda-forge

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source. `PyPI`
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged. 
	> This library (`polars`) requires a working installation of `rust`. So, `rust` was added to host requirements. But, should the user decide to additionally install rust system-wide or the conda-environment (`conda install rust -c conda-forge`), it is left as an additional package for the user to install.
	> 
	> _I am unclear/unsure of if `rust` must be added to the run-requirements as well_.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

### CODE REVIEW

**Comment by sugatoray** [comment]
@conda-forge-admin, please ping team

> I need some help in using `rust` for adding the `polars` library. The `polars` library requires a working `rust` installation to work properly. 

- I have tried until now using `{{ compiler("rust") }}` as follows:
  
  ```yml
  requirements:
    build:
      - python
      - {{ compiler("rust") }}
    host:
      - pip
      - python
      - maturin
    run:
      - numpy
      - python

  test:
    imports:
      - polars
    commands:
      - pip check
    requires:
      - pip
  ```

   But I keep getting build-failure errors like this: [run #20211102.7](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=401180&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823)

Any help in fixing this will be great. Thank you.

> :bulb: Here is another library [`huggingface/tokenizers`](https://github.com/conda-forge/tokenizers-feedstock/blob/master/recipe/meta.yaml) that also uses `rust`.

**Comment by jakirkham** [comment]
cc @conda-forge/rust (in case you have thoughts :)

**Comment by sugatoray** [comment]
Here is how `polars` is supposed to get compiled.

image

**Comment by sugatoray** [comment]
:eyes: It seems there is an experimental feature: `SIMD`, which, if turned off, this build could succeed. I have asked the authors of `polars` to help on this aspect in this [issue](https://github.com/pola-rs/polars/issues/383#issuecomment-957187996).

**Comment by nsandau** [comment]
Hi. 

I was able to build an earlier version of polars locally on both windows and linux using the following recipe: 
https://gist.github.com/nsandau/1203efaf9796f2943d307d9e5c29d164

I had to use the dev version of rust to get it to compile back then, so I had to add the following channel: conda-forge/label/rust_dev

However, I don't know if it still builds with newer versions of polars.

**Comment by ralexx** [comment]
I was unable to build polars 0.13.3 on macOS 12.2 using @nsandau 's recipe.

1) When passing the `conda-forge/label/rust_dev` channel to conda-build.

This seems to be because the channel's latest version of rust is not current (1.56.0.dev20210816...). The rust compiler helpfully suggested adding a parameter `cargo-features = ["edition2021"]` to `Cargo.toml`, which I did to `/py-polars/Cargo.toml` using a Github fork as the source in meta.yaml. Many file not found errors ensued, referencing non-Python dependencies located in the root folder of the project source. I tried building locally from downloaded and modified source, after cd'ing to the `py-polars` subdirectory and setting `src: ..` in meta.yaml, but more file not found errors.

2) Using rust packages from the conda-forge channel (e.g. conda-forge/osx-64::rust-1.58.1-h7e1429e_0, conda-forge/noarch::rust-std-x86_64-apple-darwin-1.58.1-h059895a_0) throws another error related to a `feature` statement.

3) Changing @nsandau's `build.sh` from `maturin build...` to `maturin develop...` (per the [compilation instructions](https://github.com/pola-rs/polars#python-compile-polars-from-source) in the project's README) did not trigger any of the previous errors. Instead, maturin complained about `No matching distribution found for numpy>=1.16.0`.


<details>
 <summary>Log snippet from error 1</summary>
 
```sh
+ maturin build '--rustc-extra-args=-C codegen-units=16 -C lto=thin -C target-cpu=native' --release
🍹 Building a mixed python/rust project
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error: error: failed to parse manifest at `/Users/ralexx/anaconda/conda-bld/polars_1645049236428/work/Cargo.toml`

Caused by:
  feature `edition2021` is required

  The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.56.0-nightly (b51439fd8 2021-08-09)).
  Consider adding `cargo-features = ["edition2021"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.
Traceback (most recent call last):
  File "/Users/ralexx/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 480, in main
    execute(sys.argv[1:])
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 469, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-o', 'errexit', '/Users/ralexx/anaconda/conda-bld/polars_1645049236428/work/conda_build.sh']' returned non-zero exit status 1.
```

</details>

<details>
 <summary>Log snippet from error 2</summary>
 
```sh
+ maturin build '--rustc-extra-args=-C codegen-units=16 -C lto=thin -C target-cpu=native' --release
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.6
🐍 Not using a specific python interpreter (With abi3, an interpreter is only required on windows)
📦 Built source distribution to /Users/ralexx/anaconda/conda-bld/polars_1645049833205/work/target/wheels/polars-0.13.3.tar.gz
   Compiling libc v0.2.118
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling cfg-if v1.0.0
   Compiling libm v0.2.2
   Compiling memchr v2.4.1
   Compiling scopeguard v1.1.0
   Compiling futures-core v0.3.21
   Compiling serde_derive v1.0.136
   Compiling lazy_static v1.4.0
   Compiling serde v1.0.136              ] 0/279: scopeguard, autocfg, future...
   Compiling crossbeam-utils v0.8.7      ] 1/279: scopeguard, autocfg, future...
   Compiling futures-channel v0.3.21     ] 2/279: autocfg, futures-core(build...
   Compiling futures-task v0.3.21        ] 3/279: autocfg, futures-core(build...
   Compiling futures-sink v0.3.21        ] 4/279: autocfg, futures-core(build...
   Compiling futures-util v0.3.21        ] 5/279: futures-core(build.rs), cro...
   Compiling static_assertions v1.1.0
   Compiling crossbeam-epoch v0.9.7
   Compiling pin-project-lite v0.2.8     ] 8/279: crossbeam-epoch(build.rs), ...
   Compiling slab v0.4.5
   Compiling pin-utils v0.1.0           ] 10/279: crossbeam-epoch(build.rs), ...
   Compiling futures-io v0.3.21
   Compiling parking_lot_core v0.8.5
   Compiling async-trait v0.1.52        ] 13/279: crossbeam-epoch(build.rs), ...
   Compiling smallvec v1.8.0            ] 14/279: crossbeam-epoch(build.rs), ...
   Compiling log v0.4.14
   Compiling crc32fast v1.3.2           ] 16/279: crossbeam-epoch(build.rs), ...
   Compiling pkg-config v0.3.24         ] 17/279: crossbeam-epoch(build.rs), ...
   Compiling rayon-core v1.9.1          ] 18/279: crossbeam-epoch(build.rs), ...
   Compiling serde_json v1.0.79         ] 19/279: crossbeam-epoch(build.rs), ...
   Compiling ryu v1.0.9                 ] 20/279: crossbeam-epoch(build.rs), ...
   Compiling hashbrown v0.11.2          ] 21/279: crossbeam-epoch(build.rs), ...
   Compiling crunchy v0.2.2             ] 22/279: crossbeam-epoch(build.rs), ...
   Compiling zstd-safe v4.1.4+zstd.1.5.2
   Compiling alloc-no-stdlib v2.0.3     ] 24/279: crossbeam-epoch(build.rs), ...
   Compiling snap v1.0.5                ] 25/279: alloc-no-stdlib, futures-io...
   Compiling libm v0.1.4                ] 26/279: alloc-no-stdlib, snap(build...
   Compiling itoa v1.0.1                ] 27/279: alloc-no-stdlib, libm(build...
   Compiling signal-hook v0.3.13        ] 28/279: alloc-no-stdlib, libm(build...
   Compiling adler v1.0.2               ] 29/279: signal-hook(build.rs), libm...
   Compiling either v1.6.1
   Compiling build_const v0.2.2         ] 31/279: signal-hook(build.rs), libm...
   Compiling version_check v0.9.4       ] 32/279: signal-hook(build.rs), libm...
   Compiling fallible-streaming-iterator v0.1.99: signal-hook(build.rs), libm...
   Compiling regex-automata v0.1.10     ] 34/279: signal-hook(build.rs), libm...
   Compiling byteorder v1.4.3           ] 35/279: libm(build.rs), snap(build....
   Compiling rle-decode-fast v1.0.3     ] 36/279: snap(build.rs), fallible-st...
   Compiling packed_simd_2 v0.3.7       ] 37/279: snap(build.rs), fallible-st...
   Compiling array-init-cursor v0.2.0   ] 38/279: snap(build.rs), fallible-st...
   Compiling ppv-lite86 v0.2.16         ] 39/279: snap(build.rs), fallible-st...
   Compiling once_cell v1.9.0           ] 40/279: ppv-lite86, snap(build.rs),...
   Compiling itoa v0.4.8                ] 41/279: ppv-lite86, once_cell, snap...
   Compiling unicode-segmentation v1.9.0] 42/279: ppv-lite86, once_cell, snap...
   Compiling rawpointer v0.2.1          ] 43/279: ppv-lite86, once_cell, snap...
   Compiling pyo3-build-config v0.15.1 (https://github.com/ghuls/pyo3?branch=polars_pypy_hasattr#53574425)
   Compiling proc-macro-hack v0.5.19    ] 45/279: ppv-lite86, once_cell, itoa...
   Compiling adler32 v1.2.0             ] 46/279: ppv-lite86, once_cell, itoa...
   Compiling bitflags v1.3.2            ] 48/279: ppv-lite86, packed_simd_2(b...
   Compiling anyhow v1.0.53             ] 49/279: ppv-lite86, unicode-segment...
   Compiling simdutf8 v0.1.3            ] 50/279: ppv-lite86, unicode-segment...
   Compiling strength_reduce v0.2.3     ] 51/279: ppv-lite86, unicode-segment...
   Compiling streaming-iterator v0.1.5  ] 52/279: ppv-lite86, strength_reduce...
   Compiling hash_hasher v2.0.3         ] 53/279: ppv-lite86, streaming-itera...
   Compiling base64 v0.13.0             ] 54/279: ppv-lite86, streaming-itera...
   Compiling unicode-width v0.1.9       ] 55/279: ppv-lite86, streaming-itera...
   Compiling strum v0.22.0              ] 56/279: ppv-lite86, streaming-itera...
   Compiling regex-syntax v0.6.25       ] 57/279: ppv-lite86, streaming-itera...
   Compiling unsafe_unwrap v0.1.0       ] 58/279: ppv-lite86, streaming-itera...
   Compiling hex v0.4.3                 ] 59/279: ppv-lite86, streaming-itera...
   Compiling inventory v0.1.11          ] 60/279: ppv-lite86, streaming-itera...
   Compiling unindent v0.1.7            ] 61/279: ppv-lite86, streaming-itera...
   Compiling glob v0.3.0                ] 63/279: streaming-iterator, regex-s...
   Compiling cfg-if v0.1.10             ] 64/279: regex-syntax, strength_redu...
   Compiling instant v0.1.12            ] 65/279: regex-syntax, strength_redu...
   Compiling lock_api v0.4.6            ] 66/279: regex-syntax, base64, unico...
   Compiling num-traits v0.2.14         ] 67/279: lock_api, regex-syntax, bas...
   Compiling num-integer v0.1.44        ] 68/279: lock_api, regex-syntax, bas...
   Compiling memoffset v0.6.5           ] 69/279: lock_api, num-integer(build...
   Compiling indexmap v1.8.0            ] 70/279: lock_api, num-integer(build...
   Compiling miniz_oxide v0.4.4         ] 71/279: lock_api, num-integer(build...
   Compiling num-bigint v0.4.3          ] 72/279: lock_api, num-integer(build...
   Compiling rayon v1.5.1               ] 73/279: lock_api, regex-syntax, min...
   Compiling num-rational v0.4.0        ] 74/279: lock_api, regex-syntax, min...
   Compiling num-iter v0.1.42           ] 75/279: lock_api, regex-syntax, min...
   Compiling lexical-util v0.8.1        ] 88/279: regex-syntax, libc(build), ...
   Compiling alloc-stdlib v0.2.1        ] 94/279: crossbeam-epoch(build), reg...
   Compiling libflate_lz77 v1.1.0      ] 100/279: crossbeam-epoch(build), asy...
   Compiling streaming-decompression v0.1.02/279: crossbeam-epoch(build), asy...
   Compiling crc v1.8.1                ] 103/279: crossbeam-epoch(build), asy...
   Compiling planus v0.2.0             ] 104/279: crossbeam-epoch(build), asy...
   Compiling matrixmultiply v0.3.2     ] 106/279: snap(build), async-trait(bu...
   Compiling ahash v0.7.6              ] 108/279: snap(build), async-trait(bu...
   Compiling heck v0.3.3               ] 110/279: snap(build), regex-syntax, ...
   Compiling brotli-decompressor v2.3.2] 129/279: libc, regex-syntax, miniz_o...
   Compiling lexical-parse-integer v0.8.0130/279: libc, regex-syntax, memchr,...
   Compiling lexical-write-integer v0.8.0131/279: lexical-parse-integer, libc...
   Compiling crossbeam-channel v0.5.2  ] 143/279: snap, regex-syntax, memchr,...
   Compiling csv-core v0.1.10          ] 148/279: snap, indexmap, regex-synta...
   Compiling aho-corasick v0.7.18      ] 149/279: snap, indexmap, regex-synta...
   Compiling quote v1.0.15>            ] 151/279: snap, indexmap, regex-synta...
   Compiling lexical-parse-float v0.8.2] 152/279: snap, regex-syntax, miniz_o...
   Compiling lexical-write-float v0.8.2] 153/279: snap, regex-syntax, miniz_o...
   Compiling jobserver v0.1.24         ] 155/279: regex-syntax, miniz_oxide, ...
   Compiling getrandom v0.2.4          ] 156/279: jobserver, regex-syntax, mi...
   Compiling num_cpus v1.13.1          ] 158/279: jobserver, regex-syntax, mi...
   Compiling signal-hook-registry v1.4.0 159/279: jobserver, regex-syntax, mi...
   Compiling time v0.1.43==>           ] 160/279: jobserver, signal-hook-regi...
   Compiling mio v0.7.14===>           ] 161/279: jobserver, signal-hook-regi...
   Compiling dirs-sys v0.3.6           ] 162/279: jobserver, signal-hook-regi...
   Compiling memmap2 v0.5.3>           ] 163/279: signal-hook-registry, regex...
   Compiling libflate v1.1.2           ] 164/279: signal-hook-registry, regex...
   Compiling bitpacking v0.8.4         ] 166/279: crc, signal-hook-registry, ...
   Compiling brotli v3.3.3==>          ] 169/279: signal-hook-registry, regex...
   Compiling cc v1.0.73=====>          ] 171/279: syn, signal-hook-registry, ...
   Compiling ordered-float v1.1.1      ] 173/279: syn, cc, regex-syntax, libf...
   Compiling num-complex v0.4.0        ] 174/279: syn, cc, regex-syntax, orde...
   Compiling rand_core v0.6.3          ] 175/279: syn, cc, regex-syntax, num-...
   Compiling paste-impl v0.1.18        ] 177/279: syn, cc, regex-syntax, num-...
   Compiling lexical-core v0.8.2       ] 178/279: syn, cc, regex-syntax, num-...
error[E0554]: `#![feature]` may not be used on the stable release channelnum-...
   --> /Users/ralexx/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.7/src/lib.rs:214:1
    |
214 | / #![feature(
215 | |     adt_const_params,
216 | |     repr_simd,
217 | |     rustc_attrs,
...   |
226 | |     custom_inner_attributes,
227 | | )]
    | |__^


   Compiling regex v1.5.4
   Compiling parking_lot v0.11.2       ] 180/279: syn, cc, regex-syntax, num-...
   Compiling dirs v4.0.0=====>         ] 182/279: syn, cc, regex-syntax, park...
   Compiling pyo3 v0.15.1 (https://github.com/ghuls/pyo3?branch=polars_pypy_hasattr#53574425)
   Compiling crossbeam-deque v0.8.1    ] 184/279: syn, regex-syntax, parking_...
   Compiling chrono v0.4.19==>         ] 187/279: syn, regex-syntax, parking_...
   Compiling cmake v0.1.48===>         ] 188/279: syn, regex-syntax, parking_...
   Compiling rand_chacha v0.3.1        ] 189/279: syn, cmake, regex-syntax, p...
   Compiling ndarray v0.15.4==>        ] 190/279: syn, cmake, parking_lot, nu...
   Compiling lexical v6.0.1===>        ] 191/279: syn, cmake, num-bigint, sig...
   Compiling zstd-sys v1.6.3+zstd.1.5.2] 192/279: syn, lexical, num-bigint, s...
   Compiling lz4-sys v1.9.2===>        ] 193/279: syn, zstd-sys(build.rs), nu...
   Compiling libmimalloc-sys v0.1.24   ] 194/279: syn, lz4-sys(build.rs), num...
   Compiling paste v0.1.18====>        ] 195/279: syn, lz4-sys(build.rs), lib...
   Compiling signal-hook-mio v0.2.1
   Compiling rand v0.8.5======>        ] 199/279: syn, rayon-core, num-bigint...
   Compiling libz-sys v1.1.3==>        ] 200/279: syn, rayon-core, num-bigint...
   Compiling crossterm v0.22.1=>       ] 204/279: syn, rayon-core, lz4-sys(bu...
   Compiling pyo3-macros-backend v0.15.1 (https://github.com/ghuls/pyo3?branch=polars_pypy_hasattr#53574425)
   Compiling rand_distr v0.4.3=>       ] 208/279: syn, rayon, lz4-sys(build),...
   Compiling num v0.4.0========>       ] 209/279: syn, rayon, lz4-sys(build),...
   Compiling hashbrown v0.12.0=>       ] 212/279: syn, rayon, lz4-sys(build),...
   Compiling polars-utils v0.1.0 (/Users/ralexx/anaconda/conda-bld/polars_1645049833205/work/local_dependencies/polars-utils)
   Compiling futures-macro v0.3.21     ] 214/279: lz4-sys(build), libmimalloc...
   Compiling async-stream-impl v0.3.2  ] 215/279: async-trait, lz4-sys(build)...
error: aborting due to previous error  ] 216/279: async-trait, async-stream-i...


For more information about this error, try `rustc --explain E0554`.

error: could not compile `packed_simd_2` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed==============>     ] 228/279: bitpacking
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib -- -C codegen-units=16 -C lto=thin -C target-cpu=native -C link-arg=-undefined -C link-arg=dynamic_lookup -C link-args=-Wl,-install_name,@rpath/polars.cpython-39-darwin.so`
Traceback (most recent call last):
  File "/Users/ralexx/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 480, in main
    execute(sys.argv[1:])
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 469, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/ralexx/anaconda/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-o', 'errexit', '/Users/ralexx/anaconda/conda-bld/polars_1645049833205/work/conda_build.sh']' returned non-zero exit status 1.
```

</details>


<details>
 <summary>Log snippet from error 3</summary>
 
```sh
⋊> /m/polars-py-polars-v0.13.3 conda build --debug --python=3.9 --numpy=1.22 .
# [...snip...]
+ maturin develop '--rustc-extra-args=-C codegen-units=16 -C lto=thin -C target-cpu=native' --release
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.6
🐍 Not using a specific python interpreter (With abi3, an interpreter is only required on windows)
Ignoring typing_extensions: markers 'python_version < "3.10"' don't match your environment
Ignoring fsspec: markers 'extra == "fsspec"' don't match your environment
Ignoring pyarrow: markers 'extra == "pandas"' don't match your environment
Ignoring pandas: markers 'extra == "pandas"' don't match your environment
Ignoring connectorx: markers 'extra == "connectorx"' don't match your environment
Ignoring pyarrow: markers 'extra == "pyarrow"' don't match your environment
ERROR: Could not find a version that satisfies the requirement numpy>=1.16.0 (from versions: none)
ERROR: No matching distribution found for numpy>=1.16.0
💥 maturin failed
  Caused by: pip install finished with "exit status: 1"
```

</details>

**Comment by timkpaine** [comment]
can be closed in favor of https://github.com/conda-forge/staged-recipes/pull/18906

**Pull request closed without merging**
